### ISSUE TITLE
Executar querys semelhante ao TDS (Eclipse)

### ISSUE THREAD

**Issue by wfsouza** [totvs/tds-vscode#10]
Permitir executar querys em tempo de debug semelhante ao TDS na versão eclipse. Desta forma ganhariamos produtividade e agilidade no processo de correção e/ou melhorias no desenvolvimento.

**Comment by izacsc** [comment]
Existe um plugin, se sua base for SQL, pra executar queries diretamente no banco.

https://marketplace.visualstudio.com/items?itemName=ms-mssql.mssql

**Comment by lwtnb-wrk** [comment]
@izacsc esse plugin que voce utiliza para executar queries diretamente no banco atende suas necessidades ou voce vê a necessidade do tds-vscode ter uma implementacao propria para isso?

**Comment by izacsc** [comment]
O plugin atende perfeitamente, porém não atende outros bancos além do MS SQL.

**Comment by lwtnb-wrk** [comment]
Ah entendido @izacsc . Grato pela informação.

@wfsouza sua base é MS SQL tambem? Voce utiliza outro BD? Já chegou a procura extensões para seu BD? Se houver realmente a necessidade podemos estudar a implementação no tds-vscode, mas acredito que existam diversas opções para praticamente todos os BD disponiveis no mercado. Alem disso o vscode é preparado exatamente para ser extendido conforme as necessidades dos desenvolvedores. Assim se houver algum impedimento em usar alguma outra extensão nos informe para que possamos reavalidar, ok?

**Comment by wfsouza** [comment]
> Ah entendido @izacsc . Grato pela informação.
> 
> @wfsouza sua base é MS SQL tambem? Voce utiliza outro BD? Já chegou a procura extensões para seu BD? Se houver realmente a necessidade podemos estudar a implementação no tds-vscode, mas acredito que existam diversas opções para praticamente todos os BD disponiveis no mercado. Alem disso o vscode é preparado exatamente para ser extendido conforme as necessidades dos desenvolvedores. Assim se houver algum impedimento em usar alguma outra extensão nos informe para que possamos reavalidar, ok?

@lwtnb-wrk @izacsc perfeito, acredito que tenha para oracle também e não vejo problema em usar. Agora estou numa situação a qual estou acessando remotamente a base do cliente via APSDU e isso é muito comum quando estamos num cliente que tem o serviço em cloud, onde nos restringimos ao APSDU para fazer querys.

**Comment by lwtnb-wrk** [comment]
@wfsouza vamos estudar essa questao de acesso via APSDU, mas não temos previsão para implantar isso. de qualquer forma grato pela sugestao

**Comment by ricardomansano** [comment]
Boa tarde a todos,

Agradecemos a sugestão, mas após analise decidimos que ela não entrará em roadmap.

O acesso aos dados deverá ser feito via APSDU por questões de segurança.

Muito grato pela sugestão,
