### ISSUE TITLE
Problema na visualização do codigo

### ISSUE THREAD

**Issue by lucasndas** [totvs/tds-vscode#100]
Ao incluir a palava "aScan" o VS code perde a referencia de cores para funções /variaveis etc..  

![image](https://user-images.githubusercontent.com/21094275/60267786-61e4b780-98c1-11e9-9b0c-b3947f73ba29.png)

Como podemos ver na imagem acima, perdemos as cores, agora vou comentar a linha com o aScan.
![image](https://user-images.githubusercontent.com/21094275/60267902-93f61980-98c1-11e9-97a1-01cdeb9aef2a.png)

Vou remover apenas o "S" do aScan

![image](https://user-images.githubusercontent.com/21094275/60267921-a2dccc00-98c1-11e9-9c09-bff04c97588a.png)

Pelo que entendi o problema é apresentado com a palavra "AS", com isso todo o resto do fonte perde a referencia das cores

**Comment by DanielYampolschi** [comment]
Ola @lucasndas , muito obrigado pela observação. 

Vamos verificar assim que possível.

Porém, reforço que esse projeto é colaborativo, então, caso tenha urgência e/ou interesse em colaborar , aceitamos a ajuda de muito bom grado.

Abraço!

**Comment by ricardomansano** [comment]
Boa tarde @lucasndas lucasndas , 
Problema não reproduzido na versão 0.3.15, por gentileza atualize e refaça os testes.
