### ISSUE TITLE
Erro ao compilar fonte

### ISSUE THREAD

**Issue by gvlakatos** [totvs/tds-vscode#1000]
Olá pessoal,

Ao realizar a compilação de um fonte, é exibida mensagem que o fonte foi compilado com sucesso porém ao consultar o inspetor de funções, aparece **#NONE** antes e após o nome da função conforme imagem abaixo (ao consultar o inspetor de objetos, o fonte aparece na lista).

![image](https://user-images.githubusercontent.com/37455296/178031753-3e07f255-a92b-48db-a05c-2d4dabe7780c.png)

Com isso, ao executar a rotina que está com problema, é exibida a mensagem que a função não está compilada no repositório.

Outro problema que encontrei (desta vez em um outro ambiente), é que ao compilar um fonte, é exibida mensagem que o fonte foi compilado com sucesso porém ao consultar o inspetor de objetos, o fonte não aparece na lista e também é exibida a mensagem de função não compilada no repositório caso tente executar a função dentro do Protheus.

Já desinstalei por completo o VSCode e refiz a instalação e criação dos workspaces porém nada adiantou. 

Alguém já passou ou está passando por isso também?

Caso necessário mais informações estou à disposição.

Obrigado.

**Comment by brodao** [comment]
@gvlakatos 

Reabra este chamado informando os dados solicitados conforme [Informações importantes ao abrir o chamado](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#informa%C3%A7%C3%B5es-importantes-ao-abrir-uma-issue) e anexe os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)

No aguardo
