### ISSUE TITLE
Problema ao compilar fonte

### ISSUE THREAD

**Issue by gvlakatos** [totvs/tds-vscode#1001]
Olá pessoal,

Ao realizar a compilação de um fonte, é exibida mensagem que o fonte foi compilado com sucesso porém ao consultar o inspetor de funções, aparece **#NONE** antes e após o nome da função conforme imagem abaixo (ao consultar o inspetor de objetos, o fonte aparece na lista).

![image](https://user-images.githubusercontent.com/37455296/178031753-3e07f255-a92b-48db-a05c-2d4dabe7780c.png)

Com isso, ao executar a rotina que está com problema, é exibida a mensagem que a função não está compilada no repositório.

Outro problema que encontrei (desta vez em um outro ambiente), é que ao compilar um fonte, é exibida mensagem que o fonte foi compilado com sucesso porém ao consultar o inspetor de objetos, o fonte não aparece na lista e também é exibida a mensagem de função não compilada no repositório caso tente executar a função dentro do Protheus.

Já desinstalei por completo o VSCode e refiz a instalação e criação dos workspaces porém nada adiantou. 

Alguém já passou ou está passando por isso também?

Version: 1.69.0 (system setup)
Commit: 92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9
Date: 2022-07-07T05:28:36.503Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044

Versão do VSCode - 1.3.14

Em anexo os logs gerados pelo VSCode.

Obrigado.
[totvsls.log](https://github.com/totvs/tds-vscode/files/9074130/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/9074131/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/9074132/totvsls_out.log)

**Comment by brodao** [comment]
Verificando os log os arquivos parecem que foram compilados corretamente.

Qual a versão do seu appServer?

**Comment by lwtnb-wrk** [comment]
@gvlakatos Realmente pelos logs, aparentemente não ocorreu nenhum problema na compilação.

No console.log do AppServer apos a compilacao aparece o nome do fonte seguido do numero de linhas do fonte, corretamente?

Qual a build exata do AppServer que esta utilizando? Esta atualizada??

**Comment by gvlakatos** [comment]
@brodao @lwtnb-wrk 

Dados do AppServer do ambiente que está 'descompilando' a função ao compilar o fonte

> Versão: TOTVS Manufatura
> Build AppServer: 7.00.210324P-20220312 - 64 bits
> Nome do servidor: EDGSRV-APP-001
> Sistema operacional: Windows Server 2012 R2
> Appserver version: 20.3.0.8
> Build DBAccess: 20210202-20220202
> Release do RPO:  12.1.033
> Release do dicionário: 12.1.033
> Local files: CTREE
> License server: 2014 - 3.3.0
> DB DataBase: MSSQL
> DB API Build: 20210202-20220202
> 
> Versão da Lib:20211004
> Data da Lib: 20211006_135652
> Commit ID:94c212d6522f77c511f4ddc68641247405742f8b

Dados do AppServer do ambiente que aparece a #NONE# ao consultar o inspetor de funções

> Versão: TOTVS Distribuição e Logística
> Build AppServer: 7.00.191205P-20210114 - 64 bits
> Nome do servidor: SBLSP-VM01
> Sistema operacional: Windows Server 2012 R2
> Appserver version: 19.3.1.5
> Build DBAccess: 20200606-20201110
> Release do RPO:  12.1.025
> Release do dicionário: 12.1.025
> Local files: CTREE
> License server: 2014 - 3.3.3
> DB DataBase: MSSQL
> DB API Build: 20200606-20201110
> 
> Versão da Lib:20210809
> Data da Lib: 20210830_151551
> Commit ID:bb999155b414c8a657878a6fb05b47e099b279fd

**Comment by lwtnb-wrk** [comment]
@gvlakatos Mas o problema está ocorrendo na LG 19, correto? Os logs indicam a compilação apenas nesse AppServer.

E pela versão vimos que se trata da 19.3.1.5 que realmente teve alguns problemas que podem ter relação com a questão reportada. Atualize para a última versão 19.3.1.8 e verifique se o problema persiste.

**Comment by gvlakatos** [comment]
Boa tarde pessoal,

Consegui identificar o problema da compilação...

Havia solicitado à um membro da minha equipe para compilar o mesmo fonte no mesmo ambiente que estava usando e ele conseguiu compilar sem problemas e assim vi que o problema era no VSCode e não no ambiente em questão.

Após alguns testes, descobri que o erro ocorria devido ao tamanho do diretório onde o fonte estava localizado. Por utilizar o Google Drive, o caminho do arquivo está muito extenso. Ao mover o arquivo para um caminho mais "curto" (criei uma pasta C:\temp\ como exemplo) e compilar o fonte, o mesmo foi compilado com sucesso.

Obrigado @brodao e @lwtnb-wrk pela disposição em ajudar.

**Comment by lwtnb-wrk** [comment]
@gvlakatos Grato pela informação. 
Vamos avaliar para ver se conseguimos melhorar os processos para ajudar a identificar e acusar esse tipo de problema.

**Comment by fmercurio** [comment]
Apenas complementando as informações passadas pelos colegas:

Ao compilar fontes isolados (CTRL+F9 em um determinado arquivo aberto) o caminho relativo não importa, a compilação se dá normalmente, porém ao compilar uma pasta ou selecionar vários arquivos fontes para compila-los o retorno tanto no tds-vscode quanto no Console do AppServer é que a compilação se deu com sucesso, porém ao tentar acessar um programa ou pesquisá-lo no inspetor de objetos/funções o mesmo não é encontrado.

Alterando o local dos arquivos e/ou diretório a ser compilado para um caminho mais curto (por exemplo c:\src\fontes) os mesmos são compilados normalmente.

**Comment by danielbolognani** [comment]
Boa dia @fmercurio isso é proposital, se quiser mudar esse comportamento, existe uma opção nas preferências da extensão:
![image](https://user-images.githubusercontent.com/25229827/202466259-87d99377-286f-4486-b3be-da954c52d908.png)
