### ISSUE TITLE
Regras do CodeAnalysis no TDS

### ISSUE THREAD

**Issue by gtrabach** [totvs/tds-vscode#1002]
Bom dia!

Existe alguma forma de ativar as regras do CodeAnalysis diretamente no TDS? Por exemplo: validação de uso da API em loop, acesso indevido a SX3, etc.

Se existir, como posso ativar?

Ter essas regras seria uma mão na roda, principalmente no desenvolvimento de novos fontes, afim de evitar os erros já na fase do desenvolvimento.

**Comment by lwtnb-wrk** [comment]
@gtrabach Até onde temos conhecimento, o CodeAnalysis não possuí uma API para que possamos realizar quaisquer tipos de integração com seus serviços, então infelizmente não temos o que fazer.
Se houver mudanças no futuro talvez possamos rever esta possibilidade.
De qualquer forma, grato pela sugestão.

**Comment by luizhj** [comment]
Senão me engano o "CodeAnalysis" roda em cima do Sonarqube.

Existe a extensão "SonarLint" que faz a mesma análise de código que o Sonarqube.
https://marketplace.visualstudio.com/items?itemName=SonarSource.sonarlint-vscode

Não sei se a extensão em si tem como customizar as regras para ADVPL/TLPP, mas ela tem um modo "conectado" em que ela obtém as regras de análise a partir de um servidor do sonarqube (que poderia ser o servidor do codeanalysis)

Se fosse possível fazer download da regra de análise do ADVPL/TLPP para Sonarqube era só rodar um DOCKER do sonarqube e importar a regra baixada.
