### ISSUE TITLE
Error ao compilar na 12.1.33

### ISSUE THREAD

**Issue by feliperafaelmendes** [totvs/tds-vscode#1004]
# Help us to help you.

## Before opening an issue

- Make sure the extension is up to date.
- See [Resolução de Problemas](TROUBLESHOOTING.md#problemas-gerais), with common and/or known occurrences.

## Enter the data below

**Describe the bug**
Boa tarde

Estou com erro ao compilar na 12.1.33 conforme abaixo:
[Info  - 14:42:52] Start file recompile.
[Info  - 14:42:52] Using Includes: c:/Totvs/Includes
[Info  - 14:42:52] Start secure compiling c:/Totvs/Fontes/Gest�o Agricula/Gestao Agricola/Originacao/OGX155.PRW (1/1).
[Error - 14:42:52] [FATAL] Aborting: OGX155.PRW(2)   Regular functions are not allowed in code. Use USER FUNCTION or STATIC FUNCTION.
[Info  - 14:42:52] Aborting end build (rollback changes).
[Error - 14:42:52] One or more files have errors and/or warnings. See problems and logs for details.
[Info  - 14:42:52] Recompile finished.

O erro é referente a chave de compilação, porém a chave de compilação está no período de validade conforme imagem:
![image](https://user-images.githubusercontent.com/62951059/180051993-acd25792-beb4-40c5-b901-5dc874140130.png)

**To Reproduce**
1. Configurar um servidor da 12.1.33 no VSCODE
2. Tentar compilar um programa com FUNCTION

**Expected behavior**
Compilar o programa sem erro.

**Desktop (please complete the following information):**
 - OS/Architecture:  Windows 64 bits

**Appserver (please complete the following information):**
 - Build (with date): TOTVS - Build 7.00.210324P - Jun 28 2022 - 01:53:55 
 - OS/Architecture: Windows 64 bits

**Additional context**

**Comment by danielbolognani** [comment]
Boa tarde @feliperafaelmendes 
Na versão 12.1.33 ou superior a autorização para compilação de FUNCTION/MAIN FUNCTION mudou para geração de Token, é necessário a utilização de um outro plugin do VSCode mantido pela equipe do GCAD da TOTVS.
Se for colaborador, procure alguém da equipe do GCAD para conseguir esse acesso.
