### ISSUE TITLE
Insufficient privileges for COMPILE

### ISSUE THREAD

**Issue by keinou** [totvs/tds-vscode#1005]
Insufficient privileges for COMPILE, no output da extenção, mas no do appserver nada aparece.

O Problema esta acontecendo apenas neste binario
***  TOTVS S/A  ***
***  www.totvs.com.br  ***
* TOTVS - Build 7.00.210324P - Jun  8 2022 - 18:12:55 
* Build: 64 bits
* SVN Revision: 35284
* Build Version: 20.3.0.10

Informacoes do Host:
NAME="Oracle Linux Server"
VERSION="7.9"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Oracle Linux Server 7.9"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:9:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.9
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.9

**Comment by brodao** [comment]
@keinou 

Favor consultar [Sistema de privilégios](https://github.com/totvs/tds-vscode/blob/master/docs/servers.md#sistema-de-privil%C3%A9gios).

A disposição.

**Comment by keinou** [comment]
Ja esta com:
[TDS]
AllowCompile=*

Com a extensão nao oficial a compilação é feita.

**Comment by keinou** [comment]
Preciso fazer uma correcao, este binario 7.00.210324P no windows funciona.

**Comment by brodao** [comment]
O que você chama de "não oficial"?

Informe os dados solicitados conforme [Informações importantes ao abrir o chamado](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#informa%C3%A7%C3%B5es-importantes-ao-abrir-uma-issue) e anexe os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)

**Comment by keinou** [comment]
A Extensão do VScode do Rodrigo Antonio

**Comment by brodao** [comment]
> A Extensão do VScode do Rodrigo Antonio: https://github.com/totvs/advpl-vscode/issues

O uso do TDS-VSCode junto com o a não oficial, podem gerar problemas de execução. Remova a não oficial e certifique-se que o TDS-VSCode esta atualizado.

**Comment by keinou** [comment]
Eu utilizei ela apenas para realizar teste, a mesma nao esta habilitada, e o TDS-VSCode se encontra na versão mais atual (v1.3.15).
[totvsls.log](https://github.com/totvs/tds-vscode/files/9161252/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/9161253/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/9161254/totvsls_out.log)

**Comment by brodao** [comment]
Consegue fazer um teste para mim, por favor. 
Coloca a chave AllowCompile, tudo em maiúsculas.

**Comment by keinou** [comment]
Nao funcionou

**Comment by brodao** [comment]
Você pode me encaminhar o ini do server e o console log.
Pode mandar direto pro meu e-mail acandido@totvs.com.br

**Comment by keinou** [comment]
Encaminhei

**Comment by brodao** [comment]
Recebido. Abrindo o INI, no notepad++, ele foi identificado como UTF-8 e até onde seu, isso pode dar problemas.
Converta-o no ANSI (ou CP1252).

![image](https://user-images.githubusercontent.com/949914/180319154-da572aa9-2507-4949-8d43-36791633232e.png)

**Comment by lwtnb-wrk** [comment]
@keinou Confirme novamente os cenários de teste de falha e o que está funcionando.

Pelo que entendi seu appserver está um servidor Linux correto?

- Acessando o tds-vscode de um desktop Windows está funcionando
- Mas acessado o tds-vscode do servidor Linux está ocorrendo o erro mencionado?

É isso?

**Comment by keinou** [comment]
Bom dia.

Pelo que entendi seu appserver está um servidor Linux correto?
- Correto

Acessando o tds-vscode de um desktop Windows está funcionando.
- Nao, em client Windows apontado para este appserver em questao, o problema tambem ocorre.

Mas acessado o tds-vscode do servidor Linux está ocorrendo o erro mencionado?
- Exato, tanto do Windows, quanto do linux

**Comment by brodao** [comment]
> Recebido. Abrindo o INI, no notepad++, ele foi identificado como UTF-8 e até onde eu sei, isso pode dar problemas. Converta-o no ANSI (ou CP1252).
> 
> ![image](https://user-images.githubusercontent.com/949914/180319154-da572aa9-2507-4949-8d43-36791633232e.png)

Verificou o que falei sobre _code page_?

**Comment by keinou** [comment]
Fiz o teste mas o problema persistiu.


[appserver.ini.zip](https://github.com/totvs/tds-vscode/files/9184098/appserver.ini.zip)

**Comment by lwtnb-wrk** [comment]
@keinou Estou intrigado com a informação que no Windows funciona que você mencionou acima...

> Preciso fazer uma correcao, este binario 7.00.210324P no windows funciona.

No caso então funcionou quando o AppServer estava rodando no Windows e voce usou o tds-vscode no Windows tambem? Nesse caso faz ate sentido, pois o AppServer é considerado como localhost e o tratamento é diferente...

De qualquer forma eu notei um detalhe que não consegui testar aqui, pois eu teria que montar um outro ambiente, mas veja se adicionado um "enter" no final da ultima linha de seu appserver.ini faz diferença... No caso a ultima linha passaria a ser uma linha vazia, ok? E lembre-se de reiniciar o AppServer e o tds-vscode apos essa alteracao no appserver.ini

**Comment by keinou** [comment]
A nivel de informação, o problema foi solucionado internamente.

O TDS-VsCode tem esse problema quando o appserver.ini esta como 'apenas para leitura'.
