### ISSUE TITLE
Erro ao debugar

### ISSUE THREAD

**Issue by Giovane-Oliveira** [totvs/tds-vscode#1006]
Sou iniciante no desenvolvimento ADVPL TOTVS, e estou com dificuldade de debugar o fonte MATR550.prx, apresenta este seguinte erro:

![ERRO_MATR550](https://user-images.githubusercontent.com/35038647/180210305-7a97febf-64c6-48ed-a674-71f5683ad15b.PNG)

**Comment by brodao** [comment]
@Giovane-Oliveira 

Você não pode chamar o MATR550 direto no executor. Coloco um ponto de parada na função MATR550 e no executor informe o módulo a qual ele pertence e acesse via menu.

**Comment by Giovane-Oliveira** [comment]
> @Giovane-Oliveira
> 
> Você não pode chamar o MATR550 direto no executor. Coloco um ponto de parada na função MATR550 e no executor informe o módulo a qual ele pertence e acesse via menu.

Tem imagens ou tutorial de como fazer isso? Muito grato pela ajuda.

**Comment by brodao** [comment]
[TDS: Depuração e execução](https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md)

No caso, para depurar o ponto de interrupção (entendendo que seja ponto de entrada), você deve colocar o ponto de parada no seu ponto de entrada.

Para depurar o MATR550 em si, você deve ter acesso aos fontes da TOTVS. 
Se for um TOTVER, fale com o seu superior.

A disposição.

**Comment by danielbolognani** [comment]
Boa tarde,
Se tiver acesso a abrir chamados, pode tentar pedir ajuda para a equipe de ADVPL, por aqui não conseguimos te ajudar nessa parte.

**Comment by Giovane-Oliveira** [comment]
> Boa tarde, Se tiver acesso a abrir chamados, pode tentar pedir ajuda para a equipe de ADVPL, por aqui não conseguimos te ajudar nessa parte.

A equipe DVPL respondeu quase a mesma coisa, a única diferença é que disseram para acionar a equipe Hub Plataformas para fazer avaliação/orçamento.
