### ISSUE TITLE
Erro ao debugar no modulo SIGAFIN

### ISSUE THREAD

**Issue by fconfuorto** [totvs/tds-vscode#1007]
# Help us to help you.

## Before opening an issue

- Make sure the extension is up to date.
- See [Resolução de Problemas](TROUBLESHOOTING.md#problemas-gerais), with common and/or known occurrences.

## Enter the data below

**Describe the bug**
Ao tentar debugar no modulo SIGAFIN, da um erro. O modulo mal chega a abrir.
 [14:31:12] ERROR: Saída no final: Inconsistência na base de dados
           Foi detectada uma inconsistência na base de dados, contate o Administrador do Sistema.
FINAL - MSFINAL.PRW(244) - Params: CSTR:Inconsistência na base de dados,CSTR1:Foi detectada uma inconsistência na base de dados, contate o Administrador do Sistema.,LLOGOFF:.F.,LLOGIN:.F.,NTIMER:0 )
ERRDATABASE - MPCHECKTBLINDB.PRW(395)
CHKDICINDB - MPCHECKTBLINDB.PRW(151) - Params: LMDIOPENED:.F. )
RPCSETENV - TBICONN.PRW(702) - Params: CRPCEMP:02,CRPCFIL:01,CENVUSER:JOB                                                                                                                                                   ,CENVPASS:FIN                      ,CENVMOD:FAT,CFUNNAME:NIL,@ATABLES:,LSHOWFINAL:.F.,LABEND:.T.,LOPENSX:.T.,LCONNECT:.T.,LOPENSM0:.T. )
FINEXECFKS - FINXFIX.PRW(116) - Params: CEMP:02,CFIL:01 )

**To Reproduce**
1. Go to 'VS CODE'
2. Click on 'F5 - SIGAFIN'

**Expected behavior**
Esperava que o modulo abrisse e desse para selecionar a rotina que desejo

**Screenshots**
![image](https://user-images.githubusercontent.com/103668432/180277940-2b7fa617-7a19-481b-9ecd-d219bfc63bbd.png)

**Desktop (please complete the following information):**
 - OS/Architecture: Windows Server 2019 Standard

**Appserver (please complete the following information):**
 - Build (with date): [e.g. Build ?.??.??????? - XXX XX XXXX - TT:TT:TT] anexo abaixo
 - OS/Architecture: Windows Server 2019 Standard
 - Build Version [e.g. XX.X.X.XX] anexo abaixo
 - 
![image](https://user-images.githubusercontent.com/103668432/180279179-e6d65b00-5750-4201-aa32-c302ff6b3b08.png)

**Additional context**
Segue vídeo tentando debugar no módulo financeiro (que não funciona) e outro no módulo estoque (que funciona).
[DEBUG MODULO ESTOQUE.zip](https://github.com/totvs/tds-vscode/files/9161569/DEBUG.MODULO.ESTOQUE.zip)
[DEBUG MODULO FINANCEIRO.zip](https://github.com/totvs/tds-vscode/files/9161570/DEBUG.MODULO.FINANCEIRO.zip)

**Comment by brodao** [comment]
@fconfuorto 

Esse erro não é de depuração em si e sim do seu ambiente. Favor entrar em contato com o suporte do módulo, via [Portal do Cliente](https://totvscst.zendesk.com/hc/pt-br/#home).
