### ISSUE TITLE
Smartclient Protheus não abre no Debug do VSCode

### ISSUE THREAD

**Issue by George-Eivazian** [totvs/tds-vscode#1008]
Boa Tarde !! 

senhores, nao consigo de forma nenhuma fazer com que abra o Smartclient no debug do Vscode. Ja desinstalei e reinstalei, ja apaguei tudo que era arquivo do vscode para reinstalar. Ja refiz o launch.json centenas de vezes  e nao abre. 
Nem com F5 nem Ctrl + F5...podem me dar um help ?. Segue abaixo o Launch e o caminho do qual esta o SmartClient

{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Depuração do idioma TOTVS",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "C:\\Totvs\\HOMOLOG\\smartclient\\smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true,
			"programArguments": [],
			"enableMultiThread": false,
			"enableProfile": false,
			"isAccessibilityMode": false,
			"doNotShowSplash": false,
			"openglMode": false,
			"dpiMode": false,
			"language": "",
			"ignoreFiles": false
		}
	],
	"lastPrograms": [
		{
			"label": "SIGAADV"
		}
	],
	"lastProgramExecuted": "SIGAADV"
}

Caminho: C:\Totvs\HOMOLOG\smartclient\smartclient.exe

**Comment by brodao** [comment]
Favor complementar chamado informando os dados solicitados conforme [Informações importantes ao abrir o chamado](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#informa%C3%A7%C3%B5es-importantes-ao-abrir-uma-issue) e anexe os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)

No aguardo.

**Comment by George-Eivazian** [comment]
Segue abaixo os documentos e informações solicitadas.

![image](https://user-images.githubusercontent.com/69053300/180517416-6ca66fe6-f9dd-4848-b51c-81cf2f2a2276.png)

![image](https://user-images.githubusercontent.com/69053300/180517738-629b3b63-7fac-4fab-ad64-78d1dbdbfd8b.png)

![image](https://user-images.githubuser
content.com/69053300/180519774-21608028-920f-40c2-8b80-7793021c4b71.png)

![image](https://user-images.githubusercontent.com/69053300/180519862-112d5239-568a-4d0a-b158-0b53fc94e414.png)

[dap.log](https://github.com/totvs/tds-vscode/files/9170484/dap.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/9170485/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/9170486/totvsls_out.log)

**Comment by brodao** [comment]
@George-Eivazian 

Pelos logs, seu arquivo laucher.json e as pastas de trabalho contém acentos. Ajuste o conteúdo do arquivo launcher e as pastas.

https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#pastas-com-acentua%C3%A7%C3%A3o

**Comment by George-Eivazian** [comment]
Alan, Boa Noite !!!

Segui sua orientações, verificando acentuação no workspace, letras maisculas e minusculas nas pasta, deixando tudo com letras maisculas e mesmo assim nao esta abrindo o SmartClient no debug.

**Comment by brodao** [comment]
Solução: Utilize somente letras minúsculas em todo o caminho, inclusive no nome dos arquivos quando utilizar o TDS VS Code em Linux ou Mac. (conforme documentação).

Favor refazer os testes e encaminhar os logs novamente.

**Comment by danielbolognani** [comment]
Bom dia, apague todos os breakpoints antes de tentar novamente. Pelos logs parece que um breakpoints está causando o problema.

**Comment by lwtnb-wrk** [comment]
@George-Eivazian Complementando a informação do @danielbolognani acima, além de remover os breakpoints, reveja o caminho no parâmetro "cwb" de seu launcher que está com o mesmo problema na parte do caminho com a pasta "Área de Trabalho".

**Comment by George-Eivazian** [comment]
Bom Dia !!! senhores, todas as alternativas sugeridas por vcs foram aplicadas e nenhuma delas surgiu efeito. Lembrando que o meu SO é Win10, nao é Linux nem MacOs. Ja estou sem saber o que fazer.

**Comment by George-Eivazian** [comment]
Senhores, Boa Tarde !!! acabei descobrindo o pq o smartclient nao abria no debug...a Workspace que eu estava abrindo, estava na área de trabalho da minha maquina....e como os meus arquivos da área de trabalho. Meus arquivos da Área de Trabalho ficam no One Drive. 
Quando levei a workspace para o C: funcionou. pois no C: os arquivos nao ficam no OneDrive. Agradeço a atenção de vcs e peço que encerrem esta Issue.
