### ISSUE TITLE
Erro ao compilar fontes

### ISSUE THREAD

**Issue by ThiagoMarq** [totvs/tds-vscode#1009]
Ao tentar compilar um fonte que eu havia criado o seguinte erro é apresentado: File c:/protheus/bravox/financeiro/pontos de entrada/FI040ROT.prw has no valid content after precompiled.

A partir do dia que apresentou essa mensagem não consigo compilar novos arquivos, não consigo remover o arquivo do RPO e diversos arquivos appreXXX.prx são gerados.

Informações VsCode:
Version: 1.69.2 (user setup)
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:52.460Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044

Informações extensão:
Versão [1.3.14]

Versão do RPO (LIB) e do TOTVS Server:
![image](https://user-images.githubusercontent.com/65978430/180784973-778dc123-2646-417a-a042-71f2ec6fd112.png)
[totvsls.log](https://github.com/totvs/tds-vscode/files/9181449/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/9181451/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/9181452/totvsls_out.log)
![image](https://user-images.githubusercontent.com/65978430/180784802-f784f23b-c050-4ad9-9097-c1c031f1605d.png)

**Comment by lwtnb-wrk** [comment]
@ThiagoMarq Mas esse fonte FI040ROT.prw tem conteudo válido mesmo? Eu já vi esse erro ocorrendo e quando abri o fonte ele estava inteiro comentado...

**Comment by ThiagoMarq** [comment]
Tem sim, eu criei ele e o mesmo estava funcionando. Se não me engano na segunda ou na terça ele parou de funcionar, aconteceu com outro fonte também.
![image](https://user-images.githubusercontent.com/65978430/180788560-d8619e05-b00f-4685-98e0-167e3e7bfebf.png)

**Comment by brodao** [comment]
@ThiagoMarq 

Fiz testes com os dados dos logs e seu fonte foi reconhecido como UTF-8. 
Veja se ajuda https://www.kindacode.com/article/how-to-change-file-encoding-in-vs-code/

![image](https://user-images.githubusercontent.com/949914/180835976-f4038c72-31b0-473a-aad4-b2276284b0dc.png)

**Comment by lwtnb-wrk** [comment]
@ThiagoMarq Está com cara de ser problema com includes, ainda mais se acontece com outros fontes também.
Confirme se as configurações de includes estão corretas no arquivo servers.json.
Atente-se ao fato que existem duas configurações possíveis de "includes", uma Geral (no mesmo nível de "version") e outra dentro das configurações do servidor (no mesmo nível de "smartclientBin", por exemplo), se não estiver definido no servidor ele usa a Geral, caso contrário usa a específica do servidor...

**Comment by ThiagoMarq** [comment]
Boa tarde, pessoal.
Já havia verificado várias vezes as configurações de includes, verifiquei o encoding também (para mim, aparecia como Windows1252).

Mas descobri o motivo, era uma linha do código, em que eu estava setando numa variável o código de uma imagem em base64. Removi a linha e funcionou perfeitamente.
Peço perdão por incomodar vocês e ocupar o tempo, mas fico muito grato com a ajuda!

**Comment by brodao** [comment]
@ThiagoMarq 

Fiquei curioso. Que linha é essa?

**Comment by lwtnb-wrk** [comment]
@ThiagoMarq Compartilhe mais detalhes do problema que você conseguiu resolver, pois isso pode ajudar outros com o mesmo problema.

**Comment by ThiagoMarq** [comment]
Na linha 102, só coloquei o a imagem em base64. Removei ela, o arquivo volta ao normal.
[ex.zip](https://github.com/totvs/tds-vscode/files/9183923/ex.zip)

**Comment by brodao** [comment]
@ThiagoMarq 

Falei com o pessoal do server e a linha AdvPPl tem que ter no máximo 4K (teórico).
Particularmente, acho que devemos nos limitar (em casos **bem excepcionais)** a 3K.
No dia a dia, não deve exceder 120 caracteres (dificulta a leitura do código).

No seu caso, você tem algumas opções:
- usar o arquivo de imagem e informar como src na tag, deixando-o em local público do sítio;
- quebrar a linha em blocos menores (não usar ; e tem site que faz a geração em blocos) concatenando cada bloco em uma string (string pode tem 1M);
- gravar o arquivo com o conteúdo binário e usar funções de codificação AdvpL ([Base64](https://siga0984.wordpress.com/tag/base64/)) no conteúdo obtido:
  - de recurso compilado no RPO e extraído por função apropriada
  - ler o arquivo em uma pasta do server

O suporte AdvPL pode ajudá-lo de como ler o arquivo ou extrair o recurso do RPO.

A disposição.
