### ISSUE TITLE
Ajuste na documentação 

### ISSUE THREAD

**Issue by lucasndas** [totvs/tds-vscode#101]
Por gentileza, verificar se é possível colocar um exemplo de como deve ficar o Lauche.json em caso de uso dos parâmetros de diretivas de depuração. 
confesso que não consegui entender e aplicar o ajuste na minha base local.  

https://github.com/totvs/tds-vscode/wiki/Configura%C3%A7%C3%A3o-de-diretivas-no-depurador

**Comment by DanielYampolschi** [comment]
@lucasndas , realmente a pagina de wiki precisa de atualização, temos colocado apenas na página inicial [https://github.com/totvs/tds-vscode] por ser mais ágil durante o desenvolvimento pois precisamos editar apenas um arquivo. De qualquer forma, concordo com você que é necessário melhorar o Wiki.

Em relação à sua questão, sugiro usar o assistente que possui todos os parametros permitidos e o qual configura o arquivo launcher.json automaticamente. Verifique na pagina inicial aqui do projeto o item:
> Criando uma configuração de debug com assistente

**Comment by ricardomansano** [comment]
Boa tarde @lucasndas ,

Não recomendamos que o arquivo launch.json seja alterado manualmente, o plugin irá se encarregar de seu preenchimento quando utilizado os parâmetros -a=param, por exemplo, no campo de inicio da depuração.

Caso encontre algum problema neste processo ficaremos felizes em ajudá-lo.

Segue abaixo o trecho salvo no arquivo json, mas apenas para elucidação, a documentação não será alterada pelos motivos que lhe informei acima.

	],
	"lastPrograms": [
		{
			"args": [
				"param1",
				"param2"
			],
			"label": "u_myprog",
			"description": "param1 param2"
		}
	],
	"lastProgramExecuted": "u_myprog"
}

Muito grato pela interação, e ficamos à disposição.
