### ISSUE TITLE
Erro na abertura do VSCODE - Cannot execute Linter. Includes not defined

### ISSUE THREAD

**Issue by Smmartinez** [totvs/tds-vscode#1010]
Boa trade pessoal
Toda vez que abro o VS CODE e ele conectar no TOTVS aparece a mensagem da imagem. Isso não impede nada na operação, mas aparece essa mensagem.

Outra dúvida a versão .15 já esta disponivel para baixar?
![rwerwerwe](https://user-images.githubusercontent.com/4532855/180831506-48c054d0-c4d7-4ca0-a4d6-c809b8d57134.png)

**Comment by brodao** [comment]
@Smmartinez 

Veja [TDS: Linter](https://github.com/totvs/tds-vscode/blob/master/docs/linter.md) ou desative-o acessando `Settins`, filtro `totvsLanguageServer.editor.linter`

**Comment by lwtnb-wrk** [comment]
@Smmartinez Outra forma de evitar a mensagem de erro do Linter seria configurar os Includes para que o Linter possa funcionar.

Nota: Liberarmos a 1.3.15 ontem ;)

**Comment by Smmartinez** [comment]
@lwtnb-wrk tem a documentação de como configurar?

**Comment by lwtnb-wrk** [comment]
@Smmartinez O link está na resposta acima do @brodao 
Se tiver alguma duvida ou sugestão sobre a documentação, nos avise que veremos aqui.
