### ISSUE TITLE
Não consigo conectar o TSS 

### ISSUE THREAD

**Issue by pedrojlima** [totvs/tds-vscode#1011]
Quando tento conectar o TSS não exibe nenhum erro nem solicita o login e senha.

Versão: 1.69.1 (user setup)
Commit: b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a
Data: 2022-07-12T08:21:24.514Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 6.3.9600

![image](https://user-images.githubusercontent.com/85879332/181510035-bf01af50-5e40-42c2-9dc9-5ba64138b80b.png)

[iSSUe.zip](https://github.com/totvs/tds-vscode/files/9209786/iSSUe.zip)
[Gravar_2022_07_28_09_22_30_188.zip](https://github.com/totvs/tds-vscode/files/9209790/Gravar_2022_07_28_09_22_30_188.zip)

**Comment by lwtnb-wrk** [comment]
@pedrojlima Pelos logs enviados, o AppServer simplesmente não respondeu ao pedido de conexão inicial.
Isso geralmente ocorre quando o:
- O AppServer está fora do ar
- O IP:porta cadastrado está incorreto
- O servidor não está acessivel (firewall ou anti-virus bloqueando)
- O servidor cadastro no tds-vcode está com alguma informação incorreta
Então se o AppServer está no ar, o IP:porta está correto e não existe um firewall/anti-virus bloqueando, experimente apagar o servidor e recadastra-lo novamente.

Note que se conseguir se conectar, ao ser requisitado o usuario/senha, voce deve utilizar o usuario/senha que usa para entrar no SIGACFG, por exemplo, e nao o usuario/senha que utiliza no Smartclient do TSS para o uso do dia-a-dia.

**Comment by ricardomansano** [comment]
Encerrado por falta de retorno
