### ISSUE TITLE
Erro após stop debug ou compilação 

### ISSUE THREAD

**Issue by alanFaccin** [totvs/tds-vscode#1012]
**Describe the bug**
Após compilar uma rotina ou utilizar o stop de debug e na sequência subir uma nova depuração após login apresenta o erro abaixo. Para Subir uma nova depuração é necessário reiniciar o appServer, após reiniciar funciona corretamente até depurar novamente ou usar o stop do debug.

Info  - 1:45:34 PM] [13:45:34] ERROR: Only server path are allowed to PrivKey on HttpSGet in file C:\bamboo\xml-data\build-dir\TP11-OF20300-TECXWIN64\advpl\webfuncs.inl at line 940
           
TLPP.MONITOR.CHECKURL - MONITOR_INIT.TLPP(936) - Params: NPORT:53822,CPATH:/api,CURI:/tlpp/healthCheck,CSSL_CERTIFICATE:C:\Totvs\AppProtheus\Protheus_Data\Certificados\ssl\erppro_unoesc_edu_br.crt,CSSL_KEY:C:\Totvs\AppProtheus\Protheus_Data\Certificados\ssl\erppro_unoesc_edu_br.key,CSSL_PASSPHRASE:,NTIMEOUT:2,AHEADOUT:NIL,CRESP:NIL,CRET:NIL,CHEADRET:NIL )
TLPP.MONITOR.INIT - MONITOR_INIT.TLPP(151) - Params: CCERT:C:\Totvs\AppProtheus\Protheus_Data\Certificados\ssl\erppro_unoesc_edu_br.crt,CKEY:C:\Totvs\AppProtheus\Protheus_Data\Certificados\ssl\erppro_unoesc_edu_br.key,CPASS:,CMETHOD:TLSV1.2 )

**To Reproduce**
Iniciar uma depuração, para com Stop e iniciar uma depuração novamente logando no sistema.
ou 
Compilar uma rotina utilizado o killAllUser ativo e após iniciar uma depuração e logar no sistema.

**Screenshots**
![image](https://user-images.githubusercontent.com/9438826/182664177-7796fb36-4c0f-4cf9-8b16-8fc112a7dee3.png)

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/9438826/182665802-0d4f65ce-7d60-499d-b493-ba7072191478.png)

**Appserver (please complete the following information):**

![image](https://user-images.githubusercontent.com/9438826/182666163-1f2a1afe-54c0-4952-a38f-ca10aaa64a30.png)

**Comment by alanFaccin** [comment]
Estou utilizando a versão v1.3.15

**Comment by DanielYampolschi** [comment]
Ola @alanFaccin, o ambiente que você está depurando possui alguma conexão de monitor? Se sim, experimente desligar o monitor e conectar nesse ambiente apenas com o usuário e máquina que está realizando o debug.

**Comment by lwtnb-wrk** [comment]
@alanFaccin Favor ver em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise, mas pode ser questao do appserver.
