### ISSUE TITLE
VS Code não importa arquivo TOTVS Replay

### ISSUE THREAD

**Issue by gustavo-krug** [totvs/tds-vscode#1013]
O TOTVS Replay não está importando mais nenhum arquivo.
Eu utilizo o TOTVS Replay diariamente para análise de problemas de clientes no suporte.
Entretanto, após a atualização do plugin v1.3.15, a qual atualizei essa semana, começou a não importar mais os arquivos.
Ja fiz testes com arquivos de clientes e criados por mim e não funcionou.
já fiz testes também voltando a versão do plugin, mas não funcionou.
Já desinstalei o Visual Studio Code, limpei todos os arquivos remanescentes do VS Code e reinstalei e não adiantou.

Versão Visual Studio Code:
Versão: 1.69.2 (user setup)
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Data: 2022-07-18T16:12:52.460Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

Versão Windows: 11 21H2

Em anexo estão o Log do VS Code, um vídeo do processo, o arquivo .trplay de um cliente como exemplo.

[tdsSupport.zip](https://github.com/totvs/tds-vscode/files/9253534/tdsSupport.zip)
https://user-images.githubusercontent.com/45034725/182665803-2ffa6dd5-ab75-4bcf-abd4-39e0eb672678.mp4

https://drive.google.com/file/d/1aewrPhW6atnShMRQqp_QHBCanBfH9qq6/view?usp=sharing

**Comment by DanielYampolschi** [comment]
Olá @gustavo-krug Testei por aqui e não encontrei problema. o Log que vc mandou não trouxe nenhuma informação que ajudou, mas tudo bem.

Olhando o vídeo que você mandou e fiquei com algumas duvidas... quando vc tenta importar, na Aba Console, selecione a opção TOTVS LS e me informe se você vê informações como na imagem abaixo:

![image](https://user-images.githubusercontent.com/10711513/182672481-a8bdb247-0fec-4f9c-914e-5aa4b1858ec5.png)

Caso tenha as informações, experimente aguardar mais um tempo, pois o arquivo que você enviou é u m log bem grande. 

Caso não tenha, ao invés de usar a opção de "logger capture" (que é uma captura de log antiga na realidade) adicione a opção "logFile" na configuração do seu executor como na imagem abaixo:

![image](https://user-images.githubusercontent.com/10711513/182673315-1689797c-e39e-499c-8532-520e1d4a3111.png)

**Comment by gustavo-krug** [comment]
Olá, @DanielYampolschi 

Eu não tinha mostrado a aba do TOTVS LS por não exibir nada: 
![image](https://user-images.githubusercontent.com/45034725/182678464-49363571-68e0-490e-b793-7bbac6d69678.png)


Segue vídeo do processo mostrando a aba TOTVS LS e o log gerado pelo LogFile


[tdsreplayDAP.log](https://github.com/totvs/tds-vscode/files/9253999/tdsreplayDAP.log)

https://user-images.githubusercontent.com/45034725/182678312-fba347e5-062d-4f3f-ae16-107e932a9916.mp4

**Comment by DanielYampolschi** [comment]
Legal, muito obrigado.

Só por desencargo, faz um teste por favor. 
O seu arquivo do TDS Replay esta em uma pasta que contem espaços: C:\\TOTVS\\Fontes\\Master\\Fontes\\Gestao de Transportes\\Replay\\gefco.trplay

Copia essa arquivo para uma pasta que NAO tenha espaço em nenhum lugar no caminho e altera o seu launcher apontando pra essa novo arquivo e me diga se isso resolve por favor.

**Comment by gustavo-krug** [comment]
Fiz um teste com o arquivo na pasta C:\TOTVS\ e a situação persiste.

![image](https://user-images.githubusercontent.com/45034725/182681653-91a92bd5-f859-4fa2-ac79-30e45fd60467.png)

**Comment by gustavo-krug** [comment]
Olá @DanielYampolschi

Consegui realizar a importação de arquivos .trplay após desinstalar o VS Code novamente, limpar todos os arquivos do VS Code e os arquivos temporários locais da máquina (%temp%).

![image](https://user-images.githubusercontent.com/45034725/182713543-48ef7e47-2cf7-43b5-a980-574c1d201049.png)

**Comment by lwtnb-wrk** [comment]
@gustavo-krug Eu ia sugerir apenas limpar ou reimportar o arquivo do trplay, pois pode ter tido algum problema durante a importacao, mas se ja conseguiu resolver desinstalando e reinstalando tudo, é isso que importa.
Grato pelo retorno

**Comment by gustavo-krug** [comment]
@lwtnb-wrk eu já tinha feito vários testes de reimportar o replay, com alguns arquivos e limpei algumas pastar que o VS Code cria, como descrito em [Desinstalação Completa do VSCODE](https://devforum.totvs.com.br/1252-desinstalacao-completa-do-vscode) após desinstalar uma primeira vez, mas eu não tinha limpado a pasta %temp% na primeira vez, e vi que é ali que gera os arquivos temporários do TOTVS Replay. Após limpar funcionou. Muito obrigado

**Comment by lwtnb-wrk** [comment]
@gustavo-krug Valeu pela informação. Vamos rever o processo de reimportação para ver o que podemos melhorar.
