### ISSUE TITLE
COMPILEERROR-300 It wasn't possible to obtain exclusive access to the objects repository

### ISSUE THREAD

**Issue by lufeos** [totvs/tds-vscode#1014]
Boa tarde,

Estou tentando aplicar uma LIB em meu ambiente e estou me deparando com o seguinte problema:

[Error - 14:48:22] Start build error: Server returned: 
Win : The process cannot access the file because it is being used by another process.COMPILEERROR-300 It wasn't possible to obtain exclusive access to the objects repository

Aqui usamos usamos balanceamento de carga no Protheus, onde temos um MASTER e 10 SLAVES.

No appserver.ini estamos usando a chave BuildKillUsers=1 na seção [General]

[General]
	BuildKillUsers=1

[totvsls.log](https://github.com/totvs/tds-vscode/files/9310824/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/9310825/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/9310826/totvsls_out.log)

**Comment by lwtnb-wrk** [comment]
@lufeos Esse servidor PRODUCAO33 rodando em localhost na porta 3134 é o Master ou um dos Slaves?

O erro descrito ocorre quando o tentamos obter acesso exclusivo ao RPO mas existe algo conectado a este RPO. A chave BuildKillUsers=1 deveria derrubar as conexões, mas existem casos em que ele não consegue derrubar essa conexão...

Eu estava fazendo um outro teste sem relação com essa issue e por acaso eu tinha dois AppServer apontando para o mesmo RPO, e coincidentemente deu exatamente esse erro descrito... 

De qualquer forma verifique se não existe mais nada conectado neste AppServer e tente aplicar o Patch novamente.

**Comment by lufeos** [comment]
Boa tarde,

@lwtnb-wrk o servidor PRODUCAO33 na porta localhost:3134 é o MASTER

Tenho mais 10 SLAVES, todos apontando para o mesmo RPO (inclusive o MASTER)
	SourcePath=F:\TOTVS12\Microsiga\Protheus\apo
	RPOCustom=F:\TOTVS12\Microsiga\Protheus\apo_BRASNICA\apobrasnica.rpo

Já foi verificado e estou conectado sozinho ao servidor, portas de firewall desativadas para conexões externas e mesmo assim o problema persiste;

Precisava rodar umas atualizações, tive que comentar nos appserver.ini as configurações abaixo:

[Drivers]
	Active=TCP
	;MultiProtocolPortSecure=0
	;MultiProtocolPort=1

[General]
	;App_Environment=BRASNICA
	BuildKillUsers=1


At.te,

@lufeos

**Comment by brodao** [comment]
@lufeos 

Salvo engano meu, no master não se pode fazer compilação e outros processos. 
Você tem que se conectar em um slave.

**Comment by lwtnb-wrk** [comment]
@lufeos Mas comentando as configurações mencionadas você conseguiu aplicar o patch??

É exatamente esse cenário que mencionei, múltiplos AppServers apontando para o mesmo RPO vai causar esse erro. Ao aplicar o patch nesse RPO, você deverá manter apenas um AppServer funcionando e aplicar nesse servidor. Os outros servidores não podem estar "online".

**Comment by lufeos** [comment]
@lwtnb-wrk comentando sim, consegui aplicar normalmente os patchs. isso passou a ocorrer somente na versão 33 após eu adicionar as configurações abaixo:

[Drivers]
Active=TCP
MultiProtocolPortSecure=0
MultiProtocolPort=1

[General]
App_Environment=BRASNICA
BuildKillUsers=1

O @brodao sugeriu que eu conectasse diretamente a um SLAVE (esse teste eu não fiz). Agora o sistema está em produção e não vou conseguir testar.

Será que tem uma forma de fazer isso melhor? imagina toda vez que precisar atualizar eu ter que comentar essas linhas em 11 arquivos appserver.ini rsrsrs

Obrigado pela colaboração ai turma!

**Comment by lufeos** [comment]
> @lufeos
> 
> Salvo engano meu, no master não se pode fazer compilação e outros processos. Você tem que se conectar direto em um slave. Outra coisa, não pode haver nenhum job rodando (tanto no server como nos slaves).

@brodao até a versão 27 eu semprei conectei ao MASTER... na 33 que começou aparecer isso somente depois que ativei as configurações abaixo:

[Drivers]
Active=TCP
MultiProtocolPortSecure=0
MultiProtocolPort=1

[General]
App_Environment=BRASNICA
BuildKillUsers=1

**Comment by danielbolognani** [comment]
@lufeos 
Tudo bem?
Isso começou a acontecer principalmente devido a chave "App_Environment". Essa chave sobe um serviço REST e mantém o RPO em uso mesmo sem nenhum usuário conectado no ambiente, como no seu caso são 10 appservers apontando para o mesmo RPO, ele nunca deixaria de estar "em uso". 
Desligar a chave app_environment resolveu pois desligou o serviço REST.

Nossa recomendação é, parar todos os serviços em um determinado horário e deixar apenas um appserver no ar, aplicar o patch diretamente nesse appserver e após isso reiniciar todos os serviços, garantindo assim que nenhum usuário (nem serviços) , estejam utilizando o RPO.

Abraços!

**Comment by lwtnb-wrk** [comment]
@lufeos Ah sim, o modo de acesso ao RPO na 33 foi bastante modificada em relação a versão 27 então alguns comportamentos novos irão realmente acontecer.

De qualquer forma a configuração que está "prendendo" a conexão ao RPO que não está sendo encerrada pela BuildKillUsers=1 é a App_Environment=BRASNICA

Essa configuração sobe um serviço REST em todos os servidores Slaves. E pelo visto o BuildKillUsers=1 não está identificando essas threads no Master.

Acredito que o uso de um RPO exclusivo para cada Slave, além de melhorar a escalabilidade e desempenho dos Slaves, é a forma mais adequada de se trabalhar no cenário de Master/Slaves. A contra-partida é que ao aplicar um patch, será preciso aplicar em todos estes RPOs ou após aplicar em um deles, este RPO deverá ser copiado para todos os Slaves restantes. Acho que ainda assim será melhor que ficar alterando os sppserver.ini de todos os Slaves.

**Comment by danielbolognani** [comment]
Complementando os comentário acima:
https://tdn.totvs.com/display/tec/Balanceamento+de+carga

Seria bom rever a configuração do seu ambiente, principalmente:
- Uma cópia do repositório e build deve ser utilizado no servidor Master e nos servidores Slave.
- Uma atualização de build ou de repositório quando realizada deve ser replicada nos demais servidores.
- Separe em um servidor dedicado, o ambiente de compilação: compilação é uma operação crítica, exclusiva, que não deve ser executada no mesmo serviço que atende as conexões de usuários do ambiente de produção.
- Em um ambiente balanceado, cada ambiente deve ter seu próprio RPO, sendo todos iguais. NÃO compartilhe RPO em rede, pelos seguintes motivos:
    - Em casos conhecidos os logs mostram que o sistema operacional está causando os erros de comunicação nos servidores de aplicação e não nas estações.
    - As mensagens que as estações enviam no momento de uma nova conexão mostram que foi a parte servidora da operação que cortou a conexão de rede.
    - Os servidores de aplicação fazem leitura intensiva dos RPOs quando executam o ERP, pois neles estão compiladas todas as regras de negócio, se o RPO é compartilhado em rede, tem como resultado:
      - Degradação na performance de execução dos servidores de aplicação que utilizam o RPO compartilhado (tráfego de RPO em rede).
      - O aumento do consumo de recursos de rede nos servidores que compartilham RPO, tipicamente, saturam o uso das interfaces de rede, criando uma concorrência de transmissão de dados com as estações que utilizam o TOTVS | SmartClient.

**Comment by lufeos** [comment]
> @lufeos Tudo bem? Isso começou a acontecer principalmente devido a chave "App_Environment". Essa chave sobe um serviço REST e mantém o RPO em uso mesmo sem nenhum usuário conectado no ambiente, como no seu caso são 10 appservers apontando para o mesmo RPO, ele nunca deixaria de estar "em uso". Desligar a chave app_environment resolveu pois desligou o serviço REST.
> 
> Nossa recomendação é, parar todos os serviços em um determinado horário e deixar apenas um appserver no ar, aplicar o patch diretamente nesse appserver e após isso reiniciar todos os serviços, garantindo assim que nenhum usuário (nem serviços) , estejam utilizando o RPO.
> 
> Abraços!

@danielbolognani bom dia! tudo bom e com você? Obrigado pela informação e contribuição!

**Comment by lufeos** [comment]
> Complementando os comentários acima: https://tdn.totvs.com/display/tec/Balanceamento+de+carga
> 
> Seria bom rever a configuração do seu ambiente, principalmente:
> 
> * Uma cópia do repositório e build deve ser utilizado no servidor Master e nos servidores Slave.
> * Uma atualização de build ou de repositório quando realizada deve ser replicada nos demais servidores.
> * Separe em um servidor dedicado, o ambiente de compilação: compilação é uma operação crítica, exclusiva, que não deve ser executada no mesmo serviço que atende as conexões de usuários do ambiente de produção.
> * Em um ambiente balanceado, cada ambiente deve ter seu próprio RPO, sendo todos iguais. NÃO compartilhe RPO em rede, pelos seguintes motivos:
>   
>   * Em casos conhecidos os logs mostram que o sistema operacional está causando os erros de comunicação nos servidores de aplicação e não nas estações.
>   * As mensagens que as estações enviam no momento de uma nova conexão mostram que foi a parte servidora da operação que cortou a conexão de rede.
>   * Os servidores de aplicação fazem leitura intensiva dos RPOs quando executam o ERP, pois neles estão compiladas todas as regras de negócio, se o RPO é compartilhado em rede, tem como resultado:
>     
>     * Degradação na performance de execução dos servidores de aplicação que utilizam o RPO compartilhado (tráfego de RPO em rede).
>     * O aumento do consumo de recursos de rede nos servidores que compartilham RPO, tipicamente, saturam o uso das interfaces de rede, criando uma concorrência de transmissão de dados com as estações que utilizam o TOTVS | SmartClient.

@danielbolognani Bom dia! Estarei revisando meu ambiente, obrigado pela informação e contribuição. Valeu

**Comment by lufeos** [comment]
> @lufeos Ah sim, o modo de acesso ao RPO na 33 foi bastante modificada em relação a versão 27 então alguns comportamentos novos irão realmente acontecer.
> 
> De qualquer forma a configuração que está "prendendo" a conexão ao RPO que não está sendo encerrada pela BuildKillUsers=1 é a App_Environment=BRASNICA
> 
> Essa configuração sobe um serviço REST em todos os servidores Slaves. E pelo visto o BuildKillUsers=1 não está identificando essas threads no Master.
> 
> Acredito que o uso de um RPO exclusivo para cada Slave, além de melhorar a escalabilidade e desempenho dos Slaves, é a forma mais adequada de se trabalhar no cenário de Master/Slaves. A contra-partida é que ao aplicar um patch, será preciso aplicar em todos estes RPOs ou após aplicar em um deles, este RPO deverá ser copiado para todos os Slaves restantes. Acho que ainda assim será melhor que ficar alterando os sppserver.ini de todos os Slaves.

@lwtnb-wrk Bom dia! Obrigado pela informação e contribuição! Estarei revisando todo meu ambinete. Valeu
