### ISSUE TITLE
Erro na autenticação de ambiente

### ISSUE THREAD

**Issue by TavinZampier** [totvs/tds-vscode#1016]
Quando tento logar no ambiente teste , dá a seguinte mensagem :

connection_manager.cc:4796  | Authentication error: Server returned a non numeric value. See Protheus Server log console for details.
[Error - 11:37:16] Authentication error: Server returned a non numeric value. See Protheus Server log console for details.
[Error - 11:37:16] Retrieve connection error: An error ocurred while autoReconnect.\n\

Na base Oficial está normal, mas a teste não consigo logar.

**Comment by brodao** [comment]
@TavinZampier 

As versões de binários são as mesmas? O RPO é um cópia do de produção?
As configurações do appServer (ini) são iguais, exceto o que envolve o ambiente de teste?

Favor complementar chamado informando os dados solicitados conforme [Informações importantes ao abrir o chamado](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#informa%C3%A7%C3%B5es-importantes-ao-abrir-uma-issue) e anexe os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)

**Comment by TavinZampier** [comment]
@brodao estava conectado e do nada a conexão caiu e entao não consegui entrar mais.
Nosso .ini e rpo estão no Tcloud, então acredito que esteja tudo igual quando a totvs configurou.

**Comment by lwtnb-wrk** [comment]
@TavinZampier Pode ser um corrompimento do RPO então.
A mensagem basicamente nos diz que o retorno da autenticação não é a esperada, pois deveria ser um valor numério e não é.
Veja se o pessoal do TCloud pode recuperar ou copiar um novo RPO para este ambiente, que isso deve resolver seu problema.

**Comment by TavinZampier** [comment]
Boa @lwtnb-wrk ,fiz o rollback do apo e deu certo, conectou, muito obrigado senhores.
