### ISSUE TITLE
Inspetor de variáveis não mostra sub-objetos

### ISSUE THREAD

**Issue by cirilorocha** [totvs/tds-vscode#1017]
DESCRIÇÃO:
Na versão mais atual do plugin 1.3.15 o debug não está mostrando objetos que estão contidos em outros objetos, como por exemplo os objetos MVC que tem vários componentes internos que também são objetos. Nesta versão do plugin o VSCode não mostra o sub-objeto, ficando com o conteúdo NIL. Fiz testes com a versão anterior 1.3.14 e ela mostra perfeitamente os dados.

![image](https://user-images.githubusercontent.com/96308173/186674536-db421a22-1f12-4b6e-beb7-646cde8c885e.png)

**Desktop (please complete the following information):**
 - OS/Architecture: Windows 11 x64

**Appserver (please complete the following information):**
 - Build (with date):  7.00.210324P-20220608
 - OS/Architecture: Windows 11 x64
 - Build Version 20.3.0.10

**Comment by cirilorocha** [comment]
@lwtnb-wrk sim tentei clicando no ">" e ele não abre, se eu digitar o caminho completo oModel:aAllSubModels por exemplo ele abre no inspetor.

Abaixo um exemplo:

User Function uTeste()
	oTemp	:= FWLoadModel( "TAFA433" )
Return

**Comment by DanielYampolschi** [comment]
Ola @cirilorocha, obrigado pelo exemplo.

Fiz alguns testes aqui e mesmo com o exemplo que você enviou não consigo reproduzir de forma alguma. 
Veja na imagem abaixo que os objetos foram expandidos corretamente.
![image](https://user-images.githubusercontent.com/10711513/187515762-e76406f9-89c6-4b28-8817-a772a7bf5006.png)

Uma duvida, no seu print, o objeto aparece como conteudo como "NIL" mas se voce tentar expandir ainda sim nao abre nada?

E outra coisa, isso acontece na visao de Watch (Inspeção) quanto na visão de Variáveis para o mesmo objeto? Ou só em uma delas?

**Comment by cirilorocha** [comment]
@DanielYampolschi O problema é na visual Watch (Inspeção), realmente não tinha observado que na lista de variáveis abre normalmente.
Se eu clicar em expandir não expande. Se eu adicionar o caminho completo na janela Watch, ele abre esse nível normalmente, ex.: oTemp:aAllSubModels vai conseguir abrir na janela de inspeção.

**Comment by lwtnb-wrk** [comment]
@cirilorocha Nao estamos conseguindo reproduzir seu problema aqui, mesmo na ultima versao v1.3.15 do tds-vscode

Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by cirilorocha** [comment]
Pelo que identifiquei aqui o problema ocorre quando utilizo o include RWMake.ch. Sem ele o debug fica normal. Acho que foi por isso que não reproduziu ai.
Seguem os arquivos de log solicitados.
[dap.log](https://github.com/totvs/tds-vscode/files/9461780/dap.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/9461781/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/9461782/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/9461783/totvsls_out.log)

**Comment by lwtnb-wrk** [comment]
@cirilorocha Poderia nos enviar um programa bem simples com includes necessários para reproduzir o problema?
Sua pasta de includes é a de qual data? A penúltima de 22-07-15-P12_INCLUDES ou anterior?

Eu compilei com o RWMake.ch antigo e não havia reproduzido o problema, mas ao recompilar com um include mais recente o problema se manifestou. Só que agora mesmo recompilando com includes antigo o problema persiste. Então seria bom se você pudesse informar os passos exatos para reproduzir e corrigir o problema somente trocando os includes.

**Comment by cirilorocha** [comment]
@lwtnb-wrk Acho que consegui reproduzir 100%. Tem alguma haver quando o objeto no inspetor fica expandido (mostrando os detalhes) e eu encerro o cliente com ele desta forma. Ao abrir outro debug e usando o mesmo inspetor (eu não removi a variável que já estava lá expandida) ele não consegue mais mostrar os detalhes. Se eu adicionar ela novamente consigo expandir os detalhes normalmente. Se eu tiver fechado o cliente com a variável no watch recolhida, essa situação não ocorre.
Gravei um pequeno vídeo de todo o processo, espero que ajude a identificar.


https://user-images.githubusercontent.com/96308173/187744315-f3527082-4ebf-4858-a2f3-5a0176893b2f.mp4

**Comment by lwtnb-wrk** [comment]
@cirilorocha Grato pelo vídeo e informações de como reproduzir a ocorrência.
Conseguimos reproduzir e vamos trabalhar na correção.

**Comment by cirilorocha** [comment]
Instalei a release 1.3.16 do plugin e o appserver 20.3.1.2 e o problema não ficou resolvido. Agora ele não mostra de forma alguma os dados do objeto no inspetor, apenas se eu olhar diretamente em variáveis.

![image](https://user-images.githubusercontent.com/96308173/209397008-70a8e8e9-3f7f-4f78-b44b-931e8c6dddd8.png)

**Comment by lwtnb-wrk** [comment]
Geramos uma versão Pré-Release da v1.3.17 que já deve corrigir este problema.
Se quiser/puder testar, instale a versão https://github.com/totvs/tds-vscode/releases/tag/v1.3.17-RC1 manualmente seguindo https://github.com/totvs/tds-vscode/blob/master/docs/install.md

**Comment by cirilorocha** [comment]
Fiz diversos testes em vários cenários e o problema ficou resolvido nesta versão 1.3.17RC1. Muito obrigado pela força.

**Comment by lwtnb-wrk** [comment]
show. assim que liberamos a versao oficial eu fecho a issue. grato pelos testes
