### ISSUE TITLE
Erro Application Server

### ISSUE THREAD

**Issue by RamoniMiranda** [totvs/tds-vscode#1018]
Bom dia,
fiz toda a configuração do Vscode,  o fonte compila normalmente, mas ao executar da erro no Application Server.
Estou usando uma base de testes, com o usuário Admin.
Conseguem me ajudar.
Desde já agradeço

![image](https://user-images.githubusercontent.com/111885431/187459327-3233603f-25cc-426e-869d-a0872c6cf2fb.png)

2022-08-30T11:02:20.419000-03:00 10980|
[INFO ][SERVER] [Thread 10980] [30/08/2022 11:02:20] End Build.
2022-08-30T11:02:34.272000-03:00 2168|
[WARN ][SERVER] SourcePath Key not defined in the ini file. Using default set to C:\TOTVS12133\Protheus\Protheus\bin\appserver\appserver.rpo
2022-08-30T11:02:34.273000-03:00 2168|
[WARN ][SERVER] RpoCustom Key not defined in the ini file. Using default set to C:\TOTVS12133\Protheus\Protheus\bin\appserver\custom.rpo
2022-08-30T11:03:12.491000-03:00 11336|[VDRPORT] 220830_110312 2C48 BPC2115 E x 04 ctx:844 error 64 (operacao em conexao fechada remotamente) in receive from client 127.0.0.1:56723

2022-08-30T11:03:12.492000-03:00 10980|
[WARN ][SERVER] [THROW][Thread  10980] tConnnErrorException (8:Erro de comunicacao: Erro de sincronismo) on C:\bamboo\xml-data\build-dir\TP11-OF20300-TECXWIN64\lib_comm\msgmanager.cpp:472

2022-08-30T11:03:12.492000-03:00 10980|
[INFO ][SERVER] [[Thread  10980][30/08/2022 11:03:12] Debugger finished ( (ramoni.miranda, PROENG11589)

2022-08-30T11:03:46.596000-03:00 13908|
[INFO ][SERVER] [Thread 13908] [30/08/2022 11:03:46] Starting Debugger (ramoni.miranda, PROENG11589)

2022-08-30T11:03:46.751000-03:00 13908|
[WARN ][SERVER] SourcePath Key not defined in the ini file. Using default set to C:\TOTVS12133\Protheus\Protheus\bin\appserver\appserver.rpo
2022-08-30T11:03:46.752000-03:00 13908|
[WARN ][SERVER] RpoCustom Key not defined in the ini file. Using default set to C:\TOTVS12133\Protheus\Protheus\bin\appserver\custom.rpo

**Comment by RamoniMiranda** [comment]
Sim consigo, entro com o Admin sem senha.

**Comment by lwtnb-wrk** [comment]
@RamoniMiranda Ok, mas esse erro que aparece é na configuração do AppServer.ini
Você configurou esse parâmetro corretamente?

Se estiver com esse parâmetro configurado corretamente, veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analises.

**Comment by RamoniMiranda** [comment]
Tá ok, seguem os arquivos.

[totvsls_in.log](https://github.com/totvs/tds-vscode/files/9453962/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/9453963/totvsls_out.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/9453964/totvsls.log)

**Comment by danielbolognani** [comment]
@RamoniMiranda essa mensagem de erro normalmente é quando tenta conectar em um ambiente inexistente.
Verifique se o ambiente que está sendo informado na conexão com o appserver no VSCode existe no appserver.ini. Esse ambiente é o mesmo que precisa ser informado nos parâmetros iniciais do smartclient.

Ps. Os logs que vc enviou não possuem informações, após ligar os logs é necessário conectar no appserver e compilar/executar para que as informações sejam gravadas.

Abraços

**Comment by RamoniMiranda** [comment]
Daniel bom dia,

obrigada configurei e agora ao compilar o fonte está com a mensagem de
Invalid RPO signature. Please update your RPO file.

**Comment by lwtnb-wrk** [comment]
@RamoniMiranda Agora aparentemente ele está lendo o RPO e o problema é a versão da lib de seu RPO e relação ao dicionário configurado.

**Comment by RamoniMiranda** [comment]
Iwtnb baixei um rpo novo e deu certo.
Muito obrigada pela ajuda de vcs!!!!!
