### ISSUE TITLE
Sugestão Resultado da Compilação

### ISSUE THREAD

**Issue by alissonph** [totvs/tds-vscode#102]
A tabela de resultado de compilação (Compilation Result) aparece somente quando é compilado mais de um arquivo (CTRL + F10), sugestão é também permitir que seja exibido essa tabela quando compilar somente um fonte (CTRL + F9). A informação quando é compilado "SKIPPED" é importante e não é exibida quando compilado somente um arquivo.

**Comment by matheus-sales** [comment]
@alissonph essa informação é informada no console de ADVPL, então apenas para um fonte você consegue facilmente visualizar lá. O Compilation Result só será exibido quando compilado mais de um fonte, já que no console é exibida tantas compilações que as informações ficam perdidas.

**Comment by alissonph** [comment]
@matheus-sales obrigado pela informação, encontrei no "Output" a opção "AdvPL", não sabia da existência da mesma. Isso mesmo que precisava.
