### ISSUE TITLE
Problema de conexão com 2 vscodes abertos

### ISSUE THREAD

**Issue by likid** [totvs/tds-vscode#1020]
Ao abrir 2 vscodes, em workspaces diferentes, para projetos diferentes, ao realizar a conexão no appserver em um vscode, a conexão do outro é invalidada, necessitando reconectar cada vez que for fazer uma compilação ou debug nos vscodes abertos.
Resumindo, não é possível manter duas conexões diferentes abertas nos appservers em dois vscodes abertos.

**Comment by lwtnb-wrk** [comment]
@likid Se entendi corretamente, você está trabalhando com dois VS Codes abertos em dois workspaces diferentes, mas conectados em um mesmo AppServer?

Mas porque exatamente você precisar fazer isso??

**Comment by likid** [comment]
Leo, quase isso, estou conectado em 2 appservers diferentes.
VSCode 1 - conecto no appserver 1, compilo, debugo, tudo funciona.
VSCode 2 - conecto no appserver 2, compilo, debugo, tudo funciona.

VSCode1 - tento compilar, ocorre erro dizendo que a conexão está inválida e tenho que me conectar novamente.
Após isso se volto ao VSCode 2, ocorre o mesmo problema do VSCode1 e também tenho que reconectar.

**Comment by lwtnb-wrk** [comment]
@likid Entendi. Fui testar aqui e já sei o que está ocorrendo.

O "problema" é que os dois VS Codes estão usando e compartilhando do mesmo servers.json (Global).
Então quando o segundo VS Code se conecta, a informação do AppServer conectado pelo primeiro é sobrescrita.
Para este seu cenário com dois VS Code funcionar, você precisa usar servers.json separados. Um deles pode até ser o Global, mas o outro terá que ser Local (Workspace).
Em um dos dois VS Code, clique no ícone que parece um "globo terrestre" na barra inferior do tds-vscode. Com isso o ícone vai passar a ser uma "casinha" (indicando uso local do workspace). Cadastre o AppServer novamente, pois a configuração será "nova". E assim as conexões de um VS Code não interferirão na do outro VS Code.
 
Enfim, acho que esse uso simultâneo de dois tds-vscodes, pode trazer mais confusões a longo prazo que ficar em apenas um workspace e ter que eventualmente trocar de servidor. Se possível use apenas um VS Code mesmo...

**Comment by likid** [comment]
Entendi. Irei fazer esta alteração aqui. Infelizmente estou em um cenário onde preciso utilizar 2 vscodes para compilar em 2 servers diferentes de duas empresas diferentes, apesar de que é uma situação temporária.
Obrigado pelo suporte.
