### ISSUE TITLE
VSCode Windows X Protheus Linux

### ISSUE THREAD

**Issue by SidBrs** [totvs/tds-vscode#1021]
Bom dia a todos !
Temos um VSCode instalado em uma máquina windows e o Protheus (GFE) instalado em um servidor linux.
É possível compilar/aplicar pacotes no Protheus Linux a partir desse VSCode no windows? Caso positivo, como fazer?

**Comment by brodao** [comment]
Sim. Os pacotes de atualização e compilações geram código independente de máquina.
Veja em [Compileação](https://github.com/totvs/tds-vscode/blob/master/docs/compilation.md) e [Aplicação de atualizações](https://github.com/totvs/tds-vscode/blob/master/docs/apply-patch.md).

**Comment by SidBrs** [comment]
@brodao, muito obrigado pela sua resposta rápida e objetiva !
