### ISSUE TITLE
Erro ao tentar excluir um ambiente.

### ISSUE THREAD

**Issue by ofnerjulio** [totvs/tds-vscode#1022]
Alguém já pegou esse erro ao tentar excluir um ambiente.
![image](https://user-images.githubusercontent.com/72528922/190649881-523fc602-32e4-4421-ad25-89217a5f2f52.png)

**Comment by lwtnb-wrk** [comment]
@ofnerjulio Grato por reportar o problema.

Já reproduzi aqui e vamos ver o que está ocorrendo. Assim que possível disponibilizaremos uma correção.

**Comment by lwtnb-wrk** [comment]
v1.3.16 com a correção liberada no Marketplace.
