### ISSUE TITLE
Exclusão de função do RPO

### ISSUE THREAD

**Issue by ofnerjulio** [totvs/tds-vscode#1023]
Estou tentado excluir um Ponto de entrada do meu RPO e não estou conseguindo.
O vsCode não fazer exatamente nada.

**Comment by lwtnb-wrk** [comment]
@ofnerjulio Aproveitando a questão, qual era o seu problema e o que fez para soluciona-lo?

Assim se outro dev tiver esse problema ela já saberá como resolve-la.

**Comment by ofnerjulio** [comment]
Foi passar aqui, mais era algo muito besta
Essa mensagem não estava aparecendo.
![image](https://user-images.githubusercontent.com/72528922/190656257-84fc2168-db39-4e51-968c-9ea2fbf8b488.png
como essa pergunta não era apresentada, não conseguia efetuar a exclusão.
A mensagem não era apresentada pois estava desativado.
![image](https://user-images.githubusercontent.com/72528922/190657441-eeb78a02-62a9-4539-b299-f017f6d17c72.png)

**Comment by lwtnb-wrk** [comment]
@ofnerjulio Grato pela informação.

Então você estava com o modo "Não Perturbe" (Do Not Disturb) ativado e com isso a notificação de confirmação não foi exibida no canto inferior.

Eu testei aqui e reparei que com esse modo ativado, aparece um "ponto" sobre a campainha para notificar que existe uma nova "Notificação", mas realmente ela não é exibida automaticamente por conta do "Não Perturbe". Vamos avaliar essa questão e talvez alterar para um outro componente que não seja oculto quando este modo estiver ativado.
