### ISSUE TITLE
Erro ao tentar executar meu código HTML

### ISSUE THREAD

**Issue by emanuel963** [totvs/tds-vscode#1024]
Olá a todos, me chamo Emanuel e recentemente comecei um curso de ADS. Para encurtar a história, pouca familiarização com as ferramentas pois até então só editava e configurava diretamente pelo navegador. Enfim. 
Escrevi um código do que seria uma página e até ai tudo bem. A questão é que tive dúvidas na hora de implementar ou adicionar o CSS no código HTML. Vi um vídeo e até consegui, através de um link que buscava na outra aba o código.
O que acontece é que quando executo o depurador uma pasta chamada ".vscode" é criada e dentro um arquivo ou o que seja, chamado "launch.json" e daí fica abrindo uma página de localhost... Bom é isso. Se alguém puder me ajudar, ficarei bastante grato. 
Ah, e sou novo por aqui, peço desculpas caso eventualmente eu esteja postando isso no lugar errado do site. 

Abaixo o que aparece dentro desse arquivo "launch.json"

{
    // Use o IntelliSense para saber mais sobre os atributos possíveis.
    // Focalizar para exibir as descrições dos atributos existentes.
    // Para obter mais informações, acesse: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}"
        }
    ]
}

Abaixo o meu código, que no caso é uma atividade do primeiro semestre do curso, na parte de Front-End. 

<!DOCTYPE html>
	<hmtl lang="en">
		<head>
		<link href="css/formulario.css" rel="stylesheet">
		<meta charset="uts-8">
		<meta name="viewport" content="width=device-width,inicial-scale=1.0">
		<title>Cadastro XYZ </title>
	</head>
	<body>
		<div>
			<h1 id="titulo"> Cadastro</h1>
			<P id="subtitulo">Complete com suas informaçoes os seguintes campos</P>
			<br>
        </div>
		
        <form>
        	<fieldset>
        		<div>
        			<label>Nome</label>
        			<input type="text" name="nome" id="nome">
        		</div>
        	

        		<div>
        			<label>Sobrenome</label>
        			<input type="text" nome="nome" id="nome">
        		</div>
           
            <div>
            	<label>Data de Nascimento</label>
            	<input type="text" name="Data de Nascimento" id="Data de Nascimento">
            </div> 
      
            <div>
                 <label>Endereço</label>
                 <input type="text" name="Endereço" id="Endereço">
            </div> 	
         
            <div>
            	<label>Numero da Casa ou Apto</label>
            	<input type="text" name="Numero da Casa ou Apto" id="Numero da Casa ou Apto">
            </div>		

            <div>
            	<label>Cidade</label>
            	<input type="text" name="Cidade" id="Cidade">
            </div>	
            
            <div>
            	<label>Estado</label>
            	<select id="Estado">
            		<option>Acre</option>
            		<option>Alagoas</option>
            		<option>Amapá</option>
            		<option>Amazonas</option>
            		<option>Bahia</option>
            		<option>Ceará</option>
            		<option>Distrito Federal</option>
            		<option>Espírito Santo</option>
            		<option>Goiás</option>
                    <option>Maranhão</option>
                    <option>Mato Grosso</option>
                    <option>Mato Grosso do Sul</option>
                    <option>Minas Gerais</option>
                    <option>Pará</option>
                    <option>Paraíba</option>
                    <option>Paraná</option>
                    <option>Pernambuco</option>
                    <option>Piauí</option>
                    <option>Rio de Janeiro</option>
                    <option>Rio Grande do Norte</option>
                    <option>Rio Grande do Sul</option>
                    <option>Rondônia</option>
                    <option>Roraima</option>
                    <option>Santa Catarina</option>
                    <option>São Paulo</option>
                    <option>Sergipe</option>
                    <option>Tocantins</option>

            </select>

            	<div>
            		<label>Sexo:</label>
            		<label>
            			<input type="radio" name="devweb" value="masculino">Masculino
            		</label>
            		<label>
            			<input type="radio" name="devweb" value="feminino">Feminino
            		</label>	

            	</div>
            
              <div>
                  <label>Bens Pessoais:</label>
                  <input type="checkbox" id="bens1" name="bens1" value="Casa">
                  <label for=bens1>Casa</label>
                  <input type="checkbox" id=bens2 name="bens2" value="Carro">
                  <label for=bens2>Carro</label>
                  <input type="checkbox" id="bens3" name="bens3" value="Moto">
                  <label for=bens3>Moto</label>
              </div>

            </fieldset>

            <div>
            	<br>
            	<label>Conte suas experiencias pessoais </label>
            	<textarea row="13" style="width:26em" id="experiencia"></textarea>
            </div>
            
            <button type="submit">Enviar</button>	
        </form>
	</body>
	</hmtl>	

e para finalizar, segunda página que criei para linkar a ela o CSS no HTML acima, com alguns alterações que tentei implementar... Até então a parte do body com a mudança de cor do fundo tinha sido bem executada, mas ai ficou acontecendo isso e sequer consigo ver a página HTML que to editando, pois novamente, quando tento abrir... não executa.

body {
    background-color: silver;
    color:black
  }
  * {font-family: Verdana;
}
h1 {
    color:purple;
    text-align: center;
}
fieldset {
    width:60% 
    border: radius 15px;
background-color:white
box: shadow 2px 2px 2px gray;
}

É isso pessoal, de já agradeço a paciência e o suporte. 
Grato.

**Comment by danielbolognani** [comment]
Boa tarde @emanuel963 
Esse espaço é reservado para dúvidas/problemas com a extensão tds-VSCode para utilização com o ERP Protheus e Logix. 
Não temos como auxiliar com assuntos não relacionados a nossa extensão.
Abraços
