### ISSUE TITLE
Compilar no VsConde via webapp (SmartClienteHtml)

### ISSUE THREAD

**Issue by DiogoGiacomazzi** [totvs/tds-vscode#1025]
Bom dia!
Preciso compilar um fonte via WebApp (http://localhost:8089)
No laucher estou entrando com configuração abaixo:
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "WebApp",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientUrl": "http://localhost:8089",
			"isMultiSession": true,
			"enableTableSync": true,
			"enableMultiThread": true
		}

Visual Studio Code: Web Navigator not informed
Open launch.json or cancel

**Comment by lwtnb-wrk** [comment]
@DiogoGiacomazzi Você esta tentando compilar um fonte ou depurar?

Veja as documentações abaixo do que você precisa fazer:
https://github.com/totvs/tds-vscode/blob/master/docs/compilation.md
https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md

**Comment by DiogoGiacomazzi** [comment]
Boa tarde.

 

Depuração mesmo.

 

Era justamente esta documentação que eu estava procurando, muito obrigado.

 



 

De: lwtnb-wrk ***@***.*** 
Enviada em: quinta-feira, 22 de setembro de 2022 11:00
Para: totvs/tds-vscode ***@***.***>
Cc: DiogoGiacomazzi ***@***.***>; Mention ***@***.***>
Assunto: Re: [totvs/tds-vscode] Compilar no VsConde via webapp (SmartClienteHtml) (Issue #1025)

 

@DiogoGiacomazzi <https://github.com/DiogoGiacomazzi>  Você esta tentando compilar um fonte ou depurar?

Veja as documentações abaixo do que você precisa fazer:
https://github.com/totvs/tds-vscode/blob/master/docs/compilation.md
https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md

**Comment by lwtnb-wrk** [comment]
@DiogoGiacomazzi E já percebi que o type que está usando está incorreto. 
Corrija conforme a documentação https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md#totvs-language-web-debug-html e ajuste a configuração de navegador.
Com isso você deve ser capaz de depurar o webapp.
