### ISSUE TITLE
Erro na aplicacao de patchs Protheus

### ISSUE THREAD

**Issue by snlacerda89** [totvs/tds-vscode#1029]
Ao tentar aplicar um patch via vscode, é apresentado o seguinte erro:

[Info  - 17:54:35] Starting patch validate.
[Info  - 17:54:35] Patch file: c:/Users/sergio.lacerdagass/Downloads/22-06-06_ATUALIZACAO_12.1.33_WMS_EXPEDICAO_CONTINUA/expedicao_continua_12_1_33_wms_tttm120_hp.ptm
[Info  - 17:54:35] Starting build for environment ENVIRONMENT.
[Info  - 17:54:41] Starting build using RPO token ...
[Error - 17:54:41] File could not be copied to the server.
[Error - 17:54:41] Patch validate could not be executed. Server returned: Patch file D:\Totvs\Protheus\Data\\tmptdstotvs-tst/expedicao_continua_12_1_33_wms_tttm120_hp29-09-2022-17-54-41.ptm not found
[Info  - 17:54:41] Aborting end build (rollback changes).
[Info  - 17:54:41] Patch validate finished.
[Error - 17:54:41] Patch file D:\Totvs\Protheus\Data\\tmptdstotvs-tst/expedicao_continua_12_1_33_wms_tttm120_hp29-09-2022-17-54-41.ptm not found

Versao plugin: 1.3.15

Versao appserver:
2022-09-29T17:59:03.152000-03:00 7204|***  TOTVS S/A  ***
***  www.totvs.com.br  ***
* TOTVS - Build 7.00.210324P - Sep 16 2022 - 14:42:37 
* Build: 64 bits
* SVN Revision: 36512

* Build Version: 20.3.0.14

**Comment by snlacerda89** [comment]
Windows Server 2008 R2

**Comment by lwtnb-wrk** [comment]
@snlacerda89 O AppServer está em um Windows Server 2008 R2 ou você está executando o tds-vscode em um Windows Server 2008 R2?
O tds-vscode não funciona corretamente em SO Windows Server, pois é uma limitação do próprio VS Code.
Se este for seu caso, instale o tds-vscode em um Windows Desktop e repita essa operação. Mas caso não seja seu caso, veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by snlacerda89** [comment]
Estou executando no windows server 2008 R2! Infelizmente nosso acesso remoto é somente ao server!
Vou pedir para o pessoal de infra criar uma regra que possibilite eu trabalhar localmente
