### ISSUE TITLE
Passagem de parametros para a inicialiação do Program

### ISSUE THREAD

**Issue by rodrigofelippeac** [totvs/tds-vscode#103]
Estou tentando fazer a execução do programa utilizando as diretivas, porém a 
${command:AskForProgramArguments} não é chamada ao tentar executar os parâmetros conforme a documentação abaixo:  
https://github.com/totvs/tds-vscode/wiki/Configura%C3%A7%C3%A3o-de-diretivas-no-depurador

Segue a configuração do launch.json: 

{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Totvs Language Debug",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "C:\\smartclient\\SmartClient.exe",
			"isMultiSession": true,
			"enableTableSync": true,
			"programArguments": "${command:AskForProgramArguments}",
			"enableMultiThread": true,
			"enableProfile": false,
			"isAccessibilityMode": false,
			"doNotShowSplash": false,
			"language": "",
			"ignoreFiles": true
		}
	],
	"lastPrograms": [
		{
			"args": [],
			"label": "sigaloja",
			"description": ""
		}
	],
	"lastProgramExecuted": "sigaloja"
}

**Comment by lwtnb-wrk** [comment]
@rodrigofelippac Notei que voce utilizou o separador '\' em "smartclientBin". Experimente utilizar o separador '/' ou substituir por '\\'.

**Comment by lwtnb-wrk** [comment]
@rodrigofelippac Ah outra coisa veja se utilizando:
"programArguments": [ "${command:AskForProgramArguments}" ],
ao inves de apenas:
"programArguments": "${command:AskForProgramArguments}",
funciona.

**Comment by rodrigofelippac** [comment]
Troquei e continua sem funcionar! 

{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Totvs Language Debug",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "C://smartclient//SmartClient.exe",
			"isMultiSession": true,
			"enableTableSync": true,
			"programArguments": "${command:AskForProgramArguments}",
			"enableMultiThread": true,
			"enableProfile": false,
			"isAccessibilityMode": false,
			"doNotShowSplash": false,
			"language": "",
			"ignoreFiles": true
		}
	],
	"lastPrograms": [
		{
			"args": [],
			"label": "sigaloja",
			"description": ""
		}
	],
	"lastProgramExecuted": "sigaloja"

**Comment by lwtnb-wrk** [comment]
@rodrigofelippac Estamos analisando o problema. Grato por nos avisar.

**Comment by ronrodrigues** [comment]
Bom dia.

Solicito informações acerca deste problema, pois necessito muito desse processo.

**Comment by edvarwv** [comment]
Segue abaixo todo meu arquivo launch.json 

{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Totvs Language Debug",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "C:\\Protheus_12.1.23\\smartclient.exe",
			"enableMultiThread": true,
			"enableProfile": false,
			"isMultiSession": true,
			"isAccessibilityMode": false,
			"doNotShowSplash": false,
			"ignoreFiles": true,
			"enableTableSync": true
		}
	],
	"lastPrograms": [
		{
			"args": [],
			"label": "SIGAADV",
			"description": ""
		}
	],
	"lastProgramExecuted": "SIGAADV"
}

**Comment by rogeriorc** [comment]
> Bom dia.
> 
> Solicito informações acerca deste problema, pois necessito muito desse processo.
no launch.json:

			"program": "U_testParam",
			"programArguments": [
				"A",
				"B",
				"C"
			],

**Comment by ricardomansano** [comment]
Boa tarde, dado o tempo sem interação acredito que o problema tenha sido resolvido nas ultimas versões.
Qualquer inconsistência estamos à disposição.
