### ISSUE TITLE
Server returned: Win: The process cannot access the file because it is being used by another process. DEFAULT

### ISSUE THREAD

**Issue by badwilliams** [totvs/tds-vscode#1030]
## Enter the data below
29/09/2022

**Describe the bug**
Estamos tentando compilar qualquer fonte em um ambiente exclusivo e ocorre o erro em anexo, não deixando finalizar a compilação.

**To Reproduce**
1. Go to - Abrir fonte
2. Click on - Compilar
3. See error - Server returned: Win: The process cannot access the file because it is being used by another process. DEFAULT

**Screenshots**
![image](https://user-images.githubusercontent.com/102381573/193140600-3c18eb30-f116-4bfe-9e40-6ddbed375b41.png)

 - Build (with date): Build 7.00.210.324P-20220608-64 bits
 - OS/Architecture: Windows Server 2016
 - Build Version 20210202-20220802
 - Appserver version: 20.3.0.10
 - Versão da Lib: 20220725

**Additional context**
O ambiente que estamos compilando é totalmente exclusivo, não temos nenhum outro apontamento pra ele.

**Comment by lwtnb-wrk** [comment]
@badwilliams O que pode estar ocorrendo é que existem jobs (como um serviço REST) rodando neste AppServer. O Harpia, por padrão, sobe um serviço REST durante a inicialização, então ele pode estar "prendendo" o processo impedindo a compilação.
Enfim, veja se existe a chave BuildKillUsers=1 na seção [general] de seu AppServer. Ela força a derrubada de todos os processos antes da compilação e deve permitir que você realize a compilação.
Se não for seu caso, veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analises.

**Comment by badwilliams** [comment]
Obrigado pelo retorno @lwtnb-wrk. Realmente haviam conexões travadas no dbaccess. Não precisei utilizar a chave BuildKillUsers, apenas reiniciar todo o nosso ambiente na janela de manutenções.
