### ISSUE TITLE
Protheus - Debug de webservice não funciona corretamente através do vscode

### ISSUE THREAD

**Issue by rlajunior** [totvs/tds-vscode#1033]
Eu e alguns analistas desenvolvimento estamos sofrendo com problema crônico ao efetuar um debug de uma aplicação webservice no vscode, isso já ocorre bastante tempo, seguimos o passo a passo para o debug, conectando no appserver do rest, abrimos um sessão no debug, consumimos a api por postman ou por aplicação e debug não para.

Por algumas vezes isso funciona, mas para de funcionar sem qualquer explicação lógica.

Meu extensão no vscode está na última versão v1.3.15, tudo configurado corretamente, tanto que um debug de tela funciona perfeitamente, mais de webservice sempre esse mesmo problema intermitente.

Lembro que não tinha esse problema no TDS antigo.

Vídeo em anexo, compilo o fonte no RPO que está o rest, entro no serviço do rest, rodo o debug e não funciona, isso estava funcionando ontem e simplesmente parou.

Uso windows 11 com vscode

Servidor do appserver windows 2019 appserver 64

**Comment by rlajunior** [comment]
Boa tarde @lwtnb-wrk sei que depuração do rest,  existem algumas particularidades, como já existia no TDS antigo.

Como está nessa documentação passada pela Totvs
https://centraldeatendimento.totvs.com/hc/pt-br/articles/4635440648471-Cross-Segmento-TOTVS-Backoffice-Linha-Protheus-ADVPL-Depura%C3%A7%C3%A3o-de-Jobs-ou-WebService-bin%C3%A1rio-harpia?source=search

O Problema que para mim como para outros analista a depuração funciona de forma intermitente, hoje pela manhã estava depurando um código, precisei compilar novamente o serviço, fui efetuar novamente a depuração e parou.

Conversando com alguns analista desenvolvedores os mesmos dizem ter esse mesmo problema essa intermitência que antigamente não ocorria no TDS.
 
Tenho certeza não ser um problema na configuração do appserver.ini, porque funciona por algumas vezes.

No que puder me ajudar, posso fornecer mais informações.

**Comment by lwtnb-wrk** [comment]
@rlajunior Se possível envie o vídeo que mencionou no início. O problema de analisar algo que falha de forma intermitente é que não conseguimos reproduzir localmente.
E qual a build exata do AppServer que estão usando? Por exemplo, 20.3.0.14...

**Comment by rlajunior** [comment]
Descobri o problema, conversando com a Totvs, verifiquei que tudo estava atualizado  menos o appserver , deposi que atualizei o appserver voltou a funcionar.

Obrigado.

**Comment by lwtnb-wrk** [comment]
@rlajunior Excelente, menos mal que era somente isso.
Ah, se puder deixar a informação de para qual versão você atualizou, ela vai ficar para todos que tiverem o mesmo tipo de problema que você teve.
