### ISSUE TITLE
Rpo padrão não está sendo desfragmentado

### ISSUE THREAD

**Issue by gtrabach** [totvs/tds-vscode#1037]
**Describe the bug**
O rpo padrão não está sendo desfragmentado pelo TDS. Perceba na vídeo evidência que após aplicação do patch o rpo cresce de tamanho, mas após execução do processo de desfragmentação, o tamanho continua o mesmo

**To Reproduce**
1. Avalie o tamanho do rpo padrão.
2. Aplique um pacote de atualização qualquer.
3. Avalie o tamanho do rpo (terá crescido, normal).
4. Solicite a desfragmentação do rpo. Aguarde a conclusão.
5. Avalie o tamanho do rpo (não terá seu tamanho alterado, anormal).

**Expected behavior**
O rpo deveria reduzir o seu tamanho após o processo, e não manter o mesmo pós-patch.

**Versões**
Visual Studio: 1.70.0
TDS: 1.3.15
AppServer: 20.3.0.14
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/9854661/totvsls_out.log)

https://user-images.githubusercontent.com/46979335/197608198-d5385d0e-bee9-4b1c-b8d6-891d173bb927.mp4

[totvsls.log](https://github.com/totvs/tds-vscode/files/9854663/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/9854665/totvsls_in.log)

**Comment by lwtnb-wrk** [comment]
@gtrabach É um problema conhecido do AppServer. #1031 
Você vai precisar atualizar-lo para a ultima versao.
