### ISSUE TITLE
Erro ao tentar usar a extensão: spawn UNKNOWN

### ISSUE THREAD

**Issue by elcyferring** [totvs/tds-vscode#1038]
Uma nova instalação do VSCode + Extensão Protheus. Em outras instalações funciona normalmente. O detalhe é que esta máquina possui algumas restrições de instalação de apps etc, impostas pela governança global da empresa.

# Help us to help you.

## Before opening an issue

- Make sure the extension is up to date. OK
- See [Resolução de Problemas](TROUBLESHOOTING.md#problemas-gerais), with common and/or known occurrences. OK

## Enter the data below

**Describe the bug**
Erro no VSCode ao tentar utilizar a extensão do Protheus:

---------------------------v---------------------------------------------------
   //////  ////    //////  |  TOTVS Developer Studio for VS-Code
    //    //  //  //       |  Version 1.3.15
   //    //  //  //////    |  TOTVS Technology
  //    //  //      //     |
 //    ////    //////      |  https://github.com/totvs/tds-vscode
---------------------------^---------------------------------------------------
[Error - 18:29:17] Starting client failed
Error: spawn UNKNOWN
	at ChildProcess.spawn (node:internal/child_process:413:11)
	at Object.spawn (node:child_process:720:9)
	at c:\Users\elrc\.vscode\extensions\totvs.tds-vscode-1.3.15\node_modules\vscode-languageclient\lib\main.js:376:40

**To Reproduce**
1. Open VSCode
4. See error on SAÍDA \ TOTVS LS

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
Windows 64 bits

**Appserver (please complete the following information):**
Build AppServer: 7.00.210324P-20220916 - 64 bits
Nome do servidor: MJL4AHPRDESBN51
Sistema operacional: Windows Server 2016
Appserver version: 20.3.0.14
Build DBAccess: 20210202-20220802
Release do RPO:  12.1.033
Release do dicionário: 12.1.033
Local files: ctree
License server: 2014 - 3.4.2
DB DataBase: MSSQL
DB API Build: 20210202-20220802

**Additional context**

**Comment by lwtnb-wrk** [comment]
@elcyferring Se existem restrições de execução nessa máquina por conta da governança da empresa, provavelmente não há nada que possamos fazer.
Para confirmar essa questão, tente executar/abrir uma linha de comando "cmd" no Windows. Se ocorrer uma mensagem semelhante a "The command prompt has been disabled by your Administrator", requisite a liberação deste acesso, caso contrário, não será possível utilizar o tds-vscode nesta máquina.

**Comment by elcyferring** [comment]
O CMD abre, o CMD (Admin) não abre.
Consegui incluir um Servidor, mas se eu clico no botão Conectar, nada acontece.
Vejo mensagens de erro, tais como:
-> Server name already exists
-> [2864:1025/172215.027:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is disabled, ANGLE is

É possível ativar algum log que consiga detectar porque o VSCode não responde quando clico no Conectar? Se sim, podem me indicar como ativar, por favor?

**Comment by brodao2** [comment]
@elcyferring 

O VS-Code possui três tipos de instalação:
![image](https://user-images.githubusercontent.com/114854608/197887770-7987d3f7-efef-4e96-9e92-dae69d5e2cc1.png)

Recomendo que use _User Installer_ (caso tenha usado outro tipo desinstale o atual antes) e refaça os testes.

Se persistir, verifique junto a seu administrador de rede, se há alguma restrição quanto a execução de processos (_spawn_) a partir de outro e se sim, ele deve liberar o VS-Code como exceção.

Para ativar os _logs_, veja [Gerando logs](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema).

A disposição.

**Comment by danielbolognani** [comment]
Bom dia,
Devido ao tempo sem resposta, estamos fechando esse caso, caso ainda precise de auxilio, favor reabrir com as informações pedidas.
Abraços
