### ISSUE TITLE
Tela Preta Depurar

### ISSUE THREAD

**Issue by GuilhermeGomesBarreto** [totvs/tds-vscode#1039]
Prezados, 

Após a atualização do ambiente, o Protheus está apresentando tela preta ao carregar o menu através do depurar.
Alguém está passando por este problema?
 
Appserver version: 20.3.1.0
Versão da Lib:20221010
TOTVS Developer Studio For VsCode v1.3.15

**Comment by lwtnb-wrk** [comment]
@GuilhermeGomesBarreto Você atualizou o smartclient também? Qual build exata de seu smartclient?
Já estamos investigando esta questão, mas não o reproduzimos localmente.
Se puder dar mais detalhes de como essa tela preta ocorre, pode nos ajudar a identificar o problema para resolvê-lo.

**Comment by GuilhermeGomesBarreto** [comment]
SMARTCLIENT HARPIA VERSAO 12 WINDOWS X64 BUILD 20.3.1.1

Após fazer o login, ao carregar menu apresenta a tela preta.
![tela preta](https://user-images.githubusercontent.com/58429134/197766550-b2d81474-e64f-49ef-b462-2d0108c3e89e.JPG)

**Comment by lwtnb-wrk** [comment]
@GuilhermeGomesBarreto Consegue nos enviar seu appserver.ini ??
Isso ocorre ao entrar em quaisquer modulos??
E se acessar o smartclient sem estar em modo de depuração, o acesso é normal, sem a tela preta correto?

**Comment by GuilhermeGomesBarreto** [comment]
O ambiente está em Clould. 
Acessando smartclient sem estar em modo de depuração, acessa normal.
Está ocorrendo qualquer módulo.

**Comment by lwtnb-wrk** [comment]
@GuilhermeGomesBarreto Você usa algum tipo de monitor diferente? Alta resolução? 4K? 
Usa algum modo de escala diferente de 100% no Windows?

Habilitou o modo de DPI ou OpenGL no launcher? Se possivel nos envie o launcher.json que está utilizando para a depuração.

**Comment by DanielYampolschi** [comment]
@GuilhermeGomesBarreto em complemento ao @leowww , você consegue testar a situação, usando o mesmo binário em algum outro monitor e alguma outra máquina?

**Comment by GuilhermeGomesBarreto** [comment]
Tela 
![configuracoestela](https://user-images.githubusercontent.com/58429134/197777907-a8ea2fea-bac0-40bc-a93a-9b9fea0b8c01.JPG)
23" Full HD

**Comment by GuilhermeGomesBarreto** [comment]
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Begreen_dev",
			"program": "${command:AskForProgramName}",
			"smartclientBin": "C:/SmartClientsCliente/smartclient_BEGREEN_dev/smartclient.exe",
			"cwb": "${workspaceFolder}",
			"isMultiSession": true,
			"enableTableSync": true
		}
	],
	"lastPrograms": [
		{
			"label": "SIGAADV"
		},
		{
			"label": "SIGAMDI"
		},
		{
			"label": "SIGAEST"
		}
	],
	"lastProgramExecuted": "SIGAMDI"
}

**Comment by GuilhermeGomesBarreto** [comment]
Testei direto no notebook tela de 15', com as mesmas configurações de resolução, deu o mesmo problema.

**Comment by lwtnb-wrk** [comment]
@GuilhermeGomesBarreto Grato pelas informações.
Estou testando com várias configurações e não reproduzo o problema, aqui a depuração está ocorrendo normalmente.
Você saberia informar quais eram as versões antes da atualização de seu ambiente??
E se possível consegue voltar ao menos para a versão anterior do Smartclient para ver se o problema deixa de ocorrer?

**Comment by GuilhermeGomesBarreto** [comment]
Vou verificar com pessoal de Cloud, a possibilidade de voltar versão serviço exclusivo.

Estou testando aqui parece ser intermitente, tem horas que tem funcionado, não sei se pode estar havendo algum tipo de concorrência de usuário ou serviço q esteja executando.

**Comment by lwtnb-wrk** [comment]
@GuilhermeGomesBarreto A questão da versão, eu digo do Smartclient Desktop que esta usando para acessar o ambiente na Cloud. Então deve estar instalado no seu notebook.

De qualquer forma se conseguir testar também, pegue essa nova versão SC 20.3.1.2 que geramos por conta de outra questão, mas que temos suspeita que possar ter uma correlação com o problema de depuração. Baixe do link https://tinyurl.com/yyc34x2w e quando requisitado utilize a chave NGXmoNgW

**Comment by danielbolognani** [comment]
Bom dia,
Liberamos uma versão prévia com a correção do caso reportado:
https://github.com/totvs/tds-vscode/releases/tag/v1.3.16-RC3

* Versões RC não são atualizadas de forma automática.
* Sempre mantenha uma cópia de segurança de seu ambientes (VSCode e áreas de trabalho).

Abraços!

**Comment by claudiomirowalter** [comment]
a base é local, o problema acontece somente com o F5 VS ao debugar, com SIGAMDI do protheus, ai precisa ficar tentando algumas vezes ate conseguir

Dados do Server 
Versão: TOTVS Construção e Projetos
Build AppServer: 7.00.210324P-20221005 - 64 bits
Nome do servidor: CLAUDIOMIRO
Sistema operacional: Windows 10
Appserver version: 20.3.1.0
Build DBAccess: 20210202-20220202
Release do RPO:  12.1.033
Release do dicionário: 12.1.033
Local files: CTREE
License server: 2014 - 3.4.3
DB DataBase: MSSQL
DB API Build: 20220303-20221005

Dados do Remote 
Remote build: 7.00.210324P-20221013
Remote version: 20.3.1.1
Remote type: 1 - QT-5.15.9 WIN
Módulo: PON
Nome do computador: CLAUDIOMIRO
Sistema operacional: Windows 10 - 
Memória: 8102
Processador: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz

Versão da Lib:20221010
Data da Lib: 20221031_145231
Commit ID:31e8147922daa92ebb5d738c65b4d863eb60a03d
Central de Atualizações: Sem Dados

**Comment by DanielYampolschi** [comment]
@claudiomirowalter Favor instalar a versão 1.3.16-RC3 enviada pelo Daniel Otto no link acima, onde foi feita uma correção para esse problema

**Comment by claudiomirowalter** [comment]
nao tem a versao para windows ?

**Comment by danielbolognani** [comment]
A versão disponibilizada é multiplataforma, verifique como instalar em:
https://github.com/totvs/tds-vscode/blob/master/docs/install.md

Ou aguarde a liberação oficial na próxima versão.
Abs.

**Comment by claudiomirowalter** [comment]
com essa nova atualizacao o problema foi corrigido

**Comment by GuilhermeGomesBarreto** [comment]
Após a atualização versão v1.3.16-RC3 problema foi corrigido

**Comment by lwtnb-wrk** [comment]
v1.3.16 liberada no Marketplace. Atualizem caso ainda não tenham instalada esta versão.
