### ISSUE TITLE
Ambiente extremamente lento via debug

### ISSUE THREAD

**Issue by Herbert2122** [totvs/tds-vscode#104]
Pessoal o meu ambiente fica extremamento lento executado via Visual Code, quando executo normal fora do visual o ambiente está rodando ok , agora via visual code, eu estou levando cerca de 10 minutos para conseguir fazer o Login no Protheus.

**Comment by ricardomansano** [comment]
Bom dia @Herbert2122 , estamos com uma RC (0.3.11) que vai entrar em testes hj, o @DanielYampolschi  vai te passar uma cópia pra vc testar. Nessa versão mexemos num ponto de performance.
Não era nada critico, pois não tivemos nenhum reporta "grave" como o seu, mas seu teste talvez nos ajude a identificar algum ponto de atenção
Grato,

**Comment by ricardomansano** [comment]
@Herbert2122 , da pra baixar direto do link do RC: https://github.com/totvs/tds-vscode/releases/tag/0.3.11 , baixe o VSIX (tds-vscode-0.3.11.vsix) no rodapé da página.
Pra instalar: Entre na aba Extensions -> Menu superior direito ("...") -> Install from VSIX
Ficamos na escuta,

**Comment by Herbert2122** [comment]
Obrigado Ricardo, vou realizar um teste agora

**Comment by Herbert2122** [comment]
Ricardo não deu certo posso gravar um video?

**Comment by ricardomansano** [comment]
Pode sim, aproveite e mande pfv todos os dados do seu ambiente de AppServer, Smartclient, LIB, isso pode nos ajudar a entender o que esta acontecendo com seu ambiente, ja que não reproduzimos o problema internamente.

Grato

**Comment by Herbert2122** [comment]
Ricardo segue  o link, perceba que fiz um acesso sem debug no servidor de produção, e no ambiente de teste que estou usando e ambos foram ok, quando subi o debug via vscode, ficou a lentidão que eu menciono, que inclusive impede de debugar por conta do tempo: 
Tenta me ajudar pq eu não quero ter que voltar pra extensão antiga 
https://drive.google.com/drive/folders/1slwBgVnm2POqZiuPeYv8_UZUDP0VpmCs?usp=sharing

**Comment by ricardomansano** [comment]
Bom dia novamente, 

Herbert, nós não aconselhamos a depuração do SIGAMDI, ela será lenta em qualquer IDE (Delphi. TDS, VS, etc)
No ambiente MDI abrimos dois environments, um pra servir a tela principal e um pra rotina que esta em uso, o que vai degradar exponencialmente o tempo de depuração, o mesmo vai ocorrer caso precise gravar uma sessão com o TDSReplay.,
Por favor repita o teste usando diretamente o modulo, exemplo SIGAFAT e nos retorne sua impressão

Grato,

**Comment by Herbert2122** [comment]
Ricardo acabei de tentar, e continuou da mesma forma

**Comment by ricardomansano** [comment]
Herbert,

Olhando seu ambiente só o SmartClient esta um pouco antigo (20180928), mas nada que justifique o problema.

As dicas pra ter um ambiente saudável de depuração são:
-Acessar diretamente o módulo
-Acessar um ambiente em modo exclusivo, de preferencia de testes
-Caso seja um ambiente em produção, não deve ter usuários conectados, pois a cada ponto de parada vc vai literalmente travar o AppServer até que solte a depuração
-Verificar as condições da rede, dado grande numero de informações trocados em depuração, muito maior que no uso simples da rotinas. O que no seu caso não parece ser problema ja que o uso da rotina esta fluindo.

Pra gente tirar qqer sombra de duvidas, vc conseguiria clonar seu ambiente de teste pra sua maquina local, e tentar fazer a depuração nesse ambiente?

Isso vai tirar a rede e o acesso exclusivo da equação do problema, pois como lhe comentei não temos relato de lentidão como o que comentou.

Ficamos na escuta,

**Comment by Herbert2122** [comment]
Ricardo me tire uma dúvida agora na compilação de um fonte ele não compila e informa apenas a mensagem , "Recursos de Compilação Finalizado"

**Comment by DanielYampolschi** [comment]
Ola @Herbert2122, quanto a essa mensagem "Compilação de recurso finalizada", realmente ela deve ter ficado por engano em algum teste de alguem, nao deveria estar la e já foi removida. Te agradeço pelo aviso.

Quanto a depuração, apenas complementando as informações no @ricardomansano, no ponto onde seu sistema apresenta lentidão o cliente (No caso o plugin tds-vscode) não tem nenhuma influência, ele está em modo de espera até que um breakpoint seja atingido. Quando inicia uma depuração, tanto o servidor quanto o smartclient entram em um "estado especial" o que causa diferenças de performance em relação a uma execução direta ou modo "Run". Como a no seu caso isso esta excessivo, a suspeita é que exista algo ou no binário do smartclient ou no binário do servidor. Se quiser tirar a dúvida, tente executar uma depuração usando o TDS Eclipse, apontando para o mesmo smartClient e mesmo servidor. Caso exista a mesma lentidão, fica comprovado a nossa suspeita.
Ah, se possível também, envie um print mostrando as extensões que voce tem instaladas no seu VsCode por favor.

Muito obrigado.

**Comment by Herbert2122** [comment]
Daniel debugando pro outros programas como o TDS e o próprio DevStudio o ambiente roda normal  e rápido, infelizmente fui obrigado a voltar para a extensão de terceiros , pois estava atrapalhando minha produtividade.
Fico de um aguardo de uma melhora desse quadro nas próximas versões.

Obrigado pelo apoio @ricardomansano

**Comment by AdminContec** [comment]
Bom dia,

Sei que o post é um pouco antigo, mas estou tendo o mesmo problema do @Herbert2122 
Atendo vários clientes e, somente em 1 cliente ocorre essa lentidão. Nos demais tudo flui normalmente (até mesmo acessando via MDI).
O que ocorre: quando rodo pelo vsCode, ao informar usuário e senha, já começa a lentidão, fica um bom tempo na espera até que aparece a tela de boas vindas. Ao configurar filial e módulo correto (caso necessário), fica mais um bom tempo até acessar o menu, e assim vai. Mais de 2 minutos para conseguir acessar o menu.
Já tentei executar via smartClient de outro cliente e ocorre a mesma coisa, Já tentei acessar via o módulo e tb a mesma coisa.
Menu plugin está atualizado para ultima versão.

@Herbert2122, vc conseguiu descobrir algo?

Grato,

   William

**Comment by lwtnb-wrk** [comment]
@AdminContec Se desejar continuar, abra uma nova issue, pois o problema deve ser outro depois de tanto tempo.

**Comment by brodao2** [comment]
@AdminContec 

Certifique-se que encontra-se com a extensão em sua última versão (2.0.5). Se necessário atualize.
Verifique as [recomendaçoes](https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md#tds-depura%C3%A7%C3%A3o-e-execu%C3%A7%C3%A3o) sobre a depuração.

Caso persista, favor abrir um novo chamado informando os dados solicitados conforme [Informações importantes ao abrir o chamado](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#informa%C3%A7%C3%B5es-importantes-ao-abrir-uma-issue) e anexe os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema).

À disposição.
