### ISSUE TITLE
Compilo programa mas não compila as linhas

### ISSUE THREAD

**Issue by fabiopmota** [totvs/tds-vscode#1040]
Olá,
Estou com seguinte situação. (foi aberto o ticket 15504678 na Totvs)

Quando compila no console log que esta apresentando a seguinte mensagem ao compilar:

[INFO ][SERVER] [Thread 9584] Compiling mfin004.prw
2022-10-21T23:29:46.227435-03:00 9584|MFIN004.PRW:0
2022-10-21T23:29:46.246770-03:00 9584|
[INFO ][SERVER] [Thread 9584] [21/10/2022 23:29:46] Updating RPO.2022-10-21T23:29:46.246833-03:00 9584|

Pelo que eu analisei esta mensagem esta incidando que foi compilado zero linhas.

Se realizar consultas pelo inspetor de objetos o mesmo indica que esta compilado.

-----------------
1 - IXBLOG não está habilitado no Appserver.ini.
2 - No catálogo de personalização antes estava habilitado a customização, porém eu deletei o registro e mesmo assim o problema persistiu.
3 - o RpoCustom está configurado corretamente. Tenho outras customizações que estão funcionando corretamente.
    A customização que estou tentando compilar eu acessava ela normal, mas depois de recompilar, ela não está mais disponível para acessar via menu.

------------------

Hoje ao tentar compilar novamente foi processado com sucesso.
Veja imagem 1 e 2.

Depois realizei mais alguns ajustes no programa e ele voltou a apresentar no consolo zero linhas processadas.
Veja imagem 3

Para os dois casos, no VSCode aparece a seguinte mensagem informando que foi compilado com sucessol

[Info - 18:41:57] Starting build for environment cu32o0_dev.
[Info - 18:41:59] Starting build using RPO token ...
[Info - 18:41:59] Start file recompile.
[Info - 18:41:59] Using Includes: c:/includes_p12
[Info - 18:41:59] Start regular compiling e:/outros computadores/meu laptop/e/workspace/ggepar/mfin004.prw (1/1).
[Info - 18:41:59] [SUCCESS] Source e:/outros computadores/meu laptop/e/workspace/ggepar/mfin004.prw compiled successfully.
[Info - 18:41:59] Committing end build. This could take a while...
[Info - 18:42:00] All files compiled successfully.
[Info - 18:42:00] Recompile finished.

![1 - compilado - 446 linha compiladas](https://user-images.githubusercontent.com/42223351/198089039-6c14c60f-c4b6-48ea-93ba-f3df295c2c0b.png)
![2 - útima linha do fonte](https://user-images.githubusercontent.com/42223351/198089044-3741df70-f063-4fa8-bda1-450817f775ea.png)
![3 - recompilado - zero linha compilada](https://user-images.githubusercontent.com/42223351/198089047-5c58cf73-fbf0-4b28-8e00-d5d0df022037.png)

----------------
Pelo que eu analisei o problema não esta com rotina no menu, visto que se deixo o VSCode fechado por algum tempo e depois acessar ele novamente o fonte é compilado com sucesso.

Segue vídeos com áudio demonstrando as ocorrências.

[Vídeo 2 - Compilado.zip](https://github.com/totvs/tds-vscode/files/9872087/Video.2.-.Compilado.zip)
[Vídeo 1 - não compilado.zip](https://github.com/totvs/tds-vscode/files/9872091/Video.1.-.nao.compilado.zip)

**Comment by lwtnb-wrk** [comment]
@fabiopmota Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para análise.
E nos informe também a build exata do AppServer que esta utilizando. Já está na 20.3.1.0??

**Comment by danielbolognani** [comment]
Bom dia,
Devido ao tempo sem resposta, estamos fechando esse caso, caso ainda precise de auxilio, favor reabrir com as informações pedidas.
Abraços
