### ISSUE TITLE
erros na conexao ao server apos atualizacao para o MACOS Ventura 13.0

### ISSUE THREAD

**Issue by snlacerda89** [totvs/tds-vscode#1041]
---------------------------v---------------------------------------------------
   //////  ////    //////  |  TOTVS Developer Studio for VS-Code
    //    //  //  //       |  Version 1.3.15
   //    //  //  //////    |  TOTVS Technology
  //    //  //      //     |
 //    ////    //////      |  https://github.com/totvs/tds-vscode
---------------------------^---------------------------------------------------

-------------------------------------------------------------------------------
SOBRE O USO DE CHAVES E TOKENS DE COMPILAÇÃO                                   

As chaves de compilação ou tokens de compilação empregados na construção do    
Protheus e suas funcionalidades, são de uso restrito dos desenvolvedores de    
cada módulo.                                                                   

Em caso de mau uso destas chaves ou tokens, por qualquer outra parte, que não  
a referida acima, a mesma irá se responsabilizar, direta ou regressivamente,   
única e exclusivamente, por todos os prejuízos, perdas, danos, indenizações,   
multas, condenações judiciais, arbitrais e administrativas e quaisquer outras  
despesas relacionadas ao mau uso, causados tanto à TOTVS quanto a terceiros,   
eximindo a TOTVS de toda e qualquer responsabilidade.                          
-------------------------------------------------------------------------------
[Info  - 4:26:18 PM] Initializing Language Server.
[Info  - 4:26:18 PM] Language Server initialized.

Loguru caught a signal: SIGSEGV
Stack trace:
14      0x7ff818776c7b thread_start + 15
13      0x7ff81877b259 _pthread_start + 125
12         0x1045c7b9f void* std::__thread_proxy<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct> >, WorkThread::StartThread(std::string const&, std::function<void ()>)::$_0> >(void*) + 63
11         0x1045af1cd std::__function::__func<AdvPLCompleteManager::AdvPLCompleteManager(Project*, WorkingFiles*, std::function<void (std::string, std::vector<lsDiagnostic>)>, std::function<void (lsRequestId)>)::$_1, std::allocator<AdvPLCompleteManager::AdvPLCompleteManager(Project*, WorkingFiles*, std::function<void (std::string, std::vector<lsDiagnostic>)>, std::function<void (lsRequestId)>)::$_1>, void ()>::operator()() + 13
10         0x1045af209 void std::__invoke_void_return_wrapper<void>::__call<AdvPLCompleteManager::AdvPLCompleteManager(Project*, WorkingFiles*, std::function<void (std::string, std::vector<lsDiagnostic>)>, std::function<void (lsRequestId)>)::$_1&>(AdvPLCompleteManager::AdvPLCompleteManager(Project*, WorkingFiles*, std::function<void (std::string, std::vector<lsDiagnostic>)>, std::function<void (lsRequestId)>)::$_1&) + 9
9          0x1045af219 AdvPLCompleteManager::AdvPLCompleteManager(Project*, WorkingFiles*, std::function<void (std::string, std::vector<lsDiagnostic>)>, std::function<void (lsRequestId)>)::$_1::operator()() const + 9
8          0x1045af445 (anonymous namespace)::CompletionPreloadMain(AdvPLCompleteManager*) + 549
7          0x1045c1f77 TotvsLinter::callAdvplC(std::string, std::string, std::string const&, std::vector<lsDiagnostic>&, tAutoArray<ParserSymbol>&) + 3015
6          0x1045e3f85 tAdvplc::run() + 7653
5          0x1045e5fce tAdvplc::doCompile(tSrvDebuggerCmd*, tString&) + 4062
4          0x104622a04 tSrvDebuggerCmd::RMS_DBGCOMPILE(tString&, long double, int, tBinaryBuffer&, unsigned char&, int&, tString&, int&) + 1716
3          0x104abba7d tProgramAbs::compile(char const*, tPublicEnv*, int&, int&, tString&, int, unsigned char, unsigned char) + 1293
2          0x104830d85 AYaccClass::doIt() + 37
1          0x1047eff4f SSYacc::parse() + 255
0                  0x0 4   ???                                 0x0000000000000000 0x0 + 0
(  20.361s) [comp-preload    ]                       :0     | Signal: SIGSEGV
/Users/sergiolacerda/.vscode/extensions/totvs.tds-vscode-1.3.15/node_modules/@totvs/tds-ls/bin/mac/advpls: line 17:  1385 Segmentation fault: 11  "$tmp/$prog" ${1+"$@"}
[Info  - 4:26:18 PM] Connection to server got closed. Server will restart.

**Comment by lwtnb-wrk** [comment]
@snlacerda89 Pela breve descrição do log no console do tds-vscode aparentemente o erro está ocorrendo já na inicialização do tds-vscode, provavelmente com um fonte PRW aberto em um editor, correto?
Tente desabilitar o Linter por enquanto, pois parece ocorre um erro nele. Procure por Linter nas preferencias do tds-vscode e desmarque a opção "Habilitar o Linter"
De qualquer forma veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs gerados para análise.

**Comment by snlacerda89** [comment]
desabilitando o linter até que rolou! Mas de tempos em tempos ele "perde" a conexao com o server e em muitas vezes dá sucesso na compilaçao, mas o fonte nao é compilado.

Ao tentar desconectar e conectar novamente, ele nao vai e dá esse erro no appserver

[INFO ][SERVER] [Thread 4736] [28/10/2022 10:20:23] Starting Debugger (sergiolacerda, MacBook-Pro-de-Sergio.local)
2022-10-28T10:20:25.107000-03:00 4736|
[ERROR][SSL] PEM_read_bio_RSA_PUBKEY error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt2022-10-28T10:20:25.107000-03:00 4736|
[FATAL][SERVER] 28/10/2022 10:20:25[Thread 4736] [THROW] failed to decrypt 2 at file C:\bamboo\xml-data\build-dir\TP11-OF20300-TECXWIN64\lib\security.cpp line 719
2022-10-28T10:20:25.109000-03:00 4736|failed to decrypt 2 in file C:\bamboo\xml-data\build-dir\TP11-OF20300-TECXWIN64\lib\security.cpp at line 719
2022-10-28T10:20:32.003000-03:00 9580|
[INFO ][SERVER] [Thread 9580] [28/10/2022 10:20:32] Starting Debugger (sergiolacerda, MacBook-Pro-de-Sergio.local)
2022-10-28T10:20:33.303000-03:00 9580|
[ERROR][SSL] PEM_read_bio_RSA_PUBKEY error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt2022-10-28T10:20:33.303000-03:00 9580|
[FATAL][SERVER] 28/10/2022 10:20:33[Thread 9580] [THROW] failed to decrypt 2 at file C:\bamboo\xml-data\build-dir\TP11-OF20300-TECXWIN64\lib\security.cpp line 719
2022-10-28T10:20:33.318000-03:00 9808|
[INFO ][SERVER] [Thread  9808] JOB Thread finished [-PSWADMIN]

**Comment by brodao2** [comment]
@snlacerda89 

Favor efetuar as operação sobre geração de log, citada pelo @leowww em mensagem anterior.
Se for esporádico, trabalhe com o log ligado até ocorre a ocorrência.
Anexe-os ao chamado, juntamente com o log de console do server.

No aguardo.

**Comment by snlacerda89** [comment]
Aparentemente se trata da falta do Xcode Command Line Tools, ou de atualizar o mesmo!

Fiz a instalação manual e por enquanto, tá tudo funcionando como deveria.

Habilitei o linter novamente e continuou funcionando

**Comment by lwtnb-wrk** [comment]
@snlacerda89 Ah excelente. Valeu pela informação.
Como se trata de um SO novo, realmente eu nem teria como testar por aqui, pois só tenho Windows 11...
Mas se aparecer outra questão referente ao Ventura já vamos direcionar essa sua solução
