### ISSUE TITLE
Não conecta ao Server

### ISSUE THREAD

**Issue by jadilsonnery** [totvs/tds-vscode#1043]
![image](https://user-images.githubusercontent.com/64595947/201121211-1999053d-71b5-4868-9769-cf5a9437fb97.png)
Baixado a ultimo Server.
O Server abre JOB que não tem chamada no Appserver.ini

**Comment by jadilsonnery** [comment]
Apoe varios minutos aparece a mensagem : Invalid rootUri. Please fix your workspace configuration and try again.

**Comment by jadilsonnery** [comment]
Segue o Appserver.ini : [TOTVSV33H]
SourcePath=E:\TOTVS 12V33H\Microsiga\Protheus\apoH\
RpoCustom=E:\TOTVS\apo-CustomH\custom.rpo
RootPath=E:\TOTVS 12V33H\Microsiga\Protheus_data
StartPath=\system\
x2_path=
RpoDb=top
RpoLanguage=Portuguese
RpoVersion=120
LocalFiles=CTREE
Trace=0
localdbextension=.dtc
PictFormat=DEFAULT
DateFormat=DEFAULT
RegionalLanguage=BRA
DBDATABASE=MSSQL
DBSERVER=192.30.255.12
DBALIAS=HOMOLOGACAO
DBPORT=7890
SpecialKey=HOMOLOGACAO
TOPMemoMega=10
StartSysInDB=1
RepositInDataBase=1
THEME=sunset

[General]
MaxStringSize=500
MaxQuerySize=31960
Consolelog=1
BuildKillUsers=1
;MaxStringSize=10

[Drivers]
Active=TCP
MultiProtocolPortSecure=0
MultiProtocolPort=1
app_environment=TOTVSV33H

[TCP]
TYPE=TCPIP
Port=1288

[LICENSECLIENT]
server=192.30.255.14
port=5555

[TCPSERVER]
Enable=0

[GENTCPIP]
Enable=0

[Service]
Name=TOTVS-Appserver12H-V33
DisplayName=TOTVS | Appserver 12 | HOMOLOGACAO | Versao 12.1.33 | Port 1288

[MAIL]
AUTHLOGIN=1 
AUTHNTLM=1 
;Protocol=POP
Protocol=IMAP
ExtendSMTP=1
TryProtocols=1


[HTTP]
ENABLE=1
;PORT=98
Port=8081
Path=E:\TOTVS 12V33H\Microsiga\Protheus_data\http-root

[ONSTART]


 
;[HTTPV11]
;Enable=1
;Sockets=HTTPREST
 
;[HTTPREST]
;Port=3000
;IPsBind=
;URIs=HTTPURI
;Security=1
 
;[HTTPURI]
;URL=/rest
;CORSEnable=1
;Instances=2,2
;AllowOrigin=*

[localhost:8081/ws]
ENABLE=0
PATH=E:\TOTVS 12V33H\Microsiga\Protheus_data\web\ws
ENVIRONMENT=TOTVSV33H
INSTANCENAME=ws
RESPONSEJOB=JOB_WS_010101
DEFAULTPAGE=wsindex.apw

**Comment by danielbolognani** [comment]
Boa tarde @jadilsonnery 
Parece que vc nao abriu uma pasta/workspace antes de começar a utilizar a extensão.
Se esse não for o caso, e o server já era utilizado anteriormente (cadastrado na extensão), favor cadastrar um novo (pode ser com as mesmas informações) para a extensão detectar a nova versão do appserver.
Se ainda assim não conseguir, garanta que antes de conectar com a extensão você consiga se conectar no ambinete com o Smartclient, se nem com o Smartclient conseguir, ai o problema está no ambiente e não temos como auxiliar por aqui.

Abraços!

**Comment by jadilsonnery** [comment]
@danielbolognani - pasta/workspace antes de começar a utilizar a extensão... O que seria abrir para extensão ?

**Comment by danielbolognani** [comment]
Dentro do VSCode tem a opção "File"/"Open Folder..."
Isso precisa ser feito antes de começar a utilizar a extensão.

**Comment by brodao2** [comment]
@jadilsonnery 

Recomendo a leitura do [Guia Rápido](https://github.com/totvs/tds-vscode/blob/v1.3.16-RC3/README.md#guia-r%C3%A1pido).

**Comment by jadilsonnery** [comment]
> ![imagem](https://user-images.githubusercontent.com/64595947/201121211-1999053d-71b5-4868-9769-cf5a9437fb97.png) Baixado o ultimo Servidor. O Server abre JOB que não tem chamada no Appserver.ini

**Comment by danielbolognani** [comment]
Esse job sobe por padrão no appserver:
https://tdn.totvs.com/pages/viewpage.action?pageId=552580370
