### ISSUE TITLE
Ao Chamar o F5 - SIGAMDI

### ISSUE THREAD

**Issue by jadilsonnery** [totvs/tds-vscode#1045]
Aparece a mensagem : Ao chamar o F5 - SIGAMDI, aparece esta mensagem : Invalid setting. Verify STARTPATH variable in your environment option or verifiy if your file settings (.ini) is corrupted.
Mais chamadno o SIGAMDI fora do VSCode abre normalmente o Protheus.
Ultima Build

**Comment by DanielYampolschi** [comment]
Boa tarde @jadilsonnery.

Isso pode acontecer caso você esteja informando um ambiente que não existe no servidor. 
Por favor confirme se o ambiente que você usa para fazer autenticação no VSCode é o mesmo que você está usando ao chamar o SmartClient diretamente.
