### ISSUE TITLE
Usuario com Active Directory não conecta com o Servidor Protheus

### ISSUE THREAD

**Issue by amgsis** [totvs/tds-vscode#1047]
Acabei de instalar o VSCode e instalei as extensoes da TOTVS.
Utilizamos o AD para conexoes dos usuarios, no vs code nao esta conectando e nao aparece nem uma msgem de erro.

Appserver version: 20.3.1.0
Versão da Lib:20221010
TOTVS Developer Studio For VsCode v1.3.15

**Comment by brodao2** [comment]
Consegue executar o SC?

Favor complementar chamado informando os dados solicitados conforme [Informações importantes ao abrir o chamado](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#informa%C3%A7%C3%B5es-importantes-ao-abrir-uma-issue) e anexe os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)

**Comment by brodao2** [comment]
Fico no aguardo dos logs.

**Comment by amgsis** [comment]
Alan, segue:
veja se e isso mesmo:

 

password.

[Error - 10:42:35] Authentication error: Could not authenticate. Invalid user and/or password.

[Error - 10:42:35] Authentication failed. Could not authenticate to server.

[Info  - 10:46:06] Starting connection to the server 'thega' ***@***.*** ***@***.***> )

[Info  - 10:46:09] Connection to the server 'thega' finished.

[Info  - 10:46:35] Starting user 'ad\marcos.godoi' authentication.

[Info  - 10:46:35] Secure authenticating...

( 409.192s) [querydb         ]  connection_manager.cc:4787  | Authentication error: Could not authenticate. Invalid user and/or password.

[Error - 10:46:38] Authentication error: Could not authenticate. Invalid user and/or password.

[Error - 10:46:38] Authentication failed. Could not authenticate to server.

 

 

 

 

De: Alan Candido ***@***.***> 
Enviada em: quarta-feira, 16 de novembro de 2022 08:57
Para: totvs/tds-vscode ***@***.***>
Cc: amgsis ***@***.***>; Author ***@***.***>
Assunto: Re: [totvs/tds-vscode] Usuario com Active Directory não conecta com o Servidor Protheus (Issue #1047)

 

Fico no aguardo dos logs.

**Comment by brodao2** [comment]
Não é bem isso. Eu preciso é dos arquivos de log.

Olhando o que mandou, no lugar de usar 'ad\marcos.godoi', tente 'marcos.godoi'
Esse usuário é do grupo admin do Siga? Se não for,não é possível usar o TDS-VSCode.

**Comment by amgsis** [comment]
Resolvido:

 

A senha do usuario no Protheus estava diferente da senha do AD.
o VS sempre vai enxergar o ususario do Protheus e não do AD.

 

Obrigado Alan!

 

 

 

De: ***@***.*** ***@***.***> 
Enviada em: quarta-feira, 16 de novembro de 2022 11:39
Para: 'totvs/tds-vscode' ***@***.***>; 'totvs/tds-vscode' ***@***.***>
Cc: 'amgsis' ***@***.***>; 'Author' ***@***.***>
Assunto: RES: [totvs/tds-vscode] Usuario com Active Directory não conecta com o Servidor Protheus (Issue #1047)

 

Usamos o Siga com o active Directory, por isso o AD\
o Usuario esta no grupo de administradores sim...
Quais logs vc pediu?

 

De: Alan Candido ***@***.*** ***@***.***> > 
Enviada em: quarta-feira, 16 de novembro de 2022 10:55
Para: totvs/tds-vscode ***@***.*** ***@***.***> >
Cc: amgsis ***@***.*** ***@***.***> >; Author ***@***.*** ***@***.***> >
Assunto: Re: [totvs/tds-vscode] Usuario com Active Directory não conecta com o Servidor Protheus (Issue #1047)

 

Não é bem isso. Eu preciso é dos arquivos de log.

Olhando o que mandou, no lugar de usar 'ad\marcos.godoi', tente 'marcos.godoi'
Esse usuário é do grupo admin do Siga? Se não for,não é possível usar o TDS-VSCode.

**Comment by danielbolognani** [comment]
Obrigado pelo retorno @amgsis
