### ISSUE TITLE
Compilação com arquivos em pasta google drive mapeada

### ISSUE THREAD

**Issue by mbppatriota** [totvs/tds-vscode#1049]
Boa tarde a todos,

Ao transferir os arquivos fontes para o drive G:, mapeado pelo google drive, ao compilar é apresentado o log :

[Info  - 12:10:16] [SUCCESS] Source m:/meu drive/clientes/zz/fontes/my projects/faturamento/gatilhos/zzz.prw compiled successfully.
[Info  - 12:10:16] Committing end build. This could take a while...
[Info  - 12:10:17] All files compiled successfully.

Mas ao executar a rotina apresenta como não compilada. Para um outro desenvolvedor utilizando o mesmo compartilhamento e mesmo arquivo e atualiza o RPO normalmente, ao compilar apresenta:

**[Info  - 11:42:04] [WARNING] Source m:/meu drive/clientes/zz/fontes/my projects/faturamento/gatilhos/zzz.prw compiled with warnings and/or non fatal errors.**

Reinstalei a extensão TOTVS developer mas não resolveu.

Grato.

**Comment by brodao2** [comment]
Favor complementar chamado informando os dados solicitados conforme [Informações importantes ao abrir o chamado](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#informa%C3%A7%C3%B5es-importantes-ao-abrir-uma-issue) e anexe os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)

**Comment by mbppatriota** [comment]
Desculpe, novo por aqui.
Segue:

VSCODE
Versão: 1.73.1 (user setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Data: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
SO: Windows_NT x64 10.0.19045
Em área restrita: No

Extensão
Changelog
Versão [1.3.15]

Dados do Server 

Versão: TOTVS Serviços
Build AppServer: 7.00.210324P-20211206 - 64 bits
Nome do servidor: 130016-CORE-INS
Sistema operacional: Windows Server 2016
Appserver version: 20.3.0.4
Build DBAccess: 20210202-20220202
Release do RPO:  12.1.033
Release do dicionário: 12.1.033
Local files: ctree
License server: 2014 - 3.4.3
DB DataBase: MSSQL
DB API Build: 20210202-20210930

Versão da Lib:20220502
Data da Lib: 20220426_1072
Commit ID:8b6c08f36d0ad6ca27ba15b8a4f19534898c3ce9
Central de Atualizações: 2680900 (06/10/2022)

**Comment by brodao2** [comment]
E os arquivos de Log?
"e anexe os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)"

**Comment by mbppatriota** [comment]
[totvsls.log](https://github.com/totvs/tds-vscode/files/10043796/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/10043797/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/10043798/totvsls_out.log)

**Comment by brodao2** [comment]
@mbppatriota 

Pelos logs, não é possível identificar qualquer anormalidade.

Por experiência, usar o drive do google (ou qualquer outro semelhante) é possível, pode ocorrer de no mesmo momento que a extensão precise do arquivo, o processo de sincronização esta usando o mesmo. Sugiro utilizar sincronização manual, principalmente se houver compartilhamento com terceiros. 

Qualquer nova informação, reabra o chamado.

A disposição.

**Comment by mbppatriota** [comment]
Boa tarde,

Desculpe não ter retornado. Mas foi necessário mudarmos a cfg do drive de streaming para espelhamento, desta forma houve a compilação e atualização.

Grato pela ajuda.
