### ISSUE TITLE
Debug Console configuração visual

### ISSUE THREAD

**Issue by Smmartinez** [totvs/tds-vscode#105]
Boa tarde! Alguém já conseguiu configurar esse tema?

**Comment by lwtnb-wrk** [comment]
@Smmartinez Desculpe mas qual é a questão?

**Comment by Smmartinez** [comment]
![rerere](https://user-images.githubusercontent.com/4532855/60736309-e1f7c680-9f2c-11e9-85fc-e66727104a4c.png)

Pelo que entendi ele mudar as cores do debug certo? mas Não consigo fazer mudar seguindo o exemplo.

**Comment by brodao** [comment]
Ola @Smmartinez 

A intenção é mudar as cores da mensagem conforme seu nível. Fiz uns testes aqui e ocorreu seu problemas.
Favor encaminhar para meu e-mail o seu arquivo de configurações.

No aguardo.

**Comment by ricardomansano** [comment]
Boa tarde @Smmartinez,

Dado o tempo sem interação creio que o processo foi resolvido.

Muito grato pela interação,
