### ISSUE TITLE
Não foi possível abrir o editor devido a um erro inesperado: O arquivo é um diretório

### ISSUE THREAD

**Issue by EduardoRosseti** [totvs/tds-vscode#1050]
Bom dia a todos, esporadicamente aparece esse problema no VSCODE, queria saber se sabem de algo.

![image](https://user-images.githubusercontent.com/47615694/202849396-1961ee99-ada4-4e36-8d1c-66e3697ab0e9.png)

E também estou com um problema nos servidores, mesmo estando conectado na parte inferior do VSCODE mostra para selecionar o servidor e ambiente. Caso precisem de mais informações estou a disposição.

![image](https://user-images.githubusercontent.com/47615694/202849521-9ee5e8da-f6dc-48be-8813-cef50925f5e2.png)

**Comment by brodao2** [comment]
@EduardoRosseti 

Verifique se o VS-Code e a extensão TDS-VSCode estão atualizados.

Como é esporádico, trabalhe com a geração de logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema).

Ao ocorrer o problema, anexe os logs (incluindo do servidor).

No aguardo.

**Comment by EduardoRosseti** [comment]
VSCODE
Versão: 1.73.1 (user setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Data: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
SO: Windows_NT x64 10.0.18362
Em área restrita: No

Extensão
Changelog
Versão [1.3.15]

Dados do Server

Versão: TOTVS Manufatura
Build AppServer: 7.00.210324P-20220608 - 64 bits
Nome do servidor: MFNSCPSR006
Sistema operacional: Windows Server 2012
Appserver version: 20.3.0.10
Build DBAccess: 20210202-20220701
Release do RPO:  12.1.033
Release do dicionário: 12.1.033
Local files: ctree
License server: 2014 - 3.3.3
DB DataBase: ORACLE
DB API Build: 20210202-20220701

Versão da Lib:20220613
Data da Lib: 20220608_165254
Commit ID:22b712221d807e0ebd799c3721c4aa328614bd78
Central de Atualizações: 3053288 (21/11/22)

[dap.log](https://github.com/totvs/tds-vscode/files/10057051/dap.log)

Infelizmente não consegui gerar os outros arquivos, mesmo colocando as informações conforme solicitado no settings.json

![image](https://user-images.githubusercontent.com/47615694/203072084-98516194-bee1-48c7-8259-a418ea66441a.png)
