### ISSUE TITLE
TDS _ Replay C2090 File not found *******.CHLinter 

### ISSUE THREAD

**Issue by wmorais1993** [totvs/tds-vscode#1052]
Ao carregar o arquivo no TDS - Replay ocorre a mensagem "C2090 File not found *******.CHLinter interrompendo o carregamento do arquivo, sendo assim não apresentando os fontes no "TDS Replay TimeLineView".

Foi verificado o Launch.json foi visto o caminho do Include pelo Ctrl + Shift + P, foi realizado o testes com outros arquivos de Replay e ainda ocorre a mensagem 

Configuração do Launch.json;

                    "type": "totvs_tdsreplay_debug",
			"request": "launch",
			"cwb": "${workspaceRoot}",
			"ignoreSourcesNotFound": true,
			"name": "Replay_padrão",
			"tdsReplayFile": "C:\\A\\replay_20221130_114121_without_lib\\replay_20221130_114121_without_lib.trplay",
			"password": "",
			"includeSources": "*",
			"excludeSources": ""

**Comment by DanielYampolschi** [comment]
Ola @wmorais1993, 
essa situacao é bastante estranha... quando voce diz "carregar o arquivo do TDS Replay", quer dizer, "ao finalizar a importaçao?"

Voce pode me enviar esse replay e o fonte para tentar reproduzir localmente por favor?

**Comment by DanielYampolschi** [comment]
Alias @
