### ISSUE TITLE
Debug no sigaloja

### ISSUE THREAD

**Issue by josenovaes** [totvs/tds-vscode#1053]
Bom dia.

Li o chamado Debug Sigaloja #862 e configurei o server conforme orientado, porém ao executar o debug recebo a mensagem: Falha de conexão com o ECF.

Quando executo via smartclient pelo atalho do Protheus não aparece a mensagem.

C:\SMARTCLIENT12.33\smartclient.exe -A -A=03B -P=SIGAADV -C=HOMOLOG -E=KS_HOM

Criei o server no vscode utilizando o ip e a porta da conexão HOMOLOG e configurei o ambiente como KS_HOM

Ao executar a depuração digito sigaloja("03B") de acordo com o exemplo do chamado Debug Sigaloja #862, preencho usuário e senha (usuário é caixa, o mesmo que eu uso no acesso pelo smartclient) e já vem a mensagem.

Alguma dica?

**Comment by lwtnb-wrk** [comment]
@josenovaes A principio executar SIGALOJA("03B") me parece correto...
Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie o log para analise. Em especial o dap.log

**Comment by lwtnb-wrk** [comment]
@josenovaes Poderia fazer um teste tambem e chamar SIGALOJA("","03B") passando o 1o parametro vazio para ver se faz diferenca no seu caso?

**Comment by josenovaes** [comment]
Vou verificar o link.

Informações adicionais:
![versão_vscode](https://user-images.githubusercontent.com/51204354/205079298-63b78383-c46f-41bf-96c1-d29dfcc0b962.png)

Versão TOTVS Developer Staudio 1.3.15

**Comment by josenovaes** [comment]
SIGALOJA("","03B") também não deu certo. Mesma mensagem. Vou ver se gero os
logs

Em qui., 1 de dez. de 2022 às 11:29, lwtnb-wrk ***@***.***>
escreveu:

**Comment by josenovaes** [comment]
Resolvido.

Retirei a linha abaixo do lauch.json e funcionou

"programArguments": ["${command:AskForProgramArguments}"],

**Comment by lwtnb-wrk** [comment]
@josenovaes Grato pela informação. Vamos analisar aqui com base nesta sua informação.
