### ISSUE TITLE
Desfragmentação rpo padrão binário Harpia

### ISSUE THREAD

**Issue by Adailton-lanca** [totvs/tds-vscode#1054]
Qual o procedimento para desfragmentar o rpo padrão no binário Harpia?
Quando utilizo opção de desfragmentação, incide apenas no rpo custom.

**Comment by lwtnb-wrk** [comment]
@Adailton-lanca Esse procedimento é de responsabilidade do AppServer. Nos do tds-vscode, apenas enviamos o comando para que ele inicie.
Se a questão for o tamanho do RPO que não está diminuindo apos a desfragmentação, houveram mudanças no processo por questoes de seguranca. Mas tambem tivemos uma ocorrencia em uma das versoes do AppServer, então se ela nao estiver atualizada, veja se consegue atualiza-la.
