### ISSUE TITLE
Warning Compilação

### ISSUE THREAD

**Issue by suportecol** [totvs/tds-vscode#1055]
Bom dia, 
Podem nos ajudar com o alerta de compilação abaixo: 
'W0008 Too few parameters calling valtypecompile'
Fizemos conforme a documentação padrão(https://tdn.totvs.com/display/public/framework/FwBrowse) e não conseguimos identificar a falta de parâmetros.
Anexo o print do trecho do fonte. 
Obrigado.
![warning_compilacao](https://user-images.githubusercontent.com/57305813/207122406-283259ce-5258-47ee-9a81-ac5f7765b33e.png)

**Comment by brodao2** [comment]
Ola @suportecol 

Esses comandos que emitiram esse aviso, são definições de comandos AdvPL, efetuados em arquivos de definição (.ch). 

Solicito que faça uma atualização dos arquivos de definições padrão (os includes) e caso o problema persista, entre em contato com o suporte AdvPL.

A disposição.

**Comment by ricardomansano** [comment]
Bom dia,
Caso o problema persista após a atualização dos arquivos CH, pfv nos procure
