### ISSUE TITLE
Modo Tds Replay Simplificado*

### ISSUE THREAD

**Issue by carlosaugustoemp** [totvs/tds-vscode#1057]
Bom dia. Em conversa com Daniel Motta Yampolschi /Fabiana Soares da Silva via reunião meet para verificar dificuldades para importar um arquivo TDS Replay, sugerimos ao Daniel uma visualização simplificada do Replay demonstrando a lista dos fontes no arquivo. Essa sugestão ajudará os analistas que precisam apenas das datas dos fontes executados no processo (programas padrão, se existem programas customizados, etc).

Como exemplo, no ERP Datasul, é possível gerar um arquivo .txt com todos fontes executados no processo, facilitando a visualização dos programas executados sem ter que usar outra ferramenta. 
Teria como fazer um ajuste no TDS para simplificar a visualização dos fontes executados pelos clientes? Essa funcionalidade será utilizada pelo atendimento sem ter a necessidade de abrir todo o arquivo do replay e demais configurações para o debug.

**Comment by Fabianasoaresdasilva** [comment]
Caso de dúvidas, por favor me acionar via chat ou fabiana.soares@totvs.com.br

Obrigada!

**Comment by DanielYampolschi** [comment]
Apenas um reforço, conforme conversamos. 
A idéia é ter uma opção no Replay que apenas verifique os fontes que foram envolvidos nessa execução, sem fazer todo o processo de importação, o que economizaria tempo de espaço em disco.

**Comment by Fabianasoaresdasilva** [comment]
Isso mesmo Daniel.

Obrigada!

**Comment by DanielYampolschi** [comment]
Essa nova funcionalidade foi implementada e estará disponível a partir da versão 1.3.18 do plugin tds_vscode.
Caso queira testar/experimentar, baixe e instale o arquivo VSIX da versão 1.3.18-RCx que será liberada em breve pelo link:
https://github.com/totvs/tds-vscode/tags

A documentação foi atualizada com a nova funcionalidade pelos links abaixo:
Tela: [totvs_tdsreplay_debug](https://github.com/totvs/tds-vscode/wiki/TDS-Replay#tela-do-executor)
Campos: https://github.com/totvs/tds-vscode/wiki/TDS-Replay#campos-do-executor
