### ISSUE TITLE
Regras advpl do sonarqube (codeanalysis) direito no vscode

### ISSUE THREAD

**Issue by nicociri** [totvs/tds-vscode#1058]
E possivel?

o site do codeanalysis e legal, mas ele e util cuando o fonte ja foi desenvolvido! Seria legal poder atrapalhar esses falhas de qualidade no momento que eles ocorrem: na janela do desenvolvedor!
Ja existe um plugin pra vscode do sonar (sonarlint) para java, js, c, c++ e outros lenguajems...  a tecnologia necesaria ja esta disponivel...

saludos de Argentina

**Comment by lwtnb-wrk** [comment]
@nicociri Grato pela sugestão, mas essa questão do codeanalysis é mantida por um outro time de Engenharia.
Durante o desenvolvimento no tds-vscode o Linter apresentará informações que podem ajudar antes de compilar o fonte no RPO que poderá apresentar outras informações.
Mas o uso do codeanalysis por enquanto é somente pelo site deles. Caso ache conveniente abra uma sugestão de melhoria para o codeanalysis.
