### ISSUE TITLE
Gerar patch a partir de uma pasta

### ISSUE THREAD

**Issue by antunesls** [totvs/tds-vscode#106]
Ao gerar uma patch com a função "Patch generation (From folder)" , ele esta levando os arquivo ocultos da pasta .git dentro da patch ao inves de considerar apenas os arquivos .prw/.prx .

**Comment by lwtnb-wrk** [comment]
@antunesls Realmente a geração de patch por pasta pega todo o conteudo dela e nao teriamos como adivinhar se o usuario quer incluir ou nao uma determinada pasta como a .git.

Acho que poderia ser criada uma configuracao de exclusao de padroes a serem aplicadas neste caso.

Se quiser implementar essa configuracao e filtrar a lista de fontes a serem incluidas no patch, por favor, submeta um Pull Request que iremos analisar

**Comment by antunesls** [comment]
Enviado o PR.

**Comment by lwtnb-wrk** [comment]
@antunesls Vi sua PR mas temos algumas ressalvas. Voce optou por implementar atraves de um filtro de inclusao de extensoes conhecidas, mas nao sei se isso limita muito o que sera incluido no patch.
De qualquer forma essa lista deveria ser configuravel atraves de alguma opcao nos "Settings" do tds-vscode para que atenda a necessidade de outros usuarios tambem. 
Se um outro usuario quiser, por exemplo, incluir arquivos PDFs ele devera poder adicionar nas configuracoes que as extensoes .pdf fossem incluidas no patch.
Por essas questoes recusaremos a PR #113 mas caso queira submeter uma nova PR analisaremos novamente. Grato pela ajuda.

**Comment by antunesls** [comment]
Gerada uma nova PR com a opção de customizar as extensões por settings.json do workspace.

**Comment by brodao** [comment]
Ola @antunesls 

Fiz um ajustes trocando a propriedade de string para array. Fica mais claro a edição.

Grato pela colaboração.
