### ISSUE TITLE
Erro (-1):Falha ao iniciar o SmartClient. Comando: E:\TOTVS 12V2210\Microsiga\Protheus\bin\smartclient\smartclient.exe

### ISSUE THREAD

**Issue by jadilsonnery** [totvs/tds-vscode#1060]
# Podem me ajudar ?.
![image](https://user-images.githubusercontent.com/64595947/209805641-1c5bca87-a374-45d4-a1d8-cecff1751de3.png)

## Reinstalado o VSCode e extensão, executado como Administrador
Pego a mesma instrução da imagem e coloco no Atalho e funciona.

Qual é a solução ?

**Comment by jadilsonnery** [comment]
Segue o launch.json
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Depuração do idioma TOTVS",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "E:\\TOTVS 12V2210\\Microsiga\\Protheus\\bin\\smartclient\\smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true
		}
	],
	"lastPrograms": [
		{
			"label": "SIGAMDI"
		}
	],
	"lastProgramExecuted": "SIGAMDI"
}

**Comment by lwtnb-wrk** [comment]
@jadilsonnery Creio que seja o mesmo problema ja reportado na #1059 
Enquanto não sair a correção, apenas coloque seu Smartclient em uma pasta sem espaços. (por exemplo "TOTVS_12V22" ao inves de "TOTVS 12V22").

**Comment by jadilsonnery** [comment]
Obrigado pela ajuda...

**Comment by lwtnb-wrk** [comment]
duplicate #1059
