### ISSUE TITLE
Debug não para - Ou Seja - Não está parando nos pontos de interrupção

### ISSUE THREAD

**Issue by jadilsonnery** [totvs/tds-vscode#1061]
Por favor, podem ajudar ?

Segue o Dap.log que acabei de gerar.
[dap.log](https://github.com/totvs/tds-vscode/files/10314215/dap.log)
Precisa de algum outro log ?

**Comment by lwtnb-wrk** [comment]
@jadilsonnery Você está iniciando o Debug com F5 mesmo? 
Pelo log aparentemente você está executando o programa (CTRL+F5) ao inves de depurando o programa (F5)...

**Comment by jadilsonnery** [comment]
Desculpe a bobeira... Estava digitando (CTRL+F5) no automático.... Obrigado pela ajuda.
