### ISSUE TITLE
Erro ao instalar Extensão TDS - EPERM:

### ISSUE THREAD

**Issue by AlissonEF** [totvs/tds-vscode#1064]
Ao instalar o TDS na máquina local aparece o erro abaixo, não consigo instalar de nenhum jeito, será que é um erro de permissão para instalar a extensão ?, estou usando o usuário de admin e executando o VScode como administrador.

![erro VSCODE EPERM](https://user-images.githubusercontent.com/95551582/210375341-71845aa3-1011-4de0-bfac-18fd8a681c8b.jpg)

**Comment by lwtnb-wrk** [comment]
@AlissonEF Os erros apresentados não parecem ter relação com a extensão do tds-vscode. As vezes a questão é exatamente relacionada a instalar o VS Code como Administrador.
Se possível desinstale o VS Code _e_ remova/renomeie (caso deseje manter como backup) as pastas associadas as extensões do VS Code abaixo:
> C:\Users\<seu usuário>\.vscode
> C:\Users\<seu usuário>\AppData\Roaming\Code
Certifique-se que após a desinstalação a pasta abaixo não exista mais
> C:\Users\<seu usuário>\AppData\Local\Programs\Microsoft VS Code
E reinstale o VS Code sem utilizar a opção "Executar como Administrador" e depois instale a extensão tds-vscode novamente.

**Comment by AlissonEF** [comment]
@lwtnb-wrk apenas a extensão do TDS apresenta esse erro, qualquer outra extensão consegue ser instalada normalmente. Será que esse procedimento neste caso funcionaria ?

**Comment by lwtnb-wrk** [comment]
@AlissonEF Ah entendi. Possivelmente sim, pois a extensão tds-vscode precisa executar um arquivo binário (LSP) e já tivemos no passado, com outros produtos, essa questão de permissão de execução por uma instalação/execução de um usuário Administrador.
O Windows possui restrições de execução de binários, e outras ações, por usuários/instalações feitas por Admin. Então existe sim a possibilidade de que ao reinstalar o VS Code *sem ser como Admin*, a extensão possa ser instalada e funcione corretamente.
Se puder e fizer este procedimento, peço que nos informe se funcionou, pois nesse caso, adicionaremos essa restrição nas notas de instalação e evitaremos que outros usuários passem por essa situação.

**Comment by AlissonEF** [comment]
Desinstalei o vscode e me certifiquei de que a pasta C:\Users<seu  usuário>\AppData\Local\Programs\Microsoft VS Code não existisse mais, instalei novamente o vscode e na sequência tentei instalar também o TDS, porém sem sucesso... segue o erro evidenciado abaixo.

OBS: aparentemente é o mesmo erro que teve da ultima vez.
![erro TDS ](https://user-images.githubusercontent.com/95551582/210426542-90667a4d-bb2d-4f54-8015-5125f048652a.jpg)

**Comment by danielbolognani** [comment]
Aparentemente algo em uso no windows está causando o erro na instalação. Tem alguma outra extensão instalada antes da extensão TDS-VSCode?
Veja mais em:
https://stackoverflow.com/questions/58707277/vs-code-error-eperm-operation-not-permitted

Nota: Isso não é um problema com a extensão, é alguma permissão entre acesso aos arquivos e o vscode em si.

**Comment by AlissonEF** [comment]
Tem outra extensão instalada sim, a Carol BigQuery, consegui instalar ela normalmente...


![addb3150-84e5-4ac8-af00-3b53e15765c4](https://user-images.githubusercontent.com/95551582/210429756-135dca1a-e72c-4ede-bc37-5e84fd8f30cf.jpg)

**Comment by brodao2** [comment]
Não sei se pode ajuda, mas eu instalei o NodeJS com um usuário e apesar de outro usuário conseguir executar algumas comandos, outros dava erro. Removi o NodeJS do 1o usuário e reinstalei no 2o.

Você instalou o VSCode no mesmo usuário logado do Windows? 
Instalou a versão correta? Repare que tem 2 tipos associados a usuários.

![image](https://user-images.githubusercontent.com/114854608/210430362-d4c0d175-8023-4b62-a0a6-beef03e9e69f.png)

**Comment by AlissonEF** [comment]
tentei instalar dos dois jeitos... tanto o User Installer quanto o System Installer e ambos apresentaram o mesmo erro

**Comment by lwtnb-wrk** [comment]
@AlissonEF Voce tem anti-virus instalado nessa maquina? Se afirmativo, poderia fazer um teste, desligando temporariamente ele ao tentar instalar a extensao tds-vscode? Isso pode nos ajudar a entender se algum programa barrando a instalacao por algum motivo...

**Comment by AlissonEF** [comment]
testei desativar o anti-virus e instalar mas também não tive sucesso... o erro permanece mesmo assim.

**Comment by lwtnb-wrk** [comment]
@AlissonEF Seu problema é bastante estranho, e é a primeira vez que isso está sendo relatado, então também não sabemos o que pode estar ocorrendo. 

Provavelmente algum tipo de configuração e/ou software instalado em seu ambiente esteja impedindo a instalação/execução de um script que o tds-vscode usa. De acordo com os screenshots trata-se do performance-now. Esse módulo deve ser usado por algum módulo que usamos, pois não o usamos diretamente.

Seu ambiente é um Windows 10/11? 
Está em algum domíno de rede corporativo com possíveis restrições de segurança/instalação de softwares? 
Que tipo de anti-virus utiliza? 
Instalou o VS Code no local padrão sem alterá-lo e sem usar a opção "Executar como Administrador"?
Tentou instalar usando um outro usuário?
Tem outra máquina para instalar e comparar as instalações?

**Comment by DanielYampolschi** [comment]
@AlissonEF sei que vc já tentou reinstalar, mas queria te pedir um outro teste também, caso os testes com outro usuário não funcionem. 

1 - Desinstale o VsCode novamente
2 - Apague a pasta "**.vscode**" localizada em C:\Users\<Seu usuario>\
3 - Clique com o botão direito no instalador do VSCode -> Propriedades -> Aba Compatibilidade -> Garanta que o checkbox: "Executar este programa em modo de compatibilidade" esteja **desmarcada**.
4 - Reinstale o VsCode, como ja dito pelo Leo, **sem usar a opção de executar como administrador**
5 - Execute o VsCode **sem usar a opçao de executar como administrador**
6 - Tente instalar o plugin do tds_vscode.
7 - Caso ainda apresente o problema, baixe o VSIX do link abaixo e tente instalar por ele por favor.

https://github.com/totvs/tds-vscode/releases/tag/v1.3.17-RC0

PS: Imagino que voce já conheça os passos, mas estou apenas reforçando pra nao ficar nenhuma duvida.

**Comment by AlissonEF** [comment]
@lwtnb-wrk Estamos instalando a extensão TDS no VScode no Windows Server 2016. Tentei as tratativas informadas acima, mas nenhuma deu certo.

**Comment by brodao2** [comment]
Conforme documentação [_Requirements_](https://code.visualstudio.com/docs/supporting/requirements) o VSCode não esta homologado para plataformas "server.

**Comment by lwtnb-wrk** [comment]
@AlissonEF Ah, então deve ser isso mesmo. Por algum motivo achávamos que seu SO era um Windows 10 ou 11.
Veja que em https://github.com/totvs/tds-vscode/blob/master/docs/install.md temos os requisitos para funcionamento do tds-vscode. Os Windows Servers não são homologados para o uso do VS Code e portanto não funcionam adequadamente com o tds-vscode. Os Windows Servers não possuem todas as DLLs necessárias para uso de um IDE como o VS Code.

**Comment by AlissonEF** [comment]
Senhores, muito obrigado! consegui instalar a extensão em uma máquina local... o erro era este mesmo= instalar em uma maquina com o SO Windows Server.

Problema solucionado.
:)

**Comment by lwtnb-wrk** [comment]
@AlissonEF Excelente! Que bom que esclarecemos isso, pois nós também estávamos tentando entender esse problema.
Se tivéssemos perguntado do SO desde o início teria sido mais fácil.
