### ISSUE TITLE
VSCODE - Error(-1);Falha ao iniciar o smartclient 

### ISSUE THREAD

**Issue by fabiopedroza** [totvs/tds-vscode#1065]
"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Depuração do idioma TOTVS",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "E://Totvs//Smartclient_Clientes//P33 SIG SMARTCLIENT//smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true,
			"enableMultiThread": true
		}

Já tentei colocar das formas abaixo, mas não funcionou, todos dão o mesmo erro da descrição.

"smartclientBin": "E:\\Totvs\\Smartclient_Clientes\\P33 SIG SMARTCLIENT\\smartclient.exe",

"smartclientBin": "E:\Totvs\Smartclient_Clientes\P33 SIG SMARTCLIENT\smartclient.exe",

"smartclientBin": "E:/Totvs/Smartclient_Clientes/P33 SIG SMARTCLIENT/smartclient.exe",

"smartclientBin": "E://Totvs//Smartclient_Clientes//P33 SIG SMARTCLIENT//smartclient.exe",
![VSCODE ERROR ](https://user-images.githubusercontent.com/59176849/210436678-1168a5f9-5496-440e-abfb-85f437b31a63.png)

**Comment by lwtnb-wrk** [comment]
duplicada #1059
