### ISSUE TITLE
Declaração de variável não fica em destaque

### ISSUE THREAD

**Issue by Smmartinez** [totvs/tds-vscode#1066]
Bom dia!
A versão 1.3.17-RC1 não esta destacando a declaração de variveis, por exemplo Local Private.

estou enviando print das telas para analise.

É frescura mas ajuda bastante.
![tela2](https://user-images.githubusercontent.com/4532855/210772598-9f361472-43ed-4d1e-b85c-e9af95998185.png)
![tela1](https://user-images.githubusercontent.com/4532855/210772603-8af0b953-27f6-4cf8-811c-4f4d186ce284.png)

**Comment by brodao2** [comment]
Ola @Smmartinez 

Foi um efeito colateral de outro chamado e já foi resolvido. 
Favor aguardar um novo RC.

**Comment by Smmartinez** [comment]
Bom dia Alan,

Que bom fico no aguardo.


Att.
Sergio Martinez Martinez
 
 



De: "Alan Candido" ***@***.***>
Enviada: 2023/01/05 08:45:18
Para: ***@***.***
Cc:  ***@***.***, ***@***.***
Assunto:  Re: [totvs/tds-vscode] Declaração de variável não fica em destaque (Issue #1066)
 

 

Ola @Smmartinez

Foi um efeito colateral de outro chamado e já foi resolvido.
Favor aguardar um novo RC.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/totvs/tds-vscode/issues/1066#issuecomment-1372114795", "url": "https://github.com/totvs/tds-vscode/issues/1066#issuecomment-1372114795", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by lwtnb-wrk** [comment]
@Smmartinez Geramos a Pré Release v1.3.17-RC2 que deve corrigir as formatações que foram perdidas. https://github.com/totvs/tds-vscode/releases/tag/v1.3.17-RC2
Agradecemos se puder validar e confirmar se está tudo de acordo.

**Comment by Smmartinez** [comment]
Boa tarde!

Com essa versão esta ok.


Att.
Sergio Martinez Martinez
 
 



De: "lwtnb-wrk" ***@***.***>
Enviada: 2023/01/06 13:52:14
Para: ***@***.***
Cc:  ***@***.***, ***@***.***
Assunto:  Re: [totvs/tds-vscode] Declaração de variável não fica em destaque (Issue #1066)
 

 

@Smmartinez Geramos a Pré Release v1.3.17-RC2 que deve corrigir as formatações que foram perdidas. https://github.com/totvs/tds-vscode/releases/tag/v1.3.17-RC2
Agradecemos se puder validar e confirmar se está tudo de acordo.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/totvs/tds-vscode/issues/1066#issuecomment-1373887995", "url": "https://github.com/totvs/tds-vscode/issues/1066#issuecomment-1373887995", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by lwtnb-wrk** [comment]
liberada versão 1.3.17 que deve resolver esta questão, favor atualizar a extensão e caso necessário abra uma nova issue
