### ISSUE TITLE
onde trocar ou encontrar o machine id

### ISSUE THREAD

**Issue by viniciusgati** [totvs/tds-vscode#1067]
**Describe the bug**
Usando linux, na extensão tenho o seguinte machine id: 
![image](https://user-images.githubusercontent.com/60268/210778001-c0adc6a9-6501-4eaf-9292-3d7daab57419.png)

De onde vem esse valor? preciso muda-lo pois só tenho a chave de minha máquina antiga, no windows usamos VolumeId mas e no linux?

**Comment by lwtnb-wrk** [comment]
@viniciusgati As chaves de compilação funcionam apenas na máquinas para a qual foram designadas. Ou seja, sua chave vale apenas para a do Windows. 
Se quiser usar em seu Linux, requisite uma nova chave informando esta nova ID.
