### ISSUE TITLE
Identação Case em query

### ISSUE THREAD

**Issue by robsonrosilva** [totvs/tds-vscode#107]
Quando utilizo um Case dentro de um BeginSql ele está bagunçando a identação do Case.
Segue em anexo o arquivo.
[PXCSAR03.zip](https://github.com/totvs/tds-vscode/files/3360122/PXCSAR03.zip)

**Comment by lwtnb-wrk** [comment]
@robsonrosilva Vamos avaliar o problema. Grato por avisar.
