### ISSUE TITLE
Arquivos TRES

### ISSUE THREAD

**Issue by alexandro102021** [totvs/tds-vscode#1071]
Bom dia, 

Abri um chamado na TOTVS e não tiraram a minha duvida.

Gostaria de saber sobre os arquivos que vieram junto de um rotina IMPFER.PRX com vários .tres isso eu compilo ou jogo na pasta dos includes?

Grato
Alexandro

**Comment by lwtnb-wrk** [comment]
@alexandro102021 Realmente não saberemos informar, aguarde posicionamento da TOTVS pelo chamado. 
Aqui tratamos apenas de dúvidas relacionadas a extensão tds-vscode.  
Abraço

**Comment by danielbolognani** [comment]
Arquivo *.TRES normalmente é um "resource" de tradução e deve ser compilado (não é um include). Porém como o @lwtnb-wrk comentou, aqui não temos como tirar esse tipo de dúvida e o melhor seria um posicionamento do próprio time que disponibiliza essa rotina IMPFER.PRX
Abraços!
