### ISSUE TITLE
erro ao debugar de Propriedades de Classes 

### ISSUE THREAD

**Issue by ricardohmlsp** [totvs/tds-vscode#1072]
Olá Pessoal notei que ao tentar debugar uma propridade no VScode o mesmo me apresenta erro caso eu 
tente escrever com apenas :: 

Exemplo 
Tenho a Proriedade abaixo:

PRIVATE DATA aDados as Array

quando vou debugar a propriedade no vscode dessa forma ::aDados , ele nao localiza os dados tanto no debug quanto no watch
agora se eu escrevo self:aDados ai ele se comporta de maneira normal.

É natural ao debugar precisar escrever self nao podendo usar o ::?

Porem isso ocorre com os tipos array e object apenas.

Abraço a todos

**Comment by lwtnb-wrk** [comment]
@ricardohmlsp Grato por reportar essa questão. 
Conseguimos reproduzir e já estamos averiguando.

**Comment by lwtnb-wrk** [comment]
@ricardohmlsp Geramos uma versão Pre Release https://github.com/totvs/tds-vscode/releases/tag/v1.3.17-RC4 que deve corrigir este problema. https://github.com/totvs/tds-vscode/blob/master/docs/install.md
Se puder testar e validar a correcao, nos avise se estiver tudo certo ou ainda tem algum ponto a ser verificado.
