### ISSUE TITLE
Formatação Annotation REST TL++

### ISSUE THREAD

**Issue by vitor-gabriel** [totvs/tds-vscode#1073]
**Describe the bug**
No tlpp, as annotations de metodos HTTP, estão com cores diferentes, alem da formatação vir desformatada

**To Reproduce**
1. Crie um fonte tlpp
2. Crie um linha com a seguinte sintaxe: @GET('')
3. Crie uma linha abaixo com a seguinte sintaxe: @POST("")

**Expected behavior**
Todos os metodos HTTP terem a mesma cor e formatação.

**Screenshots**
![image](https://user-images.githubusercontent.com/62556013/212324179-7916a9a8-7c40-42e7-9ff6-da5ce6c782bb.png)

**Desktop (please complete the following information):**
Windows 10 Pro 64 bits

**Appserver (please complete the following information):**
 * TOTVS - Build 7.00.210324P - Oct  5 2022 - 03:14:53 
 * Build: 64 bits
 * SVN Revision: 36666
 * Build Version: 20.3.1.0

**Comment by brodao2** [comment]
@vitor-gabriel 

Curiosidade, que extensão apresenta "You, agora..."?

**Comment by vitor-gabriel** [comment]
Uso o gitlens mestre. Ele me apresenta um blame em tempo real

**Comment by brodao2** [comment]
> Uso o gitlens, mestre. Ele me apresenta um blame em tempo real

Grato Gafanhoto ;)

**Comment by brodao2** [comment]
Chamado interno DTCLIENT01-3856

**Comment by vitor-gabriel** [comment]
> Grato Gafanhoto ;)
> 
> PS: Gafanhoto é referente a uma séria antiga (https://www.youtube.com/watch?v=B7YDcLP2DeY)

Filme excelente

**Comment by vitor-gabriel** [comment]
>Chamado interno DTCLIENT01-3856

Grato mestre, fico no aguardo.

**Comment by ricardomansano** [comment]
Boa tarde,
Como já informado o assunto será tradado internamente, avaliando a viabilidade.
Caso liberado, ele constará nas notas de release das próximas versões.
Grato,
