### ISSUE TITLE
fontes não compilam na nova build do appserver 20.3.1.2

### ISSUE THREAD

**Issue by maximinocastro** [totvs/tds-vscode#1074]
Boa tarde prezados,
Tudo bem?

Não estou conseguindo mais compilar fontes na nova build do appServer.

Abri o chamado [15583444] na TOTVS e o mesmo pediram para abrir chamado aqui relatando o problema.
 
Simplesmente aparece a informação "Starting build for environment" e não sai disso congela e trava o VsCode.

**Comment by brodao2** [comment]
@maximinocastro 

Favor complementar chamado informando os dados solicitados conforme [Informações importantes ao abrir o chamado](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#informa%C3%A7%C3%B5es-importantes-ao-abrir-uma-issue) e anexe os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)

É de extrema importância informar um passo a passo e se possível, anexe print de telas ou vídeo e o console log do Protheus.

No aguardo

**Comment by maximinocastro** [comment]
@brodao2 está no chamado da TOTVS.

Refiz o server por ser uma build nova e mesmo assim.

Passo a Passo 

Cria um Server > Conecta > Compila o fonte

[Info - 11:44:12 AM] Appserver detected with build version: 7.00.210324P and secure: 0
[Info - 11:44:12 AM] Validate server cxdffk-hom-protheus.totvscloud.com.br@24206 finished
[Info - 11:44:48 AM] Starting connection to the server 'Base Homol - Rest01' (cxdffk-hom-protheus.totvscloud.com.br@24206)
[Info - 11:44:48 AM] Connection to the server 'Base Homol - Rest01' finished.
[Info - 11:44:53 AM] Starting user 'michael.castro' authentication.
[Info - 11:44:53 AM] Secure authenticating...
[Info - 11:44:55 AM] User authenticated successfully.
[Info - 11:44:55 AM] User 'michael.castro' authentication finished.
[Info - 11:45:00 AM] Starting recompile.
[Info - 11:45:00 AM] Starting build for environment CXDFFK_HOM_REST01.

E fica nisso

**Comment by brodao2** [comment]
Eu não tenho acesso aos chamados da TOTVS, até transferirem para mim.

Anexe os logs do TDS-VSCode, conforme solicitado anteriormente.

**Comment by maximinocastro** [comment]
Segue os dados

Dados do Server 

Versão: TOTVS Saúde
Build AppServer: 7.00.210324P-20221215 - 64 bits
Nome do servidor: CXDFFKPRHOMWB42
Sistema operacional: Windows Server 2016
Appserver version: 20.3.1.2
Build DBAccess: 20210202-20220802
Release do RPO:  12.1.033
Release do dicionário: 12.1.033
Local files: ctree
License server: 2014 - 3.4.1
DB DataBase: MSSQL
DB API Build: 20220303-20221111

Dados do Remote 

Remote build: 7.00.210324P-20220805
Remote version: 20.3.0.4
Remote type: 2 - QT-5.15.9 MAC
Módulo: ATF
Nome do computador: FVFFFYCAQ6L4.local
Sistema operacional: MAC OS X V:10.18.x - MacBookAir10,1 x86_64
Memória: 8 GB
Processador: Apple M1

Versão da Lib:20220613
Data da Lib: 20220802_105622
Commit ID:1c6369191c9a007e11e1bc39fe12d08956aee68c
Central de Atualizações: 3234947 (23/12/2022)


Não gera o arquivo DAP conforme documentação, só se eu acessar o protheus.

Trava nisso

[Info  - 3:41:05 PM] Starting reconnection to the server 'Base Homol - Rest01'
[Info  - 3:41:05 PM] Secure authenticating...
[Info  - 3:41:07 PM] User authenticated successfully.
[Info  - 3:41:07 PM] Reconnection to the server 'Base Homol - Rest01' finished.
[Info  - 3:41:11 PM] Starting recompile.
[Info  - 3:41:11 PM] Starting build for environment CXDFFK_HOM_REST01.

**Comment by brodao2** [comment]
Favor complementar chamado informando os dados solicitados conforme [Informações importantes ao abrir o chamado](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#informa%C3%A7%C3%B5es-importantes-ao-abrir-uma-issue) e anexe os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)

Nota: Anexos enviados por e-mail não são aceitos. Deve ser efetuado direto no chamado.

**Comment by maximinocastro** [comment]
Mas já mandei tudo que pediram
[GitAzureTOTVS\dap.log](https://github.com/totvs/tds-vscode/files/10414504/GitAzureTOTVS.dap.log)

**Comment by brodao2** [comment]
Como disse, não tenho acesso aos chamados abertos na TOTVS. 
Você tem que anexar o log da extensão.
https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs

**Comment by maximinocastro** [comment]
As mesmas informações que mandei lá são as que estão aqui, eles só informaram que que é problema de plugin e não do AppServer

**Comment by brodao2** [comment]
Repetindo. EU NÃO TENHO ACESSO.

Gere os logs conforme solicitado e reabra o chamado quando o fizer.

Parece-me que você usa TCloud, se sim:

Clientes TCloud : Os ambientes que estão no TCloud em produção são bloqueados. Promova o RPO para DEV e use esse ambiente, e se necessário, promova-o de volta para produção. Para detalhes, entre em contato com o suporte do TCloud.

**Comment by danielbolognani** [comment]
@maximinocastro 
Ficou faltando os logs "totvsls.log", "totvsls_in.log" e "totvsls_out.log" que devem ser gerados na pasta raiz do workspace.
Se possível também, favor enviar o console.log
