### ISSUE TITLE
Problema no Debug com POUI

### ISSUE THREAD

**Issue by danielnugas** [totvs/tds-vscode#1075]
Olá pessoal!

Ao tentar fazer debug no VSCode com o POUI ativo abre a tela de login, mas ela fica toda em branco. Desabilitando o POUI conecta normalmente. Anexei print da tela em branco ao final da postagem.

Para reproduzir deve ativar o POUI, adicionado as chaves abaixo no ini e reiniciando o appserver:
[Drivers]
MultiProtocolPort=1
MultiProtocolPortSecure=0
[General]
App_Environment=<nome_do_ambiente>

Será que existe alguma configuração adicional, versão específica de algum componente ou algum plug-in para o VSCode?

Utilizo Protheus release 12.1.2210, estou com todos os componentes atualizados (dbaccess, binário, lib, etc) - build 7.00.210324P-20221215 64 bits. Utilizo o VsCode 1.68.1.

At,
Daniel Nugas

![Tela em Branco no Debug com POUI](https://user-images.githubusercontent.com/122652601/212449700-7d9b5770-9983-4dc7-bd31-ba4e90f4dc84.jpg)

**Comment by danielbolognani** [comment]
Bom dia @danielnugas 
Pode ser algum problema com permissão, tente executar o VSCode como administrador e verifique se o problema persiste.
Confira também se o smartclient utilizado no VSCode é o mesmo que vc utiliza fora do VSCode.
Caso nada resolver, favor gerar os logs:  https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs

**Comment by lwtnb-wrk** [comment]
@danielnugas O problema ocorre apenas na depuração com o tds-vscode? Esse é um problema conhecido do PO UI, mas a principio não tem relação com a depuração no tds-vscode. Se executar o mesmo programa (CTRL + F5) sem a depuração ativa a tela de login do PO UI aparece??

De qualquer forma, se estiver com tudo atualizado (appserver, smartclient, etc), experimente fechar seu AppServer e renomear a pasta "http-root" (apenas para backup, pode apagar depois se funcionar) e reiniciar o AppServer, essa pasta deve ser recriada e a tela de login do PO UI deve carregar tambem...

**Comment by danielnugas** [comment]
> Bom dia @danielnugas Pode ser algum problema com permissão, tente executar o VSCode como administrador e verifique se o problema persiste. Confira também se o smartclient utilizado no VSCode é o mesmo que vc utiliza fora do VSCode. Caso nada resolver, favor gerar os logs: https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs

Estou executando com a permissão de admin e meu smartclient é o mesmo. Gerei os logs, segue em anexo:

[totvsls_in.log](https://github.com/totvs/tds-vscode/files/10439577/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/10439578/totvsls_out.log)
[dap.log](https://github.com/totvs/tds-vscode/files/10439579/dap.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/10439580/totvsls.log)

**Comment by danielnugas** [comment]
> @danielnugas O problema ocorre apenas na depuração com o tds-vscode? Esse é um problema conhecido do PO UI, mas a principio não tem relação com a depuração no tds-vscode. Se executar o mesmo programa (CTRL + F5) sem a depuração ativa a tela de login do PO UI aparece??
> 
> De qualquer forma, se estiver com tudo atualizado (appserver, smartclient, etc), experimente fechar seu AppServer e renomear a pasta "http-root" (apenas para backup, pode apagar depois se funcionar) e reiniciar o AppServer, essa pasta deve ser recriada e a tela de login do PO UI deve carregar tambem...

Não sei como depurar no Protheus sem o vscode. Executando o vscode sem depurar (CTRL + F5) apresenta o mesmo problema.

Fiz como sugerido, mas não adiantou (parei o appserver, renomeei a pasta "http-root", subi o appserver e conferir que recriou a pasta "http-root").

**Comment by danielbolognani** [comment]
Por acaso é um ambiente CITRIX?
Da uma lida na documentação, mas o CITRIX não é homologado e temos ciência de problemas com o tWebEngine que pode ser contornado com uma alteração no registro, verifique em:
https://tdn.totvs.com/display/tec/SmartClient+-+Sistemas+operacionais
Na parte que fala de Metaframes e WebEnablers

Se não for um ambiente Citrix, de qual sistema operacional estamos falando?

Verifique também o arquivo QtWebEngineProcess.exe na pasta do smartclient, ele não pode ter nenhum bloqueio de firewall/antivirus e às vezes é necessário abrir as propriedades e desbloquear a execução do mesmo.

**Comment by danielnugas** [comment]
@danielbolognani e @lwtnb-wrk , muito obrigado pela atenção. Realmente o problema era de permissão, liberamos no firewall e deu certo.

Para fins de registro, vou responder a pergunta de vocês:
- Meu ambiente é Citrix e Windows 2016 Server.
- Fiz o teste sugerido, executando o smartclient por "fora" do vscode e apresentou o mesmo problema. Havia me esquecido que estava usando um smartclient diferente para fazer o debug. Com isso, foi possível identificar de forma mais fácil o que estava sendo bloqueado.

**Comment by danielnugas** [comment]
Valeu!
