### ISSUE TITLE
TRES

### ISSUE THREAD

**Issue by alexandro102021** [totvs/tds-vscode#1076]
Amigos , bom dia e desculpa novamente

Voltou a informar e tirar a duvida, o chamado foi respondido e redirecionado GITHUB, para uma duvida pequena.

As TRES devem esta na pastas do includes juntos com ch ou compilado no RPO?

Grato
Alexandro
![2](https://user-images.githubusercontent.com/93386105/212678701-2f6b1669-3827-4fa7-8c6e-204bd1bd19e9.png)
![1](https://user-images.githubusercontent.com/93386105/212678707-45852652-bd13-4c6b-b1da-073c8d4fe708.png)

**Comment by brodao2** [comment]
@alexandro102021 

Os arquivo TRES devem ser compilados. Sugiro coloca-los na mesma pasta onde vai ficar o seu fonte.
Se ainda houver alguma dúvida ou qq outra ocorrência, reabra este chamado.

A disposição.
