### ISSUE TITLE
Acentuação em pastas/arquivos - not found na hora da compilação.

### ISSUE THREAD

**Issue by lkznogueira** [totvs/tds-vscode#1078]
Bom dia!

Gostaria de saber se tem alguma possibilidade de ajustar esse problema que ocorre com usuários de macOs e creio que Linux tbem.

Atendo vários clientes e cada um tem um padrão de workspace. Alguns utiliza acentuação nas pastas de projetos, e todo projeto que pego que tenha acentuação eu tenho que ficar tirando para a compilação poder encontrar o prw.

Neste exemplo abaixo, se eu tirar a acentuação da palavra "Pre-Venda Ração" e da pasta "Miscelânea" ele compila corretamente.

Obs: A configuração de encode no VSCODE já foi realizada para Windows 1252

![image](https://user-images.githubusercontent.com/12913181/213178688-19c32abc-38e8-4378-b714-78fb37657754.png)

**Comment by lwtnb-wrk** [comment]
@lkznogueira Tanto no MacOS quanto Linux recomendamos a utilização apenas de caracteres minúsculos e sem acentuação nos caminhos (paths).
Acredito que mesmo que ajustemos isso no tds-vscode, o próprio AppServer vai ter problemas ao tentar buscar a pasta de includes com letras maiúsculas e acentuação e também os fontes, ou seja, a compilação deva falhar também.
De qualquer forma veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs gerados para que possamos dar uma analisada.

**Comment by lwtnb-wrk** [comment]
@lkznogueira Sim, conseguimos pelo menos compilar fontes, mas ainda estamos vendo outros pontos, como a depuração, e geração/aplicação de patches. Mas tivemos resultados interessantes na compilação ao menos. Fique atento as futuras atualizações.

**Comment by lkznogueira** [comment]
@lwtnb-wrk Bom Dia.. vc acha q seria possível soltar um arquivo para eu poder usar essa versão 'teste' desse ajuste? 
Estou com um projeto aqui que está cheio de acentuações nas pastas e tenho que ficar movendo eles td hora para poder compilar.

**Comment by lwtnb-wrk** [comment]
@lkznogueira Então faça os devidos backups e faça testes com o https://github.com/totvs/tds-vscode/releases/tag/v1.3.18-RC1
Não testamos em MacOS, mas acredito que as alterações que fizemos e testamos em Linux sirvam para Mac também.
Nos avise de qualquer forma, funcionando ou não funcionando... rsrsrs

**Comment by lwtnb-wrk** [comment]
@lkznogueira Grato pelo retorno, vamos rever essa questão então.

**Comment by lwtnb-wrk** [comment]
@lkznogueira Geramos uma RC2 https://github.com/totvs/tds-vscode/releases/tag/v1.3.18-RC2 veja se agora está funcionando corretamente no seu caso.

**Comment by lkznogueira** [comment]
@lwtnb-wrk 

Com essa deu certinho a compilação..

<img width="1507" alt="image" src="https://user-images.githubusercontent.com/12913181/233844935-8c060c74-a2db-4e55-8212-88f5766ba16f.png">

**Comment by lkznogueira** [comment]
@lwtnb-wrk 

Ref. a parte de compilação OK!!

Ref. a parte de DEBUG ele não conseguiu encontrar o fonte creio que por conta do caminho..

No print abaixo ele tentou abrir a aba "BRANCA" eh visível que a parte de módulos está toda 'zuada'. E de amaralo é o fonte que já estava aberto com o 'caminho' correto.

![image](https://user-images.githubusercontent.com/12913181/234618092-c8d4748c-f9a6-45a9-8277-3c6477e12fc3.png)

Acha que é possível corrigir esse tbem?

**Comment by brodao2** [comment]
@lkznogueira 

A equipe esta trabalhando na correção.

Grato por avisar.

**Comment by lkznogueira** [comment]
@brodao2 

Eu que agradeço o empenho de vocês!! Qualquer coisa estou aqui para validar no ambiente MacOs.

**Comment by lkznogueira** [comment]
@brodao2 Quando tiverem algum retorno deste item, poderia disponibilizar a versão para que eu possa testar e utiliza-la até a disponibilização Oficial? 
Isso anda me impactando muito em alguns clientes :/

**Comment by DanielYampolschi** [comment]
Ola @lkznogueira, corrigimos o problema de debug com pasta com acentuação. Você pode ter acesso à correção instalando a o Vsix do link abaixo.

https://github.com/totvs/tds-vscode/releases/tag/untagged-1e5cefa70e6254a8bfd8

Se tiver algum problema relacionado ao mesmo assunto, pode reabrir essa issue. Se for um assunto diferente, por favor abra uma nova.

**Comment by lkznogueira** [comment]
Bom Dia Senhores,

Voltei hoje a utilizar a plataforma MacOs, e vi que este problema retornou..

Teste varias versões para ver a onde o Problem voltou a acontecer, e até a versão v1.3.23 está funcionando essa correção. Deste para cima, voltou com esse problema de not found.
![image](https://github.com/totvs/tds-vscode/assets/12913181/233e4798-2ef0-4458-8cce-9b2826c627b4)
