### ISSUE TITLE
Erro ao compilar - 

### ISSUE THREAD

**Issue by arinuskrusz** [totvs/tds-vscode#1079]
Bom dia.

Após atualização da .33 o VSCODE apresenta erro ao compilar alguns fontes. (erro esse que em alguns casos é resolvido desinstalando totalmente o vscode e todas configurações de usuário das pastas %userprofile% e %appdata%. Em alguns casos mesmo reinstalando o vscode não resolve).

Print do erro:
![image](https://user-images.githubusercontent.com/48392412/214309717-0fcd872c-136b-4225-b703-73488a593220.png)
![image](https://user-images.githubusercontent.com/48392412/214309828-9171871f-d44b-49ee-8da3-cc275f700690.png)

Fonte com problema:
[Fontes com Problema.zip](https://github.com/totvs/tds-vscode/files/10490508/Fontes.com.Problema.zip)

S.O: Windows 10 e Windows Server (o erro ocorre em ambos os casos).

Já tentei ver se os problemas são nos includes, porém mesmo configurando os includes o erro permanece.

**Comment by lwtnb-wrk** [comment]
@arinuskrusz Abrindo os fontes citados encontrei o mesmo caracter estranho em ambos:
Na linha 632 da MT681INC.PRW e na linha 634 da PONENTWO.PRW, sendo que esse caracter estranho existe em outras linhas, mas bastaria apenas um no fonte, para eventualmente causar algum tipo de problema na leitura e consequentemente na compilação.
Enfim, veja se esse caracter deveria estar ali e/ou tente remove-lo para ver se consegue compilar após a remoção.

**Comment by lwtnb-wrk** [comment]
@arinuskrusz Consegui compilar aqui e o problema é outro... Tem relação com essas linhas mas é o tamanho dela que excede 2048 caracteres. O tds-vscode 1.3.16 saiu com um problema para compilar linhas acima de 2048 caracteres e por isso que está falhando.
Já corrigimos essa questão e a próxima versão 1.3.17 deve resolver esse problema.
Se quiser testar e validar, instale manualmente a Pré Release https://github.com/totvs/tds-vscode/releases/tag/v1.3.17-RC4 veja instruções de como instalar manualmente em https://github.com/totvs/tds-vscode/blob/master/docs/install.md

**Comment by arinuskrusz** [comment]
Agradeço o retorno lwtnb-wrk!! Vou testar e validar a pré release e ver se o problema resolve.

**Comment by lwtnb-wrk** [comment]
liberada versão 1.3.17 que deve resolver esta questão, favor atualizar a extensão e caso necessário abra uma nova issue
