### ISSUE TITLE
Problemas na indentação

### ISSUE THREAD

**Issue by likid** [totvs/tds-vscode#108]
Pessoal, atualizei para a versão 0.3.11 mas ainda existem alguns problema com a indentação, vejam os prints abaixo:

Antes de indentar
![Code_2019-07-04_14-14-05](https://user-images.githubusercontent.com/10984007/60681606-44d25a80-9e66-11e9-8519-1e366aa608a1.png)

Depois de indentar, apenas os Ifs foram para frente.
![Code_2019-07-04_14-14-16](https://user-images.githubusercontent.com/10984007/60681613-4d2a9580-9e66-11e9-912f-783be0701856.png)

**Comment by lwtnb-wrk** [comment]
@likid Estamos avaliando os problemas de identacao. Grato por avisar.

**Comment by brodao** [comment]
@likid , se possível anexe o fonte que apresentou essa ocorrência.

Grato.

**Comment by likid** [comment]
@brodao pode ser de modo particular via email?

**Comment by brodao** [comment]
Sim. Mande para acandido@totvs.com.br, por favor.
