### ISSUE TITLE
Fonte não compila no VsCode

### ISSUE THREAD

**Issue by brunogfx4** [totvs/tds-vscode#1080]
Ao tentar fazer uma compilação o VSCODE, não encerra a compilação, apenas fica apresentando a seguinte tela:
[Info  - 09:34:42] Starting recompile.
[Info  - 09:34:42] Starting build for environment PERUQA.
[Info  - 09:34:45] Starting build using RPO token ...
[Info  - 09:34:45] Start file recompile.
[Info  - 09:34:45] Using Includes: c:/protheus/include
[Info  - 09:34:45] Start secure compiling c:/svn_fontes/oficina1/bruno/latamerp-194/bkp/brteste.prw (1/1).

Ja tentei apagar todos os arquivos e fazer e reinstalar, porem o erro persiste.

![image](https://user-images.githubusercontent.com/96890340/215478672-a4eace5a-badc-4c8d-86b5-19bfea00b03f.png)

**Comment by lwtnb-wrk** [comment]
@brunogfx4 Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e após repetir a ação que está falhando, nos envie os logs para análise.

**Comment by brunogfx4** [comment]
Bom dia, obrigado pela atenção.
Segue arquivos de log.
[totvsls.log](https://github.com/totvs/tds-vscode/files/10535970/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/10535972/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/10535973/totvsls_out.log)

**Comment by lwtnb-wrk** [comment]
@brunogfx4 Dessa vez não travou? Pelos logs compilou normalmente e finalizou com sucesso...

**Comment by brunogfx4** [comment]
Ele só apresenta a tela de compilar, e não conclui fica ainda aparecendo :[Info  - 10:00:16] Start secure compiling c:/svn_fontes/oficina1/bruno/latamerp-194/bkp/brteste.prw (1/1).

**Comment by lwtnb-wrk** [comment]
@brunogfx4 Estranho isso, pois nos logs aparecem as mensagens abaixo indicando sucesso...
( 129.433s) [stdout          ]               timer.cc:42    | [e2e] Message to Client: "[Info] Start secure compiling c:/svn_fontes/oficina1/bruno/latamerp-194/bkp/brteste.prw (1/1)." took 0.0 ms
( 129.644s) [stdout          ]               timer.cc:42    | [e2e] Message to Client: "[Info] [WARNING] Source c:/svn_fontes/oficina1/bruno/latamerp-194/bkp/brteste.prw compiled with warnings and/or non fatal errors." took 0.14 ms
( 129.644s) [stdout          ]               timer.cc:42    | [e2e] Message to Client: "[Info] Committing end build. This could take a while..." took 0.0 ms
( 129.852s) [stdout          ]               timer.cc:42    | [e2e] Message to Client: "[Warning] One or more files have warnings. See problems and logs for details." took 0.0 ms
( 129.853s) [stdout          ]               timer.cc:42    | [e2e] Message to Client: "[Info] Recompile finished." took 0.1 ms

**Comment by lwtnb-wrk** [comment]
@brunogfx4 Experimente fazer o seguinte teste entao, copie esse fonte "brteste.prw" para outra pasta e tente compilar deste outro local.

**Comment by brunogfx4** [comment]
Infelizmente persiste, inclusive tentei compilar outro arquivo:

[Info  - 11:20:49] Start file recompile.
[Info  - 11:20:49] Using Includes: c:/protheus/include
[Info  - 11:20:49] Start secure compiling c:/users/bsouza2/onedrive - automatic data processing inc/documents/virada adp/projeto_adp_oficial/5-financeiro/adp0001.prw (1/1).

**Comment by lwtnb-wrk** [comment]
@brunogfx4 Chegou a testar se realmente o fonte não esta no RPO compilado? Se executar uma chamada para esse fonte, ele existe ou não no RPO? 
Qual o SO em que o tds-vscode está instalado? Windows 11 mesmo?

**Comment by lwtnb-wrk** [comment]
@brunogfx4 E outro teste seria, pegar um novo RPO... Talvez tenha algum problema com o próprio RPO no final.

**Comment by brunogfx4** [comment]
Ja tentei em todos os ambientes que uso, temos 5 paises diferentes com o Protheus, estou utilizando o windows 10 Enterprise.

**Comment by lwtnb-wrk** [comment]
@brunogfx4 Isso funcionava e parou de funcionar? Instalou alguma outra extensão recentemente?

Acreditamos que deve ser algo no seu ambiente, pois caso contrário teríamos diversos relatos dessa questão, mas é a primeira vez que estamos vendo algo assim... Os logs indicando sucesso, mas a interface visual travada assim...

**Comment by brunogfx4** [comment]
Exatamente é isso que acontece, a interface esta travando, qnd o RPO nao esta em modo exclusivo ele acusa, porem qnd consegue concluir a compilação ele não diz nada, ai tenho que fechar o VSCODE, e muitas vezes tenho que apagar o arquivo de server e refazer.

**Comment by brunogfx4** [comment]
Estou usando essa versão:
Version: 1.74.3 (user setup)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19042
Sandboxed: No

**Comment by lwtnb-wrk** [comment]
@brunogfx4 Mas voce tem a chave BuildKillUsers=1 na seção [General] do seu AppServer certo?

**Comment by brunogfx4** [comment]
Sim estava dessa forma, tirei agora pra ver porem mesmo assim continua travado, a ele nao ta compilando não, irei mandar novamente os logs.

**Comment by brunogfx4** [comment]
[totvsls.log](https://github.com/totvs/tds-vscode/files/10538945/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/10538946/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/10538947/totvsls_out.log)

**Comment by brunogfx4** [comment]
Desculpa a chave estava sim habilitada, pensei que nao estivesse.

**Comment by lwtnb-wrk** [comment]
@brunogfx4 Poderia nos enviar o console.log do AppServer?

**Comment by brunogfx4** [comment]
Aonde eu consigo essa versão para Download, nao consegui localizar.

**Comment by lwtnb-wrk** [comment]
@brunogfx4 A versão oficial do v1.3.17 saiu hoje, entao tente atualizar (caso isso ja nao tenha ocorrido automaticamente) e veja se consegue compilar...
Caso contrario envie o console.log do appserver para a gente dar uma olhada

**Comment by danielbolognani** [comment]
Devido ao tempo sem retorno, estamos fechando esse caso.
Caso ainda tenha problema favor reabrir com mais detalhes conforme pedido pelo @lwtnb-wrk .
