### ISSUE TITLE
Debug - Erro v001

### ISSUE THREAD

**Issue by jpinto10** [totvs/tds-vscode#1082]
Bom dia.
Ao tentar "DEBUGAR" um ponto de entrada, na rotina de pedido de vendas, o sistema apresenta o erro em anexo.

Como devo proceder?!
[Erro.txt](https://github.com/totvs/tds-vscode/files/10578229/Erro.txt)

**Comment by lwtnb-wrk** [comment]
@jpinto10 O erro é na rotina ou erro do tds-vscode? Aqui tratamos apenas de erro na ferramenta tds-vscode, mas parece ser erro da rotina, o que você está reportando.
Se for erro no tds-vscode, veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise. Em especial o dap.log por se tratar de possivel erro na depuração.

**Comment by jpinto10** [comment]
Em teoria, na rotina.
Pois cionsigo realizar debugS, em outras. 
mais no chamado fui direcionado aq!

**Comment by lwtnb-wrk** [comment]
@jpinto10 O pessoal do suporte tem direcionado tudo que mencionam o tds-vscode para cá, mas esse tipo de chamado realmente não é tratado aqui. Peço que volte a tratar com eles e reforce que é um erro na rotina.
