### ISSUE TITLE
Erro ao executar Debug na versão .17

### ISSUE THREAD

**Issue by ivantore** [totvs/tds-vscode#1083]
Após atualizar a versão da extenção, ao tentar executar um debug o erro em anexo é apresentado:

Mesmo reinstalando o Vscode, refazendo o .json o erro persistiu.

Só foi resolvido ao voltar para versão .15

Isso já tinha ocorrido na .16 também.

O sistema operacional é MacOS.

Error(-1): Falha ao iniciar o SmartClient. Command: "/Users/ivan/Library/Mobile Documents/com~apple~CloudDocs/Totvs/SmartClients/TVCultura/TVCultura.app/Contents/MacOS/smartclient" -DEBUG=12200 -z=fpasrv102 -y=20036 -ssl "-E=TOTVS_DEV01" "-P=SIGAMDI"  -M

**Comment by lwtnb-wrk** [comment]
@ivantore Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs e nos mande os logs para analise. Em especial o dap.log.

**Comment by ivantore** [comment]
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/10579686/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/10579687/totvsls_out.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/10579688/totvsls.log)
[dap.log](https://github.com/totvs/tds-vscode/files/10579695/dap.log)

@lwtnb-wrk segue os arquivos solicitados.

**Comment by lwtnb-wrk** [comment]
@lwtnb-wrk Em um terminal você consegue executar o Smartclient com esse comando? Note que existe um espaço em "Mobile Document"
/Users/ivan/Library/Mobile Documents/com~apple~CloudDocs/Totvs/SmartClients/Grafimec/Grafimec_Producao.app/Contents/MacOS/smartclient
e caso afirmativo tente entre aspas também para confirmar se tem o mesmo resultado
"/Users/ivan/Library/Mobile Documents/com~apple~CloudDocs/Totvs/SmartClients/Grafimec/Grafimec_Producao.app/Contents/MacOS/smartclient"

**Comment by ivantore** [comment]
Nenhum dos 2 comandos funcionou.

**Comment by lwtnb-wrk** [comment]
@lwtnb-wrk Esse é o caminho completo do executável do smartclient que está sendo usado para execução/depuração.
Você tem os logs gerados pela versão 1.3.15 para que a gente possa comparar?

**Comment by ivantore** [comment]
Sim, esse é o caminho completo: ivan@MBP-Ivan ~ % cd /Users/ivan/Library/Mobile\ Documents/com~apple~CloudDocs/Totvs/Smartclients/Grafimec/Grafimec_Producao.app/Contents/MacOS/smartclient

Se executar o comando cd ele chega até a pasta MacOS

Segue os logs da versão .15 que está funcionando.

[dap.log](https://github.com/totvs/tds-vscode/files/10583094/dap.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/10583095/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/10583096/totvsls_out.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/10583097/totvsls.log)

**Comment by lwtnb-wrk** [comment]
@ivantore Estamos averiguando essa questão, pois ocorre apenas no MacOS. Está funcionando corretamente no Windows e Linux...
Por enquanto como contorne, se a 1.3.15 te atende continue utilizando, mas devemos corrigir para a 1.3.18

**Comment by ivantore** [comment]
@lwtnb-wrk Ok. Caso eu posso ajudar em algo mais, estou à disposição.

**Comment by DanielYampolschi** [comment]
Ola @ivantore, liberamos a versão Release Candidate 1.3.18-RC5 que corrigiu alguns problemas de depuração.
Por favor instale essa atualização pelo Vsix do link abaixo e verifique se o seu problema para de ocorrer. 
Caso ainda permaneça, pode reabrir essa issue.

https://github.com/totvs/tds-vscode/releases/tag/v1.3.18-RC5

**Comment by ivantore** [comment]
Bom dia,

Utilizando essa versão o problema foi corrigido.

Obrigado,
At.
Ivan

De: DanielYampolschi ***@***.***>
Data: quinta-feira, 25 de maio de 2023 16:03
Para: totvs/tds-vscode ***@***.***>
Cc: ivantore ***@***.***>, Mention ***@***.***>
Assunto: Re: [totvs/tds-vscode] Erro ao executar Debug na versão .17 (Issue #1083)

Ola @ivantore<https://github.com/ivantore>, liberamos a versão Release Candidate 1.3.18-RC5 que corrigiu alguns problemas de depuração.
Por favor instale essa atualização pelo Vsix do link abaixo e verifique se o seu problema para de ocorrer.
Caso ainda permaneça, pode reabrir essa issue.

https://github.com/totvs/tds-vscode/releases/tag/v1.3.18-RC5
