### ISSUE TITLE
Problema debug serviço Rest

### ISSUE THREAD

**Issue by cirilorocha** [totvs/tds-vscode#1085]
**Describe the bug**
- Tenho dificuldades em fazer o debug de fontes que estão sendo executados no Rest. O problema ocorre quando estou percorrendo os fontes linha a linha usando o atalho F10. Muitas vezes o compilador não respeita o comando e simplesmente não para na próxima linha, pula direto para o próximo breakpoint ou mesmo até o final da execução da rotina. Isso ocorre de forma aleatória em vários pontos do programa, percorro 5 linhas então ele pula a execução.

**To Reproduce**
- Criar um programa para subir um serviço Rest (testei com WSRESTFUL e TLPP Anotation) chamando uma outra função
- Na outra função ir debugando linha a linha o programa (usei o atalho F10), em algum ponto do programa ele vai pular e só vai parar no final ou no próximo breakpoint.

**Desktop (please complete the following information):**
 - OS/Architecture: [e.g. Windows 64 bits]: Windows 11 pro x64

**Appserver (please complete the following information):**
 - Build (with date): 7.00.210324P-20221215 - 64 bits
 - OS/Architecture: Windows 11 Pro x64
 - Build Version: 20.3.1.2

**Additional context**
- No vídeo que estou anexando o sistema pulou da linha 1141 do fonte RCOMA07 direto para o próximo breakpoint.
- Infelizmente é um cenário meio aleatório, tentei criar um fonte pequeno para reprodução e não reproduziu, como se o problema fosse com fontes grandes e cheios de chamadas.
- Consigo reproduzir o problema como mostrado no vídeo, executando meus fontes

https://user-images.githubusercontent.com/96308173/217929547-d1f63bd5-863a-44b9-9e86-5e81a5054b28.mp4

**Comment by brodao2** [comment]
@cirilorocha 

Pelo seu relato, peço que:
1. Certifique-se que o ambiente que roda o REST é o mesmo que foi selecionado na extensão;
2. Certifique-se que o fonte foi compilado nesse ambiente;
3. Atente se alguma das funções da linha em que aciona F10, se houver um ponto de parada este será respeitado (por isso o salto). Verifique a pilha de chamada no momento da parada após o salto, se a linha que deu F10 não se encontra na pilha.

Caso não resolva, favor complementar este chamado informando os dados solicitados conforme [Informações importantes ao abrir o chamado](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#informa%C3%A7%C3%B5es-importantes-ao-abrir-uma-issue) e anexe os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema).

> No seu caso, o log do _debug adapter_ (dap.log) é imprescindível.

No aguardo.

**Comment by cirilorocha** [comment]
@brodao2 
Verifiquei as situações que você elencou mas todas estavam ok.
No meu teste gerando os logs o sistema simplesmente pulou vário fontes de uma vez só da linha 1190 do fonte RCOMA07 de volta para o primeiro fonte, não passando para as linhas seguinte.
Segue o log Dap.log gerado e um arquivo com todas as informações do VSCode e do AppServer.

[dap.log](https://github.com/totvs/tds-vscode/files/10707065/dap.log)

[Versão do Servidor.txt](https://github.com/totvs/tds-vscode/files/10707066/Versao.do.Servidor.txt)

https://user-images.githubusercontent.com/96308173/218086007-02b9c945-3950-48a3-abbb-f1b17ce2a411.mp4

**Comment by brodao2** [comment]
Só para confirmar, o DAP esta pegando o fonte "c:\\AAA\\Protheus12\\FONTES_PROJETO\\Compras\\Telas\\RCOMA07.prw". Está correto? Verifique se este fonte (ou mesmo outros) não está em duplicidade na sua área de trabalho.

Uma outra hipótese, é ter uma outra thread (que você não esta esperando) que está executando outro trecho do código.

Sugiro que faça:
1. Reinicie o appServer;
2. Execute o TDS-Monitor (acesse a área de download do suporte e busque por "monitor_electron");
3. Verifique as threads em execução, antes de efetuar a 1a requisição rest;
4. Inicie a depuração e ao atingir o ponto de parada, verifique as threads em execução e veja se há alguma outra não esperada.

| Não sei detalhes do seu processo, mas em teoria, você deve ter uma thread da requisição rest e uma da depuração.

**Comment by brodao2** [comment]
O TDS-Monitor esta documentado em https://tdn.totvs.com/display/tec/Monitor+Electron.

**Comment by cirilorocha** [comment]
Está correto o fonte é este mesmo que está compilado no servidor.

Fiz a verificação no monitor e não vi nenhuma outra thread. Seguem os prints mostrando:

![Antes](https://user-images.githubusercontent.com/96308173/218098569-360148ba-47ea-4332-8a27-dad6ad192298.jpg)

![Depois](https://user-images.githubusercontent.com/96308173/218098564-693e7596-c0da-4e6e-8e62-e961ec891a0d.jpg)

**Comment by brodao2** [comment]
@cirilorocha 

Fiz alguns testes e analises de log e não identifiquei nada que possa apresentar esse comportamento.
Favor anexar os log (LS, DAP e appServer) que contenha os procedimentos:
1. Compilação de todos os fontes envolvidos;
2. Reprodução da ocorrência.

Favor também enviar o ini do appServer. caso este contenha alguma informação sensível, envie-o direto para meu e-mail (acandido@totvs.com.br).

No aguardo.

**Comment by cirilorocha** [comment]
@brodao2 
Fiz exatamente como você solicitou compilei os fontes (tive que fazer em um appserver separado porque o Rest não ia permitir), depois subi o Rest, conectei o client no modo debug. Fiz o meu debug e reproduziu o salto no programa.
Seguem os logs e um pequeno vídeo do teste.

[totvsls_out.log](https://github.com/totvs/tds-vscode/files/10725282/totvsls_out.log)
[console_appserver.log](https://github.com/totvs/tds-vscode/files/10725283/console_appserver.log)
[console_rest.log](https://github.com/totvs/tds-vscode/files/10725284/console_rest.log)
[dap.log](https://github.com/totvs/tds-vscode/files/10725285/dap.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/10725286/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/10725287/totvsls_in.log)
[appserver.zip](https://github.com/totvs/tds-vscode/files/10725297/appserver.zip)
[AppServer_Rest.zip](https://github.com/totvs/tds-vscode/files/10725298/AppServer_Rest.zip)
https://user-images.githubusercontent.com/96308173/218546729-c7707e35-ff5c-4af8-b883-dbfb88045805.mp4

**Comment by brodao2** [comment]
@cirilorocha 

Analisei os logs e efetuei testes em meu ambiente e não reproduzi a ocorrência.
Uma diferença em relação ao meu ambiente é que não uso nenhum tipo de monitor, _profiler_ ou jobs.

Favor desativar _logProfile_ em todos os ambientes e a execução de jobs (esses ambientes são executados em paralelo com o serviço rest).

No aguardo.

**Comment by cirilorocha** [comment]
@brodao2 
Allan refiz os testes desativado esse parâmetro logProfile e deixando apenas o appserver do rest ativo, e mesmo assim ainda tenho pulos no meio do debug.

**Comment by lwtnb-wrk** [comment]
@cirilorocha Esses pulos costumam ocorrer realmente quando o fonte compilado e o que o editor abre não estão sincronizados.
E outra possibilidade seria o AppServer não estar enviando os comandos para que o tds-vscode pare nos locais que você esperava.

**Comment by cirilorocha** [comment]
@lwtnb-wrk Eu acredito fortemente que está havendo uma falta de sincronia nesta comunicação com o AppServer, ou então o mesmo está se perdendo em algum processo interno e não para onde precisa. Os fontes que estou testando eu sempre forço a sua compilação antes do debug, tanto que os pulos caem em locais reais, se quando o fonte está diferente geralmente ele não coincide com a parada.
Não sei se tem algo haver com o fato de ser um servidor REST, porque observei que ele tem várias pequenas particularidades, e não executa as coisas exatamente como o serviço convencional, deve ter algo nesse sentido. E o problema ocorre tanto com Rest 2.0 como com TLPP.
Eu entendo perfeitamente que esse é um problema intermitente e que não está sendo reproduzido, eu já vi outros desenvolvedores relatarem isso também, só que não conseguimos chegar a uma solução.
Como paliativo eu coloco 1 tonelada de breaks points no programa, de forma que mesmo ele não respeitando o F10, vai parar em um ponto próximo, mas isso está dificultando muito esse debug específico.
Se infelizmente não conseguimos reproduzir, e nem identificar nada sobre a causa ou correção, podemos encerrar este ticket se acharem melhor.
