### ISSUE TITLE
Não acusa duplicidade ao compilar folder

### ISSUE THREAD

**Issue by AlexandreBeh** [totvs/tds-vscode#1086]
Bom dia, a extensão está apresentando um comportamento errado ao compilar os arquivos.

Se seleciona pela aba lateral para compilar o folder ou o arquivo, não aparece erro de duplicidade de função.
Mas se executar a compilação pela ctrl + f9 mostra o erro.

Isso é muito ruim pois, leva muito tempo para cada compilação por cada arquivo.
Como podem ver no video em anexo.

Version: 1.74.2 (user setup)
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:29:14.590Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19041
Sandboxed: No

Versão 1.3.17

https://user-images.githubusercontent.com/11984884/218099824-ccea20e0-7d8b-4258-88a9-d6bdd360b465.mp4

**Comment by brodao2** [comment]
@AlexandreBeh 

A opção de compilação via menu de contexto da pasta, pula fontes já compilados, por isso não acusa o erro. Utilize recompilar acionando `alt` junto com o acionamento do menu de contexto.

A disposição.
