### ISSUE TITLE
Erro ao depurar o programa

### ISSUE THREAD

**Issue by EvandroTEC5** [totvs/tds-vscode#1087]
Bom dia

Ao tentar depurar o programa, o Protheus não está sendo aberto, ele não carrega a tela de login, mostrando o erro em anexo.
Segue os dados do arquivo launch.json:

{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "TOTVS Language Debug",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "C:/Users/evand/Desktop/smartclient/smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true,
			"programArguments": [],
			"enableMultiThread": false,
			"enableProfile": false,
			"isAccessibilityMode": false,
			"doNotShowSplash": false,
			"language": "",
			"ignoreFiles": true
		}
	],
	"lastPrograms": [
		{
			"label": "SIGAMDI"
		},
		{
			"label": "SIGAADV"
		},
		{
			"label": "SIGACFG"
		}
	],
	"lastProgramExecuted": "SIGAADV"
}

Obrigado
Evandro
![erro01](https://user-images.githubusercontent.com/125368529/218745233-d1c19466-9748-47a7-ad76-b4cf269ac3fb.JPG)

**Comment by danielbolognani** [comment]
Bom dia @EvandroTEC5 
Nesse caso o problema não é na depuração, vc não deve conseguir acessar esse servidor mesmo fora de ambiente de depuração (executanco o smartclient diretamente, fora do vscode).
Por aqui apenas podemos ajudar com problemas relacionados a extensão TDS-VSCode.


De qualquer forma esse erro (ERR_UNSAFE_PORT) é porque o seu ambiente está subindo na porta 6000 e o chrome considera essa porta insegura e não deixa carregar. A melhor solução seria alterar o número de porta para uma diferente.

Abraços!
