### ISSUE TITLE
Não exibe informações do Json ao depurar

### ISSUE THREAD

**Issue by gtrabach** [totvs/tds-vscode#1090]
**Describe the bug**
Ao tentar depurar um Json, o TDS não exibe as informações daquela variável Json.

**Desktop (please complete the following information):**
Windows 11 Pro 64-bits 22H2
TDS 1.3.17
VsCode 1.74.3

**Appserver (please complete the following information):**
Windows Server 2012 R2
20.3.1.4

**Additional context**
Em anexo vídeo evidência, o fonte e o arquivo json utilizados no teste.
[issue json.zip](https://github.com/totvs/tds-vscode/files/10902731/issue.json.zip)

**Comment by lwtnb-wrk** [comment]
@gtrabach Pelas minhas análises preliminares o problema ocorre porque seu JSON é do tipo "Array Literal", ou seja, o primeiro nível de seu JSON já é um Array, mas o AdvPL está retornando que o ValType é um JSON, cujo tratamento não é o mesmo que o de um Array.
Por enquanto, se puder alterar seu JSON de entrada, ele deve funcionar adequadamente se o primeiro nível for um JSON 'normal', então ao invés de começar com "[]", crie um JSON com "{}" e atribua seu Array a um elemento qualquer, por exemplo:
{
  "arr": [
    ... o array que estava no primeiro nível
    ]
}
O jTeste será entendido como um JSON e acessando o jTeste["arr"] ele entenderá como um Array e realizará as tratativas corretas.
Vamos ter que analisar melhor qual a melhor estratégia para resolver essa questão, mas grato por reportar o problema.

**Comment by lwtnb-wrk** [comment]
@gtrabach Outro detalhe é que, sabendo que o jTeste, apesar de JSON é um Array também, você pode acessá-lo diretamente pelos seus índices, então ao realizar o evaluate de jTeste[1] ele vai retornar o 1o JSON do Array e assim por diante.

**Comment by gtrabach** [comment]
@lwtnb-wrk Perfeito, obrigado pela explicação. 

Sim, havia visto que ao acessar as posições ele estava exibindo as informações corretamente, só havia achado estranho ele não exibir os dados completos sem especificar a posição. E como estou trabalhando num projeto atualmente que existem várias variáveis deste tipo, pensei que poderia ser um problema geral com variáveis JSON.

Irei utilizar esse paliativo enquanto debugo, obrigado pela ajuda.

**Comment by renato-calabro** [comment]
Pessoal, alguma novidade sobre esse ponto?

Eu também tive uma situação similar e em debug o retorno me gerou dúvidas.
Achei que ele não estava carregando, mas depois de abrir uma pergunta no canal devforum, explicaram que ele foi carregado.
https://devforum.totvs.com.br/4563-jsonobject-nao-deserializa-quando-o-objeto-e-tipo-lista-inicia-com-colchetes

O ruim é que não temos visibilidade e gera dúvidas em tempo de desenvolvimento.

Segue um exemplo como o retorno fica quando tento "verificar" se foi preenchido.
![image](https://github.com/totvs/tds-vscode/assets/93009882/535c2298-24ac-4cd6-b778-56594141cc05)

Se uso o Json "normal", como o @lwtnb-wrk comentou, o varinfo é carregado:
![image](https://github.com/totvs/tds-vscode/assets/93009882/b9d003c8-6ba2-45af-8891-09c6fe8750e8)

**Comment by brodao2** [comment]
![image](https://github.com/totvs/tds-vscode/assets/114854608/52ef0789-7cf5-484e-812e-db66f3fae3ce)

**Comment by lwtnb-wrk** [comment]
Liberamos uma versão v2.0.9 Pre-release (https://github.com/totvs/tds-vscode/releases/tag/v2.0.9) que deve corrigir esta questão, baixe e instale o vsix para confirmar se o problema foi resolvido.
Se tiver questões quanto a instalação do vsix, veja https://github.com/totvs/tds-vscode/blob/master/docs/install.md
