### ISSUE TITLE
Annotation e Reflection vazios ao debuggar fonte TLPP

### ISSUE THREAD

**Issue by vitor-gabriel** [totvs/tds-vscode#1091]
## Enter the data below

**Describe the bug**
Ao debugar um fonte TLPP, especificamente testando os annotations e reflections não é me retornado o valor esperado

**To Reproduce**
1 - Crie uma classe tlpp com annotation e reflections
2 - Coloque um breakpoint após o reflection ser executado
3 - Copie o reflection para o console de depuração e veja o valor vazio sendo retornado

**Expected behavior**
O valor correto dos annotations dentro da classe

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/62556013/224622371-8752be2b-94ce-4320-9721-729cb4e8aeac.png)

**Desktop (please complete the following information):**
 - OS/Architecture: Windows 11 64 bits

**Appserver (please complete the following information):**
 - Build (with date): 7.00.210324P-20230228 - 64 bits
 - OS/Architecture: Windows 10 64 bits
 - Build Version  20.3.1.4

**Comment by brodao2** [comment]
@vitor-gabriel 

Eu não tenho certeza, mas como em ambas anotações usa-se a mesma propriedade, pode estar ocorrendo sobreposição.
Favor entrar em contato com o suporte AdvPL a respeito dessa ocorrência.
