### ISSUE TITLE
ERROR: : DBUseArea - DB driver not initialized

### ISSUE THREAD

**Issue by FerrerAndreas** [totvs/tds-vscode#1093]
Erro ao compilar fonte em AdvPL
THREAD ERROR ([8716], TI_01, TI_01)   13/03/2023 09:44:33
: DBUseArea - DB driver not initialized.  on U_RKMARCA(RKMARCA.PRW) 13/03/2023 09:44:05 line : 62

**Comment by brodao2** [comment]
@FerrerAndreas 

Pela mensagem, não me parece ser erro de compilação e execução de uma função do usuário (_user function_).

Se for de execução, favor entrar em contato com o suporte de AdvPL.
Caso contrário, complementar o chamado informando os dados solicitados conforme [Informações importantes ao abrir o chamado](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#informa%C3%A7%C3%B5es-importantes-ao-abrir-uma-issue) e anexe os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)

É de extrema importância informar um passo a passo e se possível, anexe print de telas ou vídeo e o console log do Protheus.

No aguardo.

**Comment by FerrerAndreas** [comment]
Bom dia, realmente o erro está na execução, como entro em contato com o suporte de AdvPL?

**Comment by brodao2** [comment]
Acesse o [Portal do Cliente](https://suporte.totvs.com/) e procure pela opção.
