### ISSUE TITLE
Erro - extensão TOTVS Developer

### ISSUE THREAD

**Issue by rbncosta** [totvs/tds-vscode#1094]
Olá, boa tarde!

Ao instalar a extensão TOTVS Developer não consigo conectar no servidor Prothues e nesse momento não apresenta nenhuma mensagem. Porém ao iniciar o VS Code aparece a seguinte mensagem: "Couldn't start client TOTVS Language Server"

Já exclui a pasta .vscode do projeto, refiz as configurações pelo "Boas Vindas", mas o erro persiste.

Conseguem me apoiar nessa resolução, pf?

Obrigado!

OBSERVAÇÕES:

Já tinha uma instalação funcional, mas foi bloqueada pelo nosso time de INFRA, e para resolver foi necessário fazer uma nova instalação do VS Code  (no momento tenho duas instalações na máquina).

Estou refazendo as configurações nessa segunda instalação para depois remover a primeira que foi bloqueada.

**Comment by lwtnb-wrk** [comment]
@rbncosta Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos mande os logs para analisarmos

**Comment by rbncosta** [comment]
Obrigado pelo retorno!

Fiz as configurações conforme o link, mas não gerou nenhum log na pasta.

Anexo o arquivo settings.json como ele ficou, e também uma mensagem que aparece no OUTPUT quando forço uma compilação mesmo sem o server estar conectado.

[Erro.txt](https://github.com/totvs/tds-vscode/files/10991400/Erro.txt)
[.vscode.zip](https://github.com/totvs/tds-vscode/files/10991416/default.vscode.zip)

**Comment by lwtnb-wrk** [comment]
@rbncosta Este tipo de erro "Error: spawn UNKNOWN" geralmente ocorre por problemas de permissão.
O usuário que você se logou na estação é Admin? Está executando o VS Code como Admin?
Pelo jeito, as políticas de segurança implantadas pelo time de infra estão bloqueando a execução do binário necessário dentro da extensão tds-vscode.
Experimente executar o VS Code como Administrador se possível ou vice-versa, se atualmente roda com Admin tenta rodar com um usuário não Admin...

**Comment by rbncosta** [comment]
Estou fazendo com meu usuário local que não é Admin da máquina.

Vou fazer esse teste e retorno com o resultado.

Muito obrigado!
