### ISSUE TITLE
Melhoria - Agrupar servidores em Diretórios

### ISSUE THREAD

**Issue by wallacefreitas** [totvs/tds-vscode#1095]
Prezados bom dia.

Gostaria de dar uma sugestão de melhoria para que fosse possível agrupar os servidores por pasta, pois muitas vezes temos vários serviços em uma mesma base. Hoje o plugin lista tudo de uma forma única.

A idéia aqui seria ter a possibilidade de criar diretórios e agrupar os servidores cadastrados dentro de cada diretório (funcionando como o próprio Explorer do VSCode), com o intuito de deixar a listagem de servidores mais organizado.

Por exemplo:

**> [Diretório] Base Teste**
> Server Balance 1 - 0.0.0.0:0001
> Server Balance 2 - 0.0.0.0:0002

**> [Diretório] Base Homologação**
> Server Balance 1 - 0.0.0.1:0001
> Server Balance 2 - 0.0.0.1:0002

**> [Diretório] Base Produção**
> Server Balance 1 - 0.0.0.2:0001
> Server Balance 2 - 0.0.0.2:0002

**Comment by brodao2** [comment]
@wallacefreitas 

Veja se ajuda a configuração do [Local de gravação de servers.json](https://github.com/totvs/tds-vscode/blob/master/docs/servers.md#local-de-grava%C3%A7%C3%A3o-de-serversjson).

**Comment by wallacefreitas** [comment]
@brodao2 

Mas essa configuração organizaria por Workspace correto?

Eu estava pensando em conseguir essa organização dentro de uma única Workspace.

Imagine um cenário em que você atue para vários clientes, e para cada cliente você tenha N serviços, e cada serviço com X ambientes.

Algo mais ou menos assim:

Workspace para projeto do Cliente X

**> [Diretório] Base Teste**
Server Balance 1 - 0.0.0.0:0001
Server Balance 2 - 0.0.0.0:0002

**> [Diretório] Base Homologação**
Server Balance 1 - 0.0.0.1:0001
Server Balance 2 - 0.0.0.1:0002

**> [Diretório] Base Produção**
Server Balance 1 - 0.0.0.2:0001
Server Balance 2 - 0.0.0.2:0002

Pelo que entendi do comportamento da feature do link citado teria que criar uma Workspace para cada "Grupo de Servidores" o que ficaria um pouco "estranho".  Ficando mais ou menos assim:

Workspace 1 Cliente X
Server Teste Balance 1 - 0.0.0.0:0001
Server Teste Balance 2 - 0.0.0.0:0002

Workspace 2 Cliente X
Server Homologação Balance 1 - 0.0.0.1:0001
Server Homologação Balance 2 - 0.0.0.2:0002

**Comment by ricardomansano** [comment]
Boa tarde @wallacefreitas ,
Entendi sua sugestão, mas sua implementação seria cara demais em horas, para o retorno obtido.
Agradeço o contato
Mansano
