### ISSUE TITLE
Melhoria Função de Comparar Fontes Usuario

### ISSUE THREAD

**Issue by vergil250493** [totvs/tds-vscode#1096]
Adicionar um metodo de comparação de fontes de usuários compilados no ambiente X Diretorio projeto comparando por data e hora e que liste as diferença encontra Vice e Versa tanto para fontes que existam no projeto mas não esteja compilado quanto para fontes que existam no RPO e não estejam no projetos, além de lista os fontes que existam em ambos mas a data e hora esteja diferentes.

Filtrando e olhando apenas para o RPO Custom.

**Comment by ricardomansano** [comment]
Boa tarde @vergil250493 ,

Utilize o inspetor de objetos para fazer essa auditoria, automatizar este processo é muito caro em horas para colocar em desenvolvimento, lembrando que esse é um produto colaborativo, fique a vontade para fazer um fork e desenvolver suas melhorias.

Caso queira equalizar os fontes em sua Workspace, basta compilar a pasta (Compile File/Folder), os fontes que tiverem a mesma data não serão recompilados, como pode ver no trecho de OUTPUT abaixo.

[Info  - 5:18:15 PM] Starting build for environment sqlite.
[Info  - 5:18:17 PM] Starting build using RPO token ...
[Info  - 5:18:17 PM] Start file compile.
[Info  - 5:18:17 PM] Using Includes: /media/mansano/storage/bkp_C_1/lib120/src/include
[Info  - 5:18:17 PM] Start regular compiling /media/mansano/storage/projs/advpl/acentuação teste/acento.prw (1/1).
[Info  - 5:18:17 PM] [SKIPPED] Source /media/mansano/storage/projs/advpl/acentuação teste/**acento.prw already compiled**.
[Info  - 5:18:17 PM] Committing end build. This could take a while...
[Info  - 5:18:17 PM] All files compiled successfully.
[Info  - 5:18:17 PM] Compile finished.
