### ISSUE TITLE
Erro de acesso exclusivo ao aplicar mais de 1 patch de uma única vez

### ISSUE THREAD

**Issue by wellperez** [totvs/tds-vscode#1099]
Boa tarde.

**Describe the bug**
Já aconteceu comigo algumas vezes esse problema ao aplicar vários patchs de uma única vez. Geralmente depois de aplicar o primeiro, algum dos patchs subsequentes acaba dando falha na aplicação devido não conseguir acesso exclusivo ao RPO. O que aparenta é que entre a aplicação de um patch e outro, ele não finaliza o acesso anterior para começar aplicar o próximo.

[Info  - 17:36:06] Starting validate server localhost@9979
[Info  - 17:36:06] Trying to connect to server using the build: 7.00.210324P with secure connection
[Info  - 17:36:06] Could not connect to the server
[Info  - 17:36:06] Trying to connect to server using the build: 7.00.210324P without secure connection
[Info  - 17:36:06] Appserver detected with build version: 7.00.210324P without secure connection
[Info  - 17:36:06] Validate server localhost@9979 finished
[Info  - 17:36:09] Starting connection to the server 'EMPRESA DEV' (localhost@9979)
[Info  - 17:36:09] Connection to the server 'EMPRESA DEV' finished.
[Info  - 17:36:16] Starting user 'wellington.perez' authentication.
[Info  - 17:36:16] Secure authenticating...
[Info  - 17:36:20] User authenticated successfully.
[Info  - 17:36:20] User 'wellington.perez' authentication finished.
[Info  - 17:36:39] Starting patch validate.
[Info  - 17:36:39] Patch file: c:/Users/ADMINI~1.DCM/AppData/Local/Temp/3/tds-t9shL4/expedicao_continua_12_1_33_pcp_tttm120_hp.ptm
[Info  - 17:36:39] Starting build for environment hml.
[Info  - 17:36:41] Starting build using RPO token ...
[Info  - 17:36:42] Patch validated without structure problems.
[Info  - 17:36:42] Aborting end build (rollback changes).
[Info  - 17:36:42] Patch validate finished.
[Info  - 17:36:42] Starting function inspector.
[Info  - 17:36:42] Loading functions from server.
[Info  - 17:36:47] Functions loaded (Duration: 4.465000)
[Info  - 17:36:47] 124226 functions successfully retrieved.
[Info  - 17:36:47] Function inspector finished.
[Info  - 17:36:47] Starting patch info.
[Info  - 17:36:47] Patch file: c:/Users/ADMINI~1.DCM/AppData/Local/Temp/3/tds-t9shL4/expedicao_continua_12_1_33_pcp_tttm120_hp.ptm
[Info  - 17:36:47] Starting build for environment hml.
[Info  - 17:36:49] Starting build using RPO token ...
[Info  - 17:36:51] Aborting end build (rollback changes).
[Info  - 17:36:51] Patch info finished.
[Info  - 17:36:51] Starting get patch resource.
[Info  - 17:36:51] Patch file: c:/Users/ADMINI~1.DCM/AppData/Local/Temp/3/tds-t9shL4/expedicao_continua_12_1_33_pcp_tttm120_hp.ptm
[Info  - 17:36:51] Starting build for environment hml.
[Info  - 17:36:53] Starting build using RPO token ...
[Info  - 17:36:55] Aborting end build (rollback changes).
[Info  - 17:36:55] Getting organizations (company/branch)
[Info  - 17:37:00] Starting reconnection to the server 'EMPRESA DEV_rpc'
[Info  - 17:37:00] Authenticating...
[Info  - 17:37:04] User authenticated successfully.
[Info  - 17:37:04] Reconnection to the server 'EMPRESA DEV_rpc' finished.
[Info  - 17:37:04] Validating a package in Protheus application
[Info  - 17:37:04] Secure authenticating...
[Info  - 17:37:08] User authenticated successfully.
[Info  - 17:37:08] Server 'EMPRESA DEV_rpc' successfully disconnected.
[Info  - 17:37:08] Starting apply patch.
[Info  - 17:37:08] Starting build for environment hml.
[Info  - 17:37:13] Starting build using RPO token ...
[Info  - 17:37:13] Applying patch file: c:/Users/ADMINI~1.DCM/AppData/Local/Temp/3/tds-t9shL4/expedicao_continua_12_1_33_pcp_tttm120_hp.ptm
[Info  - 17:37:21] Patch (expedicao_continua_12_1_33_pcp_tttm120_hp.ptm) successfully applied.
[Info  - 17:37:21] Committing end build. This could take a while...
[Info  - 17:37:26] Apply patch finished.
[Info  - 17:37:26] Starting patch validate.
[Info  - 17:37:26] Patch file: c:/Users/ADMINI~1.DCM/AppData/Local/Temp/3/tds-8gpqbU/expedicao_continua_12_1_33_atf_tttm120_hp.ptm
[Info  - 17:37:26] Starting build for environment hml.
[Info  - 17:37:29] Starting build using RPO token ...
[Info  - 17:37:29] Patch validated without structure problems.
[Info  - 17:37:29] Aborting end build (rollback changes).
[Info  - 17:37:30] Patch validate finished.
[Info  - 17:37:30] Starting function inspector.
[Info  - 17:37:30] Loading functions from server.
[Info  - 17:37:34] Functions loaded (Duration: 4.425000)
[Info  - 17:37:34] 124258 functions successfully retrieved.
[Info  - 17:37:34] Function inspector finished.
[Info  - 17:37:34] Starting patch info.
[Info  - 17:37:34] Patch file: c:/Users/ADMINI~1.DCM/AppData/Local/Temp/3/tds-8gpqbU/expedicao_continua_12_1_33_atf_tttm120_hp.ptm
[Info  - 17:37:34] Starting build for environment hml.
[Info  - 17:37:37] Starting build using RPO token ...
[Info  - 17:37:37] Aborting end build (rollback changes).
[Info  - 17:37:37] Patch info finished.
[Info  - 17:37:37] Starting get patch resource.
[Info  - 17:37:37] Patch file: c:/Users/ADMINI~1.DCM/AppData/Local/Temp/3/tds-8gpqbU/expedicao_continua_12_1_33_atf_tttm120_hp.ptm
[Info  - 17:37:37] Starting build for environment hml.
[Info  - 17:37:40] Starting build using RPO token ...
[Info  - 17:37:41] Aborting end build (rollback changes).
[Info  - 17:37:41] Getting organizations (company/branch)
[Info  - 17:37:46] Starting reconnection to the server 'EMPRESA DEV_rpc'
[Info  - 17:37:46] Authenticating...
[Info  - 17:37:53] User authenticated successfully.
[Info  - 17:37:53] Reconnection to the server 'EMPRESA DEV_rpc' finished.
[Info  - 17:37:53] Validating a package in Protheus application
[Info  - 17:37:53] Secure authenticating...
[Info  - 17:37:57] User authenticated successfully.
[Info  - 17:37:57] Server 'EMPRESA DEV_rpc' successfully disconnected.
[Info  - 17:37:57] Starting apply patch.
[Info  - 17:37:57] Starting build for environment hml.
[Error - 17:38:17] std::runtime_error
[Error - 17:38:17] Start build error: Server returned: 
[DBGSTARTBUILD][OPENAPO] It wasn't possible to obtain exclusive access to the objects repository.

[Error - 17:38:17] Patch validate could not be executed.
[Info  - 17:38:17] Starting patch validate.
[Info  - 17:38:17] Patch file: c:/Users/ADMINI~1.DCM/AppData/Local/Temp/3/tds-fgyFmt/expedicao_continua_12_1_33_pco_tttm120_hp.ptm
[Info  - 17:38:17] Starting build for environment hml.
[Info  - 17:38:18] Starting build using RPO token ...
[Info  - 17:38:18] Patch validated without structure problems.
[Info  - 17:38:18] Aborting end build (rollback changes).
[Info  - 17:38:19] Patch validate finished.
[Info  - 17:38:19] Starting function inspector.
[Info  - 17:38:19] Loading functions from server.
[Info  - 17:38:23] Functions loaded (Duration: 4.670000)
[Info  - 17:38:23] 124258 functions successfully retrieved.
[Info  - 17:38:23] Function inspector finished.
[Info  - 17:38:23] Starting patch info.
[Info  - 17:38:23] Patch file: c:/Users/ADMINI~1.DCM/AppData/Local/Temp/3/tds-fgyFmt/expedicao_continua_12_1_33_pco_tttm120_hp.ptm
[Info  - 17:38:23] Starting build for environment hml.
[Info  - 17:38:26] Starting build using RPO token ...
[Info  - 17:38:27] Aborting end build (rollback changes).
[Info  - 17:38:27] Patch info finished.
[Info  - 17:38:27] Starting get patch resource.
[Info  - 17:38:27] Patch file: c:/Users/ADMINI~1.DCM/AppData/Local/Temp/3/tds-fgyFmt/expedicao_continua_12_1_33_pco_tttm120_hp.ptm
[Info  - 17:38:27] Starting build for environment hml.
[Info  - 17:38:30] Starting build using RPO token ...
[Info  - 17:38:30] Aborting end build (rollback changes).
[Info  - 17:38:30] Getting organizations (company/branch)
[Info  - 17:38:35] Starting reconnection to the server 'EMPRESA DEV_rpc'
[Info  - 17:38:36] Authenticating...
[Info  - 17:38:42] User authenticated successfully.
[Info  - 17:38:42] Reconnection to the server 'EMPRESA DEV_rpc' finished.
[Info  - 17:38:42] Validating a package in Protheus application
[Info  - 17:38:42] Secure authenticating...
[Info  - 17:38:46] User authenticated successfully.
[Info  - 17:38:49] Server 'EMPRESA DEV_rpc' successfully disconnected.
[Info  - 17:38:49] Starting apply patch.
[Info  - 17:38:49] Starting build for environment hml.
[Info  - 17:38:54] Starting build using RPO token ...
[Info  - 17:38:54] Applying patch file: c:/Users/ADMINI~1.DCM/AppData/Local/Temp/3/tds-fgyFmt/expedicao_continua_12_1_33_pco_tttm120_hp.ptm
[Info  - 17:38:58] Patch (expedicao_continua_12_1_33_pco_tttm120_hp.ptm) successfully applied.
[Info  - 17:38:58] Committing end build. This could take a while...
[Info  - 17:39:07] Apply patch finished.
[Info  - 17:39:07] Starting patch validate.
[Info  - 17:39:07] Patch file: c:/Users/ADMINI~1.DCM/AppData/Local/Temp/3/tds-pmorUV/expedicao_continua_12_1_33_backoffice_tttm120_hp.ptm
[Info  - 17:39:07] Starting build for environment hml.
[Info  - 17:39:10] Starting build using RPO token ...
[Info  - 17:39:20] Patch validated without structure problems.
[Info  - 17:39:20] Aborting end build (rollback changes).
[Info  - 17:39:20] Patch validate finished.
[Info  - 17:39:20] Starting function inspector.
[Info  - 17:39:20] Loading functions from server.
[Info  - 17:39:25] Functions loaded (Duration: 4.242000)
[Info  - 17:39:25] 124266 functions successfully retrieved.
[Info  - 17:39:25] Function inspector finished.
[Info  - 17:39:25] Starting patch info.
[Info  - 17:39:25] Patch file: c:/Users/ADMINI~1.DCM/AppData/Local/Temp/3/tds-pmorUV/expedicao_continua_12_1_33_backoffice_tttm120_hp.ptm
[Info  - 17:39:25] Starting build for environment hml.
[Info  - 17:39:27] Starting build using RPO token ...
[Info  - 17:39:36] Aborting end build (rollback changes).
[Info  - 17:39:37] Patch info finished.
[Info  - 17:39:37] Starting get patch resource.
[Info  - 17:39:37] Patch file: c:/Users/ADMINI~1.DCM/AppData/Local/Temp/3/tds-pmorUV/expedicao_continua_12_1_33_backoffice_tttm120_hp.ptm
[Info  - 17:39:37] Starting build for environment hml.
[Info  - 17:39:39] Starting build using RPO token ...
[Info  - 17:39:48] Aborting end build (rollback changes).
[Info  - 17:39:48] Getting organizations (company/branch)
[Info  - 17:39:53] Starting reconnection to the server 'EMPRESA DEV_rpc'
[Info  - 17:39:53] Authenticating...
[Info  - 17:40:00] User authenticated successfully.
[Info  - 17:40:00] Reconnection to the server 'EMPRESA DEV_rpc' finished.
[Info  - 17:40:00] Validating a package in Protheus application
[Info  - 17:40:00] Secure authenticating...
[Info  - 17:40:04] User authenticated successfully.
[Info  - 17:40:04] Server 'EMPRESA DEV_rpc' successfully disconnected.
[Info  - 17:40:04] Starting apply patch.
[Info  - 17:40:04] Starting build for environment hml.
[Info  - 17:40:09] Starting build using RPO token ...
[Info  - 17:40:09] Applying patch file: c:/Users/ADMINI~1.DCM/AppData/Local/Temp/3/tds-pmorUV/expedicao_continua_12_1_33_backoffice_tttm120_hp.ptm
[Info  - 17:40:51] Patch (expedicao_continua_12_1_33_backoffice_tttm120_hp.ptm) successfully applied.
[Info  - 17:40:51] Committing end build. This could take a while...
[Info  - 17:41:04] Apply patch finished.
[Info  - 17:42:14] Starting patch validate.
[Info  - 17:42:14] Patch file: c:/Users/ADMINI~1.DCM/AppData/Local/Temp/3/tds-w3tTMW/expedicao_continua_12_1_33_atf_tttm120_hp.ptm
[Info  - 17:42:14] Starting build for environment hml.
[Info  - 17:42:19] Starting build using RPO token ...
[Info  - 17:42:20] Patch validated without structure problems.
[Info  - 17:42:20] Aborting end build (rollback changes).
[Info  - 17:42:20] Patch validate finished.
[Info  - 17:42:20] Starting function inspector.
[Info  - 17:42:20] Loading functions from server.
[Info  - 17:42:24] Functions loaded (Duration: 4.762000)
[Info  - 17:42:24] 124337 functions successfully retrieved.
[Info  - 17:42:24] Function inspector finished.
[Info  - 17:42:24] Starting patch info.
[Info  - 17:42:24] Patch file: c:/Users/ADMINI~1.DCM/AppData/Local/Temp/3/tds-w3tTMW/expedicao_continua_12_1_33_atf_tttm120_hp.ptm
[Info  - 17:42:24] Starting build for environment hml.
[Info  - 17:42:28] Starting build using RPO token ...
[Info  - 17:42:28] Aborting end build (rollback changes).
[Info  - 17:42:28] Patch info finished.
[Info  - 17:42:28] Starting get patch resource.
[Info  - 17:42:28] Patch file: c:/Users/ADMINI~1.DCM/AppData/Local/Temp/3/tds-w3tTMW/expedicao_continua_12_1_33_atf_tttm120_hp.ptm
[Info  - 17:42:28] Starting build for environment hml.
[Info  - 17:42:31] Starting build using RPO token ...
[Info  - 17:42:32] Aborting end build (rollback changes).
[Info  - 17:42:32] Getting organizations (company/branch)
[Info  - 17:42:38] Starting reconnection to the server 'EMPRESA DEV_rpc'
[Info  - 17:42:38] Authenticating...
[Info  - 17:42:45] User authenticated successfully.
[Info  - 17:42:45] Reconnection to the server 'EMPRESA DEV_rpc' finished.
[Info  - 17:42:45] Validating a package in Protheus application
[Info  - 17:42:45] Secure authenticating...
[Info  - 17:42:49] User authenticated successfully.
[Info  - 17:42:52] Server 'EMPRESA DEV_rpc' successfully disconnected.
[Info  - 17:42:52] Starting apply patch.
[Info  - 17:42:52] Starting build for environment hml.
[Info  - 17:42:57] Starting build using RPO token ...
[Info  - 17:42:57] Applying patch file: c:/Users/ADMINI~1.DCM/AppData/Local/Temp/3/tds-w3tTMW/expedicao_continua_12_1_33_atf_tttm120_hp.ptm

**Desktop (please complete the following information):**
Windows Server 2019 Standard
VsCode 1.74.2

**Appserver (please complete the following information):**
Windows Server 2019 Standard
* TOTVS - Build 7.00.210324P - Oct  6 2021 - 23:33:57 
* Build: 64 bits
* SVN Revision: 32672
* Build Version: 20.3.0.2

**Comment by lwtnb-wrk** [comment]
@wellperez Voce tem a chave BuildKillUsers=1 na seção [General] configurada?

**Comment by lwtnb-wrk** [comment]
@wellperez Ah e se possivel, atualize seu AppServer para a ultima versao do portal

**Comment by wellperez** [comment]
> @wellperez Voce tem a chave BuildKillUsers=1 na seção [General] configurada?

SIm, está com a chave.

**Comment by wellperez** [comment]
> @wellperez Ah e se possivel, atualize seu AppServer para a ultima versao do portal

Assim que conseguir fazer o teste com a outra versão eu reporto.

**Comment by lwtnb-wrk** [comment]
@wellperez O problema foi resolvido com a atualização do AppServer?

**Comment by ricardomansano** [comment]
Bom dia @wellperez , caso o problema prossiga com o ambiente atualizado, pode nos contactar novamente
