### ISSUE TITLE
Depurador percorre sempre a declaração das variáveis estáticas.

### ISSUE THREAD

**Issue by Vitor-Santos-Totvs** [totvs/tds-vscode#11]
Depurador percorre sempre a declaração das variáveis estáticas antes de cair na função chamada pelo vscode, mesmo que não haja nenhum breakpoint nestas declarações estáticas e mesmo que a opção de multi thread esteja desabilitada. Acredito que isso aconteça porque uma thread separada faz a declaração dessas variáveis e outra thread inicia o programa chamado pelo vscode, pois ao apertar F5 na declaração das estáticas, o depurador pula para a execução correta chamada pelo vscode.

**Comment by lwtnb-wrk** [comment]
@Vitor-Santos-Totvs poderia dar mais detalhes de como podemos reproduzir esse cenario? 
Grato pelos teste!

**Comment by Vitor-Santos-Totvs** [comment]
Tenho um projeto onde em um fonte há várias declarações de variáveis estáticas e sempre que eu inicio a depuração do projeto, chamando uma user function que está em um fonte diferente das estáticas, o depurador inicia a execução pela declaração de todas as variáveis estáticas antes de sequer chamar minha user function e só após declara-las que começa a execução. Nesse fonte onde estão as estáticas, não há nenhum breakpoint. Seguem algumas imagens para exemplificar melhor, caso tenha alguma dúvida é só me avisar.
Agradeço pela atenção.
Essa é a função q estou chamando:
![image](https://user-images.githubusercontent.com/50745570/58210072-ba230b00-7cbe-11e9-8dd2-9fd2316367a2.png)
Porém a depuração inicia aqui:
![image](https://user-images.githubusercontent.com/50745570/58210108-d7f07000-7cbe-11e9-98f6-03b6475cc033.png)

**Comment by lwtnb-wrk** [comment]
@Vitor-Santos-Totvs Comecei a ver essa issue e fiz alguns testes, mas não consegui reproduzir o comportamento que voce menciona. Tenho uma user function que chama outras user function em outros fontes. Declarei variaveis estaticas nesses outros fontes mas eles so esta sendo chamados quando a minha user function principal chama esses outros fontes... Teria como tentar criar um cenario bem minimalista que reproduza o problema? Grato pelos testes.

**Comment by Vitor-Santos-Totvs** [comment]
Tentei isolar o problema mas inicialmente nao estava conseguindo em uma plataforma que tinha só tinha esse plugin novo. Porém reparei que o problema voltou a acontecer quando instalei o plugin antigo do advpl, portanto acredito que esse problema é alguma interferência da configuração de debug do plugin antigo nesse novo. Vou tentar confirmar como simular corretamente o problema e comento aqui como fiz.

**Comment by lwtnb-wrk** [comment]
@Vitor-Santos-Totvs Vou fechar essa issue como não reproduzida então. Grato pelos testes
