### ISSUE TITLE
Lista de fontes

### ISSUE THREAD

**Issue by romasp** [totvs/tds-vscode#110]
Boa tarde !
Percebi que, tanto na lista de fontes no explorador, quanto ao usar a opção de localizar nos arquivos, são exibidos/considerados arquivos de todas as extensões (*.PRW, *.BAK, *.OLD etc).
Existe alguma configuração para filtrar somente arquivos ADVPL/TL++ ?
Muito obrigado !

**Comment by lwtnb-wrk** [comment]
@romasp Na lista de fontes no explorador realmente são exibidos todos os arquivos e não acredito que deveria ser diferente. De qualquer forma isso é padrão do VsCode.

Mas na opção de localizar nos arquivos, experimente clicar nos "..." logo abaixo a direita do campo de pesquisa (fica abaixo do icone ".*"). Ele abre outros campos de inclusão e exclusão onde voce pode colocar um filtro como o *.prw na inclusão, então a pesquisa ocorrera somente nos fontes .prw. 
Veja se isso te atende.

**Comment by DanielYampolschi** [comment]
Ola @romasp, sua dúvida parece mais relacionada à usabilidade do VsCode em si. Verifica se a opção 
"Edit -> "Find in Files" é o que você procura

**Comment by romasp** [comment]
Muito obrigado pelas respostas !
