### ISSUE TITLE
ERRO AO INSERIR VALORES NO BANCO VIA ADVPL 

### ISSUE THREAD

**Issue by FerrerAndreas** [totvs/tds-vscode#1100]
Pesquiso, corrijo, coloco no chatgpt e não aparenta erro e é retornado certo o que eu fiz no código, porém no banco não é inserido valor algum

#INCLUDE "totvs.ch"
#INCLUDE "TopConn.ch"
#INCLUDE "rwMake.ch"
#INCLUDE "protheus.ch"
#INCLUDE "tbiconn.ch"

User Function RKMARCA()

local cSql := ""
local aResult := {}

cSql := "select ROW_NUMBER() OVER (ORDER BY sum(RESULTADO.VALOR) DESC) AS 'RK_MARCA' "
cSql += "from (SELECT B1_XDESCM AS MARCA,(CASE WHEN (Z7_TPOPER='1') THEN ((Z7_QUANT)) "
cSql += "ELSE ((-Z7_QUANT)) END) AS QUANTIDADE, "
cSql += "ROUND((CASE WHEN (Z7_TPOPER='1') THEN (((Z7_QUANT * Z7_PRCVEN))) "  
cSql += "ELSE ((-(Z7_QUANT * Z7_PRCVEN)))END),2) AS VALOR,	'' CURVA_DOMA, '' CURVA_MARCA "
cSql += "FROM SZ7010 " 
cSql += "INNER JOIN SZ6010 ON SZ7010.Z7_DOC = SZ6010.Z6_DOC AND SZ7010.Z7_SERIE = SZ6010.Z6_SERIE "
cSql += "LEFT JOIN SB1010 ON SB1010.D_E_L_E_T_='' AND B1_COD = Z7_COD "
cSql += "LEFT JOIN SA3010 ON SA3010.D_E_L_E_T_='' AND A3_COD = Z6_CODVEND "
cSql += "INNER JOIN SZ0010 ON Z0_CODIGO = B1_XMARCA AND SZ0010.D_E_L_E_T_='' "
cSql += "WHERE SZ7010.D_E_L_E_T_='' "
cSql += "AND Z7_ESTOQUE IN ('S','E') "
cSql += "AND Z7_TPOPER IN ('1','2') "
cSql += "AND CONVERT(DATE,Z7_EMISSAO, 103) >= CONVERT(DATE,DATEADD(YEAR,-1,GETDATE()) ,103) "
cSql += "AND CONVERT(DATE,Z7_EMISSAO, 103) <= CONVERT(DATE, GETDATE() ,103) "

cSql += " UNION all "

cSql += "SELECT B1_XDESCM AS MARCA, D2_QUANT AS QUANTIDADE, "
cSql += "ROUND(D2_VALBRUT - D2_SEGURO,2) AS VALOR,'' CURVA_DOMA,'' CURVA_MARCA "
cSql += "FROM SD2010 "
cSql += "LEFT JOIN SC5010 ON SC5010.D_E_L_E_T_='' AND C5_NUM = D2_PEDIDO AND C5_FILIAL = D2_FILIAL "
cSql += "LEFT JOIN SB1010 ON SB1010.D_E_L_E_T_='' AND B1_COD = D2_COD "
cSql += "INNER JOIN SA3010 ON SA3010.D_E_L_E_T_='' AND SA3010.A3_COD = C5_VEND1 "
cSql += "INNER JOIN SZ0010 ON Z0_CODIGO = B1_XMARCA AND SZ0010.D_E_L_E_T_='' "
cSql += "WHERE SD2010.D_E_L_E_T_=''  AND C5_X_TPOPE IN ('01','09','18') "
cSql += "AND CONVERT(DATE,D2_EMISSAO, 103) >= CONVERT(DATE,DATEADD(YEAR,-1,GETDATE()) ,103) "
cSql += "AND CONVERT(DATE,D2_EMISSAO, 103) <= CONVERT(DATE, GETDATE() ,103) "

cSql += "UNION all "

cSql += "SELECT B1_XDESCM AS MARCA,-D1_QUANT AS QUANTIDADE "
cSql += ", -D1_QUANT * D1_VUNIT AS VALOR,	'' CURVA_DOMA,	'' CURVA_MARCA "
cSql += "FROM SD1010 "
cSql += "INNER JOIN SC5010 ON C5_NOTA = D1_NFORI AND C5_FILIAL = D1_FILORI AND SC5010.D_E_L_E_T_='' AND C5_X_TPOPE IN ('01','09','18') "
cSql += "LEFT JOIN SB1010 ON SB1010.D_E_L_E_T_='' AND B1_COD = D1_COD "
cSql += "INNER JOIN SA3010 ON SA3010.D_E_L_E_T_='' AND SA3010.A3_COD = C5_VEND1 "
cSql += "INNER JOIN SZ0010 ON Z0_CODIGO = B1_XMARCA AND SZ0010.D_E_L_E_T_='' "
cSql += "WHERE SD1010.D_E_L_E_T_='' AND D1_TIPO='D'  "

cSql += "AND CONVERT(DATE,D1_EMISSAO, 103) >= CONVERT(DATE,DATEADD(YEAR,-1,GETDATE()) ,103) "
cSql += "AND CONVERT(DATE,D1_EMISSAO, 103) <= CONVERT(DATE, GETDATE() ,103) "
cSql += "and B1_XMARCA != '') RESULTADO "
cSql += "group by RESULTADO.MARCA "

// Executa o comando SQL criando uma tabela temporária
TCQUERY cQuery NEW ALIAS "QRANKING"
cQuery->(DbExecSQL(cSql))

// Abre a área da tabela temporária
DbSelectArea("QRANKING")

// Cria um array com os valores da coluna RK_MARCA da tabela temporária
While !QRANKING->(Eof())
    aAdd(aResult, QRANKING->(FieldGet("RK_MARCA")))
    QRANKING->(DbSkip())
EndDo

// Fecha a área da tabela temporária
QRANKING->(DbCloseArea())

// Percorre os registros da tabela SZ0 e atualiza a coluna Z0_RKMARCA com os valores do array
DbSelectArea("SZ0")
While !SZ0->(Eof())
    RecLock("SZ0", .F.)
    SZ0->Z0_RKMARCA := aResult[SZ0->Z0_CODIGO]
    MsUnlock()
    SZ0->(DbSkip())
EndDo

Return

**Comment by lwtnb-wrk** [comment]
@FerrerAndreas Tratamos aqui apenas de problemas na ferramenta tds-vscode. Grato.
