### ISSUE TITLE
Não Debuga API REST

### ISSUE THREAD

**Issue by elvissiq** [totvs/tds-vscode#1101]
- Versão do Plugin 1.3.17

Pessoal, não consigo de forma alguma debugar fontes de aplicação REST, 
Conseguem dar um apoio, antes eu conseguia na boa, agora não consigo mais. 

Já ativei o "isMultiSession": true no arquivo launsh.json e starto o debug utilizando a Function XXXXXXXX, mas não vai de forma alguma.

* TOTVS - Build 7.00.210324P - Feb 28 2023 - 22:59:52
* Build: 64 bits
* SVN Revision: 38079
* Build Version: 20.3.1.4

Segue vídeo demonstrando o processo - [Debug REST.zip](https://github.com/totvs/tds-vscode/files/11054645/Debug.REST.zip)

![image](https://user-images.githubusercontent.com/76496310/227308108-7cf9b64f-7542-403c-b1d2-e344914f97c2.png)

**Comment by lwtnb-wrk** [comment]
@elvissiq Temos uma outra ocorrência referente a debug de REST que estamos analisando. Isso pode ser algum comportamento do AppServer que não "para" em alguns breakpoints, por razões ainda desconhecidas.
Experimente colocar mais pontos de paradas pelo seu fonte para verificar se ele para em outro ponto além do que apresentado no vídeo.
Tambem veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise. Em especial o dap.log por se tratar de problema no debug.

Outro ponto importante é que o fonte precisa estar compilado e atualizado no RPO, parece obvio, mas é bom sempre deixar isso claro também rsrsrs

**Comment by elvissiq** [comment]
Segue o arquivo dap.log gerado.
[dap.log](https://github.com/totvs/tds-vscode/files/11054980/dap.log)

**Comment by lwtnb-wrk** [comment]
@elvissiq  Ops, não tinha notado anteriormente, mas acho que você está usando a configuração incorreta para este tipo de depuração. Ao inves de usar o "isMultiSession": true, você deve usar o "enableMultiThread": true
Veja se é isso que está causando o seu problema.

**Comment by elvissiq** [comment]
Alterei para enableMultiThread para ainda assim não parou nos pontos de debug.

**Comment by lwtnb-wrk** [comment]
@elvissiq Tem novos logs para podermos analisar?

**Comment by lwtnb-wrk** [comment]
Encerrando por falta de retorno

**Comment by jpinto10** [comment]
Bom dia, @lwtnb-wrk 
Posso assumir o problema!?

Estou com a mesma "dor".

O codigo do erro é:
[09:48:11] INFO: Application Server connected.
[09:48:11] INFO: TDS-DA ready.
[09:48:18] INFO: SmartClient closed. ExitCode=62097 ExistStatus=CancelExit
[09:48:18] INFO: TDS-DA finished.

obs.: 
ja coloquei:
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "FBS_CONTAGEM",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "C:/Users/Edilson/Desktop/SMARTCLIENT_2210_contagem/SMARTCLIENT_2210/SmartClient.exe",
			"isMultiSession": true,
			"enableTableSync": true,
			"enableMultiThread": true,
			"waitForAttach": 5,
			"logFile": "${workspaceFolder}\\dap.log"


[dap.log](https://github.com/totvs/tds-vscode/files/11916375/dap.log)

**Comment by lwtnb-wrk** [comment]
@jpinto10 Veja se a documentação em https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md#depura%C3%A7%C3%A3o-de-servi%C3%A7os-jobs ajuda, pois depurar serviço REST/Jobs tem particularidades.
Caso não consiga, abra uma nova issue e adicione o máximo de informações que tiver para que possamos analisar.
