### ISSUE TITLE
Erro comentario com &&

### ISSUE THREAD

**Issue by danielblaia** [totvs/tds-vscode#1103]
Bom dia
estou com o plugin Totvs Developer Studio 1.3.17 instalado no VS Code
notei que as linhas não aparecem com comentario quando se usa a sintaxe &&

se eu faço comentario com // ou /* fica comentado, mas com && não

abraços

**Comment by lwtnb-wrk** [comment]
@danielblaia Grato por avisar. 
Consultei o time aqui e ninguém conhecia essa questão do uso do && como comentário. Parece ser uma coisa bem antiga e já deixou de ser usada a um bom tempo. Inclusive nem consta mais da documentação oficial da TOTVS https://tdn.totvs.com/pages/releaseview.action?pageId=22480445
Enfim, agradecemos novamente sua mensagem, mas não faremos alterações, pois atualmente, fontes APH utilizam && como operador AND, então se alterássemos isso teríamos efeitos colaterais diverso.
Aconselhamos, onde possível, a atualizar o fonte para utilizar o padrão atual com comentários com //
