### ISSUE TITLE
Não consigo conectar o VSCode com o Server do Protheus

### ISSUE THREAD

**Issue by RobertoZoadelli** [totvs/tds-vscode#1104]
Bom dia!

Estou com problema para conectar o VSCode com o Server do Protheus.

[Info  - 10:37:22 AM] Starting connection to the server 'DBRH' (localhost@1234)
[Error - 10:37:22 AM] Connection failed. Could not connect to server localhost:1234.

{
	"version": "0.2.0",
	"includes": [
		"D:\\TOTVS\\Protheus\\Protheus\\include"
	],
	"permissions": {
		"authorizationtoken": ""
	},
	"connectedServer": {},
	"configurations": [
		{
			"id": "t1n1ucdnk4lfwijupo6a9uxr3eevh",
			"type": "totvs_server_protheus",
			"name": "DBRH",
			"port": 1234,
			"address": "localhost",
			"buildVersion": "7.00.210324P",
			"secure": false,
			"includes": [
				"D:\\TOTVS\\Protheus\\Protheus\\include"
			],
			"environments": [
				"environment"
			]
		}
	],
	"savedTokens": []
}

Ini

[environment]
SourcePath=d:\TOTVS\Protheus\protheus\apo
RPOCustom=d:\TOTVS\Protheus\protheus\custom.rpo
RootPath=d:\TOTVS\Protheus\protheus_data
StartPath=\system\
RpoCustom=d:\TOTVS\Protheus\protheus\apo\custom.rpo
x2_path=
RpoDb=top
RpoLanguage=multi
RpoVersion=120
LocalFiles=CTREE
Trace=0
localdbextension=.dtc
StartSysInDB=1
topmemomega=50

[DBAccess]
DataBase=MSSQL
server=localhost
Port=7890
ALIAS=DBRH
ProtheusOnluy=0

[GENERAL]
MaxQuerySize=31960
Consolelog=1
MaxStringSize=500
BUILDKILLUSERS=1

[Drivers]
Active=TCP
MULTIPROTOCOLPORT=0
;MULTIPROTOCOLPORTSECURE=0

[APP_MONITOR]
enable=0

[TCP]
TYPE=TCPIP
Port=1234

[TDS]
ALLOWAPPLYPATCH=*
ALLOWEDIT=*

[LICENSECLIENT]
server=localhost
port=5555

[Service]
Name=TOTVS-Appserver12
DisplayName=TOTVS | Appserver 12

[WEBAPP]
;port=4321
;[WebApp/webapp]
;MPP=

**Comment by RobertoZoadelli** [comment]
![image](https://user-images.githubusercontent.com/129523165/229138443-f4819d51-8491-4649-844a-e9df61492835.png)

**Comment by lwtnb-wrk** [comment]
@RobertoZoadelli Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by RobertoZoadelli** [comment]
@lwtnb-wrk  Bom dia! Obrigado pelo retorno. 
Seguem os logs para analise.

[totvsls_out.log](https://github.com/totvs/tds-vscode/files/11123161/totvsls_out.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/11123162/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/11123163/totvsls_in.log)

**Comment by lwtnb-wrk** [comment]
@RobertoZoadelli Você alterou alguma configuração de seu AppServer após sua criação? Enfim, você pode tentar apagar o registro atual e recriá-lo para ver se ajuda.
Caso ainda não consiga se conectar, você consegue acessar este AppServer diretamente através de um Smartclient?

**Comment by RobertoZoadelli** [comment]
@lwtnb-wrk Esse AppServer é uma instalação padrão, como não consegui acessar pelo VSCode, fiz várias alterações no ini para ver se dava certo. 

Eu acesso esse AppServer através do SmartClient perfeitamente. 

Eu não entendi quando vc fala de recriar o registro. O que seria esse registro? Se for a conexão no VSCode, eu refiz, e continua com o mesmo problema. 

![image](https://user-images.githubusercontent.com/129523165/229183821-cd878a83-72d7-4f2a-b6c8-baf415e013b1.png)

**Comment by lwtnb-wrk** [comment]
@RobertoZoadelli Agora reparei na versão da sua instalação e esta super desatualizada. Atualize e veja se isso resolve. Alias, depois de atualizar, se continuar a falhar, apague e crie novamente o servidor para ter certeza... 
Se continuar com problema, reenvie os logs com as novas tentativas.

**Comment by RobertoZoadelli** [comment]
@lwtnb-wrk Oque está desatualizado? O Vscode ou o AppServer?

**Comment by lwtnb-wrk** [comment]
@RobertoZoadelli Sua extensão tds-vscode. Estamos na versão 1.3.17 e você ainda utiliza a versão 1.0.6 que nem lembro de quando foi lançada...

**Comment by RobertoZoadelli** [comment]
@lwtnb-wrk  Fiz a atualização conforme informado e deu certo. 
Muito obrigado. Acabei não me atendando de atualizar essa extensão.
