### ISSUE TITLE
Erro com gerar o client de um WSDL pelo VSCode

### ISSUE THREAD

**Issue by Zoadelli** [totvs/tds-vscode#1105]
Boa tarde!

Estou tentando gerar um cliente de um WSDL pelo Vscode, só que está retornando um erro:

VSCode:
[Info  - 5:29:24 PM] Starting generate Wsdl.
[Info  - 5:29:24 PM] Generating WSDL client at server.
[Error - 5:29:27 PM] *** ERRO AO GERAR FONTE ADVPL ***
Source URL : https://ws1.soc.com.br/WSSoc/services/CargoWs?wsdl
-------------------------------------------------------------------------------
variable is not array - Type [C]
ADVPL WSDL Client 1.120703 / TOTVS Servi�os Desenv on 20230331 17:29:30
-------------------------------------------------------------------------------
[Info  - 5:29:27 PM] Generate Wsdl finished.

Console.log:
[INFO ][SERVER] [Thread  5456] JOB Thread finished [-WSDLSOURCE]
2023-03-31T17:29:30.635000-03:00 5844|
[ERROR][SERVER] *** ERRO AO GERAR FONTE ADVPL ***
Source URL : https://ws1.soc.com.br/WSSoc/services/CargoWs?wsdl
-------------------------------------------------------------------------------
variable is not array - Type [C]
ADVPL WSDL Client 1.120703 / TOTVS Serviços Desenv on 20230331 17:29:30

-------------------------------------------------------------------------------

Tela para criação do Client WSDL com os Methodos:

![image](https://user-images.githubusercontent.com/73349271/229223493-6c9c3309-d02d-46e7-9123-632e33eb13de.png)

Tela com erro
![image](https://user-images.githubusercontent.com/73349271/229223675-74fd2284-8139-4a22-9b18-b2d1cd372fd8.png)

**Comment by lwtnb-wrk** [comment]
@Zoadelli Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar, e nos envie os logs para analise.
Já adianto que provavelmente é falha na geração por parte do método que chamamos, e nós do tds-vscode apenas chamamos essa funcionalidade.

**Comment by Zoadelli** [comment]
@lwtnb-wrk Bom dia!
Seguem os logs.

[totvsls_out.log](https://github.com/totvs/tds-vscode/files/11138602/totvsls_out.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/11138603/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/11138604/totvsls_in.log)

**Comment by Zoadelli** [comment]
@lwtnb-wrk  Muito obrigado.
