### ISSUE TITLE
Erro ao compilar

### ISSUE THREAD

**Issue by renanpaivamobi** [totvs/tds-vscode#1106]
Ao tentar compilar recebo o erro C2001  Syntax error: appre Ln 1, Col 1

Para reproduzir:
1. Tentar compilar qualquer fonte.

Erro:
<img width="237" alt="image" src="https://user-images.githubusercontent.com/39959748/232146417-3f40622c-62fe-4e17-96af-df8c04a541fc.png">

 O problema ocorre no Windows 11 (x64) e MacOS Ventura (não tentei em Linux)

**Appserver (please complete the following information):**
 - Build (with date): 7.00.210324P-20221215 - 64 bits
 - OS/Architecture: Windows Server 2012 R2
 - Build Version 20.3.1.2

**Comment by lwtnb-wrk** [comment]
@renanpaivamobi Geralmente esse tipo de erro ocorre quando os includes não estão configurados corretamente.
https://github.com/totvs/tds-vscode/blob/master/docs/compilation.md

Se não for seu caso, veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para análise.

**Comment by lwtnb-wrk** [comment]
@renanpaivamobi Se sua pasta de include esta em c:/include, verifique se a pasta está realmente integra.
Experimente baixar novamente a pasta do Portal de Downloads, pois a única coisa que imagino, seria que tem algum problema nessa pasta de include em particular.

Se puder compartilhar esse arquivo rscont.prw podemos verificar se tem algum problema em particular neste arquivo...

**Comment by brodao2** [comment]
@renanpaivamobi 

Após atualizar a pasta de includes e o erro continuar, favor anexar o fonte ou enviar direto para mim em acandido@totvs.com.br.

A disposição.

**Comment by lwtnb-wrk** [comment]
@renanpaiva64 Compilei esse fonte "rscont.prw" sem problemas, com a última pasta de includes disponibilizada no portal de downloads (23-03-22-P12_INCLUDES.ZIP). Dentro da sua pasta de includes "c:/include" você deve ter todos os arquivos CH disponibilizado neste arquivo zipado (149 arquivos na versão acima mencionada).

Seu AppServer está rodando em um Windows Server 2012 correto? Mas seu tds-vscode está rodando em qual SO??

**Comment by renanpaiva64** [comment]
Um outro consultor consegue, mas ao configurarmos em outros PC's não conseguimos. 

Tentei no Windows Server 2018, Windows 11 e MacOS Ventura 13.3.1

Sim, o server 2012 T-Cloud.
Todos com o mesmo erro.

**Comment by lwtnb-wrk** [comment]
@renanpaiva64 A única coisa que pode ter dado diferença entre meu ambiente que funciona e o seu, pode ser o AppServer, pois estou utilizando a última versão do portal 20.3.1.4.
Experimente atualizar seu AppServer para ver se resolve, mas ainda acho que parece ser alguma configuração/ambiente que ainda não está correta...

**Comment by renanpaiva64** [comment]
@lwtnb-wrk o problema é que com a mesma configuração, mas em outra instalação do Protheus eu consigo compilar sem problemas.

**Comment by lwtnb-wrk** [comment]
@renanpaiva64 Essa é exatamente a questão, algo diferente de configuração nesse ambiente está causando esse seu problema, mas a partir dos logs não identificamos nenhum problema aparente.
Se quiser experimentar, realize os devidos backups, desinstale tudo e refaça a instalação.
Note que temos pastas que não são removidas após a desinstalação e que devem ser removidas manualmente, tais como:
C:\Users\<username>\.totvsls
C:\Users\<username>\.vscode\extensions\totvs.tds-vscode-1.3.17

**Comment by renanpaiva64** [comment]
@lwtnb-wrk tentei fazer a reinstalação do VS Code removendo tudo e o problema persiste. Realmente deve ser algo com a configuração do servidor, mas como fica no T-Cloud não temos acesso, pois em outros servidores eu compilo normalmente. Triste saber que o log não auxilia a entender qual o problema para este caso.

**Comment by lwtnb-wrk** [comment]
@renanpaiva64 Perdi a parte que você falou que estava no T-Cloud. Neste caso pode ser que os servidores esteja bloqueados para compilação. No T-Cloud geralmente aplicamos patches para ter uma rastreabilidade do que foi alterado no RPO.
Esse ambiente T-Cloud é de desenvolvimento mesmo? Ou seria homologação ou produção??

**Comment by renanpaiva64** [comment]
Homologação, mas outros consultores conseguem compilar nele normalmente, antes de tombar a base de produção para este ambiente eu compilava normalmente.

**Comment by lwtnb-wrk** [comment]
@renanpaiva64 Atualmente então outros consultores conseguem compilar nesse servidor de homologação e somente você não consegue?
Ou depois de tombar a base de produção, todos pararam de conseguir compilar nesse servidor?

**Comment by renanpaiva64** [comment]
@lwtnb-wrk somente eu não consigo, utilizando o mesmo usuário que eles utilizam para compilar. O time tentou a configuração em 4 computadores diferentes, todos com o mesmo resultado, inclusive 2 destes computadores utilizam SO's distintos.

**Comment by renanpaiva64** [comment]
@lwtnb-wrk as maquinas que conseguem compilar utilizam Windows 10

**Comment by lwtnb-wrk** [comment]
@renanpaiva64 Só consigo imaginar que, o que poderia causar esse tipo de comportamento, é a configuração de includes.
Quantos arquivos existem na sua pasta "c:/include" ?

**Comment by renanpaiva64** [comment]
@lwtnb-wrk fiz e gerou estes 2 arquivos
[rspag.errprw.txt](https://github.com/totvs/tds-vscode/files/11285818/rspag.errprw.txt)
[rspag.ppo.txt](https://github.com/totvs/tds-vscode/files/11285823/rspag.ppo.txt)

**Comment by brodao2** [comment]
Senhores,

Estou acompanhando a troca de mensagens dessa ocorrência e pela última do @renanpaiva64, acredito que o arquivo totvs.ch está corrompido, descartando ser configuração no TCloud. 
Solicito que faça os testes:
1o Teste
- Com o VSCode fechado, abra o fonte em um editor que identifique o codepage, p.e. Notepad++. Este deverá indicar CP1251 ou algo semelhante.
- Retorne ao VSCode, abra o arquivo, verifique o codepage e tente compilar.

2o Teste
- Abra um outro fonte qualquer, verifique o codepage e tente compilar.

3o Teste
- renomear a pasta com os includes e recompilar o fonte. Deve ocorrer que não achou o arquivo.
- copie os CH de um de seus colegas que conseguem compilar e recrie a pasta (mantenha a renomeada) de includes com esses arquivos copiados
- compile o fonte

Aguardo retorno dos testes.

**Comment by renanpaiva64** [comment]
@brodao2 acho que não está ficando claro que se eu pegar a IDE e os includes do jeito que estão conectar em outro servidor eu compilo este fonte sem problema algum.

**Comment by lwtnb-wrk** [comment]
@renanpaiva64 Mas se, outros colegas, conectando nesse AppServer, que você está tentando compilar, eles conseguem compilar?
