### ISSUE TITLE
Compilação release 0.3.11 não apresentar se o arquivo foi compilado.

### ISSUE THREAD

**Issue by Smmartinez** [totvs/tds-vscode#111]
Bom dia!
A compilação na release 0.3.11 não apresenta se o arquivo terminou de ser compilado, mostra a mensagem:
[Log   - 00:00:00] Start file compile.
[Log   - 00:00:00] Start regular compiling c:/Totvs/fontes_vscode/Pertech/Fontes/Fontes/Help/Chm01Mnt.prw (1/1).

**Comment by DanielYampolschi** [comment]
Ola @Smmartinez , esse problema ocorre somente com esse fonte? 

Faz um teste por favor, desconecta e conecta novamente no seu servidor e compila um outro arquivo. 

Fiz testes aqui e não consegui reproduzir, deve ter algo particular nesse fonte ou no seu ambiente que cai em alguma situação que não prevista. 

Dede já, te agradeço a ajuda pra identificarmos que situação é essa.

**Comment by isaquer** [comment]
Estou com o mesmo problema, o arquivo não é compilado.

**Comment by isaquer** [comment]
> Estou com o mesmo problema, o arquivo não é compilado.

Fonte estava com erro de syntax, erro que não é retornado ao compilar.

Ex:
* Syntax errada: nNumero := (cAlias2)->(TAB.CAMPO)
* Syntax correta: nNumero := (cAlias2)->(CAMPO)

**Comment by Smmartinez** [comment]
É isso mesmo que o Isaquer disse, tem um erro no fonte so que não retorna não da erro no VSCODE e o fonte não compila

**Comment by isaquer** [comment]
> É isso mesmo que o Isaquer disse, tem um erro no fonte so que não retorna não da erro no VSCODE e o fonte não compila

Mesmo após corrigir o erro de syntax, o fonte não é compilado.

**Comment by DanielYampolschi** [comment]
Pessoal, o @fernandoadvpl na issue #112 conseguiu isolar o problema com a tag %NotDel%. 
O problema ocorre no pre-compilador. Já notificamos a equipe responsável a qual já está trabalhando na correção para liberarmos uma nova versão o mais rápido possível. 
Pedimos desculpas pelo transtorno e agradecemos a ajuda de todos.

**Comment by DanielYampolschi** [comment]
Versão 0.3.12 liberada no marketplace com a correção do pre-compilador. 
Mais uma vez agradeço a todos pelos testes.
