### ISSUE TITLE
Rest não é "derrubado" ao compilar um fonte

### ISSUE THREAD

**Issue by ThiagoMarq** [totvs/tds-vscode#1110]
## Enter the data below

**Describe the bug**
Bom dia. 
Ao tentar compilar um fonte utilizando o VSCode, o Rest não é "derrubado" como antes. Mesmo com a chave BuildKillUsers ativada na aba GENERAL do arquivo .ini e a chave app_environment desativada como puder ler em outras issues pesquisadas anteriormente.

**To Reproduce**
1. Deixar o Rest ativado
2. Tentar compilar qualquer fonte

**Screenshots**
![image](https://user-images.githubusercontent.com/65978430/235654135-5963b3fb-c602-4b46-bc0a-7c17f138b083.png)

**Appserver (please complete the following information):**
 - Build (with date): e.g. Build  7.00.210324P-20221215 - 64 bits 
 - OS/Architecture: Windows Server 2019
 - Build Version:  20.3.1.2

**Comment by danielbolognani** [comment]
Bom dia @ThiagoMarq
Qual a mensagem de erro que ocorre no VSCode?

Essa chave BuildKillUsers=1 é de responsabilidade do Appserver, portanto a recomendação é atualizar o binário para a última versão disponível (20.3.1.5)

**Comment by ThiagoMarq** [comment]
Olá, Daniel.
Ele apresentava o a mensagem de RPO em uso, mesmo sem ninguém estar usando. Porém, agora com sua recomendação, verifiquei a versão e atualizei o Appserver e resolveu o meu problema.
Muito obrigado, Daniel. Grato!

**Comment by lwtnb-wrk** [comment]
@ThiagoMarq Apenas um comentário adicional, mesmo sem "usuários" conectados, os JOBS (como o próprio REST) são considerados na questão de RPO em uso...
