### ISSUE TITLE
Inconsistência com aplicação de patch

### ISSUE THREAD

**Issue by rodstephanel** [totvs/tds-vscode#1111]
Boa tarde pessoal,

Estou com dificuldade para aplicar patches, faço o processo de aplicação de patch e o processo fica 'preso' na instrução 'Loading functions from Server'. Como é uma base Protheus local e somente para gerar patches, já apaguei ela e instalei novamente usando o instalador do Protheus, mesmo assim continuo com o problema relatado, na imagem abaixo mostro onde fica preso a aplicação de patch:
![VSCode](https://user-images.githubusercontent.com/31445805/236503926-2cf6d7b3-e620-422d-a747-c86eed6cb393.png)

Abaixo segue imagem exibida em meu appserver:
![Appserver](https://user-images.githubusercontent.com/31445805/236504103-4081814a-6d97-4287-b503-dc49f6b211eb.png)

Obs.: Sempre 'quebra' meu RPO Custom após realizar a tentativa de aplicar o patch.

 **Dados do Server **
Versão: TOTVS Construção e Projetos
Build AppServer: 7.00.210324P-20221005 - 64 bits
Nome do servidor: DESKTOP-S80CJU8
Sistema operacional: Windows 11
Appserver version: 20.3.1.0
Build DBAccess: 20220303-20221005
Release do RPO:  12.1.2210
Release do dicionário: 12.1.2210
Local files: CTREE
License server: 2014 - 3.4.3
DB DataBase: MSSQL
DB API Build: 20220303-20221005

Logs VSCode:
[totvsls.log](https://github.com/totvs/tds-vscode/files/11407965/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/11407967/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/11407968/totvsls_out.log)

**Comment by danielbolognani** [comment]
Boa tarde,
Nesse caso o appserver está "caindo", por isso ocorre o problema na aplicação de patch.

Atualize o seu appserver com a última versão disponível no portal que deve resolver o problema.

**Comment by rodstephanel** [comment]
Boa tarde @lwtnb-wrk 

Isso o appserver que baixei foi o APPSERVER HARPIA VERSAO 12 WINDOWS X64 BUILD 20.3.1.5.
Aparentemente é só com Custom, apliquei o acumulado de RH para testar e foi aplicado o patch (log anexo)
Detalhe estou gerando o patch pela opção 'Patch Genration (from Folder)'


Patch que estou tentando aplicar
[TESTE_1005.zip](https://github.com/totvs/tds-vscode/files/11444772/TESTE_1005.zip)

Log Patch RH
[log_patch.txt](https://github.com/totvs/tds-vscode/files/11444760/log_patch.txt)

**Comment by lwtnb-wrk** [comment]
@rodstephanel Temos realmente uma questão em aberto referente a aplicação de patch corromper o custom.rpo em alguns cenários. Tentei aplicar o patch "TESTE_1005.ptm" e realmente ocorreu o mesmo "DBGMAP Error" que você obteve.
Porém isso está ocorrendo, a princípio, apenas quando o AppServer tenta criar um "custom.rpo" durante a aplicação de patch.
Para contornar esse problema temos o seguinte contorno:
- realize o backup e apague o arquivo "custom.rpo" (de seu AppServer corrente)
- compile um programa qualquer para criar um novo "custom.rpo"
- aplique o patch TESTE_1005.ptm
- se desejar, remova o programa compilado inicialmente (no 2o passo)
Veja se consegue aplicar o patch usando este contorno.
De qualquer forma vou reportar esta ocorrência para o time de AppServer averiguar.

**Comment by rodstephanel** [comment]
@lwtnb-wrk Segui suas orientações e deu certo aplicar o patch.

O apagar o arquivo Custom.rpo da maneira correta fiz assim:
* Parei os serviços
* Apaguei o RPO
* Iniciei os serviços

Após isso compilei um fonte e o excluí do rpo em seguida, dessa forma ele gerou um arquivo Custom.rpo de tamanho 21k, dessa forma foi possível aplicar o patch.

Obrigado pelo apoio.

**Comment by lwtnb-wrk** [comment]
@rodstephanel De qualquer forma, acredito que isso será corrigido nas próximas versões do AppServer e também adicionamos proteções para não ocorrer o "DBGMap Error" na próxima versão do tds-vscode também.
