### ISSUE TITLE
Problema Linter

### ISSUE THREAD

**Issue by ricardohmlsp** [totvs/tds-vscode#1112]
Estou a tempos observando o problema no Linter em entender que um metodo de uma classa é tipada explicitamente.

Por exemplo:

Class exemplo
Public Method Teste() as array
EndClass

Method Teste() Class Teste as array

Return array

Acima o codigo funciona normalmente e linter entende perfeitamente sem erro, o problema esta quando eu tenho parametros passados para os metodos , veja a baixo

Class exemplo
Public Method Teste(nNumero as numeric ) as array
EndClass

Method Teste(nNumero as numeric) Class Teste as array -> apresenta erro no Linter, 

Return array

Acima o Linter apresenta erro e para contornar eu retiro a tipagem do metodo e funciona normalmente.

Abraço

RHML

**Comment by lwtnb-wrk** [comment]
@ricardohmlsp O Linter apenas "adianta" os problemas que ocorreriam durante a compilação do fonte.
Nesse caso, aparentemente, a tipagem dos parâmetros na implementação de métodos não é suportada ainda pela linguagem mesmo. Note que na declaração do método a tipagem não apresenta erro.
Para confirmar, você pode desligar o Linter e observar que ao compilar o fonte o mesmo erro é apresentado. Aliás, mesmo com o Linter ligado, você pode compilar o fonte e o erro será o mesmo.
Caso acredite que seja um erro mesmo, abra um chamado na TOTVS questionando esse problema na linguagem. (Mas neste caso é melhor nem mencionar o 'tds-vscode' ou eles te redirecionarão para cá... rsrsrs)

**Comment by ricardohmlsp** [comment]
@lwtnb-wrk  pois é o problema é que tem toda a documentação sobre a tipagem de classes métodos e etc em tlpp e a mesma ainda nao suportada, vou abrir um chamado com eles para entender o porque de não funcionar, caso seja normal pedir pra corrigir ao menos a documentação deles , dizendo que não funciona tipagem de métodos que recebem atributos. 

Obrigado pela atenção , abraço.
