### ISSUE TITLE
Problemas de acentuações no debug 

### ISSUE THREAD

**Issue by bocaotmkt** [totvs/tds-vscode#1113]
Ao debugar o sistema para identificar problemas de automação, verificamos que o retorno das mensagens não estão sendo validadas de forma correta, para um exemplo na imagem enviada forçamos o encode e decode das mensagens apresentando no console a mesma formatação, ao analisar a comparação o retorno dela é correto, continuamente na clausula negamos a decisão e mesmo retornando .F. o sistema entra na decisão incorretamente. Poderíamos nos ajudar?
*Possivelmente deve ser algum problema de encode.

**Expected behavior**
O sistema deveria entender o como .F. e desprezar a clausula. 

**Screenshots**
![image](https://github.com/totvs/tds-vscode/assets/72392906/7145b445-f808-4877-a704-6e5e9746832c)

**Desktop (please complete the following information):**
Windows 64

**Appserver (please complete the following information):**
***  TOTVS S/A  ***
***  www.totvs.com.br  ***
* TOTVS - Build 7.00.210324P - Apr  8 2023 - 12:44:53
* Build: 64 bits
* SVN Revision: 38492
* Build Version: 20.3.2.0_ts06

Versão TDS v1.3.18-RC4

**Comment by lwtnb-wrk** [comment]
@bocaotmkt Existe uma limitação ao tentar usar o "Console de Depuração" no tds-vscode, pois até onde entendo, o encoding esperado no console, seria o utf-8, enquanto que usamos as string em cp1252.
Então ao "digitar" uma string com acentuação no console, acredito que internamente ele entenda como utf-8, mas ao submeter essa string para o AppServer, conversões ocorrerão e que podem acabar "confundindo" tanto o AppServer quanto nós desenvolvedores.
Veja esse exemplo e perceba o problema na comparação de seu programa.
![image](https://github.com/totvs/tds-vscode/assets/49563478/c8668818-34c1-4635-834f-54aebeef3b11)

**Comment by lwtnb-wrk** [comment]
@bocaotmkt Note que no "Console de Depuração" propositadamente não usei strings explicitas, mas variáveis que foram compiladas no programa AdvPL, por isso não ocorreram problemas de tradução utf-8/cp1252 no console.

**Comment by maximinocastro** [comment]
@lwtnb-wrk boa tarde,

Estou tendo mesmo problema e está acarretando um nas API quando faz o retorno, e conforme o exemplo que deu da Tradução para API não funciona.

Abaixo os Exemplos:

![image](https://github.com/totvs/tds-vscode/assets/42280023/de1d8240-ebfd-40da-9eeb-4a04fbd797d6)

![image](https://github.com/totvs/tds-vscode/assets/42280023/f2e9359a-2d33-4dfd-9841-2bcafeb1eff8)

**Comment by danielbolognani** [comment]
@maximinocastro O problema relatado originalmente é apenas na entrada de dados pelo debug console.

O seu problema parece ser com a resposta de um serviço rest de fato, confundindo codepage.

Lembrando que o Protheus/Appserver trabalha com CP1252 para português/espanhol e CP1251 para russo. Se vc enviar um texto para fora do ambiente protheus (um servidor REST por exemplo) precisa verificar qual o codepage deve estar no texto, se for UTF-8, por exemplo, é necessário converter em advpl (encodeutf8) antes de enviar a resposta.

**Comment by maximinocastro** [comment]
@danielbolognani estou consumindo um serviço REST do PROTHEUS e devolvendo com ENCODE conforme a documentação (https://tdn.engpro.totvs.com.br/display/public/framework/FWhttpEncode) e mesmo assim vem todo desconfigurado.

**Comment by danielbolognani** [comment]
Certo, mas o problema nesse caso não é no debugger, certo?

**Comment by maximinocastro** [comment]
Certo. 

O debugar eu até entendo o que você falou fica errado, más é só visualização. O Problema que mesmo visualizado e com o ENCODE retorna errado na API.

E sobre o debug não tem como deixar da mesma forma como antigamente, debug mostrando com acentução correta. Colocar um flag tipo o do LINTER. Quem quiser usar a forma antiga é só desmarcar?

**Comment by brodao2** [comment]
Senhores,

Foram adicionadas [funcionalidades](https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md#funcionalidade-estendida-chardetails) envolvendo _strings_ em UTF-8, que podem lhes ajudar.

À disposição.
