### ISSUE TITLE
Capturar exceptions antes do errorlog

### ISSUE THREAD

**Issue by vitor-gabriel** [totvs/tds-vscode#1114]
**Descreva a solução que você gostaria**
Olá, tudo joia?
Em outras linguagens, temos a possibilidade de capturar o erro com um breakpoint "automatico" na exception do codigo fonte que estamos depurando. Imagino que isso seria de grande ajuda também no ADVPL/TLPP.

![image](https://github.com/totvs/tds-vscode/assets/62556013/66571731-794f-465f-b16f-8f623e3951bc)

**Descreva as alternativas que você considerou**
Hoje só temos o errorlog pra saber as informações do erro, o que ajuda muito, mas com esta feature, podemos testar os dados antes de ocorrer realmente o errorlog.

**Comment by Kkayke** [comment]
Otima ideia, seria muito util mesmo trazer isso para o ADVPL👍

**Comment by KrebsGustavo** [comment]
Uma ótima ideia, seria de grande ajuda para nós desenvolvedores ADVPL e TLPP.

**Comment by ricardomansano** [comment]
Boa tarde,
O caso será avaliado internamente, caso liberado, ele constará nas notas de release das próximas versões.
Reforçando que a extensão pode ser estendida pelo usuários, com novas features, seu desenvolvimento não depende exclusivamente dos times internos da TOTVS.
Grato,
