### ISSUE TITLE
Bug Watch VsCode debugando propriedade de objeto com Array (aCols)

### ISSUE THREAD

**Issue by brunnomcosta** [totvs/tds-vscode#1115]
Olá, tudo bem?

Conversei com o @DanielYampolschi e notamos um bug ao debugar um processo de fonte que possui um oObjeto:aCols que está exibindo no Watch do VsCode o conteúdo de uma variável private aCols ao invés do conteúdo correto do oObjeto:aCols conforme evidência anexo.

Solicito apoio para correção do bug.

Nota: investi cerca de 3h tentando ajustar um problema de produto, até que notei que na verdade aparentemente é um bug da ferramenta (vsCode).

Vídeo demonstando o problema: 

https://drive.google.com/file/d/1xufb02E0Wu5TYiZED2L1-FMSeAiKmDBV

Se precisar do fonte, favor me solicitar no Hangout.

Atenciosamente.

**Comment by DanielYampolschi** [comment]
Olá @brunnomcosta, eu preciso de uma ajuda sua para parar o debug no ponto que reproduz o problema, pois não consigo reproduzir com um exemplo simples e nem parando em outros pontos do fonte. 

Te chamei no Chat, mas você estava offline, então te peço pra, por favor, entrar em contato comigo assim que possível para darmos andamento a esse problema. 

Muito Obrigado

**Comment by lwtnb-wrk** [comment]
@brunnomcosta Só uma coisinha antes disso, já atualizou seu tds-vscode para a última versão?? Se ainda não atualizou, veja se na última versão o problema continua ocorrendo e nos avise dos resultado.

**Comment by DanielYampolschi** [comment]
Encerrando a issue pois não conseguimos mais reproduzir o problema após atualização para a versão 1.3.18 do plugin tds-vscode
