### ISSUE TITLE
Erro ao iniciar smartclient no vscode

### ISSUE THREAD

**Issue by leonardoMenagaro** [totvs/tds-vscode#1117]
Ola´ sou novo por aqui, procurei e não encontrei com a mesma situação, então quero ver se podem me ajudar?

Tenho Protheus em T-cloud 
No ambiente de desenvolvimento conectei o vscode conforme a porta  do tds no smartclient.ini, ate aqui tudo certo.
Porem ao tentar fazer o debug quando aperto F5 para iniciar o smartcliente depois de colocar login e senha, retorna a mensagem abaixo.
isso seria alguma liberação no acesso no cloud? ou configuração errada?
Grato.

![erro vscode](https://github.com/totvs/tds-vscode/assets/134397239/a728e9b2-0ad9-40d0-a3f1-223387fe53fb)

![conf](https://github.com/totvs/tds-vscode/assets/134397239/dcecc88b-bebd-4909-ba66-ee6498a58cf0)

**Comment by brodao2** [comment]
@leonardoMenagaro 

Ambientes em T-Cloud, necessitam de procedimentos próprios. Veja em [TDS: Depuração e Execução](https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md#tds-depura%C3%A7%C3%A3o-e-execu%C3%A7%C3%A3o) o bloco "Recomendações".

A disposição.

**Comment by brodao2** [comment]
@leonardoMenagaro 

Vou fechar o chamado, mas se for necessário, pode reabri-lo.

A disposição.
