### ISSUE TITLE
Não consigo conectar o APPSERVER para realizar atualização do PATCH TSS

### ISSUE THREAD

**Issue by raphaelassis1** [totvs/tds-vscode#1119]
Prezados Bom Dia!

Não estou conseguindo deixar o VSCODE online para atualizar o PATCH DO TSS para a realização de teste da mudança do servidor da SEFAZ MG. Não é apresentado erro, mas também não fica online.

Poderiam dar uma apoio? Preciso realizar o teste antes que isso fique em produção.

No aguardo.

**Comment by brodao2** [comment]
Verifique o log de console do appServer e veja se há alguma informação relevante.

**Comment by raphaelassis1** [comment]
não estou conseguindo gerar o log, nunca mexi com isso. Teria alguma forma para entrar em contato?

**Comment by raphaelassis1** [comment]
Segue o meu arquivo console.log
[console.log](https://github.com/totvs/tds-vscode/files/11653021/console.log)

**Comment by brodao2** [comment]
Pelo log do _appServer_, você está com problemas de SSL. Pela mensagem, a chave ``CertificateServer `` da sessão ``SSLConfigure``, não aponta para um arquivo CRT.

```
2023-06-05T10:16:19.265000-03:00 5568|[VDRPORT] 230605_101619 15C0 VSC0891 E fatal error from SSL [error:02001015:system library:fopen:Is a directory]
```

Ajuste a configuração e tente novamente. Caso o erro persista, entre em contato com o 
[suporte do módulo ou servidor](https://totvscst.zendesk.com/hc/pt-br/#home).

Vou fechar este chamado e caso ainda tenha problemas após a correção do SSL, pode reabri-lo.

A disposição.

**Comment by lwtnb-wrk** [comment]
@raphaelassis1 tem uns caracteres bem estranhos nesse console.log, onde aparentemente seria o nome de um environment no appserver.ini...
Voce esta utilizando algum nome estranho para os environments do appserver??
Veja se não seria esse o problema que esta enfrentando...
Se quiser nos envie seu appserver.ini para darmos uma olhada tambem.
