### ISSUE TITLE
Erro ao compilar quando código contém: %NotDel%

### ISSUE THREAD

**Issue by fernandoadvpl** [totvs/tds-vscode#112]
Ao utilizar Sql Embedded a compilação trava quando utilizamos a expressão "%NotDel%". 

Na saída, a compilação trava na mensagem: "Start regular compiling"

Att,
Fernando Alves

**Comment by DanielYampolschi** [comment]
Ola @fernandoadvpl , obrigado pela informação, estamos analisando. Peço para  por favor acompanhar pela issue #111

**Comment by DanielYampolschi** [comment]
@fernandoadvpl . Caso não tenha visto na issue #111, te agradeço em nome da equipe por ter encontrado a causa raiz desse problema. 
O problema ocorre no pre-compilador e equipe responsável já está trabalhando na correção.
Muito obrigado.

**Comment by fernandoadvpl** [comment]
@DanielYampolschi Show de bola! Fico feliz em ter ajudado! Forte abraço
