### ISSUE TITLE
bom dia estou com esse seguinte erro

### ISSUE THREAD

**Issue by guerraph2022** [totvs/tds-vscode#1120]
![erro](https://github.com/totvs/tds-vscode/assets/117463893/51d5986c-7030-4153-9525-7d959d13c67f)
// Definindo as estruturas de dados
STRUCTURE stCabecalho
  num Id
  c(8) Placa
  c(50) ModeloMarca
  n(4) Ano
  n(8) Km
  
END

STRUCTURE stItem
  num Id
  num IdCabecalho
  num ProximoFila
  c(50) Cliente
  d DataHoraInicial
  d DataHoraFinal
END

// Função para gerar o próximo ID disponível
STATIC FUNCTION NextId(nTabela)
  LOCAL cQuery := "SELECT MAX(Id) + 1 AS NextId FROM " + nTabela
  DBUseArea(.T., "ALIAS", nTabela)
  DBSelectArea(nTabela)
  DBCloseArea(nTabela)

  IF !EOF()
    RETURN ALIAS->NextId
  ELSE
    RETURN 1
  ENDIF
ENDFUNC

// Função para verificar se o cliente já existe na lista
STATIC FUNCTION ClienteExiste(nIdCabecalho, cCliente)
  LOCAL nContador
  DBUseArea(.T., "ALIAS", "Item")
  DBSelectArea("Item")
  DBCloseArea("Item")

  FOR nContador := 1 TO LEN(Item->Id)
    IF Item->IdCabecalho[nContador] == nIdCabecalho && Item->Cliente[nContador] == cCliente
      RETURN .T.
    ENDIF
  NEXT

  RETURN .F.
ENDFUNC

// Rotina para adicionar um novo cabeçalho
FUNCTION AddCabecalho(cPlaca, cModeloMarca, nAno, nKm)
  LOCAL nIdCabecalho := NextId("Cabecalho")
  DBSelectArea("Cabecalho")
  DBCreateArea("Cabecalho", .T.)

  Cabecalho->Id := nIdCabecalho
  Cabecalho->Placa := cPlaca
  Cabecalho->ModeloMarca := cModeloMarca
  Cabecalho->Ano := nAno
  Cabecalho->Km := nKm

  DBReplace()
  DBCloseArea("Cabecalho")
  RETURN nIdCabecalho
ENDFUNC

// Rotina para adicionar um novo item à lista
FUNCTION AddItem(nIdCabecalho, cCliente, dDataHoraInicial, dDataHoraFinal)
  LOCAL nProximoFila := LEN(Item->IdCabecalho) + 1
  LOCAL nIdItem := NextId("Item")
  DBSelectArea("Item")
  DBCreateArea("Item", .T.)

  Item->Id := nIdItem
  Item->IdCabecalho := nIdCabecalho
  Item->ProximoFila := nProximoFila
  Item->Cliente := cCliente
  Item->DataHoraInicial := dDataHoraInicial
  Item->DataHoraFinal := dDataHoraFinal

  DBReplace()
  DBCloseArea("Item")
  RETURN nIdItem
ENDFUNC

// Rotina para alterar a posição de um cliente na fila
FUNCTION AlterarPosicao(nIdItem, nNovaPosicao)
  LOCAL nIdCabecalho := 0
  DBSelectArea("Item")
  DBCloseArea("Item")

  FOR EACH Item
    IF Item->Id == nIdItem
      nIdCabecalho :=

**Comment by lwtnb-wrk** [comment]
@guerraph2022 De onde você pegou esse fonte? Pois a principio não temos essa estrutura de dados (STRUCTURE) por padrão.
