### ISSUE TITLE
Novo - Compilo programa mas não compila as linhas

### ISSUE THREAD

**Issue by fabiopmota** [totvs/tds-vscode#1121]
Olá,
Estou com seguinte situação. 

1 - Quando compilo no console log do VS Code  esta apresentando a seguinte indicando que foi compilado com sucesso.

[Info  - 12:32:10] Starting recompile.
[Info  - 12:32:10] Starting build for environment PRODUCAO_DESENV.
[Info  - 12:32:15] Starting build using RPO token ...
[Info  - 12:32:15] Start file recompile.
[Info  - 12:32:15] Using Includes: c:/includes_p12
[Info  - 12:32:15] Start secure compiling e:/outros computadores/meu laptop/e/#projetos/renovagro/projeto_renovagro/contabilidade/miscelanea/mctb001.tlpp (1/1).
[Info  - 12:32:15] [SUCCESS] Source e:/outros computadores/meu laptop/e/#projetos/renovagro/projeto_renovagro/contabilidade/miscelanea/mctb001.tlpp compiled successfully.
[Info  - 12:32:15] Committing end build. This could take a while...
[Info  - 12:32:16] All files compiled successfully.
[Info  - 12:32:16] Recompile finished.

2 - No log do AppServer esta indicando que zero linha foram compiladas. Veja parte do log

2023-06-07T12:31:52.088000-03:00 15680|
[INFO ][SERVER] [Thread 15680] [07/06/2023 12:31:52] Updating RPO E:\TOTVS\Protheus_PRD\Protheus\apo\Desenv\custom.rpo2023-06-07T12:31:52.088000-03:00 15680|
[INFO ][SERVER] Updating map 1/5 Custom RPO: 635
2023-06-07T12:31:52.089000-03:00 15680|
[INFO ][SERVER] Updating map 2/5 Custom RPO: 5
2023-06-07T12:31:52.089000-03:00 15680|
[INFO ][SERVER] Updating map 3/5 Custom RPO: 0
2023-06-07T12:31:52.089000-03:00 15680|
[INFO ][SERVER] Updating map 4/5 Custom RPO: 0
2023-06-07T12:31:52.090000-03:00 15680|
[INFO ][SERVER] Updating map 5/5 Custom RPO: 237
2023-06-07T12:31:52.148000-03:00 15680|
[INFO ][SERVER] [Thread 15680] [07/06/2023 12:31:52] End Build.2023-06-07T12:32:23.643000-03:00 15680|
[INFO ][SERVER] [Thread 15680] Start Build.
2023-06-07T12:32:24.645000-03:00 15680|
[WARN ][SERVER] there isn't active HTTP server
2023-06-07T12:32:24.646000-03:00 15680|Rpo with Total Users: 1 (Custom RPO)
2023-06-07T12:32:28.587000-03:00 15680|
[INFO ][SERVER] [Thread 15680] Compiling mctb001.tlpp
2023-06-07T12:32:28.588000-03:00 15680|MCTB001.TLPP:0

3 - Se realizar consultas pelo inspetor de objetos o mesmo indica que esta compilado.
![image](https://github.com/totvs/tds-vscode/assets/42223351/1b620ca3-9c95-429a-ac09-7874a46e4960)

[totvsls_out.log](https://github.com/totvs/tds-vscode/files/11679542/totvsls_out.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/11679543/totvsls_in.log)
![Screenshot_50](https://github.com/totvs/tds-vscode/assets/42223351/77278fc6-5ae6-45ba-927d-4eae8db6d41a)
[totvsls.log](https://github.com/totvs/tds-vscode/files/11679544/totvsls.log)

**Comment by lwtnb-wrk** [comment]
@fabiopmota Pela estrutura dos diretorios, aparentemente você usa algum tipo de drive na nuvem (One Drive, Google Drive, etc) certo?
Experimente copiar os arquivos que estao compilando com zero linhas em um diretorio local diferente, por exemplo C:\teste e tente compilar desse outro diretorio.
Se a compilacao funcionar neste outro diretorio local, nos passe mais informacoes sobre o tipo de drive na nuvem utiliza.

**Comment by fabiopmota** [comment]
Realmente o diretório esta em uma pasta que uso compartilhada no Google Drive.

Coloque os arquivo no C:\ e deu certo, compilado com sucesso.
