### ISSUE TITLE
After the last update the Monitor is not showing corretly nor terminating connections

### ISSUE THREAD

**Issue by gmatiash** [totvs/tds-vscode#1123]
After updating the VSCode extension the information shown on the Monitor is "corrupted" as shown on the following image:
![image](https://github.com/totvs/tds-vscode/assets/49596341/374dea36-fae1-408f-b168-38d0e99c5810)

When trying to terminate the "LPULSE" connection is not terminating it and adding the second line shown on the screenshot.

Restarting the service does not help.

I tried using a previous version of the extension that I had on another installation and it worked fine, it terminated the LPULSE job without errors.

**Desktop:**
 - OS/Architecture: Windows 11 Enterprise 22H2
 - VSCode version: 1.79.1
 - Extension version: v1.3.18

**Appserver:**
 - Build: 7.00.210324P-20230228
 - OS/Architecture: Windows Server 2019

**Comment by lwtnb-wrk** [comment]
@gmatiash Reproduzimos a ocorrência e já estamos corrigindo no tds-vscode. 
Se tiver acesso ao Portal de Downloads da TOTVS você pode baixar e usar o Monitor Electron que não está com este problema.

**Comment by gmatiash** [comment]
Eu ja instale a vercao anterior da extencao, obrigado.

**Comment by leandroayala** [comment]
Identifiquei o mesmo problema!

**Comment by lwtnb-wrk** [comment]
geramos uma versao pre-release que deve corrigir o problema reportado
https://github.com/totvs/tds-vscode/releases/tag/v1.3.19-RC1

caso tenham duvidas na instalacao vejam https://github.com/totvs/tds-vscode/blob/master/docs/install.md

**Comment by HTM-Joaquim** [comment]
Testei a instalação da extensão e posso comprovar que o problema na exibição e kill das licenças foi resolvido
