### ISSUE TITLE
Posicionamento do Fonte no Explorer do VsCode.

### ISSUE THREAD

**Issue by lkznogueira** [totvs/tds-vscode#1124]
Prezados,

Recentemente fizeram a correção de um problema ref. acentuações para Linux/MacOs

https://github.com/totvs/tds-vscode/issues/1078

Hoje venho trazer outra informação, toda vez que vc clica em um código fonte aberto, a arvore do projeto (explorer VsCode) posiciona no fonte aberto, no MACOS quando o código fonte está dentro dessas pastas com acentuação,o fonte não é posicionado.

**Comment by brodao2** [comment]
Pelo que andei pesquisando e entendi, pode ser problema do VS-Code mesmo. 
Nas configurações, verifique se "Files: Encoding" esta como "UTF-8". 
Não só afeta o conteúdo como também o sistema de arquivos.

Atente que pode afetar a carga de fontes Advpl/4gl. Se for o caso, ajuste/force a chave "totvsLanguageServer.filesystem.encoding" para cp1252 ou cp1251. 

Sugiro fortemente abandonar acentuação em nomes de pastas e arquivos.

``#BANISH_ACCENTS``

**Comment by lwtnb-wrk** [comment]
@lkznogueira Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by brodao2** [comment]
Força a ``Files: Encoding`` (``files.encoding``) para UTF-8.

**Comment by lkznogueira** [comment]
@brodao2 
Mudei mas msm assim sem sucesso.. Após analisar bem aqui, vi que o problema acontece quanto o referido fonte é aberto pelo Search do VsCode..

No print abaixo é possível ver 2 fontes com o msm nome "PRIVRA" o que está na coloração verde é o que foi aberto pelo Search do VSCODE. E o que está em cinza é o que foi aberto percorrendo o caminho no explorer e clicando para abrir o fonte.
<img width="583" alt="image" src="https://github.com/totvs/tds-vscode/assets/12913181/d5a5e379-db80-4ce8-a8f3-cf31465bcf65">

Segue um exemplo:
Quando eu clico no fonte clsMobile nessa aba superior de fontes abertos, ele me posiciona no Explorer do VSCODE no código fonte referido.

No PRIVRA que está cinza, quando eu também clico na aba ele também me posiciona na pasta que está o fonte..

Agora o PRIVRA (VERDE - Aberto pelo SEARCH) ele não me posicoina no Explorer.. o GIT até entende ele como sendo um fonte Untracked.. E olha que eh o msm caminho..
<img width="372" alt="image" src="https://github.com/totvs/tds-vscode/assets/12913181/c96a57c6-df00-4353-a80c-4770cede0595">
<img width="342" alt="image" src="https://github.com/totvs/tds-vscode/assets/12913181/e221d193-4d05-464e-ae20-902fffe7e07f">

**Comment by lwtnb-wrk** [comment]
@lkznogueira Pelo que entendo isso é um comportamento padrão do VS Code e não tem nenhuma interferência do tds-vscode. Acredito que se tentar desinstalar o tds-vscode, o comportamento vai permanecer o mesmo, pois é algo que o VS Code não está tratando corretamente (no momento não consigo realizar esse teste).

Enfim, nesse caso, o caminho seria abrir um chamado diretamente para o VS Code https://github.com/microsoft/vscode/issues

De qualquer forma se puder enviar os logs gerados atualmente pelo tds-vscode podemos dar uma conferida apenas para confirmar esta questão.
