### ISSUE TITLE
Erro ao gerar patch

### ISSUE THREAD

**Issue by fmcdomaia** [totvs/tds-vscode#1125]
Estamos com erro para gerar um patch apartir do RPO atual da empresa , segue abaixo . 

---------------------------v---------------------------------------------------
   //////  ////    //////  |  TOTVS Developer Studio for VS-Code
    //    //  //  //       |  Version 1.3.18
   //    //  //  //////    |  TOTVS Technology
  //    //  //      //     |
 //    ////    //////      |  https://github.com/totvs/tds-vscode
---------------------------^---------------------------------------------------

-------------------------------------------------------------------------------
SOBRE O USO DE CHAVES E TOKENS DE COMPILAÇÃO                                   

As chaves de compilação ou tokens de compilação empregados na construção do    
Protheus e suas funcionalidades, são de uso restrito dos desenvolvedores de    
cada módulo.                                                                   

Em caso de mau uso destas chaves ou tokens, por qualquer outra parte, que não  
a referida acima, a mesma irá se responsabilizar, direta ou regressivamente,   
única e exclusivamente, por todos os prejuízos, perdas, danos, indenizações,   
multas, condenações judiciais, arbitrais e administrativas e quaisquer outras  
despesas relacionadas ao mau uso, causados tanto à TOTVS quanto a terceiros,   
eximindo a TOTVS de toda e qualquer responsabilidade.                          
-------------------------------------------------------------------------------
[Info  - 1:25:58 PM] Initializing Language Server.
[Info  - 1:25:58 PM] Language Server initialized.
[Info  - 1:25:58 PM] Starting reconnection to the server 'Compila'
[Info  - 1:25:59 PM] Secure authenticating...
[Info  - 1:26:03 PM] User authenticated successfully.
[Info  - 1:26:03 PM] Reconnection to the server 'Compila' finished.
[Info  - 1:26:12 PM] Starting object inspector.
[Info  - 1:26:12 PM] Loading objects from server.
[Info  - 1:26:16 PM] Objects loaded (Duration: 3.970000)
[Info  - 1:26:16 PM] 123913 objects successfully retrieved.
[Info  - 1:26:16 PM] Object inspector finished.
[Info  - 1:26:43 PM] Starting generate patch.
[Info  - 1:26:43 PM] Starting build for environment compila.
[Info  - 1:26:46 PM] Starting build using RPO token ...
[Error - 1:26:46 PM] Patch could not be generated.
[Info  - 1:26:46 PM] Cleaning up appserver OK.
[Info  - 1:26:46 PM] Aborting end build (rollback changes).

**Comment by lwtnb-wrk** [comment]
@fmcdomaia Basicamente houve um erro na geração indicado pelo AppServer. Verifique se existem mensagens de erro no console.log do AppServer. 
Do lado do tds-vscode não recebemos muita informação sobre o motivo da falha.

**Comment by fmcdomaia** [comment]
Nao apresenta erro no console, apenas na hora da geração mesmo !

**Comment by brodao2** [comment]
Salvo engano meu, desenvolvedores que não possuem Token de RPO não podem gerar pacotes com fontes do RPO padrão.

Se tiver o Token de RPO, verifique se o mesmo é valido.

**Comment by fmcdomaia** [comment]
Alan , como valido essa informação ?

**Comment by brodao2** [comment]
Com o suporte ao cliente via [Central de Relacionamento](https://centraldeatendimento.totvs.com/hc/pt-br).

**Comment by fmcdomaia** [comment]
Alan, e qual caminho coloco esse token no vscode para ele entender ?

**Comment by brodao2** [comment]
Em [Token RPO](https://github.com/totvs/tds-vscode/blob/master/docs/rpo.md#token-de-rpo) explica como informar o Token de RPO. 

Quanto a como obter um ``Token de RPO``, entre em contato com o [suporte](https://centraldeatendimento.totvs.com/hc/pt-br).

**Comment by brodao2** [comment]
Se necessário apoio na aplicação do Token, favor reabrir o chamado.
