### ISSUE TITLE
Não Debuga API REST - ExitCode=62097 

### ISSUE THREAD

**Issue by jpinto10** [totvs/tds-vscode#1126]
Versão do Plugin 1.3.18
Pessoal, não consigo de forma alguma debugar fontes de aplicação REST,
Preciso de um apoio, antes eu conseguia na boa, agora não consigo mais.

Já ativei o "isMultiSession": true no arquivo launsh.json e starto o debug utilizando a Function XXXX, OIA, mas não vai de forma alguma.

Mesmo depois de Verificar a documentação, identifiquei que estão configuradas de forma certa - NÃO ESTOU VENDO ERRO APARENTE ( 
Veja se a documentação em https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md#depura%C3%A7%C3%A3o-de-servi%C3%A7os-jobs ajuda, pois depurar serviço REST/Jobs tem particularidades. )

//Complementando as informações
Versão: TOTVS Varejo
Build AppServer: 7.00.210324P-20230531 - 64 bits
Appserver version: 20.3.1.9
Build DBAccess: 20220303-20230224
Release do RPO:  12.1.2210
Release do dicionário: 12.1.2210

Versão da Lib:20230515
Data da Lib: 20230523_151237

O codigo do erro é:
[09:48:11] INFO: Application Server connected.
[09:48:11] INFO: TDS-DA ready.
[09:48:18] INFO: SmartClient closed. ExitCode=62097 ExistStatus=CancelExit
[09:48:18] INFO: TDS-DA finished.

obs.:
ja coloquei:
"type": "totvs_language_debug",
"request": "launch",
"name": "FBS_CONTAGEM",
"program": "${command:AskForProgramName}",
"cwb": "${workspaceFolder}",
"smartclientBin": "C:/Users/Edilson/Desktop/SMARTCLIENT_2210_contagem/SMARTCLIENT_2210/SmartClient.exe",
"isMultiSession": true,
"enableTableSync": true,
"enableMultiThread": true,
"waitForAttach": 5,
"logFile": "${workspaceFolder}\[dap.log](https://github.com/totvs/tds-vscode/files/11916375/dap.log)"

[dap.log](https://github.com/totvs/tds-vscode/files/11916671/dap.log)

**Comment by brodao2** [comment]
Lembre-se que o job que responde o rest deve ser iniciado após a conexão de debug ter sido iniciada.

**Comment by jpinto10** [comment]
@danielbolognani - Vou testar, mais pelo que vi de videos e docs, eu tenho que fechar.. mais vou testar!!!
isso eu realmente não fiz, eu fechava..

**Comment by jpinto10** [comment]
@danielbolognani - obrigado.. funcionou 
ou seja, não podemos fechar a tela de aviso, NÃO DEVEMOS "CLICAR" NO "OK".

Obrigado.
