### ISSUE TITLE
"File could not be copied to the server." and "Start build error: Start build with token execution failed."

### ISSUE THREAD

**Issue by wico2k** [totvs/tds-vscode#1127]
Buenos días, al aplicar LIB con VSCode con plugin v1.3.18 en 2 ocasiones, aparece los siguientes mensaje:

OCASION 1
[Info  - 5:11:12 AM] Starting patch validate.
[Info  - 5:11:12 AM] Patch file: d:/Users/jbravo/OneDrive/Downloads/23-07-17-LIB_LABEL_26062023_P12_HARPIA/23-07-17-LIB_LABEL_26062023_P12_HARPIA-TTTM120.PTM
[Info  - 5:11:12 AM] Starting build for environment mp12133_bib.
[Info  - 5:11:16 AM] Starting build using RPO token ...
[Error - 5:11:17 AM] File could not be copied to the server.
[Info  - 5:11:17 AM] Aborting end build (rollback changes).
[Info  - 5:11:17 AM] Patch validate finished.
[Error - 5:11:17 AM] Patch validate could not be executed.

OCASION 2
[Info  - 5:23:00 AM] Starting patch validate.
[Info  - 5:23:00 AM] Patch file: d:/TOTVS/23-07-17-LIB_LABEL_26062023_P12_HARPIA/23-07-17-LIB_LABEL_26062023_P12_HARPIA-TTTM120.PTM
[Info  - 5:23:00 AM] Starting build for environment mp12133_bib.
[Error - 5:23:02 AM] Start build error: Start build with token execution failed. Please check if the server is online or the RPO is not in use.
[Error - 5:23:02 AM] Start build with token execution failed. Please check if the server is online or the RPO is not in use.

SO: Windows 11 Pro 22H2

Ver logs adjunto.

[totvsls.log](https://github.com/totvs/tds-vscode/files/12078788/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/12078789/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/12078791/totvsls_out.log)

**Comment by lwtnb-wrk** [comment]
@wico2k Aparentemente pelos logs, parece ter ocorrido um erro durante a copia do patch para o servidor e o mesmo ficou travado, causando o erro de todas as outras acoes subsequentes. Nao sei dizer se o AppServer vai conseguir se recuperar depois desse erro, então talvez seja necessário reiniciar o servidor.
Notei que o patch estava em uma pasta "OneDrive" e temos vários relatos de problemas no uso de drives na nuvem. Na segunda aplicação vi que já tentou mudar a pasta, mas como o AppServer já estava "baleado" ele não conseguiu responder adequadamente.
Então a principio experimente reiniciar o AppServer e aplicar dessa pasta fora do OneDrive e nos avise se conseguiu aplicar o patch.

**Comment by lwtnb-wrk** [comment]
@wico2k Apenas para informação, baixei e apliquei o patch que você está tentando aplicar aqui no meu tds-vscode sem problemas.
