### ISSUE TITLE
C2001 Syntax error: linter ln1, col1

### ISSUE THREAD

**Issue by alexlabteck** [totvs/tds-vscode#1129]
Bom dia, 

Por favor não sou deve ainda estou em treinamento e preciso de uma ajuda em fonte que eu estou fazendo.
Ele esta me dando o erro de sintaxe no include e os mesmos estão na pasta mencionada ao criar Server.

Poderiam me ajudar?

Grato
[WFBloqueioAcessoFerias.tlpp.zip](https://github.com/totvs/tds-vscode/files/12136494/WFBloqueioAcessoFerias.tlpp.zip)

**Comment by alexlabteck** [comment]
add
<img width="1275" alt="Captura de Tela 2023-07-22 às 10 02 05" src="https://github.com/totvs/tds-vscode/assets/139159093/a22dc551-9810-4d7b-b3bf-014dcd51b5c6">

**Comment by brodao2** [comment]
@alexlabteck 

O comando ``beginSql`` é finalizado com ``endSql`` e não ``endif`` (linha 20).
Na linha 41, há um ``endif`` sem o ``if`` correspondente.

De qq forma, esta **comunidade é exclusivo** a ocorrências relacionadas a **extensão TDS-VScode**.
Solicito que abra um chamado para o [suporte de AdvPL](https://totvscst.zendesk.com/hc/pt-br/#home) para outras ocorrências.
