### ISSUE TITLE
Correções nas Funções Repository Log e Objects Inspector.

### ISSUE THREAD

**Issue by fcredidio** [totvs/tds-vscode#1130]
Prezados, bom dia. 

Por gentileza, seria possível incluir o repositório Custom, na leitura da função Repository Log? 
Hoje a função apresenta somente o log referente ao repositório principal.  

Em paralelo, a documentação do object inspector, menciona que a data apresentada é a data da compilação do fonte. 
Porém, a data apresentada é a data e criação ou alteração do fonte em si. 
Se possível, por gentileza, apresentar as duas datas? Compilação e data do fonte em si. 

Ambos os processos são importantes para auditoria do repositório e controle de implementações. 

No aguardo e obrigado, 

Fabiano Credidio.

**Comment by lwtnb-wrk** [comment]
@fcredidio Favor abrir um chamado no suporte da TOTVS para cada questão, detalhando a melhoria pretendida e o motivo para que serão úteis. 
Aqui tratamos de problemas gerais e pequena melhorias, mas essas melhorias que você está sugerindo podem envolver outras áreas e não somente o tds-vscode.
De qualquer forma grato pelas sugestões.
