### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by Lschinor** [totvs/tds-vscode#1131]
# Help us to help you.

## Before opening an issue

- Make sure the extension is up to date.
- See [Resolução de Problemas](TROUBLESHOOTING.md#problemas-gerais), with common and/or known occurrences.

## Enter the data below

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS/Architecture: [e.g. Windows 64 bits]

**Appserver (please complete the following information):**
 - Build (with date): [e.g. Build ?.??.??????? - XXX XX XXXX - TT:TT:TT]
 - OS/Architecture: [e.g. Linux 64 bits Ubuntu]
 - Build Version [e.g. XX.X.X.XX]

**Additional context**

**Comment by Lschinor** [comment]
![Sem título](https://github.com/totvs/tds-vscode/assets/84096911/19575f22-ac87-4888-8b5a-15fbb7842d52)
![Sem título1](https://github.com/totvs/tds-vscode/assets/84096911/11959da4-eb49-4cd1-84c4-2ddece378616)

Está dando esse erro comigo, me informaram que poderia ser o nome do ambiente está errado, porém o mesmo está correto. Pderiam me ajudar para eu dar continuidade aos meus estudos? 
Obrigado!!

**Comment by brodao2** [comment]
Favor complementar chamado informando os dados solicitados conforme [Informações importantes ao abrir o chamado](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#informa%C3%A7%C3%B5es-importantes-ao-abrir-uma-issue) e anexe os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)

**Comment by Lschinor** [comment]
**Dados do Vs Code**
Versão: 1.81.0 (user setup)
Confirmar: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Data: 2023-08-02T12:37:13.485Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
SO: Windows_NT x64 10.0.22621

**Versão Totvs** 
![versaototvs](https://github.com/totvs/tds-vscode/assets/84096911/9da7e3ac-6d58-4d10-a473-a0bd4d7a4ec2)

**Versão do RPO (LIB) e do TOTVS Server**
![Versão do RPO (LIB) e do TOTVS Server](https://github.com/totvs/tds-vscode/assets/84096911/00aa14aa-b9ae-43cf-bd8f-9ae5aca72610)

Não consegui gerar os logs.

**Comment by lwtnb-wrk** [comment]
@Lschinor Removemos a ação ao clicar no environment que causava o erro, se quiser conectar no environment utilize o icone "Selecionar" do environmente para se conectar ou utilize o opção Conectar diretamente e selecione depois o environmente.
