### ISSUE TITLE
Configuração gitHub vs Vscode

### ISSUE THREAD

**Issue by alexandro102021** [totvs/tds-vscode#1133]
Bom dia, 

Por favor estou tentando configurar o GitHub para subir todos os meu fontes para repositório criado, mais não estou conseguindo.

Poderiam me ajudar?

Grato
Alexandro

**Comment by lwtnb-wrk** [comment]
@alexandro102021 Realmente aqui tratamos apenas de problemas da ferramenta tds-vscode.
