### ISSUE TITLE
Totvs Broker - 12.1.2210 - vsCode com erro "Authentication error: Server returned a non numeric value..."

### ISSUE THREAD

**Issue by rodrigoteixeira1975** [totvs/tds-vscode#1135]
Bom dia,

Já vi aqui nos posts anteriores que tivemos algumas outras ocorrências para o erro que estou tendo de conexão no vsCode, mas, não consegui localizar nenhuma ocorrência quando utilizando o TotvsBroker.

Segue abaixo erro ao informar dados para conexão no ambiente via vsCode:
"See AppServer log console for details. [Error - 09:28:39] 
  Authentication error: Server returned a non numeric value. See AppServer log console for details."

Já exclui o custom.rpo da pasta do repositorio e coloquei o repositorio padrão, mas, tambem sem sucesso.

Anexos estão os appserver.ini, tanto o server Broker quanto do ambiente o qual foi configurado para atualizações do rpo.

[APPSERVER_COMPILAR03.TXT](https://github.com/totvs/tds-vscode/files/12312788/APPSERVER_COMPILAR03.TXT)
[APPSERVER_BROKER.TXT](https://github.com/totvs/tds-vscode/files/12312789/APPSERVER_BROKER.TXT)

Atenciosamente
Rodrigo Teixeira

**Comment by lwtnb-wrk** [comment]
@rodrigoteixeira1975 O que você está tentando realizar? Um broker não deve ser utilizado como ambiente de desenvolvimento, i.e., compilar, depurar...
Quanto ao erro "Authentication error: Server returned a non numeric value", o problema realmente parece ser referente ao RPO corrompido ou configuração de ambiente, pois o tds-vscode aparentemente está tentando se conectar ao servidor e a autenticação está retornando um valor não esperado.
Você consegue se conectar diretamente nesse servidor através de um Smartclient? Se negativo, definitivamente seu ambiente está com problema, caso contrário, veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para análises.
