### ISSUE TITLE
Erro Validate Patch Fail. Please input patch file. (arquivos zip)

### ISSUE THREAD

**Issue by marciorollo** [totvs/tds-vscode#1136]
Bom dia!

Após atualizar para o TDS da versão v1.3.18 para 19 ou 20 esta apresentando o erro "Validate Patch Fail. Please input patch file." ao
aplicar um patch (arquivo zip).

![image](https://github.com/totvs/tds-vscode/assets/127785/6a9aaff4-5b25-4349-b14a-11e725ca033e)

**Comment by brodao2** [comment]
Favor complementar chamado informando os dados solicitados conforme [Informações importantes ao abrir o chamado](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#informa%C3%A7%C3%B5es-importantes-ao-abrir-uma-issue) e anexe os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)

**Comment by lwtnb-wrk** [comment]
@marciorollo Estamos avaliando a questão, por enquanto descompacte o arquivo e aplique o .ptm diretamente.

**Comment by marciorollo** [comment]
![image](https://github.com/totvs/tds-vscode/assets/127785/2db9b3dc-58d8-4d7e-b9cd-1e4fe13cbc2d)

![image](https://github.com/totvs/tds-vscode/assets/127785/a38bf224-9e11-4a29-bd6d-d82aaf48e8bf)

Dados do Server 

Versão: TOTVS Manufatura
Build AppServer: 7.00.210324P-20230228 - 64 bits
Nome do servidor: VMSRV-PROTHEUS
Sistema operacional: Windows Server 2012 R2
Appserver version: 20.3.1.4
Build DBAccess: 20220303-20230224
Release do RPO:  12.1.2210
Release do dicionário: 12.1.2210
Local files: ctree
License server: 2014 - 3.6.0
DB DataBase: MSSQL
DB API Build: 20220303-20230224

Versão da Lib:20230515
Data da Lib: 20230523_151237
Commit ID:019e83bcdc53e1a3cae5dbd9cca7bb6e7d2251c3
Central de Atualizações: 4371652 (14/08/23)

[totvsls_in.log](https://github.com/totvs/tds-vscode/files/12334491/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/12334492/totvsls_out.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/12334493/totvsls.log)

**Comment by lwtnb-wrk** [comment]
@marciorollo Geramos um VSIX contendo correções que devem solucionar seu problema. 

Para validar esta correção, favor baixar o arquivo VSIX v1.3.21 de https://github.com/totvs/tds-vscode/releases/tag/v1.3.21

Siga os procedimento para sua instalação segundo https://github.com/totvs/tds-
vscode/blob/master/docs/install.md#instalando-de-um-arquivo-vsix
