### ISSUE TITLE
Patch não consegue ser aplicado

### ISSUE THREAD

**Issue by raquelhager** [totvs/tds-vscode#1138]
Boa tarde!

Estou com a seguinte situação, ao tentar aplicar qualquer tipo de patch no VS Code, notei que durante a validação do patch o caminho do arquivo é trocado e por isso ele acaba não sendo validado e muito menos aplicado.

Utilizei os seguintes artefatos:
01/08/2023, 15:10:11 (publicado)
23-07-28-P12_APPSERVER_BUILD-20.3.1.12_WINDOWS_X64

21/07/2023, 16:44:42 (publicado)
23-07-26-P12-SMARTCLIENT_BUILD 20.3.1.5_WINDOWS_X64

15/08/2023, 11:25:50 (d-1)
tttm120.rpo

VS Code
Versão 1.3.20

Como devo proceder neste caso?

![Aplicação-Patch-1](https://github.com/totvs/tds-vscode/assets/55213765/e89b06a5-09c2-45e0-9623-3ce0f142ce56)
![Aplicação-Patch-2](https://github.com/totvs/tds-vscode/assets/55213765/278b0052-b3d6-4758-8d43-77c78b40f459)

**Comment by DanielYampolschi** [comment]
Isso acontece pois, a partir da versao 1.3.20, o patch é validado no momento em que é adicionado, antes mesmo da aplicação, e para fazer isso, é necessário já envia-lo para o servidor. A informação do caminho que você vê é apenas a localização dele no servidor. Portantao, o problema que você observa. não necessariamente tem a ver com isso.

Por favor siga os passos do link abaixo para gerar os logs para analisarmos:

https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs

Obrigado.

**Comment by raquelhager** [comment]
[appserver.zip](https://github.com/totvs/tds-vscode/files/12352191/appserver.zip)

**Comment by raquelhager** [comment]
Boa tarde!

Ao tentar seguir os procedimentos acima notei  que o caminho do meu RootPath no appserver.ini estava errado..
RootPath=C:\Protheus12ROBO\HARPIA_BRA\P122210_BRA
Na verdade a pasta P122210_BRA  é o meu Protheus_Data
O caminho abaixo não existe:
RootPath=C:\Protheus12ROBO\HARPIA_BRA\P122210_BRA\Protheus_Data

Depois que ajustei consegui aplicar o patch!

Muito obrigada!
