### ISSUE TITLE
Aplicar patch TSS

### ISSUE THREAD

**Issue by douglasizidio** [totvs/tds-vscode#1139]
Boa tarde,

Nas versões v1.3.19 e v1.3.20 está ocorrendo o erro abaixo ao tentar aplicar patch no RPO do TSS.

Erro: Get organization list could not be executed. Server returned: Error reading data from SX's files.

**Desktop (please complete the following information):**
 - OS/Architecture: [Windows 11 64 bits]

**Appserver (please complete the following information):**
 - Build (with date): [APPSERVER_BUILD-20.3.1.9_WINDOWS_X64 ]
 - OS/Architecture: [Windows Server 2012 64 bits]

Output em anexo.
[VsCode Output.txt](https://github.com/totvs/tds-vscode/files/12399454/VsCode.Output.txt)

**Comment by lwtnb-wrk** [comment]
@douglasizidio Por enquanto retorne para a versão 1.3.18, mas já estamos analisando esta questão reportada.

**Comment by lwtnb-wrk** [comment]
@douglasizidio Geramos um VSIX contendo correções que devem solucionar seu problema. 

Para validar esta correção, favor baixar o arquivo VSIX v1.3.21 de https://github.com/totvs/tds-vscode/releases/tag/v1.3.21

Siga os procedimento para sua instalação segundo https://github.com/totvs/tds-
vscode/blob/master/docs/install.md#instalando-de-um-arquivo-vsix
