### ISSUE TITLE
Para projetos não TOTVS, não iniciar configuração automaticamente

### ISSUE THREAD

**Issue by rvieceli** [totvs/tds-vscode#114]
Uso o vscode para AdvPL, mas também Node/Reacts/Python, e toda vez que abro um projeto desses abre a tela para configuração do projeto TOTVS.

Poderia ter opção F1 + "iniciar projeto totvs" 
ou/e quando identificar arquivo .pr?/.tlpp/.ap? e outros mais na pasta aberta, ou quando criar um arquivo nessas extensões, abrir a configuração.

**Comment by lwtnb-wrk** [comment]
@rvieceli Voce se refere a tela de "Boas Vindas" ("Welcome")? Normalmente apos a primeira execução ao configurar o local do smartclient e includes, esta tela nao deveria ser mais exibida.
Porem para ela ser exibida novamente é possivel habilitar atraves das preferencias ("Settings") na seção "totvsLanguageServer.welcomePage".
Veja se esta opção esta marcada e caso afirmativo desmarque para que a tela nao volte a aparecer.

**Comment by rvieceli** [comment]
Opa, é justamente o contrário, não quero que nada inicie em projeto node por exemplo.
Deixando esta opção como falso, resolve parte do problema, não abre mais a tela, mas continua com ambiente TOTVS ativo.
![image](https://user-images.githubusercontent.com/2790845/61010889-7a87af80-a34e-11e9-8a9b-3104e2703b0f.png)

e só consigo desabilitar por completo, desabilitando para o projeto, e tenho que fazer isso para todos.
![image](https://user-images.githubusercontent.com/2790845/61010928-9723e780-a34e-11e9-829f-16909ef3bca1.png)

No eclipse tem uma opção quando o projeto não era TOTVS para torna-lo TOTVS, deveria ter uma opção semelhando, pois o VSCode pode ser a IDE para muitos projetos em linguagens e frameworks diferentes.

**Comment by lwtnb-wrk** [comment]
@rvieceli Se voce iniciar o VS Code em uma pasta sem arquivos ".prw" ou outros de AdvPL, a extensão "tds-vscode" não será iniciada. Mas uma vez iniciada acredito que não é normal ela ser finalizada a não ser que voce feche o VS Code ou troque de pasta.
Inclusive na troca de pasta voce pode perceber que o VS Code "pisca" pois ele, acredito que, praticamente se recarrega todo e se a nova pasta não tiver arquivos TOTVS ele não vai carregar o "tds-vscode".
Talvez seu problema seja que ao fechar o VS Code voce esteja em um projeto com arquivo AdvPL e a extensão "tds-vscode" ativa. Ao abrir o VS Code novamente ele continua de onde estava ou seja na pasta com arquivos AdvPL então o "tds-vscode" inicia.
Se quiser abrir um VS Code limpo, clique no icone do VS Code com o botao direito e selecione "Nova Janela" ("New Window") e voce pode começar seu projeto Node ou outro qualquer sem a interferencia do "tds-vscode".
