### ISSUE TITLE
Debug no MACOS - 1.3.19 e 1.3.20

### ISSUE THREAD

**Issue by Carraro-BH** [totvs/tds-vscode#1140]
Bom dia!

O erro descrito na issue #1083 (https://github.com/totvs/tds-vscode/issues/1083) voltou a ocorrer nas atualizações 1.3.19 e 1.3.20. 

Realizando o downgrade para 1.3.18 o problema não ocorre.

Error(-1): Falha ao iniciar o SmartClient. Command: /Applications/Work/Totvs/smartclient/smartclient.app -DEBUG=13028 -z=nome_servidor -y=1301  "-E=DEV" "-P=sigaadv"  -M

At.

Carraro

**Comment by danielbolognani** [comment]
Normalmente precisa apontar para o executável em si e não para o pacote (.app)
Não é só mudar sua configuração para smartclient.app/Contents/MacOS/smartclient ?

**Comment by Carraro-BH** [comment]
Boa Daniel! Fiz conforme informou e funcionou adequadamente, porém na 1.3.18 o problema não ocorria mesmo utilizando a direção do Pacote. Todavia fica a informação de que há esta diferença a partir da 1.3.19. Muito obrigado pela dica!
