### ISSUE TITLE
Aumentou o consumo de CPU

### ISSUE THREAD

**Issue by mandjf** [totvs/tds-vscode#1143]
Bom dia, 

Após atualização para a versão 1.3.21, o consumo da CPU aumentou bastante, para algo em torno de 45% somente para a extensão no VS Code.

Grato,

Marcelo Dutra

**Comment by heitorwss** [comment]
Estou com o mesmo problema, após a atualização da extensão 50% de cpu sempre.....

**Comment by lwtnb-wrk** [comment]
Liberamos uma funcionalidade que ainda esta em desenvolvimento, porem ja publicamos a versão 1.3.22 removendo essa funcionalidade.
