### ISSUE TITLE
Aplicação de Patch

### ISSUE THREAD

**Issue by fjcgnogueira** [totvs/tds-vscode#1145]
Bom dia

Após atualização do plugin "TOTVS Developer Studio for VSCode (AdvPL, TLPP e 4GL)" para a versão v1.3.22 não consigo mais fazer aplicação de patchs.

Na janela de aplicação de patchs não traz mais de forma automática as informações do server, como nome, endereço e ambiente.

Dessa forma não habilita o botão para aplicação da patch.

Att,
Fernando Nogueira

**Comment by DanielYampolschi** [comment]
bom dia @fjcgnogueira, consegui reproduzir aqui. Muito obrigado por reportar.
