### ISSUE TITLE
Problema com aplicação de patchs

### ISSUE THREAD

**Issue by gposetta** [totvs/tds-vscode#1146]
Não consigo aplicar os patchs, na tela onde selecionamos os pacotes os botões ficam desabilitados. Consigo buscar o pacote a ser aplicado porem na hora de confirmar o botão fica desabilitado impossibilitando o processo. Fiz a desinstalação do VSCode instalei novamente e o problema persiste.

**Comment by lwtnb-wrk** [comment]
@gposetta Uma correção referente a essa questão foi publicada agora a pouco, poderia confirmar se a versão da sua extensão já esta como 1.3.23?
Caso afirmativo, veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by gposetta** [comment]
Estou com a v1.3.22

**Comment by lwtnb-wrk** [comment]
@lwtnb-wrk Atualize para a 1.3.23 e verifique se tudo está em ordem.

**Comment by gposetta** [comment]
Deu certinho.
Muito obrigado!!!
