### ISSUE TITLE
 Vscode Travando o serviço no debug quando demora muito para finalizar as validações

### ISSUE THREAD

**Issue by Jfcastaldi** [totvs/tds-vscode#1147]
Bom dia!
Vscode Travando o serviço no debug quando demora muito para finalizar as validações.
esse comportamento começou a ocorrer depois que atualizamos o ambiente para a versão 12.1.2210 Protheus
VCcode 1.3.22

**Comment by lwtnb-wrk** [comment]
@Jfcastaldi Poderia dar maiores detalhes do que está tentado fazer? 
A atualização em questão seria do 12.1.33 para o 12.1.2210??
Além da LIB houve atualização de binário?
Poderia anexar um video demonstrando essa diferença?
Grato pelas informações.

**Comment by Jfcastaldi** [comment]
Bom dia!
a versão atual é a 12.1.2210 e o Binario Build Version: 20.3.1.12 
Versão da Lib:20230515
Data da Lib: 20230523_151237
o problema de travamento vem ocorrendo desde a mudando da versão de 12.1.27 p/ 12.1.2210 em todas as atualizações de LIB e Binário necessárias para a versão 
o problema ocorre em todos os nossos desenvolvedores que utilizam nosso projeto.
Não sei se precisa de alguma configuração especifica no appserver.ini além do BuildKillUsers=1 e no Vscode "enableMultiThread": true no caso de rest
há um erro de sincronismo com o smarclient porem quando acontece o erro o RPO fica trava
![image](https://github.com/totvs/tds-vscode/assets/73646396/4c6c7d49-3bcb-4445-9c7d-5f1f53c81eec)
![image](https://github.com/totvs/tds-vscode/assets/73646396/a55887b9-0d27-4135-b25e-eaf772c81bb2)
derrubo o que ficou travado 
![image](https://github.com/totvs/tds-vscode/assets/73646396/15461351-c389-4c4b-95bf-0759a96ebe53)
ai tento compilar e ocorre o erro dizendo que está em modo exclusivo o RPO e a alternativa seria derrubar o serviço e iniciar novamente 
![image](https://github.com/totvs/tds-vscode/assets/73646396/936513f5-0e18-4fd8-8c4c-5733ab974b98)



Obrigado 
José Frrancisco

**Comment by Jfcastaldi** [comment]
Complementando 
o smartclient utilizado no VScode 
está na pasta 
![image](https://github.com/totvs/tds-vscode/assets/73646396/452c39b9-df68-484c-8da2-1592c7cd513d)

da versão 12.1.2210
Obrigado

**Comment by lwtnb-wrk** [comment]
@Jfcastaldi Em que situação ocorre o travamento na depuração? Você está depurando um serviço REST?
Pelo que descreveu, o problema original seria na depuração, pois o erro na compilação ocorre após o problema de travamento na depuração correto?
Se o problema for na depuração veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para análise, em especial o dap.log
Se possível envie o console.log do AppServer em que ocorreu essa situação de travamento.

**Comment by Jfcastaldi** [comment]
Preparei o ambiente de só executei o sistema depurando fiquei 3 minutos sem fazer nenhuma chamada de Menu e já travou  
![image](https://github.com/totvs/tds-vscode/assets/73646396/083ffc88-59a7-4186-8a62-a54b9188615c)
Dados do Server 

Versão: TOTVS Distribuição e Logística
Build AppServer: 7.00.210324P-20230727 - 64 bits
Nome do servidor: RHL0TRPRHOMBN41
Sistema operacional: Windows Server 2012 R2
Appserver version: 20.3.1.12
Build DBAccess: 20220303-20230623
Release do RPO:  12.1.2210
Release do dicionário: 12.1.2210
Local files: ctree
License server: 2014 - 3.6.0
DB DataBase: MSSQL
DB API Build: 20220303-20230623
Versão da Lib:20230807
Data da Lib: 20230811_162829
Commit ID:f9cd43f38e6cae700a18e8aa1359193583f7d004
Central de Atualizações: 4464404 (31/08/2023)
![image](https://github.com/totvs/tds-vscode/assets/73646396/4a8de1f6-3ad5-40fa-b5b3-f85403201640)
![image](https://github.com/totvs/tds-vscode/assets/73646396/e8bf331e-1db9-45dc-9836-5d4e631076c2)
[RHL0TRPRHOMCR40_console_RHL0TR_HOM_COMP_24001.log](https://github.com/totvs/tds-vscode/files/12515766/RHL0TRPRHOMCR40_console_RHL0TR_HOM_COMP_24001.log)

[dap.log](https://github.com/totvs/tds-vscode/files/12515757/dap.log)
Os arquivos totvsls.log" , "totvsls_in.log" e "totvsls_out.log nem mesmo foram gerados porque provavelmente eu nem mesmo consegui dar inicio a depuração

**Comment by brodao2** [comment]
Experimenta aumentar o timeout. No ini do appServer, na sessão ``General``:

``inactiveTimeout=<segundos>``

``<segundos>`` é o tempo de inatividade para o appServer fechar a conexão. Salvo engano, 3min é o valor padrão.

**Comment by Jfcastaldi** [comment]
Boa Tarde!
Nunca determinamos o tempo no Appserver.ini justamente p/ não ocorrer esse tipo de problema o timeout é determinado em usuários 
e esse problema começou com a versão 12.1.2210 na versão 12.1.27 não ocorria esse problema e inclusive as principais configurações do appserver.ini permanece as mesmas mudando apenas a compatibilidade da versão 

[Appserver.txt](https://github.com/totvs/tds-vscode/files/12515883/Appserver.txt)

Tentative de depurar um programa e em seguida um erro 
![image](https://github.com/totvs/tds-vscode/assets/73646396/677fe840-7f48-4c15-8237-bac23a8c6625)
Serviço travado 
Processo ainda em execução só consigo dar continuidade se derrubar o serviço

**Comment by lwtnb-wrk** [comment]
@Jfcastaldi Percebi um erro no console.log que não creio que deveria ocorrer. Poderia realizar um teste e alterar seu AppServer.ini na seção [TELNET] e trocar a chave Enable=0. Reinicie o AppServer para essa configuração surtir efeito. 
E outra coisa, ao disparar a depuração não utilize um módulo SIGAMDI, este módulo para depuração pode causar comportamentos inesperados.
Realize novos testes de depuração para que possamos entender se isso está causando o problema relatado. 
Se o erro persistir nos envie novamente os logs console.log e dap.log
Grato pelos testes.

**Comment by Jfcastaldi** [comment]
Estamos em Cloud, vou ter que abrir um chamado na Totvs para alterar a chave 
logo que possível efetuo novos testes 
Obrigado

**Comment by brodao2** [comment]
> Boa Tarde! Nunca determinamos o tempo no Appserver.ini justamente p/ não ocorrer esse tipo de problema o timeout é determinado em usuários e esse problema começou com a versão 12.1.2210 na versão 12.1.27 não ocorria esse problema e inclusive as principais configurações do appserver.ini permanece as mesmas mudando apenas a compatibilidade da versão


Como houve troca de binários (appServer), pode ter ocorrido alteração de comportamento.
Sugiro um teste de colocar o ``inactiveTimeout`` com valor de 5 min (300) e verificar o comportamento.

Em meus ambientes de desenvolvimento, costumo usar 15 min (900) independente da versão do appServer.

**Comment by Jfcastaldi** [comment]
> @JfcastaldiPercebi um erro no console.log que não acredito que deveria ocorrer. Você poderia realizar um teste e alterar seu AppServer.ini na seção [TELNET] e trocar a chave Enable=0. Reinicie o AppServer para essa configuração surtir efeito. E outra coisa, ao disparar a depuração não utilizar um módulo SIGAMDI, este módulo para depuração pode causar comportamentos inesperados. Realize novos testes de depuração para que possamos entender se isso está causando o problema relatado. Se o erro persistir nos envie novamente os logs console.log e dap.log Grato pelos testes.

Boa Tarde! lwtnb-wrk

agora deu certo,  dentre as duas orientação que você deu acho que a que teve efeito foi a do não utilização do SIGAMDI, efetuei varias vezes e não ocorreu o erro, inclusive testei em outros serviços que inclusive tinha a chave enable=1
executando diretamente com os modulos ou com o sigaadv Sem erros
Muito obrigado pela ajuda 
um grande Abraço

**Comment by lwtnb-wrk** [comment]
@Jfcastaldi Excelente. Vamos destacar essa informação na nossa documentação para reforçar que o SIGAMDI não deve ser utilizado no modo de depuração.
