### ISSUE TITLE
Secure authenticating...

### ISSUE THREAD

**Issue by cleberfernandes1** [totvs/tds-vscode#1148]
Meu VSCODE não conecta fico na mensagem Secure authenticating... e não apresenta nenhum erro 
Voltei algumas versões para ver se resolvia e não resolveu o problema
Parou de funcionar do nada

**Comment by lwtnb-wrk** [comment]
@cleberfernandes1 Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para análise.

**Comment by cleberfernandes1** [comment]
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/12516494/totvsls_in.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/12516495/totvsls.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/12516496/totvsls_out.log)

Deixei alguns minutos rodando e segue o log

**Comment by lwtnb-wrk** [comment]
@cleberfernandes1 Realmente o processo ficou parado na autenticação.
Você consegue acessar esse ambiente neste AppServer diretamente através de um Smartclient sem utilizar o tds-vscode??

**Comment by cleberfernandes1** [comment]
Sim consigo, o mais estranho é estava funcionando certinho, derrepente parou 
Achei estranho pois não mostra nenhum erro

**Comment by lwtnb-wrk** [comment]
@cleberfernandes1 E isso ocorre com qualquer AppServer? Ou ocorre com qualquer AppServer que você tenta se conectar?

**Comment by cleberfernandes1** [comment]
A principio é só um server, mais tive que excluir ele para conseguir conectar nos outros 
no console.log fica Starting Debugger

Mais excluindo todos os servers e adicionando novamente o problema foi corrigido

**Comment by lwtnb-wrk** [comment]
@cleberfernandes1 Que bom que resolveu, mas realmente este caso foi estranho pois não deu erro. Enfim pelo menos sabemos que nestes casos de travamento no "Secure authenticating..." pode ser resolvido com uma reconfiguração dos servidores.
Valeu pela informação.
