### ISSUE TITLE
Invalid rootUri. Please fix your workspace configuration and try again.

### ISSUE THREAD

**Issue by bocaotmkt** [totvs/tds-vscode#1150]
**Describe the bug**
Ao efetuar a simples abertura do vscode o sistema apresenta a mensagem de Invalid rootUri. Please fix your workspace configuration and try again. Efetuamos a reconfiguração das pastas e criação de novo workspace mas o problema persiste, atualizamos para ultima atualização da extensão, mas mesmo assim o problema persiste.

**To Reproduce**
1 - Possuir workspace configurado;
2 - Ter o totvs=vscode com extensão;
3 - Simplesmente abrir o vscode

**Expected behavior**
Ao acessar o vscode não apresente a mensagem "Invalid rootUri. Please fix your workspace configuration and try again."

**Screenshots**
![image](https://github.com/totvs/tds-vscode/assets/72392906/c98b33d4-9a0f-43b6-8946-098cd017f1e1)

**Desktop (please complete the following information):**
 - Windows 11 - 64bits

**Appserver (please complete the following information):**
Versão 12.1.2310 porém deixou de funcionar em todas as versões.
***  TOTVS S/A  ***
***  www.totvs.com.br  ***
* TOTVS - Build 7.00.210324P - Jun 26 2023 - 19:37:55
* Build: 64 bits
* SVN Revision: 39195
* Build Version: 20.3.2.0_ts11

**Comment by bocaotmkt** [comment]
Tentei refazer conforme dica https://devforum.totvs.com.br/3668-vs-code-nao-conecta-no-servidor-para-compilar mesmo assim não obtive êxito

**Comment by lwtnb-wrk** [comment]
@bocaotmkt Geralmente essa mensagem é emitida quando não temos um projeto/workspace aberto no tds-vscode durante sua inicialização, porém pela imagem anexada aparentemente existe um workspace aberto.
Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs gerados para análises.
