### ISSUE TITLE
Ponto de entrada FA181EST - ExecAuto + MostraErro

### ISSUE THREAD

**Issue by rodrigoteixeira1975** [totvs/tds-vscode#1152]
Bom dia,

Na rotina FINA716 (POUI) é chamado o ponto de entrada FA181EST, neste ponto de entrada tenho um execauto da rotina FINA100, após processar o execauto, quando existir erro é chamada a função MostraErro(), quando chama esta função MostraErro() vem a mensagem "Internal Server Error" 

MSExecAuto({|x,y,z| FinA100(x,y,z)},0,aFINA100,7)
If lMsErroAuto
    MostraErro()
EndIf

Não podemos utilizar a MostraErro() em POUI ?

Atte
Rodrigo Teixeira

**Comment by lwtnb-wrk** [comment]
@rodrigoteixeira1975 Tratamos aqui de problemas exclusivamente da ferramenta tds-vscode. Para assuntos relacionados a programação, procure diretamente o suporte da TOTVS.

**Comment by rodrigoteixeira1975** [comment]
Perfeitamente.
Obrigado pela orientação
