### ISSUE TITLE
Compilação de Arquivo TLPP não busca os .TH da pasta include configurada no servers.json

### ISSUE THREAD

**Issue by alexandreandradeg** [totvs/tds-vscode#1153]
Boa tarde,

Estou usando Mac OS Darwin x64 22.6.0
Visual Studio Code 1.8.3.1 (Universal)
Totvs Developer Studio for VSCODe 1.3.23

Copiei os arquivos .TH (includes TLPP) para dentro da pasta onde já estavam os outros includes .CH configurado no servers.json, e ao tentar compilar um arquivo TLPP ele não encontra as includes.

Somente compilou, após colocar os includes, dentro da mesma pasta onde estava o fonte TLPP.

![image](https://github.com/totvs/tds-vscode/assets/53089942/2fa15fdf-a5a1-4415-ac87-c115caee8f83)
![image](https://github.com/totvs/tds-vscode/assets/53089942/f15d7ca6-24c4-49ad-9dbc-a2d48cca79ff)

**Comment by brodao2** [comment]
Olá @alexandreandradeg 

Você deve especificar a pasta onde esta os arquivos de definição de forma explicita.
Sugiro que coloque-os em uma pasta diferente dos fontes, que conterá apenas arquivos de definição do TH (evitaria usar a pasta .ch padrão).

A configuração é efetuada no arquivo de definição de servidor (``servers.json``).
Detalhes em [Visão Servers](https://github.com/totvs/tds-vscode/blob/master/docs/servers.md#vis%C3%A3o-servers)].

À disposição.

**Comment by alexandreandradeg** [comment]
Boa tarde, perdão acho que não fui claro no texto que enviei, meu ambiente já está configurado corretamente, mas na hora de compilar, ele não está respeitando a pasta de includes definida dentro do servers.json para arquivos TLPP.

Para arquivos PRW compila normalmente, e encontra os (includes .CH) na pasta definida, mas quando é TLPP ele não encontra os (includes .TH) mesmo a pasta estando definida no servers.json

Veja o print abaixo, o caminho está correto, e os arquivos .CH e .TH estão na pasta corretamente.

![image](https://github.com/totvs/tds-vscode/assets/53089942/c3d6837c-704c-4ba7-8687-4401a55dfd0f)

**Comment by brodao2** [comment]
Na chave "includes", você deve adicionar a pasta onde está os TH.
Por hábito, uso duas pastas, uma os CH padrão e outra pro TLPP.
![image](https://github.com/totvs/tds-vscode/assets/114854608/54f70660-3ebe-4e4b-b503-a2b4341b1ac3)

**Comment by brodao2** [comment]
No print que mandou, há arquivos TH, por isso entendi que havia colocado junto com os fontes.
A pasta indica para "includes" tem os TH?

**Comment by alexandreandradeg** [comment]
Bom dia, coloquei os includes em pasta separada conforme seu print, e agora deu certo, muito obrigado.
