### ISSUE TITLE
Excluir Fonte do RPO

### ISSUE THREAD

**Issue by jpinto10** [totvs/tds-vscode#1154]
Bom dia
Ao tentar excluir um fonte do RPO o sistema apresenta essa mensagem.
Obs.: Consigo compilar normalmente e sou adm ( tenho a senha de adm ) 

[Info  - 11:41:22 AM] Starting program deletion.
[Info  - 11:41:22 AM] Starting build for environment FREITASVAREJO.
[Info  - 11:41:26 AM] Starting build using RPO token ...
[Error - 11:41:26 AM] One or more programs could not be deleted from RPO. Server returned: No programs are removed.
[Info  - 11:41:26 AM] Aborting end build (rollback changes).

Estamos na 12.22.10

**Comment by brodao2** [comment]
Pela mensagem de retorno, o fonte não existe no rpo ou é um fonte padrão. Nesse 2o caso, somente com token de rpo aplicado.

Para verificar o fonte, acione o inspetor de objetos

**Comment by jpinto10** [comment]
Boa tarde..

Não é fonte padrão.

Pior que o fonte existe.

Eu compilo mais não apago.

 

Vou mandar um vídeo, pode ser?

 

 

De: Alan Candido ***@***.***> 
Enviada em: sexta-feira, 3 de novembro de 2023 14:57
Para: totvs/tds-vscode ***@***.***>
Cc: Edilson ***@***.***>; Author ***@***.***>
Assunto: Re: [totvs/tds-vscode] Excluir Fonte do RPO (Issue #1154)

 

Pela mensagem de retorno, o fonte não existe no rpo ou é um fonte padrão. Nesse 2o caso, somente com token de rpo aplicado.

Para verificar o fonte, acione o inspetor de objetos

**Comment by jpinto10** [comment]
Desculpe..

Você tinha razão!!

 

Não estava no RPO 

Obrigado

 

De: Alan Candido ***@***.***> 
Enviada em: sexta-feira, 3 de novembro de 2023 14:57
Para: totvs/tds-vscode ***@***.***>
Cc: Edilson ***@***.***>; Author ***@***.***>
Assunto: Re: [totvs/tds-vscode] Excluir Fonte do RPO (Issue #1154)

 

Pela mensagem de retorno, o fonte não existe no rpo ou é um fonte padrão. Nesse 2o caso, somente com token de rpo aplicado.

Para verificar o fonte, acione o inspetor de objetos
