### ISSUE TITLE
Outline com estrutura de classe

### ISSUE THREAD

**Issue by ccabagro** [totvs/tds-vscode#1155]
Na visão do Outline é exibida corretamente as funções de um determinado fonte. Porém se o fonte possui uma ou mais classes, os métodos delas não são exibidos.

Poderiam verificar a possibilidade de ser implementado a estruturas de classes no Outline? É uma ferramenta que ajuda bastante em fonte muitos longos.

Outline em fonte com funções:
![image](https://github.com/totvs/tds-vscode/assets/53842559/55918bb1-2814-4503-bab2-d2f54b3a1432)

Outline em fonte com classe (9 métodos implementados):
![image](https://github.com/totvs/tds-vscode/assets/53842559/015ade6f-fd56-41db-8e5b-edac1fcb1131)

**Comment by brodao2** [comment]
Favor complementar chamado informando os dados solicitados conforme [Informações importantes ao abrir o chamado](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#informa%C3%A7%C3%B5es-importantes-ao-abrir-uma-issue) e anexe os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)

É de extrema importância informar um passo a passo e se possível, anexe print de telas ou vídeo e o console log do Protheus.

No aguardo.

**Comment by ccabagro** [comment]
> Favor complementar chamado informando os dados solicitados conforme [Informações importantes ao abrir o chamado](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#informa%C3%A7%C3%B5es-importantes-ao-abrir-uma-issue) e anexe os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)
> 
> É de extrema importância informar um passo a passo e se possível, anexe print de telas ou vídeo e o console log do Protheus.
> 
> No aguardo.

Segue informações:

Versão do VS CODE:

Version: 1.84.2 (user setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22635

Versão da Extensão:
1.3.23

**Comment by ccabagro** [comment]
> Se desejar, pode nos ajudar usando [v2.0.0-RC14](https://github.com/totvs/tds-vscode/releases/tag/v2.0.0-RC14), que possui uma série de novas funcionalidades e inclusive, essa correção.
> 
> Conheça-as em [Versão 2.0.0](https://github.com/totvs/tds-vscode/blob/dev2/CHANGELOG-V2.md#vers%C3%A3o-200)
> 
> Grato pela colaboração.

Será um prazer, vou testar a nova versão :)

**Comment by lwtnb-wrk** [comment]
https://github.com/totvs/tds-vscode/blob/master/docs/install.md
