### ISSUE TITLE
Extensão no vscode

### ISSUE THREAD

**Issue by cesantosrj** [totvs/tds-vscode#1156]
Prezados boa tarde.
Toda vez que tento compilar no vscode aparece erro na extensão, mesmo usando a extensão correta.

![image](https://github.com/totvs/tds-vscode/assets/150052803/0a0edad1-0c16-4037-a025-a2d5236e527a)

**Comment by danielbolognani** [comment]
O atalho Ctrl-F9 compila o documento em foco pelo VSCode. No seu caso o que está em foco é a janela de saída (output) e não a janela do fonte em si.
Clique primeiro em alguma linha do fonte PRW e após isso utilize o atalho CTRL-F9 ou utilize o botão direito diretamente no fonte e selecione a opção "Compile"

**Comment by cesantosrj** [comment]
Muito obrigado meu amigo, agora consigo compilar.
