### ISSUE TITLE
Configurar Saída padrão no VSCode

### ISSUE THREAD

**Issue by wendel-borges** [totvs/tds-vscode#1157]
Bom dia,
Sempre que abro o VSCode, no Painel "SAÍDA", sempre fica com a opção "Advpl" como padrão, saberiam informar se tem como mudar esse padrão para "TOTVS LS"?
![VSCode](https://github.com/totvs/tds-vscode/assets/150147945/f975ae9c-d6b7-4931-8753-9ae39a3b877e)

**Comment by brodao2** [comment]
@wendel-borges 

Grato pela melhoria apontada. Vamos verificar se há essa possibilidade.

**Comment by brodao2** [comment]
@wendel-borges 

Verifiquei aqui a possibilidade e não é possível efetuar essa mudança.
A aba "Saída" é de uso genérico pelo próprio VS-Code.

Vou verificar se é possível criar uma aba própria pra o Totvs-LS.

**Comment by lwtnb-wrk** [comment]
@wendel-borges Avaliamos esta questão mas não faremos novas implementações nessa área. 
O "problema" do foco na aba Output é que várias extensões pedem o foco para suas saídas e o "TOTVS LS" é apenas uma delas.
Neste caso a extensão da opção "Advpl" acaba por pedir o foco por último e fica marcada.
Como não temos controle sobre isso não faremos mais nada a respeito.
De qualquer forma grato pela sugestão e se tiver outras favor abrir novas issues de melhoria.
