### ISSUE TITLE
Connection failed. Conectar para debugar serviço rest

### ISSUE THREAD

**Issue by joaocoelho90** [totvs/tds-vscode#1158]
Boa tarde
Estamos tentando conectar pelo VS CODE no IP/PORTA TCP do serviço rest que temos e ocorre a mensagem Connection failed. Could not connect to server.
Teria algo que precisa ter no arquivo .ini do serviço para conectar?
[Info - 11:47:17 AM] Starting connection to the server 'reste base teste debugar' ([10.80.0.7@1079](mailto:10.80.0.7@1079))
[Error - 11:47:19 AM] Connection failed. Could not connect to server 10.80.0.7:1079.

![image](https://github.com/totvs/tds-vscode/assets/82460556/62d2ebac-dc44-489d-97f8-51d9c4b0c6c5)

**Comment by danielbolognani** [comment]
Esse ip/porta é uma servidor/porta Multiprotocolo do appserver ?
Se for um serviço HTTP do appserver, não vai conseguir conectar mesmo. 
Por padrão, esse ip/porta precisa estar acessível pelo Smartclient Desktop, se conseguir acessar pelo Smartclient, o VSCode consegue conectar também.

**Comment by joaocoelho90** [comment]
@danielbolognani o multiprotocolo desse serviço está desabilitado.
O que devo fazer para que ele inicie no smartclient desktop e também conecte no vs?
@brodao2 eu habilitei já o multithread.

Segue o ini e parametros que estão nele:
;--------------
;AMBIENTES
;--------------

[REST]
SOURCEPATH=D:\TOTVS12\Protheus\protheus\apo_rest
RPOCustom=D:\TOTVS12\Protheus\protheus\apo_rest\custom\mycustom.rpo
ROOTPATH=D:\TOTVS12\Protheus\protheus_data\
STARTPATH=\system\
RPODB=Top
RPOVERSION=120
LOCALFILES=CTREE
TRACE=0
LOCALDBEXTENSION=.dtc
TOPMEMOMEGA=1
PICTFORMAT=DEFAULT
DATEFORMAT=DEFAULT
REGIONALLANGUAGE=BRA
TOPPORT=7892
TOPDATABASE=MSSQL
TOPSERVER=10.80.0.14
TOPALIAS=dadosadv
THEME=STANDARD
HELPSERVER=10.80.0.13:8283
FWTRACELOG=1
ChangeEncodingBehavior=1
StartSysinDB=1
SpecialKey=Producao
;FWLOGMSG_DEBUG = 1


;--------------
;CONFIGURA  ES
;--------------

[Drivers]
Active=TCP
MULTIPROTOCOLPORT=1  

[TCP]
TYPE=TCPIP
Port=1079

[Service]
Name=TOTVS-Appserver12_rest
DisplayName=TOTVS | Appserver 12_rest

[General]
InstallPath=D:\TOTVS12\Protheus\protheus
CONSOLELOG=1
CONSOLEFILE=D:\TOTVS12\Protheus\protheus\Logs\outros_logs\wsrest.log
CONSOLEMAXSIZE=2120000
SEGMENTO=pV2QYzlWQdud=HZy=JHb
MaxQuerySize=31960
MAXSTRINGSIZE=5000
APP_ENVIRONMENT=REST
BuildKillUsers=1
;FWLOGMSG_DEBUG = 1

[LICENSECLIENT]
server=10.80.0.13
port=5562
                  
[MAIL]
Protocol=SMTP
AUTHLOGIN=1
AUTHNTLM=0

[SSLConfigure]
HSM=0
SSL2=1
SSL3=1
TLS1=3
TLS1_0 = 1
TLS1_1 = 0
TLS1_2 = 0

[HTTPJOB]
MAIN=HTTP_START
ENVIRONMENT=REST

[HTTPV11]
Enable=1
Sockets=HTTPREST

[HTTPREST]
Port=9213
IPsBind=
URIs=HTTPURI1, HTTPURI2, HTTPURI3, HTTPURI4, HTTPURI5, HTTPURI6, HTTPURI7, HTTPURI8
Security=0

[HTTPURI1]
URL=/rest
CORSEnable=1
PrepareIn=09
Instances=1,1
AllowOrigin=*
ENVIRONMENT=REST

[HTTPURI2]
URL=/rest
CORSEnable=1
PrepareIn=03
Instances=1,1
AllowOrigin=* 
ENVIRONMENT=REST

[HTTPURI3]
URL=/rest
CORSEnable=1
PrepareIn=02
Instances=1,1
AllowOrigin=* 
ENVIRONMENT=REST

[HTTPURI4]
URL=/rest
CORSEnable=1
PrepareIn=08
Instances=1,1
AllowOrigin=* 
ENVIRONMENT=REST

[HTTPURI5]
URL=/rest
CORSEnable=1
PrepareIn=11
Instances=1,1
AllowOrigin=* 
ENVIRONMENT=REST

[HTTPURI6]
URL=/rest
CORSEnable=1
PrepareIn=13
Instances=1,1
AllowOrigin=* 
ENVIRONMENT=REST

[HTTPURI7]
URL=/rest
CORSEnable=1
PrepareIn=14
Instances=1,1
AllowOrigin=* 

[HTTPURI8]
URL=/rest
CORSEnable=1
PrepareIn=15
Instances=1,1
AllowOrigin=* 

[OnStart]
JOBS=HTTPJOB
RefreshRate=120

[HTTP]
Enable=1
Port=9214
Path=D:\TOTVS12\Protheus\protheus_data\http-root
ENVIRONMENT=REST
Cache-Control = no-store
XFRAMEOPTIONS = ALLOW-FROM *

**Comment by joaocoelho90** [comment]
Resolvido, foi só comentar essa seção:
[SSLConfigure]
HSM=0
SSL2=1
SSL3=1
TLS1=3
TLS1_0 = 1
TLS1_1 = 0
TLS1_2 = 0
