### ISSUE TITLE
Não consigo iniciar o modo debug no vscode em uma maquina especifica

### ISSUE THREAD

**Issue by AdlerLima** [totvs/tds-vscode#1159]
Estou enfrentando um problema em uma maquina em especifico, ao iniciar o modo debug pelo visual code, fica apenas carregando e não abre o Protheus.
Visualizando o appserver, nada acontece.
As mesmas conexões que estou usando como teste, funciona em uma outra maquina.
Segue log do appserver e alguns prints para evidenciar.
[launch.json](https://github.com/totvs/tds-vscode/files/13320555/launch.json)
![image](https://github.com/totvs/tds-vscode/assets/55037402/09912c22-fdfc-47de-b99e-59eb790d8688)
[console.log](https://github.com/totvs/tds-vscode/files/13320625/console.log)

Estou utilizando binarios, TDS, VsCode, nas verões mais recentes.

**Comment by brodao2** [comment]
@AdlerLima 

Certifique-se que a conexão ao servidor, está sendo efetuada no ambiente correto.
O SmartClient (por fora do VSCode) consegue conexão? 

Favor complementar chamado informando os dados solicitados conforme [Informações importantes ao abrir o chamado](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#informa%C3%A7%C3%B5es-importantes-ao-abrir-uma-issue) e anexe os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema).

No aguardo

**Comment by DanielYampolschi** [comment]
Ola @AdlerLima , na propriedada "smartclientBin, esta faltando uma barra no trecho: "..Protheus\bin..."

Isso deve corrigir sua situação (mas garanta que esse caminho realmente aponta para o arquivo smartclient.exe).

Caso o problema persista, pode reabrir a issue...
