### ISSUE TITLE
Problema no Syntax Highlight  ao utilizar a keyword "as"

### ISSUE THREAD

**Issue by edusfc15** [totvs/tds-vscode#116]
Boa tarde, 

o Syntax Highlight para de funcionar ao usar a keyword "as" como exemplificado na imagem abaixo:

![problema_as](https://user-images.githubusercontent.com/13476234/60832159-9abe3f80-a191-11e9-989f-b7704920e1b1.PNG)

Grato.

**Comment by lwtnb-wrk** [comment]
@edusfc15 Voce esta com a ultima versao do tds-vscode? Tem outra extensao de AdvPL instalada?

**Comment by edusfc15** [comment]
@lwtnb-wrk ultima versão. Tenhos outras instaladas, mas estão desabilitadas.

![image](https://user-images.githubusercontent.com/13476234/60992589-2ca98200-a323-11e9-93b2-a215cac56977.png)


Segue uma gif evidenciando o problema, quando eu aperto Crtl + A e depois Shift + tab.

![keyword_as](https://user-images.githubusercontent.com/13476234/60992639-48148d00-a323-11e9-9b4b-bdcb8f3d298d.gif)

Obs: O problema ocorre quando usa "as" dentro de um "for".
Obs2:  Como pode observar se trata de um método de uma classe (Não sei se influencia).

Obrigado.

**Comment by DanielYampolschi** [comment]
@edusfc15 Qual o tema voce esta utilizando e qual a versão do VsCode?
Esta realmente estranho essa questão porque além de não conseguirmos reproduzir, algumas cores estão bem diferentes:
Note as palavras: "Method", "local", o nome da classe (em verde) por exemplo

![image](https://user-images.githubusercontent.com/10711513/60996582-3d5df600-a32b-11e9-87ff-6a0930f938ac.png)

Estamos pensando se não pode ser um problema do próprio VsCode com versões de plugins.

Tente desinstalar mesmo, e não desativar, todos os plugins relacionados a Advpl, inclusive o totvs.tds-vscode.
Vá na seguinte pasta: C:\Users\<seu_usuario>\.vscode\extensions e apague (Mande para a lixiera) as pastas dos plugins que foram desinstalados.
Reinstale o plugin tds-vscode e verifique se resolve por favor.

**Comment by edusfc15** [comment]
@DanielYampolschi 

![image](https://user-images.githubusercontent.com/13476234/60997433-2e784300-a32d-11e9-8f74-1c20ec3b9419.png)

O tema é o Dark+ (default dark)

Vou tentar achar o que pode tá influenciando nesse caso, e realizar os passos que você mandou.

Grato pela atenção.

**Comment by DanielYampolschi** [comment]
@edusfc15 Logo após te enviar a mensagem, reparamos um detalhe logo no inicio do seu Gif onde aparece, bem rapidamente, você fazendo uma seleção geral e usando o atalho Shift+tab e verificamos que isso reproduz o problema. 
A causa é a remoção dos espaços iniciais na declaração de variáveis e métodos na declaração da Classe.
Já efetuamos a correção estará disponível na próxima atualização.
Para contornar seu problema, sugiro você selecionar todas as variaveis e metodos na declaração da classe e adicionar um espaço ou tab.
Muito obrigado pelo aviso.

**Comment by edusfc15** [comment]
Opa, ótimo. 
Não vou precisar reinstalar.

Eu estava vendo essa situação aqui na declaração da classe e já ia enviar pra vocês, mas que bom que acharam o problema. 

Eu que agradeço pela correção.
