### ISSUE TITLE
Como posso realizar a deburação de um P.E no portal de gestão de vendas ?

### ISSUE THREAD

**Issue by AdlerLima** [totvs/tds-vscode#1160]
Olá, utilizando o PGV, a necessidade é a seguinte:
Na inclusão de pedido de vendas pelo portal, deve aparecer somente a tabela de preço que esta amarrada ao cadastro do cliente;
Para isso, estou utilizando o P.E GVPCLQRY, porém quando tento realizar o relacionamento para trazer apenas a tabela amarrada, ocorre alguns erros e deixa o PGV inacessivel. 
O que eu preciso, é um meio de conseguir debugar este P.E, e identificar como as informações estão chegando, e de que modo eu posso estar transmitindo a alteração na Query da forma correta.

**Comment by DanielYampolschi** [comment]
Ola @AdlerLima , esse canal é apenas para questões relacionadas ao plugin tds-vscode em si.

**Comment by brodao2** [comment]
Pelo que entendi, você esta usando um serviço rest ou um job http, para depurar esses tipos veja em [[Depuração de serviços (jobs)](https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md#depura%C3%A7%C3%A3o-de-servi%C3%A7os-jobs)](https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md#depura%C3%A7%C3%A3o-de-servi%C3%A7os-jobs).
