### ISSUE TITLE
Extensão não compila arquivos .TRES

### ISSUE THREAD

**Issue by fwsoares** [totvs/tds-vscode#1161]
**Describe the bug**
Estou compilando um fonte que tem o arquivo .ch e .tres customizados, com o mesmo nome do fonte, mesmo habilitando a extensão .TRES e .CH no settings.json em totvsLanguageServer.folder.extensionsAllowed, os arquivos .tres não estou sendo compilados no rpo, e precisamos ter essa posibilidade pois temos uma unidade no EUA que também usa o sistema e vamos precisar tratar o idioma pelo arquivo .TRES

**To Reproduce**
Compilar fonte customizado com arquivo .ch e .tres personalizados

**Expected behavior**
Arquivos .tres compilados no rpo

**Screenshots**
![image](https://github.com/totvs/tds-vscode/assets/38725127/479861bc-a528-4863-8cb0-04bee5304241)
![image](https://github.com/totvs/tds-vscode/assets/38725127/c3083b19-5876-4069-97ed-f01b71e573db)
![image](https://github.com/totvs/tds-vscode/assets/38725127/eb9f6424-4113-431f-9120-dfe6e8f07641)

**Desktop (please complete the following information):**
 - OS/Architecture: Windows 64 bits

**Appserver (please complete the following information):**
 - Build (with date): 7.00.210324P-20230727 - 64 bits
 - OS/Architecture: Linux
 - Build Version 20.3.1.12

**Comment by brodao2** [comment]
@fwsoares
Pelo log apresentado, o fonte guacds02.prw foi compilado. Arquivos CH não podem ser compilados diretamente, é necessário efetuar um "include" deste. 
O CH em questão esta sendo incluído no fonte? 
As pastas informadas para busca contém o referido CH?
Atente-se na ordem de busca. As pastas são varridas de acordo com a ordem na lista de include. A 1a ocorrência do arquivo que será usada.
Quanto os TRES, acione o menu de contexto sobre ele e acione "compilar".

Caso não resolva, favor fazer todos os procedimentos com o sistema de log ligado conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema) e anexo-os ao chamado.

**Comment by fwsoares** [comment]
@brodao2 tentando a compilação direta do arquivo .TRES também não foi, estou fazendo as configurações pra enviar os logs para vocês.

**Comment by fwsoares** [comment]
Segue logs.

Version: 1.84.2 (system setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

TDS Version:
![image](https://github.com/totvs/tds-vscode/assets/38725127/9cbf92e1-0e1d-4117-82de-60f0875dd5b2)

Dados do Server
Versão: TOTVS Manufatura
Build AppServer: 7.00.210324P-20230727 - 64 bits
Nome do servidor: UNKNOWHOST
Sistema operacional: Linux
Appserver version: 20.3.1.12
Build DBAccess: 20220303-20230623
Release do RPO:  12.1.2210
Release do dicionário: 12.1.2210
Local files: SQLiteCli
License server: 2014 - 3.6.0
DB DataBase: MSSQL
DB API Build: 20220303-20230623

Versão da Lib:20230918
Data da Lib: 20230913_173652
Commit ID:a8dcfa38d67e399d35a4103abbe4ed7890776a72
Central de Atualizações: 4736565 (24/10/2023)
[totvsls.log](https://github.com/totvs/tds-vscode/files/13426570/totvsls.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/13426571/totvsls_out.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/13426572/totvsls_in.log)

**Comment by lwtnb-wrk** [comment]
@fwsoares Nos logs nao mostram nenhuma tentativa de compilar um arquivo .TRES
Como voce esta tentando compilar o arquivo .TRES?

**Comment by fwsoares** [comment]
Coloquei a chamada do include no meu fonte:
![image](https://github.com/totvs/tds-vscode/assets/38725127/c90fe30a-be59-493e-a8f0-e84cb851fd18)

Coloquei o includes e os arquivos .TRES na mesma pasta do fonte, além das pasta de include
![image](https://github.com/totvs/tds-vscode/assets/38725127/189e6611-8c72-4537-b6a6-5395847c5636)

Pasta de include:
![image](https://github.com/totvs/tds-vscode/assets/38725127/cd4b09e1-86d9-4363-b348-a8a2bae18a3a)
![image](https://github.com/totvs/tds-vscode/assets/38725127/de5e24be-7ccd-4765-b465-6bea14764a42)
![image](https://github.com/totvs/tds-vscode/assets/38725127/f6587330-a53e-48dd-9598-5f146059e124)
![image](https://github.com/totvs/tds-vscode/assets/38725127/f0d4d7a6-347d-498e-baf3-9bd3c6772d0c)

**Comment by lwtnb-wrk** [comment]
@fwsoares Os arquivos .TRES não são compilado automaticamente apenas chamando nos includes. É preciso compilar como se fossem fonte PRW por exemplo. Ou seja, abra o arquivo .TRES no editor e acione compilar (CTRL + F9) ou clique com o botao direito no arquivo .TRES e acione compilar.
