### ISSUE TITLE
Problema na aplicação de pacote de atualização (path) na versão12.1.33

### ISSUE THREAD

**Issue by raquelhager** [totvs/tds-vscode#1162]
Bom dia!

Estou fazendo a compilação do patch 23-11-01-LIB_LABEL_09102023_P12_HARPIA no rpo PUBLICADO da release 12.1.33  porém esta sendo apresentado o erro conforme texto abaixo no VsCode.

Artefatos - Últimos publicados
23-10-09-P12_APPSERVER_BUILD-20.3.2.1_WINDOWS_X64
3-10-09-P12-SMARTCLIENT_BUILD 20.3.2.0_WINDOWS_X64
21-10-08-REPOSITORIO_DE_OBJETOS_BRASIL_12_1_33_TTTM120.RPO
23-11-01-LIB_LABEL_09102023_P12_HARPIA

* TOTVS - Build 7.00.210324P - Oct  5 2023 - 19:06:27
* Build: 64 bits
* SVN Revision: 40194
* Build Version: 20.3.2.1
Erro apresentado - arquivos de log em anexo.
[totvsls_33.zip](https://github.com/totvs/tds-vscode/files/13349090/totvsls_33.zip)

[Info  - 10:06:57 AM] Patch file: c:\Protheus_Padrao_Azure\Protheus_Padrao\Fontes_Doc\Master\Fontes\Recursos Humanos\.vscode\Patches\23-11-01-LIB_LABEL_09102023_P12_HARPIA-TTTM120.PTM
[Info  - 10:06:57 AM] Starting build for environment P12133MNTDB.
[Error - 10:06:57 AM] Start build error: Server returned: Request ignored -- RMS_DBGSTARTBUILD -- Already building ...
[Info  - 10:07:02 AM] Starting apply patch.
[Info  - 10:07:02 AM] Starting build for environment P12133MNTDB.
[Error - 10:07:02 AM] std::runtime_error
[Error - 10:07:02 AM] Start build error: Server returned: Request ignored -- RMS_DBGSTARTBUILD -- Already building ...

**Comment by brodao2** [comment]
@raquelhager 

Nos logs, vi que há uma notificação de token inválido retornado pelo server.
Favor desativar/remover o token RPO e tentar novamente.

totvsls.log
Start build error: Server returned: [DBGSTARTBUILD][VERIFYTOKEN] Invalid token:

Caso não resolva, solicito que entre em contato com a equipe responsável pela distribuição de RPO e pacotes de atualização.

À disposição.

**Comment by raquelhager** [comment]
Eu desativei/removi o Token de Compilação e deu certo para aplicação do patch da lib porém ao aplicar o patch liberado da expedição contínua, ele segue dando erro.
<img width="767" alt="Patch_Apply_Erro" src="https://github.com/totvs/tds-vscode/assets/55213765/7c2b10a3-ffed-43df-bd63-e44bf9a3e747">

<img width="941" alt="Patch_Apply_From_File_Erro" src="https://github.com/totvs/tds-vscode/assets/55213765/203f7eb9-d146-44ea-9219-83adca05ddce">

Logs:
[totvsls_expedicao.zip](https://github.com/totvs/tds-vscode/files/13350023/totvsls_expedicao.zip)

**Comment by brodao2** [comment]
@raquelhager 

O pacote que esta tentando aplicar contém fontes mais antigos que o RPO.
Se quiser aplicar esse pacote assim mesmo, deve indicar se quer só os mais novos ou todos.
Veja [Aplicando pacotes de atualização](https://github.com/totvs/tds-vscode/blob/master/docs/apply-patch.md#aplicando-de-pacotes-de-atualiza%C3%A7%C3%A3o-_patch) para detalhes.

À disposição.

**Comment by raquelhager** [comment]
O patch não é validado pelo VS Code e a opção de aplicar (mesmo marcando a opções de aplicar fontes antigos) não fica habilitada.

Lembrando que eu estou pegando o rpo PUBLICADO  + LIB + PATCH EXPEDIÇÃO CONTÍNUA
Não deveria nem exibir a mensagem falando que contém arquivos antigos.

<img width="770" alt="Patch_Apply_From_File_Erro_OldFiles" src="https://github.com/totvs/tds-vscode/assets/55213765/c79da8a2-158a-4b8f-8e81-441390944026">

**Comment by raquelhager** [comment]
Estou encerrando a issue pois a Engenharia republicou o pacote da Expedição Contínua e foi possível aplicar o pacote.
Obrigada!
