### ISSUE TITLE
Duplicidade em método de API TLPP com Annotation

### ISSUE THREAD

**Issue by carloseniemeyer** [totvs/tds-vscode#1164]
**Duplicidade em método de API TLPP com Annotation**
Compilação não detecta que um método TLPP está sendo compilado em duplicidade, gerando o erro fatal no AppServer: 
**[FATAL][SERVER] [THROW] HTTP Server - error, duplicated method.**

**Dados da Versão Atualizada TDS e VsCode:**
Version: 1.84.2 (user setup)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
Versão TDS: 1.3.23

**Descrição do bug**
Não valida a duplicidade de métodos de APIs TLPP com annotation na compilação.
Linter não identifica essa duplicidade
Ao Subir o WS REST causa um erro fatal e para todas as APIs REST que funcionavam e nada tem a ver com o processo em questão.

**Exemplos:**

**Fonte1.tlpp**
namespace processos
@GET(endpoint='/processos/api/v2/ping',description="Valida se a API está ativa")
User Function apiGetPing()

**Fonte2.tlpp**
namespace api
@GET(endpoint='/processos/api/v2/ping',description="Valida se a API está ativa")
User Function apiGetPing2()

**Para Reproduzir**
Passos para reproduzir o erro:
- Criar Fonte tlpp 1 com Método Get com Annotation
- Criar Fonte tlpp 2 com o mesmo Método Get com Annotation
- Compilar os 2 fontes
- Subir o AppServer WS REST
- Validar os Métodos GET

**Expected behavior**
Ao compilar o Linter deveria travar a compilação com um erro fatal informando da duplicidade do método de annotation tal como é feito com uma User Function ou Function padrão TOTVS, evitando o sintoma acima.

Além disso, o time de Framework TOTVS ou do AppServer validar a duplicidade e não causar a queda de todas as APIs REST TLPP por causa de um fonte compilado indevidamente, parando todo o ambiente REST Protheus por erros de compilação.

**Desktop (please complete the following information):**
 - OS/Architecture: Windows 11 - 64 bits

**Appserver (please complete the following information):**
 - Build (with date):  7.00.210324P-20231005 - 64 bits
 - OS/Architecture:  Windows Server 2019 64 bits
 - Build Version: 7.00.210324P

**Contexto Adicional**
Appserver version: 20.3.2.1
Build DBAccess: 20230303-20230929
Release do RPO:  12.1.2210
Release do dicionário: 12.1.2210
Local files: ctree
License server: 2014 - 3.6.0
DB DataBase: ORACLE
DB API Build: 20222512-20230929

Versão da Lib:20230626
Data da Lib: 20230717_93727

http://devforum.totvs.com.br/4024-validacao-de-duplicidade-de-metodos-de-api-tlpp-com-annotation

**Comment by danielbolognani** [comment]
Esse pedido precisa ser feito para o time do appserver, nossa extensão apenas envia o comando e quem de fato compila e tem acesso ao RPO para verificar problemas duplicidade é o appserver.
Favor abrir um chamado diretamente pelo canal de atendimento oficial da TOTVS.

**Comment by carloseniemeyer** [comment]
Feito!

https://centraldeatendimento.totvs.com/hc/pt-br/community/posts/19138814763287-TOTVS-Framework-Linha-Protheus-LIB-Valida%C3%A7%C3%A3o-de-Duplicidade-de-M%C3%A9todos-de-API-TLPP-com-Annotation
