### ISSUE TITLE
Erro Compilação (Modo Exclusivo)

### ISSUE THREAD

**Issue by MauroWe** [totvs/tds-vscode#1165]
Não estou conseguindo compilar fonte via VSCode

Retorna que não é possivel ter modo exclusivo do RPO
[Error - 9:27:13 AM] Start build error: Server returned: 
Unix : Resource temporarily unavailable.COMPILEERROR-300 Failed to obtain exclusive access to the objects repository

Ambiente em Cloud, versão dos binarios HARPIA

APPServer já está com a chave BuildKillUsers=1
Poderiam me auxiliar nessa situação?

Segue abaixo logs
[totvsls.log](https://github.com/totvs/tds-vscode/files/13391699/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/13391701/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/13391704/totvsls_out.log)

**Comment by brodao2** [comment]
@MauroWe 

Para compilar você deve utilizar um servidor exclusivo, com um ambiente que aponte para um RPO que só você usará. Este não pode ser utilizado por nenhum outro usuário e nem ter 'jobs' em execução.

Caso tenha certeza que é o único usuário desse servidor, pode adicional a chave 'BuildKillUsers=1' na sessão '[General]' do ini. **Não use** essa chave em produção ou ambientes compartilhado com outros usuários (desenvolvedores ou nã0).

**Comment by lwtnb-wrk** [comment]
@MauroWe Realmente pelos logs temos apenas que o AppServer não conseguiu obter o acesso exclusivo necessário para remover o recurso do RPO.
Mas o interessante é que o retorno do AppServer está indicando "Unix : Resource temporarily unavailable." o que pode ter relação com configurações de "ulimit".
Como seu ambiente está em Cloud, peça para que eles verifiquem esta questão primeiro.
