### ISSUE TITLE
Create File - The editor cold not be opened because the file was not found

### ISSUE THREAD

**Issue by Adailton-lanca** [totvs/tds-vscode#1169]
Ola.
Entendendo que um determinado fonte estava em uma pasta errada no meu projeto, fiz a mudança de local, excluí o fonte do rpo, mudei de pasta e compilei novamente e ocorre sem erro mas quando vou debugar, ocorre a mensagem abaixo e eu ja excluí o custom e recompilei o projeto todo, ja utilizei um RPO "limpo" e ja excluí todos arquivos de configuração do vscode da minha maquina e reinstalei do zero, entretanto, a mensagem continua, ele nao encontra o arquivo na nova pasta nem, fica sempre procurando na antiga. Onde o VSCODE guarda com tanto carinho a localização dos arquivos?

Create File - The editor cold not be opened because the file was not found

**Comment by lwtnb-wrk** [comment]
@Adailton-lanca Não lembro de ter visto este erro anteriormente.
Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para análise.

**Comment by Adailton-lanca** [comment]
![Mensagem](https://github.com/totvs/tds-vscode/assets/64661146/b7b23f22-16ab-4f44-850c-e21e6a95f7c6)

**Comment by Adailton-lanca** [comment]
Depois de excluir o custom, compilar tudo novamente, desconfiar do rpo e utilizar um "limpo", reconfigurar o vscode o problema continuar, recebi a dica do @brodao2 , removi todos os pontos de parada, incluí novamente o ponto de parada no fonte que precisava debugar, e, funcionou, não deu mais o erro. Eu não entendi nada, importante que funcionou.
Obrigado.

**Comment by lwtnb-wrk** [comment]
@Adailton-lanca Somente para esclarecer, o VS Code, independentemente de linguagens de programação, grava os breakpoints em um banco de dados interno, então realmente, ao marcar o breakpoint no fonte incorreto, isso ficou gravado internamente. Ao remover e adicionar novos pontos de parada, os novos registros funcionaram pois o caminho do fonte agora estava correto.
