### ISSUE TITLE
Erro ao aplicar um pacote

### ISSUE THREAD

**Issue by alexandrearume** [totvs/tds-vscode#1172]
Boa tarde,

Ao aplicar um pacote pela opção Patch Apply, na validação está aparecendo o seguinte erro.

[Error - 5:27:58 PM] Patch info could not be executed. Server returned: ManagerRpo is not inicialized correctly. Please contact TECH
Called from E:\build-dir\TP11-OF20320-TECXWIN64\advpl\publicenv.cpp line 12863

Versão do plugin: 12.3.23
Versão do pacote: 12.1.2310

***  TOTVS S/A  ***
***  www.totvs.com.br  ***
* TOTVS - Build 7.00.210324P - Oct  5 2023 - 19:06:27
* Build: 64 bits
* SVN Revision: 40194
* Build Version: 20.3.2.1

**Comment by lwtnb-wrk** [comment]
@alexandrearume Aparentemente tem alguma coisa estranha em seu AppServer, pois o erro está ocorrendo no servidor. 
De qualquer forma veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.
Voce chegou a reiniciar seu AppServer para ver se consegue aplicar o Patch?

**Comment by alexandrearume** [comment]
Sim, eu reiniciei o appserver.
Seguem os arquivos gerados.
[totvsls.log](https://github.com/totvs/tds-vscode/files/13661038/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/13661039/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/13661040/totvsls_out.log)

**Comment by lwtnb-wrk** [comment]
@alexandrearume O log enviado não contem as informações da aplicação de patch. Repita a aplicação de patch com o log ligado e reenvie o arquivo gerado.

Você testou a aplicação em outros AppServer? Ou tentou aplicar outros patches neste AppServer?

**Comment by alexandrearume** [comment]
Você testou a aplicação em outros AppServer? 
Sim, testei com a versão 20.3.2.0_ts14 e deu o mesmo problema.

Ou tentou aplicar outros patches neste AppServer?
Sim, com um outro pacote não deu o problema.

[totvsls.log](https://github.com/totvs/tds-vscode/files/13661311/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/13661312/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/13661313/totvsls_out.log)

**Comment by lwtnb-wrk** [comment]
@alexandrearume Esse log também veio truncado e não tem as informações da aplicação de patch.

Pelo que você relatou pode ser um problema do patch então. Esse patch é do portal? Poderia informar o link para eu tentar aplicar por aqui?

**Comment by brodao2** [comment]
@alexandrearume 

Por um acaso você tem chave de compilação ou token de RPO?
Se sim, experimente desativar. F1, totvs-developer-studio.selectRpoToken.disable.

**Comment by lwtnb-wrk** [comment]
@brodao2 Eu chamei o @alexandrearume diretamente e peguei o patch.
Também não consegui aplicar, o que pode indicar um problema na geração desse patch em particular.
Mas no meu ambiente o patch info foi executado corretamente e falhou em outro ponto da validação, alem de gerar uma exception no appserver.
Enfim, pedi para o @alexandrearume confirmar com o GCAD se houve algum problema e/ou relatos de problema na aplicação desse patch em particular.
Do lado do tds-vscode aparentemente não há nada a ser feito
