### ISSUE TITLE
Erro na inicializacao do language server com MACOS

### ISSUE THREAD

**Issue by eternauta123** [totvs/tds-vscode#1173]
# Help us to help you.
Quando inicia o Language Server, da um erro no console sobre as permissoes dos arquivos na pasta .advpl

## Enter the data below

**Describe the bug**
Version: totvsls 2.0 (Rev.: Last Changed Rev: 40566)
[Info  - 12:56:36] Language Server initialized.
(   7.391s) [languageServer  ]     dbcode_manager.cpp:544   | Binary file error. Error: [/Users/bsobieski/gitfolder/ma3-tmp/ma3/.vscode/.advpl/_binary_functions.prw] Permission denied
(   7.451s) [languageServer  ]     dbcode_manager.cpp:573   | Binary file error. Error: [/Users/bsobieski/gitfolder/ma3-

**To Reproduce**
Se os arquivos nao existem na pasta .advpl
1-Abrir VSCODE com um projeto advpl
2-Os arquivos serao criados
3-Fechas o VSCODE
4-Pular para passo 5
5-Abrir VSCODE com um projeto advpl

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS/Architecture: MACOS 64 bits M1

**Additional context**
os arquivos sao criados com as seguintes permissoes:
-------r--  1 user0001  182019625   414K Dec 13 12:59 _binary_class.prw
-------r--  1 user0001  182019625   430K Dec 13 12:59 _binary_functions.prw

**Comment by brodao2** [comment]
@eternauta123 

Efetuamos a correção e esta disponível uma RC em https://drive.google.com/file/d/1XM_FEuYCkICeJp6RsPQ1iEg3ron1L1G3/view?usp=drive_link

Se puder efetuar alguns testes, agradeço.

Fico no aguardo.

**Comment by lwtnb-wrk** [comment]
confirmação recebida de @eternauta123
