### ISSUE TITLE
No Debug, F10 pula linhas

### ISSUE THREAD

**Issue by Mayco-Andrey-Ranghetti** [totvs/tds-vscode#1175]
Olá,
Estou com um problema bem estranho, em pelo menos 2 fontes.
Estou com o multitheard desativado, confirmei que o fonte foi atualizado (inclusive removi do RPO e recompilei), e quando estou debugando com o F10, o compilador não está passando linha por linha, o comportamento que ocorre seria similar ao comando F5, que continua a execução da rotina até o final.
Eu posso colocar o breakpoint na primeira declaração de variável e seguir com o F10, passa 1 ou 2 linhas, e depois disso, perco o foco. Mas se houver outro breakpoint mais a frente, a rotina para novamente.
Se fosse comparar o comportamento, seria igual a tentar debugar uma função no Rest.
Contudo, me certifiquei e não estou em ambiente Rest.
Tenho outros fontes, que usando o mesmo ambiente e mesma configuração de debug, dá tudo certo.
Não entendo o motivo deste problema em 2 fontes específicos. Os fontes são chamados através de uma Ação que está no aRotina de outra função, algo diferente de quando chamamos a função pelo Menu do Protheus.
Estes fontes em questão, eu já trabalhei neles anteriormente, e não me recordo de ter problemas. Recentemente apliquei a nova LIB que está na Central de Atualizações, este é o único ponto que vejo de alteração em meu ambiente:  a atualização da LIB.
Isso pode ter afetado o debug?

**Comment by lwtnb-wrk** [comment]
@Mayco-Andrey-Ranghetti A principio a atualização de LIB nao deveria alterar nenhum comportamento na depuração.
Somente alterações no binário do AppServer deveriam influenciar a depuração.
De qualquer forma veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analises. Em especial o dap.log e certifique-se de efetuar as operacoes e descrever onde ocorre o problema.

**Comment by brodao2** [comment]
@Mayco-Andrey-Ranghetti 

Favor complementar chamado informando os dados solicitados conforme [Informações importantes ao abrir o chamado](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#informa%C3%A7%C3%B5es-importantes-ao-abrir-uma-issue) e anexe os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)

Faça os procedimentos de compilar e depurar com a geração de logs configurado.

Tire um _print_ dos trechos de código que apresentam a ocorrência.

No aguardo

**Comment by Mayco-Andrey-Ranghetti** [comment]
olá, boa tarde.
Seguem alguns dados que consegui coletar.
![image](https://github.com/totvs/tds-vscode/assets/33654096/b14fff3d-6f79-4880-91c0-8771ab079257)
Versão do VSCode

![image](https://github.com/totvs/tds-vscode/assets/33654096/17bd7daf-2648-44c3-8cca-c2795f03b8f3)
Versão do plugin TDS

![image](https://github.com/totvs/tds-vscode/assets/33654096/a8574a30-97b2-45f6-b3bf-7f3ccf252dec)
Versão do SmartClient e Appserver

[dap.log](https://github.com/totvs/tds-vscode/files/13754234/dap.log)
E arquivo dap.log. 
Este arquivo eu gerei enquanto estava debugando um fonte e o F10 não está passando linha a linha.

**Comment by lwtnb-wrk** [comment]
@Mayco-Andrey-Ranghetti Pelos logs vejo apenas que ele parou na linha 18 do ETQVOL.PRW e apos o F10 o AppServer apenas parou novamente na linha 18 e apos seguir o AppServer parou apenas na linha 25 etc.
Mas isso é o AppServer quem está retornando isso para o tds-vscode.
De qualquer forma, não vi nenhum problema do lado do tds-vscode, e como você disse que apenas alguns fontes em particular não sei dizer se isso seria o problema.
Se puder compartilhar esses fontes em particular conosco, podemos tentar reproduzir o problema localmente. Caso contrario não temos muito como auxiliar.

**Comment by Mayco-Andrey-Ranghetti** [comment]
https://github.com/totvs/tds-vscode/assets/33654096/bc27f75d-9465-40db-99c0-2fb9414a2931

Segue um vídeo demonstrando a situação. Até coloquei breakpoint na rotina principal, que tem o browser, para ver que o F10 está funcionando.
Mas quando chega no fonte ETQVOL.PRW, o F10 não funciona. Tive que colocar outros breakpoints para poder demonstrar as paradas.
Note que o problema com o F10, ocorre já no início do fonte, nas declarações de variáveis.

**Comment by lwtnb-wrk** [comment]
@Mayco-Andrey-Ranghetti Reparei que está usando o SIGAMDI para iniciar e ele pode causar comportamentos imprevistos na depuracao. Experimente usar o SIGAADV e veja se isso resolve o problema.

**Comment by Mayco-Andrey-Ranghetti** [comment]
Nada feito, tentei com o SIGAADV e ocorreu o mesmo problema.

**Comment by lwtnb-wrk** [comment]
@Mayco-Andrey-Ranghetti Poderia compartilhar um fonte onde o problema ocorre?

**Comment by brodao2** [comment]
@Mayco-Andrey-Ranghetti 

Atente que F10 é 'step-over', ou seja, executa sem entrar nas funções.
Ao efetuar o F10 na chamada do "mbrowser", o código será executado até finalizar a 'mbrowser' ou encontrar um ponto de parada. Experimente deixar somente o BP na rotina ETQVOL.PRW.

Se for necessário parar no "mbrowser", no lugar de F10, acione F11 (step into). Como você não deve ter os fontes da LIB, a execução ocorrerá até achar o fonte na sua área de trabalho.

Pode tentar tb, ao parar no 1o BP do ETQVOL.PRW, acione uma vez o F11 e depois use o F10.

O server pode apresentar 'comportamentos estranhos' dependendo de como a função foi chamada, p.e. chamada direta ou macro ou ainda codeblock. Infelizmente não tempos controle sobre isso.
