### ISSUE TITLE
Erro ao debugar

### ISSUE THREAD

**Issue by lbloliveira** [totvs/tds-vscode#1176]
**Describe the bug**
Ao realizar o debug, eu coloco o breakpoint para executar a parada no fonte determinado.
Para ir para a próxima linha, eu pressiono a tecla F10 (Step Over). Entretanto, notei que ultimamente não está executando o esperado. Simplesmente é executado como se eu tivesse pressionado F5 (Continue). 

Exemplo:

Coloquei o breakpoint nas linhas 5, 30 e 50.

Ao parar na linha 5, caso eu pressione F10 (Step Over), vai direto para a linha 30. Se eu pressionar novamente F10 (Step Over) vai direto para a linha 50. É como se eu sempre estivesse pressionando F5 (Continue).

Já desinstalei o VS Code, limpei as pastas temporárias mas nada resolveu. 

Fiz o seguinte teste no qual detectei ser algo relacionado ao RPO.

Ambiente de Produção:

**Dados do Server:**
Versão: TOTVS Manufatura
Build AppServer: 7.00.210324P-20231005 - 64 bits
Nome do servidor: SRV-PROTH
Sistema operacional: Windows Server 2019
Appserver version: 20.3.2.1
Build DBAccess: 20230303-20230929
Release do RPO:  12.1.2210
Release do dicionário: 12.1.2210
Local files: CodeBase
License server: 2014 - 3.6.0
DB DataBase: ORACLE
DB API Build: 20230303-20230929

**Dados do Remote:**
Remote build: 7.00.210324P-20230623
Remote version: 20.3.1.5
Remote type: 1 - QT-5.15.9 WIN
Módulo: TMK
Nome do computador: GALE864
Sistema operacional: Windows 10 - 
Memória: 11699
Processador: Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz

Versão da Lib:20231121
Data da Lib: 20231228_11356
Commit ID:7f1a29a4e93b26e32836afc6ffe1759e43cf6945
Central de Atualizações: 5058998 (08/01/2024)

Simplesmente peguei um RPO (padrão e custom de uma base mais antiga) e o debug simplesmente funciona.
Se eu pego o RPO (padrão e custom) e coloco no mesmo ambiente pula os pontos.

**Comment by lwtnb-wrk** [comment]
@lbloliveira Grato por informar. Já temos tido relatos desta questão, mas não havíamos reproduzido o problema.
Essa informação sobre a versão da LIB é muito interessante e se possível nos passe mais detalhes de versões.
Se possível veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs e nos envie os logs gerados (dap.log) tanto no RPO que esta apresentando problemas e se possível outro conjunto de logs onde o problema não ocorre.

**Comment by lbloliveira** [comment]
Bom dia,

Segue em anexo os logs solicitados.





Luiz Oliveira
Analista de Sistemas

Tel.: +55 (19) 3746-7786
***@***.***<https://www.linkedin.com/company/galenaindustrial/>
***@***.***<https://www.instagram.com/galenafarmaceutica/?hl=pt-br>
***@***.***<https://www.facebook.com/galenafarmaceutica/>
[Uma imagem contendo Ícone  Descrição gerada automaticamente]




[Logotipo  Descrição gerada automaticamente]



Esta mensagem, incluindo seus anexos, pode conter informações privilegiadas e/ou de caráter confidencial, não podendo ser retransmitida sem autorização do remetente. Caso você não seja o destinatário desta mensagem, pedimos desculpas pelo transtorno e solicitamos que entre em contato com o remetente, informando-o, e promova, desde logo, a eliminação do seu conteúdo em sua base de dados, registros ou sistema de controle, ficando desde já expressamente notificado de que em hipótese alguma está autorizado a usar, divulgar ou encaminhar esta mensagem a terceiros. Atenção: nos termos da legislação vigente, a divulgação, transcrição ou modificação indevida do conteúdo desta mensagem, incluindo anexos, caracteriza prática de ato criminoso.



De: lwtnb-wrk ***@***.***>
Enviada em: segunda-feira, 8 de janeiro de 2024 08:34
Para: totvs/tds-vscode ***@***.***>
Cc: Luiz Oliveira ***@***.***>; Mention ***@***.***>
Assunto: Re: [totvs/tds-vscode] Erro ao debugar (Issue #1176)


@lbloliveira<https://github.com/lbloliveira> Grato por informar. Já temos tido relatos desta questão, mas não havíamos reproduzido o problema.
Essa informação sobre a versão da LIB é muito interessante e se possível nos passe mais detalhes de versões.
Se possível veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs e nos envie os logs gerados (dap.log) tanto no RPO que esta apresentando problemas e se possível outro conjunto de logs onde o problema não ocorre.

**Comment by lwtnb-wrk** [comment]
@lbloliveira Os anexos de emails não são refletidos na issue no github. É preciso entrar na issue pelo github e anexar. Poderia anexar novamente?

**Comment by lbloliveira** [comment]
[logs_rpo_problema.zip](https://github.com/totvs/tds-vscode/files/13860034/logs_rpo_problema.zip)
[logs_rpo_sem_problemas.zip](https://github.com/totvs/tds-vscode/files/13860035/logs_rpo_sem_problemas.zip)

Segue os anexos solicitados.

att

**Comment by lwtnb-wrk** [comment]
@lbloliveira Como o problema relatado é referente ao debug, precisamos do "dap.log" que eh gerado apenas durante a depuração. Poderia nos enviar este outro log?

**Comment by lwtnb-wrk** [comment]
@lbloliveira Aparentemente é algum comportamento no AppServer (e LIB), pois os comando do lado do tds-vscode parece tudo dentro do esperado.
Somente para confirmar, não devemos usar o SIGAMDI durante a depuração. Então utilize o SIGAADV ou acesse diretamente o modulo, por exemplo, SIGAFAT, durante a depuração.

**Comment by lwtnb-wrk** [comment]
@lbloliveira E se possivel envie o console.log do AppServer que seja do momento quando ocorre o pulo do debug.

**Comment by lwtnb-wrk** [comment]
@lbloliveira Qual a última LIB que você usou onde o problema não ocorre?

**Comment by lbloliveira** [comment]
Bom dia,

Fiz o teste com o SIGAADV e o comportamento se repete. Porém se eu acessar diretamente pelo módulo, no meu caso o SIGATMK, o debug funcionou corretamente.





Luiz Oliveira
Analista de Sistemas

Tel.: +55 (19) 3746-7786
***@***.***<https://www.linkedin.com/company/galenaindustrial/>
***@***.***<https://www.instagram.com/galenafarmaceutica/?hl=pt-br>
***@***.***<https://www.facebook.com/galenafarmaceutica/>
[Uma imagem contendo Ícone  Descrição gerada automaticamente]




[Logotipo  Descrição gerada automaticamente]



Esta mensagem, incluindo seus anexos, pode conter informações privilegiadas e/ou de caráter confidencial, não podendo ser retransmitida sem autorização do remetente. Caso você não seja o destinatário desta mensagem, pedimos desculpas pelo transtorno e solicitamos que entre em contato com o remetente, informando-o, e promova, desde logo, a eliminação do seu conteúdo em sua base de dados, registros ou sistema de controle, ficando desde já expressamente notificado de que em hipótese alguma está autorizado a usar, divulgar ou encaminhar esta mensagem a terceiros. Atenção: nos termos da legislação vigente, a divulgação, transcrição ou modificação indevida do conteúdo desta mensagem, incluindo anexos, caracteriza prática de ato criminoso.



De: lwtnb-wrk ***@***.***>
Enviada em: terça-feira, 9 de janeiro de 2024 08:49
Para: totvs/tds-vscode ***@***.***>
Cc: Luiz Oliveira ***@***.***>; Mention ***@***.***>
Assunto: Re: [totvs/tds-vscode] Erro ao debugar (Issue #1176)


@lbloliveira<https://github.com/lbloliveira> Aparentemente é algum comportamento no AppServer (e LIB), pois os comando do lado do tds-vscode parece tudo dentro do esperado.
Somente para confirmar, não devemos usar o SIGAMDI durante a depuração. Então utilize o SIGAADV ou acesse diretamente o modulo, por exemplo, SIGAFAT, durante a depuração.

**Comment by lwtnb-wrk** [comment]
@lbloliveira Grato por esta importante informação. 
Se puder, por favor, envie o dap.log desse acesso direto ao SIGATMK pra gente avaliar tambem.

**Comment by lbloliveira** [comment]
Segue em anexo os arquivos console.log com os 3 testes:
SIGAMDI
SIGAADV
SIGATMK

[console_COM_ADV.log](https://github.com/totvs/tds-vscode/files/13874625/console_COM_ADV.log)
[console_COM_MDI.log](https://github.com/totvs/tds-vscode/files/13874626/console_COM_MDI.log)
[console_COM_TMK.log](https://github.com/totvs/tds-vscode/files/13874627/console_COM_TMK.log)

Também envio o dap.log referente ao teste acessando pelo SIGATMK.

[dap_COM_TMK.log](https://github.com/totvs/tds-vscode/files/13874741/dap_COM_TMK.log)

Segue a informação da LIB conforme solicitado.

![inf_lib](https://github.com/totvs/tds-vscode/assets/155967444/41e04335-df70-4ee7-92f1-e4b82eab401c)


att

**Comment by lwtnb-wrk** [comment]
@lbloliveira Grato por todas as informações.
A principio como a depuração está funcionando com o acesso direto ao módulo, entendo que consiga continuar seu trabalho, mas de qualquer forma faremos mais investigações por aqui.
E apenas para deixar claro, o SIGAMDI sempre teve problemas na depuração então não recomendamos sua utilização, mas a novidade é que o problema também passou a ocorrer com o uso do SIGAADV, que até então funcionava adequadamente.
Para evitar problemas futuros atualizaremos a documentação para alertar destas questões.
Grato novamente pelos testes, logs e informações importantes.

**Comment by lbloliveira** [comment]
Obrigado pelo retorno. Conte comigo caso necessário.

**Comment by lwtnb-wrk** [comment]
@lbloliveira Estou fechando essa questão e faremos ajustes na documentação e melhorias para alertar sobre o comportamento inesperado na depuração ao utilizar o SIGAMDI e SIGAADV.
Grato pela ajuda.
