### ISSUE TITLE
Abertura do appserver via terminal VScode

### ISSUE THREAD

**Issue by jacomolisa** [totvs/tds-vscode#118]
Criar um parâmetro na configuração do appserver, dizendo qual o caminho do executável
Criar um atalho para executar o appserver via terminal do VSCode conforme definido na lista de servers
Ex:
![image](https://user-images.githubusercontent.com/28158470/60990605-3204cd80-a31f-11e9-8860-c4ed37eb1b1b.png)
e adicionar no contextmenu da seleção do server "Run in VSTerminal"

**Comment by lwtnb-wrk** [comment]
@jacomolisa Interessante sugestão. Se quiser implementar, submeta uma PR que iremos analisar.

**Comment by ricardomansano** [comment]
Boa tarde @jacomolisa,

Agradecemos a sugestão, mas após analise decidimos que ela não entrará em roadmap.

Você pode facilmente resolver o problema abrindo o terminal do vscode, e iniciando o AppServer neste, inclusive é a maneira que eu desenvolvo no meu dia.

Muito grato pela sugestão
