### ISSUE TITLE
Erro no C++ Runtime

### ISSUE THREAD

**Issue by vitor-gabriel** [totvs/tds-vscode#1180]
**Describe the bug**
Ao depurar e compilar fontes com a nova release TDS 2.0.2 esta me aparecendo habitualmente este erro no print abaixo.
![image](https://github.com/totvs/tds-vscode/assets/62556013/43b3ed22-ef71-440e-b030-36ab8e8b9fff)

**Screenshots**
Versão TDS:
![image](https://github.com/totvs/tds-vscode/assets/62556013/452433a0-2d02-4a75-9b79-5fc41f67385f)

**Desktop (please complete the following information):**
 - OS/Architecture: Windows 11 64 bits

**Appserver (please complete the following information):**
Build AppServer: 7.00.210324P-20231005 - 64 bits
Sistema operacional: Windows 11
Appserver version: 20.3.2.1
Build DBAccess: 20230303-20230929
Release do RPO:  12.1.2210
Release do dicionário: 12.1.2210
Local files: CTREE
License server: 2014 - 3.6.0
DB DataBase: MSSQL
DB API Build: 20230303-20230929

**Comment by lkznogueira** [comment]
Acompanhando.. Estou com o mesmo problema nesta ultima versão.

**Comment by brodao2** [comment]
Favor complementar chamado anexando os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)

**Comment by lwtnb-wrk** [comment]
@vitor-gabriel @lkznogueira Foi gerado um arquivo "core_99999.dmp" na pasta de trabalho de vocês quando ocorreu o erro?
Se afirmativo, favor enviar este arquivo para auxiliar nas análises.

**Comment by Vtrespro** [comment]
Para mim da o mesmo erro e o pior que se tem conectar novamente.

**Comment by lkznogueira** [comment]
@lwtnb-wrk 
Ele gera um .dmp mas eh mto grande (284mb). nem zipado consigo mandar aqui! Teria algum url q vcs recomandam para subir ele?

**Comment by vitor-gabriel** [comment]
Segue evidencia no link abaixo, como tem fonte padraões envolvido dentro do DMP, deixei somente visivel para emails @totvs

https://drive.google.com/file/d/15TRvjhwSBJXL_PU6edtDkQt1tDTNhNIZ/view?usp=sharing

**Comment by keilaemytaniguchi** [comment]
Mesmo problema

**Comment by lwtnb-wrk** [comment]
Vejam em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs e deixem os logs ativos. Se o erro voltar a ocorrer, nos envie os logs gerados para analise.

**Comment by lwtnb-wrk** [comment]
Já identificamos a causa provável do erro de C++ Runtime e estamos efetuando a correção. Em breve lançaremos uma atualização. Peço que aguardem um pouco.

**Comment by leandroramorim** [comment]
Bom dia @lwtnb-wrk,

O arquivo é superior a 25 MB, que é o limite do GIT, teria algum e-mail que possa compartilhar para enviar link para download?

**Comment by lwtnb-wrk** [comment]
@leandroramorim grato, mas por enquanto não precisaremos mais do arquivo, já que a próxima atualização já deve corrigir essa queda com geração de dump.

**Comment by jmfrolim** [comment]
> Já identificamos a causa provável do erro de C++ Runtime e estamos efetuando a correção. Em breve lançaremos uma atualização. Peço que aguardem um pouco.

Aguardando também a atualização.

**Comment by gtrabach** [comment]
Caso ainda ajude, segue log coletados juntamente com o dump: https://drive.google.com/file/d/1Ttia-mNGyjf7bERlliNzOSAh45NiN3rB/view?usp=sharing

**Comment by erichmbuttner** [comment]
Log de dump coletado. https://drive.google.com/file/d/10HYWtnU7UVpJjAkL5ps691Y_hjq2u83C/view?usp=drive_link

**Comment by lwtnb-wrk** [comment]
A versão 2.0.3 foi disponibilizada no Marketplace e já deve estar disponível para atualização no VS Code.
Se ainda assim tiverem algum problema nesta nova versão 2.0.3 favor abrir uma nova issue anexando mais informações.
