### ISSUE TITLE
Não aparece os servidroes

### ISSUE THREAD

**Issue by Ti-Mv2023** [totvs/tds-vscode#1181]
Type: <b>Bug</b>

Os servidores não são mais listados na versão 2.0.2. Seu fizer o dowgrade para 1.0.3 aparecem

Extension version: 2.0.2
VS Code version: Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:16.462Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.85GB (13.68GB free)|
|Process Argv|--crash-reporter-id 2fe03699-5e9b-45dc-8bcc-1433d6368909|
|Screen Reader|no|
|VM|33%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
0bi6i642:30933247
pythongtdpath:30769146
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
dsvsc019a:30933241

```

</details>

**Comment by brodao2** [comment]
@Ti-Mv2023 

Ainda na versão 1.0.3, editar o arquivo settings.json, conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema), para que sejam gerados logs adicionais.

Faça a atualização e se o problema persistir, anexe os logs gerados e o arquivo servers.json.

No aguardo.

**Comment by RegisNJr** [comment]
Eu já abandonei essa versão 2.0.2 está muito ruim
Deixou o VsCode com alto consumo de processador e memória, além de dificuldade de conexão com os Servers, fica fazendo indexação dos fontes e depois dando erro de Includes sendo que não mudei nada na pasta, além do pouco tempo que usei ficou travando o Vscode e gerando arquivo de Dump de erro... achei melhor voltar para 1.3.23 que está 100%

**Comment by brodao2** [comment]
@RegisNJr 

Agradecemos o seu comentários e já estamos trabalhando para resolver a questão do DUMP.
Pelo que levantamos aqui, ocorre quando você abre um fonte que não esteja na sua área de trabalho e já estamos trabalhando na resolução.

Quanto ao consumo de CPU e memória, isso ocorre somente na indexação dos arquivos.
Se configurar o cache para "onDisk", isso ocorrerá somente ao abrir a área de trabalho pela 1a vez ou se remover o cache do disco.

Em https://github.com/totvs/tds-vscode/blob/dev2/docs/dss.md há informações sobre os ganhos que terá e de mais detalhes de como configurar o cache e o comportamento esperado em cada configuração.

Se desejar que a versão 2.0.2 trabalhe de forma mais parecida com as versões anteriores,
configure a chave de cache para "off" .

A disposição.

**Comment by brodao2** [comment]
@RegisNJr 

Em complemento a mensagem anterior, você pode cancelar a indexação a qualquer momento (pelo 'popup'ou fechando o VSCode). O processo será retomando do ponto que parou.

**Comment by RegisNJr** [comment]
Brodao2 obrigado pelo feedback vou dar uma olhada no link e nas dicas.

Mas de toda forma vou esperar sair alguma versão superior a 2.0.2 pra ver se estará melhor,
Aqui na empresa são 6 programadores e todos já desistiram da 2.0.2 pois acabamos perdendo tempo e desempenho nas entregas.

Bom saber que já estão trabalhando em melhorias, vou aguardar a próxima versão
Obrigado

**Comment by jgardezani** [comment]
Olá,
Observei que ao atualizar para a versão 2.0.2 a lista de servidores parou de ser exibida.
Voltei para versão anterior (1.3.23) e a lista de servidores voltou a ser exibida.
[VSCODE.pptx](https://github.com/totvs/tds-vscode/files/14023969/VSCODE.pptx)

**Comment by felipe-brainbox** [comment]
Instale a ultima versão do vscode (1.85) que vai resolver.
Aconteceu comigo tambem

**Comment by evertonmgs** [comment]
Boa tarde,
Alguém consegue explicar como faz para voltar para versões anteriores enquanto a 2.0.2 não está 100%?

**Comment by lwtnb-wrk** [comment]
A versão 2.0.3 foi disponibilizada no Marketplace e já deve estar disponível para atualização no VS Code.
Se ainda assim tiverem algum problema nesta nova versão 2.0.3 favor abrir uma nova issue anexando mais informações.
