### ISSUE TITLE
Ao aplicar patch, derruba o appserver.

### ISSUE THREAD

**Issue by pablovbc** [totvs/tds-vscode#1182]
Ao aplicar um ou mais patches, ainda na fase de validação, o serviço do appserver é derrubado.
Fiz os seguintes testes:

1 - Aplicação de um patch.
2 - Aplicação de vários patches, selecionando vários de uma vez.
3 - Fiz downgrade da extensão para 1.3.23.

Em todos os cenários, ocorre o erro.
Em alguns momentos o erro ocorreu na fase de validação e em outros na fase de aplicação.

![lib_appserver](https://github.com/totvs/tds-vscode/assets/83319121/fc045f01-f45d-4f7a-8108-f9a5824a2e95)
![versão_tds](https://github.com/totvs/tds-vscode/assets/83319121/da06fa2b-9289-44a2-bc63-1069badcbf8e)
[versão_vscode.txt](https://github.com/totvs/tds-vscode/files/14010359/versao_vscode.txt)

**Comment by AlexandreBeh** [comment]
Para mim também acontece cenário de cair o appserver. Ao recompilar todo o workspace da erro no fonte número 100.
[Info  - 10:11:29 AM] Connection to server got closed. Server will restart.
true
[Error - 10:11:29 AM] Pending response rejected since connection got disposed
  Message: Pending response rejected since connection got disposed
  Code: -32097

**Comment by lwtnb-wrk** [comment]
@pablovbc Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by pablovbc** [comment]
[totvsls.log](https://github.com/totvs/tds-vscode/files/14010876/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/14010878/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/14010879/totvsls_out.log)

**Comment by lwtnb-wrk** [comment]
@pablovbc Tivemos relatos de um problema no AppServer que pode causar esse comportamento no tds-vscode.
Para testar se é isso realmente, é necessário desabilitar o [WEBMONITOR] e [APP_MONITOR].
Veja se estas seções existem no seu AppServer.ini e desabilite com a chave Enable=0 ou se não existirem crie as seções a seguir.
[WEBMONITOR]
Enable=0
[APP_MONITOR]
Enable=0
Reinicie o AppServer e veja se a aplicação de patches funciona conforme esperado.
O time do AppServer já está trabalhando na resolução deste problema.

**Comment by pablovbc** [comment]
@lwtnb-wrk fiz isso e funcionou, obrigado!
Então será disponibilizado um novo appserver no portal?

**Comment by lwtnb-wrk** [comment]
@pablovbc Sim, mas não tenho informações de quando isto ocorrerá. 
De qualquer forma, grato pelo rápido retorno.
