### ISSUE TITLE
em ADVPL a variável no tipo "raw" 

### ISSUE THREAD

**Issue by telso** [totvs/tds-vscode#1183]
no DEBUG em ADVPL a variavel caracter no debug visualizando no tipo "raw" 
tem alguma configuração para voltar ao padrão xbase ?

**Comment by telso** [comment]
segue imagem
![image](https://github.com/totvs/tds-vscode/assets/51102850/0cc20d6b-a4ee-46cc-acfc-ffe0b7e766c5)

**Comment by keilaemytaniguchi** [comment]
O meu também está assim, começou hoje, como voltar para o formato antigo ?

**Comment by keilaemytaniguchi** [comment]
mesmo problema aqui, começou após a ultima atualização 2.0.2

**Comment by brodao2** [comment]
Isso não é um problema. As variáveis do tipo "character" sofreu mudança na forma de apresentação.

Se não expandir o item, no caso "cBodyTratado", será apresentado como nas versões anteriores.
Se expandir, a propriedade "raw" (cru/bruto) é apresentado como esta armazenado internamente.
E sequencia, a string byte a byte, com seu favor ASCII correspondente.

Essa melhoria foi efetuada para quando houver texto UTF8 em alguma variável.

**Comment by likid** [comment]
É claro que isso é um problema. O comportamento da apresentação da informação foi alterado, mostra informações úteis para poucas pessoas e que dependendo do tamanho da string, torna lento e confuso o acesso a informação. Pense em você abrir o conteúdo de uma variável string contendo o XML de um NFe ou um SQL de várias linhas. 

Sem contar que antes ao visualizar o conteúdo de uma string, o mesmo era envolto de aspas duplas, o que facilmente informava ser uma string, quando a variável está com conteúdo numérico, era mostrado sem as aspas duplas. Agora mesmo sendo string, fica sem aspas duplas, o que acaba confundindo o programador, exemplo, ao listar o código que é string mas contém apenas números.

Esta informação nova, contendo o ascii de cada caracter, deveria vir em um array fechado, deixando para o programador a opção de visualizar ou não o conteúdo ou uma opção do plugin para que venha com essa visualização nova.

O conteúdo string deveria continua envolto de aspas duplas para rápida avaliação do conteúdo.

Estas alterações efetuadas são de longe chamadas de melhorias, pois só atrapalharam o trabalho de quem os utiliza diariamente.

**Comment by brodao2** [comment]
@likid 

Realmente a questão das aspas, passou batido. Vou corrigir.
O processo adicional, só deve ocorrer ao expandir o nó. Vou revisar o procedimento.

Grato pela colaboração.

**Comment by amjgfarias** [comment]
> É claro que isso é um problema. O comportamento da apresentação da informação foi alterado, mostra informações úteis para poucas pessoas e que dependendo do tamanho da string, torna lento e confuso o acesso a informação. Pense em você abrir o conteúdo de uma variável string contendo o XML de um NFe ou um SQL de várias linhas.
> 
> Sem contar que antes ao visualizar o conteúdo de uma string, o mesmo era envolto de aspas duplas, o que facilmente informava ser uma string, quando a variável está com conteúdo numérico, era mostrado sem as aspas duplas. Agora mesmo sendo string, fica sem aspas duplas, o que acaba confundindo o programador, exemplo, ao listar o código que é string mas contém apenas números.
> 
> Esta informação nova, contendo o ascii de cada caracter, deveria vir em um array fechado, deixando para o programador a opção de visualizar ou não o conteúdo ou uma opção do plugin para que venha com essa visualização nova.
> 
> O conteúdo string deveria continua envolto de aspas duplas para rápida avaliação do conteúdo.
> 
> Estas alterações efetuadas são de longe chamadas de melhorias, pois só atrapalharam o trabalho de quem os utiliza diariamente.

Concordo plenamente com o que foi dito acima.

Essa "melhoria" não atende a maioria dos desenvolvedores que trabalham com advpl e sim somente um gato pingado de programadores.

Essa "melhoria" deveria ser parametrizável via settings.json para que cada dev usasse da forma que lhe convem e nao de guela abaixo como esta sendo feito.

Obrigado e desculpem a franqueza do meu texto.

**Comment by walterfcarvalho** [comment]
Essa melhoria não foi muito boa não, ficou muito ruim pegar os valores das variáveis no console, se pudessem remover iria ser uma boa.

**Comment by lwtnb-wrk** [comment]
Senhores, as alterações que fazemos visam melhorar o produto como um todo, mas eventualmente teremos algo que não vai agradar a todos.
Levaremos em conta suas sugestões e faremos ajustes.
Mas fiquem a vontade para expressar suas percepções pois no final, esta extensão foi criada para vocês devs utilizarem e se algo não estiver bom, queremos ouvir e melhorar.
Grato pelas informações e reclamações.

**Comment by jmfrolim** [comment]
> Senhores, as alterações que fazemos visam melhorar o produto como um todo, mas eventualmente teremos algo que não vai agradar a todos. Levaremos em conta suas sugestões e faremos ajustes. Mas fiquem a vontade para expressar suas percepções pois no final, esta extensão foi criada para vocês devs utilizarem e se algo não estiver bom, queremos ouvir e melhorar. Grato pelas informações e reclamações.

Entendemos que a intenção é melhorar o produto, bem como essa funcionalidade pode auxiliar no dia a dia de alguns desenvolvedores.

Mas a grande maioria não conseguiu enxergar valor nessa funcionalidade, sendo opção de deixar isso configurável uma caminho mais adequado.

**Comment by endreodev** [comment]
No DEBUG em ADVPL a variável caracteres no debug visualizando no tipo "raw". Ficou péssimo sem poder mudar essa configuração, podem reavaliar para que tenha uma configuração para voltar o mesmo comportamento de antes ou ter uma opção para desativar isso.

Sobre este comportamento, dificulta o entendimento claro do conteúdo das variáveis e dificulta o aprendizado de novos programadores

**Comment by enakamatu** [comment]
Acho que sou um dos que deu mais hora/aula de ADVPL nos ultimos 10 anos, e essa mudança atrapalha e muito, veja quantos releases passou o Plugin e esta não agrega nada. Veja que deixei claro ADVPL, pois uitas vezes vejo mudanças pensando em outra linguagem e o grande uso é ADVPL

**Comment by leandroayala** [comment]
O melhor caminho seria realmente possibilitar a configuração via json dessa nova opção de visualização.

**Comment by maximinocastro** [comment]
> > É claro que isso é um problema. O comportamento da apresentação da informação foi alterado, mostra informações úteis para poucas pessoas e que dependendo do tamanho da string, torna lento e confuso o acesso a informação. Pense em você abrir o conteúdo de uma variável string contendo o XML de um NFe ou um SQL de várias linhas.
> > Sem contar que antes ao visualizar o conteúdo de uma string, o mesmo era envolto de aspas duplas, o que facilmente informava ser uma string, quando a variável está com conteúdo numérico, era mostrado sem as aspas duplas. Agora mesmo sendo string, fica sem aspas duplas, o que acaba confundindo o programador, exemplo, ao listar o código que é string mas contém apenas números.
> > Esta informação nova, contendo o ascii de cada caracter, deveria vir em um array fechado, deixando para o programador a opção de visualizar ou não o conteúdo ou uma opção do plugin para que venha com essa visualização nova.
> > O conteúdo string deveria continua envolto de aspas duplas para rápida avaliação do conteúdo.
> > Estas alterações efetuadas são de longe chamadas de melhorias, pois só atrapalharam o trabalho de quem os utiliza diariamente.
> 
> Concordo plenamente com o que foi dito acima.
> 
> Essa "melhoria" não atende a maioria dos desenvolvedores que trabalham com advpl e sim somente um gato pingado de programadores.
> 
> Essa "melhoria" deveria ser parametrizável via settings.json para que cada dev usasse da forma que lhe convem e nao de guela abaixo como esta sendo feito.
> 
> Obrigado e desculpem a franqueza do meu texto.

Exatamente como o amigo Alessandro disse, deixar o dev selecionar criando o botão "Manager > Settings > TOTVS" ou criar um tag no settings.json para desconsiderar, igual vocês fizeram sobre o LINTER que dá pra desativar.

Da forma que está o Plugin é impossivel utilizar no dia a dia nos clientes.

**Comment by abzapponi** [comment]
Fora que cria um arquivo DMP gigante no seu projeto.
Achei essa nova versão uma porcaria.
Fui lá e voltei a versão antiga e acabaram os problemas

**Comment by lwtnb-wrk** [comment]
Geramos uma versão pré-release 2.0.4 que deve resolver o problema reportado.
Se quiser/puder testar e confirmar se está funcionando como deveria, baixe e instale o arquivo vsix disponibilizado em https://github.com/totvs/tds-vscode/releases/tag/v2.0.4
Para instruções mais detalhadas sobre instalação de vsix veja https://github.com/totvs/tds-vscode/blob/master/docs/install.md
O comportamento voltou ao anterior e caso o dev sinta a necessidade dessa "extended feature" ela pode ser ligada depois.

**Comment by lwtnb-wrk** [comment]
A versão 2.0.4 do tds-vscode foi expedida através do marketplace. 
https://marketplace.visualstudio.com/items?itemName=totvs.tds-vscode
Atualizem a extensão tds-vscode e caso necessário abra uma nova issue com o maior numero de informações possíveis.
