### ISSUE TITLE
Debug caindo sem mensagem de erro

### ISSUE THREAD

**Issue by vitorpirestotvs** [totvs/tds-vscode#1185]
Ao efetuar o debug o processo cai sozinho sem mensagem de erro. A Tela continua aberta mas não repsonde e o bscode sai do modo debug

Segue logs e video

Version: 1.85.2 (user setup)
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:10.514Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22000

att.,
Vitor Pires
[anexos.zip](https://github.com/totvs/tds-vscode/files/14028552/anexos.zip)

**Comment by vitorpirestotvs** [comment]
conforme identificado com o Leo, o problema ocorre ao avaliar o watch com a expressão table:xxx em um breakpoint. No caso, testei no debug com table:pcy e table:se1, sempre caindo.

**Comment by lwtnb-wrk** [comment]
@vitorpirestotvs Grato pelos testes e já identificamos onde ocorria o problema, em breve teremos uma atualização com a correção.

**Comment by lwtnb-wrk** [comment]
A versão 2.0.3 foi disponibilizada no Marketplace e já deve estar disponível para atualização no VS Code.
Se ainda assim tiverem algum problema nesta nova versão 2.0.3 favor abrir uma nova issue anexando mais informações.
