### ISSUE TITLE
Mudança de comportamento - Compile/Recompile folder

### ISSUE THREAD

**Issue by gtrabach** [totvs/tds-vscode#1186]
**Describe the bug**
Até a versão 1.3.23 do TDS existia uma opção chamada **Compile file/folder** ao clicar com o botão direito em uma pasta da workspace.

A partir da versão 2.0.2 essa opção foi alterada para **Recompile file/folder**. Essa mudança de comportamento está correta? É possível manter ambas as opções?

A opção anterior (compile) era importante pois possibilitava o desenvolvedor avaliar quais fontes de uma pasta já haviam sido aplicados anteriormente (skipped) e quais eram novos (success/warn). Utilizando a nova opção de recompile não dá pra ter esse controle, visto que todos os fontes terão sua compilação forçada.

**Screenshots**
1.3.23:
![image](https://github.com/totvs/tds-vscode/assets/46979335/5008830f-4c53-4e1c-9c3b-31133da3bfbb)

2.0.2:
![image](https://github.com/totvs/tds-vscode/assets/46979335/32bf3aec-4593-4996-ad62-8fa084891597)

**Desktop (please complete the following information):**
Windows 11 Pro 21H2 64-bits

**Appserver (please complete the following information):**
 - Build (with date): 7.00.210324P 
 - OS/Architecture: Windows 11 Pro 21H2 64-bits
 - Build Version 20.3.2.2

**Comment by lwtnb-wrk** [comment]
@gtrabach Apenas priorizamos a opção de "Recompile" frente a "Compile", mas acho que ficou um pouco confuso mesmo. Vamos ajustar para trazer uniformemente as opções de "Recompile" em primeiro plano, e não somente para "File/Folder".

A opção de "Compile" ainda está disponível e é acionada da mesma forma que era para a "Recompile", antes de clicar com o botão direito acione e segure a tecla SHIFT e clique com o botão direito e as opções serão "invertidas".

**Comment by lwtnb-wrk** [comment]
A versão 2.0.3 foi disponibilizada no Marketplace e já deve estar disponível para atualização no VS Code.
Se ainda assim tiverem algum problema nesta nova versão 2.0.3 favor abrir uma nova issue anexando mais informações.
