### ISSUE TITLE
Pacotes não são listados

### ISSUE THREAD

**Issue by fabianojustino** [totvs/tds-vscode#1187]
Eu não consigo aplicar pacotes pelo vscode, mas todo resto funciona.
Quando estou na tela aplicar pacotes "Patch Apply", clico no botão "Escolher arquivos", seleciono o pacote, mas ele não é listado para validação.

Sistema operacional: Ubuntu 22.04.3 LTS , 64 bits
Versão Gnome 42.9
Sistema de janelas X11

**Comment by brodao2** [comment]
Veja no log de console do protheus se há alguma mensagem que possa ajudar.

**Comment by brodao2** [comment]
Anexe os logs conforme https://github.com/totvs/tds-vscode/blob/dev2/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema

**Comment by fabianojustino** [comment]
Boa tarde amigo, ele não chega a aplicar, porque não carrega os arquivos:
![image](https://github.com/totvs/tds-vscode/assets/93944231/d3c397f8-9f16-4a25-9250-f3bdfd17dfe6)

Já coloquei o caminho todo em minúsculo, mas sem sucesso.
Também tentei gerar o log, mas sempre termina corrompido.

**Comment by fabianojustino** [comment]
Mas ele consegue gerar os arquivos: totvsls_in, 
[totvsls.log](https://github.com/totvs/tds-vscode/files/14042469/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/14042470/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/14042471/totvsls_out.log)
 totvsls_out, totvsls

**Comment by lwtnb-wrk** [comment]
@fabianojustino Me ocorreu somente agora que isso pode ser uma limitação do próprio VS Code, pois em https://code.visualstudio.com/docs/supporting/requirements eles listam apenas "Ubuntu Desktop 20.04".
Você tem essa versão para testar?? Sinceramente não sei qual seria a limitação, mas infelizmente algo no VS Code pode ainda ser incompativel com a versão que você está usando atualmente.

**Comment by fabianojustino** [comment]
@lwtnb-wrk , não tenho, atualizei já faz um bom tempo, mas no caso, as incompatibilidades mencionadas no link são bem especificas, não falam exatamente das extensões.

**Comment by lwtnb-wrk** [comment]
@fabianojustino Acontece que se existir uma limitação no VS Code como uma incompatibilidade de libs, o componente que usamos para abrir a "dialog" de seleção de arquivos pode não estar se comunicando apropriadamente com nossa extensão e não recebemos a informação correta.

Tente o seguinte, com o VS Code aberto, abra o menu "Ajuda > Toggle Developer Tools", selecione a aba "Console" e repita a operação de "Aplicar Patch", veja se aparece algum erro no momento que voce seleciona o arquivo de patch na "dialog" e clica em "Abrir".
