### ISSUE TITLE
ERRO AO TENTAR DEBUGAR PELO VSCODE

### ISSUE THREAD

**Issue by FelipePelissari** [totvs/tds-vscode#119]
Boa tarde! feitas as configurações consigo compilar fontes e Patches porém para debugar o servidor apresenta o seguinte erro anexo.
Obs.: arquivo zipado com vídeo rodando.

[Configurações VSCODE.docx](https://github.com/totvs/tds-vscode/files/3378998/Configuracoes.VSCODE.docx)
[2019-07-10-15-44-51.zip](https://github.com/totvs/tds-vscode/files/3379006/2019-07-10-15-44-51.zip)

**Comment by lwtnb-wrk** [comment]
@FelipePelissari Esse erro apresentado indica o uso do Broker. Voce esta utilizando o Broker?
Se afirmativo, poderia fazer um teste? Entrar no smartclient.ini e remover todas as linhas de configuração que habilitam o broker e retestar o Debug?
Grato pelos testes e por apontar esse problema.

**Comment by FelipePelissari** [comment]
@lwtnb-wrk comentei as linhas do broker porém apareceu o seguinte erro. segue anexo tb a configuração que deixei no smartclient para avaliar se o problema não está na configuração que fiz no .INI
[Configurações VSCODE smartclient.docx](https://github.com/totvs/tds-vscode/files/3381866/Configuracoes.VSCODE.smartclient.docx)

**Comment by lwtnb-wrk** [comment]
@FelipePelissari as linhas do broker estao comentadas como devem estar no Debug, mas agora o erro parece ser de configuração do ambiente.
Se voce tentar entrar diretamente no SIGAADV pelo SmartClient funciona ou estoura o mesmo erro?

**Comment by FelipePelissari** [comment]
@lwtnb-wrk funciona normal... o DEBUG é sempre pelo DESENV. segue video.
o Smartclient11 é somente o teste que fiz e deixei ele.
[2019-07-11-09-51-22.zip](https://github.com/totvs/tds-vscode/files/3382082/2019-07-11-09-51-22.zip)

**Comment by lwtnb-wrk** [comment]
@FelipePelissari Esse ultimo video mostra apenas que o SmartClient acessa o Broker (TCP_BROKER) ao inves do servidor (DESENV).
E mostra tambem que ele usa as configurações sem os comentario do Broker pois se essas configurações estivessem comentadas este servidor não estaria acessível por este SmartClient.
Vi tambem nas configurações "launch.json" que nas sua configuração de "TOTVS LANGUAGE DEBUG" o "program" esta como "DESENV"... É esse mesmo o programa que voce deseja iniciar? Não seria o "SIGAADV"??
Para garantir que o SmartClient utilizado pelo Debug é o mesmo, conecte-se no servidor DESENV pelo VS Code e acione a "Execução" ("Start without Debuging") do SmartClient atraves do CTRL + F5.

**Comment by FelipePelissari** [comment]
@lwtnb-wrk Humm entedi, mas no caso, preciso acessar o TCP_BROKER na porta 1238, programa inicial SIGAADV e o ambiente seria o DESENV.
Porém como faço para iniciar o programa SIGAADV no ambiente Desenv? nas configurações do servidor, quando compilo, a porta 1238 eu consigo selecionar o DESENV.

**Comment by FelipePelissari** [comment]
@lwtnb-wrk ok, estou conectado no server Desenv, coloquei no program "SIGAADV", coloco o CTRL + F5 porém a mensagem é a mesma.
[Configurações VSCODE TOTVS LANGUAGE DEBUG.docx](https://github.com/totvs/tds-vscode/files/3382445/Configuracoes.VSCODE.TOTVS.LANGUAGE.DEBUG.docx)

**Comment by lwtnb-wrk** [comment]
@FelipePelissari Veja que na tela de erro a porta conectada e a 51966 e não a 1238. Aparentemente as configurações do Broker ainda estão ativas não?
Mude nas configurações de "TOTVS LANGUAGE DEBUG" o caminho do SmartClient para usar a pasta smartclient11 (que voce comentou as configurações do Broker) e tente novamente.

**Comment by FelipePelissari** [comment]
Perfeito!! subiu!!
Existe algum problema eu conectar e debugar por esse outro smartclient?

**Comment by lwtnb-wrk** [comment]
@FelipePelissari Na verdade para o Debug voce nao deve usar as configurações da mesma forma, por causa do Broker e Load Balance.
Se a versão do smartclient for a mesma (que acredito ser pois deve ser uma copia da original) não tem problema nenhum em se conectar e debugar por esse outro smartclient.
Ficamos a disposição, caso encontre outros problemas, por favor abra outra issue descrevendo a situação. 
Abraço
