### ISSUE TITLE
Pending response rejected since connection got disposed   Code: -32097

### ISSUE THREAD

**Issue by ronilson-rodrigues** [totvs/tds-vscode#1190]
Ao realizar a operação Compile File/Folder ou Recompile All Workspace, para compilar todo o projeto, apresenta erro mencionado.

Segue prints com os dados necessários. E também anexo os logs do processo efetuado.
![Captura de tela 2024-01-25 093044](https://github.com/totvs/tds-vscode/assets/149424511/30bbede2-97c7-4e74-8df7-bb20d47681ff)
![Captura de tela 2024-01-25 093141](https://github.com/totvs/tds-vscode/assets/149424511/8b06621d-609c-472a-bea4-48b0587b4cbe)
![Captura de tela 2024-01-25 093246](https://github.com/totvs/tds-vscode/assets/149424511/094adda0-1a8d-4788-8c91-5c2a406cdfdc)
[totvsls.log](https://github.com/totvs/tds-vscode/files/14051719/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/14051721/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/14051722/totvsls_out.log)
[console.log](https://github.com/totvs/tds-vscode/files/14051758/console.log)

**Comment by brodao2** [comment]
@ronilson-rodrigues 

Experimente desligar quaisquer monitores (chave webmonitor, appmonitor e assemelhados) e 'jobs'.
Limpe o console.log e reinicie o servidor.

Se o problema persistir, mande o console.log novamente e o ini do appserver, por favor.

**Comment by raulv329** [comment]
Boa tarde, Pessoal.

Estou com o mesmo erro, algum paliativo?

**Comment by ronilson-rodrigues** [comment]
@brodao2 

Esse serviço não possui nenhum tipo de job, pois é usado exclusivamente para compilação dos arquivos.
Segue anexo o appserver.ini deste serviço.
Precisei mudar a extensão do arquivo para poder anexar aqui.

[appserver.txt](https://github.com/totvs/tds-vscode/files/14054737/appserver.txt)

**Comment by pablosnascimento** [comment]
Mesmo erro aqui em várias máquinas. Aguardando solução!

**Comment by pablosnascimento** [comment]
Me passaram uma solução temporária: voltar a versao do plugin TOTVS Developer. Pra mim resolveu!

![image](https://github.com/totvs/tds-vscode/assets/15107506/02eb075d-43af-4491-8d92-a897d9fe0265)
![image](https://github.com/totvs/tds-vscode/assets/15107506/474d0053-8ee5-40fd-9e55-55e5ce4306b6)

**Comment by ronilson-rodrigues** [comment]
@pablosnascimento 

Aqui fiz isso também, para solucionar provisoriamente o problema.

**Comment by brodao2** [comment]
> @brodao2
> 
> Esse serviço não possui nenhum tipo de job, pois é usado exclusivamente para compilação dos arquivos. Segue anexo o appserver.ini deste serviço. Precisei mudar a extensão do arquivo para poder anexar aqui.
> 
> [appserver.txt](https://github.com/totvs/tds-vscode/files/14054737/appserver.txt)

Se puder fazer mais um teste, agradeço.
Vejo que no ini tem a chave ``PROTHEUS_MONITOR_EMBEDDED``, favor colocar em ``0`` e reiniciar o server.

Grato por colaborar.

**Comment by brodao2** [comment]
> @pablosnascimento
> 
> Aqui fiz isso também, para solucionar provisoriamente o problema.

Pode anexar o console log do server no momento da ocorrência?

Grato.

**Comment by raulv329** [comment]
@pablosnascimento  

Voltei a versão igual orientado e resolveu provisoriamente...

**Comment by lwtnb-wrk** [comment]
@ronilson-rodrigues Remove ou comenta a chave abaixo da seção [general] para ver se muda o comportamento:
App_Environment=COMPILA
E aproveitando, sabe informar a build exata do AppServer que esta usando para compilar?

**Comment by ronilson-rodrigues** [comment]
@lwtnb-wrk Comentei a linha que sugeriu, mas ainda persiste o problema.
A versão da build do AppServer está em um dos prints iniciais: 7.00.210324P-20230531.
Segue novas evidências após remover a chave App_Environment.

[console.log](https://github.com/totvs/tds-vscode/files/14065162/console.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/14065164/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/14065165/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/14065166/totvsls_out.log)

**Comment by ronilson-rodrigues** [comment]
@lwtnb-wrk Fiz atualização do AppServer para versão **Build AppServer: 7.00.210324P-20231113**, mas mesmo assim continua o mesmo problema.

**Comment by lwtnb-wrk** [comment]
@ronilson-rodrigues Como o tds-vscode está reiniciando os logs enviados não contem as informações de antes do reinicio.
Se puder, altere as configurações de log como a seguir para ativar a geração de um log completo
	"totvsLanguageServer.launch.args": [
		"--log-file=totvsls.log",
		"--log-file-append=totvsls-full.log",
		"--record=totvsls"
	],
Com isso, efetue novamente a compilação e no envie o arquivo "totvsls-full.log" que deverá conter as informações antes da reinicializacao.
Grato,

**Comment by lwtnb-wrk** [comment]
@ronilson-rodrigues Apenas para avisar que reproduzimos o problema e já estamos analisando.

**Comment by ronilson-rodrigues** [comment]
@lwtnb-wrk Segue.

[totvsls_out.log](https://github.com/totvs/tds-vscode/files/14067198/totvsls_out.log)
[totvsls-full.log](https://github.com/totvs/tds-vscode/files/14067199/totvsls-full.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/14067200/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/14067201/totvsls_in.log)

**Comment by ronilson-rodrigues** [comment]
@lwtnb-wrk Opa, boa notícia. Espero te ajudado.
Aguardo novas atualizações.

**Comment by lwtnb-wrk** [comment]
Somente para deixar mais claro, essa situação ocorre ao compilar/recompilar pasta/workspace com mais de 88 fontes. Se compilarem até 88 fontes o problema não ocorre.
O problema já foi localizado e a correção sairá na próxima atualização.

**Comment by lwtnb-wrk** [comment]
Geramos uma versão pré-release 2.0.4 que deve resolver o problema reportado.
Se quiser/puder testar e confirmar se está funcionando como deveria, baixe e instale o arquivo vsix disponibilizado em https://github.com/totvs/tds-vscode/releases/tag/v2.0.4
Para instruções mais detalhadas sobre instalação de vsix veja https://github.com/totvs/tds-vscode/blob/master/docs/install.md

**Comment by Smmartinez** [comment]
Bom dia!
Acabei de testar a recompilação e compilou todos os meus fontes.


Att.
Sergio Martinez Martinez
 
 



De: "lwtnb-wrk" ***@***.***>
Enviada: 2024/02/06 09:16:05
Para: ***@***.***
Cc:  ***@***.***
Assunto:  Re: [totvs/tds-vscode] Pending response rejected since connection got disposed Code: -32097 (Issue #1190)
 

 

Geramos uma versão pré-release 2.0.4 que deve resolver o problema reportado.
Se quiser/puder testar e confirmar se está funcionando como deveria, baixe e instale o arquivo vsix disponibilizado em https://github.com/totvs/tds-vscode/releases/tag/v2.0.4
Para instruções mais detalhadas sobre instalação de vsix veja https://github.com/totvs/tds-vscode/blob/master/docs/install.md

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/totvs/tds-vscode/issues/1190#issuecomment-1929399414", "url": "https://github.com/totvs/tds-vscode/issues/1190#issuecomment-1929399414", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by lwtnb-wrk** [comment]
A versão 2.0.4 do tds-vscode foi expedida através do marketplace. 
https://marketplace.visualstudio.com/items?itemName=totvs.tds-vscode
Atualizem a extensão tds-vscode e caso necessário abra uma nova issue com o maior numero de informações possíveis.
