### ISSUE TITLE
Outline

### ISSUE THREAD

**Issue by lkznogueira** [totvs/tds-vscode#1192]
Boa noite.. 

Na ultima versão v2.0.3 na parte do outline não está saindo nenhuma informação..  Segue prints do mesmo código fonte porem de versões diferentes do Plugin.

Na versão v2.0.3
![image](https://github.com/totvs/tds-vscode/assets/12913181/24bc5f71-ab51-4794-a649-d0fcbedb5611)
Depois ele atualiza para
![image](https://github.com/totvs/tds-vscode/assets/12913181/59bed03c-77cc-4acf-9e83-e0a16505904c)

Na versão v2.0.2
![image](https://github.com/totvs/tds-vscode/assets/12913181/5a09b67b-e688-4ab4-9a0e-194540011c65)

E na versão v1.3.23
![image](https://github.com/totvs/tds-vscode/assets/12913181/05204a24-d124-4441-b87e-d4543a3f4ed4)

**Comment by brodao2** [comment]
@lkznogueira 

Esse fonte encontra-se fora da área de trabalho? Sem sim, por enquanto o DSS ignora esses fontes.

Se estiver na área de trabalho e puder, mande esse fonte para acandido@totvs.com.br

Grato.

**Comment by lkznogueira** [comment]
> @lkznogueira
> 
> Esse fonte encontra-se fora da área de trabalho? Sem sim, por enquanto o DSS ignora esses fontes.
> 
> Se estiver na área de trabalho e puder, mande esse fonte para [acandido@totvs.com.br](mailto:acandido@totvs.com.br)
> 
> Grato.

Está no seu e-mail.

**Comment by brodao2** [comment]
@lkznogueira 

Grato pelo fonte.

Carreguei o fonte para testes e o mesmo acusou "erro de sintaxe". Quando isso ocorre, o ``Outline`` passa a ignorar o fonte. 

![image](https://github.com/totvs/tds-vscode/assets/114854608/05ed514a-e453-4685-9dd3-394d627f5845)


Vou fechar o chamado e se depois de corrigir o fonte, continuar com problemas ou verificar novas ocorrências no ``Outine``, reabra o chamado.

Grato pela colaboração e a disposição.

**Comment by lkznogueira** [comment]
@brodao2 

Te reenviei o e-mail com as explicações.. No fonte em questão que te enviei tive que retirar alguns pedaços do código fonte a pedido do cliente.

Te mandei um novo fonte com as devidas explicações no seu e-mail.

**Comment by WBaldin** [comment]
Também estou com o mesmo problema!

**Comment by brodao2** [comment]
Ocorrência reproduzida. Já estamos trabalhando na correção.

**Comment by brodao2** [comment]
Ocorrência resolvida. Favor aguardar nova liberação.

**Comment by lwtnb-wrk** [comment]
A versão 2.0.4 do tds-vscode foi expedida através do marketplace. 
https://marketplace.visualstudio.com/items?itemName=totvs.tds-vscode
Atualizem a extensão tds-vscode e caso necessário abra uma nova issue com o maior numero de informações possíveis.
