### ISSUE TITLE
TDS Replay - Não exibe quantidade de linhas na linha do tempo

### ISSUE THREAD

**Issue by haniellourenco** [totvs/tds-vscode#1193]
Olá,

Nas versões 2.0.2 e 2.0.3, ao importar um arquivo TOTVS Replay para depuração não está exibindo a quantidade de linhas existentes no Replay, por consequência não é possível fazer a paginação.
![image](https://github.com/totvs/tds-vscode/assets/62188157/a493c291-d39a-49c8-97e8-96f5ab683ddb)

Ao desmarcar a opção "Ignore Source Not Found", o número de linhas volta a ser exibido.
![image](https://github.com/totvs/tds-vscode/assets/62188157/a75d5424-985a-4616-a3fa-6a96ff8e94fa)

 - Windows 11 64 bits
 - VS Code versão 1.85

Segue em anexo 2 arquivos TOTVS Replay que reproduzi este caso.
[replay.zip](https://github.com/totvs/tds-vscode/files/14087902/replay.zip)

**Comment by cirilorocha** [comment]
Também estou com o mesmo problema. Isso gera problemas sérios, porque depois da última linha apresentada nesta tela ele não consegue mais avançar no debug, ficamos limitados a 5000 linhas que é o máximo que aparece aí.

**Comment by brodao2** [comment]
Senhores,

Ocorrência reproduzida e corrigida. Favor aguardar liberação de novo _release_.

À disposição
