### ISSUE TITLE
Ao recompilar apresenta o erro: Connection to server got closed. Server will restart.

### ISSUE THREAD

**Issue by Redschenko** [totvs/tds-vscode#1195]
Olá, 

Estou utilizando a versão 2.0.3 da extensão tds-vscode e ao recompilar o projeto está apresentando a erro conforme mensagem abaixo:
##############################################################
[Info  - 4:36:31 PM] Starting recompile.
[Info  - 4:36:31 PM] Starting build for environment P12_TEMP01.
[Info  - 4:36:37 PM] Starting build using RPO token ...
[Info  - 4:36:37 PM] Start recompile of 1301 files.
[Warn  - 4:36:37 PM] Too many files to compile. Disabling detailed notifications during this compilation only.
[Info  - 4:36:37 PM] Using Includes: c:/totvs/workspaces/zaccaria_vscode/protheus_12/include
[Info  - 4:36:44 PM] Connection to server got closed. Server will restart.
true
[Error - 4:36:44 PM] Pending response rejected since connection got disposed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 4:36:44 PM] Initializing Language Server.
[Info  - 4:36:44 PM] Language Server initialized.
[Info  - 4:36:44 PM] Developer Support Subsystem initialized.
[Info  - 4:36:45 PM] Indexed folder: PROTHEUS_12 (1264 files) in 553ms (avg. 0 ms)
##############################################################

No log do appserver está apresentando a seguinte mensagem:
##############################################################
2024-01-30T16:36:44.599000-03:00 3704|[VDRPORT] 240130_163644 0E78 BPC1858 E x 04 ctx:024 error 64 (operacao em conexao fechada remotamente) in receive from client 192.168.0.5:64253
2024-01-30T16:36:44.599000-03:00 5284|
[WARN ][SERVER] [THROW][Thread  5284] tConnnErrorException (8:Communication error: Sync error) on E:\build-dir\TP11-OF20320-TECXWIN64\lib_comm\msgmanager.cpp:472
2024-01-30T16:36:44.599000-03:00 5284|
[WARN ][SERVER] [Thread 5284][30/01/2024 16:36:44] Debugger -- Operation aborted while building -- RPO changes not saved.
2024-01-30T16:36:44.599000-03:00 5284|
[INFO ][SERVER] [[Thread  5284][30/01/2024 16:36:44] Debugger finished ( (prodrigo, 100-0532)
##############################################################

Dados do VS Code:
##############################################################
Version: 1.85.2 (system setup)
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:10.514Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
##############################################################

Dados do ambiente Protheus Utilizado:
##############################################################
Informações do AppServer
Tipo do servidor;Console
AppServer Build;7.00.210324P-20231113
Appserver version;20.3.2.2
Servidor 64 bits;Sim
Servidor Unix;Não

Informações da LIB
Versão da Lib;20240115
Data da Lib;20240116_163657
ID da Lib;dbad1b9b01cb101714c01f573eb17e132c1d9b0a
Release;12.1.2210
HardLock;2014
Versão do License Server;3.6.0
Versão do Protheus;TOTVS Manufatura
Dicionário no banco de dados;Sim
##############################################################

![Screenshot_14](https://github.com/totvs/tds-vscode/assets/21147378/c517e61e-407f-446a-9e61-f4f7889e9dc1)

Segue console.log completo, arquivos de log da Extensão do VS Code (totvsls.log, totvsls_in.log e totvsls_out.log)

[console_P12_TESTE.log](https://github.com/totvs/tds-vscode/files/14103369/console_P12_TESTE.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/14103371/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/14103372/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/14103373/totvsls_out.log)

Aguardo uma solução.

At
Rodrigo de Oliveira.

**Comment by brodao2** [comment]
@Redschenko 

Pelos logs, parece-me que você simplesmente abriu o VS-Code. 

Caso a operação seja a (re)compilação de pastas, já verificamos que isso ocorre com pastas com mais de 88 fontes (a queda ocorre no 89o fonte) e já foi solucionado (#1190).

Se não for esse o caso, favor refazer a operação com os logs ligados e reenvia-los.

Grato

PS: Parabéns pela qualidade dos dados na abertura do chamado.

**Comment by Redschenko** [comment]
@brodao2 

É o mesmo problema do caso #1190 .
Se quiser pode fechar este e vou acompanhar por lá.

Obrigado pela resposta.

At
Rodrigo de Oliveira.
