### ISSUE TITLE
No VSCODE está mudando a visualização quando tem comando SQL com ADVPL .

### ISSUE THREAD

**Issue by roseadri** [totvs/tds-vscode#1197]
No VSCODE os fontes Advpl quando tem SQL na passagem de parâmetros parece que o VS Code está entendendo que é comentário . o fonte mostra conforme a imagem 
<img width="692" alt="image_VSCODE" src="https://github.com/totvs/tds-vscode/assets/38508762/3c7d90ae-9a38-4d7b-93fd-74a6d8ac419c">
. 

Qualquer duvida estou a disposição. 
Atenciosamente,
Roselaine
roselaine.adriano@totvs.com.br

**Comment by lwtnb-wrk** [comment]
@roseadri Grato por reportar, vamos analisar para entender e corrigir o problema.

**Comment by brodao2** [comment]
@roseadri 

Repare que na linha 1466, Exp:cwhere não esta entre %.
Acredito que ao colocar o % de terminação, deve resolver.

**Comment by lwtnb-wrk** [comment]
@roseadri Conforme conversamos, então o erro na formatação foi devido a falta de fechamento da tag "%", mesmo que isso não cause erro de compilação foi bom que pode localizar uma tag malformatada.
Se num futuro isso vier a causar erro de compilação esse fonte já foi corrigido.
