### ISSUE TITLE
Erro: not allowed more than one source with same name

### ISSUE THREAD

**Issue by raquelhager** [totvs/tds-vscode#1199]
Boa tarde!

Estou utilizando o binário da imagem em anexo com o rpo do dia 31/01/2024, 23:06:46:
https://arte.engpro.totvs.com.br/protheus/padrao/builds/12.1.2210/latest/repositorio/harpia/

Ao tentar compilar o arquivo GPEM550TestCase.prw  é exibida a mensagem:
not allowed more than one source with same name. Rename your source.	

Eu tentei desativar o token, reativei ele com o ESP:Login e sempre ocorre a mesma mensagem.

[totvsls_out.zip](https://github.com/totvs/tds-vscode/files/14130022/totvsls_out.zip)
[appserver.zip](https://github.com/totvs/tds-vscode/files/14130031/appserver.zip)
<img width="959" alt="Binários-2210" src="https://github.com/totvs/tds-vscode/assets/55213765/e679cc03-d8e4-4f7c-af15-7b132c369e0e">

**Comment by lwtnb-wrk** [comment]
@raquelhager Ops, nao vi que ja estavam anexados la no comeco, vou avaliar.

**Comment by lwtnb-wrk** [comment]
@raquelhager Verifique atraves dos inspetores de objeto/funcao se esse arquivo ja esta compilado no RPO utilizado, pois essa mensagem de erro é retornada pelo AppServer. 
Como tentou compilar com um token de compilacao, se este fonte existir no RPO padrao ele deve exibir essa mensagem.

**Comment by brodao2** [comment]
@raquelhager 

Pelo relato já existe no RPO um fonte compilado com esse nome que foi compilado com token.
E, até onde sei, precisa de um token para recompilar fontes compilados com token e mesmo assim você não consegue compilar. Solicito que entre em contato com a Engenharia, para ver se é algum problema no seu token ou no RPO.

**Comment by brodao2** [comment]
@raquelhager 

Lembrei que EngProKit teve atualização recente. Veja a documentação do EngProKit, pode ser que seu token tornou-se inválido.

A disposição.

**Comment by raquelhager** [comment]
@brodao2 


Eu atualizei as seguintes extensões:
v1.13.0 da extensão EngProKit
v2.0.3 TOTVS Developer Studio for VSCode

Realizei a geração do Token conforme documentação:
https://code.engpro.totvs.com.br/engpro/vscode-engpro-extension/wiki/Instala%C3%A7%C3%A3o-%28PT-BR%29#esp-token

Através da opção ESP:Login
Eu consigo compilar fontes do padrão exceto esse fonte que comentei na issue.

Também identifiquei que os fontes constam no d-1 indevidamente desde do dia 26/01 (até onde fui baixando os rpos):
<img width="419" alt="image" src="https://github.com/totvs/tds-vscode/assets/55213765/08c26afe-9835-4823-9759-87acf233ea8b">

**Comment by raquelhager** [comment]
@lwtnb-wrk 
Muito obrigada pela explicação, eu não havia reparado nisso!
Porém, ao usar a opção de exclusão pelo próprio Vs Code eu não consegue, então optei por excluir o rpocustom. Após realizado isso, coloquei o token de compilação e consegui compilar!

Muito obrigada pela ajuda! =D
