### ISSUE TITLE
O Intelisense nao contempla as classes do advpl.

### ISSUE THREAD

**Issue by Vitor-Santos-Totvs** [totvs/tds-vscode#12]
Acredito que essa questão deva estar no roadmap do plugin, mas como não encontrei este roadmap, deixo aqui a sugestão de que sejam adicionadas as classes e seus métodos/propriedades ao intelisense do plugin.

**Comment by ricardomansano** [comment]
Essa implementação depende da criação do nosso motor de parser que foi prorrogada para o primeiro semestre de 2020, manteremos os canais informados quando da liberação.
