### ISSUE TITLE
Opção de compilação sumiu do menu / Compilation is missing from menu

### ISSUE THREAD

**Issue by gworks-giovani** [totvs/tds-vscode#1202]
# Help us to help you.

## Before opening an issue

- Make sure the extension is up to date.
2.04

## Enter the data below

**Describe the bug**
Opção de compilação de pastas e do workspace, sumiu do menu.
Compilation over folders and workspace is missing from menu.

**To Reproduce**
1. Clique com o botão direito sobre qualquer pasta do projeto /  Right click over any folder from project;
2. Veja que existe apenas a opção de "recompilação" e não mais a de compilação / See that exists only "recompilation" option and no more "compilation".

**Expected behavior**
Que exista a opção de "compilação" 
That exists the "compilation" option.

**Screenshots**
![image](https://github.com/totvs/tds-vscode/assets/119347637/aeede28d-a7d5-438b-9fac-98b218c5fee8)

**Desktop (please complete the following information):**
OS/Architecture:
 - Windows 11 x64
 - Ubuntu 22.04 x64

**Appserver (please complete the following information):**
 - Build (with date): [e.g. Build 7.00.210324P]
 - OS/Architecture: [e.g. Ubuntu 22.04 64 bits]

**Additional context**
A opção de recompilação não ignora arquivos de uma pasta que não precisam ser compialdos, ou seja, sempre o arquivo é compilado. Já a opção de compilação, o arquivo é compilado somente quando há alguma diferença entre a versão compilada no rpo e o arquivo em questão.

The recompilation option does not skip files in a folder that do not need to be compressed, that is, the file is always compiled. As for the compilation option, the file is compiled only when there is some difference between the version compiled in the rpo and the file in question.

**Comment by lwtnb-wrk** [comment]
@gworks-giovani Este foi um trabalho para a harmonização da interface, pois tinhamos a opcao "Compilação de Workspace", "Compilação de Pasta" e "Recompilação de Editor".
De qualquer forma para acessar a segunda ação basta acionar o botão SHIFT do teclado antes de acionar o menu de contexto (botão direito do mouse)
