### ISSUE TITLE
Erro Linter - C2090 File not Found totvs.ch

### ISSUE THREAD

**Issue by gabrielbonfim1** [totvs/tds-vscode#1203]
Mesmo erro da Issue anterior.
Include sublinhado em vermelho como erro no Linter.
Se tentar compilar : "C2001 Syntax error: appre [Ln 1, Col 1]"
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/14193659/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/14193660/totvsls_out.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/14193661/totvsls.log)
[servers.json](https://github.com/totvs/tds-vscode/files/14193664/servers.json)
[settings.json](https://github.com/totvs/tds-vscode/files/14193665/settings.json)

**Comment by lwtnb-wrk** [comment]
@gabrielbonfim1 Você adicionou os includes do TLPP na mesmas pasta "/Users/gabriel/Docs/Lorenfer/include" ?

Você pode criar um arquivo de exemplo TLPP bem simples e tentar compilar esse exemplo apenas? E se falhar, por favor, nos envie esse exemplo apenas para garantirmos que não é algo especifico de seu ambiente de compilacao TLPP.

**Comment by gabrielbonfim1** [comment]
Ta na mão chefe. O fonte anterior eu consigo compilar de outro computador Windows,  somente no meu Mac que não.
Os includes tlpp estão na pasta sim. Em anexo o que foi pedido.

Tive que renomear o fonte de .tlpp para .txt pois o GitHub não estava aceitando .tlpp

[teste.txt](https://github.com/totvs/tds-vscode/files/14194973/teste.txt)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/14194974/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/14194975/totvsls_out.log)
<img width="824" alt="sstlpp" src="https://github.com/totvs/tds-vscode/assets/75266996/db7ea36c-256c-44e9-89ae-f71d8d9c305a">

[totvsls.log](https://github.com/totvs/tds-vscode/files/14194977/totvsls.log)

**Comment by lwtnb-wrk** [comment]
@gabrielbonfim1 Mas a pasta de includes que está sendo utilizada é a "/Users/gabriel/Docs/Lorenfer/include"

**Comment by gabrielbonfim1** [comment]
Perdão chefe, essa outra eu criei essa semana durante nossos testes, a outra também possui os includes tlpp
<img width="694" alt="ss" src="https://github.com/totvs/tds-vscode/assets/75266996/1bf6e3af-93c1-409d-b97c-be24c259212d">

**Comment by lwtnb-wrk** [comment]
@gabrielbonfim1 Poderia nos enviar os arquivos .TH que esta utilizando??

Em seguida consegue extrair novamente os arquivos de includes do TLPP de seu tlpp.rpo atual?
https://tdn.totvs.com/pages/viewpage.action?pageId=619741238
Talvez estejam corrompidos e possam estar causando este problema.

**Comment by gabrielbonfim1** [comment]
[Archive.zip](https://github.com/totvs/tds-vscode/files/14224507/Archive.zip)
Na mão chefe

**Comment by lwtnb-wrk** [comment]
@gabrielbonfim1 Testei aqui e com os seus includes realmente ocorreu o mesmo erro que esta relatando. Esses includes aparentemente estão corrompidos ou não são compatíveis com o AppServer que utilizei. No caso testei com um appserver (Build Version: 20.3.2.1).
Veja se extraindo um novo conjunto de includes de seu TLPP.rpo resolve seu problema (https://tdn.totvs.com/pages/viewpage.action?pageId=619741238). Ou se preferir, segue em anexo a pasta de includes que utilizei para o teste.
[includes-tlpp.zip](https://github.com/totvs/tds-vscode/files/14224657/includes-tlpp.zip)

**Comment by lwtnb-wrk** [comment]
@gabrielbonfim1 Só um complemento, abri os arquivos de includes que você enviou, em um editor hexadecimal e o conteúdo está completamente "zerado", todos os bytes são x00. Então certamente os seus includes de TLPP não estão íntegros.

**Comment by lwtnb-wrk** [comment]
@yecalo Aparentemente seu includes parecem corretos. Apenas confirme se suas configurações de includes estão corretas (https://github.com/totvs/tds-vscode/blob/master/docs/compilation.md#configura%C3%A7%C3%A3o-de-include-busca-de-arquivos-de-defini%C3%A7%C3%A3o).
