### ISSUE TITLE
Sugestão - Deixar a extensão um pouco menos invasiva

### ISSUE THREAD

**Issue by vinisbitten** [totvs/tds-vscode#1206]
**Meu problema como usuário:**
Sempre que eu abro qualquer projeto a extensão já cria os arquivos na pasta .vscode e isso às vezes me atrapalha no desenvolvimento e quando excluo esses arquivos são gerados novamente

**Minha solução**
Como uso WSL, acabei desabilitando a extensão lá dentro e para projetos ADVPL/TLPP utilizo o code no windows

**Sugestão**
Não criar os arquivos automáticamente, talvez só durante o "bem-vindo", também não criar os arquivos novamente quando o usuário deleta. e dar a opção ao usuário de criar esses arquivos

Desde já, agradeço pela atenção e me coloco à disposição!

**Comment by lwtnb-wrk** [comment]
@vinisbitten Apenas para ficar mais claro, esses outros projetos que você abre e que estão criando a pasta .vscode contem fontes com alguma extensão referente a TOTVS? A saber, PRW, PRG, PRX ou TLPP? Atualmente estes são as extensões de fontes reconhecidas e que ativam a extensão tds-vscode. 
Se os projetos que estiver abrindo contiverem ao menos um fonte TOTVS a extensão será ativada e a pasta .vscode e arquivo da extensão tds-vscode serão criados.
Pelos meus testes se essa condição não for satisfeita, apenas abrindo a visão TOTVS onde estão cadastrados os servidores, também pode ativar a extensão e consequentemente gerar a pasta .vscode e seus arquivos.
Se não for estes os casos, nos informe como reproduzir o problema e iremos analisar a viabilidade de sua sugestão.
Valeu!
