### ISSUE TITLE
Ctrl + clique na chamada da função para ir até ela não está funcionando

### ISSUE THREAD

**Issue by jvvasquesn** [totvs/tds-vscode#1207]
@lwtnb-wrk @brodao2 

Como solicitado issue aberta.
Liguei  o cache em "onMemory", sem sucesso.

"Exclui" as pastas ".vscode" e ".totvsls", instalei o TDS, mas sem sucesso.

Version: 1.86.1
Commit: 31c37ee8f63491495ac49e43b8544550fbae4533
Date: 2024-02-07T09:07:19.849Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 6.5.0-17-generic snap

TOTVS Developer Studio for VSCode (AdvPL, TLPP e 4GL) v2.0.4

**Comment by lwtnb-wrk** [comment]
@jvvasquesn Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos mande os logs para analisarmos.

E pelo que indicou acima, você está usando um Linux, correto? Qual Linux está usando? Lembrando que apenas alguns Linux são homologados pelo VS Code (https://code.visualstudio.com/docs/supporting/requirements), tais como o Debian 10 (Ubuntu Desktop 20.04) e Red Hat Enterprise Linux 8 e Fedora 36. Tivemos alguns relatos de outras versões de Linux não estarem 100% funcionais. Geralmente é apenas uma questão de falta ou versão incompatível de alguma lib, mas não temos como ajudar muito nesses casos.

**Comment by jvvasquesn** [comment]
Estou usando o Ubuntu 22.04.3 LTS

**Comment by lwtnb-wrk** [comment]
@jvvasquesn Realmente esse Linux não consta na lista de ambientes homologados pelo VS Code, mas de qualquer forma nos envie os logs para ver se conseguimos identificar alguma coisa e tentar resolver.

**Comment by jvvasquesn** [comment]
Depois que habilitar os logs qual teste você precisa que eu faça?

Em seg., 12 de fev. de 2024 às 10:27, lwtnb-wrk ***@***.***>
escreveu:

**Comment by jvvasquesn** [comment]
@lwtnb-wrk 
[console_error.log](https://github.com/totvs/tds-vscode/files/14240216/console_error.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/14240217/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/14240218/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/14240219/totvsls_out.log)

Segue os arquivos

**Comment by lwtnb-wrk** [comment]
@jvvasquesn Pelos logs parece apenas que as configurações de includes não estão corretas. Veja nas configurações de includes se o diretório informado "/home/v" existe e aponta para a pasta onde estão os includes necessários para a compilação de fontes.
Se você tiver a pasta de includes em outro lugar, ajuste essa configuração de includes, pois sem ela o Linter/DSS não conseguirão avaliar os fontes e todos os processos que dependem dessa configuração não funcionarão adequadamente.

**Comment by jvvasquesn** [comment]
Deu certo, coloquei  /home/v/includes, antes estava o caminho do include
onde está o projeto no path tem letras maiúsculas.

O path de "totvsLanguageServer.editor.linter.includes": ele só usa para o
linter?

O "includes[]" do servers.json ele usa para compilação?

Em seg., 12 de fev. de 2024 às 13:13, lwtnb-wrk ***@***.***>
escreveu:

**Comment by lwtnb-wrk** [comment]
@jvvasquesn Excelente. Então era apenas a configuração de Includes mesmo.

Essa "totvsLanguageServer.editor.linter.includes" é usada internamente, e nem deve ser modificada manualmente. 

Temos duas configurações de includes veja mais detalhes em https://github.com/totvs/tds-vscode/blob/master/docs/compilation.md#configura%C3%A7%C3%A3o-de-include-busca-de-arquivos-de-defini%C3%A7%C3%A3o
