### ISSUE TITLE
Step Over (F10) não sendo respeitado

### ISSUE THREAD

**Issue by WBaldin** [totvs/tds-vscode#1209]
Após última atualização (v2.0.4), notei que o Step Over do Debug, não está sendo respeitado e o debug se comporta com o se fosse o F5 execução continua, e parando somente se encontra algum ponto de parada.

**Comment by WBaldin** [comment]
Após última atualização (v2.0.4), notei que o Step Over do Debug, não está sendo respeitado e o debug se comporta com o se fosse o F5 execução continua, e parando somente se encontra algum ponto de parada.

**Comment by WBaldin** [comment]
Após última atualização (v2.0.4), notei que o Step Over do Debug, não está sendo respeitado e o debug se comporta com o se fosse o F5 execução continua, e parando somente se encontra algum ponto de parada.

**Comment by lwtnb-wrk** [comment]
@WBaldin Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie o DAP.log gerado após repetir as operações de debug.
E se possível, volte para alguma versão anterior onde isso se comporta de maneira diferente, pois a principio não tivemos alterações nessa questão de depuração.
Além do tds-vscode você recentemente atualizou mais algum binário??

**Comment by WBaldin** [comment]
Não, mais nenhum binário foi atualizado!
Vou providênciar as evidencia de logs e retornarei.

**Comment by WBaldin** [comment]
Estou fechando essa "Issue", pois de alguma modo voltou ao normal e não consigo mais reproduzir o problema.
Grato!
