### ISSUE TITLE
Dúvida - Comportamento do Linter na versão v2.0

### ISSUE THREAD

**Issue by gtrabach** [totvs/tds-vscode#1211]
**Is your feature request related to a problem? Please describe.**
Anteriormente, quando um fonte possuía erros ou alertas, eles só eram exibidos ao compilar o determinado fonte. Além disso, quando os erros eram exibidos, ao fechar o arquivo com o determinado problema, o console era limpo e tal erro não era mais exibido (até reabrir ou tentar compilar o fonte novamente).

**Describe the solution you'd like**
A partir da versão 2.0 da extensão, sempre que um fonte com erro ou alerta é aberto, aquele aviso é exibido no console até que o problema seja sanado e o fonte recompilado, o que acaba sendo incomodo. Muitas vezes você está trabalhando em determinados fontes, acaba tendo que abrir outros para consulta e caso existir algum problema de include ou coisa parecida, o Linter acusa erro e fica assim até que seja efetuada correção. Anteriormente bastava fechar o arquivo com erro que o aviso seria fechado também.

Seria interessante se houvesse uma opção para habilitar ou não o comportamento, pois acaba se tornando incômodo ao abrir vários fonte de uma só vez.

**Comment by lwtnb-wrk** [comment]
@gtrabach Grato pela sugestão. 
Vamos avaliar essa questão e caso aceita, implementaremos em uma versão futura.
Se tiverem mais sugestões, por favor, nos enviem, pois serão muito úteis já que vocês que utilizam o tds-vscode no dia-a-dia e sabem o que faz falta ou que incomoda durante o desenvolvimento.

**Comment by lwtnb-wrk** [comment]
@gtrabach Eu havia entendido errado a questão levantada incialmente.
Existe realmente um problema, pois ao fechar o arquivo, de fato os avisos deveriam ser removidos e não estão sendo.
Na próxima atualização devemos liberar esta correção.
Grato pelo aviso.
