### ISSUE TITLE
Versão 2.0.4 - Scan de fontes (que vai gerando resultado na aba problemas) deixa lento uso do VsCode

### ISSUE THREAD

**Issue by RegisNJr** [totvs/tds-vscode#1212]
Tenho diversas pastas com fontes .prw na minha Workspace

Exemplo
\producao\... (projeto de produção e sincronizado com o GitHub)

Depois usei a opção de Adicionar pasta ao Workspace e tenho também ex:
C:\Fontes\em desenvolvimento\...
C:\Fontes\Modelo\...
C:\Fontes\Exemplo internet\...

Porém são muitos fontes e toda vez que abro o vscode observo que ele fica muito lento e fazendo alguma varredura pois na aba de Problemas (Ctrl + Shit + M) 

![image](https://github.com/totvs/tds-vscode/assets/68110738/d45e15da-e28c-4209-9778-502c8aa72839)

Entendo a importância e que o correto seria tratar os erros e alertas
Mas gostaria de saber se isso é padrão do VScode em si, ou se é da extensão da Totvs
Se algum local que eu possa desabilitar essa varredura para que seja feito apenas na compilação por exemplo
ou pelo menos deixar ou escolher apenas alguma pasta exemplo \producao e não fazer nas pastas de modelo

**Comment by lwtnb-wrk** [comment]
@RegisNJr Observamos esse tipo de comportamento apenas quando temos o Linter habilitado (enable) E o Cache de Navegação ligados (onMemory ou onDisk) em conjunto, para projetos maiores.
Veja em https://github.com/totvs/tds-vscode/blob/master/docs/dss.md e https://github.com/totvs/tds-vscode/blob/master/docs/linter.md como desabilitar essas funcionalidades neste workspace grande.
Tente habilitar o Linter apenas em editores abertos (enableOnlyOpenFiles) ou desabilitar o Cache de Navegação (off), ou reestruture seu Workspace para conter apenas o necessario para o desenvolvimento do dia-a-dia.

**Comment by RegisNJr** [comment]
Boa tarde, esta exatamente com essas configurações

![image](https://github.com/totvs/tds-vscode/assets/68110738/7e8c4ac9-823c-40ba-bcc1-fc17656996b0)

Tenti usar o .tdsindexignore mas não entendi muito bem e acho que não deu muito certo
Por enquanto a única saída é abrir o VsCode quando chega no trabalho e não fechar mais.... até o final do expediente

Preciso procurar como trabalhar com 2 workspace pois nunca fiz, pode ser uma saída

**Comment by brodao2** [comment]
@RegisNJr,

Certifique-se que a configuração esta no nível de usuário e que os arquivos _settings.json_ das área de trabalho, não contenha nenhuma das configurações ``totvsLanguageServer.editor.index.cache`` e ``totvsLanguageServer.editor.linter.behavior``.

Após verificar os arquivos, desligue o _linter_ (nível usuário) e reinicie o VS-Code. 
Use um pouco e sinta a performance. Coloque o _linter_ em ``enableOnlyFile`` e reinicie o VSCode. 

**Importante**: Caso a somatória da quantidade de arquivos seja alto (estimo +10K, pois depende muito do seu _hardware_), pode apresentar problemas de performance, mas não devido a nossa extensão e sim o VSCode gerenciando um grande número de arquivos.

![image](https://github.com/totvs/tds-vscode/assets/114854608/0d0f5560-b865-4872-a3c5-0f107a106540)

**Comment by RegisNJr** [comment]
brodao2

Obrigado pelo retorno, desativei a config de usuário do Linter
Vou usar e ver se melhora

**Comment by RegisNJr** [comment]
Bom dia @brodao2 depois que desativei a config de usuário do Linter melhorou o uso do VsCode.
Obrigado
