### ISSUE TITLE
Na versão 2.0.5 não aparece opção Apply Old Files

### ISSUE THREAD

**Issue by douglasmouraf** [totvs/tds-vscode#1214]
Com a versão 2.0.5 do plugin, ao aplicar um pacote, não exibe a opção Apply old files. Testei a versão 2.0.4 e também não exibe.

Fiz um downgrade para versão 1.3.23 e a opção aparece.

Versão 1.3.23
![image](https://github.com/totvs/tds-vscode/assets/163147570/c15c8f0c-3b05-4417-a8ca-379339e6f56e)

Versão 2.0.5
![image](https://github.com/totvs/tds-vscode/assets/163147570/7fa0b12d-067a-4573-bf3c-0bfb7c4af068)

**Comment by lwtnb-wrk** [comment]
@douglasmouraf Grato por informar sobre esta questão e por já dar uma solução de contorno enquanto uma correção não é realizada.

Na realidade, o que ocorreu foi uma alteração no processo de validação (desde a v2.0.0) antes da aplicação de um patch onde habilitamos a opção de "Apply old files" apenas quando a validação retorna que existem fontes antigos no patch.
O problema é que no processo atual o AppServer não está retornando a informação correta sobre a existência de fontes antigos.
Isso já está mapeado com o time do AppServer e a previsão que nas próximas atualizações isso seja resolvido, então fique de olho nas atualizações do AppServer.

Do lado do tds-vscode não temos como resolver isso, então fecharei essa issue por enquanto.

Pelo menos você já deixou até uma solução de contorno para este problema enquanto não sai a correção do AppServer.
