### ISSUE TITLE
Não efetue leitura do trplay

### ISSUE THREAD

**Issue by BrunoHJorge1** [totvs/tds-vscode#1216]
Pessoal, boa tarde!

Estou utilizando a versão 2.0.6 e iniciar o Debug, o VS Code fica preso na mensagem TDS-DA being initialized, e não roda o debug.
Mesmo arquivo funciona em outros ambientes de outros usuários. 

Segue print:
![vscode](https://github.com/totvs/tds-vscode/assets/163452284/f2c12ddb-6b5c-4ca3-9119-0037da7dc2ad)

Desde já agradeço.
Atenciosamente,

**Comment by lwtnb-wrk** [comment]
@BrunoHJorge1 Conforme conversamos, apagar o arquivo ".dbmap" e reimportando os arquivos, o Replay voltou a funcionar.
