### ISSUE TITLE
Erro ao executar o codigo

### ISSUE THREAD

**Issue by Arthur-Diasz** [totvs/tds-vscode#1218]
A fonte compila normal, na hora de executar aparece o seguinte erro: 
invalid setting verify startpath variable in your environment option or verify if your file setting (.ini) is corrupted

**Comment by lwtnb-wrk** [comment]
@Arthur-Diasz Este provavelmente é um problema de configuração de seu AppServer e não um problema do tds-vscode. 
Aqui tratamos apenas de problemas na extensão tds-vscode.
Procure o suporte da TOTVS para resolver esta questão.

**Comment by danielbolognani** [comment]
Só para tentar ajudar, isso normalmente está no nome do ambiente utilizado no smartclient, verifique se é exatamente o mesmo durante a compilação e durante a execução
