### ISSUE TITLE
Aplicacao de patch: Apply old files ausente

### ISSUE THREAD

**Issue by m-rollo** [totvs/tds-vscode#1219]
Boa tarde!

A partir da versao 2 da extensao nao existe mais a opcao "Apply old files"?

![image](https://github.com/totvs/tds-vscode/assets/133796535/68482f24-0ed0-4165-962a-d00dcbc4c6c7)

Obrigado,

**Comment by lwtnb-wrk** [comment]
mesma questão da #1214
