### ISSUE TITLE
ProtheusDOC

### ISSUE THREAD

**Issue by marcosnqsdev** [totvs/tds-vscode#122]
Seria possível adicionar o ProtheusDOC Generator ao VSCode? É uma funcionalidade muito interessante para documentação do projeto.

ProtheusDOC: http://tdn.totvs.com.br/display/tec/ProtheusDOC

**Comment by lwtnb-wrk** [comment]
@marcosnqsdev Isso seria interessante mesmo. Se quiser tentar implementar e submeter um PR vamos analisar com certeza!

**Comment by charlesreitz** [comment]
+1

**Comment by ricardomansano** [comment]
PRs são bem vindas quanto à essa feature
Grato,

**Comment by AlencarGabriel** [comment]
Olá @marcosnqsdev  , lancei recentemente uma extensão com o intuito de dar ao VsCode praticamente todos os recursos ProtheusDoc do TDS. 

https://github.com/AlencarGabriel/ProtheusDoc-VsCode

O interessante de ser a parte também, é que fica mais fácil para contribuições específicas e funciona para ambas extensões de suporte a AdvPL para VsCode.
