### ISSUE TITLE
Parametros no SC DEBUG SIGALOJA

### ISSUE THREAD

**Issue by raulv329** [totvs/tds-vscode#1221]
Bom dia, só verificando se ficou claro, Eu gostaria de passar como parametro o -A= -A=003 que é o recomendado pelo pessoal do SIGALOJA para eu conseguir manter a conexão com a minha impressora de cupom na tag "programArguments" eu estou passando:
"programArguments": [
"${command:AskForProgramArguments}",
"-M",
"-A=",
"-A=003",
],

Pórem não está dando certo, não consigo finalizar as vendas no modo debug. Outra observação interessante é que quando eu abro o meu smartclient sem o modo debug, eu consigo finalizar as vendas normalmente, mas com o Debug, não.

![Screenshot 2024-04-01 112300](https://github.com/totvs/tds-vscode/assets/75450869/d7c0f80e-673c-4a37-a34f-bed16fb0f3f3)
![Screenshot 2024-04-01 112730](https://github.com/totvs/tds-vscode/assets/75450869/63d9d1c9-7620-4571-879f-21b87ee1f6bf)

**Comment by lwtnb-wrk** [comment]
@raulv329 O argumento "-M" não precisa ser informado pois é configurado pela opção "isMultiSession" (que já está habilitada).
Os outros argumentos devem ser informados sem o "-A=" então informe apenas como:
"programArguments": [
"",
"003"
]
