### ISSUE TITLE
C2090  File not found PRTOPDEF.CH

### ISSUE THREAD

**Issue by ferilva1989** [totvs/tds-vscode#1222]
Prezados,

Instalei a última versão da extensão e está apresentando a seguinte mensagem no primeiro include declarado: C2090  File not found PRTOPDEF.CH

Tenho essa include na pasta, mas não para de apresentar essa msg!

**Comment by DanielYampolschi** [comment]
Bom dia @ferilva1989 , verifique no arquivo servers.json (Que pode ser acessado clicando no botao de engrenagem na visao de servidores) as configuracoes de include. 

Tem que existir pelo menos uma pasta configurada na seção de includes global:

{
"version": "0.2.2",
	"includes": [
		"C:\\Totvs\\Servers\\Protheus\\includes",		
	],
...

Ou na configuração do servidor:
...
"buildVersion": "7.00.210324P",
		"secure": false,
		"includes": [], // <-- Adicione suas pastas de includes aqui
		"environments": [
...

**Comment by ferilva1989** [comment]
Boa tarde!

Está correto... Veja o anexo.

O caminho dos includes está correto tb e dentro da pasta include tem o
PRTOPDEF.CH

Att,

Filipe Ferreira da Silva Nantes
Whatsapp: (19) 99925-2401
https://instabio.cc/ferilva1989


Em qua., 3 de abr. de 2024 às 09:52, DanielYampolschi <
***@***.***> escreveu:

**Comment by lwtnb-wrk** [comment]
@ferilva1989 Os anexos não chegam quando enviado por resposta de emails. Anexe na issue no github para que possamos avaliar, e tambem veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs e nos envie esses logs gerados ao executar a compilação.

**Comment by ferilva1989** [comment]
Perdão. Vou responder pelo GitHub. Segue anexo.
[servers.json](https://github.com/totvs/tds-vscode/files/14920271/servers.json)

**Comment by lwtnb-wrk** [comment]
@ferilva1989 Temos relatos de problemas diversos ao utilizar drives compartilhados na nuvem (google drive, onedrive, etc...).
Experimente copiar a pasta de INCLUDES para um diretório local na sua maquina e ajuste as configurações conforme necessário.
Nos informe se isso resolve seu problema.

**Comment by lwtnb-wrk** [comment]
@ferilva1989 Essa pasta "OneDrive - KAEFER" não é um drive compartilhado do OneDrive? 
De qualquer forma poderia copiar a pasta de includes para um drive do tipo "C:\TOTVS\Includes" e confirmar se isso resolve o problema?

**Comment by ferilva1989** [comment]
Sim, está no OneDrive. Achei que estivesse falando sobre compartilhamento de rede interna, desculpa.
Vou testar e te retorno.

**Comment by ferilva1989** [comment]
Alterei e reiniciei o VS Code.

[servers.json](https://github.com/totvs/tds-vscode/files/14921716/servers.json)

Porém, o problema persiste:

![image](https://github.com/totvs/tds-vscode/assets/59833126/398a2a21-6bf8-428d-be43-88f822708121)

**Comment by lwtnb-wrk** [comment]
@ferilva1989 Você chegou a tentar compilar este arquivo? Ou apenas abriu no editor??

De qualquer forma veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie esses logs para analisarmos.

**Comment by ferilva1989** [comment]
Excluí e reconfigurei o ambiente, abri o fonte e deu certo, compilei e continuou a não apresentar mais o erro.
É realmente essa questão da pasta do OneDrive.
Muito obrigado.

**Comment by lwtnb-wrk** [comment]
@ferilva1989 Excelente.

Apenas para deixar registrado, isso ocorre, pois apesar de aparecerem no Windows Explorer, estes arquivos ainda não estão na pasta localmente. Quando clicamos em um arquivo para abri-lo o respectivo programa do drive, baixa este arquivo e o apresenta conforme seu tipo. Enfim, quando usamos a pasta de "Include" desta forma, tentamos usar o arquivo que ainda não existe localmente e ocorre o erro.

Por isso, para resolver este tipo de questão, recomendamos que seja utilizada uma pasta de Include na máquina local.

Creio que se tornar essa pasta de "Include" como disponível "Offline" também possa resolver o problema, mas não temos esta informação neste momento.
