### ISSUE TITLE
Erro no linter 

### ISSUE THREAD

**Issue by dabraga** [totvs/tds-vscode#1224]
Estou enfrentando o problema abaixo:
Toda vez que digito a palavra class ou method estoura esses erros 
	"buildVersion": "7.00.210324P",

[Info  - 9:22:12 AM] Initializing Language Server.
[Info  - 9:22:12 AM] Language Server initialized.
[Info  - 9:22:12 AM] Developer Support Subsystem initialized.
[Error - 9:22:12 AM] The TOTVS Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

Error - 9:05:10 AM] Delivering pending changes failed
TypeError: this.task is not a function
	at c:\Users\d.braga\.vscode\extensions\totvs.tds-vscode-2.0.5\out\extension.js:56:46272

**Comment by brodao2** [comment]
Favor complementar chamado informando os dados solicitados conforme [Informações importantes ao abrir o chamado](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#informa%C3%A7%C3%B5es-importantes-ao-abrir-uma-issue) e anexe os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema).

No aguardo.

**Comment by brodao2** [comment]
A ocorrência relatada foi corrigida. Favor aguardar liberação da próxima versão da extensão.

À disposição.

**Comment by lwtnb-wrk** [comment]
@dabraga Liberamos uma versão que deve corrigir o problema reportado, caso encontre novos problemas, favor abrir uma nova issue.
