### ISSUE TITLE
Invalid setting (VSCode)

### ISSUE THREAD

**Issue by caarolbritto** [totvs/tds-vscode#1225]
Olá, estou tentando depurar o código mas dá esse erro. 

![image](https://github.com/totvs/tds-vscode/assets/99297825/ab6efc4d-5e9f-4c26-9c09-9ced5630c660)

O caminho do meu launch está assim: 
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Depuração do idioma TOTVS",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "C://totvs//Protheus//Protheus//bin//smartclient//smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true,
			"extendFeatures": {
				"charDetails": false
			},
			"programArguments": [],
			"enableMultiThread": false,
			"enableProfile": false,
			"isAccessibilityMode": false,
			"doNotShowSplash": false,
			"openglMode": false,
			"dpiMode": false,
			"olddpiMode": false,
			"language": "1",
			"ignoreFiles": true
		}
	],
	"lastPrograms": [
		{
			"label": "teste.prw"
		}
	],
	"lastProgramExecuted": "teste.prw"
}

Já verifiquei se o executável do SmartClient está funcionado, está rodando certinho. 
![image](https://github.com/totvs/tds-vscode/assets/99297825/92f7dd1a-40ef-4a27-8684-92511043029e)

O servidor também se encontra conectado. 
![image](https://github.com/totvs/tds-vscode/assets/99297825/7ea90720-22ce-4425-9abc-66cff156e543)

**Comment by danielbolognani** [comment]
Bom dia, verifique o nome do ambiente. No TDS-VSCode vc conectou no ambiente "PROTHEUS1212210" e no Smartclient o ambiente está como "environment". 
Essa mensagem normalmente indica que o ambiente utilizado não existe no appserver.ini

**Comment by caarolbritto** [comment]
Oi, boa noite!

Desculpa pela demora.
Coloquei conforme você falou, mas da o mesmo erro.
![image](https://github.com/totvs/tds-vscode/assets/99297825/52827603-12b5-44bb-9b4e-8f9ef638cf4e)

![image](https://github.com/totvs/tds-vscode/assets/99297825/7a265bdf-599d-4f82-ac20-044dc8e937cf)

**Comment by caarolbritto** [comment]
Troquei direto no arquivo e também não abre. 
![image](https://github.com/totvs/tds-vscode/assets/99297825/7b44639a-026e-4072-946b-57c950f0b2cc)

**Comment by brodao2** [comment]
@caarolbritto 

Acredito que o ini do appServer que está inválido. Verifique se existe o ambiente que está usando e se o mesmo esta com todas as chaves obrigatórias e corretas, p.e. apontando para uma pasta local.
A sua ocorrência não esta relacionada com o uso da extensão em si.

Esta comunidade é exclusivo a ocorrências relacionadas a extensão TDS-VScode e no seu caso, parece-me ser configuração de ambiente.
Solicito que abra um chamado para o [suporte do módulo ou Framework](https://totvscst.zendesk.com/hc/pt-br/#home), onde poderá obter melhor apoio.  

À disposição.
