### ISSUE TITLE
Command 'totvs-developer-studio.config' not found

### ISSUE THREAD

**Issue by EduardoParo** [totvs/tds-vscode#1226]
Após atualização do TDS e VSCODE não consigo me conectar nos servidores ou executar qualquer função da extensão TDS no VSCODE

Já desinstalei com revo unistall instalei novamente não funcionou.

Já voltei o TDS para versão anteriores tbm não funcionou.

Já coloquei em outra pasta os fontes também não resolveu.

segue abaixo print

![image](https://github.com/totvs/tds-vscode/assets/63751196/7069eace-518c-4a3b-ab4f-513b63c81e32)

Version: 1.88.1 (user setup)
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-04-10T17:41:02.734Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.19043

TOTVS Developer Studio for VSCode (AdvPL, TLPP e 4GL)
v2.0.6

**Comment by brodao2** [comment]
@EduardoParo 

Por algum motivo, a extensão não esta sendo inicializada corretamente.
Acesse as abas ``Extension Host`` e ``Main`` e veja se há alguma informação que possa nos ajudar.
Em qualquer uma delas, pode efetuar uma busca por ``TDS-VSCode``.

![image](https://github.com/totvs/tds-vscode/assets/114854608/25dc7eb5-60d0-42b8-b872-625183271648)
![image](https://github.com/totvs/tds-vscode/assets/114854608/0bc4ab84-d59a-4281-88f8-122abbebfbc0)

No aguardo.

**Comment by EduardoParo** [comment]
Renomeei o arquivo <user home>\.totvsls. e funcionou !!! 👍🏻  Muito Obrigadoooo !!!!
