### ISSUE TITLE
Como debugar rotina PO-UI

### ISSUE THREAD

**Issue by fabiofurlanc** [totvs/tds-vscode#1227]
Conforme orientação recebida do suporte.totvs.com dúvidas sobre VSCODE extensão TOTVS devem ser por aqui, como debugar uma rotina em PO-UI, no caso em questão é a rotina PCPMONITOR ponto de entrada PBDetail
tentamos incluindo no atalho do smartclient a instrução  --remote-debugging-port=8888

"\smartclient.exe" -m --remote-debugging-port=8888

e acessado na maquina que executou o smartclient no navegador
localhost:8888

mostra algo assim:
Inspectable WebContents

[TotvsManMonitor](http://localhost:8888/devtools/inspector.html?ws=localhost:8888/devtools/page/A400351DA0C82A1B176BD8260A3B73FD)

[sigapcp-bra-por](http://localhost:8888/devtools/inspector.html?ws=localhost:8888/devtools/page/B176FE53FE13E568815327765D77CD9D)

mas não entendi como fazer a relação com o ponto de entrada PBDetail.tlpp e usar o debug no vscode, ler o ponto de parada, etc

Tem algum procedimento completo sobre isso ?

**Comment by danielbolognani** [comment]
Boa tarde, no seu caso a rotina é em POUI mas o ponto de entrada é advpl/tlpp, então o processo de debug é normal como qualquer outro ponto de entrada. 
É necessário iniciar o Smartclient pelo TDS-VSCode como um debug comum só garantir que a opção "enableMultiThread": true no launch.json
Lembrando que aqui nós damos suporte apenas a problemas relacionados ao uso do TDS-VSCode, dúvidas sobre ponto de entrada, advpl/tlpp e etc não serão tratadas por aqui.
Abraços!

**Comment by fabiofurlanc** [comment]
Olá @danielbolognani  já fiz isso e não para em nenhum ponto de parada e já tratei isso com o suporte.totvs e recomendaram a tratar isso aqui conforme descrito nos tickets #19829415 e #19941024, por isso estou acionando por aqui, então afinal quem resolve é o suporte.totvs que fala que é aqui no github ou o github que fala que é com o suporte.totvs.com ?

**Comment by danielbolognani** [comment]
Está entrando no ponto de entrada? Coloca umas mensagens de conout, se entrar no ponto de entrada vai mostrar em console. A partir daí o problema pode ser algo com o debug no TDS-VSCode, mas se nem chegar no ponto de entrada ai não vai ter jeito de ajudar por aqui.

**Comment by fabiofurlanc** [comment]
Olá @danielbolognani claro que entra no ponto de entrada, tanto que são apresentados os campos adicionais que estou incluindo via PE na tela do Protheus só não debuga.

**Comment by brodao2** [comment]
@fabiofurlanc 

Veja em https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md#depura%C3%A7%C3%A3o-de-servi%C3%A7os-jobs algumas informações sobre depuração.

Lembrando que a depuração deve ser iniciada antes de você rodar o SmartClient (supondo que é web) e que deve-se usar a porta definida na sessão de driver ativa, tanto no SC quanto no VS-Code e o mesmo ambiente.
```
[drivers]
active=tcp
....
[tcp]
type=tcpip
port=20302
...
```

Caso ainda não consiga, favor anexar logs conforme https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema.
