### ISSUE TITLE
SmartClient closed. ExitCode=62097 ExistStatus=CancelExit

### ISSUE THREAD

**Issue by SanHonda** [totvs/tds-vscode#1228]
Bom dia, tudo bem?

Se puderem me ajudar com esse problema....ao tentar debugar um JOB com passagem de parâmetro, ocorre essa msg:
OBS: Eu conseguia debugar esse mesmo JOB e de "uma hora pra outra" parou de funcionar....

[09:39:27] INFO: Application Server connected.
[09:39:27] INFO: TDS-DA ready.
[09:39:31] INFO: SmartClient closed. ExitCode=62097 ExistStatus=CancelExit
[09:39:31] INFO: TDS-DA finished.

Já fiz todos os procedimento que encontrei na internet, porem sem sucesso:
01 - Acessar o VS como ADMIN;
02 - Colocar "enableMultiThread": true no arquivo JSON;
03 - replicar o arquivo "opengl32" pra raiz da pasta do smartclient;
04 - Instalei versões anteriores do TDS;
05 - Reinstalei o VS.....

OBS: Consigo acessar o client normalmente e tb debugar outra rotina colocando, por exemplo, SIGACOM.

Em anexo, arquivo de log e data do appserver.....

Obrigado!

[dap.log](https://github.com/totvs/tds-vscode/files/15321744/dap.log)
[launch.json](https://github.com/totvs/tds-vscode/files/15321747/launch.json)
![appserver](https://github.com/totvs/tds-vscode/assets/161632524/26966a2f-d8d3-4b92-b585-8340f3394fa5)

**Comment by lwtnb-wrk** [comment]
@SanHonda Para depurar JOBS temos alguns procedimentos, pois a depuração tem que se anexar a thread correta para efetuar as operações necessárias.
Em primeiro lugar, o JOB não pode iniciar antes da thread de depuração estar ativa. 
Pelos logs você executa uma "user function" (U_PCPI0E6) para iniciar o JOB, é isso? Como esta estruturada esse disparo do JOB que você quer depurar? Após o disparo do JOB a "user function" permanece ativa? O JOB está no fonte PCPI006.PRW, correto?
Com a "MultiThread" habilitada, e o JOB disparado apos a thread de depuração iniciada, a depuração deveria parar nos breakpoints do JOB.

Voce mencionou tambem que funcionava e parou, consegue voltar para a versao tds-vscode-2.0.6 e ver se algo muda?
