### ISSUE TITLE
erro de compilação

### ISSUE THREAD

**Issue by silfar** [totvs/tds-vscode#123]
boa tarde, quando tento compilar recebo esse erro, alguma ideia ?

Start build error: Start build failed

**Comment by lwtnb-wrk** [comment]
@silfar Existem alguns motivos pelas quais o "start build" pode falhar. Uma delas é tentar compilar em um ambiente onde o RPO esteja em uso, pois para compilar é necessario acesso exclusivo. Verifique se realmente apenas voce esta conectado no ambiente que queira compilar, ou voce pode tentar adicionar a chave BUILDKILLUSER=1 na secao [GENERAL] do appserver.ini do Appserver que voce esta usando para o desenvolvimento. Com essa chave o Appserver deveria derrubar as conexoes previas antes de efetuar a compilacao. 
Enfim de qualquer forma na proxima atualizacao o mensagem devera vir com uma informacao adicional que podera dar pistas do motivo da falha no "start build".
Faca os testes e nos informe se conseguiu compilar.

**Comment by silfar** [comment]
Certo, era um erro na configuração do ambiente. O problema é exatamente
esta questão da mensagem que não nos diz o motivo.

Em qua, 17 de jul de 2019 16:37, lwtnb-wrk <notifications@github.com>
escreveu:

**Comment by lkznogueira** [comment]
Boa Noite Pessoal!!

Também estou com um problema de compilação!

Nesse caso no VS CODE da essas mensagens abaixo de alguns arquivos contem warnings ou errors..
![image](https://user-images.githubusercontent.com/12913181/62336351-4f543400-b4a6-11e9-8333-f5ae0e399fad.png)

E não compila no RPO de forma alguma..

Pego esse mesmo fonte, coloco no TDS e ele compila normalmente....

**Comment by DanielYampolschi** [comment]
Mensagem alterada para indicar melhor para o usuário onde verificar caso esse erro ocorra.
#135
