### ISSUE TITLE
Não consigo usar o visual studio

### ISSUE THREAD

**Issue by Kioruus** [totvs/tds-vscode#1231]
No momento que eu aperto o run aparece o seguinte:
![Captura de tela 2024-05-20 193153](https://github.com/totvs/tds-vscode/assets/167563403/cb0c5ff3-3050-43f6-aff3-309841329143)

**Comment by lwtnb-wrk** [comment]
@Kioruus O que exatamente você estava tentando fazer? Executar um webapp? Depurar um webapp? 
A principio esse erro não parece ser nada relacionado ao tds-vscode...

**Comment by Kioruus** [comment]
Eu seleciono Run and debug e clico aqui apos eu fazer meu html.
![Imagem do WhatsApp de 2024-05-21 à(s) 09 42 34_da17ecf0](https://github.com/totvs/tds-vscode/assets/167563403/37bed334-d6c7-4cb4-b28c-0563d7345e44)
e aparece isso tambem:
![image](https://github.com/totvs/tds-vscode/assets/167563403/7a31d757-a9ff-4a6e-8769-26c7317d1260)

**Comment by DanielYampolschi** [comment]
@Kioruus , essa configuracao de executor com "type": "chrome" me parece ser da extensao do Chrome para o VsCode. Para o tds-vscode, use as instruções no link abaixo:

https://github.com/totvs/tds-vscode/wiki/Configura%C3%A7%C3%A3o-de-diretivas-no-depurador
