### ISSUE TITLE
Nao conecta no TSS

### ISSUE THREAD

**Issue by Adailton-lanca** [totvs/tds-vscode#1232]
Olá.
Estou tentando conectar no TSS para aplicar um patch no RPO e fica apenas na mensagem abaixo e nunca conecta.
"Validando servidor TSS"
![image](https://github.com/totvs/tds-vscode/assets/64661146/61d04572-4e07-4de7-b6bc-e72ab822a467)
[arquivos.zip](https://github.com/totvs/tds-vscode/files/15403375/arquivos.zip)

**Comment by brodao2** [comment]
@Adailton-lanca 

Certifique-se que o endereço, porta e ambiente estão corretos e o appServer disponível.
Caso tenha atualizado o servidor, experimente remover as chave "buildVersion" e "secure" da definição do servidor (f1, busque por "configure server view").

À disposição.

**Comment by lwtnb-wrk** [comment]
@Adailton-lanca Apenas complementando a informação do @brodao2 basicamente pelos logs vimos que aparentemente a combinação de IP:porta (10.2.37.14:5060) não está respondendo a validação.
Porém no seu ambiente ele também cai em uma condição que atrasa a finalização do processo. 
Imagino que se tivesse aguardado, eventualmente o processo de validação teria terminado, mas poderia demorar algo em torno de 30 minutos.
De qualquer forma, vamos alterar o processo para que essa situação não "trave" o processo de validação e mesmo que o IP:porta não respondam, o processo seja mais breve.
Porém seu problema real é que o servidor não está acessível para o tds-vscode, seja por IP:porta incorretos ou algo de infra bloqueando o acesso como firewall ou rotas de IP.

**Comment by Adailton-lanca** [comment]
Deixei o processo de validação executando, foram duas vezes, uma foi mais de 2 horas, outra 1 hora mas não mudou o cenário.
O pessoal de infra informou que não tem nenhum bloqueio, informaram que temos PDVs que estão em acesso VPN, externos a rede e conectam no TSS para transmitir as NFCEs.

**Comment by brodao2** [comment]
@Adailton-lanca 

Esse servidor encontra-se no TCloud? Se sim, existem alguns requisitos para que consiga conectar o TDS-VSCode a ele. Salvo engano meu, é a promoção do RPO de produção para desenvolvimento.

Tentou fazer conexão com e sem VPN?
Tente adicionando uma nova definição.

No aguardo.

**Comment by lwtnb-wrk** [comment]
@Adailton-lanca Você consegue se conectar nesse IP:porta diretamente usando um smartclient?

**Comment by brodao2** [comment]
Chamado encerrado devido a falta de retorno. Caso necessário, favor reabrir.

À disposição.
