### ISSUE TITLE
Abrir uma janela do navegador quando iniciar o debug do tipo "totvs_language_web_debug"

### ISSUE THREAD

**Issue by walterfcarvalho** [totvs/tds-vscode#1233]
Olá!  Estou usando a versão 2.0.6 do TDS Vs code.

Hoje quando inicia o debug com type "totvs_language_web_debug" , o "smartclient" é iniciado em uma nova aba do navegador.

Gostaria de sugerir que houvesse uma "extendedFeature" com a opção de iniciar o "smartclient" uma nova janela do navegador. 

Obrigado.

**Comment by brodao2** [comment]
Grato por nos informar essa necessidade. Esta foi implementada e estará disponível na próxima versão da extensão.

À disposição.
