### ISSUE TITLE
Erro ao iniciar server VSCode

### ISSUE THREAD

**Issue by karinaalves0905** [totvs/tds-vscode#1235]
Ao tentar iniciar os servers no VSCode está ocorrendo o erro em anexo.

<img width="788" alt="ErroVSCode" src="https://github.com/totvs/tds-vscode/assets/170720605/c9d3a631-160e-4188-b654-5568b614633d">
<img width="935" alt="ErroVSCode_2" src="https://github.com/totvs/tds-vscode/assets/170720605/89dc40bf-e83a-4993-88c2-a97801a36bd2">

**Comment by brodao2** [comment]
@karinaalves0905 

Favor complementar o chamando anexando os logs, conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)

No aguardo.

**Comment by lwtnb-wrk** [comment]
@karinaalves0905 Conforme alinhamos por outros canais, o seu problema não estava no appserver mas estava no fonte que estava aberto no editor.
A saber, o fonte estava com extensão PRW, ou seja, AdvPL, mas os nomes das classes e metodos estavam "grandes", coisa que o AdvPL tem limitação. Para contornar esta situação podemos utilizar a extensão/tipo TLPP que permite nomes "grandes", com isso o appserver não causa erro no parser e não derruba o tds-vscode.
De qualquer forma vamos reavaliar as proteções para tentar mais uma vez evitar essa queda no tds-vscode.
