### ISSUE TITLE
File could not be copied to the server ao visualizar os fontes de um patch

### ISSUE THREAD

**Issue by gtrabach** [totvs/tds-vscode#1237]
**Describe the bug**
Ao tentar visualizar o conteúdo de um patch em específico, o TDS está retornando o seguinte erro: File could not be copied to the server.

O patch é validado com sucesso, o erro ocorre ao clicar em PATCH INFO.

**To Reproduce**
1) Selecione o pacote ptm enviado no link abaixo.
2) Aguarde o processo de validação e clique em PATCH INFO.

**Expected behavior**
Exibir os fontes contidos no pacote.

**Screenshots**

**Desktop (please complete the following information):**
Windows 11 64-bits 21H2

**Appserver (please complete the following information):**
20.3.2.5 7.00.210324P-20240219 - 64 bits

Link com o pacote em questão e logs capturados: https://drive.google.com/file/d/1eCbMPrWQ72Qs755tsZGI0TxonThoS8ci/view?usp=sharing

Qualquer coisa podem me acionar no giordano.xavier@totvs.com.br

**Comment by gtrabach** [comment]
@lwtnb-wrk acredito que encontrei o problema. O pacote estava numa pasta com caractere especial (acento e espaço). Quando coloquei em uma pasta sem essas características foi possível visualizá-lo normalmente.

De qualquer maneira, segue logs em anexo.
[Logs TDS.zip](https://github.com/totvs/tds-vscode/files/15471218/Logs.TDS.zip)

**Comment by lwtnb-wrk** [comment]
@gtrabach Grato pela informação adicional dos caracteres especiais e espaços, vamos averiguar essa questão

**Comment by brodao2** [comment]
Grato por nos informar. A ocorrência relatada foi corrigida. Favor aguardar liberação da próxima versão da extensão.

À disposição.
