### ISSUE TITLE
Debug independente do tipo de projeto.

### ISSUE THREAD

**Issue by robsonrosilva** [totvs/tds-vscode#124]
Bom dia,

Poderiam remover do package.json para a extensão ser ativada com qualquer DEGUB, trabalho com o VsCode com linguagens diferentes de ADVPL, quando utilizo com um projeto Typescript se não desativar a extensão no workspace ele sempre abre ela em vez de abrir o debug da própria linguagem.

**Comment by DanielYampolschi** [comment]
Ola @robsonrosilva Obrigado pela sugestao, vamos corrigir.
