### ISSUE TITLE
TOTVS Language Server client: couldn't create connection to server

### ISSUE THREAD

**Issue by fnanttes** [totvs/tds-vscode#1242]
Prezados, bom dia!

Acabo de atualizar a extensão para a última versão e não estou conseguindo conectar aos meus servidores.

É apresentada a seguinte mensagem:

[Error - 09:06:09] TOTVS Language Server client: couldn't create connection to server.
Error: spawn EPERM
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at Object.spawn (node:child_process:799:9)
    at c:\Users\silvafili\.vscode\extensions\totvs.tds-vscode-2.0.8\out\extension.js:62:58093
    at R0.createConnection (c:\Users\silvafili\.vscode\extensions\totvs.tds-vscode-2.0.8\out\extension.js:62:12688)
    at R0.start (c:\Users\silvafili\.vscode\extensions\totvs.tds-vscode-2.0.8\out\extension.js:62:2945)

E antes da atualização conectou normal.

Podem me ajudar, por favor?

Att,

Filipe Nantes

**Comment by lwtnb-wrk** [comment]
@fnanttes Aparentemente o tds-vscode esta com dificuldades de iniciar o processo do Language Server.
Você instalou seu VS Code usando um usuario Admin? Você executa o VS Code como um usuario Admin?

**Comment by fnanttes** [comment]
Descobrimos aqui, nossa política de rede bloqueou os arquivo Code.exe e Advpls.exe.
Estamos verificando com nossa equipe da Alemanha para fazer a liberação.

Na versão 2.0.7 não ocorre, então fiz o downgrade.

**Comment by brodao2** [comment]
Grato pelo retorno.
