### ISSUE TITLE
Compilação / Recompilação de recursos extesão .TRP

### ISSUE THREAD

**Issue by Smmartinez** [totvs/tds-vscode#1243]
Opa pessoal, estamos com uma situação estranha na compilação de programas que utilizem a extensão TRP, essa extensão são as utilizadas nos relatórios extraído do Smartview e compilados para utilização em funções.
O que notei é que quando compilamos o recurso a primeira vez é compilado, se se vamos recompilar ele não esta sobrepondo.

Notei que isso ocorre se escolhemos a opção de recompilar as pasta toda, se a gente vai no arquivo e escolhe o recompilar o processo é  feito.

Poderiam analisar essa situação.

Att
Sergio Martinez

**Comment by lwtnb-wrk** [comment]
@Smmartinez Poderia ver em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos enviar os logs para analise? Se possivel nos cenarios informados, de 1a compilacao, de recompilar a pasta toda e recompilar apenas o arquivo.

**Comment by danielbolognani** [comment]
Devido ao tempo sem respostas, estamos fechando essa solicitação.

Estamos a disposição caso ainda tenha o problema, só não esqueça de anexar os logs ao reabir o chamado.
