### ISSUE TITLE
Acentuação em pastas/arquivos - not found na hora da compilação

### ISSUE THREAD

**Issue by lkznogueira** [totvs/tds-vscode#1244]
Retorno da Issue https://github.com/totvs/tds-vscode/issues/1078

Voltei hoje a utilizar a plataforma MacOs, e vi que este problema retornou..

Teste varias versões para ver a onde o Problema voltou a acontecer, e até a versão v1.3.23 está funcionando essa correção. Desta para cima, voltou com esse problema de not found.
![image](https://github.com/totvs/tds-vscode/assets/12913181/233e4798-2ef0-4458-8cce-9b2826c627b4)

**Comment by lwtnb-wrk** [comment]
@lkznogueira É só na compilação o problema? No debug está tudo em ordem?

**Comment by lkznogueira** [comment]
@lwtnb-wrk 

Debug tbm está com o mesmo problema.

**Comment by lkznogueira** [comment]
@lwtnb-wrk 

Caso precisem de mais informações estou a disposição.

**Comment by lkznogueira** [comment]
@lwtnb-wrk Alguma novidade ref. a este tópico?

**Comment by lwtnb-wrk** [comment]
@lkznogueira Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analisarmos. Tanto o totvsls.log quanto o dap.log.
Grato

**Comment by lkznogueira** [comment]
@lwtnb-wrk Esse erro vocês já corrigiram conforme apontado.. Precisa mesmo gerar os logos novamente?

**Comment by lwtnb-wrk** [comment]
@lkznogueira Ainda não identificamos o problema do macos. 

Um outro problema pontual de acentuação na depuração de pastas com alguns caracteres de letras maiusculas acentuadas foi identificada e corrigida apenas.

**Comment by lkznogueira** [comment]
@lwtnb-wrk 
[totvsls_in.log](https://github.com/user-attachments/files/16553356/totvsls_in.log)
[totvsls_out.log](https://github.com/user-attachments/files/16553358/totvsls_out.log)
[totvsls.log](https://github.com/user-attachments/files/16553359/totvsls.log)

Segue os arquivos.. 

problema na compilação de dar a parte do 'not found' e também quando vai debugar ele não posiciona no fonte.

só recapitulando que é o mesmo problema => (https://github.com/totvs/tds-vscode/issues/1078 ) 
Até essa versão marcada a correção que tinham feito deste problema está OK. A Partir desta versão é que voltou o problema.

![image](https://github.com/user-attachments/assets/94c37c08-9528-4291-9907-ce5129d3728b)

**Comment by lwtnb-wrk** [comment]
@lkznogueira Liberamos uma versão v2.0.9 Pre-release (https://github.com/totvs/tds-vscode/releases/tag/v2.0.9) que deve corrigir esta questão, baixe e instale o vsix para confirmar se o problema foi resolvido.
Se tiver questões quanto a instalação do vsix, veja https://github.com/totvs/tds-vscode/blob/master/docs/install.md

**Comment by lkznogueira** [comment]
@lwtnb-wrk Bom Dia!!

Compilação - OK
Debug - OK

Quando eu abro o código fonte, o mesmo é mostrado na janela de 'Problems'
![image](https://github.com/user-attachments/assets/49fff8eb-0fed-49e5-add8-1c92fbb0d725)

Quando clico nesse item, ele me joga para um fonte inexistente (acho que é o mesmo problema q tínhamos no DEBUG de não posicionar no fonte correto)
![image](https://github.com/user-attachments/assets/0f8755f2-950c-4855-bf2f-04a92a08e87d)

Porem mesmo ele relatando problema nessa telinha, ele compila sem erro algum.
![image](https://github.com/user-attachments/assets/dfe2039e-1f73-44c7-9307-57962eb52036)

**Comment by lwtnb-wrk** [comment]
@lkznogueira Grato pelos testes e informações adicionais.
Vamos corrigir essa questão na aba de Problemas, mas essa questão de diferença poderia ocorrer se houver alguma diferença nos includes utilizados pelo Linter e na Compilação, mas o mais importante seria a compilação que está ocorrendo com sucesso.

**Comment by lwtnb-wrk** [comment]
@lkznogueira Só para alinhar, liberamos a versão 2.0.9, mas ela ainda não tem a correção desse problema no Linter que você apontou.

Abra uma nova issue com essa questão para deixarmos separado o erro desta issue que foi corrigida, okay?
