### ISSUE TITLE
Falha da pintura de comentários ao utilizar BeginSql

### ISSUE THREAD

**Issue by gtrabach** [totvs/tds-vscode#1247]
**Describe the bug**
Ao efetuar um comentário (seja com // ou /*) em um fonte que tenha BeginSql, o conteúdo do BeginSql não é pintado de verde.

**To Reproduce**
1. Crie um fonte que faça uso de BeginSql (ou utilize o fonte XBEGINSQL.prw enviado no zip em anexo).
2. Comente todo o fonte ou partes do BeginSql, seja com // ou /*.
3. Apesar do comentário ser efetivo, as cores do código não são atualizadas para verde.

**Expected behavior**
Todo o bloco de código comentado ficar com a cor verde ou relacionada.

**Screenshots**
![image](https://github.com/totvs/tds-vscode/assets/46979335/c90bb6aa-0dfd-4c32-93d0-c061c7a18874)

Desktop (please complete the following information):
Windows 11 64-bits 21H2

Appserver (please complete the following information):
20.3.2.5 7.00.210324P-20240219 - 64 bits

[Bug TDS BeginSql.zip](https://github.com/user-attachments/files/16021368/Bug.TDS.BeginSql.zip)

**Comment by lwtnb-wrk** [comment]
@gtrabach apenas para informar que a correcao foi liberada na ultima versao 2.0.9
