### ISSUE TITLE
Erro ao Compilar VSCODE - C2006 Statement not allowed outside procedure or function

### ISSUE THREAD

**Issue by jzabotto** [totvs/tds-vscode#1250]
Boa tarde.

Ao tentar compilar o fonte abaixo, apresenta o seguinte erro:

C2006 Statement not allowed outside procedure or function

Estranho que ocorre apenas no ambiente HOMOLOG do REST, na PRODUCAO REST funciona.

Att

**Comment by brodao2** [comment]
@jzabotto 

Agilize a análise da sua ocorrência.

Nenhum fonte anexo ou informado.

Favor complementar chamado informando os dados solicitados conforme [Informações importantes ao abrir o chamado](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#informa%C3%A7%C3%B5es-importantes-ao-abrir-uma-issue).

No aguardo

**Comment by jzabotto** [comment]
Boa tarde,

 #INCLUDE "PROTHEUS.CH"
#INCLUDE "TOTVS.CH"
#Include 'FWMVCDEF.CH'
#INCLUDE "RESTFUL.CH"
#INCLUDE "FIND100.CH"
#include "tlpp-rest.th"

//-------------------------------------------------------------------
/*/{Protheus.doc} SALESFORCE

API de integração de Painéis de Saldo po Natureza

@author		Francisco Oliveira
@since		24/11/2020
@version Protheus 12
/*/
//-------------------------------------------------------------------

//SUBIDA PARA O D-1 EM 08/06/2021

WSRESTFUL SALESFORCE DESCRIPTION "Saldo Por Natureza"

	WSDATA Username AS STRING	OPTIONAL
	WSDATA Password AS STRING	OPTIONAL
	WSDATA Branch   AS STRING	OPTIONAL
	WSDATA Company  AS STRING	OPTIONAL

	WSMETHOD POST cliente ;
		DESCRIPTION "Inclusao cadastro de cliene através do Sales Force" ;
		WSSYNTAX "/api/cliente/{User, Pass, Company, Branch}" ;
		PATH "/api/cliente/";
		PRODUCES APPLICATION_JSON

	WSMETHOD POST pedido ;
		DESCRIPTION "Inclusao cadastro de cliene através do Sales Force" ;
		WSSYNTAX "/api/pedido/{User, Pass, Company, Branch}" ;
		PATH "/api/pedido/";
		PRODUCES APPLICATION_JSON

ENDWSRESTFUL

//-------------------------------------------------------------------
/*/{Protheus.doc} POST itemsDetails
Carrega os Itens Utilizados para Montagem do Painel

@author		Francisco Oliveira
@since		24/11/2020
@version Protheus 12
/*/
//-------------------------------------------------------------------

WSMETHOD POST cliente WSRECEIVE Username, Password, Company, Branch WSSERVICE SALESFORCE

	local aArea         := getArea()
	local lRet          := .t.
	local aCab          := {}
	local cJson         := self:getContent()
	local oJson         := nil
	local oJsonRet      := nil
	local aNomes		:= ""
	local cCampo		:= ""
	local nI			:= 0
	Local oParser       := Nil

	FwJsonDeserialize(cJson,@oParser)

	Self:SetContentType("application/json")
	oJson       := jSonObject():new()
	oJsonRet    := jSonObject():new()

	cError      := oJson:fromJson(cJson)

	if !empty(cError)
		setRestFault(500, 'Parser Json Error')
		lRet    := .f.
	else
		cLog := GrvCliente(oJson,oParser)
		oJsonRet['Mensagem']    := cLog
		::SetResponse(EncodeUTF8(oJsonRet:getJSonObject('Mensagem')))
	endif

	restArea(aArea)


return (.t.)

**Comment by jzabotto** [comment]
[WsSalesForce.zip](https://github.com/user-attachments/files/16353557/WsSalesForce.zip)

**Comment by brodao2** [comment]
Favor complementar chamado informando os dados solicitados conforme [Informações importantes ao abrir o chamado](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#informa%C3%A7%C3%B5es-importantes-ao-abrir-uma-issue) e anexe os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)

No aguardo

**Comment by jzabotto** [comment]
Boa Noite

Segue dados solicitado

VSCODE

Version: 1.91.1 (user setup)
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:06:49.809Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

Extensão TDS v2.0.8

Dados do Server 

Versão: TOTVS Manufatura
Build AppServer: 7.00.210324P-20240703 - 64 bits
Nome do servidor: IX34HRPRHOMCR40
Sistema operacional: Windows Server 2016
Appserver version: 20.3.2.11
Build DBAccess: 20230303-20240531
Release do RPO:  12.1.2310
Release do dicionário: 12.1.2310
Local files: ctree
License server: 2014 - 3.6.1
DB DataBase: MSSQL
DB API Build: 20230303-20240531

Dados do Remote 

Remote build: 7.00.210324P-20210914
Remote version: 20.3.0.0
Remote type: 1
Remote Arquitetura: x86_64 - QT-5.15.3 WIN
Módulo: FAT
Nome do computador: ZABS-AVELL
Sistema operacional: Windows 10 - 
Memória: 32503
Processador: 12th Gen Intel(R) Core(TM) i9-12900HX

Versão da Lib:20240701
Data da Lib: 20240627_171311
Commit ID:9952f3ca1736c307624396a7f32331ab53d74a19
Central de Atualizações: 6081068 (10/07/2024)

Att

**Comment by brodao2** [comment]
@jzabotto 

Faltou os logs com a gravação da ocorrência. Favor gerar log com procedimentos que deram certo e os que deram errado.

**Comment by jzabotto** [comment]
Bom dia,

Alan, fiz o procedimento do arquivo settuings.json e launch.json, porém não gera os arquivos.

[cid:6276b337-204a-4c1d-aaf4-038efaa7a7e3]

[cid:a74b8837-b672-484a-baec-f5912f916ff1]

Ao compilar não encontro na raiz do projeto estes arquivos.

Att


____________________________

João Zabotto | MBA | CAPM |

Analista Sênior Protheus | Líder de Projetos

• (+55 15) 9 8139-7272

________________________________
De: Alan Candido ***@***.***>
Enviado: quarta-feira, 24 de julho de 2024 08:31
Para: totvs/tds-vscode ***@***.***>
Cc: jzabotto ***@***.***>; Mention ***@***.***>
Assunto: Re: [totvs/tds-vscode] Erro ao Compilar VSCODE - C2006 Statement not allowed outside procedure or function (Issue #1250)


@jzabotto<https://github.com/jzabotto>

Faltou os logs com a gravação da ocorrência. Favor gerar log com procedimentos que deram certo e os que deram errado.

**Comment by jzabotto** [comment]
Segue abaixo detalhes

Settings.json

{
    "totvsLanguageServer.launch.args": [
        "--log-file=totvsls.log",
        "--record=totvsls"
    ],
    "totvsLanguageServer.welcomePage": false,
    "totvsLanguageServer.askCompileResult": true,
    "totvsLanguageServer.askEncodingChange": true
}

launch.json

{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "totvs_language_debug",
            "request": "launch",
            "name": "Socer - Com Thread",
            "program": "${command:AskForProgramName}",
            "cwb": "${workspaceFolder}",
            "smartclientBin": "D:\\Work\\Files\\Totvs-Ip\\Clientes\\ResinasBrasil\\smartclient_prd\\Smartclient.exe",
            "isMultiSession": true,
            "enableTableSync": true,
            "enableMultiThread": true,
            "enableProfile": false,
            "isAccessibilityMode": false,
            "doNotShowSplash": false,
            "language": "",
            "ignoreFiles": true,
            "logFile": "${workspaceFolder}\\dap.log"
        }
    ],
    "lastPrograms": [
        {
            "label": "SIGAMDI"
        },
        {
            "label": "APSDU"
        },
        {
            "label": "SIGACDF"
        },
        {
            "label": "SIGACFG"
        },
        {
            "label": "U_ZFATAUT"
        },
        {
            "label": "U_RBUPDFSC"
        },
        {
            "label": "U_RBUPDFOM"
        },
        {
            "label": "U_ZEXPLORE"
        },
        {
            "label": "U_RBUPDCPO"
        },
        {
            "args": [],
            "label": "U_ZCOMAUT"
        },
        {
            "label": "U_RBUPDTMS"
        },
        {
            "label": "SIGMADI"
        },
        {
            "label": "U_RBUPDAMO"
        },
        {
            "label": "U_ZFATFTP"
        },
        {
            "label": "SIGAADV"
        },
        {
            "label": "U_RBUPDCOT"
        },
        {
            "label": "U_RBUPDBD2"
        },
        {
            "args": [],
            "label": "U_RBUPDBD2"
        },
        {
            "args": [
                "\\"
            ],
            "label": "APSDU"
        },
        {
            "args": [
                "\\"
            ],
            "label": "U_RBUPDANX"
        },
        {
            "args": [],
            "label": "U_RBUPDANX"
        },
        {
            "args": [],
            "label": "U_ZFATAUT"
        },
        {
            "label": "U_ZFATUAT"
        },
        {
            "args": [
                "[{ \t\"resource\": \"/d:/Work/OneDrive/Repository/WorkSpace/Protheus_Socer/trunk/ADVPL_DESENVOLVIMENTO/Fomento/Update/RBUPDFOM.PRW\"",
                "owner\": \"AdvPL",
                "severity\": 4, \t\"message\": \"W0003 Local variable CDESC6 never used",
                "source\": \"compile",
                "startLineNumber\": 41, \t\"startColumn\": 1, \t\"endLineNumber\": 42, \t\"endColumn\": 1 }]"
            ],
            "label": "U_"
        },
        {
            "label": "U_RBUPDATF"
        },
        {
            "args": [],
            "label": "U_PRCCHKWF"
        },
        {
            "label": "U_RBUPDCRE"
        },
        {
            "label": "U_ZACESX6"
        },
        {
            "label": "UPDBATCH"
        },
        {
            "label": "U_RBUPDBFC"
        },
        {
            "args": [],
            "label": "U_RBUPDATF"
        },
        {
            "args": [],
            "label": "U_FIXREINF"
        },
        {
            "label": "WIZARDUUID"
        },
        {
            "label": "U_ZGENAUT"
        },
        {
            "label": "U_RBUPDMEX"
        },
        {
            "args": [],
            "label": "U_RBESTAUT"
        },
        {
            "label": "U_RBFAT24"
        },
        {
            "label": "U_RBUPDCTC"
        },
        {
            "label": "SIGAMI"
        },
        {
            "args": [
                "[{ \t\"resource\": \"/D:/Work/OneDrive/Repository/WorkSpace/Protheus_Socer/trunk/ADVPL_DESENVOLVIMENTO/Controle Contrato/Rotina/RBCTCA01.prw\"",
                "owner\": \"AdvPL",
                "severity\": 4, \t\"message\": \"W0003 Local variable OMDLCAB never used",
                "source\": \"Linter",
                "startLineNumber\": 277, \t\"startColumn\": 1, \t\"endLineNumber\": 278, \t\"endColumn\": 1 }]"
            ],
            "label": "U_"
        },
        {
            "args": [],
            "label": "U_ZMILEAUT"
        },
        {
            "label": "SIGAMCFG"
        },
        {
            "label": "SIAMDI"
        },
        {
            "label": "U_RBUPDCSG"
        },
        {
            "label": "U_ZFISAUT"
        },
        {
            "label": "U_RBUPDEMP"
        },
        {
            "label": "SIGAMID"
        },
        {
            "args": [
                "\\"
            ],
            "label": "SIGAMDI"
        },
        {
            "args": [
                "Function RBUPDCTC cEmpAmb",
                "cFilAmb"
            ],
            "label": "_User"
        },
        {
            "args": [],
            "label": "U_RBUPDCTC"
        },
        {
            "label": "U_RBUPDCTC\\"
        },
        {
            "label": "U_RBCERF04"
        },
        {
            "label": "U_RBUPDRAT"
        },
        {
            "label": "U_RBRACTB1"
        },
        {
            "label": "U_RBUPDCAF"
        },
        {
            "label": "U_RBUPDFS2"
        },
        {
            "label": "U"
        },
        {
            "label": "SIGAMDO"
        },
        {
            "label": "SIGAMDI]"
        },
        {
            "label": "U_RBUPDFAT"
        },
        {
            "label": "U_ZEXPLORER"
        }
    ],
    "lastProgramExecuted": "SIGAMDI",
    "lastProgramArguments": []
}



____________________________

João Zabotto | MBA | CAPM |

Analista Sênior Protheus | Líder de Projetos

• (+55 15) 9 8139-7272

________________________________
De: Alan Candido ***@***.***>
Enviado: quarta-feira, 24 de julho de 2024 08:31
Para: totvs/tds-vscode ***@***.***>
Cc: jzabotto ***@***.***>; Mention ***@***.***>
Assunto: Re: [totvs/tds-vscode] Erro ao Compilar VSCODE - C2006 Statement not allowed outside procedure or function (Issue #1250)


@jzabotto<https://github.com/jzabotto>

Faltou os logs com a gravação da ocorrência. Favor gerar log com procedimentos que deram certo e os que deram errado.

**Comment by jzabotto** [comment]
Boa Tarde.

Alan, consegui gerar os arquivos, segue em anxo

Att


____________________________

João Zabotto | MBA | CAPM |

Analista Sênior Protheus | Líder de Projetos

• (+55 15) 9 8139-7272

________________________________
De: Alan Candido ***@***.***>
Enviado: quarta-feira, 24 de julho de 2024 08:31
Para: totvs/tds-vscode ***@***.***>
Cc: jzabotto ***@***.***>; Mention ***@***.***>
Assunto: Re: [totvs/tds-vscode] Erro ao Compilar VSCODE - C2006 Statement not allowed outside procedure or function (Issue #1250)


@jzabotto<https://github.com/jzabotto>

Faltou os logs com a gravação da ocorrência. Favor gerar log com procedimentos que deram certo e os que deram errado.

**Comment by brodao2** [comment]
@jzabotto 

Resposta por e-mail, não aceitam anexos. Favor anexar direto no chamado via Web.

**Comment by jzabotto** [comment]
[Homolog_NaoCompila.log](https://github.com/user-attachments/files/16365376/Homolog_NaoCompila.log)
[Producao_Compilou.log](https://github.com/user-attachments/files/16365377/Producao_Compilou.log)

Segue

**Comment by jzabotto** [comment]
Boa Tarde,

Alan, conforme conversamos foi identificado o problema que era a definição de includes no server.json.

Obrigado

Att
