### ISSUE TITLE
Configurar VSCPDE p/ Depurar Webapp com Broker BALANCE_HTTP

### ISSUE THREAD

**Issue by Jfcastaldi** [totvs/tds-vscode#1251]

**Comment by Jfcastaldi** [comment]
Bom dia! 
Gostaria de saber como configuro VSCODE para depurar Webapp porem utilizamos Brocker_HTML

		{
			"type": "totvs_language_web_debug",
			"request": "launch",
			"name": "TOTVS Language web_Debug-12-1-2310",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientUrl": "https://rhl0tr-hom-protheus.totvscloud.com.br:24080/webapp/",
			"webNavigator": "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",
			"isMultiSession": true,
			"enableTableSync": true,
			"enableMultiThread": false
		}
Obrigado 
José Francisco

**Comment by lwtnb-wrk** [comment]
@Jfcastaldi O processo de depuração não deve ser realizado com Broker nem Balance.
A depuração tem que ser realizada diretamente em qualquer um dos AppServer existentes.
Lembrando também, que a depuração deve ser realizada em ambientes não produtivos.

**Comment by Jfcastaldi** [comment]
Eu sei que não é possível depurar no Broker  nem no Balance 
eu precisava dupurar no WebAPP HTML Protheus porém as portas estão configuradas p/ Broker 
o que fazer 
preciso criar um ambiente com WEBAPP.DLL isolado

**Comment by brodao2** [comment]
@Jfcastaldi 

Você deve conectar o server do VS-Code em um "slave" e a URL do WebApp deve apontar para esse mesmo servidor.

A disposição.

**Comment by Jfcastaldi** [comment]
Bom dia!
obrigado pela dica mas identifiquei qual era meu erro
estava configurado no servidor como SSL  https porém nosso servidor não tem
ainda SSL portanto minha configuração deveria ser http apenas
muito obrigado de certo
Abraço
José Francisco

Em seg., 29 de jul. de 2024 às 07:54, Alan Candido ***@***.***>
escreveu:
