### ISSUE TITLE
Breakpoints desaparecem ao debugar arquivos em pastas com acentos

### ISSUE THREAD

**Issue by gtrabach** [totvs/tds-vscode#1252]
Describe the bug
Ao debugar qualquer fonte que esteja em uma pasta que possua caracteres especiais (como acento), os breakpoints não são exibidos. Sem debugar (apenas com o editor aberto), os breakpoints são exibidos corretamente.

To Reproduce
1. Crie uma pasta com acentos na raiz do projeto e inclua alguns arquivos.
2. Coloque um ou mais breakpoints nos arquivos que estejam dentro da pasta.
3. Inicie um debug. Verifique que os breakpoints irão desaparecer. Além disso, na janela Breakpoints na seção Run and Debug, o caminho do arquivo irá exibir caracteres estranhos.

Expected behavior
Breakpoints aparecerem independente da localização do arquivo fonte.

Screenshots
Sem debugar:
![sem modo debug](https://github.com/user-attachments/assets/ddffd96b-1c87-41cd-9729-c7a4348745a3)

Debugando:
![em modo debug](https://github.com/user-attachments/assets/e51af14d-4486-4cbd-b899-d18c600bef7c)

Desktop (please complete the following information):
Windows 11 64-bits 21H2

Appserver (please complete the following information):
20.3.2.5 7.00.210324P-20240219 - 64 bits

[TDS Logs.zip](https://github.com/user-attachments/files/16382335/TDS.Logs.zip)

**Comment by gtrabach** [comment]
@lwtnb-wrk Segue log conforme solicitado. Ao remover o acento do "TÍTULO", os breakpoints funcionam corretamente.

[Logs e DAP.zip](https://github.com/user-attachments/files/16383775/Logs.e.DAP.zip)

**Comment by lwtnb-wrk** [comment]
@gtrabach Mas eu vi que você retornou parte da acentuação para "GERACAO DE TÍTULO A RECEBER", e ao renomear, como está o funcionamento? 
Voltou a dar problema ou está funcionando mesmo com essa acentuação??

**Comment by gtrabach** [comment]
@lwtnb-wrk Ao remover a acentuação, os breakpoints funcionam. Ao retornar com a acentuação, os breakpoints deixam de funcionar.

**Comment by lwtnb-wrk** [comment]
@gtrabach Mas apenas para confirmar, você está removendo todos os breakpoint entre as alterações? Ao adicionar um breakpoint e depois renomear qualquer pasta e/ou o próprio fonte, é necessário remover os breakpoints e adicioná-los novamente.

Os breakpoints voltaram a exibir caracteres estranhos e sumir do editor, ou a depuração apenas não localiza e interrompe a depuração??

**Comment by gtrabach** [comment]
@lwtnb-wrk

1) Você está removendo todos os breakpoint entre as alterações?
R: Ao renomear a pasta (seja para remover ou incluir acentos), todos os breakpoints são removidos automaticamente. Sendo assim, não há a necessidade de removê-los de forma manual.

2) Os breakpoints voltaram a exibir caracteres estranhos e sumir do editor, ou a depuração apenas não localiza e interrompe a depuração?
R: Sim, os breakpoints voltaram a exibir caracteres estranhos e sumiram do editor. Além disso, quando a depuração cai em uma linha que esteja com breakpoint e o diretório esteja com esses acentos, o editor não localiza o arquivo e não é possível seguir com a depuração. Porém, a aplicação não "cai", simplesmente não é possível navegar pelo fonte. Exemplo:
![image](https://github.com/user-attachments/assets/1223fa6a-53b7-4583-a329-f21f8d0790ca)

**Comment by lwtnb-wrk** [comment]
@gtrabach Reproduzi a ocorrência relatada. 
Ainda não sei o motivo e não testei com outros caracteres, mas a existência da letra "Í" especificamente em maiúsculo está causando esse problema. Se estivesse escrito "í" em minúsculo não teria problema...
Enfim estou analisando para corrigir esta questão.
Grato pelos testes e informações

**Comment by lwtnb-wrk** [comment]
@gtrabach Liberamos uma versão v2.0.9 Pre-release (https://github.com/totvs/tds-vscode/releases/tag/v2.0.9) que deve corrigir esta questão, baixe e instale o vsix para confirmar se o problema foi resolvido.
Se tiver questões quanto a instalação do vsix, veja https://github.com/totvs/tds-vscode/blob/master/docs/install.md
