### ISSUE TITLE
VSCode fica tentando conectar com servers e não para

### ISSUE THREAD

**Issue by Wanderleifusco** [totvs/tds-vscode#1253]
Estava debugando com o VSCode e simplesmente ele saiu da conexão, mas o Protheus não caiu. Depois disso, tentei conectar no Server e agora só fica com a barra tentando.
Qualquer server que eu tento conectar fica assim. Já desinstalei, exclui as pastas e reinstalei do zero mas continua da mesma forma.

**Comment by brodao2** [comment]
@Wanderleifusco 


Favor complementar chamado informando os dados solicitados conforme [Informações importantes ao abrir o chamado](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#informa%C3%A7%C3%B5es-importantes-ao-abrir-uma-issue) e anexe os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)

No aguardo
