### ISSUE TITLE
 Acoplar CodeAnalysis na extensão do VsCode

### ISSUE THREAD

**Issue by Ti-Portao** [totvs/tds-vscode#1254]
- Como está hoje:
Atualmente as empresas precisam criar uma conta no CodeAnalysis, cadastrar projeto, enviar as includes e os fontes em zip para o CodeAnalysis e submeter o projeto aos testes.

- O que pode mudar:
A ferramenta do CodeAnalysis poderia ser acoplada dentro da própria extensão do VsCode disponibilizada pela Totvs. E poderia ser executada antes da compilação do fonte por exemplo ou um comando extra ao alcance da mão para poder submeter o fonte a validação.

- Valor da entrega (benefícios ou problemas a serem resolvidos com essa melhoria):
Isso geraria mais produtividade no processo de desenvolvimento e aumentaria em 100% o uso do CodeAnalysis , já que apesar dessa ferramenta ser excelente, ainda não é utilizada  por todos os clientes.

Isso é uma sugestão de melhoria desde 2022 feita na central colaborativa. 
Vocês poderiam adotar essa sugestão já que o CodeAnalysis por melhor que seja hoje não é utilizado com tanta frequência nos clientes. 

Link sugestão de melhoria da central colaborativa: [https://centraldeatendimento.totvs.com/hc/pt-br/community/posts/5987706123671-TOTVS-Framework-Linha-Protheus-Configurador-Configurador-Acoplar-CodeAnalysis-na-extens%C3%A3o-do-VsCode](https://centraldeatendimento.totvs.com/hc/pt-br/community/posts/5987706123671-TOTVS-Framework-Linha-Protheus-Configurador-Configurador-Acoplar-CodeAnalysis-na-extens%C3%A3o-do-VsCode)

**Comment by danielbolognani** [comment]
Olá, já conversamos com o time responsável pela ferramento CodeAnalysis e por enquanto essa integração não é possível.

Agradecemos a sugestão.
