### ISSUE TITLE
Sugestão - Validar concatenação para evitar fontes que burlam o codeanalysis

### ISSUE THREAD

**Issue by Anderson-Arrais** [totvs/tds-vscode#1255]
Olá, 

Gostaria de uma melhoria, como sugestão, se for possível, validar concatenação dentro dos fontes, acredito que precise de algo assim também no codeanalysis, por exemplo:

A função StaticCall é de compilação proibida desde a versão 33, porém é possível burlar e usar ela apenas concatenando, assim, alguns perssimos dev fazem uso dessa manobra para entregar um fonte que passa pelo codeanalysis mas com problema e pessima qualidade por não está fazendo o basico, segue exemplo:

------
Static Function ALGUM(_cEst,_cMun)
Local _cCodMun  := ""
Local _cStatic  := "S"+"t"+"a"+"t"+"i"+"c"+"C"+"a"+"l"+"l"

_cCodMun  := Eval( {|| &(_cStatic + "(" + "ABCDE, EcCodMun, _cEst, _cMun" + ")") })

Return _cCodMun
------

Como é uma função que não poderia nem ser compilada, poderia existir essa validação no VSCODE, valida essas concatenação e suas variantes e caso ache esse tipo de situação, já bloqueia, isso acontece para dicionario entre outros.

https://centraldeatendimento.totvs.com/hc/pt-br/articles/360016461772-Cross-Segmento-TOTVS-Backoffice-Linha-Protheus-ADVPL-Fun%C3%A7%C3%B5es-classes-e-vari%C3%A1veis-de-propriedade-interna

Recursos restritos e de propriedade interna, com a compilação bloqueada a partir da release 12.1.33, que não possuem suporte:
1	StaticCall()
2	PTInternal()

**Comment by danielbolognani** [comment]
Olá, nossa extensão não faz esse tipo de validação, mesmo pensando no nosso linter, é apenas uma prévia do que o Appserver irá fazer durante a compilação. 
Sugerimos abrir essa sugestão de melhoria para o time de appserver, pois eles são responsáveis pela compilação e validação de fato.
