### ISSUE TITLE
Aplicação de Patch Protheus Release 2310

### ISSUE THREAD

**Issue by DayaneDQZ** [totvs/tds-vscode#1257]
Ao carregar arquivo no VSCode, automaticamente inicia a validação do pacote, porém, passados muitos minutos, a tela não sai da validação.

[Info  - 16:28:06] Starting build for environment PROTHEUS12.
[Info  - 16:28:07] Starting build using RPO token ...

Como proceder?
Obrigada,

**Comment by lwtnb-wrk** [comment]
@DayaneDQZ Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar logs e nos envie os arquivos para analise.
