### ISSUE TITLE
Add Old file indisponível V2.0.8

### ISSUE THREAD

**Issue by GMSalgueiro** [totvs/tds-vscode#1258]
Boa tarde. 

Na versão 2.0.8, a opção "Apply olf files" encontra-se indisponível, impossibilitando o downgrade de fontes caso necessário. 

1. No VSCODE, Vá para a extensão da TOTVS
2. Clique em em server disponível, realize o login
3. Com o botão direito, clique em Patch Apply
4. Veja o erro

É esperado que apareça a opção conforme imagem em anexo:
![Vscode2](https://github.com/user-attachments/assets/91f78304-38d5-46ec-b55e-4711b0067fcd)

Windows 64 bits

**Comment by lwtnb-wrk** [comment]
duplicate #1214
