### ISSUE TITLE
TDS-CLI Script - action patchGen - Possibilitar a definicao do nome do patch gerado

### ISSUE THREAD

**Issue by domagalhaes** [totvs/tds-vscode#1259]
Ao utilizar o TDS-CLI com scripts [https://github.com/totvs/tds-ls/blob/master/TDS-cli-script.md](url) além das chaves já existentes para a definição do caminho (saveLocal ou saveRemote) e a extensão do arquivo (patchType) seria uma melhoria importante uma chave para definir também o nome do arquivo gerado.

Atualmente os arquivos são gerados com o formato: "custom" + data + "-" + hora + "." + extensão (patchType) e quando trabalhamos com a geração de patch para mais de uma release, fica dificil de identificar exatamente qual o patch gerado.

Sugiro criar a chave "fileName" onde pudessemos vincular variaveis ou até constantes, como por exemplo:

```
[user]
RELEASE_NUM=12_1_2310
PATCH_VERSION=1_0_10

[patchGen]
action=patchGen
fileResourceList=${PATCH_LIST}
patchType=PTM
saveLocal=${OUTPUT_DIR}custom_${RELEASE_NUM}
fileName=patch_${RELEASE_NUM}_ver_${PATCH_VERSION}
```

E gerasse um patch com o nome: patch_12_1_2310_ver_1_0_10-2024-08-22-12-56-12.ptm

**Comment by lwtnb-wrk** [comment]
@domagalhaes Grato pela sugestão, mas na realidade esse parâmetro existe ("patchName") e apenas estava faltando na documentação (https://github.com/totvs/tds-ls/blob/master/TDS-cli-script.md), então adicionamos esse parâmetro na documentação do patchGen (https://github.com/totvs/tds-ls/blob/master/TDS-cli-script.md#action--patchgen).

De qualquer forma, grato pela sugestão de melhoria, que na verdade foi uma falha de documentação, pois já existia.

Se tiver outras sugestões fique a vontade para abrir novas issues aqui.
Valeu.

![image](https://github.com/user-attachments/assets/e6c58449-64e0-48ef-b4e7-78d2c31210c6)
