### ISSUE TITLE
Indentação de Código WSRESTFUL e END WSRESTFUL

### ISSUE THREAD

**Issue by alexandreandradeg** [totvs/tds-vscode#126]
Bom dia,

Tem como deixar a tratativa de indentação dos programas de webservices do mesmo jeito que foi feito para um (user function) ou (static function) e (return)?

Pois quando se usa, as funções abaixo, a indentação empurra eles pra frente, acho que deviam ser tratados como se fossem uma (user function) ficando a esquerda.

WSRESTFUL
END WSRESTFUL
WSMETHOD

**Comment by brodao** [comment]
Ajustado regras de indentação de estruturas rest (wsretful/end wsrestful/wsmethod.).

![image](https://user-images.githubusercontent.com/949914/61801809-ceda6700-ae05-11e9-89a6-1ccd2b618b6e.png)
