### ISSUE TITLE
Too many files to compile

### ISSUE THREAD

**Issue by danielblaia** [totvs/tds-vscode#1261]
Bom dia

estamos com essa mensagem ao compilar vários fontes:
[Warn  - 11:18:53] Too many files to compile. Disabling detailed notifications during this compilation only.
porém eu gostaria de continuar recebendo as notificações, mesmo quando mando compilar vários fontes
como fazer?

no aguardo

Daniel

**Comment by lwtnb-wrk** [comment]
@danielblaia Essa restrição existe para evitar a poluição com milhares de linhas de log no "Output", e que é automaticamente ativada se forem compilados mais de 1000 fontes de uma vez.

Para exibição de tanta informação, existe a opção de exibir uma tabela com o retorno de problemas na compilação (errors e warnings), após o termino de todo o processo.

![image](https://github.com/user-attachments/assets/4446e4c0-036d-4087-adcb-cd5de8688580)

Se essa mensagem não está aparecendo verifique a configuração

![image](https://github.com/user-attachments/assets/38380aab-1cd4-49b2-8394-cc4a64fcd831)

Ao clicar para exibir a tabela, o retorno de erros e avisos serão exibidos em uma tabela conforme

![image](https://github.com/user-attachments/assets/99506ea1-2257-49a4-8117-ef73b3519c1c)

Se isso não está te atendendo, nos explique melhor a situação e iremos avaliar a questão.
