### ISSUE TITLE
Debug Pulando Linha no VsCode.

### ISSUE THREAD

**Issue by M35925** [totvs/tds-vscode#1264]
Bom dia, tudo bem?
De forma intermitente as vezes o debug não respeita o F10 e segue o código até o próximo ponto de parada, caso não possuir ponto de parada ele segue sem debug.
Como resolvo isso?
Obrigado.

**Comment by lwtnb-wrk** [comment]
@M35925 Geralmente os problemas de depuração são relacionados a problemas de configuração do launcher ou problemas de sincronismo de código fonte no workspace vs RPO. 
Esse tipo de comportamento no debug geralmente é algo que o Appserver não está nos enviando as mensagens de parada após o F10. Mas isso pode ser por conta de depuração com SIGAMDI e/ou SIGAADV. Você está depurando diretamente nos módulos, por exemplo, SIGAFAT?
Se não for um desses problema, precisamos de informações adicionais para avaliar o problema.
- Qual a build exata do AppServer em uso, e qual a versão do tds-vscode você está usando?
- Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise, em especial o DAP.log

**Comment by M35925** [comment]
Boa tarde,

Uso o SIGAATF.

Versão: 1.70.2 (user setup)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Data: 2022-08-16T05:35:13.448Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
SO: Windows_NT x64 10.0.19045
Em área restrita: undefined

Dados do Server 

Versão: TOTVS Varejo
Build AppServer: 7.00.210324P-20240509 - 64 bits
Nome do servidor: HVACTAPPROSCH01
Sistema operacional: Windows Server 2019
Appserver version: 20.3.2.8
Build DBAccess: 20230303-20240401
Release do RPO:  12.1.2310
Release do dicionário: 12.1.2310
Local files: ctree
License server: 2014 - 3.6.1
DB DataBase: ORACLE
DB API Build: 20230303-20240401

[dap.log](https://github.com/user-attachments/files/16803569/dap.log)

**Comment by lwtnb-wrk** [comment]
@M35925 Aparentemente não tem nada de errado, por parte do tds-vscode, neste log enviado, pois o AppServer parou no breakpoint da linha 462 do fonte MADERO_COM102.PRW e ao receber o comando de F10 (Next) entrou em uma rotina do FWMGSCHDEXECUTE.PRW que você não possui, pois é interno do Framework da TOTVS, e no final do log tem uma desconexão do SC. 
Se essa desconexão não foi forçada por você, pode ter ocorrido um erro dentro desta rotina que então encerrou a conexão do tds-vscode com o AppServer. Talvez alguma informação adicional possa ser encontrada no "console.log" do AppServer
Veja se essa informação te ajuda a encontrar seu problema.

**Comment by M35925** [comment]
Mas o cursor do F10 deveria pelo menos parar na linha 463, pois nem entraria nessa função que vc mencionou que é interna, não é mesmo?
Ele simplesmente executou a rotina toda, só parou no início na linha 462.

**Comment by lwtnb-wrk** [comment]
@M35925 Como não tenho o fonte MADERO_COM102.PRW não saberia dizer qual o comportamento esperado para o comando de F10 após a linha 462. 
Poderia adicionar um print desse trecho para nossa referencia? O que tem na linha 462?
Então a desconexão do SC no final é porque a rotina terminou todo o processamento?

**Comment by M35925** [comment]
![image](https://github.com/user-attachments/assets/01d54e88-0e1a-495b-aaf7-2778833cdaef)

Sim, terminou todo o processamento!

**Comment by lwtnb-wrk** [comment]
@M35925 Bom, realmente neste caso, parece ser alguma coisa no AppServer, pois apos o tds-vscode enviar o comando F10 (next) na linha 462, ele não nos envia o comando para parar na linha 463. 

Você disse que seu AppServer esta na versao 20.3.2.8, tente atualizar  para a última versão do portal 20.3.2.12 (realizando os backups necessários) e veja se o comportamento muda.

**Comment by M35925** [comment]
Eu atualizei o vscode e deu certo, grato pela ajuda.

**Comment by lwtnb-wrk** [comment]
@M35925 Só pra confirmar, o problema de pular linhas no debug foi resolvido atualizando apenas o tds-vscode para a última versão, ou você atualizou seu AppServer também?

**Comment by M35925** [comment]
Só o tds-vscode.
