### ISSUE TITLE
Sumiu os servidores do VSCode.

### ISSUE THREAD

**Issue by M35925** [totvs/tds-vscode#1265]
Boa tarde, tudo bem?

Quando fiz o update do VSCode para a 2.0.2 sumiram meus servidores e quando vou adicionar um dá erro, tive que voltar para a versão anterior, sabem o que pode ser?

Obrigado.

**Comment by lwtnb-wrk** [comment]
@M35925 Que versão você estava usando ainda? E porque está fazendo o update para a versão 2.0.2 sendo que a ultima versao liberada é a 2.0.9? A principio tínhamos um processo para compatibilizar o cadastro de servidores, mas se você estava ainda em uma versão muito antiga, pode ter tido algum problema para compatibilizar esse cadastro.

Veja se você encontra a pasta "C:\Users\<usernamen>\.totvsls". Nela que salvamos o arquivo com as configurações dos servidores "servers.json".

Se ela ainda existir pode conter as informações dos servidores cadastrados. Uma possibilidade seria, renomear este arquivo para algo como "servers_old.json" e deixar o tds-vscode criar um novo "servers.json" para a versão mais atualizada do tds-vscode e então recadastrar os servidores manualmente.

Editar esse arquivo não é recomendável, pois a falta de uma vírgula pode fazer com que o tds-vscode não consiga ler corretamente as configurações.

**Comment by M35925** [comment]
Eu voltei para a versão anterior, que é a 

Versão: 1.70.2 (user setup)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Data: 2022-08-16T05:35:13.448Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
SO: Windows_NT x64 10.0.19045
Em área restrita: undefined

Mas quando vou atualizar, só tem a opção 2.0.2, como faço para pegar a 2.0.9?

**Comment by lwtnb-wrk** [comment]
@M35925 Ah, agora que reparei, seu VS Code também esta super desatualizado, a última versão já é a 1.92.
O VS Code nessa versão deve estar limitando a atualização do tds-vscode para 2.0.2.
Atualize seu VS Code para poder usar a última versão do tds-vscode 2.0.9.

**Comment by M35925** [comment]
Atualizei e deu certo, até debugar agora estou conseguindo, hehehe, grato pela ajuda.
