### ISSUE TITLE
demora para carregar VSCode

### ISSUE THREAD

**Issue by Mayco-Andrey-Ranghetti** [totvs/tds-vscode#1266]
Ao abrir o VSCode, o último projeto aberto é carregado automaticamente, e isto é legal.
Contudo, o VSCode fica um bom tempo validando os fontes procurando por erros e avisos.
Existe alguma configuração para desabilitar esta análise inicial?
Ou, além o VSCode abrir o último projeto, ele também reabre todas as abas (fontes) que estavam abertos ao fechar, tem como configurar a validação apenas para os fontes abertos?

**Comment by brodao2** [comment]
@Mayco-Andrey-Ranghetti 

Pode modificar o comportamento através das chaves do [Linter](https://github.com/totvs/tds-vscode/blob/master/docs/linter.md#tds-linter).

À disposição.

**Comment by Mayco-Andrey-Ranghetti** [comment]
Eu verifiquei o Linter, e no meu caso, já está ativo a opção para exibir info apenas dos arquivos abertos.
Mas, sabendo agora desta opção, eu percebi o seguinte:
- ao iniciar o VSCode, tenho a impressão que o Linter está passando por todos os arquivos do projeto
- ao final, de fato, os erros e avisos que ficam na status bar são apenas dos arquivos abertos
Isto procede?

**Comment by lwtnb-wrk** [comment]
@Mayco-Andrey-Ranghetti Para termos uma noção maior do seu cenário, quantos fontes você mantem aberto normalmente? Qual o tamanho do workspace que você trabalha normalmente?

De qualquer forma, veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by Mayco-Andrey-Ranghetti** [comment]
@lwtnb-wrk , agora que vc perguntou quantos fontes eu mantenho aberto, eu me deparei com um fato de que nunca fecho os fontes. Agora eu fiz uma limpa na área de trabalho do VSCode, fechei todos os fontes, e o VSCode iniciou normalmente e já conectou no appserver.

**Comment by lwtnb-wrk** [comment]
@Mayco-Andrey-Ranghetti Ah excelente, mas apenas para termos noção, como estava seu ambiente?
Quantos fontes estavam abertos para você perceber essa lentidão?

**Comment by Mayco-Andrey-Ranghetti** [comment]
Eu uso um notebook, core I7 com 16GB de memória e SSD e sempre tenho vários outros aplicativos abertos e ultimamente, sempre está batendo entre 80% e 90% de consumo de memória.
Muitas as vezes que eu abro o VSCode, chego a perceber que a ventoinha do notebook dá uma acelerada, ouço o barulho dela girando com maior velocidade, indicando que ocorreu um consumo maior de processamento.
Quando o barulho diminui indica que o VSCode já inicializou completamente.
Eu uso o navegador Opera e Teams.
Agora que eu fechei todos os fontes abertos, o VSCode abriu normalmente e sem grandes indícios de alto processamento.

**Comment by lwtnb-wrk** [comment]
@Mayco-Andrey-Ranghetti Grato por todas as informações.
Realmente a máquina parece ser capaz de lidar com isso, mas de qualquer forma, programas como o VSCode e outras IDEs sempre exigem bastante da máquina.
Mas se trabalhar com menos fontes abertos resolveu, vamos deixar a criterio dos devs, de trabalhar com mais ou menos performance de acordo com a quantidade de fontes abertos.
Vou finalizar essa issue, mas se tiver outros problemas, favor abrir novas issues que avaliaremos.
