### ISSUE TITLE
Resultado da Compilação de pastas

### ISSUE THREAD

**Issue by jeffersonbcm** [totvs/tds-vscode#1267]
Boa Noite,

Notei que depois de algumas atualizações, que ao compilar uma pasta, o VS Code não identifica mais os fontes que já estavam compilados e com isso apresenta sempre a coluna de Result como SUCCESS.

![Screenshot_367](https://github.com/user-attachments/assets/810b5c6d-12e1-4e4c-8c1e-6b793332c54a)

Vs Code: 1.93.1
TDS: v2.0.9
AppServer: 
* TOTVS - Build 7.00.210324P - Sep  2 2024 - 14:23:19 
* Build: 64 bits
* SVN Revision: 42368
* Build Version: 20.3.2.14

**Comment by brodao2** [comment]
@jeffersonbcm 

O comportamento da compilação em lotes (pastas) foi modificado para recompilar todo os fontes.
Para usar o comportamento anterior, acione a tecla ALT.

À disposição.

**Comment by lwtnb-wrk** [comment]
@jeffersonbcm Apenas confirme na visão de Saída (Output) se você acionou a compilação ou recompilação.
A recompilação irá forçar a compilação independentemente se ela já se encontrava compilada no RPO.

**Comment by jeffersonbcm** [comment]
Boa noite,

Obrigado @brodao2 e @lwtnb-wrk , deu certo acionando ALT e compilando a pasta, mostrou skipped para os fontes que já estavam compilados.
