### ISSUE TITLE
Depuração F10 step over, não pula linha a linha

### ISSUE THREAD

**Issue by eurairapelli** [totvs/tds-vscode#1269]
Depuração ADVPL F10 step over, não pula linha a linha, ele avança como se fosse o F5;
O F11 executa linha a linha, porém por ser "into" é lento.

Depurar fonte, com queries, abertura de alias, posicionamento, etc.

Windows 10 64 bit
![image](https://github.com/user-attachments/assets/c3abb15b-8af2-4ddc-ba19-5a27978a5aca)

"buildVersion": "7.00.210324P",
Reproduzido no tcloud, porém acontece em ambientes não tcloud (aleatório)

**Comment by lwtnb-wrk** [comment]
@eurairapelli Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise. Em especial o dap.log por se tratar de questao na depuracao.

**Comment by eurairapelli** [comment]
Segue

[dap.log](https://github.com/user-attachments/files/16999488/dap.log)

**Comment by lwtnb-wrk** [comment]
@eurairapelli Vi no logs, vário comandos de Next sendo executados, não consigo determinar onde está pulando, pois teria que ter o fonte e instruções de onde parar e que ações tomar.

E este dialog não está sendo exibido ao iniciar a depuração?
![image](https://github.com/user-attachments/assets/556f4b43-33d7-4116-9d8d-136323f13f88)

**Comment by eurairapelli** [comment]
1. Sim, ele abre.
2. Não é exclusivo deste fonte, problema acontece a mais de 1 ano e outros devs também passam pelo problema.

Posso mandar o fonte PE.
Mas você pode pegar um fonte e depurar, com querie, etc.
Me avisar se precisar do fonte

**Comment by lwtnb-wrk** [comment]
@eurairapelli Mas então você ignora a mensagem e espera que a depuração funcione corretamente usando SIGAMDI? 

Esse problema na depuração usando SIGAMDI e SIGAADV é conhecido a muito tempo, e é algo no AppServer que não temos controle. Isso já está na documentação do tds-vscode a muito tempo, mas mesmo assim adicionamos essa mensagem de alerta para que o usuário tivesse conhecimento do problema.

**Comment by eurairapelli** [comment]
SIGAMDI, aperto confirmar.
Não pode usar sigamdi e sigaadv? 
Tem que ir de modulo, sigafat?

**Comment by lwtnb-wrk** [comment]
https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md
