### ISSUE TITLE
Debug - smartclientUrl Dinâmico

### ISSUE THREAD

**Issue by bryanfarroupilha** [totvs/tds-vscode#1271]
Na configuração de Degub do VSCode usando WEBAPP, é possível deixar o parâmetro smartclientUrl dinâmico igual ao program ?
Pois em cada momento eu posso estar realizando um debug em um ambiente diferente. 
Para não criar VARIAS configurations dentro do launch.json, se tornar a URL dinâmica, vai ajudar MUITO.

**Comment by brodao2** [comment]
Grato pela solicitação de melhoria.

A mesma já foi implementada e encontra-se em ciclo de testes e será liberada em breve.

À disposição.

**Comment by lwtnb-wrk** [comment]
Versao 2.0.10 publicada no [marketplace](https://marketplace.visualstudio.com/items?itemName=totvs.tds-vscode) com a melhoria.
