### ISSUE TITLE
MACOS Sequoia 15.0

### ISSUE THREAD

**Issue by snlacerda** [totvs/tds-vscode#1272]
# Help us to help you.

## Before opening an issue

- Make sure the extension is up to date.
- See [Resolução de Problemas](TROUBLESHOOTING.md#problemas-gerais), with common and/or known occurrences.

## Enter the data below

**Describe the bug**
Apos a atualizacao do MacOS para o Sequoia, não esta sendo possivel utilizar o plugin

**To Reproduce**
Abra o VSCode e tente conectar em qualquer servidor

Loguru caught a signal: SIGSEGV
Stack trace:
12      0x7ff80f4aebef thread_start + 15
11      0x7ff80f4b3253 _pthread_start + 99
10         0x1026fa0cf void* std::__thread_proxy<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, WorkThread::_StartThread(std::string const&, std::function<void ()>)::$_0>>(void*) + 63
9          0x1026cce67 std::__function::__func<QueueManager::LaunchLsThread(bool)::$_0, void ()>::operator()() + 759
8          0x1025b146e BaseMessageHandler<(anonymous namespace)::In_TextDocumentDidOpen>::Run(std::shared_ptr<InMessage>) + 366
7          0x1025b1afb (anonymous namespace)::Handler_TextDocumentDidOpen::Run((anonymous namespace)::In_TextDocumentDidOpen*) + 1163
6          0x102731ef6 WorkspaceFile::doProcess(DBCodeAction, std::function<void (std::vector<lsDiagnostic>*)>) + 3238
5          0x1026f2e7d TotvsLinter::callAdvplC(CallAdvplCParams const*) + 2477
4          0x102707e31 tAdvplc::run() + 7601
3          0x1034d788f executeAppreDll(int, char*, tString&, tString&, tString&, tString&, char*, std::function<void (tAbstractParserInterface*)>) + 655
2          0x1034cd124 Preprocessor(int, char**, tString&, tString&, tString&, bool, tString*, char*, std::function<void (tAbstractParserInterface*)>) + 1012
1          0x1034cbbd8 ParseCommandLine(int, char**, tAutoArray<tString>&, tString&, tAutoArray<tString>&, tString&, unsigned char&, unsigned char&, tString&, tString&, unsigned char&, unsigned char&, unsigned char&, tString&) + 2184
0                  0x0 4   ???                                 0x0000000000000000 0x0 + 0
(   0.044s) [languageServer  ]                       :0     | Signal: SIGSEGV

**Comment by lwtnb-wrk** [comment]
duplicate #1270
