### ISSUE TITLE
Log detalhado de compilacao

### ISSUE THREAD

**Issue by nicociri** [totvs/tds-vscode#1275]
(google translate)
Existe alguma maneira de manter um log de compilação detalhado?

Preciso saber:

*quem compilou?
* quando foi compilado?
* o que é compilado?

O log atual do repositório solo lista a aplicação de patches, mas nenhuma compilação de rdmakes. É possível? Existe?

obrigado!
----------------------------------- SPANISH
Existe alguna manera de tener un log detallado de compilaciones?

Necesito saber:

* quien compilo?
* cuando compilo?
* que compilo?

El log de rpo actual solo lista la aplicacion de parches pero no compilaciones de rdmakes. Es posible? Existe?

gracias!

**Comment by lwtnb-wrk** [comment]
@nicociri O Inspetor de Objetos apresenta todos os fontes e recursos compilados no RPO, com a sua data de compilação, status (Prod ou Dev) e em qual RPO está compilado (Default, Custom ou TLPP).
É isso que procura ou tem alguma informação adicional que procura??

**Comment by nicociri** [comment]
mas e realmente a data de compilacao?
Si um rdmake tem data de ontem no filesystem, mas eu compilo HOJE. Cual e a data que aparece no inspetor de objetos?

Alem disso, tem jeito de saber que usuario foi que fez a compilacao?

**Comment by brodao2** [comment]
@nicociri 

A data apresentada é da última edição no momento da compilação. A data mesmo da compilação e usuário não temos essa informação.

À disposição.

**Comment by nicociri** [comment]
E possivel solicitar como melhoria?

tem varios clientes que preguntaram por esta info... e seria util pra nos mesmo...

**Comment by danielbolognani** [comment]
Boa tarde,
Essas informações do patch são mantidas dentro do RPO e de responsabilidade do time de Appserver. Um log mais detalhado de compilação teria que seguir o mesmo caminho, ser armazenado pelo Appserver para podermos trazer para dentro do TDS-VSCode.
Para sugestões de melhorias no Appserver, é necessário abrir um ticket para o atendimento e a equipe de Appserver irá analisar e responder a viabilidade ou não dessa melhoria.
