### ISSUE TITLE
Erro Loguru caught a signal: SIGSEGV depois que atualizei meu Mac para Sequoia 15.0 

### ISSUE THREAD

**Issue by maickonqueiroz** [totvs/tds-vscode#1276]
## Depois que atualizei meu macos para Sequoia começou a aparecer esse erro dentro do VSCODE na extensão do TDS.

Loguru caught a signal: SIGSEGV
Stack trace:
12      0x7ff80a976bef thread_start + 15
11      0x7ff80a97b253 _pthread_start + 99
10         0x1026c50cf void* std::__thread_proxy<std::tuple<std::unique_ptr<std::__thread_struct, std::default_delete<std::__thread_struct>>, WorkThread::_StartThread(std::string const&, std::function<void ()>)::$_0>>(void*) + 63
9          0x102697e67 std::__function::__func<QueueManager::LaunchLsThread(bool)::$_0, void ()>::operator()() + 759
8          0x10256d48e BaseMessageHandler<(anonymous namespace)::In_TextDocumentDidChange>::Run(std::shared_ptr<InMessage>) + 366
7          0x10256da4b (anonymous namespace)::Handler_TextDocumentDidChange::Run((anonymous namespace)::In_TextDocumentDidChange*) + 955
6          0x1026fcef6 WorkspaceFile::doProcess(DBCodeAction, std::function<void (std::vector<lsDiagnostic>*)>) + 3238
5          0x1026bde7d TotvsLinter::callAdvplC(CallAdvplCParams const*) + 2477
4          0x1026d2e31 tAdvplc::run() + 7601
3          0x1034a288f executeAppreDll(int, char*, tString&, tString&, tString&, tString&, char*, std::function<void (tAbstractParserInterface*)>) + 655
2          0x103498124 Preprocessor(int, char**, tString&, tString&, tString&, bool, tString*, char*, std::function<void (tAbstractParserInterface*)>) + 1012
1          0x103496bd8 ParseCommandLine(int, char**, tAutoArray<tString>&, tString&, tAutoArray<tString>&, tString&, unsigned char&, unsigned char&, tString&, tString&, unsigned char&, unsigned char&, unsigned char&, tString&) + 2184
0                  0x0 4   ???                                 0x0000000000000000 0x0 + 0
(   4.440s) [languageServer  ]                       :0     | Signal: SIGSEGV

## Itens realizados para tentar resolver o problema

**Instalar novamente a extensão do VsCode**
1. Apaguei todos os arquivos do VSCODE do meu Macos incluindo as includes, depois de instalar novamente o erro persiste;
2. Instalei outras versões do TDS da TOTVS;
3. Busquei alternativas em forúms, executei algumas delas, porém aparentemente o problema esteja na extensão TDS;

**Screenshots**
<img width="1141" alt="image" src="https://github.com/user-attachments/assets/38390aa2-30d7-43a6-ac53-896979a800fa">
Acontece o erro quando conecta em um servidor Protheus, abrindo o editor, qualquer palavra escrita o erro será apresentado, depois desse erro conforme imagem acima, nada mais funciona, isto é, conectar em um servidor Protheus, compilação. 

Parece que depois do erro a extensão para VSCode interrompe o funcionamento.

**Appserver:**
 - OS/Architecture: MacOs Sequoia 15.0
 - "buildVersion": "7.00.210324P",
Obs.: Testei em outras build's e o erro ainda é apresentado.

**Comment by brodao2** [comment]
Duplicado #1270
