### ISSUE TITLE
Não encontrei a opção "Apply old files".

### ISSUE THREAD

**Issue by lmatsura** [totvs/tds-vscode#1277]
Bom dia,

Não estou conseguindo aplicar o patch com a opção "Apply old files."

**Comment by brodao2** [comment]
@lmatsura 

Ao selecionar o pacote de atualização e após a validação, apresenta erro de que há fontes mais antigos?

Se não for o caso, favor anexar os logs, conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema). 

Um instantâneo da tela após selecionar o pacote, também será útil.

À disposição.

**Comment by lmatsura** [comment]
Boa tarde,

O que esta ocorrendo é quando vou aplicar o patch e não esta aparecendo no
formulário de path a opção ""Apply old files"", não esta aparecendo
[image: image.png]

antes estava aparecendo a opção
[image: image.png]




Version: 1.93.0 (user setup)

Commit: 4849ca9bdf9666755eb463db297b69e5385090e3

Date: 2024-09-04T13:02:38.431Z

Electron: 30.4.0

ElectronBuildId: 10073054

Chromium: 124.0.6367.243

Node.js: 20.15.1

V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.20348

[image: image.png]

Versão da Lib:

20240408 - 20240403_114352



AppServer - Build: 7.00.210324P-20240219
AppServer - Versão: 20.3.2.5


att




Em sex., 4 de out. de 2024 às 10:31, Alan Candido ***@***.***>
escreveu:

**Comment by lwtnb-wrk** [comment]
@lmatsura Atualmente a exibição da opção de "Apply old files" depende da validação do patch a ser aplicado. Porém existia um problema no AppServer que não nos fornecia as informações corretas de fontes antigos durante a validação. Em meus testes a partir da versao 20.3.2.13 do AppServer, esse problema foi corrigido, então confirme se seu AppServer está atualizado.

Caso não possa atualizar o AppServer neste momento, existe a opção de usar uma versão mais antiga do tds-vscode (v1.3.23) que não utilizava essa informação ainda.

#1214

**Comment by brodao2** [comment]
@lmatsura 

Respostas por e-mail não repassa anexos ao chamado. Favor acessar o chamado via navegador e anexar os arquivos. Reforço que nos envie os de log também.

No aguardo.

**Comment by lmatsura** [comment]
@lwtnb-wrk, obrigado pelo retorno, atualizei o appserver e apareceu a opção "Apply old files"

att
