### ISSUE TITLE
Problema com o debug no TDS-VsCode

### ISSUE THREAD

**Issue by BrunoORosa90** [totvs/tds-vscode#1278]
Bom dia, ontem conversei com o analista Alan Candido a respeito do problema com o debug no TDS-VsCode, gerei os logs solicitados e já repassei para o mesmo.

A extensão tanto na versão v2.0.8 e v2.0.9 ocorrem o mesmo problema.
versão do VsCode - 1.94.0

Foram gerados os logs conforme sugestão - https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema
[dap.log](https://github.com/user-attachments/files/17293463/dap.log)

Estou realizando o debug, em um processo de mensagem via postman com utilização da fila do Smartlink, o fonte da fila executa e os pontos de parada funcionam e seguem até o fonte principal do execauto, mas não consegue avançar para outras funções de outros fontes mesmo com os pontos de parada definidos. está passando pela função MsGetDBAuto, mas nao entra nas funções informadas nos  parâmetros.

No debug com a utilização do F10 ou F11 ele não vai para as funções de outros fontes e sim para próxima linha conforme imagem:

<img width="680" alt="08102024" src="https://github.com/user-attachments/assets/855ecd40-5025-4191-afe9-89c75ca435cf">

   .
No Aguardo,
Atenciosamente,

**Comment by brodao2** [comment]
@BrunoORosa90 

Você está com a chave enableMultiThread ligada?

Lembrando que somente as threads iniciadas após a conexão de depuração podem ser depuradas.
No caso de serviços rest, veja em https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md#depura%C3%A7%C3%A3o-de-servi%C3%A7os-jobs como proceder.

À disposição.

**Comment by BrunoORosa90** [comment]
Sim, a chave enableMultiThread está ligada

<img width="368" alt="ConfiguracaoLaunch" src="https://github.com/user-attachments/assets/0f10571e-e77a-453c-864b-f0fb4f6a30fa">

Até o mês de Setembro estava conseguindo debugar normalmente, conforme se depura o serviço rest, essa questão do debug se perder começou nesse mês de Outubro, impossibilitando continuidade de analises dos fontes.

**Comment by brodao2** [comment]
Favor informar a versão exata do appServer em uso. Algo como:
***  TOTVS S/A  ***
***  www.totvs.com.br  ***
* TOTVS - Build 7.00.*******************
* Build: 64 bits
* DEBUG VERSION
* SVN Revision: **************
* Build Version: ******************

Aparece ao colocar o appServer no ar.

No aguardo.

**Comment by BrunoORosa90** [comment]
Segue conforme solicitado.

<img width="349" alt="appserverLocal" src="https://github.com/user-attachments/assets/f4a395fc-a54a-4221-a4ad-3791ad8c8182">

**Comment by DanielYampolschi** [comment]
@BrunoORosa90 Vc pode anexar o dap.log aqui na issue por favor? 

Outra dúvida, a porta que vc informa no smartclientUrl (localhost:4321) essa é a porta multiprotocolo (A mesma que vc usa para conectar no servidor) ou a porta do webapp?

Mais uma dúvida, você possui os outros fontes (Os que não estão entrando no mesmo workspace certo? 

E uma última coisa.. Tente alterar, no seu launch.json, a chave type.:

No seu caso está com: **totvs_language_debug**. Substitua por: **totvs_language_web_debug**

**Comment by BrunoORosa90** [comment]
Passei a versão do webapp, e a versao do appserver é
<img width="235" alt="image" src="https://github.com/user-attachments/assets/d78adf95-03cd-4ba6-bfa9-91fdd9861ce7">

dap.log 
[dap.log](https://github.com/user-attachments/files/17299350/dap.log)

Respostas
1) Mesma porta
2) Sim, possuo todos os fontes no mesmo workspace/
3) Vou realizar a alteração da chave e reporto aqui (Obs.: Outro analista está com o mesmo problema e a chave dele está como totvs_language_web_debug)

**Comment by DanielYampolschi** [comment]
Muito obrigado pelas informações. 

Mais umas coisas:

1 - Caso o teste de ajustar o type não mude o comportamento, tente usar a porta do webapp diretamente:
Por favor olhe nesse link para detalhes de como fazer isso: https://github.com/totvs/tds-vscode/wiki/Depura%C3%A7%C3%A3o-com-WebApp-%E2%80%90-Configura%C3%A7%C3%B5es 

Por favor leia tudo, mas no seu caso seria alterar para forma descrita no item 1: "1. Usando a porta do próprio WebApp:"

2 - Após a parada ocorrer em em CTBA102.PRW linha 1449, quando vc pressiona F10 ou F11 , qual exatamente seria o(s) fonte(s) e linha(s) esperados que ocorra a parada do debug?

PS: O VsCode e os logs não conhecem "funções" e etc.. apenas fontes e linhas, por isso a pergunta acima.

Muito obrigado.

**Comment by BrunoORosa90** [comment]
Boa tarde

Foi realizado a alteração do type e também a configuração conforme orientações
<img width="418" alt="09102024_settings" src="https://github.com/user-attachments/assets/ccb9d0cf-3711-4da7-874b-5be30a0ecf60">
<img width="358" alt="09102024_launch" src="https://github.com/user-attachments/assets/26d6cca5-89e2-4ea4-9ef7-f2324ecf430b">
Não surtiu efeito, continua mesma situação da linha 1449 vai para 1451 (CTBA102.PRW) em vez de ir para linha 3731 (CTBA105.PRW)

**Comment by brodao2** [comment]
@BrunoORosa90 

Fiz testes para depurar macros e codeblocks e o mesmo ocorreu sem programa. Anexo o programa de teste.
Se desejar, faça um teste compilando e depurando esse fonte, colocando um BP na linha 7.
[macro.txt](https://github.com/user-attachments/files/17363031/macro.txt)
Renomear o arquivo para prw e colocar na sua área de trabalho.

Favor efetuar os seguintes procedimentos:

1. Certifique-se que:
- não esta em ambiente com balanceamento de carga;
- que o ambiente que compila e depura é o mesmo de execução do WebApp;
- as chaves "enableMultiSession" e "enableMultiThread" ativadas na definição do executor de depuração.
- ative todos os logs https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs

2. Recompilar todos os fontes envolvidos na depuração
- Certifique-se que não haja mais de um fonte com o mesmo nome na sua área de trabalho.

4. Remova todos os BP (pode haver algum erro de sincronismo) e adicione o BP no local desejado.

5. Caso use JOBs ou serviços Rest, certifique-se que estes iniciem a execução após a conexão de debug ser efetuada ([Depuração de Serviços e JOBs](https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md#depura%C3%A7%C3%A3o-de-servi%C3%A7os-jobs)

6. Inicie a depuração.

Caso os problemas persistam, anexe ao chamado (se preferir pode mandar direto param mim acandido@t...) os logs gerados (principalmente DAP), ini e console log do appServer e launcher.json.

No aguardo.

Nota: Envios diretos ao meu e-mail sem solicitação, serão ignorados.
