### ISSUE TITLE
Conectar ao monitor com broker

### ISSUE THREAD

**Issue by FelipePelissari** [totvs/tds-vscode#128]
Bom dia! Como vão?
Tenho um Broker com 5 servers da porta 1234 a 1238. existe alguma possibilidade de eu me conectar de alguma maneira que eu visualize todas as portas juntas? pois na estrutura do VS não me permite permanecer conectado na porta 1234 e ao mesmo tempo me conectar a porta 1235, dificultando a visualização dos usuários logados.

Desde já agradeço!
[2019-07-24-07-31-53.zip](https://github.com/totvs/tds-vscode/files/3426408/2019-07-24-07-31-53.zip)

**Comment by FelipePelissari** [comment]
bom dia!
Alguma ideia?

**Comment by ricardomansano** [comment]
Boa tarde @FelipePelissari ,

Infelizmente a estrutura do Broker não permite este tipo de conexão, porém já esta na fila de desenvolvimento a conexão com o AppServer Master, que ai trará todas as conexões com os Slaves.

Muito grato pela sugestão.
