### ISSUE TITLE
Como obter a Compile Key 

### ISSUE THREAD

**Issue by EmaterMG** [totvs/tds-vscode#1281]
Estou tendo problemas por não conseguir remover um fonte padrão no RPO da TOTVS utilizando VS Code

No link abaixo cita o mesmo problema
https://github.com/totvs/tds-vscode/issues/182

Cita que é necessário autorização através da chave de compilação para poder compilar Function e/ou substituir fontes do padrão.

Utilizei o atalho Ctrl-Shift-P e procurei por TOTVS:Compile Key que retornou conteúdo no camp o This Machine ID, mas o campo Compile Key ID está em Branco, como também os campos Generates,  Expire e Token.

Favor orientar como obter a chave Compile Key e como habilitar esta chave.

Desde já agradeço

Att

Adriano Dias - EMATER-MG.

**Comment by lwtnb-wrk** [comment]
@EmaterMG Por questões de segurança, alterações desse tipo, seja compilação/alteração ou a remoção de fontes padrão, exigem um token de compilação que é de uso exclusivo da TOTVS.

Entre em contato com o suporte da TOTVS para que possamos entender sua necessidade, pois remover um fonte padrão não deveria ser algo necessário.
