### ISSUE TITLE
Criar Servidor Totvs no VSCode para o Totvs 2410 - SEM SMARTCLIENT

### ISSUE THREAD

**Issue by AndRibeiroP** [totvs/tds-vscode#1282]
**Describe the bug**
Para versão Totvs 12.1.2410 o smartclient foi descontinuado, com isso não consigo configurar um novo servidor no VSCode. Como está sendo tratado esse ponto no VSCode.

*Até encontrei no site o passo a passo de como configurar o Debug WebApp porém está no pré requisito do mesmo. 
"Servidor Conectado" e neste caso, não encontrei nenhum manual ou instrução de como configurar o Servidor Totvs no VSCode sem 
 apontar a pasta Smartclient.

**Comment by brodao2** [comment]
@AndRibeiroP 

Confirme qual a versão do TDS-VScode, por favor.

**Comment by AndRibeiroP** [comment]
Appserver é o 24.3.0.1 e o TDS-VScode 1.2.1 e 1.3.23.

Log abaixo do TDS-VScode 1.2.1
[Uploading totvsls_
[totvsls.log](https://github.com/user-attachments/files/17482386/totvsls.log)
[totvsls_in.log](https://github.com/user-attachments/files/17482387/totvsls_in.log)
out.log…]()

**Comment by danielbolognani** [comment]
Para utilização da versão 12.1.2410 é obrigatório atualizar a extensão (versão 2.0.9)

**Comment by AndRibeiroP** [comment]
Funcionou Obrigado.
Só complementando a solução então atualizar os aplicativos VScode e TDS é necessário:

VScode minimo VSCodeUserSetup-x64-1.94.2
Extensão Totvs - TDS totvs.tds-vscode-2.0.9


*O que ocorreu no meu cenário específico foi que o VScode estava tambem desatualizado e sugerindo atualização da extensão apenas até o 2.0.2, após atualizar ele sugeriu a 2.0.9.
