### ISSUE TITLE
Patch Validate

### ISSUE THREAD

**Issue by charles-altoe** [totvs/tds-vscode#1285]
Boa tarde!
Ao escolher a opção Patch Apply, o botão "patch validate" não está sendo carregado.
Poderiam me auxiliar na correção deste cenario?

Desde já agradeço

Charles
![validate](https://github.com/user-attachments/assets/715f91fd-5aa5-49ee-9b08-2ed2f095236d)

**Comment by brodao2** [comment]
Duplicate https://github.com/totvs/tds-vscode/issues/1283

Pode aplicar o mesmo paliativo.

À disposição.

**Comment by charles-altoe** [comment]
Brodao2, muito obrigado!
O botão não aparece mas ao escolher o arquivo o sistema executa a validação que antes não estava ocorrendo.

**Comment by lwtnb-wrk** [comment]
versao 2.0.10 publicada no marketplace
