### ISSUE TITLE
Insufficient privileges for COMPILE - AllowApplyPatch=*

### ISSUE THREAD

**Issue by bryanfarroupilha** [totvs/tds-vscode#1286]
Ao tentar compilar está apresentando o erro: Insufficient privileges for COMPILE

No .ini do serviço a chave AllowApplyPatch está * 

![image](https://github.com/user-attachments/assets/34b5b2de-fd54-4de9-9421-3d709d1ed2f2)

Versão do TDS: v2.0.10

Esse erro aconteceu em um teste que estamos fazendo em debug com webapp.
Configuramos o servidor com URL e PORTA que usamos para acessar o WEBAPP
![image](https://github.com/user-attachments/assets/0c2d6b84-532b-40d8-854e-31d646c2d1c3)

Desta forma que vamos fazer o debug a URL fica montada corretamente. Mas não estamos conseguindo compilar.

Caso o serviço fique configurado com a porta do TCP, até da para conectar e compilar, mas quando vamos fazer um debug, a porta da URL fica incorreta pois permanece a do TCP e não do WEBAPP.

**Comment by brodao2** [comment]
@bryanfarroupilha 

A extensão TDS-VSCode usa somente a porta MPP (multi-port-protocol) ou SmartClient Desktop. 
A porta do WebApp só atende requisições destes.

O ideal é configurar com MPP e usar esta tanto para compilar como para depuração.

Lembrando que smartCLientUrl foi depreciada. Veja o CHANGE.LOG.

Caso utilize ambiente balanceado (broker), não pode ser conectar direto nele. Veja SERVERS.MD.

**Comment by lwtnb-wrk** [comment]
@bryanfarroupilha Observe que a chave "AllowApplyPatch" refere-se a "Aplicar pacotes de atualização (patchs)". Confira a documentação completa em https://github.com/totvs/tds-vscode/blob/master/docs/servers.md

O debug do Webapp não teria nenhuma relação com a compilação.

**Comment by bryanfarroupilha** [comment]
Blz. Então o que poderia estar causando o problema de "Insufficient privileges for COMPILE" ?

**Comment by lwtnb-wrk** [comment]
@bryanfarroupilha Confirme se existe alguma restrição referente a configuração de "Compilar fontes e recursos".
