### ISSUE TITLE
"Compile Error" no Outline

### ISSUE THREAD

**Issue by wrne** [totvs/tds-vscode#1287]
Bom dia!

Pessoal, de um tempo pra cá (não sei precisar a partir de qual release, a seção Outline não está conseguindo mapear a estrutura do fonte com as funções, métodos, variáveis, etc.

Antes, toda vez que o um fonte era aberto a estrutura dele era exibida. Agora é exibida a mensagem: "Compile Error The outline may be outdated. See the 'Problems View'".
Olhando a aba Problems, é relatada a falta de um include (std.ch). No fonte o Linter aponta erro no #include 'protheus.ch'. Mas isso não impede a compilação do fonte.

Acredito que o protheus.ch faça alguma referência a ele.
O problema é que este include não existe nem no pacote disponibilizado no portal (print abaixo).

Poderiam avaliar se é alguma configuração do meu ambiente que está incorreta? Acredito que não pois antes o Outline funcionava devidamente.

Isso atrapalha a experiência pois todos os fontes aparecem como se tivessem falhas e perdemos uma funcionalidade importante ao ter de separar os que de fato possuem falhas. Sem contar o Outline propriamente dito, que facilita muito na navegação de fontes maiores.

**Screenshots**
![image](https://github.com/user-attachments/assets/703f2be4-c2c1-48af-afeb-915ec736669a)

O pacote baixado hoje (04/11/24):
![image](https://github.com/user-attachments/assets/12e59da3-a050-4b75-9cf6-3046244abd6a)

**Desktop:**
 - OS/Architecture: MacOS Sequoia (mas tive o mesmo comportamento no PC com Windows 11).

**Appserver:**
AppServer - Build: 7.00.210324P-20240509
AppServer - Versão: 20.3.2.8
Versão da Lib:	 2.5.3 - 20240517
OS: Windows Server 2016 Standard

Att,

**Comment by lwtnb-wrk** [comment]
@wrne Para o Linter conseguir analisar os fontes corretamente, ele precisa de todos os includes que o fonte requer para ser compilado. 

O erro apresentado aponta para o a inexistencia do include 'std.ch' que acredito ser um include especifico de FW.

Experimente incluir na configuracao de includes, a pasta de includes do FW, para que o Linter consiga encontrar esse arquivo e não apresente mais este erro.

**Comment by wrne** [comment]
Boa tarde @lwtnb-wrk !

A pasta de includes do FW já está parametrizada.
Eu inclusive atualizei a mesma hoje com o pacote disponível no portal.

O protheus.ch é um include padrão e acredito que ele que tenha referencia ao std.ch. No pacote disponível no portal o std.ch não existe.

Att,

**Comment by lwtnb-wrk** [comment]
@wrne E ao compilar este arquivo, você não tem o mesmo problema?

Se puder, veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar, e nos envie os logs para analise.

**Comment by wrne** [comment]
Bom dia Leo!

Desculpe a demora no retorno.
Segue os logs gerados:

[totvsls_in.log](https://github.com/user-attachments/files/17716427/totvsls_in.log)
[totvsls_out.log](https://github.com/user-attachments/files/17716429/totvsls_out.log)
[totvsls.log](https://github.com/user-attachments/files/17716430/totvsls.log)

att,

**Comment by lwtnb-wrk** [comment]
@wrne Poderia gerar novos logs efetuando a compilacao do fonte? Pois nesses logs enviados nao consta nenhuma compilacao.

E so para confirmar o arquivo "std.ch" nao existe nestas pasta de includes, correto?
/Users/wanderleyneto/Projetos/CCAB/myprojects/Includes
/Users/wanderleyneto/Projetos/includes

Outro teste interessante tambem, seria comentar a 2a linha com o include "FwMVCDef.ch" para verificar se o "erro" detectado pelo Linter some apos o comentario.

**Comment by wrne** [comment]
Opa, 

Segue print com erro antes de compilar:
![image](https://github.com/user-attachments/assets/7bdfe908-615a-454a-9e4a-67ab8fd4cd63)

Print da Saida com a compilação:
![image](https://github.com/user-attachments/assets/203266d7-f24f-41fd-bee7-5052a95ea00f)

Um detalhe, que esqueci de comentar e não sei se pode interferir, meu ambiente aponta para duas pastas de include (uma padrão com o pacote disponibilizado pela Totvs e outra com defines do projeto com annotations e interfaces por exemplo).

Após comentar a linha FwMVCDef.ch, o linter acusou o "erro" imediatamente:
![image](https://github.com/user-attachments/assets/033943e6-bea5-4661-9adc-04c59f55440a)

Sobre o arquivo, ele não existe no pacote padrão. Existe um com nome parecido (stdwin.ch):
<img width="615" alt="image" src="https://github.com/user-attachments/assets/4d753f4d-a524-4833-a331-037e8b0c8619">

Os arquivos de log:
[totvsls_in.log](https://github.com/user-attachments/files/17719795/totvsls_in.log)
[totvsls_out.log](https://github.com/user-attachments/files/17719797/totvsls_out.log)
[totvsls.log](https://github.com/user-attachments/files/17719798/totvsls.log)

À disposição.

**Comment by wrne** [comment]
Bom dia!

Acessei o ambiente de outro usuário aqui (onde o Outline estava funcionando) notei que ele estava com uma versão bem desatualizada (1.3.21).

Retomei esta versão e o Outline voltou.
Segue prints:
![image](https://github.com/user-attachments/assets/675ab9ac-1b3c-48fa-8d2a-46c85e43ed6f)
![image](https://github.com/user-attachments/assets/1cd50913-bef7-439a-acca-94cc268aad4a)

Vou atualizar as versões para identificar em qual o problema apareceu, acredito que possa ajudar na análise.


Respondendo sua solicitação, segue um fonte simples de um cadastro customizado que temos, feito em tlpp e usando o tlpp-core.ch e apresentando o mesmo erro do Linter (isso na versão atual, não na antiga):
![image](https://github.com/user-attachments/assets/f3091668-28a3-4904-9ce4-96c8b65e1a9a)

Logo retomo com a versão que começou a ocorrer o problema.

Att,

**Comment by wrne** [comment]
> @wrne Experimente tambem alterar as pastas de includes, deixando apenas a ultima oficial do Portal, pois nao consigo reproduzir a falta deste "std.ch".

Mesma coisa... =/

**Comment by wrne** [comment]
@lwtnb-wrk ,

Testei a versão atual em outra máquina (SO Windows 11) e ocorreu o mesmo problema. Não sei o que pode ser mas não é específico da minha máquina.

Testei as versões:

2.0.2 - OK
![image](https://github.com/user-attachments/assets/455ae2ce-287b-4188-864c-3d3e7b307e6e)

2.0.3 - Já não aparece a estrutura, mas não tem msg de erro:
![image](https://github.com/user-attachments/assets/73d187c7-6b94-41fa-ae14-58d86df2a2c7)


Será que ajuda?

Att,

**Comment by lwtnb-wrk** [comment]
@wrne Mas nesta outra estação você abriu o mesmo workspace e usou os mesmos includes?

Se puder nos enviar os arquivos e includes, tentaremos reproduzir o problema aqui, mas sem esses arquivos aqui eu não tenho mais o que fazer.

**Comment by wrne** [comment]
Isso, mesmo ambiente. Compartilhamos o mesmo repositório/ appserver/ pastas de includes são copias da mesma origem.
A única diferença é que eu estou no MacOs e ele no Windows.

Segue a pasta de includes custom:
[Includes_custom.zip](https://github.com/user-attachments/files/17737119/Includes_custom.zip)

A pasta de includes é a do portal:
[24-05-10-P12_INCLUDES.ZIP](https://github.com/user-attachments/files/17737144/24-05-10-P12_INCLUDES.ZIP)

**Comment by lwtnb-wrk** [comment]
@wrne Usei os includes acima fornecidos e o Outline foi montando sem problemas, inclusive alertando sobre os problema detectados pelo Linter.

![image](https://github.com/user-attachments/assets/e8d954f2-2ffb-46d9-add2-bed2537f7e10)

**Comment by wrne** [comment]
Bom dia!

@lwtnb-wrk, acha que é possível identificar a causa analisando a diferença entre as versões? Desde a semana passada, estou usando a versão 2.0.2 e não tem apresentado o problema.
Não sei mais o que pode influenciar para te informar.

Att,

**Comment by lwtnb-wrk** [comment]
@wrne Mas antes de começar este problema, você estava com uma versão desatualizada do tds-vscode? 
Quando o problema começou? Após alguma atualização?

**Comment by wrne** [comment]
Não, sempre mantive a extensão atualizada. Por isso não consigo precisar em qual momento parou de funcionar.

Esta semana, depois da abertura da Issue, voltei as versões para tentar identificar até onde funcionava. Identifiquei que a 2.0.2 foi a última. A partir dela o Outline ficava em branco (sem a mensagem de erro, mas também sem a informação da estrutura do fonte).

**Comment by lwtnb-wrk** [comment]
@wrne Então mesmo com a extensão atualizada, ela funcionava e parou após alguma alteração no ambiente, certo?
Seja de workspace de trabalho, includes ou ambas?

Eu não consigo reproduzir e determinar qual o problema.
Consegue abrir um workspace vazio e realizar novos testes?

**Comment by wrne** [comment]
Ah não, desculpe, não foi isso que tinha entendido...

Ela parou de funcionar faz bastante tempo, em uma versão já antiga. Eu que demorei pra abrir a Issue...
Não consigo associar a nada no meu ambiente. Esses includes são antigos já.

Posso tentar fazer com uma workspace vazia sim. Em breve retorno com o resultado

Att,

**Comment by rodrigopg** [comment]
Boa tarde!!

@lwtnb-wrk A issue foi fechada, mas não vi se houve a correção!
Eu continuo com o mesmo problema relatado pelo @wrne.

**Comment by brodao2** [comment]
@rodrigopg 

Esse erro ocorre pois seu programa contém erro de compilação.
Force uma compilação (F9 no fonte em edição) e ajuste o código se necessário.
Caso continue com problemas, abra um chamado conforme

**Comment by wrne** [comment]
> [@rodrigopg](https://github.com/rodrigopg)
> 
> Esse erro ocorre pois seu programa contém erro de compilação. Force uma compilação (F9 no fonte em edição) e ajuste o código se necessário. Caso continue com problemas, abra um chamado conforme conforme [Informações importantes ao abrir o chamado](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#informa%C3%A7%C3%B5es-importantes-ao-abrir-uma-issue) e anexe os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)
> 
> À disposição.

Bom dia Alan! não é este o caso, não foi identificado nada no fonte que justifique (até pq no meu caso é geral, para todos os fontes). Testamos com programas bem simples, validado inclusive pelo @lwtnb-wrk (Na maquina dele funcionou). O problema é que não conseguimos identificar a causa e nem reproduzir no ambiente de vocês.

A thread foi encerrada pois parei de retornar (desculpem por isso). 
@rodrigopg , estou usando a versão 2.0.11, onde o Outline está funcionando. Se quiser reabrir o chamado posso contirbuir com os testes já realizados.

Att,

**Comment by wrne** [comment]
> E como o [@wrne](https://github.com/wrne) relatou, nessa última versão parece tudo certo agora.

Pessoal, desculpe, me confundi na informação da versão. A que estou usando é antiga, a correta é a 1.3.23.
Olhei rápido no "Extensions" e informei a Latest..

Na 2.0.11 o problema com o Outline persiste...

Att e desculpe o engano,

**Comment by rodrigopg** [comment]
De fato o problema consiste. Já preparei um ambiente para testar com tudo do zero, e mesmo assim não resolveu. O último teste foi compilar toda a extensão a partir do código fonte, mas sem sucesso. Estou a disposição para demais informações.
Acredito que o problema está no LS mesmo.
