### ISSUE TITLE
Montagem de URL no Debug - https://https//..........

### ISSUE THREAD

**Issue by bryanfarroupilha** [totvs/tds-vscode#1288]
![image](https://github.com/user-attachments/assets/87b0a591-8e62-4c60-866c-ceefd1a3feb6)

Ao iniciar Debug, URL está sendo montada da seguinte forma: https://https//..........

Configuração do servidor está ok
![image](https://github.com/user-attachments/assets/66195751-9bcb-4358-95bc-1493f7ab3a8e)

**Comment by lwtnb-wrk** [comment]
@bryanfarroupilha Somente para confirmar, voce cadastrou este AppServer usando o endereço (IP) como https://protheushml.xxx correto?
É um não muito usual mas modo possível, então vamos ajustar para levar esse cenário em consideração.
Por enquanto se recadastrar ou criar um novo AppServer com o endereço (IP) apontando para o servidor "protheushml.xxx" sem usar o "https://" o processo deve funcionar como o esperado.

**Comment by BryanBSantana** [comment]
@lwtnb-wrk 
Usando IP e a porta TCP conseguimos conectar. Mas usando a porta MPP não passa.
Talvez seja devido o certificado SSL do ambiente.

**Comment by lwtnb-wrk** [comment]
@BryanBSantana Na verdade o problema esta na montagem automática da URL webapp que o debug usa caso o parâmetro smartclientUrl nao seja informado.
Na versão 2.0.10 ao remover este parâmetro o tds-vscode monta a URL, mas não consideramos este cenário onde o AppServer é cadastrado como URL https://hostname 
Se informar o parâmetro smartclientUrl com o endereço webapp, ele vai usar diretamente e deve funcionar normalmente também.

**Comment by bryanfarroupilha** [comment]
Esse detalhe será ajustado nas próximas versões?

**Comment by lwtnb-wrk** [comment]
@bryanfarroupilha Publicamos uma correção que deve resolver o problema.
