### ISSUE TITLE
Erro na compilação de pacote com rdmakes enviados: not allowed more than one source with same name. Rename your source

### ISSUE THREAD

**Issue by fabiolaleitao** [totvs/tds-vscode#1289]
Olá pessoal, 

Peço que me ajudem, pois recebi um pacote de vários fontes com orientação da Totvs para compilar em nosso ambiente, mas diversos fontes tem apresentado o seguinte erro: not allowed more than one source with same name. Rename your source.
Como proceder neste caso?

Atte.
Fabíola

**Comment by lwtnb-wrk** [comment]
@fabiolaleitao Vocês estao tentando compilar fontes ou aplicar um patch??

E para confirmar a questão de nome duplicado, abra o inspetor de objetos e verifique se já existe um fonte com o mesmo nome.

Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analises.

**Comment by fabiolaleitao** [comment]
Obrigada pelo retorno!

Não é aplicar patch mas sim, compilar fontes de RDMAKES e REPORT que a Totvs enviou e pediu para aplicarmos compilando e gerando o ptm para aplicar em nosso ambiente.
Já verifiquei, e de fato, os fontes já existem no RPO. porém não consigo compilar em cima e ocorre o referido erro.

Atte.
Fabíola

**Comment by lwtnb-wrk** [comment]
@fabiolaleitao Entre em contato com que enviou os fontes para orientacao, pois se os fontes ja existem, eles nao podem ser sobrescritos sem a devida autorizacao (token de compilacao). 
Ou verifique se quem mandou os fontes pode gerar o patch para que voce apenas aplique e nao tenha esse problema.

**Comment by fabiolaleitao** [comment]
Ok @lwtnb-wrk , muito obrigada!
