### ISSUE TITLE
Limpar logs no OutPut Advpl antes de Compilar

### ISSUE THREAD

**Issue by alexandreandradeg** [totvs/tds-vscode#129]
Boa tarde, é possível limpar os logs no OutPut do Advpl, automaticamente antes de iniciar a compilação?

**Comment by DanielYampolschi** [comment]
Ola @alexandreandradeg Vamos analisar, obrigado pela sugestao, porém, lembrando que esse é um projeto colaborativo, caso queira, voce mesmo pode implementar essa funcionalidade e submeter um pullrequest, contribuindo para a ferramenta. Muito obrigado novamente.

**Comment by brodao** [comment]
FIX #158
