### ISSUE TITLE
Debug na Release 2410

### ISSUE THREAD

**Issue by ivantore** [totvs/tds-vscode#1291]
Boa tarde,

Agora com a release 2410 não tendo um smartclient como realizaremos o debug dos programas, qual patch apontaremos no launch.json?

No aguardo.

Grato,
Ivan

**Comment by brodao2** [comment]
@ivantore 

Defina um executor do tipo [TOTVS_LANGUAGE_WEB](https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md#totvs-language-web-debug-html).

À disposição.
