### ISSUE TITLE
Debug de REST na release 12.1.2410 não para no breakpoint

### ISSUE THREAD

**Issue by eldertrevisan** [totvs/tds-vscode#1292]
Olá! Recentemente atualizamos nosso Protheus para a release 12.1.2410 e estou com problemas para debugar serviços REST pois simplesmente não para em nenhum Breakpoint. Já configurei o debug HTML, apontei o caminho do navegador, a função startRest está compilada (já usava muito antes da atualização). Enfim, segui tudo conforme o que manda no docs/debugger.md. Quando clico no botão de debug, abre o navegador normalmente e é exibido o alert da função startRest. Só um detalhe que na parte de [Preparação para serviços REST](https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md#prepara%C3%A7%C3%A3o-para-servi%C3%A7os-rest) no item 1 vocês recomendam comentar a sessão [OnStart], porém se fizer isso, aí que não funciona mesmo, pois ao tentar enviar uma requisição via Postman dá o erro "Error: connect ECONNREFUSED", ou seja, nem chega a fazer requisição para o servidor.

**Comment by lwtnb-wrk** [comment]
@eldertrevisan Somente da confirmar a questao de remover o [OnStart], a thread de debug precisa iniciar antes da thread que será depurada e por isso o serviço REST não pode iniciar automaticamente. Após o inicio da depuração o REST deve ser inicializado via "startJob" conforme sugestão dada na "Preparação para serviços REST". Então somente após iniciar a debug de thread em seguida iniciar a thread do REST o postman está sendo chamado para consumir o REST? 

No console.log do AppServer não ocorre nenhum erro durante a subida do REST? 

De qualquer forma, veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie o DAP.log para analise, e se possivel o console.log do AppServer.

**Comment by eldertrevisan** [comment]
@lwtnb-wrk sobre o debug, consegui resolver. Era a chave "enableMultiThread" que estava faltando. Por algum motivo eu tinha lido a chave "enableTableSync" e na minha cabeça era o enableMultiThread rsrsrs.


Sobre o [OnStart], gerei os logs e estou enviando aqui.

[dap.log](https://github.com/user-attachments/files/17708414/dap.log)
[totvsls.log](https://github.com/user-attachments/files/17708416/totvsls.log)
[totvsls_in.log](https://github.com/user-attachments/files/17708417/totvsls_in.log)
[totvsls_out.log](https://github.com/user-attachments/files/17708418/totvsls_out.log)
