### ISSUE TITLE
@RegisNJr Pela sua informação notamos que apos o -I não está sendo enviado o Include necessario...

### ISSUE THREAD

**Issue by sandroalves1971** [totvs/tds-vscode#1293]
Referente a https://github.com/totvs/tds-vscode/issues/440#issuecomment-656794667

ao Issue fechada https://github.com/totvs/tds-vscode/issues/440

Estou com problema na versão v2.0.11 com VSCode 1.95.2

esse problema voltou para mim.

**Comment by lwtnb-wrk** [comment]
@sandroalves1971 Temos relatos de desconfiguração da pasta de includes apos atualizacao do VS Code para a 1.95, verifique se as pastas de includes estao configuradas corretamente. 
Durante a compilação tambem exibimos as informacoes de que includes estao sendo considerado entao verifique no Output durante a compilação para ver se os Includes estao corretos;

Caso esteja tudo em ordem com os includes, veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise

**Comment by sandroalves1971** [comment]
Obrigado @lwtnb-wrk 
Encontrei o problema, não estava declarada o include nas configurações globais

{
"version": "0.2.0",
"includes": [
"D:\TOTVS\Protheus\Protheus\include"
],
"permissions": {
"authorizationtoken": ""
},
