### ISSUE TITLE
Autenticação Servers - Gerenciamento Centralizado de Credenciais no VSCode

### ISSUE THREAD

**Issue by bryanfarroupilha** [totvs/tds-vscode#1298]
Atualmente, é necessário autenticar com usuário e senha separadamente para cada Server/Environment configurado no VSCode. Quando a senha do usuário é alterada no sistema, é preciso atualizar manualmente as credenciais em todos os Server/Environments, mesmo quando o mesmo usuário é utilizado em vários deles.

Sugere-se implementar uma funcionalidade que permita centralizar o gerenciamento de credenciais. O objetivo é que o usuário precise informar apenas o nome de usuário para cada Server/Environment, enquanto as credenciais (incluindo a senha) possam ser cadastradas e gerenciadas em um único local. Essa abordagem facilitará e agilizará a atualização de senhas quando necessário, reduzindo retrabalho e otimizando a experiência do usuário.

**Comment by lwtnb-wrk** [comment]
@bryanfarroupilha Cada environment pode apontar para um banco de dados/RPO diferentes logo os usuários e as senhas podem ser diferentes para cada combinação de Server/Environment. 
Além disso o uso de mesmo usuário/senha em múltiplos environments não é recomendado, pois em caso de vazamento em um ambiente, todos os outros estarão comprometidos.
A troca de senha periódica é uma boa prática de segurança, porém não é algo que fazemos com uma frequência tão alta para justificar esta melhoria.
De qualquer forma agradecemos a sugestão, e se tiver outras, nos avise que avaliaremos, pois sempre queremos ouvir as ideias de quem usa diariamente o produto.
Abraço.

**Comment by bryanfarroupilha** [comment]
- Cada environment pode apontar para um banco de dados/RPO diferentes logo os usuários e as senhas podem ser diferentes para cada combinação de Server/Environment.
**Resposta:** Em um ambiente onde uso autenticação pelo AD, a senha é a mesma. Até porque em caso de vazamento, uma ação no meu usuário no AD já bloqueia todos os acessos. 

- A troca de senha periódica é uma boa prática de segurança, porém não é algo que fazemos com uma frequência tão alta para justificar esta melhoria.
**Resposta:** Trocamos a senha à cada 45 dias. Então a cada 45 dias tenho que trocar 24 Servers onde alguns tem quase 10 Environment.
![image](https://github.com/user-attachments/assets/6fa39ce3-2f88-4b68-b07f-be9dd610e65a)


Exemplo de uso:
Supondo que tenho 20 server cadastrado. 10 são autenticados com o usuário A, 3 são com o usuário B e 7 com o usuário C.
Então eu teria um Cadastro Centralizado de Credenciais com 3 usuários. E nos 20 servers cadastrados, eu informo somente qual é o usuário relacionado. Quando mudar a senha, eu altero somente no Cadastro Centralizado de Credenciais.

**Comment by danielbolognani** [comment]
Bom dia Bryan, esse é um dos motivos de a nossa extensão ser de código aberto!

Fique a vontade para ajustar o código a sua necessidade e se achar válido pode subir sua alteração que analisaremos para incorporar ao produto padrão.

Abraços!
