### ISSUE TITLE
Function GetAutoGRLog não aparece no console

### ISSUE THREAD

**Issue by maximinocastro** [totvs/tds-vscode#1299]
Boa tarde Pessoal
Tudo bem?

Hoje estou fazendo um teste utilizando rotina com execauto padrão e custom porém simplesmente só funciona se atribuido em uma variavel e se tentar chamar novamente no console simplemente não tem mais a informação é como se as informações que estão na CACHE do GetAutoGRLog simplesmente apagasse e mesmo parando o break point no GetAutoGRLog ele não traz no console .

**Evidência:**

<img width="703" alt="image" src="https://github.com/user-attachments/assets/033f10d0-17ee-407f-b60f-259f0b97f2ff">

**Versão da Lib:**	
2.5.3 - 20240517
Desatualizado
Commit ID:	
620c7270a68dbc730c507c728072bf926da2f4d0

**AppServer - Build:**	
7.00.210324P-20240902
Atualizado
AppServer - Versão:	
20.3.2.14
Porta Conexão:	
5001

**Ambiente:**	
DESENVOLVIMENTO
Release do RPO:	
12.1.2310
Release do dicionário:	
12.1.2310
Dicionário:	
Dicionário no Banco
Local files:	
CTREE

**DBAccess:**
DBAccess 4.2 Server Started - Build 20240224-20241002 - STANDALONE MultiDB Version - Windows [RELEASE] [SMARTHEAP] Version 11.6.1 [X86_64] - Version 24.1.0.0

**Sistema Operaciona** - Windows 11 Professional

**Comment by brodao2** [comment]
@maximinocastro 

O console de depuração apresenta o conteúdo da variável não fazendo nenhum tratamento especifico.
Experimente colocar um varInfo de aLog para ver se há alguma coisa a mais.
E nos envie o log do DAP, conforme [Gerando Logs](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs) e do server.

No aguardo.

**Comment by danielbolognani** [comment]
O TDS-VSCode não faz tratamento nem execução de ADVPL/TLPP, apenas traz os valores das variáveis e comandos do backend (appserver). Se teve alguma alteração nesse sentido, pode ser algo no RPO (o mais provável) ou no appserver.
Vale tentar atualizar o ambiente com os últimos binários e RPOs disponíveis.

**Comment by maximinocastro** [comment]
AppServer e RPO já estão atualizado. 

Só LIB que está desatualizado.

Segue em anexo os arquivos solicitados.


[totvsls_out.log](https://github.com/user-attachments/files/17984090/totvsls_out.log)
[console.log](https://github.com/user-attachments/files/17984091/console.log)
[dap.log](https://github.com/user-attachments/files/17984092/dap.log)
[totvsls.log](https://github.com/user-attachments/files/17984088/totvsls.log)
[totvsls_in.log](https://github.com/user-attachments/files/17984089/totvsls_in.log)

Colocando VARINFO na variavel aLOG apresenta erro
<img width="489" alt="image" src="https://github.com/user-attachments/assets/36f3e763-aa0f-4f51-9ce7-00cf2fec81eb">

Após VarInfo console da variavel 
<img width="414" alt="image" src="https://github.com/user-attachments/assets/ac4b9e12-1516-4639-86d7-5c0b35e7b4a3">

**Comment by brodao2** [comment]
@maximinocastro 

Analisei os logs enviados e o mesmo indica que executou como esperado.

Quanto ao erro de varInfo, você chamou-a dessa forma: `conout(varinfo("string explicativa", aLog))`?
Isso deve ser feito dentro do seu código, logo após a chamada GetAutoGRLog.
Com isso, o conteúdo de aLog será apresentado no console log do Protheus.
Se não for o mesmo obtido no console de depuração, anexe o console log do protheus a esse chamado, para nova análise.

Quanto ao comportamento da função, recomendo que entre contato com o suporte AdvPL/FW para mais informações.

No aguardo.

**Comment by maximinocastro** [comment]
@brodao2 bom dia, já que o problema é com o FRAME, vou encerrar o chamado e vou abrir o chamado no FRAME.
