### ISSUE TITLE
Debug EAI

### ISSUE THREAD

**Issue by WilliamsPrado** [totvs/tds-vscode#13]
Boa tarde prezados,

Configurei o visual code conforme os videos feitos pelo Ricardo Mansano 

https://www.youtube.com/watch?v=MwIu01Ztfvg
https://www.youtube.com/watch?v=Cz4N0XWCXHY

E o debug ocorre normalmente para uma rotinas de contas a receber. Mas quando tento debugar via recebimento de mensagem, especificamente no FINI070LST.prw ele simplesmente não é efetivo.

Mas via TDS o debug é realizado com sucesso.

gostaria de entender onde estou errando.

Obrigado.
contato: william.prado@totvs.com.br
              williamsprado@gmail.com

**Comment by DanielYampolschi** [comment]
Ola @WilliamsPrado, o que voce quer dizer com "simplesmente não é efetivo"? 
Informe o máximo de detalhes possivel sobre o problema que voce esta no debug por favor.

**Comment by WilliamsPrado** [comment]
O debug não funciona. ( não é efetivo )

**Comment by DanielYampolschi** [comment]
William, como conversamos, e pelo que você me mostrou, parece ser um problema se depuração com processo de webservice, onde uma o debug não para em uma função chamada pelo webservice.
Agradeço bastante a observação, e já adicionei n roadmap para corrigirmos o mais rápido possível.

**Comment by brodao** [comment]
Foi verificado se a depuração multi-thread esta ligada?

**Comment by ricardomansano** [comment]
@WilliamsPrado , boa tarde, conforme o @brodao comentou: Vc pode verificar se o debug mult-thread esta ligado? pra confirmar veja na launcher.json de sua pasta .vscode se a tag a seguir esta "enableMultiThread": true, abaixo um modelo completo do json:

{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_web_debug",
			"request": "launch",
			"name": "Totvs Language Web Debug (SmartClient HTML)",
			"program": "${command:AskForProgramName}",
			"isMultiSession": true,
			"smartclientUrl": "http://localhost:8017"
		},
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Totvs Language Debug",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "/home/mansano/_c/totvs12/bin/smartclient/smartclient",
			"enableMultiThread": false,
			"enableProfile": false,
			"isMultiSession": false,
			"isAccessibilityMode": false,
			"doNotShowSplash": false,
			"language": "",
			"ignoreFiles": true
		}
	],
	"lastProgramExecuted": "tabTest"
}

**Comment by WilliamsPrado** [comment]
Boa tarde Ricardo, 
segue o arquivo launcher.json.   ( caso, deseja verificar, posso compartilhar a tela contigo. william.prado@totvs.com.br)

Desde já agradeço

{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Wrp",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "C:\\agua\\bin\\smartclient\\SmartClient.exe",
			"isMultiSession": true,
			"enableMultiThread": true
		},
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Totvs Language Debug",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "C:\\agua\\bin\\smartclient\\SmartClient.exe",
			"enableMultiThread": true,
			"enableProfile": false,
			"isMultiSession": false,
			"isAccessibilityMode": false,
			"doNotShowSplash": false,
			"language": "",
			"ignoreFiles": true
		}
	],
	"lastProgramExecuted": "SIGAFIN"
}

**Comment by ricardomansano** [comment]
@WilliamsPrado , não precisa, fica tranquilo, agora com seu json fica mais facil da gente testar, pespondemos assim que possível, grato pelo retorno.

**Comment by DanielYampolschi** [comment]
Ola @WilliamsPrado , Voce poderia atualizar seu plugin do tds-vscode por favor e informar se o problema ainda ocorre? Obrigado.

**Comment by ricardomansano** [comment]
Encerrado por falta de retorno, continuamos a disposição.

**Comment by WilliamsPrado** [comment]
Bom dia Pessoal,

Após atualizar e modificar launcher.json tive sucesso.
Desculpe pela demora no retorno.

Obrigado pessoal
