### ISSUE TITLE
Problema no Syntax Highlight para o BeginSQL

### ISSUE THREAD

**Issue by LeonardoRios** [totvs/tds-vscode#130]
Olá, 

Aparentemente o Syntax HighLight para o BeginSQL está com problema, porque só diferencia o "FROM"
![Print](https://user-images.githubusercontent.com/6351312/61901455-2fe16800-aef6-11e9-8510-6659edd11366.png)

**Comment by caiadofelipe** [comment]
@LeonardoRios , já foi feita a alteração. Na próxima release será liberada.

**Comment by DanielYampolschi** [comment]
Correção liberada na versão 0.3.13
