### ISSUE TITLE
Idioma definido como inglês ao ativar debug direto em função

### ISSUE THREAD

**Issue by tembra** [totvs/tds-vscode#1300]
Estou desenvolvendo uma função TLPP e executando a mesma diretamente através do debug com o objetivo de testar sua funcionalidade rapidamente, pois a mesma não precisa do ambiente Protheus inicializado para funcionar. Entretanto na execução constatei que o idioma utilizado pelo debug é o inglês, pois as datas estão sendo interpretadas como `mm/dd/yyyy`.

Tentei modificar o atributo `language` dentro do `configurations` no `launch.json` do vscode. O mesmo está definido como `1`. Testei valores de `0` a `3` sem obter sucesso na mudança do idioma.

Verifiquei ainda o idioma definido no arquivo `language.ini` do smartclient que está sendo utilizado no debug (`smartclientBin` dentro do `launch.json`) e lá, pra todos os ambientes, inclusive o que estou utilizando para debugar, a chave `currentlanguage` está configurada como `pt-br`.

Segue abaixo um exemplo de código onde é possível reproduzir o cenário:
```advpl
#include 'tlpp-core.th'
#include 'totvs.ch'

namespace misc

User Function Teste()
    Local dDateEn := CTOD('12/31/2024') as Date
    Local dDatePtBr := CTOD('31/12/2024') as Date
    Local cText as Character

    cText := ''
    cText += 'Mês EN: >>' + CMonth(dDateEn) + '<<' // December
    cText += CRLF
    cText += 'Mês PT-BR: >>' + CMonth(dDatePtBr) + '<<' // Vazio

    Alert(cText)
    
Return Nil
```

Para executar a função basta executar o debug (F5) informando o programa `misc.u_Teste`.

---

> [!NOTE]
> **ATUALIZAÇÃO:**
> Refiz o teste utilizando um programa em ADVPL (PRW) e o comportamento foi o mesmo. Ou seja, não trata-se de algo específico do TLPP.

---

**VSCode version:** 1.95.3
**tds-vscode version:** v2.0.11
**Appserver version:** 20.3.2.5
**Remote version:** 20.3.2.2
**Remote type:** 1
**Remote Arquitetura:** x86_64 - QT-6.2.6 WIN
**Remote OS:** Windows 11
**Versão da Lib:** 20240812
**Release do RPO:** 12.1.2310

**Comment by brodao2** [comment]
@tembra 

Como não passa pelos procedimentos de inicialização do Protheus, o argumento `language` passado no depurador pode estar sendo ignorado.

Verifique junto ao suporte AdvPL/FW se é possível você ajustar o idioma sem a inicialização padrão ou mesmo como você fazer uma inicialização/configuração mínima.

Um tentativa seria com o comando `prepare environment' ou forçar com `set date to`.

À disposição.

**Comment by brodao2** [comment]
@tembra 

Em complemento a mensagem anterior, a configuração `language` é do ambiente Protheus. O depurador apenas repassa.

À disposição

**Comment by tembra** [comment]
@brodao2

Agradeço pelas informações! Compreendi perfeitamente o funcionamento.

Eu já estava em busca de uma função pra definir o formato da data, imaginando que poderia funcionar. O `set date to` informado resolveu.

Entretanto eu preferi usar a função direta em vez do comando/alias: `Set(_SET_DATEFORMAT, 'dd/mm/yyyy')`.

Agradeço o rápido retorno.
