### ISSUE TITLE
Bug "Parameter WebNavigator not informed"

### ISSUE THREAD

**Issue by devjuliusotto** [totvs/tds-vscode#1301]
Prezados, boa tarde!

Sou funcionário da Totvs SC e estou enfrentando o seguinte problema ao rodar uma aplicação ADVPL no Vscode:

"Parameter WebNavigator not informed."

Entretanto, eu defini sim o meu navegador nas settings (img em anexo).
![image](https://github.com/user-attachments/assets/d10009ec-329a-4555-a2f8-c054101fe23d)
Saberiam oq mais poderia ser esse erro?

Aqui vocês podem achar o script que menciona o erro "Parameter WebNavigator not informed".

https://github.com/totvs/tds-vscode/blob/master/src/debug/TotvsConfigurationWebProvider.ts

Meu launch.json está do jeito q mandei na imagem anexa.
![image](https://github.com/user-attachments/assets/efe338c2-875d-4444-b77d-744c5193666b)

Já tentei inserir no launch.json o campo "webnavigator" mas tbm, sem sucesso.

Abs,
Julius

**Comment by brodao2** [comment]
@devjuliusotto 

Você informou no local errado. O correto é em `totvsLanguageServer.web.navigator` e não em `totvsLanguageServer.web.arguments`.

![image](https://github.com/user-attachments/assets/c81c3155-481f-43df-a8b9-d1a1d25c92f4)
