### ISSUE TITLE
Opção de compilação em mais de um ambiente 

### ISSUE THREAD

**Issue by alanFaccin** [totvs/tds-vscode#131]
O recurso multi ambientes do TDS está disponível no Vs ?

https://uploaddeimagens.com.br/imagens/multi_ambientes_-jpg

**Comment by ricardomansano** [comment]
Boa tarde @alanFaccin ,

Após analisar a opção de compilação em múltiplos ambientes julgamos o processo arriscado, principalmente se houver ambientes de produção e desenvolvimento conectados ao mesmo tempo.

Agradecemos muito sua sugestão mas ela não será endereçada no momento, mesmo que já exista no no TDS-Eclipse.
