### ISSUE TITLE
Debug não inicia

### ISSUE THREAD

**Issue by jcstorino** [totvs/tds-vscode#133]
Bom dia a todos..

Não estou conseguindo lançar o debug no VSC, estou usando windows 10 e a última versão do VSC e da extensão, meu lauch.json parece estar correto, o que pode ser ?

Clico no debug, informo o programa inicial SIGAADV e nada acontece, fica só mostrando a barra do debug mas o smartclient não abre...

**Comment by DanielYampolschi** [comment]
Ola @jcstorino , preciso de um favor e te fazer umas perguntas:

Você pode enviar o seu launch.json aqui para verificarmos se está tudo correto por favor?
Confirme também por favor, se você está com a versão 0.3.12 do plugin TDS VsCode instalado.

Qual a build do servidor que você está tentando conectar?

Você está tentando depurar em um servidor na sua máquina ou remoto? Se for remoto é um servidor de produção?

Isso sempre acontece? Já tentou reiniciar o servidor quando isso acontece? Dependendo da situação, caso tenha ocorrido um erro anteriormente por exemplo, pode ficar alguma "thread" presa no servidor o que requer uma reinicialização.

Obrigado.

**Comment by ricardomansano** [comment]
Boa tarde @jcstorino, 
Problema não reproduzido na versão 0.3.15, por gentileza atualize e refaça os testes.

**Comment by AndersonDavyd** [comment]
Estou com o mesmo problema :(

**Comment by lwtnb-wrk** [comment]
@AndersonDavyd veja esta issue: https://github.com/totvs/tds-vscode/issues/308
Se não resolver abra uma nova Issue com o maximo de detalhes possiveis.
