### ISSUE TITLE
Qual a versão do VsCode é compatível com esta Extensão?

### ISSUE THREAD

**Issue by cicerocruz** [totvs/tds-vscode#134]
Olá, após o VsCode se atualizar a extensão parou de  conectar nos  server's tanto remoto quando local... desabilitei o AutoUpdate, fiz o Downgrade do VsCode  e instalei a extensão novamente ai  funcionou perfeitamente..

Qual a  ultima  versão do VsCode que não apresenta problemas de conexão (local/remoto)?

**Comment by lwtnb-wrk** [comment]
a principio o plugin deveria funcionar sem problemas apos a atualizacao do vscode...
apresentava algum tipo de erro no console?

**Comment by cicerocruz** [comment]
Pelo que  pude avaliar conecta mas não compila... testamos inclusive em outra maquinas depois do downgrade do vscode voltou a funcionar...

**Comment by cicerocruz** [comment]
Não apresenta nenhuma mensagem no console...

**Comment by DanielYampolschi** [comment]
@cicerocruz Essa é uma situação realmente estranha, e não conseguimos reproduzir de forma alguma. 
No inicio da semana que vem vamos liberar uma versão nova. 
Te peço para por favor, ficar atento para essa liberação e testar novamente. 

Muito obrigado.

**Comment by lwtnb-wrk** [comment]
@cicerocruz Voce ainda esta tendo problemas com o plugin?
Aqui atualizei inclusive para a ultima versao do VS Code 1.38.0 e aparentemente está tudo funcionando.
