### ISSUE TITLE
'$totvsserver/compilation - (8149)

### ISSUE THREAD

**Issue by cicerocruz** [totvs/tds-vscode#135]
Olá quando compilo tenho como retorno isso:

[Info  - 00:56:42] Compilation started
[Trace - 00:56:42] Received notification 'window/logMessage'.
[Info  - 00:56:42] Starting compile.
[Trace - 00:56:42] Received notification 'window/showMessage'.
[Trace - 00:56:42] Received notification 'window/logMessage'.
[Info  - 00:56:42] Starting build for environment PRODUCAO.
[Trace - 00:56:42] Received notification 'window/showMessage'.
[Trace - 00:56:42] Received notification 'window/logMessage'.
[Error - 00:56:42] Start build error: Start build failed.
[Trace - 00:56:42] Received notification 'window/showMessage'.
[Trace - 00:56:42] Received response '$totvsserver/compilation - (8149)' in 40ms.
[Trace - 00:56:48] Sending notification '$advpl/textDocumentDidView'.
[Trace - 00:56:48] Sending notification '$advpl/textDocumentDidView'.
[Trace - 00:56:48] Sending notification '$advpl/textDocumentDidView'.

Acho que o codigo de erro é 8149 correto?

**Comment by DanielYampolschi** [comment]
Ola @cicerocruz , esse erro aconteceu uma vez ou é algo frequente? Você consegue informar um processo que o reproduz? 
Pelo que investiguei no Language Server esse erro pode ocorrer quando o servidor não é inciado, talvez você esteja tentando compilar antes do servidor se conectar? Ou Talvez ele tenha perdido a conexão? 
Vamos tentar colocar uma proteção com um erro mais explicativo, mas a situação deve ocorrer pelo informado acima.

**Comment by cicerocruz** [comment]
@DanielYampolschi  O Servidor realmente não estava inicializado... seria  legal postarem uma lista dos códigos de erro... assim ficaria mais fácil nos orientarmos...

**Comment by DanielYampolschi** [comment]
@cicerocruz Obrigado pela sugestão. Já estamos analisando a melhor forma de adicionar e documentar códigos de erros, porém sem previsão ainda de quando teremos isso.

A mensagem de erro apresentada já foi alterada, informando que o servidor pode estar offline, e estará disponível na próxima liberação.

De qualquer forma, apenas uma observação. O número 8149 não é um código de erro, repare que ele está informado na linha de "trace" da mensagem de comunicação com o LanguageServer. Esse tipo de mensagem pode ser ligado ou desligado nas preferencias do VsCode e esse número é apenas uma referência interna.
