### ISSUE TITLE
Tela de erro ao debugar no vsCode

### ISSUE THREAD

**Issue by marjorietaki** [totvs/tds-vscode#137]
Ao tentar debugar no VsCode é apresentado uma tela de erro.
Notei também que não esta mais aparecendo as informações na parte de variáveis.

**Comment by danielbolognani** [comment]
O problema gera um core.dmp que eu j analisei e abri um chamado para o time do AppServer (chamado TTEC-3302), assim que esse chamado for concluído informo qual versão terá esse problema resolvido.

**Comment by le0zz** [comment]
@danielbolognani Alguma previsão de correção? Notei que esse erro passou a ocorrer somente após a atualização do VSCode para a versão 1.37.1, mas não sei se é possível fazer downgrade...

**Comment by le0zz** [comment]
Segue infos do appserver utilizado onde é reproduzido o erro:

![image](https://user-images.githubusercontent.com/37678190/63175808-29d53780-c01b-11e9-9067-cbde39c0c486.png)

RPO: D-1 (20190816)
SmartCliente: Último x64 disponível para download no portal do cliente

**Comment by danielbolognani** [comment]
@le0zz Para termos certeza que se trata do mesmo erro precisaríamos fazer uns testes, pode me chamar pelo hangout (daniel.bolognani)?
Se for realmente o mesmo problema, a solução está na sprint atual do time do AppServer, acredito que em no máximo 15 dias uma versão preliminar já esteja disponível.

**Comment by danielbolognani** [comment]
Com a versão 0.3.15 disponibilizada do plugin, essa situação foi protegida e pode ligar novamente a Sincronização de tabelas
