### ISSUE TITLE
Monitorar variáveis através de arrasta e solta

### ISSUE THREAD

**Issue by cfasilva** [totvs/tds-vscode#138]
Ao selecionar uma variável/expressão qualquer, seria possível incluí-la na "Watch Window" ao arrastar e soltar?

![image](https://user-images.githubusercontent.com/488565/63124051-c696c700-bf80-11e9-850e-f3b3be149a2f.png)

**Comment by DanielYampolschi** [comment]
@cfasilva É uma idéia interessante, tenho dúvidas da viabilidade pois me parece ser algo relacionado mais ao "core" do VsCode. Adicionei no projeto Help Wanted caso você ou alguém queira colaborar com a implementação dessa funcionalidade.
Obrigado pela sugestão.

**Comment by klauswolfgram** [comment]
@DanielYampolschi Esse é um recurso bacana. Naquele primeiro TDS, que vinha na pasta do smartclient, tinha essa opção de arrastar a expressão pra dentro da janela de watch. De qualquer forma, obrigado por colocar na lista.

**Comment by ricardomansano** [comment]
Boa tarde @cfasilva ,

Esta funcionalidade pode facilmente ser utilizada clicando com o botão direito do Mouse sobre a variável, e selecionando a opção "Debug: Add to Watch" no menu popup, sendo inclusive até mais funcional do que o próprio drag and drop.

Muito grato pela sua sugestão.
