### ISSUE TITLE
Auto-Complete: Melhorar informações das funções com dados do TDN

### ISSUE THREAD

**Issue by DanielYampolschi** [totvs/tds-vscode#14]
As funções Advpl devem ser retornadas seguindo o padrao de nomes, em "camelcase", com a primeira letra maiúsculo (ex.: ExampleFunction).
Utilizar as informações o TDN para identificar e informar melhor o usuário sobre os parâmetros de cada função.

**Comment by Vitor-Santos-Totvs** [comment]
As informações sobre funções/classes do TDN, assim como a página de boas práticas, utilizam notação húngara. Isso será alterado pra Camelcase nesse plugin então?

**Comment by DanielYampolschi** [comment]
Ola Vitor, no TDN, os nomes das funções estão documentados como camelcase, por isso a idéia é manter dessa forma. Obrigado pela dica, vamos verificar.

**Comment by Vitor-Santos-Totvs** [comment]
Ah, entendi. Achei que vocês estavam se referindo aos parâmetros das funções, mas realmente, o nome das funções seguem o padrão Camelcase, assim como os parâmetros seguem a notação húngara.

**Comment by ricardomansano** [comment]
Essa implementação depende da criação do nosso motor de parser que foi prorrogada para o primeiro semestre de 2020, manteremos os canais informados quando da liberação.
