### ISSUE TITLE
Compilar WORKSPACE ou Selecionar todas as pastas e compilar deixar fontes sem compilar

### ISSUE THREAD

**Issue by charlesreitz** [totvs/tds-vscode#141]
Olá, mandei compilar a WORKSPACE, e alguns fontes tiveram alguns problemas, feito a correção mandei compilar toda workspace novamente, no consolelog aparece, porém alguns fontes não foram compilados, tive que entrar no fonte e mandar compilar, somente após isso ele compilou. 

O mesmo problema acontece quando seleciono todas as pastas e mando compilar, alguns fontes não compilam.

**Comment by DanielYampolschi** [comment]
Ola @charlesreitz , obrigado pela informação, vamos verificar.

**Comment by DanielYampolschi** [comment]
Ola @charlesreitz eu tentei reproduzir esse comportamento e não consegui.
Fiz o seguinte processo:
1 - Criei algumas pastas e em cada uma coloquei 10 fontes.
2 - De forma aleatoria, adicionei linhas que causem erro de compilação.
3 - Mandei compilar com a opção "Compile All Workspace" e como era de esperado, os fontes apresentaram os problemas
4 - Corrigi os problemas dos fontes e mandei compilar novamente pelo mesmo metodo acima
5 - A compilação foi efetuada com sucesso e os erros foram removidos.
6 - Executei os fontes que antes deram erro de compilação e eles foram executados normalmente.

Isso aconteceu apenas uma vez ou sempre acontece?
Voce pode enviar um passo a passo onde essa situação sempre ocorre?

Obrigado.

**Comment by charlesreitz** [comment]
Olá Daniel, vou tentar fazer uns novos testes aqui, isso acontia no servidor de um cliente que tínhamos o VSCode, vou pegar os fontes deles e fazer na minha maquina local para tentar dar mais detalhes.

**Comment by brodao** [comment]
Ola @charlesreitz 

Tem alguma informação a respeito da sua ocorrência?

No aguardo.

**Comment by ricardomansano** [comment]
Agradecemos o report, dado o prazo sem resposta acredito que o problema tenha sido resolvido.
Qualquer outra issue estamos a disposição
