### ISSUE TITLE
Demora para sincronização das variáveis no debug

### ISSUE THREAD

**Issue by caiadofelipe** [totvs/tds-vscode#142]
Quando mando debugar, no primeiro breakpoint está demorando 5 minutos para sincronizar as variáveis.

Existe alguma configuração que resolva isso?

![image](https://user-images.githubusercontent.com/49681823/63449724-05ac9880-c417-11e9-94cf-8181e2421a65.png)

**Comment by DanielYampolschi** [comment]
Ola @caiadofelipe , faça um teste por favor. 

Desabilite o sincronismo de tabelas no executor e verifique se o problema continua.

Para desabilitar o sincronismo de tabelas, abra o arquivo launch.json e nas configurações do seu executor (Pelo que vi no seu print, com o nome: Totvs Protheus12...) adicione o seguinte parametro:
"enableTableSync": false

Orbigado.

**Comment by caiadofelipe** [comment]
Boa tarde @DanielYampolschi ,

Conforme solicitado inclui a opção no arquivo de configuração, conforme abaixo, mas o problema não foi resolvido.

		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Totvs PROTHEUS_12_1_17",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "C:\\TOTVS\\Base\\Protheus12\\bin\\smartclient\\smartclient.exe",
			"enableMultiThread": true,
			"enableProfile": false,
			"enableTableSync": false,
			"isMultiSession": true,
			"isAccessibilityMode": false,
			"doNotShowSplash": false,
			"language": "",
			"ignoreFiles": true
		}

**Comment by DanielYampolschi** [comment]
@caiadofelipe 
Isso acontece apenas na primeira vez que acontece a parada? 
Caso voce faça um step qualquer o sincronismo ocorre sem problemas?
Isso acontece apenas com esse fonte?

Consegue testar no TDS Eclipse e verificar se tem o mesmo comportamento por favor?

A principio, nao econtrei nada o processo de sincronismo que justificaria uma demora tao acentuada, a nao ser por duas coisas:
1 - Alto numero de variaveis
2 - O servidor é remoto e pode haver algum problema na rede.

**Comment by caiadofelipe** [comment]
@DanielYampolschi ,

Responde suas perguntas

Acontece somente na primeira vez, no Step o problema não ocorre.

No TDS está normal, não gera lentidão.
O Servidor é local e está acontecendo isso.

Abraço,

**Comment by edvarwv** [comment]
Boa tarde @DanielYampolschi 
Comigo acontece a mesma coisa e com mais 3 analistas da empresa, alem de outros colegas que reclamaram da mesma situação.

Sempre a 1a parada do Debug demora entre 1 a 2 minutos.
Depois todo o processo de debug segue liso.

Já desabilitei a configuração de tablesync mas continua o mesmo problema.

Obs.: Isso ocorre com qualquer fonte no vsCode, mesmo um fonte simples e pequeno .. 
Fiz o mesmo processo de debug no TDS e lá funciona sem lentidão!

Se puder ajudar agradeço

Meu launch.json

{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Totvs Language Debug",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "C:\\Protheus_12.1.23\\smartclient.exe",
			"enableMultiThread": true,
			"enableProfile": false,
			"isMultiSession": true,
			"isAccessibilityMode": false,
			"doNotShowSplash": false,
			"ignoreFiles": true,
			"enableTableSync": false
		}
	],
	"lastPrograms": [
		{
			"args": [],
			"label": "SIGAADV",
			"description": ""
		}
	],
	"lastProgramExecuted": "SIGAADV"
}

**Comment by danielbolognani** [comment]
@edvarwv Poderia me informar se existe muitos arquivos no seu workspace?
Poderia também ligar o log do DAP:
Adcionar a linha abaixo
"logFile": "${workspaceFolder}\\daplog.log"
no ambiente do seu arquivo launch.json e nos enviar o arquivo daplog.log que será criado na raiz do seu workspace.

**Comment by edvarwv** [comment]
> @edvarwv Poderia me informar se existe muitos arquivos no seu workspace?
> Poderia também ligar o log do DAP:
> Adcionar a linha abaixo
> "logFile": "${workspaceFolder}\daplog.log"
> no ambiente do seu arquivo launch.json e nos enviar o arquivo daplog.log que será criado na raiz do seu workspace.

Bom dia @danielbolognani ,
Realmente eu deixo todos fontes de todas empresas que passei no workspace devido a facilidade de buscas etc...

Fazendo um novo workspace com somente um projeto realmente foi bem rapido e solucionou o problema.

Tem alguma forma de colocar varios projetos no workspace e ele não carregar tudo no 1o ponto de parada ?

Muito Obrigado

**Comment by danielbolognani** [comment]
@edvarwv 
Vou deixar como melhoria para tentar deixar o processo mais rápido.

**Comment by edvarwv** [comment]
Muito obrigado pela ajuda

**Comment by danielbolognani** [comment]
Resolvido na versão 0.3.18
