### ISSUE TITLE
Problemas em aplicar path pela lista da workspace

### ISSUE THREAD

**Issue by marjorietaki** [totvs/tds-vscode#144]
Bom dia,
Ao tentar aplicar uma patch clicando com o botão direito no arquivo listado na workspace é apresentado uma mensagem de erro.
Aplicando a mesma patch pela telinha de aplicação de patch, é finalizada com sucesso.
![image](https://user-images.githubusercontent.com/50883319/63514711-93dc5980-c4bf-11e9-92ba-97b701378d52.png)

Poderiam verificar por favor? Fico à disposição para dúvidas.
Obrigada

**Comment by DanielYampolschi** [comment]
Ola @marjorietaki , muito obrigado pela informação, vamos verificar.

**Comment by DanielYampolschi** [comment]
Correção liberada na versão 0.3.13
