### ISSUE TITLE
Ecossistema RM/Fluig

### ISSUE THREAD

**Issue by msmosso** [totvs/tds-vscode#145]
Bom dia, 

Há alguma intenção de lançar algum plugin para o ecossistema RM e/ou para o Fluig?

Obrigado desde já.

**Comment by lwtnb-wrk** [comment]
@msmosso A que tipo de plugin voce esta se referindo?? 
O plugin "tds-vscode" é especificamente para desenvolvedores que precisam compilar e depurar fontes AdvPL nos servidores Protheus.

**Comment by ricardomansano** [comment]
Boa tarde @msmosso ,

Os times de RM e Fluig tem suas próprias iniciativas técnicas.

Peço a gentileza que leve esta demanda à cada um deles.

Grato pela dua interação,
