### ISSUE TITLE
Porque duas extensões para o VSCode?

### ISSUE THREAD

**Issue by afucher** [totvs/tds-vscode#149]
Vi que existem duas extensões para o VSCode, porque dividir os esforços? Quais são as diferenças entre elas?

**Comment by charlesreitz** [comment]
Até onde sei, uma é a oficinal da equipe de TEC, a outra foi criado por outra pessoa interna na TOTVS.

**Comment by ricardomansano** [comment]
@afucher, você como ex-totver já que conhece toda a historia do "porque dois"

Ambas são da TOTVS mas a da TEC irá pro SmartERP como Oficial, já que possui motores de LSP e DAP 100% compatíveis com o mercado, inclusive o mesmo motor ja esta em teste pelo TDS-Eclipse.

Quando às diferenças, a da TEC tem uma equipe por traz, 100% alinhada com os setores de AppServer e SmartClient, trabalhando como um único time pra melhorar todo ecossistema Protheus.
