### ISSUE TITLE
Auto-Complete: Identificação de variáveis

### ISSUE THREAD

**Issue by DanielYampolschi** [totvs/tds-vscode#15]
Implementar processo de identificação de variáveis do fonte corrente para ser informado no auto-complete

**Comment by Vitor-Santos-Totvs** [comment]
Já que foi criada essa segunda issue exatamente igual à que eu tinha solicitado (Intelisense omite variáveis e funções locais #8), peço que marquem a minha como duplicada e caso seja possível de implementar, peço que adicionem a identificação de funções do fonte corrente também.

**Comment by DanielYampolschi** [comment]
Criado uma mensagem no Language Server a qual permite Habilitar/Desabilitar o Auto-Complete do mesmo. 
Essa solução é temporário, apenas um contorno, pois no momento o Language Server ainda não possui um Auto-Complete mais inteligente, e ao desabilita-lo, o VSCode passa a usar as informações do próprio fonte. 
Aguardando implementação de um comando no VSCode o qual utilizará essa mensagem.

**Comment by brodao** [comment]
Implementado de opção para troca de comportamento do auto-complete:
- Acesse 'setttings', opção "Totvs Language Server › Editor › Toggle: Autocomplete"
- No editor, acione o atalho ctrl+alt+space

Na barra de status será apresentado o comportamento atual, sendo:
- basic: executa o autocompletar padrão do VSCode
- rpo: inclui informações disponíveis no RPO do ambiente corrente.
![auto complete - rpo - 2019-05-24 141846](https://user-images.githubusercontent.com/949914/58345582-186efb80-7e2f-11e9-9166-31740902568e.png)
![auto complete - basic - 2019-05-24 141846](https://user-images.githubusercontent.com/949914/58345584-186efb80-7e2f-11e9-8f24-b8f5831a0400.png)
