### ISSUE TITLE
Problema ao Debugar WS no Vscode.

### ISSUE THREAD

**Issue by brunos0** [totvs/tds-vscode#150]
Bom dia Senhores.

Estou usando o Vscode 1.37.1 em conjunto com o TDS-Vscode versão 0.3.11 ( pois a versão 0.3.12 está com erro ao aplicar patch - erro já detectado pela equipe da TOTVS ).

Preciso fazer um debug de um WebService que criei no Protheus. Para tal eu abro o SoapUI, marco com o Break point, abro o SIGAMDI e faço o request.

O processamento passa reto e a rotina executa sem parar no breakpoint. 

Se faço um debug chamando uma rotina, por exemplo um P.E. o Vscode para no breakpoint com sucesso.

Se faço o mesmo setup no DEV Studio do smartclient, eu consigo debugar o meu fonte do WS com sucesso.

Já estou com a chave "isMultiSession": true dentro do arquivo launch.json.

Tenho a impressão que essa funcionalidade tinha rodado em alguma versão antiga do plug-in.

Poderiam verificar o caso?
Vocês tem ideia de quando vai sair a versão 0.3.13?

Atenciosamente,
Bruno Horvat

**Comment by DanielYampolschi** [comment]
@brunos0 O plugin tds-vscode não possui essa chave no settings.json. 

Pode ser que ela tenha ficado configurada da instalação de algum outro plugin (Verifique se essa chave possui um risco embaixo, o que informa que essa configuração não foi encontrada e não possui efeito), ou você ainda possui esse plugin instalado, o que não é recomendado pois pode ocasionar conflitos.
