### ISSUE TITLE
#VisualStudioCode - ERROR LOG em modo debug variável objeto

### ISSUE THREAD

**Issue by cleuto** [totvs/tds-vscode#151]
o "Visual Studio Code" com o plugin TOTVS está gerando error log quando colocamos um ponto de parada em uma variável do tipo objeto como segue vídeo em anexo, quando utilizado o ponto de parada em qualquer outro lugar funciona normalmente, mas quando passa por uma variável do tipo objeto o erro é apresentado. obs.: isso ocorre apenas no binári
[error log.zip](https://github.com/totvs/tds-vscode/files/3551911/error.log.zip)
o do lobo-guara.

**Comment by DanielYampolschi** [comment]
Ola @cleuto Muito obrigado pela informação.
Vendo se video notei que voce esta usando o SIGAMDI para depurar.
Devido à natureza de funcionamento do SIGAMDI, não recomendamos a depuração por ele. Essa é uma limitação do próprio processo de depuração do servidor.
Te peço para fazer o mesmo teste depurando via SIGAADV.
Muito obrigado.

**Comment by lwtnb-wrk** [comment]
@cleuto se ainda estiver com problemas mesmo utilizando o SIGAADV favor abrir uma outra issue descrevendo o novo cenario

**Comment by cleuto** [comment]
bom dia!
muito obrigado, utilizando o SIGAADV não tive mais problema para debugar!
