### ISSUE TITLE
Indentação automática ao digitar a palavra "do"

### ISSUE THREAD

**Issue by LeonardoRios** [totvs/tds-vscode#152]
Sempre que eu vou escrever algo em que tenha as letras "do" nela o código da linha com estas letras é indentado recuando o código.

**Comment by caiadofelipe** [comment]
Tenho esse problema também, alguém tem alguma solução?

**Comment by FelipeRossi08** [comment]
Comigo também acontece esse problema.

**Comment by ricardomansano** [comment]
Problema solucionado estará disponível na versão superior à 0.3.19

**Comment by ricardomansano** [comment]
Resolvido estara disponivel na versão 0.3.20
