### ISSUE TITLE
Problema no Syntax Highlight

### ISSUE THREAD

**Issue by LeonardoRios** [totvs/tds-vscode#153]
Olá,

O Syntax HighLight não está reconhecendo as palavras reservadas "EXIT" e "LOOP".

![image](https://user-images.githubusercontent.com/6351312/64070274-07563780-cc33-11e9-90a7-ef4b695cec69.png)

**Comment by DanielYampolschi** [comment]
Ola @LeonardoRios Obrigado pelo aviso.

Como esse é um projeto colaborativo, essa issue será adicionada ao projeto "Help Wanted" para que você mesmo ou alguma outra pessoa possa nos ajudar a resolver isso o mais rápido possível.

**Comment by caiadofelipe** [comment]
Boa tarde @DanielYampolschi e @LeonardoRios ,

Inclui uma PR para essa ISSUE: https://github.com/totvs/tds-vscode/pull/155
Favor avaliar.

**Comment by DanielYampolschi** [comment]
PR incluída.
Estará disponível na próxima liberação.
Muito obrigado
