### ISSUE TITLE
Mac-include-PRTOPDEF

### ISSUE THREAD

**Issue by joaov1tor** [totvs/tds-vscode#154]
Bom dia, 
Ao tentar compilar me deparo com os erro para localizar os includes, ja alterar a localização da pasta e mesmo assim o erro ocorre, não aparece o problema na aba problems, detalhe, consigo debugar normalmente.

**Segue log da compilação.**
[Log   - 00:00:00] Start file compile.
[Log   - 00:00:00] Start regular compiling /Users/joaovitor/Documents/Desenvolvimento/Totvs/TBC/Clientes/capul/src/xml_importacao_xml/rotinas/PRENF.prw (1/1).
[Info  - 10:17:38 AM] totvsls @EdummyForX64 @F/Users/joaovitor/Documents/Desenvolvimento/Totvs/TBC/Clientes/capul/src/xml_importacao_xml/rotinas/PRENF.prw -I/Users/joaovitor/includes @D/var/folders/47/1mnz68bj1h3bww13kytbdcwc0000gn/T @I7237709 /N /S /P /dPROTHEUS /DAP-101 /dTOP /uPRTOPDEF.CH /DPORTUGUESE 
[Warn  - 10:17:38 AM] Source /Users/joaovitor/Documents/Desenvolvimento/Totvs/TBC/Clientes/capul/src/xml_importacao_xml/rotinas/PRENF.prw precompiled with warnings and/or errors.
[Log   - 00:00:00] Committing end build.
[Warn  - 10:17:38 AM] One or more files have warnings and/or errors. See problems and logs for details.
[Info  - 10:17:38 AM] Compile finished.

**Comment by DanielYampolschi** [comment]
Ola @joaov1tor Testei por aqui, forçando um inlcude inexistente e o erro apareceu na visao "Problems" normalmente. 

Qual a versão do seu VsCode e do plugin tds-vscode que você está usando por favor?

**Comment by joaov1tor** [comment]
O plugin tds-vscode está na 0.3.13
Abaixo informações do meu vscode.
Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:16:34.800Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 17.7.0

**Comment by DanielYampolschi** [comment]
@joaov1tor O log que você passou acima não informa erro de include, apenas que algum evento (Erro ou Warning) ocorreu no fonte PRENF.prw. 
Por favor de mais detalhes, ou mesmo enviar um print do que acontece para termos uma visão melhor.
Muito Obrigado.

**Comment by joaov1tor** [comment]
Boa noite, segue prints dos processos e do problema..
![Screen Shot 2019-09-19 at 23 10 14](https://user-images.githubusercontent.com/36445314/65294775-a0db7f80-db35-11e9-822d-48db65f7dc24.png)
![Screen Shot 2019-09-19 at 23 09 04](https://user-images.githubusercontent.com/36445314/65294776-a0db7f80-db35-11e9-9b56-29f3e4dc2bf1.png)
![Screen Shot 2019-09-19 at 23 08 50](https://user-images.githubusercontent.com/36445314/65294777-a0db7f80-db35-11e9-8243-5d0ca22bcaa4.png)

**Comment by DanielYampolschi** [comment]
@joaov1tor Muito obrigado pelos prints, porem eles ainda não mostram o erro em si, por favor, mande um print da aba "Problems" (A qual mostra 6 ocorrencias), e um print da linha do fonte com a a marcação do erro... 
obrigado mais uma vez.

**Comment by joaov1tor** [comment]
@DanielYampolschi segue novos, prints, mas como pode ver nao mostra nada alem do que tem na view **"OUTPUT"**
![Screen Shot 2019-09-20 at 11 59 02](https://user-images.githubusercontent.com/36445314/65337324-4d514c00-db9e-11e9-96ce-a354a51a26dd.png)
![Screen Shot 2019-09-20 at 11 58 32](https://user-images.githubusercontent.com/36445314/65337325-4de9e280-db9e-11e9-8430-4408f5854fe6.png)



**Comment by joaov1tor** [comment]
Boa tarde,
Segue verbose da comunicação com o server, as tags connectionToken e connectionToken eu removi.

[Trace - 4:58:29 PM] Sending request '$totvsserver/compilation - (51)'.
Params: {
    "compilationInfo": {
        "connectionToken": "",
        "environment": "",
        "includeUris": [
            "file:///Users/joaovitor/Documents/Desenvolvimento/Totvs/TBC/includes",
            "file:///users/joaovitor/documents/desenvolvimento/totvs/includes"
        ],
        "fileUris": [
            "file:///Users/joaovitor/Documents/Desenvolvimento/Totvs/TBC/Clientes/unity/src/Integracao/Receita/Ws/WsTasy.tlpp"
        ],
        "compileOptions": {
            "recompile": false,
            "debugAphInfo": true,
            "gradualSending": true,
            "generatePpoFile": false,
            "showPreCompiler": false,
            "priorVelocity": true
        }
    }
}


[Trace - 4:58:29 PM] Received notification 'window/logMessage'.
Params: {
    "type": 3,
    "message": "Starting compile."
}


[Info  - 4:58:29 PM] Starting compile.
[Trace - 4:58:29 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "[Log   - 00:00:00] Starting build for environment cv8kf0_dev."
}


[Log   - 00:00:00] Starting build for environment cv8kf0_dev.
[Trace - 4:58:30 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "[Log   - 00:00:00] Start file compile."
}


[Log   - 00:00:00] Start file compile.
[Trace - 4:58:30 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "[Log   - 00:00:00] Start regular compiling /Users/joaovitor/Documents/Desenvolvimento/Totvs/TBC/Clientes/unity/src/Integracao/Receita/Ws/WsTasy.tlpp (1/1)."
}


[Log   - 00:00:00] Start regular compiling /Users/joaovitor/Documents/Desenvolvimento/Totvs/TBC/Clientes/unity/src/Integracao/Receita/Ws/WsTasy.tlpp (1/1).
[Trace - 4:58:30 PM] Received notification 'window/logMessage'.
Params: {
    "type": 2,
    "message": "Source /Users/joaovitor/Documents/Desenvolvimento/Totvs/TBC/Clientes/unity/src/Integracao/Receita/Ws/WsTasy.tlpp precompiled with warnings and/or errors."
}


[Warn  - 4:58:30 PM] Source /Users/joaovitor/Documents/Desenvolvimento/Totvs/TBC/Clientes/unity/src/Integracao/Receita/Ws/WsTasy.tlpp precompiled with warnings and/or errors.
[Trace - 4:58:30 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {
    "uri": "file:///Users/joaovitor/Documents/Desenvolvimento/Totvs/TBC/Clientes/unity/src/Integracao/Receita/Ws/WsTasy.tlpp",
    "diagnostics": [
        {
            "range": {
                "start": {
                    "line": -1,
                    "character": 0
                },
                "end": {
                    "line": 0,
                    "character": 0
                }
            },
            "severity": 1,
            "source": "appre",
            "message": "C2090  File not found PRTOPDEF.CH"
        }
    ]
}


[Trace - 4:58:30 PM] Received notification 'window/logMessage'.
Params: {
    "type": 4,
    "message": "[Log   - 00:00:00] Committing end build."
}


[Log   - 00:00:00] Committing end build.
[Trace - 4:58:30 PM] Received notification 'window/logMessage'.
Params: {
    "type": 2,
    "message": "One or more files have warnings and/or errors. See problems and logs for details."
}


[Warn  - 4:58:30 PM] One or more files have warnings and/or errors. See problems and logs for details.
[Trace - 4:58:30 PM] Received notification 'window/logMessage'.
Params: {
    "type": 3,
    "message": "Compile finished."
}


[Info  - 4:58:30 PM] Compile finished.
[Trace - 4:58:30 PM] Received response '$totvsserver/compilation - (51)' in 1455ms.
Result: {
    "returnCode": 0,
    "compileInfos": [
        {
            "status": "APPRE",
            "filePath": "/Users/joaovitor/Documents/Desenvolvimento/Totvs/TBC/Clientes/unity/src/Integracao/Receita/Ws/WsTasy.tlpp",
            "message": "Precompiled with warnings and/or errors",
            "detail": "APPRE457850878.TLPP(0) Error C2090  File not found PRTOPDEF.CH\n"
        }
    ]
}

**Comment by ricardomansano** [comment]
Boa tarde @joaov1tor , esse chamado acabou caindo numa lista de espera e não falamos a algum tempo, Algumas duvidas:

Primeira: Lançamos algumas versões neste periodo, vc chegou a atualizar e refazer o teste?

Segunda: A primeira mensagem de saida que postou não necessariamente é um erro, aparenta ser apenas um warning, motivo pelo qual pode nao ter cido direcionada pra aba problems.

Terceira: A ultima mensagem, onde não é colalizado o arquivo PRTOPDEF pode ser um erro, mas na versão 0.3.20 inserimos a opção de pasta de include por servidor cadastrado, que pode em teoria resolver tbem seu problema:

![image](https://user-images.githubusercontent.com/33813921/69755385-dd7bb680-1136-11ea-8781-b91aba7f6443.png)

Poderia testar por gentileza?
Grato,

**Comment by joaov1tor** [comment]
E tão pode fechá-lo, estou usando Windows agora.

Enviado do meu iPhone

Em 27 de nov de 2019, à(s) 16:56, Mansano <notifications@github.com<mailto:notifications@github.com>> escreveu:


Boa tarde @joaov1tor<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjoaov1tor&data=02%7C01%7C%7C43aafaf51de94660ca9908d77373f23d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637104814128604547&sdata=cKWejLunl8bWsWMkgBYwBZvgATXHgTJTCWnaqnTQwhk%3D&reserved=0> , esse chamado acabou caindo numa lista de espera e não falamos a algum tempo, Algumas duvidas:

Primeira: Lançamos algumas versões neste periodo, vc chegou a atualizar e refazer o teste?

Segunda: A primeira mensagem de saida que postou não necessariamente é um erro, aparenta ser apenas um warning, motivo pelo qual pode nao ter cido direcionada pra aba problems.

Terceira: A ultima mensagem, onde não é colalizado o arquivo PRTOPDEF pode ser um erro, mas na versão 0.3.20 inserimos a opção de pasta de include por servidor cadastrado, que pode em teoria resolver tbem seu problema:

[image]<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F33813921%2F69755385-dd7bb680-1136-11ea-8781-b91aba7f6443.png&data=02%7C01%7C%7C43aafaf51de94660ca9908d77373f23d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637104814128614552&sdata=jn1utyYG4TafpRpF9sdmw2TkRSl2Hx8fYQOpzgIQB54%3D&reserved=0>

Poderia testar por gentileza?
Grato,

**Comment by ricardomansano** [comment]
Grato pelo retorno
