### ISSUE TITLE
Erro identação do código quando se tem Embedded Sql

### ISSUE THREAD

**Issue by titosca** [totvs/tds-vscode#156]
Prezados, 

Quando temos um código de embedded Sql com uma query que apresenta o operador UNION ALL a formatação abaixo do mesmo fica toda desconfigurada, o código logo após o comando UNION ALL fica todo desformatado.

![issue_VsCode](https://user-images.githubusercontent.com/54855906/64190996-e74e9000-ce4d-11e9-9f47-7ebcbfede0fe.png)

**Comment by LeonardoRios** [comment]
@DanielYampolschi, 

Aproveitando este problema do Embedded Sql, quando existe o "ORDER BY" o syntax highlight não funciona para o "ORDER BY".

**Comment by charlesreitz** [comment]
+1

**Comment by ricardomansano** [comment]
Problema solucionado estará disponível na versão superior à 0.3.19

**Comment by ricardomansano** [comment]
Resolvido estara disponivel na versão 0.3.20
