### ISSUE TITLE
Solicitar senha novamente

### ISSUE THREAD

**Issue by likid** [totvs/tds-vscode#159]
Ao conectar a um servidor cujo o token esteja salvo, mas após o usuário alterar a senha, a extensão está apenas informando erro de usuário e senha. Poderia ser feito uma detecção do erro de senha e solicitar a senha novamente para salvar o novo token.

**Comment by lwtnb-wrk** [comment]
@likid Grato pela sugestão. Ela será avaliada e adicionada em nosso Roadmap.

**Comment by ricardomansano** [comment]
Agradecemos a sugestão, mas como a senha compõe o token este processo não justifica a melhoria. Caso altere a senha basta excluir e recriar o servidor, um processo rápido e simples.

**Comment by renanpaiva64** [comment]
TOTVS e UX never match
