### ISSUE TITLE
Barra invoca intelisense

### ISSUE THREAD

**Issue by Vitor-Santos-Totvs** [totvs/tds-vscode#16]
Ao digitar o caractere "/" dentro de uma função, o intelisense é invocado sugerindo a ultima função usada dele. Não sei se isso é intencional, mas acaba atrapalhando um pouco ao comentar linhas quando a configuração está para invocar o intelisense após um caractere digitado.

![bug barra](https://user-images.githubusercontent.com/50745570/57959501-891b9280-78da-11e9-9cf7-f74f34fc9929.jpg)

**Comment by Vitor-Santos-Totvs** [comment]
Após um segundo teste encontrei mais alguns caracteres com o mesmo comportamento:
: (dois pontos) . (ponto) < (menor) > (maior) ¨ (trema) " (aspas duplas) ´ (acento agudo)
O caractere # (cerquilha) também tem o mesmo comportamento, ao invés de invocar a seção de comandos que começam com ele.

**Comment by lwtnb-wrk** [comment]
@Vitor-Santos-Totvs removemos este comportamento enquanto nossa implementacao de intelisense nao esta funcional. assim que implementarmos retornaremos o disparo conforme o contexto atual da digitacao.
