### ISSUE TITLE
Erro no debug ao tentar capturar conteúdo de objeto json

### ISSUE THREAD

**Issue by pauloapolinario** [totvs/tds-vscode#160]
Estou tendo problemas ao debugar uma rotina que acessa um webservice rest externo e quando posiciono o mouse sobre uma variável de objeto json o vscode apresenta o erro a seguir.

![image](https://user-images.githubusercontent.com/7171411/64615898-ccca6880-d3b1-11e9-8d00-6cf26add9329.png)

Segue trecho do código.
`
User Function ZDWR01ENV(aPedidos)
Local lRet     := .F.
Local oSend
Local oVeiculo
Local oVisita
Local cJSon    := ""
Local nAux     := 0
Local nQtd     := 0
Local cxAlias  := GetNextAlias()

	LogTrace( "Criando Objeto", 1 )

	oSend := JsonObject():New()
	oSend["descricao"]        := ""
	oSend["dataPlanejamento"] := u_ZDWR_Data()
	oSend["codigo"]           := "TESTE" + dTos(dDataBase) + Time()
	oSend["tipoOtimizacao"]   := 0
	oSend["publico"]          := .T.
	oSend["visitas"]          := {}
	oSend["veiculos"]         := {}
	
	LogTrace( "Incluindo Visitas", 1 )

	// Adicionar os Pedidos
	For nAux := 1 To Len(aPedidos)
		oVisita := u_ZDWR_VIS( aPedidos[nAux] )
		If oVisita != Nil
			nQtd++
			aadd( oSend["visitas"], oVisita )
		Endif
	Next

	LogTrace( "Incluido " + Alltrim( Str( nQtd ) ) + " Visitas", 1 )
Return 
`

**Comment by brodao** [comment]
Ola @pauloapolinario 

Verifique se seu ambiente TDS-VSCode esta atualizado e caso não esteja, faça a atualização e repita os testes.

Se ainda estiver com a ocorrência, execute a função "varInfo"* e anexe o log de console do Protheus para análise.

_*Coloque a chamada da **varInfo** para as variáveis oSend e oVisita no seu código antes do local que ocorre o problema de depuração, compile o fonte e tente novamente.
Exemplo varinfo: VarInfo("oSend:", oSend)_

No aguardo.

**Comment by ricardomansano** [comment]
Bom dia, dado o prazo sem resposta acredito que o problema tenha sido solucionado.
Estaremos aqui caso precise de apoio.
Grato,
