### ISSUE TITLE
Indentação de código WSRESTFUL e END WSRESTFUL

### ISSUE THREAD

**Issue by alexandreandradeg** [totvs/tds-vscode#164]
Bom dia, a indentação de código dos comandos (WSRESTFUL, WSDATA, WSMETHOD,  e END WSRESTFUL) não estão sendo tratados corretamente, ficando desalinhados do restante do código.

**Comment by charlesreitz** [comment]
+ 1

**Comment by ricardomansano** [comment]
Problema solucionado estará disponível na versão superior à 0.3.19

**Comment by ricardomansano** [comment]
Resolvido estara disponivel na versão 0.3.20
