### ISSUE TITLE
#VisualStudioCode - Debug Error afeta Watch e Tables

### ISSUE THREAD

**Issue by raquelhager** [totvs/tds-vscode#165]
Boa tarde!

Ao executar Debug (acessando SIGAMDI ou SIGAADV) é gerado o erro em anexo.
Durante execução não consigo adicionar expressões no Watch, ao selecionar o '+' não é aberta caixa para inclusão e a opção 'Add expression' fica desabilitada.

A execução e salto entre os pontos de parada funcionam normalmente, exceto as abas do Debug - Watch e Tables em Variables.

Alguém já passou por isso?

Obrigada!
![VsCode-DebugError](https://user-images.githubusercontent.com/55213765/64979539-51275a80-d88e-11e9-9e63-138d87376e5d.JPG)

**Comment by danielbolognani** [comment]
Ola,
Pode ser que seja o mesmo problema da issue #137 
Como contorno tente desabilitar a sincronização de tabelas:
No arquivo launch.json, dentro do ambiente que vc utiliza para debug, adicione a linha a seguir:
"enableTableSync": false

Verifique a imagem como exemplo.
![exemplo_launchjson](https://user-images.githubusercontent.com/25229827/65044582-8934a900-d933-11e9-9163-43b5c4a05e7e.PNG)


Se resolver, estamos dependente de uma correção do lado do appserver.

**Comment by raquelhager** [comment]
Olá,

Eu alterei como descrito acima - "enableTableSync": false
E o erro persiste - não consigo adicionar, remover expressões do Watch e nem ver as Tabelas em Variables.

Segue dados do meu binário/build:
Build AppServer: 7.00.170117A-20190628 - 64 bits
SVN Revision: 23527
Build Version: 17.3.0.13  
Appserver version: 17.3.0.13
Build DBAccess: 20181212-20190211
Release do RPO:  12.1.023
Release do dicionário: 12.1.023
License server: 2014 - 2.3.4

**Comment by LucasGoleiro** [comment]
Bom dia, eu estava com o mesmo erro, após alterar o "enableTableSync" para false está funcionando normalmente.

**Comment by DanielYampolschi** [comment]
Ola @raquelhager faz um favor? 

Va até a seguinte pasta: 
C:\Users\<seu usuario>\.vscode\extensions\totvs.tds-vscode-0.3.14\node_modules\@totvs\tds-da\bin\windows

Nela deve existir um ou mais arquivos com a extensão ".dmp". Caso exista mais de um, selecione apenas o mais recente e envie para mim por favor.

Como esse arquivo pode ser grande, voce provavelmente tera que enviar para a nuvem, habilitar o compartilhamento e enviar o link para baixar.

Alias, caso exista mais de um arquivo ".dmp", após voce enviar para o Drive para que a gente possa baixar, voce pode remove-los pois eles podem ocupar bastante espaço em disco.

Muito obrigado.

**Comment by danielbolognani** [comment]
Com a versão 0.3.15 disponibilizada do plugin, essa situação foi protegida e pode ligar novamente a Sincronização de tabelas
