### ISSUE TITLE
Problema ao Adicionar Servidor ( macOS Mojave )

### ISSUE THREAD

**Issue by emersonmuniz** [totvs/tds-vscode#166]
> Reinstalei aqui e tudo funcionou perfeitamente!
> Obrigado!

Uso a mesma versão do macOS 10.14.6.

Apaguei o VSCode e apaguei as extenções em ~/.vscode/extensions, instalei novamente o VSCode e instalei a extenção novamente e continuo com o erro "command 'totvs-developer-studio.add' not found"

Algum componente a mais devo instalar e não notei ?

Grato...

_Originally posted by @emersonmuniz in https://github.com/totvs/tds-vscode/issues/66#issuecomment-532773567_

**Comment by ricardomansano** [comment]
Bom dia,
Dado o prazo do chamado e as novas atualizações sem problemas reportados acredito que o problema ja tenha sido resolvido
Estamos a disposição no caso de novas ocorrencias
