### ISSUE TITLE
Habilitar a opção de ativar ou não os componentes

### ISSUE THREAD

**Issue by rcarloslima** [totvs/tds-vscode#17]
Não sei se é impressão minha, mas o plugin carrega muita coisa que acaba ficando pesado o vscode, por exemplo, o plugin do killer carregava apenas o necessário, com isso era muito rápido desenvolver.

Por exemplo as caixas de notificações, poderia ter uma opção para desabilitar, o auto complete, as msgs do log tá trazendo varias informações mas na maioria das vezes apenas interessa saber se foi compilado ou não.

Mas parabéns pela iniciativa!!!

**Comment by matheus-sales** [comment]
@rcarloslima Talvez seja só impressão mesmo, mas vamos criar opções de desabilitar algumas funcionalidades.

Obrigado!

**Comment by izacsc** [comment]
Sinceramente, discordo da opção de desabilitar funcionalidades pra aumentar performance. Acredito que o melhor caminho seja melhorar a performance da extensão, como deixar algumas requisições assíncronas ou coisa do tipo.

**Comment by matheus-sales** [comment]
@izacsc eu concordo contigo, não é bom desabilitar funcionalidades. A maioria (se não todas) as requisições do VSCode são assíncronas, até porque ele só trabalha assim. Mas existem funcionalidades que usuários não usam, independente da velocidade, talvez seja interessante pro usuário desabilita-lá. A opção vai passar a existir e o usuário escolhe se vai ou não desabilitar. 

Por enquanto ainda faremos ajustes e refinos para melhora-las.

**Comment by rcarloslima** [comment]
@izacsc eu prefiro a opção de desabilitar, eu particularmente gosto muito mais do auto complete que já vinha padrão no vscode, porque ele me sugeria as variáveis e métodos que estava usando no código, não gostei das caixas q ficam subindo com as notificações, prefiro olhar no console, mas ai é gosto, pra atender todo mundo tem que deixar a opção para o usuário.

**Comment by izacsc** [comment]
Então @rcarloslima ... O autocomplete deveria ser a funcionalidade mais forte de uma extensão de Language Server, como essa que aqui... O padrão do vscode só avalia as palavras usadas no fonte inteiro, sem avaliar contexto e sem nada. A da extensão ainda precisa melhorar bastante, mas é um trabalho inicial. Me parece que sugere todas as diretivas de AdvPL, depois todas as funções de binário, depois os templates e vai filtrando conforme o que for digitado, não levando em conta o fonte utilizado para sugerir as palavras do contexto. O correto na minha opinião é melhorar o autocomplete disponibilizado e não voltar ao padrão do vscode.

Pra mim as mensagens nas notificações também são demais, poderia ser só no console pra 90% das mensagens.

Abraço

**Comment by lwtnb-wrk** [comment]
inicialmente grato pelas sugestoes e opnioes para melhorar o tds-vscode

@rcarloslima conforme comentado pelo @izacsc estamos em uma fase inicial e realmente o nosso autocomplete ainda exibe apenas informacoes basicas. para ser realmente funcional estamos trabalhando para podermos avaliar contexto locais e de outros fontes tambem. de qualquer forma devemos inicialmente liberar uma forma de temporariamente desabilitar o nosso autocomplete ate que ele possa suprir as necessidades reais dos desenvolvedores.

em relacao as notificacoes tambem deixaremos de uma forma configuravel pelo usuario, assim quem prefere ver mais notificacoes pode habilitar e quem prefere apenas ver no console podera desabilitar as notificacoes essa questao esta sendo tratada na issue #25

**Comment by lwtnb-wrk** [comment]
Cliquei no botão errado... rsrsrs

**Comment by ricardomansano** [comment]
Boa tarde time,

Alinhando expectativas:
-Decidimos criar um mecanismo mais completo switchs de opção, cada desenvolvedor usa-rá o que for mais interessante para sí.
-Faremos uma documentação forte deste mecanismo garantindo que não hajam dificuldas em sua configuração
-Até onde sei a lista de autocomplete anterior não trazia todas as funções (RPO/BIN/FONTE/ETC), pelo menos não sistemicamente, se precisarmos melhorar o mecanismo não haverá qualquer dificuldades em fazê-lo, temos dois times trabalhando nisso, mas não existe segredo: Quanto mais camadas, mais lento... 

Cercando os pontos acima agradamos a todos, mesmo que em pontos diferentes.
Agradeço as interações

**Comment by brodao** [comment]
Senhores,

O chamado #25, atende a configuração de mensagens de notificação.

A disposição.

**Comment by ricardomansano** [comment]
Boa tarde,

Conforme interação em 3/Jul a issue #25, atende a configuração de mensagens de notificação.

Muito grato a todos
