### ISSUE TITLE
Travamento no debug

### ISSUE THREAD

**Issue by andremaximo5** [totvs/tds-vscode#170]
Boa Tarde

Mesmo após a ultima atualização, ao iniciar o debug o sistema trava notei que não foi somente ao carregar as variáveis mas também o Debug Adapter fica sobrecarregado e deixa a maquina com processamento elevado só depois de 2 a 3 min ele destrava e continua processando.

**Comment by lwtnb-wrk** [comment]
@andremaximo5 estamos avaliando esta questão.
Grato pelas informações.
