### ISSUE TITLE
Erro ao aplicar patch fora do servidor (linux)

### ISSUE THREAD

**Issue by flaviotxa** [totvs/tds-vscode#171]
No linux, ao tentar aplicar patch vindo de uma pasta local para o servidor, o vs-code retorna o seguinte erro: File could not be copied to the server.

![Captura de tela de 2019-09-23 16-23-33](https://user-images.githubusercontent.com/33399384/65456728-581b1380-de20-11e9-9957-244a872e381a.png)

**Comment by brodao** [comment]
Ola @flaviotxa 

Qual o tamanho do pacote? É superior a 500K? Tivemos relatos de problemas na aplicação de pacotes em algumas versões do appServer.

Favor anexar log de console do protheus, com o momento da ocorrência.

Nota: Experimente renomear o nome do pacote para que este fique todo em minúsculas.

No aguardo.

**Comment by brodao** [comment]
Ola @flaviotxa 

Complementado, todos o caminho e nome do arquivo deve ser em minúsculas, sem acentos e preferivelmente sem espaços.

A dsposição..

**Comment by ricardomansano** [comment]
Bom dia, dado o prazo sem resposta acredito que o problema tenha sido solucionado.
Estaremos aqui caso precise de apoio.
Grato,

**Comment by marcianovc** [comment]
Bom dia, estou com o mesmo problema aqui, porem alem desse ainda ta pedindo o compilekey
![Captura de tela de 2019-12-11 12-03-22](https://user-images.githubusercontent.com/6756534/70632905-6c480300-1c0e-11ea-92d5-ff26f11f9ccb.png)

**Comment by jvvasquesn** [comment]
Tente tudo minusculo.
Por exemplo, coloque o arquivo tttp120.ptm na pasta marciano.

Atenciosamente.

**Comment by marcianovc** [comment]
> Tente tudo minusculo.
> Por exemplo, coloque o arquivo tttp120.ptm na pasta marciano.
> 
> Atenciosamente.

ja esta tudo minusculo @jvvasquesn

**Comment by lwtnb-wrk** [comment]
@marcianovc Pelo screenshot vejo que a pasta "Downloads" e "TOTVS" contem letras em maiúsculo. 

Tente colocar o patch em uma pasta aonde não existe em nenhuma subpasta nenhum carácter em maiúsculo e veja se isso resolve o problema.

**Comment by jvvasquesn** [comment]
Na imagem que você mandou TOTVS e o 'D' do downloads esta em maiúsculo

![image](https://user-images.githubusercontent.com/55854184/70646999-d1a7ee00-1c26-11ea-81d1-b76039f14b03.png)

**Comment by marcianovc** [comment]
boa agora intendi, fiz aqui com tudo em minusculo e foi, muuuuito obrigado @lwtnb-wrk e @jvvasquesn

**Comment by Felipe-Raposo** [comment]
Boa tarde.
Estou com o mesmo erro.

**Comment by lwtnb-wrk** [comment]
@Felipe-Raposo E testou as soluções propostas??

Se testou e não funcionou abra uma nova issue e adicione o máximo de informações para reproduzir o problema, sem isso nada podemos fazer.
