### ISSUE TITLE
Focar na janela de "problemas" quando ocorrer "erro de compilação"

### ISSUE THREAD

**Issue by luizhj** [totvs/tds-vscode#172]
Quando ocorrer um erro ao compilar (somente erro, não warning) abrir o panel inferior e focar na aba "problemas" como fazia os antigos devs.

![image](https://user-images.githubusercontent.com/16191002/65609149-ab5aa680-df85-11e9-9585-989a02bf798f.png)

**Comment by ricardomansano** [comment]
Bom dia @luizhj , vamos ver a viabilidade, como lidamos como uma plataforma de terceiros, tem features que não são liberadas, mas acho que essa não deve se problema.

**Comment by ricardomansano** [comment]
Issue corrigida, estara disponivel na versão superior a 0.3.20 do plugin do TDS-VSCode
