### ISSUE TITLE
Falha em recompilação no ambiente Linux 

### ISSUE THREAD

**Issue by rodrigomicrosiga** [totvs/tds-vscode#173]
A recompilação no linux não está sendo realizada...
É apresentada a mensagem de recompilação com sucesso, porém verificando via inspetor de objetos a informação não está correta.
No exemplo abaixo, os dois fontes foram baixados do TFS para serem recompilados no meu ambiente:

![fontes](https://user-images.githubusercontent.com/6909839/65610972-861b6780-df88-11e9-8fa8-5683a0b26d3a.png)

Recompilação realizada via CODE:

![info_recompile](https://user-images.githubusercontent.com/6909839/65611012-96cbdd80-df88-11e9-94e4-79b503e78d54.png)

Consultando via inspetor de objetos:

CTBA420 está com a data de ontem e não com a data conforme o fonte baixado do TFS:

![consulta01](https://user-images.githubusercontent.com/6909839/65611049-a2b79f80-df88-11e9-99a9-544702cbe29e.png)

CTBI420 com o mesmo problema:

![consulta02](https://user-images.githubusercontent.com/6909839/65611071-ac410780-df88-11e9-884d-492d04802711.png)

Utilizando a tecla ALT, não é apresentada a opção de "recompilar" no menu de contexto.
Realizando o uso do CTRL+SHIT+F9 é apresentada a mensagem de que foi recompilado com sucesso, porém não é apresentado na consulta via inspetor de objetos.
O mesmo vale para quando a alteração ocorre somente no CH.

**Comment by ricardomansano** [comment]
@leowww , @acacioegas , favor priorizar este atendimento na próxima Sprint.
Grato,

**Comment by brodao** [comment]
Ola @rodrigomicrosiga 

A data que consta no RPO será a data da última modificação do fonte, mesmo que você solicite a recompilação. 

Experimente efetuar um modificação qualquer (um comentário basta), salve o arquivo e mande recompilar.

No aguardo.

**Comment by ricardomansano** [comment]
@brodao , o @rodrigomicrosiga alterou só o CH, assim a recompilação tem que entender que houve alteração no momento do parser.
Da uma olha pfv como ta esse cenário no VS e no TDS, pois eles tem que ser iguais
Valew

**Comment by ricardomansano** [comment]
@rodrigomicrosiga , como lhe comentei ontem, utilizando a 0.3.20 não tive problema no Mint recompilando com CTRL+SHIFT+F9., alterando apenas o CH e não o fonte PRW.

Só deve atentar que a data do PRW que ira pro RPO é a data que esta fonte foi salvo, não a data do CH nem a data do dia que foi compilado.

Este processo exite pra que haja rastreio dos fontes, atualize e proceda com os testes pfv.
