### ISSUE TITLE
Problema no Monitor #MACOSX

### ISSUE THREAD

**Issue by dabraga** [totvs/tds-vscode#174]
Quando adiciono um servidor no monitor não tem a opção de excluir e também não conecta.
E não consigo ver os usuário logados

**Comment by ricardomansano** [comment]
Bom dia @dabraga , tivemos que parar o desenvolvimento do Monitor devido à tarefas que foram priorizadas.
Esto projeto será retomado no 1o trimestre de 2020,  manteremos os canais informados na sua liberação.

Grato
