### ISSUE TITLE
Compilação de Fontes 4GL 

### ISSUE THREAD

**Issue by fbcaetano** [totvs/tds-vscode#175]
Boa tarde,

Gostaria de saber como compilar fontes 4GL, na descrição da extensão ele tem 4GL mas não vi documentação alguma para isso.

**Comment by ricardomansano** [comment]
Bom dia @fbcaetano, essa feature esta em nosso roadmap pro 1o trimestre de 
2020, manteremos os canais informados na sua liberação.

Grato
