### ISSUE TITLE
Problema ao Debugar no Protheus 12v25

### ISSUE THREAD

**Issue by matheuspegoraro** [totvs/tds-vscode#176]
Ao tentar debugar um código no vscode, ele informa que não conseguiu encontrar o alias na SX2. Exemplo de um erro:

> ERROR:  Alias does not exist: SX2

> RETSQLNAME - APLIB070.PRW(1853) - Params: CALIAS:SA1 )
> U_EXSQL - EXSQL.PRW(26)

Existe algum problema de compatibilidade da versão P12v25 com o plugin?

**Comment by ricardomansano** [comment]
Bom dia @matheuspegoraro , não existe problema reportado, a 25 é onde fazemos nossos testes

precisamos de mais informações:
-Como reproduzir o problema
-Versão do appserver (pode pegar no start ou via shift+f6)

**Comment by ricardomansano** [comment]
Bom dia,
Dado o tempo sem resposta creio que o problema tenha sido resolvido
Estamos a disposição no caso de novas ocorrencias
