### ISSUE TITLE
Problemas ao configurar plugin ADVPL VSCode MACOS 

### ISSUE THREAD

**Issue by demadelosrios** [totvs/tds-vscode#177]
Boa tarde.

Estou tentando configurar no MACOS o plugin totvs.tds-vscode.

Quando tento adicionar um ambiente, apresenta o erro abaixo: 
command 'totvs-developer-studio.add' not found

Alguma dica ou questão que devamos fazer?

**Comment by ricardomansano** [comment]
Bom dia @demadelosrios , 
Vc lembra se teve algum problema durante a instalação do plugin?
Me confirma se esta usando a ultima versão que é a 0.3.15

**Comment by demadelosrios** [comment]
Ola @ricardomansano, primeiramente muito obrigado pelo breve retorno.

Durante a instalação do plugin não houve nenhum erro.
Até pra desencargo de consciencia, desinstalei o app da máquina, instalei novamente, instalei o pluign novamente e continuo com o mesmo problema, qualquer ação relacionada o plugin apresenta a mensagem: 'totvs-developer-studio.add' not found.

Confirmei a versão do plugin também, que está na 0.3.15.

Ps: achei uma outra issue (#166) ref. o mesmo problema. Também estou na versão mojave do OSx, precisamente na 10.14.6 

Muito obrigado mais uma vez.

**Comment by ricardomansano** [comment]
@demadelosrios , perfeito, vamos colocar na fila pra te ajudar.

Grato pelo retorno

**Comment by danielbolognani** [comment]
Ola @demadelosrios, antes de tentar adicionar um servidor, chegou a abrir um workspace/folder no VSCode? Por favor tente antes de tudo abrir uma pasta com arquivos advpl como área de trabalho no vscode e após isso tente configurar os servidores.

**Comment by ricardomansano** [comment]
Bom dia,
Dado o tempo sem resposta creio que a configuração tenha resolvido o problema
Estamos a disposição no caso de novas ocorrencias
