### ISSUE TITLE
Problema em depuração no MACOS

### ISSUE THREAD

**Issue by alanFaccin** [totvs/tds-vscode#178]
Ao depurar um fonte, as vezes é gerado no app um erro de invalid ReadMsChar, notei que isso ocorre quando utilizado o Debug console para ver o valor de alguma variável ou ainda com mais frequência quando utilizado a opção variables.
 Por exemplo, durante uma depuração desejo ver os valores de uma variável private, quando eu clico em variables e depois em private o erro é gerado, e as variáveis ficam carregando e não mostra mais nada. 

Não são em todos os casos que isso ocorre. 

<img width="482" alt="erro_dev" src="https://user-images.githubusercontent.com/9438826/66052788-8f1bb400-e507-11e9-8a58-ddef235a3ab4.png">

<img width="1394" alt="debug" src="https://user-images.githubusercontent.com/9438826/66052894-bd00f880-e507-11e9-8707-5a2ef8ab55dd.png">

**Comment by likid** [comment]
Passei por este problema também na versão 0.3.15, por este motivo fiz o downgrade para 0.3.14, pois estava impossível debugar.

**Comment by danielbolognani** [comment]
Poderiam testar na versão 0.3.17, por favor? Se ainda assim acontecer, é com qualquer fonte? qualquer ponto de parada?

**Comment by alanFaccin** [comment]
Estou testando a Versão 0.3.17 e por hora não tive este erro inesperado durante o debug. Percebi que este erro está ocorrendo na aplicação somente quando eu dou um STOP na depuração, e além disso o App não é encerrado, sendo necessário um kill para matá-lo.

**Comment by DanielYampolschi** [comment]
@alanFaccin Testei essa situação no Mac e não consigo reproduzir de nenhuma forma usando a versão 0.3.19. Você poderia atualizar seu plugin do TDS VsCode para essa versão e informar se você ainda observa esse comportamento? Obrigado.

**Comment by ricardomansano** [comment]
Bom dia, dado o prazo sem resposta acredito que o problema tenha sido solucionado.
Estaremos aqui caso precise de apoio.
Grato,
