### ISSUE TITLE
Erro Criação de Servidor

### ISSUE THREAD

**Issue by joseneto** [totvs/tds-vscode#179]
O vscode mostra a mensagem:

`Unexpected token  in JSON at position 0`

Mesmo clicando em adicionar um server ele não salva. Vinha utilizando normalmente, houve alguma atualização?

**Comment by danielbolognani** [comment]
@joseneto da uma olhada no servers.json, pelo jeito está com algum caractere inválido para o JSON.
Se não descobrir nada, tenta fazer um backup desse arquivo e apaga ele do ambiente que um novo será gerado e deve resolver o problema.

**Comment by joseneto** [comment]
> @joseneto da uma olhada no servers.json, pelo jeito está com algum caractere inválido para o JSON.
> Se não descobrir nada, tenta fazer um backup desse arquivo e apaga ele do ambiente que um novo será gerado e deve resolver o problema.

Acredito que seja realmente algo relacionado a isso, porque realmente todos os meus servidores desapareceram e não encontro nenhum arquivo  servers.json no meu projeto, o sistema não deveria recriar?

**Comment by joseneto** [comment]
Resolvido o arquivo fica em C:\Users\user\.totvsls

Deletei e o sistema recriou. Muito Obrigado.
