### ISSUE TITLE
MacOS

### ISSUE THREAD

**Issue by pabliuscf** [totvs/tds-vscode#18]
Boa tarde,

Funciona com o MacOS ? Na hora de configurar o caminho do smartclient não está me oferecendo essa possibilidade.

grato,

**Comment by ricardomansano** [comment]
Boa tarde, como descrito nos videos de liberacao a versao para Mac estara disponivel ate final de Julho/2019
https://www.youtube.com/watch?v=MwIu01Ztfvg e https://www.youtube.com/watch?v=Cz4N0XWCXHY

**Comment by fAbReGaS17** [comment]
Bom Dia, Já tem a liberação para Mac ?

**Comment by ricardomansano** [comment]
Bom dia @fAbReGaS17 , sim, ela já esta em testes, até o final do mês devemos jogar para o Padrão,
