### ISSUE TITLE
Error(-1): Falha ao iniciar o SmartClient. Command

### ISSUE THREAD

**Issue by MauroNunes** [totvs/tds-vscode#180]
Boa tarde Galera,

Alguém saberia me dizer porque estou tendo este erro?

![Erro VS Code](https://user-images.githubusercontent.com/56134741/66158717-d33cb080-e5fc-11e9-92c9-204707997ca5.JPG)

**Comment by danielbolognani** [comment]
A configuração do path do Smartclient foi feito manualmente ou pelo wizard?
Verifique no launch.json o path do arquivo (smartclientBin), por ser windows ele deve estar assim:
"smartclientBin": "D:\\Protheus12\\Protheus\\bin\\smartclient\\Smartclient.exe"

**Comment by danielbolognani** [comment]
opa no comentário saiu apenas com uma barra, verifique se está com barras duplas:
D:\\\\Protheus....

**Comment by MauroNunes** [comment]
Olha como esta meu launch.json

{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Totvs Language Debug",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "D:\\Protheus12\\Protheus\\bin\\smartclient\\smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true
		}
	],
	"lastPrograms": [
		{
			"args": [],
			"label": "sigamdi",
			"description": ""
		},
		{
			"args": [],
			"label": "sigaadv",
			"description": ""
		}
	],
	"lastProgramExecuted": "sigaadv"
}

**Comment by danielbolognani** [comment]
Essa situação é bastante atípica, verifique permissão da pasta/arquivo do smartclient.
Se não conseguir, tente me chamar pelo Hangout para tentarmos resolver isso juntos.

**Comment by ricardomansano** [comment]
Bom dia,
Dado o tempo sem interações crio que a configuração sugerida resolveu o problema
Estamos a disposição no caso de novas ocorrencias

**Comment by rpinheirols** [comment]
Olá, bom dia!!

Após atualização do VSCODE, não consigo mais debugar. Pode me ajudar?

**Comment by ricardomansano** [comment]
Bom dia @rpinheirols 

Infelizmente ja tivemos reports (poucos Graças!) que na atualização do VS (não do plugin) algo para de funcionar.

Infelizmente nesses casos é necessário desinstalar o plugin, apagar a pasta .totvsls que fica na sua paste de usuario (veja exemplo abaixo), dai reinstalar o plugin e prosseguir com seu uso

Vc pode salvar o servers.json pra recuperar seus servidores ja configurados

![image](https://user-images.githubusercontent.com/33813921/74144937-740b3000-4bdc-11ea-9b73-ee4f7f4174ce.png)

**Comment by JaniceRodrigues** [comment]
Boa tarde,
Eu estou com esse problema no VSCode ao executar o programa criado via F5, se alguém puder me ajudar eu agradeço.

[Window Title]
Visual Studio Code

[Content]
Error(-1): Falha ao iniciar o SmartClient. Command: C:\Protheus_27\Protheus\bin\SMARTCLIENT\ -DEBUG=11968 -C=_DBG_TEMP "-E=TOTVS12" "-P=U_CAD1"  -M

[Abrir launch.json] [Cancelar]

Esse problema está ocorrendo depois que atualizei o meu appserver para a última versão.

**Comment by lwtnb-wrk** [comment]
@JaniceRodrigues Reveja sua configuração do SmartclientBin pois aparentemente está apontando para o diretorio onde o Smartclient.exe está. 
O SmartclientBin do launch.json deveria ser "C:\Protheus_27\Protheus\bin\SMARTCLIENT\smartclient.exe"

**Comment by JaniceRodrigues** [comment]
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
		
		"advpl.environments":[{
				"smartClientPath":"C:\\Protheus_27\\Protheus\\bin\\SMARTCLIENT\\smartclient.exe",
				"environment": "TOTVS12",
				"includeList": "C:\\Protheus_27\\Protheus\\include",
				"server": "localhost",
				"port": "1257",
				"user": "Admin",
			
			},
			{
				"smartClientPath":"C:\\Protheus_27\\Protheus\\bin\\SMARTCLIENT\\smartclient.exe",
				"environment": "TOTVS12",
				"includeList": "C:\\Protheus_27\\Protheus\\include",
				"server": "localhost",
				"port": "1257",
				"user": "Admin",
			}]
	}
}

**Comment by JaniceRodrigues** [comment]
Bom dia , mesmo realizando essa alteração que me sugeriu o erro ocorre.
[![image](https://user-images.githubusercontent.com/70334075/91737720-d41bf080-eb85-11ea-9ec1-dfc6e0741c57.png)](url)

**Comment by lwtnb-wrk** [comment]
@JaniceRodrigues Ao utilizar a contra-barra é necessário colocar duas contra-barras, ou substitui-las por barras.

**Comment by JaniceRodrigues** [comment]
@lwtnb-wrk  Obrigada pela dica, porém mesmo utilizando dessa forma o erro persiste, eu estou na versão 12.1.27. Instalei tudo novamente do zero sem exito. 

[
![image](https://user-images.githubusercontent.com/70334075/91754131-4c42e000-eb9f-11ea-9a56-48073c8e0407.png)
](url)

**Comment by JaniceRodrigues** [comment]
@lwtnb-wrk Consegui resolver o problema, a versão do meu TOTVS Developer Studio for VSCode  estava com a mais atual e com isso estava acontecendo aquele erro, desinstalei tudo e instalei novamente usando uma versão mais antiga e funcionou, obrigada pela ajuda.

**Comment by JaniceRodrigues** [comment]
@lwtnb-wrk tem alguma dica?

**Comment by JaniceRodrigues** [comment]
@lwtnb-wrk Obrigada pela ajuda, o problema estava relacionado a permissões da máquina.

**Comment by felipecsaraiva** [comment]
Olá, tive o mesmo problema  e aqui o problema era permissão:

Verifique nas propriedades do smartclient.exe, na aba 'Compatibilidade' se a opção 'Executar este programa como administrador' está habilitada. Se estiver, desabilite.

![image](https://user-images.githubusercontent.com/14803717/133608131-5af6431e-812e-4571-8647-77c56bacbdb5.png)

**Comment by ds2u-sergio-artero** [comment]
Boa noite pessoal, somente compartilhando um detalhe que ocorreu comigo, vai que ajuda mais alguém. 

No meu caso, o problema ainda acontecia mesmo com permissão de admin e tendo reinstalado o plugin, conforme o Mansano orientou. O que resolveu foi mudar o diretório do smartclient. Não sei se era algo específico no nome, mas o diretório que estava com erro, estava assim:

"smartclientBin": "C:\\Users\\sergi\\OneDrive\\TOTVS\\SmartClients\\Clientes\\JetFly\\Aeropart_Smartclient_Homologacao_12.1.27\\smartclient.exe",

O diretório que não deu mais erro, ficou assim:
"smartclientBin": "C:\\Users\\sergi\\OneDrive\\TOTVS\\SmartClients\\Clientes\\JetFly\\Smartclient_12_1_27\\smartclient.exe",

Abraços.

**Comment by h2danilo** [comment]
Boa tarde,

Meu Smartclient esta ocorrendo esse erro:
![image](https://user-images.githubusercontent.com/38380833/145880242-c5ec2d03-03af-40de-ac92-72d408b5f137.png)

Segue Config:
![image](https://user-images.githubusercontent.com/38380833/145880655-c1c8d641-81df-4ae9-aaa2-33db3bc1736c.png)


`{
	"version": "0.2.1",
	"includes": [
		""
	],
	"permissions": {
		"authorizationtoken": ""
	},
	"connectedServer": {
		"id": "xxxxxxxxxxxxxx",
		"type": "totvs_server_protheus",
		"name": "dev",
		"port": 1241,
		"address": "xxx.xxx.xxx.xxx",
		"buildVersion": "7.00.191205P",
		"secure": true,
		"includes": [
			"C:\\TOTVS12\\FUTURO\\include"
		],
		"environments": [
			"compilacao"
		],
		"username": "admin",
		"environment": "compilacao",
		"token": "xxxxxxxxxxxxxxxxxx"
	},
	"configurations": [
		{
			"id": "xxxxxxxxxx",
			"type": "totvs_server_protheus",
			"name": "dev",
			"port": 1241,
			"address": "xxx.xxx.xx.xxx",
			"buildVersion": "7.00.191205P",
			"secure": true,
			"includes": [
				"C:\\TOTVS12\\FUTURO\\include"
			],
			"environments": [
				"compilacao"
			],
			"username": "admin",
			"environment": "compilacao",
			"token": "xxxxxxxxxxxxxxxxxxxxxxx"
		}
	],
	"savedTokens": [
		[
			"xxxxxxxxxxxx:compilacao",
			{
				"id": "xxxxxxxxxxxxxxxxxx",
				"token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
			}
		]
	],
	"lastConnectedServer": "xxxxxxxxxxxxxxxxxxxxxxxxx"
}`

dap.log:
[dap.log](https://github.com/totvs/tds-vscode/files/7706695/dap.log)

versao: 
![image](https://user-images.githubusercontent.com/38380833/145881853-ebc15eed-6932-47af-ab96-52d41dde273d.png)

**Comment by danielbolognani** [comment]
@h2danilo o seu smartclientBin está configurado apontando para uma pasta e não para o arquivo smartclient.exe
Verifique em https://github.com/totvs/tds-vscode/wiki#configura%C3%A7%C3%B5es-de-debug como realizar corretamente as configurações de depuração.

**Comment by brodao** [comment]
@h2danilo 

A chave ``smartClientBin`` tem que apontar para o exe e não para a pasta.

**Comment by petersondeveloper** [comment]
Este erro foi solucionado após dar direitos de Administrador ao VSCODE.
Para isso, vá até a pasta de instalação do VSCODE, por exemplo: "C:\Users\peter\AppData\Local\Programs\Microsoft VS Code\Code.exe"

Ao localizar o Code.exe, clique bom o botão direito do mouse sobre o arquivo, e selecione na Propriedades -> Compatibilidade e em seguida Marque a caixa de seleção Executar como Administrador.

![image](https://user-images.githubusercontent.com/16672911/210154373-0a04da46-b3aa-4098-8ae6-15d5b4291c29.png)

**Comment by itacolomymariano** [comment]
Em meu caso estava relacionado ao caminho da pasta de instalação do smartclient, neste caminho havia uma pasta cujo nome tinha espaço vazio, movi a pasta do executável smartclient para um caminho sem espaços vazios, o debug voltou a funcionar. A questão que fica é: Se funcionava antes, porquê deixou de funcionar?

**Comment by lwtnb-wrk** [comment]
Esta questão voltou a ocorrer por questões de novas implementações internas e está sendo trata pela #1059
