### ISSUE TITLE
Não consigo compilar e nem descompilar fontes

### ISSUE THREAD

**Issue by alexandrearume** [totvs/tds-vscode#182]
Bom dia,
Não estou conseguindo compilar e nem descompilar fontes no meu ambiente.
- Ao compilar um fonte aparece a mensagem de erro "Cannot overwrite TOTVS programs."
- Ao descompilar um fonte "One or more programs could not be deleted from RPO."

Eu tentei mudar de pasta de trabalho, verifiquei as permissões da pasta, abri o vscode como administrador e nada.

Versão: Commit de 1.38.1

Poderiam verificar o que pode ser, por favor?

**Comment by charlesreitz** [comment]
Manda um print do fonte que vc está tentando compilar.

**Comment by alexandrearume** [comment]
![vscode](https://user-images.githubusercontent.com/8157617/66213699-b05eda80-e696-11e9-9ffe-baa101851451.PNG)

**Comment by alexandrearume** [comment]
![vscode2](https://user-images.githubusercontent.com/8157617/66213813-e13f0f80-e696-11e9-951d-2174695bb0b7.PNG)

**Comment by charlesreitz** [comment]
Você tem a chave de compilação da TOTVS? Caso não, vc não pode compilar fontes padrões

**Comment by danielbolognani** [comment]
Bom dia, está faltando aplicar/gerar a chave de compilação.
Da mesma forma que o TDS-Eclipse, é necessário autorização através da chave de compilação para poder compilar Function e/ou substituir fontes do padrão.

Para isso utilize o atalho Ctrl-Shift-P e procure por TOTVS:Compile Key, lembrando que a chave do TDS-Eclipse não é compatível com a chave utilizada pelo VsCode, por isso será necessário pedir uma nova chave de compilação.

**Comment by alexandrearume** [comment]
Eu tenho a chave de compilação mas não sabia que tinha diferença entre o Eclipse e VsCode.

E esse problema começou de um dia para o outro, sendo exatamente de quarta para quinta.

**Comment by wkve** [comment]
como faço pra gerar ou conseguir essa Compile Key??
