### ISSUE TITLE
Falha no carregamento da tela welcome

### ISSUE THREAD

**Issue by yurysilva** [totvs/tds-vscode#185]
Eu faço todos os passos do vídeo no caso a primeira opção abro a pasta e o arquivo ".tlpp". E então a apere a opção para por o repositório do smartclient e include, só que quando clico no botão "SAVE/CLOSE" nada acontece, na vdd nem sai da tela de welcome, isso acontece também qundo tento criar um novo servidor, ele não sai da tela de welcome não deixando criar outro servidor.
![image](https://user-images.githubusercontent.com/52840612/66709092-25837d00-ed33-11e9-8806-31badcaf2db3.png)

**Comment by danielbolognani** [comment]
Olá @yurysilva, só garante que vc abriu uma pasta ou workspace antes de completar a tela de welcome.
Se precisar pode fechar, pode abrir novamente com Ctrl-Alt-P e buscar por Welcome.

**Comment by ricardomansano** [comment]
Bom dia,
Dado o tempo sem resposta acredito que a configuração resolveu o problema
Ficamos a disposição no caso de outras ocorrencias
