### ISSUE TITLE
Erro ao abrir o SmartClient ao utilizar o Debug na versão 0.3.16

### ISSUE THREAD

**Issue by willianmfaria** [totvs/tds-vscode#186]
Após atualizar a extensão para a versão 0.3.16, ao utilizar o debug o VS Code conecta no appserver, o console exibe a mensagem "Configuração TDS-DA concluída" porém não abre o SmartClient. Testei as versões 1.39.1 e 1.38.1 do VS Code, ambas apresentam o mesmo erro, ambas funcionam normalmente com a versão 0.3.15 da extensão.

**Comment by lwtnb-wrk** [comment]
@willianmfaria Ja estamos verificando o problema. Grato pelo aviso

**Comment by rodrigomorgon** [comment]
@lwtnb-wrk mesmo problema por aqui... após update do vscode. A build da extensão deu erro

obrigado

**Comment by lwtnb-wrk** [comment]
@willianmfaria @rodrigomorgon Favor testarem a versão 0.3.17 e confirmem se o problema foi resolvido. Grato

**Comment by willianmfaria** [comment]
Resolvido, muito obrigado

**Comment by rodrigomorgon** [comment]
Não consegui fazer update aqui da versão, build falhou. @willianmfaria atualizou manualmente?

**Comment by sandroalves1971** [comment]
Prezados, vejo que vocês passaram por esse problema.
Estou com VS Code atualizado 1.56.2
E a extensão do Totvs Developer Studio na versão 1.0.6

como resolver esse problema?
