### ISSUE TITLE
Indentação de código BeginSQL e EndSQL

### ISSUE THREAD

**Issue by alexandreandradeg** [totvs/tds-vscode#188]
Bom dia, quando se usa BeginSQL e EndSQL o sistema está se perdendo na indentação após o EndSQL.

O EndSQL devia ficar na mesma coluna do BeginSQL, mas ele fica uma tabulação adiante, fazendo com que todo o resto do arquivo o acompanhe.

Existe uma issue (#156) sobre indentação do BeginSQL, mas lá é mencionado outro problema com o comando union all.

![image](https://user-images.githubusercontent.com/53089942/66756519-97151580-ee70-11e9-9a1c-d41e2a6f539b.png)

**Comment by charlesreitz** [comment]
+1

**Comment by ricardomansano** [comment]
Problema solucionado estará disponível na versão superior à 0.3.19

**Comment by ricardomansano** [comment]
Resolvido estara disponivel na versão 0.3.20

**Comment by ricardomansano** [comment]
Bom dia @alexandreandradeg , resouvi o problema da identação na formatação do documento, vai estar disponivel no plugin com versão superior a 0.3.20.

**Comment by alexandreandradeg** [comment]
Bom dia, obrigado, vlw Mansano...
