### ISSUE TITLE
Após atualização do VSCODE o smarclient não abre no debug

### ISSUE THREAD

**Issue by LeonardoRios** [totvs/tds-vscode#190]
Depois da última atualização do VSCODE o smartclient não está mais abrindo no debug.

![Screenshot](https://user-images.githubusercontent.com/6351312/66772993-5dee9c80-ee94-11e9-8ded-a1ac53aab6b6.jpg)
![Screenshot2](https://user-images.githubusercontent.com/6351312/66772996-5dee9c80-ee94-11e9-886d-f879568f0225.jpg)

**Comment by willianmfaria** [comment]
Já tentou a versão 0.3.17 da extensão?

**Comment by LeonardoRios** [comment]
> Já tentou a versão 0.3.17 da extensão?

Ainda não. Irei fazer um teste aqui.

**Comment by danielAlbuquerque** [comment]
Mesmo problema aqui, to usando a versao 0.3.17

**Comment by danielbolognani** [comment]
A principio a versão do VSCode não deveria ter diferença nessa situação.
Verificar se está habilitado a opção de -M (Multiple sessions) habilitada.
Tenta nos passar o arquivo launch.json para analisarmos tbm e, se possível, liga o log do debug no arquivo launch.json:
"logFile": "${workspaceFolder}\\daplog.log"

**Comment by ricardomansano** [comment]
Bom dia,
Passado os dias sem retorno suponho que a atualização tenha resolvido o problema
Ficamos na escuta em caso de novos problemas
