### ISSUE TITLE
Não compila workspace

### ISSUE THREAD

**Issue by Redschenko** [totvs/tds-vscode#191]
Bom dia.

Ao compilar todo o workspace no VSCode, está sendo gerado uma mensagem de erro

_

> [WARN ][SERVER] Debugger - Rollback executed for the repository. Check IDE for details.

_

Este mesmo workspace quando compilado via TDS não apresenta problemas.

Segue em anexo vídeo demonstrando o erro e log gerado pelo VSCode (TOTVS: On Logger Capture)

[1910161003.zip](https://github.com/totvs/tds-vscode/files/3734766/1910161003.zip)

At
Rodrigo de Oliveira

**Comment by ricardomansano** [comment]
Bom dia @Redschenko ,

Consegue fazer um testes com a ultima versão disponibiloizada por gentileza

**Comment by Redschenko** [comment]
Boa tarde @ricardomansano 

Fiz o teste usando a versão 1.40 do VSCode e a versão 0.3.19 da extensão Totvs Developer Studio for VSCode.
Ainda apresenta o mesmo problema.

> [WARN ][SERVER] Debugger - Rollback executed for the repository. Check IDE for details.

At
Rodrigo de Oliveira.

**Comment by DanielYampolschi** [comment]
@Redschenko Faz um favor, posta aqui o conteudo da visao Output com o AdvPl selecionado no combo do lado direito.
E uma duvida, a visão problems possui alguma informação?
Muito obrigado.

**Comment by ricardomansano** [comment]
Bom dia, dado o prazo sem resposta acredito que o problema tenha sido solucionado.
Estaremos aqui caso precise de apoio.
Grato,

**Comment by Redschenko** [comment]
Olá, problema não resolvido.
Na visão output apresenta a mensagem

[Log   - 00:00:00] Start secure compiling c:/TOTVS/WORKSPACES/REDEON/INCLUDES/aplrd.ch (26/121).
[Log   - 00:00:00] Aborting end build (rollback changes).

Baixei o pacote de includes novamente do portal e adicionei ao workspace.
Mesmo assim apresenta o problema.

At
Rodrigo de Oliveira

**Comment by alanFaccin** [comment]
@Redschenko é só não compilar a pasta dos includes, passei pelo mesmo problema, faz um teste aí.

**Comment by Redschenko** [comment]
@alanFaccin 
Como faço para não compilar a pasta de **INCLUDES**?
Utilizo controle de versionamento e ela está dentro do workspace. 
Quando compilo, seleciono a opção "**_Compile All Workspace_**" e com isto ele compila a pasta de INCLUDES.

![Screenshot_6](https://user-images.githubusercontent.com/21147378/69020502-7110f280-0993-11ea-9335-d0b4a2da8276.png)

**Comment by alanFaccin** [comment]
Passei pelo mesmo problema, por hora, organizei meu projeto de maneira que todos os fontes que devem ser compilados estão em um diretório, e os includes não fazem parte dele, ficam acima deste, mas ainda estão dentro do projeto e versionados. A melhor maneira para este problema seria definir quais os diretórios do projeto não devem ser compilados, e vi que já abriram chamado sobre isso...

**Comment by alanFaccin** [comment]
para compilar vc pode utilizar a opção compile file sobre o diretório onde estão todos os sources que vc deseja compilar (sem os includes)

**Comment by Redschenko** [comment]
@alanFaccin Você sabe o número do chamado/issue sobre "definir quais diretórios não devem ser compilados"?

**Comment by Redschenko** [comment]
> A melhor maneira para este problema seria definir quais os diretórios do projeto não devem ser compilados, e vi que já abriram chamado sobre isso...

@alanFaccin Você tem o número do chamado/issue?

**Comment by ricardomansano** [comment]
@brodao , to reabrindo o chamado agora que temos mais informações, coloque nao fila pfv

**Comment by ricardomansano** [comment]
@Redschenko, testa pra mim na 3.0.20 incluindo um nosso appserver, a partir desta versão vc pode definir uma pasta de includes paea cada server configurado, só pra garantir que vs esta usando o CH correto, ficamos na escuta:

![image](https://user-images.githubusercontent.com/33813921/69071228-5331a500-0a08-11ea-93de-9433e6e3898d.png)

**Comment by Redschenko** [comment]
@ricardomansano 

Fiz o teste, porém problema persiste.
Segue em anexo vídeo demonstrando o problema e o log da visão output.
[1911181406.zip](https://github.com/totvs/tds-vscode/files/3859778/1911181406.zip)

**Comment by charlesreitz** [comment]
Eu tive um problema parecido, era na 12.1.17, o RPO estava com mais de  1,6gb, fiz o defrag dele e consegui compilar.

**Comment by Redschenko** [comment]
@charlesreitz 
No meu caso o RPO está com 254MB.

**Comment by ricardomansano** [comment]
@boa tarde, @Redschenko , seu problema agora é realmente a estrutura da sua workspace, retire a pasta include deixando-a fora desta arvore, conforme indicação do @alanFaccin , que já nosso DEV honorário aqui no projeto.

Esse reorganização resolverá seu problema
Grato pelo report

**Comment by rodsmello** [comment]
Boa tarde! 
Encontro este mesmo problema em diretórios/projetos que não possuem "includes" na estrutura.
Há alguma outra divergência na estrutura do projeto que gere este erro?

**Comment by lwtnb-wrk** [comment]
@rodsmello Favor abrir uma outra issue e postar o maximo de detalhes do seu problema.
