### ISSUE TITLE
Debug com dois arquivos com o mesmo nome

### ISSUE THREAD

**Issue by alissonph** [totvs/tds-vscode#192]
Ao tentar debugar com dois fontes com nomes idênticos ele "se perde" e encontra somente o primeiro arquivo.

Ex: Tenho dois arquivos com o nome teste.prw

Se eu colocar breakpoint no primeiro arquivo ele entra normal, se eu colocar breakpoint somente no segundo arquivo ele ignora.

No TDS tem uma opção de identificar fontes duplicados na workspace e selecionar qual utilizar para o debug.

Já existe essa função no plugin? Se não fica essa sugestão de melhoria.

**Comment by danielbolognani** [comment]
@alissonph hoje não é tratado dois arquivos com o mesmo nome, porém, se o arquivo em questão possui breakpoint, esse arquivo terá sempre prioridade na busca.

**Comment by ricardomansano** [comment]
Bom dia @alissonph,

Não utilize fontes com o mesmo nome, essa é uma pratica que inviabiliza o controle de depuração

Grato,

**Comment by Nhaca** [comment]
Ricardo, mas no caso de trabalharmos com vários "projetos" na workspace, como faremos? Isso era bem comum no TDS.
Obrigado.

**Comment by Nhaca** [comment]
@ricardomansano, no TDS trabalhávamos com vários diretórios na workspace do cliente (ex. producao, dev, hom) como faremos neste caso? Não há nenhuma solução?

**Comment by ricardomansano** [comment]
@Nhaca , isso sempre gerou problemas, foi sorte nao ter pego isso no Eclipse, é completamente desaconselhável este modelo, então deve resolver em sua estrutura de projetos.
Lamento
