### ISSUE TITLE
Debug cai quando chega no Breakpoint

### ISSUE THREAD

**Issue by jvvasquesn** [totvs/tds-vscode#193]
Quando chega no breakpoint o VS desconecta e mas a conexão fica ativa no servidor e o smartclient aberto travado.
A conexão cai pois é possível abrir um outro degub mesmo com o smartclient anterior ainda aberto.

**Comment by danielbolognani** [comment]
Ola, isso acontece sempre e em qualquer breakpoint? 
Poderia testar com a última versão disponível e ligar o log do DAP?
Para ligar o log, adicione a seguinte linha:
"logFile": "${workspaceFolder}\\daplog.log"
dentro do seu ambiente de debug no arquivo launch.json

Com isso, após acontecer o problema nos envie o arquivo daplog.log que vai ser criado na mesma pasta raiz do workspace.

**Comment by jvvasquesn** [comment]
Boa tarde.

Aparentemente quando posiciono o mouse em cima de uma variável tipo array é
quando cai a conexão.

atenciosamente.

Em sex, 18 de out de 2019 às 17:17, Daniel Otto Bolognani <
notifications@github.com> escreveu:

**Comment by jvvasquesn** [comment]
Bom dia

Outra situação, quando usei o "DEBUG CONSOLE", quando dei Enter ele caiu a
conexão

[image: image.png]

Em sex, 18 de out de 2019 às 17:17, Daniel Otto Bolognani <
notifications@github.com> escreveu:

**Comment by danielbolognani** [comment]
@jvvasquesn Tenta ligar o log para termos mais informações por favor:
"Para ligar o log, adicione a seguinte linha:
"logFile": "${workspaceFolder}\daplog.log"
dentro do seu ambiente de debug no arquivo launch.json"

**Comment by jvvasquesn** [comment]
Eu enviei em anexo nos emails anteriores.

Em qua, 23 de out de 2019 às 14:13, Daniel Otto Bolognani <
notifications@github.com> escreveu:

**Comment by danielbolognani** [comment]
Os anexos não são enviados para o github, se puder, por favor faça o upload em algum serviço (onedrive, google drive, etc..).

**Comment by jvvasquesn** [comment]
Segue
https://drive.google.com/drive/folders/15MXC5dO6nfsnkbUtnzZleeDRC45_IxU3?usp=sharing

Em qui, 24 de out de 2019 às 09:20, Daniel Otto Bolognani <
notifications@github.com> escreveu:
