### ISSUE TITLE
Customização de coloração

### ISSUE THREAD

**Issue by keinou** [totvs/tds-vscode#196]
Permitir alterar a coloração do fonte, também destacando o BeginSQL quando existente.
![image](https://user-images.githubusercontent.com/20158261/67436486-7b221a00-f5bc-11e9-8d63-862eeb8f9245.png)

Para fazer isso hoje é preciso alterar o fonte do plugin e também criar um novo tema para mudanças pequenas.

**Comment by ricardomansano** [comment]
Bom dia @keinou 
Agradecemos a sugestão mas ela não pe interessante para o projeto no momento
