### ISSUE TITLE
Porque não consigo debugar o VS Code

### ISSUE THREAD

**Issue by MauroNunes** [totvs/tds-vscode#197]
Bom dia Galera,

Alguém poderia me explicar porque nao consigo iniciar o Debug?
![Erro Vc Code](https://user-images.githubusercontent.com/56134741/67481693-bbbf7900-f638-11e9-9f4c-2b8f706d5cd5.JPG)
![Launch](https://user-images.githubusercontent.com/56134741/67481695-bbbf7900-f638-11e9-8f00-97ff7202543a.JPG)

**Comment by danielbolognani** [comment]
@Mauro, já tem outra issue que vc mesmo abriu sobre esse problema, por favor acompanhe por ela (#180)

**Comment by MauroNunes** [comment]
Bom dia Daniel, 
Desculpe mano realmente abri, porem nao localizei no forum onde encontrar
Pode me ajudar a se localizar

**Comment by MauroNunes** [comment]
Achei o outro post, mandei nele, olha se consegui me ajudar @danielbolognani
