### ISSUE TITLE
Abrir Projeto no Developer Studio

### ISSUE THREAD

**Issue by crisrud39** [totvs/tds-vscode#198]
É possível abrir o antigo arquivo .PRJ ou algum plugin que converta em workspace o projeto do TDS ou Developer Studio. Vi que no VsCode abre as pastas/arquivos, inclusive os arquivos .bak

**Comment by ricardomansano** [comment]
Bom dia @crisrud39 
Essa feature não é interessante para o projeto, mas agradecemos a sugestão

**Comment by Jona-than4** [comment]
> Bom dia @crisrud39
> Essa feature não é interessante para o projeto, mas agradecemos a sugestão

Bom dia @ricardomansano
Poderia me indicar como devo iniciar o uso do VSCode, como recomenda fazer a migracao dos fontes do projeto do TDS?

**Comment by ricardomansano** [comment]
@Jona-than4, bom dia,

O VSCode trabalha com diretórios, ele não tem o conceito de workspace e links do Eclipse

Basta abrir a pasta raiz de seu projeto, não é necessário qqer tipo de migração.

**Comment by Jona-than4** [comment]
@ricardomansano Obrigado, e pra subversão utiliza extensão Tortoise ou alguma outra?
