### ISSUE TITLE
Mensagem de alerta sobre fontes com data mais recente ao aplicar patchs

### ISSUE THREAD

**Issue by robsonrosilva** [totvs/tds-vscode#2]
Apliquei o patch de correção usando o IDE TDS e apareceu a mensagem que existe fontes no RPO com data mais recente que os fontes do Patch e com as opções de escolher (Todos ou Somente os mais Recentes), ao aplicar esse mesmo Patch pelo VsCode a mensagem não é apresentada.

**Comment by matheus-sales** [comment]
Obrigado @robsonrosilva vamos verificar.

**Comment by matheus-sales** [comment]
Criamos um checkbox na tela de aplicação de patch para forçar ou não a aplicação de arquivos mais antigos. Quando marcado, o patch forçara a aplicação mesmo com fontes mais antigos que o RPO. Quando desmarcado, forçará a aplicação sem os fontes mais antigos.

Estará disponível na próxima versão. 

Obrigado
