### ISSUE TITLE
Exibir tabelas e conteúdos

### ISSUE THREAD

**Issue by guilhermebigois** [totvs/tds-vscode#20]
Na extensão [advpl-vscode](https://github.com/totvs/advpl-vscode/wiki/Configura%C3%A7%C3%A3o) temos a opção de exibir as tabelas (advpl.debug_showTables: mostra as tabelas abertas), porém esta opção não está disponível na extensão tds-vscode.

Seria possível implementar? Pois a verificação do estado das tabelas é de grande valia no momento da depuração dos fontes (principalmente no uso de pontos de entrada).

Segue um vídeo em anexo ilustrando a solicitação: [ISSUE_20.zip](https://github.com/totvs/tds-vscode/files/3198259/ISSUE_20.zip)

**Comment by matheus-sales** [comment]
@guilhermebigois  Colocamos em nosso Roadmap para implementação. 

Obrigado!

**Comment by DanielYampolschi** [comment]
@wfsouza Ja temos a issue e ja esta no roadmap, nao deve demorar pra sair.

**Comment by DanielYampolschi** [comment]
Ola, a implementação da exibição de tabelas foi feita e estará disponível na próxima atualização. Teremos uma documentação sobre o processo, mas apenas para deixar registrado o que foi feito:

1 - A sincronização de tabelas pode ser habilitada pelo parâmetro "enableTableSync" por "launcher". O padrão é true, mesmo para "launchers" já existentes que não possuem a chave explicitamente.

2 - A sincronização pode ser ligada e desligada durante a depuração pelo comando: "TOTVS: Toggle table sync". Uma notificação aparecerá tanto no console Advpl, como em um diálogo (Dependendo da configuração de exibição de diálogos).

3 - As tabelas sincronizadas serão mostras na visão de variáveis, em uma raiz com o nome "Table", ou seja, como um escopo de variáveis. E esse escopo, da mesma forma que os outros, só aparecerá se existir algum conteúdo.

4 - A visão "Debug Console" consegue mostrar o conteúdo de uma tabela, da mesma forma que é feito com Arrays e Objetos, mas para isso é necessário informar o comando na seguinte forma: "table:<table_name>". Por exemplo: table:SM0 (PS. o comando "table:" é case Insensitive)
