### ISSUE TITLE
command 'totvs-developer-studio.add' not found

### ISSUE THREAD

**Issue by PedroPedrada** [totvs/tds-vscode#201]
Pessoal, boa noite!

Estou com problemas no meu vsCode!

Ao iniciá-lo agora pela noite, abri minha workspace e notei que todos os meus servidores desapareceram!! 

E ao tentar incluir manualmente apresentou a mensagem abaixo:

![vsCode](https://user-images.githubusercontent.com/48094977/68065738-33159c80-fd0c-11e9-8f3f-9b17a98f0cc0.png)

Desinstalei/instalei a extensão da Totvs;
Desinstalei/Instalei o vsCode;

E mesmo assim o problema persiste!

Por acaso alguém já passou por essa situação?

Obrigado.

**Comment by caiadofelipe** [comment]
Boa tarde.

Esse problema aconteceu comigo também depois da instalação da 0.3.18, na 0.3.17 não acontece.
Voltei a versão e o problema parou de ocorrer.

Abraço

**Comment by PedroPedrada** [comment]
Boa tarde!

@caiadofelipe, obrigado pelo retorno!! Ia interagir na issue agora relatando isso!! rsrs

Fiz esse mesmo procedimento, reinstalei a versão anterior voltou a funcionar normalmente!

Abraço!

**Comment by EvaldoBatista** [comment]
Pessoal, estou com esse problema, e não sei como obter a versão anterior (0.3.17) da extensão, como faço para instalar a versão anterior ?

**Comment by caiadofelipe** [comment]
> Pessoal, estou com esse problema, e não sei como obter a versão anterior (0.3.17) da extensão, como faço para instalar a versão anterior ?

@EvaldoBatista,

clique em cima da extensão -> Instale outra versão
![image](https://user-images.githubusercontent.com/49681823/68075103-3b102380-fd82-11e9-8f30-b4cd1607d040.png)

Depois escolha a 0.3.17
![image](https://user-images.githubusercontent.com/49681823/68075107-482d1280-fd82-11e9-987b-b23f5f977283.png)

**Comment by EvaldoBatista** [comment]
Muito obrigado, tão simples e eu não sabia fazer. era exatamente o que eu precisava, tudo voltou a funcionar.

**Comment by danielbolognani** [comment]
Pessoal, deu algum problema na hora que subimos a última atualização. Quem estiver com o mesmo problema pode voltar para a 0.3.17 por enquanto, segunda feira vamos resolver isso.

**Comment by danielbolognani** [comment]
Regeramos o pacote e publicamos novamente, corrigido na versão 0.3.19.

**Comment by danielAlbuquerque** [comment]
To usando a 0.3.23 e o problema ainda acontece

**Comment by thiagocomelli** [comment]
Estou usando a 1.0.1 e o problema permanece.
