### ISSUE TITLE
Adicionar Server - Totvs Developer Studio for VsCode

### ISSUE THREAD

**Issue by eduardofm1** [totvs/tds-vscode#202]
Boa noite!

Estou tentando adicionar um novo server ou clicar em Configure Server View na extensão Totvs Developer Studio for VsCode porém aparece as mensagens abaixo:

command 'totvs-developer-studio.add' not found
command 'totvs-developer-studio.config' not found

Uso ambiente windows. 
Isso aconteceu depois que adicionei o Git e depois vinculei ao GitHub para versionar nossos projetos.

Podem nos ajudar ? 
Obrigado.
![erro_add_server](https://user-images.githubusercontent.com/57256971/68078568-492c6700-fdb7-11e9-87fe-2aaa052ead1c.png)

**Comment by eduardofm1** [comment]
Voltei para versão 0.3.17 e deu certo.

**Comment by cfasilva** [comment]
Mesmo problema aqui após atualizar para versão **0.3.19**.

**Comment by danielbolognani** [comment]
> Mesmo problema aqui após atualizar para versão **0.3.19**.

Por favor verifique se nenhuma outra extensão está em conflito com a Totvs Developer Studio for VSCode, se vc possuir duas extensões que tratam arquivos advpl esse tipo de problema pode ocorrer.

**Comment by danielbolognani** [comment]
Recebi uma informação de usuário que continuou com o mesmo problema na 0.3.19, ele apenas desinstalou a extensão e instalou novamente a 0.3.19 e resolveu. Se precisar pode me chamar pelo hangout.

**Comment by cfasilva** [comment]
@danielbolognani 

Reinstalei e mesmo assim não funcionou!

Porém após executar o projeto no **TDS** e reabri-lo no **VSCODE** milagrosamente a lista foi restaurada. Estou compartilhando pra ajudar quem passar por essa situação.

Obrigado pela atenção.

**Comment by betteher** [comment]
Instalei a 0.3.19, 0.3.17 e a ultima 0.3.23 e o erro ao tentar incluir servidores persiste.
command 'totvs-developer-studio.add' not found
command 'totvs-developer-studio.config' not found

**Comment by danielbolognani** [comment]
@betteher Conforme comentários anteriores, verifique se não tem nenhuma outra extensão instalada, caso positivo, faça um teste deixando apenas a extensão Totvs Developer Studio instalada.

**Comment by lwtnb-wrk** [comment]
Não utilizem issues fechadas para indicar problemas. 
Indiquem o passo a passo para reprodução e a maior quantidade de informações possíveis, pois não temos como adivinhar quais tipo de ambiente vocês estão utilizando.
