### ISSUE TITLE
Monitor de usuários

### ISSUE THREAD

**Issue by caiadofelipe** [totvs/tds-vscode#203]
Gostaria de saber se existe alguma previsão de monitor no VSCODE, com isso conseguimos parar de usar o TDS.

Abraço,

**Comment by cfasilva** [comment]
@caiadofelipe 

Essa é uma funcionalidade que também aguardo com expectativa pra largar de vez o **TDS**, mas caso não saiba existe aqui mesmo o projeto **TDS-Monitor**: https://github.com/totvs/tds-monitor

**Comment by caiadofelipe** [comment]
@cfasilva, eu até vi esse projeto ai, mas muito limitado, não atualiza os usuários, não dá pra desconectar os usuários, não conseguimos excluir servidores.
Se ele evoluir vai ficar muito bom.

Abraço,

**Comment by ricardomansano** [comment]
Bom dia, ainda não temos previsão de liberação, mas deve ocorrer no 1o trimestre de 2020
Manteremos vcs informados
Grato,
