### ISSUE TITLE
Vocês pode criar uma configuração tipo "file.exclude" para configurar os arquivos a serem compilados

### ISSUE THREAD

**Issue by EvaldoBatista** [totvs/tds-vscode#204]
Ola pessoal, 

Primeiramente gostaria de agradecer, a todos vocês. TDS para Vs-Code está mito bom. estão fazendo um ótimo trabalho.

No entanto, eu tenho um cliente que tem um portal versionado junto com o projeto Protheus no GitHub, este portal, não precisa ser compilado e sempre que vou compilar o projeto inteiro, tenho que ficar selecionando as pastas que quero compilar. Se houvesse uma opção do tipo "file.exclude" para o ADVPL, eu poderia deixar isso configurado e compilar todo o projeto.

Aguardo seus comentários

**Comment by danielbolognani** [comment]
Muito obrigado pelo elogio.
Pelo projeto ser _open source_ e colaborativo, aceitamos também ajuda para esse tipo de solicitação. Se quiser/puder nos ajudar pode gerar um pull request que analisaremos.

**Comment by ricardomansano** [comment]
Bom dia,
Dado o prazo da ultima interação, sem a submissão de um pull request, agredecemos a sugestão encerrando a issue.
