### ISSUE TITLE
Compilação no 12.1.25 64 Bits

### ISSUE THREAD

**Issue by FabioPonte** [totvs/tds-vscode#205]
Tentei compilar na versão 64 Bits (Lobo-Guara) e o Vs Code não realizou a compilação.

**Comment by danielbolognani** [comment]
Verifique sua pasta de includes, quando o VSCode não mostra erro, é por causa de include faltando

**Comment by ricardomansano** [comment]
Bom dia, dados o prazo sem retorno acredito que o problema tenha sido solucionado
Havendo outras questões estaremos aqui pra apoiar
Grato
