### ISSUE TITLE
Erro na Conexão em Servidor na versão 12.1.25

### ISSUE THREAD

**Issue by alanFaccin** [totvs/tds-vscode#207]
Ao configurar uma conexão com um servidor na versão 12.1.25,  não efetua a conexão, apresenta uma mensagem de erro 'Cloud not connect to server'.

<img width="2515" alt="Screen Shot 2019-11-05 at 17 14 53" src="https://user-images.githubusercontent.com/9438826/68242820-f5589280-ffef-11e9-91e1-b35acb2f4f39.png">

Se conectar no meso server pelo TDS ele funciona corretamente:

<img width="2045" alt="Screen Shot 2019-11-05 at 17 16 50" src="https://user-images.githubusercontent.com/9438826/68243053-74e66180-fff0-11e9-9c4f-e90f4b0dc648.png">

Sistema operacional utilizado:

<img width="588" alt="Screen Shot 2019-11-05 at 17 17 34" src="https://user-images.githubusercontent.com/9438826/68243074-7fa0f680-fff0-11e9-8b5c-3eb610b823e6.png">

***  TOTVS S/A  ***
***  www.totvs.com.br  ***
* TOTVS - Build 7.00.170117A - Jun 28 2019 - 11:16:56 
* Build: 64 bits
* SVN Revision: 23527
* Build Version: 17.3.0.13

Starting (Totvs - [HOMOLOGA - APP_DEV])...
Please wait...
*** SERVER BUILD WITH CLASS INSTANCE RUNNING CHECK

Podem me auxiliar ?

**Comment by charlesreitz** [comment]
Estou com o mesmo problem mas no windows, tive que voltar a versão do TDS para conseguir conectar, e tirei o update automático do vscode

**Comment by alanFaccin** [comment]
@charlesreitz  qual versão você está utilizando ?

**Comment by danielbolognani** [comment]
Pessoal, verifiquem se no servers.json a chave "secure" está com 1. Se estiver, mudem para 0 manualmente que deve resolver. A solução definitiva já está feita e estará disponível na versão 0.3.20

**Comment by alanFaccin** [comment]
Fiz o teste alterando o secure para 0 e funcionou, aguardo a liberação da 0.3.20 com a correção, obrigado !
