### ISSUE TITLE
Erro ao adicionar servidor

### ISSUE THREAD

**Issue by lucasbrustolin** [totvs/tds-vscode#208]
** Erro ao adicionar servidor **

Mensagem: Cannot read property 'length' of undefined

Versão: 0.3.19 

Obs: Foi feito teste limpando os arquivos configuração e reinstalando novamente o VsCode + extensão Totvs Advpl.

![01](https://user-images.githubusercontent.com/29780876/68323747-d23bea80-00a4-11ea-9ac6-b2723381d562.PNG)
![02](https://user-images.githubusercontent.com/29780876/68323757-d8ca6200-00a4-11ea-911d-937dae0c73cc.PNG)

![image](https://user-images.githubusercontent.com/29780876/68323829-fbf51180-00a4-11ea-920a-93d9c7ac6e21.png)

**Comment by lwtnb-wrk** [comment]
@lucasbrustolin Imagino que tenha editado o arquivo manualmente e apagou apenas toda a seção "configurations" do arquivo servers.json, correto?
Se for o caso, experimente adicionar novamente a linha:
`"configurations": []`
e acrescentando um virgula no final da secao anterior conforme necessidade.
De qualquer forma faremos uma proteção para evitar este problema novamente.
Se não for o caso nos informe o passo a passo para reproduzir o problema.
Grato

**Comment by EVSolutionSystem** [comment]
Boa noite, amigos. Podem dar uma força?

Comigo aconteceu a mesma coisa. Formatei minha maquina e instalei o vscode, porem ao tentar adicionar um servidor de cara aparece a mensagem: _**Cannot read property 'id' of undefined**_

Você informa todos os dados para configurar o servidor e os botões de salvar não funcionam...

Meu server.json tem este ponto mencionado e mesmo assim ocorre o erro também. Já reinstalei unas 5 vezes

{
	"version": "0.2.0",
	"includes": [
		""
	],
	"permissions": {
		"authorizationtoken": ""
	},
	"connectedServer": {},
	"configurations": []
}

**Comment by lucasbrustolin** [comment]
Boa noite.

   Alguns analistas relataram este problema hoje, parece que houve alguma atualização do plugin ADVPL / VsCode.
   Faça o downgrade do plugin e veja se resolve o problema até que tenhamos nova atualização.

Atenciosamente.

De: EVSolutionSystem <notifications@github.com>
Enviada em: quinta-feira, 9 de julho de 2020 23:03
Para: totvs/tds-vscode <tds-vscode@noreply.github.com>
Cc: brustolin <lucasbrustolin@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [totvs/tds-vscode] Erro ao adicionar servidor (#208)


Boa noite, amigos. Podem dar uma força?

Comigo aconteceu a mesma coisa. Formatei minha maquina e instalei o vscode, porem ao tentar adicionar um servidor de cara aparece a mensagem: Cannot read property 'id' of undefined

Você informa todos os dados para configurar o servidor e os botões de salvar não funcionam...

Meu server.json tem este ponto mencionado e mesmo assim ocorre o erro também. Já reinstalei unas 5 vezes

{
"version": "0.2.0",
"includes": [
""
],
"permissions": {
"authorizationtoken": ""
},
"connectedServer": {},
"configurations": []
}

**Comment by lwtnb-wrk** [comment]
@EVSolutionSystem @lucasbrustolin veja #434
