### ISSUE TITLE
Compilar File/Workspace

### ISSUE THREAD

**Issue by eduardofm1** [totvs/tds-vscode#209]
Boa tarde!

Quando compilo uma pasta ou a workspace toda o VsCode não consegue compilar e trava o RPO deixando um processo em execução.

Podem me ajudar com isso ?

Obrigado.
![compilar_workspace](https://user-images.githubusercontent.com/57256971/68336006-4635bd00-00bc-11ea-9f93-dfc005ca0105.png)
![Sem título](https://user-images.githubusercontent.com/57256971/68336007-46ce5380-00bc-11ea-95a2-077e2ab2c045.png)

**Comment by brodao** [comment]
Ola @eduardofm1 

Quando a conexão "presa" isso é normal. Na verdade o TDS-VSCode mantém uma conexão permanente com o servidor.

Favor repetir o teste (depois de você se certificar que esta atualizado) e anexar o console log do protheus no momento da ocorrência.

Certifique-se que você é o único usuário do ambiente e que não tenha nenhuma outra sessão (na imagem de tela enviada, vemos que há duas conexões. Apesar de serem ambientes diferentes, certifique-se que não apontam para o mesmo arquivo RPO. 

No aguardo.

**Comment by ricardomansano** [comment]
Bom dia, dado o prazo sem resposta acredito que o problema tenha sido solucionado.
Estaremos aqui caso precise de apoio.
Grato,
