### ISSUE TITLE
Iniciar conectado no ambiente anterior

### ISSUE THREAD

**Issue by guilhermebigois** [totvs/tds-vscode#21]
Na extensão [advpl-vscode](https://github.com/totvs/advpl-vscode/wiki/Configura%C3%A7%C3%A3o) quando o Visual Studio Code é aberto, ela já mantem o último ambiente conectado como ativo, não tendo a necessidade de informar ambiente, usuário e senha novamente.

Seria possível implementar esse recurso? Pois o mesmo agilizava o início da depuração.

Segue um vídeo ilustrando a solicitação: [ISSUE_21.zip](https://github.com/totvs/tds-vscode/files/3198185/ISSUE_21.zip)

**Comment by matheus-sales** [comment]
Relacionamos o chamado #5 , não fazemos a auto conexão porque não guardamos o usuário e senha. Mas vamos reavaliar a salva e a reconexão. 

Obrigado
