### ISSUE TITLE
Erro ao conectar Servidor Protheus

### ISSUE THREAD

**Issue by caiadofelipe** [totvs/tds-vscode#212]
Está acontecendo erro ao conectar no servidor do Protheus
Error running command totvs-developer-studio.connect: Running the contributed command: 'totvs-developer-studio.connect' failed.. This is likely caused by the extension that contributes totvs-developer-studio.connect.

1- Criar Servidor
2- Conectar ao servidor

**Screenshots**
![image](https://user-images.githubusercontent.com/49681823/68590563-99699000-046d-11ea-8b2f-9ca201ef04f9.png)

 - OS/Architecture: Windows 7 - 64 bits

**Comment by claudio0107** [comment]
![image](https://user-images.githubusercontent.com/56644354/68606171-a0ec6180-048c-11ea-8ded-0752aca94787.png)

**Comment by claudio0107** [comment]
![image](https://user-images.githubusercontent.com/56644354/68606334-03ddf880-048d-11ea-9097-5001bd9426f4.png)
![image](https://user-images.githubusercontent.com/56644354/68606422-2f60e300-048d-11ea-9626-d4535f832480.png)
![image](https://user-images.githubusercontent.com/56644354/68606468-48699400-048d-11ea-98a7-8191928d7b68.png)
![image](https://user-images.githubusercontent.com/56644354/68606487-53242900-048d-11ea-86b7-fce4e2b3ef65.png)
depois que coloco manualmente a versão ele pede pra conectar enviroment, user e senha, depois disso aparece o erro de autheticidade

**Comment by danielbolognani** [comment]
Pessoal, verifiquem se no servers.json a chave "secure" está com 1. Se estiver, mudem para 0 manualmente que deve resolver. A solução definitiva já está feita e estará disponível na versão 0.3.20

**Comment by claudio0107** [comment]
Deu certo Daniel, obrigado.

**Comment by caiadofelipe** [comment]
@danielbolognani, no meu caso não deu certo.

**Comment by danielbolognani** [comment]
@caiadofelipe Verifique se está aberta uma pasta ou workspace de trabalho antes de se conectar.
Isso é necessário para o correto funcionamento do plug-in.
Verifique também se não está instalado outro plug-in que faça o mesmo que o nosso, caso positivo desabilite-o(s) e tente novamente.

**Comment by caiadofelipe** [comment]
@danielbolognani, muito obrigado, era isso mesmo.
Tinha esquecido deste pequeno detalhe.

**Comment by raphasferreira** [comment]
Está dando erro já na instalação do plugin aqui pra mim:
Starting client failed
Error: spawn UNKNOWN
	at ChildProcess.spawn (internal/child_process.js:394:11)
	at Object.spawn (child_process.js:553:9)

**Comment by lwtnb-wrk** [comment]
@raphasferreira Abra uma nova issue com o maior numero de informacao possivel. Grato
