### ISSUE TITLE
Conexão ao vscode com appserver

### ISSUE THREAD

**Issue by claudio0107** [totvs/tds-vscode#213]
segue o appserver conforme o mansano pediu meu appserver.ini.

[root@srvaplic ~]# cat /totvs12/protheus/bin/app25_compile/appserver.ini
[compilacao]
SourcePath=/totvs12/protheus/apo/compilacao25/
RootPath=/totvs12/protheus_data/
StartPath=/system/
x2_path=
RpoDb=top
RpoLanguage=Portuguese
RpoVersion=120
LocalFiles=CTREE
Trace=0
localdbextension=.dtc
TopMemoMega=2
PictFormat=DEFAULT
DateFormat=DEFAULT
RegionalLanguage=BRA
TopDataBase=MSSQL
TopServer=192.168.1.12
TopALIAS=prod25
TopPORT=7890
topcontype=tcpip
Helpserver=192.168.1.9:8889
#theme=sunset
StartSysInDB=1
#IXBLOG=NORUN

[Drivers]
Active=TCP

[TCP]
TYPE=TCPIP
Port=1205

[General]
INSTALLPATH=/totvs12/protheus_data/
;CTREEMODE=server
;CTREEMODE=LocalFiles
CONSOLELOG=0
Segmento=pZFVvWym
Serie===AV
CONSOLEFILE=/totvs12/protheus_data/log/P12.1.025.log
maxStringSize=10
MaxQuerySize=31960
CheckSpecialKey=0
BuildKillUsers=1
PowerSchemeShowUpgradeSuggestion=0
DebugThreadUsedMemory=1
ReleaseInactiveConn=60

[TDS]
ALLOWEDIT=*
allowApplyPatch=*
ENABLEDISCONNECTUSER=*
ENABLESENDMESSAGE=*
ENABLEBLOCKNEWCONNECTION=*
ENABLESTOPSERVER=*

[LICENSECLIENT]
server=192.168.1.12
port=5555

[Service]
Name=APPCOMPILE
DisplayName=APPCOMPILE

[HTTP]
PORT=8888
InstanceName=HTTP Instance
Enable=0
PATH=/totvs12/protheus/Central_de_Ajuda/
Environment=compilacao

**Comment by danielbolognani** [comment]
Boa tarde, por favor utilize a issue #212 não termos duplicidade.

**Comment by claudio0107** [comment]
Após recriar a conexão com o server no vs, ele não traz a build version, informo manualmente, ele pede ambiente, id e senha, mais não conecta.

![image](https://user-images.githubusercontent.com/56644354/68606664-a8603a80-048d-11ea-8781-f125dfac5c6c.png)

**Comment by claudio0107** [comment]
> 
> 
> Boa tarde, por favor utilize a issue #212 não termos duplicidade.

ok daniel.
