### ISSUE TITLE
Ao fazer Debug a conexão cai sem erro e o SmartClient fica aberto no Ubuntu

### ISSUE THREAD

**Issue by jvvasquesn** [totvs/tds-vscode#215]
**Describe the bug**
Quando estamos no Debug e está parado em um BreakPoint, ao começar a analisar as variaveis a conexão cai sem erro e o SmartClient fica travado.

**To Reproduce**
1. Iniciar um Debug
2. Ao parar em um Breakpoint analisar as variáveis
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Linux 4.4.0-166-generic #195-Ubuntu SMP Tue Oct 1 09:35:25 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Appserver (please complete the following information):**
 - Build (with date): 7.00.170117A - Jun 28 2019 - 13:39:54 
 - OS/Architecture: Linux version 3.10.0-693.50.3.el7.x86_64 (mockbuild@x86-038.build.eng.bos.redhat.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) #1 SMP Sat Jun 15 17:39:46 UTC 2019
 - Build Version: 17.3.0.13

**Additional context**
T-Cloud

**Comment by danielbolognani** [comment]
@jvvasquesn chegou a testar essa situação com a versão 0.3.20? Teve correções relativas ao debug no Linux nessa última versão liberada

**Comment by jvvasquesn** [comment]
Sim atualizei hoje pela manhã

Em qua., 13 de nov. de 2019 às 16:48, Daniel Otto Bolognani <
notifications@github.com> escreveu:

**Comment by ricardomansano** [comment]
Boa tarde @jvvasquesn , 
Só confirma o seguinte:

-Versão do Ubuntu
-Timeout esta ligado no AppServer
-Se sim, pra quanto tempo? Já que pode ser o seu problema
-Acontece em toda conexão ou esporádico?

**Comment by jvvasquesn** [comment]
Bom dia.
Estou usando o Ubuntu 16.04 LTS.
O Timeout não esta ligado.
Acontece toda vez. Assim que tendo ver o valor da variável ou função cai.

**Comment by ricardomansano** [comment]
@jvvasquesn , agora vc falou algo que chamou minha atençãp: A variavel que esta analisando por acaso é um Json?

**Comment by jvvasquesn** [comment]
Não, é variavel qualquer, contendo texto ou numero.
Um outro exemplo.
If Posicione("SA1",1, xFilial("SA1") + '00000101',"A1_EST") = 'SP'
EndIf

Se eu marco com o _Posicione("SA1",1, xFilial("SA1") + '00000101',"A1_EST")_ e coloco o mouse em cima para ver o resultado ele cai.

**Comment by DanielYampolschi** [comment]
@jvvasquesn Me tira algumas duvidas por favor.
1 - Esse comportamento acontece apenas se você parar o mouse em cima da variável ou acontece também ao usar a visão de "Debug Console" ou "Watch"?
2 - Pelos comentários acima na ficou claro se isso acontece com absolutamente qualquer variável, ou apenas caso você tente avaliar uma função que contenha texto ou numero por exemplo. 

Faz um favor tambem, no arquivo launch.json (O qual pode ser acessado clicando no icone de engrenagem na perspectiva de debug, ao lado do nome do executor), adiciona o seguinte parametro: "logFile": "${workspaceFolder}\\daplog.log" , execute a operação até ocorrer o erro e me envie o arquivo daplog.log que deve ser gerado na mesma raiz do seu workspace.

**Comment by jvvasquesn** [comment]
1 - Com o mouse em cima e no "Debug Console", com o "Watch" eu não testei.
2 - Qualquer variável ou função.

Atualizei hoje o VSCode
Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:54:40.719Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 4.4.0-169-generic

[daplog.log](https://github.com/totvs/tds-vscode/files/3897265/daplog.log)

**Comment by lwtnb-wrk** [comment]
@jvvasquesn Foi liberada uma nova versão com alterações diversas em relação ao debug, por favor verifique se nesta ultima versão o problema foi resolvido.
Grato.

**Comment by jvvasquesn** [comment]
Bom dia.
Atualizei tudo mas mesmo assim, quando estamos "degubando" ao colocar o mouse em cima de uma variável a conexão cai

**Comment by jvvasquesn** [comment]
Boa tarde!
Tivemos alguma evolução?

**Comment by ricardomansano** [comment]
Boa tarde @jvvasquesn , não temos evolução simplesmente porque nao conseguimos reproduzir, testei varios tipos de variaveis e todos funcionam, se acharmos algo te avisamos

![image](https://user-images.githubusercontent.com/33813921/71916808-874e5a00-315d-11ea-84ae-7d571e5dea6c.png)

**Comment by jvvasquesn** [comment]
Se tiver alguma coisa que eu possa fazer me avise.
Abraço!

**Comment by ricardomansano** [comment]
Boa tarde @jvvasquesn , realmente não consguimos reproduzir este problema, pode ser algo relativo à sua versão mais antiga do Ubuntu.
Em meus testes na 18.04 LTS e no Mint (minha máquina de desenvolvimento) não reproduzi, o time testou na 19.10 tbem sem problemas.
Grato novamente pela ajuda em tentarmso cercar este problema
