### ISSUE TITLE
Debug não para na próxima linha, debugando JOB Rest Protheus

### ISSUE THREAD

**Issue by charlesreitz** [totvs/tds-vscode#216]
Ao realizar o DEBUG de um JOB, para ser mais exato o JOB Rest do Protheus, colocamos o ponto de parada em 2 lugares, porém quando usamos o F10 para pular a linha ele somente para quando existe um ponto de parada setado, caso não existir ele segue o programa. 

***  TOTVS S.A.  ***
***  www.totvs.com.br  ***
* TOTVS - Build 7.00.131227A - Jan 14 2019 - 21:08:41 NG
* Build: 32 bits
* RPO Format: 32 bits
* SVN Revision: 11137 - 21765 - 2116
* Build Version: 13.2.3.41

Starting (.TOTVS | Appserver 12 - Comp)...
Please wait...

Segue log:
File verbosity level: 9
date       time         ( uptime  ) [ thread name/id ]                   file:line     v| 
2019-11-19 13:33:42.548 (   0.000s) [                ]             loguru.cpp:755   INFO| Logging to 'c:\Users\charles.reitz\git\unifique\Fontes\log_debug_visual_studio_code_adpvl.log', mode: 'w', verbosity: 9
(   0.000s) [main thread     ]             loguru.cpp:591   | arguments: C:\\Users\\charles.reitz\\.vscode\\extensions\\totvs.tds-vscode-0.3.20\\node_modules\\@totvs\\tds-da\\bin\\windows\\debugAdapter.exe --log-file=c:\\Users\\charles.reitz\\git\\unifique\\Fontes\\log_debug_visual_studio_code_adpvl.log
(   0.000s) [main thread     ]             loguru.cpp:594   | Current dir: C:\Users\charles.reitz\AppData\Local\Programs\Microsoft VS Code
(   0.001s) [main thread     ]             loguru.cpp:596   | stderr verbosity: 0
(   0.001s) [main thread     ]             loguru.cpp:597   | -----------------------------------
(   0.002s) [main thread     ]    security_manager.cc:788   | lsRsaInit
(   0.100s) [main thread     ]    security_manager.cc:994   | userRsaInit
(   0.100s) [main thread     ]    security_manager.cc:1013  | Loading user prv key.
(   0.100s) [main thread     ]    security_manager.cc:1044  | Loading user pub key.
(   0.100s) [main thread     ]    security_manager.cc:1143  | Loading user symm key.
(   0.108s) [main thread     ]        tMessageDAP.cpp:100   | DAP Rcv < - {"command":"initialize","arguments":{"clientID":"vscode","clientName":"Visual Studio Code","adapterID":"totvs_language_debug","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true,"locale":"en-us"},"type":"request","seq":1}

(   0.108s) [main thread     ]       tDAPProtocol.cpp:141   | REQUEST RECEIVED: initialize

(   0.108s) [main thread     ]        tMessageDAP.cpp:71    | DAP Snd - > (888) {"body":{"supportTerminateDebuggee":false,"supportsCompletionsRequest":false,"supportsConditionalBreakpoints":true,"supportsConfigurationDoneRequest":true,"supportsDelayedStackTraceLoading":true,"supportsEvaluateForHovers":true,"supportsExceptionInfoRequest":false,"supportsExceptionOptions":false,"supportsFunctionBreakpoints":false,"supportsGotoTargetsRequest":false,"supportsHitConditionalBreakpoints":true,"supportsLoadedSourcesRequest":false,"supportsLogPoints":true,"supportsModulesRequest":false,"supportsRestartFrame":false,"supportsRestartRequest":false,"supportsSetExpression":true,"supportsSetVariable":false,"supportsStepBack":false,"supportsStepInTargetsRequest":false,"supportsTerminateRequest":false,"supportsTerminateThreadsRequest":false,"supportsValueFormattingOptions":false},"command":"initialize","message":"","request_seq":1,"seq":2,"success":true,"type":"response"}

(   0.108s) [main thread     ]        tMessageDAP.cpp:71    | DAP Snd - > (46) {"event":"initialized","seq":1,"type":"event"}

(   0.113s) [main thread     ]        tMessageDAP.cpp:100   | DAP Rcv < - {"command":"launch","arguments":{"type":"totvs_language_debug","request":"launch","cwb":"C:\\Users\\charles.reitz\\git\\unifique\\Fontes","name":"totvs","program":"sigafat","smartclientBin":"E:\\TOTVS12\\Microsiga\\Protheus\\bin\\smartclient\\smartclient.exe","enableMultiThread":true,"enableProfile":false,"isMultiSession":true,"isAccessibilityMode":false,"doNotShowSplash":false,"language":"","logFile":"C:\\Users\\charles.reitz\\git\\unifique\\Fontes\\log_debug_visual_studio_code_adpvl.log","ignoreFiles":true,"enableTableSync":true,"environment":"dev1","token":"djI6ZnlsanBxY3RyeTRrMGUxMDJjeDl4cHF5cHN2dHF3OjE6MTkyLjE2OC42NS4yNTQ6MTA3MDE6MDo3LjAwLjEzMTIyN0E=:djE6ZGV2MTphZG1pbjpqL1ZoY2x6WnZlM2grTG1tdldFeDhhdTNKMW1qWXF3Q2g1WHlNUlBzSzhJPQ==|djE6MTU3NDE2NjgzMTowOjE=.afrxjTFDJgSzRthXpi7Fjgay9xSUlxbaU0E9ofOSwgYf6qrrVhG4yQZKBHF7yyAdNhNnvHGm+pSVYDbXSksMijIOgAqAppVL1VGkAzEyjwin5JfJorH/1Dna1l5utJX5FR4NS+yMudL/3BtkEdVfls/lLNCdHZwqgV8xgn7MkXskMeDZZa6YnmaVDIvMrYbv3EYZ851RsGCzPlpqDTFpVqrAfN0ajVD/TeJuyu6KD2asvz7ZCllYHiC9w/oLoHxbD8erjKlnminVbyhSrs4gp7hJBVLCoZj0R7ZRezLPwQqfMIIsFtY4nwNQ2H/qVIUQhnt6Zl3JssB8k6v5K7OqyQ==","workspaceFolders":["c:\\Users\\charles.reitz\\git\\unifique\\Fontes"],"programArguments":[],"__sessionId":"be9e0625-fb52-4604-a48b-c328e309b81c"},"type":"request","seq":2}

(   0.113s) [main thread     ]       tDAPProtocol.cpp:141   | REQUEST RECEIVED: launch

(   0.113s) [main thread     ]        tMessageDAP.cpp:71    | DAP Snd - > (137) {"body":{"level":"INFO","message":"TDS-DA sendo inicializado.","notify":true,"time":"13:33:42"},"event":"TDA/log","seq":3,"type":"event"}

(   0.113s) [main thread     ]    security_manager.cc:308   | authentic TRUE
(   0.113s) [main thread     ]    security_manager.cc:331   | authentic TRUE
(   0.124s) [main thread     ]        tMessageDAP.cpp:100   | DAP Rcv < - {"command":"setBreakpoints","arguments":{"source":{"name":"TSCAProcessos.prw","path":"c:\\Users\\charles.reitz\\git\\unifique\\Fontes\\Financeiro\\Atendimento\\TSCAProcessos.prw"},"lines":[65,69],"breakpoints":[{"line":65},{"line":69}],"sourceModified":false},"type":"request","seq":3}

(   0.124s) [main thread     ]       tDAPProtocol.cpp:141   | REQUEST RECEIVED: setBreakpoints

(   0.124s) [main thread     ]        tMessageDAP.cpp:71    | DAP Snd - > (549) {"body":{"breakpoints":[{"column":1811373055,"endcolumn":0,"endline":0,"line":65,"source":{"name":"TSCAProcessos.prw","path":"c:\\Users\\charles.reitz\\git\\unifique\\Fontes\\Financeiro\\Atendimento\\TSCAProcessos.prw"},"verified":true},{"column":1811373055,"endcolumn":0,"endline":0,"line":69,"source":{"name":"TSCAProcessos.prw","path":"c:\\Users\\charles.reitz\\git\\unifique\\Fontes\\Financeiro\\Atendimento\\TSCAProcessos.prw"},"verified":true}]},"command":"setBreakpoints","message":"","request_seq":3,"seq":4,"success":true,"type":"response"}

(   0.135s) [main thread     ]        tMessageDAP.cpp:100   | DAP Rcv < - {"command":"setExceptionBreakpoints","arguments":{"filters":[]},"type":"request","seq":4}

(   0.135s) [main thread     ]       tDAPProtocol.cpp:141   | REQUEST RECEIVED: setExceptionBreakpoints

(   0.135s) [main thread     ]        tMessageDAP.cpp:71    | DAP Snd - > (106) {"command":"setExceptionBreakpoint","message":"","request_seq":4,"seq":5,"success":true,"type":"response"}

(   0.146s) [                ]       tDAPProtocol.hpp:158   | Caching files in workspace folder(s) (may take a long time if folder(s) has a lot of files/subfolders)
(   0.146s) [main thread     ]    security_manager.cc:331   | authentic TRUE
(   0.147s) [main thread     ]        tMessageDAP.cpp:71    | DAP Snd - > (137) {"body":{"level":"INFO","message":"Protheus Server connected.","notify":true,"time":"13:33:42"},"event":"TDA/log","seq":6,"type":"event"}

(   0.147s) [main thread     ]        tMessageDAP.cpp:71    | DAP Snd - > (90) {"command":"launch","message":"","request_seq":2,"seq":6,"success":true,"type":"response"}

(   0.147s) [main thread     ]        tMessageDAP.cpp:100   | DAP Rcv < - {"command":"configurationDone","type":"request","seq":5}

(   0.147s) [main thread     ]       tDAPProtocol.cpp:141   | REQUEST RECEIVED: configurationDone

(   0.147s) [main thread     ]        tMessageDAP.cpp:71    | DAP Snd - > (145) {"body":{"level":"INFO","message":"Configuração TDS-DA concluída.","notify":false,"time":"13:33:42"},"event":"TDA/log","seq":6,"type":"event"}

(   0.147s) [main thread     ]        tMessageDAP.cpp:71    | DAP Snd - > (101) {"command":"configurationDone","message":"","request_seq":5,"seq":6,"success":true,"type":"response"}

(   0.151s) [main thread     ]        tMessageDAP.cpp:100   | DAP Rcv < - {"command":"threads","type":"request","seq":6}

(   0.151s) [main thread     ]       tDAPProtocol.cpp:141   | REQUEST RECEIVED: threads

(   0.151s) [main thread     ]        tMessageDAP.cpp:71    | DAP Snd - > (139) {"body":{"threads":[{"id":1,"name":"Thread 1"}]},"command":"threads","message":"","request_seq":6,"seq":7,"success":true,"type":"response"}

(   0.153s) [                ]       tDAPProtocol.hpp:178   | Caching files completed)
(   1.601s) [main thread     ]       tDAPProtocol.cpp:959   | GETACTION RECEBIDO: TSCAPROCESSOS.PRW - 65

(   1.601s) [main thread     ]        tMessageDAP.cpp:71    | DAP Snd - > (164) {"body":{"allThreadsStopped":true,"description":"","preserveFocusHint":false,"reason":"breakpoint","text":"","threadId":1},"event":"stopped","seq":8,"type":"event"}

(   1.602s) [main thread     ]        tMessageDAP.cpp:100   | DAP Rcv < - {"command":"threads","type":"request","seq":7}

(   1.602s) [main thread     ]       tDAPProtocol.cpp:141   | REQUEST RECEIVED: threads

(   1.602s) [main thread     ]        tMessageDAP.cpp:71    | DAP Snd - > (139) {"body":{"threads":[{"id":1,"name":"Thread 1"}]},"command":"threads","message":"","request_seq":7,"seq":8,"success":true,"type":"response"}

(   1.603s) [main thread     ]        tMessageDAP.cpp:100   | DAP Rcv < - {"command":"stackTrace","arguments":{"threadId":1,"startFrame":0,"levels":1},"type":"request","seq":8}

(   1.603s) [main thread     ]       tDAPProtocol.cpp:141   | REQUEST RECEIVED: stackTrace

(   1.604s) [main thread     ]        tMessageDAP.cpp:71    | DAP Snd - > (359) {"body":{"stackFrames":[{"column":0,"id":5,"line":65,"name":"$GET_TRANSACOES_V1","source":{"adapterData":"advpl-adapter-data","name":"TSCAPROCESSOS.PRW","path":"C:/Users/charles.reitz/git/unifique/Fontes/Financeiro/Atendimento/TSCAProcessos.prw"}}],"totalFrames":6},"command":"stackTrace","message":"","request_seq":8,"seq":9,"success":true,"type":"response"}

(   2.012s) [main thread     ]        tMessageDAP.cpp:100   | DAP Rcv < - {"command":"scopes","arguments":{"frameId":5},"type":"request","seq":9}

(   2.012s) [main thread     ]       tDAPProtocol.cpp:141   | REQUEST RECEIVED: scopes

(   2.022s) [main thread     ]        tMessageDAP.cpp:71    | DAP Snd - > (348) {"body":{"scopes":[{"expensive":false,"name":"Local","namedVariables":6,"variablesReference":51},{"expensive":true,"name":"Public","namedVariables":261,"variablesReference":49},{"expensive":false,"name":"Table","namedVariables":45,"variablesReference":54}]},"command":"scopes","message":"","request_seq":9,"seq":10,"success":true,"type":"response"}

(   2.023s) [main thread     ]        tMessageDAP.cpp:100   | DAP Rcv < - {"command":"variables","arguments":{"variablesReference":51},"type":"request","seq":10}

(   2.023s) [main thread     ]       tDAPProtocol.cpp:141   | REQUEST RECEIVED: variables

(   2.023s) [main thread     ]        tMessageDAP.cpp:71    | DAP Snd - > (1025) {"body":{"variables":[{"evaluateName":"","indexedVariables":0,"kind":"","name":"SELF","namedVariables":0,"type":"O","value":"...","variablesReference":61,"visibility":""},{"evaluateName":"","indexedVariables":0,"kind":"","name":"_QUERYPARAM","namedVariables":0,"type":"U","value":"NIL","variablesReference":0,"visibility":""},{"evaluateName":"","indexedVariables":0,"kind":"","name":"DATADE","namedVariables":0,"type":"U","value":"NIL","variablesReference":0,"visibility":""},{"evaluateName":"","indexedVariables":0,"kind":"","name":"DATAATE","namedVariables":0,"type":"U","value":"NIL","variablesReference":0,"visibility":""},{"evaluateName":"","indexedVariables":0,"kind":"","name":"WSNOSEND","namedVariables":0,"type":"U","value":"NIL","variablesReference":0,"visibility":""},{"evaluateName":"","indexedVariables":0,"kind":"","name":"NCOUNT","namedVariables":0,"type":"U","value":"NIL","variablesReference":0,"visibility":""}]},"command":"variables","message":"","request_seq":10,"seq":11,"success":true,"type":"response"}

(   2.030s) [main thread     ]        tMessageDAP.cpp:100   | DAP Rcv < - {"command":"stackTrace","arguments":{"threadId":1,"startFrame":1,"levels":19},"type":"request","seq":11}

(   2.031s) [main thread     ]       tDAPProtocol.cpp:141   | REQUEST RECEIVED: stackTrace

(   2.031s) [main thread     ]        tMessageDAP.cpp:71    | DAP Snd - > (749) {"body":{"stackFrames":[{"column":0,"id":4,"line":0,"name":""},{"column":0,"id":3,"line":419,"name":"$CALLMETHOD","source":{"adapterData":"advpl-adapter-data","name":"WSRESTFUL.PRG","path":"WSRESTFUL.PRG"}},{"column":0,"id":2,"line":706,"name":"RESTEXECUTE","source":{"adapterData":"advpl-adapter-data","name":"FWRESTSRV.PRW","path":"FWRESTSRV.PRW"}},{"column":0,"id":1,"line":325,"name":"REST_CONNECT","source":{"adapterData":"advpl-adapter-data","name":"FWRESTSRV.PRW","path":"FWRESTSRV.PRW"}},{"column":0,"id":0,"line":852,"name":"HTTP_WT","source":{"adapterData":"advpl-adapter-data","name":"FWHTTPSRV.PRX","path":"FWHTTPSRV.PRX"}}],"totalFrames":6},"command":"stackTrace","message":"","request_seq":11,"seq":12,"success":true,"type":"response"}

(   3.379s) [main thread     ]        tMessageDAP.cpp:100   | DAP Rcv < - {"command":"next","arguments":{"threadId":1},"type":"request","seq":12}

(   3.379s) [main thread     ]       tDAPProtocol.cpp:141   | REQUEST RECEIVED: next

(   3.379s) [main thread     ]        tMessageDAP.cpp:71    | DAP Snd - > (90) {"command":"next","message":"","request_seq":12,"seq":13,"success":true,"type":"response"}

(   3.396s) [main thread     ]       tDAPProtocol.cpp:959   | GETACTION RECEBIDO: TSCAPROCESSOS.PRW - 69

(   3.396s) [main thread     ]        tMessageDAP.cpp:71    | DAP Snd - > (159) {"body":{"allThreadsStopped":true,"description":"","preserveFocusHint":false,"reason":"step","text":"","threadId":1},"event":"stopped","seq":14,"type":"event"}

(   3.399s) [main thread     ]        tMessageDAP.cpp:100   | DAP Rcv < - {"command":"threads","type":"request","seq":13}

(   3.399s) [main thread     ]       tDAPProtocol.cpp:141   | REQUEST RECEIVED: threads

(   3.399s) [main thread     ]        tMessageDAP.cpp:71    | DAP Snd - > (141) {"body":{"threads":[{"id":1,"name":"Thread 1"}]},"command":"threads","message":"","request_seq":13,"seq":14,"success":true,"type":"response"}

(   3.400s) [main thread     ]        tMessageDAP.cpp:100   | DAP Rcv < - {"command":"stackTrace","arguments":{"threadId":1,"startFrame":0,"levels":1},"type":"request","seq":14}

(   3.400s) [main thread     ]       tDAPProtocol.cpp:141   | REQUEST RECEIVED: stackTrace

(   3.400s) [main thread     ]        tMessageDAP.cpp:71    | DAP Snd - > (361) {"body":{"stackFrames":[{"column":0,"id":5,"line":69,"name":"$GET_TRANSACOES_V1","source":{"adapterData":"advpl-adapter-data","name":"TSCAPROCESSOS.PRW","path":"C:/Users/charles.reitz/git/unifique/Fontes/Financeiro/Atendimento/TSCAProcessos.prw"}}],"totalFrames":6},"command":"stackTrace","message":"","request_seq":14,"seq":15,"success":true,"type":"response"}

(   3.811s) [main thread     ]        tMessageDAP.cpp:100   | DAP Rcv < - {"command":"scopes","arguments":{"frameId":5},"type":"request","seq":15}

(   3.811s) [main thread     ]       tDAPProtocol.cpp:141   | REQUEST RECEIVED: scopes

(   3.820s) [main thread     ]        tMessageDAP.cpp:71    | DAP Snd - > (429) {"body":{"scopes":[{"expensive":false,"name":"Local","namedVariables":6,"variablesReference":51},{"expensive":false,"name":"Private","namedVariables":1,"variablesReference":50},{"expensive":true,"name":"Public","namedVariables":261,"variablesReference":49},{"expensive":false,"name":"Table","namedVariables":45,"variablesReference":54}]},"command":"scopes","message":"","request_seq":15,"seq":16,"success":true,"type":"response"}

(   3.821s) [main thread     ]        tMessageDAP.cpp:100   | DAP Rcv < - {"command":"variables","arguments":{"variablesReference":51},"type":"request","seq":16}

(   3.821s) [main thread     ]       tDAPProtocol.cpp:141   | REQUEST RECEIVED: variables

(   3.821s) [main thread     ]        tMessageDAP.cpp:71    | DAP Snd - > (1023) {"body":{"variables":[{"evaluateName":"","indexedVariables":0,"kind":"","name":"SELF","namedVariables":0,"type":"O","value":"...","variablesReference":61,"visibility":""},{"evaluateName":"","indexedVariables":0,"kind":"","name":"_QUERYPARAM","namedVariables":0,"type":"U","value":"NIL","variablesReference":0,"visibility":""},{"evaluateName":"","indexedVariables":0,"kind":"","name":"DATADE","namedVariables":0,"type":"U","value":"NIL","variablesReference":0,"visibility":""},{"evaluateName":"","indexedVariables":0,"kind":"","name":"DATAATE","namedVariables":0,"type":"U","value":"NIL","variablesReference":0,"visibility":""},{"evaluateName":"","indexedVariables":0,"kind":"","name":"WSNOSEND","namedVariables":0,"type":"U","value":"NIL","variablesReference":0,"visibility":""},{"evaluateName":"","indexedVariables":0,"kind":"","name":"NCOUNT","namedVariables":0,"type":"N","value":"0","variablesReference":0,"visibility":""}]},"command":"variables","message":"","request_seq":16,"seq":17,"success":true,"type":"response"}

(   3.827s) [main thread     ]        tMessageDAP.cpp:100   | DAP Rcv < - {"command":"stackTrace","arguments":{"threadId":1,"startFrame":1,"levels":19},"type":"request","seq":17}

(   3.827s) [main thread     ]       tDAPProtocol.cpp:141   | REQUEST RECEIVED: stackTrace

(   3.827s) [main thread     ]        tMessageDAP.cpp:71    | DAP Snd - > (749) {"body":{"stackFrames":[{"column":0,"id":4,"line":0,"name":""},{"column":0,"id":3,"line":419,"name":"$CALLMETHOD","source":{"adapterData":"advpl-adapter-data","name":"WSRESTFUL.PRG","path":"WSRESTFUL.PRG"}},{"column":0,"id":2,"line":706,"name":"RESTEXECUTE","source":{"adapterData":"advpl-adapter-data","name":"FWRESTSRV.PRW","path":"FWRESTSRV.PRW"}},{"column":0,"id":1,"line":325,"name":"REST_CONNECT","source":{"adapterData":"advpl-adapter-data","name":"FWRESTSRV.PRW","path":"FWRESTSRV.PRW"}},{"column":0,"id":0,"line":852,"name":"HTTP_WT","source":{"adapterData":"advpl-adapter-data","name":"FWHTTPSRV.PRX","path":"FWHTTPSRV.PRX"}}],"totalFrames":6},"command":"stackTrace","message":"","request_seq":17,"seq":18,"success":true,"type":"response"}

(   4.064s) [main thread     ]        tMessageDAP.cpp:100   | DAP Rcv < - {"command":"next","arguments":{"threadId":1},"type":"request","seq":18}

(   4.064s) [main thread     ]       tDAPProtocol.cpp:141   | REQUEST RECEIVED: next

(   4.064s) [main thread     ]        tMessageDAP.cpp:71    | DAP Snd - > (90) {"command":"next","message":"","request_seq":18,"seq":19,"success":true,"type":"response"}

(   4.152s) [main thread     ]       tDAPProtocol.cpp:959   | GETACTION RECEBIDO: FWAPP.PRW - 1055

(   4.152s) [main thread     ]       tDAPProtocol.cpp:968   | Arquivo FWAPP.PRW n䯠encontrado. Executando ultima a褯: 3
(   4.160s) [main thread     ]       tDAPProtocol.cpp:959   | GETACTION RECEBIDO: FWAPP.PRW - 1061

(   4.160s) [main thread     ]       tDAPProtocol.cpp:968   | Arquivo FWAPP.PRW n䯠encontrado. Executando ultima a褯: 3
(   4.176s) [main thread     ]       tDAPProtocol.cpp:959   | GETACTION RECEBIDO: FWAPP.PRW - 1061

(   4.176s) [main thread     ]       tDAPProtocol.cpp:968   | Arquivo FWAPP.PRW n䯠encontrado. Executando ultima a褯: 3
(   4.192s) [main thread     ]       tDAPProtocol.cpp:959   | GETACTION RECEBIDO: FWAPP.PRW - 1065

(   4.192s) [main thread     ]       tDAPProtocol.cpp:968   | Arquivo FWAPP.PRW n䯠encontrado. Executando ultima a褯: 3
(   4.517s) [main thread     ]       tDAPProtocol.cpp:959   | GETACTION RECEBIDO: FWAPP.PRW - 1068

(   4.517s) [main thread     ]       tDAPProtocol.cpp:968   | Arquivo FWAPP.PRW n䯠encontrado. Executando ultima a褯: 3
(   4.524s) [main thread     ]       tDAPProtocol.cpp:959   | GETACTION RECEBIDO: FWAPP.PRW - 966

(   4.524s) [main thread     ]       tDAPProtocol.cpp:968   | Arquivo FWAPP.PRW n䯠encontrado. Executando ultima a褯: 3
(   4.526s) [main thread     ]       tDAPProtocol.cpp:959   | GETACTION RECEBIDO: FWAPP.PRW - 966

(   4.526s) [main thread     ]       tDAPProtocol.cpp:968   | Arquivo FWAPP.PRW n䯠encontrado. Executando ultima a褯: 3
(   4.528s) [main thread     ]       tDAPProtocol.cpp:959   | GETACTION RECEBIDO: FWAPP.PRW - 991

(   4.528s) [main thread     ]       tDAPProtocol.cpp:968   | Arquivo FWAPP.PRW n䯠encontrado. Executando ultima a褯: 3
(   4.531s) [main thread     ]       tDAPProtocol.cpp:959   | GETACTION RECEBIDO: FWAPP.PRW - 997

(   4.531s) [main thread     ]       tDAPProtocol.cpp:968   | Arquivo FWAPP.PRW n䯠encontrado. Executando ultima a褯: 3
(   7.303s) [main thread     ]       tDAPProtocol.cpp:959   | GETACTION RECEBIDO: FWAPP.PRW - 999

(   7.303s) [main thread     ]       tDAPProtocol.cpp:968   | Arquivo FWAPP.PRW n䯠encontrado. Executando ultima a褯: 3
(  18.860s) [main thread     ]        tMessageDAP.cpp:100   | DAP Rcv < - {"command":"disconnect","arguments":{"restart":false},"type":"request","seq":19}

(  18.860s) [main thread     ]       tDAPProtocol.cpp:141   | REQUEST RECEIVED: disconnect

**Comment by ricardomansano** [comment]
Bom dia @charlesreitz , esse é um comportamente antigo na depuração de Jobs, WS, Rest e todos os demais serviços que rodam em background. Continue inserindo os pontos de parada conforme comentou, é o contorno que os analista utilizam.

Como esta é uma caracteristica da nossa arquitetura não há contorno via plugin, é uma resposta direta do appserver.

Grato pelo report.
