### ISSUE TITLE
List of folders to search for definitions not configured.

### ISSUE THREAD

**Issue by charlesreitz** [totvs/tds-vscode#217]
Alguém pegou essa mensagem ao tentar compilar uma pasta ou a workspace? 

List of folders to search for definitions not configured.

**Comment by leandropaulino85** [comment]
Também estou com o mesmo problema @charlesreitz ...

List of folders to search for definitions not configured.

**Comment by alisonkaique** [comment]
Essa mensagem é que não encontrou os diretórios de includes no arquivo servers.json.

Configure-o nessa estrutura:

![image](https://user-images.githubusercontent.com/6303443/69348979-c845ea00-0c55-11ea-8be4-f11d384e4d98.png)

**Comment by leandropaulino85** [comment]
Obrigado pelo apoio Alison, mas já tenho o incldude cadastrado no servers.json.

![image](https://user-images.githubusercontent.com/24957490/69363120-a147e200-0c6e-11ea-93f8-f7a719987979.png)

**Comment by ricardomansano** [comment]
Bom dia @charlesreitz , nao consegui reproduzir internamente, em conversa com o @leandropaulino85 vi que ele teve o mesmo problema, deve ser alguma sujeita no server ou launcher.json.

Resolvemos o problems do Leandro configurando um novo server, pois a partir da 3.0.20 é possivel inserir um conjunto de includes pra cada server. Isso se tornou necessário para garantir que nossos analistas consigam conviver com includes distintos pra cada versão do ERP.

Insira o novo server conforme imagem abaixo, grtato pelo report:
![image](https://user-images.githubusercontent.com/33813921/69728136-a8ee0780-1102-11ea-8a1d-e3ace49f10b5.png)
