### ISSUE TITLE
Não esta compilando so fontes das Pastas e subpastas

### ISSUE THREAD

**Issue by jvvasquesn** [totvs/tds-vscode#218]
**Describe the bug**
Quando clicamos em uma pasta e colocamos para compilar o VSCode não esta compila os fontes que foram alterados, a opção Recompilar também não esta compilando.

**Desktop (please complete the following information):**
 - Ubuntu 16.04

**Comment by ricardomansano** [comment]
Bom dia,

@acacioegas , @brodao , consegui reproduzir essa situação no Ubuntu 18.04 tbem

No Linux Mint ela não é reproduzida, deve ser alguma divergência na comparação de datas entre as distros.

**Comment by jvvasquesn** [comment]
Bom dia

@ricardomansano , com esse comentário percebi que a hora da compilação que aparece no console Advpl é uma hora adiantada. Olha a imagem.

Atenciosamente
![image](https://user-images.githubusercontent.com/55854184/69732919-42b9b280-110b-11ea-98e4-1cdabfe83829.png)

**Comment by ricardomansano** [comment]
Boa tarde @jvvasquesn , 

Extato foi o mesmo que eu peguei no 18.04, devemos estar usando alguma função de captura de data hora que no Ubuntu esta apresentando problemas:
![image](https://user-images.githubusercontent.com/33813921/69741745-5a4c6780-111a-11ea-8614-3631fa01f8bd.png)

O Mint apresenta o mesmo problema de divergencia de hora mas deixa compilar, o importante é verificar de onde ele esta pegando essa informação errada.

![image](https://user-images.githubusercontent.com/33813921/69742046-e1014480-111a-11ea-8e60-24d3d753ee29.png)

Vamos olhar assim que possivel, por hora compile manualmente pfv.

**Comment by jvvasquesn** [comment]
Boa tarde.
Temos alguma evolução?

**Comment by ricardomansano** [comment]
@leowww , Este problema como eu falei nao foi reproduzido no Mint, testa no Ubuntu 18.04 diretamente.

@jvvasquesn , vamos testar no 18.04, sendo a ultima LTS pra nós é mais seguro manter nesse ambiente, se a acharmos uma solução pro 18.04 que não funcione no 16.04 vou precisar que vc atualize seu Ubuntu.

![image](https://user-images.githubusercontent.com/33813921/71917208-4efb4b80-315e-11ea-81d5-f6129406be0b.png)

**Comment by lwtnb-wrk** [comment]
Srs. este parece ser algum problema especificamente relacionado com a alteração neste ano de não aderirmos ao horario de verao.
Verifiquem qual a Time Zone que seu Sistema Operacional esta configurado e se estiver configurado para -03:00/-02:00 (Brasilia) experimente trocar para, -03:00 (Fortaleza, pois nunca entra no horario de verao) se houver, ou algum -03:00 generico sem DST.
Este tipo de problema deve ocorrer pois o SO não sabe que não estamos no horario de verao (DST) como deveriamos e suas configuracoes nao foram atualizadas.
Imagino que este problema sumirá inexplicavelmente no começo de fevereiro quando deveriamos sair do horario de verao.

**Comment by jvvasquesn** [comment]
> @leowww , Este problema como eu falei nao foi reproduzido no Mint, testa no Ubuntu 18.04 diretamente.
> 
> @jvvasquesn , vamos testar no 18.04, sendo a ultima LTS pra nós é mais seguro manter nesse ambiente, se a acharmos uma solução pro 18.04 que não funcione no 16.04 vou precisar que vc atualize seu Ubuntu.
> 
> ![image](https://user-images.githubusercontent.com/33813921/71917208-4efb4b80-315e-11ea-81d5-f6129406be0b.png)

@ricardomansano o Ubuntu 18.04 ainda não é homologado para o Protheus, por isso ainda não atualizei.
Ticket #6792022 - Homologação Ubuntu 18

**Comment by jvvasquesn** [comment]
> Srs. este parece ser algum problema especificamente relacionado com a alteração neste ano de não aderirmos ao horario de verao.
> Verifiquem qual a Time Zone que seu Sistema Operacional esta configurado e se estiver configurado para -03:00/-02:00 (Brasilia) experimente trocar para, -03:00 (Fortaleza, pois nunca entra no horario de verao) se houver, ou algum -03:00 generico sem DST.
> Este tipo de problema deve ocorrer pois o SO não sabe que não estamos no horario de verao (DST) como deveriamos e suas configuracoes nao foram atualizadas.
> Imagino que este problema sumirá inexplicavelmente no começo de fevereiro quando deveriamos sair do horario de verao.

@lwtnb-wrk alterei para Fortaleza e realmente o horário dentro do VSCode ficou certo.

**Comment by lwtnb-wrk** [comment]
@jvvasquesn Grato pelo retorno.
