### ISSUE TITLE
VS Code Não apresenta opção para compilar pasta?

### ISSUE THREAD

**Issue by emersonbn** [totvs/tds-vscode#219]
No meu VS, não esta aparecendo a opção da compilar pasta, já reinstalei o plugin, mas continua.
Alguém sabe dizer como resolver isso?

![image](https://user-images.githubusercontent.com/18156895/69357695-51fcb400-0c64-11ea-841c-399250687776.png)

![image](https://user-images.githubusercontent.com/18156895/69357733-62149380-0c64-11ea-8a43-599b004c2d47.png)

**Comment by caiadofelipe** [comment]
Boa tarde @emersonbn,

Se clicar com o botão direito em cima da pasta e clicar em Compile File, ele compila a pasta inteira.

Att,

**Comment by emersonbn** [comment]
Deu certo, obrigado.
