### ISSUE TITLE
Abas exibidas, porém sem variáveis

### ISSUE THREAD

**Issue by guilhermebigois** [totvs/tds-vscode#22]
Na extensão [advpl-vscode](https://github.com/totvs/advpl-vscode) quando o Visual Studio Code está em modo de depuração, são exibidas apenas as abas (local, private, static) que contém variáveis, contudo nesta extensão não.

O fato da exibição das abas sem variáveis gera a ilusão que dentre das mesmas contém variáveis.

Este comportamento é comum a extensão acima citada e ao TOTVS Developer Studio.

Segue um vídeo ilustrando a solicitação: [ISSUE_22.zip](https://github.com/totvs/tds-vscode/files/3198306/ISSUE_22.zip)

**Comment by DanielYampolschi** [comment]
Implementado. Estará disponível na próxima atualização.
