### ISSUE TITLE
Indentação de Comentários

### ISSUE THREAD

**Issue by caiadofelipe** [totvs/tds-vscode#220]
Boa tarde.

A indentação de comentário não está sendo feita quando pressionamento o ALT+SHIFT+F.

**Comment by ricardomansano** [comment]
Bom dia @caioquiqueto , por favor insira um "antes" e "depois" só pra gente visualizar o problema

**Comment by caiadofelipe** [comment]
@ricardomansano ,

Segue conforme solicitado:

Antes:
![image](https://user-images.githubusercontent.com/49681823/69802554-8caca200-11b8-11ea-8b34-d0ebdd649bfa.png)

Depois:
![image](https://user-images.githubusercontent.com/49681823/69802571-9a622780-11b8-11ea-90e6-2e71a0e286b6.png)

Resultado Esperado:
![image](https://user-images.githubusercontent.com/49681823/69802596-a8b04380-11b8-11ea-8cf5-35197243df4d.png)

Qualquer dúvida estou a disposição

**Comment by ricardomansano** [comment]
@Bom dia @caiadofelipe 
Grato, vms verificar

**Comment by ricardomansano** [comment]
Boa tarde @caiadofelipe 

Cai no mesmo problema que encontramos no BeginSQL juntos, o que aocnteceu é que o comentário foi tratacomo como um estrutura, mas sem qqer identação, assim vc poderia usar "acima" de uma função, ex:

// Blocos de codigo recebidos via JavaScript
static function jsToAdvpl(self,key,value)

Se eu tiro o comentario, seja de linha ou de bloco, desta lógica, tlt vai reoranizar todo o trecho, bagunçando o que não deve, como na imagem abaixo.,

![image](https://user-images.githubusercontent.com/33813921/69827001-53922300-11f4-11ea-8f99-0184935e14f6.png)

Mais uma vez brigamos com o codebase, pois nossa estrutura de funções é anomala, e não tem uma estrutura de abertura e fechamento padão, com o JS por exemplo ( { } ).

Testei diversas maneiras pra resolver o problema, mas nenhuma sem colaterais, então melhor conviver com o menor dos problemas.

Agradeço novamente o report
