### ISSUE TITLE
[Linux] - Erro ao aplicar patch (Archlinux - Manjaro - Elementary OS)

### ISSUE THREAD

**Issue by emnovaes** [totvs/tds-vscode#221]
Erro ao aplicar patch usando o Linux.

Já tentei em Archlinux, Manjaro e agora no Elementary OS

Se observar, o VSCode tenta obter o arquivo com um link inválido :: l:/home/emnovaes/Documentos/TTTP120_LG.PTM (observe um "L" no início do caminho do arquivo)

Para não ser injusto com o tds-vscode, acredito que seja um erro do protheus mesmo, pois o mesmo erro acontece qdo tento abrir um arquivo DTC por exemplo, localizado em uma pasta do servidor.

apresenta l:/data/arquivo.dtc no caminho e não abre o arquivo.

![patch](https://user-images.githubusercontent.com/4050436/69672194-57983680-1076-11ea-937b-079b6c2fc2e9.png)

**Comment by ricardomansano** [comment]
Bom dia @emnovaes, 

Vc ta certo, esse L: é coisa da nossa arquitetura, inserimos um l:/ e tratamos internamente a informação em nossas funções de IO, isso ja tem uns 15 anos e hj não dá pra mudar dado os fontes que ja usam a lógica.

Só me fala uma coisa: 
Teu Server tbem é Linux? Se sim me fala a versão,

Nunca testei fora dos "Debian like" mas isso não deve ser um problema. 

Teste em um VS numa VM do Ubuntu e meu Server esta na minha estação que é Mint.

Consegui aplicar sem problemas, então peço que veja se tem direito de escrita no teu server, e partimos dai pra continuar a investigação.

![image](https://user-images.githubusercontent.com/33813921/69726250-e3ee3c00-10fe-11ea-99eb-40f2a1d36a53.png)

**Comment by emnovaes** [comment]
Mansano, 

Sim o server de aplicação também é Linux >> Oracle Linux 7.1
[edson.novaes@FUABCXF01 ~]$ uname -r
3.8.13-98.7.1.el7uek.x86_64

Meu notebook está dual boot, acesso pelo Windows quando preciso aplicar patch.

**Comment by ricardomansano** [comment]
Boa tarde @emnovaes , como os plugins tem o mesmo comportamento em windows e linux, realmente deve ser permissão qdo esta rodando no Linux, coisas do Pinguim.

Pelo menos vc não esta parado, grato pelo retorno

**Comment by emnovaes** [comment]
Sim, apenas se perde um pouco de produtividade.

Uso o VSCode com outro plugin desde 2017, mas estou migrando pro tds-vscode justamente para aplicação de patchs, este aplica o patch, porém não pergunta se devo sobrescrever arquivos com data mais atual no RPO.

Vou aproveitar e abrir um chamado na tecnologia, relacionado a uso de arquivos no Linux, pois até o cGetFile se perde com o L:/xxx e não grava o arquivo um arquivo local corretamente >> exemplo: l:/home/xxx/arquivo.txt e não grava neste local (mesmo com direito de leitura e gravação)

**Comment by emnovaes** [comment]
Mansano, testei hoje novamente com o Debian e Manjaro... ambos com sucesso!
