### ISSUE TITLE
Seria possível a servers.json na mesma pasta que launch.json?

### ISSUE THREAD

**Issue by emebatista** [totvs/tds-vscode#222]
Possuo diversas conexões para ambientes (clientes diferentes).

Se o arquivo servers.json ficasse na raiz da pasta, poderíamos ter servers vinculados às pastas/workspaces.

O que vem ocorrendo é que corro o risco de estar com o fonte aberto de uma pasta (cliente) e compilar no server conectado de outro ambiente (cliente). 

Alguém já se deparou com isso?

**Comment by ricardomansano** [comment]
Bom dia @emebatista , O que fizemos pra facilitar é que na 3.0.20 inserimos um conjunto de includes por Server, isso ja facilita se vc tiver includes diferentes pra cada cliente.

Quanto ao risco que comentou infelizemente é necessário atenção no momento da compilação.

Grato pela sugestão,
