### ISSUE TITLE
Indentação quando existe BeginSQL

### ISSUE THREAD

**Issue by caiadofelipe** [totvs/tds-vscode#223]
Bom dia.

A indentação está com problema quando no fonte existe o BeginSQL. Abaixo, segue evidência.

Antes da Indentação:
![image](https://user-images.githubusercontent.com/49681823/69808174-bddf9f00-11c5-11ea-9a98-c728b3cabf3f.png)

Depois da Indentação:
![image](https://user-images.githubusercontent.com/49681823/69808204-cafc8e00-11c5-11ea-9271-1e46a37c9f49.png)

**Comment by ricardomansano** [comment]
Bom dia @caiadofelipe , conforme conversamos, usando a versão DEV isso não ocorre, mas temos o problema dele não identar o conteudo do beginSQL caso o trecho esteja alinhado(colado) à esquerda antes da formatação.

Como lhe comentei esse tipo de estrutura não existe em qualquer outra linguagem, algo muito pareceido acontece com o Do Case, então é muito provável que não exista um tratamento viável, simplesmente porque o VSCode não deveria se preparar pra tratar esse formato exclusivo.

Se tiver alguma ideia agradecemos, mas eu me preparia psicologicamente pra conviver com esse problema,

De qqer forma vou fazer umas tentativas aqui

Valew,

**Comment by ricardomansano** [comment]
@caiadofelipe , conforme conversamos, estou encerrando a issue por termos chegado no limite do ajuste possivel pra esse tipo de estrutura.

Brigadão pela força durante os testes
