### ISSUE TITLE
Continuação https://github.com/totvs/tds-vscode/issues/216

### ISSUE THREAD

**Issue by charlesreitz** [totvs/tds-vscode#224]
@ricardomansano  discordo dessa situação, pois é algo intermitente, as vezes funciona, as vezes não funciona. 

Então nunca deveria funcionar, certo? 

https://github.com/totvs/tds-vscode/issues/216

**Comment by ricardomansano** [comment]
Boa tarde @charlesreitz ,

Entendo sua posição, mas essa situação é corriqueira desde o IDE Delphi
Se a depuração esta complicada desta maneira, pode colocar conouts em sua aplicação e investigar desta maneira

**Comment by Felipe-Raposo** [comment]
Boa tarde. Esse chamado e um outro chamado que abri referente a aplicar patch com letra maiúscula no Linux foram fechados com o argumento de que o "culpado" é o AppServer.

Nesses casos vocês comunicam a equipe responsável pelo AppServer, ou fica por isso mesmo? Por que, apesar de haver maneiras de contornar o problema, o problema continua lá. Não há maneira de corrigir o problema em vez de mandar o usuário dar a volta?
