### ISSUE TITLE
Conection terminated by the administrator

### ISSUE THREAD

**Issue by almeidaga** [totvs/tds-vscode#227]
Após iniciar o debug e acessar qualquer opção no menu, diversas vezes o debug cai e na tela é apresentado o erro "Conection terminated by the administrator".

![image](https://user-images.githubusercontent.com/29076410/70329922-df1e3c00-1812-11ea-8090-184602301aff.png)

**Comment by danielbolognani** [comment]
Utilizar a issue #189 que já está aberta para esse caso.
