### ISSUE TITLE
Falha de conexão Versão 25

### ISSUE THREAD

**Issue by paolastekl** [totvs/tds-vscode#228]
Não estou conseguindo conectar a versão 12.25 do Protheus no debuger do VS Code. Ele conecta ao servidor, consigo compilar e aplicar patch porém ao conectar para debugar não consigo avançar por falha de conexão.
SmartClient está conectado normalmente.

Segue launch.json:

{
"version": "0.2.0",
"configurations": [
{
"type": "totvs_language_debug",
"request": "launch",
"name": "%tds.package.totvs_language_debug%",
"program": "${command:AskForProgramName}",
"smartclientBin": "C:\smartclient_P1225\SmartClient.exe",
"isMultiSession": true,
"enableTableSync": true
},
{
"type": "totvs_language_debug",
"request": "launch",
"name": "Totvs Language Debug",
"program": "${command:AskForProgramName}",
"cwb": "${workspaceFolder}",
"smartclientBin": "C:\smartclient_P1225\SmartClient.exe",
"isMultiSession": true,
"enableTableSync": true,
"enableMultiThread": false,
"enableProfile": false,
"isAccessibilityMode": false,
"doNotShowSplash": false,
"language": "",
"ignoreFiles": true
}
],
"lastPrograms": [
{
"args": [],
"label": "U_DVSMR090",
"description": ""
},
{
"args": [],
"label": "SIGAMDI",
"description": ""
}
],
"lastProgramExecuted": "SIGAMDI"
}

**Comment by lwtnb-wrk** [comment]
@paolastekl O erro que ocorre é o "Connection terminated by administrator"?

**Comment by paolastekl** [comment]
Não ele dá erro de conexão mesmo. "SmartClient conectou com TOTVS Application Server mas houve erro no inici de validação de conexão"

**Comment by lwtnb-wrk** [comment]
@paolastekl Essa é a mensagem exata do erro? Você teria como anexar um print da tela com erro??

**Comment by paolastekl** [comment]
é sim! 
![conexao](https://user-images.githubusercontent.com/37141661/70824251-9f31f880-1dc0-11ea-977b-f7be8c06687d.png)

**Comment by danielbolognani** [comment]
@paolastekl Esse erro pode estar relacionado ao SSL, pode colocar aqui também o conteúdo do arquivo servers.json?

**Comment by paolastekl** [comment]
{
	"version": "0.2.0",
	"includes": [
		"Z:\\Workspace\\Paola Stekl - P12_25\\includes_P12"
	],
	"permissions": {
		"authorizationtoken": ""
	},
	"connectedServer": {
		"name": "P12_25",
		"id": "f4ctfasjlg6k48lvn20gn7ouy980gi",
		"token": "djI6ZjRjdGZhc2psZzZrNDhsdm4yMGduN291eTk4MGdpOjE6MTkyLjE2OC4zMC4xMToxMTAxMDowOjcuMDAuMTcwMTE3QQ==:djE6RFZTQzpwYW9sYS5zaWx2YTphWmgxQXc5Sm5iVlFtamtKejN0dndadWJ5M1kvcm91MkFwVlZBeC9PaTBNPQ==|djE6MTU3NjUxOTkyMjowOjE=.UUGjIYt8vtR2GJ+uLf3nxf/tWnpunz6gD/cdES8/060LPNmCJ6gVPqt/LJTzwJdVWZvdCl6QBuMk0R4IP8yXUwPx48zH4Q+PLUu0TdNjlo4KMD2s5RFRmq4qy+OSR7beDtcAIAarZ9LMif+GzbpQz6l5cuMAmgiS/ONAsTUwy7au7yDf31tfXYZjCx0mjNljPwCJEKY4bBZz/6n3XWuXx3B4ScvVMKdn9WMQTgJPqcurOBUPnZTNn5EpviPcZGJi8n6i1mQZGTOPcZ5LKMiYnm9ab+HB+cH3X9hKkwIcZmf41VY9xlfG7G7A6yUe1Na4lrftC0GO2dSaHJu8wj9+6A==",
		"environment": "DVSC"
	},
	"configurations": [
		{
			"id": "juc6l4str1pk4058s9m4qqpa878l8j",
			"type": "totvs_server_protheus",
			"name": "DVT_TST",
			"port": 11030,
			"address": "192.168.30.11",
			"buildVersion": "7.00.170117A",
			"includes": [
				"C:\\Totvs\\Workspace\\Paola Stekl - P12_25\\includes_P12"
			],
			"environments": [
				"DVTHMLB"
			],
			"username": "paola.silva",
			"environment": "DVTHMLB"
		},
		{
			"id": "20ugbczhd4yk40c9p5kzfoj81k816",
			"type": "totvs_server_protheus",
			"name": "DVT",
			"port": 11001,
			"address": "192.168.30.11",
			"buildVersion": "",
			"includes": [
				"C:\\Totvs\\Workspace\\Paola Stekl - P12_25\\includes_P12"
			]
		},
		{
			"id": "6ent6wqh7m9k4190o6fji6arzdduo8",
			"type": "totvs_server_protheus",
			"name": "Homolog_p12",
			"port": 7007,
			"address": "192.168.30.9",
			"buildVersion": "7.00.131227A",
			"includes": [
				"Z:\\Workspace\\Paola Stekl - P12_17\\includes_P12"
			],
			"environments": [
				"Homolog-Desenv3"
			],
			"username": "paola.silva",
			"environment": "Homolog-Desenv3"
		},
		{
			"id": "4zw1rn93p33k43596i5gsivam2ef3b",
			"type": "totvs_server_protheus",
			"name": "Desenv_P12",
			"port": 7788,
			"address": "192.168.30.9",
			"buildVersion": "7.00.131227A",
			"includes": [
				"C:\\Totvs_old\\Workspace\\Paola Stekl - Desenv\\includes_P12"
			],
			"environments": [
				"Desenv"
			],
			"username": "paola.silva",
			"environment": "Desenv"
		},
		{
			"id": "f4ctfasjlg6k48lvn20gn7ouy980gi",
			"type": "totvs_server_protheus",
			"name": "P12_25",
			"port": 11010,
			"address": "192.168.30.11",
			"buildVersion": "7.00.170117A",
			"includes": [
				"Z:\\Workspace\\Paola Stekl - P12_25\\includes_P12"
			],
			"environments": [
				"DVS",
				"DVSA",
				"DVSC"
			],
			"username": "paola.silva",
			"environment": "DVSC"
		}
	],
	"lastConnectedServer": {
		"name": "P12_25",
		"id": "f4ctfasjlg6k48lvn20gn7ouy980gi",
		"token": "djI6ZjRjdGZhc2psZzZrNDhsdm4yMGduN291eTk4MGdpOjE6MTkyLjE2OC4zMC4xMToxMTAxMDowOjcuMDAuMTcwMTE3QQ==:djE6RFZTQzpwYW9sYS5zaWx2YTphWmgxQXc5Sm5iVlFtamtKejN0dndadWJ5M1kvcm91MkFwVlZBeC9PaTBNPQ==|djE6MTU3NjUxOTkyMjowOjE=.UUGjIYt8vtR2GJ+uLf3nxf/tWnpunz6gD/cdES8/060LPNmCJ6gVPqt/LJTzwJdVWZvdCl6QBuMk0R4IP8yXUwPx48zH4Q+PLUu0TdNjlo4KMD2s5RFRmq4qy+OSR7beDtcAIAarZ9LMif+GzbpQz6l5cuMAmgiS/ONAsTUwy7au7yDf31tfXYZjCx0mjNljPwCJEKY4bBZz/6n3XWuXx3B4ScvVMKdn9WMQTgJPqcurOBUPnZTNn5EpviPcZGJi8n6i1mQZGTOPcZ5LKMiYnm9ab+HB+cH3X9hKkwIcZmf41VY9xlfG7G7A6yUe1Na4lrftC0GO2dSaHJu8wj9+6A==",
		"environment": "DVSC"
	},
	"savedTokens": [
		[
			"yje69tqkrkk3sxoaw9j3ebfgzgpq:Homolog_P12",
			{
				"id": "yje69tqkrkk3sxoaw9j3ebfgzgpq",
				"token": "djI6eWplNjl0cWtya2szc3hvYXc5ajNlYmZnemdwcToxOjE5Mi4xNjguMzAuOTo3MDA3OjA6Ny4wMC4xMzEyMjdB:djE6SG9tb2xvZ19QMTI6cGFvbGEuc2lsdmE6NWpYUzcyZnkwYTFjK051L3QvT3dFNlIza0hEU2MyeEUvNk16bndXaUF6az0=|djE6MTU3NTU2NTAwMjowOjE=.kUFwEY5C2IDlFq2sW8LgpA50mBMXcnYKMooTcAKGpyyWONBONeP4JdI+2Gskapzw597EHg640xYwh/I5Jfjs3SGDAHeV1NL5hwXSfyaymgeYLVSPdqhiWTdnCZj0LnC/SmCdp0R0iBznzktnBNtGGX1HoArzTYlMlWKLI90IjWXpokjURhKU2Z5GMrFUnRMIU1rk/Bh8by0vogGXxfBQwxJOQ9/8q1u5qo2BUyPH8euj54s1BRRlOr2A4EMaWFBInWcQrxm6WwU2T/SI1M7R6ks59lJZqXlJ+0HpdbKQkSqTgWRBEme6eNp0rsfMxuqfQ/T4m4NIrz3/B5CFME/QdA=="
			}
		],
		[
			"vm2rkv5pkgk3syszk373qtgyik50a:DVS",
			{
				"id": "vm2rkv5pkgk3syszk373qtgyik50a",
				"token": "djI6dm0ycmt2NXBrZ2szc3lzemszNzNxdGd5aWs1MGE6MToxOTIuMTY4LjMwLjExOjExMDAxOjA6Ny4wMC4xNzAxMTdB:djE6RFZTOnBhb2xhLnNpbHZhOkpWemU2THJSY2VldEM3c1VFRVkwUVVGcytNYTJOWGVrT2hFT21UYlIxTkk9|djE6MTU3NTU2NTE4NjowOjE=.pVXJGAeG+LAnP5eNajLOmAP/ZTnf4oc3aIhxE2A/irmM3DpHgo6DojBPur22Lxxvdn2oispQCGEYzMdalUOEyMVNyMEw89qgFEix7p7ErK1RP8pCPvEwboTw1avVn67v9l2jzPUhpioNgNoPyTzz6AHROwWLVfmjfy20ZfIYn8xxk9frYIdfCpBeHVQGlbHkwCm5mk/lQM1o2OKOppxbmnUtI5ivQI+t1xHHr+WsvTLBCFY4NMRW0cgGwjQuJZZEJj2WbssthXn1FGgFNJx3dmKSwjbtDvJceF+AVnhYBZoJ2oyP24NnOzA20KTu/MHBFNjkIrOXeHOdr/6sSHzu0Q=="
			}
		],
		[
			"z0nnlwp4bmfk3t266eumw0gddv0qe9:DVS",
			{
				"id": "z0nnlwp4bmfk3t266eumw0gddv0qe9",
				"token": "djI6ejBubmx3cDRibWZrM3QyNjZldW13MGdkZHYwcWU5OjE6MTkyLjE2OC4zMC4xMToxMTAwMTowOjcuMDAuMTcwMTE3QQ==:djE6RFZTOnBhb2xhLnNpbHZhOnpyUllaTTg5Rm8xdEhoUUFUalhUZkUyOTFhdVNLUE1ZcGtzRDhXNXFDRjQ9|djE6MTU3NTU3MDg2MjowOjE=.Yea+e5HMsCp7ZeF94X/slI7wEw63ZoEJ6pmoq29ozuqtEgA2o3vLdBm+2QP9MPhnEVNEalJJojmkS5T8HB0dH9903UTiCYaRIgAhMXCUBFaV578Y6I2MeckYgPme1IeJ84KeeMVIjnuMdmh5gNbcPvpvAa/871V7rjrnDcm+YlIzU5LJ0X7FfRrxgh8Rzg4BfqrZDv6BgR4L/daB1RrXy56yzAoRTVLF9hn93AAs0n0NMPIoqNefuY11caw+eZmt3wMtMIb5ImQST/AFP1RRsl0/srS3M5+jNNViaKg8z/DaNfuqy/IG3MWeH5/TzRqKykhpPUmd95phVgZaF800+w=="
			}
		],
		[
			"c7gu1qvf0qdk3yc8jit882fnhc855n:DVTHML",
			{
				"id": "c7gu1qvf0qdk3yc8jit882fnhc855n",
				"token": "djI6YzdndTFxdmYwcWRrM3ljOGppdDg4MmZuaGM4NTVuOjE6MTkyLjE2OC4zMC4xMToxMTAzMDowOjcuMDAuMTcwMTE3QQ==:djE6RFZUSE1MOnBhb2xhLnNpbHZhOm5OR1g4Z092b000UHl3b1BrOVZWT1NuSnhlWUZEclBEQ2JidVNrUFlibWc9|djE6MTU3NTg5MDA4NTowOjE=.N4FYuc1ZaMWTL6QPZB4EgTbyMSFZK2OF6wvJdE9MslIgALUf3qEVAD8ERoZDz/ZUxAHm+0KCBsETSB1beStVi4mRinZJzvpRzfTw6IGQ5Q9xHDwggiNcBPkkSf4PCTeAGeTlUbTDN25l3I5xAhRpiW2Uubdsum07OAqCkxdy6HM6Yj4lsLs+dEE7NQWhGcjr1XA9Jv+IuPCBBnt+FrxOH62I7exOTLCz3bbxiDh7osVauVTVsJ8wYgu13gb0Wr43sgQm1h+CZgAKW0BvBuzNHeAZGyDJcZn2AeKIpH1YO5cD77scedK6qXKJ3NU82O614FUctW6UyoVHEh58Ip/xoA=="
			}
		],
		[
			"e5su0xu845k3yrb5af2yhec343d0p:DVTHMLB",
			{
				"id": "e5su0xu845k3yrb5af2yhec343d0p",
				"token": "djI6ZTVzdTB4dTg0NWszeXJiNWFmMnloZWMzNDNkMHA6MToxOTIuMTY4LjMwLjExOjExMDMwOjA6Ny4wMC4xNzAxMTdB:djE6RFZUSE1MQjpwYW9sYS5zaWx2YTpadWJ1TkNITmhHSjlJdDJ5UnZBRy9PRWhBS0o5RHFhUEFOVWNSUHpzRmowPQ==|djE6MTU3NTkxNTM5MjowOjE=.UFUCtCXJNOP5wG9tnWRvFK3eI2Rkkp4umpjVzUS8WwQxjH6iRQjVtL5SL6TQ6PR165T9thsnFAv1R1EmBt9c8u7swqpHJguvFzBhbXj/XSEH0aMapDNYH76cD0AbSPs4T+A7CKvO8scu8aKiSDJf45/sLp9t/8rSBX14GCrAK0lgeJ+RoM+4G1rpbPJ6xXg1Veyr7oQizQMFm5TZv+c+XT2Kt+MQVhY65rAWteUseEnaD/AnTSA1F3IvnnUNde0q50zS/LagYmLJb4qwpWM/j6vQRjJssTF5+ekdAcU2DdtoK7sKa5bwrvrmq3+S72yQievJChk8PaGSOVBOYVd8uw=="
			}
		],
		[
			"l3mm5o36nypk3yv8sract91va6qhuh:DVTHMLB",
			{
				"id": "l3mm5o36nypk3yv8sract91va6qhuh",
				"token": "djI6bDNtbTVvMzZueXBrM3l2OHNyYWN0OTF2YTZxaHVoOjE6MTkyLjE2OC4zMC4xMToxMTAzMDowOjcuMDAuMTcwMTE3QQ==:djE6RFZUSE1MQjpwYW9sYS5zaWx2YTpuWmNVT09YTzI5ckNtTmF3am5mSm1pL3dnM0Y1YzVicWJJK0hiMHBhdE5NPQ==|djE6MTU3NTkyMjAyMjowOjE=.p9kZ6lwzr1XiNQ0/LkgKGnvc9sV8GH8aD2XAqSYbyNIHkYFer5rx2YDai3Q/1dX6tNmfMGrVhb6hMIokRbQDD8pRxav9QQDFsiiU4NuUEH+u4h6BSI2rwbsENKVtOlTpFOy+x5BxU/lxNlfVNqo/Kl/YN8on/QQJJcKTOqEq7NLMBZTXYBoEnYw0KdQ8/G6aq/HhTMqIte4V/ZtOjIIcwicnIWjNZDfdxfTC3BkEfOvkvPR5SjJR1jB5Ap+76FBlDeYbUuFVZhjLHuPzcvwBwZ9gZbvxzJDhfxQr63d/ihoK8BwWl5yeW+IRCCaXWPApIY5YLSZQFtHSnBWKap46DQ=="
			}
		],
		[
			"juc6l4str1pk4058s9m4qqpa878l8j:DVTHMLB",
			{
				"id": "juc6l4str1pk4058s9m4qqpa878l8j",
				"token": "djI6anVjNmw0c3RyMXBrNDA1OHM5bTRxcXBhODc4bDhqOjE6MTkyLjE2OC4zMC4xMToxMTAzMDowOjcuMDAuMTcwMTE3QQ==:djE6RFZUSE1MQjpwYW9sYS5zaWx2YTp6dFV3M2FmcnJENFFlTUNoZU0wNkRJTFJrd1VBZ1ZRaGQyQUFPb09CYU84PQ==|djE6MTU3NTk5OTI2NzowOjE=.DLPlc/lxX3kpPfibuX/Uz7/0tOhqkBO7q0cXRhPOFw7EQXXtYUeNdh3oJ/Lbi2GS0SKgPfXoCF1veJyr9mrzvJMybg08ztRaeKimiya6kEcei+A6yVfJBrIYaZu2N6kXwoC31bYIjPZWekXwKvvImS5W5RCKX+UUkyRK0KBtX2dVOUgpMHYYrjfgK2sr2Fag57zT5zaiFZbp26fLY6kPbJfMkkQEJtqJs3dYjV9JhaE32DJPdXdK/mZnxj4tQu1OUVa/5SSLiLMB2x2uAdVpUBdN+1Ppy1SzAJ16nMCYgW6VpJyBE3bzd8dmYDF3jU2x7ndVK6Ee+rDSuWElMcPHzA=="
			}
		],
		[
			"ir92p8qtkrk40c8oufwxmslwdcal:Homolog_P12",
			{
				"id": "ir92p8qtkrk40c8oufwxmslwdcal",
				"token": "djI6aXI5MnA4cXRrcms0MGM4b3Vmd3htc2x3ZGNhbDoxOjE5Mi4xNjguMzAuOTo3MDA3OjA6Ny4wMC4xMzEyMjdB:djE6SG9tb2xvZ19QMTI6cGFvbGEuc2lsdmE6cndwdTd0akkyWThuWEJHVHRMU21IWW9qWVA1b2hSWjIycVpzckN2YXZpOD0=|djE6MTU3NjAxMTE2NTowOjE=.BMv1FBp3nayREDfzKAdQ9A+tXaXAbMtTk212PuiC6CaovRrSlX/6TFmJXwuMUcD6VdDI/lnjBxu54z0uZwGlFKDqo9NB0zQjXGQgaox3TYFBeBf2VOYbIvyMTBcObH51jfMYi2PjdC7XPBTqtjkIdoF61MOswjh2Zaw39CgLFA/GTxkCz78/L00f5m0o/VJ3NwX3dPi1T88qP90AXO3iUPnFyberkbyv100LwMIJXiD7bd93ISh49fmPTKQqMcmKTnuNolvFacQszrNORkMaArLmnT8yyx+eaq0VxM+evIUP79e+q+t8bbhhFCtAyChSqnZsEu0TqYzEnVVtkHvA4g=="
			}
		],
		[
			"6ent6wqh7m9k4190o6fji6arzdduo8:Homolog_P12",
			{
				"id": "6ent6wqh7m9k4190o6fji6arzdduo8",
				"token": "djI6NmVudDZ3cWg3bTlrNDE5MG82ZmppNmFyemRkdW84OjE6MTkyLjE2OC4zMC45OjcwMDc6MDo3LjAwLjEzMTIyN0E=:djE6SG9tb2xvZ19QMTI6cGFvbGEuc2lsdmE6SmkyK3RENlFjR0ozV1FuczRPbis1ODZvaHY2eDR0aE0xclhKQ200eEpKOD0=|djE6MTU3NjA2NjA1NTowOjE=.VmFHJM9yfxpUNNmBvaK0al1mauA38+N7NQccb+UCXUjWnFZf/1VDJZ82yljyUC6MOp1L/lEmkXonvN7F0zhkNeEDyjLMh1qSJ26p+ptGk9oKUv9EyAzWwR9IxbBasGWiYDiMgqreZ/r0fxNITNcPG2qhqUYrakYiFCijuRCi9EIPxhmKUs8tm308AR/heiX9CDS0LvA0cuovmayY0xkheO2slE4sewLrWtcRgHNucxzPpXzaCyl95BD2xLKAdygJxI1wPvsLg4Cq17svZNeMbXxLM0mTOE01FKFn9+74z6YatIm6rWZPN1z/f+p8z+Hi0s7pWjF+6dSBhEkM4eQ4bQ=="
			}
		],
		[
			"6ent6wqh7m9k4190o6fji6arzdduo8:Homolog-Desenv3",
			{
				"id": "6ent6wqh7m9k4190o6fji6arzdduo8",
				"token": "djI6NmVudDZ3cWg3bTlrNDE5MG82ZmppNmFyemRkdW84OjE6MTkyLjE2OC4zMC45OjcwMDc6MDo3LjAwLjEzMTIyN0E=:djE6SG9tb2xvZy1EZXNlbnYzOnBhb2xhLnNpbHZhOjE3ZDJzTEhsVGcxTzBsUXJPaUo3ekg5Wmo5QVZseHlKY3pWMlpNaWJCNVU9|djE6MTU3NjA2NjE3NjowOjE=.BkNQup5TLkKVba5FRDw5/AeyuItZ7qEWvdBoJGd05Mi5/WWR1OJFkbrhn10NDYaELTvZM7bClpX5/bZKadLByXlTh5HBefJYJx8Hz1uWvwaXPysbu4LQ6muI81VrptHZx+qhS0LBUBK/Kz6UXEgi+B21Z/RK/uMIEnNOOSu5JkxuVVmRDpCrpJjW5UIYDzr2PC0d2X4uLSZOc/zBiNpJoB1DzF1bGuiAtup0DA5dlX8Gtbl5+Zit+cvws2pIp1gD9wYx41RiaqytrF9XByHFORiJcwcDClVIU7jYKuuaUwfqpdRv2KmnOW29LYr/epdxLdHAEceRVIHtNqlNY98tGQ=="
			}
		],
		[
			"4zw1rn93p33k43596i5gsivam2ef3b:Desenv",
			{
				"id": "4zw1rn93p33k43596i5gsivam2ef3b",
				"token": "djI6NHp3MXJuOTNwMzNrNDM1OTZpNWdzaXZhbTJlZjNiOjE6MTkyLjE2OC4zMC45Ojc3ODg6MDo3LjAwLjEzMTIyN0E=:djE6RGVzZW52OnBhb2xhLnNpbHZhOkJSNmo1TWZWaG1yVnZlT1V0UEgyR2NqemFBM3hJOVUrMisvdW02cVViNGs9|djE6MTU3NjE4MDcxMDowOjE=.J/iEQQb8FTg6Y1mXOLUTM8JyaVCXTi2bqC+Ogli6C2kGS4jblkwrMgLVsAJbjjEHf8f7zUu+FJQj2q2ML+E/VZ9HRsaSRoDVLisXQ1XGrEFcIZt0+f4wv/Dw/RJ6Q0tEsanuQirZXYH3FRF5BDUm4vthJfO55G78PrOgAfH2KUpLQ1EiGKWKC+ngkFOvi/zU/3MOOAujIIDFS5RyaG6Pjfh1TF+Gh3yJm1/6RN9aghTK4xniIUF1ljInJz3v7iIK3C1qrTE8PKgKuEoSiexwkwi39e4fdl21nc+G1EkJL030+jt223Q/7aHb02+Z/P3Feg+Iowu0ZSPNpR/fhW3mwA=="
			}
		],
		[
			"5804dep63ltk48ljyua4b7nzjm1r0v:DVS",
			{
				"id": "5804dep63ltk48ljyua4b7nzjm1r0v",
				"token": "djI6NTgwNGRlcDYzbHRrNDhsanl1YTRiN256am0xcjB2OjE6MTkyLjE2OC4zMC4xMToxMTAxMDowOjcuMDAuMTcwMTE3QQ==:djE6RFZTOnBhb2xhLnNpbHZhOkM0TTNrbnVEeVdIVGNCU3lMa2x1b1dUdGwzOXdkZi90c2Jya3BvTS8rdXM9|djE6MTU3NjUxMDM2MjowOjE=.mltvj7semvqTzeo5oPSlqK+eGYEFh5M4IY5eVSH+uArID3P9YMFIXADMPeyf8TTm6JNT+Dtxb7cHhDEXrJKLdQlxv/vCgztmMkXTJi1jUa0h01wnf7cO0slvnJ1Uqn6DamU92LnM57tUD+02m6rNxf+/G+Dpv6sdSd4wDCkMN2yokSNVdq+zbihouLf+FgQc0fFVh4X0kXAAZ0wPlvNdz0U22/VjEVV2PckrsvtrCEucQ8oaMk2UaVa7AbFhA8Wx3JPsv9Gw4V2NXfs/MkFoMo8S3lItoyU2F04eQ2lY8LUiUrrm8d2q/VdtVIJlF3G3T57B1WYaSfU3H2h4on7iVA=="
			}
		],
		[
			"f4ctfasjlg6k48lvn20gn7ouy980gi:DVS",
			{
				"id": "f4ctfasjlg6k48lvn20gn7ouy980gi",
				"token": "djI6ZjRjdGZhc2psZzZrNDhsdm4yMGduN291eTk4MGdpOjE6MTkyLjE2OC4zMC4xMToxMTAxMDowOjcuMDAuMTcwMTE3QQ==:djE6RFZTOnBhb2xhLnNpbHZhOjJybnVMRkRNZW9OMHJmaC9TYUg1ZTVlNTNCcnhYNHdTbVl4NlFFMGZlVUU9|djE6MTU3NjUxMDkyNjowOjE=.Rsa2eqjxowEd/99rcASUIpP2zVJfgVbzoqKbz4MQ0iS0RxaKwaCjRZ3xGohbeLWvOSwv+rncgeeqdidNSzkBlyHc+PO6ZBzW4bWjTBEEfKx/O9bAuAJD3gmwchpOpiTKiF2/Jq22ymmRbv0SauGfAcqSAxXo70rfDtiuse8GydrxXSu0qqZ2sbiDnTaQmg8pkfkt+i0zMGOe1JD4SXXalgaBsF5y80dLEba1DqtQsJKdahpSDHPpT/vgsugsCrbn/RgpCb1LXHC3lXw1bPpBUu3nmDB0xOuUjSGk5DOkr/AAwfy+m5q6WnoinkXJg3YS3d+GMNImAH5V7dKyiZGw1g=="
			}
		],
		[
			"f4ctfasjlg6k48lvn20gn7ouy980gi:DVSA",
			{
				"id": "f4ctfasjlg6k48lvn20gn7ouy980gi",
				"token": "djI6ZjRjdGZhc2psZzZrNDhsdm4yMGduN291eTk4MGdpOjE6MTkyLjE2OC4zMC4xMToxMTAxMDowOjcuMDAuMTcwMTE3QQ==:djE6RFZTQTpwYW9sYS5zaWx2YTpZQUVJM1NzdytWUEV5ZjBnbTJleU1jcDlONDRUL044cnhHODZWUDQyd2hvPQ==|djE6MTU3NjUxMTI1NjowOjE=.IHBPCGF5cJp2CCgN25SlJrqFgxSp1sFCpMVG7seS0W2Lnn8F1hWw0VDwOqQQQvMZnyf1Ey0TDWomPdl73q44ezyfGPt07pn82yXY5PZbnFg6CN1IEDBm2sM8LfSF1wcNGHES8boWDBX405H15b69bEBBsjtJwOBFZ2tuow/WN6GJdbv7sN6M1Yo27A1vej0Xa4b0Pmbm3uraz+XBsXgZ3P7+CVUrf7NGtvf6bkKxamwPe7pqIGnVrc7Z8h1fKF3/42F+/GpzmqH4BtH82C4Lt1uCZXAqfUgEVh5vghpyJg8lBdxhKPC1b6cmgnv2zQIFiAC3L7NKv44M330Pp3rh/g=="
			}
		],
		[
			"f4ctfasjlg6k48lvn20gn7ouy980gi:DVSC",
			{
				"id": "f4ctfasjlg6k48lvn20gn7ouy980gi",
				"token": "djI6ZjRjdGZhc2psZzZrNDhsdm4yMGduN291eTk4MGdpOjE6MTkyLjE2OC4zMC4xMToxMTAxMDowOjcuMDAuMTcwMTE3QQ==:djE6RFZTQzpwYW9sYS5zaWx2YTphWmgxQXc5Sm5iVlFtamtKejN0dndadWJ5M1kvcm91MkFwVlZBeC9PaTBNPQ==|djE6MTU3NjUxOTkyMjowOjE=.UUGjIYt8vtR2GJ+uLf3nxf/tWnpunz6gD/cdES8/060LPNmCJ6gVPqt/LJTzwJdVWZvdCl6QBuMk0R4IP8yXUwPx48zH4Q+PLUu0TdNjlo4KMD2s5RFRmq4qy+OSR7beDtcAIAarZ9LMif+GzbpQz6l5cuMAmgiS/ONAsTUwy7au7yDf31tfXYZjCx0mjNljPwCJEKY4bBZz/6n3XWuXx3B4ScvVMKdn9WMQTgJPqcurOBUPnZTNn5EpviPcZGJi8n6i1mQZGTOPcZ5LKMiYnm9ab+HB+cH3X9hKkwIcZmf41VY9xlfG7G7A6yUe1Na4lrftC0GO2dSaHJu8wj9+6A=="
			}
		]
	]
}

**Comment by lwtnb-wrk** [comment]
@paolastekl Voce ainda tem algum ambiente 12.1.17 ou 12.1.23 para verificar se é um problema especifico da 12.1.25?

**Comment by paolastekl** [comment]
É um problema da 25 mesmo. Nas versão anterior, a 1.17 não tenho problemas.

**Comment by lwtnb-wrk** [comment]
@paolastekl Notei somente agora que voce acessou via SIGAMDI. 
Poderia tentar acessar diretamente o modulo, por exemplo, SIGAFAT e verificar se o problema persiste?

**Comment by caiadofelipe** [comment]
@paolastekl , As vezes tenho esse problema, mas é quando tento executar um smartclient de outra versão que não é a 25 no CTRL+F5.

**Comment by lwtnb-wrk** [comment]
@paolastekl Foi liberada uma nova versão com alterações diversas em relação ao debug, por favor verifique se nesta ultima versão o problema foi resolvido.
Grato.

**Comment by paolastekl** [comment]
Agradeço o apoio! Consegui resolver. O problema estava que no meu .ini estava direcionando para o Broker e com isso ele não conecta, deixando o .ini apontado para uma porta específica consegui conectar normalmente.

**Comment by ricardomansano** [comment]
Boa tarde @paolastekl ,

Agradeço o retorno, qualquer problema nos informe.
