### ISSUE TITLE
Compilação para apos erro FATAL. 

### ISSUE THREAD

**Issue by rtorquette** [totvs/tds-vscode#229]
**Describe the bug**
Após solicitar a compilação de uma pasta, ou uma listas selecionada e encontrar um  erro de compilação "Cannot overwrite TOTVS programs (XXXXXX.PRW)", todos os elementos a serem compilados após a progrma com erro apresentam o mesmo erro, somente sendo possível retomar a compilação após desconectar e conectar novamente no ambiente. 

**To Reproduce**
1. Selecionar a lista de arquiivos que deseja compilar, clicar com o botão direito e escolher a opção "Complile File"
![image](https://user-images.githubusercontent.com/58786746/70648528-fce00c80-1c29-11ea-97a8-55db3bd03626.png)

2. Veja que os arquivos selecionados vão do "ACOM003.PRW" até "BEMM500.prw"
3. Após a compilação o resultado é o seguinte:
![image](https://user-images.githubusercontent.com/58786746/70649695-711baf80-1c2c-11ea-864f-df4f4c59746e.png)
4. Após este erro (o arquivo "ATFA500.PRW" está compilado com chave, por isso não pode ser sobreposto), qualquer compilação que for realizada, em qualquer arquivo, apresenta este mesmo erro e somente é possível a compilação de novos fontes após a desconexão e nova conexão com o ambiente.

**Expected behavior**
A compilação deveria continuar nos demais arquivos apresentando a mensagem e status da compilação (cor do arquivo) correta.

**Comment by lwtnb-wrk** [comment]
@rtorquette Realizei testes e observei que mesmo com erro FATAL a compilacao continua e apresenta os erros corretamente.

Qual a possibilidade dos dois arquivos, que apresentaram erros, estarem tentando sobrescrever funções que estão compiladas no ATFA500.PRW?

**Comment by lwtnb-wrk** [comment]
fechado por falta de retorno
