### ISSUE TITLE
Chave de compilação com ID do TDS

### ISSUE THREAD

**Issue by gustavo-krug** [totvs/tds-vscode#23]
Gerei minha chave de compilação conforme o ID exibido no TDS, e só depois da chave gerada eu vi na documentação a seguinte mensagem: 
"A partir de 17/05/2019 todas as chaves devem ser regeradas utilizando o ID exibido no nosso plugin do VSCode. Isse se faz necessário para suporte de Linux e MAC."

Entendo a regra, mas não faço utilizo ambiente Windows para desenvolvimento.
No ambiente Windows ele não poderia continuar aceitando a chave como era gerada anteriormente?

**Comment by matheus-sales** [comment]
@gustavo-krug Não é possível manter a forma antiga pra windows, primeiro porque fizemos alterações no algoritmo e na segurança em geral. Não é só por conta no Linux e Mac

**Comment by matheus-sales** [comment]
@gustavo-krug Vale lembrar que o programa gerador é o mesmo, mudando apenas o ID que deve ser utilizado pra gerar a chave e toda chave tem validade de no máximo 3 meses.

**Comment by lwtnb-wrk** [comment]
Conforme informado pelo @matheus-sales por questões de segurança as chaves de compilação criadas para o TDS (Eclipse) não funcionarão no tds-vscode, sendo necessario requisitar uma nova chave com o ID informado na tela da chave de compilação do tds-vscode.
