### ISSUE TITLE
Ao formatar o documento a identação fica errada quando existe #ifdef

### ISSUE THREAD

**Issue by luizhj** [totvs/tds-vscode#230]
Ao executar a formação do arquivo prw que contem #ifdef a identação fica errada, parece que não identifica #endif

1- crie um arquivo prw.
2- crie um fluxo com #ifdef dentro de #ifdef e um #else
3- formate o arquivo com shift+alt+f ou no menu contexto

![image](https://user-images.githubusercontent.com/16191002/70715448-15ebca80-1cc9-11ea-99a0-c25bfa6814b5.png)

VSCODE 1.40.2
tds-vscode 0.321

**Comment by lwtnb-wrk** [comment]
@luizhj A correção será disponibilizada na próxima release
