### ISSUE TITLE
Não compila e fica congelado

### ISSUE THREAD

**Issue by PatrickZerbinatti** [totvs/tds-vscode#234]
**Describe the bug**
Ao tentar compilar um fonte que possua apenas uma linha de comentário, sem os includes, ele congela a compilação, não trava nada, porem não permite que eu compile mais nada também.
![bug_compilador](https://user-images.githubusercontent.com/33162950/71665092-46f47380-2d3a-11ea-996c-ee2f6bdc7472.PNG)

**To Reproduce**
1.Preencha um fonte apenas com uma linha de comentario
2.Compile
3.Nada acontece

**Desktop (please complete the following information):**
 - OS/Architecture: Windows 64 bits

**Comment by ricardomansano** [comment]
Bom dia @PatrickZerbinatti ,

O que vc esta tentando fazer vai "jogar" um fonte vazio pro RPO, pois os comentários são suprimidos na pré-compilação, e isso não é permitido.

Compile um fonte com uma função qualquer, como no exemplo abaixo, isso vai funcionar:

function u_dummy1()
return

**Comment by PatrickZerbinatti** [comment]
Mas ele tem uma validação que fala quando o fonte esta vazio, certo? Por que não aplicar essa validação para este caso também?

**Comment by ricardomansano** [comment]
Por que é desnecessário, não existe "o porque" de um fonte vazio.

**Comment by PatrickZerbinatti** [comment]
A, aqui nós só deixamos para não perder as nossas sequencias, pois apagamos alguns fontes inuteis na virada do lobo. Mas enfim, obrigado.

**Comment by ricardomansano** [comment]
Como eu disse na interação anterior, vc pode continuar este processo incluindo a função dummy, com o mesmo nome do fonte por exemplo, assim não perderá um recurso que facilita sua organização de projetos.

**Comment by PatrickZerbinatti** [comment]
Só de colocar os includes funciona também, esta tudo certo.
