### ISSUE TITLE
Aplicação de Patch

### ISSUE THREAD

**Issue by juliooriebir** [totvs/tds-vscode#235]
Boa tarde.
Estou utilizando o VSCode no linux Ubuntu 18.04.3 LTS, ao tentar aplicar um patch a seguinte mensagem de erro foi apresentada.

**File could not be copied to the server.**

**Comment by lwtnb-wrk** [comment]
@juliooriebir Verifique se alguma das pastas ou subpastas que estão sendo utilizadas contem caracteres em maiúsculo.
Existe uma limitação do appserver em relação ao tratamento de nome de pasta com caracteres em maiúsculo.
Você pode também copiar o patch para uma pasta aonde não existe nenhum carácter em maiúsculo (inclusive nas subpastas) e aplicar deste local.

**Comment by cintiapaul** [comment]
Estou utilizando o VSCode, utilizando a extensão do TDS. 
Seleciono a opção para aplicar patch e no console do Appserver aparece que o patch está sendo aplicado, porém após o término, a data do fonte que constava no patch não foi alterada. Seguem imagens anexas. 
![appserver](https://user-images.githubusercontent.com/52964891/72354098-e8c57a00-36c3-11ea-9ad1-3fbd18def0a1.png)
![VSCode](https://user-images.githubusercontent.com/52964891/72354099-e8c57a00-36c3-11ea-8121-bc2685359dbc.jpg)

**Comment by cintiapaul** [comment]
@lwtnb-wrk você consegue ajudar?

**Comment by lwtnb-wrk** [comment]
@juliooriebir Esta issue esta sendo fechada pois não tivemos retorno acerca da solução proposta

@cintiapaul Abra uma outra issue descrevendo seu problema, que é diferente da informada nesta issue, e adicione a maior quantidade de informações possiveis para a reproducao do problema.
