### ISSUE TITLE
Não esta excluindo objeto do RPO

### ISSUE THREAD

**Issue by jvvasquesn** [totvs/tds-vscode#236]
Bom dia.
Ao tentar excluir um fonte do RPO é apresentado as mensagens abaixo no Log, porem o objeto não é excluido.

[Info  - 10:07:46 AM] Starting program deletion.
[Log   - 00:00:00] Starting build for environment stalo01.

Loguru caught a signal: SIGILL
(  72.036s) [querydb         ]                       :0     | Signal: SIGILL
[Info  - 10:07:49 AM] Connection to server got closed. Server will restart.
[Info  - 10:07:49 AM] Initializing Language Server.
[Info  - 10:07:49 AM] Language Server initialized.

**Comment by lwtnb-wrk** [comment]
@jvvasquesn Não reproduzi o problema aqui. 

Seu tds-vscode está atualizado? Que ambiente você esta usando? 
Reiniciou o VS Code e tentou outras vezes? O problema ocorre com a exclusão de qualquer fonte do RPO?

**Comment by jvvasquesn** [comment]
@lwtnb-wrk 
Seu tds-vscode está atualizado?
_**Sim está, Versão 0.3.23**_

Que ambiente você esta usando?
_**Build AppServer: 7.00.131227A-20180920 NG - 32 bits**_

Reiniciou o VS Code e tentou outras vezes?
_**Sim**_

O problema ocorre com a exclusão de qualquer fonte do RPO?
_**Tentei com 3 fontes e todos com o mesmo resultado**_

**Comment by lwtnb-wrk** [comment]
@jvvasquesn Voce esta com o Ubuntu correto? Consegue testar em outro SO?

E isso ocorre com qualquer versao de AppServer? Ou ocorre apenas com uma versão especificamente?

**Comment by jvvasquesn** [comment]
@lwtnb-wrk 
Estou usando o Ubuntu 16.04, infelizmente não tenho outro SO no meu note.
Atualmente so estou trabalhando com a versão 7.00.170117A do Protheus.

**Comment by ricardomansano** [comment]
Boa tarde novamente @jvvasquesn, mais um caso nao reproduzido, e que suspeitamos de sua versão do Ubuntu.
Vc consegue atualizar pro 18.04LTS facilmente, inclusive isso deve lhe ser questionado com frequencia, pois o update do Ubuntu é insistente.
Sugerimos que faça essa atualização.
Grato pelo report,
