### ISSUE TITLE
Erro ao conectar em servidor com o novo binário 7.00.191205P

### ISSUE THREAD

**Issue by gustavo-krug** [totvs/tds-vscode#238]
Olá

Atualizei o binário da minha base 12.1.25 para a versão 7.00.191205P.
Ao tentar criar uma nova conexão, não reconhece o buildVersion.
Mesmo preenchendo o buildVersion="7.00.191205P", não conecta.

O erro ocorre apenas para esta versão de build, se eu voltar a versão, conecta. Entretanto, preciso conectar com esta versão pois o License me impede de utilizar o sistema com binário desatualizado.

![image](https://user-images.githubusercontent.com/45034725/72014513-caccc500-323e-11ea-8513-b53a7dabebc3.png)

![image](https://user-images.githubusercontent.com/45034725/72014564-dfa95880-323e-11ea-810d-3e11bccbafe2.png)

**Comment by lwtnb-wrk** [comment]
@gustavo-krug Primeiro, imagino que já tenha atualizado o plugin para a última versão, certo?

Pela sua descrição, se voltar a buildVersion para 7.00.170117A e conectar, seu AppServer é um 7.00.170117A e portanto não vai mesmo reconhecer a buildVersion 7.00.191205P. Certifique-se que está realmente usando um AppServer 7.00.191205P e cadastre um novo servidor para seu acesso.

**Comment by gustavo-krug** [comment]
![image](https://user-images.githubusercontent.com/45034725/72065761-b7ad0a00-32bd-11ea-9e7c-a131c00d15c3.png)

Conforme print, meu appserver está sim com a buildVersion": "7.00.191205P
Quando adiciono um novo servidor para esse appserver, não reconhece a  versão e o buildVersion fica em branco no servers.json, conforme print.
![image](https://user-images.githubusercontent.com/45034725/72065926-1d00fb00-32be-11ea-8a15-638625bd5d8b.png)

Ainda assim, mesmo que eu preencha o buildVersion com a nova versão 7.00.191205P, não conecta.

**Comment by danielbolognani** [comment]
@gustavo-krug Verifique também se por acaso a conexão SSL está ativa no AppServer 191205P, se estiver, precisa ativar a tag "secure" também no VSCode.
No build 19, a conexão SSL é ativada por padrão.

**Comment by gustavo-krug** [comment]
No appserver não há nada sobre conexão SSL, mas como comentou que por padrão esta conexão é ativa, habilitei a tag secure no VS Code e consegui conectar. Obrigado @danielbolognani

**Comment by danielbolognani** [comment]
Bom dia @gustavo-krug, na verdade no console do AppServer avisa:
[INFO ][SERVER] [MPPORT] Starting Multi Protocol using default SSL
De qualquer forma, que bom que deu certo :)
