### ISSUE TITLE
Não consigo compilar fontes Vs Code

### ISSUE THREAD

**Issue by thiagorover** [totvs/tds-vscode#239]
Bom dia,

Após migra do Tds para Vs Code com a extensão Totvs Developer Studio for VSCode identifiquei que todas as vezes que solicitava a compilação de um fonte o mesmo não ocorria, era apresentado a mensagem de Recompile Fineshed, porém, meu inspetor de objetos permanece com a data antiga.

Notei que a aba Problems não lista os Erros\Warns, mesmo compilando um fonte que existe algum erros apresenta essa mensagem:
"No problems have been detected in the workspace so far"

Log de compilação:

[Warn  - 11:12:58] Source c:/Users/thiago.rover/source/Workspaces/Protheus_Padrao/Fontes_Doc/Master/Fontes/Gestão de Qualidade/Gestão de Inspeção de Processos/QIPXFUN.PRW precompiled with warnings and/or errors.
[Log   - 00:00:00] Committing end build.
[Warn  - 11:12:58] One or more files have warnings and/or errors. See problems and logs for details.
[Info  - 11:12:58] Recompile finished.
![Print_compilação_Output](https://user-images.githubusercontent.com/43826096/72155898-e943d500-3392-11ea-96d3-7d3f1eb8ba4b.png)
![Print_compliação_Problems](https://user-images.githubusercontent.com/43826096/72155939-037db300-3393-11ea-9268-e88d0f6b1a81.png)

**Comment by lwtnb-wrk** [comment]
@thiagorover Me parece que o Appre retornou alguma mensagem de erro que não era prevista e por isso não apareceu na visão "Problems".

Por favor, adicione a chave:
    "totvsLanguageServer.launch.args": [
        "--log-file=totvsls.log",
        "--record=totvsls"
    ],
no arquivo settings.json de seu projeto e reinicie o VS Code. Um arquivo "totvsls.log" deve ser gerado durante as novas execuções.

Reexecute as operações de compilação e nos envie o arquivo gerado para analises.

Grato,

**Comment by danielbolognani** [comment]
Normalmente esses erros de compilação sem mensagem de erro estão relacionados a configuração de includes. De uma olhada nessa configuração e confirme que sua pasta de include possui todos os arquivos chs necessários.

**Comment by thuliofilipp** [comment]
> Normalmente esses erros de compilação sem mensagem de erro estão relacionados a configuração de includes. De uma olhada nessa configuração e confirme que sua pasta de include possui todos os arquivos chs necessários.

Perfeito, passei por esse mesmo problema quando estava indicando uma pasta do include que tinha outras subpastas.

Após a indicação da pasta correta do include deu tudo certo.

**Comment by thiagorover** [comment]
@lwtnb-wrk segue abaixo o arquivo totvsls.log.
[totvsls.log](https://github.com/totvs/tds-vscode/files/4047027/totvsls.log)

@danielbolognani analisei o apontamento da pasta include, porém está apontado correto, sem pasta dentro.

@thuliofilipp agradeço pelo contribuição também.

**Comment by thiagorover** [comment]
@lwtnb-wrk segue abaixo o arquivo totvsls.log.
[totvsls.log](https://github.com/totvs/tds-vscode/files/4047051/totvsls.log)

@danielbolognani analisei o apontamento da pasta include, porém está apontado correto, sem pasta dentro.

@thuliofilipp agradeço pelo contribuição também.

**Comment by ThiagoMarq** [comment]
Olá, estou enfrentando o mesmo problema. 
Porém a pasta include está indicada corretamente.
![image](https://user-images.githubusercontent.com/65978430/180759430-e0324492-a51a-4954-8b16-04754652b12a.png)
![image](https://user-images.githubusercontent.com/65978430/180759498-b84dce3a-7807-45d6-afd7-e1e6b72541ad.png)

Já tentei criar uma nova pasta, excluir o server e criar de novo, só que mesmo assim não consigo compilar.

**Comment by ThiagoMarq** [comment]
Issue Criada #1009
