### ISSUE TITLE
Mensagens exibidas na compilação poderiam ser apresentadas no output do console

### ISSUE THREAD

**Issue by delsonfilho** [totvs/tds-vscode#24]
Prezados, 

Ao compilar no vscode, o mesmo apresenta diversas mensagens na tela ao inves de mostrar no console na opção output.

Não seria possível mostra apenas essas informações nessa opção?
![WhatsApp Image 2019-05-20 at 12 51 07](https://user-images.githubusercontent.com/27447637/58045011-a38e7f80-7b17-11e9-8c0a-ae23e1cb88a1.jpeg)

**Comment by lwtnb-wrk** [comment]
Delson,
Por enquanto estamos exibindo ambas as informações, no console E notificações, porem conforme já foi sugerido, podemos implementar opções nas preferencias para que os usuarios possam escolher se desejam exibir notificações ou não.
![image](https://user-images.githubusercontent.com/49563478/58045472-fd437980-7b18-11e9-9e8c-2c49aca68cd0.png)

**Comment by lwtnb-wrk** [comment]
Vamos criar a preferencias para habilitar quais notificacoes serao exibidas atraves da Issue #25

**Comment by fmercurio** [comment]
É necessário fazer alguma configuração para que as informações de compilação (entre outras) sejam apresentadas na janela OUTPUT? Pois no meu ambiente os popups são apresentados normalmente, porém não está sendo apresentada mensagem alguma no OUTPUT ao compilar.

**Comment by lwtnb-wrk** [comment]
@fmercurio Veja em https://github.com/totvs/tds-vscode/tree/dev#console-de-sa%C3%ADda-output-advpl
Se algo nao estiver funcionando de acordo favor abrir uma nova issue.
Grato
