### ISSUE TITLE
Customizar Auto Complete

### ISSUE THREAD

**Issue by PatrickZerbinatti** [totvs/tds-vscode#240]
Não sei nem se o responsavel por isso é a extensão de vocês, mas será que não teria como adicionar de alguma forma um jeito de customizar o Auto Complete?
Por exemplo na imagem, a estrutura que o auto complete é a que esta no segundo quadro, porem eu gostaria que o cabeçalho que viesse fosse o do primeiro quadro, pois é o que utilizamos aqui.

![sugestão](https://user-images.githubusercontent.com/33162950/72161028-19dd3c00-339e-11ea-983e-f2c899d4e393.png)

**Comment by lwtnb-wrk** [comment]
@PatrickZerbinatti Isso me parece muito especifico para seu uso.
Se quiser experimentar, faça um fork e brinque com algumas alterações no arquivo snippets.json e veja se te atende.
Enfim grato pela sugestão mas não implementaremos isso por enquanto.
