### ISSUE TITLE
Compilar pasta

### ISSUE THREAD

**Issue by FabioStones** [totvs/tds-vscode#241]
Bom dia!

Olhando o vídeo (https://www.youtube.com/watch?v=Cz4N0XWCXHY) do Ricardo Mansano percebi que na versão dele havia a opção de Compilar a pasta (Compile Folder - Minuto 4:47). Essa opção é muito útil para mim pois, agrupo na Workspace não só a pasta do projeto da empresa, mas também locais onde crio programas para teste. Sem essa opção eu acabo compilando coisas que não são necessárias.

Aguardo retorno.

**Comment by danielbolognani** [comment]
Bom dia Fabio, se vc selecionar "Compile File" em cima de uma pasta, a pasta inteira será compilada, portanto a opção ainda existe!

**Comment by FabioStones** [comment]
Obrigado Daniel!
Sim, realmente ele compilou os arquivos da pasta selecionada.
