### ISSUE TITLE
Adicionar Ambiente

### ISSUE THREAD

**Issue by lucianoaol** [totvs/tds-vscode#242]
Ao clicar no sinal de + da aba Environment Manager para adicionar o ambiente que eu quero compilar aparece a mensagem: command 'advpl.serversManagement.AddServer' not found

**Comment by danielbolognani** [comment]
Bom dia, essa área é para problemas com o plugin TDS-VSCode (https://marketplace.visualstudio.com/items?itemName=totvs.tds-vscode), pela mensagem de erro parece que vc está com outro plugin instalado. Caso esteja e queira utilizar nosso plugin, garanta que só ele esteja instalado para tratar os arquivos ADVPL.
