### ISSUE TITLE
Templates ou Amostras

### ISSUE THREAD

**Issue by FabioStones** [totvs/tds-vscode#243]
Bom dia!

No antigo TDS, via Eclipse, havia uma opção chamada Amostras (Templates). Essa opção ficava em:
- Menu Janela/ Preferências
- Na árvore Developer Studio/ ADVPL/ Amostras

Nesta tela eu poderia criar várias amostras de um única linha ou diversas linhas, por exemplo:
Nome: MPSysOpenQuery
Descrição: Executa uma consulta no banco de dados atravpes de uma expressão SQL
Padrão: 

	Local cAlias    := ""
	Local cQuery    := ""
	Local aTCFields := {}

		//Campos formatados
		aAdd(aTCFields, {"${cCampo}", "${cTipo}", ${nTamanho}, ${nDecimal}})

		//Cria a consulta
		cQuery := "SELECT * "
		cQuery += "FROM " + RetSQLName("${tabela}") + " ${Alias} "
		cQuery += "WHERE ${Alias}.D_E_L_E_T_ <> '*' "
		cQuery += "AND ${Alias}.${Alias}_FILIAL = '" + xFilial("${Alias}") + "' "
	
		//Executa a pesquisa
		cAlias := MPSysOpenQuery(cQuery,, aTCFields)
	
		//Percorre os registros
		(cAlias)->(dbGoTop())
		Do While !(cAlias)->(EOF())
			${cursor}
			//Próximo registro
			(cAlias)->(dbSkip())
		EndDo
	
		//Fecha a conexão
		(cAlias)->(dbCloseArea())

Em cada ponto ${...} abria um campo para edição. Nos nomes iguais a informação digitada repetia a cada chamada colocada no exemplo.

No VC CODE existe essa opção e se existe onde a crio? Haveria uma forma de importar os templates do Eclipse no VSCODE?

Desde já agradeço

**Comment by lwtnb-wrk** [comment]
@FabioStones O recurso que voce procura se chama Snippets no VS Code.
No seu diretorio de usuario procure a pasta .vscode, nela voce vai encontrar a extensao do tds-vscode.
Dentro da pasta do tds-vscode existe a pasta snippets com o arquivo snippets.json onde estao os Snippets que ja fazem parte do TDS VS Code.
Edite esse arquivo conforme os snippets que ja existem e voce pode sugerir novos snippets para serem incorporados na extensao.

**Comment by FabioStones** [comment]
Olá!

Consegui fazer contudo, o que não ficou direito foi o código abaixo:
	cQuery := "SELECT * "
	cQuery += "FROM " + RetSQLName("${tabela}") + " ${Alias} "
	cQuery += "WHERE ${Alias}.D_E_L_E_T_ <> '*' "
	cQuery += "AND ${Alias}.${Alias}_FILIAL = '" + xFilial("${Alias}") + "' "

No original eu usava aspas duplas para a instrução SQL e simples para o texto da pesquisa. Agora tenho que trocar tudo para aspas simples? Como fica a concatenação da última linha onde deveria ser _FILIAL = '00'?

Aguardo retorno

**Comment by lwtnb-wrk** [comment]
@FabioStones Não sei responder esses detalhes de como tratar as aspas é necessario ver a documentacao do VS Code.
Se quiser colaborar com o snippet deste SELECT, faça um clone do projeto e submeta uma Pull Request que iremos incorporar nas proximas atualizacoes.
Valeu
