### ISSUE TITLE
Não consigo compilar um fonte advpl - Vs Code

### ISSUE THREAD

**Issue by thiagorover** [totvs/tds-vscode#244]
Boa tarde pessoal,

Estou tentando fazer a compilação de um fonte para validar minha codificação, porém, me deparei com essa situação, inspetor de objetos mostrou alteração data e hora do RPO, e a rotina quando faço o debug para em uma linha vazia, como se não tivesse conseguido compilar o fonte, vou anexar as imagens.

![Print Inspetor de Objetos](https://user-images.githubusercontent.com/43826096/72272370-447dfd80-3607-11ea-9a2d-122ef6972184.png)
![Print Debug linha](https://user-images.githubusercontent.com/43826096/72272380-49db4800-3607-11ea-9789-9d5ac8d27eaa.png)
![Print output](https://user-images.githubusercontent.com/43826096/72272474-70997e80-3607-11ea-9c5c-c55e67b7726c.png)

Alguma ideia ?

Cordialmente Rover.

**Comment by CarlosDev2591** [comment]
estou com o mesmo problema , vc resolveu ? pode me ajudar.
