### ISSUE TITLE
Posicionamento nas definições de variáveis e funções

### ISSUE THREAD

**Issue by WBaldin** [totvs/tds-vscode#246]
Seria possível fazer o posicionamento em variáveis e funções através do CTRL + Click, como é feito através do TDS Eclipse. É uma funcionalidade muito interessante e agiliza bastante os posicionamento nos códigos.

**Comment by ricardomansano** [comment]
Boa tarde @WBaldin , 

O nosso plugin é colaborativo, você pode propor um pull request com a melhoria

Grato

**Comment by WBaldin** [comment]
Então, mas não sei como desenvolver isso em VSCode e sim seria uma melhoria a ser desenvolvida na extensão.
