### ISSUE TITLE
Debug Ubuntu -  tds.getDAP failed

### ISSUE THREAD

**Issue by LucasFidelis** [totvs/tds-vscode#247]
Olá,
estou tentando realizar o debug de um fonte através do visual, porém, ao preencher a função advpl o seguinte erro é reportado na tela:

![image](https://user-images.githubusercontent.com/25336055/72532852-e0e81000-3852-11ea-9675-2b08bf4f84e1.png)

Segue o launch.json

`{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Totvs Language Debug",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "/totvs/smartclient/smartclient",
			"isMultiSession": true,
			"enableTableSync": true,
			"programArguments": [
				"${command:AskForProgramArguments}"
			],
			"enableMultiThread": true,
			"enableProfile": false,
			"isAccessibilityMode": false,
			"doNotShowSplash": false,
			"language": "",
			"ignoreFiles": true
		}
	],
	"lastPrograms": [
		{
			"args": [],
			"label": "sigaloja",
			"description": ""
		}
	],
	"lastProgramExecuted": "sigaloja"
`}``

 - OS/Architecture: Ubuntu 18.04 64 bits

**Appserver:**
 - Build: 7.00.170117A-20200102 - 64 bits
 - OS/Architecture: Windows Server 2016 Standard 64 bits

**Comment by LucasFidelis** [comment]
Referente ao erro acima, existe a mesma relação com outra issue #180 .
A solução foi apagar todas as configurações relacionadas ao visual, extensão e criar um novo workspace. (Não podendo neste caso apenas copiar e colar arquivos de uma workspace anterior, pois, neste caso, o erro retorna)

Portanto, segue funcionando normalmente.

**Comment by lwtnb-wrk** [comment]
@LucasFidelis Grato por compartilhar a solução de seu problema.
