### ISSUE TITLE
Configurar chave de compilação: Authorization token must be informed

### ISSUE THREAD

**Issue by nicholaswgd** [totvs/tds-vscode#248]
**Describe the bug:**
Após realizar as configurações gerais do ambiente, sigo para inserir a chave de compilação, e ocorre o erro abaixo:

![Capturar](https://user-images.githubusercontent.com/21965230/72536612-5525b200-3859-11ea-82db-83a7f01549d4.JPG)

[Log   - 00:00:00] Starting authorization legacy request.
[Error - 13:03:22] Invalid key (code: 4500.1).
[Error - 13:03:22] Authorization token must be informed.

**To Reproduce**
1. Configurar uma conexão com o appserver
2. Realizar a importação da chave de compilação

**+ Infos**
- Chave de compilação está válida
- Chave funciona no TDS
- Consigo compilar os fontes
- Consigo abrir User Functions diretamente
- Consigo realizar chamada do Smart

**Comment by lwtnb-wrk** [comment]
@nicholaswgd A chave de compilação utilizada no TDS Eclipse não é compatível com o TDS VS Code.

Na tela do Compile Key, observe que o Machine ID provavelmente não é a mesma que consta na chave de compilação que voce tem.

Requisite uma nova chave de compilação informando essa nova Machine ID e teste novamente.
