### ISSUE TITLE
Atalho F12 (pergunte) não é ativada no debug

### ISSUE THREAD

**Issue by rubensredel** [totvs/tds-vscode#249]
Ao realizar um debug (F5) em telas que fazem uso do F12 (função Pergunte) não são ativadas ou não tem nenhum efeito. Em anexo temos a mesma tela acessando o mesmo ambiente. Enquanto que no ambiente padrão (sem debug) a tecla F12 é ativada e os parâmetros aparecem, no ambiente com o debug o mesmo não aparece e suas variáveis não são carregadas.

![f12-debug](https://user-images.githubusercontent.com/51825277/72616128-01789e80-3915-11ea-8f26-501271ceb1ce.png)
![f12-sem-debug](https://user-images.githubusercontent.com/51825277/72616129-01789e80-3915-11ea-9fe3-5156d8cfbac8.png)

**Comment by lwtnb-wrk** [comment]
@rubensredel Esse é um comportamento do framework da TOTVS e não temos nenhum tipo de controle sobre isso no TDS VS Code.
Se achar necessário abra um chamado na TOTVS pedindo a alteração deste comportamento para o time do framework.
