### ISSUE TITLE
Permitir configurar quais notificações serão exibidas.

### ISSUE THREAD

**Issue by lwtnb-wrk** [totvs/tds-vscode#25]
Permitir configurar (atraves de Settings) quais notificações serão exibidas (Nenhuma, Apenas Erros, Erros + Warnings, Todas)
Assim quem preferir mais informações visuais pode alterar conforme seu gosto.

**Comment by lwtnb-wrk** [comment]
Relacionada a Issue #24

**Comment by brodao** [comment]
Adicionado opção de configuração, onde o usuário define qual o nível de mensagem que será notificada via 'popup'. Independente da configuração, todas as mensagens serão apresentadas no log de console "AdvPL".
![configuração de apresentação de mensagens](https://user-images.githubusercontent.com/949914/58205040-01f06500-7cb4-11e9-9a6d-a4b7ef361326.png)

**Comment by lwtnb-wrk** [comment]
ainda falta a implementacao do lado do LS
