### ISSUE TITLE
App server zerado

### ISSUE THREAD

**Issue by yurysilva** [totvs/tds-vscode#250]
Apaguei o servidor como no video para poder criar um novo, mas agora não consigo adicionar outro servidor, o programa trava se coloco meu servidor, endereço e porta, sem falar que quando tento por inlcudes não mostra nada na pasta, além de que o botão direito não funciona na parte de servidores, ele não me dá os opções.
![image](https://user-images.githubusercontent.com/52840612/72635140-def97c00-393a-11ea-81a6-465da34085cc.png)

![image](https://user-images.githubusercontent.com/52840612/72635446-a1e1b980-393b-11ea-8990-548a4fc528d8.png)
Mas se tiro isso informação o botão funciona
![image](https://user-images.githubusercontent.com/52840612/72635532-c9d11d00-393b-11ea-9c90-90297c5e0663.png)

Agradeço a atenção
Att:
Yury

**Comment by lwtnb-wrk** [comment]
@yurysilva Não conseguimos reproduzir o seu problema aqui. O cadastro de servidores está funcionando sem problemas. Nos de mais detalhes de como o problema pode ser reproduzido ou tente desinstalar a extensão e instalar novamente.

Quanto a questão da seleção da pasta de includes ele não exibirá o conteúdo da pasta mesmo. Serve apenas para a seleção da pasta de includes a ser adicionada na configuração deste servidor.

**Comment by yurysilva** [comment]
Certo! então fui meio descuidado e fiz todos os passos do video sem atenção, e exclui o servidor que já pronto pela extensão e não consigo mais fazer outro, acho que danifiquei o .json. Já tentei desinstalar ela varias vezes, mas ela já vem sem o servidor com os mesmos problemas.

**Comment by lwtnb-wrk** [comment]
@yurysilva Voce editou o arquivo servers.json manualmente? 

Se for o caso, voce pode renomear o arquivo servers.json para qualquer coisa com TDS VS Code fechado e ao abri-lo ele vai criar um novo arquivo, e voce deve conseguir adicionar os servidores novamente.

**Comment by yurysilva** [comment]
Acho que foi esse aquivo que apaguei
![image](https://user-images.githubusercontent.com/52840612/72920259-b650f800-3d27-11ea-880e-a34b5ff11277.png)

**Comment by yurysilva** [comment]
Aparece esse error

![image](https://user-images.githubusercontent.com/52840612/72921236-ae925300-3d29-11ea-87f5-c642089e2d30.png)

**Comment by lwtnb-wrk** [comment]
@yurysilva Veja que o arquivo servers.json está na pasta .totvsls que está na sua pasta de usuário. Ela que deve estar com problemas e não as do seu projeto. 
Apague/renomeie esse arquivo "servers.json" e veja se consegue cadastrar um novo servidor.

**Comment by yurysilva** [comment]
Opa! Foi. Só não estou conseguindo debugar fonte.
Fala que não tem suporte .jsnon nessa parte
![image](https://user-images.githubusercontent.com/52840612/72925749-fae19100-3d31-11ea-9d95-380ecd66d282.png)

**Comment by yurysilva** [comment]
Dá essa mensagem
![image](https://user-images.githubusercontent.com/52840612/72926185-c1f5ec00-3d32-11ea-93c4-feb88ca95b60.png)

**Comment by lwtnb-wrk** [comment]
@yurysilva Está com cara que voce tem outra extensão que trata de AdvPL instalada, ou voce esta aproveitando uma pasta que foi usada por outra extensão.

Remova ou renomeie o arquivo launch.json e crie uma nova configuração de Debug.

Se continuar a ter problemas abra outra issue, pois estou fechando essa pois o problema relatado foi resolvido.
