### ISSUE TITLE
Associar smartclient à servidor conectado

### ISSUE THREAD

**Issue by gustavo-krug** [totvs/tds-vscode#251]
Há alguma maneira de alterar o smartclient definido no launch.json com base no servidor conectado? 
Por exemplo, tenho os ambiente Protheus 12.1.17(32 bits) e Protheus 12.1.25(64 bits). Há alguma forma de conectar o servidor da Protheus 12.1.17 e o launch.json entender que deve alterar o smartclient? Segue vídeo
[https://drive.google.com/file/d/1saCr-mZIQ_zk4sB708q7Grnu3bVJDwm2/view?usp=sharing]()

**Comment by lwtnb-wrk** [comment]
@gustavo-krug Sua ideia é bem interessante.
Se quiser implementar e submeter uma Pull Requeste ficaremos felizes em avaliar sua implementação.

**Comment by ricardomansano** [comment]
Agradecemos a sugestão, e nosso repositório estara sempre aberto para melhorias ao produto
