### ISSUE TITLE
Opção "Select" no menu contextual do conexão ambiente não esta funcionando 

### ISSUE THREAD

**Issue by AleksSyntek** [totvs/tds-vscode#253]
**Describe the bug**
Boa tarde, na vista do Totvs Servers é com una conexão ativa ao tentar seleccionar o ambiente distinto com o menu contextual, o comando "_Select_" (_Seleccionar_ no Espanhol) o TDS não troca a conexão, só faz isso desde o iten na barra do estado do VSCode.
Segue o link do video [https://imgur.com/a/xEE8oC7](url)
**To Reproduce**
1. Seleccionar o conexão
2. Click no menu _Conectar/Connect_
3. Seleccionar ambiente, ex: _mp12Test_
4. Click com botão dereito no outro ambiente no mesma conexão ex. _mp12test2_
5. Seleccionar opão do menu contextual _Seleccionar/Select_
6. Não troca o ambiente ativo

**Expected behavior**
Devería trocar a conexão ativa ao seleccionar o menu contextual _Select_

**Desktop (please complete the following information):**
 - OS/Architecture: Windows 10 Professional x64
 - Versão VSCode: 1.40.1
 - Versão TDS for VSCode: 0.3.23

**Appserver (please complete the following information):**
 - Build (with date): Build 7.00.131227A - Jul 3 2019 - 22:16:49 NG (x32)
 - OS/Architecture: Windows Server 2012 R2
 - Build Version: 13.2.3.44

**Comment by lwtnb-wrk** [comment]
@AleksSyntek Realmente esta opção parece não estar funcionando.
Se quiser corrigir e submeter uma Pull Request ficaremos felizes em avaliar sua implementação.

**Comment by AleksSyntek** [comment]
Boa tarde @lwtnb-wrk vou a fazer os testes e enviarle enquanto tenha una possível solução o pull request.
Slds.

**Comment by lwtnb-wrk** [comment]
@AleksSyntek Nas proximas liberaçoes esta questao sera resolvida. 
Grato pelas informacoes.

**Comment by AleksSyntek** [comment]
Boa noite, estaba olhando o commands e achoq eu si podemos ativar no menu contextual o seguente command:
`authenticate(server, environment, state.username, state.password);`
tomando os dados do árvore do servers é com os dados gravados no servers.json devería permeter trocar o servidor/ambiente

**Comment by lwtnb-wrk** [comment]
corrigida na versao 1.0.1
