### ISSUE TITLE
Auto Complete não traz funções personalizadas

### ISSUE THREAD

**Issue by PatrickZerbinatti** [totvs/tds-vscode#254]
Uma coisa que venho notando é que nunca o autocomplete sugere funções customizadas.
![autoComplete](https://user-images.githubusercontent.com/33162950/72898463-e508a780-3d02-11ea-8bcc-ddfa48fd4f95.png)
Teria alguma configuração que eu possa fazer para isso acontecer? E em caso de classes customizadas ao digitar por exemplo"classe:" ele sugerir pra mim os métodos dessa classe?

**Comment by lwtnb-wrk** [comment]
@PatrickZerbinatti Esta funcionalidade está em nosso Roadmap porém sem previsão para implementação.
Se quiser implementar e submeter uma Pull Request ficaremos felizes em avaliar sua implementação.

**Comment by ricardomansano** [comment]
Boa tarde,

@PatrickZerbinatti , na verdade não é algo que se consiga resolver via pull request, temos a previsão de começar a escrever nosso parser no 2o semestre, e sem essa ferramenta não há como implementar a busca de funções.

Manteremos as comunidades alinhadas quando este ferramental estiver pronto
