### ISSUE TITLE
Erro ao conectar o servidor

### ISSUE THREAD

**Issue by willianvilhena** [totvs/tds-vscode#255]
Instalei a extensão em um SO MacOS versão Catalina e ao tentar conectar no servidor, a IDE apresenta a seguinte mensagem:
Error running command totvs-developer-studio.connect: Running the contributed command: 'totvs-developer-studio.connect' failed.. This is likely caused by the extension that contributes totvs-developer-studio.connect.

verifiquei as sugestões documentadas na issue #212 
 - Desinstalei as extensões anteriores
 - Apaguei as extensões da pasta ~./vscode/extensions
 - Reinstalei a extensão tds-vscode
 - no arquivo de configuração servers.json defini o valor de secure para 0

Notei que ao iniciar o vscode recebo o seguinte erro:
The TOTVS AdvPL Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

**Comment by danielscheeren** [comment]
Olá.
Aconteceu exatamente o mesmo comigo @willianvilhena, as sugestões na issue #212 também não resolveram.

Depois de fuçar bastante, instalar versões antigas e deletar arquivos.
Encontrei a pasta \\.totvsls dentro da pasta de usuários. (No meu caso "C:\Users\Daniel\\")
Notei que mesmo excluindo o plugin não estava apagando essa pasta.
Deletei ela e reinstalei o plugin.
Configurei a conexão de novo e voltou a funcionar.

Resumindo:
- Desinstale o plugin.
- Feche o VSCode.
- Delete a pasta \\.totvsls dentro da pasta do seu usuário.
- Abra o VSCode e reinstale o plugin.

**Comment by willianvilhena** [comment]
Estou usando o MacOs, dei uma vasculhada aqui e não achei a pasta com esse nome, obrigado pela resposta @danielscheeren

**Comment by danielscheeren** [comment]
@willianvilhena Clica no plugin e na área dos servers clica na engrenagem, vai abrir o arquivo "servers.json".
Logo abaixo da aba do arquivo tem o caminho onde ele está.
Essa pasta deve corresponder à minha \.totvsls.

![Server totvs](https://user-images.githubusercontent.com/45018228/73305281-8ce90e00-41f8-11ea-9dad-37d1d80037e5.jpg)

**Comment by ricardomansano** [comment]
@danielscheeren , siga a dica do @willianvilhena , ela vai te levar à pasta .totvsls onde poderá seguir a dica dele.
Esse problema ja foi reportado outras 2 ou 3 vezes, mas estamuito mais envolvido no processo de instalação do plugin do que no plugin em si.
Temos outra issue que aparente ser o mesmo problema (#257 ), peço a gentileza de acompanhar por ela.
Continuamos na escuta,

**Comment by willianvilhena** [comment]
Obrigado @danielbolognani, exclui a pasta informada e reconfigurei os servidores e conectou certinho.

**Comment by danielscheeren** [comment]
> @danielscheeren , siga a dica do @willianvilhena , ela vai te levar à pasta .totvsls onde poderá seguir a dica dele.
> Esse problema ja foi reportado outras 2 ou 3 vezes, mas estamuito mais envolvido no processo de instalação do plugin do que no plugin em si.
> Temos outra issue que aparente ser o mesmo problema (#257 ), peço a gentileza de acompanhar por ela.
> Continuamos na escuta,

@ricardomansano Foi eu que dei a dica hehehe.
Mas obrigado pela resposta.
Abraço!

**Comment by ricardomansano** [comment]
> > @danielscheeren , siga a dica do @willianvilhena , ela vai te levar à pasta .totvsls onde poderá seguir a dica dele.
> > Esse problema ja foi reportado outras 2 ou 3 vezes, mas estamuito mais envolvido no processo de instalação do plugin do que no plugin em si.
> > Temos outra issue que aparente ser o mesmo problema (#257 ), peço a gentileza de acompanhar por ela.
> > Continuamos na escuta,
> 
> @ricardomansano Foi eu que dei a dica hehehe.
> Mas obrigado pela resposta.
> Abraço!

Então troquei as bolas, foi mal...
Valew a dica
