### ISSUE TITLE
Não conecta no server do logix pelo plugin  TDS para VSCode

### ISSUE THREAD

**Issue by michellerhen** [totvs/tds-vscode#256]
**Describe the bug**
Ao tentar conectar no server do logix, ocorre as mensagens no VS-Code ocorre:
- Authentication failed. Could not connect to server localhost:7085.
- Authentication failed. Could not connect to server localhost:7085.
Anexo o arquivo tdsSupport.zip

**To Reproduce**
1. Ir no totvs Server
2. Incluir um server logix
3. digitar o usuário e senha
4. Ocorrerá erro de conexão

**Expected behavior**
Permitir a conexão de um server do logix.
Obs: A nomenclatura dos arquivos do appserver e smartcliente do logix são TotvsSmartClient e TotvsAppServer

**Screenshots**
![image](https://user-images.githubusercontent.com/50241488/73078738-95acad80-3ea1-11ea-9b90-3644b85569fb.png)

![image](https://user-images.githubusercontent.com/50241488/73078758-a0ffd900-3ea1-11ea-9658-4c17470957eb.png)
![image](https://user-images.githubusercontent.com/50241488/73078768-a65d2380-3ea1-11ea-9db2-acaf7baf1595.png)
![image](https://user-images.githubusercontent.com/50241488/73078781-aeb55e80-3ea1-11ea-9781-f7aeff309031.png)
![image](https://user-images.githubusercontent.com/50241488/73078872-e9b79200-3ea1-11ea-9436-9aebb174d6c3.png)

**Desktop (please complete the following information):**
 - Windows 10pro 64 bits

**Appserver (please complete the following information):**
* TOTVS - Build 7.00.131227A - Sep  9 2019 - 02:38:59
* Build: 32 bits
* SVN Revision: 24104
* Build Version: 13.1.3.45

**Additional context**
[tdsSupport.zip](https://github.com/totvs/tds-vscode/files/4109111/tdsSupport.zip)

**Comment by brodao** [comment]
Ola @michellerhen

O TDS_VSCode não esta preparado para usar servidor Logix. Favor utilizar o TDS Eclipse (https://tdn.totvs.com/pages/viewpage.action?pageId=527830513).

Esta em nosso "radar" a implementação de 4GL e uso de servidor Logix.

A disposição
