### ISSUE TITLE
Erro ao tentar conectar ao servidor (localhost)

### ISSUE THREAD

**Issue by LuizGMX** [totvs/tds-vscode#257]
Ao tentar conectar a um servidor ele apresenta o erro a seguir:

![image](https://user-images.githubusercontent.com/44658199/73088261-a87bae00-3eb2-11ea-907b-9d7d7733ad0d.png)

Obs: já desinstalei todos os plugins do vscode, bem como reinstalei o próprio vscode.

**Comment by brodao** [comment]
Ola @LuizGMX 

Veja na visão "Output", seleção "Extensions" ou "Log (WIndow)" se há mais informações.
Verifique também os privilégios de acesso e execução na pasta \@totvs/tds-ls e \@totvs/tds-dap (se for Windows, vejam se os executáveis não estão bloqueados via propriedades dos arquivos no explorer).

A disposição.

**Comment by LuizGMX** [comment]
[cid:image003.png@01D5D772.219871E0]

Não tem nada no output

________________________________
De: Alan Cândido <notifications@github.com>
Enviado: Wednesday, January 29, 2020 3:56:38 PM
Para: totvs/tds-vscode <tds-vscode@noreply.github.com>
Cc: LuizGMX <luizguestape54@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [totvs/tds-vscode] Erro ao tentar conectar ao servidor (localhost) (#257)


Ola @LuizGMX<https://github.com/LuizGMX>

Veja na visão "Output", seleção "Extensions" ou "Log (WIndow)" se há mais informações.
Verifique também os privilégios de acesso e execução na pasta @totvs/tds-ls e @totvs/tds-dap (se for Windows, vejam se os executáveis não estão bloqueados via propriedades dos arquivos no explorer).

A disposição.

**Comment by brodao** [comment]
@LuizGMX 

Na visão output, há a opção de selecionar "AdvPL"? Se sim, copie e envie essas informações.Qual a versão do server? No console log do appServer há alguma informação?
Consegue conectar-se via SC?

No aguardo.

**Comment by lwtnb-wrk** [comment]
@LuizGMX Procure pela pasta ".totvsls" que deve estar na sua pasta de usuario. Renomeie e reinicie o VS Code. Ele deve recriar esta pasta. Cadastre novamente um servidor e teste para ver se conecta.

**Comment by LuizGMX** [comment]
Funcionou perfeitamente, exclui a pasta indicada e abri novamente o vscode e deu certo.
Obrigado!

**Comment by lwtnb-wrk** [comment]
@LuizGMX Excelente! Grato pelo retorno
