### ISSUE TITLE
vscode plugin totvs monitor erro ao tentar conectar

### ISSUE THREAD

**Issue by fabiofurlanc** [totvs/tds-vscode#259]
Após instalar/reinstalar o vscode versão 1.41.1 atualmente disponível, bem como o plug in da totvs monitor versão 0.0.7, ao tentar conectar em servidor Protheus lobo guará devidamente atualizado e apresentado erro : "validations error detected"

Anexo evidências.

Já tentamos obter suporte pelo portal do cliente, mas depois de enviarmos várias evidências do ambiente e problema, foi negado o atendimento por lá, solicitado pela Totvs que reportasse aqui.

**Appserver (please complete the following information):**
 - Build (with date): Build 7.00.170117A - Jan  2 2020 - 14:57:42 
 - OS/Architecture: windows 64
 - Build Version 
* Build: 64 bits
* SVN Revision: 25561
* Build Version: 17.3.0.18

[evidencia 02 para totvs.docx](https://github.com/totvs/tds-vscode/files/4122601/evidencia.02.para.totvs.docx)

**Comment by ricardomansano** [comment]
Boa tarde @fabiofurlanc, este plugin ainda esta em desenvolvimento, liberamos a previa apenas a titulo de informação.
Essa versão deverá estar concluida até final de Fevereiro, mas até esta Sexta() liberaremos no Portal um Monitor baseado no ElectronJS, que ira suprir sua necessiade até que o do VS esteja concluido.
Grato,
