### ISSUE TITLE
Compilação do Projeto

### ISSUE THREAD

**Issue by evandromariano** [totvs/tds-vscode#26]
Bom dia.

Não existe a opção de compilar o Projeto? .PRJ, Somente o Folder?

Quando compilo o folder, ele literalmente compila todos os fontes. Não da skip nos fontes que estão com a mesma versão.
Temos em média mais de 1000 fontes customizados, está demorando em torno de 15 minutos para compilar todos os fontes.

**Comment by ricardomansano** [comment]
@evandromariano , vc tem a opção de compilar a Workspace, ele vai compilar todos os fontes.

@lwtnb-wrk / @brodao  , verifiquem pfv se a compilação por pasta e workspace esta "forçando" a ultima versão, lembro que combinamos de forçar apenas o fonte em edição quando damos Ctrl+F9, mas nas pastas/ws tem que respeitar o Hash de versionamento, senão vai demorar bastante, grato

**Comment by lwtnb-wrk** [comment]
@evandromariano realizei um teste aqui compilando uma pasta (folder) e ele se comportou como deveria. os fontes que ja estavam compilados foram pulados e compilou apenas o fonte que eu alterei.
![image](https://user-images.githubusercontent.com/49563478/58120054-cf266e00-7bda-11e9-8729-ca4d43f0ef52.png)
para forçar a recompilação é preciso segurar a tecla ALT e abrir o menu de contexto para que as opções de compilar mudem para recompilar, mas neste caso estará claro que se trata de recompilação (forçada)
favor informar os passos utilizados para que possamo avaliar o problema relatado

**Comment by Smmartinez** [comment]
Boa tarde! Eu notei o seguinte, eu tenho o vs code e o TDS eclipse, quando eu compilo no TDS eclipse e depois vou compilar no vs code ele recompila todos os fontes novamente tanto em compilar PASTA ou WORKSPACE. E o contrário também é verdadeiro, depois de compilar pelo vs code e for compilar no TDS eclipse ele recompilado todos os fontes.
OBS. compilado no mesmo RPO.

**Comment by evandromariano** [comment]
Acabei de realizar o teste.

Estou fazendo a compilação da Folder.
No meu caso a folder protheus12, onde é a raiz das demais folders, onde constam os fontes.

![image](https://user-images.githubusercontent.com/44401584/58124784-6bee0900-7be5-11e9-8c5b-bb84223b77d1.png)

Fazendo dessa forma, ele compila todos os fontes.

![image](https://user-images.githubusercontent.com/44401584/58124996-ecad0500-7be5-11e9-9a7b-27702f38b69e.png)

**Comment by evandromariano** [comment]
O que eu percebi tbm...

Seguindo a estrutura das minhas folders.
-protheus12
--ativo_fixo

Dentro do ativo fixo eu possuo fontes.
Quando compilo a pasta ativo_fixo, ele compila normalmente. Ai realizo novamente a compilação da pasta ativo_fixo e o SKIP dos fontes acontece normalmente.

Quando subo o nivel e tento compilar a pasta protheus12, onde constam todos o fontes, isso não acontece, ele sai compilando novamente todos os fonte, sem dar SKIP nos fontes já compilados.

**Comment by lwtnb-wrk** [comment]
@evandromariano @Smmartinez grato pelos testes e informações. iremos reavaliar como a validação dos fontes está sendo efetuado e como a recompilação de estruturas com multiplos niveis esta ocorrendo.

**Comment by ricardomansano** [comment]
O cenário que o @Smmartinez comentou é plausivel, aparentemente cada editor (TDS/VS)  manda o fonte com algo que o AppServer esta entendendo que eles são diferentes, mas quem defini isso é o Server não o editor, então não temos como intervir.

@evandromariano , esse por acaso foi o seu cenário tbem? Se foi ja entendemos o problema.
Confirma por favor de vc esta usando a versão 0.1.0 da extensão

Eu fiz os testes com Pasta dentro de Pasta, compilando a partir de cada uma delas e deu Skip tanto usando o AppServer NG quanto o Lobo-Guara, veja nas imagens. Se tiver mais alguma dica do mode que esat fazendo, ou conseguir gravar um video compilando duas vezes seguidas uma pasta que tenha poucos fontes agradecemos, pois parace que estamos correndo atras de fantasmas.
![skip1](https://user-images.githubusercontent.com/33813921/58128253-8a580280-7bed-11e9-80f2-f2fb7fe0e1a0.png)
![skip2](https://user-images.githubusercontent.com/33813921/58128259-8deb8980-7bed-11e9-992f-bbf940dcae84.png)

**Comment by lwtnb-wrk** [comment]
@evandromariano @Smmartinez encontramos uma diferenca no calculo do checksum quando o fonte continha caracteres acentuados causando a recompilacao. nos testes internos isso resolveu, mas se encontrarem divergencias, favor nos enviar o fonte que causa a divergencia para testarmos.
somente reforcando que esta correcao so estara disponivel a partir da proxima atualizacao. grato pelos testes e comentarios
