### ISSUE TITLE
Variable Local Never Used

### ISSUE THREAD

**Issue by charllesrox** [totvs/tds-vscode#260]
Issue Type: <b>Bug</b>

Quando uso o Embeded SQL, exemplo %exp:cVariavel%, ao compilar diz que a variável nunca foi usada e é tratado como um problema, tudo bem que não impede o código de seguir mas, muitas vezes acabam ficando muita coisa para ficar conferindo. Deveria passar sem nenhum problema pois a variável foi declarada e utilizada.

Extension version: 0.3.23
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by brodao** [comment]
Ola @charllesrox 

Quem reporta essa ocorrência é o compilador existente no appServer, nós apenas mostramos a ocorrência. Dê uma olhada em https://code.visualstudio.com/docs/getstarted/tips-and-tricks, que há dicas de como adicionar filtros na visão "Problemas".

A disposição.
