### ISSUE TITLE
Debug WebService - MultiThread

### ISSUE THREAD

**Issue by eduardofm1** [totvs/tds-vscode#261]
Boa noite pessoal!

Qual o procedimento para conseguir debugar WebService via Totvs Developer Studio for VSCode ?

Coloquei a opção enableMultiThread como True  no launch.json  porém ao debugar não para no ponto de parada.

Obrigado.

**Comment by brodao** [comment]
@eduardofm1 , experimente:
. ligar o ponto de parada no local desejado
. execute em modo de debug o SC chamando um programa qualquer ou mesmo uma função inexistente (não encerre, assim você mantém uma conexão)
. faz a chamada do do WS via outra aplicação

A disposição

**Comment by ricardomansano** [comment]
Grato pelo report, estaremos a disposição caso não consiga efetuar a configuração.
