### ISSUE TITLE
Link de arquivos

### ISSUE THREAD

**Issue by Nhaca** [totvs/tds-vscode#262]
Olá,
É possível criar link de fontes igualmente era no TDS(Eclipse).
Por exemplo, tenho um arquivo origem e gostaria apenas de referenciá-lo em outro diretório da mesma workspace, sendo possível alterá-lo, mas mantendo apenas uma versão.
Obrigado.

**Comment by ricardomansano** [comment]
Boa tarde,
o VSCode funciona de maneira diferente do Eclipse, ele trata pastas ao invés de links.
Grato pelo report

**Comment by brodao** [comment]
Ola @Nhaca ,

Complementando o @ricardomansano, o VSCode usa os "links" do próprio sistemas de arquivos.
Saiba mais :
* https://stackoverflow.com/questions/46071131/display-symbolic-links-in-visual-studio-code
* https://pt.phhsnews.com/complete-guide-to-creating-symbolic-links-on-windows3371

A disposição
