### ISSUE TITLE
Erro na instalação do plugin

### ISSUE THREAD

**Issue by Nhaca** [totvs/tds-vscode#264]
![Erro Plugin](https://user-images.githubusercontent.com/17277863/73490457-5a234f00-438b-11ea-8313-f7a85727b2ab.png)

**Comment by lwtnb-wrk** [comment]
@Nhaca Favor detalhar seu ambiente e procedimentos para reproduzir o problema.

Logo apos a instalacao, a extensao ja é iniciada e esse erro aparentemente parece ser na execução do advpls.exe...

Ao reiniciar o Windows e/ou VS Code o mesmo erro continua a ocorrer?

**Comment by Nhaca** [comment]
@lwtnb-wrk logo ao abrir o VS Code o erro já acontece.
Sim, reiniciei Windows e VS Code.

SO:
Windows Server 2016 Standard 64x

Instalados
Microsoft Visual C++ 2017 Redistributable (x64) - v. 14.16.27029
Microsoft Visual Studio Tools for Applications 2017
![Extensões](https://user-images.githubusercontent.com/17277863/73539080-56cfa800-440b-11ea-9f97-88431c676821.png)
![Vs Code](https://user-images.githubusercontent.com/17277863/73539081-56cfa800-440b-11ea-90d3-c706a689ba3f.png)

**Comment by lwtnb-wrk** [comment]
@Nhaca Sua configuração do VS Code esta praticamente idêntica a minha... Apenas meu SO é um Windows 10 Pro x64... 

Já tentou reinstalar a extensão?

Tente também verificar na sua pasta de usuário se existe a pasta ".totvsls" e caso afirmativo, renomeie e reinicie o VS Code...

**Comment by Nhaca** [comment]
Fiz o processo de reinstalação mais de 3 vezes. 
Também renomeei  o diretório informado e... nada!
=/

**Comment by ricardomansano** [comment]
Bom dia @Nhaca ,

SOs voltados para camada servidora normalmente não dispõe de DLLs/LIBs necessárias à execução de aplicações Desktop.

Por favor monte seu ambiente de desenvolvimento em uma estação Windows 10, Linux ou MacOS se preferir.

Não temos como reproduzir seu cenário e tbem não o recomendamos.

Grato pelo report

**Comment by Nhaca** [comment]
@ricardomansano @lwtnb-wrk instalei o VS Code (User Installer) apenas no meu usuário do servidor e no atalho com "-N" no final e desta forma consegui utilizar no servidor. (compartilhando o resultado).

**Comment by lwtnb-wrk** [comment]
@Nhaca Grato por compartilhar essa informação!
De acordo com a documentação do VS Code a opção "-N" força a abrir uma nova janela.
Não faço ideia do porque isso fez com que sua instalação funcionasse, mas já que funcionou, boa codificação!!

**Comment by ricardomansano** [comment]
@Nhaca ,

Mais uma pro livro de "esquisitices da tecnologia", agradeço o report, vamos guardar na manga caso algum outro colega passe pelo mesmo.
