### ISSUE TITLE
User not authenticated

### ISSUE THREAD

**Issue by R1CH2RDS0N** [totvs/tds-vscode#265]
Bom dia a todos,

Estou testando o VSCODE para migração dos fontes da empresa para o mesmo.
Segui os paços postados no vídeo: https://www.youtube.com/watch?v=MwIu01Ztfvg&t=34s, porém não consigo debugar a aplicação.

Conecto o servidor (ficar verde), Consigo compilar, porém na hora de rodar o "executor" ele mostra a mensagem de erro: User not authenticated. Please connect/reconnect to a server.

**Comment by lwtnb-wrk** [comment]
@R1CH2RDS0N Pode ser que houve algum problema nas configurações de seus servidores e/ou tokens de conexão.
Experimente renomear a pasta ".totvsls" que deve existir na sua pasta de usuário e reinicie o VS Code
Recrie as configurações de servidores e tente novamente.
Veja se isso resolve seu problema.

**Comment by R1CH2RDS0N** [comment]
Muito obrigado pela rápida resposta.
Estou muito empolgado com a "nova IDE", e gostaria de ajuda para fazer funcionar

Fiz o procedimento que me foi citado, recriei os servers,compilei e de novo a mesma mensagem.

![2020-02-04 09_50_21-launch json - VSCode - Visual Studio Code](https://user-images.githubusercontent.com/60651749/73746647-72e98700-4734-11ea-9b1d-d1577cb5e1a9.png)

**Comment by lwtnb-wrk** [comment]
@R1CH2RDS0N Essa mensagem ocorre apenas quando o token de conexão gerado durante a autenticacao nao é reconhecido pelo Debug...
Infelizmento nao temos outros relatos desse problema que voce esta tendo entao deve ser algo mais especifico de seu ambiente. Qual o SO que voce esta utilizando?

**Comment by R1CH2RDS0N** [comment]
O que acho estranho é o fato de que ele conecta e compila, mas n debuga.
Testado em Windows 10 + Protheus 25 e 17.
Mesmo erro.

**Comment by lwtnb-wrk** [comment]
@R1CH2RDS0N voce apenas instalou a ultima versao da extensao e nao atualizou nada via npm, correto?
estou com windows 10 e operando sem problemas por aqui

**Comment by R1CH2RDS0N** [comment]
Cara... Já desenvolvo em ADVPL a um tempo. Tenho aqui, nessa maquina, Alguns ambientes de testes com versões P12 17, 23 e 25.
O que fiz foi, baixar o Visual Studio e instalar a extensão nele

![2020-02-04 11_16_31-servers json - VSCode - Visual Studio Code](https://user-images.githubusercontent.com/60651749/73752914-87338100-4740-11ea-8b53-a6e47e4b21a1.png)
![2020-02-04 11_17_08-Extension_ Totvs Developer Studio for VSCode (AdvPL, TLPP e 4GL) - VSCode - Visu](https://user-images.githubusercontent.com/60651749/73752915-87338100-4740-11ea-99fc-070493ab4f58.png)

**Comment by lwtnb-wrk** [comment]
@R1CH2RDS0N Me parece tudo correto. Nao tenho ideia do que pode estar ocorrendo de errado...
Voce consegue instalar e testar em outra maquina?

**Comment by lwtnb-wrk** [comment]
sem retorno do usuario

**Comment by dyhalmeida** [comment]
Erro a Debugar no vscode.
"User Not Authenticated", estou passando pelo mesmo problema no windows 10,
Já refiz as configurações e não consigo debugar, apenas compilar.

**Comment by lwtnb-wrk** [comment]
@dyhalmeida abra uma nova issue e documente com detalhes o problema e como esta seu ambiente.
