### ISSUE TITLE
Identação com problema utilizando EndFilBrw()

### ISSUE THREAD

**Issue by Redschenko** [totvs/tds-vscode#266]
Bom dia.
Na versão 0.3.23, quando utilizado a função EndFilBrw() não está formatando o texto corretamente (Shift+Alt+F), conforme imagem a seguir:

![image](https://user-images.githubusercontent.com/21147378/73840323-b3113e00-47f6-11ea-9de8-ab1813f7c204.png)

**Expected behavior**
A formatação correta seria, por exemplo, conforme a seguinte imagem:

![image](https://user-images.githubusercontent.com/21147378/73840854-f0c29680-47f7-11ea-85ba-1ee942bffeb7.png)

**Desktop**
 - OS/Architecture: Windows 7 SP1 64 bits

**Appserver**
 - Build (with date): 7.00.170117A-20190628 - 64 bits
 - OS/Architecture: Windows Server 2012
 - Build Version: 17.3.0.16

**Additional context**
- Plugin: Totvs Developer Studio for VSCode 0.3.23

**Comment by ricardomansano** [comment]
Boa tarde, o AdvPL (codeBase) tem um tipo de abertura e fechamento de estrutura que não é mais usado, a maioria das linguagens usa chaves {}, seja JS, C#, C++, ou outras

Estudei o arquivo de formatação ( https://github.com/totvs/tds-vscode/blob/master/src/formatter/formmatingRules.ts ) e confirmei que o END das demais estruturas, como END DO, END WSRESTFUL, END STRUCTURE e muitas outras, estão batendo de com o ENDIF.

No seu caso isso se refletiu na chamada da função EndFilBrw(), que começa com "END".
Infelizmente esse é um erro do parser do VSCode que teremos que conviver, só salientando que não culpo o VSCode, mas sim a linguagem AdvPL, que herdou do DBase uma estrutura que nenhuma IDE se preocupa em suportar, como eu disse, porque não é mais usada.

Grato pelo reporte e lamento não termos ação pra essa issue.
