### ISSUE TITLE
Problema para incluir Servidores

### ISSUE THREAD

**Issue by klausperes** [totvs/tds-vscode#267]
Prezados,

Estou com problemas para incluir os servidores no VSCode.

Ao tentar incluir, é apresentada a tela de cadastro. Preencho todas as informações solicitadas, como nome do servidor, ip, e porta, bem como as includes. Assim que clico em Save/Close a tela não fecha e não salva. Se clico somente no botão Save também não faz nada.

Meu sistema é o macOS Catalina.

PS: Eu já havia cadastrado 5 servidores. Eu fechei a aplicação, e ao reabrir começou a dar esse problema.

Grato pela atenção.

**Comment by lwtnb-wrk** [comment]
@klausperes Veja se foi algum problema pontual durante o cadastro dos servidores.
Feche o VS Code e efetue as seguintes operações.
Na sua pasta de usuario, localize a pasta ".totvsls" e renomeie o arquivo "servers.json".
Abra o VS Code e cadastre novamente um servidor e reinicie o VS Code.
Veja se consegue cadastrar outro servidor.

**Comment by klausperes** [comment]
Obrigado, resolveu o problema...
