### ISSUE TITLE
Separar servidores por workspace

### ISSUE THREAD

**Issue by Emesilver** [totvs/tds-vscode#268]
Gravar as configurações dos servidores por Workspace. Assim quando criamos um workspace por cliente, cada cliente fica apenas com seus servidores aparecendo.

**Comment by ricardomansano** [comment]
Boa tarde @Emesilver , lhe mandei uma mensagem pelo hangout, conforme coloquei lá vamos avaliar seu PR assim que o submeter, e confirmar se é interessante e seguro para ferramenta manter configurações distintas de Server por workSpaces.

Voce poderia resolver isso facilmente criando um AppServer para cada cliente, como os DEVs internos tem feito, mas vamos estudar sua proposta

Aguardo seu PR

**Comment by ricardomansano** [comment]
Bom dia, favor nos contactar se conseguir rever a melhoria

Grato
