### ISSUE TITLE
Erro de compilação

### ISSUE THREAD

**Issue by PatrickZerbinatti** [totvs/tds-vscode#270]
**Describe the bug**
Quando nos compilamos alguns fontes se uma variável de um FOR for declarada em cadeia, ele deixa de considera-la e da Warning falando que em versões futuras poderá ser considerado erro.
![erro_compilacao](https://user-images.githubusercontent.com/33162950/74039355-7123fb80-49a0-11ea-8527-1ff99034a7c1.png)

**Comment by lwtnb-wrk** [comment]
@PatrickZerbinatti Realmente verifiquei que existe um erro na padronização da mensagem emitida pelo appserver nesta situação.
Faremos uma correção para tratar deste caso "especial", mas de qualquer forma existe outro problema no appserver em relação a essa declaração em cadeia, pois tanto a variável "NI" quanto a "nRecSB1" não estão sendo consideradas como "Local" pelo appserver e por isso é emitido um "Warning".
Se achar necessário abra um chamado para o time do appserver verificar essa questão e futuramente corrigir no appserver o tratamento de variáveis locais em cadeia.
Em breve disponibilizaremos uma correção para tratar este warning como warning.
Grato por avisar.

**Comment by PatrickZerbinatti** [comment]
Interessante, vou abrir um chamado lá com eles.

**Comment by lwtnb-wrk** [comment]
corrigida na versao 1.0.1
