### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by sipmann** [totvs/tds-vscode#272]
Hoje cedo, começou a estourar o aviso abaixo. Não conecta mais nos APPServer nem o Monitor (outra extensão).

---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Debug Error!
Program: ...nitor-0.0.7\node_modules\@totvs\tds-ls\bin\windows\advpls.ex
abort() has been called
(Press Retry to debug the application)
---------------------------
Anular   Repetir   Ignorar   
---------------------------

**To Reproduce**
No idea.

**Screenshots**
![image](https://user-images.githubusercontent.com/545754/74155680-5ee9cd80-4beb-11ea-8825-d2408510a23f.png)

**Desktop:**
 - OS/Architecture: Windows 10 Pro 64 bits

**Appserver:**
Build AppServer: 7.00.170117A-20191024 - 64 bits
 - OS/Architecture: Win 2019 Server

**Additional context**
Removi e adicionei a extensão novamente mas o erro permaneceu.

**Comment by lwtnb-wrk** [comment]
@sipmann Por enquanto, favor não utlizar a extensão TDS Monitor. Desinstale e veja se o erro persiste.

**Comment by sipmann** [comment]
infelizmente mesmo comportamento. Percebi que a extensão se atualizou, até então eu utilizava um menu lateral, agora passou para abaixo do workspace dos arquivos.
![image](https://user-images.githubusercontent.com/545754/74235124-c0ba3e00-4ca4-11ea-8911-de9e162d7f25.png)

**Comment by lwtnb-wrk** [comment]
@sipmann Experimente renomear a pasta ".totvsls" que existe na sua pasta de usuario.
Sera necessario recadastrar os servidores.
Veja se assim a extensao volta a funcionar.

**Comment by sipmann** [comment]
Perfeito. Resolvido. Muito Obrigado
