### ISSUE TITLE
O TDS-VScode não está abrindo nem o smartclient e nem o smartclient html para efetuar o debug.

### ISSUE THREAD

**Issue by michellerhen** [totvs/tds-vscode#274]
**Describe the bug**
Não executa em modo debug o smartclient e nem o smartclient HTML.
**To Reproduce**
1. Ao utilizar a versão 0.3.23 ou a 0.03.22, conecta o server mas não executa o smartclient.

**Desktop (please complete the following information):**
 - Windows 64 Bits

**Appserver (please complete the following information):**
***  TOTVS S/A  ***
***  www.totvs.com.br  ***
* TOTVS - Build 7.00.191205P - Feb  5 2020 - 15:20:05
* Build: 64 bits
* SVN Revision: 25991
* Build Version: 19.3.0.1_RC13

**Additional context**
![image](https://user-images.githubusercontent.com/50241488/74170933-72596080-4c0c-11ea-802b-e04a47d85441.png)
![image](https://user-images.githubusercontent.com/50241488/74171089-bb111980-4c0c-11ea-960a-ded30af9ce75.png)

**Comment by lwtnb-wrk** [comment]
@michellerhen Experimente renomear a pasta ".totvsls" que existe em sua pasta de usuario.
Recadastre os servidores e tente novamente.
Veja se isso resolve seu problema.

**Comment by michellerhen** [comment]
Oi!
resolveu sim.
obrigada!
