### ISSUE TITLE
Recompilar projeto com o botão direito sem usar atalho.

### ISSUE THREAD

**Issue by fabriciostefanini** [totvs/tds-vscode#275]
Seria muito interessante uma opção de recompilação, usava bastante isso para garantir que todos os fontes do meu projeto foram Recompilados.

Através do botão direito no na pasta do fonte ou todo o workspace.

Vi que existe a opção nos atalhos mas eu não costumo decorar atalho, já que a ferramente oficial será essa e no botão direito eu tenho opção de compilar, porque não adicionar lá também a opção de recompilar, e não ter que ficar decorando atalhos.

Já que é para ter um padrão vamos mantê-lo! Ou acham que estou errado?

Obrigado

**Comment by lwtnb-wrk** [comment]
@fabriciostefanini Pressione a tecla SHIFT antes de acionar o menu de contexto. As opções de compilar serão modificadas para Recompilar. Veja se é isso que você precisa.

**Comment by fabriciostefanini** [comment]
Sim isso mesmo, eu utilizo SHIFT somente para isso ou tenho outras funcionalidade usando SHIFT?

Seria possível fazer um recompilar por PASTA? Hoje separo os dontes em subpastas com o nome dos módulo e muitas vezes acabo recompilando somente os fontes de um módulo somente ao invés do workspace inteiro.

Mas só de existir o Recompilar no SHIFT já me ajudou bastante.

**Comment by lwtnb-wrk** [comment]
@fabriciostefanini Se clicar no menu de contexto de uma pasta com o SHIFT acionado voce pode recompilar esta pasta.
