### ISSUE TITLE
Compile/Recompile open Editors 

### ISSUE THREAD

**Issue by WBaldin** [totvs/tds-vscode#276]
A opção:
**Ctrl + F10** _(Compile Open Editors)_ 
ou 
**Ctrl + Shift + F10** _(Recompile Open Editors)_
funcionavam perfeitamente e após uma atualização do Windows vem se comportando de forma estranha e não fazendo o que se compromete a fazer. 
Deveria compilar/recompilar todos os fontes das abas abertas e o que está fazendo é compila/recompila o fonte da aba que está sendo visualizada ou aberta e passa para a próxima onde deveria compilar/recompilar e simplesmente encerra o processo de compilação/recompilação. Como resultado final, apresenta o resumo somente do fonte compilado através da "Output" ou na opção de abrir tabela de fontes compilados/recompilados, mas somente com  o fonte que foi compilado/recompilado.
Vale lembrar que funcionava perfeitamente e nenhuma configuração de atalhos foi modificada.

**Comment by lwtnb-wrk** [comment]
@WBaldin Voce quis dizer atualizacao do VS Code ou foi do Windows mesmo? Alias quais as versoes do Windows, do VS Code e da extensao voce esta utilizando?

**Comment by WBaldin** [comment]
Olá @lwtnb-wrk, eu percebi esta alteração de comportamento após uma atualização do Windows que foi grande onde parece fazer uma reinstalação do Windows. 

As versões são as seguintes:

**Windows 10 Pro 64 Bits**
_Versão:_ **1903**
_Instalado em_: **10/02/2020**
_Compilação do SO:_ **18362.592**

**VS Code**
_Versão:_ **1.42.0**
_Data:_ **06/02/2020**

**Totvs Developer Studio For VsCode (AdvPL, TLPP e 4GL)**
_Versão:_ **0.3.23**

**Comment by lwtnb-wrk** [comment]
@WBaldin Grato pelas informações. Iremos avaliar o problema.

**Comment by Felipe-Raposo** [comment]
Eu estou com esse mesmo problema, usando Linux. Ao usar o CTRL+F10 ou CLTR+P e comando "TOTVS: Compile Open Editors", o VSCode compila o editor aberto, passa para o próximo editor e para.

**Comment by thebritto** [comment]
Mesmo problema aqui tbm.
Versão do VS Code: 1.43.0 de 09/03/2020
Versão do Plugin Totvs: 0.3.23
