### ISSUE TITLE
Compilação da WorkSpace para sem informar o problema e apresenta rollback no RPO

### ISSUE THREAD

**Issue by charlesreitz** [totvs/tds-vscode#277]
Ao clicar com o botão direito e mandar compilar toda workfspace, ele compila uma parte , após para e não apresenta msg no VSCODE de erro, mas no Appserver aparece a msg que deu rollback. 

**To Reproduce**
1) Botão direito em cima do projeto opção compilar toda workspace

**Expected behavior**
2) Compilar todo o projeto

**Screenshots**
![image](https://user-images.githubusercontent.com/1248135/74440065-13822a00-4e4c-11ea-9140-53152538307a.png)

**Desktop (please complete the following information):**
Windows server 2012 R2

**Appserver (please complete the following information):**
***  TOTVS S/A  ***
***  www.totvs.com.br  ***
* TOTVS - Build 7.00.170117A - Oct 24 2019 - 12:14:41 
* Build: 64 bits
* SVN Revision: 24668
* Build Version: 17.3.0.16

**Comment by lwtnb-wrk** [comment]
@charlesreitz O erro ocorre sempre no mesmo ponto ou pode ocorrer e diversos pontos do workspace?
Pelo screenshot o TDS VS Code estava iniciando a compilação do UNIA053.PRW quando ocorreu o rollback no appserver.
Se tentar rodar novamente ele para no mesmo fonte?

**Comment by charlesreitz** [comment]
Sim sempre no mesmo fonte, se eu compilar apenas onde ele parou, ele compila. 

Posso lhe enviar o projeto caso necessário.

**Comment by lwtnb-wrk** [comment]
@charlesreitz Podemos tentar reproduzir o problema aqui entao... Me mande esse projeto que ocorre o erro entao.

**Comment by lwtnb-wrk** [comment]
@charlesreitz Conforme nos falamos ja identificamos o problema. 
Se tentar compilar um fonte que esta todo comentado, o preprocessamento o transforma em um fonte vazio. 
Existe um tratamento que impede a compilação de fontes vazios, mas o erro nao chega ao VS Code.
Estamos corrigindo esse tratamento para que seja exibida uma mensagem de erro nesta situação.
Aguarde as próximas atualizações com essa correção.
