### ISSUE TITLE
Erro na configuração do DEBUG

### ISSUE THREAD

**Issue by yurysilva** [totvs/tds-vscode#278]
Estou tentando fazer a utilização da versão do pluggin para area de homologação do sistemas, criei um servidor com os mesmos parâmetros do sistemas, pois quando chamava pela area de welcome ele não conectava, quando criei ele conecta, porém quando fiz a configuração do debug não consigo compilar a fonte.
![image](https://user-images.githubusercontent.com/52840612/74455355-f35e6500-4e63-11ea-88a5-644ef473f5b4.png)
Da a mensagem do print.

**Comment by lwtnb-wrk** [comment]
@yurysilva Pelo erro no screenshot é possivel ver que ele não conseguiu realizar o "Start Build" por não ter acesso exclusivo ao RPO.
Voce esta em um ambiente de desenvolvimento exclusivo? Ou seja, apenas voce esta conectado ao appserver?
Para compilar é necessario acesso exclusivo. Se houver outra pessoa conectada ao appserver não é possivel compilar neste appserver.
Verifique tambem se a chave "buildKillUser" está habilitada.

**Comment by yurysilva** [comment]
Então, estava em acesso exclusivo, mas tem varios ambientes, ele pergunta se é on-line e diz que não consegue o acesso ao rpo
Eu acesso ele via citrix

**Comment by lwtnb-wrk** [comment]
@yurysilva Quem retorna essa informação de acesso exclusivo é o próprio appserver.
Se ele diz não ter acesso exclusivo significa que existe outro usuário (smartclient) conectado ao ambiente.
Se ligar a chave "buildKillUser" o próprio appserver derruba todas as conexões antes de compilar evitando essa mensagem de erro.
