### ISSUE TITLE
Debug não funciona TDS-VSCODE

### ISSUE THREAD

**Issue by mateus-erp** [totvs/tds-vscode#279]
Bom dia.

Não estou conseguindo debugar após a atualização do VSCODE.
Segue Launch,

{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Totvs Language Debug",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "C:\\TOTVS12\\Protheus\\Protheus\\bin\\smartclient\\smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true,
			"programArguments": "undefined",
			"enableMultiThread": false,
			"enableProfile": false,
			"isAccessibilityMode": false,
			"doNotShowSplash": false,
			"language": "",
			"ignoreFiles": true
		}
	],
	"lastPrograms": [
		{
			"args": [],
			"label": "SIGAADV",
			"description": ""
		}
	],
	"lastProgramExecuted": "SIGAADV"
}

**Comment by mateus-erp** [comment]
Binário e Versão do plugin,

Build AppServer: 7.00.170117A-20190628 - 64 bits
Totvs Developer Studio for VSCode - Versão 0.3.23

**Comment by lwtnb-wrk** [comment]
@mateus-erp Experimente renomear a pasta ".totvsls" que existe na sua pasta de usuario.
Recadastre os servidores e tente novamente.

**Comment by ricardomansano** [comment]
Bom dia,

Dado tempo sem resposta creio que o problema tenha sido resolvido.

Qualquer situação por favor nos contate

**Comment by mateus-erp** [comment]
Bom dia.
Desculpe pela demora, mas o problema foi resolvido.
Muito obrigado!

**Comment by rpinheirols** [comment]
Bom dia!! estou com problema no VSCODE, já deletei os arquivos como .vscode, .totvsls .Já desistalei umas 3 vezes e tambem configurei tudo novo. Não está funcionando para Debugar. Alguem pode me ajudar ? Até Janeiro ele funcionava, depois de atualização parou. No aguardo

**Comment by ricardomansano** [comment]
@rpinheirols , 
Essa issue ta fechada, siga os passos abaixo, mas se nao tiver sucesso pfv abra outra issue, ou as interações poderão nao ser vista pelo time.

A ultima atualização do vscode bagunçou o ambiente de alguns colegas, e a dica abaixo resolveu o problema de um deles:

Vamos do começo então:
-A versão 1.42.1 do Vs é a ultima, então nao vamos mexer nisso (esse foi o caso dele, veja o seu VS se esta)
-Desinstale o plugin pra limparmos qualquer cache do VSCode
-Delete (não renomeie, ja que é um nova instalação) a pasta .totvsls, como o Leo comentou ela fica na pasta de usuarios, na minha maquina é a /home/mansano/.totvsls/
-Aproveite e delete a pasta .vscode de seu projeto, vai ter que reconfigurar o ambiente mas vamos garantir que não havera "sujeira"
-Vamos reinicar sua máquina pra garantir que mais nenhum cache possa estar prendendo seus arquivos
-Depois de reinicar reinstale o plugin e configure novamente o ambiente em sua pasta de projeto (ja que apagou a pasta .vscode)

Se ainda assim não tiver sucesso, abra uma outra issue com o maximo de informações pra que possamos apoiá-lo
