### ISSUE TITLE
Ambientes AppServer x Servidor VSCode

### ISSUE THREAD

**Issue by CidGianni** [totvs/tds-vscode#280]
Olá, procurei e não localizei o tópico, e também não tenho certeza de ser um Bug ou uma sugestão de melhoria.

É normal nos appserver.ini ter mais de um ambiente. No TDS, ao configurar uma conexão de servidor, puxa todos os ambientes, apesar de precisar informar usuário e senha para cada ambiente.

No VSCode cria o servidor mas na primeira conexão grava apenas um ambiente. Estou precisando criar um servidor para cada ambiente. É isso mesmo?

Aparecido Gianni

**Comment by lwtnb-wrk** [comment]
@CidGianni Realmente o TDS Eclipse antigamente carregava toda a lista de servidores que existiam, porém esse comportamento foi removido nas versões mais atuais por questões de segurança.
Portanto a lista de ambientes no TDS VS Code deve ser cadastrada individualmente pelo usuário.
Para cadastrar múltiplos ambientes, inicie uma nova conexão e na tela de seleção de ambientes, se o ambiente ainda não estiver na lista clique no botão "+" e informe o novo ambiente. Ele será salvo e aparecerá na lista nas próximas conexões.
Iremos atualizar a documentação para deixar essa informação disponivel.
