### ISSUE TITLE
Erro em novas instalações

### ISSUE THREAD

**Issue by dennerM** [totvs/tds-vscode#281]
Ao instalar o pluguin na versão 1.42.1 do visual studio code, o sistema apresenta o seguinte erro: 

![image](https://user-images.githubusercontent.com/26337710/74659461-2447de00-5173-11ea-8679-402e4853f3b1.png)

**Comment by lwtnb-wrk** [comment]
@dennerM Somente com essa informação não temos como adivinhar o que pode estar ocorrendo.

Primeiro experimente renomear a pasta ".totvsls" que deve existir na sua pasta de usuario. Recadastre os servidores e veja se resolve.

Se nao funcionar informe qual o SO que voce usa? É uma nova instalação ou foi alguma atualização? Em que momento ocorre o erro? Ja ao abrir ou apos alguma operacao?

**Comment by dennerM** [comment]
@lwtnb-wrk Sou novo nesta história de reportar problemas, mas entendo que adivinhar é complicado, sugiro perguntar.

Primeiro experimento renomear uma pasta ".totvsls" que deve existir na sua pasta de usuário. Registrar os servidores e veja se resolver.
- Apaguei a pasta mencionada, reinstalei o visual studio code e não resolveu. 

Se não funcionar, informe qual é o SO que você usa? 
- Windows 10 Pro 

É uma nova instalação ou foi alguma atualização? 
- Nova instalação

Em que momento ocorre o erro? Já para abrir ou apos alguma operação?
Ao instalar a extensão o erro começa a ser apresentado, e some apos desinstalá-la e reiniciar o vscode.

**Comment by ricardomansano** [comment]
Bom dia @dennerM,

Vamos do começo então:
-A versão 1.42.1 do Vs é a ultima, então nao vamos mexer nisso
-Desinstale o plugin pra limparmos qualquer cache do VSCode
-Delete (não renomeie, ja que é um nova instalação) a pasta .totvsls, como o Leo comentou ela fica na pasta de usuarios, na minha maquina é a /home/mansano/.totvsls/
-Vamos reinicar sua máquina pra garantir que mais nenhum cache possa estar prendendo seus arquivos
-Depois de reinicar reinstale o plugin e siga os passos do meuvideo (se é que ja não fez): https://www.youtube.com/watch?v=MwIu01Ztfvg

Se ainda assim não tiver sucesso, me chame diretamente aqui que vamos botar teu VS pra funfar

Fico na escuta
Mansano

**Comment by dennerM** [comment]
Bom dia @ricardomansano,

Funcionou!! Valeu.
Já havia apagado a pasta conforme orientação do @lwtnb-wrk mas não testava reiniciando a máquina. Acredito que seja isto. 
Obrigado.

**Comment by ricardomansano** [comment]
Boa tarde @dennerM,

Bacana, 
Continue contando conosco
