### ISSUE TITLE
Aplicar patch local no Linux com letra maiúscula

### ISSUE THREAD

**Issue by Felipe-Raposo** [totvs/tds-vscode#282]
Ao aplicar uma patch, usando VSCode no Linux, se houver alguma letra maiúscula no nome ou no caminho da patch, dá o erro abaixo:

[Error] File could not be copied to the server.

**Comment by lwtnb-wrk** [comment]
@Felipe-Raposo Existe uma limitação na implementação do Appserver a qual não temos controle.
Na aplicação de patch, todo o caminho deve estar em letras minúsculas, caso contrário ocorrerá o erro: "File could not be copied to the server".
Renomeie os diretórios e subdiretórios para que não contenham letras maíusculas nem acentuações e espaços.
