### ISSUE TITLE
Não Compilar Pasta Especifiva

### ISSUE THREAD

**Issue by ValbergMoura** [totvs/tds-vscode#283]
Olá a todos!

No TDS temos a opção de marcar uma pasta para não ser compilado conforme imagem anexa, é possível efetuar esta configuração no VSCODE?

![image](https://user-images.githubusercontent.com/54451890/75093575-49649400-5559-11ea-915e-d01d0141dc96.png)

**Comment by ricardomansano** [comment]
Bom dia,

Essa feature ja passou por nossa analise e a principio não foi aprovada.

Uma simples reorganização de seu projeto resolvera o problema, colocando por exemplor, todos os source codes em uma pasta SRC e documentos, exemplos e outros artefatos em paralelo a esta pasta.

É o modelo utiizado em projetos Git e se mostrou muito eficiente

Grato pelo contato
