### ISSUE TITLE
TDS Estrutura Fonte com Funções X VS Code

### ISSUE THREAD

**Issue by CidGianni** [totvs/tds-vscode#284]
Olá, bom dia. Sinceramente ainda não consegui ver o ganho na mudança para o VS Code, em relação aos recursos que o TDS-Eclipse oferece, mas já que tem que mudar, vou incomodar os expert Totvs para esclarecer as dúvidas. 

No TDS Eclipse ao abrir um programa PRW tem uma visão que aparece todas as funções do programa. O VS Code tem este recurso?

Grato.

Aparecido Gianni

**Comment by ricardomansano** [comment]
Bom dia,

Esta função será implementada no segundo semestre/2020, baseada em um ferramental de parser que trará varias implementações ao produto.

Manteremos os canais atualizados quando da liberação.
