### ISSUE TITLE
file could not be copied to the server

### ISSUE THREAD

**Issue by rodsmello** [totvs/tds-vscode#287]
Bom dia! 
Encontrei o erro "file could not be copied to the server" ao tentar aplicação patch conectado ao novo appserver 20-02-21-P12_APPSERVER_BUILD-19.3.0.2_WINDOWS_X64. A build anterior (17.3.0.18_WINDOWS_X64) os pacote são aplicados sem problemas.
Existe alguma nova configuração? 

console - vscode (v: 1.42.1 - system setup)

```
[Info  - 12:08:52] Starting reconnection to the server: lg-log
[Log   - 00:00:00] Secure authenticating...
[Log   - 00:00:00] User authenticated successfully.
[Info  - 12:08:55] Reconnection to the server: lg-log finished.
[Info  - 12:09:11] Starting apply patch.
[Log   - 00:00:00] Starting build for environment UPDDISTR.
[Log   - 00:00:00] Applying patch file: c:/TOTVS/Microsiga/Protheus_Data/update/20-02-21-LIB_LABEL_14022020_P12_LOBO-TTTP120.PTM
[Error - 12:09:17] File could not be copied to the server.
[Log   - 00:00:00] Aborting end build (rollback changes).
```

appserver - console.log
```
2020-02-25T12:09:12.713000-03:00 17288|------0--c:\totvs\microsiga\protheus_data\update\20-02-21-lib_label_14022020_p12_lobo-tttp120.ptm

2020-02-25T12:09:12.717000-03:00 17288|
[WARN ][SERVER] [THROW][Thread  17288] tConnnErrorException (8:Communication error: Sync error) on D:\bamboo-agent-5.7.2\xml-data\build-dir\TP11-TECX17V3R1-TECXWIN64\lib_comm\msgmanager.cpp:719

2020-02-25T12:09:12.718000-03:00 17288|
[INFO ][SERVER] [[Thread  17288][25/02/2020 12:09:12] Debugger finished ( (user, server)

2020-02-25T12:09:17.650000-03:00 12356|[MPPORT] 200225_120917 3044 BPC2019 W x 05 ctx:009 expired timeout for closing of client connection seconds=5 o1r0R1s0S0
```

**Comment by lwtnb-wrk** [comment]
@rodsmello Fiz um teste aqui e não reproduzi o problema. Peguei o mesmo Appserver e apliquei o mesmo patch tranquilamente.
O seu Appserver esta na mesma maquina que o TDS VS Code estava?
Certifique-se de que as pastas de destino no Appserver tem permissão de escrita.

**Comment by rodsmello** [comment]
@lwtnb-wrk foi realizado de várias formas, na mesma maquina (server) e em outras conectada pela rede (windows e linux). O curioso é que com a build anterior o problema não ocorre.

Talvez ajude com o processo: 
Ao adicionar o server é apresentado o erro `4083: An error ocurred while creating a new connection.`, porém a conexão é realizada com o serviço.

**Comment by rodsmello** [comment]
@lwtnb-wrk foram criados novos servidores e sobre a pasta ".totvsls", se server de ajuda o teste foi realizado em uma estação de trabalho com a instalação do vscode do zero.

**Comment by melkzsiqueira** [comment]
Habilita a opcao de SLL ou altera o atributo "secure": 1 no arquivo server.json

**Comment by rodsmello** [comment]
@melkzsiqueira foi feito isto, a conexão nem fecha sem o SSL no novo appserver.

**Comment by tedcostaanjos** [comment]
Boa noite! Estou com o mesmo problema ao aplicar a LIB, com qualquer uma outra patch é aplicada normalmente, só o arquivo a LIB que não.

**Comment by lwtnb-wrk** [comment]
@rodsmello @tedcostaanjos Tivemos relatos de problemas de incompatibilidade de patches que geram erros de "File could not be copied to the server"...
Poderiam confirmar as versões/build dos AppServers que estão utilizando?
E vocês tem certeza que estão aplicando os patch compatíveis com os ambientes?
Valeu!

**Comment by tedcostaanjos** [comment]
Segue os dados, tentamos aplicar em outros computadores com o VSCODE e apresenta o mesmo problema, eu suspeito que seja algo na transferência do arquivo, mas como arquivos de patches estão indo não deve ser problema de escrita.
Segue a tela da central de atualizaçôes do Protheus.

![image](https://user-images.githubusercontent.com/29553317/78150119-358c3780-740d-11ea-823f-8a3394329338.png)

**Comment by lwtnb-wrk** [comment]
@tedcostaanjos É um ambiente cloud?

**Comment by tedcostaanjos** [comment]
sim, só que na Amazon, gestão nossa aqui.

**Comment by rodsmello** [comment]
> Bom dia!
> Encontrei o erro "file could not be copied to the server" ao tentar aplicação patch conectado ao novo appserver 20-02-21-P12_APPSERVER_BUILD-19.3.0.2_WINDOWS_X64. A build anterior (17.3.0.18_WINDOWS_X64) os pacote são aplicados sem problemas.
> Existe alguma nova configuração?
> 
> console - vscode (v: 1.42.1 - system setup)
> 
> ```
> [Info  - 12:08:52] Starting reconnection to the server: lg-log
> [Log   - 00:00:00] Secure authenticating...
> [Log   - 00:00:00] User authenticated successfully.
> [Info  - 12:08:55] Reconnection to the server: lg-log finished.
> [Info  - 12:09:11] Starting apply patch.
> [Log   - 00:00:00] Starting build for environment UPDDISTR.
> [Log   - 00:00:00] Applying patch file: c:/TOTVS/Microsiga/Protheus_Data/update/20-02-21-LIB_LABEL_14022020_P12_LOBO-TTTP120.PTM
> [Error - 12:09:17] File could not be copied to the server.
> [Log   - 00:00:00] Aborting end build (rollback changes).
> ```
> 
> appserver - console.log
> 
> ```
> 2020-02-25T12:09:12.713000-03:00 17288|------0--c:\totvs\microsiga\protheus_data\update\20-02-21-lib_label_14022020_p12_lobo-tttp120.ptm
> 
> 2020-02-25T12:09:12.717000-03:00 17288|
> [WARN ][SERVER] [THROW][Thread  17288] tConnnErrorException (8:Communication error: Sync error) on D:\bamboo-agent-5.7.2\xml-data\build-dir\TP11-TECX17V3R1-TECXWIN64\lib_comm\msgmanager.cpp:719
> 
> 2020-02-25T12:09:12.718000-03:00 17288|
> [INFO ][SERVER] [[Thread  17288][25/02/2020 12:09:12] Debugger finished ( (user, server)
> 
> 2020-02-25T12:09:17.650000-03:00 12356|[MPPORT] 200225_120917 3044 BPC2019 W x 05 ctx:009 expired timeout for closing of client connection seconds=5 o1r0R1s0S0
> ```

@lwtnb-wrk build 19.3.0.2 Windows x64

**Comment by juniorcc01** [comment]
Olá, estou com o mesmo problema.
Houve alguma solução?

Console.log
[Info  - 15:58:13] Starting apply patch.
[Log   - 00:00:00] Starting build for environment Teste.
[Log   - 00:00:00] Applying patch file: c:/Users/c.oliveira/Desktop/Att-Protheus/20-02-21-LIB_LABEL_14022020_P12_LOBO-TTTP120.PTM
[Error - 15:58:19] File could not be copied to the server.
[Log   - 00:00:00] Aborting end build (rollback changes).
[Info  - 15:58:20] Apply patch finished.

[console.log](https://github.com/totvs/tds-vscode/files/4471393/console.log)

**Comment by lwtnb-wrk** [comment]
@juniorcc01 Acabei de realizar um teste com o mesmo AppServer e mesmo patch, e em meu ambiente consegui aplicar o patch sem problemas.
Não conseguimos reproduzir este problema aqui e por isso não estamos conseguindo identificar o possível problema.
Se puder realizar um teste em seu ambiente faça o seguinte:
Na seção [GENERAL] de seu appserver.ini adicione a linha:
IDEMESSAGES=1
E reinicie o AppServer.
Repita a operação até ocorrer o erro novamente e nos envie o console.log do AppServer.

**Comment by juniorcc01** [comment]
> 
> 
> @juniorcc01 Acabei de realizar um teste com o mesmo AppServer e mesmo patch, e em meu ambiente consegui aplicar o patch sem problemas.
> Não conseguimos reproduzir este problema aqui e por isso não estamos conseguindo identificar o possível problema.
> Se puder realizar um teste em seu ambiente faça o seguinte:
> Na seção [GENERAL] de seu appserver.ini adicione a linha:
> IDEMESSAGES=1
> E reinicie o AppServer.
> Repita a operação até ocorrer o erro novamente e nos envie o console.log do AppServer.

@lwtnb-wrk fiz conforme orientou. 
Segue o console.log novamente!
[console.log](https://github.com/totvs/tds-vscode/files/4477137/console.log)

**Comment by lwtnb-wrk** [comment]
@juniorcc01 Grato pelo teste e console.log.
O que observei no log é que durante a cópia do arquivo para o AppServer ocorre um erro de sincronia e a conexão é derrubada.
Poderia confirmar se seu AppServer está na mesma máquina que o TDS VS Code? Ou está em algum servidor remoto? Talvez em um servidor na Cloud?

**Comment by juniorcc01** [comment]
@lwtnb-wrk O AppServer está no servidor e o VSCode está no meu computador. 
Meu SO é W10 x64
Serveridor: W. Server 2008 R2.

acabei de testar aqui com o VSCode instalado no servidor e ocorre o mesmo problema.

**Comment by lwtnb-wrk** [comment]
@juniorcc01 Vou averiguar esta questão com o time do AppServer, para ver se conseguimos reproduzir esse erro por aqui com essas informações.
Grato pelas informações adicionais.

**Comment by juniorcc01** [comment]
> 
> 
> @juniorcc01 Vou averiguar esta questão com o time do AppServer, para ver se conseguimos reproduzir esse erro por aqui com essas informações.
> Grato pelas informações adicionais.

@lwtnb-wrk Agradeço a Ajuda!
Só para titulo de informação, com a Build 17.3.0.20 a aplicação ocorre normalmente.

**Comment by mhelmers76** [comment]
@lwtnb-wrk estou com o mesmo problema, porém, estou usando a build 17.3.0.20

[INFO ][SERVER] [Thread  7785] JOB Thread finished [-PSWADMIN]
[200415 14:53:04.770] T 7579    O    1  [SW>] MS_RETURN | BIT_END | BIT_COMMIT
[       00:00:02.65407] T 7579  O    1  [__R] CHRONOMETER
[200415 14:53:04.770] T 7579    O    1  [__R] MS_DBGINIREAD | BIT_COMMIT
[200415 14:53:04.770] T 7579    O    1  [SW>] MS_RETURN | BIT_END | BIT_COMMIT
[       00:00:00.000] T 7579    O    1  [__R] CHRONOMETER
[200415 14:53:15.113] T 7579    O    1  [__R] MS_DBGSTARTBUILD | BIT_COMMIT
[200415 14:53:16.027] T 7579    O    1  [SW>] MS_RETURN | BIT_END | BIT_COMMIT
[       00:00:01.65449] T 7579  O    1  [__R] CHRONOMETER
[200415 14:53:16.027] T 7579    O    1  [__R] MS_DBGTMPDIR | BIT_COMMIT
[200415 14:53:16.027] T 7579    O    1  [SW>] MS_RETURN | BIT_END | BIT_COMMIT
[       00:00:00.000] T 7579    O    1  [__R] CHRONOMETER
[200415 14:53:16.027] T 7579    O    1  [__R] MS_DBGCPYFILE | BIT_COMMIT
[200415 14:53:16.027] T 7579    O    1  [SW>] MS_FILEOPEN | BIT_COMMIT
[       00:00:00.000] T 7579    O    1  [__R] CHRONOMETER
[200415 14:53:16.028] T 7579    O    1  [__R] MS_RETURN | BIT_END | BIT_COMMIT
[200415 14:53:16.028] T 7579    O    1  [SW>] MS_RETURN | BIT_END | BIT_COMMIT
[       00:00:00.000] T 7579    O    1  [__R] CHRONOMETER
[200415 14:53:16.028] T 7579    O    1  [__R] MS_DBGCLEANUP | BIT_COMMIT
[200415 14:53:16.028] T 7579    O    1  [SW>] MS_DBGCLEANUP | BIT_COMMIT
[       00:00:00.000] T 7579    O    1  [__R] CHRONOMETER
[200415 14:53:16.028] T 7579    O    1  [SW>] MS_ACKL | BIT_END
[       00:00:00.000] T 7579    O    1  [__R] CHRONOMETER
[200415 14:53:16.028] T 7579    O    1  [__R] MS_DBGENDBUILD | BIT_COMMIT
[200415 14:53:16.048] T 7579    O    1  [SW>] MS_RETURN | BIT_END | BIT_COMMIT
[       00:00:00.020] T 7579    O    1  [__R] CHRONOMETER
[200415 14:54:16.046] T 7579    O    1  [__R] MS_PULSESERVER
[200415 14:54:16.046] T 7579    O    1  [SW>] MS_RETURN | BIT_END | BIT_COMMIT
[       00:00:00.000] T 7579    O    1  [__R] CHRONOMETER

Pode verificar, por favor. Grato!

**Comment by lwtnb-wrk** [comment]
@mhelmers76 Qual o SO de seu AppServer?

**Comment by mhelmers76** [comment]
@lwtnb-wrk segue:
# VERSION="20200414"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20200414"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20200414"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
LOGO="distributor-logo"

**Comment by lwtnb-wrk** [comment]
@rodsmello @tedcostaanjos @juniorcc01 @mhelmers76 
Voces usaram o Apply/Close ou somente Apply para aplicar os patches?
Poderiam testar a aplicação de Patch usando o botão Apply ao inves do Apply/Close ?

**Comment by mhelmers76** [comment]
@lwtnb-wrk eu tentei dos dois jeitos e deu a mesma mensagem, depois testei clicando com o botão direito do mouse no nome do patch e fui em patch apply from file e também deu a mesma mensagem.

**Comment by rodsmello** [comment]
> @rodsmello @tedcostaanjos @juniorcc01 @mhelmers76
> Voces usaram o Apply/Close ou somente Apply para aplicar os patches?
> Poderiam testar a aplicação de Patch usando o botão Apply ao inves do Apply/Close ?

@lwtnb-wrk as duas opções ocorrem o mesmo problema.

**Comment by juniorcc01** [comment]
> 
> 
> @rodsmello @tedcostaanjos @juniorcc01 @mhelmers76
> Voces usaram o Apply/Close ou somente Apply para aplicar os patches?
> Poderiam testar a aplicação de Patch usando o botão Apply ao inves do Apply/Close ?

Já tentei com as duas opções. acontece o mesmo erro.

**Comment by miguelmiziara** [comment]
Olá caros.... estava com o mesmo problema, batendo cabeça.
Façam um teste, para mim resolveu.
Coloquem os includes de vocês exatamente nesse camiho:
C:/totvs/includes

**Comment by rodsmello** [comment]
@lwtnb-wrk 
o problema tem ocorrido quando seleciono mais de um arquivo para aplicação dos pacotes.
Fiz o processo selecionando apenas um arquivo por vez e deu certo. 

__Aplicando um arquivo por vez___
```[Info  - 11:30:10] Initializing Language Server.
[Info  - 11:30:10] Language Server initialized.
[Info  - 11:30:10] Starting reconnection to the server 'local-p12'
[Log   - 00:00:00] Authenticating...
[Log   - 00:00:00] User authenticated successfully.
[Info  - 11:30:13] Reconnection to the server 'local-p12' finished.
[Info  - 11:30:26] Starting apply patch.
[Log   - 00:00:00] Starting build for environment protheus12.
[Log   - 00:00:00] Applying patch file: l:/home/rodrigo/totvs/mp12/protheus_data/update/atf.ptm
[Log   - 00:00:00] Patch successfully applied.
[Log   - 00:00:00] Committing end build.
[Info  - 11:30:34] Apply patch finished.
[Info  - 11:31:08] Starting apply patch.
[Log   - 00:00:00] Starting build for environment protheus12.
[Log   - 00:00:00] Applying patch file: l:/home/rodrigo/totvs/mp12/protheus_data/update/ctb.ptm
[Log   - 00:00:00] Patch successfully applied.
[Log   - 00:00:00] Committing end build.
[Info  - 11:31:14] Apply patch finished.
[Info  - 11:31:35] Starting apply patch.
[Log   - 00:00:00] Starting build for environment protheus12.
[Log   - 00:00:00] Applying patch file: l:/home/rodrigo/totvs/mp12/protheus_data/update/est.ptm
[Log   - 00:00:00] Patch successfully applied.
[Log   - 00:00:00] Committing end build.
[Info  - 11:31:54] Apply patch finished.
[Info  - 11:32:43] Starting apply patch.
[Log   - 00:00:00] Starting build for environment protheus12.
[Log   - 00:00:00] Applying patch file: l:/home/rodrigo/totvs/mp12/protheus_data/update/fat.ptm
[Log   - 00:00:00] Patch successfully applied.
[Log   - 00:00:00] Committing end build.
[Info  - 11:32:59] Apply patch finished.
[Info  - 11:33:32] Starting apply patch.
[Log   - 00:00:00] Starting build for environment protheus12.
[Log   - 00:00:00] Applying patch file: l:/home/rodrigo/totvs/mp12/protheus_data/update/fin.ptm
[Log   - 00:00:00] Patch successfully applied.
[Log   - 00:00:00] Committing end build.
[Info  - 11:34:06] Apply patch finished.
[Info  - 11:34:06] Starting apply patch.
[Log   - 00:00:00] Starting build for environment protheus12.
[Log   - 00:00:00] Applying patch file: l:/home/rodrigo/totvs/mp12/protheus_data/update/fis.ptm
[Log   - 00:00:00] Patch successfully applied.
[Log   - 00:00:00] Committing end build.
[Info  - 11:34:34] Apply patch finished.
[Info  - 11:35:11] Starting apply patch.
[Log   - 00:00:00] Starting build for environment protheus12.
[Log   - 00:00:00] Applying patch file: l:/home/rodrigo/totvs/mp12/protheus_data/update/gs.ptm
[Log   - 00:00:00] Patch successfully applied.
[Log   - 00:00:00] Committing end build.
[Info  - 11:35:22] Apply patch finished.
[Info  - 11:35:36] Starting apply patch.
[Log   - 00:00:00] Starting build for environment protheus12.
[Log   - 00:00:00] Applying patch file: l:/home/rodrigo/totvs/mp12/protheus_data/update/lib.ptm
[Log   - 00:00:00] Patch successfully applied.
[Log   - 00:00:00] Committing end build.
[Info  - 11:36:22] Apply patch finished.
[Info  - 11:36:38] Starting apply patch.
[Log   - 00:00:00] Starting build for environment protheus12.
[Log   - 00:00:00] Applying patch file: l:/home/rodrigo/totvs/mp12/protheus_data/update/tmk.ptm
[Log   - 00:00:00] Patch successfully applied.
[Log   - 00:00:00] Committing end build.```

__Aplicando varios arquivos de uma so vez___
```[Info  - 11:36:49] Apply patch finished.
[Info  - 11:37:03] Starting apply patch.
[Log   - 00:00:00] Starting build for environment protheus12.
[Log   - 00:00:00] Applying patch file: l:/home/rodrigo/totvs/mp12/protheus_data/update/atf.ptm
[Log   - 00:00:00] Patch successfully applied.
[Log   - 00:00:00] Applying patch file: l:/home/rodrigo/totvs/mp12/protheus_data/update/ctb.ptm
[Error - 11:37:11] File could not be copied to the server.
[Log   - 00:00:00] Aborting end build (rollback changes).
[Info  - 11:37:11] Apply patch finished.```

**Comment by lwtnb-wrk** [comment]
@rodsmello Grato pela informação.

**Comment by rodsmello** [comment]
> @rodsmello Grato pela informação.

@lwtnb-wrk, o problema tem ocorrido ao aplicar multiplos arquivos PTM de uma unica vez. Ao realizar a aplicação de patchs uma a uma, não encontrei novamente a divergência.

**Comment by lwtnb-wrk** [comment]
@rodsmello Ainda não conseguimos identificar o problema pois não reproduzimos aqui em desenvolvimento.
O seu primeiro relato (no começo desta issue) indicava erro mesmo aplicando apenas um patch ("20-02-21-LIB_LABEL_14022020_P12_LOBO-TTTP120.PTM").
Já em seu ultimo comentario informa que aplicando os patches um a um funciona.
Estamos ficando sem ideias para solucionar este problema, mas ainda estamos testando cenarios.
Se tiver mais informacoes nos avise.

**Comment by Diogopsm** [comment]
Estou com o mesmo problema, abri um chamado para a totvs se tiver uma resposta deixo aqui.

**Comment by rodsmello** [comment]
@lwtnb-wrk o vscode tem sido atualizado, talvez algum impacto, abaixo meu ambiente atual:
- SO ubuntu 19.10
- vscode 1.44.2
* TOTVS - Build 7.00.191205P - Mar 31 2020 - 18:40:26 
* Build: 64 bits
* SVN Revision: 26467
* Build Version: 19.3.0.3

**Comment by lwtnb-wrk** [comment]
Pessoal, tivemos relatos indicando que a provável causa do problema está na conexão SSL do AppServer.
Se puderem testar desligando a conexão SSL doa AppServer conforme a configuração abaixo:
````
[Drivers]
Active=TCP
MultiProtocolPortSecure=0
MultiProtocolPort=0
```
Mas lembrem-se de alterar a flag `"secure": 0` no 'servers.json' deste AppServer

**Comment by rodsmello** [comment]
Para mim não resolveu @lwtnb-wrk 
Ao tentar com vários pacotes de uma vez, o problema é apresentado no segundo arquivo da fila. 
Em seguida, tentei aplicar apenas o arquivo que apresentou a falha e deu certo.
Se precisar de mais informações, é só pedir.

```[Info  - 14:42:01] Initializing Language Server.
[Info  - 14:42:01] Language Server initialized.
[Log   - 00:00:00] Starting connection to the server 'local-p12' (localhost@1234)
[Log   - 00:00:00] Connection to the server 'local-p12' finished.
[Log   - 00:00:00] Starting user 'admin' authentication.
[Log   - 00:00:00] Authenticating...
[Log   - 00:00:00] User authenticated successfully.
[Log   - 00:00:00] User 'admin' authentication finished.
[Info  - 14:42:53] Starting apply patch.
[Log   - 00:00:00] Starting build for environment protheus12.
[Log   - 00:00:00] Applying patch file: l:/home/rodrigo/totvs/mp12/protheus_data/update/central.ptm
[Log   - 00:00:00] Patch successfully applied.
[Log   - 00:00:00] Applying patch file: l:/home/rodrigo/totvs/mp12/protheus_data/update/comex.ptm
[Error - 14:42:55] File could not be copied to the server.
[Log   - 00:00:00] Aborting end build (rollback changes).
[Info  - 14:42:55] Apply patch finished.
[Info  - 14:43:23] Starting apply patch.
[Log   - 00:00:00] Starting build for environment protheus12.
[Log   - 00:00:00] Applying patch file: l:/home/rodrigo/totvs/mp12/protheus_data/update/comex.ptm
[Log   - 00:00:00] Patch successfully applied.
[Log   - 00:00:00] Committing end build.
[Info  - 14:43:26] Apply patch finished.```

**Comment by lwtnb-wrk** [comment]
@rodsmello Grato pelos testes. Continuaremos analisando entao.

**Comment by lwtnb-wrk** [comment]
@rodsmello Voce poderia enviar os logs do TDS VS Code e do AppServer para verificarmos?

**Comment by andreaweisslou** [comment]
Ola, 
fiz a alteracao indicada e no meu ambiente funcionou

[Drivers]
Active=TCP
MultiProtocolPortSecure=0
MultiProtocolPort=0


Mas lembrem-se de alterar a flag `"secure": 0` no 'servers.json' deste AppServer

**Comment by rodsmello** [comment]
@lwtnb-wrk 
Consegui fazer a aplicação de várias patchs. Problema corrigido.
O ambiente Protheus, continua como antes mas com o VSCode atualizado com a versão 1.45.0.

[console.log](https://github.com/totvs/tds-vscode/files/4630249/console.log)
[vscode.log](https://github.com/totvs/tds-vscode/files/4630264/vscode.log)

**Comment by RaphaelGLeal** [comment]
Boa tarde!

Estava quebrando a cabeça aqui tb, pois tive um pacote que consegui aplicar e vários outros não estava conseguindo, ao realizar a alteração indicada funcionou. ;)

[Drivers]
Active=TCP
MultiProtocolPortSecure=0
MultiProtocolPort=0

**Comment by rbadoni** [comment]
Estou com o mesmo problema. Já tentei todas as sugestões acima.
A particularidade que percebi: só acontece quando o arquivo referenciado esta gravado no servidor (\\xx.xx.x.xxx\d$\totvs ...)

VsCode instalado Local - Versão 1.45.1

Build AppServer: 7.00.191205P-20200424 - 64 bits
Appserver version: 19.3.0.4
Versão da Lib:20200504
Data da Lib: 20200518_142132
Sistema operacional: Windows Server 2016

Remote build: 7.00.191205P-20200221
Remote version: 19.3.0.1
Windows 10 64 Bits

**Comment by maurorajr** [comment]
Porta Multiprotocolo

A TOTVS não recomenda desligar a comunicação segura entre o TOTVS | Application Server e o TOTVS | SmartClient.

Desativar esta chave deixa os dados de conexão vulneráveis (MultiProtocolPortSecure=0).

https://tdn.totvs.com/pages/viewpage.action?pageId=538506132

**Comment by juniorcc01** [comment]
@lwtnb-wrk 
fiz as configurações indicadas e funcionou.
[Drivers]
Active=TCP
MultiProtocolPortSecure=0
MultiProtocolPort=0

Mas lembrem-se de alterar a flag "secure": 0 no 'servers.json' deste AppServer

más e quanto a instrução da TOTVS?
https://tdn.totvs.com/pages/viewpage.action?pageId=538506132

**Comment by fmercurio** [comment]
O teste sugerido no reply abaixo pelo @lwtnb-wrk funcionou aqui.

No meu caso conecto ao AppServer em um servidor remoto via VPN.

Informações do ambiente AppServer:
```
Build AppServer: 7.00.191205P-20200629 - 64 bits
Appserver version: 19.3.0.5
Release do RPO:  12.1.027
Versão da Lib:20200615
Data da Lib: 20200612_1531
```

Informações do VSCode:
```
Version: 1.47.3
Windows 10 Build 19041
TSD Extension: 1.0.6
```

> Pessoal, tivemos relatos indicando que a provável causa do problema está na conexão SSL do AppServer.
> Se puderem testar desligando a conexão SSL doa AppServer conforme a configuração abaixo:
> 
> ```
> [Drivers]
> Active=TCP
> MultiProtocolPortSecure=0
> MultiProtocolPort=0
> 
> 
> Mas lembrem-se de alterar a flag `"secure": 0` no 'servers.json' deste AppServer
> ```

**Comment by lwtnb-wrk** [comment]
> O teste sugerido no reply abaixo pelo @lwtnb-wrk funcionou aqui.
> 
> No meu caso conecto ao AppServer em um servidor remoto via VPN.
> 
> Informações do ambiente AppServer:
> 
> ```
> Build AppServer: 7.00.191205P-20200629 - 64 bits
> Appserver version: 19.3.0.5
> Release do RPO:  12.1.027
> Versão da Lib:20200615
> Data da Lib: 20200612_1531
> ```
> 
> Informações do VSCode:
> 
> ```
> Version: 1.47.3
> Windows 10 Build 19041
> TSD Extension: 1.0.6
> ```
> 
> > Pessoal, tivemos relatos indicando que a provável causa do problema está na conexão SSL do AppServer.
> > Se puderem testar desligando a conexão SSL doa AppServer conforme a configuração abaixo:
> > ```
> > [Drivers]
> > Active=TCP
> > MultiProtocolPortSecure=0
> > MultiProtocolPort=0
> > 
> > 
> > Mas lembrem-se de alterar a flag `"secure": 0` no 'servers.json' deste AppServer
> > ```

@fmercurio Poderia confirmar qual o SO em que o Appserver esta rodando?

**Comment by tnascimento220987** [comment]
Boa tarde, eu também estou com o mesmo problema

[Info  - 13:26:48] User authenticated successfully.
[Info  - 13:26:48] Starting build for environment sped_compila.
[Info  - 13:26:49] Applying patch file: d:/DOWNLOAD/20-07-30_ATUALIZACAO_12.1.27_TSS_EXPEDICAO_CONTINUA/expedicao_continua_12.1.27_tss_tttp120_lg.ptm
**[Error - 13:26:54] File could not be copied to the server.**
[Info  - 13:26:54] Aborting end build (rollback changes).
[Info  - 13:26:54] Apply patch finished

**Comment by lwtnb-wrk** [comment]
@tnascimento220987 Voce tentou utilizar os contornos sugeridos?
E aproveitando, qual o SO que voce utiliza no tds-vscode e com seu Appserver?

**Comment by tnascimento220987** [comment]
Tentei sem sucesso.

Windows Server 2008 R2 Standard

Percebi que o erro é no APPSERVER do TSS mesmo.

Peguei o RPO do TSS e mudei para um APO do ERP e consegui.

Mas achei na internet o link resolvi postar


Em sex., 7 de ago. de 2020 às 13:53, lwtnb-wrk <notifications@github.com>
escreveu:

**Comment by fmercurio** [comment]
> @fmercurio Poderia confirmar qual o SO em que o Appserver esta rodando?
@lwtnb-wrk, está rodando em Windows Server 2016.

**Comment by cleberorati** [comment]
Comecei a ter esse problema, achei que pudesse ser update do Visual Studio, tentei todas as sugestões aqui e não funcionou. Percebi que eu tinha mudado o atalho na minha máquina o AppServer para iniciar como Administrador (eu uso em modo console). Quando voltei tudo como era antes, ou seja, tirei as cláusulas MultiProtocolPortSecure=0 e MultiProtocolPort=0 do appserver.ini, voltei a cláusula "secure": true no servers.json e desmarquei do atalho do AppServer.exe a opção de Executar como Administrador. Depois disso consegui aplicar patches, antes só conseguia compilar prw´s.

**Comment by brunoviskz** [comment]
Olá, tenho o mesmo problema, porém como o cliente é Cloud, não tenho acesso ao appserver.ini. 
O parâmetro 'secure' já está desabilitado (0). 
Versões: Protheus 12.1.25, build 7.00.170117A. VSCode 1.48.2. 
OS do VSCode (diferente do servidor): Windows 7 x64 (Windows_NT x64 6.1.7601)
Existe alguma solução neste caso? Obrigado!

**Comment by brunoviskz** [comment]
**Atualização**: Coincidência ou não, consegui resolver com a dica de um amigo. 
O patch foi aplicado ao **remover as letras maiúsculas do path**!

**Comment by lwtnb-wrk** [comment]
@brunoviskz Só para tentar entender melhor, seu AppServer está rodando em que SO? Se estiver em um Linux este cenário informado faz sentido, pois o Linux tem um filesystem case-sensitive e pelo que sei o AppServer altera o patch para tudo em minúsculos.

**Comment by brunoviskz** [comment]
@lwtnb-wrk é bem provável que seja Linux, mas como é TCloud não consigo te afirmar. 
Fica como dica de melhoria: Tudo que receber no caminho do patch já converter para letras minúsculas, como o Windows não é case-sensitive já funcionaria pra ambos automaticamente.
De qualquer forma, obrigado pelo apoio!

**Comment by rodrigomicrosiga** [comment]
Bom dia, estou utilizando a build 19.3.1.0, já realizei a alteração para secure "false" e também as alterações citadas nas mensagens anteriores referente ao appserver.ini. Porém mesmo assim, o patch não consegue ser aplicado, conforme apresentado abaixo:
[Info  - 09:13:38] User authenticated successfully.
[Info  - 09:13:38] User 'admin' authentication finished.
[Info  - 09:13:53] Starting apply patch.
[Info  - 09:13:53] Starting build for environment T12127PATCH.
[Info  - 09:13:59] Applying patch file: /media/rodrigo/app/totvstec-framework/lib/20-10-13-lib_label_09102020_p12_lobo-tttp120.ptm
[Error - 09:13:59] File could not be copied to the server.
[Info  - 09:13:59] Aborting end build (rollback changes).
[Info  - 09:13:59] Apply patch finished.

O ambiente em questão, é exclusivo para desenvolvimento e está rodando num sistema operacional Linux Mint 20.
Alguma correção e/ou sugestão para corrigir o problema?

**Comment by Ragoy** [comment]
Bom dia,

Até a semana do dia 07/11/2020 eu não tinha problema algum para fazer as atualizações e não importava a forma, depois dessa data com todo o sistema atualizado, no meu caso Protheus 12.1.25 com os binários appserver e smartclient do dia 12/10/2020, passei a ter problemas, tentando atualizar com os novos que sairão depois dessa data.
Eu consigo compilar os .prw como um amigo acima  também comentou, mas não consigo aplicar os pacotes em lote e independente do botão que utilizei, realizei todos os teste acima e todos foram sem sucesso efetivo, então passei a compilar um a um e notei que o problema está nos pacotes do TSS, todos os pacotes do TSS que tentei ele fez rollback changes.
Então removi todos os pacotes que tinha referente ao TSS e depois adicionei para aplicar em lote e funcionou perfeitamente.
Att,

**Comment by hiarlyalves** [comment]
Fiz o que o colega recomendou.
Tirei execução como Administrador..

**"Desfiz tudo isso"**
[Drivers]
Active=TCP
MultiProtocolPortSecure=0
MultiProtocolPort=0
Mas lembrem-se de alterar a flag `"secure": 0` no 'servers.json' deste AppServer

e funcionou!!!!
Mas lembrando que toda dica e ajuda é sempre bem vinda !!!!!!
Aos participantes fica meu agradecimento !!!!!

**Comment by brunoviskz** [comment]
Fala pessoal, tudo bem?
Gostaria de compartilhar a solução que consegui:
Mesmo após todas as tentativas acima, eu não conseguia aplicar ptm's maiores que 14mb.
Como contorno, eu usava o FTP para enviar o patch para o cloud (\system) e o Eclipse para aplicar via servidor, isso funcionava.

Porém, recentemente precisei atualizar para Build 19.312, onde o Eclipse não se conecta mais. Para a minha surpresa, após essa atualização o VS Code passou a aceitar arquivos com mais de 14mb! Detalhe: Com 'secure' ligado.
Bom, não quero dizer que é uma solução definitiva, mas caso tenha mais alguém com o mesmo problema que eu, fica a dica. No meu caso, a versão 17.0117A não aceitava arquivos "pesados".

Obrigado a todos pela contribuição.

**Comment by danielvscode** [comment]
Pessoal, apenas compartilhando:
Estava com o mesmo problema, fiz todos os passos acima sem sucesso, porem era o tamanho do caminho do diretório onde estava o Patch,  deixei em uma pasta dentro o C:/ e Funcionou.

**Comment by thiagoaagomez** [comment]
Estava com o mesmo problema aqui quando tentava aplicar o patch que estava saldo em meu servidor de dados, bastou jogar os arquivos pro meu pc e consegui aplicar o patch.

**Comment by joliv3ira** [comment]
Quem ainda tiver o problema, com dicionários no Banco de Dados, dá 1 olhada no RoothPath para o ambiente, definido no AppServer.ini ...

**Comment by viniciusgati** [comment]
Podia ter um detalhe do erro nesse caso não acham? está meio generico minha maquina está apresentando isso também e não consigo saber o motivo

Ao pedir patch info do mesmo pacote que deu errado aparece `DBGCpyFile error.`
