### ISSUE TITLE
Erro ao Executar Debug

### ISSUE THREAD

**Issue by iurycardoso** [totvs/tds-vscode#29]
![image](https://user-images.githubusercontent.com/33526377/58108581-7d71e980-7bc2-11e9-94ee-9b777bcb4de9.png)

![image](https://user-images.githubusercontent.com/33526377/58108475-48659700-7bc2-11e9-95b2-a9670e3482fa.png)

**Comment by ricardomansano** [comment]
@iurycardoso, boa tarde, faz um teste rápido pra gente garantir que vai mexer no lugar certo:
-Tira o espaço do teu diretório TOTVS[*]12 (isso dá pra gente ajustar no plugin)
-No laucher.json coloca smartclient.exe (se o nome estiver errado vc precisa ajustar esse)
Ficamos na escuta

**Comment by iurycardoso** [comment]
@ricardomansano , grato pelo retorno. Alterações efetuadas e seguimos com o erro. 

![image](https://user-images.githubusercontent.com/33526377/58118476-4c4fe400-7bd7-11e9-97e2-74329c4a792e.png)

**Comment by lwtnb-wrk** [comment]
@iurycardoso não estamos conseguindo reproduzir seu problema
favor tentar renomear o arquivo "launch.json" que esta na pasta ".vscode" e depois acionar o comando (CTRL+SHIFT+P) "TOTVS: Configure Launchers" e tente refazer as configurações de laucher. depois tente executar o debug novamente para ver se o erro persiste.
outros testes possiveis, executar o smartclient.exe por fora do tds-vscode para ver se ele esta funcionando corretamente.
grato pelos testes!

**Comment by iurycardoso** [comment]
@lwtnb-wrk , grato pelo retorno. 
Sim, efetuei todos os testes possíveis e está tudo funcionando corretamente. 
TDS
SmartClient por fora
tudo certinho! 

Mas de qualquer forma agradeço vocês pelo retorno e suporte.

**Comment by lwtnb-wrk** [comment]
@iurycardoso só não entendi se agora está tudo funcionado como esperado ou se você está com problemas ainda... 
e chegou a tentar refazer as configurações de launcher?

**Comment by iurycardoso** [comment]
@lwtnb-wrk desculpe, me posicionei errado! 

No VSCode segue sem funcionar.

**Comment by ricardomansano** [comment]
@iurycardoso , grato pelos testes, vamos dar seguimento na analise

**Comment by likid** [comment]
Pessoal, estou com um problema no debug também, se eu deixo no launch.json "${command:AskForProgramName}" ele não funciona, mas se deixo sigaadv, aí ele abre o sigaadv diretamente.

![Code_2019-05-22_15-23-34](https://user-images.githubusercontent.com/10984007/58198864-9dc6a480-7ca5-11e9-8732-bd26d85396be.png)

**Comment by likid** [comment]
Descobri porque ocorria este problema. Eu tenho no workspace várias pastas configuradas, uma para cada projeto, eu movi o launch.json da primeira pasta para a segunda e começou a ocorrer o problema, quando eu voltei o arquivo para a pasta .vscode da primeira pasta o debug voltou a funcionar normalmente.

**Comment by lwtnb-wrk** [comment]
> Descobri porque ocorria este problema. Eu tenho no workspace várias pastas configuradas, uma para cada projeto, eu movi o launch.json da primeira pasta para a segunda e começou a ocorrer o problema, quando eu voltei o arquivo para a pasta .vscode da primeira pasta o debug voltou a funcionar normalmente.

@likid realmente os arquivos dentro da pasta .vscode nao devem ser movido ou alterados manualmente, pois podem causar comportamentos inesperados. de qualquer forma, grato por compartilhar a informação

**Comment by lwtnb-wrk** [comment]
> @lwtnb-wrk desculpe, me posicionei errado!
> 
> No VSCode segue sem funcionar.
> Sim refiz todos os passos mas deu o mesmo erro.

@iurycardoso Refez os passos mas chegou a refazer o laucher.json tambem?

**Comment by iurycardoso** [comment]
@lwtnb-wrk Sim, refiz ele mas o erro seguiu. 

Hoje chegando em casa irei efetuar alguns testes e lhe passo um feedback.

**Comment by ricardomansano** [comment]
@iurycardoso , bom dia, chegou a fazer o teste pra gente?

**Comment by DanielYampolschi** [comment]
Ola @iurycardoso, tudo bom, pode confirmar por favor se o problema foi resolvido para fecharmos essa issue? muito obrigado.

**Comment by ricardomansano** [comment]
Issue encerrada por falta de retorno.

**Comment by iurycardoso** [comment]
Bom dia Pessoal, desculpe a demora. Na máquina a qual fiz os testes não consegui resolver (Irei formatar o ambiente e iniciar tudo do zero para testar). Já em outra máquina minha, eu instalei tudo do zero (Vscode e extensão) e funcionou!

**Comment by lwtnb-wrk** [comment]
> Bom dia Pessoal, desculpe a demora. Na máquina a qual fiz os testes não consegui resolver (Irei formatar o ambiente e iniciar tudo do zero para testar). Já em outra máquina minha, eu instalei tudo do zero (Vscode e extensão) e funcionou!

@iurycardoso Pelo menos voce tem um ambiente funcionando entao!!! se precisar abrir outra issue fique a vontade. Grato pelos testes
