### ISSUE TITLE
Onde Desativar Debug com Multi Threads?

### ISSUE THREAD

**Issue by CidGianni** [totvs/tds-vscode#290]
A alguns meses atrás, um colega estava fazendo um desenvolvimento ADVPL com o VSCode, e sempre que fazia um debug em um ambiente, derrubava o serviço do AppServer.
Sugeri e ele confirmou que estava com o Debug Multi Threads ativado. Desativou e parou de derrubar o servidor. 
Agora que estou utilizando o VSCode, não estou localizando onde desativar esta condição para debug.

Att.

Aparecido Gianni

![image](https://user-images.githubusercontent.com/61091421/75385032-c9725d00-58bd-11ea-99b3-cdd57055ac65.png)

**Comment by CidGianni** [comment]
A tela que anexei é do TDS Eclipse, apenas para referencia.

**Comment by lwtnb-wrk** [comment]
@CidGianni A principio se não for configurado especificamente como ligado, essa configuração vem desativada por padrão.
Veja nas configuracoes de seu "launch.json" se existe a configuracao:
"enableMultiThread": true,
e se houver, remova essa configuracao ou marque para false, para desativar.
