### ISSUE TITLE
Problema p/ conectar APPSERVER_BUILD-19.3.0.2_WINDOWS_X64

### ISSUE THREAD

**Issue by charllesrox** [totvs/tds-vscode#291]
Issue Type: <b>Bug</b>

Boa tarde, após atualizar o appserver para a versão 20-02-21-P12_APPSERVER_BUILD-19.3.0.2_WINDOWS_X64 o VSCode não consegue mais conectar, já refiz todas as configurações como fiz anteriormente nos outros appservers e não passa. Sendo assim, voltei o appserver para a versão anterior e deu certo. Podem me ajudar?

Extension version: 0.3.23
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by caiadofelipe** [comment]
@charllesrox , Passei por esse problema também, essa Build nova do Protheus está aceitando somente conexão segura, mude o server.json do seu vscode conforme o exemplo abaixo

"secure": 1

{
			"id": "gydeclxgnhk74y73xdw3cg10vt8z",
			"type": "totvs_server_protheus",
			"name": "Local - PROTHEUS_12_1_27",
			"port": 1235,
			"address": "LOCALHOST",
			"buildVersion": "7.00.191205P",
			"secure": 1,
			"includes": [],
			"environments": [
				"PROTHEUS_12_1_27"
			],
			"username": "ADMIN",
			"environment": "PROTHEUS_12_1_27"
		}

**Comment by lwtnb-wrk** [comment]
@charllesrox Conforme apontado pelo @caiadofelipe , o novo AppServer 19 vem com a conexão segura habilitada por padrão então se a flag secure não estiver marcada, a conexão não será aceita.
Mude no seu "servers.json" ou na criação marque a opção "Secure".
Na próxima release do TDS VS Code faremos a detecção automática no cadastro do servidor.
