### ISSUE TITLE
Problema na compilação com binário 7.00.191205P

### ISSUE THREAD

**Issue by Smmartinez** [totvs/tds-vscode#292]
Estou com um erro intermitente, quando coloco para recompilar todos os fontes no binário 7.00.191205P a compilação simplesmente aborta no meio da compilação. Não é sempre no mesmo fonte, são fontes aleatórios. Se vou e compilo apenas aquele fonte onde parou a compilação ele compila sem problema.
Versão do Vs CODE: 1.42.1
Binário 7.00.191205P
Versão do Protheus Release 27

**Comment by Smmartinez** [comment]
Apenas complementando, acabei de fazer um teste tirando o multiprotocolo do INI e fazendo uma nova conexão sem sem segura e a compilação ocorreu sem cair no meio.

**Comment by lwtnb-wrk** [comment]
@Smmartinez Grato pelas informações.
Chegou a testar a compilação por partes? Apenas um modulo de cada vez??

**Comment by Smmartinez** [comment]
@lwtnb-wrk Sim... se vou rodando pasta a pasta aparentemente o problema não ocorre. Só notei o problema quando coloco todos os fontes para compilar e com o SSL ativado.

**Comment by lwtnb-wrk** [comment]
@Smmartinez Fizemos alterações no feedback da compilação em casos com muitos arquivos (acima de 1000 arquivos).
Aparentemente isso causava um "congestionamento" no pipe de comunicação entre o TDS VS Code e o LS e o uso da memoria começava a subir causando uma falha ao consumir toda a memoria.
Com essa limitacao de notificações para compilacao aparentemente o problema foi resolvido.
Aguarde as proximas atualizacoes do TDS VS Code.
