### ISSUE TITLE
Extensão TOTVS Monitor for VS Code

### ISSUE THREAD

**Issue by CidGianni** [totvs/tds-vscode#293]
Bom dia colegas. A extensão TOTVS Monitor for VS Code terá as mesmas funcionalidades do Totvs Monitor Electron JS, o qual permite desconectar sessão de usuário? Caso negativo irei desinstalar a  extensão.

Att.

Aparecido Gianni

**Comment by lwtnb-wrk** [comment]
@CidGianni Realmente no momento o Monitor está passando por uma reestruturação e em breve estará disponivel novamente. Se preferir pode desinstalar por enquanto e fique de olho nas atualizações.
