### ISSUE TITLE
Atalho de projetos no VsCode

### ISSUE THREAD

**Issue by diasssp** [totvs/tds-vscode#294]
Pessoal, é possível criar uma pasta de um determinado projeto utilizando atalhos de fontes que estão em outras pastas?

**Comment by carloseniemeyer** [comment]
Issue relacionado a questão no DevForum:
**https://devforum.totvs.com.br/1266-organizacao-de-projetos-no-vscode---mesmo-arquivo-em-projetos-diferentes**

**Comment by lwtnb-wrk** [comment]
@diasssp Creio que quis dizer "links" (link simbolico) ao dizer "atalhos de fontes" correto?
Isso se trata de funcionalidade do proprio VS Code na questao de organizacao de workspace.
O TDS VS Code não implementará nenhuma funcionalidade adicional nesta questão.
Se ela existir e/ou for implementada no futuro no "core" do VS Code o TDS receberá o recurso automaticamente.
