### ISSUE TITLE
Erro ao aplicar mais de um patch ao mesmo tempo.

### ISSUE THREAD

**Issue by diegollelis** [totvs/tds-vscode#296]
**Describe the bug**
Ao selecionar mais de um patch para aplicação, a partir do segundo aparece a mensagem de erro "File could not be copied to the server.".

**Comment by lwtnb-wrk** [comment]
@diegollelis Realizei a aplicação de dois patches e não ocorreu nenhum erro. 
Poderia detalhar seu problema?

**Comment by diegollelis** [comment]
Bom dia, seleciono 2 patches, cada um em um diretório diferente, a partir do segundo aparece uma mensagem de erro.

Segue imagem da tela apply patch.
![apply patch](https://user-images.githubusercontent.com/54968947/76316065-ac279080-62b8-11ea-9f17-d5e23d12f0f0.png)


Log: 
[Info  - 10:16:26] Starting apply patch.
[Log   - 00:00:00] Starting build for environment prd_diego.
[Log   - 00:00:00] Applying patch file: e:/01-Atualizacao Protheus/12.1.25/08-Pacotes/20-03-06_ATUALIZACAO_12.1.25_GS_EXPEDICAO_CONTINUA_TTTP12_LG/TTTP120_LG.PTM
[Log   - 00:00:00] Patch successfully applied.
[Log   - 00:00:00] Applying patch file: e:/01-Atualizacao Protheus/12.1.25/08-Pacotes/PACOTE_DE_CORRECAO_7958279_DVARLOJ4-7026_12.1.25/7958279_dvarloj4-7026_12.1.25_tttp120_lg.ptm
[Error - 10:16:29] File could not be copied to the server.
[Log   - 00:00:00] Aborting end build (rollback changes).

**Comment by lwtnb-wrk** [comment]
@diegollelis Aplicando os patches individualmente funciona?

**Comment by bkeniti** [comment]
Estou com o mesmo erro, aplicando vários patches ao mesmo tempo da erro. Ao Aplicar os patches individualmente funciona. Percebi isso no servido Linux. No Windows aplica normal. Já tentei com o caminho todo minúsculo e mesmo assim da erro.

**Comment by lwtnb-wrk** [comment]
@bkeniti Grato pela informação sobre o S.O.

@diegollelis Seu servidor também está em um Linux?

**Comment by diegollelis** [comment]
Boa tarde, sim.

**Comment by lwtnb-wrk** [comment]
@diegollelis @bkeniti Voces usaram o Apply/Close ou somente Apply para aplicar os patches?
Poderiam testar a aplicação de Patch usando o botão Apply ao inves do Apply/Close ?

**Comment by bkeniti** [comment]
O erro ocorre independentemente de clicar em apply, ou apply/close.

obrigado

Em qui., 16 de abr. de 2020 às 17:35, lwtnb-wrk <notifications@github.com>
escreveu:

**Comment by lwtnb-wrk** [comment]
@diegollelis @bkeniti Tivemos relatos indicando que a provável causa do problema esta na conexão SSL do AppServer.
Se puderem testar desligando a conexão SSL doa AppServer conforme a configuração abaixo:
````
[Drivers]
Active=TCP
MultiProtocolPortSecure=0
MultiProtocolPort=0
```
Mas lembrem-se de alterar a flag `"secure": 0` no 'servers.json' deste AppServer

**Comment by ricardomansano** [comment]
Boa tarde,
Dado tempo sem resposta acredito que o problema tenha sido resolvido.
Continuamos a disposição
