### ISSUE TITLE
configuração totvsLanguageServer.extensions.folder.patch não está sendo respeitada.

### ISSUE THREAD

**Issue by diegollelis** [totvs/tds-vscode#297]
**Describe the bug**
Boa noite, estou usando a configuração "totvsLanguageServer.extensions.folder.patch", para definir as extensões que serão compiladas(deixei as que vem por padrão), porem quando vou compilar utilizando o "Compile file" posicionado na pasta do projeto é apresentado um erro e abortada a compilação. Possuo o arquivo README.md e é justamente nele que dá o problema, pelo que percebi a extensão .md não está sendo ignorada no momento da compilação.

**Comment by lwtnb-wrk** [comment]
@diegollelis Você tentou não usar essa configuração?
A princípio o TDS VS Code entende as extensões padrão do Protheus e caso não reconheça a extensão, como no caso da extensão .md, ele compila esse arquivo com um resource.

**Comment by carloseniemeyer** [comment]
Bom Dia! Existe a opção para evitar que o arquivo seja enviado como Recurso (Resource) para o RPO?

Pretendo também excluir arquivos .txt, .sql que estão no projeto, mas não seja aplicado ao RPO, principalmente ao usar o recurso Compile All Workspace (Usando o recurso de Multi-Root).

Já tentei usar files.exclude porém também não removeu esses arquivos da compilação, mesmo que não sejam exibidos na pasta explorer.

**Comment by lwtnb-wrk** [comment]
@carloseniemeyer O recurso "Compile All Workspace" deve ser utilzado para compilar todo o workspace. Se deseja que alguma coisa não seja compilada, remova do workspace ou compile apenas o que deseja que seja compilado.
Esses filtros de exibição realmente não farão nenhum efeito.
Se achar interessante, desenvolva essa funcionalidade e submenta via Pull Request para que possamos avaliar e incorporar na extensão.

**Comment by antunesls** [comment]
> **Describe the bug**
> Boa noite, estou usando a configuração "totvsLanguageServer.extensions.folder.patch", para definir as extensões que serão compiladas(deixei as que vem por padrão), porem quando vou compilar utilizando o "Compile file" posicionado na pasta do projeto é apresentado um erro e abortada a compilação. Possuo o arquivo README.md e é justamente nele que dá o problema, pelo que percebi a extensão .md não está sendo ignorada no momento da compilação.

@diegollelis , como está sua configuração do setting.json na parte da opção "totvsLanguageServer.extensions_folder_patch"  ?

Esse parâmetro foi colocado ai justamente pra evitar isso mesmo.

**Comment by carloseniemeyer** [comment]
Pessoal, boa tarde!

No meu arquivo settings local está dessa forma:

{
    "files.encoding": "windows1252",
    "workbench.sideBar.location": "left",
    "workbench.colorTheme": "Default Light+",
    "files.autoSave": "afterDelay",
    "files.exclude": {
        "**/*.json": true,
        "**/*.sql": false,
        "**/*.txt": true
    },
    "totvsLanguageServer.extensions.folder.patch": [
        ".PRW",
        ".PRX",
        ".PRG",
        ".APW",
        ".APH",
        ".TRES",
        ".PNG",
        ".BMP",
        ".RES",
        ".APL",
        ".TLPP",
        ".4GL"
      ],

E mesmo assim ao compilar uma pasta ou workspace ele compila todo tipo de extensão (No meu caso enviando para o RPO .txt e .sql). Gostaríamos de evitar isso.

Criamos workspace relacionado links de fontes específicos e também de algumas pastas que contém .sql .txt, mas ao compilar All Workspace (Para não ter que compilar fonte a fonte), ele compila todos os arquivos .prw e também envia outros arquivos que são mostrados na página de resultado da compilação (Já verificados também no inspetor de objetos que foram compilados).

**Comment by lwtnb-wrk** [comment]
@diegollelis A opcao "totvsLanguageServer.extensions.folder.patch" está limitando apenas as extensões consideradas para a geração de patches. 
Na realidade ela era utilizada para compilar os fontes antes de gerar um patch com estes fontes.
Então alteramos a chave para "totvsLanguageServer.folder.extensionsAllowed"que será utilizada na compilação não importa de onde vier.
Se voce alterou esta chave, quando atualizarmos o TDS VS Code apenas certifique-se de que a nova chave tenha as mesmas alterações que ja fez.
Esta mudança estará na próxima atualização.

**Comment by DouglasChagas** [comment]
@lwtnb-wrk mesmo meu settings.json estando assim:
{
    "totvsLanguageServer.welcomePage": false,
    "[advpl]": {
        "files.encoding": "windows1252"
    },
    "totvsLanguageServer.askEncodingChange": false,
    "totvsLanguageServer.askCompileResult": true,
    "totvsLanguageServer.folder.extensionsAllowed": [
        ".TRES",
        ".PRW",
        ".PRX",
        ".PRG",
        ".PPX",
        ".PPP",
        ".TLPP",
        ".APW",
        ".APH",
        ".APL",
        ".AHU",
        ".TRES",
        ".PNG",
        ".BMP",
        ".RES",
        ".4GL",
        ".PER",
        ".JS"
    ]
}

Ele não compila o arquivo .tres informando:
[Info  - 00:16:54] Start secure compiling d:/vscode_fontes/caracol/caracol/antigos/rh/fontes_totvs/impirpf_pt-br.tres (1/1).
[Error - 00:16:54] User with no rights to change resource.
[Info  - 00:16:54] Aborting end build (rollback changes).
[Error - 00:16:54] One or more files have errors and/or warnings. See problems and logs for details.
[Info  - 00:16:54] Recompile finished.

Sabe o que pode ser?

**Comment by lwtnb-wrk** [comment]
@DouglasChagas Seu problema não tem relação com esta issue. Abra uma nova issue com o maior numero de detalhes para que podemos te ajudar.
