### ISSUE TITLE
go to definition advpl 

### ISSUE THREAD

**Issue by charlesreitz** [totvs/tds-vscode#298]
Olá Pessoal, algumas linguagens no VS Code trabalham com go to definition onde pode-se clicar sobre a função e ela vai onde está a linha. 

Existe isso no ADVPL com VSCode?

Achei esse link que acredito ser o que estou procurando, mas precisa ser implementando certo? 

https://code.visualstudio.com/docs/editor/editingevolved#_go-to-definition

**Comment by lwtnb-wrk** [comment]
@charlesreitz Ainda não temos esta funcionalidade mas ela existe em nossa lista de implementações futuras, porém ainda sem previsão.
Vou fechar este chamado mas fique de olho nas atualizações.
