### ISSUE TITLE
Traducao para o Russo

### ISSUE THREAD

**Issue by eternauta123** [totvs/tds-vscode#299]
Como fazer o pull request para a traducao para russo? So editar os arquivos da pasta i18n/src? (tem uma mensagem que pede para nao editar dentro dos arquivos)

**Comment by acacioegas** [comment]
Documentamos as formas de contribuir com a tradução no arquivo https://github.com/totvs/tds-vscode/blob/dev/LOCALIZING-VSCode.md.
