### ISSUE TITLE
Indentação de código

### ISSUE THREAD

**Issue by likid** [totvs/tds-vscode#3]
Ao utilizar o TDS baseado no eclipse é possível realizar a indentação dos códigos através de um comando existente nele o qual podemos customizar qualquer tecla de atalho para executa-lo, na extensão feita para o vscode eu não encontrei uma forma de fazer a indentação do código, esta funcionalidade já existe ou já está planejada?

**Comment by matheus-sales** [comment]
Olá @likid 

A funcionalidade ainda não existe, mas está nos nossos planos. 

Obrigado!

**Comment by delsonfilho** [comment]
Aguardando a funcionalidade 👍

**Comment by likid** [comment]
Pessoal, esta funcionalidade eu acho bem interessante estar no roadmap pois muitos devs provavelmente ainda não migraram para o vscode por conta da falta desta funcionalidade, assim como acontece aqui conosco. Esta funcionalidade é uma das principais e mais básicas de qualquer IDE também.

**Comment by DanielYampolschi** [comment]
Ola @likid , concordamos que é uma funcionalidade bastante importante e já está no Roadmap.
Muito obrigado pela sugestão.

**Comment by likid** [comment]
@DanielYampolschi realmente está, me desculpe a cobrança mas eu realmente não havia visto que já estava.
Obrigado pelo retorno.

**Comment by brodao** [comment]
Efetuado correção no processo de formatação de recursos a partir da visão "Explorer".
