### ISSUE TITLE
Patch could not be applied. Server returned: DUplicated function...

### ISSUE THREAD

**Issue by physyyxx** [totvs/tds-vscode#300]
Bom dia,

Estou tendo problemas ao aplicar patchs utilizando o plugin no VSCode.

No Eclipse tínhamos a opção se aplicar somente funções mais novas. 

Não vejo essa opção no VScode e acredito que este seja o motivo de eu não estar conseguindo aplicar patches.

Segue o link com print do erro: [PRINT](https://imgur.com/WoJFXrO)

**Comment by lwtnb-wrk** [comment]
@physyyxx A opção para aplicar funções antigas existe. É a última opção na tela ("Apply old files") e vem desmarcada por padrão.
Esse erro de funções duplicadas é um retorno de um erro do Appserver e pode indicar que o patch que esta sendo aplicado não é compativel ou necessita que outros patches seja aplicados antes deste.
Verifique se realmente este patch deve ser aplicado no seu ambiente.
