### ISSUE TITLE
Aplicação de Patch - Possibilidade de exportar arquivo com as informações do conteúdo do patch

### ISSUE THREAD

**Issue by danflavio** [totvs/tds-vscode#301]
**Is your feature request related to a problem? Please describe.**
Não

**Describe the solution you'd like**
No inspetor de patch, seria interessante ter uma opção para exportar o conteúdo do patch para algum tipo de arquivo (exemplo: .txt) que facilite a análise do conteúdo.

![patch_infos](https://user-images.githubusercontent.com/33727221/76091810-0b299480-5f9d-11ea-8459-acd73ae056b1.png)

**Describe alternatives you've considered**
Sem comentários

**Additional context**
Com um patch que possui uma quantidade maior de arquivos/fontes, a navegação via "Previous" e "Next" não fica muito usual.

**Comment by ricardomansano** [comment]
Boa tarde,
Issue resolvida e disponibilizado hoje na versão 1.0.3 do plugin
At,
