### ISSUE TITLE
Lentidão com extensões no VsCode utilizando o TDS

### ISSUE THREAD

**Issue by Wexlei** [totvs/tds-vscode#302]
Olá.
Ao utilizar a extensão 'Totvs Developer Studio for VSCode', todas as outras extensões e plugins instalados apresentam lentidão, que cessa ao desabilitar a extensão da Totvs.
A própria extensão em si fica lenta na maioria das vezes, demorando para responder aos comandos de compilação e debug.
O VsCode em si funciona normalmente e sem lentidão, mas todas as outras extensões ficam lentas de alguma forma enquando a TDS for VsCode está habilitada, sendo os mais visíveis o Git e o Numbered Bookmarks.
Exemplo: Com a extensão habilitada, a extensão Numbered Bookmarks simplesmente não responde aos comandos ou, quando responde, demora vários minutos.
No caso do Git, em vários momentos preciso desabilitar a extensão do TDS para conseguir fazer um commit.

Já tentei reinstalar a extensão, excluindo a pasta totvsls conforme instruído em uma outras issues daqui, mas a lentidão persiste. Também tentei desabilitar outras extensões, deixando apenas a TDS com Git, também sem eficácia.

**As extensões que tenho instaladas e habilitadas no VsCode são:**
> ADVPL Snippets;
> Numbered Bookmarks;
> Protheus for VsCode;
> TODO Highlight;
> Todo Tree;
> Totvs Developer Studio for VSCode

**Plugins instalados:**
> Git

**Versões:**
VsCode: 1.42.1
SO: Windows 10 Pro (6.2.9200)
Totvs Developer Studio for VSCode: 0.3.23
DBAccess: 20191119-20191206

**Appserver**
Build 7.00.191205P - Jan 24 2020 - 00:47:15
Build: 64 bits
SVN Revision: 25876
Build Version: 19.3.0.1_RC10

**Comment by lwtnb-wrk** [comment]
@Wexlei Nao observamos nenhum tipo de lentidão em nossos ambientes.
O problema ocorre em multiplas maquinas ou somente na sua maquina?

**Comment by Wexlei** [comment]
Descobri, a partir do comando F1 > Show Running Extensions que o problema real era uma outra extensão que estava apresentando lentidão ao inicializar, a _Todo Tree_.
A extensão do TDS está funcionando normalmente, pode fechar esta issue.
