### ISSUE TITLE
Erro no modo Debug

### ISSUE THREAD

**Issue by davidpulz** [totvs/tds-vscode#303]
Bom dia, executando a função de usuário abaixo em modo debug, o erro abaixo é apresentado:

THREAD ERROR ([8540], david, L288)   09/03/2020 08:26:08
variable does not exist CACESSO on VERSENHA(MSLIB.PRW) 12/07/2019 17:27:31 line : 1446

--------------------------------------------------------------------------------------------------------
User Function KSCADSA1()
	AxCadastro("SA1", "TESTE", NIL, NIL)
Return

**Comment by lwtnb-wrk** [comment]
@davidpulz Realmente reproduzi o erro aqui tanto em um sevidor build 17 e um build 19, mas aparentemente trata-se de algo do lado do Framework.
Por favor abra um chamado com o time de Framework para que eles possam verificar.
Grato por informar.
