### ISSUE TITLE
Build version was not informed

### ISSUE THREAD

**Issue by wico2k** [totvs/tds-vscode#304]
Buenos días,

Hasta el día de ayer 10/03/2020 lograba conectarme a un ambiente Protheus Release 27 sin inconvenientes con VSCode.

Sin embargo, hoy me aparece el mensaje: "One or more validations errors detected: Build version was not informed."

Por ello hemos modificado el archivo "servers.json" de la siguiente manera:
* Anterior "buildVersion": "",
* Actual "buildVersion": "7.00.191205P",

Luego de modificar la llave "buildVersion", VSCode emite un nuevo mensaje: "Authentication failed. Could not connect to server JFFB-T430:5127."

Aguardamos su pronta respuesta.

Atentamente,

Federico Fernandez

**Comment by lwtnb-wrk** [comment]
@wico2k los servidores 7.00.191205P tienen que tener la llave ("secure": 1) para conectarse.
verifique si esta clave existe en su "server.json" o intente crear un nuevo servidor con la casilla de verificación segura marcada

**Comment by wico2k** [comment]
Gracias @lwtnb-wrk - luego de hacer el cambio que indica, pude conectarme.
