### ISSUE TITLE
Instalação !

### ISSUE THREAD

**Issue by JoelberGarcia** [totvs/tds-vscode#305]
Bom dia, 

estou tentando adicionar um server e a extensão do TDS não deixa eu salvar o servidor. Gera a mensagem de .json e não deixa eu confirmar conforme vídeo.
[vscode.zip](https://github.com/totvs/tds-vscode/files/4312474/vscode.zip)
![vscode](https://user-images.githubusercontent.com/61033874/76313899-9d3edf00-62b4-11ea-9d4a-91da671fc180.jpg)

**Comment by lwtnb-wrk** [comment]
@JoelberGarcia Houve algum tipo de edição manual no arquivo "servers.json"? Aparentemente ele está corrompido.
Clique na "engrenagem" e verifique se no final do arquivo ele está com uma marcação de erro.
Provavelmente é necessário adicionar uma "}" sem as aspas no final do arquivo e salvar em seguida.
Caso não funcione, procure o arquivo "servers.json" na sua pasta de usuário, renomeie ele para qualquer coisa e reinicie o TDS VS Code. Um novo arquivo "servers.json" será criado e voce deve conseguir cadastrar novos servidores.

**Comment by JoelberGarcia** [comment]
Boa tarde, peguei os dados de um servidor do colega e colei no meu servers.json e funcionou. O meu estava em branco !

**Comment by lwtnb-wrk** [comment]
@JoelberGarcia Vamos adicionar umas proteções para prevenir este tipo de erro nas proximas atualizaçoes.
