### ISSUE TITLE
Plugin Totvs não instala

### ISSUE THREAD

**Issue by LandoaldoMSantos** [totvs/tds-vscode#307]
Instalei o Vscode e quando tento instalar o plugin, não instala. O Vscode manda fazer download do plugin e instalar manualmente, mas também não instala. Estou usando Windows Server 2012 R2.

**Comment by lwtnb-wrk** [comment]
@LandoaldoMSantos Já tivemos reports informando que existem problemas em usar nossa extensão no Windows Server, pois essa versão do Windows pode não ter as DLLs necessarias para execucao de aplicacoes desktops.
Apesar disso o usuario que estava com problema nos informou que conseguiu usar o TDS VS Code adicionando o parametro "-N" no atalho de execução do TDS VS Code.
Veja se isso funciona para voce tambem...
De qualquer forma aconselhamos a usar um versão desktop do Windows para usar o TDS VS Code, ok?

**Comment by LandoaldoMSantos** [comment]
Muito obrigado lwtnb-wrk. A opção -N não funcionou para mim. Vou ver aqui para usar no desktop. Grato.
