### ISSUE TITLE
Debug não funciona - VSCode (versão 1.43)

### ISSUE THREAD

**Issue by rpinheirols** [totvs/tds-vscode#308]
Pessoal, Bom dia!!

Desde que meu debug do VSCode (versão 1.43) que tenho no meu laptop parou de abrir, eu tentei de tudo. Refiz o Launch, o Settings, desabilitei o plugin, removi, reinstalei.
Já **desistalei 4 vezes**, deletei arquivos como .totvsls, .vscode, deletei os arquivos temporários (TEMP) e mesmo assim ele não abre a janela do smartclient de jeito nenhum. 

Pode me ajudar ?

**Desktop** 
 - OS/Architecture: Windows 10 64 bits]

**Appserver** : P12.1.23
 - Build:  7.00.170117A-20190628 - 64 bits]
 - OS/Architecture: Windows 10 64 bits]

**Comment by lwtnb-wrk** [comment]
@rpinheirols Qual o sintoma observado? Voce inicia o Debug e ele apenas não responde?
No arquivo launch.json localize a configuração que você está usando e adicione a linha:
"logFile": "${workspaceFolder}\\dap.log"
e execute um debug.
Nos envie o arquivo "dap.log" gerado para analise.

**Comment by rpinheirols** [comment]
@lwtnb-wrk  Boa tarde!! Eu inicio o Debug e ele fica como se fosse esperando o SmartClient abrir.

Encontrei o arquivo launch e coloquei conforme voce mencionou. Segue arquivo Dap.log em anexo.

Grato

Ricardo
[daplog.log](https://github.com/totvs/tds-vscode/files/4320176/daplog.log)

**Comment by lwtnb-wrk** [comment]
@rpinheirols O seu problema é a acentuação existente no workspace (Área de Trabalho) que está usando. 
Experimente utilizar um caminho sem nenhuma acentuação e veja se isso resolve seu problema.

**Comment by rpinheirols** [comment]
@lwtnb-wrk , entendi. Agora removi workspace(Área de Trabalho) , porém ele continua o erro.

Como remover o "historico" do workspace anterior ?

Segue anexo o log

Arquivo:
[daplog.log](https://github.com/totvs/tds-vscode/files/4320560/daplog.log)

**Comment by lwtnb-wrk** [comment]
@rpinheirols Apesar de remover a pasta "Área de Trabalho" da lista de workspaceFolders, seu fonte ainda está na pasta "TNU" que está na "Área de Trabalho".
Altere essa localização também e veja se isso resolve seu problema.

**Comment by rpinheirols** [comment]
@lwtnb-wrk , está bem estranho. Meu fonte não está mais na área de trabalho.. Vou excluir os arquivos .totvsls, .vscode. e ver se vai surtir efeito.

**Comment by lwtnb-wrk** [comment]
@rpinheirols Pode ser que o breakpoint ainda esteja apontando para o fonte antigo... 
Remova os breakpoints que existem e crie novos breakpoints.

**Comment by rpinheirols** [comment]
@lwtnb-wrk , realmente era isso mesmo. Agora está funcionando. Muito obrigado pela ajuda!!
