### ISSUE TITLE
Watch

### ISSUE THREAD

**Issue by marjorietaki** [totvs/tds-vscode#31]
Ao incluir uma variável no watch durante o debug, em muitos momentos o watch trava não atualizando o valor da variável como impossibilitando que seja incluso ou excluso os conteúdos.

**Comment by ricardomansano** [comment]
@marjorietaki , boa tarde, poderia dizer se temos muitas variaveis no momento da trava? E os tipos: Ex: objetos, arrays, etc. 
Essa informação vai ajudar nos testes,
Grato

**Comment by marjorietaki** [comment]
@ricardomansano no momento só possuía uma variável numérica. Caso queiram verificar em algum momento me passe quem posso procurar, assim que ocorrer novamente chamo a pessoa para mostrar na minha maquina.

**Comment by ricardomansano** [comment]
@marjorietaki , agradeço o retorno, a duvida era se o problema podia ser devido à uma grande quantidade de variáveis, mas não é o caso, daremos seguimento à analise, grato

**Comment by ricardomansano** [comment]
@marjorietaki , bom dia, os meninos fizeram duzias de testes, e pegaram o comportamento "muito de vez em quando", tão poucas vezes que esta dificil até de definir se o problema esta na extensão ou se é um Bug do proprio VSCode.
Vc conseguiu alguma maneira (passo-a-passo), ou algum fonte especifico que o problema ocorra com facilidade pra gente trabalhar encima?

**Comment by marjorietaki** [comment]
@ricardomansano , infelizmente é isso mesmo. Este é um problema intermitente, tentei de algumas formas achar um padrão para a reprodução, mas não consegui achar uma regra. Mesmo porque com o mesmo fonte e debugando a mesma variável, ao fechar o vscode e abri-lo novamente o problema para de ocorrer.

**Comment by DanielYampolschi** [comment]
Ola @marjorietaki Encontramos uma forma de verificar o problema e uma possível causa. Fizemos alguns testes e a situação que tinhamos onde ocorria o problema com o watch parou de ocorrer. 
Essa correção vai sair já nessa próxima atualização. 
Após você atualizar, caso ainda ocorra o problema, pode reabrir essa issue ok? 
Muito obrigado.
