### ISSUE TITLE
Modelos de Configurações ADVPL JSON

### ISSUE THREAD

**Issue by carloseniemeyer** [totvs/tds-vscode#311]
Na extensão Oficial da TOTVS- tds-vscode existe documentação de parametrizações JSON - Modelos que podemos usar para configurar os workspaces e ambientes dos devs da forma que existe na extensão advpl-vscode?

https://github.com/totvs/advpl-vscode/wiki/Configura%C3%A7%C3%A3o

Um exemplo seria: Como filtrar os arquivos que não queremos remeter como resource no RPO e nem compilar.

**Comment by Wexlei** [comment]
Gostaria de complementar e sugerir que fossem documentadas as opções que temos disponíveis para utilizar no settings.json com a chave totvsLanguageServer. Na documentação existente aqui na página do git apenas três são mencionadas.

**Comment by lwtnb-wrk** [comment]
@carloseniemeyer Na proxima atualizacao disponibilizaremos uma configuração geral de extensões de arquivos permitidas para compilação (tambem utilizada na geracao de patch por pasta).
Se houverem outras features em outras extensões que acharem interessante, abra uma issue para cada descrevendo a funcionalidade.
