### ISSUE TITLE
Definir pasta a ser considerada no Debug | Arquivos duplicados

### ISSUE THREAD

**Issue by sandro-costa** [totvs/tds-vscode#314]
No TDS, caso eu possua fontes iguais em projetos diferentes, por meio da opção Source Lookup Path em Debug Configurations é possível definir qual projeto será considerado no Debug, para que a versão correta do fonte a ser debugado seja aberta.

Como realizo esta configuração no vscode? Pois tenho 2 projetos (Ex.: P11 e P12) no mesmo diretório, com fontes iguais e versões diferentes, e ao debugar determinado fonte existente em ambos os projetos, é aberto o fonte com a versão desatualizada, mesmo que o breakpoint esteja posicionado na versão correta.

**Comment by lwtnb-wrk** [comment]
@sandro-costa Realmente esta feature não existe atualmente no TDS VS Code, mas você pode resolver facilmente separando os projetos para que eles não causem essa confusão durante o Debug.
Se desejar implementar sua solução para resolver esta questão, submeta uma Pull Requeste que analisaremos e poderemos incorporar na extensão no futuro.
