### ISSUE TITLE
Compilação de Fontes !

### ISSUE THREAD

**Issue by JoelberGarcia** [totvs/tds-vscode#316]
Bom dia, estou com problemas na compilação de fontes no VS Code. Quando compilo ele fala que compilou porém na compilação do resultado gera a tela em anexo. 
![vscode](https://user-images.githubusercontent.com/61033874/76966880-647eb580-6905-11ea-9fc5-dbf1f4591d16.jpg)

**Comment by danielbolognani** [comment]
Bom dia, esse problema normalmente está relacionado com os includes, verifique sua pasta de includes, algum deve estar faltando. Pegue a pasta de includes com alguém que tem ela completa.
A mensagem de erro não está sendo exibida corretamente mas será corrigido nas próximas versões.

**Comment by lwtnb-wrk** [comment]
@JoelberGarcia Tivemos relatos de problemas ocasionados por atualizações de versão do VS Code que causam a seleção de um arquivo .CH durante a seleção do diretório de includes no cadastro de servidores.
Como o @danielbolognani informou certifique-se de que a pasta de includes é realmente o diretório de includes correto. Se estiver configurado com um arquivo .CH remova esse arquivo mantendo apenas o diretório.

**Comment by JoelberGarcia** [comment]
Boa tarde, existe algo a mais a ser feito, pois mesmo já exclui e crie novamente a configuração do include no server tanto local quanto no servidor e não funcionou. Continuo compilando  e a alteração não é compilada.

**Comment by JoelberGarcia** [comment]
[compilar.zip](https://github.com/totvs/tds-vscode/files/4350222/compilar.zip)

**Comment by lwtnb-wrk** [comment]
@JoelberGarcia A configuração de include deve informar o diretório onde os arquivos .chs necessários para a compilação estão.
No vídeo é possível ver que você tem o diretório de includes apontando para um arquivo.
Ajuste esta configuração e veja se resolve seu problema.

**Comment by JoelberGarcia** [comment]
@lwtnb-wrk  eu verifiquei aqui depois e apontei conforme img, porém sem sucesso.
![vscode_I](https://user-images.githubusercontent.com/61033874/76988551-a3236880-6923-11ea-90af-d3885530754b.JPG)

**Comment by marcelipe** [comment]
Foi aberta uma discussão no [Fórum](https://devforum.totvs.com.br/1312-compilacao-vscode), respondi o pessoal lá. Acredito que seja um Bug mesmo no VsCode que deve ser corrigido, por hora a solução que apresentei lá tem atendido a mim e meus colegas.

**Comment by PedreirasBahia** [comment]
Olá Marcelipe,

Passei pelo mesmo problema.

Edite o servers.json. apague o arquivo para o qual está apontando deixando apenas apontado para a pasta.

Observe se há outras linhas apontando para o arquivo. Ajuste para apontar apenas para a pasta.

Acredito que em atualizações futuras, isso possa ser resolvido, pois ao apontar a pasta de includes, o sistema grava o primeiro arquivo da pasta gerando o erro.

**Comment by JoelberGarcia** [comment]
@marcelipe @PedreirasBahia funcionou editando o servers.json em alguns servidores ele estava colocando apenas um include e não a pasta.

Obrigado !

**Comment by lwtnb-wrk** [comment]
Somente complementando as informações referente a este problema, ele foi causado por uma atualização do VS Code que alterou o comportamento do componente de seleção de diretórios.
Estamos revendo os pontos onde selecionamos diretórios para que este problema não ocorra mais.
Grato a todo.
