### ISSUE TITLE
Gerar patch

### ISSUE THREAD

**Issue by rodstephanel** [totvs/tds-vscode#317]
Bom dia Pessoal,
Tive problemas para gerar patch, quando usado a opção 'Patch Generation (From RPO)', no momento em que vou selecionar o diretório para gerar o patch, ele seleciona um arquivo aleatório que contenha neste diretório (imagem). Com isso não gera o patch e não acusa erro também.
Como medida estou apagando o nome do arquivo selecionado.
![issue](https://user-images.githubusercontent.com/31445805/77072279-37490a80-69cc-11ea-8ff3-51559f19fc3c.JPG)

**Comment by lwtnb-wrk** [comment]
@rodstephanel Esse problema começou com uma das últimas atualizações do VS Code.
É um problema que está afetando todos os processos que necessitem a seleção de um diretório.
Faremos os ajustes necessários porém por enquanto o procedimento é este mesmo, apagar manualmente o arquivo, após a seleção do diretório, mantendo apenas a parte do diretório selecionado.
Grato por reportar este caso.
