### ISSUE TITLE
precompiled with warnings and/or errors.

### ISSUE THREAD

**Issue by JulianoCDorneles** [totvs/tds-vscode#318]
**Describe the bug**
Ao tentar compilar um fonte pelo VSCode utilizando o Plugin está apresentando erro e não compilando o fonte. As outras opções e funcionalidade estão funcionando normalmente.

![image](https://user-images.githubusercontent.com/52940967/77111717-93c91b80-6a06-11ea-90db-e3e8984d257f.png)

**Servidor remoto"

**Desktop :**
 - OS/Architecture: [e.g. Windows 10 PRO 64 bits]

**Appserver :**Dados do Server 

Versão: TOTVS Agroindustria
Build AppServer: 7.00.170117A-20191024 - 64 bits
Appserver version: 17.3.0.16
Build DBAccess: 20181212-20190924
Release do RPO:  12.1.025
Release do dicionário: 12.1.025
Local files: CTREE
License server: 2014 - 2.3.11
DB DataBase: ORACLE
DB API Build: 20181212-20190724

**Additional context**

VSCode Versão:
Version: 1.43.0 (user setup)
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by lwtnb-wrk** [comment]
@JulianoCDorneles Realmente existe um problema que será corrigido na próxima atualização pois alguns erros gerados pelo Appre estavam sendo marcados na linha 0 (zero) que não existe e portando não aparecia na visão Problems.
Normalmente esse erro está relacionado a problemas de configuração de Includes, reveja as configurações de Includes em seu servers.json.
Um problema recentemente introduzido por uma atualização do VS Code faz com que a seleção de diretórios, selecione um arquivo deste diretório ao invés do próprio diretorio. Logo, verifique se em seus Includes não está configurado um arquivo (normalmente .ch) ao inves do diretorio e se necessario ajuste esta informação.

**Comment by JulianoCDorneles** [comment]
O Vscode tinha uma atualização para ser executada, ficando na seguinte versão:


Version: 1.43.1 (user setup)
Commit: fe22a9645b44368865c0ba92e2fb881ff1afce94
Date: 2020-03-18T07:01:20.184Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763


Analisando o arquivo servers.json foram realizados os seguintes ajustes:


--No início do arquivo estava:

{
	"version": "0.2.0",
	"includes": [
	""
	],

--Ajustado para:

{
	"version": "0.2.0",
	"includes": [
		"C:\\protheus\\include\\"
	],

--Na seção do ambiente:


"includes": [
	"C:\\protheus\\include\\A020DELE.CH"
			],

--Ajustado para:
"includes": [
	"C:\\protheus\\include\\"
			],

--
Após os ajustes foi possível compilar.

**Comment by JulianoCDorneles** [comment]
Funcionando agora :), obrigado!

![image](https://user-images.githubusercontent.com/52940967/77201497-55e1fb00-6acb-11ea-9c29-29d27e580427.png)
