### ISSUE TITLE
Não executa o smartclient pelo VS Code

### ISSUE THREAD

**Issue by marcoswa** [totvs/tds-vscode#319]
Estou tentando debugar a partir do VS Code, porém o smartclient não é executado.

Se eu executo o mesmo diretamente ele abre sem problemas.

- Já verifiquei senão havia nenhum processo preso do smartclient.
- Reiniciei o VS Code
- Verifiquei o caminho do smartclient no lauch.json e está correto.

Alguém tem alguma ideia do que pode ser?

Obrigado.

**Comment by marcelipe** [comment]
Boa Tarde!
Isso acontece geralmente quando você alterna entre versões diferentes de smarclient.

Por exemplo está executando um SC da versão 23 e depois quer executar um da 25. Se for o caso bastar limpar a pasta *temp*.

Utilize o comando "Windows + R";
digite %TEMP% e exclua todo o conteúdo da pasta;
após isso é só executar o SC que deseja. 
_Obs.: Sempre que alterno entre Smarts eu faço isso._

**Comment by marcoswa** [comment]
Tentei e não funcionou. 

Um detalhe, faz algum tempo que estou trabalhando apenas com o mesmo smartclient, da 25.

**Comment by marcoswa** [comment]
Pessoal, era algum problema na minha Workspace, criei uma nova e executou o SC perfeitamente.
