### ISSUE TITLE
Adicionas ambientes

### ISSUE THREAD

**Issue by Evertonpx** [totvs/tds-vscode#32]
Adicionar mais de um ambiente ao servidor

**Comment by ricardomansano** [comment]
@Evertonpx , boa tarde, como vc imaginou essa implementação (usabilidade) ? Hoje apenas exibimos um campo para preenchimento do nome dos ambiente/user/senha na camada superior. Foi feito assim na intenção de acelerar/simplificar a conexão.

**Comment by Vitor-Santos-Totvs** [comment]
@Evertonpx Você pode cadastra o mesmo servidor novamente mas com outro ambiente. Como fica memorizado o ambiente que você conseguiu fazer a conexão no servidor, dá pra deixar cada versão do mesmo servidor com um ambiente.
![image](https://user-images.githubusercontent.com/50745570/58184054-c12e2700-7c86-11e9-9723-2a49d1aaa458.png)

**Comment by Evertonpx** [comment]
Ok ... Obrigado
