### ISSUE TITLE
Configurando novo server e seleccionando pasta Includes trae arquivo .ch

### ISSUE THREAD

**Issue by AleksSyntek** [totvs/tds-vscode#320]
Boa noite, recentemente tuve um erro que nao deixaba compilar é nao detectaba erros do codificacao no fontes, devido que ao incluir um novo servidor no VS já existente o em una nova instalacao do VSCode + plugin TDS configurando un novo server, em lugar de trazer só a pasta include, adiciona tambén ao path o primer arquivo .ch que pesquisa.

A solucao para esse erro é quitar o nome do arquivo do path, mais si o desenvolvedor nao presta atencao no momento do carregamento do path da pasta include, pode incurrir no erro.

Acho que pode houver algum issue com o path retronado pela funcao do botao [seleccionar arquivos] que retorna o dado do path con arquivo (mais só devería retornar até caracter da barra do pasta).

**To Reproduce**
1. Ir ao vista do servidores TOTVS
2. CIicar no "+" para adicionar novo servidor
3. Preencher os dados do server (opcional)
4. Clicar botao do seleccionar arquivo na secao "Includes directory"
5. Olhar que o camino da pasta include adiciona o arquivo .ch ao final ej: D:\Devstudio\DEV\Include\ap5mail.ch
6. Apos do isso tente alterar um fonte quitando por exemplo uma asignacao do variável ex: 
`Local dDataTest := dDatabase` para `Local dDataTest  dDatabase`
7. Compile o fonte com Ctrl+F9
8. Avalie que nao va ter mensagem do erro do sintaxe, mais tampoco compila

Opcional

9. Quite o nome do arquivo do path do include no servers.json e tente comppilar novamente.

**Expected behavior**
Devería verificar-se que ao momento da compilacao se emita um erro do path do include incorreto, ou avaliar que a sintaxe esta errada antes da compilar (acho que quiza nao seja possivel como é lancada a precompilacao)

**Screenshots**
![imagen](https://user-images.githubusercontent.com/30332762/77219956-72a51f80-6b19-11ea-80b4-db73eeaedb01.png)

**Desktop (please complete the following information):**
 - OS/Architecture: Windows 10 pro 64 bits
 - VSCode 1.43.1 64 bits
 - TDS for VSCode 0.3.23
 
**Appserver (please complete the following information):**
 - Build (with date): Build 7.00.191205P-20200220 - 64 bits - 20 Fev 2020]
 - OS/Architecture: Windows Server 2012 R2
 - Build Version: 19.3.0.2

**Additional context**
Erro detectado tambén no DevForum: [https://devforum.totvs.com.br/1312-compilacao-vscode](url)

**Comment by lwtnb-wrk** [comment]
@AleksSyntek Grato pela informacao, ja estamos corrigindo essa questao que foi introduzida apos atualizacao do VS Code. O comportamento do componente foi alterado e causou este problema em nossa extensao.

**Comment by lwtnb-wrk** [comment]
@AleksSyntek acompanhar pelo #317
