### ISSUE TITLE
Builde de fonte apresenta problema mas não quais.

### ISSUE THREAD

**Issue by sipmann** [totvs/tds-vscode#321]
Olá, Estou tentando compilar um fonte mas o mesmo não atualiza no RPO. Tenho as mensagens que podem ser vistas no print mas não aparece nada no Problems. Altero informação, coloco conout mas nada faz atualizar a data do fonte no RPO.

Remote build: 7.00.170117A-20200211
Remote version: 17.3.0.13
Remote type: 1 - QT-5.9.7 WIN
Build AppServer: 7.00.170117A-20200102 - 64 bits
Appserver version: 17.3.0.18
Build DBAccess: 20181212-20191121
Release do RPO:  12.1.025

![image](https://user-images.githubusercontent.com/545754/77316082-17bd2500-6cdf-11ea-8c08-4d983ba06c90.png)

**Comment by lwtnb-wrk** [comment]
@sipmann Faz parte do problema #270 e sera corrigido em breve
