### ISSUE TITLE
Compilação não mostra o conteúdo do Erro

### ISSUE THREAD

**Issue by felipe-brainbox** [totvs/tds-vscode#322]
Pessoal, estou utilizando o VSCODE e simplesmente não consigo identificar porque o sistema está dando erro em um arquivo funcional e em uso.
Segue a tela da compilação:
![image](https://user-images.githubusercontent.com/53801561/77369547-a3659e80-6d3d-11ea-8d96-4478e3b87bf5.png)
Como resolvo isso e como ver qual exatamente é o error/warning?

**Comment by lwtnb-wrk** [comment]
@felipe-brainbox corrigida na versao 1.0.1
