### ISSUE TITLE
Simplesmente não está compilando mais.

### ISSUE THREAD

**Issue by PatrickZerbinatti** [totvs/tds-vscode#324]
De ontem para hoje parou de funcionar a compilação.
Log:
[Info  - 12:56:30] Starting recompile.
[Log   - 00:00:00] Starting build for environment desenvolvimento.
[Log   - 00:00:00] Aborting end build (rollback changes).

**Comment by lwtnb-wrk** [comment]
@PatrickZerbinatti Voce atualizou a extensao para a versao 1.0.1?
Se afirmativo experimente desabilitar o uso do token de reconexão (Settings > Extensions > AdvPL > Use Reconnection Token) e veja se resolve o problema.

**Comment by PatrickZerbinatti** [comment]
Não resolveu. Esta atualizado sim.

**Comment by PatrickZerbinatti** [comment]
Um colega de equipe não atualizou ainda e para ele esta compilando normalmente.

**Comment by lwtnb-wrk** [comment]
@PatrickZerbinatti Adicione as linhas:
    "totvsLanguageServer.launch.args": [
        "--log-file=totvsls.log",
        "--record=totvsls"
    ],
No arquivo settings.json, reinicie o TDS VS Coded e repita a operação que deu problema.
Um arquivo "totvsls.log" deve ser gerado na raiz de seu projeto.
Nos envie esse arquivo para que possamos analisa-lo.

**Comment by PatrickZerbinatti** [comment]
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/4386773/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/4386774/totvsls_out.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/4386775/totvsls.log)

**Comment by lwtnb-wrk** [comment]
@PatrickZerbinatti Existe algum problema com os includes que estão sendo utilizados nesta compilação. Reveja os includes utilizados que devem apontar para os diretórios onde se encontram os arquivos .CHs necessários.
Estou analisando o porque da falha na exibição de uma mensagem de erro apropriada.
Grato pelos logs.

**Comment by PatrickZerbinatti** [comment]
[totvsls.log](https://github.com/totvs/tds-vscode/files/4387274/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/4387275/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/4387276/totvsls_out.log)

Atualizei as includes conforme o site da TOTVS e ainda ta dando erro. Lendo o Log eu vi que ele aborta depois de tentar achar o PRTOPDEF.ch, porem este include esta na pasta. Olhando a configuração do server, ta apontando corretamente para o driver S, onde estão nossos includes.

**Comment by lwtnb-wrk** [comment]
@PatrickZerbinatti Nos logs enviado acima não existe nenhuma indicação de que houve uma tentativa de compilação. Você anexous os logs corretos?
Temos duas configurações de includes, uma por servidor e outra geral que estão definidas no arquivo servers.json. Se na configurações do servidor utilizado existir a informação de includes, elas serão utilizadas. Caso contrário ele utilizará as configurações gerais de includes.
Se quiser anexe o servers.json que esta na pasta ".totvsls" que existe na sua pasta de usuario.

**Comment by PatrickZerbinatti** [comment]
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/4387972/totvsls_out.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/4387973/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/4387974/totvsls_in.log)
[servers.zip](https://github.com/totvs/tds-vscode/files/4387981/servers.zip)

Ai esta.

**Comment by lwtnb-wrk** [comment]
@PatrickZerbinatti Grato pelos logs. Notei que os arquivos .ch estão localizados diretamente no drive S: e não existe uma pasta , como por exemplo, "includes" neste drive.
Crie um pasta "includes" e mova os arquivos .ch para esta pasta e atualize as configurações de include apontando para "S:\\includes", ou com o nome que desejar.
Vamos avaliar e corrigir este cenário onde os includes estão diretamente na raíz do drive ao inves de em uma pasta.
Grato

**Comment by PatrickZerbinatti** [comment]
Na verdade o mapeando S é direto na pasta include, então criei a pasta "new", pois ja temos a "old" com os includes anteriores. Mas enfim, adicionei a pasta, mudei o direcionamento e funcionou. Obrigadão!
