### ISSUE TITLE
Versão 1.0.1 não efetua autenticação de usuário do servidor

### ISSUE THREAD

**Issue by Wexlei** [totvs/tds-vscode#325]
Após atualizar o plugin para a versão 1.01, não é mais possível compilar, apresentando inicialmente o seguinte erro:

> user must be logged in before compile

Excluí o servidor da lista e adicionei novamente, porém sem sucesso, desta vez apresentava a seguinte mensagem:

> Retrieve connection error: Connection is not authenticated but requires authentication.

Após verificar o arquivo servers.json, observei que o campo username estava com usuário igual a 'nouser', mesmo substituindo para o nome do usuário admin, o erro persistia. Cabe lembrar que, ao adicionar o server novamente, não foi solicitado usuário e senha para login, como ocorria nas versões anteriores do plugin.

Voltando o plugin para a versão anterior, foi possível adicionar o servidor normalmente, onde solicitou usuário e senha e permitiu compilar.
Este mesmo problema foi reproduzido em outras máquinas da NG.

**Versões:**
VsCode: 1.43.2
SO: Windows 10 Pro (6.2.9200)
Totvs Developer Studio for VSCode: 1.0.1
DBAccess: 20191119-20191206

**Appserver**
Build 7.00.191205P - Jan 24 2020 - 00:47:15
Build: 64 bits
SVN Revision: 25876
Build Version: 19.3.0.1_RC10

**Comment by lwtnb-wrk** [comment]
@Wexlei Utilize o AppServer oficial do portal. Esta versão RC10 não oficial tem bugs que foram corrigidas nas versões posteriores. Sempre utilize as últimas versões para evitar estes problemas.
