### ISSUE TITLE
Ao conectar em um ambiente com nome "compile" o vscode conecta com "NOUSER"

### ISSUE THREAD

**Issue by luizhj** [totvs/tds-vscode#327]
Ao conectar em um ambiente com nome "compile" o vscode conecta com "NOUSER", sem usuário e senha impedindo de compilar os fontes.

Trocado o nome do ambiente para comp1 e o tds solicitou usuário e senha normalmente.

vscode 1.43.2
tds 1.0.1

**Comment by lwtnb-wrk** [comment]
@luizhj Provavelmente o token de reconexão está com uma informação errada e por isso não pede usuário e senha. Ao trocar o nome do ambiente o token associado a este novo ambiente não existia e não continha a informação incorreta.
Experimente desabilitar a opção "Use reconnection token" em seu Settings e veja se ele pede o usuário e senha, pois não usará o token incorreto.

**Comment by luizhj** [comment]
não foi o caso.

tinha acabado de instalar o vscode no servidor do cliente, configurei o ambiente de teste e produção.
pra simular o caso do cliente eu mandei conectar no outro ambiente (q não tinha tido conexão antes) com nome Compile.

Exclui a conexão, criei novamente e ao conectar direto no ambiente compile não pediu usuário e senha e conectou direto com "nouser".

renomeei o ambiente no appserver para comp1 exclui a conexão e criei novamente no vscode e ao mandar conectar ele pediu usuário e senha.

**Comment by lwtnb-wrk** [comment]
@luizhj Qual o AppServer que voce esta utilizando? A versão exata e data da build?
O que voce quer dizer com excluir a conexão? Está apagando o servidor e cadastrando novamente ou está desconectando e conectando novamente?
Chegou a testar com a opção "Use reconnection token" desabilitada?

**Comment by luizhj** [comment]
sim, quando digo excluir a conexão eu realmente excluía o perfil de conexão do vscode pela extensão do tds (não excluia nem pelo server configuration).

![image](https://user-images.githubusercontent.com/16191002/78257791-b829fb00-74d0-11ea-9a92-3bbea8e29bd0.png)

**Comment by lwtnb-wrk** [comment]
@luizhj Atualize seu AppServer. Você está com uma versão super desatualizada. Pegue a versão oficial do Portal, refaça as exclusões das conexões e teste novamente.

**Comment by luizhj** [comment]
sério?
o ambiente foi virado da 12.1.17 pra 12.1.27 semana passada (não fui eu q fiz). :facepalm:
