### ISSUE TITLE
User Not Authenticated. Please Connect/Reconnect to a Server

### ISSUE THREAD

**Issue by ferreiraregis** [totvs/tds-vscode#328]
Bom dia

Ao tentar debuggar, está apresentando a mesangem em anexo.
Reinstalei o VScode, reinstalei o plugin to Totvs Developer for VsCode, voltei a versão mais antiga do plugin (0.3.23).
Excluir e refiz meu servers.json e também o launch.json, fiz manual e pelo configure.
Conecto no server normalmente, aplico patch, compilo, mas não abre o debug
![vscode](https://user-images.githubusercontent.com/52089310/78024624-115a2900-732f-11ea-8c00-e90552e51b6b.PNG)

**Comment by lwtnb-wrk** [comment]
@ferreiraregis Experimente renomear a pasta ".totvsls" que existe na sua pasta de usuário.
Você terá que cadastrar novamente os servidores, mas acredito que isso deva resolver o problema.

**Comment by ferreiraregis** [comment]
Boa Noite @lwtnb-wrk 
Fiz o seguinte procedimento
Desinstalei o plugin
Desinstalei o VSCode
Apaguei a pasta .Totvsls
Apaguei a pasta .vscode
Reinstalei tudo
Criei uma nova WorkSpace, um novo server.json, um novo launch.json
Consegui compilar, apliquei patch, mas continuo a não conseguir debugar

To pensando em formatar

**Comment by lwtnb-wrk** [comment]
@ferreiraregis Antes de formatar você pode tentar reinstalar o VS Code novamente, mas desta vez apos a desinstalação do VS Code, localize e apague a pasta 
C:\Users\<seu_usuario>\AppData\Roaming\Code
Temos relatos de que, mesmo com uma reinstalação o VS Code continua apresentando comportamentos pois esta pasta mantem arquivos que não são removidos na desinstalação.
Talvez com isso o VS Code retornará ao padrão de instalação zerada.

**Comment by ferreiraregis** [comment]
Bom dia @lwtnb-wrk 
Ele voltou ao padrão, pois antigamente ele trazia os fontes abertos recentemente.
Fiz o procedimento porém o problema persiste, não sei se teria outra coisa pra fazer antes de formatar
Detalhe que eu tinha instalado um plugin não oficial da Totvs a um tempo atrás, mas já desinstalei, porém não sei se fica algum rastro em outro lugar

**Comment by ferreiraregis** [comment]
OBrigado pela @lwtnb-wrk 
O problema está no usuário da minha máquina, o usuário tinha um acento no nome, após criar outro usuário sem acento, o problema foi resolvido.
