### ISSUE TITLE
Lentidão ao encerrar o debug

### ISSUE THREAD

**Issue by delsonfilho** [totvs/tds-vscode#33]
Prezados,

Ao encerrar o debug no meio da execução quando o breakpoint está ativo, a IDE demora a encerrar o processo.

No antigo plugin era imediato.

**Comment by DanielYampolschi** [comment]
Ola Delson, Voce pode dar mais detalhes por favor? Tentamos reproduzir por aqui e o encerramento do debug ocorreu normalmente.
Consegue dar uma idéia, em segundos, do quanto esta levando para encerrar? 
Voce esta usando debug com  multiplas threads?
Obrigado.

**Comment by delsonfilho** [comment]
@DanielYampolschi demorou mais de 20 seg, e hoje já ocorreu umas 2x de ter que fechar o vscode para cair o debug.
o debug está marcado para multithreads.

**Comment by DanielYampolschi** [comment]
Ola @delsonfilho voce pode atualizar seu plugin do tds-vscode e informar se o problema ainda ocorre por favor? Obrigado.

**Comment by delsonfilho** [comment]
olá @DanielYampolschi, aparentemente parou de travar.

**Comment by lwtnb-wrk** [comment]
@delsonfilho Estamos fechando essa issue entao. Se precisar abra uma nova issue como reproduzir o problema e voltaremos a analisar. Grato por testar e reportar problemas.
