### ISSUE TITLE
Versão 1.0.1 troca usuário para 'nouser' e não permite autenticação e compilação

### ISSUE THREAD

**Issue by raquelhager** [totvs/tds-vscode#331]
Boa tarde!

Gostaria de reportar um incidente que vem ocorrendo comigo e outros colegas:

Ao utilizar a versão do Vs Code 1.0.1 percebi que ele está alterando o meu usuário no arquivo servers.json para 'no user' conforme imagem:

![image](https://user-images.githubusercontent.com/55213765/78070846-dc6fc580-7372-11ea-9dd7-60d5ae609f54.png)

Ao tentar compilar é exibida a seguinte mensagem:
![image](https://user-images.githubusercontent.com/55213765/78070874-e8f41e00-7372-11ea-89dd-a99d3c16619a.png)

Realizei o seguinte teste:
- Limpei todo o conteúdo da tag 'saved tokens' no arquivo .servers.json e desmarquei a opção 'Use reconnection token to login' em File > Preferences > Settings,
- Reiniciei o Vs Code,
- Removi todos os servidores cadastrados,
- Cadastrei um novo servidor.

Ao tentar conectar foi exibida a mensagem:
![image](https://user-images.githubusercontent.com/55213765/78071070-340e3100-7373-11ea-9064-49770b2a0c2d.png)

Ao autenticar, é exibido o usuário 'nouser' como default:
![image](https://user-images.githubusercontent.com/55213765/78071096-41c3b680-7373-11ea-94cd-9df12ba72164.png)

Mesmo que eu altere manualmente para 'admin', o resultado é o mesmo.

Estou utilizando a versão 0.3.23 desde então pois este incidente fica se repetindo.

Dados do ambiente:
RPO D-1 12.1.23
https://arte.engpro.totvs.com.br/protheus/padrao/builds/12.1.23/latest/repositorio/lobo_guara/   

appserver-17.3.0.18-winx64
TOTVS - Build 7.00.170117A - Jan  2 2020 - 14:57:42https://arte.engpro.totvs.com.br/tec/appserver/lobo_guara/windows/64/latest/

**Comment by lwtnb-wrk** [comment]
@raquelhager Foi a descrição mais bem detalhada que já vi das mais de 330 issues que recebemos até hoje!! rsrsrs
Enfim tivemos relatos desse problema e até então não tínhamos esses detalhes, mas infelizmente ainda assim não consegui reproduzir o problema...
Peguei a mesmas versões de RPO e AppServer do Arte, mas consegui me conectar e me logar sem problemas.
Você chegou a aplicar algum patch neste RPO ou falha a conexão desde o primeiro acesso a este RPO?
Se já aplicou algum patch, poderia testar com um RPO zerado e ver se o problema ocorre desde o primeiro login?
E se possível no envie o console.log do AppServer para analisarmos.
Grato

**Comment by PatrickZerbinatti** [comment]
[totvsls.log](https://github.com/totvs/tds-vscode/files/4416275/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/4416276/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/4416277/totvsls_out.log)

Só pra tentar ajudar, no meu esta dando exatamente isso, gerei um log como voce me ensinou outro dia. Gerei com a opção "Use Reconnection Token" desativada, porem mesmo assim ele nem me pede meu usuario e senha.

segue meu server, eu até apaguei o antigo para ver se resolvia, mas nada.
[servers.txt](https://github.com/totvs/tds-vscode/files/4416290/servers.txt)

**Comment by lwtnb-wrk** [comment]
@PatrickZerbinatti Acho que seu problema deve ser outro pois pelo log aparentemente voce ainda nao atualizou sua extensao para a versao 1.0.1

**Comment by PatrickZerbinatti** [comment]
@lwtnb-wrk não, é um RPO cheio de customizações. Será que por conta do problema de conexão ele não ta achando que o RPO ta vazio? Por que sinceramente ele nem deve estar conectando corretamente. Mesmo eu recriando o server ele nao me pediu senha nenhuma vez.

**Comment by raquelhager** [comment]
Boa tarde,

Fico feliz em saber que o detalhamento ajuda! =D

@lwtnb-wrk , em todas as vezes que foi exibida essa mensagem meu rpo não havia sofrido nenhuma aplicação de path, nos prints em questão e nas demais ocasiões eu estava compilando sempre os mesmos fontes - era num momento aleatório do dia.

Procuro não atualizar para a nova versão pois interrompe demais a minha produtividade, vou atualizar e tentar simular esse erro para enviar o console.log!

**Comment by lwtnb-wrk** [comment]
@raquelhager Perguntei sobre os patches pois aparentemente o retorno da função PSWADMIN esta com problema neste seu RPO. Grato pelas informacoes

**Comment by lwtnb-wrk** [comment]
@PatrickZerbinatti Realmente me pareceu estranho pois a contagem de programas esta zerada no RPO e por isso não esta pedindo usuário e senha. Qual o motivo do uso desse RPO que não é padrão?

**Comment by PatrickZerbinatti** [comment]
Nossa... que coisa mais esquisita, meu RPO estava com 0 kb. Bom resolveu meu problema, peguei um RPO de backup que estava normal.

**Comment by raquelhager** [comment]
@lwtnb-wrk um colega da minha equipe também sofreu do mesmo problema e conseguiu o console.log para nós.

Só que ele está com a lib mais atualizada do LG-19 pelo oq eu pude observar.

Segue arquivo em anexo.
[console.log](https://github.com/totvs/tds-vscode/files/4421530/console.log)

**Comment by lwtnb-wrk** [comment]
@raquelhager Seus colegas ainda estao com algum problema de autenticacao?
Se algum deles ainda estiver com problema, peça para ver https://github.com/totvs/tds-vscode/blob/dev/TROUBLESHOOTING.md e enviar novas informacoes e logs.
E se precisar reabra esta Issue ou crie uma nova se for outro problema
