### ISSUE TITLE
Erro ao tentar conectar ao servidor

### ISSUE THREAD

**Issue by knsuper** [totvs/tds-vscode#332]
Acabei de instalar o plugin para Vscode, adicionei um servidor e quando tento conectar dá o erro:
Error running command totvs-developer-studio.connect: Running the contributed command: 'totvs-developer-studio.connect' failed.. This is likely caused by the extension that contributes totvs-developer-studio.connect.

Segue o arquivo servers.json:
{
	"version": "0.2.0",
	"includes": [
		"D:\\Protheus12\\Includes"
	],
	"permissions": {
		"authorizationtoken": ""
	},
	"connectedServer": {},
	"configurations": [
		{
			"id": "a5nfuccuu07k6uz7ggx2pvwmtuikln",
			"type": "totvs_server_protheus",
			"name": "CLIENTE 1",
			"port": 4600,
			"address": "10.125.3.85",
			"buildVersion": "",
			"secure": 0,
			"includes": [
				"D:\\Protheus12\\Includes"
			]
		},
		{
			"id": "zxpyslbps7k8hetnjbizc9imt1h0b",
			"type": "totvs_server_protheus",
			"name": "CLIENTE 2",
			"port": 6000,
			"address": "fixcomercio108538.protheus.cloudtotvs.com.br",
			"buildVersion": "",
			"secure": 0,
			"includes": [
				"D:\\Protheus12\\Includes"
			]
		}
	]
}

**Comment by lwtnb-wrk** [comment]
@knsuper Pelo menos a extensão tds-vscode deve estar inicializando corretamento, certo?
De qualquer forma adicione as linhas:
"totvsLanguageServer.launch.args": [
"--log-file=totvsls.log",
"--record=totvsls"
],
em seu settings.json (ajustando eventualmente a virgula)
Reinicie seu TDS VS Code e repita a operação.
No envie os arquivos de log gerados na raiz do projeto aberto.

**Comment by saldanha85** [comment]
Estou com o mesmo problema. Onde fica o settings.json ?

**Comment by saldanha85** [comment]
Achei o settings json dentro do workspace. e deixei conforme abaixo, mas o erro permanece
{
    "totvsLanguageServer.launch.args": [
        "--log-file=totvsls.log",
        "--record=totvsls"
        ],


    "files.encoding": "iso88591"
   
}

**Comment by saldanha85** [comment]
Observação. Em minha máquina que utilizei o user installer não tive problema. Agora estou tentando utilizar o system installer no servidor.

**Comment by lwtnb-wrk** [comment]
@saldanha85 Qual o SO do TDS VS Code que esta dando problema e em qual SO funcionou sem problemas?
Os procedimentos de adicionar as linhas no settings são para habilitar o log para verificar algumas informações a fim de descobrir o que tem de errado apenas...

**Comment by saldanha85** [comment]
Bom dia.

Em minha máquina local que deu certo, utilizo o windows 10, e a instalação foi a User Installer 64 bit.

No servidor que está dando problema, utilizamos o windows server 2012 R2, e a instalação foi a system installer 64 bit.


________________________________
De: lwtnb-wrk <notifications@github.com>
Enviado: segunda-feira, 6 de abril de 2020 09:10
Para: totvs/tds-vscode <tds-vscode@noreply.github.com>
Cc: saldanha85 <ras_rsaldanha@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [totvs/tds-vscode] Erro ao tentar conectar ao servidor (#332)


@saldanha85<https://github.com/saldanha85> Qual o SO do TDS VS Code que esta dando problema e em qual SO funcionou sem problemas?
Os procedimentos de adicionar as linhas no settings são para habilitar o log para verificar algumas informações a fim de descobrir o que tem de errado apenas...

**Comment by lwtnb-wrk** [comment]
@saldanha85 Realmente não recomendamos o uso do TDS VS Code em SO voltados para servidores, pois já tivemos relatos de problemas em seu uso. Provavelmente nos SO Server faltam biblitecas (DLLs) que existem nos SO padrão e por isso ocorrem os problemas em seu uso.

**Comment by lwtnb-wrk** [comment]
@knsuper O SO que esta ocorrendo o problema é do tipo Windows Server como o do @saldanha85 ?
