### ISSUE TITLE
Plugin 1.0.1 sumiu a opção "Secure (SSL)"

### ISSUE THREAD

**Issue by alissonph** [totvs/tds-vscode#333]
Descrição:
A versão do plugin 1.0.1 sumiu a opção "Secure (SSL)" ao adicionar um novo servidor. Então não estou conseguindo conectar a Protheus 12.1.27 que tenha SSL habilitado. Ao voltar para a versão 0.3.23 a opção "Secure (SSL)" volta a ser exibida.

Para reproduzir:
Tentar adicionar um novo servidor

Sistema Operacional:
Windows 10 64 bits

Appserver:
 - Build (with date): 7.00.191205P-20200220
 - OS/Architecture: Windows Server 64 bits
 - Build Version 19.3.0.2

**Comment by lwtnb-wrk** [comment]
@alissonph Removemos a opção mesmo pois parecia mais confundir os usuarios do que ajudar.
O processo passou a auto-detectar as configuracoes de versao de build e configuracao de SSL do Appserver no cadastro.
Se o cadastro foi realizado antes realmente pode ter havido um problema na conversao, mas bastaria desabilitar a opcao "Use reconnection token" no Settings do TDS VS Code, que a conexão deveria ser recriada corretamente.
Note tambem que no cadastro de um novo servidor a partir da 1.0.1 a informacao de secure no arquivo servers.json deve exibir a do AppServer no momento do cadastro.
Enfim teste estes cenarios e nos informe se conseguiu se conectar.
Grato

**Comment by alissonph** [comment]
Consegui conectar normalmente, acho que foi um erro pontual.
