### ISSUE TITLE
Erro ao compilar fontes em aberto (.app junto)

### ISSUE THREAD

**Issue by alissonph** [totvs/tds-vscode#334]
Descrição:
Vi que já foi corrigido o bug de compilar os fontes em aberto na versão do plugin 1.0.1, porém se eu tiver um arquivo .app (portinari) aberto para tentar compilar junto ele não compila todos os arquivos em aberto.

Para reproduzir:
1- Abra vários arquivos .prw e um arquivo .app
2- Tente compilar os fontes em aberto (CTRL + F10)

Sistema Operacional:
Windows 10 64 Bits

Appserver:
 - Build (with date): 7.00.170117A-20190628 - 64 bits
 - OS/Architecture: Windows 10 64 Bits
 - Build Version: 17.3.0.13

**Comment by lwtnb-wrk** [comment]
@alissonph O arquivo tem extensão .app, como em teste.app, ou é somente ".app"
Este arquivo precisa ser compilado como resource no RPO?

**Comment by alissonph** [comment]
É um arquivo com extensão .app. Ex: aplicativo.app

Precisa ser compilado no RPO sim, seguindo essa documentação para rodar aplicativos em Angular/Portinari dentro do Protheus:
https://tdn.totvs.com/display/public/PROT/FwCallApp+-+Abrindo+aplicativos+Web+no+Protheus

**Comment by lwtnb-wrk** [comment]
@alissonph Grato pela confirmação. Fiz um teste aqui e com vários arquivos abertos sendo um deles com a extensão .app e não tive problemas:
[Log   - 00:00:00] Start secure compiling d:/desenv_workspaces/vscode_workspaces/lsda_tests/tst/teste.app (7/8).
[Log   - 00:00:00] [SUCCESS] Resource compiled successfully.
Não aparece nada no Output (AdvPL) que possa indicar algum erro?

**Comment by alissonph** [comment]
Verifiquei aqui, olha a maneira que fiz:
![image](https://user-images.githubusercontent.com/37026901/78172259-21a3fe00-742c-11ea-9386-8be12e9451c2.png)

Voltei no primeiro fonte aberto e apertei CTRL + F10:
![image](https://user-images.githubusercontent.com/37026901/78172300-37192800-742c-11ea-98d4-1d67925f30bb.png)

Ao chegar no .app ele para, porém olhe a mensagem na primeira imagem "O arquivo não é exibido no editor....". Se eu clicar em "Você quer abri-lo de qualquer maneira?" e após isso apertar CTRL + F10 aí tem o funcionamento esperado. 

Se eu tentar compilar o arquivo sozinho antes de clicar no "Você quer abri-lo de qualquer maneira" aparece o seguinte warning: 
![image](https://user-images.githubusercontent.com/37026901/78172432-7182c500-742c-11ea-9f81-83aa8d1a9463.png)

**Comment by lwtnb-wrk** [comment]
@alissonph Entendi. Mas isso é coisa do VS Code mesmo. Ele deve "olhar" dentro do arquivo e como não sabe do que se trata ou existem dados que indicam que é um arquivo binário ele intercepta e dá essa mensagem de alerta.
Tem como me enviar esse arquivo "ratreabilidade.app" para eu testar?

**Comment by alissonph** [comment]
Entendi, não posso te mandar, pois é confidencial.

Faz o seguinte, zipa um arquivo qualquer e altera a extensão de .zip para .app, acabei de testar aqui e tem o mesmo efeito no vscode.

**Comment by alissonph** [comment]
[protheusportinari.zip](https://github.com/totvs/tds-vscode/files/4417055/protheusportinari.zip)

Achei um que posso te mandar, dentro desse zip está um .app de portinari.

**Comment by lwtnb-wrk** [comment]
@alissonph Ah beleza. Eu peguei um pdf e vi que aparecia a mesma mensagem. Eu dando uma olhada nisso. Valeu

**Comment by lwtnb-wrk** [comment]
@alissonph Correção prevista para a próxima atualização da extensão.

**Comment by GuilhermeGomesBarreto** [comment]
Boa Noite
Este problema foi solucionado? estou com mesmo problema para compilar arquivos .app

**Comment by lwtnb-wrk** [comment]
@GuilhermeGomesBarreto Sim e estará disponível a partir da próxima atualização

**Comment by lwtnb-wrk** [comment]
Somente informando que a chave nos settings para o filtro de extensão é o "totvsLanguageServer.folder.extensionsAllowed"
Veja mais detalhes em https://github.com/totvs/tds-vscode#filtro-de-extens%C3%B5es-de-arquivos

**Comment by GuilhermeGomesBarreto** [comment]
Foi feito a configuração da extensão .app, porém continuo não conseguindo compilar o arquivo. Ao abrir dois arquivos um PRW e outro APP, compilando através das teclas Ctrl + F10, é feito a compilação do PRW e ignorado o APP

![image](https://user-images.githubusercontent.com/58429134/81457224-b7d5ed00-916b-11ea-8e8b-da7e274e75e2.png)

Compilando individualmente com botão direito no arquivo Compile/File Folder esta apresentando o erro abaixo

![image](https://user-images.githubusercontent.com/58429134/81457059-29616b80-916b-11ea-9819-2a046e7e99f1.png)

**Comment by lwtnb-wrk** [comment]
@GuilhermeGomesBarreto Fiz um teste aqui e não reproduzi seu problema, tanto com CTRL + F10 quanto com o Compile File/Folder individualmente.
Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md como gerar e envie os logs gerados apos o erro para que possamos analisar seu problema.

**Comment by lwtnb-wrk** [comment]
@GuilhermeGomesBarreto @alissonph Somente um parenteses no que se refere os arquivos .APP ou outros arquivos binários como .PDF, etc...
Estes são arquivos binários e portanto não serão compilados através do CTRL + F10 se eles não estiverem abertos "totalmente" no editor. Se estiverem abertos "parcialmente" ou seja nas abas dos editores o arquivo está presente mas ao seleciona-lo apresentar uma mensagem semelhante a "O arquivo é binário ou não suportado. Deseja abri-lo mesmo assim?" é preciso confirmar e abrir para que ele seja considerado pelo CTRL + F10.
Mas nestes caso seria melhor usar o Compile File/Folder mesmo que não usa o editor, apenas o arquivo.
Lembrando é claro de configura-los como extensões permitidas conforme https://github.com/totvs/tds-vscode#filtro-de-extens%C3%B5es-de-arquivos

**Comment by morarog** [comment]
Alguma solução para o debug error do print acima ?

**Comment by lwtnb-wrk** [comment]
@morarog Não reproduzimos o erro. Se ele está ocorrendo sempre, veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md como gerar logs e nos envie para analises.

**Comment by GuilhermeGomesBarreto** [comment]
Quando clico no arquivo .APP exibe a mensagem ""O arquivo não é exibido no editor porque é binário ou usa uma codificação de texto sem suporte. Você quer abri-lo de qualquer maneira?", mesmo confirmando não esta sendo compilado CTRL + F10 e compilando através Compile File/Folder compilando apenas o arquivo apresenta o erro do Debug Erro, conforme o print encaminhado anteriormente.

segue os logs abaixo?

[totvsls.log](https://github.com/totvs/tds-vscode/files/4617252/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/4617253/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/4617254/totvsls_out.log)

**Comment by lwtnb-wrk** [comment]
@GuilhermeGomesBarreto Realmente então parece que é melhor não abrir o arquivo .APP pelo editor (não recomendamos mesmo para quaisquer arquivos binários) e apenas compila-lo pela pasta ou diretamente pelo menu de contexto do arquivo. 
Estranhamente em seu log não é apresentado nenhum tipo de conexão com o AppServer.
Esse "Debug Error!" ocorre já ao abrir o TDS VS Code então?

**Comment by GuilhermeGomesBarreto** [comment]
Segue o vídeo do momento em que ocorre o erro

[Erro compilar app.zip](https://github.com/totvs/tds-vscode/files/4617417/Erro.compilar.app.zip)

**Comment by lwtnb-wrk** [comment]
@GuilhermeGomesBarreto Voce poderia nos enviar esse arquivo que esta causando o problema? 
Tenho apenas um arquivo .APP para testar e consigou compila-lo sem problemas.
Voce testou com outros arquivos .APP ?

**Comment by GuilhermeGomesBarreto** [comment]
tenho apenas este app, este está sendo o primeiro app.
Acho que não vou conseguir te enviar ele por aqui, zipado esta com 103 MB, como posso te encaminhar?

**Comment by alissonph** [comment]
@GuilhermeGomesBarreto o .app que você está fazendo é angular com portinari/THF? Gera uma build de prod para subir, 103mb acho que é muito grande, não sei se influencia na compilação, o app que tenho é uma personalização relativamente grande e ficou com 6mb.

**Comment by GuilhermeGomesBarreto** [comment]
Isso, em THF.
A pasta maior do app está na pasta "node_modules" devidos os pacotes angular que são instalados e os componentes po-ui/ng-components.

**Comment by alissonph** [comment]
Isso, na build de produção não existe node_modules, somente desenvolvimento, tente dessa maneira.

**Comment by GuilhermeGomesBarreto** [comment]
O problema estava no tamanho do arquivo, após retirar a pasta node_modules o arquivo foi compilado.
Não sei como ficaria o funcionamento, devido o app utilizar componente que estão dentro da pasta node_modules.

Qual limite de tamanho para compilação de arquivos?

**Comment by alissonph** [comment]
@GuilhermeGomesBarreto leia um pouco sobre como gerar build de projeto de angular. Você não deve gerar um .app com a node_modules junto, isso não é recomendado.

https://www.devmedia.com.br/angular-cli-como-gerar-builds-de-projetos-angular/38249

**Comment by lwtnb-wrk** [comment]
@GuilhermeGomesBarreto Graças ao seu relato e suporte enviando logs e videos identificamos um problema que está afetando o tamanho máximo de arquivos de recursos (como o seu .APP).
Não sei dizer ao certo qual o limite, mas ao corrigir o processo fiz uma compilação com o arquivo binário de 130 MB.
Então na próxima atualização será possível compilar arquivos de recurso grandes.
@alissonph Grato pelo seu apoio ao @GuilhermeGomesBarreto também
@morarog Veja se seu problema é o mesmo do @GuilhermeGomesBarreto 
Grato a todos

**Comment by GuilhermeGomesBarreto** [comment]
Obrigado @lwtnb-wrk e @alissonph pela ajuda.

**Comment by morarog** [comment]
Pessoal, é isso ae, meu app estava quase com 200 mb. Tudo certinho agora e compilando que é uma beleza.

Obrigado a todos pelo apoio

**Comment by paulosoaresr** [comment]
Boa tarde , estou fazendo um teste aqui na empresa e estou me deparando com a seguinte situação, ao fazer a chamado do FwCallApp o sistema da um erro dizendo que não consegue extrair os arquivos  Exemplo.app alguém já passou por isso

**Comment by lwtnb-wrk** [comment]
@paulosoaresr Este forum e destinado a resolver problema encontrados na extensao tds-vscode.
Para suporte de AdvPL procure outros canais apropriados.
