### ISSUE TITLE
Retrieve connection error: Connection is not authenticated but requires authentication.

### ISSUE THREAD

**Issue by sampamito** [totvs/tds-vscode#335]
Descrição:
- Ao realizar a compilação na release Protheus 12.1.27 mesmo com SSL ativado na configuração do Server, acontecesse a mensagem abaixo:
"Retrieve connection error: Connection is not authenticated but requires authentication."

A configuração do server.json para o meu servidor
{
			"id": "gniv3rhy2pdk7s34ny5x94kxc1u7lr",
			"type": "totvs_server_protheus",
			"name": "[Virtus] Protheus_27",
			"port": 6004,
			"address": "54.86.220.135",
			"buildVersion": "7.00.191205P",
			"secure": 1,
			"includes": [
				"D:\\TOTVS\\P12_INCLUDES_25"
			],
			"environments": [
				"virtus27"
			],
			"username": "nouser",
			"environment": "virtus27"
		}

**Screenshots**
![image](https://user-images.githubusercontent.com/46483050/78264000-0511cf80-74d9-11ea-8ac9-7e2f2f056049.png)

**Desktop:**
 - OS/Architecture: Windows 10, 64 bits

**Appserver**
 - Build (with date): Build 7.00.191205P - Feb 20 2020 - 17:32:02 
 - OS/Architecture: Windows Server 2012 R2 64 bits
 - Build Version: 19.3.0.2

**Comment by lwtnb-wrk** [comment]
@sampamito Desligue a opção "Use reconnection token" nos Settings e tente se conectar novamente. Veja se isso resolve o problema.

**Comment by gmatiash** [comment]
@lwtnb-wrk I was having the same issue and this allowed me to connect. Now it requests credentials every time I try to connect.

**Comment by lwtnb-wrk** [comment]
@gmatiash Just turn "Use reconnection token" back on and it will use the reconnection token again. The problem was some incorrect information was probably store in the token and disabling it temporary renewed the token with one with the correct informations.

**Comment by sampamito** [comment]
> @sampamito Desligue a opção "Use reconnection token" nos Settings e tente se conectar novamente. Veja se isso resolve o problema.

Retorno para dizer que conforme às orientações consegui compilar normalmente, obrigado pela ajuda.

![image](https://user-images.githubusercontent.com/46483050/78391893-a83c1500-75bd-11ea-87bc-5d700cdd864a.png)
