### ISSUE TITLE
Problemas com a conexão ao servidor no Linux

### ISSUE THREAD

**Issue by vitormds22** [totvs/tds-vscode#337]
Boa tarde, tudo bem pessoal?

Estou com um problema que acredito ser simples, vejam se é possível me auxiliar. 

No momento em que eu tento realizar uma conexão com o ambiente ele simplesmente não segue para a caixa para inserção do usuário. O que pode ser esse problema?

- Configuração
- Comunicação da API com o Servidor ? 
- Bug? 

Quando faço o mesmo processo no windows funciona, porém eu utilizo mais o Linux para desenvolver, 

Obrigado!

**Comment by lwtnb-wrk** [comment]
@vitormds22 Qual a build do AppServer? LG 17 ou o novo LG 19??
Como assim funciona no Windows e so tem problema no Linux? Voce esta acessando o mesmo AppServer do Windows e do Linux??

**Comment by vitormds22** [comment]
@lwtnb-wrk, vide print da versão do appServer.

![Screenshot from 2020-04-07 14-55-28](https://user-images.githubusercontent.com/33588882/78704650-8e167580-78e2-11ea-835f-9092a9f10595.png)

Sim, é o mesmo appServer. Também achei estranho.

**Comment by lwtnb-wrk** [comment]
@vitormds22 Experimente desabilitar o "Use reconnection token" no Settings e veja se isso resolve... Se funcionar e pedir o usuario e senha, pode habilitar novamente a opcao.

**Comment by vitormds22** [comment]
Esse parâmetro fica nesse arquivo ? 

![Screenshot from 2020-04-07 15-21-08](https://user-images.githubusercontent.com/33588882/78705153-6c69be00-78e3-11ea-802b-016be94da001.png)

Seria o objeto permissions ? 

At.te

**Comment by lwtnb-wrk** [comment]
@vitormds22 Nos Settings do TDS VS Code mesmo. File > Preferences > Settings ou CTRL + , (virgula).
Procure em Extensions > AdvPL pelo "Use reconnection token" e desmarque ele.
Refaça as conexões e veja se resolve.

**Comment by vitormds22** [comment]
@lwtnb-wrk FUNCIONOOU! Obrigado.
