### ISSUE TITLE
command 'totvs-developer-studio.add' not found

### ISSUE THREAD

**Issue by thiagocomelli** [totvs/tds-vscode#338]
Issue Type: <b>Bug</b>

command 'totvs-developer-studio.add' not found

VERSÃO 1.0.1 do Plugin

Extension version: 1.0.1
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (5.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|44%|
</details>

**Comment by lwtnb-wrk** [comment]
@thiagocomelli É uma nova instalação? Atualização? Chegou a tentar desintalar e reinstalar?
No Output aparece a opção AdvPL no combo box? Se afirmativo aparece algumas informação no console de saida?
Tenho praticamente as mesmas configurações e aqui não temos problemas.

**Comment by thiagocomelli** [comment]
Olá @lwtnb-wrk ,
Eu estava usando em um ambiente antigo, que foi sendo atualizado ao longo do tempo automaticamente.

Deletei as extensões todas, removi o VSCODE e reinstalei, fazendo também uma limpeza no registro com CCleaner.

Depois de reinstalar tudo novamente, voltou a funcionar.
