### ISSUE TITLE
Debug não Executar Smatclient.exe 

### ISSUE THREAD

**Issue by rubem-mn** [totvs/tds-vscode#339]
Quando executo debug o smarclient não é carregado.

Já excluir o arquivo launch.json e fiz novamente configuração e sem sucesso.

{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Totvs Language Debug",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "C:\\Totvs\\smartclient\\smartclient.exe",
			"enableMultiThread": true,
			"enableProfile": false,
			"isMultiSession": true,
			"isAccessibilityMode": false,
			"doNotShowSplash": false,
			"language": "",
			"ignoreFiles": true
		}
	],
	"lastProgramExecuted": "sigamdi",
	"lastPrograms": [
		{
			"args": [],
			"label": "SIGAMDI",
			"description": ""
		},
		{
			"args": [],
			"label": "SIGAMDI.",
			"description": ""
		},
		{
			"args": [],
			"label": "x",
			"description": ""
		},
		{
			"args": [
				"()"
			],
			"label": "U_CARGTABZF",
			"description": "()"
		},
		{
			"args": [],
			"label": "SI",
			"description": ""
		},
		{
			"args": [
				"()"
			],
			"label": "U_EXECFORMS",
			"description": "()"
		},
		{
			"args": [],
			"label": "U_EXECFORMS",
			"description": ""
		},
		{
			"args": [],
			"label": "S",
			"description": ""
		}
	]
}
	],

**Comment by lwtnb-wrk** [comment]
@rubem-mn Executando o debug pelo F5 nao carrega, mas se executar SEM o Debug via CTRL + F5 o smartclient carrega e executa o programa AdvPL ?

E somente a titulo de informacao, nao aconselhamos nunca a utilizar a depuracao com o SIGAMDI. Execute diretamente o modulo que deseja depurar.

**Comment by DanielYampolschi** [comment]
@rubem-mn , complementando a informação do Leo, verifique nesse seu arquivo launch.json duas situações:
1 - No que voce enviou esta terminando com um "]," a mais. Provavelmente o VsCode esta acusando um erro, pintando essa ultima linha de vermelho, se for realmente o caso, corrija esse fechamento de colchetes
2 - A chave "smartclientBin":  no seu arquivo possui apenas uma barra para esquerda como separador de diretório. É possível que o VsCode também mostre uma cor diferente em cada barra. Se for o caso voce pode ou adicionar uma segunda barra para esquerda ou troca-las por barra à direita. Por exemplo:
"C:\\Totvs\\smartclient\\smartclient.exe" 
ou
"C:/Totvs/smartclient/smartclient.exe"

Por favor informe se o seu problema estava relacionado a alguma dessas questões.

Obrigado.

**Comment by rubem-mn** [comment]
> @rubem-mn Executando o debug pelo F5 nao carrega, mas se executar SEM o Debug via CTRL + F5 o smartclient carrega e executa o programa AdvPL ?
> 
> E somente a titulo de informacao, nao aconselhamos nunca a utilizar a depuracao com o SIGAMDI. Execute diretamente o modulo que deseja depurar.

@lwtnb-wrk  quando executei ctrl + f5 carregou smarclient.

**Comment by rubem-mn** [comment]
@DanielYampolschi , o vscode não está alertando erro algum.

`{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Totvs Language Debug",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "C:\\Totvs\\smartclient\\smartclient.exe",
			"enableMultiThread": true,
			"enableProfile": false,
			"isMultiSession": true,
			"isAccessibilityMode": false,
			"doNotShowSplash": false,
			"language": "",
			"ignoreFiles": true
		}
	],
	"lastProgramExecuted": "sigaadv",
	"lastPrograms": [
		{
			"args": [],
			"label": "SIGAMDI",
			"description": ""
		},
		{
			"args": [],
			"label": "SIGAMDI.",
			"description": ""
		},
		{
			"args": [],
			"label": "x",
			"description": ""
		},
		{
			"args": [
				"()"
			],
			"label": "U_CARGTABZF",
			"description": "()"
		},
		{
			"args": [],
			"label": "SI",
			"description": ""
		},
		{
			"args": [
				"()"
			],
			"label": "U_EXECFORMS",
			"description": "()"
		},
		{
			"args": [],
			"label": "U_EXECFORMS",
			"description": ""
		},
		{
			"args": [],
			"label": "S",
			"description": ""
		},
		{
			"args": [],
			"label": "sigaadv",
			"description": ""
		}
	]
}`

**Comment by lwtnb-wrk** [comment]
@rubem-mn Este segundo json que voce apresentou realmente não contem o "]," no final e portanto está válido.
Voce consegue compilar, gerar/aplicar patches normalmente?
Ao tentar executar um Debug não ocorre erro? Seja no TDS VS Code quanto no Appserver??

**Comment by rubem-mn** [comment]
@lwtnb-wrk consigo aplicar patch e compilar normal.

Estou enviando print para facilitar.
![erro_vscode](https://user-images.githubusercontent.com/26410331/78904673-4a8f4900-7a53-11ea-87d4-91f6baeb6ebc.png)

**Comment by lwtnb-wrk** [comment]
@rubem-mn O print acima nao esta consistente com as configuracoes que voce postou.
Veja que os caminhos dos smartclients utilizados nao coincidem.
Como voce pegou o conteudo do json que voce postou aqui?

**Comment by rubem-mn** [comment]
Refiz configuração novamente com atalha shift+ctrl+p

Segue como ficou meu launch.json



{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Totvs Language Debug",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "C:/totvs/bin/smartclient/smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true
		},
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"cwb": "${workspaceRoot}",
			"name": "TOTVS DEBUG 25",
			"smartclientBin": "C:\\Totvs\\TOTVS12\\Protheus\\bin\\smartclient\\smartclient.exe",
			"program": "${command:AskForProgramName}",
			"programArguments": "${command:AskForProgramArguments}",
			"enableMultiThread": false,
			"enableProfile": false,
			"isMultiSession": true,
			"isAccessibilityMode": false,
			"doNotShowSplash": false,
			"language": "",
			"ignoreFiles": true,
			"enableTableSync": true
		}
	]
}
![Screenshot_1](https://user-images.githubusercontent.com/26410331/78907221-cf2f9680-7a56-11ea-9b04-cefa6316d972.png)

**Comment by lwtnb-wrk** [comment]
@rubem-mn Nesta configuração existem dois profiles o "Totvs Language Debug" e o "TOTVS DEBUG 25" sendo que cada um aponta para um smartclient diferente.
Veja qual você tem que utilizar para o Appserver conectado e selecione no combo antes de iniciar o Debug. 
Veja se era esse o problema e nos avise.

**Comment by lwtnb-wrk** [comment]
@rubem-mn O seu projeto e/ou diretorios tem pastas com alguma acentuacao? Se tiver, remova as acentuacoes e veja se isso resolve o problema.
Se o problema persistir adicione as linhas:
    "totvsLanguageServer.launch.args": [
        "--log-file=totvsls.log",
        "--record=totvsls"
    ],
Em seu settings.json, reinicie o TDS VS Code e repita as operações. Depois nos envie os arquivos de log gerado na raiz do projeto aberto.

**Comment by rubem-mn** [comment]
@lwtnb-wrk remove as pastas que tinha acentuação, carregou na primeira vez smarclient.exe fechei vs code depois refiz o teste e não abriu.

Segue arquivos.

[totvsls.log](https://github.com/totvs/tds-vscode/files/4458579/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/4458580/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/4458581/totvsls_out.log)

**Comment by lwtnb-wrk** [comment]
@rubem-mn Adicione no launch.json a linha:
"logFile": "${workspaceFolder}\\dap.log"
no "configurations" que esta usando para debugar, ajustando a virgula conforme necessario.
Realize o procedimento que esta dando erro e envie o arquivo "dap.log" gerado.

**Comment by rubem-mn** [comment]
Segue
[dap.log](https://github.com/totvs/tds-vscode/files/4469592/dap.log)

**Comment by lwtnb-wrk** [comment]
@rubem-mn Ainda existem pastas com acentuações e por isso esta ocorrendo o erro:
(   0.245s) [main thread     ]        tMessageDAP.cpp:121   | DAP Rcv < - {"command":"setBreakpoints","arguments":{"source":{"name":"F330SE5.prw","path":"c:\\Users\\rubem\\Documents\\Developer\\ADVPL-GIT\\ACTVS\\ACTVS - SA\\ELG\\FINANCEIRO\\COMPENSAÃ?Ã?O CONTAS A RECEBER\\F330SE5.prw"},"lines":[54],"breakpoints":[{"line":54}],"sourceModified":false},"type":"request","seq":3}
(   0.246s) [main thread     ]        tMessageDAP.cpp:128   | Error parsing JSon (invalid UTF8 string)
Acredito que a pasta se chame "COMPENSAÇÃO CONTAS A RECEBER", remova as acentuações de todas as pastas em todos os níveis, e veja se resolve o problema.

**Comment by rubem-mn** [comment]
@lwtnb-wrk  obrigado!

Fiz correção da pasta com acentos. 

Problema resolvido!
