### ISSUE TITLE
Localização do strings para espanhol

### ISSUE THREAD

**Issue by AleksSyntek** [totvs/tds-vscode#34]
Bom día, tenho já completado a localização do strings para o idioma espanhol (https://github.com/AleksSyntek/tds-vscode), mais acho que não é visualizada corretamente por alguma configuração já que tem tudo ok em apariéncia pero após do reinicio do VSCode é a extensão segue com maioria do strings no inglés é algum otro em espanhol é/ou portugués. 
Álguem pode indicarme onde devo avaliar que as configurações feitas esten certas?
Obrigado pela possivel resposta.

**Comment by lwtnb-wrk** [comment]
Assim que possivel faremos o "merge" de suas traduções para o espanhol para nosso projeto. 
Das proximas vez acredito que o melhor seria "clonar" o projeto e submeter suas alteracoes atraves deu um "pull request", mas nos tambem estamos aprendendo como funciona essa colaboracao pelo github.
De cualquier manera gracias por ayudar!!!

**Comment by ricardomansano** [comment]
@AleksSyntek , muito grato pelo apoio. @acacioegas, psc

**Comment by likid** [comment]
@AleksSyntek você poderia abrir um pull request para o pessoal fazer um merge do seu fork.

**Comment by AleksSyntek** [comment]
Sim, agora genero o pull request, obrigado pela resposta @ricardomansano é @lwtnb-wrk

**Comment by AleksSyntek** [comment]
@likid já vi olhé que lwtnb-wrk fiz o pull request. Caso que verifiquen que se necesite fazer mais correções estoy a disposicion.
Slds.

**Comment by lwtnb-wrk** [comment]
@AleksSyntek consegui fazer um "pull request" de seu repositorio e ja incorporei as traducoes em nosso codigo, mas ainda precisamos realizar ajustes para que todas as mensagens sejam exibidas em espanhol. ainda nao posso informar quando conseguiremos realizar os ajustes.
