### ISSUE TITLE
AdvPL - Authentication error: Server returned a non numeric value

### ISSUE THREAD

**Issue by wico2k** [totvs/tds-vscode#341]
El error ocurre cuando se realiza la conexión, si bien logro conectarme al servidor, no logro autentificarme:

[Log   - 00:00:00] Starting connection to the server 'SERVTOTVS_cbl'
[Log   - 00:00:00] Connection to the server 'SERVTOTVS_cbl' finished.
[Log   - 00:00:00] Starting user 'admin' authentication.
[Log   - 00:00:00] Authenticating...
[Error - 20:56:10] Authentication error: Server returned a non numeric value.
[Error - 20:56:10] Authentication failed. Could not authenticate to server.

	"configurations": 
			"type": "totvs_server_protheus",
			"name": "SERVTOTVS_cbl",
			"port": 5200,
			"address": "172.17.4.6",
			"buildVersion": "7.00.131227A",
			"secure": 0,

**Comment by lwtnb-wrk** [comment]
@wico2k Usando um smarclient para se conectar diretamente no AppServer ele funciona?
O AppServer esta em Load Balance?
Envie o appserver.ini para analisarmos tambem.

**Comment by wico2k** [comment]
@lwtnb-wrk La respuesta de ambas pregunta es afirmativa.
Adjunto el archivo de configuración del appserver master.



[appserver.txt](https://github.com/totvs/tds-vscode/files/4472096/appserver.txt)

**Comment by lwtnb-wrk** [comment]
@wico2k Quando se usa a configuração de Load Balance ao se conectar com um Smartclient o servidor Master redireciona a conexão a um dos servidores Slaves disponíveis, mas quando você se conecta pelo TDS VS Code a conexão é direta com o servidor Master.
Comente a seção [ServerNetwork] desta forma e reinicie o AppServer Master:
;[ServerNetwork]
;MasterConnection=0
;Servers=SLAVE1,SLAVE2,SLAVE3,SLAVE4
Veja se consegue conectar-se com este servidor Master pelo Smartclient novamente e nos informe o resultado.

**Comment by wico2k** [comment]
@lwtnb-wrk Somos conscientes de la funcionalidad de Load Balance. Sin embargo, asumimos que el TDS VS Code iba a responder de la misma manera que TDS Eclipse.
Por lo tanto, hemos cambiado la configuración del servidor en TDS VS Code a un puerto slave y pudimos conectar sin inconvenientes - Gracias!

**Comment by lwtnb-wrk** [comment]
@wico2k Voce poderia informar se o Monitor do TDS Eclipse consegue se conectar ao Master que esta dando erro no TDS VS Code?

A principio se a autenticacao do servidor Master estiver funcionando corretamente voce pode ser conectar no Master com o TDS VS Code. E neste cenario de Load Balance o Master agruparia as informacoes de todos os Slaves no Monitor. Nao precisaria monitorar todos os Slaves individualmente.

**Comment by wico2k** [comment]
@lwtnb-wrk El TDS Eclipse tampoco puede conectarse al puerto tcp del appserver master. Emite el mensaje: "Connection information not valid in environment mp12bib."

**Comment by lwtnb-wrk** [comment]
@wico2k É isso que estou dizendo. O problema está no seu servidor Master. Não acredito que seja problema do TDS (VS Code nem Eclipse). Por isso gostaria que se possível testasse.
Comente a seção [ServerNetwork] desta forma e reinicie o AppServer Master:
;[ServerNetwork]
;MasterConnection=0
;Servers=SLAVE1,SLAVE2,SLAVE3,SLAVE4
Veja se consegue conectar-se com este servidor Master pelo Smartclient novamente e nos informe o resultado.

**Comment by wico2k** [comment]
@lwtnb-wrk Correcto, con Load Balance deshabilitado - si se puede conectar tanto TDS Ecclipse como TDS VS Code.

**Comment by wico2k** [comment]
@lwtnb-wrk Y tambien el Smartclient se mantiene operativo.

**Comment by lwtnb-wrk** [comment]
@wico2k Grato pelo teste.   Poderia no mandar o console.log do AppServer Master?

**Comment by wico2k** [comment]
@lwtnb-wrk Adjunto lo solicitado.
[MP12BIB.log](https://github.com/totvs/tds-vscode/files/4480958/MP12BIB.log)

**Comment by lwtnb-wrk** [comment]
@wico2k Pelo console.log vi que seu AppServer é bastante antigo. Não consigo nem testar nessa versão que você tem instalada. Vou montar um ambiente com a versão mais atualizada do AppServer.
***  TOTVS S.A.  ***
***  www.totvs.com.br  ***
* TOTVS - Build 7.00.131227A - Feb 13 2020 - 14:49:15 NG
* Build: 32 bits
* RPO Format: 32 bits
* SVN Revision: 11297 - 26094 - 2213
* Build Version: 13.2.3.49
Você consegue atualizar seu AppServer para esta versão?

**Comment by wico2k** [comment]
@lwtnb-wrk Por favor aguarde, se tiene planeado actualizar a LG en estos días venideros. Le doy un feedback una vez actualizado.

**Comment by lwtnb-wrk** [comment]
@wico2k Vou deixar esse chamado fechado entao. Se voltar a ter problemas reabra este chamado ou se achar melhor abra um novo com os detalhes novos.

**Comment by wico2k** [comment]
@lwtnb-wrk Me parece correcto, gracias!

**Comment by nahimdhaney** [comment]
Boa tarde,

O problema foi solucionado adicionado o specialkey no ambiente:

[](https://centraldeatendimento.totvs.com/hc/es/articles/360024647291-MP-FRAME-C%C3%B3mo-configurar-la-cl%C3%A1usula-SpecialKey-
)

**Comment by fabiopedroza** [comment]
Estou com o problema parecido. Não tenho balaceamento e já coloquei SpecialKey no appserver.ini. Mas está dando erro.

[Error - 09:03:38] Authentication error: Server returned a non numeric value. See Protheus Server log console for details.
[Error - 09:03:38] Authentication failed. Could not authenticate to server.

**Comment by brodao** [comment]
@fabiopedroza 

Veja https://github.com/totvs/tds-vscode/issues/341#issuecomment-664606397 se resolve.
