### ISSUE TITLE
Erro ao aplicar um patch

### ISSUE THREAD

**Issue by alexandroale77** [totvs/tds-vscode#342]
Bom dia, 

Atualizei o binário para 19 e ao conectar via vscode o mesmo se conecta, porem ao eu aplicar um patch estou tendo a seguinte mensagem.

"FILE COULD NOT BE COPIED TO THE SERVER"

Como posso resolver isso?

Grato
Alexandro

**Comment by lwtnb-wrk** [comment]
@alexandroale77 Poderia nos informar exatamente a build que ocorre o problema?
Voce atualizous somente os binarios ou criou todo um novo ambiente para este AppServer 19?

**Comment by alexandroale77** [comment]
Então eu atualizei para ultima versão disponivel no site da TOTVS, atualizei o APPSERVER e SMARTCLIENT 191205P.

Grato
Alexandro

**Comment by lwtnb-wrk** [comment]
@alexandroale77 Então somente os binarios foram atualizados?
O RPO era o mesmo utilizado pelo AppServer anterior assim como base de dados, dicionario etc?
Somente para confirmar o AppServer anterior era um 170117A?

**Comment by Celpio** [comment]
Olá
Estou parcialmente com o mesmo problema.
Meu servidor é Linux e ambiente todo atualizado: appServer 19.3.0.3 e Release 12.1.27
Quando seleciono apenas um arquivo de patch pelo VSCode funciona OK. 
A partir do momento que seleciono dois ou mais, apresenta mesmo problema: "FILE COULD NOT BE COPIED TO THE SERVER".
Para funcionar, estou tendo que compilar os patch um por um.

**Comment by alexandroale77** [comment]
Sim os demais como RPO é o mesmo a base de dados é atualizado a cada patch aonde temos que executar o UPDDISTR.

Grato

**Comment by alexandroale77** [comment]
O meu acontece somente quando aplico patch.

Grato

**Comment by AleksSyntek** [comment]
@lwtnb-wrk anexe o trace desde o _VSCode_ é saída do _Appserver_ no console.log, já que tambén tenho o mesmo erro ao aplicar pacotes.  Esto aparentemente sucede com o último binário appserver 19.3.0.3:
[console_appserver_19.3.0.3.log](https://github.com/totvs/tds-vscode/files/4472062/console_appserver_19.3.0.3.log)
[vscode_trace_apply_lib_appserver_lg_19.3.0.3.log](https://github.com/totvs/tds-vscode/files/4472064/vscode_trace_apply_lib_appserver_lg_19.3.0.3.log)

Tamben com a versao anterior 19.3.0.2.
[console_appserver_19.3.0.2.log](https://github.com/totvs/tds-vscode/files/4472066/console_appserver_19.3.0.2.log)

Espero possa dar maior claridade para o erro com estos arquivos.
Slds.

**Comment by alexandroale77** [comment]
Novamente venho pontuar que nas aplicações de patch com binario "buildVersion": "7.00.170117A", eu consigo aplicar os patchs necessario mais com este binario "buildVersion": "7.00.191205P" o erro de "File could no be copied the server" aparece e não é aplicado o patch.

**Comment by lwtnb-wrk** [comment]
@alexandroale77 Já tomamos conhecimento deste problema porém ainda não foi reproduzido em nenhum de nossos ambientes e portanto não conseguimos analisá-lo.
Favor informar os build exatos do AppServer, qual o SO, topologia do ambiente para ver se temos mais pistas de como ele ocorre.
Grato

**Comment by alexandroale77** [comment]
Eu tenho dois ambiente, mais o mais atualizado é 7.00.191205P, o SO da onde esta VSCODE é Windows 10 o SO do Servidor Windows Server 2008 R2 Standard.

Grato

**Comment by alexandroale77** [comment]
Acabei de reparar uma coisa eu desconectei o server pelo VSCODE e Conectei novamente e o mesmo aplicou o patch se erro então fui aplicar um outro patch e deu o erro novamente dive que desconectar e conectar novamente e ai foi.

**Comment by lwtnb-wrk** [comment]
@alexandroale77 Veja "Gerando logs" em https://github.com/totvs/tds-vscode/blob/dev/TROUBLESHOOTING.md 
Se possível gere os logs nessas duas situações que mencionou e além disso nos envie o console.log do AppServer apos os erros.

**Comment by alexandroale77** [comment]
Acho que descobri o que pode esta ocorrendo, acabei de fazer um teste agora e não precisei desconectar e conectar novamente. na parte Apply Patch aonde selecionamos o patch no final temos Apply e Apply\Close, fiz o teste quando clico Apply\Close ele me da o erro e neste instante apliquei utilizando Apply e foi de boa

**Comment by lwtnb-wrk** [comment]
@alexandroale77 Grato pela informação vou analisar essa diferença.

**Comment by lwtnb-wrk** [comment]
@Celpio @AleksSyntek Voces usaram o Apply/Close ou somente Apply para aplicar os patches?
Poderiam testar a aplicação de Patch usando o botão Apply ao inves do Apply/Close ?

**Comment by AleksSyntek** [comment]
@lwtnb-wrk eu fiz uso solamente do Apply, vou a testar com Apply/Close é doy retorno do teste.

**Comment by AleksSyntek** [comment]
@lwtnb-wrk fiz Apply/Close mais genera o mesmo erro. Neste o Appserver trocó o mensagem do erro:

`2020-04-17T22:12:13.129000-03:00 18156|` 
` [INFO ][SERVER] [Thread 18156] [17/04/2020 22:12:13]`  
` Starting Debugger (alejandro.medina, NBK-ARG-019)` 

` 2020-04-17T22:12:14.371000-03:00 744|` 
` *** Loading dbapi.dll` 

` 2020-04-17T22:12:14.371000-03:00 744|*** dbapi.dll Build 20191119-20200116 RELEASE` 

` 2020-04-17T22:12:15.508000-03:00 744|` 
` [INFO ][SERVER] [Thread   744] JOB Thread finished [-PSWADMIN]` 

` 2020-04-17T22:13:30.399000-03:00 18156|------0--d:\totvs\downloads\rpo\12\20-02-21-lib_label_14022020_p12_lobo-ttts120.ptm` 

` 2020-04-17T22:14:44.624000-03:00 18156|` 
` [FATAL][SERVER] 17/04/2020 22:14:44[Thread 18156] [THROW] Memory Allocation Failure ( 2627839496 bytes ) at file D:\bamboo-agent-5.7.2\xml-data\build-dir\TP11-TECX17V3R1-TECXWIN64\lib_base\memstream.cpp line 36` 

` 2020-04-17T22:14:44.625000-03:00 18156|Memory Allocation Failure ( 2627839496 bytes ) in file D:\bamboo-agent-5.7.2\xml-data\build-dir\TP11-TECX17V3R1-TECXWIN64\lib_base\memstream.cpp at line 36`

Anexo [vscode.log](https://github.com/totvs/tds-vscode/files/4495806/vscode.log)
O Server tem estas características:

![imagen](https://user-images.githubusercontent.com/30332762/79624776-67361b80-80fa-11ea-8fc7-60eb1d1fae38.png)

**Comment by alexandroale77** [comment]
Boa tarde,

Acredito que não descobrir o que ocorre, estou tentando aplicar varios patch e o mesmo não deixa.
segue console log

Grato
[alexandro_server.log](https://github.com/totvs/tds-vscode/files/4505231/alexandro_server.log)

**Comment by IRENIO-S** [comment]
Bom dia, 
Eu também estou com o mesmo problema. 
Alguns patchs consigo aplicar, outros não vai de jeito nenhum. 
Já instalei o VSCode no servidor, mudei o local da pasta include, mudei nome do arquivo de patch. 
Já tentei de tudo. 
Meu ambiente, 
Servidor = WINDOWS SERVER 2008 R2 64BITS
Build do appserver:
* TOTVS - Build 7.00.191205P - Mar 31 2020 - 12:54:19
* Build: 64 bits
* SVN Revision: 26467
* Build Version: 19.3.0.3

Erro na aplicação do patch:
[INFO ][SERVER] [Thread  7464] JOB Thread finished [-PSWADMIN]
------0--c:\totvs12\20200422\tttp120_lg.ptm

[WARN ][SERVER] [THROW][Thread  9072] tConnnErrorException (8:Erro de comunicacao: Erro de sincronismo) on D:\bamboo-agent-5.7.2\x
ml-data\build-dir\TP11-TECX17V3R1-TECXWIN64\lib_comm\msgmanager.cpp:472

[INFO ][SERVER] [[Thread  9072][23/04/2020 09:05:35] Debugger finished ( (Administrador, SERVERAPL)
[MPPORT] 200423_090540 31A8 BPC2019 W x 05 ctx:008 expired timeout for closing of client connection seconds=5 o1r0R1s0S0

Alguma Luz?
Irenio S. Oliveira

**Comment by alexandroale77** [comment]
Boa tarde,

Nenhuma novidade sobre este ajuste, não sei o que ocorreu mais a minha teoria estava errado, eu continuo sem aplicar patch pelo VSCODE com appserver 7.00.191205P

Grato
Alexandro

**Comment by AleksSyntek** [comment]
Bom dia @lwtnb-wrk , tenho um companheiro que hoje empezó com o mismo erro no outro ambiente mais com RPO 12.1.27, o error devuelto é:
[Log   - 00:00:00] Applying patch file: c:/Users/jose.castro/Documents/Clientes/KOMPASS/llamados/8766926/Patch LIB ttts120.ptm
[Error - 10:41:24] Patch could not be applied. Server returned: Failed to open patch file: C:\TOTVS\P12.1.27\DEV\Protheus_Data\\tmptdsdesktop-ctvogfk/Patch LIB ttts120.ptm
[Log   - 00:00:00] Aborting end build (rollback changes).
[Info  - 10:41:24] Apply patch finished.

Acho que o nome do path devuelto indica que nao pode encontrar o pacote na rota local **C:\TOTVS\P12.1.27\DEV\Protheus_Data\\tmptdsdesktop-ctvogfk** onde após da Protheus_data tem doble "\", pode que isso genere o falho do aplicacao do pacote pelo appserver??

**Comment by lwtnb-wrk** [comment]
@AleksSyntek Esse erro pode ser outro problema que existe no AppServer e que pode indicar que o patch que esta sendo aplicado não é compatível com o RPO. 
E grato pelo UPDATE faremos testes aqui para verificar esta questão.

**Comment by alexandroale77** [comment]
Como não tivemos nenhuma solução para caso , retornei para versão antiga e não tenho mais problema de aplicação de patch  tanto 1 quando vários.

Grato

**Comment by lwtnb-wrk** [comment]
@alexandroale77 Poderia nos informar a versao/build exata do AppServer que esta funcionando o apply patch?

**Comment by alexandroale77** [comment]
Boa tarde, segue!

"buildVersion": "7.00.170117A",

Grato

**Comment by AleksSyntek** [comment]
Pude falar com o analista do HDMI que envió pacote do chamado é ele fiz o teste de aplicar o pacote no seu ambiente sendo com sucesso (binario appserver 19.3.0.3). A diferenza que tem é que ele esta usando sim conexao SSL:

`[Drivers]`
`Active=TCP`
`MultiProtocolPortSecure=0`
`MultiProtocolPort=0`

Com isso ele pudo aplciar pacote no seu ambiente sem problema. Eu vou a fazer um teste montando um slave copia do servicio actual com essa mudanza no [Drivers] para avaliar si da certo.

**Comment by lwtnb-wrk** [comment]
@AleksSyntek Muchas gracias por la información
Estavamos exatamente chegando nesta conclusao e iriamos pedir este teste para todos que pudessem.
Voce ja se adiantou e nos informou o que queriamos saber.
Vamos informar o time do AppServer que existe alguma questao envolvendo a conexao SSL da MPPort.

**Comment by lwtnb-wrk** [comment]
@alexandroale77 Se quiser e puder, teste o AppServer com a conexão SSL desligada.
De acordo com nosso colega isso está causando o problema.
De qualquer forma estamos trabalhando com o time do AppServer para identificarmos o problema.

**Comment by AleksSyntek** [comment]
@lwtnb-wrk Finalize o teste com sucesso, desilge o SSL, crie uam nova conexao no VSCode e fiz aplicacao do pacote sim erro. Anexo o log do VSCode é do console.log do appserver configurado sim SSL.

[appserver_19.3.0.3_console.log.zip](https://github.com/totvs/tds-vscode/files/4531878/appserver_19.3.0.3_console.log.zip)

[tds-vscode.log](https://github.com/totvs/tds-vscode/files/4531880/tds-vscode.log)

Slds.

**Comment by AleksSyntek** [comment]
Boa noite @lwtnb-wrk , até hoje nao tuve problemas de aplicacao do pacotes com a seguranca SSL desligada, por exemplo hoje aplique os pacotes dos utiles do Ernani (FSEnvMail e FSBitmap) sim erros.
Acho que é muito raro o erro e nao peco que poderá resolverse asim simples.

**Comment by AleksSyntek** [comment]
Boa tarde @lwtnb-wrk , hoje um analista tuvo o mesmo erro do "file could not be copied to server" ao aplicar o pacote no ambiente com un appserver com SSL ligado é VSCode sobre uma conexao VPN, mais ele instaló o VSCode no servidor é fiz o aplicacao do pacote com sucesso. Acho que pode ser um problema com o timeout do conexao SSL??

**Comment by jairo1610** [comment]
Boa tarde, estou tentando aplicar as patchs da 12.1.27 não aplica jeito nenhum para não falar que nunca apliquei consegui aplicar uma agora como foi já não sei fico desconectando e conectando e uma hora foi outra tentativa aplicar depois aplicar e fechar já consegui tmb mas é impossível ficar assim a mensagem é a mesma do pessoal "file could not be copied to server" estou com a ultima atualização binario, rpo.
Sr. da Totvs será que conseguem esclarecer isso obrigado

**Comment by alexandroale77** [comment]
Bom dia, 

Até mesmo com versão antiga do appserver ele aplica o patch uma vez ou outra.

Grato
![APPSERVER_FILE_SERVER](https://user-images.githubusercontent.com/29817613/82806054-6e6bea00-9e5b-11ea-93e9-e77b9894b966.png)

**Comment by alexandroale77** [comment]
Ai acontece isso.
![FILE_COULD_NOT_BE_COPIED_TO_THE_SERVER](https://user-images.githubusercontent.com/29817613/82806182-a5420000-9e5b-11ea-90fb-5e18b94460b0.png)

**Comment by Celpio** [comment]
Bom dia

Meu ambiente é appServer em Linux com os Smartclient em Windows.
Conforme já havia mencionado, o VSCode me trazia essa mensagem "file could not be copied to server" quando eu selecionava mais de um patch ao mesmo tempo para compilar.
Caso eu selecionasse somente um patch, o mesmo aplicava OK.

Porém, meus problemas foram todos resolvidos.
Semana passada atualizei meu appServer para versão 19.3.0.4 e a extensão do TDS no VSCode para 1.0.3 e tudo normalizou.

Celpio



Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: alexandroale77<mailto:notifications@github.com>
Enviado:segunda-feira, 25 de maio de 2020 07:45
Para: totvs/tds-vscode<mailto:tds-vscode@noreply.github.com>
Cc:Celpio<mailto:celpio@hotmail.com>; Mention<mailto:mention@noreply.github.com>
Assunto: Re: [totvs/tds-vscode] Erro ao aplicar um patch (#342)


Ai acontece isso.
[FILE_COULD_NOT_BE_COPIED_TO_THE_SERVER]<https://user-images.githubusercontent.com/29817613/82806182-a5420000-9e5b-11ea-90fb-5e18b94460b0.png>

**Comment by jairo1610** [comment]
Boa tarde, no meu caso nem de um a um vai consegui aplicar uma patch depois de um monte de tentativa estou com as ultimas versões do appserver e do vscode

**Comment by alexandroale77** [comment]
No meu caso está assim vou até o serviço appserver reinício ele , depois fecho vscode de conecto ao servidor e com isso vai e até o momento nenhum informação de ajuste nem pela TOTVS

**Comment by AleksSyntek** [comment]
Boa noite, após da fazer um teste relacionado com o ticket 390, tuve o siguiente comportamento:

Conexao com appserver 19.3.0.4 com SSL y TDS-VSCode 1.0.3 + patch 20-02-21-LIB_LABEL_14022020_P12_LOBO-TTTS120.PTM, deu certo aplicando.

Apos do isso tenté aplicar o patch 20-03-27-LIB_LABEL_25032020_P12_LOBO-TTTS120.PTM e mostró novamente o erro >[Error - 1:51:00] File could not be copied to the server.}}

Mais novamente tenté aplicar o patch 20-02-21-LIB_LABEL_14022020_P12_LOBO-TTTS120.PTM esperando que mostre o erro... pero estranhamente nao ocurrio! 

Dexio adjunto o captura do saída do VsCode é console.log do appserver
![aplicar patchs](https://user-images.githubusercontent.com/30332762/82980287-78a6f900-9fbf-11ea-87d5-6d46b8c2f41a.jpg)

[console.zip](https://github.com/totvs/tds-vscode/files/4686558/console.zip)

**Comment by jairo1610** [comment]
Bom dia, está difícil a resolução desse problema já fiz de tudo e não vai de maneira nenhuma uma pessoa da Totvs agendou comigo para fazer um acesso remoto para verificar minhas configurações estou aguardando a 3 dias, caso ele resolva posto aqui

**Comment by brodao** [comment]
@alexandroale77

Favor publicar o cabeçalho de inicialização do appServer, para que eu possa ver a build exata do seu appServer. Algo semelhante a:

***  www.totvs.com.br  ***
* TOTVS - Build 7.00.191205P - XXXXXX - XXXXXX
* Build: 64 bits
* SVN Revision: XXXXX
* Build Version: XX.X.X.X

Utilizando a ultima build disponível (Build 7.00.191205P - Apr 24 2020 - 14:30:50), quando ocorre erro de aplicação é apresentado uma mensagem e passando-se o mouse sobre ela, obtemos detalhes. O erro reportado em si, não reproduzi.

Os demais amigos que também estão com problemas, favor publicar o cabeçalho do appServer também.

Grato pela colaboração.

**Comment by jairo1610** [comment]
Bom dia pessoal, conversando com o analista da Totvs fizemos um acesso remoto mostrei o erro ao aplicar qualquer patch e só tinha conseguido aplicar uma e acabamos identificando que patchs abaixo de 100kb aplica normalmente acima disso não vai e nos dois releases 27 e 27.
O Analista ficou de verificar e me retornar logo que acontecer aviso aqui

**Comment by brodao** [comment]
Senhores,

Realizando testes, detectamos que a mensagem de "arquivo não encontrado" esta sendo emitida quando na verdade o erro é de "pacote não compatível com o RPO", p.e.:
- pacote de inglês em RPO portugues;
- pacote topConnect em RPO ctree.

Certifique-se que o pacote esta de acordo com o seu RPO. A ocorrência já está em análise pela equipe do servidor. 

Os testes foram realizados com a última "build" disponibilizada:

> \* TOTVS - Build 7.00.191205P - Apr 24 2020 - 14:30:50
> \* Build: 64 bits
> \* SVN Revision: 26664
> \* Build Version: 19.3.0.4

A disposição.

**Comment by AleksSyntek** [comment]
Bom día @brodao , no meu caso o erro sucede com a LIB TTTS120 é com RPO TopConnect em Espanhol, porém acho que pode houver algum conflicto da versao? Por ex: Pacote generado para o 12.1.27 quando o RPO solicitado é 12.1.25? Agradeco su ayuda na dúvida.

**Comment by brodao** [comment]
Olá Aleks,

Até onde sei, no momento da aplicação não. Pode ocorrer na hora de executar
uma funcionalidade do Protheus. O erro de incompatibilidade entre pacote e
RPO na aplicação, ocorre quando o idioma ou a base de dados não são a mesma
ou a versão do Protheus não esta correta, p.e. pacote para 12 e tentar
aplicar no 19.
Pelo que descreve, com esse pacote e RPO de mesmo idioma e banco, não
deveria ocorrer.
Você consegue disponibilizar o seu RPO e o pacote para meu e-mail da TOTVS (
acandido@totvs.com.br). Fiz testes aqui e não tive problemas.

A disposição.

[:>} Alan Cândido ><>


*Especialista de Pesquisa e DesenvolvimentoExpert Research and Development*
.[====].[====].(----).(----).\___/.[___].]@|--Y\_
 _o__o___o__o___o__o___o__o___o_o___o_o___O___oo_\


Em ter., 2 de jun. de 2020 às 09:40, Aleks <notifications@github.com>
escreveu:

**Comment by AleksSyntek** [comment]
Ok @brodao , vou a deixar os arquivos no drive da totvs é compartilharlos para vc.
Slds.

**Comment by brodao** [comment]
Ola @aleks

Grato pelos arquivos. Estão sendo úteis nos testes.

[:>} Alan Cândido ><>


*Especialista de Pesquisa e DesenvolvimentoExpert Research and Development*
.[====].[====].(----).(----).\___/.[___].]@|--Y\_
 _o__o___o__o___o__o___o__o___o_o___o_o___O___oo_\


Em qui., 4 de jun. de 2020 às 02:52, Aleks <notifications@github.com>
escreveu:

**Comment by brodao** [comment]
Foi detectado que a ocorrência é devido a não conformidade no appServer.
A equipe responsável já foi comunicada da ocorrência.

A disposição.

**Comment by phillipe857** [comment]
boa tarde estou com este problema no VScode, alguem poderia me ajudar.

[Info  - 12:57:36] Starting apply patch.
[Info  - 12:57:36] Starting build for environment SERVERPROTHEUSBACKER.
[Error - 12:57:36] Start build error: Server returned: Session [SERVERPROTHEUSBACKER] not found in AppServer.ini. Verify the "Environment in the Server"
Called from D:\bamboo-agent-5.7.2\xml-data\build-dir\TP11-TECX17V3-TECXWIN64\lib\config.cpp line 78

**Comment by phillipe857** [comment]
> boa tarde estou com este problema no VScode, alguem poderia me ajudar.
> 
> [Info - 12:57:36] Starting apply patch.
> [Info - 12:57:36] Starting build for environment SERVERPROTHEUSBACKER.
> [Error - 12:57:36] Start build error: Server returned: Session [SERVERPROTHEUSBACKER] not found in AppServer.ini. Verify the "Environment in the Server"
> Called from D:\bamboo-agent-5.7.2\xml-data\build-dir\TP11-TECX17V3-TECXWIN64\lib\config.cpp line 78
