### ISSUE TITLE
Aborting: the user must be logged in before compile

### ISSUE THREAD

**Issue by osmar-cioni** [totvs/tds-vscode#343]
Estou tentando compilar em um ambiente, mas esta apresentando a mensagem:[FATAL] Aborting: the user must be logged in before compile.

Obs: Ele nao pede usuario e senha ao criar o servidor no vscode.

Realizei o seguinte teste de acordo com outra issue 331:

Limpei todo o conteúdo da tag 'saved tokens' no arquivo .servers.json e desmarquei a opção 'Use reconnection token to login' em File > Preferences > Settings,
Reiniciei o Vs Code,
Removi todos os servidores cadastrados,
Cadastrei um novo servidor.
Mas nao esta dando certo.

Versão do server:
***  www.totvs.com.br  ***
* TOTVS - Build 7.00.191205P - Feb  5 2020 - 15:20:05
* Build: 64 bits
* SVN Revision: 25991
* Build Version: 19.3.0.1_RC13

**Comment by lwtnb-wrk** [comment]
@osmar-cioni Atualize seu AppServer com a ultima versão atualizada do portal da TOTVS. 
Remova os tokens novamente e tente outra vez.

**Comment by bardez** [comment]
Mesmo após fazer isso @osmar-cioni  continua o problema. começou na versão 1.05

**Comment by lwtnb-wrk** [comment]
@bardez liberamos uma nova versão 1.0.6 mas se o seu problema persistir veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e abrar uma nova issue com a maior quantidade de informacoes possiveis
