### ISSUE TITLE
Erro ao conectar no Totvs Monitor for VScode 0.0.7

### ISSUE THREAD

**Issue by fercobta** [totvs/tds-vscode#345]
Senhores(as), bom dia.

Quando tento fazer a conexão pelo Totvs Monitor for VScode 0.0.7 no binário do Protheus do dia 21/02/2020, Remote build: 7.00.191205P-20200221, Remote version: 19.3.0.1, Build AppServer: 7.00.191205P-20200220 - 64 bits e Appserver version: 19.3.0.2, instalado no Sistema operacional: Windows Server 2012.
Ocorre o erro de conexão.
![image](https://user-images.githubusercontent.com/63671317/79339135-cfb8a900-7efe-11ea-9316-9c678472eb0a.png)
Assim, o que devo fazer para corrigir esse erro?

Att,
Fernando Azevedo Coelho.

**Comment by lwtnb-wrk** [comment]
@fercobta A extensão do Monitor esta passando por reformulações. Acho que o melhor neste momento é desinstala-lo. 
Se quiser testar temos o Monitor Electron em fase de testes:
https://arquivos.totvs.com.br/TrocaArquivos/download.aspx?id=37033&key=O5bM2lZGxNTlaLZh2B7u3scQOUO-86UfPcEVuuATozI1

**Comment by fercobta** [comment]
lwtnb-wrk ótima dica.
Desinstalei a extensão do VScode e instalei o Monitor Electron.
Obrigado.
![image](https://user-images.githubusercontent.com/63671317/79346067-4ad28d00-7f08-11ea-818e-f978741dde35.png)
