### ISSUE TITLE
Erro ao compilar pasta

### ISSUE THREAD

**Issue by alissonph** [totvs/tds-vscode#346]
**Describe the bug**
Tenho um projeto com mais de 600 fontes, peguei um RPO zerado e ao tentar compilar a pasta completa foi acusado 6 fontes com erro, a tabela de resultado de compilação informa que foram compilado os fontes, porém os que estavam apenas com warning ou sem erro não foram compilados no RPO. Após ajustar os 6 fontes com erro e compilar o projeto completo, aí sim compila corretamente todos os fontes.

**To Reproduce**
Compilar uma pasta com vários fontes que existam alguns fontes com erros (erro de sintaxe, include etc).

**Expected behavior**
Os fontes que não estão com erro deveriam ser compilados no RPO sem nenhum problema. A informação exibida na tabela de resultado de compilação não é uma informação verdadeira, pois informa que os fontes com warning/sem erro foram compilados, mas eles não existem no RPO.

**Desktop:**
 - OS/Architecture: Windows 10 64 Bits

**Appserver:**
 - Build (with date): 7.00.191205P-20200220
 - OS/Architecture: Windows Server 2016 64 bits
 - Build Version: 19.3.0.2

**Comment by lwtnb-wrk** [comment]
@alissonph Que tipo de erros foram ajustados nos fontes?
Se possível gere os logs durante a compilacao desses fontes com problemas e nos envie para que possamos avaliar melhor o problema.
Veja como gerar estes logs na seção "Gerando logs"em https://github.com/totvs/tds-vscode/blob/dev/TROUBLESHOOTING.md

**Comment by lwtnb-wrk** [comment]
@alissonph Li melhor agora seu relato e acho que havia entendido errado anteriormente.
Os seis fontes que voce corrigiu continham ERROS e nao apenas WARNINGS, correto?
Se continham ERROS toda a "transacao" sera abortada, pois se fizessemos o commit seu RPO poderia ficar em um estado inconsistente.
Se esse for o seu cenário, então não faremos alterações, pois não podemos comprometer a integridade do RPO.
Se meu entendimento foi errado favor reabrir a Issue e nos de mais informacoes para avaliarmos a questao.
A unica questao que podemos alterar seria que neste caso removeriamos os fontes sem ERROS nem WARNINGS da tabela de resultado, mesmo que no final da compilacao é informado que abortamos a compilacao por existir erros.

**Comment by alissonph** [comment]
Realmente aparece que foi abortado a compilação, não tinha reparado na mensagem: 
[Log   - 00:00:00] Aborting end build (rollback changes).

Na tabela de resultado exibe com sucesso:
![image](https://user-images.githubusercontent.com/37026901/79487848-39b07b80-7fef-11ea-9c85-996b0f292e26.png)

Na minha opinião ficaria bom acrescentar uma mensagem na tabela de resultados que a compilação foi abortada e exibir na lista somente os com erros. Mas fica a critério de vocês fazer ou não essa melhoria.
