### ISSUE TITLE
Não é executado o Client ao iniciar o Debug

### ISSUE THREAD

**Issue by evandruns** [totvs/tds-vscode#348]
**Describe the bug**
Apos atualização do VSCODE, ao iniciar o Debug (F5) o SmartClient não é executado.
Efetuei a atualização dos Binários para ultima versão 19.x.x, retorne para Versões 17. no entanto em nenhuma desta é chamado

Efetuei tentativa no release 12.1.25 e 12.1.27 X64

Procedimento para tentativa de correção:
-Desinstalo o nosso plugin
-Apagado a pasta .totvsls (tem um PONTO antes), ela fica na sua pasta de usuários
-Apagado a pasta .vscode do seu diretório de projetos
-reiniciado a maquina pra limpar qualquer cache que o VS guardou
-depois de reiniciar, reinstala o plugin
-reconfigura o ambiente

Dados do Server 
Versão: TOTVS Serviços
Build AppServer: 7.00.191205P-20200220 - 64 bits
Appserver version: 19.3.0.2
Build DBAccess: 20191119-20200217
Release do RPO:  12.1.027
Release do dicionário: 12.1.027
Local files: CTREE
License server: 2014 - 3.0.3
DB DataBase: MSSQL
DB API Build: 20191119-20200116

Dados do Remote 
Remote build: 7.00.191205P-20200131
Remote version: 19.3.0.0_RC6
Remote type: 1 - QT-5.14.0 WIN
Sistema operacional: Windows 10 - 
Memória: 8067
Processador: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz

Versão VSCODE 1..44.1

Video com procedimento:
http://suporte.totvs.com/totvs-tdi-files-maps/mapeamentos/portal-anexos/anexos/zendesk/20200416/TTVFLGP1J001-1587065401303-696865.zip

**Comment by lwtnb-wrk** [comment]
@evandruns Nao entendi o que voce quis mostrar no video em anexo.
Enfim de uma lida em https://github.com/totvs/tds-vscode/blob/dev/TROUBLESHOOTING.md 
Veja se pode ser o problema de acentuação ou versão de smartclient
Se ainda assim não tiver uma solução nos envie os logs gerados.

**Comment by evandruns** [comment]
Olá
No vídeo mostro que o SmartClient não esta sendo executado, inicia a Thread porem não sobe o ambiente.
Testei com versão de binário 19. e também anteriores como 17, pois sou @Totvs possuo acesso ao Arte.
Esta situação passou a ocorrer apos atualização do VSCODE.
Quais Logs você precisa?

**Comment by lwtnb-wrk** [comment]
@evandruns Veja "Gerando logs" em https://github.com/totvs/tds-vscode/blob/dev/TROUBLESHOOTING.md

**Comment by evandruns** [comment]
Refiz toda a instalação novamente, desta utilizando um versão anterior, e o Client foi executado.
Obrigado!

**Comment by evandruns** [comment]
@lwtnb-wrk Perdão, acabei de tentar depurar um fonte e notei que não para nos pontos de parada, utilizando Ctrl+F5 e com F5 não executa o SmartClient.

Seguem arquivos:
http://suporte.totvs.com/totvs-tdi-files-maps/mapeamentos/portal-anexos/anexos/zendesk/20200417/TTVFLGP1J001-1587148463291-741475.zip

Note que ambos estão totalmente atualizados, VSCODE 1.44.2
Protheus:
Dados do Server 

Versão: TOTVS Serviços
Build AppServer: 7.00.191205P-20200331 - 64 bits
Appserver version: 19.3.0.3
Build DBAccess: 20191119-20200217
Release do RPO:  12.1.025
Release do dicionário: 12.1.025
Local files: CTREE
License server: 2014 - 3.0.3
DB DataBase: MSSQL
DB API Build: 20191119-20200116

Dados do Remote 

Remote build: 7.00.191205P-20200131
Remote version: 19.3.0.0_RC6
Remote type: 1 - QT-5.14.0 WIN
Sistema operacional: Windows 10 - 
Memória: 8067
Processador: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz

Versão da Lib:20200325
Data da Lib: 20200320_172337
Commit ID:02fdc8f9b32dc542af3a7cd63c9a451b1a631df5

**Comment by walterfcarvalho** [comment]
Peguei esse erro também, quando eu mando debugar, o smartclient não abre.
Vou fazer o procedimento dos logs para poder ajudar.

**Comment by lwtnb-wrk** [comment]
@evandruns Seu problema é de acentuação mesmo
c:\\Totvs\\vscode\\PADRÃO\\FINA450.PRX
Remova a acentuação da pasta que deve funcionar

@walterfcarvalho Veja se existe acentuação em qualquer pasta que o fonte tenha breakpoints

**Comment by evandruns** [comment]
Opa, onde esta definido este caminho, pois não possuo esta na minha área de trabalho.
Realmente havia esta pasta, no entanto ela foi excluída, existe algum arquivo que guarda esta informação?

**Comment by evandruns** [comment]
Encontrei, são os pontos de parada.
Muito obrigado pela ajuda!
