### ISSUE TITLE
Compilar arquivos com acentuação.

### ISSUE THREAD

**Issue by naganava** [totvs/tds-vscode#349]
Ao compilar arquivos que tem acentuação no nome da erro dizendo que o arquivo não foi encontrado.
"File /Users/teclaserti/VSCode/Teclaser/Producao/TPROD005 - Peças de dobra programada.prw not found."

Renomeie o arquivo, mas não consigo compilar de novo, pois da o erro de função duplicada.
[FATAL] Aborting: Duplicated function U_TPROD005 (found in TPROD005 - PE�AS DE DOBRA PROGRAMADA.PRW) 

E se eu tento remover a função do RPO também não funciona, creio que mesmo motivo de acentuação.

Alguma solução pra isso? Vi alguns outros issues que tinham a ver com acentuação, mas a solução era basicamente remover a acentuação, que nesse meu caso não ta funcionando.

**Comment by lwtnb-wrk** [comment]
@naganava Favor ler a https://github.com/totvs/tds-vscode/blob/dev/TROUBLESHOOTING.md e enviar mais informações sobre ambiente e logs com erros.

**Comment by naganava** [comment]
Versão do VS code
Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:07:18.473Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 17.7.0

Versão da extensão tds-vscode
1.0.1

[totvsls_in.log](https://github.com/totvs/tds-vscode/files/4505867/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/4505868/totvsls_out.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/4505869/totvsls.log)

**Comment by lwtnb-wrk** [comment]
@naganava Essa função U_TPROD005 já havia sido compilada neste RPO em outro ambiente?
Os caminhos com acentuação atualmente são suportados apenas no Windows por questões de encoding.
Aparentemente o função está compilada no RPO (em um fonte com acentuação no nome) e como você está no Mac o RPO não consegue sobrescrever nem apagar.
Até que o suporte a acentuação seja implementada no Mac será preciso utilizar um Windows para remover essa função do RPO para que depois você possa compila-la no Mac.

**Comment by lwtnb-wrk** [comment]
@naganava Outro detalhe que percebi. 
O arquivo se chama "TPROD005 - Peças de dobra programada.prw" ou "TPROD005 - PEÇAS DE DOBRA PROGRAMADA.PRW"? 
Em Linux e Mac, os nomes de arquivos são case sensitive.
Tente mudar o case do arquivo para ver se funciona ou se o erro muda.

**Comment by naganava** [comment]
No windowns funcionou. Muito obrigado.
Vou testar a questão de case sensitive.

**Comment by lwtnb-wrk** [comment]
@naganava Se possível teste também renomeando tudo para minúscolo "tprod005 - peças de dobra programada.prw"

**Comment by lkznogueira** [comment]
Realmente, acabei de fazer um teste no meu macbook e ao compilar um arquivo onde a pasta que ele está na workspace tenha acentuação, no compiler do vscode ele da "file not found" após retirar a acentuação a compilação ocorreu normal...

**Comment by lwtnb-wrk** [comment]
@lkznogueira Grato pelo teste e informação.
