### ISSUE TITLE
Falha na compilação com caminho longo (diretório)

### ISSUE THREAD

**Issue by thiagocomelli** [totvs/tds-vscode#350]
Ao compilar um fonte com 117 linhas de código (qualquer fonte pode ser testado, o problema acontece com todos os fontes), caso o caminho do arquivo (diretórios) tenha mais que 128 caracteres, é gerado um problema na compilação. No meu caso o fonte com 117 linhas apresenta um resultado de compilação de 140 linhas no console.log.

Ao reduzir o tamanho do caminho do arquivo para 128 caracteres ou menos o fonte é compilado normalmente com resultado de 117 linhas no console.log.

O problema da compilação com caminho longo (maior que 128 caracteres) é que ao apresentar error.log a linha que gerou o erro é mostrada incorretamente. Também o DEBUG não funciona corretamente, pois o programa compilado não corresponde ao programa original na questão de numeração das linhas, os Breakpoints ficam desposicionados.

Exemplo de caminho que não funciona:
c:/Users/Comelli/Dropbox/Fontes Ventura . Teste/123456789001/123456789002/003/7. Fontes de Programas/7.1 Fontes/7.1.2 RDMAKETESTE/Fontes/WSPAPRI.prw

Exemplo de caminho que funciona:
c:/Users/Comelli/Dropbox/Fontes Ventura . Teste/123456789001/002/003/7. Fontes de Programas/7.1 Fontes/7.1.2 RDMAKETESTE/Fontes/WSPAPRI.prw

**Comment by thiagocomelli** [comment]
> @thiagocomelli Favor ler https://github.com/totvs/tds-vscode/blob/dev/TROUBLESHOOTING.md e nos enviar todos os logs gerados para analise.

@lwtnb-wrk , com toda vênia, acho que este problema é demasiadamente simples e pode ser reproduzido sem dificuldades no ambiente de qualquer um que rode o VsCode em Windows.
Não vou gerar todos os logs solicitados, pois vai tomar tempo demais, sendo que basta mover os fontes para um caminho mais curto para solucionar o problema.

Eu abri a Issue para que vocês possam melhorar a ferramenta, sabendo de um problema que talvez seja desconhecido pela equipe.

Se não quiserem investigar, para mim não tem problema. Eu tentei ajudar :-)

**Comment by lwtnb-wrk** [comment]
@thiagocomelli Com certeza essa é uma via de mao dupla. Sempre pediremos os logs para facilitar a analise do problema relatado. Grato pela notificacao.

**Comment by lwtnb-wrk** [comment]
@thiagocomelli Data venia, realizamos testes com caminhos longos "D:\desenv_workspaces\vscode_workspaces\lsda_tests\long_path_test\12345678901234567890123456789012345678901234567890\12345678901234567890123456789012345678901234567890" e não observamos problemas.
O arquivo nesta pasta foi compilado corretamente e também depurado corretamente.
Se puder enviar o arquivo utilizado e os logs pedidos anteriormente poderemos analisar o que pode esta ocorrendo em seu ambiente.

**Comment by DanielYampolschi** [comment]
@thiagocomelli Você pode por favor informar qual a mensagem que é gerada no VsCode na compilação com caminho com mais de 128 characteres?

Muito obrigado.

**Comment by thiagocomelli** [comment]
> @thiagocomelli Você pode por favor informar qual a mensagem que é gerada no VsCode na compilação com caminho com mais de 128 characteres?
> 
> Muito obrigado.

Não dá erro, ele compila o fonte normalmente, mas no console.log do server ele mostra um numero maior de linhas compiladas do que realmente existe.

**Comment by thiagocomelli** [comment]
> @thiagocomelli Data venia, realizamos testes com caminhos longos "D:\desenv_workspaces\vscode_workspaces\lsda_tests\long_path_test\12345678901234567890123456789012345678901234567890\12345678901234567890123456789012345678901234567890" e não observamos problemas.
> O arquivo nesta pasta foi compilado corretamente e também depurado corretamente.
> Se puder enviar o arquivo utilizado e os logs pedidos anteriormente poderemos analisar o que pode esta ocorrendo em seu ambiente.

Vou gerar e enviar.
