### ISSUE TITLE
Problema ao compilar fontes

### ISSUE THREAD

**Issue by pazetto** [totvs/tds-vscode#351]
Olá,

Havia localizado um tópico anterior falando para separar a pasta dos includes e do projeto dos fontes [aqui.](https://github.com/totvs/tds-vscode/issues/191) Sabendo disso, já precavi e separei anteriormente a pasta dos includes (C:\include), e meu projeto de fontes está em C:\Projetos\Fontes_PRD
O serviço já foi por outras vezes utilizado para compilação de fontes no VsCode pelo meu usuário e estação, porém depois que atualizei o VsCode não consigo mais compilar.

A mensagem é essa abaixo:

> [Info  - 14:34:11] Starting recompile.
[Log   - 00:00:00] Starting build for environment COMPILA.
[Log   - 00:00:00] Aborting end build (rollback changes).

Fiz um teste aplicando um patch, e ele faz com sucesso.

> [Info  - 14:36:21] Starting apply patch.
[Log   - 00:00:00] Starting build for environment COMPILA.
[Log   - 00:00:00] Applying patch file: c:/Users/Felipe/Desktop/RFC/8432084_rhmobile01-7120_12.1.25_tttp120_lg.ptm
[Log   - 00:00:00] Patch successfully applied.
[Log   - 00:00:00] Committing end build.
[Info  - 14:36:28] Apply patch finished.

Vejo o console.log e não há nenhum erro/alerta.

Versão do VsCode: 1.43.2
Versão do plugin TOTVS: 1.0.1
Windows 10

**Comment by lwtnb-wrk** [comment]
@pazetto Favor ler o https://github.com/totvs/tds-vscode/blob/dev/TROUBLESHOOTING.md e enviar os logs do TDS VS Code para analise.

**Comment by pazetto** [comment]
> @pazetto Favor ler o https://github.com/totvs/tds-vscode/blob/dev/TROUBLESHOOTING.md e enviar os logs do TDS VS Code para analise.

Obrigado @lwtnb-wrk , através do Troubleshooting já resolvi meu problema.
De fato, o arquivo verificado era o incorreto "settings.json" e "launch.json", porém verificando o arquivo "servers.json" o problema foi solucionado.
