### ISSUE TITLE
Vscode não pede login e senha do ambiente com binario 19.3.0.3

### ISSUE THREAD

**Issue by zettazt512** [totvs/tds-vscode#352]
Bom dia.

Com binário 19.3.0.3 disponível no portal do cliente vscode não pede login e senha na configuração do ambiente. Com isso ao tentar compilar os fontes gera a seguinte mensagem e não compila

Retrieve connection error: Connection is not authenticated but requires authentication.

**Desktop (please complete the following information):**
 Windows 10 64 bits

**Appserver (please complete the following information):**
* TOTVS - Build 7.00.191205P - Mar 31 2020 - 12:54:19
* Build: 64 bits
* SVN Revision: 26467
* Build Version: 19.3.0.3

**Comment by lwtnb-wrk** [comment]
@zettazt512 Favor ler https://github.com/totvs/tds-vscode/blob/dev/TROUBLESHOOTING.md 
Se nao for o caso, anexe os logs e reabra a issue
