### ISSUE TITLE
Patch Generation  (From Folder)

### ISSUE THREAD

**Issue by GustavoLuizOliveira** [totvs/tds-vscode#353]
Ao gerar um patch de uma pasta, e se na pasta contiver imagens, não é considerado as imagens no pacote, somente os fontes.

**Comment by lwtnb-wrk** [comment]
@GustavoLuizOliveira Atualmente existe uma configuração que permite o filtro de determinadas extensões na geração de patches. Por padrão apenas BPM e PNG estao entrando nos patches.
Veja em File > Preferences > Extensions > AdvPL   -   Extensions > Folder: Patch
Mas na próxima atualização iremos tornar essa configuração geral para a compilação e geração de patches por pastas.

**Comment by lwtnb-wrk** [comment]
@GustavoLuizOliveira Alteramos a preferencia para que ela seja considerada na compilacao de pastas e geracao de patch por pastas.
Veja em https://github.com/totvs/tds-vscode#filtro-de-extens%C3%B5es-de-arquivos
