### ISSUE TITLE
Problema ao Instalar um Plug in no VS Code

### ISSUE THREAD

**Issue by rickalves13** [totvs/tds-vscode#354]
Bom dia! 

Ao fazer a instalação do PlugIn abaixo, apresenta uma mensagem ao instalar os servidores 
![image](https://user-images.githubusercontent.com/64543516/80612006-bf7def00-8a11-11ea-928e-85a97c3d54f4.png)

Mansagem de erro 
![image](https://user-images.githubusercontent.com/64543516/80612081-d9b7cd00-8a11-11ea-9fc2-b9d1a094df18.png)

Dados do ambiente Windows 10 64bits
![image](https://user-images.githubusercontent.com/64543516/80612166-f81dc880-8a11-11ea-90c4-37ba5dd4e296.png)

![image](https://user-images.githubusercontent.com/64543516/80612204-066be480-8a12-11ea-8d5a-3d28fb2a5a58.png)

**Comment by lwtnb-wrk** [comment]
@rickalves13 veja https://github.com/totvs/tds-vscode/blob/dev/TROUBLESHOOTING.md e se não resolver nos envie os logs para análise
