### ISSUE TITLE
Erro ao conectar no TOTVS:SERVERS

### ISSUE THREAD

**Issue by jadilsonnery** [totvs/tds-vscode#355]
Ao conectar no TOTVS SERVERS seleciono o server e a resposta diz que a Senha está errada. Já refiz a senha settings.json

**Comment by lwtnb-wrk** [comment]
@jadilsonnery veja https://github.com/totvs/tds-vscode/blob/dev/TROUBLESHOOTING.md e nos envie os logs gerados para analise

**Comment by jadilsonnery** [comment]
Authentication failed. Could not authenticate to server.

Authentication error: Could not authenticate. Invalid user and/or password.

 

Já fiz isso também:

Falha de conexão (Retrieve connection error)

Se ocorrer um erro com a mensagem do tipo: Retrieve connection error: Connection is not authenticated but requires authentication Indica que o token de reconexão pode conter dados incorretos. Solução: Acione File > Preferences > Settings ( ou CTRL + , ) e localize AdvPL em Extensions. Procure a opção "Use reconnection token" e desabilite temporariamente. Tente se conectar novamente e os dados do token de reconexão serão atualizados com os novos dados da conexão.

 

 

 

Jadilson S. Nery
Atendimento e Relacionamento
Solution Partner
www.solucoesconsultoria.com <http://www.solucoesconsultoria.com/> 
Unidade Minas Gerais
* 55 (31) 8481-6219

* jadilson@ <mailto:jadilson@solucoesconsultoria.com> solucoesconsultoria.com
*  <mailto:jadilson.nery@totvs.com.br> jadilson.nery@totvs.com.br

 

 

De: lwtnb-wrk <notifications@github.com> 
Enviada em: quinta-feira, 30 de abril de 2020 10:57
Para: totvs/tds-vscode <tds-vscode@noreply.github.com>
Cc: jadilsonnery <jadilson@solucoesconsultoria.com>; Mention <mention@noreply.github.com>
Assunto: Re: [totvs/tds-vscode] Erro ao conectar no TOTVS:SERVERS (#355)

 

@jadilsonnery <https://github.com/jadilsonnery>  veja https://github.com/totvs/tds-vscode/blob/dev/TROUBLESHOOTING.md e nos envie os logs gerados para analise

**Comment by leogr85** [comment]
Bom dia! Estou homologando o TSS 3.0  e estou com mesmo problema,.
Já revisei usuarios do TSS, tentei com outro e mesma msg,

Segue log para envio:

File verbosity level: 9
date       time         ( uptime  ) [ thread name/id ]                   file:line     v| 
2022-08-26 10:59:54.049 (  20.011s) [                ]             loguru.cpp:755   INFO| Logging to 'totvsls.log', mode: 'w', verbosity: 9
(  20.011s) [main thread     ]             loguru.cpp:591   | arguments: c:\\Users\\leogr\\.vscode\\extensions\\totvs.tds-vscode-1.3.15/node_modules/@totvs/tds-ls/bin/windows/advpls.exe language-server --enable-auto-complete=LS --notification-level=\"all\" --fs-encoding=cp1252 --includes=C:\\Users\\leogr\\OneDrive\\Documentos\\WORK\\Clientes\\Central\\Repositorios\\Includes --linter=enabled --wait-for-attach=20000 --log-file=totvsls.log --record=totvsls
(  20.011s) [main thread     ]             loguru.cpp:594   | Current dir: c:\Users\leogr\OneDrive\Documentos\WORK\Clientes\Central\Repositorios\COFREP
(  20.012s) [main thread     ]             loguru.cpp:596   | stderr verbosity: -2
(  20.012s) [main thread     ]             loguru.cpp:597   | -----------------------------------
(  20.012s) [main thread     ]    security_manager.cc:883   | lsRsaInit
(  20.013s) [main thread     ]    security_manager.cc:1419  | lsAsymmDecrypt
(  20.013s) [main thread     ]    security_manager.cc:1420  | plaintext 
(  20.013s) [main thread     ]    security_manager.cc:1421  | ciphertext 1770386239A4BB8D0705DD9AC59E2DF39F63B9B84214626B1F676B1250D2C9D2D1EB9703D23D500D4C1D93735488DD914523B74597FCB92C531E3F95E7A5E95F27C7C6DC51B2E2851E245A3048036A9957E4F6097309D30262E8C9A0ABFB3E196EF83053C2E0535ACA99FDF82BF7F783CC3E275D3FFBFA7E245C72D34C922ACED95BAB023D3CCFAF987C47DBF00A9A0351C7DC3E65960DD1DC552DEF1756409E122C5FED5A82F952D6040D4AB8ACC9317EA11E139F5DA1E88EF917F8B9659656C127F6C09972CE6EBEE5CE09CC6191343958D3C19C2D0C4E75519B9A49C73B509DB215C6E1583BB7247C4D4C9FA2B7340CE6DDE6B15DE1A498E9C795C80E4CAA
(  20.013s) [main thread     ]    security_manager.cc:1422  | ciphertext_len 256
(  20.019s) [main thread     ]    security_manager.cc:1099  | userRsaInit
(  20.019s) [main thread     ]    security_manager.cc:1118  | Loading user prv key.
(  20.019s) [main thread     ]    security_manager.cc:1149  | Loading user pub key.
(  20.019s) [main thread     ]    security_manager.cc:1248  | Loading user symm key.
(  20.027s) [querydb         ]msg_lsp_initialize_requ:496   | Start Running initialize
(  20.027s) [stdout          ]               timer.cc:42    | [e2e] Message to Client: "[Info] Initializing Language Server." took 0.0 ms
(  20.027s) [querydb         ]msg_lsp_initialize_requ:502   | Init parameters: {"compilationDatabaseCommand":"","compilationDatabaseDirectory":"","cacheDirectory":"","cacheFormat":"json","resourceDirectory":"","discoverSystemIncludes":true,"extraClangArguments":[],"progressReportFrequencyMs":500,"emitQueryDbBlocked":false,"emitInactiveRegions":false,"showDocumentLinksOnIncludes":true,"codeLens":{"localVariables":true},"completion":{"enableSnippets":true,"detailedLabel":false,"dropOldRequests":true,"filterAndSort":true,"includeMaxPathSize":30,"includeSuffixWhitelist":[".h",".hpp",".hh",".ch"],"includeBlacklist":[],"includeWhitelist":[]},"formatting":{"enabled":false},"diagnostics":{"blacklist":[],"whitelist":[],"frequencyMs":0,"onParse":true,"onType":true},"highlight":{"enabled":false,"blacklist":[],"whitelist":[]},"index":{"attributeMakeCallsToCtor":true,"blacklist":[],"whitelist":[],"comments":2,"enabled":true,"logSkippedPaths":false,"threads":0},"workspaceSymbol":{"maxNum":1000,"sort":true},"xref":{"maxNum":2000},"enableIndexOnDidChange":false}
(  20.027s) [stdout          ]               timer.cc:42    | [e2e] Message to Client: "[Info] Initializing Language Server." took 0.0 ms
(  20.028s) [querydb         ]msg_lsp_initialize_requ:517   | [querydb] Initialize in directory c:/users/leogr/onedrive/documentos/work/clientes/central/repositorios/cofrep with uri file:///c%3A/Users/leogr/OneDrive/Documentos/WORK/Clientes/Central/Repositorios/COFREP
(  20.028s) [querydb         ]msg_lsp_initialize_requ:574   | Using -resource-dir=c:/users/leogr/onedrive/documentos/work/clientes/central/repositorios/cofrep/default_resource_directory
(  20.028s) [querydb         ]msg_lsp_initialize_requ:577   | Send initialization before starting indexers, so we don't send a status update too early.
(  20.028s) [querydb         ]msg_lsp_initialize_requ:597   | Set project root.
(  20.028s) [stdout          ]               timer.cc:42    | [e2e] Running initialize took 0.825 ms
(  20.044s) [querydb         ]               timer.cc:42    | compile_commands.json advpllang time took 0.0 ms
(  20.044s) [querydb         ]               timer.cc:42    | compile_commands.json our time took 0.0 ms
(  20.044s) [querydb         ]               timer.cc:42    | [perf] Loaded compilation entries (0 files) took 0.137 ms
(  20.044s) [querydb         ]msg_lsp_initialize_requ:640   | Starting 9 indexers
(  20.044s) [querydb         ]               timer.cc:42    | [perf] Dispatched initial index requests took 0.0 ms
(  20.044s) [querydb         ]msg_lsp_initialize_requ:669   | End Running initialize
(  20.044s) [querydb         ]msg_lsp_initialized_not:22    | Got Initialized Notification
(  20.044s) [stdout          ]               timer.cc:42    | [e2e] Message to Client: "[Info] Language Server initialized." took 0.0 ms
(  20.044s) [stdout          ]               timer.cc:42    | [e2e] Message to Client: "[Info] Language Server initialized." took 0.0 ms
(  20.051s) [scan_includes   ]               timer.cc:42    | [perf] Scanning for includes took 6.6823 ms
(  40.000s) [querydb         ]msg_totvsserver_connect:55    | Start Running $totvsserver/connect
(  40.000s) [querydb         ]msg_totvsserver_connect:67    | Connection to server connType: 3 at P12_33_TSS(qu8anbsukkl7aj0iil9oj3kp8pdna) (1) 192.168.1.12:1250 Secure:1 [7.00.210324P] for env: SPED (autoReconnect: 1)
(  40.000s) [querydb         ]  connection_manager.cc:281   | Starting connection to the server 'P12_33_TSS' (192.168.1.12@1250)
(  40.000s) [stdout          ]               timer.cc:42    | [e2e] Message to Client: "[Info] Starting connection to the server 'P12_33_TSS' (192.168.1.12@1250)" took 0.0 ms
(  40.000s) [querydb         ]    security_manager.cc:384   | encodedServerInfo: djM6cXU4YW5ic3Vra2w3YWowaWlsOW9qM2twOHBkbmE6MToxOTIuMTY4LjEuMTI6MTI1MDoxOjcuMDAuMjEwMzI0UDoz
(  40.000s) [stdout          ]               timer.cc:42    | [e2e] Message to Client: "[Info] Starting connection to the server 'P12_33_TSS' (192.168.1.12@1250)" took 0.0 ms
(  40.000s) [querydb         ]    security_manager.cc:471   | done password symmEncrypt (32)
(  40.000s) [querydb         ]    security_manager.cc:474   | done p4U3y2+bhAIYglH7C3fYpUQarxkLWwFOuryLzxqbB4E=
(  40.000s) [querydb         ]    security_manager.cc:479   | encodedLoginInfo: djE6U1BFRDpub3VzZXI6cDRVM3kyK2JoQUlZZ2xIN0MzZllwVVFhcnhrTFd3Rk91cnlMenhxYkI0RT0=
(  40.000s) [querydb         ]  connection_manager.cc:4446  | ConnectionManager::newConnection: 192.168.1.12:1250 (20210324103317) [1] {3}
(  40.000s) [querydb         ]  connection_manager.cc:4450  | connected status: 0
(  40.111s) [querydb         ]  connection_manager.cc:4453  | connected status: 2
(  40.112s) [querydb         ]  connection_manager.cc:4461  | MS_DBGGETBUILD OK
(  40.112s) [querydb         ]  connection_manager.cc:4471  | build: 7.00.210324P
(  40.112s) [querydb         ]  connection_manager.cc:4480  | creating secureContext
(  40.112s) [querydb         ]  connection_manager.cc:4482  | secureContext initialize
(  40.276s) [querydb         ]  connection_manager.cc:4485  | asymmetric generateKeys
(  40.277s) [querydb         ]  connection_manager.cc:4487  | secureContext initialized
(  41.244s) [querydb         ]               timer.cc:42    | [perf] ConnectionManager dbgcheckauth exec took 712.712005 ms
(  41.244s) [querydb         ]  connection_manager.cc:4567  | MS_DBGCHECKAUTH OK
(  41.244s) [querydb         ]  connection_manager.cc:4569  | authRequired 1 for SPED
(  41.244s) [querydb         ]               timer.cc:42    | [perf] ConnectionManager dbgcheckauth processed took 0.56 ms
(  41.244s) [querydb         ]    security_manager.cc:541   | encodedExtraInfo: djI6MTY2MTUyMjQxNToyOjE6MQ==
(  41.260s) [querydb         ]    security_manager.cc:289   | signature hp7HxL4g9734Osm6PSkjvp5ikEXe99FXo8ZKqu5mgw5xCl1W+ZyAEe3ciTztF4wUiYozjzh01knwbcEF2mlJoxKdB9IiPuTb1EgzgqarJhyaK5wwa2d/UMV5bcQYpLGQCBNISdcTM5hqlnrXJ6XHMFbve/0nbYdwPIKMFEszsgfACfBEPM5XfzqjnMjbDb3pcCuQlUVI/OuNztO6Ow0s3uNEZynN/K/R/MIYHge6jOYrR77ysWYJVfm8xn05Pxd8FG3frFn90r9PQPSEQ/eqB+hJwomj1qgi1EHhgU0vkZs1ygyb2mlScVn69d9IuhuBLJmeJNROjn6R8XY1ofbsSg==
(  41.260s) [querydb         ]  connection_manager.cc:320   | Connection to the server 'P12_33_TSS' finished.
(  41.260s) [querydb         ]               timer.cc:42    | [perf] ConnectionManager Connect to server qu8anbsukkl7aj0iil9oj3kp8pdna [1] 192.168.1.12:1250 with environment: SPED => connectionToken: djM6cXU4YW5ic3Vra2w3YWowaWlsOW9qM2twOHBkbmE6MToxOTIuMTY4LjEuMTI6MTI1MDoxOjcuMDAuMjEwMzI0UDoz:djE6U1BFRDpub3VzZXI6cDRVM3kyK2JoQUlZZ2xIN0MzZllwVVFhcnhrTFd3Rk91cnlMenhxYkI0RT0=|djI6MTY2MTUyMjQxNToyOjE6MQ==.hp7HxL4g9734Osm6PSkjvp5ikEXe99FXo8ZKqu5mgw5xCl1W+ZyAEe3ciTztF4wUiYozjzh01knwbcEF2mlJoxKdB9IiPuTb1EgzgqarJhyaK5wwa2d/UMV5bcQYpLGQCBNISdcTM5hqlnrXJ6XHMFbve/0nbYdwPIKMFEszsgfACfBEPM5XfzqjnMjbDb3pcCuQlUVI/OuNztO6Ow0s3uNEZynN/K/R/MIYHge6jOYrR77ysWYJVfm8xn05Pxd8FG3frFn90r9PQPSEQ/eqB+hJwomj1qgi1EHhgU0vkZs1ygyb2mlScVn69d9IuhuBLJmeJNROjn6R8XY1ofbsSg== and needAuthentication=1 took 1260.1259301 ms
(  41.260s) [querydb         ]msg_totvsserver_connect:141   | End Running $totvsserver/connect
(  41.260s) [stdout          ]               timer.cc:42    | [e2e] Message to Client: "[Info] Connection to the server 'P12_33_TSS' finished." took 0.2 ms
(  41.261s) [stdout          ]               timer.cc:42    | [e2e] Message to Client: "[Info] Connection to the server 'P12_33_TSS' finished." took 0.0 ms
(  41.261s) [stdout          ]               timer.cc:42    | [e2e] Running $totvsserver/connect took 1260.1259567 ms
(  44.343s) [querydb         ]msg_totvsserver_authent:48    | Start Running $totvsserver/authentication
(  44.343s) [querydb         ]msg_totvsserver_authent:56    | Authentication to server with connectionToken: djM6cXU4YW5ic3Vra2w3YWowaWlsOW9qM2twOHBkbmE6MToxOTIuMTY4LjEuMTI6MTI1MDoxOjcuMDAuMjEwMzI0UDoz:djE6U1BFRDpub3VzZXI6cDRVM3kyK2JoQUlZZ2xIN0MzZllwVVFhcnhrTFd3Rk91cnlMenhxYkI0RT0=|djI6MTY2MTUyMjQxNToyOjE6MQ==.hp7HxL4g9734Osm6PSkjvp5ikEXe99FXo8ZKqu5mgw5xCl1W+ZyAEe3ciTztF4wUiYozjzh01knwbcEF2mlJoxKdB9IiPuTb1EgzgqarJhyaK5wwa2d/UMV5bcQYpLGQCBNISdcTM5hqlnrXJ6XHMFbve/0nbYdwPIKMFEszsgfACfBEPM5XfzqjnMjbDb3pcCuQlUVI/OuNztO6Ow0s3uNEZynN/K/R/MIYHge6jOYrR77ysWYJVfm8xn05Pxd8FG3frFn90r9PQPSEQ/eqB+hJwomj1qgi1EHhgU0vkZs1ygyb2mlScVn69d9IuhuBLJmeJNROjn6R8XY1ofbsSg== by ADMIN:... for env: SPED
(  44.343s) [querydb         ]  connection_manager.cc:333   | Starting user 'ADMIN' authentication.
(  44.344s) [querydb         ]  connection_manager.cc:4915  | Searching for connection token: djM6cXU4YW5ic3Vra2w3YWowaWlsOW9qM2twOHBkbmE6MToxOTIuMTY4LjEuMTI6MTI1MDoxOjcuMDAuMjEwMzI0UDoz:djE6U1BFRDpub3VzZXI6cDRVM3kyK2JoQUlZZ2xIN0MzZllwVVFhcnhrTFd3Rk91cnlMenhxYkI0RT0=|djI6MTY2MTUyMjQxNToyOjE6MQ==.hp7HxL4g9734Osm6PSkjvp5ikEXe99FXo8ZKqu5mgw5xCl1W+ZyAEe3ciTztF4wUiYozjzh01knwbcEF2mlJoxKdB9IiPuTb1EgzgqarJhyaK5wwa2d/UMV5bcQYpLGQCBNISdcTM5hqlnrXJ6XHMFbve/0nbYdwPIKMFEszsgfACfBEPM5XfzqjnMjbDb3pcCuQlUVI/OuNztO6Ow0s3uNEZynN/K/R/MIYHge6jOYrR77ysWYJVfm8xn05Pxd8FG3frFn90r9PQPSEQ/eqB+hJwomj1qgi1EHhgU0vkZs1ygyb2mlScVn69d9IuhuBLJmeJNROjn6R8XY1ofbsSg==
(  44.344s) [querydb         ]  connection_manager.cc:4920  | Connections thread size: 1
(  44.344s) [stdout          ]               timer.cc:42    | [e2e] Message to Client: "[Info] Starting user 'ADMIN' authentication." took 0.0 ms
(  44.344s) [querydb         ]  connection_manager.cc:4930  | connection pointer address 000001A17090E090
(  44.344s) [querydb         ]  connection_manager.cc:343   | retrievedConnectionThread status 2
(  44.344s) [stdout          ]               timer.cc:42    | [e2e] Message to Client: "[Info] Starting user 'ADMIN' authentication." took 0.0 ms
(  44.344s) [querydb         ]    security_manager.cc:337   | authentic TRUE
(  44.344s) [stdout          ]               timer.cc:42    | [e2e] Message to Client: "[Info] Secure authenticating..." took 0.0 ms
(  44.344s) [stdout          ]               timer.cc:42    | [e2e] Message to Client: "[Info] Secure authenticating..." took 0.0 ms
(  45.444s) [querydb         ]  connection_manager.cc:4771  | MS_DBGPSWADM_SEC OK
(  45.445s) [querydb         ]  connection_manager.cc:4787  | Authentication error: Could not authenticate. Invalid user and/or password.
(  45.445s) [stdout          ]               timer.cc:42    | [e2e] Message to Client: "[Error] Authentication error: Could not authenticate. Invalid user and/or password." took 0.1 ms
(  45.445s) [stdout          ]               timer.cc:42    | [e2e] Message to Client: "[Error] Authentication error: Could not authenticate. Invalid user and/or password." took 0.0 ms
(  45.445s) [querydb         ]               timer.cc:42    | [perf] ConnectionManager Authenticate server error took 1101.1100053 ms
(  45.445s) [querydb         ]msg_totvsserver_authent:117   | End Running $totvsserver/authentication
(  45.445s) [stdout          ]               timer.cc:42    | [e2e] Running $totvsserver/authentication took 1101.1100140 ms
(  45.445s) [stdout          ]               timer.cc:42    | [e2e] Message to Client: "[Error] Authentication failed. Could not authenticate to server." took 0.0 ms
(  45.445s) [stdout          ]               timer.cc:42    | [e2e] Message to Client: "[Error] Authentication failed. Could not authenticate to server." took 0.0 ms

**Comment by lwtnb-wrk** [comment]
@leogr85 O usuario/senha que deve utilizar é o que voce usa para acessar o SIGACFG atraves do Smartclient Desktop.
Aparentemente o AppServer está sendo chamado corretamente, mas o usuário/senha utilzados é inválida.

Se continuar com problemas favor abrir uma nova issue anexando os log gerados https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs

**Comment by brodao** [comment]
Complementado o @lwtnb-wrk, o usuário deve ser admin ou do grupo admin.
