### ISSUE TITLE
One or more files have warnings and/or errors. See problems and logs for details.

### ISSUE THREAD

**Issue by fabiopedroza** [totvs/tds-vscode#356]
Ao tentar compilar está dando as seguintes mensagens:
[Info  - 23:42:53] Starting compile.
[Log   - 00:00:00] Starting build for environment P12.
[Log   - 00:00:00] Start file compile.
[Log   - 00:00:00] Start regular compiling d:/WorkSpaceVS/Totvs/Local/TesteDiversos/Tela_ADVPL/Teste_Tl.prw (1/1).
[Warn  - 23:42:55] Source d:/WorkSpaceVS/Totvs/Local/TesteDiversos/Tela_ADVPL/Teste_Tl.prw precompiled with warnings and/or errors.
[Log   - 00:00:00] Committing end build.
[Warn  - 23:42:55] One or more files have warnings and/or errors. See problems and logs for details.
[Info  - 23:42:55] Compile finished.

launch.json
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Totvs Language Debug",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "D:\\Totvs\\Smartclient_Clientes\\Casa Brasileira\\smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true
		}
	]
}

servers.json

{
	"version": "0.2.0",
	"includes": [
		"D:\\Totvs\\TOTVSV1217\\Protheus\\Include"
	],
	"permissions": {
		"authorizationtoken": ""
	},
	"connectedServer": {
		"name": "CB_HOM",
		"id": "h222fpr3qik9njotmsk95qvvher3e",
		"token": "aDIyMmZwcjNxaWs5bmpvdG1zazk1cXZ2aGVyM2U6Y2FzYWJyYXNpbGVpcmEuZGMuY29hY2hpbmd0ZWNoLmNvbS5icjoyMzAwOjcuMDAuMTMxMjI3QQ==:SE9NT0xPR0FDQU86QURNSU46QnJnc0RNKzdvczRualVOOU9wdCtZM1gzWjZYWkNBS1R4Skw5UWxLeVUwVT0=|MTU4ODI5ODE0OTowOjE=.W/vDxnXTqA/sCptYcmHMUiszmYO4UZ/nYySRt2uuymqtcIXOICrXQ2L4lEc4LEZZveQvI7eSdMX2U0ugUn/IbyewSfPs4NZ6J/jBiAGWevH2FXO1xtecHxSRa0yAH3rLWFL0vcTzAdMxNsOW9kB5Ox9Pg9qbH2J/nHODitJLKZdIKrxgz9xy6YYY0WrtyysSy6qnNhqil1IoX+yxXdtKdFKt8mRm2co9g2iSiIYVo5jF2QJE3f6Ox4NNhgXym0/eCkOkwbdbF6csgAQoE0UCdFRqy2ZdWzKfkHbn1K9lyD6vR2xq7bZLer+P5AV6zmi/yTXqyrgQSAznLqWutR3yTg==",
		"environment": "HOMOLOGACAO"
	},
	"configurations": [
		{
			"id": "kj6j4v04af9k9nj0ec9bjucz4vgtmp",
			"type": "totvs_server_protheus",
			"name": "LOCAL",
			"port": 1234,
			"address": "LOCALHOST",
			"buildVersion": "7.00.131227A",
			"environments": [
				"P12"
			],
			"username": "ADMIN",
			"environment": "P12"
		},
		{
			"id": "h222fpr3qik9njotmsk95qvvher3e",
			"type": "totvs_server_protheus",
			"name": "CB_HOM",
			"port": 2300,
			"address": "casabrasileira.dc.coachingtech.com.br",
			"buildVersion": "7.00.131227A",
			"environments": [
				"HOMOLOGACAO"
			],
			"username": "ADMIN",
			"environment": "HOMOLOGACAO"
		}
	],
	"lastConnectedServer": {
		"name": "CB_HOM",
		"id": "h222fpr3qik9njotmsk95qvvher3e",
		"token": "aDIyMmZwcjNxaWs5bmpvdG1zazk1cXZ2aGVyM2U6Y2FzYWJyYXNpbGVpcmEuZGMuY29hY2hpbmd0ZWNoLmNvbS5icjoyMzAwOjcuMDAuMTMxMjI3QQ==:SE9NT0xPR0FDQU86QURNSU46QnJnc0RNKzdvczRualVOOU9wdCtZM1gzWjZYWkNBS1R4Skw5UWxLeVUwVT0=|MTU4ODI5ODE0OTowOjE=.W/vDxnXTqA/sCptYcmHMUiszmYO4UZ/nYySRt2uuymqtcIXOICrXQ2L4lEc4LEZZveQvI7eSdMX2U0ugUn/IbyewSfPs4NZ6J/jBiAGWevH2FXO1xtecHxSRa0yAH3rLWFL0vcTzAdMxNsOW9kB5Ox9Pg9qbH2J/nHODitJLKZdIKrxgz9xy6YYY0WrtyysSy6qnNhqil1IoX+yxXdtKdFKt8mRm2co9g2iSiIYVo5jF2QJE3f6Ox4NNhgXym0/eCkOkwbdbF6csgAQoE0UCdFRqy2ZdWzKfkHbn1K9lyD6vR2xq7bZLer+P5AV6zmi/yTXqyrgQSAznLqWutR3yTg==",
		"environment": "HOMOLOGACAO"
	},
	"savedTokens": [
.... monte de id token

**Comment by lwtnb-wrk** [comment]
@fabiopedroza Veja https://github.com/totvs/tds-vscode/blob/dev/TROUBLESHOOTING.md e nos envie os logs gerado para analise.
Acredito que o problema ja tenha sido resolvido pelo #329 mas se puder nos enviar o logs podemos confirmar.

**Comment by fabiopedroza** [comment]
Seguem os arquivos.

[WorkSpaceVS.zip](https://github.com/totvs/tds-vscode/files/4575081/WorkSpaceVS.zip)

**Comment by lwtnb-wrk** [comment]
@fabiopedroza Agora que reparei... A mensagem apresentada é apenas de aviso "Warning". O fonte foi compilado com sucesso.
Mas de qualquer forma na visão "Problems" os avisos devem ser sido exibidos...
