### ISSUE TITLE
Erro ao debugar job no vscode.

### ISSUE THREAD

**Issue by Adailton-lanca** [totvs/tds-vscode#357]
Ola. Estou tentando debugar um job em uma rotina utilizando abertura de ambiente (prepare environment), utilizo o nome da rotina que quero debugar na solicitação de função do vscode mas dá a mensagem de erro abaixo, vi uma explicação no TDN (também abaixo) e acredito que meu ambiente já tenha uma estrutura similar, pois estou utilizando uma porta de um serviço slave configurada no smartclient, entretanto ocorre a mensagem e não consigo debugar, e pergunto, como informar ao VSCODE a conexao informada no smartclient pois no "Configure server view" não tem um parametro para informar o nome da conexao que tenho no smartclient.
Erro ocorrido:
debugando jobs error loading debug thread first run application remote alone in file vscode advpl

URL no TDN:
https://tdn.totvs.com/pages/releaseview.action?pageId=271874518

**Comment by lwtnb-wrk** [comment]
@Adailton-lanca Em configurações de Load Balance não se deve utilizar o Master para depurar. A depuração deve ser realizada se conectando em um dos slaves.

**Comment by lwtnb-wrk** [comment]
@Adailton-lanca Somente complementando, acredito que a solução mais fácil no TDS VS Code é cadastrar um dos servidores Slaves e se conectar e depurar diretamente neste servidor.
Veja se consegue depurar com esse procedimento.

**Comment by Adailton-lanca** [comment]
Boa tarde! Como eu informei no enunciado, já estou utilizando um serviço slave e dava o erro que informei, hoje antes de tentar novamente fechei o Folder e abri novamente, funcionou, coincidência ?

**Comment by lwtnb-wrk** [comment]
@Adailton-lanca O TDS VS Code sempre realiza a depuração no servidor atualmente conectado. Se você se conectar no Master e tentar debugar deve ocorrer esse erro. Se você se conectar no Slave o debug deve funcionar como esperado.
Enfim que bom que está funcionado conforme esperado.
