### ISSUE TITLE
Erro ao debugar (F5)

### ISSUE THREAD

**Issue by PatrickZerbinatti** [totvs/tds-vscode#358]
Ao utilizar o F5 para iniciar o protheus ele da o erro abaixo:

![image](https://user-images.githubusercontent.com/33162950/80969446-fed08500-8def-11ea-9afd-7a16c4627c17.png)

segue os logs, basicamente abri o vscode, apertei F5, deu o erro, fechei o vscode.

[totvsls.log](https://github.com/totvs/tds-vscode/files/4574836/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/4574837/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/4574838/totvsls_out.log)

após o erro ele cria esse arquivo nos temporários também, modificando as informações do smarclient:
[smartclient_user_ti02_20728.zip](https://github.com/totvs/tds-vscode/files/4574870/smartclient_user_ti02_20728.zip)

Sabem dizer o que tem de errado? Ontem nós fizemos algumas atualziações de appserver e dbacess.

**Comment by PatrickZerbinatti** [comment]
Obs. Utilizando o smartclient funciona normalmente(após deletar esse arquivo que ele cria).
Obs2. Ctrl+F5 tambem da erro.

**Comment by lwtnb-wrk** [comment]
@PatrickZerbinatti Ele criou o arquivo smartclient.ini com o nome que esta no arquivo em anexo? Onde ele criou este arquivo temporario??
Se possivel no envie o log de depuracao tambem. 
Veja como gerar esse log em https://github.com/totvs/tds-vscode/blob/dev/TROUBLESHOOTING.md

**Comment by PatrickZerbinatti** [comment]
Aqui esta.
[dap.log](https://github.com/totvs/tds-vscode/files/4575535/dap.log)

Ele não criou um smartclient.ini, só esse arquivo que eu mandei em .zip e criou ele na Temp do windows (%temp% no explorador de arquivos)

**Comment by lwtnb-wrk** [comment]
@PatrickZerbinatti Vi pelo log que provavelmente voce utiliza um drive mapeado em Z:, correto?
Se for isso experimente mapear um nivel abaixo para utilizar o caminho, por exemplo, Z:\\\\diretorio\\smartclient.exe
Lembro de ter visto um problema similar ao mapear um drive de rede e utilizar a raiz do drive mapeado.

**Comment by PatrickZerbinatti** [comment]
Fiz o teste, mapeei um nivel acima, mas mesmo assim esta dando o mesmo erro.
Apontamento: "smartclientBin": "W:\\smartclient\\smartclient.exe"
novo dap
[dap.log](https://github.com/totvs/tds-vscode/files/4576121/dap.log)

**Comment by lwtnb-wrk** [comment]
@PatrickZerbinatti essa pasta do smartclient e o arquivo smartclient.ini tem permissão de escrita? o tds-vscode precisa atualizar o smartclient.ini adicionando uma nova seção (_DBG_TEMP). Aparentemente ele não está conseguindo gravar essa configuração, pois no smartclient.ini que é gerado na pasta temporária não tem essa seção.
Se estiver com permissão de escrita e ainda sim não estiver funcionando, tente adicionar manualmente as linhas:

[_DBG_TEMP]
server=localhost
port=61912
SecureConnection=1

no final do smartclient.ini e ajuste o endereço ip do server, a porta e a informação de secureConnection (por padrão é 1 mesmo)

**Comment by PatrickZerbinatti** [comment]
precisa necessariamente ter esse nome? [_DBG_TEMP] ?

**Comment by lwtnb-wrk** [comment]
@PatrickZerbinatti Sim, neste caso em particular é o nome que definimos para que o tds-vscode procure por uma seção apenas usada por ela para se conectar ao smartclient.

**Comment by danielbolognani** [comment]
@PatrickZerbinatti Só para completar, é necessário que a extensão tenha acesso de escrita na pasta do SmartClient, se não, sempre que vc mudar o appserver vai ser necessário alterar na mão o smartlcient.ini.
Faça uma cópia do Smartclient para uma pasta local ao invés de utiliza-lo diretamente de uma pasta na rede, que além de tudo não é recomendado segundo as instruções: https://tdn.totvs.com/display/tec/SmartClient+-+Sistemas+operacionais

**Comment by Redschenko** [comment]
Tive um problema recentemente para debugar no VSCODE e resolvi configurando a chave MultiProtocolPort=0 no ambiente de depuração.

Documentação:
https://tdn.totvs.com/pages/viewpage.action?pageId=538506039

**Comment by lwtnb-wrk** [comment]
@Redschenko Grato pela dica!

Apesar de neste caso em particular aparentemente não é este problema pois no erro que aparece a configuração do servidor/porta estão vazios/invalidos mesmo (server="" e port=65535).

A proposito, estou com um Lobo Guara 19 com o MultiProtocolPort ativo e a depuração ocorre sem problemas. Seu server está configurado com a chave secure=1 para esse servidor? Veja no arquivo servers.json se a chave está ligada ou desligada. Ela precisa estar em sincronia com o AppServer.

**Comment by PatrickZerbinatti** [comment]
Resolvemos, muito obrigado pessoal! 
Colocamos o caminho do smartclientBin por outro lugar, direto no servidor, com IP e tudo mais ai funcionou, realmente é o problema do acesso de escrita. Obrigado novamente.

**Comment by jvvasquesn** [comment]
Boa tarde.
Estou com o mesmo problema.
Estou usando Ubuntu 18.
Coloquei permissão pra tudo e todos na pasta. Ele cria o smartclient.ini mas não inclui o [_DBG_TEMP]
