### ISSUE TITLE
Permitir passagem de parâmetros para a função principal (-A)

### ISSUE THREAD

**Issue by ricardomansano** [totvs/tds-vscode#36]
Permitir passagem de parâmetros para a função principal através do parâmetro -A na chamada do SmartClient

@DanielYampolschi , PSC

**Comment by guilhermebigois** [comment]
No plugin "I Love ADVPL", era só passar os parâmetros no campo que aparecia ao apertar F5, tipo assim: SIGALOJA -A -A=002

**Comment by ricardomansano** [comment]
@brodao acho que a saida que o @guilhermebigois comentou fica elegante, vai ficar guardado depois da execução e vai ser simples de usar. O que acha?

**Comment by brodao** [comment]
@ricardomansano e @guilhermebigois,

Implementei a passagem de parâmetro conforme documentado em https://github.com/totvs/tds-vscode/wiki/Configura%C3%A7%C3%A3o-de-debug:-diretivas-$%7Bcommand:%7D

A disposição.

**Comment by rodrigofelippac** [comment]
A documentação não está abrindo, como fazemos para chamada de parâmetros?

**Comment by lwtnb-wrk** [comment]
O link foi alterado...
Veja a documentacao em https://github.com/totvs/tds-vscode/wiki/Configura%C3%A7%C3%A3o-de-diretivas-no-depurador

**Comment by rodrigofelippac** [comment]
Fiz o procedimento, porém não execura os argumentos, estou tentando passar
a estação para depurar no sigaloja.

Em seg, 1 de jul de 2019 às 13:45, lwtnb-wrk <notifications@github.com>
escreveu:

**Comment by brodao** [comment]
Ola @rodrigofelippac ,

Salvo engano meu, eu vi uma chamada do sigaloja com o 1o. parâmetro vazio, algo como `-a -a=123.
Tente assim, se não funcionar favor enviar o _server.json_ e  _print_ de tela mostrando como informa os parâmetros (se estiver usando a diretiva `${command:AskForProgramArguments}`).

No aguardo,

**Comment by rodrigofelippac** [comment]
Estou usando o  ${command:AskForProgramArguments}`), porém ele não abre a
pergunta de solicitação de parâmetros, só solicita o programa e depois
inicia a aplicação!

Em seg, 1 de jul de 2019 às 20:32, Alan Cândido <notifications@github.com>
escreveu:

**Comment by brodao** [comment]
Ola Rodrigo,

Parece-me que o seu TDS-VSCode não esta atualizado. Verifique se há
atualizações e faça-a.

[:>} Alan Cândido ><>


*Especialista de Pesquisa e DesenvolvimentoExpert Research and Development*
.[====].[====].(----).(----).\___/.[___].]@|--Y\_
 _o__o___o__o___o__o___o__o___o_o___o_o___O___oo_\


Em seg, 1 de jul de 2019 às 23:47, rodrigofelippac <notifications@github.com>
escreveu:
