### ISSUE TITLE
CRIAR SERVERS

### ISSUE THREAD

**Issue by paulokliamca** [totvs/tds-vscode#363]
nao consigo criar servers de maneira nenhuma 

simplesmente nao conecta e nao solicita o ambiente e nem o usuario e nem a senha

**Comment by DanielYampolschi** [comment]
Ola @paulokliamca por favor, nos de mais detalhes do problema:

1 - Alguma mensagem de erro é apresentada em algum momento (Desde a abertura do VsCode)?

2 - De uma olhada no link abaixo e verifique se alguma das propostas resolve teu problema:
https://github.com/totvs/tds-vscode/blob/dev/TROUBLESHOOTING.md

3 - Nos mande prints de tela exemplificando seu problema por favor.

Quanto mais informações você passar, melhor será para identificarmos o problema.

Abraço!

**Comment by paulokliamca** [comment]
1 - NÃO
2- NÃO
3- processo padrão - adiciono um server, coloco o nome IP e includes salvo e tento conectar...

ele nao grava a build e a secure vem como 0
coloco como 1 e ele abre para digitar o ambiente e quando se da o enter ele nao grava no json

![SERVER](https://user-images.githubusercontent.com/64988130/81346120-1ded4200-9090-11ea-8ec3-34598b06fc13.png)

**Comment by paulokliamca** [comment]
![image](https://user-images.githubusercontent.com/64988130/81346340-82100600-9090-11ea-9bbd-2229475fda4b.png)

![image](https://user-images.githubusercontent.com/64988130/81346385-9522d600-9090-11ea-9ff5-4e3af8e011fd.png)

e nao sai disso

**Comment by paulokliamca** [comment]
https://travis-ci.org/github/totvs/tds-vscode

**Comment by lwtnb-wrk** [comment]
@paulokliamca Conforme requisitado anteriormente veja https://github.com/totvs/tds-vscode/blob/dev/TROUBLESHOOTING.md como gerar os logs e nos envie para analise.
Se ao cadastrar um servidor a build esta vazia, ele não conseguiu sequer se conectar ao servidor durante o cadastramento, então certifique-se de que o IP e porta informados estao corretos e nao existe nenhum impedimento como firewall ou anti-virus barrando esta comunicação.
Mas pelos logs poderemos verificar melhor o que pode estar ocorrendo.

**Comment by paulokliamca** [comment]
obrigado consegui resolver

**Comment by lwtnb-wrk** [comment]
@paulokliamca E afinal qual era o problema? 
Se puder informar, veremos se tem algo que podemos fazer no tds-vscode para ajudar a evitar o problema...

**Comment by paulokliamca** [comment]
o problema é que nao aparece nenhuma mensagem na tela que o serviço tinha caído, e quando estava fazendo a documentação para te enviar consegui identificar isso... seria bom um alerta que ele nao encontrou nem serviço ativo, para que ele não crie o server com a build em branco...

**Comment by lwtnb-wrk** [comment]
@paulokliamca Quando voce diz serviço seria o AppServer? Se o AppServer nao estava online durante o cadastro ocorre o erro:
[Error - 09:46:24] Could not connect to server.
E o servidor é criado sem a informação da build conforme voce percebeu.
Porem ao tentar se conectar, se o servidor não tiver a build ele vai tentar detectar essa informacao e se nesse momento o AppServer ja estiver online ele deve detectar e salvar as informações de build e secure que ele não tinha salvo durante o cadastro.
A mensagem de erro "Could not connect to server." não apareceu em nenhum momento?
Vamos alterar a mensagem para "Unable to connect to the server. Check if the IP:port is correct, the server is online and try again." para deixar mais claro, mas acho que não temos mais o que fazer neste caso.

**Comment by paulokliamca** [comment]
a mensagem nao apareceu em nenhum momento, ele simplesmente abria o campo para colocar o ambiente e nao gravava nada .... mas a mensagem ajuda bastante... obrigado
