### ISSUE TITLE
Ao tentar debugar uma User function apresenta Erro de conexão 

### ISSUE THREAD

**Issue by Everson26** [totvs/tds-vscode#364]
![autenticação](https://user-images.githubusercontent.com/64992887/81356690-26517700-90a8-11ea-9a07-c3e06fce042b.png)
Ao tentar compilar uma User Function é apresentado a validação abaixo.

Retrieve connection error: Connection is not authenticated but requires authentication.

![image](https://user-images.githubusercontent.com/64992887/81353185-cbffe880-909e-11ea-8b4d-d3e05132c92a.png)

	"version": "0.2.0",
	"configurations": [

![autenticação](https://user-images.githubusercontent.com/64992887/81356666-19cd1e80-90a8-11ea-91ff-057f31a1fc6a.png)

**Comment by lwtnb-wrk** [comment]
@Everson26 Veja https://github.com/totvs/tds-vscode/blob/dev/TROUBLESHOOTING.md as questoes de falha de conexao.
Se nao resolver gere os logs e nos envie para analise.
