### ISSUE TITLE
Erro ao adicionar servidor - VSCode - TSS

### ISSUE THREAD

**Issue by tatitozzo** [totvs/tds-vscode#367]
**Erro ao adicionar servidor**

Ao adicionar servidor está sendo apresentada a mensagem:  "Cannot read property 'length' of undefined"

**To Reproduce**
Configurar novo servidor: Informado nome, servidor e porta.
Ao salvar é apresentada a mensagem.

**Desktop**
 - OS/Architecture: Windows 64 bits

**Appserver**
* TOTVS - Build 7.00.191205P - Mar 31 2020 - 12:54:19 
* Build: 64 bits
* SVN Revision: 26467
* Build Version: 19.3.0.3

**Additional context**
Trata-se de configuração para aplicação de patch do TSS. Na instalação do TSS não encontrei o diretório include, por tanto não informei diretório de include na configuração do vscode.
A instalação do TSS está em um servidor e o VSCode estou executando em meu desktop, por tanto fiz a cópia do diretório smartclient para minha máquina, para poder informar este smartclient.exe.

Verifiquei que já existe um issue com da mesma situação porém esta está encerrada e o solução não se aplica neste caso.

Grata

**Comment by lwtnb-wrk** [comment]
@tatitozzo Provavelmente o arquivo servers.json foi editado por fora do TDS VS Code ou ocorreu algum problema na salva do arquivo e a estrutura JSON está corrompida.
Veja se consegue identificar o problema, usualmente uma falta ou excesso de virgula, ou uma estrutura [] ou {} faltando abrir/fechar, enfim algo com o JSON. Existem ferramentas online que podem ajudar tambem.
De qualquer forma se nao identificar o problema, voce pode apagar completamente o arquivo servers.json, porem tera que recadastrar todos servidores novamente.
Se isso não resolver o problema veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md como gerar logs e nos envie para analise.

**Comment by tatitozzo** [comment]
@lwtnb-wrk não havia outros servidores configurados pois eu acabei de instalar a extensão e estava configurando o servidor pela primeira vez. Tentei eliminar os arquivos json, reiniciar o VSCode e refazer o processo, porém o problema persiste. Não houve alteração manual dos arquivos json. Percebi agora que o erro apareceu mesmo antes de adicionar um servidor. De qualquer forma gerei os logs conforme orientado. Seguem...
[totvsls.log](https://github.com/totvs/tds-vscode/files/4615621/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/4615622/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/4615623/totvsls_out.log)

**Comment by lwtnb-wrk** [comment]
@tatitozzo Envie o servers.json que esta na pasta .totvsls dentro da sua pasta de usuario para analise tambem.

**Comment by tatitozzo** [comment]
@lwtnb-wrk Segue o arquivo (apenas renomeei como txt para poder fazer o upload)
[servers.json.txt](https://github.com/totvs/tds-vscode/files/4615987/servers.json.txt)

Note que o servidor configurado não chegou a ser salvo, provavelmente devido ao erro.
Eu poderia também fazer um vídeo com o processo todo.

**Comment by lwtnb-wrk** [comment]
@tatitozzo Realmente este arquivo está bem estranho. Se puder fazer o vídeo e enviar seria muito útil para nossas analise.

**Comment by tatitozzo** [comment]
Boa tarde @lwtnb-wrk 

Tentei reinstalar todo o VScode e a extensão, mas o resultado é o mesmo.
Segue o vídeo.
[config-server.zip](https://github.com/totvs/tds-vscode/files/4617587/config-server.zip)

**Comment by lwtnb-wrk** [comment]
@tatitozzo Grato pelos logs e video. Realmente identificamos um problema que está ocorrendo nas primeiras instalações da extensão.
Localize o arquivo "servers.json" que está na pasta ".totvsl" dentro de sua pasta de usuário (C:\Users\seu_usuario).
Utilize este arquivo em anexo (apenas renomeie para .json, pois não foi possível anexar sem alterar a extensão para .txt) no lugar do arquivo existente.
[servers.json.txt](https://github.com/totvs/tds-vscode/files/4617911/servers.json.txt)
Na próxima atualização o problema já estará corrigido.

**Comment by tatitozzo** [comment]
@lwtnb-wrk  Bom dia!

Ótimo! Funcionou, consegui configurar e conectar ao servidor.

Obrigada

**Comment by lwtnb-wrk** [comment]
Apenas mantendo aberto esta issue e redirecionando as ocorrências similares até a liberação da atualização.

**Comment by ricardomansano** [comment]
Boa tarde,
Issue resolvida e disponibilizado hoje na versão 1.0.3 do plugin
At,
