### ISSUE TITLE
Organizar os Server em pastas

### ISSUE THREAD

**Issue by douglasbergamo** [totvs/tds-vscode#368]
Possibilitar colocar os server em pasta, visto que alguns clientes tem mais de um ambiente com portas diferentes de acesso, temos que criar n server para acesso.

**Comment by ricardomansano** [comment]
Boa noite Douglas,
Agradecemos a sugestão, mas ela não sera implementada no momento.
Por se tratar de um produto colaborativo você pode fazer um Fork do projeto e implementar suas próprias melhorias.
Grato pela sugestão
