### ISSUE TITLE
Problema ao tentar gerar cliente WSDL.

### ISSUE THREAD

**Issue by antonioamaury** [totvs/tds-vscode#369]
Problema ao tentar gerar cliente WSDL.

[Error - 14:15:44] One or more validations errors detected:
- Authorization token was not informed.

**To Reproduce**
1. Tentar gerar novo cliente WSDL.
2. CTRL+SHIFT+P
3.TOTVS: GENERATE WS PROTHEUS

![SCREENSHOT](https://user-images.githubusercontent.com/65246703/81725668-8fe0d500-945c-11ea-8aaa-9faae85b3a1a.png)

 - OS/Architecture: Windows 64 bits

* TOTVS - Build 7.00.170117A - Oct 24 2019 - 12:14:41 
* Build: 64 bits
* SVN Revision: 24668
* Build Version: 17.3.0.16
 - OS/Architecture: Windows Server 2012 R2

**Comment by lwtnb-wrk** [comment]
@antonioamaury Grato pelo aviso. Realmente identificamos um problema que será corrigido na próxima atualização.
Para gerar um cliente WSDL enquanto a correção não é disponibilizada edite o arquivo `servers.json ` que esta na pasta `.totvsls` dentro de sua pasta de usuário. Localize a seção "permissions" e adicione este "authorizationToken" conforme abaixo:
```
	"permissions": {
		"authorizationToken": "ZHVtbXk6MDowOjo6MToxNQ==.wlcUgwgGoezgFzjOh3f6REK0dEbSEmD9E2sHylYuMeScLXkZh+UUyKX84HBg5wa9zIJPvzFmrGCfh3wbDb8vQX2FlR+nrSO7mFQ2Va6M7HhQr3Vr+5pBBoP1acG/N90eQFCBftmKz9yGG3bGkomBVfbzf026XdPoiIisgBtpSz5jLVOHVVJNaSJSdIzj9glRmTxP2DozAhtq9LbKSG8gP+Gz7A4NksMM8k6wpEu6wTapCMDLcVy26ZWmfKalUnr7XQxv5aEWK1UeyTVdXmVoSYGeit3OMbgoavgoIejzl/eQXGocQT4O+bMAx9unHOo7Tv2SAvp1ZSWj7Es4CAvJtg=="
	},
```
Veja se assim consegue gerar o cliente WSDL.

**Comment by eduardofm1** [comment]
Boa tarde pessoal,

Estou com o mesmo problema, adicionei a chave authorizationToken porém o erro ainda persiste.
Podem me ajudar?
![image](https://user-images.githubusercontent.com/57256971/81966753-5345e280-95f0-11ea-8430-e1c7075fb384.png)
![image](https://user-images.githubusercontent.com/57256971/81966808-69ec3980-95f0-11ea-824c-2962f7d84cda.png)

**Comment by lwtnb-wrk** [comment]
@eduardofm1 O atributo "authorizationToken" é case-sensitive. Percebi que o "t" do "token" está em letra minúscula e deveria ser maíuscula. Troque para "authorizationToken" que ele deve ser considerado.

**Comment by eduardofm1** [comment]
Deu certo, era isso. Obrigado.

**Comment by AleksSyntek** [comment]
> 
> 
> @antonioamaury Grato pelo aviso. Realmente identificamos um problema que será corrigido na próxima atualização.
> Para gerar um cliente WSDL enquanto a correção não é disponibilizada edite o arquivo `servers.json ` que esta na pasta `.totvsls` dentro de sua pasta de usuário. Localize a seção "permissions" e adicione este "authorizationToken" conforme abaixo:
> 
> ```
> 	"permissions": {
> 		"authorizationToken": "ZHVtbXk6MDowOjo6MToxNQ==.wlcUgwgGoezgFzjOh3f6REK0dEbSEmD9E2sHylYuMeScLXkZh+UUyKX84HBg5wa9zIJPvzFmrGCfh3wbDb8vQX2FlR+nrSO7mFQ2Va6M7HhQr3Vr+5pBBoP1acG/N90eQFCBftmKz9yGG3bGkomBVfbzf026XdPoiIisgBtpSz5jLVOHVVJNaSJSdIzj9glRmTxP2DozAhtq9LbKSG8gP+Gz7A4NksMM8k6wpEu6wTapCMDLcVy26ZWmfKalUnr7XQxv5aEWK1UeyTVdXmVoSYGeit3OMbgoavgoIejzl/eQXGocQT4O+bMAx9unHOo7Tv2SAvp1ZSWj7Es4CAvJtg=="
> 	},
> ```
> 
> Veja se assim consegue gerar o cliente WSDL.

Deu certo para mim que tenho uma configuracao do AppSever LG19.3.0.3 no backoffice é um Appserver 7.00.131227A como servico TSS que tenhia que generar os clientes Ws do fatura eletrónica do Argentina.

**Comment by ricardomansano** [comment]
Boa tarde,
Issue resolvida e disponibilizado hoje na versão 1.0.3 do plugin
At,
