### ISSUE TITLE
Encoding sugerido

### ISSUE THREAD

**Issue by likid** [totvs/tds-vscode#37]
Pessoal, na documentação está sendo informado que o encoding sugerido deve ser o ISO-8859-16, até então eu estava utilizando o Windows-1252 que é o mesmo utilizado no TDS no Eclipse. Ao alterar para o encoding sugerido, os arquivos ficaram com problema nos caracteres especiais e com isso acabei voltando para o Windows-1252. 
Dessa forma, o correto não seria sugerir o uso do encoding Windows-1252?

**Comment by ricardomansano** [comment]
@likid , conversei isso hj a tarde com o time de Frame e eles confirmaram que usam o Windows-1252.
em alinhamento com o @matheus-sales resolvemos fazer o seguinte:
-Criar uma Tag em nosso Json com Windows 1252
-Quando alguem alterar (ex: pra 1251 (cirilico), agente joga essa informacao no nosso Json, respeitando a configuracao do usuario

Vc acha que assim funciona?

**Comment by likid** [comment]
@ricardomansano usar um encoding diferente do Windows-1252 não poderia gerar erros de apresentação dos textos no ERP? Até onde eu conheço o sistema, ele trabalha com este encoding, o ideal seria sugerir que o desenvolvedor sempre use Windows-1252 no meu ponto de vista.

**Comment by ricardomansano** [comment]
@likid , concordo, eu posso sugerir, mas não posso obrigar.
   Se eu forçar a mudança a cada abertura do VS e o analista voltar para o que ele deseja, o plugin acaba sendo um problema, e não uma solução.
   Vamos documentar "com destaque" no Git que o padrão adotado pela TOTVS é o W1252, na esperança que apenas o time da Russia altere, já que precisará do W1251. (@matheus-sales PSC)
   Creio que na próxima semana ja tenhamos essa feature na liberação, amanhã faremos nosso primeiro update com correções/melhorias, fique atento.
Grato pelo apoio,

**Comment by matheus-sales** [comment]
Na abertura do workspace criamos uma opção que o usuário pode definir se deseja alterar o encoding dos fontes advpl para o padrão (Windows1252). Caso aceite, alteramos o encoding apenas para os fontes advpl e o padrão do vscode continua como está. Caso não aceite, na próxima abertura é apresentado a pergunta novamente. Temos também uma opção de não perguntar novamente. 
![encoding](https://user-images.githubusercontent.com/11618741/58332087-e058c000-7e10-11e9-9c97-4c934a127881.PNG)

**Comment by fabiofurlanc** [comment]
@matheus-sales, no vscode usando o W1252 OK, no GITHUB para ver as alterações nos fontes só mostra corretamente se estiver em UTF-8, não achei tem como mudar isso no GITHUB para apresentar o arquivo em W1252 e mostrar os acentos corretamente ?

**Comment by lwtnb-wrk** [comment]
@fabiofurlanc Esta é uma issue muito antiga, se estiver com problemas nas versoes mais atuais do tds-vscode, favor abrir um novo chamdo.

**Comment by lwtnb-wrk** [comment]
@fabiofurlanc Só um ponto, se o problema for na visualização do github isso não tem relação com o tds-vscode e o encoding utilizado nos fontes AdvPL/4GL.
