### ISSUE TITLE
Configuração de Novo Servidor

### ISSUE THREAD

**Issue by GersonBelini** [totvs/tds-vscode#370]
Ao finalizar a configuração de um novo servidor, quando salvo, recebo a mensagem:

Cannot read property 'length' of undefined
[ScreenHunter 128.zip](https://github.com/totvs/tds-vscode/files/4617698/ScreenHunter.128.zip)

**Comment by lwtnb-wrk** [comment]
@GersonBelini Grato por informar. Realmente identificamos um problema que está ocorrendo nas primeiras instalações da extensão.
Localize o arquivo "servers.json" que está na pasta ".totvsl" dentro de sua pasta de usuário (C:\Users\seu_usuario).
Utilize este arquivo em anexo (apenas renomeie para .json, pois não foi possível anexar sem alterar a extensão para .txt) no lugar do arquivo existente.
[servers.json.txt](https://github.com/totvs/tds-vscode/files/4617885/servers.json.txt)
Na próxima atualização o problema já estará corrigido.

**Comment by GersonBelini** [comment]
Substituímos o arquivo e conseguimos efetuar a configuração.

Muito grato pelo apoio.
