### ISSUE TITLE
Senha não fica salva

### ISSUE THREAD

**Issue by likid** [totvs/tds-vscode#371]
Sempre que é feito a alteração de ambiente, mesmo com o token salvo no servers.json, a extensão está solicitando o usuário e senha do ambiente novamente. Fiz a exclusão de todos os tokens salvos e mesmo assim após informar a primeira vez o usuário e senha, ao alternar para o mesmo ambiente novamente ele solicita as informações.
Isso começou após a versão 1.0.1. Estou usando a versão 1.0.2.

**Comment by lwtnb-wrk** [comment]
@likid Você está usando o Connect ou Reconnect?
Veja essa nova funcionalidade em https://github.com/totvs/tds-vscode/#conex%C3%A3o-vs-reconex%C3%A3o

**Comment by likid** [comment]
@lwtnb-wrk nenhum dos dois, apenas clico na conexão atual na barra embaixo e seleciono o outro ambiente que desejo conectar. Provavelmente a ação tomada nesta opção está sendo a de connect pois o comportamento está igual, segundo a documentação que você informou.

**Comment by lwtnb-wrk** [comment]
@likid Realmente a ação tomada ao clicar na barra inferior é a de Connect e portanto vai requisitar o usuário/senha. Vamos alterar para Reconnect pois faz mais sentido mesmo.
Se o usuário quiser explicitamente um Connecte sera apenas pelo menu de contexto. Vamos assumir que o uso da barra inferior é para agilizar o processo e portanto o Reconnect faz mais sentido.
Na próxima atualização já deverá ter este novo comportamento.
Grato pelo aviso

**Comment by ricardomansano** [comment]
Boa tarde,
Issue resolvida e disponibilizado hoje na versão 1.0.3 do plugin
At,

**Comment by likid** [comment]
@ricardomansano @lwtnb-wrk este problema aparentemente voltou na release 1.0.6. A ação novamente está como connect ao invés de reconnect.

**Comment by marciorollo** [comment]
Sim, está solicitando usuário e senha novamente.

**Comment by ricardomansano** [comment]
Bom dia,
@leowww , 
Da uma olhada depois pfv.

**Comment by brodao** [comment]
Encerrado pois não foi reproduzido na versão 1.0.6.

**Comment by likid** [comment]
Alan, discordo, estou com a versão 1.0.6 aqui e ao fazer a alteração do ambiente clicando na barra inferior, a ação é de CONNECT e não RECONNECT e isso faz com que sempre seja solicitado a senha novamente.

**Comment by likid** [comment]
Fiz um gif mostrando o problema. @brodao @ricardomansano 

![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/10984007/94917218-85b08900-0486-11eb-98f5-2125eeec672b.gif)

**Comment by brodao** [comment]
Ola @likid 

Reproduzi a sua ocorrência, quando a conexão com o último servidor esta desabilitada. 
Por um acaso é o seu caso?
![image](https://user-images.githubusercontent.com/949914/94928402-01680100-049a-11eb-9f71-4655857429bd.png)
De qualquer forma, vou iniciar a correção.

Grato pelo apoio.

**Comment by likid** [comment]
@brodao aqui esta opção está habilitada. Como mencionei na issue, o problema havia sido corrigido e acabou voltando quando liberaram a versão 1.0.6.

**Comment by brodao** [comment]
@likid 

> @brodao aqui esta opção está habilitada. 

Aqui,  na verdade, foi uma sequencia de operações que fez com que eu reproduzisse o erro.
Já arrumei e vai estar disponível na próxima liberação.

Grato.
