### ISSUE TITLE
Como executar o debug chamando a aplicação como SIGAMDI por exemplo

### ISSUE THREAD

**Issue by sheila-araujo77** [totvs/tds-vscode#372]
Como executar o debug chamando a aplicação como SIGAMDI por exemplo. Pois preciso executar a analise de um fonte com variaveis nativas.

**Comment by lwtnb-wrk** [comment]
@sheila-araujo77 Até onde entendo não existe a necessidade de se debugar com SIGAMDI.
Alias você sempre deve debugar diretamente no modulo, por exemplo, SIGAFAT e ter acesso a todas as variaveis visiveis na depuracao.
Se este nao for o caso explique melhor o que deseja realizar.

**Comment by sheila-araujo77** [comment]
Desculpe, seria no modulo direto, não sei como fazer essa configuracao ou chamada via vscode.

**Comment by lwtnb-wrk** [comment]
@sheila-araujo77 Ao iniciar uma depuração o tds-vscode pede o programa a ser executado. Basta indicar SIGAFAT por exemplo e a depuração será realizada diretamente neste módulo.
https://github.com/totvs/tds-vscode/#iniciando-um-debug

**Comment by ricardomansano** [comment]
Boa tarde,
Dado prazo sem resposta acredito que o problema tenha sido resolvido
Ficamos a disposição
