### ISSUE TITLE
Cannot read Property ‘length’ of undefined - Update VSCode 1.45.0

### ISSUE THREAD

**Issue by maximinocastro** [totvs/tds-vscode#373]
Bom dia Prezados,

Estou instalando o VsCode + Plugin em uma maquina nova porém após toda instalação, ao tentar adicionar um server estou recebendo a seguinte mensagem (**Cannot read Property ‘length’ of undefined**).

Mas em uma outra maquina que já tenho o VSCode com o Plugin e já foi atualizado não tenho esse problema consigo adicionar.

Acredito que esse BUG é só para usuários novos.

Att.

Mike

**Comment by lwtnb-wrk** [comment]
@maximinocastro Este problema já foi relatado e corrigido na issue #367
A correcao sera disponibilizada na proxima atualizacao mas veja nessa issue como realizar uma correcao de contorno para seguir com a utilizacao do tds-vscode.
Grato pelo aviso.
