### ISSUE TITLE
Erro ao adicionar servidor

### ISSUE THREAD

**Issue by ronaldotapia** [totvs/tds-vscode#374]
** Erro ao adicionar servidor **

Mensagem: Cannot read property 'length' of undefined
Teste realizado em máquina nova, sem nenhuma instalação anterior. Tentei em duas máquinas diferente e ocorre o mesmo erro.

Por favor, podem ajudar?

**Comment by lwtnb-wrk** [comment]
@ronaldotapia Realmente este problema foi relatado, corrigido e sera disponibilizado na próxima atualização.
Uma solução paliativa esta disponível em #367.
Grato pelo aviso
