### ISSUE TITLE
Erro ao adicionar servidor

### ISSUE THREAD

**Issue by juliano-melo** [totvs/tds-vscode#375]
Bom dia.
Ao tentar adicionar o servidor ocorre um erro: "Cannot read property 'lenght' of udefined".

Após abrir o VSCode, acessar do lado esquerdo o plugin da Totvs, na aba Servers, clica-se no sinal de +. Preenche os dados, nome do servidor, endereço, porta e o caminho do include. Ao clicar em Save/Close, ocorre o erro mencionado acima e o servidor não é adicionado.

**Comment by lwtnb-wrk** [comment]
@juliano-melo Este problema já foi relatado e corrigido na issue #367
A correção sera disponibilizada na próxima atualização mas veja nessa issue como realizar uma correção de contorno para seguir com a utilização do tds-vscode.
Grato pelo aviso.
