### ISSUE TITLE
Erro configuração ambiente

### ISSUE THREAD

**Issue by loucarvalho** [totvs/tds-vscode#376]
ao configurar o VSCod, depois de baixar e instalar a extensão Totvs Devevolper Studio for VSCode
a mensagem abaixo aparece ao tentar criar o ambiente.
Cannot read property 'length' of undefined

isso ocorreu na versão 1.0.2
baixei outra e funcinou, mas essa fica aparecendo essa mensagem e nao deixa eu criar o server

**Comment by lwtnb-wrk** [comment]
@loucarvalho Este problema já foi relatado e corrigido na issue #367
A correção sera disponibilizada na próxima atualização mas veja nessa issue como realizar uma correção de contorno para seguir com a utilização do tds-vscode.
Grato pelo aviso.
