### ISSUE TITLE
Problema ao criar launchers a partir das configurações do Smartclient na inicialização

### ISSUE THREAD

**Issue by leowww** [totvs/tds-vscode#377]
**Describe the bug**
Problema ao criar launchers a partir das configurações do Smartclient na inicialização

**To Reproduce**
Selecione um smartclient na tela de boas vindas e salve. Os launchers não estão sendo gerados corretamente.

**Expected behavior**
Que os launchers sejam gerados a partir das configurações do smartclient indicado.

**Screenshots**

**Desktop (please complete the following information):**
 - OS/Architecture: Windows 64 bits

**Appserver (please complete the following information):**
 - Não aplicável

**Additional context**

**Comment by ricardomansano** [comment]
Boa tarde,
Issue resolvida e disponibilizado hoje na versão 1.0.3 do plugin
At,
