### ISSUE TITLE
Tela de Welcome não abre para configurar o VSCode

### ISSUE THREAD

**Issue by dwb-ti** [totvs/tds-vscode#379]
**Describe the bug**
O VSCode foi instalado normalmente, instalei a extensão da TOTVS e após a instalação não apareceu a tela para configurar a pasta do smartclient e a pasta include

**Desktop (please complete the following information):**
Windows Server 2019 64 bits

Windows Server 2019 64 bits
Build AppServer: 7.00.191205P-20200331 - 64 bits
Appserver version: 19.3.0.3
Build DBAccess: 20191119-20200217
Release do RPO:  12.1.025
Release do dicionário: 12.1.025
Local files: ctree
DB DataBase: MSSQL
DB API Build: 20191119-20200116
Remote build: 7.00.191205P-20200413
Remote version: 19.3.0.3

**Comment by lwtnb-wrk** [comment]
@dwb-ti É uma nova instalação ou reinstalação? A pasta/projeto utilizado já havia sido utilizada anteriormente pelo TDS VS Code?
Abra o menu File > Preferences > Settings (ou `CTRL + ,`) e procure em Extensions a seção AdvPL.
Nela localize a última opção "Welcome Page" e verifique se ela está desmarcada (Pode estar desmarcada no Workspace também).
Marque esta opção e reinicie o TDS VS Code. A tela de Welcome deve ser exibida.

**Comment by dwb-ti** [comment]
lwtnb-wrk é uma instalação nova! A opção do Welcome Page já estava selecionada.

**Comment by lwtnb-wrk** [comment]
@dwb-ti Agora que reparei que seu SO eh um Windows Server. Temos diversos relatos de problemas com este SO e não aconselhamos o uso do TDS VS Code neste SO.
Não tenho como testar nesse SO aqui pois tenho um Windows 10...

**Comment by dwb-ti** [comment]
lwtnb-wrk é que este é o meu servidor do protheus, no caso tenho que deixar instalado em uma estação então?

**Comment by lwtnb-wrk** [comment]
@dwb-ti Acreditamos que no Windows Server faltem DLLs que existem somente nas versões Desktop e por isso algumas funcionalidades falham.
Sim, se possível utilize o TDS VS Code em uma estação com um Windows (Desktop).

**Comment by dwb-ti** [comment]
instalei no meu note e a tela para configurar o smartclient também não apareceu .. tem algum caminho para abrir essa tela ou forçar a configuração ?

**Comment by lwtnb-wrk** [comment]
@dwb-ti São apenas aquelas configurações que já mencionei.
Mas as configurações do smartclient podem ser realizadas de outras formas.

O cadastro de servidores pode ser feito individualmente na visão de servidores (clicar no "+" e preencher os dados do servidor).

A configuração de includes pode ser feita acionando `CTRL + SHIFT + P` e procurando por `TOTVS: Include`

Os launchers para depuração podem ser feitos acionando `CTRL + SHIFT + P` e procurando por  `TOTVS: Configure Launchers`

Com isso será possível se conectar ao servidor, desenvolver e compilar seus fontes, ou aplicar os patches.

**Comment by SimoesTec** [comment]
Bom dia, estou com o mesmo erro, é uma instalação antiga que teve o VSCode atualizado para a versão 1.45.1.

Instalação do VSCode do zero e instalando a extensão ocorre o mesmo erro, verifiquei que a versão do VSCode 1.45.0 esta funcionando corretamente.

Utilizo o Windows 10.

**Comment by SimoesTec** [comment]
Segue mais informações sobre o erro:

Versão do VSCode
Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

Versão do Totvs Developer
1.0.2

Em uma instalação do ZERO, ocorre o erro:
command 'totvs-developer-studio.add' not found

![Capturar1](https://user-images.githubusercontent.com/64440671/82225002-9525a000-98f2-11ea-9477-e27895de771b.PNG)
![Capturar2](https://user-images.githubusercontent.com/64440671/82225007-9656cd00-98f2-11ea-9691-a03559467196.PNG)
![Capturar3](https://user-images.githubusercontent.com/64440671/82225009-96ef6380-98f2-11ea-9bf1-dbef473493a5.PNG)
![Capturar4](https://user-images.githubusercontent.com/64440671/82225012-96ef6380-98f2-11ea-9fa6-53f8c5292ff7.PNG)

**Comment by dwb-ti** [comment]
> @dwb-ti São apenas aquelas configurações que já mencionei.
> Mas as configurações do smartclient podem ser realizadas de outras formas.
> 
> O cadastro de servidores pode ser feito individualmente na visão de servidores (clicar no "+" e preencher os dados do servidor).
> 
> A configuração de includes pode ser feita acionando `CTRL + SHIFT + P` e procurando por `TOTVS: Include`
> 
> Os launchers para depuração podem ser feitos acionando `CTRL + SHIFT + P` e procurando por `TOTVS: Configure Launchers`
> 
> Com isso será possível se conectar ao servidor, desenvolver e compilar seus fontes, ou aplicar os patches.

não funciona, ao clicar no + para adicionar o servidor aparece a mensagem command 'totvs-developer-studio.add' not found .. ao fazer a pesquisa .. não abre a página pesquisada. Já desinstalei e instalei novamente e nada.

**Comment by dwb-ti** [comment]
todas as pesquisas retornam o seguinte no final: resultou em um erro (command 'totvs-developer-studio.config' not found)

**Comment by ESCFLA** [comment]
Fizemos um teste aqui e conseguimos conectar. Pegamos o arquivo servers.json de um PC que está funcionando, jogamos dentro da pasta C:\Users\user\.totvsls e funcionou.

Com os passos do @lwtnb-wrk , desativei a opção "Welcome Page" no User e Workspace, fechei o VSCode, add no servers.json, aí foi.

Abraços


Elmo Costa.

**Comment by DanielYampolschi** [comment]
Pessoal, por favor atualizem o plugin para a última versão: 1.0.3, onde esse problema deve ter sido corrigido.
Obrigado.

**Comment by ricardomansano** [comment]
Boa tarde,
Correção aplicada na versão 1.0.3 do plugin.
