### ISSUE TITLE
Permitir visualizar o conteúdo de um patch antes de aplicar

### ISSUE THREAD

**Issue by VctrAndrade** [totvs/tds-vscode#38]
Deveria ser possível visualizar o conteúdo de um patch antes de aplicar, igualmente o TDS disponibilizava.

**Comment by ricardomansano** [comment]
@VctrAndrade , bacana, valew a dica

**Comment by matheus-sales** [comment]
@VctrAndrade Funcionalidade implementada. Acionamento via CTRL + SHIFT + P + "TOTVS: Patch Inspector".

Colocaremos na documentação.

Vou criar mais uma opção de acionamento via menu de contexto em arquivos ".ptm".
