### ISSUE TITLE
NÃO CONECTA AMBIENTE SPED NO VSCODE

### ISSUE THREAD

**Issue by RodrigoTeixeira-2101** [totvs/tds-vscode#380]
Olá,
Estou tentando conectar no ambiente SPED para aplicar um patch no TSS TOTVS, mas, não conecta de nenhuma maneira no VSCODE conforme msg abaixo:

"[Log   - 00:00:00] Starting connection to the server 'SPED' (localhost@5060)
[Log   - 00:00:00] Connection to the server 'SPED' finished.
[Log   - 00:00:00] Starting user 'ADMIN' authentication.
[Log   - 00:00:00] Secure authenticating...
[Error - 08:54:20] Authentication error: Could not authenticate. Invalid user and/or password.
[Error - 08:54:20] Authentication failed. Could not authenticate to server."

PS. Ao utilizar o smartclient a conexão acontece sem nenhum problema no ambiente, só não funciona o VSCODE.

Att
Rodrigo Teixeira

**Comment by DanielYampolschi** [comment]
Ola @RodrigoTeixeira-2101 por favor verifique o "troubleshooting" em https://github.com/totvs/tds-vscode/blob/dev/TROUBLESHOOTING.md e veja se resolve seu problema.
Caso não seja resolvido, por favor também veja nesse mesmo link como gerar os logs e no envie para analise.

**Comment by RodrigoTeixeira-2101** [comment]
Ola Daniel, 
Obrigado pelo retorno!
Abaixo estão as versões das aplicações e os logs.
Continuo não conseguindo a conexão ao ambiente SPED TSS para aplicar patchs no repositorio do TSS.

Versão: Commit de 1.45.1 
(user setup): 5763d909d5f12fe19f215cbfdd29a91c0fa9208a 
Data: 2020-05-14T08:27:35.169Z 
elétron: 7.2.4 
Chrome: 78.0.3904.130 
node. js: 12.8.1 V8: 7.8.279.23-electron.0 
OS: Windows_NT x64 6.3.9600


Totvs Developer Studio for VSCode (AdvPL, TLPP e 4GL)
totvs.tds-vscode
TOTVS
30.082
Repositório
Licença
1.0.2
[totvsls.log](https://github.com/totvs/tds-vscode/files/4645757/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/4645760/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/4645761/totvsls_out.log)

Grato!
Rodrigo Teixeira

**Comment by DanielYampolschi** [comment]
Obrigado pelas informações @RodrigoTeixeira-2101 .

Pelos logs foi possível verificar que é o servidor quem não está conseguindo fazer a autenticação, retornando um código de autenticação inválida. 

Os logs não informam qual a versão da build do seu servidor, mas mesmo assim, por favor, tente logar novamente desabilitando o SSL:

Altere/Defina ao arquivo servers.ini:
`[Drivers]
Active=TCP
MultiProtocolPortSecure=0
MultiProtocolPort=0
`
Alterar também a flag `"secure": 0` no 'servers.json' deste AppServer

**Comment by RodrigoTeixeira-2101** [comment]
Bom dia Daniel, 
Obrigado pelo pronto atendimento.
Então amigo, fiz a alteração e mesmo assim não conecta.
Vou avaliar se existe alguma atualização do instalador do TSS para ver se resolve.

Obrigado!
Rodrigo Teixeira

**Comment by RodrigoTeixeira-2101** [comment]
Olá Daniel, 
Verifiquei aqui que já estamos com a ultima instalação do TSS em nosso ambiente, portanto, não existem como atualizar via instalador, ou seja, não temos como aplicar patchs por nao conseguir conexão e não temos atualização via instalador.
FIM!

**Comment by RodrigoTeixeira-2101** [comment]
Esta é a release do TSS....

![release smartclient tss](https://user-images.githubusercontent.com/65543451/82331619-c073c200-99ba-11ea-8e80-c699d5554c65.jpg)

**Comment by DanielYampolschi** [comment]
Ola @RodrigoTeixeira-2101, verifiquei mais uma vez o log que voce enviou, e não parece ter nenhum outro problema a não ser as informações de autenticação que estão sendo enviadas para o servidor. 

Faz um teste por favor, exclua os servidores cadastrados e remova as entradas de "lastConnectedServer" e "savedTokens" conforme a image abaixo:
![image](https://user-images.githubusercontent.com/10711513/82341274-958f6b00-99c6-11ea-8677-19c0d9653b64.png)

Atenção nesse processo para que o json não fique faltando virgula ou fechar alguma chave ou colchete. No final, teu servers.json deve ficar como (Se preferir, copie e cole o trecho abaixo):

`
{
	"version": "0.2.0",
	"includes": [
	],
	"permissions": {
		"authorizationtoken": ""
	},
	"connectedServer": {},
	"configurations": []
}
`

Cadastre novamente seu servidor e verifique se a autenticação é efetuada. Em caso negativo, sugiro verificar com o administrador do servidor se as informações de login que você tem estão realmente corretas.

Abraço.

**Comment by ricardomansano** [comment]
Boa tarde,
Correção aplicada na versão 1.0.3 do plugin.

**Comment by RodrigoTeixeira-2101** [comment]
Bom dia Ricardo Mansano,

Plugin reinstalado e continua não conectando ao ambiente SPED do TSS.

Att
Rodrigo Teixeira

**Comment by ed-gouvea** [comment]
Tenho o mesmo problema... VSCODE não conecta no ambiente SPED do TSS.

**Comment by lwtnb-wrk** [comment]
@RodrigoTeixeira-2101 @ed-gouvea Vocês conseguem entrar nesse ambiente utilizando um Smartclient comum, sem ser o Smartclient do TSS?
Ocorre alguma mensagem de erro no console ao tentar logar pelo Smartclient comum?

**Comment by blogadvpl** [comment]
Boa tarde, estou com o mesmo problema, não consigo fazer o vscode se conectar ao ambiente do TSS, alguem conseguiu resolver? 

No smartclient do TSS ok, no smartclient comum ocorre "Checksum: Erro no checkSum do registro, verifique com o admnistrador."

**Comment by lwtnb-wrk** [comment]
@RodrigoTeixeira-2101 @ed-gouvea @blogadvpl 
O TSS é um serviço que apenas realiza a interface entre sistemas e não possui nenhum tipo de ponto de entrada para customizações então pelo que entendo não faz sentido tentar se logar no TSS...
O que exatamente estão tentando realizar ao tentar se conectar no TSS??

**Comment by rodrigolparaujo** [comment]
Bom dia, preciso compilar um patch no RPO do TSS, porém estou com problema para me conectar neste repositório.

Copiei o arquivo tttp120.rpo do TSS para a minha pasta no qual faço referencia no meu arquivo appserver.ini

`[NFE]
SourcePath=D:\Microsiga\MP12HOMOLOGA\APONFE
RootPath=D:\Microsiga\MP12HOMOLOGA\protheus_data
FormPath=D:\Microsiga\MP12HOMOLOGA\rpoform
StartPath=\system\
x2_path=
RpoDb=TOP
RpoLanguage=Portuguese
RpoVersion=120
LocalFiles=ctree
localdbextension=.dtc
RepositInDataBase=1
PictFormat=DEFAULT
DateFormat=DEFAULT
helpserver=10.224.192.21:9079
Specialkey=MP12PRCHOM
TOPMEMOMEGA=1
MaxStringSize=30`

Ao tentar me conectar, no ambiente, o vscode apresenta a mensagem:
[Info  - 08:48:44] Starting connection to the server 'Produção Balance 1' (10.224.192.21@1243)
[Info  - 08:48:45] Connection to the server 'Produção Balance 1' finished.
[Info  - 08:48:50] Starting user 'admin' authentication.
[Info  - 08:48:50] Secure authenticating...
[Error - 08:48:52] Authentication error: Server returned a non numeric value.
[Error - 08:48:52] Authentication failed. Could not authenticate to server.

Consigo me conectar normalmente nos outros ambientes que tenho. Preciso atualizar meu RPO do TSS, mas não consigo me conectar para aplicar o patch.

**Comment by lwtnb-wrk** [comment]
@rodrigolparaujo Eu falei com o pessoal do TSS e ele pediram que entre em contato com o Suporte da TOTVS que eles devem te orientar em como proceder para aplicar um patch no TSS. Eu realmente não tenho essa informação para te passar neste momento.
Somente para informar, pelo que entendi do TSS ele realmente não foi "feito" para que um usuário se conecte e customize o TSS e portanto não tem a função necessária para a autenticação nele e por isso a autenticação falha [Authentication error: Server returned a non numeric value.].

**Comment by rodrigolparaujo** [comment]
A orientação que tenho do suporte é abrir chamado aqui 
[TOTVS] Solicitação nº 10016692 (Compilar patch em repositorio do TSS)

> Olá,
> 
> Todas as dúvidas e erros referente a extensão TOTVS Developer Studio for VS Code, devem ser direcionadas ao canal oficial
> https://github.com/totvs/tds-vscode
> 
> Segue abaixo link  para abertura de chamados referente ao plugin TOTVS Developer Studio :
> https://github.com/totvs/tds-vscode/issues
> 
> Segue abaixo documentação
> MP - ADVPL - VSCODE:
> 
> Atenciosamente,
> Eduardo Paro de Simoni
> EQUIPE DE SUPORTE TÉCNICO ADVPL
>

**Comment by lwtnb-wrk** [comment]
@rodrigolparaujo Excelente, então deu deadlock!!! Vou verificar com o TSS qual seria a real solução para se aplicar patches no TSS.

**Comment by rodrigolparaujo** [comment]
> @rodrigolparaujo Excelente, então deu deadlock!!! Vou verificar com o TSS qual seria a real solução para se aplicar patches no TSS.

ok, fico no aguardo. obrigado

**Comment by ed-gouvea** [comment]
Gente, a solução é simples. Enquanto no Smartclient você precisa usar login admin e senha admin, no vs-code pra aplicar o patch no TSS é só usuário admin sem senha.

**Comment by ricardomansano** [comment]
Bom dia, 

@ed-gouvea , não é tão simples...

@leowww , me passa segunda com quem vc falou do TSS, vou fupar o assunto.

@rodrigolparaujo , vou conversar com o Eduardo Paro de Simoni pra entender esse direcionamento, se conseguir me colocar de listener no chamado (caso ainda nao tenha sido fechado), dá um reply pra mansano@totvs.com.br pfv

**Comment by lwtnb-wrk** [comment]
@RodrigoTeixeira-2101 @blogadvpl @rodrigolparaujo Conseguem testar a orientação do @ed-gouvea se logar usando "admin" sem senha?

@ricardomansano Faz sentido essa questão, pois o @ed-gouvea relatou problema para acessar o TSS também e segundo ele utilizando o usuário "admin" e senha em branco ele conseguiu se conectar ao TSS, então é possível que os outros usuários estão tentado se conectar com seus respectivos usuários do TSS, mas que não são validados corretamente pelo PSWADMIN e somente o usuário "admin" é validado corretamente.

**Comment by rodrigolparaujo** [comment]
bom dia, testei com o usuário admin sem senha e não funcionou. consigo conectar em qualquer outro RPO, menos no RPO do TSS.
[Info  - 08:53:27] Starting connection to the server 'Homologação Balance 1' (10.224.192.21@5243)
[Info  - 08:53:28] Connection to the server 'Homologação Balance 1' finished.
[Info  - 08:53:34] Starting user 'admin' authentication.
[Info  - 08:53:34] Secure authenticating...
[Error - 08:53:36] Authentication error: Server returned a non numeric value.
[Error - 08:53:36] Authentication failed. Could not authenticate to server.

Segue meu RPO do TSS (https://we.tl/t-jhX5giJ2g2) e o meu appserver.ini, este RPO foi enviado tempos atras pelo suporte corrigindo um outro problema que eu tinha e agora é a primeira vez que vou compilar uma atualização e não consigo.

[appserver.zip](https://github.com/totvs/tds-vscode/files/5438661/appserver.zip)

att,

**Comment by ricardomansano** [comment]
Bom dia,

Ja respondi ao chamado @rodrigolparaujo , preciso saber quais as funções disponiveis no RPO do TSS pra que nós usemos.

Como não conseguiu se validar com Admin "sem senha" é sinal que temos um Cadastro de Usuários, precisamos entender como esta disponivel este cadastro pra que haja segurança na aplicação de patch apenas por pessoas autorizadas, e que vc consiga trabalhar.

Devemos ter novidades no decorrer dos dias

**Comment by lwtnb-wrk** [comment]
@rodrigolparaujo Reparei na documentação do TSS que indica que o 1o acesso deve ser feito com o usuário "admin", mas com a senha "admin" e que será requisitada a alteração dessa senha... Poderia ver se consegue acessar com esse usuário/senha?

Se esse usuário/senha não funcionar, suspeito que o RPO enviado pelo Suporte pode conter algum outro usuário/senha diferente desses que são padrão inicial da TOTVS.

Peço que realize um backup de seu RPO e pegue um RPO zerado do site de Suporte da TOTVS e veja que deve conseguir se logar e acredito que a ultima versão do RPO, de 19/10/2020, inclusive deva conter o patch que esteja tentando aplicar.

**Comment by brodao** [comment]
Senhores,

Há um bom tempo atrás, em determinadas versões da LIB FW, não era permitida conexão do TDS usando "admin". 
Tinha que usar um usuário, que não o "admin" e que este fosse ao grupo "admin". Não poderia ser o caso do TSS? 

A disposição

**Comment by rodrigolparaujo** [comment]
@lwtnb-wrk baixei o RPO do portal e consegui me conectar nele com o meu **usuario** e **senha**,  e já consegui aplicar os patchs.

Então com certeza, o RPO enviado pelo suporte, que impediu a minha conexão.

[Info  - 10:34:03] Starting connection to the server 'Homologação Balance 1' (10.224.192.21@5243)
[Info  - 10:34:04] Connection to the server 'Homologação Balance 1' finished.
[Info  - 10:34:09] Starting user '**raraujo**' authentication.
[Info  - 10:34:09] Secure authenticating...
[Info  - 10:34:11] **User authenticated successfully.**
[Info  - 10:34:11] User '**raraujo**' authentication finished.
[Info  - 10:35:46] Starting apply patch.
[Info  - 10:35:46] Starting build for environment NFE.
[Info  - 10:35:46] Applying patch file: c:/Users/admroar/AppData/Local/Temp/2/tds-ZG4Hdw/9283728_dsertss2-6641_12.1.25_tttp120_lg.ptm
[Info  - 10:35:46] Patch (9283728_dsertss2-6641_12.1.25_tttp120_lg.ptm) successfully applied.
[Info  - 10:35:46] Committing end build.
[Info  - 10:35:46] Apply patch finished.

obrigado a todos.

**Comment by ricardomansano** [comment]
@rodrigolparaujo , grato pelo retorno

Vou pedir a gantileza que documente isso no chamado, isso ajudara o Suporte em futuros direcionamentos, vou conversar tbem com o PO do TSS a respeito

Grato  a todos que participaram deste apoio

**Comment by diegobt88** [comment]
Boa tarde!
Estou enfrentando o mesmo problema do Rodrigo!

Porém estou com a versão do TDS Vscode 1.2.2

Quando tento me logar para compilar um patch no RPO do TSS versão 12.1.27 ele da esta msg.
![image](https://user-images.githubusercontent.com/67063754/113439331-c00ccb80-93c0-11eb-8430-f40b6dbcdffc.png)

E acessando via smartclient com o USER "ADMIN" vai normalmente. Já tentei até criar um user e mesmo assim o erro persiste!

Preciso aplicar o patch para atualizar o eSocial!
