### ISSUE TITLE
VS Code como excluir somente um ambiente sem excluir o server ?

### ISSUE THREAD

**Issue by decomoldemaq** [totvs/tds-vscode#381]
Att!

Preciso saber como excluir um ambiente sem excluir um server ? Digamos tenho 2 ou 3 ambientes dentro de um server e quero excluir somente 1 que adicionei de forma errada...como fazer ?:

Favor voltar o DEV Studio na proxima versao do smartclient 64 bits....esta complicado assim!!!

**Comment by DanielYampolschi** [comment]
Caso queira excluir um de ambiente do servidor, isso deve ser feito no arquivo server.ini.

Caso queira apenas excluir um ambiente do servidor cadastrado, onde o nome ou as informações de login foram cadastradas erroneamente, abra o arquivo servers.json (Pode ser feito de duas formas: Clique no icone de engrenagem no lado direito superior da visao de servidores, ou clique com o botão direito em servidor ou ambiente e clique na opção: Configure Server View)

Após abrir o arquivo de configuração de servidores server.json, basta apagar o ambiente que foi cadastrado com problema.
