### ISSUE TITLE
Favor voltar o Dev Studio na proxima versão do smartclient 64 bits...esta complicado assim!!!

### ISSUE THREAD

**Issue by decomoldemaq** [totvs/tds-vscode#382]
Att!

Nós clientes precisamos de algo simples e pratico como o Dev Studio...favor voltarem isto!!

Favor voltar o DEV Studio na proxima versao do smartclient 64 bits....esta complicado assim!!!

**Comment by DanielYampolschi** [comment]
O DevStudio, o qual possui bem menos funcionalidades que o plugin do VsCode e do Eclipse, foi descontinuado tem algum tempo e não irá voltar. 

Caso tenha algum problema específico com o plugin do VsCode, leia a documentação da ferramenta em: https://github.com/totvs/tds-vscode/wiki 
ou o troubleshooting em: 
https://github.com/totvs/tds-vscode/blob/dev/TROUBLESHOOTING.md
