### ISSUE TITLE
Erro ao tentar aplicar patch 

### ISSUE THREAD

**Issue by alanFaccin** [totvs/tds-vscode#386]
Ao tentar aplicar patch esta apresentando a seguinte mensagem:

"One or more validations errors detected:
The following patch(es) contains at least one upper case character,
which is not allowed for unix base systems:

/Users/alanjhones/lib.PTM;"
![Captura de Tela 2020-05-20 às 07 42 12](https://user-images.githubusercontent.com/9438826/82437248-7861a780-9a6d-11ea-9a79-271920febcbb.png)

![Captura de Tela 2020-05-20 às 07 47 54](https://user-images.githubusercontent.com/9438826/82437885-8ebc3300-9a6e-11ea-88ab-13028d072c68.png)

TDS for VSCode versão 1.0.2

Estou utilizado o sistema operacional macOS Catalina Versão 10.15.4 (19E287)
* TOTVS - Build 7.00.170117A - Mar 31 2020 - 12:20:16 
* Build: 64 bits (Windows)
* SVN Revision: 26466
* Build Version: 17.3.0.20

**Comment by alanFaccin** [comment]
Na versão 10.0.1 do plugin o erro não ocorre.

**Comment by doug7dos** [comment]
Olá!

Estou com o mesmo erro e . 

Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

Também estou usando o sistema operacional macOS Catalina Versão 10.15.4 (19E287)

Build:  7.00.170117A-20190628 - 64 bits (Windows)
Release do RPO:  12.1.025
Release do Dic.:   12.1.025
LIB 20200214

**Comment by dantonbertuol** [comment]
Boa tarde.

Estou com o mesmo problema.

**Comment by DanielYampolschi** [comment]
Pessoal, por favor vejam que a mensagem informa que para sistemas operacionais como Mac e Linux (Base Unix) não é possível que o caminho completo do Patch possua caractere em maiúsculo.

Esse é uma limitação do próprio servidor e essa mensagem foi colocada para ajudar a identificar o problema, pois caso esse Patch fosse aplicado, daria um erro mais complicado de identificar a causa.

Na versão 1.0.1 não possui essa proteção, portanto não terá essa mensagem de erro, mas provavelmente um Patch que contenha alguma letra maiúscula (Lembrando, em qualquer ponto do caminho dele, e não apenas no nome) também não será aplicado.

Renomeie o nome do Patch e/ou alguma pasta que contenha letra maiúscula e aplique novamente.

Obrigado.

**Comment by alanFaccin** [comment]
Sempre utilizei o MAC para aplicar patch e nunca tive problemas com isso. 

Se você observar as próprias pastas do sistema são criadas com letras maiúsculas, isso porque por padrão o Mac OS  é Case sensitive. 
![Captura de Tela 2020-05-25 às 09 17 48](https://user-images.githubusercontent.com/9438826/82812098-9ca3f680-9e68-11ea-99bd-3d88b92d83e6.png)

Renomear estas pastas do sistema não é uma boa ideia, assim como alterar para que o sistema não trabalhe de forma case sensitive. 

Criar pastas na Raiz do Mac também não e uma boa alternativa, tendo em vista que será necessário alterar as permissões pra poder fazer isso, pois a raiz possui somente leitura.

**Comment by doug7dos** [comment]
![Captura de Tela 2020-05-25 às 12 20 49](https://user-images.githubusercontent.com/65781363/82825791-404dd080-9e82-11ea-8bec-9e242f0d94df.png)

Reforçando. 

Como eu seleciono uma pasta com nome minúsculo sendo que as pastas padrões do SO já começam com letra maiúsculas?

**Comment by ricardomansano** [comment]
Bom dia @alanFaccin e @doug7dos , vcs tem razão, em MAC o case minusculo não é obrigatório
Veremos o que pode estar ocorrendo

**Comment by DanielYampolschi** [comment]
Pessoal, conforme o @ricardomansano comentou, o Mac realmente não tem essa limitação. A correção foi feita e estará disponível com a próxima atualização.
Obrigado a todos por reportarem essa questão.
