### ISSUE TITLE
Erro ao tentar incluir um servidor - Command 'totvs-developer-studio.add' not found

### ISSUE THREAD

**Issue by SimoesTec** [totvs/tds-vscode#387]
Bom dia, ao tentar incluir um novo servidor esta ocorrendo o erro em anexo:

Versão do VSCode
Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

Versão do Totvs Developer
1.0.2

Em uma instalação do ZERO, ocorre o erro:
command 'totvs-developer-studio.add' not found
**Expected behavior**

![82225002-9525a000-98f2-11ea-9477-e27895de771b](https://user-images.githubusercontent.com/64440671/82454055-52450300-9a7f-11ea-81cd-0d032266344d.png)
![82225007-9656cd00-98f2-11ea-9691-a03559467196](https://user-images.githubusercontent.com/64440671/82454059-53763000-9a7f-11ea-92f2-82701597ba30.png)
![82225009-96ef6380-98f2-11ea-9bf1-dbef473493a5](https://user-images.githubusercontent.com/64440671/82454060-53763000-9a7f-11ea-8747-918f02c476f9.png)
![82225012-96ef6380-98f2-11ea-9fa6-53f8c5292ff7](https://user-images.githubusercontent.com/64440671/82454061-540ec680-9a7f-11ea-92ed-1d5a0f85ea4d.png)

Já informo de antemão que para corrigir este erro foi necessário voltar a versão da extensão: 1.0.1.

Com esta versão tanto a tela de boa vindas, como a adição do servidor estão funcionando corretamente.

Este erro começou a ocorrer após a atualização da versão do VSCode.

Atenciosamente
Henrique Simões

**Comment by DanielYampolschi** [comment]
Ola @SimoesTec liberamos hoje a atualização 1.0.3 do plugin que deve corrigir esse comportamento. Por favor atualize seu ambiente e informe se passa a funcionar. Obrigado

**Comment by ricardomansano** [comment]
Boa tarde,
Correção aplicada na versão 1.0.3 do plugin.

**Comment by MjuniorFacic** [comment]
Bom dia
Como baixo este plugin?

**Comment by lwtnb-wrk** [comment]
@MjuniorFacic Acho que você deve estar com o plugin bem mais recente que esse. Veja a ultima ocorrencia em #1189

**Comment by brodao2** [comment]
@MjuniorFacic 

Veja como em https://code.visualstudio.com/docs/editor/extension-marketplace#_install-an-extension e informe na caixa de pesquisa ``TDS-VSCode``.

Já aviso, que a versão disponível (2.0.3), em alguns ambientes pode apresentar instabilidade. Recomendo aguardar atualização ou utilizar a versão 1.3.23. 

A disposição.
