### ISSUE TITLE
Estouro de tela Compilation Result

### ISSUE THREAD

**Issue by SimoesTec** [totvs/tds-vscode#388]
Estou utilizando as seguintes versões:

Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Totvs Developer Studio for VSCode - 1.0.1 (a versão atual esta com erro na inclusão de novos servidores)

![Capturar](https://user-images.githubusercontent.com/64440671/82460138-cd5de780-9a86-11ea-95fb-2800f08193e6.PNG)

Após compilação de vários fontes e abrir a tabela de resultado das compilações ocorre um "estouro" de tela, onde é necessário trabalhar com o cursor, não esta havendo o remanejamento automático da tela e nem é possível faze manualmente.

Atenciosamente
Henrique Simões

**Comment by DanielYampolschi** [comment]
Ola @SimoesTec por favor atualize seu plugin para a versão 1.0.3 e informe se o problema ainda continua. Obrigado

**Comment by ricardomansano** [comment]
Boa tarde,
Correção aplicada na versão 1.0.3 do plugin.
