### ISSUE TITLE
Dados do arquivo de chave de compilação não são recarregados

### ISSUE THREAD

**Issue by Vitor-Santos-Totvs** [totvs/tds-vscode#39]
Criei um arquivo .aut com os dados da minha chave de compilação e tentei carregá-lo no plugin, porém devido a alteração do ID para compatibilidade com mac/linux, minha chave estava inválida.
Assim, gerei uma nova chave de compilação com o novo ID e alterei o mesmo arquivo com os novos dados, porém como esse arquivo já tinha sido carregado uma vez no plugin, ao selecionar o mesmo arquivo novamente, o plugin não recarregava os dados. Para solucionar isso tive que selecionar um outro arquivo aleatório e depois selecionar novamente meu arquivo com os novos dados.

**Comment by ricardomansano** [comment]
@Vitor-Santos-Totvs , neste caso o plugin fez o correto, ele viu que ja tinha "tentado" carregar e depois ignorou a segunda tentativa.
Não havia a necessidade de alterar o arquivo .aut, bastava preencher os dados no formulário no VS. Ma sé bom que vc agora já conhece o processo.
