### ISSUE TITLE
Conexao com Appserver com erro - Smartclient 19.3.0.5 (com SSL desligado)

### ISSUE THREAD

**Issue by AleksSyntek** [totvs/tds-vscode#390]
**Describe the bug**
Após da actualizacao do binário do smartclient 19.3.0.5 quando tento lancar um debug com o TDS-VSCode, tenho a janela com siguiente erro: "ERR0027: TOTVS | SmartClient conectou com TOTVS | Application Server mas houve erro no início de validação de conexão."

Esto é devido que si o appserver tem o switch do conexao SSL desligada, o smartclient tem que ter tamben desligada la conexao segura (SecureConnection=0 no smartclient.ini) 

**To Reproduce**
1. Upgrade o binario do smartclient ao versao 19.3.0.5
2. Abra o VSCode com a configuracao já preexistente do conexao ao ambiente com SSL desligado, ex:
			"type": "totvs_server_protheus",
			"name": "TOTVS DEV (LG19)",
			"port": 1225,
			"address": "10.1.1.158",
			"buildVersion": "7.00.191205P",
			**"secure": 0,**

3. Tente lancar um debug com F5
4. Debe mostrar o erro "ERR0027: TOTVS | SmartClient conectou com TOTVS | Application Server mas houve erro no início de validação de conexão."

**Expected behavior**
Deve poder lancar o smartclient sim mostrar o erro ja que deve detectar automaticamente si a conexao do appserver e SSL o nao (com a versao 19.3.0.3 nao occuría esto)

**Screenshots**
iniciando o debug
![imagen](https://user-images.githubusercontent.com/30332762/82486027-aa492d00-9ab2-11ea-9f49-1df85b8897c0.png)

Smartclient com erro:
![imagen](https://user-images.githubusercontent.com/30332762/82486143-d369bd80-9ab2-11ea-973b-408c799569cb.png)

**Desktop (please complete the following information):**
 - Remote build:7.00.191205P-20200504
 - Remote version:19.3.0.5
 - Remote type:1 - QT-5.14.0 WIN
 - Modulo: FAT
 - Nombre de la computadora: NBK-ARG-019
 - Sistema operativo: Windows 10 - 
 - Memoria: 8051
 - Procesador: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz

**Appserver (please complete the following information):**
 - OS/Architecture: Windows Server 2012R2
 - Build AppServer: 7.00.191205P-20200424 - 64 bits
 - Appserver version: 19.3.0.4
 - Build DBAccess: 20191119-20200217
 - Release del RPO:  12.1.025
 - Release del diccionario: 12.1.025
 - Local files: CTREE
 - License server:2014 - 1.03.017
 - DB DataBase:MSSQL
 - DB API Build:20191119-20200116

**Additional context**
Após do análise detecté que só si por linha de comando se executa com o parametro -C (connection) en ves do -Z (endereco server) é -Y (porta) , o smartclient pode executarse, devido que pode leer a configuracao SecureConnection=0. Si bem o smartclient tem o swith do linha do commando -SSL só sirve para **ligar** conexao segura ou SSL, mais no hover uma opcao para **desligar** coexao SSL via linha do commando.

**Comment by AleksSyntek** [comment]
ë possible indicar no execucao no launch.json que deve apagar a conexao SSL padrao?

**Comment by ricardomansano** [comment]
Boa noite Alek,
A informação de SSL esta no **servers.json**
O VSCode deveria ver o tipo de conexão automaticamente, vou testar isso amanha com calma.
Suas informações estão bem completas então não devemos ter dificuldade em analisar.

![image](https://user-images.githubusercontent.com/33813921/82956809-ffd87a80-9f87-11ea-90f6-2a289967ad38.png)

**Comment by AleksSyntek** [comment]
Boa noite @ricardomansano , tenho no servers.json o "secure" : 0 devido que apagamos o protocolo SSL para poder aplicar pacotes mientras se avalia o problema reportado no issue #342 

![imagen](https://user-images.githubusercontent.com/30332762/82972136-b77e8400-9faa-11ea-8676-4023a5ff2017.png)

Entao sim uso o ultimo binario 19.3.0.5 com issa configuracao, ao tentar debugar o TDS-VSCode genera o error ERR0027 indicado arriba, 
Vou a tentar adicionar um servico appserver para o ambiente, com configuracao SSL padrao, tirando o switch `MultiProtocolPortSecure=0` do appserver.ini para fazer um teste, acho que assim nao va a ter problema para lancar um debug com último binario, mais o aplicacao do pacotes pode dar erro ainda.

**Comment by AleksSyntek** [comment]
Finalmente fiz o teste com o binario e com o appserver adicional com SSL ligado e dá certo ao lancar o debug com o binário smartclient 19.3.0.5, mais com SSL desligado o lancamento do binario smartclient 19.3.0.5 tem erro. Anexo as duas capturas do telas, mesmo binario, mesmo appserver (replicado x 2, porta 2225 com SSL, porta 1225 sim SSL)

Appserver com SSL ligado/conectado:
![TDS-VSCode_SSL_19 3 0 5](https://user-images.githubusercontent.com/30332762/82978581-527f5a00-9fbb-11ea-8ab9-ecb86c115424.jpg)

AppServer com SSL desligado/apagado:
![TDS-VSCode_SIN_SSL_19 3 0 5](https://user-images.githubusercontent.com/30332762/82978734-a5f1a800-9fbb-11ea-8313-b5cf1c786f6d.jpg)

Slds.
