### ISSUE TITLE
Erro na configuração do TSD ou VSCODE

### ISSUE THREAD

**Issue by Reserplastic2020** [totvs/tds-vscode#391]
Prezados, boa tarde!
Migramos nosso ambiente para um novo servidor.
Porém não consigo configurar o TDS, pois não encontra os servidores e nem instalar a nova ferramenta o VSCODE dá erro de permissão porém meu usuário do Windows é Administrador Local.

![ping](https://user-images.githubusercontent.com/65729466/82587636-ec847400-9b6f-11ea-837b-e27d00dbbba1.JPG)
![TDS](https://user-images.githubusercontent.com/65729466/82587637-ed1d0a80-9b6f-11ea-8166-02e409519258.JPG)
![Vscode](https://user-images.githubusercontent.com/65729466/82587639-edb5a100-9b6f-11ea-9180-c18b0a7cc65e.JPG)
![vscode1](https://user-images.githubusercontent.com/65729466/82587644-ee4e3780-9b6f-11ea-8c0c-c8065effc3d0.JPG)

**Comment by Reserplastic2020** [comment]
[appserver (1).txt](https://github.com/totvs/tds-vscode/files/4663848/appserver.1.txt)
[appserver (2).txt](https://github.com/totvs/tds-vscode/files/4663850/appserver.2.txt)
[appserver (3).txt](https://github.com/totvs/tds-vscode/files/4663851/appserver.3.txt)
[appserver (4).txt](https://github.com/totvs/tds-vscode/files/4663852/appserver.4.txt)
[appserver (5).txt](https://github.com/totvs/tds-vscode/files/4663853/appserver.5.txt)
[appserver.txt](https://github.com/totvs/tds-vscode/files/4663854/appserver.txt)

**Comment by ricardomansano** [comment]
Boa tarde,

**Quanto ao Eclipse:**

Você esta usando a Release 27?
Se sim, precisa usar o plugin para Eclipse, a versão anterior do TDS é compatível apenas com a Release 25 ou inferior, abaixo a documentação:
https://tdn.totvs.com/pages/viewpage.action?pageId=527830513

Atente que seu print do TDS não possui a opção SSL, obrigatória na Release 27, inserida no plugin acima:
![image](https://user-images.githubusercontent.com/33813921/82956173-9f950900-9f86-11ea-99f2-105c74b0879f.png)

**Quanto ao VSCode**

Você seguiu a documentação para configurar seu ambiente? O VSCode identifica sozinho se a conexão é ou não SSL.
Segue a documentação e os videos pra lhe ajudar neste processo:
https://marketplace.visualstudio.com/items?itemName=totvs.tds-vscode
https://www.youtube.com/watch?v=MwIu01Ztfvg
https://www.youtube.com/watch?v=Cz4N0XWCXHY

Ficamos na escuta

**Comment by Reserplastic2020** [comment]
Bom dia Mansano,

 

Fiquei aguardando um tempo para você me mandar o link do youtube.

 

Já tentei de todas as formas, até mesmo um consultor da TOTVS não conseguiu me ajudar, por esse motivo abri um chamado.

 

Segue abaixo grifado em amarelo as respostas ao seu questionamento.

 

Att,

 

 

	




Fernando Faria
Tecnologia da Informação
 <mailto:ti@reserplastic.com.br> ti@reserplastic.com.br
Tel: +55 (47) 3489-7030



 <https://www.linkedin.com/company/reserplastic/about/?viewAsMember=true> 

 <https://www.facebook.com/ReserPlastic> 

 <https://www.instagram.com/reserplastic/?hl=pt-br> 

 <https://www.youtube.com/channel/UCDdrlGsxd93KWgB5L6gE0BQ?view_as=subscriber> 

 <http://www.reserplastic.com.br/InstalarCatalogoReserplastic.exe> 



 

 

De: Mansano [mailto:notifications@github.com] 
Enviada em: terça-feira, 26 de maio de 2020 19:28
Para: totvs/tds-vscode <tds-vscode@noreply.github.com>
Cc: Reserplastic2020 <suporte@reserplastic.com.br>; Author <author@noreply.github.com>
Assunto: Re: [totvs/tds-vscode] Erro na configuração do TSD ou VSCODE (#391)

 

Boa tarde,

Quanto ao Eclipse:

Você esta usando a Release 27?  Release 25
Se sim, precisa usar o plugin para Eclipse, a versão anterior do TDS é compatível apenas com a Release 25 ou inferior, abaixo a documentação:
https://tdn.totvs.com/pages/viewpage.action?pageId=527830513

Atente que seu print do TDS não possui a opção SSL, obrigatória na Release 27, inserida no plugin acima:
 <https://user-images.githubusercontent.com/33813921/82956173-9f950900-9f86-11ea-99f2-105c74b0879f.png> 

Quanto ao VSCode

Você seguiu a documentação para configurar seu ambiente? O VSCode identifica sozinho se a conexão é ou não SSL.
Segue a documentação e os videos pra lhe ajudar neste processo:
https://marketplace.visualstudio.com/items?itemName=totvs.tds-vscode
https://www.youtube.com/watch?v=MwIu01Ztfvg
https://www.youtube.com/watch?v=Cz4N0XWCXHY

O consultor da TOTVS me auxiliou com a configuração, porém conforme os prints que lhe enviei, apresenta um erro de permissão. 

Ficamos na escuta

**Comment by brodao** [comment]
@Reserplastic2020 

Ao abrir o VSCode e selecionar a visão "Explorer", o mesmo apresenta-se dessa forma:
![image](https://user-images.githubusercontent.com/949914/83180019-2ec22e00-a0f9-11ea-8bba-388b0c9159cf.png)

Se sim, abra uma pasta que contenha fontes AdvPL e tente efetuar o registro do servidor.

Fico no aguardo.

**Comment by Reserplastic2020** [comment]
Fernando Faria
Tecnologia da Informação
 <mailto:ti@reserplastic.com.br> ti@reserplastic.com.br
Tel: +55 (47) 3489-7030



 <https://www.linkedin.com/company/reserplastic/about/?viewAsMember=true> 

 <https://www.facebook.com/ReserPlastic> 

 <https://www.instagram.com/reserplastic/?hl=pt-br> 

 <https://www.youtube.com/channel/UCDdrlGsxd93KWgB5L6gE0BQ?view_as=subscriber> 

 <http://www.reserplastic.com.br/InstalarCatalogoReserplastic.exe> 



 

 

De: Alan Cândido [mailto:notifications@github.com] 
Enviada em: quinta-feira, 28 de maio de 2020 15:39
Para: totvs/tds-vscode <tds-vscode@noreply.github.com>
Cc: Reserplastic2020 <suporte@reserplastic.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [totvs/tds-vscode] Erro na configuração do TSD ou VSCODE (#391)

 

@Reserplastic2020 <https://github.com/Reserplastic2020> 

Ao abrir o VSCode e selecionar a visão "Explorer", o mesmo apresenta-se dessa forma:
 <https://user-images.githubusercontent.com/949914/83180019-2ec22e00-a0f9-11ea-8bba-388b0c9159cf.png> 

Se sim, abra uma pasta que contenha fontes AdvPL e tente efetuar o registro do servidor.

Fico no aguardo.

**Comment by Reserplastic2020** [comment]
Bom dia Alan,

 

Segui as suas orientações.

 

Segue abaixo o print.

 

 



 

	




Fernando Faria
Tecnologia da Informação
 <mailto:ti@reserplastic.com.br> ti@reserplastic.com.br
Tel: +55 (47) 3489-7030



 <https://www.linkedin.com/company/reserplastic/about/?viewAsMember=true> 

 <https://www.facebook.com/ReserPlastic> 

 <https://www.instagram.com/reserplastic/?hl=pt-br> 

 <https://www.youtube.com/channel/UCDdrlGsxd93KWgB5L6gE0BQ?view_as=subscriber> 

 <http://www.reserplastic.com.br/InstalarCatalogoReserplastic.exe> 



 

 

 

 

De: Alan Cândido [mailto:notifications@github.com] 
Enviada em: quinta-feira, 28 de maio de 2020 15:39
Para: totvs/tds-vscode <tds-vscode@noreply.github.com>
Cc: Reserplastic2020 <suporte@reserplastic.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [totvs/tds-vscode] Erro na configuração do TSD ou VSCODE (#391)

 

@Reserplastic2020 <https://github.com/Reserplastic2020> 

Ao abrir o VSCode e selecionar a visão "Explorer", o mesmo apresenta-se dessa forma:
 <https://user-images.githubusercontent.com/949914/83180019-2ec22e00-a0f9-11ea-8bba-388b0c9159cf.png> 

Se sim, abra uma pasta que contenha fontes AdvPL e tente efetuar o registro do servidor.

Fico no aguardo.

**Comment by Reserplastic2020** [comment]
Tentei criar a conexão com o servidor, segue a mensagem que aparece.

 



 

	




Fernando Faria
Tecnologia da Informação
 <mailto:ti@reserplastic.com.br> ti@reserplastic.com.br
Tel: +55 (47) 3489-7030



 <https://www.linkedin.com/company/reserplastic/about/?viewAsMember=true> 

 <https://www.facebook.com/ReserPlastic> 

 <https://www.instagram.com/reserplastic/?hl=pt-br> 

 <https://www.youtube.com/channel/UCDdrlGsxd93KWgB5L6gE0BQ?view_as=subscriber> 

 <http://www.reserplastic.com.br/InstalarCatalogoReserplastic.exe> 



 

 

De: Alan Cândido [mailto:notifications@github.com] 
Enviada em: quinta-feira, 28 de maio de 2020 15:39
Para: totvs/tds-vscode <tds-vscode@noreply.github.com>
Cc: Reserplastic2020 <suporte@reserplastic.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [totvs/tds-vscode] Erro na configuração do TSD ou VSCODE (#391)

 

@Reserplastic2020 <https://github.com/Reserplastic2020> 

Ao abrir o VSCode e selecionar a visão "Explorer", o mesmo apresenta-se dessa forma:
 <https://user-images.githubusercontent.com/949914/83180019-2ec22e00-a0f9-11ea-8bba-388b0c9159cf.png> 

Se sim, abra uma pasta que contenha fontes AdvPL e tente efetuar o registro do servidor.

Fico no aguardo.

**Comment by brodao** [comment]
Ola Fernando,

Nas suas duas mensagens anteriores, não consigo visualizar as imagens. Por favor, reenviar direto para acandido@totvs.com.br.

Grato pela colaboração.
