### ISSUE TITLE
Session [admin]

### ISSUE THREAD

**Issue by emanuelsc3s** [totvs/tds-vscode#392]
Ao compilar estou com o seguinte erro:

segue em anexo print do erro e appserver.ini

Como resolver ? Grato

[Error - 08:12:29] Start build error: Server returned: Session [admin] not found in AppServer_slv01.ini. Verify the "Environment in the Server"
Called from D:\bamboo-agent-5.7.2\xml-data\build-dir\TP11-TECX17V3R1-TECXWIN64\lib\config.cpp line 78

![image](https://user-images.githubusercontent.com/4842242/82810279-682e3b80-9e64-11ea-98b6-ddefde2532eb.png)

[AppServer_slv01.txt](https://github.com/totvs/tds-vscode/files/4677033/AppServer_slv01.txt)

**Comment by ricardomansano** [comment]
Boa tarde Emanuel,

Você acidentalmente digitou o nome do usuário (ADMIN) no lugar do environment, basta excluir o Servidor cadastrado e inclui-lo novamente, pode também editar o Json de Servers, mas eu não recomendo.

Abaixo eu reproduzi o problema para que vc entenda o que aconteceu.

![image](https://user-images.githubusercontent.com/33813921/82955484-509aa400-9f85-11ea-8476-64275db33bee.png)
