### ISSUE TITLE
Erro ao compilar fontes com Prepare environment

### ISSUE THREAD

**Issue by RicardoNisiyama-Tech** [totvs/tds-vscode#393]
Boa tarde,
Recentemente tivemos a necessidade de atualizar o binário do sistema, e tivemos que começar a trabalhar os fontes com o VSCODE, ocorre que ao tentar compilar fontes que trabalham automaticamente com PREPARE ENVIRONMENT não compila.
Aparece erro de sintaxe.

**Comment by ricardomansano** [comment]
Boa tarde Ricardo,

Você pode continuar utilizando o TDS-Eclipse até o fim do suporte em Dez/2020, mesmo para a Release 27, conforme documentação abaixo:
https://tdn.totvs.com/pages/viewpage.action?pageId=527830513

Quanto ao seu problema, por gentileza envie mais detalhes do seu ambiente, sistema operacional que esta usando no Server e na estação, e o erro completo.

Verifique também se sua pasta de INCLUDES esta correta, esse erro aparenta ser problema na pré-compilação, que não esta conseguindo traduzir o comando.

Ficamos na escuta.

**Comment by brodao** [comment]
Encerrado por falta de retorno.

**Comment by jfsbarreto** [comment]
Tive esse problema e corrigiu colocando os includes no fonte: 

#include "tbiconn.ch"
#include "protheus.ch"

**Comment by xhuntet** [comment]
Perfeito @jfsbarreto, acabei de passar por isso e essa foi a solução.

Obrigado!
