### ISSUE TITLE
Compilação de Projeto no VS-Code

### ISSUE THREAD

**Issue by renatocgarcia** [totvs/tds-vscode#394]
Gostaria de saber como faço a compilação de um projeto inteiro dos fontes advpl no VS-Code.

**Comment by brodao** [comment]
Ola Renato,

O VSCode não tem um conceito de projeto. Você abra a patas que contém os fontes e manda compilar a pasta. Em nosso [wiki](https://github.com/totvs/tds-vscode/wiki) e no [canal](https://www.youtube.com/user/MansanoRicardo) do @ricardomansano  , há informações a respeito.

[](url)

**Comment by renatocgarcia** [comment]
Ok...

Você sabe me dizer se tem um conversor de projetos para pastas em algum
lugar?

Em seg., 1 de jun. de 2020 às 14:29, Alan Cândido <notifications@github.com>
escreveu:

**Comment by ricardomansano** [comment]
Boa tarde @renatocgarcia ,

Você pode compilar a workspace completa, conforme print abaixo, basta selecionar uma das pastas no VSCode **com o botão direito do mouse**, ou pode ainda compilar uma pasta específica 

![image](https://user-images.githubusercontent.com/33813921/83545701-f1cdb100-a4d5-11ea-843f-4534a9a00ba7.png)
