### ISSUE TITLE
file could not be copied to the server

### ISSUE THREAD

**Issue by rbadoni** [totvs/tds-vscode#395]
Estou com o mesmo problema reportado na Issue #287 . Já tentei todas as sugestões reportadas.

A particularidade que percebi: só acontece quando o arquivo referenciado esta gravado no servidor (\xx.xx.x.xxx\d$\totvs ...)

VsCode instalado Local - Versão 1.45.1

Build AppServer: 7.00.191205P-20200424 - 64 bits
Appserver version: 19.3.0.4
Versão da Lib:20200504
Data da Lib: 20200518_142132
Sistema operacional: Windows Server 2016

Remote build: 7.00.191205P-20200221
Remote version: 19.3.0.1
Windows 10 64 Bits

**Comment by brodao** [comment]
Similar issue #342

**Comment by brodao** [comment]
@rbadoni ,

Se possível, favor encaminhar para acandido@totvs.com.br, o ini do appServer e o pacote que gerou o erro.

Grato pela colaboração.

**Comment by brodao** [comment]
Senhores,

Realizando testes, detectamos que a mensagem de "arquivo não encontrado" esta sendo emitida quando na verdade o erro é de "pacote não compatível com o RPO", p.e.:
- pacote de inglês em RPO portugues;
- pacote topConnect em RPO ctree.

Certifique-se que o pacote esta de acordo com o seu RPO. A ocorrência já está em análise pela equipe do servidor. 

Os testes foram realizados com a última "build" disponibilizada:

> \* TOTVS - Build 7.00.191205P - Apr 24 2020 - 14:30:50
> \* Build: 64 bits
> \* SVN Revision: 26664
> \* Build Version: 19.3.0.4

A disposição.

**Comment by rbadoni** [comment]
> @rbadoni ,
> 
> Se possível, favor encaminhar para [acandido@totvs.com.br](mailto:acandido@totvs.com.br), o ini do appServer e o pacote que gerou o erro.
> 
> Grato pela colaboração.

Arquivos enviados

**Comment by rbadoni** [comment]
> Estou com o mesmo problema reportado na Issue #287 . Já tentei todas as sugestões reportadas.
> 
> A particularidade que percebi: só acontece quando o arquivo referenciado esta gravado no servidor (\xx.xx.x.xxx\d$\totvs ...)
> 
> VsCode instalado Local - Versão 1.45.1
> 
> Build AppServer: 7.00.191205P-20200424 - 64 bits
> Appserver version: 19.3.0.4
> Versão da Lib:20200504
> Data da Lib: 20200518_142132
> Sistema operacional: Windows Server 2016
> 
> Remote build: 7.00.191205P-20200221
> Remote version: 19.3.0.1
> Windows 10 64 Bits

Compilação acontecendo no release 27

**Comment by rbadoni** [comment]
> Senhores,
> 
> Realizando testes, detectamos que a mensagem de "arquivo não encontrado" esta sendo emitida quando na verdade o erro é de "pacote não compatível com o RPO", p.e.:
> 
> * pacote de inglês em RPO portugues;
> * pacote topConnect em RPO ctree.
> 
> Certifique-se que o pacote esta de acordo com o seu RPO. A ocorrência já está em análise pela equipe do servidor.
> 
> Os testes foram realizados com a última "build" disponibilizada:
> 
> > * TOTVS - Build 7.00.191205P - Apr 24 2020 - 14:30:50
> > * Build: 64 bits
> > * SVN Revision: 26664
> > * Build Version: 19.3.0.4
> 
> ![image](https://user-images.githubusercontent.com/949914/83439721-17958000-a41a-11ea-8300-d1f9bf7f2bd4.png)
> 
> A disposição.

Mas aqui estamos tratando a mensagem "file could not be copied to the server", correto ?

**Comment by brodao** [comment]
Senhores,

Devido a restrições no processo de aplicação de pacotes, a aplicação de pacotes obtendo-o de um caminho não local não é suportado. Se for necessário, copie para uma pasta na máquina local ou mapeie um drive para o endereço compartilhado.

A disposição.
