### ISSUE TITLE
[dúvida][pergunta] Compilação de Pasta  x Fonte com Erro x Rollback de Tudo

### ISSUE THREAD

**Issue by charlesreitz** [totvs/tds-vscode#397]
Existe alguma forma de parametrizar o comportamento de uma compilação de uma pasta e caso algum programa possuir problema não fazer o rollback de toda compilação? 

Ou seja, o que compilo compilo, o que deu erro apenas mostra que deu erro mas não faz rollback. 

Obrigado

**Comment by brodao** [comment]
@charlesreitz 

No momento não existe. Coloquei seu chamado como melhoria.

A disposição.

**Comment by brodao** [comment]
@charlesreitz 

Melhor dizendo, favor abrir um chamado de melhoria.

Grato.

**Comment by lwtnb-wrk** [comment]
@charlesreitz Pode indicar um caso de uso aonde esse comportamento faça sentido? O rollback ocorre somente em caso de erros que impedem a compilação de um dos arquivos. Esse arquivo pode ser usado por outro que esta sendo compilado tambem. Então se não ocorresse o rollback o arquivo compilado ao chamar o que nao foi compilado ocorreria um erro que seria dificil de identificar. Não consigo identificar um cenario aonde o commit parcial do compile faça sentido. Valeu!

**Comment by charlesreitz** [comment]
Léo, no TDS Eclipse ele fazia isso.

**Comment by lwtnb-wrk** [comment]
@charlesreitz Por que voce acha que deveria continuar assim? 
Estamos tentando criar uma extensao do tds-vscode mais leve e funcional e nao necessariamente igual ao TDS Eclipse. E toda a sugestao é bem-vinda!

**Comment by charlesreitz** [comment]
Veja meu cenário, tenho um projeto de um cliente que preciso compilar para fazer alguns testes em um RPO zerado (Padrão do Produto), clico na pasta e mando compilar tudo, alguns fontes de testes, ou fontes antigos ao qual não serão utilizados apresenta erro, sendo que naquele momento preciso dar alguma tratativa para eles para conseguir alcançar  meu objetivo de compilar toda a pasta. 

Eu posso remover eles, comentar ou arrumar. 

Nesse momento não queria ter esse trabalho, pois não é o foco da minha atividade naquele momento, então acaba atrapalhando. 

Por isso acredito que deveria existir a possibilidade de compilar de forma parcial. 

Abraços,

**Comment by lwtnb-wrk** [comment]
@charlesreitz Na proxima versão procure por "Comitar a compilação com erros/alertas" e marque a opção para comitar mesmo com erros/warnings #564
