### ISSUE TITLE
Servidor não conecta

### ISSUE THREAD

**Issue by lisnageoliveira** [totvs/tds-vscode#399]
Bom dia,

Estava usando o VS Code para debugar normalmente, até que pedi para ele interromper, porque iria recomeçar. Porém, ele não conecta mais em nenhum servidor. E não apresenta erro.

Quando inicio ele, o máximo que aparece na tela de OUTPUT é isso:

[Info  - 08:54:25] Initializing Language Server.
[Info  - 08:54:25] Language Server initialized.
[Info  - 08:54:25] Starting reconnection to the server 'PRD RH - LIS'
[Log   - 00:00:00] Authenticating...

Mas se tento desconectar, informa que não está conectado. Se tento conectar, não dá erro, mas não conecta. Aparece a caixinha para eu selecionar o ambiente e após selecionar, nada.

Se tento defrag, aplicação de patch, informa que não está conectado em nenhum servidor.

Não atualizei nada. Como disse, vinha utilizando normalmente. E parou após eu interromper uma execução de debug.

Tentei reinstalar a extensão Totvs Developer Studio, mas nada mudou.

Alguém saberia por onde começar a olhar? 

Eu sou bem iniciante com o VS Code e ele foi configurado por terceiros.

Obrigada,

Lis Oliveira

**Comment by lwtnb-wrk** [comment]
@lisnageoliveira O appserver foi reiniciado? Pode ser que esteja travado...
Se ele foi reiniciado e o problema persiste, veja https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md e nos envie os logs para analises.
