### ISSUE TITLE
Intellisense retornando em caixa alta

### ISSUE THREAD

**Issue by VctrAndrade** [totvs/tds-vscode#4]
Ao utilizar o Intellisense do plugin, as palavras são retornadas sempre em caixa alta, não respeitando as boas práticas do AdvPl, onde para função temos a primeira letra em caixa alta e o restante em caixa baixa.

**Comment by matheus-sales** [comment]
Olá @VctrAndrade, 

Já tínhamos identificado esse problema e está na nossa lista de correções.

Obrigado.

**Comment by matheus-sales** [comment]
Vitor, criamos a task no nosso projeto de roadmap para controlar essa questão. 

Vou fechar essa task como duplicada e passamos a acompanhar pela outra. Por favor. 

https://github.com/totvs/tds-vscode/issues/14
