### ISSUE TITLE
Chave de compilação necessita de um arquivo .aut

### ISSUE THREAD

**Issue by Vitor-Santos-Totvs** [totvs/tds-vscode#40]
Não é possível validar uma chave de compilação sem fornecer um arquivo .aut.
Uma vez que o arquivo apenas contém esses dados e ao ser carregado os preenche na interface do plugin, acredito que apenas preencher os dados deveria ser suficiente para validar uma chave, sem a necessidade de sempre haver o arquivo .aut.

**Comment by lwtnb-wrk** [comment]
@Vitor-Santos-Totvs possivelmente voce deve ter aplicado uma chave anteriormente? Neste caso os campos ficam realmente bloqueado com as informacoes da ultima chave aplicada. Se precisar aplicar outra chave, seja por arquivo ou digitando os campos, é necessario clicar em "Clean Key" para remover a chave atual e habilitar a adicao da nova chave. Quando um arquivo é carregado ele faz esse processo de limpar a chave anterior automaticamente, mas para aplicar manualmente é preciso limpar a chave anterior. Veja se este é o seu caso e nos informe caso continue com problemas.

**Comment by Vitor-Santos-Totvs** [comment]
No meu ambiente inicialmente autentiquei pelo fluig e só tentei adicionar a chave de compilação após ter vencido o período em que isso era válido. Como eu nunca tive um arquivo .aut, apenas adicionei os dados e tentei validá-los, mas como eu estava usando o ID antigo não funcionou. Peguei o ID novo e então tentei fazer a adição sem o arquivo e ocorreu o erro que mencionei.
Porém tentei fazer essa adição sem o arquivo em uma outra estação onde o plugin tinha sido recém instalado e apenas colocando os dados sem selecionar nenhum arquivo não funcionou, mesmo sem ter preenchido nenhuma outra chave anteriormente.

**Comment by lwtnb-wrk** [comment]
> No meu ambiente inicialmente autentiquei pelo fluig e só tentei adicionar a chave de compilação após ter vencido o período em que isso era válido. Como eu nunca tive um arquivo .aut, apenas adicionei os dados e tentei validá-los, mas como eu estava usando o ID antigo não funcionou. Peguei o ID novo e então tentei fazer a adição sem o arquivo e ocorreu o erro que mencionei.
> Porém tentei fazer essa adição sem o arquivo em uma outra estação onde o plugin tinha sido recém instalado e apenas colocando os dados sem selecionar nenhum arquivo não funcionou, mesmo sem ter preenchido nenhuma outra chave anteriormente.

@Vitor-Santos-Totvs nesta outra estação onde o plugin tinha sido recem instalado voce nao conseguiu preencher manualmente os dados da chave de compilacao ou a chave inserida manualmente nao foi validada? 
Nao deveria fazer nenhuma diferenca mas qual o ambiente que voce esta usando o tds-vscode? Windows 10 mesmo??

**Comment by Vitor-Santos-Totvs** [comment]
Nessa outra estação preenchi manualmente e os dados não foram validados sem escolher o arquivo .aut.
Após carregar o arquivo ai sim a validação ocorreu normalmente. Estamos usando windows 10 mesmo.

**Comment by lwtnb-wrk** [comment]
> Nessa outra estação preenchi manualmente e os dados não foram validados sem escolher o arquivo .aut.
> Após carregar o arquivo ai sim a validação ocorreu normalmente. Estamos usando windows 10 mesmo.

Mas depois de preencher manualmente os dados voce clicou em "Validate Key"? Ao aplicar a chave por arquivo os dados sao automaticamente preenchidos e o "Validate Key" é chamado, mas ao preencher manualmente é necessario chamar manualmente o "Validate Key".

**Comment by Vitor-Santos-Totvs** [comment]
Não sabia nem que havia essa validação automática, eu sempre clico no botão validar para checar se está correto, tanto preenchendo manualmente quanto quando carrego o arquivo.

**Comment by lwtnb-wrk** [comment]
@Vitor-Santos-Totvs Vamos adicionar uma area no form da chave de compilacao para ter um feedback apos as validacoes, pois como as notificacoes podem ou nao estar habilitadas, as messagem poderao aparecer apenas no console. Acho que assim vai ficar claro se a chave foi ou nao aplicada com sucesso.

**Comment by Vitor-Santos-Totvs** [comment]
Entendi. Agradeço pelo suporte.

**Comment by lwtnb-wrk** [comment]
@Vitor-Santos-Totvs fizemos algumas melhorias na pagina de aplicacao da chave de compilacao. as alteracoes estarao disponiveis na proxima liberacao.

**Comment by Vitor-Santos-Totvs** [comment]
Fico muito grato pela resolução e pela cordialidade.
