### ISSUE TITLE
Erro ao abrir o inspetor de objetos

### ISSUE THREAD

**Issue by Diogo04** [totvs/tds-vscode#400]
Boa tarde
apos atualização do BIN e LIB (informações anexas), ao clicar com o botão direito no server e Patch Generation apresenta um erro e derruba meu server
OBS consigo compilar normalmente e estou com o ambiente totalmente atualizado

![caminho](https://user-images.githubusercontent.com/66440904/83802513-4bbeaa00-a681-11ea-98ac-f9143d4d9eb6.PNG)
![erro](https://user-images.githubusercontent.com/66440904/83802517-4cefd700-a681-11ea-961b-25df98dc5f66.PNG)
![LIB](https://user-images.githubusercontent.com/66440904/83802519-4cefd700-a681-11ea-8b25-72bf52816a56.PNG)
![versao](https://user-images.githubusercontent.com/66440904/83802521-4d886d80-a681-11ea-9e83-61c26bcfa626.PNG)

**Comment by brodao** [comment]
Duplicate #396
