### ISSUE TITLE
Compilação - Lista de problemas não limpa após correção dos erros

### ISSUE THREAD

**Issue by DanielYampolschi** [totvs/tds-vscode#401]
**Describe the bug**
Ao realizar uma segunda compilação (Testado com compilação de workspace, mas parece ter o mesmo comportamento em todas as compilações com uma lista de arquivos), onde a primeira teve alguns erros, e a segunda eles foram corrigidos, apesar da compilação ser feita normalmente, a lista de problemas continua apresentando os erros anteriores.

**To Reproduce**
1. Realizar uma compilação com uma lista de arquivos ou com o comando "Compile All Workspace" com um ou mais arquivos que tenha qualquer problema de compilação.
2. Corrigir o erro de compilação do(s) arquivo(s)
3. Compilar novamente toda a lista de arquivos
4. Verificar que a visao de problemas continua mostrando os erros da primeira compilção apesar dela ter acontecido com sucesso.

**Expected behavior**
Após corrigir os erros e executar uma nova compilação, a visão "Problems" deve mostrar apenas os warnings/erros da última compilação.

**Screenshots**
![image](https://user-images.githubusercontent.com/10711513/84070460-8d619480-a9a2-11ea-988d-33a0ddf6d860.png)

**Desktop (please complete the following information):**
 - OS/Architecture: [e.g. Windows 64 bits]
Testado com igual resultado em Win64 e Linux Mint 64

**Appserver (please complete the following information):**

* TOTVS - Build 7.00.191205P - Apr 24 2020 - 14:30:50
* Build: 64 bits (Windows)
* SVN Revision: 26664
* Build Version: 19.3.0.4

**Comment by lwtnb-wrk** [comment]
@DanielYampolschi Testei na ultima versão e não reproduzi mais o problema.
Se com a última versão você continuar com problemas, nos dê mais detalhes de como reproduzir e reabra a issue.
