### ISSUE TITLE
Tabela da tela de resultado de compilação ultrapassando os limites do container

### ISSUE THREAD

**Issue by DanielYampolschi** [totvs/tds-vscode#402]
**Describe the bug**
Tabela da tela de resultado de compilação ultrapassando os limites do container

**To Reproduce**
1. Realizar uma compilação com uma lista de arquivos
2. Abrir a tela de resultados de compilação

**Expected behavior**
A tabela de resultados deve respeitar os limites do container adicionando barra de scroll caso necessario

**Screenshots**
![image](https://user-images.githubusercontent.com/10711513/84073475-3e6a2e00-a9a7-11ea-91d7-96cf4b34530d.png)

**Comment by brodao** [comment]
Encerrado. Se após atualizar o seu ambiente e a ocorrência ainda persistir, reabra o chamado com as informações de versão (TDS-VSCode e appServer).
