### ISSUE TITLE
"Patch generate from RPO" não carrega os fontes

### ISSUE THREAD

**Issue by le0zz** [totvs/tds-vscode#403]
**Describe the bug**
A funcionalidade "Patch generate from RPO" não carrega os fontes, fica sempre em "loading".

**To Reproduce**
1. Selecionar e conectar-se a um servidor
2. Clicar com botão direito e clicar em "Patch generate from RPO"
3. Verificar que a tela não carrega os fontes.

**Expected behavior**
A tela deveria carregar todos os fontes..

**Screenshots**
![image](https://user-images.githubusercontent.com/37678190/84152619-4c698e80-aa3b-11ea-8945-360673ee54af.png)

**Desktop (please complete the following information):**
 - OS/Architecture: Windows 64bit

**Appserver (please complete the following information):**
 - Build (with date): Build 7.00.191205P - Apr 20 2020 - 14:30:50
 - OS/Architecture: Windows 10 x64
 - Build Version 19.3.0.4

**Aditional information**
Versão da extensão: 1.0.3
Versão do VSCode: 1.45.1

**Comment by lwtnb-wrk** [comment]
@le0zz veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md como gerar os logs e nos envie para que possamos analisar.
Anexe tambem o console.log do appserver.
