### ISSUE TITLE
templates

### ISSUE THREAD

**Issue by Wesley524** [totvs/tds-vscode#404]
Olá eu vi em um vídeo que existem alguns templates disponíveis assim como é feito no vídeo 

https://www.youtube.com/watch?v=MwIu01Ztfvg&t=1s

09:32 

diz que se der ctrl + espaço aparecem os templates de funções mas no meu vscode já com a extensão do vídeo não possui essa funcionalidade, queria saber como faço para ter esses templates.

Grato,
Wesley Andrade
wesley@veti.com.br

**Comment by lwtnb-wrk** [comment]
@Wesley524 O que ocorre ao pressionar "CTRL + espaço"?
Testei aqui e aparentemente está funcionando corretamente. Ao pressionar "CTRL + espaço" abre uma lista de seleção. Ao digitar "function" o template é exibido e ao seleciona-lo o codigo é inserido no fonte.
Se não estiver funcionando veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md como gerar logs e nos envie para analise.
