### ISSUE TITLE
Problema conexão - APPSERVER

### ISSUE THREAD

**Issue by pinesi** [totvs/tds-vscode#406]
Após atualização binários não consigo mais conectar ao APPSERVER.

VSCODE

Versão: Commit de 1.45.1 (user setup): 5763d909d5f12fe19f215cbfdd29a91c0fa9208a 
Data: 2020-05-14T08:27:35.169Z elétron: 7.2.4 
Chrome: 78.0.3904.130 
node. js: 12.8.1 V8: 7.8.279.23-electron.0 
OS: Windows_NT x64 6.3.9600

Totvs Developer Studio for VSCode (AdvPL, TLPP e 4GL)
Versão 1.0.3

Dados do Server 
Informações do AppServer
Tipo do servidor;Console
AppServer Build;7.00.191205P-20200424
Appserver version;19.3.0.4
Servidor 64 bits;Sim
Servidor Unix;Não

Informações da LIB
Versão da Lib;20200504
Data da Lib;20200403_133549
ID da Lib;00f96be495b9f3c5ed7e244639ea63e63b7c3b8b
Release;12.1.025
HardLock;2014
Versão do License Server;2.0.0
Versão do Protheus;TOTVS Manufatura
Dicionário no banco de dados;Não

**Comment by brunobc00** [comment]
Boa tarde, 
O mesmo erro esta ocorrendo aqui comigo.
appserver 7.00.191205P aqui conecto no appserver, mas nao consigo debugar.

[dap.log](https://github.com/totvs/tds-vscode/files/4793726/dap.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/4793727/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/4793728/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/4793729/totvsls_out.log)

**Comment by fwsoares** [comment]
boa noite,
estou tendo este mesmo problema após atualizar o binário do protheus para o 19.3.0.4
[totvsls.log](https://github.com/totvs/tds-vscode/files/4795144/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/4795145/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/4795146/totvsls_out.log)

**Comment by lwtnb-wrk** [comment]
@brunobc00 Voce atualizou o binario do appserver recentemente? 
Consegue testar com um appserver de uma versao anterior para ver se o problema tambem ocorre?
Vi que o erro que está ocorrendo é um abort no debugAdapter. Qual a versão de SO você utiliza?

@fwsoares Pelo log ocorreu erro no login. O AppServer indicou que o usuário/senha estão incorretos. Teste o seguinte, ao invés de Reconect, utilize o Connect e informe novamente o usuário/senha. Se o erro persistir anexo o novo log gerado e também o console.log do AppServer.

**Comment by brunobc00** [comment]
Sim atualizei, faz um tempo que estamos na nova versão. Infelizmente to sem o backup da versao do appserver antigo, se puder me passar eu faço o teste.
Esse erro esta ocorrendo quando eu tento debugar na minha base teste, tanto o vscode quanto a base teste estao usando ubuntu 20.04
Ao retirar a conexão SSL e voltar para o TCP
[Drivers]
Active=TCP
MultiProtocolPortSecure=0
MultiProtocolPort=0

o debug funciona normalmente.

**Comment by lwtnb-wrk** [comment]
@brunobc00 Grato pelas infomações sobre o SSL. Temos outros relatos de comportamentos inesperados com o uso do SSL.

**Comment by maurorajr** [comment]
@brunobc00 , aqui onde trabalho estamos utilizando um appserver exclusivo só para configurar os ambientes no VSCode, exatamente pelo fato de ter que configurar o MultiProtocolPortSecure e MultiProtocolPort. Pelo que vi na própria documentação da Totvs, adicionar estes parâmetros não é uma boa opção devido questões de segurança, porém como precisamos dele para funcionar a conexão do VSCODE, criamos um appserver a parte só para ele.
