### ISSUE TITLE
Debug não para no Breakpoint

### ISSUE THREAD

**Issue by WFilhocompany** [totvs/tds-vscode#408]
Olá à todos,

Estou com uma situação que não consigo resolver, já desinstalei e instalei o VSCode umas 10 vezes e o problema ainda persiste. O que ocorre ?
Eu abro um Fonte e coloco um Breakpoint no mesmo e no Debug o VSCode não respeita o ponto de parada, em algumas situações ele passa pelo breakpoint e depois volta, seria mais ou menos como estar debugando fonte na versão errada, eu sei que passou direto e depois voltou por causa das variáveis que não deveriam conter valor naquele momento e estão com valores atribuídos.
É um situação bastante estranha, pois como eu disse depende de onde sei breakpoint está no fonte ele para e depois volta ou então passa direto, nunca respeitando o momento correto do debug.

Alguém já passou por algo semelhante ou teria um norte para me ajudar ?

**Comment by lwtnb-wrk** [comment]
@WFilhocompany Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar logs e nos envie para que possamos analisar.

**Comment by WFilhocompany** [comment]
[dap.log](https://github.com/totvs/tds-vscode/files/4780934/dap.log)

Achei o DAP.LOG, os demais arquivos de LOG não foram gerados, vou tentar novamente.

**Comment by WFilhocompany** [comment]
@lwtnb-wrk , está gerando somente o arquivo de DAP.LOG os demais arquivos solicitados não está sendo gerado.
As configurações foram preenchias conforme a documentação solicitada, e também foi re-iniciado o VSCode, mas não foi gerado os arquivo totvs de log.

**Comment by WFilhocompany** [comment]
@lwtnb-wrk , eu tive de colocar na Configuração da WorkSpace para gerar os Arquivos de LOGs solicitados e não no settings.json da pasta .vscode do Projeto como solicita a documentação.

**Comment by WFilhocompany** [comment]
[dap.log](https://github.com/totvs/tds-vscode/files/4781064/dap.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/4781065/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/4781066/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/4781067/totvsls_out.log)

Segue em anexo os LOGs faltantes solicitados.

**Comment by lwtnb-wrk** [comment]
@WFilhocompany Nos logs realmente não parece que houve nenhum problema.
Como você comentou que trabalha com workspaces, confirme se o fonte que você está debugando existe em mais de um local. Isso realmente poderia ocasionar comportamentos inesperados.
Se puder gravar um video demonstrando o problema, nos envie para ajudar na analise.

**Comment by WFilhocompany** [comment]
Como eu posso enviar esse vídeo para vocês ??? Pois o GitHub não está aceitando.
E o compactado em .ZIP tem quase 300Mb e o GitHub não aceita maior que 10Mb ?

**Comment by WFilhocompany** [comment]
@lwtnb-wrk , segue abaixo o Link de Compartilhamento do OneDrive para que possa baixar o vídeo.

https://1drv.ms/u/s!AjFgOuUPl9AXj6QPyccznwnNdq6wNg?e=Eqj1Gf

**Comment by lwtnb-wrk** [comment]
@WFilhocompany Notei que você utilizou o SIGAMDI para debugar.
Experimente usar o SIGAADV e selecione o SIGAFIN ou use diretamente o SIGAFIN.
E veja se a depuração funciona corretamente.

**Comment by WFilhocompany** [comment]
@lwtnb-wrk , a situação é a mesma.
Utilizei SIGAFIN

**Comment by WFilhocompany** [comment]
@lwtnb-wrk , Algo mais que poeria fazer ???? Estou precisando debugar e não consigo.

**Comment by lwtnb-wrk** [comment]
@WFilhocompany Fiz um teste simulando o cenario que voce tem e aqui funcionou normal.
Declarei um array local e adicionei elementos via aadd. Coloquei um breakpoint no primeiro aadd e como esperado a variavel nao contem nenhum elemento ao parar no breakpoint.
O tds-vscode apenas "conversa" com o AppServer entao se ao parar no 1o breakpoint ele informa que esta variaveis ja contem valores, isso esta vindo do AppServer. 
Aparentemente um outro "processo" esta passando pelo fonte antes, e isso poderia ocorrer no cenario usando o SIGAMDI que utiliza outras threads. Mas nao deveria ocorrer utilizando diretamente o SIGAFIN por exemplo.
Agora me ocorreu que isso pode ocorre com JOBS tambem. Poderia enviar seu asspserver.ini para analisarmos?

**Comment by WFilhocompany** [comment]
[appserver.zip](https://github.com/totvs/tds-vscode/files/4787228/appserver.zip)

Segue o arquivo solicitado.

**Comment by WFilhocompany** [comment]
@lwtnb-wrk , Eu também tentei tirando o SSL que está configurado no .ini e não deu certo tb.

**Comment by lwtnb-wrk** [comment]
@WFilhocompany Realmente não sei o que pode estar ocorrendo. 
Depois de parar no 1o breakpoint se você clicar em F10 (Step over) ele vai pulando para as próximas linhas corretamente ou fica pulando para linha "sem sentido"?

**Comment by WFilhocompany** [comment]
@lwtnb-wrk , Eu retirei os comentários do fonte e deixei somente à Programação e obtive o seguinte resultado:
Nessa fonte que tirei os comentário o Debug passou a ser realizado com 1 linha de diferença entre o executado e a linha que realmente está posicionado na DEBUG, Exemplo, Coloco o Breakpointo na Linha 28, o Degub para na Linha 28, mas as informações são da Linha 29 e quando eu preciono F10, vai para linha 29, mas as informações são da Linha 30 e assim sucessivamente.
Não estou entendendo mais nada.

**Comment by WFilhocompany** [comment]
@lwtnb-wrk , creio que descobri o problema.
O Problema está nas minhas quebras de linha, quando o fonte possui uma linha em branco de o breakpoint não é executado corretamente, mas quando eu deixo o mesmo fonte sem nenhuma quebra de linha em branco, com todas as linhas juntas ele para no breakpoint corretamente.
Acho que o problema está quando o VSCode envia os Dados para o Server e na Quebra de Linha está enviando de forma incorreta fazendo que o mesmo não entenda quando é uma Quebra de Linha em Branco e uma Quebra de Linha com informações.
Os fontes estão na tipo de letra Windows 1252 conforme solicitado pelas documentações da TOTVS.

**Comment by lwtnb-wrk** [comment]
@WFilhocompany Então na situação inicial quando parava na linha 28 ele estava mais adiante no fonte e já havia processado os AADD e por isso os arrays já continham valores. É isso?
Isso faz sentido pois o AppServer tinha um fonte compilado que estava diferente do fonte aberto no editor.
Enfim, também reparei que um dos fonte esta com quebra de linha LF e o outro com CRLF (Veja no rodapé do editor do lado do encoding Windows 1252). De onde você pegou os arquivos?

**Comment by WFilhocompany** [comment]
@lwtnb-wrk , Agora que descobri que a questão está na Quebra de Linha eu removi as linhas em branco, mudei de CRLF para LF troquei os Encoding para UFT-8 e Windows 1252 e nenhuma dessa mistura de configuração deu certo, todas não respeitou a situação quando havia uma quebra de linha com uma Linha em Braco, não importando a configuração que eu muda-se e as combinações que fizesse.
Tentei até criar os Arquivo pelo Bloco de Notas e tentei pelo VSCode também e sempre o resultado foi o mesmo.

**Comment by WFilhocompany** [comment]
@lwtnb-wrk , para complementar os testes, eu agora instalei o Eclipse e atualizei o mesmo com o Patch para o novo server, peguei o mesmo fonte no Eclipse, Compilei no mesmo server e rpo que estou utilizando com o VSCode, com as linhas em branco e funcionou perfeitamente o breakpoint.

**Comment by lwtnb-wrk** [comment]
@WFilhocompany Voce pode nos enviar os fontes que estao com problema para vermos se conseguimos reproduzir o problema com eles aqui?

**Comment by WFilhocompany** [comment]
[FONTES_COM_PROBLEMA.zip](https://github.com/totvs/tds-vscode/files/4798879/FONTES_COM_PROBLEMA.zip)

Coloque no Menu o Fonte FINT01P, depois um Breakpoint na Chamado do Fonte U_FINM03P() se durante o seu debug apresentar a tela do FormBatch já não foi ter parado no breakpoint que deveria.
Depois eu coloquei um breakpoint no primeiro array para acompanhar a geração de tela via F10 e percebia a inconsistência das linhas.

Outra coisa que percebi é que quando compila é informando no Server a Quantidade de Linhas do fonte, nas compilações já são apresentadas quantidade de linhas menores que a existente no fonte.

**Comment by lwtnb-wrk** [comment]
@WFilhocompany Compilei os arquivos e ambos apresentaram no console.log o mesmo numero de linhas dos respectivos fontes.
Ao debugar eles pararam corretamente nas linhas e as variáveis estavam conforme esperado.
Não sei mais o que pode ser que esteja ocorrendo em seu ambiente.
Se conseguir teste em outra máquina para ver se é algo em particular da sua máquina.

**Comment by WFilhocompany** [comment]
@lwtnb-wrk , A única coisa que poderia estar diferente é a Instalação do Plugin de Português para o VSCode, pois o meu VSCode tem somente o Plugin da TOTVS do ADVPL e o Plugin de Português para o VSCode da Microsoft.

**Comment by lwtnb-wrk** [comment]
@WFilhocompany Problema não reproduzido em nossos testes aqui. Conseguiu testar em outro ambiente? 
Se ainda estiver com problema reabra esta issue com mais informações.

**Comment by LyndaCosta** [comment]
Prezados, esse erro aconteceu comigo após atualizar para nova versão do VS Code, e reparei que só acontecia quando tentava debugar utilizando o comando CTRL+F5, mas se eu fizesse através do botão existente, o debug funcionava corretamente. Não sei se será útil, mas fica ai uma opção de teste.

**Comment by brodao2** [comment]
@LyndaRolim 

Verifique as configurações de atalho (F1, filtro: >open keyboard settings).
![image](https://user-images.githubusercontent.com/114854608/212381757-b234f595-5ae8-46b2-9a12-6223241056ac.png)
![image](https://user-images.githubusercontent.com/114854608/212382092-4dd6a2cd-9ddc-4c51-bb0b-4275d054959a.png)
