### ISSUE TITLE
Unificação de Log Compilação Pasta

### ISSUE THREAD

**Issue by robsonrosilva** [totvs/tds-vscode#41]
Poderiam colocar para só mostrar as mensagens quando finalizar a compilação de toda a pasta, ao invés de mostrar uma mensagem para cada fonte.

**Comment by lwtnb-wrk** [comment]
@robsonrosilva Voce diz mensagem no console (output) ou notificacao (janelinha no canto inferior direito)?
as mensagens no console, acho que fazem sentido terem todas, para controle de o que esta ocorrendo.
quanto as notificacoes elas serao configuraveis, sendo o padrao a exibicao de erros e warnings apenas, entao as informacoes aparecerao no console, mas as notificacoes so aparecerao se forem warnings ou erros.
na liberacao da proxima versao no comeco da semana que vem, voce pode validar se isso vai te atender e se atender fechamos essa issue ok?

**Comment by robsonrosilva** [comment]
Falo das notificações mesmo, vou testar então essa versão da semana que vem e falo se atende.
Obrigado pela atenção.

**Comment by lwtnb-wrk** [comment]
@robsonrosilva ficaremos no aguardo entao! valeu!

**Comment by lwtnb-wrk** [comment]
@robsonrosilva testou a nova versão? estamos exibindo, por padrao, apenas erros e warnings, entao as notificacoes de info sao exibidas apenas no console output, reduzindo a poluicao visual das notificacoes. estou fechando essa issue, mas se tiver outras questoes fique a vontade para abrir outras issues

**Comment by robsonrosilva** [comment]
Boa tarde,
Vi a forma que ficaram as notificações, essa issue que abri foi para verificar a possibilidade de simplificar as notificações quando é compilada uma pasta.
Pedi para compilar uma pasta com 5 fontes olha a quantidade de alertas que apareceram:
![image](https://user-images.githubusercontent.com/26228097/58497443-597a4f00-8152-11e9-9dac-1d3c5b37c5a5.png)

Acredito que seria melhor dar uma notificação no inicio do processo de compilação e uma no fim com o resultado, os detalhes de cada arquivo na minhão visão podem ser vistos no CONSOLE.

**Comment by lwtnb-wrk** [comment]
@robsonrosilva Poderia por gentileza verificar como estao configuradas suas preferencia de exibicao de notificacao? Utilize o atalho CTRL+, (virgula) para acessar suas preferencias e filtre por TOTVS para facilitar. Deve haver as opcoes de niveis de notificacoes como segue, veja que no meu caso escolhi exibir apenas Erros e Warnings, para evitar a exibicao de multiplas informacoes de menor grau de importancia. Mas todas essas informacoes sao enviadas ao Output (saida)  
![image](https://user-images.githubusercontent.com/49563478/58554566-aa8b5100-81ed-11e9-9493-4646b72bbe9f.png)

**Comment by lwtnb-wrk** [comment]
@robsonrosilva Somente um adendo. Achei que tinhamos colocado o padrao (Default) para "Errors and Warnings", mas vi que o padrao saiu como "All" entao realmente voce vai precisar alterar de "All" para "Errors and Warnings" para ver a diferença... Na proxima liberação vamos enviar como padrão o "Errors and Warnings", mas como isso deve ficar gravado em seu arquivo de preferencias, seria preciso alterar manualmente mesmo... Espero que alterando para "Errors and Warnings" fique como voce precisa.

**Comment by robsonrosilva** [comment]
Pergunta teria como criar um meio termo, pois usando só warnings e errors não mostra se tentou compilar, se compilar sem erros ou alertas não vejo nenhuma notificação ai tenho que ir no console se quiser saber se compilou.

**Comment by lwtnb-wrk** [comment]
> Pergunta teria como criar um meio termo, pois usando só warnings e errors não mostra se tentou compilar, se compilar sem erros ou alertas não vejo nenhuma notificação ai tenho que ir no console se quiser saber se compilou.

Se habilitar todas as notificacoes vai aparecer todos os fontes compilados, seja com sucesso ou com erro. 
Se desabilitar as notificacoes de INFO elas estarao disponiveis somente no Output para nao poluir o visual com multiplas notificacoes.
@robsonrosilva O que voce propoe entao?

**Comment by robsonrosilva** [comment]
@lwtnb-wrk acho que o ideal seria independentemente da configuração das notificações algumas serem exibidas.
- Inicio de compilação.(no caso de compilação de pasta só exibir uma vez)
- Fim de Compilação.(no caso de compilação de pasta só exibir uma vez)
- Resultado de Conexão com o Servidor.
