### ISSUE TITLE
Erro ao gerar client WS

### ISSUE THREAD

**Issue by danielblaia** [totvs/tds-vscode#410]
Boa tarde
Estou conectando um cliente no Tcloud da Totvs:
higimasterdistribuidora108834.protheus.cloudtotvs.com.br
Ao tentar gerar um client WS ele da erro pedindo que conecte o server, mas já está conectado.
Vou anexar um video:

[AutoScreenRecorder_06 Jun. 16 15.14.zip](https://github.com/totvs/tds-vscode/files/4788364/AutoScreenRecorder_06.Jun.16.15.14.zip)

**Comment by lwtnb-wrk** [comment]
@danielblaia Voce tem outro plugin de AdvPL instalado? Aparentemente você esta tentando usar o gerador de outro plugin.
Veja a documentação https://github.com/totvs/tds-vscode#gera%C3%A7%C3%A3o-de-client-ws-protheus

**Comment by danielblaia** [comment]
oi, quais plugins eu preciso ter instalados?

**Comment by danielblaia** [comment]
deu certo, removi tudo e instalei de novo, deu certo!
Obrigado @lwtnb-wrk !!!
