### ISSUE TITLE
Erro ao incluir servidores

### ISSUE THREAD

**Issue by MafraL14** [totvs/tds-vscode#411]
Bom dia,  
Ao incluir um servidor, após informar os dados do servidor é apresentada a seguinte mensagem de erro e o servidor não é incluso:

Cannot read property 'forEach' of undefined

**Expected behavior**

**Screenshots**
![Erro ao incluir server](https://user-images.githubusercontent.com/67073413/85018186-2468e200-b143-11ea-99a6-7ba040a8e363.PNG)

 - OS/Architecture: [pt Windows 64 bits]

**Appserver (please complete the following information):**
 - Build (with date): [e.g. Build 7.00.170117A - Jun 28 2019 - 11:16:56]
 - OS/Architecture: [pt Windows 64 bits]
-Versão: [TOTVS Manufatura]
-Build AppServer: [7.00.191205P-20200424 - 64 bits]
-Appserver version: [19.3.0.4]
-Build DBAccess: [20181212-20191121]
-Release do RPO:  [12.1.025]
-Release do dicionário: [12.1.025]
-Local files: [CTREE]
-License server: [2014 - 2.3.4]
-DB DataBase: [MSSQL]
-DB API Build: [20191119-20200116]

Desde já, agradeço pela ajuda.

*

**Comment by lwtnb-wrk** [comment]
@MafraL14 Apesar de não apresentar a mesma mensagem acredito que seja o mesmo problema descrito em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#erro-ao-adicionar-servidores
Caso não consiga resolver com isso gere e nos envie os logs para analise https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs

**Comment by MafraL14** [comment]
Problema resolvido, muito obrigado !
