### ISSUE TITLE
VsCode não conecta ambiente TSS

### ISSUE THREAD

**Issue by RodrigoTeixeira-2101** [totvs/tds-vscode#412]
Olá, 

Desde que passamos a utilizar o VsCode que não consigo mais conectar ao ambiente do TSS para aplicar patchs no repositorio, o acesso via SMARTCLIENT do TOTVSSPED se dá normalmente com o usuario padrão ADMIN, porem, ao tentar conexão com este mesmo usuario via VsCode tenho a mensagem de falha na autenticação.

Att
Rodrigo Teixeira

**Comment by brodao** [comment]
@RodrigoTeixeira-2101 ,

Favor gerar os logs conforme https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md e anexá-los a este chamado.

No aguardo.

**Comment by RodrigoTeixeira-2101** [comment]
Aqui estão os logs meu amigo !

               Atenciosamente,

 [http://www.vivaceescola.com.br/ass/logotipo.png]
RODRIGO TEIXEIRA DE SOUZA
Coordenador de Implantação/Integrações - ERP Protheus
Tel: +55 (62) 3946-8081  ou  +55 (62) 3946-8041
e-mail:    rodrigo.souza@datatraffic.com.br<mailto:%20%20%20rodrigo.souza@datatraffic.com.br>
WebSite: www.datatraffic.com.br<http://www.datatraffic.com.br/>


De: Alan Cândido [mailto:notifications@github.com]
Enviada em: terça-feira, 23 de junho de 2020 14:22
Para: totvs/tds-vscode <tds-vscode@noreply.github.com>
Cc: Rodrigo Teixeira de Souza <rodrigo.souza@datatraffic.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [totvs/tds-vscode] VsCode não conecta ambiente TSS (#412)


@RodrigoTeixeira-2101<https://github.com/RodrigoTeixeira-2101> ,

Favor gerar os logs conforme https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md e anexá-los a este chamado.

No aguardo.

**Comment by RodrigoTeixeira-2101** [comment]
[Temp.zip](https://github.com/totvs/tds-vscode/files/4821344/Temp.zip)

**Comment by brodao** [comment]
@RodrigoTeixeira-2101 

O que veio são prints de "locks de tabelas". Eu preciso dos arquivos de logs, gerados conforme descrito em "troubleshooting".

**Comment by RodrigoTeixeira-2101** [comment]
OPA... foi mal!!!

**Comment by RodrigoTeixeira-2101** [comment]
Opa ... aqui Alan.

**Comment by RodrigoTeixeira-2101** [comment]
[VsCode.zip](https://github.com/totvs/tds-vscode/files/4821728/VsCode.zip)

**Comment by brodao** [comment]
Pelos logs, o comportamento do VSCode para ok. Verifique:

1. O usuário e/ou senha está retornando como inválido. Certifique-se que
esta corretos. Salvo engano meu, a senha é sensível a caixa.;

2. No momento da ocorrência, verifique no log do appServer, se há alguma
informação que possa ajudar;

3. Configuração do servidor de licenças e se há licenças disponíveis (salvo
engano precisar tem ao menos uma).

Alan Cândido ><>


*Especialista de Pesquisa e DesenvolvimentoExpert Research and Development*
.[====].[====].(----).(----).\___/.[___].]@|--Y\_
 _o__o___o__o___o__o___o__o___o_o___o_o___O___oo_\


Em ter., 23 de jun. de 2020 às 17:22, RodrigoTeixeira-2101 <
notifications@github.com> escreveu:

**Comment by RodrigoTeixeira-2101** [comment]
Este é o problema Alan, o log nunca gera nada que direcione para uma correção.
A senha do usuario, conforme mencionado é informada exatamente conforme senha que utilizo para conectar via SMARTCLIENT do TSS. 
Totvs sendo Totvs !
COMPLICADO DEMAIS viu meu amigo!

**Comment by jonermarcelo** [comment]
Boa tarde.

A principio, também não consigo conectar meu VSCODE no TSS (12.1.27 - Instalação padrão do portal). Também é informado erro de autenticação.

Segue evidência.
![tela](https://user-images.githubusercontent.com/68082122/87085548-6ea32780-c206-11ea-9abc-55de5efc1936.png)

**Comment by RodrigoTeixeira-2101** [comment]
Seguinte: 
Para resolver o caso, ao tive que fazer a atualização do link abaixo:
https://suporte.totvs.com/portal/p/10098/download#detail/737297

E outro detalhe é que a validação não é mais realizada pelo usuario local da instalação do TSS e sim a validação deve ser realizada pelo ADMIN e senha que voce tem no Protheus.

Att
Rodrigo Teixeira

**Comment by lwtnb-wrk** [comment]
@RodrigoTeixeira-2101 Grato por compartilhar essa informação.

**Comment by jonermarcelo** [comment]
@RodrigoTeixeira-2101, estou com o mesmo problema.

Tentei utilizar o binário que repassou, mas não adianta... ocorre à mesma situação...

**Comment by RodrigoTeixeira-2101** [comment]
Ola Marcelo, 

Coloca estas duas chaves no [General] do appserver.ini do seu TSS.
Utilize as credenciais do ADMIN conforme loga no seu sigacfg.
O novo appserver deve ser atualizado na pasta de instalação do seu TSS e não no Protheus, ok ?
Exclua e crie uma nova conexão no seu vscode para o TSS.

Att
Rodrigo Teixeira

**Comment by RodrigoTeixeira-2101** [comment]
Aqui as chaves Marcelo:

MultiProtocolPortSecure=0
MultiProtocolPort=0

**Comment by RodrigoTeixeira-2101** [comment]
Se não consegui, me manda msg no rodrigoteixeira1975@gmail.com que tento te ajudar ai !!!

**Comment by jonermarcelo** [comment]
@lwtnb-wrk e @RodrigoTeixeira-2101, segue abaixo algumas informações que descobri à respeito:

1*) Se o TSS e o ERP Protheus estiverem apontando para o mesmo database, não conecta\autentica o TSS no VSCODE de jeito nenhum. Criei um banco só para o TSS e ao tentar conectar no AppServer do TSS via VSCODE deu certo.

2*) Por mais que o usuário ADMIN do TSS tenha uma senha definida, se informar à senha dá o erro de autenticação, se informar apenas o usuário ADMIN sem senha, conecta\autentica no VSCODE.

**Comment by lwtnb-wrk** [comment]
Apenas sumarizando a questão de conexão no TSS, para utilizar um ambiente TSS no tds-vscode utilize o usuário/senha que conecte ao SIGACFG e que é diferente do usuário utilizado para se conectar pelo Smarclient do TSS.

**Comment by pedrojlima** [comment]
Bom dia, no meu caso, o Tss não solicita a senha e nem da erro. Coloco o Environment e não solicita o usuário e nem a senha.
[Gravar_2022_07_28_09_22_30_188.zip](https://github.com/totvs/tds-vscode/files/9209436/Gravar_2022_07_28_09_22_30_188.zip)

**Comment by brodao** [comment]
Normalmente isso ocorre quando o ambiente informado esta errado. Verifique a configuração no server.
Caso persista, favor abrir um novo chamado informando os dados solicitados conforme [Informações importantes ao abrir o chamado](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#informa%C3%A7%C3%B5es-importantes-ao-abrir-uma-issue) e anexe os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)
