### ISSUE TITLE
Conexão cai no Debug em ambiente T-Cloud

### ISSUE THREAD

**Issue by veltonteixeira** [totvs/tds-vscode#413]
Sempre que tento debugar no ambiente hospedado no TCloud, a conexão cai, para ambientes com servidores locais, debuga normalmente.

Obs.: O problema ocorria também com o TDS, abri chamado junto ao cloud e eles me orientaram a abrir um novo chamado aqui.

Segue em anexo vídeo.
[2020-06-21 at 22-09-32.zip](https://github.com/totvs/tds-vscode/files/4822751/2020-06-21.at.22-09-32.zip)

**Comment by lwtnb-wrk** [comment]
@veltonteixeira Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.
Se possivel peça e nos envie o console.log do AppServer tambem.

**Comment by veltonteixeira** [comment]
Boa Tarde @lwtnb-wrk,  

Segue os logs do VSCODE, como o server é in cloud, solicitei console.log
 via chamado, assim que eles me enviarem eu posto aqui.

[Logs.zip](https://github.com/totvs/tds-vscode/files/4827369/Logs.zip)

**Comment by veltonteixeira** [comment]
Segue o console.log

[104798-core_instance-n_pr_d_cgqj8z-1-041c82f8dblin_console_appserver.zip](https://github.com/totvs/tds-vscode/files/4827495/104798-core_instance-n_pr_d_cgqj8z-1-041c82f8dblin_console_appserver.zip)

**Comment by lwtnb-wrk** [comment]
@veltonteixeira Pelo console.log vejo que os servidores estão configurados em Load Balance e não é possível depurar neste tipo de configuração. 
Você precisaria de acesso direto a um dos servidores que está sendo usado pelo Load Balance, i.e., acesso ao IP:porta de um dos slaves.
Provavelmente nesse ambiente TCloud isso não será disponibilizado pois deve envolver questões da topologia e segurança.
Outro ponto que observei no console.log é que o programa acessado foi o SIGAMDI. Ao depurar deve-se utilizar o módulo diretamente (por exemplo SIGAFIN) ou acessá-lo através do SIGAADV.
O melhor mesmo é depurar localmente em um ambiente que seja idêntico ao do T-Cloud.
