### ISSUE TITLE
Configuração de Novo Servidor não é salva

### ISSUE THREAD

**Issue by GersonBelini** [totvs/tds-vscode#414]
Quando vamos configurar um novo servidor recebemos a seguinte mensagem: Cannot read property 'forEach' of undefined

Já removemos toda a instalação, instalamos novamente e continuamos com a mensagem.

**Comment by lwtnb-wrk** [comment]
@GersonBelini Veja como resolver em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#erro-ao-adicionar-servidores
Se ainda não conseguir, gere logs e grave video para nos mostrar o problema ocorrendo.
