### ISSUE TITLE
Problemas para o usar o inspetor de objetos! 

### ISSUE THREAD

**Issue by fernandogriecco** [totvs/tds-vscode#415]
**Describe the bug**
Ao tentar recuperar os fontes através do processo de Inspetor de objetos, em um server especifico o sistema informa que não conseguiu recuperar os dados: 
![image](https://user-images.githubusercontent.com/67428337/85746237-b1301480-b6dc-11ea-9c92-6e70ed33ae07.png)

Tem momento que ele consegue fazer e tem momentos q não. 

**To Reproduce**
Estou usando o Ultimo app server, com o RPO D-1 da TOTVS. 

Ao avaliar console log é possível ver q ele apresenta um erro:
![image](https://user-images.githubusercontent.com/67428337/85746656-fe13eb00-b6dc-11ea-9c6e-136cb8a9d22f.png)

**Expected behavior**
Obter a lista de fontes do repositório

**Screenshots**

**Desktop (please complete the following information):**
 - OS/Architecture: [e.g. Windows 64 bits]

**Appserver (please complete the following information):**
 - Build (with date): [e.g. Build 7.00.170117A - Jun 28 2019 - 11:16:56]
 - OS/Architecture: [e.g. Linux 64 bits Ubuntu]
 - Build Version [e.g. 17.3.0.13]
[Log_Appserver.zip](https://github.com/totvs/tds-vscode/files/4832193/Log_Appserver.zip)

**Additional context**
Esse problema acontece tanto com o Inspetor de Objeto, Inspetor de Funções, e as funcionalidade de Defrag. 

Se incluir a TAG buildKillusers = 1 no server. 
O erro passa a ser: 
![VsCode_Inspetor](https://user-images.githubusercontent.com/67428337/85761730-6cf74100-b6e9-11ea-906c-e24d263edff6.png)

**Comment by lwtnb-wrk** [comment]
@fernandogriecco Nas informações do AppServer voce informou que era uma build 170117, mas no console.log aparece que e uma build 191205... E se a build correta for a 191205 verifique se o SSL esta ligado e experimente desabilitar o SSL realizar as mesmas operações.
Se os problema persistirem veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar logs e nos envie para analise.

**Comment by fernandogriecco** [comment]
@lwtnb-wrk , quando vc fala sobre o SSL, vc se refere a configuração dentro do próprio VSCode certo? Opção Secure no ambiente certo? 
Gerei os logs rodando com as duas opções, porém com Secure 0 ele não conecta no servidor. 

[Vs_Logs_Secure0.zip](https://github.com/totvs/tds-vscode/files/4833195/Vs_Logs_Secure0.zip)
[Vs_Logs_Secure1.zip](https://github.com/totvs/tds-vscode/files/4833196/Vs_Logs_Secure1.zip)
Qualquer dúvida estou a disposição.

**Comment by lwtnb-wrk** [comment]
@fernandogriecco Era no AppServer mesmo. Temos diversos relatos de problemas causados pela configuração de SSL do AppServer. Desabilite no AppServer e no VSCode configure como Secure: 0 para testar mesmo.

Realmente se a flag Secure e a configuração do AppServer não coincidirem não vai conectar mesmo.

**Comment by fernandogriecco** [comment]
Mas eu não tenho nenhuma configuração no meu INI para o SSL certo? agora pelo que tinha entendido era nativo?
Como desabilitar tenho que usar a tag [SSLConfigure]? com quais opções sabe dizer?

**Comment by lwtnb-wrk** [comment]
@fernandogriecco Para este teste adicione esta configuração no appserver.ini , reinicie o AppServer e nos informe dos resultados.

[Drivers]
MultiProtocolPort=0

**Comment by fernandogriecco** [comment]
@lwtnb-wrk , Fiz aqui e rodou apenas uma vez, depois tentei mudar de ambiente e recuperar de novo e voltou a ficar com a mesma mensagem. 

Segue log das tentativas. 
[console.zip](https://github.com/totvs/tds-vscode/files/4833543/console.zip)
[Secure_Disable.zip](https://github.com/totvs/tds-vscode/files/4833544/Secure_Disable.zip)

**Comment by lwtnb-wrk** [comment]
@fernandogriecco Peguei a última versão do AppServer (19.3.0.4) e consegui reproduzir o problema aqui também. No AppServer (19.3.0.3) este problema não foi observado.
O time do AppServer já foi comunicado sobre o problema e devem resolver esse problema na próxima versão.
Por se tratar de um problema no AppServer não temos nada que possamos fazer. Somente aguardar a liberação da correção do Appserver prevista para o final de Julho.

**Comment by lwtnb-wrk** [comment]
@fernandogriecco Como paliativo experimente realizar o Defrag do RPO... Em alguma situações resolveu o problema.

**Comment by lwtnb-wrk** [comment]
Manterei esta issue aberta para consulta ate que o proximo Appserver seja liberado

**Comment by jsiq84** [comment]
Estou com o mesmo problema e já Verifiquei os passos acima relatados. 
Haveria uma saída contorno para isso...??

**Comment by lwtnb-wrk** [comment]
@jsiq84 Você já tentou a solução paliativa e não funcionou?

**Comment by jsiq84** [comment]
O defrag ??

**Comment by lwtnb-wrk** [comment]
@jsiq84 Isso mesmo. 
Não havia ficado claro se você já havia tentado o Defrag.
Se isso não funcionou, tente reiniciar o Appserver.
Mas se nada disso funcionar só usando o Appserver anterior 19.3.0.3 ou aguardar a próxima atualização.

**Comment by brodao** [comment]
Encerrado pois o problema é gerado pelo servidor Protheus.
