### ISSUE TITLE
Disponibilizar o breakpoint do tipo function.

### ISSUE THREAD

**Issue by walterfcarvalho** [totvs/tds-vscode#417]
Seria possivel implementar breakpoint do tipo  breakpoint at function.

[https://ephos.github.io/posts/2017-9-10-VSCode-Debugging-CondBreakPoint#:~:text=To%20add%20a%20conditional%20breakpoint,options%2C%20Hit%20Count%20and%20Expression.](https://ephos.github.io/posts/2017-9-10-VSCode-Debugging-CondBreakPoint#:~:text=To%20add%20a%20conditional%20breakpoint,options%2C%20Hit%20Count%20and%20Expression.)

**Comment by DanielYampolschi** [comment]
Ola @walterfcarvalho obrigado pela sugestão. Mas para esclarecer, você está falando de uma opção para entrar diretamente na função ao acionar um "step into", conforme fala o texto que você enviou certo?

**Comment by walterfcarvalho** [comment]
tudo bem ? a. intenção seria para habilitar o breakpoint que é feito avaliando uma condição hoje só está habilitado break plinto na linha do fone

**Comment by DanielYampolschi** [comment]
Humm.. ta certo, então qual a versao do seu plugin do tds-vscode? Pergunto porque essa funcionalidade já existe tem algum tempo:

![image](https://user-images.githubusercontent.com/10711513/85862550-4d6b2180-b798-11ea-8b80-190f87c1b308.png)

![image](https://user-images.githubusercontent.com/10711513/85862640-6f64a400-b798-11ea-81a5-d97e41842a2c.png)

Você esta com algum problema pra usá-la?

**Comment by DanielYampolschi** [comment]
Porém, apos te enviar essa mensagem, reparei que essa funcionalidade não está na documentação na página inicial aqui no GitHub... vou providenciar...

**Comment by walterfcarvalho** [comment]
![image](https://user-images.githubusercontent.com/11591494/85864261-ad62c780-b79a-11ea-8168-5caf191928b1.png)

Ah, desse  jeito aí vai de boas hein ? awsome!
