### ISSUE TITLE
"this Machine Id" em branco

### ISSUE THREAD

**Issue by lucasndas** [totvs/tds-vscode#418]
**Describe the bug**
Ao utilizar o compile Key o ID da maquina não esta sendo preenchido. 

**To Reproduce**
CRTL + P 
Usar Compile Key

**Expected behavior**
Que o ID da maquina seja preenchido para poder solicitar uma chave de compilação

**Screenshots**
![image](https://user-images.githubusercontent.com/21094275/85877785-11db5200-b7ae-11ea-86d1-6aeb4757d0d6.png)

**Desktop (please complete the following information):**
 - OS/Architecture: Windows 64 bits

**Appserver (please complete the following information):**
 - Build (with date):  Build 7.00.191205P - Apr 24 2020 - 14:30:50
 - OS/Architecture: Windows 64 bits
 - Build Version 19.3.0.4

**Additional context**

**Comment by lucasndas** [comment]
[tdsSupport.zip](https://github.com/totvs/tds-vscode/files/4838080/tdsSupport.zip)
Logs para analise

**Comment by lwtnb-wrk** [comment]
@lucasndas No envie os logs novamente pois o zip parece corrompido

**Comment by lucasndas** [comment]
[tdsSupport1593190377600.zip](https://github.com/totvs/tds-vscode/files/4838191/tdsSupport1593190377600.zip)

**Comment by lwtnb-wrk** [comment]
@lucasndas Bom conforme nos falamos por outros canais, encontramos o problema.
Era a configuração das variaveis de ambiente do Windows que estava com problemas e nao tinha a pasta C:\Windows\system32\Wbem configurada no Path.
Com isso ele nao conseguia executar o WMIC e causava um erro interno.
Configurado o PATH o problema foi resolvido.
