### ISSUE TITLE
Erro de autenticação no debug quando usuário do windows possui acentos no nome

### ISSUE THREAD

**Issue by marcos-abrahao** [totvs/tds-vscode#419]
**Describe the bug**
Erro de autenticação no debug quando usuário do windows possui acentos no nome

**To Reproduce**
1. Logar com usuário do windows 10 com acento no nome
2. No vscode e conectar no server (v1.03 Totvs)
3. F5 - Debugar
4. Erro de autenticação: User not authenticated

**Comment by lwtnb-wrk** [comment]
@marcos-abrahao Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise

**Comment by marcos-abrahao** [comment]
Bom dia,

Fiz tudo que era possível na sexta-feira, reinstalei n vezes apaguei as pastas e não consigui compilar.

Após alterar o settings.json para gerar os logs o vscode compilou!!!

Obrigado.

**Comment by lwtnb-wrk** [comment]
@marcos-abrahao Não é a primeira vez que relatam isso aqui... Eu peço para ligarem a geração de log e o bug desaparece... Os bugs são tímidos e não gostam de se mostrar aos devs que querem remove-los...
