### ISSUE TITLE
Compilação de fontes Abertos

### ISSUE THREAD

**Issue by robsonrosilva** [totvs/tds-vscode#42]
Poderiam implementar um atalho para compilação de todos fontes abertos no editor.

**Comment by lwtnb-wrk** [comment]
@robsonrosilva Implementada a compilacao de fontes abertos atraves do atalho CTRL+F10 ou CTRL+SHIFT+F10 para recompilar fontes abertos. Pode ser acessado atraves de CTRL+SHIFT+P => "Compile Open Editors" tambem. 
Disponivel a partir da proxima liberacao.
* Nota: Ao disparar o comando ele vai navegar e coletar as informacoes dos fontes abertos, pois o vscode nao disponibiliza uma lista com os fontes abertos... Vai dar para ver ele navegando entre as abas. E se houverem muitos fontes abertos ele via passar um por um.

**Comment by robsonrosilva** [comment]
@lwtnb-wrk Obrigado pela implementação, poderia usaro Open-Editor(https://github.com/lahmatiy/open-in-editor) para obter os fontes abertos no editor sem trocar as abas.
É uma sugestão de melhoria, da forma que descreveu atende ao que eu via como necessário.

**Comment by DelleonFernandes** [comment]
Depois de algumas atualizações no vscode esta função parou de funcionar.
Estou na versão 1.42.1 Data: 2020-02-11T14:45:59.656Z elétron: 6.1.6 Chrome: 76.0.3809.146 node. js: 12.4.0 V8: 7.6.303.31-electron.0 OS: Windows_NT x64 10.0.18363
