### ISSUE TITLE
Ao compilar ele altera o codigo! o codigo DATEFROMPARTS fica DATE FROM PARTS apos compilar e o codigo nao funciona. preciso que ao compilar ele nao troque o codigo. Mantenha o DATEFROMPARTS.

### ISSUE THREAD

**Issue by diegoesf** [totvs/tds-vscode#420]
Ao compilar ele altera o codigo! o codigo DATEFROMPARTS fica DATE FROM PARTS apos compilar e o codigo nao funciona. preciso que ao compilar ele nao troque o codigo. Mantenha o DATEFROMPARTS.

**Comment by diegoesf** [comment]
![image_2020_06_20T20_34_10_021Z](https://user-images.githubusercontent.com/67561556/85965248-7525d980-b992-11ea-8ab9-45477182bd60.png)
![image_2020_06_20T20_34_38_401Z](https://user-images.githubusercontent.com/67561556/85965251-77883380-b992-11ea-9b6d-76c006c72973.png)

O codigo esta dentro da query. Ao compilar ele corrige o codigo de forma errada. Preciso que ele nao altere o codigo da query.

**Comment by lwtnb-wrk** [comment]
@diegoesf Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar logs e nos envie para analise.

Habilite tambem a geração de PPO em File > Preferences > Settings: 
E marque a opção: Extensions > AdvPL > Generate Ppo Files
Nos envie o arquivo PRW e o PPO gerado apos a compilacao

**Comment by diegoesf** [comment]
[logs.zip](https://github.com/totvs/tds-vscode/files/4855483/logs.zip)

em anexo.

**Comment by lwtnb-wrk** [comment]
@diegoesf Grato pelos arquivos. Pelo logs e pelo arquivo PPO realmente não parece haver nenhum problema com o tds-vscode, mas notei o uso da função ChangeQuery(cQuery) que me causou um desconfiança.
Fiz um teste simples em que constatei que o problema está nessa função ChangeQuery(cQuery).
Enquanto o Framework não efetua a correção desta função após as chamadas da ChangeQuery(cQuery) utilize:

cQuery := StrTran(cQuery, "DATE FROM PARTS", "DATEFROMPARTS")

para corrigir a cQuery.
Como não há nada que possa ser feito no tds-vscode esta issue será fechada.
