### ISSUE TITLE
Problema conexão a servidores com pasta de rede ja aberta por outro usuário

### ISSUE THREAD

**Issue by jowks** [totvs/tds-vscode#421]
**Describe the bug**
Na nossa empresa rodamos o protheus através do servidor, e cada usuário que tem acesso ao mesmo, busca os fontes customizados dentro de uma pasta no servidor. Ou seja, para ter acesso aos fontes é necessário abrir a pasta do servidor como uma workspace no VSCode e então efetuar as alterações. A praticidade é que se houver concorrencia do mesmo arquivo, o próprio VSCode trata essa concorrência e aplica as alterações em ambos os arquivos. 

Assim que um usuário já abriu a pasta na rede, os demais usuários conseguem abrir, porém não conseguem mais se conectar aos servidores do protheus. Resumidamente:
- Dois usuários abrem a mesma pasta na rede
- O primeiro usuário consegue se conectar aos servidores do protheus
- O segundo usuário não consegue mais se conectar aos servidores do protheus enquanto não trocar a workspace

**To Reproduce**
1. Criar uma pasta em rede
2. Abrir a pasta da rede em VSCode local com usuário X
3. Abrir a pasta da rede em VSCode local com usuário Y
3. Usuário X criar nova conexão e conectar aos servidor Protheus
4. Usuário Y tentar criar nova conexão e conectar ao servidor Protheus
5. Verificar erro no usuário Y -> "Error running command totvs-developer-studio.connect: Running the contributed command: 'totvs-developer-studio.connect' failed.. This is likely caused by the extension that contributes totvs-developer-studio.connect."

**Screenshots**
![Erro1](https://user-images.githubusercontent.com/39499982/86010065-4be86600-b9f1-11ea-8860-7d970f78ad0a.png)

**Expected behavior**
Conexão simultânea a pasta da rede como usuários distintos, e possibilidade de conexão a servidores em ambos os usuários

**Desktop:**
 - OS: Windows 10 - 64 bits

**Appserver:**
 - Build: Build 7.00.191205P
 - OS/Architecture: Windows Server 2016
 - Build Version: 19.3.0.4

**Additional context**
Ao que aparenta o VSCode cria um lock sobre a pasta, e mesmo quando o usuário X fechar a workspace, o usuário Y ainda assim não consegue efetuar a conexão nos servidores.

Qualquer duvida, fico a disposição para esclarecer!

**Comment by lwtnb-wrk** [comment]
@jowks Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs gerados pelos dois usuarios.
Grave tambem um video com problema se possivel, pois nao ficou muito claro o que voces estao fazendo.

**Comment by jowks** [comment]
Bom dia @lwtnb-wrk! Fui refazer os testes e após habilitar os logs, percebemos que o VSCode nao estava localizando a pasta na rede. Depois de mapear a unidade de rede, a conexão foi feita normalmente, e o VSCode está funcionando normalmente. 

Ainda precisa que envie os logs ou posso fechar a issue?

**Comment by lwtnb-wrk** [comment]
@jowks Se seu problema foi resolvido não existe problema!   ;)
