### ISSUE TITLE
Connection got Disposed

### ISSUE THREAD

**Issue by RubensCruz** [totvs/tds-vscode#422]
Boa Tarde, 
Estou recebendo o erro "Connection got Disposed" quando vou conectar no appserver do TSS fora do servidor.

**Appserver (please complete the following information):**
 - Build : 7.00.170117A - Jun 28 2019 - 11:16: 56
 - OS/Architecture: Windows 10 64 bits
 - Build Version: 17.3.0.13

**Comment by lwtnb-wrk** [comment]
@RubensCruz Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by RubensCruz** [comment]
Boa Tarde,

Segue arquivos conforme solicitado

[totvsls.log](https://github.com/totvs/tds-vscode/files/4854045/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/4854046/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/4854047/totvsls_out.log)

**Comment by lwtnb-wrk** [comment]
@RubensCruz O log não apresentou nenhum erro. Possivelmente o LS está sendo reiniciado por algum erro durante a operação.
Consegue grava um vídeo durante a ocorrencia do erro e nos enviar?
E nos envie tambem o console.log do servidor.

**Comment by RubensCruz** [comment]
[Erro VsCode.zip](https://github.com/totvs/tds-vscode/files/4854461/Erro.VsCode.zip)
[console.log](https://github.com/totvs/tds-vscode/files/4854464/console.log)

**Comment by RubensCruz** [comment]
Seguem arquivos

**Comment by lwtnb-wrk** [comment]
@RubensCruz Seu AppServer parece bastante desatualizado. Não conseguimos reproduzir o problema no AppServer atual.
Faça um backup e atualize seu AppServer para confirmar se o problema não está no AppServer desatualizado.

**Comment by lwtnb-wrk** [comment]
@RubensCruz Veja os relatos referentes ao TSS em #465
