### ISSUE TITLE
VSCODE DEBUG

### ISSUE THREAD

**Issue by AgapitoLugo** [totvs/tds-vscode#423]
estou usando o P12-25 com VSCODE , porem qdo vou debugar, F5 ele me dar uma mensagem dizendo: USER NOT AUTHENTICATED, PLEASE CONECT/RECONNECT TO SERVER, faço a conexao porem nada acontence ele da o mesmo erro

Esta é a versao do meu VSCODE:
Versão: Commit de 1.46.1 (user setup): cd9ea6488829f560dc949a8b2fb789f3cdc05f5d Data: 2020-06-17T21:13:20.174Z elétron: 7.3.1 Chrome: 78.0.3904.130 node. js: 12.8.1 V8: 7.8.279.23-electron.0 OS: Windows_NT x64 10.0.18362

**Comment by lwtnb-wrk** [comment]
@AgapitoLugo Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by AgapitoLugo** [comment]
[totvsls.log](https://github.com/totvs/tds-vscode/files/4847388/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/4847389/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/4847391/totvsls_out.log)

[dap.log](https://github.com/totvs/tds-vscode/files/4847402/dap.log)

**Comment by AgapitoLugo** [comment]
feito e enviado

**Comment by lwtnb-wrk** [comment]
@AgapitoLugo No seu caso em particular trata-se de um problema conhecido: https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#usu%C3%A1rio-com-acentua%C3%A7%C3%A3o
Por enquanto a única solução é a troca de usuário (sem acentuaçãoes).

**Comment by AgapitoLugo** [comment]
diga-me por favor, terei que desinstalar o VSCODE e instala-lo novamente

**Comment by lwtnb-wrk** [comment]
@AgapitoLugo Por enquanto você terá que usar um outro nome de usuário (que não contenha acentuação) para usar o TDS VS Code. Então sim, você terá que reinstalar o TDS VS Code neste outro usuário...

**Comment by AgapitoLugo** [comment]
poxa, vida terei que mudar meu usuario so pelo fato que o plugin da TOTVS nao aceita acentuacao, digo da TOTVS, pois instalei o VSCODE puro e ele aceitou, qdo ponho o PLUGIN , NAO FUNCIONA, sabe dizer qdo ou tem previsao de AJUSTAREM  esse problema, nao da pra mudar de usuario, por enquanto fico sem depurar NADA no VSCODE. ponho alerts , ate a TOTVS nao resolver esse pequeninissimo problema

**Comment by lwtnb-wrk** [comment]
@AgapitoLugo Realmente o problema é do plugin, mas infelizmente não é pequeninissimo como voce pode achar.
Não temos previsão para esta correção e por enquanto somente a solução paliativa.

**Comment by AgapitoLugo** [comment]
Muito agradecido e desculpe-me pelo "PEQUENINISSIMO", eu entendo que não é fácil, mas por favor veja isso, pois pegará pessoas de surpresa, veja que existem vários usuários com acentuação, andré,joão,fátima etc,etc,etc. Imagine termos que fazer um usuário apenas para debugar. é barra. Na espera de um novo plugin, agradeco.

**Comment by brodao** [comment]
Encerrado. Foi aberto chamado interno, pois envolve o servidor Protheus. Até o momento, não há previsão para correção.

**Comment by walterfcarvalho** [comment]
já peguei esse erro, mas ao reiniciar o vscode voltou a se comportar corretamente

**Comment by lwtnb-wrk** [comment]
@walterfcarvalho Seu usuário contem caracteres acentuados? Se não contiver, não se trata deste problema.
Foi realizada uma correção que será disponibilizada na próxima atualização.

**Comment by walterfcarvalho** [comment]
Desculpe , não era o caso...  vou pegar os logs na proxima vez, sei q só falar assim é de pouca ajuda

**Comment by lwtnb-wrk** [comment]
@walterfcarvalho Sem problemas. Era só para deixar claro que trata-se de um problema mesmo, e que não se resolveria com uma simples reinicialização.
De qualquer forma ela foi corrigida e será disponibilizada em breve.

**Comment by AgapitoLugo** [comment]
que maravilha, pois ate o momento estou usando o DEVELOPER STUDIO , pois nao consigo depurar, e qdo preciso compilar jogo no VS e compilo, veja que trabalhão.

________________________________
De: lwtnb-wrk <notifications@github.com>
Enviado: terça-feira, 24 de novembro de 2020 09:05
Para: totvs/tds-vscode <tds-vscode@noreply.github.com>
Cc: AgapitoLugo <lugox@hotmail.com>; Mention <mention@noreply.github.com>
Assunto: Re: [totvs/tds-vscode] VSCODE DEBUG (#423)


@walterfcarvalho<https://github.com/walterfcarvalho> Sem problemas. Era só para deixar claro que trata-se de um problema mesmo, e que não se resolveria com uma simples reinicialização.
De qualquer forma ela foi corrigida e será disponibilizada em breve.

**Comment by walterfcarvalho** [comment]
Mas estou conseguindo debugar normalmente.
Testa a questão de caracteres especiais nas pastas do projeto
Testa o acesso do vs code nas pastas do projeto.

**Comment by lwtnb-wrk** [comment]
Geramos um VSIX versão 1.2.1 que está em Pré Release (Draft) em https://github.com/totvs/tds-vscode/releases/tag/untagged-4836c4e75f678708b252
Se quiserem/puderem baixar e instalar manualmente este VSIX para avaliar se o seu problema relatado foi solucionado, favor nos informar se está corrigido ou não para que possamos realizar a liberação oficial.
Para instalar manualmente o VSIX baixem do link acima e na aba de "Extensões" do VS Code clique em "..." e selecione "Install from VSIX" e apontem para o arquivo baixado.

**Comment by walterfcarvalho** [comment]
https://github.com/totvs/tds-vscode/releases/tag/untagged-4836c4e75f678708b252   tá com erro 404 :/

**Comment by lwtnb-wrk** [comment]
@walterfcarvalho mudei o link https://github.com/totvs/tds-vscode/releases/tag/1.2.1
