### ISSUE TITLE
Erro ao gerar patch

### ISSUE THREAD

**Issue by BrunoPastri** [totvs/tds-vscode#425]
** Descreva o bug **
ola,
ao tentar gerar um arquivo .ptm esta dando erro no VScode

**Reproduzir**
- coloquei em modo exclusivo
- abro o vscode, conecto em meu ambiente de teste.
- clico com o botao direito do mouse em cima do servidor e depois vou na opção patch generation (from RPO)
- neste momento da um erro "Could not retrieve objects list from rpo"

**Comportamento esperado**
teria que trazer a lista de fontes, onde eu iria selecionar o meu customizado e exportar para .ptm

** Capturas de tela **
![vscode](https://user-images.githubusercontent.com/67703807/86270848-48481100-bba2-11ea-9fea-1cff2a40ea66.png)

** Desktop (preencha as seguintes informações): **
 - windows 10 home / arquitetura: 64 bits

** Appserver (preencha as seguintes informações): **
Build AppServer: 7.00.191205P-20200424 - 64 bits
Appserver version: 19.3.0.4
Build DBAccess: 20191119-20200217
Release do RPO:  12.1.027
Release do dicionário: 12.1.027
Local files: ctree
License server: 2014 - 3.0.2
DB DataBase: MSSQL
DB API Build: 20191119-20200116

** Contexto adicional **
observado que após o erro, o serviço acesso exclusivo é desativado sozinho.
nosso sistema esta na cloud da totvs

**Comment by lwtnb-wrk** [comment]
@BrunoPastri É um problema nesta versãp 19.3.0.4 do AppServer mesmo. Pelo que sei, a versão 19.3.0.5 trará a correção para o problema.

Como paliativo experimente desfragmentar seu RPO.

Não há nada que possamos fazer no tds-vscode para resolver este problema no AppServer.
