### ISSUE TITLE
Erro de Conexao Servidor

### ISSUE THREAD

**Issue by Miqueiasfer** [totvs/tds-vscode#426]
Estou com o seguinte erro quando instalo a extensão:

The TOTVS AdvPL Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

Ja apaguei as pastas .totvsls e .vscode, mas nao resolveu o problema

**Comment by lwtnb-wrk** [comment]
@Miqueiasfer Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.
De mais detalhes tambem do seu ambiente e do AppServer que voce esta se conectado, como versão, build, SO, etc

**Comment by maurorajr** [comment]
![image](https://user-images.githubusercontent.com/41392660/86493656-b62e3d00-bd48-11ea-9b30-9f5e61973f16.png)
![image](https://user-images.githubusercontent.com/41392660/86493712-f1307080-bd48-11ea-9dca-6e3251439fb7.png)
Clique com direito na raiz da sua árvores de servidores desejado, conforme imagem acima e posteriormente clique em configure server view;

Veja abaixo um exemplo da minha configuração de arquivo server.json e compare com a sua:
{
	"version": "0.2.0",
	"includes": [
		"C:\\INCLUDE"
	],
	"permissions": {
		"authorizationtoken": ""
	},	
	"configurations": [		
		{
			"id": "OCULTO_INFO_PESSOAL",
			"type": "totvs_server_protheus",
			"name": "P12_PRODUC_SLV6",
			"port": 10007,
			"address": "172.16.0.109",
			"buildVersion": "7.00.191205P",
			"secure": 0,
			"includes": [
				"I:\\"
			],
			"environments": [
				"PRODUC"
			],
			"environment": "PRODUC",
			"username": "OCULTO_INFO_PESSOAL"
		}
	],
	"savedTokens": [
		
		[
			"OCULTO_INFO_PESSOAL:PRODUC",
			{
				"id": "OCULTO_INFO_PESSOAL",
				"token": "OCULTO_INFO_PESSOAL=:OCULTO_INFO_PESSOAL=|OCULTO_INFO_PESSOAL==.OCULTO_INFO_PESSOAL+OCULTO_INFO_PESSOAL/dPuAEI/OCULTO_INFO_PESSOAL+OCULTO_INFO_PESSOAL/OCULTO_INFO_PESSOAL+OCULTO_INFO_PESSOAL+OCULTO_INFO_PESSOAL/OCULTO_INFO_PESSOAL+OCULTO_INFO_PESSOAL+OCULTO_INFO_PESSOAL+OCULTO_INFO_PESSOAL+OCULTO_INFO_PESSOAL/OCULTO_INFO_PESSOAL=="
			}
		]		
	]
}

Outra observação:
Dedique um ambiente no appserver com uma porta exclusiva somente para os ambientes que deseja configurar no VSCode.
Como temos balance aqui na empresa que vai até o slave6, criamos um sétimo com porta de final 10007 e dedicamos somente para configuração no vscode devido necessidade de ativar o multiprotocol, veja abaixo:

[PRODUC]
SourcePath=OCULTO_INFO_PESSOAL
RootPath=OCULTO_INFO_PESSOAL
StartPath=\system\
x2_path=
RpoDb=Top
RpoLanguage=portuguese
RpoVersion=120
LocalFiles=CTREE
Trace=0
localdbextension=.dtc
TopMemoMega=1
PictFormat=DEFAULT
DateFormat=DEFAULT
RegionalLanguage=BRA
helpserver=OCULTO_INFO_PESSOAL
DBDataBase=MSSQL
DBServer=OCULTO_INFO_PESSOAL
DBALIAS=OCULTO_INFO_PESSOAL
PROTHEUSONLY=0
THEME=Standard
CrwStartPath=OCULTO_INFO_PESSOAL
SpecialKey=OCULTO_INFO_PESSOAL

[Drivers]
Active=TCP
MultiProtocolPortSecure=0
MultiProtocolPort=0

[TCP]
TYPE=TCPIP
Port=10007
