### ISSUE TITLE
Inspetor de Objetos Não Carrega Informações

### ISSUE THREAD

**Issue by josepaulosjc** [totvs/tds-vscode#428]
Estou com problemas para realizar a inspeção de objetos, ao conectar eu clico com o direito do mouse e vou em 'Objects Inspector', depois na janela ao lado eu coloco um filtro qualquer (MAT ou * ). Nesse momento o inspetor de objetos começa a carregar sem parar, não trazendo o resultado esperado, como se estivesse em Loop.

Informações de Software:
Version: 1.46.1
Date: 2020-06-17T21:13:08.304Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.15.0-109-generic

Dados do Server ::
Versão: TOTVS Serviços
Build AppServer: 7.00.191205P-20200424 - 64 bits
Appserver version: 19.3.0.4
Build DBAccess: 20181212-20191121
Release do RPO:  12.1.025
Release do dicionário: 12.1.025
Local files: CTREE
License server: 2014 - 2.4.14
DB DataBase: MSSQL
DB API Build: 20191119-20200116

**Comment by lwtnb-wrk** [comment]
Mesmo problema da #415
