### ISSUE TITLE
Erro no Inspetor de Objetos 

### ISSUE THREAD

**Issue by chrystian-matos** [totvs/tds-vscode#429]
Bom dia,
Ao tentar executar o inspetor de objetos no VS Code o sistema apresenta a mensagem "Could not retrieve objects list from RPO", e não exibe a lista de objetos do RPO.

Estou encaminhando a mensagem e versão do appserver, porém caso seja necessário posso enviar novas evidências .

![appserver](https://user-images.githubusercontent.com/67906209/86592842-8eb6ba80-bf6a-11ea-8e74-6d8e925af0e6.png)
![Capturar](https://user-images.githubusercontent.com/67906209/86592872-9aa27c80-bf6a-11ea-91fb-b9f095467333.PNG)

**Comment by lwtnb-wrk** [comment]
@chrystian-matos veja #415
