### ISSUE TITLE
Breakpoint não funciona no VSCode

### ISSUE THREAD

**Issue by danielblaia** [totvs/tds-vscode#430]
Bom dia,
Estou usando Protheus 12.1.25 Build 191205P.
estou com uma situação bastante incomum. O debug (F5) não está parando onde deve, nos breakpoints.
Já removi os fontes do RPO e compilei novamente.
Já removi todos os breakpoints e adicionei novamente.
Mas não está parando onde deve. No exemplo da foto, está parando no metodo CreateBarCode quando na verdade na pilha de chamadas está no NextNossoNumero

como resolver pra parar no lugar correto?

agradeço qualquer ajuda.

obrigado
![erro_vscode](https://user-images.githubusercontent.com/41373250/86600089-ef97c000-bf75-11ea-9c28-23a4861be5c4.png)

**Comment by lwtnb-wrk** [comment]
@danielblaia Geralmente isso realmente ocorre quando o fonte compilado e o encontrado pelo editor não estão em sincronia.
A pilha de chamada esta sendo enviada pelo Appserver e provavelmente é o correto.
Veja se realmente o fonte foi compilado corretamente no ambiente/appserver que está sendo depurado.
Também veja se não existe outro fonte com o mesmo nome "tcBoleto.prw" nas pastas de trabalho que estão abertas no TDS VS Code. O VS Code abre o 1o que encontrar e pode ser o incorreto.
Se ainda assim não identificar o que está ocorrendo, veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para análise.

**Comment by danielblaia** [comment]
oi,
então eu removi e compilei novamente todos os fontes
Segue dap.log em anexo
obrigado
[dap.log](https://github.com/totvs/tds-vscode/files/4879508/dap.log)

**Comment by lwtnb-wrk** [comment]
@danielblaia Pode nos enviar esse fonte tcBoleto.prw para analisarmos?
E tambem ligue a opção "Generate Ppo Files" nas preferencias e realize a compilação novamente.
Envie os logs gerais e tambem o arquivo Ppo gerado.

**Comment by DanielYampolschi** [comment]
Ola @danielblaia , olhei o log que você mandou e o VsCode esta reproduzindo corretamente o que foi informado pelo usuário e pelo servidor:

1 - Primeiro é setado um breakpoint na linha 794 (Conforme inclusive mostra a sua imagem):

`[{"column":1452541885,"endcolumn":545,"endline":-711242432,"line":794,"source":{"name":"tcBoleto.prw","path":"c:\\TOTVS\\VSCODE\\CATIVA_SVN\\Cativa lojas\\Tcsmart\\tcBoleto.prw"},"verified":true}]`

2 - Quando a execução para nessa linha, o plugin tds-vscode recebe as informações do servidor e envia para exibição:

`"stackFrames":[{"column":0,"id":9,"line":794,"name":"NEXTNOSSONUMERO","source":{"adapterData":"advpl-adapter-data","name":"TCBOLETO.PRW","path":"C:/TOTVS/VSCODE/CATIVA_SVN/Cativa lojas/Tcsmart/tcBoleto.prw"}}]`

Repare que as informações de linha e fonte são recebidas conforme mostra o seu print, porem o campo "name" do stack vem com o NEXTNOSSONUMERO e não com o nome da função. Isso pode acontecer, como o Leo comentou por falta de sincronismo do fonte (porem como você informa que já removeu e compilou novamente não parece ser esse o problema) ou pode ser algum problema no servidor que está enviando informações erradas.  

Informe (Como na imagem abaixo) qual a build do servidor que você esta usando por favor.

![image](https://user-images.githubusercontent.com/10711513/86620484-c5083000-bf92-11ea-9ece-a48645f0ec6b.png)

Se possível, tente compilar esse programa em outra versão de servidor e verifique se o problema ainda continua.

Verifique também por favor se o seu fonte realmente foi compilado, por exemplo, adicione logo antes da linha onde faz a parada um conout("teste") por exemplo e verifique se a informação aparece no console do servidor.

**Comment by danielblaia** [comment]
boa tarde,
desinstalei o vs code e instalei novamente, erro prossegue: não para no breakpoint
Build:
* TOTVS - Build 7.00.191205P - Apr 24 2020 - 14:30:50 
* Build: 64 bits
* SVN Revision: 26664
* Build Version: 19.3.0.4

Executei com os conout e ele rodou todos, mas não parou em lugar nenhum, e estavam habilitados

em anexo os logs e os fontes, o tcboleto.prw e o tcbco756.prw


[totvsls_out.log](https://github.com/totvs/tds-vscode/files/4880527/totvsls_out.log)s lo
[Uploading dap.log…]
[totvsls.log](https://github.com/totvs/tds-vscode/files/4880529/totvsls.log)



[totvsls_in.log](https://github.com/totvs/tds-vscode/files/4880526/totvsls_in.log)

**Comment by danielblaia** [comment]
acho que alguns anexos não foram
segue

[Tcsmart.zip](https://github.com/totvs/tds-vscode/files/4880535/Tcsmart.zip)
[dap.log](https://github.com/totvs/tds-vscode/files/4880537/dap.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/4880538/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/4880539/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/4880540/totvsls_out.log)

**Comment by lwtnb-wrk** [comment]
@danielblaia Conforme falamos por outro canal o problema esta uso do freeObj(self) dentro do tcBoleto.prw.
Por algum motivo ainda desconhecido a compilação com essa chamada causa uma diferença no número de linhas compiladas ocasionando esse "dessincronismo" percebido na depuração.
Por enquanto sugerimos comentar a chamada ao freeObj(self) ate que isso seja resolvido pela area responsavel.
Do lado do tds-vscode nada pode ser feito então esta issue será fechada.
