### ISSUE TITLE
Agrupamento de ambientes

### ISSUE THREAD

**Issue by rodrigomorgon** [totvs/tds-vscode#431]
Melhoria: Permitir agrupar os ambientes de conexão por projeto/cliente

**Comment by lwtnb-wrk** [comment]
@rodrigomorgon Descreva melhor a melhoria sugerida. 
De preferencia coloque "printscreen" de como é atualmente e como seria com a melhoria.
Também é possível você mesmo implementar e submeter um Pull Request para que possamos analisar e incorporar ao tds-vscode.

**Comment by MistralTecnologia** [comment]
Boa tarde pessoal, essa funcionalidade traz segurança e praticidade para quem está no cliente implantando. Segue uma visão de como entendo o básico dessa feature. Poderiamos cadastrar por cliente ou ainda por cliente/base.

![sample - vscode](https://user-images.githubusercontent.com/34134900/87580688-4015c880-c6ae-11ea-875c-d88912230482.png)

**Comment by brodao** [comment]
@rodrigomorgon 

Veja se [Local de Gravação](https://github.com/totvs/tds-vscode/blob/master/docs/servers.md#local-de-grava%C3%A7%C3%A3ol) atende a sua necessidade. Você passaria a gravar as definições por área de trabalho.

A disposição.
