### ISSUE TITLE
Acentuação no VSCode

### ISSUE THREAD

**Issue by Miqueiasfer** [totvs/tds-vscode#432]
Ao Abrir os fontes no VScode ele não consegue interpretar os acentos

![image](https://user-images.githubusercontent.com/66267539/86932105-4c7aae00-c10f-11ea-9b10-b7f4fd2cc133.png)

**Comment by lwtnb-wrk** [comment]
@Miqueiasfer Pela imagem vemos que o encoding utilizado é o correto para o AdvPL, que é o Windows 1252 (cp1252) então o mais provável é que o arquivo esteja com toda sua acentuação "corrompida" pela utilizações neste e/ou em outros editores.
Suspeito, pela imagem, que o encoding do arquivo deva ser o UTF-8, então experimente clicar em "Windows 1252" na barra inferior do TDS VS Code e utilize a opção "Reopen with encoding" e selecione UTF-8. 
Se a acentuação aparecer correta significa que o arquivo foi salvo anteriormente com o encoding UTF-8 mas aberto com o encoding Windows 1252 e por isso aparece incorretamente. E neste caso clique novamente em UFT-8 e utilize a opção "Save with encoding" e selecione Windows 1252. Ao abri-lo novamente ele deve aparecer corretamente.
Se não for o caso no envie este arquivo "MT100LOK.PRW" para que possamos dar uma olhada nele.

**Comment by Miqueiasfer** [comment]
como UTF-8 fica como abaixo:

![image](https://user-images.githubusercontent.com/66267539/86947437-2a3e5b80-c122-11ea-8984-cf5d8fe63d90.png)

**Comment by Miqueiasfer** [comment]
abrindo o prw no bloco de notas vejo que ele ja ta salvo com caracteres estranhos. Se pego um arquivo de backup que tenho aqui ta normal. O que deu pra perceber que no bloco de notas reconhece um com padrao ANSI e o como UTF-8 

![image](https://user-images.githubusercontent.com/66267539/86948233-3a0a6f80-c123-11ea-976d-07fb37cefafd.png)

**Comment by lwtnb-wrk** [comment]
@Miqueiasfer Então realmente o arquivo PRW está com seu encoding "corrompido" e não há nada que possa ser feito no TDS VS Code. Isso ocorre ao abrir um arquivo com o encoding incorreto e salvá-lo com outro encoding e assim por diante.
Quanto ao BAK, o encoding ANSI e o Windows 1252 são praticamente o mesmo com muita pouca diferença então se renomeá-lo como PRW e abrí-lo no TDS VS Code provavelmente você terá toda a acentuação correta.
A informação de encoding não fica "gravada" no arquivo e é responsabilidade do usuário informar o encoding do arquivo ao abrí-lo. Por padrão os arquivos AdvPL são abertos com o encoding Windows 1252, então se editá-lo em outro lugar com o encoding UTF-8 certamente ele vai apresentar caracteres estranhos ao abrí-lo com o Windows 1252.
Como não há nada que possa ser feito no TDS VS Code vamos fechar esta issue.
Mas se puder nos envie esse arquivo PRW "corrompido" apenas para nosso conhecimento.
