### ISSUE TITLE
erro ao gerar Totvs generate ws protheus

### ISSUE THREAD

**Issue by BrunoPastri** [totvs/tds-vscode#433]
**Describe the bug**
estou tentando aplicar um serviço mas esta retornando um erro

**To Reproduce**
conecto worflow em minha base de teste
pressiono CTRL + SHIFT + P
- seleciono: Totvs generate ws protheus
- preencho com a url do ws
seleciono uma pasta para salvar o arquivo
-nome arquivo.prw
- clico em salvar e fechar
- mensagem de erro: WSCERR066 / INVALID WSDL Content-Type (Content-type: text/html) from http://rimaturtransportes104113.protheus.cloudtotvs.com.br:8300/ws/
ADVPL WSDL Client 1.120703 / TOTVS Servi�os Testewf on 20200708 13:13:57

**Desktop (please complete the following information):**
 - windows 10 home

**Appserver (please complete the following information):**
Versão: TOTVS Serviços
Build AppServer: 7.00.191205P-20200424 - 64 bits
Appserver version: 19.3.0.4
Build DBAccess: 20191119-20200217
Release do RPO:  12.1.027
Release do dicionário: 12.1.027
Local files: ctree
License server: 2014 - 3.0.2
DB DataBase: MSSQL
DB API Build: 20191119-20200116

**Additional context**
nosso protheus esta no cloud da totvs

**Comment by lwtnb-wrk** [comment]
@BrunoPastri Você está tentando gerar o client direto com a URL http://rimaturtransportes104113.protheus.cloudtotvs.com.br:8300/ws/ ???
Esta URL é somente uma página HTML (Content-type: text/html) com a descrição de todos os Web Services que existem neste servidor.
Você deve gerar o client de um dos serviços como por exemplo o primeiro item "ANALISAREC" nele você encontra o WSDL necessário para gerar o client
http://rimaturtransportes104113.protheus.cloudtotvs.com.br:8300/ws/ANALISAREC.apw?WSDL
Utilize esta URL para gerar o client e será necessário gerar um client por serviço que quiser utilizar.

**Comment by brodao** [comment]
Ola @BrunoPastri 

Em complemento ao @leowww, é requisisto que o servidor no qual o TDS esta conectado, tenha acesso a URL do serviço.

A disposção.
