### ISSUE TITLE
Erro ao adicionar Servidor

### ISSUE THREAD

**Issue by PierryGuedes** [totvs/tds-vscode#434]
** Erro ao adicionar servidor **

Mensagem: Cannot read property 'id' of undefined

Versão: 1.0.5
![ErroVsCodeTOTVS](https://user-images.githubusercontent.com/44071912/87076602-5d531e80-c1f8-11ea-9472-c5859265da4b.png)

**Comment by lwtnb-wrk** [comment]
@PierryGuedes Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#erro-ao-adicionar-servidores como voce pode resolver este probema.
Se ainda assim nao conseguir resolve-lo veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by Allyson90** [comment]
Estou com o mesmo problema, não conecta mais em nenhum servidor, não cria servidor novo, não aplica patch. Tive que voltar para a versão 1.0.3

**Comment by jeanrehermann** [comment]
Problema relatado por diversos clientes, também aconteceu comigo. Não é problema no servers.json, pois o mesmo está íntegro, com dados e sintaxe correta. Mesmo assim na lista de servidores não aparece nenhum. Também procedi com o downgrade, na minha instalação e na instalação de clientes. É problema na versão, terá que ser revisada.

**Comment by thiagosdealmeida** [comment]
Boa tarde, também estou com o mesmo problema, já reinstalei tudo e nada.

**Comment by DanielYampolschi** [comment]
Ola pessoal, estamos cientes e a equipe toda ja esta olhando esses problemas. Ainda nao conseguimos reproduzir, peço um teste, antes de tentar uma conexao, abram um fonte .prw qualquer e informe se após isso é possível conectar. Obrigado.

**Comment by PierryGuedes** [comment]
> @PierryGuedes Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#erro-ao-adicionar-servidores como voce pode resolver este probema.
> Se ainda assim nao conseguir resolve-lo veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

Já havia verificado essa questão do arquivo Json, esse meu problema ocorreu em uma instalação nova do VsCode, portanto o arquivo servers.json estava sem dados, verifiquei a questão da vírgula também, não influenciou em nada.

**Comment by thiagosdealmeida** [comment]
> @PierryGuedes Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#erro-ao-adicionar-servidores como voce pode resolver este probema.
> Se ainda assim nao conseguir resolve-lo veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

Segue os logs para analise. 

[totvsls.log](https://github.com/totvs/tds-vscode/files/4899369/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/4899370/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/4899371/totvsls_out.log)

**Comment by DanielYampolschi** [comment]
Pessoal, encontramos um problema na identificação do arquivo servers.json, peço pra adicionarem a seguinte instrução no arquivo servers.json localizado na area do usuario do sistema operacional, pasta .totvsls.

"lastConnectedServer": ""

Obs.: Reparem que o valor do lastConnectedServer nesse caso é uma string ("") e não um objeto ({})

Adicionar essa instrução logo após a ultima, não esquecendo de colocar a virgula, segue abaixo um exemplo de arquivo servers.json inicial:

{
	"version": "0.2.0",
	"includes": [
		""
	],
	"permissions": {
		"authorizationtoken": ""
	},
	"connectedServer": {},
	"configurations": [
		{
			"id": "qzz0te605nskcfa7wuxmfutce0fbxs",
			"type": "totvs_server_protheus",
			"name": "teste",
			"port": 1219,
			"address": "localhost",
			"buildVersion": "7.00.191205P",
			"secure": true,
			"includes": []
		}
	],
	"savedTokens": [],
	"lastConnectedServer": ""
}

**Comment by jeanrehermann** [comment]
Reinstalei a última versão e segui o passo indicado acima. Agora está funcionando normalmente.

Obrigado.

**Comment by PierryGuedes** [comment]
> "savedTokens": [],
> "lastConnectedServer": ""

Resolveu pra mim com esse procedimento, vou deixar a issue aberta por mais um dia, pra ver se resolve da mesma forma pra todo mundo.

**Comment by RegisNJr** [comment]
Bom dia, aqui também perdemos toda configuração, instalamos a Extensão novamente
aí criou um arquivo servers novo que parou em configurations[]} aí resolvemos com a dica acima de inserir
,"savedTokens": [],
"lastConnectedServer": ""

Agora conseguimos reconfigurar o Server com dar o erro 'id'

{
"version": "0.2.0",
"includes": [
""
],
"permissions": {
"authorizationtoken": ""
},
"connectedServer": {},
"configurations": []**,
"savedTokens": [],
"lastConnectedServer": ""**
}

**Comment by gignan** [comment]
Como posso efetuar o downgrade para versão 1.0.3? conforme mencionado acima ?

**Comment by RegisNJr** [comment]
> Como posso efetuar o downgrade para versão 1.0.3? conforme mencionado acima ?

@gignan nesse link tem a dica como voltar a versão https://github.com/totvs/tds-vscode/issues/440#issuecomment-656676304

**Comment by gignan** [comment]
> > Como posso efetuar o downgrade para versão 1.0.3? conforme mencionado acima ?
> 
> @gignan nesse link tem a dica como voltar a versão [#440 (comment)](https://github.com/totvs/tds-vscode/issues/440#issuecomment-656676304)

Muito obrigado RegisNJr, funcionou com o Downgrade da Versão para 1.0.3 !!!!

**Comment by lwtnb-wrk** [comment]
versão 1.0.6 liberada
