### ISSUE TITLE
Problema ao conectar em qualquer servidor

### ISSUE THREAD

**Issue by CaioKretzer** [totvs/tds-vscode#435]
Ao tentar a conexão em qualquer servidor aparece a mensagem de sucesso na conexão, mas o servidor não fica "verde" como quando está conectado.

![image](https://user-images.githubusercontent.com/51425152/87076845-ad31e580-c1f8-11ea-9911-f6bcf9616e19.png)

Após fechar o VSCode e abrir de novo, todos os servidores somem e aparece a mensagem "Cannot read property 'id' of undefined".

Ao abrir o arquivo "servers.json", não existe mais o "lastConnectedServer":{}.
Ao adicionar o "lastConnectedServer":{} no arquivo, os servidores carregam.
Mas se eu tento conectar acontece o mesmo problema.

O erro acontece em qualquer servidor.

Estou rodando via WSL: Ubuntu 18.04

**Comment by Allyson90** [comment]
Estou com o mesmo problema, não conecta mais em nenhum servidor, não cria servidor novo, não aplica patch. Tive que voltar para a versão 1.0.3

**Comment by CaioKretzer** [comment]
Obrigado Allyson. Aqui funcionou voltando a versão também.

**Comment by lwtnb-wrk** [comment]
@CaioKretzer @Allyson90 Ao inves de "lastConnectedServer": {} adicione um "lastConnectedServer": "" no servers.json que por enquanto resolverá este problema.

**Comment by lwtnb-wrk** [comment]
Relacionado ao #434

**Comment by SergioLuiz1367** [comment]
Como voltar com a versão 1.0.3
