### ISSUE TITLE
SmartClient não inicia pelo F5 ou Crtl+F5 (server = / porta= 65535)

### ISSUE THREAD

**Issue by jvvasquesn** [totvs/tds-vscode#436]
**Describe the bug**
SmartClient não inicia pelo F5 ou Crtl+F5 e da a mensagem da imagem

**Screenshots**
![image](https://user-images.githubusercontent.com/55854184/87082191-da29cc80-c1e7-11ea-83a3-3693f39ca7ac.png)

**Desktop (please complete the following information):**
 - Ubuntu 18 64

**Appserver (please complete the following information):**
"buildVersion": "7.00.170117A",
			"secure": 0,

**Comment by lwtnb-wrk** [comment]
@jvvasquesn Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise

**Comment by DanielYampolschi** [comment]
bom dia @jvvasquesn por favor tente a solução informada no post abaixo, se nao funcionar nos envie os logs conforme o Leo orientou acima.

https://github.com/totvs/tds-vscode/issues/434#issuecomment-656352291

Obrigado.

**Comment by jvvasquesn** [comment]
Bom dia.
@DanielYampolschi  não resolveu
@lwtnb-wrk os arquivos "totvsls.log", "totvsls_in.log" e "totvsls_out.log" não foram gerados

Segue o dap.log

[dap.log](https://github.com/totvs/tds-vscode/files/4903785/dap.log)

**Comment by lwtnb-wrk** [comment]
@jvvasquesn Aparentemente o processo de execução do smartclient não está conseguindo criar a seção "temporária"

Veja a seção abaixo existe em seu smartclient.ini e se não existir verifique se as configurações de escritas estão aberta para o mesmo usuário que executa o tds-vscode.

Em último caso experimente adicionar manualmente esta informação e veja se consegue debugar.

[_DBG_TEMP]
server=192.168.0.16
port=1299
SecureConnection=1

**Comment by jvvasquesn** [comment]
@lwtnb-wrk as permissões estão ok
![image](https://user-images.githubusercontent.com/55854184/87204296-b470f600-c2c1-11ea-8cc9-6c41bdb432d1.png)

Se colocar manualmente da certo, o problema é que vou ter que ter um smartclient para cada cliente.

**Comment by DanielYampolschi** [comment]
bom dia @jvvasquesn , como teu SO é linux, te peço um teste por favor:

No caminho do seu executavel do smartclient, tem uma pasta com letra maiuscula ("/SmartClient..."), acontece que o servidor e o proprio smartclient tem problemas em ambiente linux quando isso acontece (E nao tem nada que a IDE possa fazer para corrigir isso). 

Por favor teste novamente renomeando para "/smartclient..." e veja se funciona...

**Comment by alanFaccin** [comment]
Bom dia, uso sistema operacional MAC OS e também tive o mesmo problema ao tentar iniciar pelo F5 ou Crtl+F5 apresenta o seguinte erro abaixo:

![Captura de Tela 2020-07-13 às 10 30 54](https://user-images.githubusercontent.com/9438826/87310424-5415ca80-c4f4-11ea-91b6-5b44647d4ef4.png)

Minha configuração é a seguinte:

![Captura de Tela 2020-07-13 às 10 33 14](https://user-images.githubusercontent.com/9438826/87310408-4fe9ad00-c4f4-11ea-97c8-19504d01de7a.png)

Notei o seguinte no meu caso um smartclient.ini está sendo criado no diretório /Applications com o conteúdo temporário para a execução. 

![Captura de Tela 2020-07-13 às 10 38 36](https://user-images.githubusercontent.com/9438826/87311029-1bc2bc00-c4f5-11ea-92eb-221da1ffad5b.png)

Sendo que o correto neste caso seria adicionar dentro do arquivo /Applications/smartclient.app/Contents/MacOS/smartclient.ini que é onde o smart cliente busca os dados, por isso não encontra na hora da execução. 

Obs: se adicionar manualmente o conteúdo para para execução temporária gerado dentro do smartclient.ini correto (/Applications/smartclient.app/Contents/MacOS/smartclient.ini) ele abre normalmente.

**Comment by lwtnb-wrk** [comment]
@alanFaccin Como não tenho um Mac OSX para testar eu não sei como é a estrutura do arquivos e diretórios do Smartclient no Mac.
Pergunta: Em "/Applications/smartclient.app/Contents/MacOS/" existe o executável do smartclient, provavelmente "/Applications/smartclient.app/Contents/MacOS/smartclient"?
Se houver poderia trocar no launch.json a configuração de "smartclientBin" para "/Applications/smartclient.app/Contents/MacOS/smartclient" e testar novamente?

**Comment by lwtnb-wrk** [comment]
> @lwtnb-wrk as permissões estão ok
> ![image](https://user-images.githubusercontent.com/55854184/87204296-b470f600-c2c1-11ea-8cc9-6c41bdb432d1.png)
> 
> Se colocar manualmente da certo, o problema é que vou ter que ter um smartclient para cada cliente.

@jvvasquesn Alem das permissoes do diretorio, voce verificou tambem as permissoes do arquivo "smartclient.ini" ?
Conseguiu tambem testar a questao do case "Smartclient" vs "smartclient" ?

**Comment by jvvasquesn** [comment]
> bom dia @jvvasquesn , como teu SO é linux, te peço um teste por favor:
> 
> No caminho do seu executavel do smartclient, tem uma pasta com letra maiuscula ("/SmartClient..."), acontece que o servidor e o proprio smartclient tem problemas em ambiente linux quando isso acontece (E nao tem nada que a IDE possa fazer para corrigir isso).
> 
> Por favor teste novamente renomeando para "/smartclient..." e veja se funciona...



Deu certo colocando tudo minusculo. Obrigado!

**Comment by emebatista** [comment]
Deu certo para mim no MacOS a dica de trocar

"/Applications/smartclient.app/Contents/MacOS/"
por 
"/Applications/smartclient.app/Contents/MacOS/smartclient"

Valeu @lwtnb-wrk

**Comment by emebatista** [comment]
Corrigindo o comentário
Troquei 
"/Applications/smartclient.app"
por
"/Applications/smartclient.app/Contents/MacOS/smartclient"

Valeu @lwtnb-wrk

**Comment by lwtnb-wrk** [comment]
Resumindo a questão do problema relatado para Linux e Mac na configuração "smartclientBin":

No Linux certifique-se de que todo o caminho esteja escrito com caracteres minúsculos.
- troque "/home/user/TOTVS/Smartclient/built123/smartclient"
- por "/home/user/totvs/smartclient/built123/smartclient"

No Mac não aponte para o ".app":
- ao inves de "/Applications/smartclient.app"
- utilize "/Applications/smartclient.app/Contents/MacOS/smartclient"

Grato @jvvasquesn e @emebatista pelos testes e feedbacks.
