### ISSUE TITLE
Extensão trava ao compilar vários fontes

### ISSUE THREAD

**Issue by rodrigomorgon** [totvs/tds-vscode#437]
Olá pessoal, com o último update a extensão passou a travar quando compilo uma pasta que tenha muitos fontes, acredito que esteja relacionado ao efeito visual dos alerts de compilação que foram alterados nessa versão.

Na versão anterior era compilado rapidamente e os popups não eram exibidos

Segue imagem com o problema. Após alguns minutos o Vscode exibe um alert informando que não está respondendo, com opção para continuar aguardando e fechar/cancelar

![image](https://user-images.githubusercontent.com/5922672/87084390-88436f80-c204-11ea-8d82-0cb27f622e2d.png)

Versão 1.0.5

**Comment by brodao** [comment]
Ola @rodrigomorgon 

Nos "settings", tem um opção para não apresentar avisos vindos do server. Ajuste-a e veja se resolve.
Acesso File | Preferences | Settings | Extensions | TOTVS | totvsLanguageServer.editor.show.notification

Aguardo retorno.

**Comment by lwtnb-wrk** [comment]
@rodrigomorgon Eu fiz uns testes aqui e pelo que vi o problema esta na atualização do VS Code e não da extensão.
Mesmo com a extensão 1.0.5 fiz uma compilação com mais de 100 arquivos e as notificações apareceram corretamente, mas isso com a versão 1.44.2 do VS Code...

**Comment by lwtnb-wrk** [comment]
Somente complementando a dica do @brodao 
Em "Show: Notification" mude a opção para "errors and warnings" (por padrão deve ser "error warnings and infos")

**Comment by lwtnb-wrk** [comment]
Mudaremos o padrão em "Show: Notification" para "none" por enquanto para evitar o travamento.
