### ISSUE TITLE
Compilar Arquivos .TRES

### ISSUE THREAD

**Issue by jonermarcelo** [totvs/tds-vscode#438]
Olá,

Pessoal, ao trabalhar com o desenvolvimento ADVPL, utilizamos inclues com arquivos de idiomas que possuem extensão .TRES.

Ocorre que, ao alterar um arquivo .TRES já compilado no RPO, caso eu modifique o mesmo e compile, não ocorre nenhum erro, só que as alterações não estão no RPO.

A única forma neste caso, é voltar um backup do RPO que não contenha o arquivo .TRES compilar e desta forma compilar novamente.

**Comment by lwtnb-wrk** [comment]
@jonermarcelo Fiz um teste e já entendi o que está ocorrendo.
Os arquivos TRES são "resources" compilados no RPO que ao serem lidos (utilizados) são "cacheados" no AppServer.
Ao compilar uma alteração no TRES o mesmo vai para RPO mas o "cache" não é alterado.
Então enquanto o AppServer não for reiniciado, as alterações não serão visíveis pelos programas que o utilizam.
Após compilar uma alteração no arquivo TRES reinicie o AppServer e veja que isso deve resolver o seu problema.

**Comment by jonermarcelo** [comment]
@lwtnb-wrk irei realizar o teste conforme solicitou e lhe posiciono.

Mas sendo o cenário conforme descreveu, acredita que caberia uma verificação com à área de frame à respeito? O que recomenda neste sentido?

**Comment by lwtnb-wrk** [comment]
@jonermarcelo Sinceramente não sei se isso seria com o Frame ou com o time do AppServer.
Eu acho que faria sentido algum esquema que percebesse durante a compilacao de um TRES que o cache deveria ser invalidado

**Comment by jonermarcelo** [comment]
@lwtnb-wrk, tudo bem?

Estive verificando à questão que você reportou e é exatamente isto que acontece. Ou seja, ao iniciar o AppServer o mesmo carrega em memória as definições dos arquivos .TRES presentes no RPO, visando questões de desempenho. Desta forma, à atualização das informações ocorre somente à partir da reinicialização do ambiente.

Validamos estas informações através do ticket 9377749 junto à área de framework do ERP Protheus. 

Diante disto, acredito que está ISSUE possa ser finalizada.

Abraços,
MARCELO JONER

**Comment by lwtnb-wrk** [comment]
@jonermarcelo Grato pelas informações.
Realmente pelos meus testes não havia nada que o tds-vscode poderia fazer para resolver esta questão.
