### ISSUE TITLE
Configuração dos Server sumiu , mas servers.json está preenchido 

### ISSUE THREAD

**Issue by SergioLuiz1367** [totvs/tds-vscode#439]
Os servers não estão mais na guia , mas o servers.jso esta preenchido

**Comment by CaioKretzer** [comment]
A versão 1.0.5 aparentemente está com problema. Consegui voltando para a 1.0.3

**Comment by lwtnb-wrk** [comment]
@SergioLuiz1367 veja a issue #435

**Comment by lwtnb-wrk** [comment]
Ops a primeira issue foi a #434
