### ISSUE TITLE
Adicionar servidores no monitor

### ISSUE THREAD

**Issue by Smmartinez** [totvs/tds-vscode#44]
Boa tarde! Permitir que o Server seja adicionado no Monitor sem a necessidade de ter que cadastrar ele, assim como ocorre no TDS hoje, onde ele adiciona ao monitoramento escolhendo essa opção.

**Comment by matheus-sales** [comment]
Olá Sérgio.

O plugin do monitor é separado desse plugin, então as questões do monitor devem ser tratados no plugin do monitor: https://github.com/totvs/tds-monitor

**Comment by Smmartinez** [comment]
Obrigado Matheus!
