### ISSUE TITLE
Compilação de diretório

### ISSUE THREAD

**Issue by thiagomeschiatti** [totvs/tds-vscode#441]
Ao compilar um projeto/diretório com muitos fontes envolvidos acontece o erro da imagem.
Depois de um longo tempo a janela de resultado de compilação é aberta.

![image](https://user-images.githubusercontent.com/17277863/87154200-3136ac80-c28f-11ea-8ab4-693da648210a.png)

![image](https://user-images.githubusercontent.com/17277863/87154296-60e5b480-c28f-11ea-8a14-7e59412b1ce8.png)

![image](https://user-images.githubusercontent.com/17277863/87154379-807cdd00-c28f-11ea-9097-7abc2b1dac35.png)

[totvsls.log](https://github.com/totvs/tds-vscode/files/4903074/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/4903077/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/4903078/totvsls_out.log)

**Comment by Nhaca** [comment]
Apenas lembrando que não havia lentidão nesse processamento.

**Comment by Nhaca** [comment]
Com a versão do pluggin 1.0.3 funcionou corretamente.

[totvsls_in.log](https://github.com/totvs/tds-vscode/files/4903154/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/4903155/totvsls_out.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/4903156/totvsls.log)

![image](https://user-images.githubusercontent.com/17277863/87155962-44974700-c292-11ea-95b3-eda109254abd.png)

**Comment by lwtnb-wrk** [comment]
@Nhaca Valeu    vamos analisar os logs     Grato pelos testes

**Comment by fmercurio** [comment]
> Com a versão do pluggin 1.0.3 funcionou corretamente.
> 
> [totvsls_in.log](https://github.com/totvs/tds-vscode/files/4903154/totvsls_in.log)
> [totvsls_out.log](https://github.com/totvs/tds-vscode/files/4903155/totvsls_out.log)
> [totvsls.log](https://github.com/totvs/tds-vscode/files/4903156/totvsls.log)
> 
> ![image](https://user-images.githubusercontent.com/17277863/87155962-44974700-c292-11ea-95b3-eda109254abd.png)

Olá, bom dia, gostaria de efetuar um teste com essa versão anterior da extensão, como você fez para instalar uma versão anterior?

**Comment by thiagomeschiatti** [comment]
@fmercurio 
![image](https://user-images.githubusercontent.com/17277863/87160304-254fe800-c299-11ea-9a0c-c2bfef7cd8f6.png)
![image](https://user-images.githubusercontent.com/17277863/87160332-300a7d00-c299-11ea-9263-807ecac1b904.png)

**Comment by lwtnb-wrk** [comment]
Favor acompanhar pela #437
