### ISSUE TITLE
Erro - Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by jonermarcelo** [totvs/tds-vscode#443]
Bom dia,

Ontem, ao tentar conectar em um AppServer para posterior compilação de rdmakes ADVPL, o VSCODE simplesmente "travou".

Reiniciei o AppServer o VSCODE onde após isto, todos os servers existentes "sumiram". Sendo apresentado à mensagem de erro conforme abaixo:

Cannot read property 'id' of undefined

Tentei adicionar novamente os AppServer, mas não adiciona... não salva...

Tentei criar uma nova workspace... mesma situação...

Removi à extensão do TDS-VSCODE TOTVS do VSCODE e instalei novamente... mesma situação...

Como consigo resolver está falha? Obrigado

![tela](https://user-images.githubusercontent.com/68082122/87156475-16fecd80-c293-11ea-8764-d990dafa511f.png)

**Comment by DanielYampolschi** [comment]
Bom dia @jonermarcelo , favor verificar a issue #434  o qual é sobre o mesmo problema e possui uma solução paliativa enquanto não liberamos a correção. Obrigado. 
Duplicate of 434#

**Comment by jonermarcelo** [comment]
@DanielYampolschi agradeço pelo pronto retorno.

Segui os procedimentos descritos na issue #434 e desta forma, consegui contornar à situação.

Obrigado!!!
