### ISSUE TITLE
Erro ao atualizar o plugin versão 1.05

### ISSUE THREAD

**Issue by aleksandro1977** [totvs/tds-vscode#445]
Após atualizar o tds versão 1.05 não compila mais nada e retorna os erros abaixo
C2090 File not found PRTOPDEF.CH

Sugiro ninguém atualizar, deu o mesmo erro em outras 5 máquinas aqui.

Voltar para versão 1.03

**Comment by sipmann** [comment]
Mesma coisa ocorrendo aqui. Para "funcionar", precisei colocar todos os includes na pasta do fonte para compilar paliativamente.

**Comment by LedBello** [comment]
Boa tarde! 

Mesmo problema aqui. Voltei para a versão 1.0.3.

**Comment by lwtnb-wrk** [comment]
Favor acompanhar pela #440
