### ISSUE TITLE
Atualização para versão 1.05 com problemas

### ISSUE THREAD

**Issue by marciorollo** [totvs/tds-vscode#446]
Boa tarde!

Ao atualizar para a versão 1.05, todas as configurações de servidores foram perdidas e não é mais possível configurar
novamente os servidores.

A versão 1.05 está com algum problema.

**Comment by aleksandro1977** [comment]
Estou com o mesmo problema.
Volte para versão anterior que funciona e risque essa do mapa

**Comment by WBaldin** [comment]
Mesmo problema aqui, todos os servidores sumiram, mas, apenas da visão servidores, pois, o arquivo "servers.json" está com todas as configurações. Já apaguei o arquivo e tentei recriá-lo, porém, a extensão não salva e nem dá erro.
Preciso fazer o downgrade da extensão, mas, ainda não descobri como fazê-lo.

**Comment by WBaldin** [comment]
Acabei de voltar para a versão 1.03 (versão imediatamente anterior) e tudo voltou a funcionar normalmente.

**Comment by pgeovane** [comment]
Sim, estou com problemas e tiver que voltar para 1.03.
Os ambientes até aparecem pra mim, mas gera um erro de compilação que não te explicação, voltei para 1.03 e não tenho mais problemas, risquem essa atualização do mapa..
A TOTVS lança tudo sem testar, patchs e até mesmo a extensão do  vscode rsrsrs

**Comment by lwtnb-wrk** [comment]
Favor acompanhar pela #434
