### ISSUE TITLE
Problema no debug apos atualização

### ISSUE THREAD

**Issue by michelschmidt** [totvs/tds-vscode#448]
Pessoal, fiz a atualização do meu vscode para a versao 1.47.0, após realizar isto, tive problema para conectar no server, onde consegui resolver o problema, porem apareceu um novo, na hora de realizar o debug ele fica um tempo e ocorre a mensagem Can´t connect to server.

**Config anterior:**
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Debug - Homologa",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "C:/Totvs/totvsclient_shared/smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true
		}

**Config nova:**
"version": "0.2.0",
	"configurations": [
		{
			"type": "advpl",
			"request": "launch",
			"name": "Debug - Homologa",
			"args": [],
			"cwd": "${workspaceFolder}",
			"programRun": "${command:AskForProgramName}",
			"stopOnEntry": false,
			"enviromentInfo": "${command:GetEnvInfos}",
			"workspace": "${workspaceFolder}/"
              }

Alguem já passou por isto?

**Comment by lwtnb-wrk** [comment]
@michelschmidt O problema pode estar relacionado ao de conexão #434. 
Veja se a solução paleativa ajuda neste caso tambem

**Comment by michelschmidt** [comment]
@lwtnb-wrk obrigado pela dica, consegui realizar o contorno com ela.
