### ISSUE TITLE
Erro ao apertar o botão OBJECTS INSPECTOR no VSCODE

### ISSUE THREAD

**Issue by williamsrcosta** [totvs/tds-vscode#449]
Estamos em migração para o Protheus 12.27.

E no VSCODE na hora de clicar em OBJECTS INSPECTOR, para apresentar os programas do R.P.O.

Acontece essa mensagem de erro no App Server Ini em modo console:

2020-07-10T16:54:43.100000-03:00 7728|
[FATAL][SERVER] 10/07/2020 16:54:43[Thread 7728] [THROW] [Thread 7728] MergeKArrays - error merging RPOs [duplicate name] - RPO list index [0] - function name 1 [] - source name 1 [ACAR615_EN.TRES] - line number 1 [2098] - function name 2 [] - source name 2 [ACAR615_ES.TRES] - line number 2 [1646].
 at file D:\bamboo-agent-5.7.2\xml-data\build-dir\TP11-TECX17V3R1-TECXWIN64\advpl\appmap.cpp line 4459

Como proceder?

**Comment by lwtnb-wrk** [comment]
@williamsrcosta Veja a issue #415
