### ISSUE TITLE
Campos da Tabela no debug não estão sendo mostrados

### ISSUE THREAD

**Issue by WBaldin** [totvs/tds-vscode#451]
Após esta última atualização "1.0.5" ao debugar algum fonte e selecionar em Variáveis\Tabela, somente aparecem os índices e apenas uns poucos campos (quando aparecem) das tabelas, onde antes apareciam todos os campos das tabelas abertas no momento de debug.

**Comment by lwtnb-wrk** [comment]
@WBaldin Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.
Alem disso se possivel grave um video com o problema e nos informe tambem os dados do AppServer e ambientes utilizados.

**Comment by WBaldin** [comment]
Bom dia @lwtnb-wrk, após reiniciar o sistema todo e tentar reproduzir o ocorrido para a produção do vídeo, não obtive sucesso, pois, o problema não mais ocorre. 
Obrigado pela atenção.
