### ISSUE TITLE
C02090 File not found PRTOPDEF.CH

### ISSUE THREAD

**Issue by jowks** [totvs/tds-vscode#452]
**Describe the bug**
Ao tentar realizar a aplicação de 3 fontes customizados, é apresentando o erro "C2090 File not found PRTOPDEF.CH", porém este include se encontra na pasta de includes, e o mesmo sequer é chamado nos fontes a serem aplicados.

**Expected behavior**
Aplicação dos fontes no RPO sem erros

**Screenshots**
![image](https://user-images.githubusercontent.com/39499982/87298589-d2687180-c4e0-11ea-8bab-ef35e521ab29.png)

**Desktop:**
 - OS/Architecture: Windows 10 x64

**Appserver:**
 - Build: 7.00.191205P
 - OS/Architecture: Windows Server 2016 x64
 - Build Version 19.3.0.4

**Additional context**
[Erro VSCode.zip](https://github.com/totvs/tds-vscode/files/4912152/Erro.VSCode.zip)
Arquivos de Log dentro do zip

**Comment by lwtnb-wrk** [comment]
@jowks Duplicado #440
