### ISSUE TITLE
Erro ao aplicar patch - Ambiente sempre busca pelo tlpp.rpo

### ISSUE THREAD

**Issue by jowkeen** [totvs/tds-vscode#454]
**Describe the bug**
Ao tentar realizar a aplicação de um patch em ambiente top connect com tttp.rpo a extensão está por default buscando o tlpp.rpo, que no caso não existe. 

**To Reproduce**
1. Selecione o ambiente tttp.rpo que deseja aplicar um patch
2. Clique em aplicar patch
3. selecione o patch em questão
4. clique em aplicar e veja o console.log do ambiente selecionado

**Expected behavior**
A extensão deveria realizar a aplicação do patch sem maiores problemas

**Screenshots**

**Desktop (please complete the following information):**
 - OS/Architecture: [e.g. Windows 64 bits]

**Appserver (please complete the following information):**
 - Build (with date): [e.g. Build 7.00.191205P]
 - OS/Architecture: [e.g. Windows 10 64]

**Additional context**
Console log com o problema:

2020-07-13T14:27:10.042000-03:00 16416|
 *********** RPO file (tlpp.rpo) not found. Creating... ***********

2020-07-13T14:27:10.042000-03:00 16416|
[WARN ][SERVER] [Thread 16416] OPEN EMPTY RPO - Environment totvstestejowkeen - File tlpp.rpo

2020-07-13T14:27:10.043000-03:00 16416|
[WARN ][SERVER] [Thread 16416] Error Loading TLPP RPO. Env: totvstestejowkeen
2020-07-13T14:27:10.049000-03:00 16416|------0--c:\users\jowkeen.canto\downloads\patch anderson\9168148_dsaube-11821_12.1.25_tttp120_lg.ptm

**Comment by lwtnb-wrk** [comment]
@jowkeen Você se certificou de que o patch realmente não foi aplicado? Essa mensagem [WARN] no console.log ocorre por outros motivos do AppServer, mas em teoria se não apresentar erro no tds-vscode o patch deve ter sido aplicado.
Se realmente voce confirmar que o patch não foi aplicado veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.
Tambem informe qual versão de AppServer utiliza e os Sistemas Operacionais utilizado.

**Comment by jowkeen** [comment]
Analisando pelo inspetor de objetos o fonte relativo ao patch foi aplicado, porém não houve nenhuma interação visual durante o processo de aplicação, a tela manteve-se estática. Segue algumas informações:


Versão: TOTVS Saúde
Build AppServer: 7.00.191205P-20200220 - 64 bits
Build DBAccess: 20181212
Release do RPO:  12.1.025
Release do dicionário: 12.1.025
Ambiente: Totvstestejowkeen
Local files: CodeBase
License server: 2014
DB DataBase: ORACLE

Módulo: PLS
Nome do computador: ADM_INF_002854
Sistema operacional: Windows 10 - 
Memória: 8099
Processador: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz

Módulo: PLS
Nome do computador: ADM_INF_002854
Sistema operacional: Windows 10 - 
Memória: 8099
Processador: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
[totvsls.log](https://github.com/totvs/tds-vscode/files/4914304/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/4914305/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/4914306/totvsls_out.log)

**Comment by lwtnb-wrk** [comment]
@jowkeen Estamos com um problema com as nofiicacoes durante a compilacao entao desabilitamos elas temporariamente.
As informacoes estao sendo apenas exibidas na visao "Output" que provavelmente nao devia estar aberta no momento.
Assim que resolvermos as questoes durante a compilacao a interacao visual deve ser reestabelecida.
Grato
