### ISSUE TITLE
Não consigo aplicar um patch através do VS Code - File could not be copied to the server

### ISSUE THREAD

**Issue by maumds** [totvs/tds-vscode#455]
[Info  - 3:04:59 PM] Applying patch file: e:/TOTVS/Protheus12/Protheus/updates/Erro verba 479 sumida/20-06-30_ATUALIZACAO_12.1.23_RH_EXPEDICAO_CONTINUA/expedicao_continua_12.1.23_rh_tttp120_lg.ptm
[Error - 3:05:04 PM] File could not be copied to the server.
[Info  - 3:05:04 PM] Aborting end build (rollback changes).
[Info  - 3:05:04 PM] Apply patch finished.

Conseguia sempre aplicar patch normalmente. Hoje fui tentar e não aplica....aparece as mensagens acima.

Ja troquei o Secure de 1 para 0 no server json e não adiantou. Tanto o Vscode como o projeto estão todos no mesmo servidor.

**Comment by lwtnb-wrk** [comment]
@maumds Favor informar as versões do AppServer e builds do RPO assim como os Sistemas Operacionais utilizados.

**Comment by maumds** [comment]
Dados do Server 

Versão: TOTVS Manufatura
Build AppServer: 7.00.191205P-20200424 - 64 bits
Appserver version: 19.3.0.4
Build DBAccess: 20181212-20190211
Release do RPO:  12.1.023
Release do dicionário: 12.1.023
Local files: CTREE
License server: 2014 - 2.3.4
DB DataBase: MSSQL
DB API Build: 20191119-20200116

Windows Server 2008 R2 standard

**Comment by maumds** [comment]
Esta faltando alguma informação de minha parte?

**Comment by lwtnb-wrk** [comment]
@maumds Você mencionou que aplicava patches normalmente mas agora não está aplicando.
Houve atualização de AppServer e/ou RPOs recentemente?
Se possível veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by maumds** [comment]
Atualização do server não ocorreu e tambem não troquei o repositorio, continuam os mesmos de quando iniciei o uso do vscode

Seguem os arquivos de log solicitados
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/4933092/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/4933094/totvsls_out.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/4933095/totvsls.log)

**Comment by lwtnb-wrk** [comment]
@maumds Fui informado que aparentemente existia um problema no AppServer que ocasiona esse erro esporadicamente. Eu não consegui reproduzi-lo aqui no meu ambiente.
Você consegue testar com um AppServer anterior (19.3.0.3)?

**Comment by maumds** [comment]
Eu vou tentar aqui com outro appserver e retorno a posterior, mas não sei se vou conseguir fazer isso exatamente agora, mas retorno.

**Comment by AleksSyntek** [comment]
Boa noite, já liberaron a versao 19.3.0.5 do Appserver é meu ticket no portal foi marcado como resolvido com esta liberacao. Ainda estou pendente de fazer o teste, 

Como solucao contorno pode desligar o protocolo SSL ou generar um slave separado com SSL desligado, ou executar na linha do comando logado no server em el diretorio onde reside o appserver, o siguiente:

`appserver.exe -compile -applypatch -files=<Caminho absoluto do arquivo de Patch> -env=<Ambiente onde o patch será aplicado>`

Slds.
