### ISSUE TITLE
Não consigo utilizar o object inspector

### ISSUE THREAD

**Issue by luisnagasakooxi** [totvs/tds-vscode#458]
Pessoal, alguém conseguindo usar o object inspector pelo vscode? Conecto no servidor e ao tentar rodar o object inspector gera as mensagens abaixo:

 Starting connection to the server 'Compila' (IPSERVIDOR)
[Info  - 10:21:24] Connection to the server 'Compila' finished.
[Info  - 10:21:28] Starting user 'admin' authentication.
[Info  - 10:21:28] Secure authenticating...
[Info  - 10:21:30] User authenticated successfully.
[Info  - 10:21:30] User 'admin' authentication finished.
[Info  - 10:21:35] Starting object inspector.
[Info  - 10:21:35] Loading objects from server.
[Error - 10:21:41] Could not retrieve objects list from RPO.
[Info  - 10:21:41] Object inspector finished.

**Comment by lwtnb-wrk** [comment]
@luisnagasakooxi Veja #415
