### ISSUE TITLE
Erro de compilação quando existe aspas simples dentro de uma string no arquivo CH

### ISSUE THREAD

**Issue by readless17** [totvs/tds-vscode#459]
O problema está acontecendo na compilação do fonte WSPORTAL01, pois o arquivo **wsportal01.ch** possui duas strings que possuem aspas simples em uma de suas palavras. Segue exemplo abaixo:

STR0005 = "Método de listagem dos grupos ou usuários vinculados ao usuário **'Administrador'**"
STR0006 = "Método de atualização das informações do usuário ou grupo do portal. A manipulação dos direitos somente pode ser feita pelo **'Administrador'**</i>"

Nos dois exemplos acima, as aspas simples que existem na palavra 'Administrador' está gerando erro de compilação. 

Dados do ambiente onde foram feitos os testes:

- OS: Windows 64 bits
- TOTVS - Build 7.00.191205P - Apr 24 2020 - 14:30:50
- Build: 64 bits
- SVN Revision: 26664
- Build Version: 19.3.0.4

![erro_vscode](https://user-images.githubusercontent.com/38880448/87458352-3c1b7500-c5e0-11ea-8c76-41c5d8192aaf.JPG)

**Comment by lwtnb-wrk** [comment]
@readless17 Fiz um teste aqui e não reproduzi o problema. Qual AppServer voce utiliza? Versões, build e SO?
Nos envie esse arquivo PRX e o CH para que possamos tentar reproduzir o problema aqui.

**Comment by readless17** [comment]
Segue em anexo os arquivos.
O problema ocorre tanto no R25 como no R27. Não sei dizer em qual momento esse problema passou a ocorrer, pois eu fiz uma manutenção nesse arquivo no final de 2019 e já existia essas strings que citei.

* TOTVS - Build 7.00.191205P - Apr 24 2020 - 14:30:50
* Build: 64 bits
* SVN Revision: 26664
* Build Version: 19.3.0.4

[wsportal01.zip](https://github.com/totvs/tds-vscode/files/4920668/wsportal01.zip)

**Comment by lwtnb-wrk** [comment]
@readless17 Isolamos o problema e está relacionado ao pré-compilador do Appserver. Estamos endereçando o problema com a equipe responsável. Informaremos assim que estiver resolvido.

**Comment by lwtnb-wrk** [comment]
@readless17 Isolamos o problema e trata-se de um problema causado pelos includes mais recentes. Acreditamos que seja um problema do Framework e vamos repassar o problema internamente.
No tds-vscode não há nada que possa ser feito e portanto vamos fechar esta issue.
Fique de olho e atualizações dos includes.

**Comment by cheyennepereira** [comment]
boa noite estou tendo o mesmo problema, gostaria de saber se já houve alguma solução para o problema em questão.

**Comment by lwtnb-wrk** [comment]
@cheyennepereira Essa não é uma questão que pode ser tratada pelo tds-vscode.

Pegue a versão mais recente dos includes compatível com sua LIB e se o problema continuar, abra um chamado no suporte da TOTVS.
