### ISSUE TITLE
Chave de compilação vencida

### ISSUE THREAD

**Issue by danielbolognani** [totvs/tds-vscode#46]
Após vencer a chave de compilação não é possível compilar nem User Function, o único jeito foi abrir a tela de chave de compilação e clicar em "Clean Key".

**Comment by lwtnb-wrk** [comment]
@danielbolognani adicionado tratamento de retorno para identificar chave vencida e remover do vscode. na proxima compilacao ou acao que necessite da chave a mesma ja nao existira pois foi removida
