### ISSUE TITLE
Debug no tds-vscode ao iniciar

### ISSUE THREAD

**Issue by clima158** [totvs/tds-vscode#460]
Olá!
Não estou conseguindo fazer debug pelo tds-vscode.
Logo após informar o nome da função AdvPL/4GL (no meu caso: u_cmpcpr10) apresenta a seguinte mensagem, abaixo:
![image](https://user-images.githubusercontent.com/68330022/87539816-982bdb00-c66c-11ea-8c48-b05fbf68cf02.png)

Não entendi o parametro "-c=_DBG_TEMP". Deveria estar como "-c=teste" (o environment está correto: -e=teste).
Qualquer que seja a rotina, inclusive SIGAADV, apresenta essa tela de erro.

A versão do meu vsCode:
![image](https://user-images.githubusercontent.com/68330022/87540547-e1c8f580-c66d-11ea-9e1a-c04ec13b0ff4.png)

A versão da extensão tds-vsCode:
![image](https://user-images.githubusercontent.com/68330022/87540793-3c625180-c66e-11ea-8daa-d41b4c1d24c5.png)

Informações do AppServer:
Tipo do servidor;Console
AppServer Build;7.00.170117A-20191024
Appserver version;17.3.0.16
Servidor 64 bits;Sim
Servidor Unix;Não

Informações da LIB
Versão da Lib;20190705
Data da Lib;20190712_17270
ID da Lib;37444b688b467b5fd60b7a1629a57747e2fac8ef
Release;12.1.025
HardLock;2014
Versão do License Server;2.4.14
Versão do Protheus;TOTVS Manufatura

Estou anexando os demais arquivos para análise.

[dap.log](https://github.com/totvs/tds-vscode/files/4924927/dap.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/4924930/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/4924932/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/4924933/totvsls_out.log)

Att.,

Carlos Lima

**Comment by lwtnb-wrk** [comment]
@clima158 Em relação ao parametro -C ela indica onde estão os parametros de conexão com o AppServer dentro do smartclient.ini apenas. É uma seção gerada por nos antes de iniciar o smartclient.
Voce consegue executar o smartclient sem ser em modo Debug (CTRL + F5)?

**Comment by clima158** [comment]
Olá!

Executei como CTRL+F5  e apresentou a mesma mensagem.

**Comment by lwtnb-wrk** [comment]
@clima158 Entendo que se executar, por fora do tds-vscode, o smartclient também apresentará o mesmo erro e isso indica que o problema está no executável do smartclient que está com algum problema ou é incompatível com o appserver que você está tentando acessar.
Corrija esse problema e você deve conseguir Debugar com o tds-vscode.
Se ainda assim não estiver conseguindo debugar reabra esta issue.
