### ISSUE TITLE
Totvs Servers X Workspace

### ISSUE THREAD

**Issue by jonermarcelo** [totvs/tds-vscode#461]
Olá,

Tenho percebido, que embora trabalhe no VSCODE com workspaces diferentes por clientes, as configurações do Totvs AppServer para compilação\debug são as mesmas em todas as workspaces que utilizo.

Ou seja, se eu tiver por exemplo 50 workspaces, uma para cada cliente... os Totvs AppServer que eu configurar aparecem em todas as 50 workspaces.

Existe alguma forma de fazer com que os Totvs AppServer configurados sejam salvos por workspace, à exemplo do que ocorria com o TDS ECLIPSE?

**Comment by lwtnb-wrk** [comment]
@jonermarcelo Estamos testando uma nova funcionalidade para isso. Mas nao temos previsao ainda para liberacao.

**Comment by bviniciusilva** [comment]
Olá,

Já existe alguma previsão da liberação dessa nova funcionalidade? Será muito importante para quem atua em campo com diversos clientes / ambientes.

**Comment by lwtnb-wrk** [comment]
@jonermarcelo @bviniciusilva Temos um VSIX versão 1.2.1 que está em Pré Release (Draft) em https://github.com/totvs/tds-vscode/releases/tag/1.2.1

A funcionalidade de salva por workspace está parcialmente implementada, pois ainda falta ajustar um listener, mas se procurarem por "Workspace Server Config" nos "Settings" e marcarem a opção, ao reiniciar o VS Code os servidores serão carregados a partir de configurações existentes no workspace.
Na próxima versão devemos ajustar o listener e adicionar facilitadores para troca da configuração sem necessitar reiniciar o VS Code.
Mas se quiserem/puderem baixar e instalar manualmente este VSIX para avaliar se o seu problema relatado foi solucionado, favor nos informar se está corrigido ou não para que possamos ver que estamos no caminho correto.

Para instalar manualmente o VSIX baixem do link acima e na aba de "Extensões" do VS Code clique em "..." e selecione "Install from VSIX" e apontem para o arquivo baixado.

**Comment by bviniciusilva** [comment]
Bom dia!

Ficou excelente, para quem é de consultoria e atende muitos clientes na
semana, da outra forma estava ficando muito confuso, minha workspace estava
com mais de 50 conexões configuradas.

Obrigado!

Em seg., 30 de nov. de 2020 às 10:48, lwtnb-wrk <notifications@github.com>
escreveu:
