### ISSUE TITLE
Mensagem "Couldn't find debug adapter descriptor for debug type 'totvs_language_debug' (extension might have failed to activate)

### ISSUE THREAD

**Issue by AleksSyntek** [totvs/tds-vscode#462]
**Describe the bug**
Boas tardes, ao momento do fazer um lacamento do debug no AdvPL, após de actualizar o VS Code ao última versao (1.47.1 c/pacote seguranca corrigido) aparece o mensagem "Couldn't find debug adapter descriptor for debug type 'totvs_language_debug' (extension might have failed to activate)".
Já fiz o reset do arquivo launch.json e recrié com o wizard (Ctrl+Shift+P -> Configurar TOTVS Launcher) é persiste mesmo erro.
Tambén fiz downgrade do plugin TDS-VsCode do versao 1.0.6 ao versao 1.0.5 sim sucesso. 

Só passa com o debug, o Smartclient executado normalmente accesa sim problema ao ambiente. Álguem já tuvo o mismo erro?

Conteúdo do arquivo launch.json:

 {
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "TOTVS Language Debug",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "D:\\TOTVS\\SmartClient LG19\\smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true,
			"programArguments": "undefined",
			"enableMultiThread": false,
			"enableProfile": false,
			"isAccessibilityMode": false,
			"doNotShowSplash": true,
			"language": "",
			"ignoreFiles": true
		}
	],
	"lastPrograms": [
		{
			"args": [],
			"label": "sigaadv",
			"description": ""
		},
		{
			"args": [],
			"label": "sigamdi",
			"description": ""
		}
	],
	"lastProgramExecuted": "sigaadv"
}

Slds.

**To Reproduce**
1. Com o ambiente AdvPL ja existente, e com versao do release 1.47.1 com data 2020-07-13 tentar fazer debug.
2. Accionar tecla F5 (Debug) 
3. Deve aparecer o mensagem "Couldn't find debug adapter descriptor for debug type 'totvs_language_debug' (extension might have failed to activate)".

**Expected behavior**
Devería permeter debuguear

**Screenshots**

![imagen](https://user-images.githubusercontent.com/30332762/87582172-69375880-c6b0-11ea-8179-53dc162e15c2.png)

**Desktop (please complete the following information):**
 - OS/Architecture: Windows 10 Pro 64 bits

**Appserver (please complete the following information):**
 - Build (with date): 7.00.191205P-20200424 - 64 bits
 - OS/Architecture: Windows Server 2012 R2 64bits
 - Build Version: 19.3.0.4

**Additional context**
VSCode:
Versión: 1.47.1
Confirmación: 485c41f9460bdb830c4da12c102daff275415b53
Fecha: 2020-07-13T22:44:14.582Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
Sistema Operativo: Windows_NT ia32 10.0.18363

**Comment by lwtnb-wrk** [comment]
@AleksSyntek Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by AleksSyntek** [comment]
@obrigado @lwtnb-wrk , estou ativando os logs do plugin é do TypeScript server, aparentemente pode ser um erro da versáo, já que estou encontrando muitas incidéncias da últimas horas relacionadas com o debug process que nao é executado (com diferentes linguagems ou cenários) no incidentes do VSCode:

https://github.com/microsoft/vscode/issues/102605
https://github.com/microsoft/vscode/issues/102615
https://github.com/microsoft/vscode/issues/102602
https://github.com/microsoft/vscode/issues/102597
https://github.com/microsoft/vscode/issues/102569

Vou a tentar obter o maior quantidade do infor no logs para entender o erro. Em paralelo estou tentado baixar una versao anterior do VSCODE (1.46) para fazer o test.
Slds.

**Comment by lwtnb-wrk** [comment]
@AleksSyntek O tds-vscode está sendo executado no Windows 10 ou no Windows Server 2012?
Nossa extensão não funciona no Windows Server 2012. Aparentemente os Windows Servers não possuem DLLs necessárias para o funcionamento dos binários utilizados pelo tds-vscode. Não há nada que possamos fazer neste caso. Você necessitará de um Windows (desktop) para utilizar o tds-vscode.
Para seu conhecimento estou na versão 1.47.0 do VS Code (Windows 10) e nela aparentemente tudo funciona conforme esperado.

**Comment by AleksSyntek** [comment]
No Windows 10 Pro, é meu máquina.

**Comment by lwtnb-wrk** [comment]
@AleksSyntek Conseguiu voltar para a versão 1.47.0 ou ate 1.46?

**Comment by AleksSyntek** [comment]
Mesmo erro @lwtnb-wrk, com esta versao:

VSCODE 1.47 x32:
Versión: 1.47.0
Confirmación: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Fecha: 2020-07-09T08:01:16.801Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
Sistema Operativo: Windows_NT ia32 10.0.18363

VSCODE 1.47.1 x64:
Versión: 1.47.1
Confirmación: 485c41f9460bdb830c4da12c102daff275415b53
Fecha: 2020-07-13T22:42:53.386Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
Sistema Operativo: Windows_NT x64 10.0.18363

**Comment by AleksSyntek** [comment]
Mais o que fiz com a versao 1.47.0 é borrar os folders .totvsls é .vscode/extensions/totvs.tds-vscode-1.0.6 e reconfigurar tudo. após do isso funcionó:

![imagen](https://user-images.githubusercontent.com/30332762/87606435-58e3a580-c6d1-11ea-916c-f72c9f5f2e2f.png)

Acho que com o update ao 1.47.1 alguma configuracao do plugin já no é leida corretamente pelo VSCode é nao registra corretamente o debug adapter.

Pode fechar o presente issue, já que será um issue relacionado com o update do VSCode mais o plugin no esta com erro já que reinstalando funciona com sucesso.
