### ISSUE TITLE
Appserver - Conexão não finaliza

### ISSUE THREAD

**Issue by prguser** [totvs/tds-vscode#463]
Caros, 

estava usando o VSCode com a extensão 1.0.6 e de repente as conexões com os servidores passaram a não finalizar, ficando no console a mensagem: 
[Trace - 15:12:32] Sending notification '$/setTraceNotification'.
[Trace - 15:29:28] Sending request '$totvsserver/connect - (17)'.
[Trace - 15:29:50] Sending request '$totvsserver/connect - (18)'.
[Trace - 15:30:22] Sending request '$totvsserver/validation - (19)'.
[Trace - 15:30:25] Sending request '$totvsserver/validation - (20)'

**Comment by lwtnb-wrk** [comment]
@prguser Não entendi bem o problema. A principio as conexões somente são finalizadas ao efetuar a desconexão.
Se possivel grave um video demonstrando o problema que voce esta tendo e no envie para analise.
