### ISSUE TITLE
Erro com compilar com F5

### ISSUE THREAD

**Issue by Ragoy** [totvs/tds-vscode#464]
Boa tarde,

Estou com problemas para compilar com F5 (StarT Debugging), é apresentado um erro que parece estar relacionado o Ctree ou o ambiente está em uso.
Segue imagem do erro para facilitar o entendimento, assim como informações da versão que estou utilizando.
Se alguém puder ajudar eu agradeço.
[VScode.docx](https://github.com/totvs/tds-vscode/files/4933411/VScode.docx)
[ErroF5Vscode.docx](https://github.com/totvs/tds-vscode/files/4933414/ErroF5Vscode.docx)

**Comment by lwtnb-wrk** [comment]
@Ragoy Isso começou após atualizar seu VS Code? Já tivemos um relato semelhante #462 sobre problemas ao debugar com especificamente após a atualização para a versão 1.47.1 do VS Code. 
Se puder retorne a versão 1.47.0 e refaça seus testes e confirme se isso resolve seu problema.

**Comment by Ragoy** [comment]
Boa tarde, obrigado pelo retorno.

Não foi depois de atualizar, na versão anterior do Vscode já apresentava esse problema.
Esse mesmo erro eu tive no TDS, quando tentava compilar (faz tempo) , eu uso balanceamento então tive que separar do ambiente de compilação para uma porta e rpo especifica e assim resolveu o problema, no TDS.
No vscode não consigo entender e configurar, pq o mesmo ambiente está rodando as duas plataformas de desenvolvimento.
Eu tenho um balance, um gridServer e 5 Slave, o que eu acredito é que meu ambiente tem que conectar direto no Slave01 poe exemplo, ele não pode passar pelo balance e gridServer.
Acredito que seja configuração.

**Comment by Ragoy** [comment]
Complemento...
No vscode no ambiente de produção está funcionando, acabei de fazer, mas no ambiente de teste não funciona, não encontro a diferença que gera esse erro.
Os dois ambientes estão no mesmo servidor e tem a mesma estrutura

**Comment by lwtnb-wrk** [comment]
@Ragoy Grato pelas informações, então se entendi corretamente você tem um ambiente de produção com o 1.47.1 e que a depuração está funcionando corretamente.
De qualquer forma em ambientes de Load Balance realmente a forma para depurar é diferente, pois não é possível depurar no servidor Master. Você sempre deve se conectar diretamente a algum dos Slaves para realizar a depuração.
Observe também que não se deve depurar em um servidor com outros usuários conectados, pois possivelmente as threads dos usuários e a de depuração poderão ocasionar comportamentos imprevisíveis.
Se possível veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para auxiliar nas análises.

**Comment by AleksSyntek** [comment]
@Ragoy o debug en uma configuracao master/slave do appservers nao deve apontar ao servico master mais o algum slave. Deve configurar IP e porta do appserver slave, já que o master nao ira a aceptar conexao si esta assim setado no appserver.ini.
Espero seja do ajuda. Slds.
