### ISSUE TITLE
VSCODE X Totvs Sped Service 12.1.27

### ISSUE THREAD

**Issue by jonermarcelo** [totvs/tds-vscode#465]
Prezados,

Não consigo conectar no AppServer do TSS 12.1.27, ocorre o erro abaixo:

![image_2020_07_20T13_37_03_791Z](https://user-images.githubusercontent.com/68082122/87944419-bed78080-ca75-11ea-822c-fe5c4ff8b8d9.png)

**Comment by lwtnb-wrk** [comment]
@jonermarcelo Veja #412

**Comment by jonermarcelo** [comment]
@lwtnb-wrk,

Fiz novos testes com binário descrito em #412, no entanto à questão "persiste".

Não consigo de jeito nenhum conectar no TSS. Já atualizei o TSS conforme portal... instalei do zero e nada...

No console do APPSERVER do TSS consta está ocorrência:

![image](https://user-images.githubusercontent.com/68082122/87963859-c73cb500-ca8f-11ea-8b9b-d51daccd5766.png)

**Comment by lwtnb-wrk** [comment]
@jonermarcelo Não conheço nada de TSS mas pelo erro apresentado, o AppServer está retornando um valor inválido quando chamamos a mensagem de autenticação.
Você consegue se conectar por fora com um smartclient nesse ambiente?

**Comment by jonermarcelo** [comment]
@lwtnb-wrk, instalei o TSS do zero e mesmo assim acontece à mesma coisa.

Eu consigo conectar com o usuário ADMIN normalmente no TSSINTERFACE por exemplo...

**Comment by lwtnb-wrk** [comment]
@jonermarcelo A documentação do TSS fala sobre um Smartclient do TSS. Você não consegue acessar o TSS através de um Smartclient padrão?
O que estou achando é que a autenticação do TSS não é a mesma utilizada pelo Protheus padrão e por isso não está validando o usuário.
Tente se conectar com um Smartclient padrão e veja se ocorre o mesmo problema de conexão.

**Comment by jonermarcelo** [comment]
@lwtnb-wrk, utilizei o SmartClient do TSS e acessei à interface TSSINTERFACE pelo mesmo no TSS sem problemas.

Ocorre que o TSS, não tem suporte para SIGAMDI... só aos programas TSSINTERFACE e TSSMONITOR onde ambos, o usuário autentica corretamente.

**Comment by lwtnb-wrk** [comment]
@jonermarcelo Mas se não conectar pelo Smartclient padrão acredito que não será possível se conectar pelo tds-vscode.
Se o TSS estiver usando uma forma diferente da padrão para se conectar não temos o que fazer.

**Comment by lwtnb-wrk** [comment]
@jonermarcelo Voce tentou se conectar com o usuario e senha que utiliza para se conectar ao SIGACFG?

**Comment by jonermarcelo** [comment]
@lwtnb-wrk, descobri questões interessantes...

1*) Se o TSS e o ERP Protheus estiverem apontando para o mesmo database, não conecta\autentica o TSS no VSCODE de jeito nenhum. Criei um banco só para o TSS e ao tentar conectar no AppServer do TSS via VSCODE deu certo.

2*) Por mais que o usuário ADMIN do TSS tenha uma senha definida, se informar à senha dá o erro de autenticação, se informar apenas o usuário ADMIN sem senha, conecta\autentica no VSCODE.
