### ISSUE TITLE
não conecta com o totvspdv

### ISSUE THREAD

**Issue by yuryrogens** [totvs/tds-vscode#466]
[**Describe](url) the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS/Architecture: [e.g. Windows 64 bits]

**Appserver (please complete the following information):**
 - Build (with date): [e.g. Build 7.00.170117A - Jun 28 2019 - 11:16:56]
 - OS/Architecture: [e.g. Linux 64 bits Ubuntu]
 - Build Version [e.g. 17.3.0.13]

**Additional context**

![Capturar](https://user-images.githubusercontent.com/68610301/88089253-13582a00-cb62-11ea-931e-7a6950c423ee.PNG)

**Comment by yuryrogens** [comment]
ao tentar conectar para aplicar patch a mensagem a seguir aparece

**Comment by yuryrogens** [comment]
12.1.27 
![Capturar](https://user-images.githubusercontent.com/68610301/88089498-75189400-cb62-11ea-89f0-141c0c48167f.PNG)

**Comment by lwtnb-wrk** [comment]
@yuryrogens Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.
Envie tambem o appserver.ini do servidor que não conecta e o console.log com possiveis erros exibidos durante a tentativa de conexao.

**Comment by yuryrogens** [comment]
não da para enviar o arquivo acima 
![Capturar](https://user-images.githubusercontent.com/68610301/88095248-2d4a3a80-cb6b-11ea-9b84-b5e47fa691b6.PNG)
![Capturar1](https://user-images.githubusercontent.com/68610301/88095250-2e7b6780-cb6b-11ea-8f1e-99bec5288aca.PNG)
![Capturar3](https://user-images.githubusercontent.com/68610301/88095524-a77abf00-cb6b-11ea-954f-de8e0f3a11ce.PNG)

ao colocar a configuração de gerar logo não gera arquivo

**Comment by lwtnb-wrk** [comment]
@yuryrogens A extensão está atualizada? A tela de cadastro está diferente da atual.
Sem os logs e informações não tem nada que possamos fazer para auxiliar.

**Comment by yuryrogens** [comment]
na nova não abria nem a estação de configuração para conectar o pdv, porém ao atualizar para 1.0.6 não sei pq deu certo agora
