### ISSUE TITLE
Erro - Compilar Cliente WSDL

### ISSUE THREAD

**Issue by jonermarcelo** [totvs/tds-vscode#468]
Olá,

Estamos com problemas ao compilar arquivo .PRW, referente à cliente WSDL gerado via VSCode através do link abaixo:

https://fwshomo.afip.gov.ar/wsctg/services/CTGService_v4.0?wsdl

Ao tentar compilar, é informado inconsistência nos trecos do arquivo PRW gerado que contém "."

![image](https://user-images.githubusercontent.com/68082122/88217383-d9a42380-cc34-11ea-92ea-1f368de5dc41.png)

**Comment by lwtnb-wrk** [comment]
@jonermarcelo Pelo que vi aqui, o tds-vscode apenas chama uma mensagem do Appserver que retorna o conteudo do arquivo PRW e do lado do Appserver ele chama o metodo "WSDLSource" do frame. Então acredito que o mesmo problema possa ocorrer ao tentar usar esse métdo do frame.
Por gentileza endereçar o problema ao time de Framework.
