### ISSUE TITLE
Conexao servidor

### ISSUE THREAD

**Issue by frangrupi** [totvs/tds-vscode#469]
Boa tarde,

Quero usar o VSCODE, porém essa é uma base que fica em nuvem da Totvs e nunca fiz dessa forma, somente em intalação local e nunca tive problema.  Acontece que esta retornando essa mensagem. Será que precisa mandar habilitar alguma coisa lá pra conseguir conexão? 	
[Error - 15:10:10] Unable to connect to the server. Check if the IP:port is correct, the server is online and try again.
[Info  - 15:10:10] Validate server xx.protheus.cloudtotvs.com.br@6000 finished

"configurations": [
		{
			"id": "8b4c4j35skkd0ji25wa6zc94m6c2",
			"type": "totvs_server_protheus",
			"name": "env",
			"port": 6000,
			"address": "xx.protheus.cloudtotvs.com.br",
			"buildVersion": "",
			"secure": 0,
			"includes": [
				"C:\\Users\\xx\\Desktop\\xx\\include"
			]
		}
	]

Att, Franciele.

**Comment by lwtnb-wrk** [comment]
@frangrupi Em se tratando de Cloud acredito que esse IP:port deve ser de um Master em Load Balance ou Broker.
É possível que esse Appserver esteja com uma configuração que pode bloquear as conexões do tds-vscode.
Pela configuração que você enviou acima, o tds-vscode nem conseguiu uma conexão simples com o Appserver.
O que você está tentando fazer se conectando a esse AppServer na Cloud?

**Comment by frangrupi** [comment]
Eu peguei a mesma configuração que esta no arquivo smartclient.ini, mas não sei se é a correta pra esse caso... onde eu consigo a configuração que tenho que colocar? Pois na Totvs me orientaram abrir chamado aqui rs.

**Comment by lwtnb-wrk** [comment]
@frangrupi A conexão por Smartclient funciona em Load Balance pois o servidor Master redireciona a conexão para os Slaves. 
No tds-vscode a conexão é realizada diretamente no Master e se o Appserver estiver configurado com o canacceptdebugger=0 o tds-vscode não vai conseguir se conectar.
Essa configuração é do AppServer e como está na Cloud você tem que verificar com o time de Cloud.
Mas já adianto que por questões de segurança eles não deveriam alterar essa configuração.
Por isso pergunto novamente, o que você quer fazer se conectando a este AppServer na Cloud?

**Comment by frangrupi** [comment]
Quero compilar fonte e debugar.

**Comment by lwtnb-wrk** [comment]
@frangrupi Esse ambiente na Cloud é de desenvolvimento, de homologação ou produção?

**Comment by frangrupi** [comment]
Ahh ta esse é de produção. Não Consigo compilar direto em produção? No caso faço como? Me desculpa a pergunta como eu disse nunca trabalhei em instalação assim to meio perdida.

**Comment by lwtnb-wrk** [comment]
@frangrupi Realmente não é aconselhável utilizar um ambiente de produção para isso. Aconselhamos a ter um ambiente local onde você pode realizar o desenvolvimento e depuração das suas user functions para depois gerar um patch que seria aplicado no ambiente de homologação para validação. Estando tudo em conformidade, o patch poderia ser aplicado em Produção pelo time de Cloud (se não me engano acredito que exista uma site de administração onde você pode realizar a aplicação do Patch).

**Comment by frangrupi** [comment]
Bom dia,
Estou tentando agora configurar o ambiente de desenvolvimento, 
neste segundo a Totvs eu posso debugar normalmente, agora conecta mas nao autentica apresenta:
[Error - 10:03:10] Authentication error: Server returned a non numeric value.
[Error - 10:03:10] Authentication failed. Could not authenticate to server.

Sabe o que pode ser?

Franciele.

**Comment by lwtnb-wrk** [comment]
@frangrupi O Appserver está retornando esse erro "Server returned a non numeric value". 
Voce consegue se conectar ao Appserver com um Smartclient? Se não estiver conseguindo se conectar ao Appserver com o Smartclient, seu ambiente deve ter problemas de configuração e precisa ser corrigido para utilizar o tds-vscode.

**Comment by frangrupi** [comment]
Do appserver com o smartclient eu consigo normal.

**Comment by lwtnb-wrk** [comment]
@frangrupi Mas o Appserver local esta com a configuração de Load Balance/Broker ou é apenas um Appserver isolado?

**Comment by lwtnb-wrk** [comment]
@frangrupi Nos foi relatado que esse problema pode ser resolvido com o uso da chave SpecialKey
Veja em https://centraldeatendimento.totvs.com/hc/pt-br/articles/360031798133-MP-FRAME-Chave-SpecialKey
nos informe se esta solução funcionou para voce

**Comment by jowks** [comment]
@frangrupi no meu caso, o servidor que estava dando problema era meu servidor de WS, e apresentava o mesmo erro.
Quando rodei o serviço em modo console, percebi que o mesmo estava apresentando erro de Checksum. Substitui o RPO por um outro RPO fornecido pela TOTVS com a correção do erro de CheckSum, e então consegui conectar normalmente.

Tente rodar a aplicação em modo console e acompanhe se no momento da autenticação no servidor o console apresenta algum erro.

**Comment by lwtnb-wrk** [comment]
@jowks Grato por compartilhar essa informação.
