### ISSUE TITLE
Aplicação de patch não detecta rpo em uso

### ISSUE THREAD

**Issue by likid** [totvs/tds-vscode#47]
Ao fazer uma compilação em um rpo em uso, a extensão gera um erro e aborta a execução da compilação, porém ao aplicar um patch em um rpo em uso, não ocorre o mesmo comportamento. O processo fica como se estivesse pendente e nunca encerra.

**Comment by lwtnb-wrk** [comment]
@likid Somente confirmando, voce tem a chave BUILDKILLUSERS=1 certo? Eu testei aqui e nao reproduzi o problema de travamento. A minha aplicacao de patch derrubou meu smartclient que estava conectado e aplicou o patch sem problemas. Favor verificar se esta com o ambiente atualizado e confirmar que o problema esta ocorrendo? Alias qual a versao de servidor (build) e RPO em uso?

**Comment by likid** [comment]
Leo, estou sem a chave buildkillusers, tanto é que quando vou compilar ele da erro na build pois o rpo está em uso, mas ao aplicar o patch ele não faz nada, não dá erro, não confirma e não cancela.

**Comment by lwtnb-wrk** [comment]
@likid Grato pela informação. Vou desativar minha chave e ver como ele se comporta para a compilação e aplicacao de patches entao.

**Comment by lwtnb-wrk** [comment]
@likid Correção efetuada. Estará disponivel na proxima atualização. Grato por informar o problema.
