### ISSUE TITLE
Usuario do Windows com acento

### ISSUE THREAD

**Issue by marcioaalmenara** [totvs/tds-vscode#470]
Meu Usuário do windows possui acentuação,  com isto, ao tentar debugar é apresentada a mensagem :"User not Authenticated. Please Connect/reconnect to a server", sendo que o servidor esta logado (consigo compilar)
Pergunto há uma solução para isto sem que eu tenha que refazer meu usuário ?

**Comment by lwtnb-wrk** [comment]
@marcioaalmenara duplicado #423 
ainda não temos previsão para resolver esta questão
