### ISSUE TITLE
The TOTVS Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by enakamatu** [totvs/tds-vscode#471]
**Describe the bug**
Mensagem ao tentar incluir novo server:
The TOTVS Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

Dados do VSCode:
Version: 1.47.3 (user setup)
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 6.3.9600

**To Reproduce**

**Desktop (please complete the following information):**
Windows Server 2012 R2

**Appserver (please complete the following information):**
[build: 7.00.191205P-20200311]
Windows Server 2012 R2

**Additional context**
Testado com plugins anteriores

**Comment by lwtnb-wrk** [comment]
@enakamatu O tds-vscode não funciona corretamente nos Windows Server. Acreditamos que o Windows Server não tenha DLL necessárias para o correto funcionamento do nosso LS.
Para utilizar o tds-vscode voce precisara usar um Windows (desktop).
