### ISSUE TITLE
Não consigo Debugar os fontes

### ISSUE THREAD

**Issue by veltonteixeira** [totvs/tds-vscode#472]
Ao debugar, o VSCODE apresenta a mensagem abaixo e não abre a aplicação:

[19:27:40] INFO: TOTVS Server connected.
[19:27:40] INFO: Configuração TDS-DA concluída.
[19:27:47] INFO: ExitCode=0 ExistStatus=NormalExit
[19:27:48] INFO: TDS-DA finished.

**Comment by veltonteixeira** [comment]
Segue a versão do VSCODE:
Version: 1.47.3 (system setup)
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:12:49.994Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 6.3.9600

**Comment by lwtnb-wrk** [comment]
@veltonteixeira Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by veltonteixeira** [comment]
Segue em anexo os logs
[dap.log](https://github.com/totvs/tds-vscode/files/5003859/dap.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/5003860/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/5003861/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/5003862/totvsls_out.log)

**Comment by lwtnb-wrk** [comment]
@veltonteixeira A não ser que tenha renomeado seu smartclient para appserver, sua configuração deve estar incorreta.
"smartclientBin":"D:\\Totvs\\Protheus12\\Aplicativos\\appserver - lg - slave02\\appserver_lg_slave_02.exe"
Veja se não é esse o problema.

**Comment by DanielYampolschi** [comment]
Ola @veltonteixeira, como ja faz 20 dias da ultima mensagem do Leo e não tivemos retorno, vamos encerrar essa issue.. se esse problema persistir, reabra ela, ou se precisar de algum outro auxilio, por favor abra uma nova issue.
