### ISSUE TITLE
Quando crio uma configuração adicional não consigo mais compilar os fontes

### ISSUE THREAD

**Issue by GersonBelini** [totvs/tds-vscode#474]
Estava usando normalmente, o VSCODE para compilar as funções, adicionei um novo SERVER e a partir daí, começou a ocorreu o erro.

As pastas de include estão configuradas.

Já removi o VSCODE e instalei novamente.

Removi todos os servers e configurei novamente, mas o erro permanece.

{
	"resource": "/d:/totvs/TotvsDeveloperStudio-11.3/WorkSpace/Parex_Trabalho/src/Automacao/Documento_Entrada/PxLoadDocE.prw",
	"owner": "AdvPL",
	"severity": 8,
	"message": "C2090  File not found PRTOPDEF.CH",
	"source": "appre",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 2,
	"endColumn": 1
}

**Comment by lwtnb-wrk** [comment]
@GersonBelini Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise

**Comment by GersonBelini** [comment]
[totvsls.log](https://github.com/totvs/tds-vscode/files/5003499/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/5003500/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/5003501/totvsls_out.log)

**Comment by GersonBelini** [comment]
Removi novamente toda a instalação.

Apaguei todas as pastas de configuração.

Criei uma nova pasta para meu projeto.

Configurei o plugin para esta nova pasta e funcionou.
