### ISSUE TITLE
user must be logged in before compile

### ISSUE THREAD

**Issue by Talha672** [totvs/tds-vscode#475]
**Describe the bug**

**To Reproduce**
Ao Excluir uma conexão e criar ela novamente não permite compilar 

**Desktop (please complete the following information):**
- Windows 10

**Appserver (please complete the following information):**
* TOTVS - Build 7.00.191205P - Feb  5 2020 - 15:20:05
* Build: 64 bits
* SVN Revision: 25991
* Build Version: 19.3.0.1_RC13

**Comment by lwtnb-wrk** [comment]
@Talha672 Atualize seu AppServer pois versões antigas continham um bug que causavam este tipo de erro.
Depois de atualizado talvez seja melhor apagar o servidor e cria-lo novamente para ter certeza de que as informações estão zeradas.
