### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by mtkmobile** [totvs/tds-vscode#476]
- Issue Type: `Bug`
- Extension Name: `tds-vscode`
- Extension Version: `1.0.6`
- OS Version: `Windows_NT x64 6.1.7601`
- VSCode version: `1.47.3`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by lwtnb-wrk** [comment]
@mtkmobile Qual o problema? Descreva o que ocorre pois não há nenhuma informação sobre o problema aqui.
E veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise
