### ISSUE TITLE
Debug F10 Linha a Linha não funciona

### ISSUE THREAD

**Issue by maximinocastro** [totvs/tds-vscode#477]
Bom dia Prezados, 

Na ultima atualização o debug linha a linha via F10 não funciona ele sisplesmente pula para o proximo break point marcado como se fosse o F5.

Att.

**Comment by lwtnb-wrk** [comment]
@maximinocastro Fiz um teste aqui e o F10 apresentou o comportamento esperado de avançar linha a linha.
Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.
Tambem informe as versões, data/build e SO do Appserver em que o problema ocorre.

**Comment by maximinocastro** [comment]
Segue os dados solicitados desculpe a demora,

Dados do Server

Versão: TOTVS Serviços
Build AppServer: 7.00.170117A-20190628 - 64 bits
Build DBAccess: 20181212
Release do RPO: 12.1.025
Release do dicionário: 12.1.025
Ambiente: Producao
Local files: ctree
License server: 2014
DB DataBase: MSSQL7

Dados da LIB

Versão da Lib:20190705
Data da Lib: 20190712_17270
Commit ID:37444b688b467b5fd60b7a1629a57747e2fac8ef

**Comment by lwtnb-wrk** [comment]
@maximinocastro E os logs? Especialmente o do DAP pois trata-se de problema na depuração.

**Comment by maximinocastro** [comment]
Irei gerar e já mando

**Comment by maximinocastro** [comment]
Segue o arquivo DAP.log
[dap.log](https://github.com/totvs/tds-vscode/files/5071019/dap.log)

**Comment by lwtnb-wrk** [comment]
@maximinocastro Pelo log observei o seguinte cenario:
Voce iniciou o debug e o Appserver parou no breakpoint da linha 175 (CALCFRTBRA.PRW) então voce enviou o comando "next" que foi para linha 176
Em seguida o Appserver tenta parar na linha 517 (PROTHEUSFUNCTIONSEARCH.PRW) que não existe no seu projeto (deve ser padrão do frame)
Porem como este fonte nao existe e vai repete a ultima ação e aparentemente entra em um loop.
E ficou assim até receber um comando de "continue" apos cerca de 17 segundos, e em seguida terminou a depuração.
Não conheço esse fonte PROTHEUSFUNCTIONSEARCH.PRW então não posso dizer se ele estava processando algo corretamente ou estava em algum loop infinito.
Você chegou a esperar quanto tempo antes de enviar o comando de "continue"?
Seu ambiente Appserver e LIB parecem meio desatualizados. Pode ser que esse seja realmente algum bug do Appserver ou da LIB que já foi corrigido, então sugiro realizar um backup e atualizar seu ambiente para confirmar se não se trata de um problema do seu ambiente.

**Comment by maximinocastro** [comment]
Entendi.

Infelizmente não será possível atualizar a LIB por que é meio complexo aqui na empresa.

E o fonte PROTHEUSFUNCTIONSEARCH.PRW não é aqui da empresa deve ser da TOTVS.

Mas de qualquer forma muito obrigado.

Na versão do Plugin 1.0.3 funcionava certinho o F10 depois parou de funcionar.

Att.

**Comment by lwtnb-wrk** [comment]
@maximinocastro Se voce reverter para a versão 1.0.3 funciona? Se afirmativo, faça esse teste. 
Repita as mesmas operações e gere novamente o dap.log para eu ver se identifico alguma diferença importante.

**Comment by maximinocastro** [comment]
Boa tarde,

Eu desinstalei e reinstalei o plugin e funcionou perfeitamente.

Att.
