### ISSUE TITLE
Compilação por pasta ou projeto - mensagem 'compilado com sucesso' mas não é compilado.

### ISSUE THREAD

**Issue by nahimdhaney** [totvs/tds-vscode#478]
O Mensagem indica que foi compilada corretamente,

Mas quando o programa e testado, a compilacao nao foi realizada no RPO.

Isto acontence com Diversos Ambientes, então não temos certeza se o arquivo foi realmente compilado.

Eu preciso compilar fonte por fonte pra fazer uma compilacao.

V.12.1.27 - Bolivia.

**Comment by lwtnb-wrk** [comment]
@nahimdhaney Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise

**Comment by nahimdhaney** [comment]
Boa tarde,

Adiciono o video de exemplo e tambem log solicitado:

https://drive.google.com/drive/folders/1d0LDcG1ancPPLETLSWIyZ7IqbaCDlePC?usp=sharing


no video voce consigue visualizar que a compilacao do fonte **PickGraf.PRW** nao e feita até ela fazer sozinho,

**Comment by lwtnb-wrk** [comment]
@nahimdhaney Pelo log pude observar que a extensão não está atualizada.
Tivemos um problema em versões passadas que não identificavam corretamente a extensão dos arquivos em uma pasta.
Atualize a extensão tds-vscode e refaça os testes.
Se o problema persistir reenvie os novos logs para analise.

**Comment by nahimdhaney** [comment]
Boa tarde, ao parecer já está compilando do jeito correito, vou fechar o issue, obrigado!
