### ISSUE TITLE
Erro ao abrir Protheus quando há mais de um SmartClient configurado no launch.json

### ISSUE THREAD

**Issue by Felipe-Raposo** [totvs/tds-vscode#479]
**Describe the bug**
Ao executar o Protheus diretamente pelo VSCode (F5 ou CTRL+F5), é criado um ambiente temporário no smartclient.ini chamado _DBG_TEMP. Mas quando o VSCode tem mais de um SmartClient configurado no launch.json, esse ambiente temporário é criado no smartclient.ini do primeiro smartclientBin encontrado no launch.jon

**To Reproduce**

1 - Configure dois smartclients no launch.json. Os smartclients precisam estar em pastas separadas. Exemplo:
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "SmartClient LG-17",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "/home/felipe/totvs/protheus/smartclient_LG17/smartclient"
		},
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "SmartClient LG-19",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "/home/felipe/totvs/protheus/smartclient_LG19/smartclient"
		}

2 - Selecione o primeiro SmartClient (no exemplo acima seria o SmartCliente LG-17) e se conecte a um AppServer Protheus compatível via F5 ou CTRL+F5.
Note que nesse momento foi criado um ambiente temporário no smartclient.ini do SmartClient selecionado.

3 - Desconecte desse AppServer e tente se conectar a outro AppServer usando o segundo SmartClient (SmartClient LG-19). Nesse momento dará erro de conexão.
Analisando, notei que o VSCode atualizou o smartclient.ini do SmartClient errado. No exemplo foi atualizado o smartclient.ini do LG-17.

**Expected behavior**

- Deveria atualizar o smartclient.ini correto e se conectar.

**Comment by lwtnb-wrk** [comment]
@Felipe-Raposo O F5 ou CTRL+F5 iniciam a execução do smartclient (em modo Debug ou Run) mas não realizam o conexão ao Appserver.
Logo a execução do Smartclient deve estar casada com o Appserver conectado na visão "TOTVS: Server", ou seja, se na visão "TOTVS: Server" você estiver conectado em um Appserver LG 17 e na visão "RUN/DEBUG" o smartclient selecionado for um compativel com o LG 19, ocorrerá o erro de conexão que voce deve estar observando.
Pelos testes que realizei o comportamento aparentemente é o esperado e ambos os smarclients (LG 17 e LG 19) tiveram a seção [_DBG_TEMP] atualizada conforme o Appserver conectado.
