### ISSUE TITLE
Lista dos ambientes ao conectar no AppServer

### ISSUE THREAD

**Issue by eurairapelli** [totvs/tds-vscode#48]
Boa tarde,

Função semelhante ao TDS.
Na primeira conexão com o appserver, listar os ambientes disponíveis no appserver e salvar no jSon environments.
Atualmente é digitado no campo ou adicionado manualmente através do servers.json
"environments": [
	"PROD",
	"PROD_COMP",
	"PROD_COMP2",
	"PROD_DESENV"
],

**Comment by lwtnb-wrk** [comment]
@eurairapelli devido a questoes de seguranca interna, as informacoes dos environments nao serao mais disponibilizadas sendo que o usuario deve informar manualmente o ambiente em que ele deseja se conectar. porem apos a 1a conexao neste ambiente salvamos esta informacao que fica disponivel para as proximas conexoes. grato pela compreensao
