### ISSUE TITLE
Workspace somente com  *.prw

### ISSUE THREAD

**Issue by Isoplast** [totvs/tds-vscode#480]
Bom dia!
Há como eu filtrar as extensões dos aquivos que são apresentados no meu workspace ?
No meu caso, aparecem os *.bak e outros que não interessam !!!

**Comment by lwtnb-wrk** [comment]
@Isoplast Procure por files.exclude do próprio VS Code.

**Comment by Isoplast** [comment]
Obrigado pelo retorno. 
Já havia tentado, mas não funciona!
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
		"totvsLanguageServer.welcomePage": false,
		"workbench.colorTheme": "Monokai",
		"workbench.preferredDarkColorTheme": "Quiet Light",
		"files.exclude": {
			"*.BAK": true,
			"**/.BAK": true
		}
	}
}
