### ISSUE TITLE
Workspace somente com *.prw

### ISSUE THREAD

**Issue by Isoplast** [totvs/tds-vscode#481]
Bom dia!
Há como eu filtrar as extensões dos aquivos que são apresentados no meu workspace ?
No meu caso, aparecem os *.bak e outros que não interessam !!!

Obrigado pelo retorno. 
Já havia tentei o files.exclude, mas não funciona!
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
		"totvsLanguageServer.welcomePage": false,
		"workbench.colorTheme": "Monokai",
		"workbench.preferredDarkColorTheme": "Quiet Light",
		"files.exclude": {
			"*.BAK": true,
			"**/.BAK": true
		}
	}
}

_Originally posted by @Isoplast in https://github.com/totvs/tds-vscode/issues/480#issuecomment-668562805_

**Comment by lwtnb-wrk** [comment]
@Isoplast Fiz um teste aqui e funcionou tranquilo. Veja melhor como definir os padrões de exclusão em https://code.visualstudio.com/docs/editor/codebasics#_advanced-search-options

**Comment by lwtnb-wrk** [comment]
@Isoplast Ah só um detalhe parece que o padrão é case-sensitive... Mas isso é coisa do VS Code infelizmente...
