### ISSUE TITLE
Erro ao compilar. Versao 1.47.3

### ISSUE THREAD

**Issue by Robsondpm** [totvs/tds-vscode#484]
Por favor, ao tentar compilar exibe o erro anexo dizendo que a pasta do include não foi encontrada mas está la. Poderiam ajudar no que pode ser?

![image](https://user-images.githubusercontent.com/69259802/89448256-b47fdc80-d72d-11ea-9e04-3e968292219b.png)

Obrigado

**Comment by lwtnb-wrk** [comment]
@Robsondpm Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.
A descricao do problema no github tambem esta incompleta pois nao exibe o erro anexo (se abriu a issue por email os anexos nao aparecem no github)

**Comment by Robsondpm** [comment]
Boa tarde,
Segui o passo a passo para gerar o log mas os arquivos mencionados não encontro.
Anexo os prints do meu ambiente no momento.

Obrigado.


Robson Miranda
     TENARIS IT

**Comment by lwtnb-wrk** [comment]
@Robsondpm A maioria dos anexos enviados por emails não são adcionados a Issue no github. 
Nesta última mensagem nada aparece na Issue.
Os arquivo, se configurado corretamente, devem aparece na raiz do projeto aberto.

**Comment by DWilhemus** [comment]
@Robsondpm 
Brother eu estava com o mesmo problema, daí eu vi que ele pega a configuração do servidor antes de usar a global...

Abre o arquivo "servers.json" na pasta "%userprofile%\.totsvls" (fica na pasta do seu usuario Windows) e altere o caminho de todas as linhas que tiverem "includes" assim como a imagem que anexei aqui, isso seria a configuração de cada server que você configurou na extensão, então cada lugar que tiver essas informações você precisa alterar para o caminho correto de seus includes... No seu caso é "C:\\VSCODE\\include".
![image](https://user-images.githubusercontent.com/69646940/90175178-6bf39f00-dd7d-11ea-898b-a6bf5382f8c3.png)


Espero que tenha ajudado...

**Comment by lwtnb-wrk** [comment]
@DWilhemus Bem observado.
Vamos adicionar essa informação mais claramente na compilação para facilitar a identificação de um possível problema de includes.

**Comment by Robsondpm** [comment]
Bom dia Pessoal, o problema foi resolvido mapeando a unidade de rede correspondente tanto para os includes como para os fontes. Aí ele reconhece corretamente como se fosse uma unidade local. Obrigado a todos pela ajuda.
