### ISSUE TITLE
ERRO conexão usuario ADMIN no ambiente WORKFLOW

### ISSUE THREAD

**Issue by RodrigoTeixeira-2101** [totvs/tds-vscode#486]
Olá, 
Somente quando tento utilizar o usuario ADMIN para conectar o VSCODE acontece o erro conforme imagem anexa.
Com qualquer outro usuario ADMINISTRADOR funciona.

Att
Rodrigo Teixeira

**Comment by RodrigoTeixeira-2101** [comment]
![image](https://user-images.githubusercontent.com/65543451/89652766-5cb3b380-d89c-11ea-95d6-4b31d82075a7.png)

**Comment by lwtnb-wrk** [comment]
@RodrigoTeixeira-2101 Para se conectar a um ambiente no tds-vscode é necessário poder se conectar com um smartclient primeiro.
Pela imagem parece que nem pelo smartclient foi possível acessar o Protheus, ou depois desta mensagem você consegue utilizar o Protheus?

**Comment by RodrigoTeixeira-2101** [comment]
Bom dia,

                O acesso ao SIGACFG TAMBEM Não funciona, vou abrir ticket para que a TOTVS avalie.

Para: totvs/tds-vscode <tds-vscode@noreply.github.com>
Cc: Rodrigo Teixeira de Souza <rodrigo.souza@datatraffic.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [totvs/tds-vscode] ERRO conexão usuario ADMIN no ambiente WORKFLOW (#486)


@RodrigoTeixeira-2101<https://github.com/RodrigoTeixeira-2101> Para se conectar a um ambiente no tds-vscode é necessário poder se conectar com um smartclient primeiro.
Pela imagem parece que nem pelo smartclient foi possível acessar o Protheus, ou depois desta mensagem você consegue utilizar o Protheus?

**Comment by lwtnb-wrk** [comment]
@RodrigoTeixeira-2101 Vou fechar esta issue por enquanto, mas caso após restaurar o acesso ao seu ambiente você não conseguir se conectar ao tds-vscode, reabra esta issue.
