### ISSUE TITLE
Erro ao gerar Patch

### ISSUE THREAD

**Issue by pauloamorimtotvs** [totvs/tds-vscode#487]
**Describe the bug**
Criei um fonte customizado. Compilei o fonte no RPO. Apos isto tentei gerar um patch com o fonte criado e é apresentado a seguinte mensagem: "Could not retrieve objects list from RPO." e apos isto o server cai e não consigo gerar o patch.

**To Reproduce**
1 - Crio um fonte novo.
2 - Compilo o fonte no RPO.
3 - Tento criar um patch deste fonte.
4 - Ocorre um erro : "Could not retrieve objects list from RPO." e o server cai sem que consiga gerar o patch.

**Expected behavior**
O patch gerado.

**Desktop (please complete the following information):**
 - OS/Architecture: . Windows 64 bits

**Appserver (please complete the following information):**
Build AppServer: 7.00.191205P-20200424 - 64 bits
Appserver version: 19.3.0.4
Build DBAccess: 20191119-20200217
Release do RPO:  12.1.025
Release do dicionário: 12.1.025
Local files: ctree
License server: 2014 - 2.3.4
DB DataBase: MSSQL
DB API Build: 20191119-20200217

**Comment by lwtnb-wrk** [comment]
@pauloamorimtotvs Este é um problema conhecido desta versão 19.3.0.4 do AppServer na obtenção de dados pelo inspetor de objetos.
Você pode tentar desfragmentar o RPO e/ou reiniciar o AppServer, mas para resolver mesmo será preciso atualizar ou em último caso reverter para a versão anterior do AppServer.
