### ISSUE TITLE
Conection got disposed

### ISSUE THREAD

**Issue by luisfmontes** [totvs/tds-vscode#488]
Quando tento conectar no meu REST ou WS recebo essa mensagem e ele não identifica a BiuldVersion

![Screenshot_2](https://user-images.githubusercontent.com/29053306/89900189-c6dc9900-dbb9-11ea-9254-1d41e137bc39.png)
![Screenshot_1](https://user-images.githubusercontent.com/29053306/89900192-c7752f80-dbb9-11ea-8eb5-4d895912747f.png)

**Comment by lwtnb-wrk** [comment]
@luisfmontes Nao entendi bem o que quis dizer com "tentar se conectar no seu REST".
Seu Appserver esta no 192.168.100.2:1293 mesmo? E consegue se conectar com um Smarclient nesse endereço?
Tambem veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by luisfmontes** [comment]
O appserver roda somente o rest, quando disse conectar foi faze a conexão para poder compilar nele

**Comment by JoseCamilo** [comment]
Boa tarde @lwtnb-wrk , 
Eu e outros colegas de trabalho percebemos que a conexão com serviço de rest parou de funcionar.
Então há algum motivo para isso, ou pode ser algum erro nas atualizações do vscode x plugin? 

Detalhe: o erro relatado acima "Connection got disposed", acontece quando tentamos conectar pela primeira vez no ambiente.
Quando se cria uma conexão com o server sem um serviço rest instanciado, a conexão é estabelecida e a versão do ambiente é preenchida. Mas depois de subir o serviço reste para o mesmo endereço de server, o vscode para de conectar. Estou mandando os logs nos dois cenários.

Segue logs e mensagens do output da ferramenta:
Sem versão "buildVersion":
[log_conexao_sem_versao.zip](https://github.com/totvs/tds-vscode/files/5086240/log_conexao_sem_versao.zip)

![image](https://user-images.githubusercontent.com/19961076/90433214-e08e4c80-e0a1-11ea-918d-c11f614f7e22.png)


Com versão "buildVersion":
[log_Conexao_com_versao.zip](https://github.com/totvs/tds-vscode/files/5086241/log_Conexao_com_versao.zip)

![image](https://user-images.githubusercontent.com/19961076/90433276-fb60c100-e0a1-11ea-83bb-d199626b0715.png)

**Comment by lwtnb-wrk** [comment]
@JoseCamilo Agora com sua explicação detalhada entendi o problema, mas como na situação sem o buildVersion ocorre um erro durante a validação, o LS internamente cai e uma nova instancia é criada. Neste caso os logs enviados não apresentam o erro pois ocorreu o "restart" e o log vem praticamente limpo.
Se possivel adicione alem das configurações de log informada para gerar os logs anteriores, adicione a linha:
        "--log-file-append=totvslsfull.log",
também, pois ela não "zera" e o "totvsfull.log" vem o que ocorreu antes do "restart".
No seu segundo caso com a versão, ocorreu um erro durante a conexão e aparentemente o AppServer não respondeu mesmo.
Pelo log aparentemente trata-se de um LG 17 correto? Favor informar a build exata, pois testei com um 17.3.0.20 aqui e não reproduzi o problema. Subi um Appserver com um serviço REST e não ocorreu o erro "Connection got disposed" aqui.

**Comment by JoseCamilo** [comment]
Boa tarde @lwtnb-wrk , estou com o Appserver version: 17.3.0.16.

Segue os logs:
Sem buildVersion: 
[sembuild-full.zip](https://github.com/totvs/tds-vscode/files/5120000/sembuild-full.zip)

Dessa vez eu mantive o buildVersion em branco e fiz uma conexão no mesmo endereço sem as configurações de rest no ini.
O plugin reconheceu a versão e fez a conexão. Em seguida eu reinicei o serviço com configurações de rest, depois pelo plugin desconectei e tentei uma nova conexão. Segue os logs: 
[AutoBuild-full.zip](https://github.com/totvs/tds-vscode/files/5120010/AutoBuild-full.zip)

Obrigado

**Comment by lwtnb-wrk** [comment]
@JoseCamilo No primeiro log vi que a versão utilizada estava indicando um Appserver 131227 que realmente não iria se conectar.
No segundo log realmente após reiniciar o serviço com as configurações REST o servidor não responde mais.
Não ocorre nenhuma mensagem de erro no console.log do Appserver?
Faça um backup de seu Appserver e atualize-o pois sua versão é um pouco antiga.

**Comment by JoseCamilo** [comment]
@lwtnb-wrk . No primeiro teste, oplugin não deveria ter testado outras versões? Parece que é dessa forma que o plugin encontra a versão no segundo teste, quando o serviço estava sem configurações de Rest.

Sobre minha versão, não adianta eu atualizar localmente ou na base de homologação da minha equipe, pois esta é a versão que a TI da Totvs esta utilizando em produção, entendo que a área toda esta com este problema. A versão nem é tão antiga, apenas o numero de menor versão/hotfix está diferente.

No log do appserver eu recebo esses dois logs na tentativa de conexão do Rest pelo plugin do vscode, dando a entender que recebeu e permitiu a conexão:

`----------         HTTP_ACPT(1700) | 08/25/20 09:47:32 | 8444         ----------

[INFO]Msg...:[Recebida a requisição 'c4ca4238a0b923820dcc509a6f75849b' na thread de processamento 'HTTP Accept']

--------------------------------------------------------------------------------


----------         HTTP_ACPT(1847) | 08/25/20 09:47:50 | 8444         ----------

[INFO]Msg...:[Liberada a thread de controle do HTTP Accept]

--------------------------------------------------------------------------------`


E pelo browse ou request, o serviço é acessado normalmente:
![image](https://user-images.githubusercontent.com/19961076/91177102-a0d6ee80-e6b9-11ea-924b-45d9644342d2.png)

**Comment by JoseCamilo** [comment]
Isso mesmo, o Connection got disposed acontece quando o buildVersion ainda está em branco no servers.json e o plugin faz teste apenas com a versão 131227.

Segue o appserver.ini. Para subir o Rest é só tirar o comentário da seção Rest API: 
[AppServer_7031.zip](https://github.com/totvs/tds-vscode/files/5123974/AppServer_7031.zip)

**Comment by lwtnb-wrk** [comment]
@JoseCamilo Acho que entendi o que está ocorrendo. 
Você está usando a mesma porta utilizada pelo AppServer para subir o serviço REST. 
Não sei se é alguma diferença da versão de meu AppServer mas ele nem deixou eu subir o REST na mesma porta do AppServer.
Apenas troque a porta do AppServer ou do serviço REST. 
Eles apenas não devem utilizar a mesma porta.

**Comment by JoseCamilo** [comment]
Boa @lwtnb-wrk .  Funcionou like a spell.
Este bloqueio da sua versão foi muito útil.

Já pro resto do pessoal que já não está utilizando a mesma porta TCP e HTTPREST, devem verificar se a porta TCP do server também está liberada na regra de rede. Já que a conexão deve ser feita por ela.

Obrigado @lwtnb-wrk
