### ISSUE TITLE
Patch Info tentando buscar o arquivo no server

### ISSUE THREAD

**Issue by jaredtotvs** [totvs/tds-vscode#489]
Bom dia,

Ao realizar um Patch info onde o patch esta na máquina local, mas o servidor protheus conectado esta configurado em outra máquina, a rotina tenta buscar o arquivo patch na minha máquina local mas usando o caminho do RootPath.

Obs: Quando eu realizo o mesmo Patch Info mas conectado em um servidor protheus instalado na máquina local, o problema não acontece e traz as informações do pacote.

Para reproduzir:
1 - Configurar um totvs server protheus no vscode onde o appserver esteja instalado em outra máquina e conectar nele.
2 - Realizar um Patch Info: CTRL + SHIFT + P > TOTVS: Patch Infos
3 - Selecionar um patch localizado na máquina local
4 - Verificar no log do Totvs LS que a rotina tenta buscar o arquivo conforme caminho do RootPath + Pasta com nome do computador local + Arquivo patch

Segue abaixo o log ao fazer o Patch info:
[Info  - 08:55:07] Starting patch info.
[Info  - 08:55:07] Patch file: c:/Users/jared/Downloads/AGRAR630.ptm
[Info  - 08:55:07] Starting build for environment JARED.
[Error - 08:55:11] Patch info could not be executed. Server returned: Patch file C:\TOTVS\PROTHEUS11\Protheus_Data\\tmptdsdesktop-r52rs4n/AGRAR630.ptm not found
[Info  - 08:55:11] Aborting end build (rollback changes).
[Info  - 08:55:11] Patch info finished.

Aqui é onde esta o arquivo na minha máquina local:
[Info  - 08:55:07] Patch file: c:/Users/jared/Downloads/AGRAR630.ptm

Aqui é o caminho do servidor RootPath + Pasta com nome do computador local + Arquivo patch:
[Error - 08:55:11] Patch info could not be executed. Server returned: Patch file C:\TOTVS\PROTHEUS11\Protheus_Data\\tmptdsdesktop-r52rs4n/AGRAR630.ptm not found

Notem que ele inclusive coloca duas barras invertidas aqui:
Protheus_Data\\tmptdsdesktop

Outras informações:
Máquina local - Windows 10 Pro - 64 bits
Máquina onde esta o Protheus server: Windows Server 2016 - 64 bits
Build version Protheus: 7.00.191205P
Plugin Versão 1.0.6

![patch_info](https://user-images.githubusercontent.com/59098572/89906390-546bb900-dbb9-11ea-9b9a-d834a0cf5034.png)

**Comment by lwtnb-wrk** [comment]
@jaredtotvs Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise

**Comment by jaredtotvs** [comment]
@lwtnb-wrk  segue anexo os logs.

[totvsls.log](https://github.com/totvs/tds-vscode/files/5057502/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/5057503/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/5057504/totvsls_out.log)

**Comment by lwtnb-wrk** [comment]
@jaredtotvs Pelo log não observamos nada estranho além do erro apresentado.
Qual a versão do Appserver utilizado? Está atualizado com o 19.3.0.5?? O patch foi gerado para sua versão do Appserver?
Sabemos que existe uma versão anterior do Appserver que emitia um erro de "File not found" quando o patch era incompatível com o Appserver.

**Comment by jaredtotvs** [comment]
@lwtnb-wrk me recordo mesmo deste problema, mas era na aplicação de um pacote. A minha versão é a 19.3.0.5. Também testei nas versões 19.3.0.2 e 19.3.0.4 sem sucesso.

Fiz um teste aqui, gerei um patch conectado no server da outra máquina e salvei o patch na minha máquina local, tentei fazer o Patch Info deste pacote e ele retornou o mesmo problema. Eu entendo que o patch ele reconhece, até porque eu consigo aplicá-lo, mas o Patch Info tenta buscar o arquivo lá no servidor, sendo que ele esta em máquina local.

***  TOTVS S/A  ***
***  www.totvs.com.br  ***
* TOTVS - Build 7.00.191205P - Jun 29 2020 - 21:39:23
* Build: 64 bits
* SVN Revision: 27206
* Build Version: 19.3.0.5

**Comment by jaredtotvs** [comment]
Fiz mais alguns testes, o cliente possui 3 servidores diferentes com Protheus instalado, em dois deles acontece o problema, e em um deles o problema não acontece, são as mesmas versões, pode ser que seja algum bloqueio de firewall. Vou verificar com a equipe de infra deles e fazer também algumas comparações. Vou encerrar esta ISSUE e qualquer novidade com relação ao Plugin, abro outra.

**Comment by lwtnb-wrk** [comment]
@jaredtotvs Grato pelas informações.
Se tiver novidades e/ou descobrir a diferença nesse servidor em que não ocorre o erro, favor postar aqui para que possamos orientar outros usuários.

**Comment by gustavo-krug** [comment]
Olá, estou com o mesmo problema, mas o servidor e o patch estão locais, não em outra máquina.
Pelo que vi no caminho que ele não encontra o patch, ele passa contra barra o caminho todo, mas no trecho da pasta tmptdsjvn019401822 ele usa 2 contra barra e no patch TTTP120.TMP ele passa barra. Além disso, o pacote não está nesse diretório.

![image](https://user-images.githubusercontent.com/45034725/90257963-3eaafd80-de1e-11ea-875f-565a61d07ee3.png)

Fiz um teste colocando o pacote nesse diretório e o patch info retornou as informações. E nesse teste ele mostra no output que pegou do caminho correto do patch
![image](https://user-images.githubusercontent.com/45034725/90258304-b8db8200-de1e-11ea-937f-9eb8370a07f9.png)

**Comment by lwtnb-wrk** [comment]
Somente para informar, esse problema está ocorrendo nos AppServer 19.3.0.5 mesmo e a correção estará disponivel na 19.3.0.6
