### ISSUE TITLE
Exclusão de fontes no RPO.

### ISSUE THREAD

**Issue by Billo21** [totvs/tds-vscode#491]
Não exclui fonte do RPO apresentando erro "End build aborted"

1. Selecione o fonte a ser deletado.
2. Clicar com botão direito do mouse no fonte.
3. utilizar a opção Delete File/Resource from RPO.

O fonte deverá ser excluído do repositório.

![image](https://user-images.githubusercontent.com/69589167/90027591-1640c900-dc8f-11ea-8fd6-ffc31c7d1a91.png)
![image](https://user-images.githubusercontent.com/69589167/90027647-2658a880-dc8f-11ea-845d-439cc9861a54.png)
![image](https://user-images.githubusercontent.com/69589167/90027664-2bb5f300-dc8f-11ea-879d-64520c637837.png)

 - OS/Architecture: [e.g. Windows 64 bits]

 - Build (with date): [e.g. Build 7.00.191205P- Jul 24 2020 - 12:44:07]
 - OS/Architecture: [e.g. Win64 bits Ubuntu]
 - Build Version [e.g. 19.3.0.6_RC7]

Erro só ocorre para fontes customizados, fontes padrões exclui normalmente.

**Comment by lwtnb-wrk** [comment]
@Billo21 Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e no envie os logs para analise.

**Comment by wkve** [comment]
Estou com o mesmo problema, qual a solução??

**Comment by wkve** [comment]
[totvsls.log](https://github.com/totvs/tds-vscode/files/5197436/totvsls.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/5197437/totvsls_out.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/5197438/totvsls_in.log)


> @Billo21 Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e no envie os logs para analise.

Segue logs solicitados

**Comment by lwtnb-wrk** [comment]
@wkve Pelos logs identifiquei que está tentando apagar o fonte GPER130.PRX que parece ser padrão da TOTVS. 
Sem as permissões necessárias isso não é possível e por isso o comando é abortado.

**Comment by wkve** [comment]
Mas aí vem a questão, quanto eu tento compilar o meu fonte utilizando User Function (como sempre fiz sem problemas) estou recebendo a mensagem "Cannot overwrite TOTVS programs (GPER130.PRX)", aí eu fico sem ter oq fazer.

Como devo proceder @lwtnb-wrk ???

[GPER130.zip](https://github.com/totvs/tds-vscode/files/5197646/GPER130.zip)

**Comment by lwtnb-wrk** [comment]
@wkve O programa em questão GPER130.PRX é um fonte padrão TOTVS e deve ser modificado apenas pela TOTVS.
Você deve gerar e trabalhar com seus fontes, caso necessário, e não tentar sobrescrever fontes da TOTVS.

**Comment by wkve** [comment]
@lwtnb-wrk desculpe insistir, mas esse fonte é disponibilizado para download, eu baixei e fizemos alguns pequenos ajustes mais de texto mesmo no cabeçalho do relatório por solicitação do nosso RH e sempre conseguimos compilar desde que alteremos as Functions para User Functions e agora não estou conseguindo mais.

Esse é o meu problema, preciso compilar esse fonte customizado (disponibilizado pela TOTVS para que possamos fazer nossos ajustes) e não estamos conseguindo.

**Comment by lwtnb-wrk** [comment]
@wkve Por curiosidade voce baixou de onde? 
Pelo que vi no "Inspetor de Objetos" esse programa já está em meu RPO padrão e não fui eu quem baixei e compilei.
Uma vez que um programa, por exemplo o GPER130.PRX é compilado pela TOTVS e vem num RPO, ele não pode ser alterado se não for pela própria TOTVS.
Nao sei se em um RPO mais antigo ele não era padrão, mas vi que nos RPO mais atuais ele é padrão então não entendo como voce o está tratando como fonte customizado.

**Comment by wkve** [comment]
Baixei esse fonte daqui https://suporte.totvs.com/portal/p/10098/download?e=947495 já tem tempo que tenho essa customização e de vez em quando, quando faço alguma atualização de acumulados de RH ele para de funcionar pq o menu aponta para a função U_GPER130 e ela deixa de existir no momento da atualização.

Eu baixo novamente o fonte padrão, adiciono no meu projeto, excluo do RPO e recompilo a minha função customizada

**Comment by danielbolognani** [comment]
@wkve Para utilizar esses fontes de relatório é necessário renomear o fonte para poder compilar. Tentar sobrescrever/excluir o fonte padrão do RPO não é possível sem uma chave de compilação válida.
Pode ser que no passado existia algum problema com esse tipo de situação que acabava deixando excluir um fonte padrão mas isso nunca deveria ter ser permitido.

**Comment by lwtnb-wrk** [comment]
@wkve Só pra confirmar, entendeu o que o @danielbolognani informou?
Para customizar seu relatorio voce deve usar o fonte GPER130.PRX como base, mas renomeando para outra coisa.
Em seguida você faz as customizações nesse novo fonte e não deve ter mais problemas.

**Comment by wkve** [comment]
Muito Obrigado, irei tentar dessa forma então @lwtnb-wrk  e @danielbolognani 

Acredito que a situação que estou pegando é a que o @danielbolognani falou, funcionava mas não deveria funcionar a exclusão e corrigiram o bug que eu estava explorando sem saber que era bug.

**Comment by Rmkodama** [comment]
Boa tarde!

Estou tentando excluir dos pontos de entradas MA330SEG e MA330TRB do RPO, mas sempre que que tento abre a aba Delete File from RPO, que é o precedimento.

Consigo debugar, recompilar os pontos de entradas, aplicar Patch, só excluir que não.

**Comment by lwtnb-wrk** [comment]
@Rmkodama Favor abrir uma issue a parte e passar a maior quantidade de informacoes possiveis.
