### ISSUE TITLE
Workspace com caminho de rede

### ISSUE THREAD

**Issue by Robsondpm** [totvs/tds-vscode#492]
**Describe the bug**
Por favor, o VSCODE não reconhece os caminhos de rede para includes e fontes?

**To Reproduce**
Conforme anexo, quando tenho INCLUDE na rede e meus fontes também, ele não reconhece nem o include e nem o caminho dos fontes para compilação. Copiando eles para uma pasta local do computador, reconhece corretamente.
Há alguma configuração para uso na rede? Aqui há vários analistas que utilizam o sistema na rede e fica muito inseguro cada um ter sua versão do fonte localmente em sua máquina.
obrigado.

Version 1.47.3
[Workspace na rede.docx](https://github.com/totvs/tds-vscode/files/5063504/Workspace.na.rede.docx)

**Comment by lwtnb-wrk** [comment]
@Robsondpm Atualmente, realmente não é possível utilizar um caminho de rede diretamente para compilar fontes.
Chegou a tentar mapear o caminho de rede para um drive local e tentar compilar nesse drive?

**Comment by Robsondpm** [comment]
Bom dia,
mapeando o caminho de rede realmente funcionou. Muito obrigado.
