### ISSUE TITLE
Rotina não Compila erro de condição IF ENDIF

### ISSUE THREAD

**Issue by maximinocastro** [totvs/tds-vscode#493]
**Describe the bug**
![log_erro](https://user-images.githubusercontent.com/42280023/90142130-65036700-dd52-11ea-883f-42cc8c2ff226.PNG)
![compilado](https://user-images.githubusercontent.com/42280023/90142131-66349400-dd52-11ea-9bda-c38c7dbdc437.PNG)
![print_code](https://user-images.githubusercontent.com/42280023/90142132-66349400-dd52-11ea-99d5-1a02ea0eac6d.PNG)

Hoje ao tentar compilar o fonte não apresenta erro de sintaxe de IF e ENDIF

Apresenta a mensagem no console como error porém não em problema.

Segue o PRINT

Att.

**Comment by lwtnb-wrk** [comment]
@maximinocastro Pela mensagem no Output foi detectado um erro de compilação "C2003 Syntax Error" mas a linha marcada (-1) é inválida.
Porque acha que o erro seja de If EndIf? Acredito que o erro seja outro. Você tem alguma indicação de que o erro seja esse?
Na fonte não consegui perceber o problema visualmente.
Se conseguir faça um fonte exemplo menor que cause e erro e nos envie esse fonte.

**Comment by maximinocastro** [comment]
Pois eh pela mensagem nem dá pra saber que é porém eu fui comentando todas as minhas condições ai identifiquei que faltava um ENDIF ou seja é um BUG.

E no fonte é Visualmente possivel ver o erro.
![304e8b6d-3096-47d1-893f-ff2642b7c86a](https://user-images.githubusercontent.com/42280023/90144966-d98bd500-dd55-11ea-9d61-4f4204639a45.jpg)

**Comment by lwtnb-wrk** [comment]
@maximinocastro Como você recortou a imagem de um pedaço do seu fonte eu realmente não saberia dizer se tem mais linhas abaixo do recorte com um EndIf...

Enfim fiz um teste aqui e nos meu Appservers (LG 19, LG 17 e um NG) ocorreram um erro se eu não colocar um EndIf e mostra a linha com o If sem o EndIf com a mensagem "C2024  Unclosed control structures".

![image](https://user-images.githubusercontent.com/49563478/90147140-3f795c00-dd58-11ea-943f-b273101d2c4d.png)

Informe as versões de deu Appserver e envie seu fonte com problema para que possamos verificar o que está ocorrendo nele.

**Comment by maximinocastro** [comment]
Segue o codigo
[CALCFRTBRA copy.zip](https://github.com/totvs/tds-vscode/files/5069674/CALCFRTBRA.copy.zip)

**Comment by lwtnb-wrk** [comment]
@maximinocastro E quanto as informações de seu Appserver? Alem disso veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

Aqui o seu fonte deu o mesmo erro, porém marcou a linha indicando pelo menos um ponto para análise

![image](https://user-images.githubusercontent.com/49563478/90149344-c4657500-dd5a-11ea-86c2-09545d3e84da.png)

**Comment by maximinocastro** [comment]
Estranho que pra mim não retornou essa informação. A versão do plugin do VsCode 1.0.6 ? 

Dados do Server 

Versão: TOTVS Serviços
Build AppServer: 7.00.170117A-20190628 - 64 bits
Build DBAccess: 20181212
Release do RPO:  12.1.025
Release do dicionário: 12.1.025
Ambiente: Producao
Local files: ctree
License server: 2014
DB DataBase: MSSQL7

Dados da LIB

Versão da Lib:20190705
Data da Lib: 20190712_17270
Commit ID:37444b688b467b5fd60b7a1629a57747e2fac8ef

**Comment by lwtnb-wrk** [comment]
@maximinocastro Versão 1.0.6 tambem.
Seu Appserver parece um pouco antigo. Faça um backup e experimente atualiza-lo para ver se o comportamento muda.

**Comment by Redschenko** [comment]
Reproduzi o mesmo problema usando o Appserver 19.3.0.5.
Não apresenta erro na aba Problems, porém apareceu nas notificações.

![image](https://user-images.githubusercontent.com/21147378/90176843-ffc66a80-dd7f-11ea-81c3-51bcf58ae57d.png)

**Comment by supacotelha** [comment]
Aqui pra mim com esse mesmo fonte não aparece o erro na aba problems, na aba output e nas notificações sim.

Versão do plugin da totvs: 1.0.6

Dados do VSCode:
Version: 1.48.0
Date: 2020-08-13T07:50:42.600Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by lwtnb-wrk** [comment]
@maximinocastro @Redschenko @supacotelha Somente para atualiza-los ontem não percebi mas estava com as configurações de multiprotocolport desabilitadas...
MultiProtocolPort=0
MultiProtocolPortSecure=0
Com essa configuração habilitada (ou se não estiverem desabilitadas explicitamente, pois por default estão habilitadas) o erro é o apresentado mesmo "C2003 Syntax Error" na linha (-1).
De qualquer forma trata-se de um problema no Appserver que emite este erro e apenas apresentamos na visão Output, porém não estamos apresentando quando a linha é a -1 (inexistente).
Enfim faremos um tratamento para pelo menos exibir o problema mesmo que seja na linha 1, pois não teremos esta informação do Appserver de qualquer forma.

**Comment by brodao** [comment]
Encerrado pois o problema é gerado pelo servidor Protheus.
