### ISSUE TITLE
Debugar Paginas APH

### ISSUE THREAD

**Issue by nuncherino** [totvs/tds-vscode#494]
Bom dia 
Não estou conseguindo mais debugar uma pagina APH
Estou usando o Chrome, no VS estou com MultThread igual a SIM, chamo o debug com um Alert"teste") e mesmo assim ele nao para mais nos pontos de parada.

**Comment by lwtnb-wrk** [comment]
@nuncherino Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise, especialmente o dap.log.
Informe também as versões dos builds e mais dados sobre seu Appserver.

**Comment by brodao** [comment]
Ola @nuncherino 

Veja se o chamado #513 ajuda.

A disposição.

**Comment by brodao** [comment]
Encerrado por falta de retorno.
