### ISSUE TITLE
Inspetor de Objetos nao exibe a lista de fontes existentes no RPO

### ISSUE THREAD

**Issue by willmr** [totvs/tds-vscode#495]
Verifiquei que apos as ultimas atualizações Binarios X LIB X DBAcess o VSCODE nao consegue mais gerar o arquivo e nem exibir os fontes do RPO, Inspetor de Objetos fica apenas processando e nao exibi nada.

Ja recriei os ambientes, e mesmo assim o inspetor nao funciona, o resto esta funcionando normalmente, consigo debugar, compilar descompilar fonte tudo normal.

Aguardo retorno

Obrigado

**Comment by lwtnb-wrk** [comment]
@willmr Provavelmente deve ser o mesmo problema de #415 
Se nao for isso veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs e informacoes do appserver para analise

**Comment by willmr** [comment]
Obrigado realmente eu troquei o APP para uma versão mais antiga e funcionou.

 

Vou aguardar a nova versão obrigado

 

Att

 




William Martão Rodrigues





 <mailto:william.rodrigues@mrconsultoria.com.br> william.rodrigues@mrconsultoria.com.br





+55 11 3740-2200 



 <http://www.mrconsultoria.com.br/> www.mrconsultoria.com.br


 <http://www.mrconsultoria.com.br/> 


 <https://www.facebook.com/MRConsultoria>   <https://www.linkedin.com/company/mr-consultoria/>   <http://www.instagram.com/mrcgestaodeti> 

 

 

De: lwtnb-wrk [mailto:notifications@github.com] 
Enviada em: segunda-feira, 17 de agosto de 2020 11:42
Para: totvs/tds-vscode <tds-vscode@noreply.github.com>
Cc: willmr <william.rodrigues@mrconsultoria.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [totvs/tds-vscode] Inspetor de Objetos nao exibe a lista de fontes existentes no RPO (#495)

 

@willmr <https://github.com/willmr>  Provavelmente deve ser o mesmo problema de #415 <https://github.com/totvs/tds-vscode/issues/415> 
Se nao for isso veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs e informacoes do appserver para analise
