### ISSUE TITLE
Análise de includes faltantes/desnecessários

### ISSUE THREAD

**Issue by ChristianPrado** [totvs/tds-vscode#496]
Seria ótimo se a extensão apontasse includes que estão faltando ou desnecessários.
Existe uma extensão que já faz isso, mas como não é oficial, creio que seria interessante trazer de forma nativa.

**Comment by lwtnb-wrk** [comment]
@ChristianPrado Qual extensão faz isso? Podemos avaliar essa inclusão ou se alguem quiser pode submeter uma Pull Request com essa nova feature na nossa extensão.

**Comment by ChristianPrado** [comment]
Segue o link da extensão que mencionei (ADVPL Análise, Snippets e GIT):
<https://marketplace.visualstudio.com/items?itemName=robsonrosilva.advpl-sintaxe>

Ela faz várias análises na verdade , visando padrões de qualidade, mas como mencionei, seria bom ter essas informações disponibilizadas pela extensão oficial.
Ela também está aqui no GitHub: <https://github.com/robsonrosilva/advpl-sintaxe>

**Comment by ricardomansano** [comment]
Bom dia @ChristianPrado 

Estamos trabalhando no Linter neste 1o semestre, ele vai acusar Includes que "estejam faltando", porém os desnecessários são ignorados pelo proprio compilador, e não devolvem qualquer informação pra IDE, impossibilitando que possamos informar isso.

Até Julho devemos ter essa liberação conluida

**Comment by danielbolognani** [comment]
Bom dia @ChristianPrado. subimos ontem no MarketPlace a versão 1.3.0 da extensão que conta com o Linter. Com isso, includes faltantes serão avisados antes mesmo da compilação no appserver.
