### ISSUE TITLE
Problema ao compilar Pasta

### ISSUE THREAD

**Issue by murilocleandro** [totvs/tds-vscode#498]
Estou com problema ao compilar uma pasta, o VS compila alguns fontes e outros não. Os Fontes não possuem erros, se for individualmente nos fontes da certo.

**Comment by DanielYampolschi** [comment]
ola @murilocleandro , testei por aqui e não consegui reproduzir esse problema, você pode dar mais informações, com print screen. Alem disso veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise por favor.

**Comment by murilocleandro** [comment]
No meu caso na aba saída, o fonte aparece que como SKIPPED porém o mesmo não existe no RPO e ele tambem não compila

**Comment by brodao** [comment]
Ola @murilocleandro 

Ao compilar por pasta, somente os arquivos que foram modificados são compilados. Se quiser forçar a compilação de tudo, use "Recompilar" (`<tecla alt> + <menu contexto pasta>`.

A disposição.
