### ISSUE TITLE
Generate WS Protheus: variáveis com mais de 10 caractéres.

### ISSUE THREAD

**Issue by brunommalmeida** [totvs/tds-vscode#499]
Boa tarde!

Hoje nós temos integração com um web service soap de terceiro em nossa empresa, via web service protheus Advpl, ou seja, nosso web service protheus consome esse web service terceiro.
A referência WSDL gerada tanto pelo VS Code está gerando variáveis com mais de 10 caractéres. Na nossa versão atual do Protheus, não ocorre nenhum problema, o advpl entende cada variável normalmente.
Contudo, na última atualização que fizemos, de binários e lib - que são as últimas disponibilizadas no Portal -, o fonte advpl está considerando os 10 primeiros caractéres.
Então gostaríamos de saber, como devemos proceder diante desse problema? Visto que a referência WSDL é gerada automaticamente pelo plugin da TOTVS no VSCode.

Essa função de gerar o WSDL não deveria levar em conta a limitação do tamanho de variável do ADVPL?

Obrigado!

**Comment by brodao** [comment]
@brunommalmeida 

A geração do WSDL cliente é efetuado pelo appServer. O VSCode apenas é uma interface de solicitação.
Favor entrar em contato com o suporte de servidores Protheus.

A disposição.
