### ISSUE TITLE
Salvar senha do ambiente

### ISSUE THREAD

**Issue by likid** [totvs/tds-vscode#5]
Gostaria de sugerir a criação de uma opção para salvar o usuário e a senha do ambiente como já existe no TDS baseado no eclipse atualmente.

**Comment by matheus-sales** [comment]
No primeiro momento que discutimos sobre o assunto, decidimos não salvar senhas por questões de segurança. Mas vamos rever o processo. Vou discutir com a equipe e analisar a solicitação. 

Obrigado @likid

**Comment by likid** [comment]
Entendo a questão de segurança @matheus-sales mas como seria algo opcional, poderiam criar uma chave de encriptação proprietária de vocês e utilizá-la no debugAdapter para repassar a senha decriptada para o appserver e isso seria por conta e risco do utilizador. Não conheço o funcionamento interno dos processos mas deixo aqui apenas uma sugestão baseada em suposições minhas. Obrigado.

**Comment by fabinajm** [comment]
Usa o password cipher como a versão feita fora da totvs.

**Comment by likid** [comment]
@matheus-sales @lwtnb-wrk fiz a atualização agora, mas ao alternar entre um ambiente e outro o vscode ainda está pedindo a senha novamente do ambiente. Há alguma opção que deva ser ativada para salvar a senha?

**Comment by matheus-sales** [comment]
@likid implementamos somente na reconexão. Quando há troca de servidor, não salvamos. Mas faremos. Já reabri a tarefa.

**Comment by lwtnb-wrk** [comment]
@likid implementada a salva de senhas por ambiente. 
Deve estar disponivel a partir da proxima liberacao.

**Comment by alexandredalpiaz** [comment]
Boa noite
@likid, esta atualização de gravação de senhas foi feita?
Se foi, como faz pra configurar isso?

Obrigado,

**Comment by likid** [comment]
> Boa noite
> @likid, esta atualização de gravação de senhas foi feita?
> Se foi, como faz pra configurar isso?
> 
> Obrigado,

Foi feita sim e é feita automaticamente.

**Comment by edvarwv** [comment]
> > Bom dia, tudo bem ?
> > [@likid](https://github.com/likid), esta atualização está ativa ? 
> > Pois não está sendo feita automaticamente, a cada conexão de ambiente é necessário sempre informar login e senha, mesmo com eles salvos no servers.json
> > Obrigado,

**Comment by brodao2** [comment]
@edvarwv 

Pode ser mais específico.

**Comment by edvarwv** [comment]
> [@edvarwv](https://github.com/edvarwv)
> 
> Pode ser mais específico.

Como vai, tudo bem ?

Ao criar um servidor no vscode colocamos usuario e senha para primeiro acesso, ok ?
Porém ao fechar e abrir o vscode ou mesmo desconectar o servidor,  e tentar nova conexão, é solicitado novamente usuario e senha.
O que estou comentando é que poderia ser feita a conexão automatica, ao invés de sempre precisar informar login e senha

Obrigado

**Comment by lwtnb-wrk** [comment]
@edvarwv A opção de "Reconectar" usa as informações anteriores de usuario/senha usadas ao "Conectar".
