### ISSUE TITLE
Compilação de arquivos/pastas selecionadas

### ISSUE THREAD

**Issue by eurairapelli** [totvs/tds-vscode#50]
Boa noite,

Analisar possibilidade de adicionar opção de compilar arquivos/pastas selecionadas com shift/ctrl.

Att

**Comment by lwtnb-wrk** [comment]
@eurairapelli O VSCode não fornece para o plugins a informação de quais arquivos estão selecionados. Assim não conseguimos saber quais são os arquivos que deverão ser compilados. Segue issue aberta para a disponibilização desta funcionalidade no VSCode: https://github.com/Microsoft/vscode/issues/3553 Somente apos esta implementacao no VSCode poderemos implementar tal funcionalidade no tds-vscode.

**Comment by matheus-sales** [comment]
> @eurairapelli O VSCode não fornece para o plugins a informação de quais arquivos estão selecionados. Assim não conseguimos saber quais são os arquivos que deverão ser compilados. Segue issue aberta para a disponibilização desta funcionalidade no VSCode: [microsoft/vscode#3553](https://github.com/microsoft/vscode/issues/3553) Somente apos esta implementacao no VSCode poderemos implementar tal funcionalidade no tds-vscode.

Em complemento ao que o @lwtnb-wrk disse: A seleção deve sempre ser única. Caso selecione uma pasta, todos os fontes da pasta serão compilados.

Mas selecionar múltiplos arquivos será compilado apenas o primeiro selecionado por conta da limitação acima.

**Comment by matheus-sales** [comment]
@eurairapelli Encontramos uma forma de pegar os itens selecionados. Subimos a correção e vamos rever os itens que fechamos por causa desse motivo. A compilação de vários arquivos está funcionando.

**Comment by carloseniemeyer** [comment]
Pessoal isso foi implementado nas novas releases do TDS VsCode?
Existe alguma maneira hoje para compilar arquivos e/ou pastas selecionadas?
Existe alguma forma de criar uma pasta virtual com arquivos pré-definidos de uma determinada branch para compilar todos de uma vez?

**Comment by brodao2** [comment]
Favor ler [Compilando arquivos não abertos para edição ou pastas](https://github.com/totvs/tds-vscode/blob/master/docs/compilation.md#compilando-arquivos-n%C3%A3o-abertos-para-edi%C3%A7%C3%A3o-ou-pastas) e [Multiselection](https://code.visualstudio.com/docs/getstarted/userinterface#_multiselection).
