### ISSUE TITLE
Erro Invalid function type ao utilizar o TDS Replay 2.0

### ISSUE THREAD

**Issue by Redschenko** [totvs/tds-vscode#500]
**Describe the bug**
Ao utilizar o TDS Replay, sistema apresenta erro
Invalid function type. Please check RPO file: TDSREPLAY on { ||   TDSREPLAY( .F. ) }(FWLOGPROFILER.PRW) 24/07/2020 17:50:50 line : 125
Apesar do erro, é gerado um arquivo .trplay no smartclient

**To Reproduce**
1. Acessar qualquer rotina
2. Ativar gravação do TDS Replay (Shift+F6)
3. Realizar qualquer operação (Ex: Visualizar registro)
4. Desativar gravação do TDS Replay (Shift+F6)
5. Erro é reproduzido

**Expected behavior**
O sistema deve concluir a gravação sem erros.

**Screenshots**
![Screenshot_153](https://user-images.githubusercontent.com/21147378/90895736-f731ed80-e398-11ea-8964-88155c069c62.png)

**Desktop (please complete the following information):**
 - OS/Architecture: Windows 10/64 bits (Compilação 19041.329)

**Appserver (please complete the following information):**
 - Build (with date): Build 7.00.191205P - Jul 24 2020 - 12:44:07
 - OS/Architecture: Windows Server 2012/64 Bits (Build 9200)
 - Build Version 19.3.0.6_RC7

**Additional context**
*Dados do Server*
Versão: TOTVS Manufatura
Build AppServer: 7.00.191205P-20200724 - 64 bits
Appserver version: 19.3.0.6_RC7
Build DBAccess: 20191119-20200706
Release do RPO:  12.1.025
Release do dicionário: 12.1.025
Local files: CTREE
License server: 2014 - 3.1.7
DB DataBase: MSSQL
DB API Build: 20191119-20200116
Dicionário no banco de dados: Não

*Dados do Remote*
Remote build: 7.00.191205P-20200714
Remote version: 19.3.0.9
Remote type: 1 - QT-5.14.0 WIN
Módulo: FAT
Nome do computador: 100-0341
Sistema operacional: Windows 10 - 
Memória: 16328
Processador: Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz

*Versão da Lib:20200727*
Data da Lib: 20200724_145022
Commit ID:53bad24e7e9bcd93df2e312ab36735b6d78d9590

**Segue em anexo:**
- Vídeo demonstrando o problema
- Console.log do AppServer
- Dados do ambiente
- error.log gerado
- arquivo replay gerado

[2008211029.zip](https://github.com/totvs/tds-vscode/files/5109061/2008211029.zip)

**Comment by DanielYampolschi** [comment]
Ola @Redschenko , antes de mais nada, obrigado por ter aberto a issue. 

Esse problema está na lib do protheus. Na realidade, já tinhamos pego e passado pro time de framework o qual já fez a correção... e ainda estamos estressando os testes pra evitar que esse tipo de situação ocorra novamente.... 

ainda não sei quando estará disponível pra baixar o patch... mas vou verificar isso e já informo aqui.

E peço desculpas por esse transtorno, nessa fase de RC ainda estamos lidando com algumas situações.

**Comment by DanielYampolschi** [comment]
@Redschenko a versão da lib do framework que terá essa correção é a 20200908.
Não tem nada que podemos fazer, do lado do VsCode para contornar isso.
Por favor aplique o patch quando ele estiver disponível e verifique se você consegue fazer uma gravação.
Vou encerrar essa issue, mas caso volte a ter problema, basta reabri-la ok?
Se preferir, como é algo relacionado ao TDS Replay, pode me chamar direto pelo Google Chat para conversarmos melhor.
