### ISSUE TITLE
Erro Access Violation in function TCBROWSE:BRLOGICLEN on ::MSSELBR:BRLOGICLEN ao utilizar o TDS Replay 2.0

### ISSUE THREAD

**Issue by Redschenko** [totvs/tds-vscode#501]
**Describe the bug**
Ao alterar o itens de um pedido na rotina de Embarque (EECAE1010) com o TDS Replay ativado, o sistema apresenta o erro:
Access Violation in function TCBROWSE:BRLOGICLEN on ::MSSELBR:BRLOGICLEN

**To Reproduce**
1. Veja o passo a passo no vídeo contido no arquivo em anexo

**Expected behavior**
O sistema deve iniciar e concluir a gravação sem erros.

**Screenshots**
![Screenshot_153](https://user-images.githubusercontent.com/21147378/90898630-35311080-e39d-11ea-9828-5dbf53859914.png)

**Desktop (please complete the following information):**
 - OS/Architecture: Windows 10/64 bits (Compilação 19041.329)

**Appserver (please complete the following information):**
 - Build (with date): Build 7.00.191205P - Jul 24 2020 - 12:44:07
 - OS/Architecture: Windows Server 2012/64 Bits (Build 9200)
 - Build Version 19.3.0.6_RC7

**Additional context**
*Dados do Server*
Versão: TOTVS Manufatura
Build AppServer: 7.00.191205P-20200724 - 64 bits
Appserver version: 19.3.0.6_RC7
Build DBAccess: 20191119-20200706
Release do RPO:  12.1.025
Release do dicionário: 12.1.025
Local files: CTREE
License server: 2014 - 3.1.7
DB DataBase: MSSQL
DB API Build: 20191119-20200116
Dicionário no banco de dados: Não

*Dados do Remote*
Remote build: 7.00.191205P-20200714
Remote version: 19.3.0.9
Remote type: 1 - QT-5.14.0 WIN
Módulo: FAT
Nome do computador: 100-0341
Sistema operacional: Windows 10 -
Memória: 16328
Processador: Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz

Versão da Lib:20200727
Data da Lib: 20200724_145022
Commit ID:53bad24e7e9bcd93df2e312ab36735b6d78d9590

**Segue em anexo:**
- Vídeo demonstrando o problema
- Console.log do AppServer
- Dados do ambiente
- error.log gerado

[2008211101.zip](https://github.com/totvs/tds-vscode/files/5109217/2008211101.zip)

**Comment by DanielYampolschi** [comment]
Ola @Redschenko esse erro tambem esta relacionado com o problema da lib onde informei na issue #500 . 
Vou encerrar essa issue e acompanhamos por la pra facilitar ok.
Obrigado.
