### ISSUE TITLE
Includes configuradas e não consigo compilar classes ou webservices.

### ISSUE THREAD

**Issue by evicentin** [totvs/tds-vscode#502]
Boa tarde.

Configurei as includes globalmente e no server que estou usando, mesmo assim não consigo compilar rotinas que não sejam do tipo "User Function".

Criei uma classe de objetos e um webservice REST, ambos não compilam. Retorna a mensagem abaixo:
"functions are not allowed in code." Use USER FUNCTION ou STATIC FUNCTION."

Alguém sabe me dizer o que pode estar ocorrendo?

Grato.

**Comment by DanielYampolschi** [comment]
Ola @evicentin, esse tipo de problema pode ocorrer se em algum momento, você adicionou uma chave de compilação e compilou esse fonte usando essa chave. Dali pra frente, mesmo que seja "user function", voce vai precisar usar uma chave de compilação. 

Para contornar esse problema você pode tentar adicionar uma chave de compilação no eu ambiente, remover o fonte do RPO, remover a chave de compilação e compilar novamente essa user function..

Essa situação é comandada pelo servidor e não tem nada que podemos fazer quanto a isso, se for esse realmente o seu caso.

**Comment by evicentin** [comment]
Daniel, bom dia.

Eu não adicionei chave de compilação. Nunca usei isso em meu ambiente.

O que notei é que estou usando a build 19, não sei se isso tem alguma relação, mas nas versões anteriores eu consigo compilar, nessa versão de build não está indo.

At.
Ewerton Vicentin

De: DanielYampolschi<mailto:notifications@github.com>
Enviado:segunda-feira, 24 de agosto de 2020 10:32
Para: totvs/tds-vscode<mailto:tds-vscode@noreply.github.com>
Cc:Ewerton Vicentin<mailto:ewertonalex@hotmail.com>; Mention<mailto:mention@noreply.github.com>
Assunto: Re: [totvs/tds-vscode] Includes configuradas e não consigo compilar classes ou webservices. (#502)


Ola @evicentin<https://github.com/evicentin>, esse tipo de problema pode ocorrer se em algum momento, você adicionou uma chave de compilação e compilou esse fonte usando essa chave. Dali pra frente, mesmo que seja "user function", voce vai precisar usar uma chave de compilação.

Para contornar esse problema você pode tentar adicionar uma chave de compilação no eu ambiente, remover o fonte do RPO, remover a chave de compilação e compilar novamente essa user function..

Essa situação é comandada pelo servidor e não tem nada que podemos fazer quanto a isso, se for esse realmente o seu caso.

**Comment by brodao** [comment]
@evicentin 

Veja se o chamado #511 ajuda.

A disposição.

**Comment by brodao** [comment]
Encerrado por falta de retorno.
