### ISSUE TITLE
Error user must be logged in before compile, 1.0.6 - AppSever  Build Version: 19.3.0.5

### ISSUE THREAD

**Issue by gabrielregatta** [totvs/tds-vscode#503]
Não consigo compilar fontes após atualização da appsever  Build Version: 19.3.0.5.

**Screenshots**
![image](https://user-images.githubusercontent.com/70148827/91051687-d666d380-e5f6-11ea-8e08-08dd3d92f313.png)

 -  TOTVS - Build 7.00.191205P - Jun 29 2020 - 21:39:23
 - Windows Server 2016 [Version 10.0.14393]
 - Build Version [e.g. 17.3.0.13]

**Comment by jevsoftwares** [comment]
Também estou com este problema sendo a mesma versão da build.

**Comment by DanielYampolschi** [comment]
Ola @gabrielpmanzoni por favor tente refazer sua configuração de de servidores conforme os passos abaixo:

1 - Na visao de servidores, clique no icone da engrenagem para abrir o arquivo servers.json.
2 - Copie todo o conteudo e cole em um arquivo de backup.
3 - Apague todo o conteudo do arquivo servers.json e salve-o
4 - Reincie o VSCode
(Caso apareca um erro do tipo: Cannot read property 'for each' of undefined, simplesmente ignore)
5 - Adicione um novo servidor e tente logar novamente.

Caso consiga logar, simplesmente copie as suas configurações de includes globais ou do servidor do backup caso nao tenha adicionado.

Caso continue dando problema por favor veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs e informacoes do appserver para analise

**Comment by josuelsilva** [comment]
Boa tarde,
Estou com o problema parecido.
Fiz o procedimento acima e consigo compilar apenas 1 fonte por vez.
Se escolho compilar os fontes de uma determinada pasta ele faz o processo de compilação mais não sobe para o RPO ao termino.

**Comment by brodao** [comment]
Ola @josuelsilva 

Por padrão, a compilação somente é efetuada se houver alterações no fonte. Para forçar a compilação, acione a tecla ALT + menu de contexto.

A disposição

**Comment by josuelsilva** [comment]
@brodao acebei descobrindo o que estava ocorrendo.
Era um erro numa rotina que estava alterando uma variável definida como DEFINE.

Ao compilar todos os fontes, dava erro nessa rotina e ao final da compilação estava sendo executado um rollback.

Obrigado mesmo assim m
Grato.
