### ISSUE TITLE
Visual Studio não está compilando

### ISSUE THREAD

**Issue by jevsoftwares** [totvs/tds-vscode#504]
Issue Type: <b>Bug</b>

Até na sexta feira estava compilando normalmente o através do VS Code e hoje não está mais compilando. Não pede o usuário e senha para acessar o servido e também ao compilar não permite dezendo que usuário não tem acesso para compilar.
![image](https://user-images.githubusercontent.com/65028697/91072715-e9ce6a80-e607-11ea-993c-91d3addb8f2d.png)

Extension version: 1.0.6
VS Code version: Code 1.48.1 (3dd905126b34dcd4de81fa624eb3a8cbe7485f13, 2020-08-19T17:12:13.244Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (3.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by DanielYampolschi** [comment]
Ola @jevsoftwares , o problmea de compilação esta realmente relacionado ao fato de você nao conseguir fazer o login. Faça um teste por favor....

1 - Na visao de servidores, clique no icone da engrenagem para abrir o arquivo servers.json.
2 - Copie todo o conteudo e cole em um arquivo de backup.
3 - Apague todo o conteudo do arquivo servers.json e salve-o
4 - Reincie o VSCode
(Caso apareca um erro do tipo: Cannot read property 'for each' of undefined, simplesmente ignore)
5 - Adicione um novo servidor e tente logar novamente.

Caso consiga logar, simplesmente copie as suas configurações de includes globais ou do servidor do backup caso nao tenha adicionado.

Caso continue dando problema por favor  veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs e informacoes do appserver para analise

**Comment by jevsoftwares** [comment]
Boa noite, fiz isso e somente puxou o login, mas a cor do server permanece anormal e apesar de mostrar compilando o script não está gravando no .rpo, sendo que está com as permissões de gravação sendo:

[TDS]
AllowApplyPatch=*
AllowEdit=*

. Segue imagens:

![image](https://user-images.githubusercontent.com/65028697/91124982-917e8380-e66e-11ea-9c8f-b5f0b43624d7.png)
![image](https://user-images.githubusercontent.com/65028697/91125010-a5c28080-e66e-11ea-96c5-20548d7dccab.png)
![image](https://user-images.githubusercontent.com/65028697/91125077-dc000000-e66e-11ea-8ea4-574c4c76852d.png)

para testar, fiz a instalação do zero do vscode em uma máquina na mesma rede e mesma forma:
![image](https://user-images.githubusercontent.com/65028697/91125261-5d579280-e66f-11ea-8fe9-cd3112889da5.png)
![image](https://user-images.githubusercontent.com/65028697/91125352-8aa44080-e66f-11ea-814a-39f4b73a0a88.png)

No ano passado ocorreu da mesma forma em outro cliente e resolveu apenas com atualização enviado para vscode. Não sei o que é mas tenho certeza que da forma que sempre faço continuo.

**Comment by jevsoftwares** [comment]
Segue os Log com Ip removido por segurança.
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/5124144/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/5124145/totvsls_out.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/5124146/totvsls.log)

**Comment by DanielYampolschi** [comment]
@jevsoftwares desculpe, mas não entendi sua resposta. Você informa que a cor do server está anormal, porém no print está mostrando na cor verde, que é a informação visual de que uma conexão foi realizada com sucesso. 

Nas imagens do consoleLog, na última linha mostra a Thread do Job finalizada com o nome do fonte e a quantidade de linhas (... JOB Thread finished [-PSWADMIN] IMPXMLDES.PRW:252) indicando que o fonte está no RPO.

Você pode confirmar se a compilação realmente ocorre da seguinte forma:
 Faça uma alteração qualquer no fonte (adicionando uma linha em branco por exemplo) e compile-o.
 Abra o inspetor de objetos, procure pelo fonte e verifique se a data de compilação dele está atualizada.

Os logs que você enviou também mostram uma operação normal.

**Comment by jevsoftwares** [comment]
![image](https://user-images.githubusercontent.com/65028697/91187012-b1896380-e6bd-11ea-9953-108ff976b82c.png)

**Comment by jevsoftwares** [comment]
Desinstalei e instalarei novamente o VS Code do zero e agora deu certo. Obrigado.
