### ISSUE TITLE
User not authenticated debug advpl

### ISSUE THREAD

**Issue by fabricioprete** [totvs/tds-vscode#505]
Bom dia!

Ao tentar debugar via vscode, me aparece esta mensagem do título, porém mesmo com ambiente já conectado, compilo normal, gero inspetor de objetos, etc, sem problema nenhum. Apenas para debugar que ocorre esta mensagem.

Já exclui ambiente, incluí novamente, apaguei usuários salvos no servers.json, apaguei e reconfigurei o launch.json e nada dá certo.
Isso ocorre independente a versão do binário de appserver/smartclient.

Espero que já exista alguma solução rs Já vi que podia ser o nome do usuário da máquina que tem acento, e no meu tem no primeiro "i" > Fabrício. 
Já vi que tiveram alguns tickets relacionados à este assunto, mas não encontrei a solução na ferramenta.
Podem me dizer se existe esta correção?

**Comment by DanielYampolschi** [comment]
Ola @fabricioprete na issue não veio o print com a mensagem que aparece, isso pode acontecer se você abriu a issue por e-mail.

Quanto ao acento no caminho, é provável que seja esse o problema sim, pois esse é uma situação conhecida conforme relatado na issue #423 e documentado em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#usu%C3%A1rio-com-acentua%C3%A7%C3%A3o

Ainda não temos uma previsão para corrigir esse comportamento, então sugiro que coloque seus fontes em uma pasta que não contenha acento e que também nenhuma outra do caminho dessa última tenha acentuação. 

Vou encerrar a issue, porém caso você tenha problema para debugar mesmo após alterar a pasta, pode reabri-la sem problemas. 

Muito obrigado.

**Comment by fabricioprete** [comment]
Daniel, eu instalei o vscode na minha unidade D, porém ele grava a pasta com as extensões no C:Username..Onde está instalado o programa, ele não tem nenhuma pasta nomeada com acento.

Segue a imagem.
Instalei por último o vscode-insiders pra ver se resolvia, mas permaneceu.

![image](https://user-images.githubusercontent.com/70180911/91183676-2363ac00-e6c2-11ea-9391-47d9f8d25dae.png)

Att,
Fabricio Del Prete
![USER_not_Auth](https://user-images.githubusercontent.com/70180911/91183495-ed262c80-e6c1-11ea-93be-8002591e33ee.png)

**Comment by DanielYampolschi** [comment]
Ola @fabricioprete , desculpa a demora... estávamos tentando buscar uma solução melhor pois o problema realmente está relacionado ao acento no nome do usuário pois algumas informações são gravadas na área de usuário do SO. 

Essa questão ainda vai levar mais tempo para ser resolvida e a única solução que temos hoje para isso é criar um novo usuário sem acentuação no nome mesmo.

**Comment by fabricioprete** [comment]
Ok, Daniel!

Para solução eu já fiz isso mesmo, espero que tão logo possam solucionar.

Obrigado pelo retorno.

Att,

Fabricio Del Prete


Em qui., 10 de set. de 2020 às 09:58, DanielYampolschi <
notifications@github.com> escreveu:
