### ISSUE TITLE
VsCode não identifica erro de sintaxe do BeginSql

### ISSUE THREAD

**Issue by gtrabach** [totvs/tds-vscode#506]
Bom dia!

O VsCode não identifica erros de sintaxe ao utilizar o BeginSql, como por exemplo, ao esquecer de informar a cláusula EndSql. Em anexo vídeo evidência.

[vscode_beginsql.zip](https://github.com/totvs/tds-vscode/files/5123768/vscode_beginsql.zip)

Perceba que é gerada uma mensagem de alerta na aba Output, mas na aba Problems não é informado nenhum problema. Além disso o arquivo não fica vermelho informando que existe um erro de compilação.

Eu forcei um erro de compilação informando uma "/" dentro do If e esse erro o VsCode identificou normalmente, exibindo em Problems e pintando o arquivo de vermelho.

Versão do AppServer: 19.3.0.4
Versão do Plugin do TDS: 1.0.6
Versão do VsCode: 1.48.1

**Comment by DanielYampolschi** [comment]
Ola @gtrabach , primeiramente, muito obrigado por ter gravado o vídeo demonstrando a situação, ajuda muito mais na analise da situação.

Eu consegui reproduzir seu problema com a mesma versão do plugin que você mostrou. 
Porém testando com o plugin em runtime, o problema não reproduz mais, portanto essa situação já foi corrigida e estará disponível na próxima atualização.

E apenas uma informação sobre detecção de erros. Eles acontecem em momentos diferentes... Alguns são detectados pelo próprio parser do plugin, gerando a informação de problema quase instantaneamente e outros só são detectados pelo compilador, obviamente gerando o erro apenas após a compilação. O parser do plugin, tende a ser mais simples que o parser do compilador por questões de performance.
