### ISSUE TITLE
DEBUG VISUAL STUDIO COM IMPRESSORA NAO FISCAL

### ISSUE THREAD

**Issue by wbarreto1** [totvs/tds-vscode#507]
*Ola bom dia !
Estou tentando realizar um debug do P.E LJ7002, contudo nao consigo pois ao realizar o DEBUG pelo Visual Studio . mesmo passando o parametro de estação , e setando a pasta com todas as dlls . ele nao encontra a impressora! 
e portanto nao consigo passar da fase de finalização de venda ! 
segue uma evidencia ! 

gostaria de uma orientação de como realizar esse debug, quando tenho uma impressora nao fiscal na estação que precisa comunicar !

https://drive.google.com/file/d/1Ry3E1WAb8EkBTgc2NOUU2AMJo6X8TpY7/view?usp=sharing

**Comment by brodao** [comment]
Ola @wbarreto1 ,

Favor gerar os logs doVSCode (https://github.com/totvs/tds-vscode#suporte) e anexar ao chamado.

No aguardo.

**Comment by brodao** [comment]
Encerrado por falta de retorno.
