### ISSUE TITLE
Como gerar um arquivo aut ou utilizar o comando getAuthorizationId

### ISSUE THREAD

**Issue by eloichavesjr** [totvs/tds-vscode#508]
Estou utilizando o vs code
![image](https://user-images.githubusercontent.com/70237034/91233784-4dd85800-e708-11ea-90ae-7914c2ade3d6.png)
 e não estou conseguindo seguir os seguintes passo para gerar um arquivo "aut":

Abra o VS Code Quick Open (atalho Ctrl +Shift + P),e escolher:

Advpl - Compiler Auth - ID Code Authorization to be requested by Totvs.

E não conseguir utilizar o comando getAuthorizationId

Pergunta é como gero um arquivo ".aut" ?

**Comment by brodao** [comment]
Ola @eloichavesjr 

Arquivos de autorização (ou chave de compilação) é de uso exclusivo da TOTVS. Se você é um colaborador TOTVS, entre em contato com o seu gerente que este pode providenciar. Caso contrário, você pode compilar arquivos usando funções do usuário (_user function_), classes, serviços web e rest.

A disposição.
