### ISSUE TITLE
Gerar PTM arquivos/pastas selecionadas

### ISSUE THREAD

**Issue by eurairapelli** [totvs/tds-vscode#51]
Boa noite,

Analisar possibilidade de Gerar PTM dos arquivos/pastas selecionadas pelo shift/ctrl.

Att

**Comment by lwtnb-wrk** [comment]
@eurairapelli O VSCode não fornece para o plugins a informação de quais arquivos estão selecionados. Assim não conseguimos saber quais são os arquivos que deverão ser compilados. Segue issue aberta para a disponibilização desta funcionalidade no VSCode: https://github.com/Microsoft/vscode/issues/3553 Somente apos esta implementacao no VSCode poderemos implementar tal funcionalidade no tds-vscode.
