### ISSUE TITLE
Fonte apresenta acentuação com erros no vscode

### ISSUE THREAD

**Issue by nelsonibr** [totvs/tds-vscode#510]
Boa tarde,
Mesmo colocando "files.encoding": "windows1252" no arquivo settings.json a acentuação sai desconfigurada como exemplo: "seguranÃ§a deverÃ¡ ser nÃ­vel 3".
No aguardo do retorno.

**Comment by brodao** [comment]
Ola @nelsonibr ,

Isso ocorre porque o arquivo não é `windows1252`, aparentemente o mesmo foi salvo como UTF-8. Repare na barra de status do VS-Code qual o código de pagina apresentado. Acione o mouse sobre ele e nos comandos apresentados leia o arquivo como UTF-8 e depois repita a operação salvando com o windows1252.

A disposição.
