### ISSUE TITLE
Problema com o Include

### ISSUE THREAD

**Issue by VANDERLEIMARIANO** [totvs/tds-vscode#511]
Está configurado a pasta Include no VSCode, mas na com pilação apresente erro "arquivo não localizado"

![Include2](https://user-images.githubusercontent.com/70330702/91581683-24e0de80-e925-11ea-91c7-6443e03cb7de.jpg)
![Include1](https://user-images.githubusercontent.com/70330702/91581692-27433880-e925-11ea-848f-7937ba08a925.jpg)

Solicito ajuda

**Comment by brodao** [comment]
Ola @VANDERLEIMARIANO 

Experimente desconectar do servidor, adicionar a configuração da pasta para buscas (obrigatoriamente deve ser local), fechar o arquivo servers.json, reiniciar o VS-Code. Tente novamente compilar.
Caso o erro persista, favor capturar os logs e anexá-los a esse chamado. Detalhes em https://github.com/totvs/tds-vscode#suporte.

A disposição.

**Comment by brodao** [comment]
Encerrado por falta de retorno.
