### ISSUE TITLE
Debug não para no breakpoint

### ISSUE THREAD

**Issue by DouglasPedrosoMello** [totvs/tds-vscode#512]
Pessoal, 
Identifiquei um problema quando estou em modo debug, pois o sistema não esta parando nos breakpoints adicionado no fonte.
Fiz testes com diversos fontes e o erro permaneceu.
Anexo evidencias coletadas durante o teste.

Obrigado pela ajuda.
Douglas
[erro-vscode.docx](https://github.com/totvs/tds-vscode/files/5158862/erro-vscode.docx)

**Comment by brodao** [comment]
Ola Douglas,

Se possível, gera um PDF e não docx anexando esse PDF. Os demais arquivos (logs), devem ser anexados separadamente.
Isso facilita o trabalho de análise.

Grato.

**Comment by DouglasPedrosoMello** [comment]
Olá, 
Seguem arquivos como solicitado.

Obrigado.

[dap.log](https://github.com/totvs/tds-vscode/files/5188375/dap.log)
[informacoes.pdf](https://github.com/totvs/tds-vscode/files/5188376/informacoes.pdf)
[totvsls.log](https://github.com/totvs/tds-vscode/files/5188377/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/5188378/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/5188379/totvsls_out.log)

**Comment by brodao** [comment]
Ola @DouglasPedrosoMello 

Analisando os logs recebidos, não identifiquei nada de anormal. Apenas posso levantar algumas hipóteses e solicito que faça a verificação/testes:

. crie uma user function com alguns conouts. Coloque BP nesses conout´s e mande executar essa user fuction no lugar do sigaadv ou qq outro módulo
. certifique-se que os BP não são condicionais ou do tipo "hitCount" ou "log message" e que todos estão ativos (bolinha vermelha na linha)
. coloque BP em várias linhas, 3 a 4 linhas, antes e depois da parada realmente desejada (para ver se há sincronização entre fonte e compilação) 
. recompile o fonte que deseja depurar e verifique se há alguma mensagem no server (no momento da compilação). 
. remova todos os BP e e adicione novamente. Atente que linhas com definição de variáveis os BP´s podem não funcionar.

A disposição.

**Comment by DouglasPedrosoMello** [comment]
Olá Alan,
Fiz o procedimento orientado e não deu certo. O problema permaneceu.
Então fiz outro procedimento que acabou resolvendo o problema. Apaguei o meu perfil de usuário do windows e o perfil sendo recriado, começou a funcionar corretamente.

Obrigado pela ajuda.
