### ISSUE TITLE
Problema para debugar webservices, Job ou API

### ISSUE THREAD

**Issue by daniel-soro** [totvs/tds-vscode#513]
Quando vou debugar webservices, Job ou API, ele não para no ponto de parada, em fontes chamados normalmente pelo sistema o erro não acontece, poderiam me ajudar.

Att. 

Daniel R. Melo

**Comment by brodao** [comment]
Ola Daniel,

Abra o arquivo .vscode/launch.json e na definição de depurador adicione a chave `enableMultiThread` com valor `true`.

![image](https://user-images.githubusercontent.com/949914/92269506-afdc4e80-eeba-11ea-8ac3-29ec06d24c48.png)

Inicie a execução do depurador executando qualquer função/módulo que mantenha a conexão com o servidor, p.e. "sigafat".
Abra o fonte a ser depurado e adicione o ponto de parada. Quando o servidor atingir esse ponto, o controle da execução passa para o depurador. *NUNCA* depure em ambiente de produção ou ambientes compartilhados com outros desenvolvedores, pois enquanto o controle esta sobre responsabilidade do depurador, o appServer para todas as _threads_.

A disposição.

**Comment by lseguralbino** [comment]
Muy buena solucion!!! efectiva. Gracias!!!
