### ISSUE TITLE
Utilizando Totvs Monitor

### ISSUE THREAD

**Issue by Adailton-lanca** [totvs/tds-vscode#514]
Olá!
instalei o Totvs Monitor no vscode, incluí um servidor e ao tentar conectar dá a seguinte mensagem:
"Validations erros detected. Please verify the log for more details". 
E, tem alguma maneira de excluir um Server no monitor?

**Comment by ricardomansano** [comment]
Boa tarde,
O Monitor será integrado ao plugin da nossa IDE, e deve ser liberado no inicio de Outubro

Pra excluir um servidor basta editar o arquivo servers.json, na imagem abaixo explico como fazê-lo:
![image](https://user-images.githubusercontent.com/33813921/94179641-298caa00-fe73-11ea-9b70-d64d9ec92213.png)

At
