### ISSUE TITLE
Authentication error: Server returned a non numeric value.

### ISSUE THREAD

**Issue by winstoncosta** [totvs/tds-vscode#515]
Estou tentando logar no RPO do TSS para aplicar um patch e o sistema retorna "Authentication error: Server returned a non numeric value."

[Info  - 14:15:05] Starting connection to the server 'TSS' (10.24.0.63@5060)
[Info  - 14:15:05] Connection to the server 'TSS' finished.
[Info  - 14:15:10] Starting user 'admin' authentication.
[Info  - 14:15:10] Secure authenticating...
[Error - 14:15:12] Authentication error: Server returned a non numeric value.
[Error - 14:15:12] Authentication failed. Could not authenticate to server.

Utilizo a versão 1.0.6 do Plugin "Totvs Developer Studio for VSCode"

**Comment by DanielYampolschi** [comment]
Ola @winstoncosta ,

Favor gerar os logs doVSCode (https://github.com/totvs/tds-vscode#suporte) e anexar ao chamado.

No aguardo.

**Comment by brodao** [comment]
Encerrado por falta de retorno.
