### ISSUE TITLE
Configuração VsCode para Protheus Intera T-Cloud

### ISSUE THREAD

**Issue by VictorHayashi** [totvs/tds-vscode#516]
Preciso de ajuda para realizar a configuração do VsCode para comunicação com a base do Protheus Intera T-Cloud, porém não consegui realiza-la com o passo a passo padrão. Vocês poderiam me ajudar?

Agradeço desde já.

**Comment by charlesreitz** [comment]
Olá, mas qual a dúvida? E gerado algum erro?

**Comment by brodao** [comment]
Encerrado por falta de retorno.
