### ISSUE TITLE
Não funciona  conexão do smartcliet que está em uma máquina Linux (Distri - Ubuntu 20.04)

### ISSUE THREAD

**Issue by altair0305** [totvs/tds-vscode#517]
**Describe the bug**
Não há a conexão do entre o vscode e nosso appsever, que está em um servidores windows 2000 server.

**To Reproduce**

**Expected behavior**
{
	"version": "0.2.0",
	"includes": [
		"/home/altair/TOTVS/include"
	],
	"permissions": {
		"authorizationtoken": ""
	},
	"connectedServer": {},
	"configurations": [
		{
			"id": "xz21hjxni9hkdj66992vydjlcfoyon",
			"type": "totvs_server_protheus",
			"name": "TOTVS12_TST_12.1.25TOTVS12_TST_12.1.25",
			"port": 9100,
			"address": "192.168.47.30",
			"buildVersion": "7.00.170117A",
			"secure": false,
			"includes": [],
			"environments": [
				"compilacao"
			],
			"environment": "compilacao",
			"token": "djM6eHoyMWhqeG5pOWhrZGo2Njk5MnZ5ZGpsY2ZveW9uOjE6MTkyLjE2OC40Ny4zMDo5MTAwOjA6Ny4wMC4xNzAxMTdBOjM=:djE6Q09NUElMQUNBTzpub3VzZXI6czRUZ3BOaWUrbTg5UFB2dzMyREpWTlVpS1QxcUV1cU5vYzlBb1FJSzlyUT0=|djI6MTU5Njc0MTk0ODoyOjE6MQ==.vO+liYl5cjLCiQI539YUcJTnbpnYBmMYFRNXN6iE4uLv9Y9w4lBtZLoEhQ5+mYc1FfZ7wc8HDnVegICl0yX5F/Lk+36D0t8B8x8F/uuYEIVWDd77/yLaNuoDNFq0nrqvE55VCHLZUg9WIIL7Xvx8lEJwOgCCwzpTQg59J0t9sAk4Jdj725mbtDapUalcVdoslgX0nR2vG6LinnVU3FA/W/UJ4NQ1+Sg6+aqdDZy3Phaj3ytJXWzSF/OIuRy9doWxgmZKvP0UBwku822g+7139F9njrshTNowK3KxIl47696Y17dreVT6ZtskOeaIgvyPV0K0F0tB+hx3Pz3W53+Khg=="
		}
	],
	"savedTokens": [
		[
			"xz21hjxni9hkdj66992vydjlcfoyon:compilacao",
			{
				"id": "xz21hjxni9hkdj66992vydjlcfoyon",
				"token": "djM6eHoyMWhqeG5pOWhrZGo2Njk5MnZ5ZGpsY2ZveW9uOjE6MTkyLjE2OC40Ny4zMDo5MTAwOjA6Ny4wMC4xNzAxMTdBOjM=:djE6Q09NUElMQUNBTzpub3VzZXI6czRUZ3BOaWUrbTg5UFB2dzMyREpWTlVpS1QxcUV1cU5vYzlBb1FJSzlyUT0=|djI6MTU5Njc0MTk0ODoyOjE6MQ==.vO+liYl5cjLCiQI539YUcJTnbpnYBmMYFRNXN6iE4uLv9Y9w4lBtZLoEhQ5+mYc1FfZ7wc8HDnVegICl0yX5F/Lk+36D0t8B8x8F/uuYEIVWDd77/yLaNuoDNFq0nrqvE55VCHLZUg9WIIL7Xvx8lEJwOgCCwzpTQg59J0t9sAk4Jdj725mbtDapUalcVdoslgX0nR2vG6LinnVU3FA/W/UJ4NQ1+Sg6+aqdDZy3Phaj3ytJXWzSF/OIuRy9doWxgmZKvP0UBwku822g+7139F9njrshTNowK3KxIl47696Y17dreVT6ZtskOeaIgvyPV0K0F0tB+hx3Pz3W53+Khg=="
			}
		]
	],
	"lastConnectedServer": "xz21hjxni9hkdj66992vydjlcfoyon"
}

**Screenshots**

**Desktop (please complete the following information):**
 - OS/Architecture: [e.g. Linux 64 bits Ubuntu 20.04]

**Appserver (please complete the following information):**

![image](https://user-images.githubusercontent.com/17034565/93371673-1a7d7a80-f829-11ea-80ee-0431ca760325.png)

**Additional context**

**Comment by charlesreitz** [comment]
Olá, estou usando normalmente o VS Code com Ubuntu, apresenta alguma falha de conexão algo assim?

**Comment by altair0305** [comment]
Já resolvi o problema com a conexão, agora estou com outro gap o objeto
 Inspetor não trás a listagem de fontes do meu rpo.

Em qui, 17 de set de 2020 08:29, Charles Reitz <notifications@github.com>
escreveu:

**Comment by brodao** [comment]
Ola @altair0305 

Você esta usando o TDS ou VS-Code? Colocou informações de dois ambientes.

Quanto ao erro do inspetor, temos conhecimento dessa ocorrência que já esta com a equipe do appServer.
Alguns conseguiram contornar efetuando a desfragmentação do RPO. Experimente isso.

A disposição.

**Comment by brodao** [comment]
Gentileza abrir um chamado para cada ocorrência. Como seu problema inicial foi resolvido, vou fechar o chamado.
