### ISSUE TITLE
Erro intermitente na conexão com o appserver advpl [advpls: tpp.c:82: __pthread_tpp_change_priority]

### ISSUE THREAD

**Issue by charlesreitz** [totvs/tds-vscode#518]
Olá, erro é gerado as vezes, sendo necessário fechar o VSCODE abrir novamente, muitas vezes preciso repetir esse procedimento até conseguir conectar, também fecho o appserver e subo ele novamente, imagino que quando estou debugando e mando compilar pode estar gerando esse problema. 

advpls: tpp.c:82: __pthread_tpp_change_priority: Assertion `new_prio == -1 || (new_prio >= fifo_min_prio && new_prio <= fifo_max_prio)' failed.

Loguru caught a signal: SIGABRT
(   8.537s) [querydb         ]                       :0     | Signal: SIGABRT

**Desktop (please complete the following information):**
 - Ubuntu 20.04.1 LTS

**Appserver (please complete the following information):**
* TOTVS - Build 7.00.191205P - Jun 29 2020 - 21:39:23 
* Build: 64 bits
* SVN Revision: 27206
* Build Version: 19.3.0.5

**Comment by lwtnb-wrk** [comment]
@charlesreitz Realmente, efetuar uma compilação durante uma depuração não é um cenário muito adequado, tampouco um crash do AppServer...
Do lado do tds-vscode vamos tentar proteger para que o LS não caia, mas o problema raiz terá que ser corrigido pelo time do AppServer.
Grato pelas informações

**Comment by brodao** [comment]
Sugestão: Desabilitar a execução de processos em geral durante a depuração de código AdvPL/Logix.

**Comment by lwtnb-wrk** [comment]
@charlesreitz Eu testei agora com a 19.3.0.6 e 19.3.1.1 e ambos não caíram nem geraram quaisquer problema, mas testei no Windows.
Você ainda observa esse problema nas versões mais atualizadas do AppServer em Linux?

**Comment by lwtnb-wrk** [comment]
@charlesreitz De qualquer forma vamos adicionar umas validações para impedir algumas ações durante a depuração

**Comment by lwtnb-wrk** [comment]
Geramos um VSIX versão 1.2.1 que está em Pré Release (Draft) em https://github.com/totvs/tds-vscode/releases/tag/untagged-4836c4e75f678708b252
Se quiserem/puderem baixar e instalar manualmente este VSIX para avaliar se o seu problema relatado foi solucionado, favor nos informar se está corrigido ou não para que possamos realizar a liberação oficial.
Para instalar manualmente o VSIX baixem do link acima e na aba de "Extensões" do VS Code clique em "..." e selecione "Install from VSIX" e apontem para o arquivo baixado.
