### ISSUE TITLE
Aplicar Patch VSCODE Linux não localiza pasta devido ao case sensitive

### ISSUE THREAD

**Issue by charlesreitz** [totvs/tds-vscode#519]
Ao realizar aplicação de patch no Linux Ubuntu 20, apresenta a mensagem que não localiza o arquivo.

One or more validations errors detected: The following patch(es) contains at least one upper case character, which is not allowed for unix base systems: /home/charlesreitz/Downloads/tttp120 (2).ptm;

Porém se colocar nesse caminho ele aplica: /home/charlesreitz/tttp120.ptm

Imagino que seja devido ao case-sensitive. 

Obrigado,

**Comment by lwtnb-wrk** [comment]
@charlesreitz Trata-se de uma limitação do AppServer que ao trabalhar com o arquivo no Linux muda o caminho todo para lowercase, então colocamos este aviso exatamente para indicar que o caminho não pode conter uppercase.
Infelizmente do lado do TDS VS Code não há nada que possa ser feito.
