### ISSUE TITLE
Descompilar arquivos/pastas selecionados

### ISSUE THREAD

**Issue by eurairapelli** [totvs/tds-vscode#52]
Boa noite,

Atualmente não permite descompilar pasta/arquivos selecionados.
Analisar possibilidade de adicionar recurso para descompilar pasta/arquivos.

Att

**Comment by lwtnb-wrk** [comment]
@eurairapelli poderia nos dizer o que voce entende por descompilar pasta/arquivos? nunca tivemos este tipo de funcionalidade para o AdvPL...

**Comment by ricardomansano** [comment]
Bom dia @eurairapelli ,
Como o Leo comentou nunca tivemos essa ferramenta, e por uma questão de segurança de informação, nunca teremos.
Mesmo na descompilação de fontes customizados incorremos em grande risco.
Grato pelo contato

**Comment by matheus-sales** [comment]
> @eurairapelli poderia nos dizer o que voce entende por descompilar pasta/arquivos? nunca tivemos este tipo de funcionalidade para o AdvPL...

@eurairapelli voce está se referindo a deletar recurso do RPO ou reverter um fonte do RPO a um estado de compreensão? 

Se for deletar o recurso do RPO a opção já existe (https://github.com/totvs/tds-vscode#deletar-recursos-do-rpo). Se for reverter o fonte, segue o que o ricardo falou acima.

**Comment by eurairapelli** [comment]
![image](https://user-images.githubusercontent.com/51135309/58591468-bce0ab80-823c-11e9-88e9-31937cba92a1.png)

Descompilar arquivos selecionados. TDS possui esse recurso de descompilar folders, arquivos.
No outro issue comentaram sobre microsoft disponibilizar esse recurso dos arquivos selecionados para implementação.

>> microsoft/vscode#3553 Somente apos esta implementacao no VSCode poderemos implementar tal funcionalidade no tds-vscode

**Comment by lwtnb-wrk** [comment]
> ![image](https://user-images.githubusercontent.com/51135309/58591468-bce0ab80-823c-11e9-88e9-31937cba92a1.png)
> 
> Descompilar arquivos selecionados. TDS possui esse recurso de descompilar folders, arquivos.
> No outro issue comentaram sobre microsoft disponibilizar esse recurso dos arquivos selecionados para implementação.
> 
> > > [microsoft/vscode#3553](https://github.com/microsoft/vscode/issues/3553) Somente apos esta implementacao no VSCode poderemos implementar tal funcionalidade no tds-vscode

Desculpe @eurairapelli mas acho que você está usando o termo errado. Não temos a função descompilar no TDS.
Como o @matheus-sales informou temos o deletar (remover) programas do RPO para apagar o fonte do RPO é isso que você está tentando dizer?

E o que comentamos na outra issue foi exatamente o contrario. A microsoft nao tem esse recurso mas estamos testando alternativas. Se conseguirmos seguir com alternativas podemos reabrir essa issue no futuro. Grato pelos teste e sugestoes.
