### ISSUE TITLE
Último programa executado, caso possuir argumentos não envia para o smartclient na segunda execução

### ISSUE THREAD

**Issue by charlesreitz** [totvs/tds-vscode#520]
Quando executo o smartclient passando na linha parâmetros, nas próximas execuções ele não leva esses parâmetros para o smartclient. 

Exemplo:

Primeira chamada do smartclient
![image](https://user-images.githubusercontent.com/1248135/93470950-1143ea80-f8c9-11ea-8acc-56c548f5e313.png)

Segunda Chamada do smartclient
![image](https://user-images.githubusercontent.com/1248135/93470915-04bf9200-f8c9-11ea-8e94-f6d8e61dc1a5.png)

Para ele funcionar, preciso apagar o que está preenchido e na sequencia selecionar o histórico que desejo
![image](https://user-images.githubusercontent.com/1248135/93471041-30db1300-f8c9-11ea-9510-b9ea0c978cf7.png)

**Comment by brodao** [comment]
Resolvido em #526 .
