### ISSUE TITLE
Informação do patch pegando caminho errado

### ISSUE THREAD

**Issue by Belyukie** [totvs/tds-vscode#521]
Olá, não consigo mais utilizar a opção 'Patch Info', pois ao tentar carregar as informações, está usando o caminho do meu ambiente ao invés do caminho do arquivo especificado, vide print
![CaminhoPatchInfo](https://user-images.githubusercontent.com/23284290/93612325-c2b84e00-f9a5-11ea-97eb-8fdc249dee50.png)

Ps: Consigo aplicar o patch normalmente, só não exibe as informações pela UI.

**Comment by brodao** [comment]
Ola @Belyukie,

Verifique se há atualização para os binários para a versão do seu server (na P19 houve correções com certeza).
Veja no log de console do server se há alguma informações adicional e anexe ao seu chamado.

A disposição.

**Comment by Belyukie** [comment]
Boa tarde,
apenas comunicando que a atualização resolveu.
Com a versão publicada no dia em que abri a issue (20-09-18-P12_APPSERVER_BUILD-19.3.0.6_WINDOWS_X64),
o 'patch info' funcionou normalmente, obrigada.
