### ISSUE TITLE
Erro ao compilar fonte

### ISSUE THREAD

**Issue by rastolfi** [totvs/tds-vscode#522]
Boa tarde!
Estou com erro ao compilar um fonte, alguém já teve esse problema.
[Error - 11:29:42] [FATAL] Aborting: BENEFARQ.PRW(495)
invalid constant STR0057
invalid constant STR0058
invalid constant STR0059
[Info - 11:29:42] Aborting end build (rollback changes).
[Error - 11:29:42] One or more files have errors and/or warnings. See problems and logs for details.
[Info - 11:29:42] Recompile finished.

**Comment by thuliofilipp** [comment]
Verifique se o DBAcess está em execução.

**Comment by brodao** [comment]
Ola @rastolfi 

As constantes iniciadas com STR, normalmente, são definições (#define) de tradução. Para compilar esse fonte, você precisa do CH de tradução dele.

A disposição.
