### ISSUE TITLE
Problema com fonte GP670ARR

### ISSUE THREAD

**Issue by mipersiga** [totvs/tds-vscode#523]
Olá, pessoal!

A sintaxe abaixo está correta ? Podem me ajudar ?

Valeu!!

#Include "PROTHEUS.CH"

User Function GP670ARR()

aCposUsr := {}

aAdd(aCposUsr,{"E2_FILORIG"       , RC1->RC1_FILTIT           , Nil},; 
			  {"E2_XITCTB"        , RC1->RC1_XITCTB         , Nil},;
			  {"E2_CONTAD"     , RC1->RC1_XCONTA       , Nil},;
			  {"E2_TIPOPEX"      , RC1->RC1_TIPOEX        , Nil},;
		          {"E2_HIST"            , RC1->RC1_HIST             , Nil},;
		          {"E2_CCD"            , RC1->RC1_CC                , Nil})  
		      
Alert("Ponto de Entrada Gp670Arr executado")

Return aCposUsr

**Comment by ricardomansano** [comment]
Boa tarde,
O AADD recebe apenas dois parametros, da maneira que construiu esta inserindo varios sub-arrays, segue a maneira correta abaixo

#INCLUDE "TOTVS.CH"

#Include "PROTHEUS.CH"
User Function GP670ARR()

aCposUsr := {}

aAdd(aCposUsr,;
{;
{"E2_FILORIG" , RC1->RC1_FILTIT , Nil},;
{"E2_XITCTB" , RC1->RC1_XITCTB , Nil},;
{"E2_CONTAD" , RC1->RC1_XCONTA , Nil},;
{"E2_TIPOPEX" , RC1->RC1_TIPOEX , Nil},;
{"E2_HIST" , RC1->RC1_HIST , Nil},;
{"E2_CCD" , RC1->RC1_CC , Nil};
};
)

Alert("Ponto de Entrada Gp670Arr executado")

Return aCposUsr

At
Mansano

**Comment by mipersiga** [comment]
Mansano, bom dia!

Desculpe a demora em respondê-lo e de agradecer pelo seu retorno. Acontece que eu compilei o programa
conforme você orientou e está dando erro log (em anexo) durante o processo.
Pode dar uma olhada pra mim ? 🙂




Atenciosamente ,

[cid:ff1d6add-fd06-4801-944e-4b4fcee5a994]


Fabiano Michelino
Analista de Sistema
Tecnologia da Informação
Telefone: +55 (21) 3506-3656
Email: fabiano.michelino@lfc.org.br
Site: http://www.lfc.org.br<http://www.lfc.org.br/>
[cid:5105635c-33db-46c6-a6b0-6cb715d90e52]

________________________________
De: Mansano <notifications@github.com>
Enviado: quinta-feira, 24 de setembro de 2020 14:28
Para: totvs/tds-vscode <tds-vscode@noreply.github.com>
Cc: Fabiano Michelino <fabiano.michelino@lfc.org.br>; Author <author@noreply.github.com>
Assunto: Re: [totvs/tds-vscode] Problema com fonte GP670ARR (#523)


Boa tarde,
O AADD recebe apenas dois parametros, da maneira que construiu esta inserindo varios sub-arrays, segue a maneira correta abaixo

#INCLUDE "TOTVS.CH"

#Include "PROTHEUS.CH"
User Function GP670ARR()

aCposUsr := {}

aAdd(aCposUsr,;
{;
{"E2_FILORIG" , RC1->RC1_FILTIT , Nil},;
{"E2_XITCTB" , RC1->RC1_XITCTB , Nil},;
{"E2_CONTAD" , RC1->RC1_XCONTA , Nil},;
{"E2_TIPOPEX" , RC1->RC1_TIPOEX , Nil},;
{"E2_HIST" , RC1->RC1_HIST , Nil},;
{"E2_CCD" , RC1->RC1_CC , Nil};
};
)

Alert("Ponto de Entrada Gp670Arr executado")

Return aCposUsr

At
Mansano
