### ISSUE TITLE
Organização de Arquivos por Projeto

### ISSUE THREAD

**Issue by veltonteixeira** [totvs/tds-vscode#524]
Gostaria de saber de alguma extensão ou recurso no VSCODE para atender a seguinte demanda:
Tenho uma estrutura de diretórios para arquivar os fontes separados por módulos do sistema (faturamento, compras, financeiro, ...), porém, alguns projetos envolve fontes de vários módulos, ou seja, estão separados em vário diretórios, mas fazem parte de um mesmo projeto, e alguns deles, fazem parte de mais de um projeto.  

Quando eu preciso compilar ou identificar todos os fontes de um projeto específico, tenho que sair garimpando em cada diretório, identificar o fonte e compilar.

Tem alguma forma de agrupar fontes por nome do projeto, tag, diretório virtual,  sem necessariamente modificar estrutura diretório, mas sim que eu possa linkar arquivos em vários diretórios diferentes?

**Comment by ricardomansano** [comment]
Boa tarde Velton,
Não sei dizer se existe essa extensão, mas conhecendo o modus operandi do VSCode acredito que não.
Sorte!
