### ISSUE TITLE
Connection got disposed versão 1.0.6

### ISSUE THREAD

**Issue by csescobar** [totvs/tds-vscode#525]
Ao tentar conectar no servidor em cloud Totvs, recebo a resposta:
![Anotação 2020-09-25 122706](https://user-images.githubusercontent.com/29630079/94285732-754e5a80-ff2a-11ea-9f5d-c5a96d3eb525.png)

**Comment by brodao** [comment]
@csescobar 

Verifique se registro do servidor foi efetuado com acesso seguro ou não. Esta informação deve estar de acordo com o configurado no server. Também pode ter ocorrido algo no server durante o processo. Veja o log de console do protheus, para ver se há alguma informação.

A disposição.

**Comment by lwtnb-wrk** [comment]
@csescobar E veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs do tds-vscode para analise

**Comment by csescobar** [comment]
Segue em anexo os logs e print da configuração do server.json

![image](https://user-images.githubusercontent.com/29630079/98545381-2a876880-2274-11eb-9cc9-641e677ef990.png)


[totvsls.log](https://github.com/totvs/tds-vscode/files/5510705/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/5510706/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/5510707/totvsls_out.log)

**Comment by csescobar** [comment]
Arquivo de log full.
[totvslsfull.log](https://github.com/totvs/tds-vscode/files/5510801/totvslsfull.log)

**Comment by lwtnb-wrk** [comment]
@csescobar No print inicial você estava tentando validar o servidor na porta 2001, mas neste ultimo print a porta é a 2010. Aparentemente pelos meus teste o correto é a porta 2010.
De qualquer forma fiz um teste aqui e realmente na porta 2001 ocorreu um erro, enquanto que na porta 2010 o cadastro foi concluído com sucesso.
O erro ocorreu durante o primeiro acesso do dia neste servidor? Temos relatos de problemas durante o primeiro acesso que deixam de ocorrer em questão de minutos após o primeiro acesso. Poderia tentar se conectar novamente no servidor na porta 2010 e verificar se o problema persiste?

**Comment by csescobar** [comment]
@lwtnb-wrk, a porta 2010 é do servidor configurado para WebService.
Eu desinstalei a extensão Totvs developer studio e reinstalei hoje e continuo sem conseguir conectar.

**Comment by lwtnb-wrk** [comment]
@csescobar Realmente eu apenas consegui cadastrar o servidor na porta 2010 mas não testei a conexão pois não tenho os dados para efetuar uma conexão. A principio eu consigo acessar algo na porta 2010 que parece responder como um Appserver.
Você não estaria atrás de algum tipo de firewall que pode estar bloqueando suas conexões?
Poderia também enviar o appserver.ini para analisarmos?

**Comment by csescobar** [comment]
@lwtnb-wrk 
   1- Eu estou trabalhando home office, então não tenho firewall bloqueando as conexões.
   2- Eu consigo acessar o smartclient através da porta 2010.

Segue o appserver.ini
[appserver.zip](https://github.com/totvs/tds-vscode/files/5511249/appserver.zip)

**Comment by lwtnb-wrk** [comment]
@csescobar Durante meus testes aqui a porta 2001 começou a responder. Veja se consegue se conectar na 2001 agora.

E esse appserver.ini parece ser local mas o endereço do AppServer é de um servidor na Cloud? A porta do WS neste appserver.ini é a 2009...

**Comment by csescobar** [comment]
O AppServer está em Totvs Cloud.
A porta 2009 é para acesso http.
Eu sempre acesso através do navegador pelo endereço https://zd6jxz-prd-protheus.totvscloud.com.br:2009/ws/

Já a porta 2010 eu acesso via smartclient e acessava antes pelo TDS.

**Comment by lwtnb-wrk** [comment]
@csescobar Ok, a porta 2009 realmente respondeu como um WS, eu havia entendido que o WS estava na porta 2010.
Consegui acessar daqui tanto o AppServer na porta 2001 quanto na 2010. Obviamente falhou na validação de usuário/senha pois coloquei qualquer coisa, mas ambos responderam. 
Os logs gerados continuam com os mesmos erros? Pois aqui nos primeiros acesso realmente tive problemas, mas provavelmente era algo nos servidores da Cloud, porque após os primeiros acessos eu estou conseguindo acessa-los.
Se os logs estiverem diferente nos envie novamente para analises.

**Comment by csescobar** [comment]
Deletei os logs, tentei conectar novamente e não consegui.
Segue os logs em anexo:

[totvsls.log](https://github.com/totvs/tds-vscode/files/5512355/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/5512356/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/5512357/totvsls_out.log)
[totvslsfull.log](https://github.com/totvs/tds-vscode/files/5512358/totvslsfull.log)

**Comment by lwtnb-wrk** [comment]
@csescobar Consegui reproduzir o problema aqui mas de forma intermitente. Algumas vezes dá erro e em outras ele valida corretamente. Observei que logo após uma falha, ao tentar na sequencia ele validou e conectou. 
Chegou a realizar varias tentativas na sequencia? Tente fazer algumas tentativas de conexão sem apagar o totvslsfull.log e nos envie apenas esse arquivo para analise.

**Comment by lwtnb-wrk** [comment]
@csescobar Sabe dizer qual a versão do AppServer na Cloud?

**Comment by csescobar** [comment]
Segue:
[totvslsfull.log](https://github.com/totvs/tds-vscode/files/5517980/totvslsfull.log)

![image](https://user-images.githubusercontent.com/29630079/98688292-735d2100-2349-11eb-8fba-d09bdce353f8.png)

**Comment by lwtnb-wrk** [comment]
@csescobar Consegui localizar o problema graças ao seu log... Estamos trabalhando na solução. Grato pelos testes.

**Comment by lwtnb-wrk** [comment]
@csescobar Foi liberada uma atualização que deve resolver seu problema, se após a atualização ainda tiver problemas, favor reabrir a issue e dar novos detalhes.
