### ISSUE TITLE
Função Inicial F5 não aceita selecionar

### ISSUE THREAD

**Issue by efdeiasoliveira** [totvs/tds-vscode#526]
**Describe the bug**
Toda vez que mandamos executar o debug através do F5 então é exibida a caixa de texto com a ultima função executada e a lista de funções já executadas.

Quando tentamos selecionar uma função que já foi executada, o debug não abre... então temos que digitar novamente a função mesmo que a mesma já esteja na lista de funções executadas.

**To Reproduce**
1. Conecte em um ambiente
2. Pressione F5 
3. Digite a função SIGAMDI
4. Após abrir o sistema, feche a aplicação.
5. Pressione F5
6. Digite a função SIGAFIN
7. Após abrir o sistema, feche a aplicação.
8. Pressione F5
9. Digite S e SELECIONE a função SIGAMDI que já esta na lista de função executadas sugeridas.
10. O sistema não irá tentará abrir a função S ao invés da função selecionada e não irá conseguir abrir.
11. Ao pressionar F5 novamente ficará gravada indevidamente uma nova função S 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS/Architecture: [e.g. Windows 64 bits]

**Appserver (please complete the following information):**
 - Build (with date): [e.g. Build 7.00.170117A - Jun 28 2019 - 11:16:56]
 - OS/Architecture: [e.g. Linux 64 bits Ubuntu]
 - Build Version [e.g. 17.3.0.13]

**Additional context**

**Comment by brodao** [comment]
Similar #520
