### ISSUE TITLE
atualização tds-vscode-1.0.6.vsix exclui servidores

### ISSUE THREAD

**Issue by eduardonogueira0405** [totvs/tds-vscode#529]
Ao realizar a atualização acima citada, na primeira vez ela exclui a extensão Totvs Developer Studio for VSCode.
Ao realizar uma segunda tentativa ela inclui novamente a extensão mas da conflito com a extesão 4gl-outline-dxc que é utilizada para mostrar as funções internas do fonte 4gl na opção 'Contorno' do "Explorador".  Com isto não é possivel ver a lista de funcões internas do código.

**Comment by brodao** [comment]
Ola @eduardonogueira0405 ,

Verifiquei a ocorrência. A extensão 4gl-outine-dxc utiliza o mesmo código de linguagem que o TDS, sobrescrevendo nossas configuração. Portanto, você não pode utilizar essa extensão junto com o TDS e não há como contornarmos.

A disposição.

**Comment by eduardonogueira0405** [comment]
Bom dia,
E como faço para mostrar as funções internas na lista de "Contorno", a extensão TDS tem um bug em relação a esta visualização. Atualmente ela somente mostra se não há espaço no primeiro campo, segue exemplo:
O código LOGIX é gerado desta forma (é um padrão utilizado por todos os desenvolvedores da Linguagem):
#---------------------------------------------------------#
 FUNCTION obf0001_prepara_livro_saida(l_modo_exibicao_msg)
#---------------------------------------------------------#

Note que na declaração há um espaço em branco no inicio da codificação, e desta forma o VSCode não mostra esta função.
A visualização só é possível se retirar este espaço, no entanto é impossível isto, pois 99,99% dos códigos fontes do Logix são escritos desta forma.

Atenciosamente
Eduardo

**Comment by brodao** [comment]
Solicito que abra um novo chamado indicando esse erro na visão "Contorno" do TDS que providenciaremos a correção o mais rápido possível.

A disposição.
