### ISSUE TITLE
Erro ao gerar Client WS no VS Code

### ISSUE THREAD

**Issue by alissonsouza05** [totvs/tds-vscode#530]
Ao tentar gerar o Client WS no VS Code, a partir da funcionalidade Generate WS Protheus, é gerado um fonte que não é compilável.
Com isso, não é possível dar prosseguimento.

Há momentos em que o fonte é gerado em branco.
![img00](https://user-images.githubusercontent.com/47537980/94755375-bbf8e600-036a-11eb-953f-973f2c7aaf02.png)
![img01](https://user-images.githubusercontent.com/47537980/94755376-bd2a1300-036a-11eb-9b58-daf3075ed7a0.png)
![img02](https://user-images.githubusercontent.com/47537980/94755377-bd2a1300-036a-11eb-8a09-8ce76b5df5f0.png)
![img03](https://user-images.githubusercontent.com/47537980/94755379-bdc2a980-036a-11eb-99e2-274ffb2c2dee.png)
![img04](https://user-images.githubusercontent.com/47537980/94755380-be5b4000-036a-11eb-81c4-a968cdc8eddb.png)

**Comment by brodao** [comment]
Ola @alissonsouza05,

O TDS-VSCode é apenas uma casca para a geração do cliente de serviço web. O responsável pela  geração é o servidor Protheus.
Favor entrar em contato com o serviço de suporte do mesmo.

A disposição.
