### ISSUE TITLE
Erro Ao Inicializar o Vscode Protheus

### ISSUE THREAD

**Issue by Miqueiasfer** [totvs/tds-vscode#532]
estou recebendo a mensagem abaixo quando tento executar o Vscode Protheus:

Initializing Language Server.
(   0.082s) [querydb         ]msg_lsp_initialize_requ:486   | ABORT: Unable to find path file://27.27.1.3/mp12r25/protheus/my%20projects/VAMTEC
[Info  - 11:54:05] Connection to server got closed. Server will restart.

**Comment by brodao** [comment]
Ola @Miqueiasfer 

Isso ocorre porquê a pasta não existe ou esta indisponível. Você usa arquivo "*.code-workspace", se sim, abra esse arquivo e remova a definição desta pasta.

A disposição.

**Comment by Miqueiasfer** [comment]
a pasta existe. como faço para abrir este arquivo code-workspace?

**Comment by lwtnb-wrk** [comment]
@Miqueiasfer Por esse caminho parece que seu projeto está um drive de rede, correto?
Se afirmativo mapeie esse caminho de rede para um drive e utilize o projeto a partir desse drive mapeado.

**Comment by Miqueiasfer** [comment]
> @Miqueiasfer Por esse caminho parece que seu projeto está um drive de rede, correto?
> Se afirmativo mapeie esse caminho de rede para um drive e utilize o projeto a partir desse drive mapeado.

@lwtnb-wrk  era isto mesmo, valeu
