### ISSUE TITLE
Problema com Debug

### ISSUE THREAD

**Issue by brunogirome** [totvs/tds-vscode#533]
Ao tentar debugar no VSCode ADVPL, o sistema sempre abre a seguinte janela de erro:

![image](https://user-images.githubusercontent.com/44439996/94848479-708e1880-03fa-11eb-9057-4f4b3b43e821.png)

As documentações da TOTVS sugerem utilizar o Appserver Slave, e não o Master, entretanto, já estamos tentando realizar este debug via Slave.

- Release do RPO:  12.1.025

- Build AppServer: 7.00.191205P-20200424 - 64 bits

- Appserver version: 19.3.0.4

- TOTVS Developer Studio for VSCode (AdvPL, TLPP e 4GL): 1.0.6

**Comment by brodao** [comment]
Você consegue executar sem depurar (ctrl+f5)?

Favor ver https://github.com/totvs/tds-vscode/blob/dev/TROUBLESHOOTING.md
