### ISSUE TITLE
DEBUG - Erro ao debugar 

### ISSUE THREAD

**Issue by raphaelmoerbeck** [totvs/tds-vscode#534]
Boa noite rapaziada ! .

Ja fiz de tudo pra tentar debugar mas tá dificil .

Como consigo prosseguir ?

![Screenshot_10](https://user-images.githubusercontent.com/69321583/94880641-e2d21d80-0439-11eb-843a-86b7f1229257.png)

Att.

**Comment by brodao** [comment]
Favor detalhar a ocorrência. Veja https://github.com/totvs/tds-vscode/blob/dev/TROUBLESHOOTING.md
