### ISSUE TITLE
VSCODE protheus 12.1.27

### ISSUE THREAD

**Issue by claudiohf** [totvs/tds-vscode#535]
Saudações.
Cliente está migrando para a versão 12.1.27 do Protheus.
Ao compilar todo o Workspace no VS Code o sistema dá como OK a compilação de todos os fontes, mas ao acessar o sistema temos o aviso que o fonte não foi compilado.
Ao compilar unitariamente o fonte, ele é compilado corretamente e funciona, porém, o cliente possui mais de 400 personalizações, inviabilizando a compilação um a um.
Como proceder?

**Comment by claudiohf** [comment]
[Info  - 11:14:50 AM] Start secure compiling d:/TOTVS/ERP_VALEO/Protheus12/Protheus_Data/fontes/estoque/FB001EST.PRW (130/890).
[Info  - 11:14:50 AM] [SUCCESS] Source d:/TOTVS/ERP_VALEO/Protheus12/Protheus_Data/fontes/estoque/FB001EST.PRW compiled successfully.

Ao testar a função da como não compilada.

**Comment by brodao** [comment]
Ola @claudiohf 

Favor verificar https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#compila%C3%A7%C3%A3o-de-fontes e caso não resolva, favor como indicado em proceder https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs, anexando os logs a esse chamado.

A disposição.

**Comment by claudiohf** [comment]
Boa tarde @brodao 
Eu coloquei as chaves para gerar os LOG's e mandei recompilar o workspace, porém nenhum log foi gerado.
Vou te encaminhar os arquivos settings.json e launch.json para análise.

launch.json
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "TOTVS Language Debug",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "D:\\TOTVS\\ERP_VALEO\\Protheus12\\bin\\smartclient\\smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true,
			"logFile": "${workspaceFolder}\\dap.log"
		}
	]
}

settings.json
{
    "totvsLanguageServer.launch.args": [
        "--log-file=totvsls.log",
        "--record=totvsls"
    ],
    "totvsLanguageServer.welcomePage": false,
    "totvsLanguageServer.askCompileResult": false
}

Versão do VSCODE
Version: 1.43.2 (system setup)
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by claudiohf** [comment]
![Captura de Tela 2020-10-08 às 15 57 35](https://user-images.githubusercontent.com/11929872/95501741-26b7ac00-097f-11eb-9ddc-f3a0b9a0ad67.png)

**Comment by claudiohf** [comment]
Envio imagem onde o fonte da como compilado mas nao está no RPO.

**Comment by boeirarb** [comment]
Boa Tarde Pessoal.

Precisamos de retorno pois amanha temos migração para a 12.1.27 no cliente, e precisamos compilar os fontes. Podem nos retornar e priorizar esta Issue por favor?

Rodrigo Barbosa Boeira / Coordenador de Projetos
TOTVS RIO GRANDE DO SUL 
(54) 3025-7170 / (54) 99136-4380
rodrigo.boeira@totvs.com.br

**Comment by brodao** [comment]
Ola @claudiohf 

Fiz uns testes aqui e peguei uma situação em que a configuração do _settings.json_ é ignorada.
Favor acessar a página 'Settings' e configurar conforme abaixo:

![image](https://user-images.githubusercontent.com/949914/95506613-836a9500-0986-11eb-9df2-5fc5c916a841.png)

E como tem um grande volume de arquivos, sugiro diminuir o nível de notificações.
![image](https://user-images.githubusercontent.com/949914/95506833-d5abb600-0986-11eb-99ab-41ed755e7e6a.png)

A disposição.

**Comment by brodao** [comment]
@claudiohf 

Em complemento, na hora de pesquisar no _Inspetor de Objetos_ , experimente colocar "\*sf2460\*" e acione \<tab\>.

A disposição.

**Comment by claudiohf** [comment]
[image: Captura de Tela 2020-10-08 às 17.01.27.png]
Sem sucesso:
[image: Captura de Tela 2020-10-08 às 17.02.23.png]
[image: Captura de Tela 2020-10-08 às 17.02.49.png]





___________________________
Cláudio Henrique Ferreira


Em qui., 8 de out. de 2020 às 17:02, Alan Cândido <notifications@github.com>
escreveu:

**Comment by claudiohf** [comment]
![Captura de Tela 2020-10-08 às 17 01 27](https://user-images.githubusercontent.com/11929872/95508214-0391fa00-0989-11eb-8f8d-95120f3cf190.png)
![Captura de Tela 2020-10-08 às 17 02 23](https://user-images.githubusercontent.com/11929872/95508227-0856ae00-0989-11eb-9b81-62376cbc7d88.png)
![Captura de Tela 2020-10-08 às 17 02 49](https://user-images.githubusercontent.com/11929872/95508245-0d1b6200-0989-11eb-99f9-71daff28a187.png)

Infelizmente, não funcionou @brodao

**Comment by lwtnb-wrk** [comment]
@claudiohf Envie o print com o último registro da lista de fontes compilados.
Se houver um ou mais fontes com algum problema grave no workspace o processo todo é abortado e nenhum fonte será comitado.
Já pelos prints das telas vejo que a aba Problemas apresenta mais de 2000 ocorrencias. 
Procure pelos erros FATAIS que impedem o commit de todos os fontes.

**Comment by claudiohf** [comment]
De fato @lwtnb-wrk ele abortou:
[Info  - 5:00:55 PM] Aborting end build (rollback changes).
[Error - 5:00:55 PM] One or more files have errors and/or warnings. See problems and logs for details.
[Info  - 5:00:55 PM] Compile finished.
[Info  - 5:02:03 PM] Starting object inspector.
[Info  - 5:02:03 PM] Loading objects from server.
[Info  - 5:02:05 PM] Objects loaded (Duration: 2.024000)
[Info  - 5:02:06 PM] 115154 objects successfully retrieved.
[Info  - 5:02:06 PM] Object inspector finished.


Entendo que o correto seria dar commit nos fontes que estão OK e ignorar os que estão com falhas.

Tenho 2 fontes com falha, vou remover e testar.

**Comment by claudiohf** [comment]
![Captura de Tela 2020-10-08 às 17 23 50](https://user-images.githubusercontent.com/11929872/95509560-0ee62500-098b-11eb-980c-956526ec5bc8.png)
Funcionou.

Minha sugestão então é, mesmo com erro ele dar o commit dos fontes que estão OK, como era no TDS antigo.

Obrigado pelo rápido apoio.

**Comment by brodao** [comment]
Ola @claudiohf 

Sugestão anotada.

A disposição.
