### ISSUE TITLE
Erro Compilar no MAC pasta com Acento

### ISSUE THREAD

**Issue by efdeiasoliveira** [totvs/tds-vscode#536]
**Describe the bug**
Comecei a utilizar o MAC e tenho um projeto muito grande no GIT e este projeto tem pastas com acento.

O problema que estou tendo é que no momento em que vou compilar os fontes que estão dentro de uma pasta que possui acento, o mesmo não é compilado e retorna file not found.

**To Reproduce**
Para reproduzir basta utilizar um projeto que tenho uma pasta com acento.

**Expected behavior**
O esperado é que fosse possível realizar a compilação. Pois se eu pego o caminho reportado no erro abro através do localizar do finder o sistema localiza o arquivo.

**Screenshots**
![image](https://user-images.githubusercontent.com/51671824/95086259-a717ac00-06f6-11eb-8277-7a003c244c8e.png)

**Desktop (please complete the following information):**
-MAC OS

**Comment by brodao** [comment]
Ola @efdeiasoliveira 

Favor verificar https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#pastas-com-acentua%C3%A7%C3%A3o.

A disposição

**Comment by marcosnathanqs** [comment]
Estou com mesmo problema em pastas com acentos e caracteres especiais. Quando compilo em pasta com nomes padrões funciona certinho.
