### ISSUE TITLE
Erro ao compilar workspace com um fonte vazio (sem conteúdo)

### ISSUE THREAD

**Issue by bardez** [totvs/tds-vscode#537]
Ao compilar workspace inteiro e um dos arquivos estiverem em branco, não é mostrado o erro na guia problemas do VSCODE 
![image](https://user-images.githubusercontent.com/12939672/95239995-26ce7500-07e2-11eb-828d-7d125addc04e.png)
![image](https://user-images.githubusercontent.com/12939672/95240025-3221a080-07e2-11eb-9b78-0b252b68e05d.png)
é mostrado apenas no table logs e as vezes a notificação para mostrar o table logs não aparece.

[Sugestão 1] :
Colocando o erro também na guia "PROBLEMAS" facilitaria com o uso dos filtros
![image](https://user-images.githubusercontent.com/12939672/95240349-a78d7100-07e2-11eb-9161-125c8ce8a100.png)

Ele compila todos os fontes retorna um log na guia "OUTPUT/SAÍDA" informando que houve um rollback ou seja, não compilou nada devido aquele problema no fonte:

```
[Info  - 08:52:05] Aborting end build (rollback changes).
[Error - 08:52:05] One or more files have errors and/or warnings. See problems and logs for details.
[Info  - 08:52:05] Compile finished.
```

[Sugestão 2] :
Retornar um erro um pouco mais visível aos usuários, pois a impressão que passa, é que a compilação deu sucesso apesar do arquivo em questão (como se o resto fosse compilado, apesar do problema)

**Comment by brodao** [comment]
Ola @bardez 

Arquivo vazio não representa necessariamente erro, salvo se este fonte fonte Microsiga e você não tem chave de compilação.
Favor verificar https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md

A disposição.

**Comment by brodao** [comment]
Ola @bardez 

Um amigo me lembrou, que ao compilar lotes e um dos arquivos tiver erro, todo o lote não é confirmado no RPO.
Verifique a aba "Problemas".

A disposição.

**Comment by lwtnb-wrk** [comment]
@bardez Grato pelas informações. Faremos um tratamento para apresentar este erro na guia "Problemas".

**Comment by lwtnb-wrk** [comment]
@bardez Foi liberada uma atualização que deve resolver seu problema, se após a atualização ainda tiver problemas, favor reabrir a issue e dar novos detalhes.
