### ISSUE TITLE
Ao debugar quando ocorre erro não retorna o erro log.

### ISSUE THREAD

**Issue by ofnerjulio** [totvs/tds-vscode#538]
Ao debugar qdo ocorre uma erro de variável, problema de vetor estouro de vetor.
não esta apresentando o error Log.
Informando o erro e a  linha

**Comment by lwtnb-wrk** [comment]
@ofnerjulio Descreva seu problema com mais detalhes e veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise
