### ISSUE TITLE
VsCode não compila

### ISSUE THREAD

**Issue by marivaldo3101** [totvs/tds-vscode#539]
Ola bom dia,

Ontem fiz a instalação do VsCode, porem agora quando fui compilar o fonte ele não compila fica estatico. 

Não apresenta nenhuma mensagem de erro tambem.

Versão 

![VsCodi](https://user-images.githubusercontent.com/72559440/95465967-2f45bd80-0952-11eb-9209-6e54731e6e6d.png)

**Comment by marivaldo3101** [comment]
Complementando o chamado, estava olhando uma coisa percebi que a o This Machine ID do VsCode não e o mesmo numero que esta no volume ID da maquina.
![image](https://user-images.githubusercontent.com/72559440/95484003-4db5b400-0966-11eb-9881-5a2fec4b9cd7.png)

**Comment by brodao** [comment]
Ola @marivaldo3101 

Não é para ser mesmo. Se possui uma chave gerada com esse ID, ele não é válido para o TDS-VSCode.

Quanto ao erro reportado, por gentileza faz um teste colocando a extensão em maiúsculas.

A disposição.

**Comment by marivaldo3101** [comment]
Olá boa tarde,

Estava procurando a extensão que menciona no retorno no chamado para colocar como Maiúsculas, mas não encontrei. Pode ser um pouco mais claro. Onde devo fazer essa alteração.

Muito obrigado...

**Comment by lwtnb-wrk** [comment]
@marivaldo3101 Pelo print enviado é possível ver a linha [...] Start sercure compiling extension-output-#4
Isso indica que provavelmente foi utilizado o atalho CTRL + F9 para efetuar a compilação, mas o foco estava fora do editor.
Certifique-se que o "foco" esteja no Editor que deseja compilar antes de acionar o CTRL + F9.
Veja se isso resolve seu problema

**Comment by marivaldo3101** [comment]
Ola boa tarde,

Não funcionou, mesmo fazendo a compilação como mostra a imagem. 
![image](https://user-images.githubusercontent.com/72559440/95622951-e02f8380-0a4a-11eb-9ea2-fa7090c0e604.png)

Obrigado.

**Comment by lwtnb-wrk** [comment]
@marivaldo3101 Ocorreu o mesmo erro? Depois de ter selecionado o "Compile File/Folder"?
No print só dá pra ver que a conexão foi bem sucedida, mas não mostra a compilação em si.

**Comment by marivaldo3101** [comment]
Sim ele não faz nada como se não tivesse executado nenhum comando...

**Comment by lwtnb-wrk** [comment]
@marivaldo3101 Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise então

**Comment by marivaldo3101** [comment]
Segue em anexo os arquivo solicitados
[totvsls.log](https://github.com/totvs/tds-vscode/files/5357207/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/5357208/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/5357209/totvsls_out.log)

**Comment by lwtnb-wrk** [comment]
@marivaldo3101 No 1o print dá pra ver que voce consegue acionar o comando de compilação, pois mostra que estava tentando recompilar, mas o problema era que o foco não estava no editor e por isso nao compilou corretamenete.
Ja nas outras evidencias nem aparece seque o acionamento da compilacao...
Realmente não sei o que voce esta fazendo e não sei o que sugerir mais.

**Comment by marivaldo3101** [comment]
Olá boa tarde,

Não tem a possibilidade de fazer um acesso remoto pra tentar solucionar o problema?

Obrigado

**Comment by lwtnb-wrk** [comment]
@marivaldo3101 Realmente isso não será possível.
Só conseguimos orientar e tirar dúvidas por aqui.

**Comment by lwtnb-wrk** [comment]
@marivaldo3101 Poderia gravar um video mostrando como está realizando as compilações?

**Comment by GeysonGW** [comment]
Sei que faz um tempo, mas caso alguém sofra com isso hj, no meu caso era pq o fonte estava no google drive, copiei pra minha máquina e compilou
