### ISSUE TITLE
Breakpoint condicional derruba conexão do smartclient

### ISSUE THREAD

**Issue by fwsoares** [totvs/tds-vscode#54]
bom dia,

Estou fazendo um debug e ao habilitar um breakpoint com uma expressão (SD3->D3_COD='024196001') o vs code derruba a conexão com smatclient, e não exibe nenhuma mensagem no console.
No appserver.log, ele está mostrando essas mensagens:
Thread 22964

Exception code: C0000005 ACCESS_VIOLATION

Fault address:  00D07EA0 01:00906EA0 E:\TOTVS12\Microsiga\Protheus\bin\appserver_x32\AppServer.exe

Stack Trace:

Address   Frame

00D07EA0  00000000  
	Unable to locate source line number

00C87300  00000000  
	Unable to locate source line number

00442B38  00000000  
	Unable to locate source line number

0114F2E9  00000000  
unqlite_compile_file+18D309
	Unable to locate source line number

76EFE84C  00000000  
NtSetInformationFile+C
	Unable to locate source line number

76EFE84C  00000000  
NtSetInformationFile+C
	Unable to locate source line number

742E34B9  00000000  
SetFilePointer+79
	Unable to locate source line number

76EFE63C  00000000  
NtWriteFile+C
	Unable to locate source line number

742D93D9  00000000  
WriteFile+79
	Unable to locate source line number

00C149A3  00000000  
	Unable to locate source line number

76EFE73C  00000000  
ZwAllocateVirtualMemory+C
	Unable to locate source line number

742E3791  00000000  
VirtualAlloc+41
	Unable to locate source line number

00443B9A  00000000  
	Unable to locate source line number

0044FD21  00000000  
	Unable to locate source line number

**Comment by brodao** [comment]
Efetuado testes e análise do processo de depuração e verificou-se que o problema ocorre do lado do appServer. Essa informação foi repassada aos responsáveis para análise.

**Comment by brodao** [comment]
A opção de ponto de parada condicional, será temporariamente desabilitada.

**Comment by likid** [comment]
Apenas para conhecimento, na extensão advpl-vscode eu utilizei breakpoint condicional algumas vezes sem problema. Talvez seja um problema no DAP e não no vscode ou appserver.

**Comment by lwtnb-wrk** [comment]
@likid Não posso afirmar com certeza, mas possivelmente a outra extensão emula o breakpoint condicional utilizando um breakpoint normal, mas ao receber a notificacao de parada do appserver avalia a condicao do breakpoint e decide se deve parar ou nao. Aparentemente o appserver esta preparado para receber breakpoint condicional mas ocorreu alguma condicao inesperada. Estamos trabalhando em conjunto com o time do appserver para corrigir esse problema, mas por enquanto tentaremos contornar o problema de outra forma. Grato pelas informacoes e testes

**Comment by brodao** [comment]
Problema contornado com execução de filtro no DAP.
