### ISSUE TITLE
Erro compilação fonte 4gl (LOGIX)

### ISSUE THREAD

**Issue by eduardonogueira0405** [totvs/tds-vscode#540]
Ao tentar compilar o fonte OBF0118.4gl (somente para este fonte) está ocorrendo o erro abaixo:
![image](https://user-images.githubusercontent.com/72161552/95616445-2af7ce00-0a40-11eb-84e6-80c39e12a411.png)

abaixo as primeiras linhas do fonte:
![image](https://user-images.githubusercontent.com/72161552/95616536-52e73180-0a40-11eb-9a44-0ec1bf2324f2.png)

Informações complementares:
![image](https://user-images.githubusercontent.com/72161552/95616914-fafcfa80-0a40-11eb-8065-4b3db61ba514.png)

VSCode versão 1.50.0

AT
Eduardo Nogueira

**Comment by brodao** [comment]
Pelos testes efetuados, foi detectado que o problema ocorre com uma versão especifica do appServer, cuja ocorrência não é mas reproduzida em versões mais novas.
