### ISSUE TITLE
Compilações com mais de 80 fontes

### ISSUE THREAD

**Issue by Elson1308** [totvs/tds-vscode#541]
Issue Type: <b>Bug</b>

Toda vez que compilo, folder dentro de workspace e esta possui mais que 80 fontes , sou obrigado a reiniciar o VsCod e Serviço Protheus.

Extension version: 1.0.6
VS Code version: Code 1.50.0 (93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3, 2020-10-07T06:10:52.432Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz (4 x 2100)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|10.00GB (5.17GB free)|
|Process Argv|--crash-reporter-id d5838cbe-3ac4-4c94-bec2-a20820b80aab|
|Screen Reader|no|
|VM|100%|
</details>

**Comment by lwtnb-wrk** [comment]
@Elson1308 Apenas 80 fontes não deveriam sem um problema já que efetuamos a compilação de workspaces com mais de 1000 arquivos sem problemas aqui.
Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by brodao** [comment]
Ola @Elson1308 

Experimente desativar (ou rebaixar nível) de notificações.
![image](https://user-images.githubusercontent.com/949914/96001275-3e26e700-0e0e-11eb-9931-de242755fca8.png)

A disposição.

**Comment by Elson1308** [comment]
Srs, @brodao e @lwtnb-wrk 
Obrigado pela ajuda. já estou conseguindo ver que a compilação vai até o final.
Porém de se compilar a workspace toda segue derrubando o serviço.
Mais de qualquer forma já posso dar andamento nos trabalhos.
Valew
