### ISSUE TITLE
Não Pede Usuário e Senha no Servidor

### ISSUE THREAD

**Issue by jevsoftwares** [totvs/tds-vscode#543]
@zettazt512 Favor ler https://github.com/totvs/tds-vscode/blob/dev/TROUBLESHOOTING.md 
Se nao for o caso, anexe os logs e reabra a issue

Bom dia, tentei todas as formas descritas acima mas sem sucesso. Ao conectar no servidor não está solicitando usuário e senha de acesso e por consequencia não compila.

**Comment by jevsoftwares** [comment]
![image](https://user-images.githubusercontent.com/65028697/95991939-635e2a00-0dfb-11eb-95ed-7405ffb1be82.png)

![image](https://user-images.githubusercontent.com/65028697/95992067-8a1c6080-0dfb-11eb-9ff1-b406b57fac2b.png)

![image](https://user-images.githubusercontent.com/65028697/95991492-d1eeb800-0dfa-11eb-8785-27cb84328bd0.png)

[totvsls_in.log](https://github.com/totvs/tds-vscode/files/5378361/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/5378362/totvsls_out.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/5378363/totvsls.log)

**Comment by lwtnb-wrk** [comment]
@jevsoftwares Aparentemente pelo logs enviados o RPO utilizado não contem a função necessária para autenticação e portanto não é requisitado o usuaário e senha.
O RPO é mesmo padrão TOTVS? 
Você consegue acessar esse ambiente utilizando somente um smartclient?

**Comment by jevsoftwares** [comment]
É meu ambiente de desenvolvimento local! consigo acessar normalmente.

![image](https://user-images.githubusercontent.com/65028697/95997982-64468a00-0e02-11eb-965e-7edc32e4c856.png)

**Comment by jevsoftwares** [comment]
AppServer atualizado neste momento!

![image](https://user-images.githubusercontent.com/65028697/96002430-18e2aa80-0e07-11eb-991e-5167da0f5be5.png)

De fato deu certo:
![image](https://user-images.githubusercontent.com/65028697/96002534-36b00f80-0e07-11eb-91e4-c761e6623360.png)

Obrigado!
