### ISSUE TITLE
Erro ao tentar conectar no server 

### ISSUE THREAD

**Issue by VictorBassoon** [totvs/tds-vscode#546]
Fail to parse '$totvsserver/connect' /params/connectionInfo/bSecur, expected int

**Comment by lwtnb-wrk** [comment]
@VictorBassoon Sua extensão está atualizada? Isso parece ser de uma extensão desatualizada...
Se estiver atualizada, veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.
