### ISSUE TITLE
Limpeza de arquivo Totvsls.log

### ISSUE THREAD

**Issue by Elson1308** [totvs/tds-vscode#547]
Bom dia, 
Amigos, estou tendo problema com atualizar fontes. E meu recurso atual esta sendo o o arquivo de log totvsls.log, pois a aba problemas não esta atualizando após efetuar correções.
Então ai vai, minha pergunta. Teria um forma de gerar o totvsls.log mais limpo, sem o log do que deu certo?
Pois compilando uma pasta pequena já gerou 7 mil linhas. Imaginei a hora de compilar os 1330 fontes.
Obrigado por enquanto.

**Comment by lwtnb-wrk** [comment]
@Elson1308 Não sei para que você está utilizando, mas o totvsls.log é utilizado apenas para efetuar diagnósticos de problemas no tds-vscode e por isso gera muita informação. Você deve ter habilitado ele conforme https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs e se não precisar dele pode desabilitar removendo as configurações adicionadas.
A aba "Problemas" exibe todos os problemas encontrados nos fontes que foram compilados e somente é atualizado quando os mesmos fontes são compilados sem problemas.
Descreva melhor o problema que está ocorrendo para que podemos tentar te ajudar.

**Comment by Elson1308** [comment]
@lwtnb-wrk , Na verdade estou um pouco perdido, pois tenho o seguinte cenario.
Estava com a versão do Tds 1.0.6 se não me falha, revisei os 1300 fontes, deixei zerado.
Ao tentar compilar a workspace inteira ele derruba o serviço do protheus e não da um log confiavel. Mais conseguiu compilar pasta por pasta.
Ontem atualizou para Tds 1.1 e apareceu milhares de erros/mensagens/info
Após a atualização apresentou o seguinte problema. Versão anterior eu ajustava um fonte com mensagens ou erro e a aba problemas ja atualizava, agora isso so acontece se compilar o fonte.
Estou muito preocupado e meu tempo esta correndo.

**Comment by lwtnb-wrk** [comment]
@Elson1308 Não é possível que a aba Problemas já atualizava sem que o fonte fosse compilado. Somente ao compilar um fonte enviamos novas informações para a aba Problemas.
Ao tentar compilar os  1300 fontes o AppServer esta caindo? Ou o que voce quer dizer com "serviço do protheus"?

**Comment by Elson1308** [comment]
Isso mesmo appserver, caso deseje analisar estou enviando arquivos de log.
Agradeço desde já a atenção

Elson Costa
(44) 99961-5164 (Tim - PR)
(595) 986 819 882 (Tygo- Py)
elsonalvesdacosta@gmail.com
elsoncosta@hotmail.com
twitter: @elsonacosta
Skype: elsoncosta@hotmail.com
"Tú te hace eternamente responsable de lo que cautiva. (Pequeno Príncipe)"


Em sex., 16 de out. de 2020 às 10:39, lwtnb-wrk <notifications@github.com>
escreveu:

**Comment by lwtnb-wrk** [comment]
@Elson1308 Os anexos não chegam quando voce responde apenas os emails.
Favor entrar no git e anexar os logs diretamente por la.

**Comment by Elson1308** [comment]
Segue os Anexos
[totvsls.log](https://github.com/totvs/tds-vscode/files/5392522/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/5392523/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/5392524/totvsls_out.log)

**Comment by lwtnb-wrk** [comment]
@Elson1308 Qual a build exata de seu AppServer? Você esta tentando compilar em um RPO padrão TOTVS??
Aparentemente o AppServer não está requisitando autenticação. Isso ocorre em dois casos principalmente. Ou o AppServer está desatualizado e precisa ser atualizado, ou o RPO utilizado não é padrão TOTVS e realmente não vai precisar da autenticação.

Além disso, no final da compilação, como existem erros Fatais está ocorrendo o rollback de tudo e portanto a compilação não ocorre.
É preciso arrumar os erros Fatais ou remove-los do workspace para que a compilação finalize com sucesso.
