### ISSUE TITLE
Mostrar apenas os fontes que foram compilados

### ISSUE THREAD

**Issue by Smmartinez** [totvs/tds-vscode#55]
Boa tarde!
Seria possível para quando for compilado uma pasta, ou o projeto por completo, mostrar no output um resumo com apenas os fontes que foram compilado, imagina que nesta pastas tem 20 fontes e foram alterados apenas 4, quando compilamos ele mostra a mensagem para os 20 fontes 16 com skiped e os 4 como compilados. Mas para verificar se esses 4 foram compilados fica difícil de ver no output.
Isso seria possível?

**Comment by lwtnb-wrk** [comment]
@Smmartinez Achamos que é importante ter no console as informações sobre o que ocorreu com cada fonte que passou pela compilação, mas entendemos que para um controle do que foi compilado em grande volume pode ficar dificil encontrar as informacoes. Por enquanto removi uma das linhas que apareciam no console entao cada fonte tera duas linhas indicando o inicio da compilacao e o que ocorreu com este fonte [SKIPPED], [SUCCESS] ou [WARNING], entao procurando por essas palavras chaves voce pode localizar os fontes. Vamos pensar em alguma solucao melhor quando detectarmos um volume maior de arquivos a serem compilados, mas por enquanto apenas deixaremos essas palavras chaves no output. Se tiver outras ideias de como podemos exibir essa informacoes estamos a disposicao. 
somente reforcando que esta alteracao estara disponivel apos a proxima atualizacao.
Grato pelas sugestoes e testes

**Comment by Smmartinez** [comment]
Bom dia! Acredito que dessa forma ajuda, mas o problema que vejo é que no output não tem como criar um filtro ou colocar uma palavra chave para filtrar.
Mas vou verificar assim que for liberado.
Não seria possível criar uma saída para um outro output, por exemplo hoje ele "imprime" no output ADVPL, não seria possível criar um ADVPL Success com apenas o nome do fonte? No output padrão poderia imprimir tudo. Não sei se isso é viável.

**Comment by lwtnb-wrk** [comment]
@Smmartinez não é exatamente um filtro mas com o CTRL+F voce pode localizar as palavras chaves. Vamos pensar em um jeito melhor para exibir o resultado de compilação de pastas e workspaces... 
Essa ideia de outro output era o que eu tambem estava pensando...
Enfim grato pelos testes e sugestoes.
