### ISSUE TITLE
Array não mostra no Watchs e nem console  e Loop Infinito For Next

### ISSUE THREAD

**Issue by maximinocastro** [totvs/tds-vscode#550]
Boa tarde Prezados,

Segue abaixo o erro que vem acontecendo.

![image](https://user-images.githubusercontent.com/42280023/96497211-b895a380-1220-11eb-9186-4c83c2dbbcda.png)

E além disso reparei que o For Next está apresentando erro.

**Desktop (please complete the following information):**
 Windows 64 bits

**Comment by lwtnb-wrk** [comment]
@maximinocastro duplicado de #549 favor acompanhar por esta outra issue.
