### ISSUE TITLE
Função duplicada no repositório

### ISSUE THREAD

**Issue by tijackwal** [totvs/tds-vscode#552]
Bom dia !

Erro ao excluir função duplicada do repositório em VSCODE.
Não sabemos como aconteceu, mas há dois fontes com o mesmo nome de user function M460FIM, o nome externo é diferente.
Agora não conseguimos excluir do repositório um dos fontes.
Como resolver esse problema ?

Grato.

Eduardo

**Comment by lwtnb-wrk** [comment]
@tijackwal Consegue mandar um print do "Inspetor de Função" com as duas user functions (U_M460FIM)?
Além disso nos informe a build exata do AppServer utilizado e veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by tijackwal** [comment]
Bom dia,

 

Segue print do Inspetor de funções.

 

Fiz as alterações em settings.json conforme solicitado, reiniciei o VsCode e ao recompilar o projeto gerou novamente o erro acusando função duplicada.

Não anexei os logs porque todos estão vazios: totvsls.log, totvsls_in.log e totvsls_out.log.

 

 

De: lwtnb-wrk <notifications@github.com> 
Enviada em: terça-feira, 20 de outubro de 2020 09:56
Para: totvs/tds-vscode <tds-vscode@noreply.github.com>
Cc: tijackwal <ti@jackwal.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [totvs/tds-vscode] Função duplicada no repositório (#552)

 

@tijackwal <https://github.com/tijackwal>  Consegue mandar um print do "Inspetor de Função" com as duas user functions (U_M460FIM)?
Além disso nos informe a build exata do AppServer utilizado e veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by lwtnb-wrk** [comment]
@tijackwal Por email nao chegam prints nem anexos. Favor entrar no git para anexa-los.

**Comment by tijackwal** [comment]
![Inspetor_Funcoes](https://user-images.githubusercontent.com/72088281/96601999-ee8e6280-12c8-11eb-8bc0-5212150150b3.png)

Desculpa !  Segue print agora.

Obrigado.

**Comment by lwtnb-wrk** [comment]
@tijackwal O fonte que voce esta compilando com a user function "U_M460FIM" é o "PE_M460FIM.PRW", mas ela já havia sido compilada na "M460FIM.PRW". O problema é que foi colocado um "PE_" alterando o nome do fonte. 
Voce pode ou renomear o fonte atual para "M460FIM.PRW" ou criar um fonte "M460FIM.PRW" apenas com a declaração da user function "U_M460FIM" e remover esse fonte do RPO.

**Comment by tijackwal** [comment]
Alterei o nome externo do fonte como você sugeriu, de PE_M460FIM.PRW para M460FIM.PRW e o projeto compilou com sucesso.
Muito obrigado meu amigo.
Valeu !
