### ISSUE TITLE
Erro de compilacao [FATAL] não é exibido na aba PROBLEMS e nem no LOG do AppServer

### ISSUE THREAD

**Issue by cleaneh** [totvs/tds-vscode#553]
Quando compilo fontes ADVPL, usando Build 19.3.0.6, que simulam falhas do tipo WARNING e FATAL, tem diferença de gerar os dados na aba PROBLEMS, onde os problemas do tipo [FATAL] nao sao registrados na aba PROBLEMS.

**SIMULAÇÃO:**
1) Fonte lgcompila01.prw simula erro do tipo WARNING. Se o foco atual está na aba OUTPUT e inicio a compilacao do fonte, como ocorrem inconsistencias do tipo WARNING, o foco muda pra aba PROBLEMS e as msgs de WARNING sao exibidas. **(OK)**

2) Fonte lgcompila02.prw simula erro do tipo FATAL. Se o foco atual está na aba OUTPUT e inicio a compilacao do fonte, como ocorre inconsistencia do tipo FATAL, o foco muda para aba PROBLEMS, mas a msg com o erro do tipo FATAL nao é registrada na aba PROBLEMS. **(ERRO)**

3) O mesmo ocorre tbm com a compilacao por pasta, onde o foco muda pra aba PROBLEMS e nao registra o erro [FATAL]. **(ERRO)**

4) O erro do tipo [FATAL] e alerta do tipo [WARNING] deixam de ser exibidos no LOG do AppServer na compilação pelo vscode. (ERRO)

- No caso de msg [WARNING] no Log do AppServer nao mostra nenhuma alerta.
- No caso de erro [FATAL] no Log do Appserver mostra a seguinte mensagem:
  **[WARN ][SERVER] Debugger - Rollback executed for the repository. Check IDE for details.**

**COMPORTAMENTO ESPERADO**
1) O registro de msgs do tipo WARNING e FATAL devem ambas serem registradas na aba PROBLEMS.
2) Avaliar se realmente na ocorrencia de falhas WARNING ouFATAL na compilacao via VSCODE, estas realmente devem deixar de ser geradas tbem no LOG do AppServer.

**BUILD AppServer 19.3.0.6 - Windows - 64 bits.**
[lgcompila.zip](https://github.com/totvs/tds-vscode/files/5409015/lgcompila.zip)

**Comment by DanielYampolschi** [comment]
Ola @cleaneh muito obrigado pelas informações bem detalhadas. O Problema foi reproduzido e já estamos verificando.

**Comment by DanielYampolschi** [comment]
Ola @cleaneh, esse problema de não mostrar mensagens está no servidor que envia as mensagens fora do padrão, fazendo com que o TDS não consiga "entender" a mensagem. 

Já entrei em contato com o pessoal pedindo a correção. 

De qualqueer forma fiz uma alteração no lado do TDS para tentar contornar um pouco, fazendo com que mesmo que não seja possível extrair a linha e etc, apareça uma indicação do erro. É o que é possível pelo client enquanto o servidor não corrigir as mensagens.

Mais uma vez obrigado por ter aberto a issue e pelos detalhes de como reproduzir.
