### ISSUE TITLE
Error ao aplicar um patch

### ISSUE THREAD

**Issue by CEOS-CONSULTORIA** [totvs/tds-vscode#554]
Ao aplicar um patch no VSCODE, ele apresenta o seguinte erro:

[Info  - 10:14:45] Starting apply patch.
[Info  - 10:14:45] Starting build for environment CEOS.
[Info  - 10:14:48] Applying patch file: file://192.168.1.250/Atualizacoes/2020-10-20/20-10-05_ATUALIZACAO_12.1.25_FAT_EXPEDICAO_CONTINUA/expedicao_continua_12.1.25_fat_tttp120_lg.ptm
[Error - 10:14:48] File could not be copied to the server.
[Info  - 10:14:48] Aborting end build (rollback changes).
[Info  - 10:14:48] Apply patch finished.

**Comment by brodao** [comment]
Olá @CEOS-CONSULTORIA 

Você não pode usar endereços IP. Mapeie um driver para o endereço indicado ou aplique a partir de uma pasta local.

A disposição.

**Comment by CEOS-CONSULTORIA** [comment]
obrigado @brodao, mas o erro persiste mesmo eu tentando aplicar no servidor !!

**Comment by lwtnb-wrk** [comment]
@CEOS-CONSULTORIA Qual o SO utilizado no servidor?

**Comment by CEOS-CONSULTORIA** [comment]
Windows Small Businees Server 2011 Standard !!

Obrigado

**Comment by lwtnb-wrk** [comment]
@CEOS-CONSULTORIA Temos relatos de que o tds-vscode não funciona adequadamente em SO do tipo Windows Server em geral.
O recomendado mesmo é utilizar um Windows Desktop e aplicar o patch no servidor remotamente.
Neste caso a orientação de mapear seu drive de rede continua, pois não é possível aplicar um arquivo direto de um servidor.
Favor proceder desta forma e nos informar se conseguiu aplicar o patch.
