### ISSUE TITLE
Erro ao Conectar no Servidor

### ISSUE THREAD

**Issue by fa6ricio** [totvs/tds-vscode#557]
A primeira vez que conectei no servidor conectou normalmente, só que depois de fechar o vscode e abrir novamente, mando conectar ele conecta não me pede usuário e senha, quando tento compilar me fala que tenho que logar antes, já apaguei o servidor, apaguei o token das configurações e nada, crio novo ele gera o token novamente e não loga.

**Comment by lwtnb-wrk** [comment]
@fa6ricio Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.
Qual a build exata do AppServer que esta utilizando?

**Comment by fa6ricio** [comment]
@lwtnb-wrk A build é "7.00.191205P" logs e prints no link abaixo

[Logs.zip](https://github.com/totvs/tds-vscode/files/5423104/Logs.zip)

**Comment by fa6ricio** [comment]
Era erro na base do protheus, reiniciamos o Appserver e o erro foi resolvido
