### ISSUE TITLE
Erro Windows 32BIT - "couldn't start client totvs language server"

### ISSUE THREAD

**Issue by lbbsantos** [totvs/tds-vscode#558]
Existe alguma incompatibilidade com a versão do windows 32 BIT?
Tenho duas máquinas funcionando corretamente essa 32BIT apresenta o erro:

"couldn't start client totvs language server"

**Comment by lwtnb-wrk** [comment]
@lbbsantos Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.
Em qual Sistema Operaciona 32 bit ocorre o problema?

**Comment by lbbsantos** [comment]
Windows 7 32bit

**Comment by lbbsantos** [comment]
Não gerou os arquivos de LOG.
Olha o que ocorre abaixo:
![TELA_ERRO](https://user-images.githubusercontent.com/47196493/96907092-27693b80-1471-11eb-8c4e-b469c8942bda.png)

**Comment by brodao** [comment]
Senhores,

Pelo que sei, os sub-processos do TDS VSCode são só 64 bits.
De qualquer forma, experimente remover a extensão e instalar novamente.

A disposição.

**Comment by lbbsantos** [comment]
Já reinstalei, tentei versões anteriores e nada.

**Comment by brodao** [comment]
Ola @lbbsantos 

Verifiquei nossos subprocessos e não há suporte para plataforma 32 bits.

A disposição.
