### ISSUE TITLE
User not authenticated

### ISSUE THREAD

**Issue by 22352927803** [totvs/tds-vscode#559]
**Describe the bug**
A mensagem "User not authenticated" na tentativa de executar o Debug é exibida. O mesmo problema da issues  conforme o link: https://github.com/totvs/tds-vscode/issues/265

"https://github.com/totvs/tds-vscode/issues/265"

Meu Usuário no windows é Marcos Simões com caracteres especiais e espaço, Criei um novo usuário do Windows sem acetuação e o Debug funcionou! Conforme relatos da Issue acima o problema parece ser causdo por causa do usuário do Windows, gostaria de saber se já tem solução para que eu não tenha que reconfigurar todos aplicativos da minha maquina para conseguir Debugar
![VSCODE](https://user-images.githubusercontent.com/73306339/96908918-a5c6dd00-1473-11eb-9d15-f8a075d017b1.png)

**Comment by brodao** [comment]
Duplicate #423
