### ISSUE TITLE
Falha ao compilar fontes

### ISSUE THREAD

**Issue by PedroMissaglia** [totvs/tds-vscode#560]
**Describe the bug**
Apesar de estar configurado o arquivo servers.json com os includes, a extensão está apresentando erro para compilar os fontes.
Já realizei alguns testes para corrigir o problema, porém nenhum com sucesso:

- Deletar a pasta .vscode e configurar novamente o servidor.
- Deletar os arquivos de configuração do vscode do endereço _'\AppData\Roaming\Code'_.
- Deletar as extensões adicionadas do endereço _%User%/.vscode\extensions_.
- Reinstalar o vscode.

**To Reproduce**
1. Configurar um ambiente e informar a pasta de includes.
2. Compilar um fonte.

**Expected behavior**
Esperado que apresente um erro ao compilar o fonte, informando que não está configurado o arquivo de definitions.

**Screenshots**
![image](https://user-images.githubusercontent.com/45774945/97316345-65d37180-1848-11eb-8ff4-4eb944e18fac.png)
![image](https://user-images.githubusercontent.com/45774945/97316370-6cfa7f80-1848-11eb-820a-0088344e4c45.png)

**Desktop (please complete the following information):**
 - Windows 64 bits

**Appserver (please complete the following information):**
 - Build (with date): 7.00.191205P-20201012 
 - OS/Architecture: Windows 64 bits
 - Build Version  19.3.1.0

**Comment by lwtnb-wrk** [comment]
@PedroMissaglia Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.
Além disso se possível nos envie o servers.json também.

**Comment by PedroMissaglia** [comment]
Boa tarde @lwtnb-wrk, segue arquivos solicitados. 
[servers.zip](https://github.com/totvs/tds-vscode/files/5447453/servers.zip)
[logs.zip](https://github.com/totvs/tds-vscode/files/5447454/logs.zip)

Observação: Verifiquei que ocorre as mensagens de syntax error para fontes que possuem utilização de For ou While, de arquivos com extensão tanto .prw quando .tlpp.

**Comment by lwtnb-wrk** [comment]
@PedroMissaglia Não parece haver nenhum problema pelos logs enviados. 
Existe sim um erro de syntaxe "C2003 Syntax Error" no arquivo ACPROFREPOSITORY.TLPP (Linha 110).
Se houvesse problemas de falta da pasta de include, o comando de "compile" iria falhar antes disso e nem apresentaria este erro.
Quanto ao erro, realmente o AppServer não é muito amigável ao informar apenas "C2003 Syntax Error", mas apenas apresentamos o que o AppServer nos informa...
O seu "servers.json" parece em ordem também apesar de nele haver duas pastas de include e nos logs apresenta que havia apenas uma pasta durante a chamada da compilação.
Também não localizei quaisquer referencia ao MATA010 nos logs que está no printscreen enviado no começo da issue.

**Comment by PedroMissaglia** [comment]
@lwtnb-wrk Estou enviando novos logs com a tentativa de compilação do MATA010, onde apresenta o mesmo problema:
 
[logs.zip](https://github.com/totvs/tds-vscode/files/5447755/logs.zip)

O fonte do MATA010 foi apenas um exemplo, todos os outros fontes que existem no TFS e possuem For, While também apresentam o mesmo erro.

Exemplo dos avisos de syntax:

![image](https://user-images.githubusercontent.com/45774945/97354651-7bf72700-1874-11eb-99cd-29637ece74d5.png)
![image](https://user-images.githubusercontent.com/45774945/97354688-8d403380-1874-11eb-9457-2beb1f76991f.png)

**Comment by lwtnb-wrk** [comment]
@PedroMissaglia Em qual build do AppServer você esta tendo este problema? Consegue testar com outras builds AppServers?
Novamente pelos logs não existe outro problema além do erro de compilação (C2003 Syntax Error) que o AppServer está indicando. Agora apenas no MATA010.PRX linha 131...

**Comment by lwtnb-wrk** [comment]
@PedroMissaglia Agora que reparei que no seu servers.json tem a configuração de includes no servidor também.
Neste caso ele sobrescreve o includes gerais, e por isso esta pegando apenas a pasta "C:\\include".
Você precisa das duas pastas de include? Se afirmativo, você pode ou adicionar na configuração especifica do servidor ou remove-la completamente para ele pegar as configurações gerais.

**Comment by PedroMissaglia** [comment]
Após auxílio do @lwtnb-wrk , verificamos que após a atualizar a build do appserver para a 19.3.1.1_rc1, a compilação dos fontes voltou a funcionar corretamente.
