### ISSUE TITLE
Chave de compilação - Inválida

### ISSUE THREAD

**Issue by AlexandreWP** [totvs/tds-vscode#563]
Foi solicitado uma chave de compilação ao GCAD-SP, porém após ser gerada e aplicada no VS Code a mesma chave informa ser invalida.

**To Reproduce**
1. Aplicar a chave de compilação a seguir no Plug-In na versão 1.50.1 e note que conforme o print a chave é considerada inválida.
[autoriza.zip](https://github.com/totvs/tds-vscode/files/5452307/autoriza.zip)

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/19178045/97445934-9381ee80-190c-11eb-8d64-18c81ded5e27.png)

**Desktop:**
 -  Windows 10 - 64 bits

**Appserver:**
 - Build: 7.00.191205P-20201012 - 64 bits
 - OS/Architecture: Windows 64 bits
 - Build Version 19.3.1.0

**Obs:**
- Plug-in já foi desinstalado e reinstalado.
- Já foi solicitado uma nova chave de compilação e a mesma apresentou o mesmo problema.

**Comment by lwtnb-wrk** [comment]
@AlexandreWP Tivemos um outro relato disso internamente e já estávamos investigando. Você e TOTVER?

**Comment by lwtnb-wrk** [comment]
@AlexandreWP E qual a versão do seu tds-vscode e de seu vscode?

**Comment by AlexandreWP** [comment]
@lwtnb-wrk  sou um parceiro TOTVS, atuo pela NG.

tds-vscode: 1.1.1
vscode: 1.50.1

**Comment by lwtnb-wrk** [comment]
@AlexandreWP Eu vi o problema ocorrendo na máquina de um usuário, mas não estamos reproduzindo o problema localmente.
Por enquanto o caminho mais rápido, seria retornar para a versão 1.0.6 e aplicar a chave nesta versão. Depois se quiser pode retornar para a versão atual pois a chave se mantem.
Para retornar uma versão seleciona a aba de extensões, localize o "TOTVS Developer Studio" e clique na engrenagem. No menu selecione "Install another version" e selecione a versão 1.0.6
Continuaremos a procurar a causa do problema para resolve-la, mas por enquanto esta seria a solução temporária.

**Comment by lwtnb-wrk** [comment]
@AlexandreWP Foi liberada uma atualização que deve resolver seu problema, se após a atualização ainda tiver problemas, favor reabrir a issue e dar novos detalhes.
