### ISSUE TITLE
Aborting end build (rollback changes) - Duplicated function

### ISSUE THREAD

**Issue by eicclindsa** [totvs/tds-vscode#564]
**Describe the bug**
Ao compilar todo o projeto, se ocorrer erro de Duplicated function, é feito rollback de todos os fontes que foram compilados.
Tem como fazer rollback só do que deu problema ? 

**To Reproduce**
4. veja log anexo

**Expected behavior**
Compilar os fontes que estao ok e nao fazer rollback de tudo o que foi compilado.

**Screenshots**
[vscode-rollback.txt](https://github.com/totvs/tds-vscode/files/5460817/vscode-rollback.txt)

**Desktop (please complete the following information):**
 - OS/Architecture: Windows 64 bits

**Appserver (please complete the following information):**
2020-10-14T08:31:10.186000-03:00 15528|***  TOTVS S/A  ***
***  www.totvs.com.br  ***
* TOTVS - Build 7.00.191205P - Sep 16 2020 - 22:24:24 
* Build: 64 bits
* SVN Revision: 28089
* Build Version: 19.3.0.6

**Additional context**

**Comment by lwtnb-wrk** [comment]
Geramos um VSIX versão 1.2.1 que está em Pré Release (Draft) em https://github.com/totvs/tds-vscode/releases/tag/untagged-4836c4e75f678708b252
Se quiserem/puderem baixar e instalar manualmente este VSIX para avaliar se o seu problema relatado foi solucionado, favor nos informar se está corrigido ou não para que possamos realizar a liberação oficial.
Para instalar manualmente o VSIX baixem do link acima e na aba de "Extensões" do VS Code clique em "..." e selecione "Install from VSIX" e apontem para o arquivo baixado.
