### ISSUE TITLE
Na compilação acusa existencia de fonte em PRW não existente

### ISSUE THREAD

**Issue by AlexandrePinheiroSUDJF** [totvs/tds-vscode#566]
Ao efetuar a compilação de um projeto, é apresentado erro indicando a duplicidade de Função em outro fonte, porém não existe o fonte mencionado no projeto.

Fonte indicado MRNCOM001 
Fonte Existente MRNCOM01

![image](https://user-images.githubusercontent.com/73946456/98128554-d278ec80-1e96-11eb-9a88-6f1c24da667b.png)

**Comment by lwtnb-wrk** [comment]
@AlexandrePinheiroSUDJF O que o erro indica é que a função U_MRNCOM001A foi anteriormente compilada no fonte MRNCOM001.PRW, mas agora está tentando ser compilada no fonte MRNCOM01.PRW.
Provavelmente o fonte MRNCOM001.PRW foi renomeado para MRNCOM01.PRW e por isso ocorre o erro.
O comportamento é totalmente normal e além disso a mensagem é de responsabilidade do AppServer.

**Comment by AlexandrePinheiroSUDJF** [comment]
inclui um novo PRW com o nome MRNCOM001.prw, compilei e exclui do projeto.

**Comment by lwtnb-wrk** [comment]
@AlexandrePinheiroSUDJF Depois disso conseguiu então compilar o MRNCOM01.PRW correto?
