### ISSUE TITLE
Confirmar exclusão de servidor

### ISSUE THREAD

**Issue by ratsclub** [totvs/tds-vscode#578]
**Is your feature request related to a problem? Please describe.**
Colocar um elemento de confirmação durante a exclusão de um server, pois algumas vezes acabamos por excluí-lo por errar o clique do mouse.

**Describe the solution you'd like**
Abrir algum elemento perguntando se você tem certeza ou algum botão para desfazer a ação.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/56177594/99713466-1bc66000-2a83-11eb-8477-fb0dea0412f9.png)

**Comment by lwtnb-wrk** [comment]
Geramos um VSIX versão 1.2.1 que está em Pré Release (Draft) em https://github.com/totvs/tds-vscode/releases/tag/untagged-4836c4e75f678708b252
Se quiserem/puderem baixar e instalar manualmente este VSIX para avaliar se o seu problema relatado foi solucionado, favor nos informar se está corrigido ou não para que possamos realizar a liberação oficial.
Para instalar manualmente o VSIX baixem do link acima e na aba de "Extensões" do VS Code clique em "..." e selecione "Install from VSIX" e apontem para o arquivo baixado.
