### ISSUE TITLE
Erro ao debugar

### ISSUE THREAD

**Issue by ofnerjulio** [totvs/tds-vscode#579]
Sempre que mudo um arquivo de pasta, ao tentar debugar é apresentado uma msg de erro.
![erro](https://user-images.githubusercontent.com/72528922/99853978-ba75be00-2b62-11eb-859d-2b40966d88eb.JPG)

**Comment by DanielYampolschi** [comment]
Ola @ofnerjulio se você mover o arquivo durante a depuração isso pode acontecer, pois o servidor de debug faz um mapa dos fontes no início do processo.

**Comment by lwtnb-wrk** [comment]
@ofnerjulio Eu realizei um teste aqui e ao iniciar a depuração ele localizou o arquivo mesmo movendo-o. 
Não consegui reproduzir o erro que você enviou.
Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.
Se possível envie um vídeo com o erro acontecendo também.
