### ISSUE TITLE
Extensão permite adicionar o mesmo server várias vezes

### ISSUE THREAD

**Issue by edusfc15** [totvs/tds-vscode#58]
Boa tarde,

Reporto que a extensão está permitindo adicionar o mesmo servidor várias vezes, na funcionalidade "New Server".  No TDS, existe uma validação para que isso não ocorra.

Segue gif evidenciando o problema.

![addserver](https://user-images.githubusercontent.com/13476234/58651432-b3f8e400-82e7-11e9-9efe-8c7134c6cbdb.gif)

**Comment by lwtnb-wrk** [comment]
@edusfc15 Internamente o tds-vscode atribui um ID e portanto para nossa extensão são servidores diferentes. Não queriamos limitar os desenvolvedores com muitas travas de nomes duplicados, etc. Se quiser ajudar no desenvolvimento e submeter um pull request com essa validação fique a vontade. Ficaremos felizes com a colaboração de todos tambem.

**Comment by izacsc** [comment]
Uma ideia talvez seria limpar os campos para evitar esse comportamento acidental. Mas sinceramente não vejo o motivo de ter a opção Save que não fecha a tela. Raramente incluo dois servidores no mesmo momento ( a não ser uma migração de ferramenta)

**Comment by lwtnb-wrk** [comment]
@edusfc15 @izacsc As implementacoes de melhorias relacionadas a usabilidade UX que envolvam apenas alteracoes no tds-vscode (sem necessidade de alterar o Language Server ou Debug Adapter) vão ser direcionadas ao projeto https://github.com/totvs/tds-vscode/projects/3 onde qualquer desenvolvedor podera pegar a issue e submeter uma "pull request". Enquanto tivermos um backlog para resolver essas issues ficarao para um momento posterior. Grato pelas sugestoes!
