### ISSUE TITLE
Erro ao gerar client WS Protheus

### ISSUE THREAD

**Issue by RodrigoGarbi** [totvs/tds-vscode#582]
Erro ao criar client WebService SOAP.
URL do WSDL: http://homologacao.smartquestion.com.br/zda/ws/WsSmartQuestionV17?wsdl 

AppServer apresenta o seguinte erro:
```
**Stack : 
String size overflow! in file d:\bamboo\xml-data\build-dir\tp11-of19310-tecxwin64\lib_base\stringz.hpp at line 994
 on UPDATEIO(XMLCSVCS.PRW) 12/06/2020 18:03:23 line : 3260**

```

**Desktop (please complete the following information):**
- OS/Architecture: Windows 10 Pro 64 bits
- VsCode 1.51.1 

**Appserver (please complete the following information):**
 - Build (with date): Build 7.00.191205P - Oct 29 2020 - 11:38:16 
 - OS/Architecture: Windows Server 2016 64 Bits
 - Build Version: 19.3.1.1

**Comment by brodao** [comment]
Olá @RodrigoGarbi 

O TDS-VSCode é apenas uma interface que solicita ao _appServer_ a geração do cliente WS. 
Este erro ocorre porque o código gerado esta estourando o limite de tamanho de strings do _appServer_.

Veja [String size overflow](https://tdn.totvs.com/display/tec/String+size+overflow).

A disposição.
