### ISSUE TITLE
Erro ao tentar debugar

### ISSUE THREAD

**Issue by danivaladao** [totvs/tds-vscode#583]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS/Architecture: [e.g. Windows 64 bits]

**Appserver (please complete the following information):**
 - Build (with date): [e.g. Build 7.00.170117A - Jun 28 2019 - 11:16:56]
 - OS/Architecture: [e.g. Linux 64 bits Ubuntu]
 - Build Version [e.g. 17.3.0.13]

**Additional context**

Mensagem ao tentar devulgar um fonte: user not authenticated. Please connect/recconet to a server

**Comment by lwtnb-wrk** [comment]
@danivaladao Seu nome de usuário contem algum tipo de acentuação? Se afirmativo, é realmente um bug e será corrigido com a próxima atualização.
Se não for isso, veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analises.

**Comment by lwtnb-wrk** [comment]
Geramos um VSIX versão 1.2.1 que está em Pré Release (Draft) em https://github.com/totvs/tds-vscode/releases/tag/1.2.1
Se quiserem/puderem baixar e instalar manualmente este VSIX para avaliar se o seu problema relatado foi solucionado, favor nos informar se está corrigido ou não para que possamos realizar a liberação oficial.
Para instalar manualmente o VSIX baixem do link acima e na aba de "Extensões" do VS Code clique em "..." e selecione "Install from VSIX" e apontem para o arquivo baixado.

**Comment by lwtnb-wrk** [comment]
@danivaladao Atualize a extensão para a versão 1.2.1 e se o problema continuar ocorrendo abra um novo chamado
