### ISSUE TITLE
Configuração  para debug no Tcloud VSCODE

### ISSUE THREAD

**Issue by MILLE2020** [totvs/tds-vscode#585]
Boa  Tarde!

Pessoal  gostaria  de pedir  uma  ajuda  quanto  a questão  de Debug  em ambiente Tcloud  abri um chamado porem 
me encaminharam para  este GITHUB  sendo  que não consigo de maneira nenhuma  realizar  o debug  neste  ambiente  somente  in loco em uma replicada do meu ambiente o que nem sempre  e legal ou possível de se  ter. 
Alguém já passou por isso?

**Comment by lwtnb-wrk** [comment]
@MILLE2020 São muitas variáveis envolvidas e geralmente um ambiente TCloud possui configurações diferenciadas.
Esse ambiente TCloud é de produção, homologação ou desenvolvimento?
Que tipo de problema está ocorrendo?

**Comment by MILLE2020** [comment]
Olá  a principio estou  tentando conectar  no ambiente de produção para  realizar um debug   o erro em questão é que ele nao consegue se conectar  
 abaixo a  configuração do server 

"connectedServer": {},
	"configurations": [
		{
			"id": "zuy9yq7od09khho6yorqybgqgojak8",
			"type": "totvs_server_protheus",
			"name": "lp",
			"port": 6000,
			"address": "empresa.protheus.cloudtotvs.com.br",
			"buildVersion": "",
			"secure": 0,
			"includes": [
				"D:\\TOTVS1217\\Protheus\\include"
			]

**Comment by brodao** [comment]
![image](https://user-images.githubusercontent.com/949914/100278517-c3400880-2f43-11eb-8ff5-414014640cc5.png)


Detalhes: https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md

**Comment by brodao** [comment]
Foi-nos passado a pouco, pelo pessoal do TCloud que:

Clientes TCloud : Os ambientes que estão no TCloud em produção são bloqueados para depuração. Promova o RPO para DEV e use esse ambiente, e se necessário, promova-o de volta para produção. Para detalhes, entre em contato com o suporte do TCloud.

Já esta documentado em nosso ramo DEV e em breve passará para o MASTER.

A disposição.

**Comment by lwtnb-wrk** [comment]
Outro ponto importante é que os ambientes no TCloud estão configurados com balanceamento de carga (Master/Slave).
Mesmo que o TCloud aprove e libere o acesso de depuração no ambiente de Produção peça a informação que qual é a porta para acesso direto a um dos Slaves, pois também não é possível depurar um servidor configurado como Master.
