### ISSUE TITLE
Depuração Schedule

### ISSUE THREAD

**Issue by Billo21** [totvs/tds-vscode#587]
Na tentativa de depuração no Vscode para um schedule, a depuração não para nos pontos de paradas.

1° Criar um schedule qualquer customizado.
2° Iniciar a depuração via SIGACFG.
3° Entrar no schedule 
4° Iniciar a aplicação.

Windows 
SQL
A partir da versão Protheus 12.1.25
Vscode v1.2.0

***  TOTVS S/A  ***
***  www.totvs.com.br  ***
* TOTVS - Build 7.00.191205P - Nov 12 2020 - 19:47:23
* Build: 64 bits
* SVN Revision: 28706
* Build Version: 19.3.1.2_rc2

smartclient 
19.3.0.9

**Comment by brodao** [comment]
@Billo21 

Temos conhecimento desta ocorrência e já estamos trabalhando na solução.

Como paliativo:

- na sessão [onStart] coloque o "refreshRate" em 60 e reinicie o server;
- proceda como indicado em [Depuração de serviços (jobs, webservice, rest, rpc e assemelhados)](https://github.com/totvs/tds-vscode/blob/dev/docs/debugger.md#depura%C3%A7%C3%A3o-de-servi%C3%A7os-jobs-webservice-rest-rpc-e-assemelhados)
- compile um fonte (para derrubar todas os jobs)
- ATENÇÃO: inicie o processo de depuração antes que o "refreshRate" vença e reinicie os jobs.

Tenha um pouco de paciência. Você pode diminuir ou aumentar o "refreshRate" conforme suas necessidades.

A disposição.

**Comment by brodao** [comment]
Foi documentado os procedimentos necessários para a depuração de 
[serviços e _jobs_](https://github.com/totvs/tds-vscode/blob/dev/docs/debugger.md#depura%C3%A7%C3%A3o-de-servi%C3%A7os-jobs)
