### ISSUE TITLE
Opção para não reconectar automaticamente quando abrir o VSCode.

### ISSUE THREAD

**Issue by jvvasquesn** [totvs/tds-vscode#588]
Seria muito interessante, pra mim pelo menos, uma opção que o VSCode não se conectasse ao ultimo Appserver utilizado, pois a cada dia estou em um cliente e quando abro ele fica tentando se conectar so que não estou no mesmo cliente, nem mesma rede, e as vezes demora para dar erro da tentativa de conexão, muitas vezes tento que fechar e abrir VSCode para tentar se conectar ao Appserver que preciso.

Obrigado!

**Comment by lwtnb-wrk** [comment]
@jvvasquesn A opção "Reconnect Last Server" nos "Settings" já faz isso.

**Comment by jvvasquesn** [comment]
Desculpe, mas poderia me mostrar como configuro, por favor?

Em sex., 27 de nov. de 2020 às 06:41, lwtnb-wrk <notifications@github.com>
escreveu:

**Comment by lwtnb-wrk** [comment]
@jvvasquesn Procure pela opção "Reconnect Last Server" nos "Settings" da extensão "tds-vscode" no VS Code e desmarque essa opção.
Para entender mais sobre "Settings" leia a documentação do VS Code em https://code.visualstudio.com/docs/getstarted/settings

**Comment by jvvasquesn** [comment]
Muito obrigado.

Em sex., 27 de nov. de 2020 às 12:20, lwtnb-wrk <notifications@github.com>
escreveu:
