### ISSUE TITLE
Informar parâmetros para debugar ponto de Entrada do LOJA701

### ISSUE THREAD

**Issue by amtakeshima** [totvs/tds-vscode#589]
Bom dia
Estou precisando debugar um ponto de Entrada LJ7001 na rotina do LOJA701.  Para isso é necessário configurar a estação onde vou debugar como se fosse um "Caixa" - no TDS / Atalho do SmartClient é informado além do caminho, os parâmetros. Por Exemplo: C:\PROTHEUS\smartclient_V25\smartclient.exe -m -p=sigafat -c=tcp -e=DESENV01 -a= -a=005
No VSCode, onde posso informar estes parâmetros, pois sem ele o ponto de entrada não passa pela rotina LJ701.
Att
Adilson Takeshima

**Comment by lwtnb-wrk** [comment]
@amtakeshima Só para ficar claro, você precisa passar dois parâmetros? Sendo o primeiro "vazio" e o segundo 005?

**Comment by amtakeshima** [comment]
Boa tarde, Obrigado pelo retorno.

O problema é que o ponto de entrada LJ7001, não passa pela rotina LJ701 - Venda Diretas, se a estação (onde vou debugar) não possuir os parâmetros como acesso de "Caixa".  Como relatei, no TDS - para execução do debug, deveria ser informado os parâmetros com o smartclient para executar. No VSCode, já tentei informar o parâmetro na linha de chamada (Launch), mas também não funcionou.

**Comment by amtakeshima** [comment]
Ainda sem solucao

**Comment by lwtnb-wrk** [comment]
@amtakeshima Quais os parametros que voce precisa passar para o SC?

**Comment by lwtnb-wrk** [comment]
@amtakeshima Realmente temos problemas na passagem de parametros pela caixa de seleção do tds-vscode, mas editando o "launch.json" é possivel passar os parametros necessario.
Na visão de Depuração clique na engrenagem para editar o "launch.json" e localize a configuração que está utilizando para depurar.
Provavelmente deve existir a configuração de "program": "${command:AskForProgramName}", altere para o progama que deseja executar como o SIGAFAT.
Em seguida adicione o "programArguments": [ "", "005" ],
*** Se o "programArguments" for a ultima linha da configuração remova a ultima "," ***
Deve ficar algo semelhante a:
...
			"name": "Minha configuração de Debug",
			"program": "SIGAFAT",
			"programArguments": [
				"",
				"005"
			],
			"cwb": "${workspaceFolder}",
...
Veja isso resolve o seu problema por enquanto, pois ja estamos revendo o processo de passagem de parametros para o Smartclient.

**Comment by raulv329** [comment]
Bom dia, só verificando se ficou claro, Eu gostaria de passar como parametro o -A= -A=003 que é o recomendado pelo pessoal do SIGALOJA para eu conseguir manter a conexão com a minha impressora de cupom na tag "programArguments" eu estou passando:
"programArguments": [
				"${command:AskForProgramArguments}",				
				"-M",			
				"-A=",				
				"-A=003",				
			],

Pórem não está dando certo, não consigo finalizar as vendas no modo debug. Outra observação interessante é que quando eu abro o meu smartclient sem o modo debug, eu consigo finalizar as vendas normalmente, mas com o Debug, não.

![Screenshot 2024-04-01 112104](https://github.com/totvs/tds-vscode/assets/75450869/2bab70f8-24c8-466a-a155-9e339b3e9d77)
![Screenshot 2024-04-01 112300](https://github.com/totvs/tds-vscode/assets/75450869/b138b9a0-f0a7-43c3-8ff1-5fe7316eaa4a)
