### ISSUE TITLE
Depurador não atualiza as variáveis 

### ISSUE THREAD

**Issue by fsbarbosa90** [totvs/tds-vscode#59]
Olá.

Estava testando o advpl no vscode, porem ao realizar um debug e fazer testes para verificar os dados que contem nas variáveis, notei que quando alteramos o conteúdo da variável via console do depurador na aba das variáveis e de monitoramento não atualiza os dados. 
![teste prw - MyProjects - Visual Studio Code](https://user-images.githubusercontent.com/20998140/58714570-60e06900-839b-11e9-9db0-9981cfdc14ea.png)

**Comment by DanielYampolschi** [comment]
Ola @fsbarbosa90 , já percebemos também esse comportamento e estamos analisando, temos a issue #31 que trata do mesmo assunto e vamos acompanhar por lá ok? De qualquer forma, obrigado pelo aviso.

**Comment by fsbarbosa90** [comment]
Opa Show obrigado @DanielYampolschi!
