### ISSUE TITLE
[4GL][TDSVsCode 1.2.1] Variáveis Array de Record não tem valores visualizados no DEBUG 

### ISSUE THREAD

**Issue by cleaneh** [totvs/tds-vscode#590]
**[testes realizados com as seguintes Versoes TDS Vscode: 1.2.0 e 1.2.1 (pre-release)]
[modular1.zip](https://github.com/totvs/tds-vscode/files/5609390/modular1.zip)

**

**Describe the bug**
Ao tentar acionar o DEBUG de um código 4GL que tenha variáveis modulares do tipo ARRAY OF RECORD, os valores deste tipo de variável nao é possivel visualizar na secao WATCH, VARIABLES ou com posicionamento do mouse sobre a variavel durante o DEBUG.

**To Reproduce**
1. Compilar o fonte **modular1.4gl** (anexo) e executar incluindo um breakpoint na ultima linha de instrução (onde tem a chamada da funcao CONOUT).
2. Executar o programa **modular1.4gl** e qdo parar no breakpoint tentar visualizar o conteudo da variavel modular **ma_lista**
3. O conteúdo da variavel array **ma_texto** que foi definida com estrutura simples é possível visualizar normalmente, sendo problema apenas para ARRAY OF RECORD.

**Expected behavior**
Exibir os dados de variaveis array of record durante o debug.

**Appserver (please complete the following information):**
* TOTVS - Build 7.00.131227A - Nov 20 2020 - 20:58:35
* Build: 32 bits
* SVN Revision: 28794
* Build Version: 13.1.3.52_RC1

**Comment by brodao** [comment]
Efetuado a correção no registro de novos servidores, adicionando-se a seleção do tipo de servidor.

Para servidores *LOGIX* registrados em versões anteriores a 1.2.2, executar os procedimentos:
- abra o arquivo `servers.json` em modo texto;
![image](https://user-images.githubusercontent.com/949914/101778759-0cab5e80-3ad3-11eb-9205-cb58497bf7e1.png)
- ajuste o atributo ``savedTokens`` com uma lista vazia;
![image](https://user-images.githubusercontent.com/949914/101779273-d0c4c900-3ad3-11eb-9d46-9fce71577b31.png)
- localize a definição do servidor LOGIX; e ajuste o atributo ``type`` para ``totvs_server_logix``;
![image](https://user-images.githubusercontent.com/949914/101779014-7592d680-3ad3-11eb-9629-25cb1e1e0713.png)

Caso esteja utilizando versão do *TDS-VSCode* anterior a 1.2.2, você pode usar os procedimentos acima como paliativo e após registrar um novo servidor Logix, ajustar o atributo ``type`` conforme acima indicado.

A disposição.

**Comment by brodao** [comment]
@cleaneh 

Disponibilizei uma RC com essa correção, se puder efetuar testes agradeço.

https://drive.google.com/file/d/1FjWIqO-7Q33cqR8gsFsi7-PxBgCIibD_/view?usp=sharing

A disposição.

**Comment by cleaneh** [comment]
@brodao, boa tarde. 
O problema persiste e ainda nao é possível visualizar o conteúdo de variáveis "array of record".

![image](https://user-images.githubusercontent.com/66372768/104227759-a5156580-5428-11eb-89aa-9780c679a1e3.png)

Foi instalada versao RC disponibilizada e o TYPE dos servers foi ajustado e tbem limpa lista savedTokens.

No Debug o array modular ainda fica inacessivel para visualizacao:

![image](https://user-images.githubusercontent.com/66372768/104227969-f160a580-5428-11eb-9519-558f1f9fb6eb.png)

**Comment by brodao** [comment]
Efetuado testes e o mesmo ocorre somente com servidor 7.00.131227A. 
Aberto chamado interno para a equipe de servidores.
