### ISSUE TITLE
Error ao aplicar Patch

### ISSUE THREAD

**Issue by yurysilva** [totvs/tds-vscode#593]
**Describe the bug**
Na empresa estamos com uma base de teste da release 25 para fazer migração, ao tentar compilar um patch no vscode ele da um error, não possivelmente por erro de configuração, sendo que acho que fiz certo, pois uns programas de teste rodaram e ao chamar o SIGAMDI ele faz a chamada sem problemas algum, não saberia dizer o que há de errado.

**To Reproduce**
1- Vou na configuração do servidos;
2- Clico o botão direito e seleciono a opção de aplicar patch;
2- Procuro a opção de correção enviada pela totvs para aplicação do recurso;
3- Então aperto para aplicar a patch.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/52840612/100900689-d867ea80-34a1-11eb-8c61-90dcc0f24080.png)

**Desktop (please complete the following information):**
 - Windows Server 2012

**Comment by lwtnb-wrk** [comment]
@yurysilva Não é possível aplicar um patch usando um caminho de rede diretamente. Mapeie um drive e utilize esse drive mapeado para acessar o arquivo.
Outro ponto é que não garantimos o funcionamento do tds-vscode em ambiente com Windows Server, pois ele não possui diversos drivers que existem nos ambientes Windows Desktop.
Realize a aplicação de patch de um Windows Desktop e com um drive mapeado. 
Se nessa situação você não conseguir aplicar o patch, reabra o chamado.
