### ISSUE TITLE
MultiThread

### ISSUE THREAD

**Issue by ofnerjulio** [totvs/tds-vscode#594]
Não consigo debugar uma rotina simples que roda no meu ambiente é como se o MultiThread  não funcioan-se.

Mesmo habilitando o "enableMultiThread": true,

**Comment by lwtnb-wrk** [comment]
@ofnerjulio Poderia dar mais detalhes do que está tentando fazer? 
Por que esta usando o enableMultiThread? Está tentado depurar Jobs, Schedeullers, WebServcices ou Rest?
Neste tipo de situação a depuração funciona de uma maneira diferente mesmo. 
Veja maiores informações em https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md

**Comment by brodao** [comment]
Ola @ofnerjulio 

Em complemento ao Leo, veja [Depuração de serviços (jobs)](https://github.com/totvs/tds-vscode/blob/dev/docs/debugger.md#depura%C3%A7%C3%A3o-de-servi%C3%A7os-jobs), pois há informações mais atuais.

A disposição.
