### ISSUE TITLE
BuildKillusers=1 com debug em andamento, VSCODE não derruba e apresenta uma mensagem 

### ISSUE THREAD

**Issue by charlesreitz** [totvs/tds-vscode#598]
Ao executar o VSCODE em execução em modo debug (smartclient aberto), quando mandava compilar e a chave BUILDKILLUSERS=1  (ativa) ele derrubava e compilava, agora está apresentando a seguinte mensagem ao tentar fazer esse processo. 

![image](https://user-images.githubusercontent.com/1248135/101780388-42e9dd80-3ad5-11eb-9a5c-5215e557ed80.png)

**Comment by brodao** [comment]
@charlesreitz 

Você precisa finalizar a depuração primeiro. Ao forçar a derrubada da depuração via _appServer_,em determinadas situações, era necessário efetuar a reconexão. 

A disposição.

**Comment by charlesreitz** [comment]
@brodao  entendo, mas era um facilitado  :( 

Obrigado,

**Comment by lwtnb-wrk** [comment]
@charlesreitz Só para complementar a informação do @brodao, infelizmente algum bug do AppServer (algumas builds) está causando um crash, então fizemos essa proteção do nosso lado para evitar esse crash. Como não temos como isolar apenas uma build do AppServer tivermos que travar para todos.

**Comment by charlesreitz** [comment]
@brodao  e @lwtnb-wrk  entendo, o problema é que ele está ficando travado  ( VSCODE ), dando sempre a mesma mensagem, as vezes preciso fechar o vscode ou parar o appserver e subir novamente para conseguir fazer uma nova compilação. 

Mesmo eu parando o DEBUG começa a apresentar esses problemas, ocasionando um impeditivo para eu continuar com meus testes pois não consigo compilar de forma ágil . 

![image](https://user-images.githubusercontent.com/1248135/102089709-5a89d480-3dfb-11eb-83bf-c3d7486afe48.png)
![image](https://user-images.githubusercontent.com/1248135/102089803-77bea300-3dfb-11eb-8ca3-d3164dbe6dfd.png)

Observa que ele apresenta que foi compilado, mas não apresenta os fontes.

**Comment by lwtnb-wrk** [comment]
@charlesreitz Essas telas apresentam que o "fonte" está dando SKIPPED, mas isso está ocorrendo pois o "foco" está em outra aba e não no Editor que está com o fonte aberto. Provavelmente está tentando compilar a aba de Problems ou Output. É uma coisa do VS Code, não sei se conseguimos mudar isso.
Enfim, eu testei novamente aqui e ao tentar compilar com um Debug ativo a mensagem de que a operação não é permitida foi exibida corretamente e ao parar o Debug clicando em Stop, consegui compilar o fonte sem problemas.
