### ISSUE TITLE
Erro de compilação: Supported data scope

### ISSUE THREAD

**Issue by DouglasCitopharma** [totvs/tds-vscode#599]
Baixei o fonte padrão MATR968.PRW para realizar algumas customizações no mesmo, mas ao tentar compilar o relatório no meu ambiente é apresentado o erro de Supported data scope na linha 1655.
![erro tds](https://user-images.githubusercontent.com/75810332/101825649-a5120500-3b0c-11eb-9ab7-cb5ecdd94675.JPG)

[matr968.txt](https://github.com/totvs/tds-vscode/files/5675448/matr968.txt)

**Comment by lwtnb-wrk** [comment]
@DouglasCitopharma Qual a versão/build do AppServer que está utilizando? E versão/build do RPO?

**Comment by DouglasCitopharma** [comment]
Boa noite!

Dados do Server 

Versão: TOTVS Varejo
Build AppServer: 7.00.191205P-20201029 - 64 bits
Nome do servidor: 108598-CORE_INS
Sistema operacional: Windows Server 2016
Appserver version: 19.3.1.1
Build DBAccess: 20200606-20201012
Release do RPO:  12.1.025
Release do dicionário: 12.1.025
Local files: ctree
License server: 2014 - 3.2.0
DB DataBase: MSSQL
DB API Build: 20200606-20201012


Versão da Lib:20201123
Data da Lib: 20201130_153311
Commit ID:dafd6a2a9f383c9a31885287d7aaf209b41d5c2c

**Comment by lwtnb-wrk** [comment]
@DouglasCitopharma Não consegui compilar exatamente o arquivo enviado pois não tenho o .CH necessário, mas criei uma classe com a mesma definição de atributo e não tive problemas para compilar. Você pode fazer um teste similar e isolar somente a classe e compilar?
E notei que o SO é um Windows Server 2016, mas isso é apenas o servidor ou você esta com o tds-vscode rodando nesta mesma máquina? Temos diversos relatos de problemas que ocorrem em SO do tipo Windows Server, então se estiver com o tds-vscode rodando nesta máquina, isso pode ser o problema e você deve instalar tds-vscode em um Windows Desktop para poder compilar.

**Comment by brodao** [comment]
@DouglasCitopharma ,

Verifique se esta com os arquivos de definição (ch) atualizados.

**Comment by DouglasCitopharma** [comment]
Bom dia!

@lwtnb-wrk, obrigado pelo apoio.

@brodao , após atualizar os includes, esse erro não mais ocorreu. Mas ainda não consegui compilar o fonte.

Irei fechar este tópico visto que a atualização dos includes resolveu o problema e irei abrir um novo para o problema que estou tendo agora.

Mais uma vez, obrigado a todos pelo apoio.

**Comment by dannielnotfound** [comment]
Alguem consegue me fornecer o fonte MATR968 também?
