### ISSUE TITLE
Erro ao utilizar pasta com espaços e caracteres acentuados

### ISSUE THREAD

**Issue by izacsc** [totvs/tds-vscode#6]
![image](https://user-images.githubusercontent.com/423449/57780713-35a11d00-76ff-11e9-9cc9-8c15b9b49bb0.png)

(   0.405s) [querydb         ]msg_lsp_initialize_requ:496   | ABORT: Unable to find path c:/TFS/Protheus Padrão/Master/GFE/Programas

**Comment by matheus-sales** [comment]
Izac, já tivemos um reporte desse a algum tempo atrás, tínhamos resolvido, mas vamos analisar novamente. 

Obrigado.

**Comment by lwtnb-wrk** [comment]
Identificamos o erro e já estamos providenciando sua correção. Esta situação difere apenas que nessas situação a pasta onde o vscode esta iniciando contem acentuação. Tinhamos tratado as situações onde as pastas a partir do workspace continham acentuação. De qualquer forma na próxima versão já devemos disponibilizar a correção. Grato por apontar o problema.

**Comment by izacsc** [comment]
@matheus-sales eu vi que você fechou a issue mas o erro ainda persiste... vocês liberaram uma nova versão? 
Geralmente só fecham as issues com a liberação das novas versões. ( dica se não conhecem ainda https://help.github.com/en/articles/closing-issues-using-keywords )

**Comment by matheus-sales** [comment]
> @matheus-sales eu vi que você fechou a issue mas o erro ainda persiste... vocês liberaram uma nova versão?
> Geralmente só fecham as issues com a liberação das novas versões. ( dica se não conhecem ainda https://help.github.com/en/articles/closing-issues-using-keywords )

Geramos uma versão mas ainda não foi liberada para todos. Estamos testando/estabilizando para poder liberar. 

Obrigado pela dica

**Comment by likid** [comment]
Matheus, tem extensões que uso que as vezes liberam 2, 3 versões no mesmo dia, o vscode por ter facilidade de retornar a versão anterior e pelo fato deste projeto estar no github, seria interessante vocês liberarem mais versões, mesmo que seja uma por dia, assim podemos testar e auxiliar melhor vocês no desenvolvimento.

**Comment by matheus-sales** [comment]
@likid Vamos discutir isso internamente pra decidir se faremos isso. Talvez uma liberação diária ou a cada 2 dias já seria bom.

Obrigado.

**Comment by iurycardoso** [comment]
Existe um erro parecido na config do launch.json, onde o "smartclientBin": "C:\\TOTVS 12\\ se contiver espaço no nome da pasta, ao debugar apresenta erro na abertura do smartclient.
