### ISSUE TITLE
Gerar saída de instruções dentro console do depurador

### ISSUE THREAD

**Issue by fsbarbosa90** [totvs/tds-vscode#60]
Olá.

Gostaria de verificar se é possível criar alguma coisa tipo System.out.println() do java, aonde ao invés de sair no console do appserver, os dados seriam gerados no console do depurado.

Desde de já agradeço a atenção.

![New Issue · totvstds-vscode - Google Chrome](https://user-images.githubusercontent.com/20998140/58714839-ff6cca00-839b-11e9-917f-f89e9f155633.png)

**Comment by izacsc** [comment]
Olha, não sei se conhecem, mas o DAP ( Debug adapter protocol) suporta Logpoints, que é como se fosse um breakpoint mas que não para, somente registra uma mensagem. Acredito que esteja relacionado à issue.

https://code.visualstudio.com/blogs/2018/07/12/introducing-logpoints-and-auto-attach#_introducing-logpoints

**Comment by DanielYampolschi** [comment]
Obrigado @fsbarbosa90 e @izacsc pelas sugestoes, vamos verificar essa funcionalidade e implementa-la assim que possivel.

**Comment by ricardomansano** [comment]
Boa tarde  @fsbarbosa90, só pra eu entender, tua ideia seria ter uma função sysOut(), parecida com a Conout() que exibiria os valores no console do VS? Se falei besteira me corrige.

**Comment by fsbarbosa90** [comment]
Boa tarde.
@ricardomansano isso mesmo, ao invés de imprimir no console do appserver do protheus, ira imprimir dentro do console do VS, exatamente igual a função sysOut().

**Comment by ricardomansano** [comment]
@fsbarbosa90 , show, a ideia é bem bacana, vamos estudar uma maneira de manter a segurança da informação trafegada, garantindo que não "vaze" entre threads e vamos implementar. Ainda temos umas issues de bug, acabando essa entra na fila. Grato

**Comment by fsbarbosa90** [comment]
Opa, show eu e minha equipe de developer iremos curtir muito isso. Pois facilita o debug do fonte, com o conout temos que parar um serviço, subir em console e acompanhar no lado do servidor a impressão dos resultados, sem contar que o conout pesa um pouco a aplicação. Grato

**Comment by brodao** [comment]
Será verificado a possibilidade de implementar esse recurso direto no VSCode, caso contrário, a implementação dependerá da equipe do AppServer.

**Comment by DanielYampolschi** [comment]
implementado via uso da funcionalidade logpoint do VsCode

**Comment by brodao** [comment]
Veja detalhes em
https://github.com/totvs/tds-vscode/wiki/Debug-Console-configura%C3%A7%C3%A3o-visual

[:>} Alan Cândido ><>


*Especialista de Pesquisa e DesenvolvimentoExpert Research and Development*
.[====].[====].(----).(----).\___/.[___].]@|--Y\_
 _o__o___o__o___o__o___o__o___o_o___o_o___O___oo_\


Em seg, 1 de jul de 2019 às 15:33, DanielYampolschi <
notifications@github.com> escreveu:

**Comment by fsbarbosa90** [comment]
Boa dia.

Pelo que entendi ele vai sair tudo no console? Como faço por exemplo para colocar uma mensagem para dizer que o sistema passou por ali tipo sysOut("PASSOU AQUI")

**Comment by brodao** [comment]
Define um logPoint.
Detalhes em https://code.visualstudio.com/docs/editor/debugging#_logpoints

[:>} Alan Cândido ><>


*Especialista de Pesquisa e DesenvolvimentoExpert Research and Development*
.[====].[====].(----).(----).\___/.[___].]@|--Y\_
 _o__o___o__o___o__o___o__o___o_o___o_o___O___oo_\


Em ter, 2 de jul de 2019 às 10:42, Fernando Souza Barbosa <
notifications@github.com> escreveu:

**Comment by fsbarbosa90** [comment]
Entendi, vou testar vlw

**Comment by edusfc15** [comment]
Pessoal, 

vocês conseguem disponibilizar um exemplo do uso dessa funcionalidade?

tentei aqui seguindo a documentação enviada mas não consegui,


![logpoints](https://user-images.githubusercontent.com/13476234/61001316-c8dc8480-a335-11e9-905c-3ee9969d14c1.gif)

Grato.

**Comment by lwtnb-wrk** [comment]
@edusfc15 Eu fiz um teste aqui e reparei que quando passo por um logpoint usando os Steps (F10) a mensagem nao era logada. Somente quando eu passei direto Continue (F5) ele logou a mensagem. Veja se este é seu caso. Coloque um breakpoint na linha 143 por exemplo e ao inves de F10 use o F5 entre os breakpoints...

**Comment by edusfc15** [comment]
@lwtnb-wrk matou a charada.

Realmente se usar o F10 ele não  loga.
Consegui aqui.
Valeu.

**Comment by danielscheeren** [comment]
Pessoal.

Testei os logpoits e funcionam muito bem para textos. Conforme a documentação seria possível também exibir variáveis utilizando chave {}, porém não obtive sucesso.
Alguém conseguiu fazer uso dessa forma?

![image](https://github.com/totvs/tds-vscode/assets/45018228/9e42505d-4f68-4da2-a79b-9d09ddc5fe15)

Grato!

**Comment by lwtnb-wrk** [comment]
@danielscheeren Grato por avisar. Testei aqui e realmente não funcionou como deveria, mas já estou revendo essa questão.
Vou fechar essa issue pois ela é bem antiga, mas peço que aguarde a próxima liberação e se o problema não estiver resolvido, abra uma nova issue com o máximo de detalhe possível.
