### ISSUE TITLE
PATCH emergencial sendo gerado com erro. Error Loading TLPP RPO.

### ISSUE THREAD

**Issue by FelipeDuarteLuna** [totvs/tds-vscode#600]
Bom dia,

Realizei a geração de uma PATCH emergencial e a mesmo está sendo gerado, porém no console apresenta um erro e na aplicação desta Patch emergencial ocorre erro relacionando o TLPP. rpo

Na Geração da PATCH Emergencial, ocorre a seguinte mensagem. Mas a PATCH é gerada corretamente, estou utilizando o vscode.

![image](https://user-images.githubusercontent.com/29357935/101904600-d7674500-3b94-11eb-881d-27e37d24599f.png)

Sou do Desenvolvimento do TSS, informações do ambiente e Binário:

- Versão do TSS 12.1.27
- RPO - Lobo Guará versão 12.1.27
- Binário:
***  TOTVS S/A  ***
***  www.totvs.com.br  ***
* TOTVS - Build 7.00.191205P - Feb 20 2020 - 17:32:02
* Build: 64 bits
* SVN Revision: 26154
* Build Version: 19.3.0.2

**Comment by FelipeDuarteLuna** [comment]
Caso tente aplicar a Patch emergencial mencionada acima, ocorre a mensagem no console:

![Uploading image.png…]()

**Comment by lwtnb-wrk** [comment]
@FelipeDuarteLuna Notei que a versão de seu AppServer está bem desatualizadas e temos relatos de problemas com patches nas versões passadas do 19.3.0.x. Se possível atualize para a versão 19.3.1.x ou pelo menos utilize a última versão da 19.3.0.x.
Se os erros persistirem, veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by FelipeDuarteLuna** [comment]
@

**Comment by FelipeDuarteLuna** [comment]
Bom dia,

Realizei o processo de atualização do Binário conforme solicitado.

Atualizei o para versão 20-09-18 Build 19.3.0.6

Consegui realizar a geração da PATCH normalmente, aplicar a patch corretamente.

Entretanto o alerta do " Error Loading TLPP RPO" persiste. Segue print abaixo:

![image](https://user-images.githubusercontent.com/29357935/101909143-d7b70e80-3b9b-11eb-8209-2ff87b084aa3.png)

Estranho que tenho este arquivo TLPP.rpo na pasta Appserver e Smartclient.

Poderia me ajudar neste pendência ?


Atenciosamente,
Felipe Luna.

**Comment by lwtnb-wrk** [comment]
@FelipeDuarteLuna Essa é uma questão do AppServer, então se quiser, veja com eles o que você pode fazer. Não conseguimos fazer nada a respeito do lado do tds-vscode.
Enfim, pelo menos com o AppServer mais atualizado você conseguiu realizar a geração e aplicação dos patches.
