### ISSUE TITLE
One or more programs could not deleted from RPO

### ISSUE THREAD

**Issue by houstonsantos** [totvs/tds-vscode#602]
**Describe the bug**
Estou tentando deletar o fonte padrão CNTR031.prw de um relatório para compilar com uma customização, porem é apresentado o seguinte erro no output:

<img width="1162" alt="Captura de Tela 2020-12-11 às 11 15 48" src="https://user-images.githubusercontent.com/20193978/101932147-21622200-3bb9-11eb-9e97-4353e613313e.png">

**Screenshots**

**Desktop (please complete the following information):**
 - Mac OS 10.15.7

**Appserver (please complete the following information):**
 - Build (with date): 7.00.191205P-20201012 - 64 bits
 - OS/Architecture: Windows Server 2012 64 bits

**Comment by lwtnb-wrk** [comment]
@houstonsantos Um fonte padrão da TOTVS somente pode ser removido se voce tiver uma chave de compilação especifica.
Para customizar um relatorio, crie um novo PRW (nome diferente do CNTR031.prw) e altere a Function CNTR031() para User Function CNTR031(). Depois altere a chamada do relatorio original para sua User Function.
