### ISSUE TITLE
Insufficient privileges for APPLY_PATCH

### ISSUE THREAD

**Issue by MarcioCatelani** [totvs/tds-vscode#603]
Ao tentar aplicar um patch hoje comecou a ser exibida a mensagem Insufficient privileges for APPLY_PATCH. Tem um topico aqui q fala sobre isso, porem a solucao apresentada nao surtiu efeito.

**Comment by lwtnb-wrk** [comment]
@MarcioCatelani Que sistema operacional voce usa com o tds-vscode?
Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by MarceloCarioca** [comment]
Boa tarde! 
Não estou conseguindo aplicar os patchs. Não há mensagens de erro mas também nada acontece quando mando aplicar. 

Semanas atrás aconteceu algo parecido pois a ferramenta apresentava a mensagem de falta de privilégios para aplicar patchs e aí foi resolvido eliminando a sessão TDS do appserver.ini. 

Agora voltou o problema mas sem apresentar a mensagem. Simplesmente não aplica. Já coloquei o IP na sessão TDS, já coloquei *, já comentei tudo... e nada. 

Precisando urgente aplicar correções e não consigo. Pior que acontece do nada. De repente, simplesmente, não é possível aplicar as correções. 

Alguma orientação?

**Comment by brodao** [comment]
Senhores,

Favor remover a extensão, reiniciar o TDS-VSCode e instalarem novamente. Verificamos que em determinadas situações, a atualização pode não ocorrer. Ainda não conseguimos identificar o motivo.

A disposição.

**Comment by brodao** [comment]
Duplicado #573
