### ISSUE TITLE
Erro ao depurar webservice Rest

### ISSUE THREAD

**Issue by fa6ricio** [totvs/tds-vscode#604]
Ao depurar o webservice rest quando se usa o "Step Over" (F10) ele pura para o próximo ponto de parada como se tivesse sido usado o Continue (F5) ao invés do F10, tem como corrigir isto pois atrapalha bastante na depuração de webserives.

**Comment by lwtnb-wrk** [comment]
@MarcioCatelani Que sistema operacional voce usa com o tds-vscode?
Qual a build exata do AppServer que esta com esse problema? A principio isso é um comportamento do AppServer, entao precisamos verificar se é algo especifico de alguma build? Voce tem outros AppServers (com outras builds) para verificar se ocorre o mesmo problema?
Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.
