### ISSUE TITLE
One or more validations errors detected: - Patch URI was not informed.

### ISSUE THREAD

**Issue by houstonsantos** [totvs/tds-vscode#605]
**Describe the bug**
Estou tendo o seguinte erro ao tentar aplicar patchs. Verifiquei que na issue #96 o erro teria sido corrigido, porem estou na versão mais atual 1.2.1 e estou tendo o erro.

<img width="1090" alt="Captura de Tela 2020-12-15 às 15 01 00" src="https://user-images.githubusercontent.com/20193978/102253876-aebdb300-3ee6-11eb-94ab-a1472d0888e2.png">

**Comment by lwtnb-wrk** [comment]
@MarcioCatelani Que sistema operacional voce usa com o tds-vscode?
Voce consegue aplicar o patch para tela de Apply Patch sem ser pela aplicação direta do arquivo de patch?
Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by houstonsantos** [comment]
Uso Mac OS.
Não consigo nem pelo arquivo direto e nem pela função Parch Apply, o erro é o mesmo em ambas tentativas.
Segue logs.

[totvsls_in.log](https://github.com/totvs/tds-vscode/files/5703073/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/5703074/totvsls_out.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/5703075/totvsls.log)

**Comment by lwtnb-wrk** [comment]
@houstonsantos Os logs não apresentaram as operações de Apply Patch. Você repetiu as operações após ligar os logs?

**Comment by houstonsantos** [comment]
Esses logs acima foram direto pelo arquivo e esses agora foram usando o Patch Apply.

[totvsls_in.log](https://github.com/totvs/tds-vscode/files/5703509/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/5703510/totvsls_out.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/5703511/totvsls.log)

**Comment by lwtnb-wrk** [comment]
@houstonsantos Os ultimos arquivos tambem nao apresentaram a execucao do apply patch. 
Poderia gerar um video demosntrando o problema que esta ocorrendo?

**Comment by ricardomansano** [comment]
encerrado dado periodo sem interação
