### ISSUE TITLE
Compile Key

### ISSUE THREAD

**Issue by cezaralberto** [totvs/tds-vscode#606]
There is a video showing the bug,
I can't compile any patch, i can't compile any font.
[Record_2020_12_16_07_34_24_207.zip](https://github.com/totvs/tds-vscode/files/5702725/Record_2020_12_16_07_34_24_207.zip)

Do i need the *.aut file do compile key ?
This MACHINE ID : 49B6-3DD1

Version 1.52.0(user setup)
Commit 940b5f4bb5fa47866a54529ed759d95d09ee80be
Date: 2020-12-10T22:45:11.850Z(5 days ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node: js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 6.3.9600

**Comment by lwtnb-wrk** [comment]
@MarcioCatelani Que sistema operacional voce usa com o tds-vscode?
Como voce obteve esse Machine ID? Pois pelo video, aparentemente não esta sendo exibida essa informacao.
Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by cezaralberto** [comment]
O machine id leva um tempo para aparecer.

Estou usando o windows server 2012 R2 Standard
Segue anexo arquivos de log conforme solicitado.
[totvsls.zip](https://github.com/totvs/tds-vscode/files/5703058/totvsls.zip)

**Comment by lwtnb-wrk** [comment]
@cezaralberto Entendi. Grato pelas informações. O problema provavelmente é o sistema operacional que você está usando.
Tivemos já diversos relatos de problemas com Windows Servers e recomendamos o uso de Windows Desktop para o tds-vscode.
Acreditamos que os Windows Servers não possuem DLLs necessárias para o funcionamento correto da extensão.
Realize as mesmas operações em um Windows Desktop e você não deverá ter problemas.

**Comment by cezaralberto** [comment]
O uso do VS Code é feito remoto no servidor em uma rede externa.
Não tem a opção de instalar o Vs em um desktop local com acesso ao servidor.
O estranho é que até a semana passada eu usei e compilei fontes sem problema algum.

Houve alguma atualização nesse periodo que pudesse ter causado essa falha ?

**Comment by lwtnb-wrk** [comment]
@cezaralberto Interessante essa sua informação, pois temos relatos desde de o inicio do tds-vscode sobre problemas com o uso de Windows Servers.
O próprio VS Code se atualiza automaticamente nas configurações padrão e a nossa ultima atualização foi em 30/11 então a principio na semana passada já devia estar com essa ultima versão da extensão.
Voce pode tentar voltar para uma versão anterior a 1.2.1 do tds-vscode e avaliar se funcionava corretamente antes disso. Isso tambem pode ser feito com o proprio VS Code, mas lembre-se de desativar a atualização automatica.
Não tenho como testar esses procedimentos pois não tenho acesso a ambiente com Windows Server.

**Comment by lwtnb-wrk** [comment]
@cezaralberto De onde você pegou esses logs que voce anexou? Não parecem ter sido geradas na sua maquina hoje. As data e nome de usuarios nao estao consistentes...

**Comment by cezaralberto** [comment]
Acho que nao foi sobreposto o arquivo.
De qualquer forma, fiz o que me indicou.
Instalei uma maquina in loco para testar e fiz a instalação do VScode. O mesmo erro foi reproduzido em um windows 10.
Para esse ja fiz o processo e gerei os logs ;
[totvsls.zip](https://github.com/totvs/tds-vscode/files/5704033/totvsls.zip)

**Comment by cezaralberto** [comment]
Na verdade, analisando esses arquivos de log pude notar que existem mensagens dizendo que os pacotes foram aplicados.

Comparei o rpo da produção com o rpo do ambiente que tentei atualizar e os fontes estão atualizados.
Deve ser um bug no VSC... e nao na aplicação do pacote.

**Comment by lwtnb-wrk** [comment]
@cezaralberto O log pareceu imcompleto para mim, mas percebi que a validação de patches falhou. Qual a build exata do AppServer que esta utilizando? Tem uma versão do AppServer que estava com problema na validação de patches, mas que funcionava a aplicação de patches. Algo como a build 19.3.0.5 se nao me engano...

**Comment by ricardomansano** [comment]
encerrado dado periodo sem interação
