### ISSUE TITLE
Não é possível aplicar Patchs

### ISSUE THREAD

**Issue by MarceloCarioca** [totvs/tds-vscode#607]
Boa tarde!
Não estou conseguindo aplicar os patchs. Não há mensagens de erro mas também nada acontece quando mando aplicar.

Semanas atrás aconteceu algo parecido pois a ferramenta apresentava a mensagem de falta de privilégios para aplicar patchs e aí foi resolvido eliminando a sessão TDS do appserver.ini.

Agora voltou o problema mas sem apresentar a mensagem. Simplesmente não aplica. Já coloquei o IP na sessão TDS, já coloquei *, já comentei tudo... e nada.

Precisando urgente aplicar correções e não consigo. Pior que acontece do nada. De repente, simplesmente, não é possível aplicar as correções.

Alguma orientação?

![figura2](https://user-images.githubusercontent.com/74668208/102371126-9f00a600-3f9c-11eb-8933-86f615669a49.PNG)
![figuraum](https://user-images.githubusercontent.com/74668208/102371128-a031d300-3f9c-11eb-8a49-0d216649bf59.PNG)

**Comment by lwtnb-wrk** [comment]
@MarceloCarioca Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analises.

**Comment by MarceloCarioca** [comment]
Desculpe. Seguem os dados: 


Informações do AppServer		
Tipo do servidor	Console	
AppServer Build	7.00.191205P-20200424	
Appserver version	19.3.0.4	
Servidor 64 bits	Sim	
Servidor Unix	        Não	


Informações da LIB		
Versão da Lib	20200504	
Data da Lib	20200518_142132	
ID da Lib	33d5ae77620b2b81654c05f22d98c4ee0129e917	
Release	12.1.025	
HardLock	2014	
Versão do License Server	2.4.14	
Versão do Protheus	TOTVS Manufatura	
Dicionário no banco de dados	Não

![vscodeversion](https://user-images.githubusercontent.com/74668208/102383571-741d4e80-3faa-11eb-988a-4967e1418614.PNG)

**Comment by lwtnb-wrk** [comment]
@MarceloCarioca Esse AppServer tem problemas mesmo. Atualize para a build 19.3.0.6 no mínimo. E refaça os testes.
