### ISSUE TITLE
Chave de compilação não valida

### ISSUE THREAD

**Issue by izacsc** [totvs/tds-vscode#61]
Ao tentar informar um arquivo de chave de compilação ele preenche corretamente as informações mas não valida ao pressionar o botão Save.

Chave recebida dia 24/05 do GCAD

![image](https://user-images.githubusercontent.com/423449/58722177-28e22180-83ad-11e9-88d0-9a6a32d7cb15.png)

**Comment by lwtnb-wrk** [comment]
@izacsc O screenshot acima mostra que a chave de compilação esta sendo validada mas é inválida para o tds-vscode.
Favor limpar a chave "Clean Key" e verificar se o "Machine Id" é o mesmo da chave utilizada. 
Conforme informamos ao adicionar o suporte a chaves de compilação no formato legado, ressaltamos que o cálculo da "Machine Id" foi modificada e portanto deveria ser regerada com o "Machine Id" informado no tds-vscode. 
Na atualização que vamos liberar semana que vem teremos dois campos para facilitar a visualização do "Machine Id" (da sua estação) e "Key Id" da sua chave de compilação. 
Se a "Key Id" (de sua chave) não for a mesma que a "Machine Id" peça uma nova chave ao GCAD informando a "Machine Id" calculada pelo tds-vscode.
De qualquer forma nos retorne com as informações requeridas para continuarmos as investigações.
Grato por testar e informar um possivel problema.

**Comment by ricardomansano** [comment]
@izacsc , conseguiu uma chave correta para o nova ID? Testou?

**Comment by izacsc** [comment]
De fato não gerei um novo ID para solicitar a chave de compilação. Não seria mais desejável suportar as duas inicialmente e emitir um warning para as pessoas com o modelo antigo? Ainda não pedi uma nova chave para o GCAD então não testei.

**Comment by ricardomansano** [comment]
A nova chave é mais segura pois não utiliza o ID do HD, que pode ser facilmente alterado, motivo pelo qual abolimos o modelo anterior. 
Como informei no video desta incompatibilidade, não se justifica mais uma informação na tela do desenvolvedor. 
Se tiver alguma dificuldade com a nova chave que for solicitar nos informe.

**Comment by izacsc** [comment]
Desculpa a falta de conhecimento, mas que vídeo é esse? Eu já acredito que a informação de ser uma chave deprecada seria extremamente útil ao desenvolvedor que ainda não assistiu ( e possivelmente nunca vai) o vídeo mencionado. A única informação que apresenta é chave inválida o que não é o caso, visto que o TDS consegue utilizá-la sem problemas.

**Comment by ricardomansano** [comment]
@izacsc , quem "nunca" assistir o video, pode ter um pouco de boa vontade e ler a documentação do plugin, que diz claramente o que deve ser feito, se ficou alguma duvida estou a disposição:

Chave de compilação
A partir de 17/05/2019 todas as chaves devem ser regeradas utilizando o ID exibido no nosso plugin do VSCode. Isse se faz necessário para suporte de Linux e MAC.

Suporte de chave de compilação em Linux e MAC a partir de 17/05/2019.

**Comment by lwtnb-wrk** [comment]
@izacsc Nao se desculpe por isso, ainda estamos em fases iniciais e muitas coisas ainda estao sendo liberadas e documentadas, mas ainda temos gaps para melhorar. É que quando liberamos a funcionalidade frisamos o fato da incompatibilidade, mas realmente quem nao estava acompanhando nao vai saber mesmo. Vamos verificar essa possibilidade de informar sobre a chave descontinuada. Enfim grato pelos teste e sugestoes. Abs

**Comment by izacsc** [comment]
São sugestões para melhoria do produto. Acredito que se não houver uma mensagem adequada outras issues poderão ser abertas com a mesma "dúvida", apesar de estar na documentação e vídeo. 

Abs

**Comment by hfolha** [comment]
Boa Tarde Pessoal!
Seria possível, o GCAD gerar uma chave para cliente?
