### ISSUE TITLE
Exclusão de fontes.

### ISSUE THREAD

**Issue by Billo21** [totvs/tds-vscode#610]
Não exclui fonte compilado com caractere especial. 

1.Compilar um fonte que contenha caractere especial. 
2. Tentar excluir o fonte compilado do RPO.

Erro
[Info  - 11:26:37] Starting program deletion.
[Info  - 11:26:37] Starting build for environment P1227.
[Error - 11:26:38] One or more programs could not be deleted from RPO.
[Info  - 11:26:38] Aborting end build (rollback changes).

 Build Version: 19.3.1.4
![image](https://user-images.githubusercontent.com/69589167/102504007-1434af80-405f-11eb-953b-fd223c045360.png)

![image](https://user-images.githubusercontent.com/69589167/102504075-24e52580-405f-11eb-8c76-56cc06c9b1ac.png)

![image](https://user-images.githubusercontent.com/69589167/102504121-33cbd800-405f-11eb-9198-56d525fd9b79.png)

**Comment by brodao** [comment]
@Billo21 

No momento, infelizmente não tem como efetuar esse procedimento. Estou colocando seu chamado na fila, para ver se conseguimos implementar algo.

Você precisará retornar o RPO antes de ter compilado esse fonte.

O uso de acentuação em nome de arquivos e pastas, não é recomendado, principalmente se o projeto for compartilhado entre S.O. distintos.

A disposição.

**Comment by ricardomansano** [comment]
Bom dia,
Essa é uma feature que não poderemos implementar, como ja indicado:
-retorne a versão do RPO anterior a essa compilação
-renomeie o PRW sem caracteres especiais
-re-compile o fonte

Via VSCode nao temos contorno, você pode abrir um chamado ao time do AppServer solicitando que eles nao aceitem a compilação de fontes com caracteres especiais.
