### ISSUE TITLE
VsCode desposicionando linhas de alertas e erros 

### ISSUE THREAD

**Issue by ThiagoTQO** [totvs/tds-vscode#612]
Boa tarde, 

Estou com um problema em que o VS Code informa que o erro está na linha 5, quando deveria estar na linha 35 do fonte.

![image](https://user-images.githubusercontent.com/76226823/102654220-f5154b00-414e-11eb-88f1-691d34641c46.png)

![image](https://user-images.githubusercontent.com/76226823/102654244-fe9eb300-414e-11eb-8819-4f19318ec3ee.png)

Segue logs conforme doc.

[totvsls.log](https://github.com/totvs/tds-vscode/files/5717717/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/5717718/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/5717719/totvsls_out.log)

Atenciosamente, 
Thiago Queiroz

**Comment by brodao** [comment]
@ThiagoTQO 

Verifique a versão do seu _appServer_ e se for o caso, atualize.
Se puder fazer testes com uma versão anterior e nos relatar os resultados, agradecemos.

A disposição.

**Comment by brodao** [comment]
@ThiagoTQO 

Em complemento, se puder gerar o [PPO ](https://github.com/totvs/tds-vscode/blob/master/docs/compilation.md#configura%C3%A7%C3%B5es-de-compila%C3%A7%C3%A3o) do fonte que apresenta a ocorrência e anexá-lo ao chamado, também ajuda.

Grato.

**Comment by ThiagoTQO** [comment]
Pessoal, bom dia

Acho que descobri o problema.

Eu uso o Drive File Stream do google (tipo um dropbox) como ambiente de trabalho, então os fontes estão numa pasta dentro desse DFS e não no meu note, diferente do dropbox que só cria uma pasta e sincroniza o que estiver dentro, esse cria um drive virtual e você só tem acesso as informações enquanto o programa está rodando, se ele parar você não tem mais acesso.

Fiz um teste ontem jogando o fonte para o drive local e ele funcionou corretamente, mesmo ambiente, mesmo include, mesmo appserver, mesmo tudo, menos o local do fonte.

Fiz alguns testes com fontes que eu estava com problemas parecidos e todos resolveram quando mudei para o drive local

Fonte no Drive do Google
![image](https://user-images.githubusercontent.com/76226823/103770245-72243980-5004-11eb-94dd-adbda3bb8726.png)


Mesmo fonte no drive local da máquina
![image](https://user-images.githubusercontent.com/76226823/103770290-810aec00-5004-11eb-9191-ad3200002434.png)

Obrigado pela ajuda.
