### ISSUE TITLE
Ao debugar, ponto de parada não funciona quando fonte tem MVC

### ISSUE THREAD

**Issue by RBandeiraSP** [totvs/tds-vscode#615]
Boa Tarde
Apenas em fontes que tem MVC , o ponto de parada não funciona.

**Comment by brodao** [comment]
Ola @RBandeiraSP 

Favor anexar um fonte o mais simples possível que reproduza a ocorrência.

No aguardo.

**Comment by RBandeiraSP** [comment]
Bom dia.
Segue conforme solicitado.
Ao procurar um fonte simples, observei que em fontes em MVC bem simples, o problema não ocorre.
Este em anexo é o menor em MVC com o problema, que encontrei.

Desde já agradeço a atenção.


[MGFFINA5.zip](https://github.com/totvs/tds-vscode/files/5734897/MGFFINA5.zip)

**Comment by brodao** [comment]
Olá @RBandeiraSP 

Efetuei testes e realmente isso ocorre. Há certas situações em que não é possível efetuar a depuração, p.e. em _code blocks_.

Favor entrar em contato com a equipe de FW para verificar se não é uma dessas situações.

A disposição.
