### ISSUE TITLE
Instruções para compilar uma função de usuário

### ISSUE THREAD

**Issue by afonsobin** [totvs/tds-vscode#616]
**Describe the bug**
Instalei o vscode , já criei o server e consigo compilar patchs.

Não sei como faço para compilar um fontes customizados que estão faltando no meu RPO atual.

Devo efetuar mais alguma configuração no vscode?

![image](https://user-images.githubusercontent.com/76748538/103307507-fec06d80-49ee-11eb-872d-2835d27bbce9.png)

![image](https://user-images.githubusercontent.com/76748538/103307571-27e0fe00-49ef-11eb-904d-ff5d116128ea.png)

**Comment by lwtnb-wrk** [comment]
@afonsobin Você seguiu a documentação em https://github.com/totvs/tds-vscode/blob/master/docs/compilation.md ?
Qual o problema que está ocorrendo?
E qual o SO que está utilizando, pois temos relatos de problemas diversos nos Windows Servers então certifique-se de utilizar Windows Desktop com o tds-vscode.

**Comment by afonsobin** [comment]
Boa tarde , esta dando esse erro quando pressiono control+F9.
![image](https://user-images.githubusercontent.com/76748538/103310878-7befe080-49f7-11eb-8417-42844b262cef.png)
![image](https://user-images.githubusercontent.com/76748538/103310927-a80b6180-49f7-11eb-9a79-5476b55d8d24.png)

**Comment by afonsobin** [comment]
Esqueci de mencionar que é windows server 2012

Eng.º Afonso Bin
Project Manager IT
+55 11 99639-5944 +244939910067
Skype afonso.bin1



Em ter., 29 de dez. de 2020 às 16:23, lwtnb-wrk <notifications@github.com>
escreveu:

**Comment by lwtnb-wrk** [comment]
@afonsobin Aparentemente é esse o problema. Realize os procedimentos em um Windows Desktop ao inves do Windows Server.
