### ISSUE TITLE
Insufficient privileges for APPLY_PATCH - VSCODE

### ISSUE THREAD

**Issue by andremendes156** [totvs/tds-vscode#618]
Ao tentar aplicar qualquer patch o VSCode retorna a mensagem que eu não tenho privilégio para aplicação do mesmo.
print anexo

![ERRO VSCODE - PATCH](https://user-images.githubusercontent.com/76815751/103412931-431a4d80-4b56-11eb-91e4-aaaebebff0d1.png)

**Comment by brodao** [comment]
Olá @andremendes156 

Veja o chamado #603.

A disposição.

**Comment by brodao** [comment]
Senhores,

Favor remover a extensão, reiniciar o TDS-VSCode e instalarem novamente. Verificamos que em determinadas situações, a atualização pode não ocorrer. Ainda não conseguimos identificar o motivo.

A disposição.

**Comment by brodao** [comment]
Duplicado #573
