### ISSUE TITLE
Insufficient privileges for APPLY_PATCH

### ISSUE THREAD

**Issue by marcoscborges** [totvs/tds-vscode#619]
Boa tarde!!

Ao tentar aplicar Patch  com VSCODE em ambiente já atualizado está dando erro "Insufficient privileges for APPLY_PATCH".

![VSCODE](https://user-images.githubusercontent.com/77026594/103699617-fa152f80-4f81-11eb-8d26-75043b438e80.png)
![Build](https://user-images.githubusercontent.com/77026594/103699728-203acf80-4f82-11eb-9cfb-5e6fb738b6b7.png)

**Comment by brodao** [comment]
Senhores,

Favor remover a extensão, reiniciar o TDS-VSCode e instalarem novamente. Verificamos que em determinadas situações, a atualização pode não ocorrer. Ainda não conseguimos identificar o motivo.

A disposição.

**Comment by brodao** [comment]
Duplicado #573
