### ISSUE TITLE
Criação de Novos arquivos

### ISSUE THREAD

**Issue by caiadofelipe** [totvs/tds-vscode#62]
Existe uma opção no VSCode nas preferências referente a Default Language para novos arquivos
(Files: Default Language
O modo de linguagem padrão que é atribuída para novos arquivos.) CTRL+N
Não consegui configurar para AdvPL, teria como fazer essa configuração?

**Comment by izacsc** [comment]
Configure assim "advpl" tudo minúsculo.

![image](https://user-images.githubusercontent.com/423449/58722732-9773af00-83ae-11e9-8190-c66dd0878b62.png)

![image](https://user-images.githubusercontent.com/423449/58722752-a5293480-83ae-11e9-9f1f-11ef2b4a37d8.png)

**Comment by caiadofelipe** [comment]
@izacsc, obrigado pelo retorno, funcionou corretamente, tinha colocado como AdvPL e ADVPL e não havia funcionado, faltou testar com minúsculo.

Abraço,

**Comment by lwtnb-wrk** [comment]
@izacsc e @caiadofelipe Somente para entender, qual a necessidade de adicionar essa configuração? Pelo que entendo se um novo arquivo for criado com as extensões conhecidas, por exemplo, .prw, ele já é reconhecido com o um fonte AdvPL sem a necessidade de informar qual sua linguagem...
Enfim, grato pelas informações e testes!!!

**Comment by caiadofelipe** [comment]
@lwtnb-wrk, No vs code quando se cria um arquivo novo vc não informa ainda a extensão, ele cria sem extensão para ser salvo posteriormente, sem essa configuração que o @izacsc passou, o arquivo novo mesmo não tendo extensão ele já reconhece as configurações do ADVPL

**Comment by lwtnb-wrk** [comment]
@caiadofelipe Entedi, é que eu costumo criar um arquivo já informando o nome e extensão. Assim faz sentido essa configuração. Grato pela informação.
