### ISSUE TITLE
MENSAGEM DE AVISO USANDO PROTHEUS.DOC

### ISSUE THREAD

**Issue by jadilsonnery** [totvs/tds-vscode#621]
Segue imagem, que antes da atualização do VSC não apareciam, reclamando do ProthuesDoc.
Como acertar isso ?
Segue imagem em anexo
![MENSAGEM](https://user-images.githubusercontent.com/64595947/104618180-23f9e080-566b-11eb-915f-716f173fb545.jpg)

**Comment by brodao** [comment]
Favor informar versão da extensão e do server.

**Comment by jadilsonnery** [comment]
Versão : 1.52.1

 

 

Jadilson S. Nery
Atendimento e Relacionamento
Solution Partner
www.solucoesconsultoria.com <http://www.solucoesconsultoria.com/> 
Unidade Minas Gerais
* 55 (31) 8481-6219

* jadilson@ <mailto:jadilson@solucoesconsultoria.com> solucoesconsultoria.com
*  <mailto:jadilson.nery@totvs.com.br> jadilson.nery@totvs.com.br

 

 

De: Alan Cândido <notifications@github.com> 
Enviada em: quinta-feira, 14 de janeiro de 2021 13:48
Para: totvs/tds-vscode <tds-vscode@noreply.github.com>
Cc: jadilsonnery <jadilson@solucoesconsultoria.com>; Author <author@noreply.github.com>
Assunto: Re: [totvs/tds-vscode] MENSAGEM DE AVISO USANDO PROTHEUS.DOC (#621)

 

Favor informar versão da extensão e do server.

**Comment by jadilsonnery** [comment]
Versão : 1.52.1

Versão: TOTVS Varejo

Build AppServer: 7.00.191205P-20200424 - 64 bits

Nome do servidor: SRVTOTVS

Sistema operacional: Windows Server 2012

Appserver version: 19.3.0.4

Build DBAccess: 20191119-20200706

Release do RPO:  12.1.027 - Out  2020

Release do dicionário: 12.1.027 - Out  2020

Local files: CTREE

License server: 2014 - 3.2.2

DB DataBase: MSSQL

DB API Build: 20191119-20200116

 

Jadilson S. Nery
Atendimento e Relacionamento
Solution Partner
www.solucoesconsultoria.com <http://www.solucoesconsultoria.com/> 
Unidade Minas Gerais
* 55 (31) 8481-6219

* jadilson@ <mailto:jadilson@solucoesconsultoria.com> solucoesconsultoria.com
*  <mailto:jadilson.nery@totvs.com.br> jadilson.nery@totvs.com.br

 

 

De: Alan Cândido <notifications@github.com> 
Enviada em: quinta-feira, 14 de janeiro de 2021 13:48
Para: totvs/tds-vscode <tds-vscode@noreply.github.com>
Cc: jadilsonnery <jadilson@solucoesconsultoria.com>; Author <author@noreply.github.com>
Assunto: Re: [totvs/tds-vscode] MENSAGEM DE AVISO USANDO PROTHEUS.DOC (#621)

 

Favor informar versão da extensão e do server.

**Comment by brodao** [comment]
Essa versão não existe nesta extensão.
![image](https://user-images.githubusercontent.com/949914/104623170-dbddbc80-5670-11eb-9b37-9f3d704baf42.png)
Ultimo oficial

![image](https://user-images.githubusercontent.com/949914/104623227-ec8e3280-5670-11eb-9ea5-1f81af4ccfb1.png)
Versão Candidata

**Comment by jadilsonnery** [comment]
Jadilson S. Nery
Atendimento e Relacionamento
Solution Partner
www.solucoesconsultoria.com <http://www.solucoesconsultoria.com/> 
Unidade Minas Gerais
* 55 (31) 8481-6219

* jadilson@ <mailto:jadilson@solucoesconsultoria.com> solucoesconsultoria.com
*  <mailto:jadilson.nery@totvs.com.br> jadilson.nery@totvs.com.br

 

 

De: Alan Cândido <notifications@github.com> 
Enviada em: quinta-feira, 14 de janeiro de 2021 14:02
Para: totvs/tds-vscode <tds-vscode@noreply.github.com>
Cc: jadilsonnery <jadilson@solucoesconsultoria.com>; Author <author@noreply.github.com>
Assunto: Re: [totvs/tds-vscode] MENSAGEM DE AVISO USANDO PROTHEUS.DOC (#621)

 

Essa versão não existe nesta extensão.
 <https://user-images.githubusercontent.com/949914/104623170-dbddbc80-5670-11eb-9b37-9f3d704baf42.png> 
Ultimo oficial

 <https://user-images.githubusercontent.com/949914/104623227-ec8e3280-5670-11eb-9ea5-1f81af4ccfb1.png> 
Versão Candidata

**Comment by jadilsonnery** [comment]
Alguma posição ?

**Comment by brodao** [comment]
Foi solicitado a versão do TDS-VSCode em uso. Estou aguardando.

**Comment by jadilsonnery** [comment]
Te enviei a imagem do VSC, opção Sobre

Indicando que é : 1.52.1

 

Se não é isso, seria o que ??

 

Atenciosamente

 

Jadilson S. Nery
Atendimento e Relacionamento
Solution Partner
www.solucoesconsultoria.com <http://www.solucoesconsultoria.com/> 
Unidade Minas Gerais
* 55 (31) 8481-6219

* jadilson@ <mailto:jadilson@solucoesconsultoria.com> solucoesconsultoria.com
*  <mailto:jadilson.nery@totvs.com.br> jadilson.nery@totvs.com.br

 

 

De: Alan Cândido <notifications@github.com> 
Enviada em: sexta-feira, 15 de janeiro de 2021 14:15
Para: totvs/tds-vscode <tds-vscode@noreply.github.com>
Cc: jadilsonnery <jadilson@solucoesconsultoria.com>; Author <author@noreply.github.com>
Assunto: Re: [totvs/tds-vscode] MENSAGEM DE AVISO USANDO PROTHEUS.DOC (#621)

 

Foi solicitado a versão do TDS-VSCode em uso. Estou aguardando.

**Comment by jadilsonnery** [comment]
Te enviei a imagem do VSC, opção Sobre
Indicando que é : 1.52.1

Se não é isso, seria o que ??

![versao VSC](https://user-images.githubusercontent.com/64595947/104760041-91774100-573f-11eb-80fc-c6988452fbd8.jpg)

**Comment by brodao** [comment]
Versão da extensão TDS-VSCode, aqui borrada.
![image](https://user-images.githubusercontent.com/949914/104760049-963bf500-573f-11eb-96b8-4f932d1e4364.png)

**Comment by jadilsonnery** [comment]
Segue imagem
![versao VSC-2](https://user-images.githubusercontent.com/64595947/104768635-c0e07a80-574c-11eb-9c62-9d3c9ebc6614.jpg)

**Comment by brodao** [comment]
@jadilsonnery 

Vi que esta usando algumas extensões a mais.
- Advpl, não recomendamos o uso em conjunto com o TDS-VSCode. Use uma ou outra.
- ProtheusDOC for VSCode, provavelmente é ele que esta emitindo essas mensagens.

Entre em contado com o desenvolvedor dela.

A disposição.
