### ISSUE TITLE
Erro Debug WATCH com informação desatualizada

### ISSUE THREAD

**Issue by maximinocastro** [totvs/tds-vscode#623]
Versão do VSCode e Plugin 

VsCode = 1.52.1
Plugin = 1.2.1

**Expected behavior**
Ao instanciar minha classe o retorno no Watchs apresenta a informação errada.

**Screenshots**

![image](https://user-images.githubusercontent.com/42280023/104762328-ec5e6780-5742-11eb-96ab-ec6833fd77d4.png)

![image](https://user-images.githubusercontent.com/42280023/104762484-32b3c680-5743-11eb-8d6b-5d537c365e03.png)

**Desktop (please complete the following information):**
 - Windows 64 bits

**Appserver (please complete the following information):**
Versão: TOTVS Serviços
Build AppServer: 7.00.170117A-20190628 - 64 bits
Build DBAccess: 20181212
Release do RPO:  12.1.025
Release do dicionário: 12.1.025

**Additional context**

**Comment by lwtnb-wrk** [comment]
@maximinocastro Favor prover maiores detalhes do problema. Se possível anexe um fonte simples que mostre o problema.
Não tenho como saber o que você estava esperando apenas observando os screenshots anexados.

**Comment by maximinocastro** [comment]
Boa tarde,

Segue os fontes de exemplo.

Att.

[fontes.zip](https://github.com/totvs/tds-vscode/files/5831471/fontes.zip)

**Comment by lwtnb-wrk** [comment]
@maximinocastro Ainda não sei qual o problema que está ocorrendo. Os exemplos enviados não rodaram, pois ainda devem depender de outros fatores (pelo que entendi acessam um outro serviço REST). Mas também deram erro de runtime (ERROR: variable does not exist OBRWLIST)...
Se puder explicar melhor o problema talvez possamos ajudar.

**Comment by maximinocastro** [comment]
Boa tarde,

Realmente se tentar DEBUGAR meu código vai dar erro por isso é só um EXEMPLO.

Vamos se eu instanciar a CLASSE e depois chamar um METODO A o VSCODE me traz as informações certinha, porém após matar o Objeto Instanciado utilizando NIL e instanciar novamente a CLASSE chamando o METODO B no WATCHS mostra as informações do METODO A qual foi instanciado primeiro "COMO SE TIVESSE NA MEMORIA" más é só visualmente, por que se eu jogar a instrução no DEBUG CONSOLE retorna as informações que deveria apresentar no WATCHS.

Att.

**Comment by lwtnb-wrk** [comment]
@maximinocastro Quando pedimos um exemplo que demonstre o problema seria interessante que ele apresentasse o erro, neste caso o erro durante o debug, mas acho que não fui claro.
Enfim se conseguirmos reproduzir o problema faremos a análise.

**Comment by maximinocastro** [comment]
Bom dia,

Esse erro do Watchs só acontece com classe quando é chamado 2x em métodos diferentes.

Att.

**Comment by lwtnb-wrk** [comment]
@maximinocastro Fiz testes tentando reproduzir o comportamento informado mas não observei nenhum problema de informações incorretas.
Poderia gravar um video e descrever com detalhes o erro que está observando?

**Comment by maximinocastro** [comment]
Segue o Vídeo

REPARE nas variáveis oRetObj e oRetObj2.

[TOTVS_DEBUG_VSCODE.zip](https://github.com/totvs/tds-vscode/files/5836705/TOTVS_DEBUG_VSCODE.zip)

**Comment by lwtnb-wrk** [comment]
@maximinocastro Acho que entendi, pelo menos parcialmente, o que você está fazendo. E pelo que entendo o comportamento está correto, mas eu posso não ter reparado em alguma coisa que você tentou mostrar, pois o video não tem um audio explicando o que você está tentando mostrar.
As variáveis oRetObj e oRetObj2 são referências a objetos que são instanciados nos métodos (OpenTeam e InfoTeam) e são independentes dos oBlip() que voce instanciou. Então não sei se é isso que você está tentando apresentar.
E quando você pede o valor de oRetObj2:Resource:Total não seria oRetObj2:Resource:Items:Total ?
Se não conseguir colocar um audio no video, abra um notepad e explique o que esta tentando mostrar.

**Comment by maximinocastro** [comment]
Boa tarde,

Leo segue o DAP.log
[dap.log](https://github.com/totvs/tds-vscode/files/5837935/dap.log)

**Comment by maximinocastro** [comment]
Segue novo log
[dap.log](https://github.com/totvs/tds-vscode/files/5837986/dap.log)

**Comment by lwtnb-wrk** [comment]
@maximinocastro Grato pelos testes e logs. Identificamos o problema e faremos a correção assim que possível.

**Comment by lwtnb-wrk** [comment]
@maximinocastro Favor informar a build exata do AppServer que está utilizando.

**Comment by maximinocastro** [comment]
Que maravilha,

Segue os dados.

Versão: TOTVS Serviços
Build AppServer: 7.00.170117A-20190628 - 64 bits
Build DBAccess: 20181212
Release do RPO: 12.1.025
Release do dicionário: 12.1.025

**Comment by lwtnb-wrk** [comment]
@maximinocastro Notei que sua versão do AppServer está bem desatualizada. Você consegue retestar em ambientes mais atualizados tanto do Lobo Guará 17 quanto no 19? 
Como não consigo reproduzir o problema localmente, esse seria um teste interessante para cobrir questões de AppServer atualizados...

**Comment by maximinocastro** [comment]
Bom dia, 

Poderia me mandar o Link do Portal do Appserver 12.1.25 ?

Tá horrível achar o link para download, quando acessa o ambiente TOTVS PLATFORM > APPSERVER não mostra nada.

**Comment by lwtnb-wrk** [comment]
@maximinocastro Pegue em https://suporte.totvs.com/portal/p/10098/download#000006/368/TFAPP/

**Comment by maximinocastro** [comment]
Cara atualizei o appserver para o do link e está dando erro.

![image](https://user-images.githubusercontent.com/42280023/105195663-9cecb280-5b19-11eb-9570-1135008a02d6.png)


2021-01-20T12:13:33.986000-03:00 6308|[VDRPORT] 210120_121333 18A4 LOG0218 E 2021-01-20 12:13:33, wed, appserver(4260/6308),
       0ms [vdr_ssl_session.cpp:185], conCode: 2, retCode: 1, message: status(phase): 4, SSL_read, alocated: 16384, result: -1, error: 1

2021-01-20T12:13:33.987000-03:00 6308|[VDRPORT] 210120_121333 18A4 LOG0218 E 2021-01-20 12:13:33, wed, appserver(4260/6308),
       0ms [vdr_ssl_session.cpp:185], conCode: 2, retCode: 1, message: SSL error: 336027900, 'error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol'

**Comment by lwtnb-wrk** [comment]
@maximinocastro Você cadastrou um novo AppServer? Isso parece ser a configuração de secure incorreta... Esse AppServer é um LG 19? Abra as configurações de servidores (servers.json) e mude a flag secure de true para false ou vice-versa.

**Comment by maximinocastro** [comment]
Eu nem abri pelo Vscode ainda, o erro é apresentando ao tentar iniciar o Smatclient rs

**Comment by lwtnb-wrk** [comment]
@maximinocastro Ah não... Atualize o smartclient tambem... Ele tem essa diferença no LG 19...

**Comment by maximinocastro** [comment]
Baixei o Smatclient LG e deu error log.

20/01/2021 17:08:54
sigapss.spf: SuperFile Open error 920 - File: e:\protheus_labor\protheus\protheus_data\system\sigapss.spf - undefined error on __SPFREBUILD(SIGAPSW.PRG) 12/07/2019 17:27:26 line : 3040

**Comment by maximinocastro** [comment]
[Mike.log](https://github.com/totvs/tds-vscode/files/5845038/Mike.log)

Log Completo

**Comment by danielbolognani** [comment]
@maximinocastro Por aqui a gente não consegue ajudar com problemas na atualização do ambiente e/ou binários/framework, esse Error.log não tem ligação nenhuma com o erro inicial. Se acreditar que é um problema da lib (Framework) favor procurar a equipe ou abrir um chamado para eles.

Vamos focar apenas no problema de watch. Para o problema que vc está tendo o ideal seria tentar montar um exemplo pequeno que mostra exatamente o problema para que possamos testar por aqui também.
At.

**Comment by maximinocastro** [comment]
Concordo Daniel,

Porém foi o outro analista que pediu pra atualizar e verificar se era problema de appserver.

Aguardo a correção então.

**Comment by danielbolognani** [comment]
É interessante sempre atualizar o ambiente, mesmo porque muitos erros de
debug vem da camada do Appserver. Vc não consegue montar uma base zerada
com as versões atualizadas do Appserver/Smartclient para realizar esse
teste?

Em qua., 20 de jan. de 2021 às 17:24, Michael Maximino de Castro <
notifications@github.com> escreveu:

**Comment by maximinocastro** [comment]
Atualmente não.

Estou enrolado com outros projetos e não tenho tempo de montar por isso criei um ambiente separado na base teste só pra fazer esse teste do VSCODE.

**Comment by ricardomansano** [comment]
Bom dia Michael,

Seu ambiente tá bem desatualizado, isso explica porque o Leo não reproduziu a situação.

Consulte o time de Suporte ou TIS da TOTVS se for montar um novo ambiente, eles conseguirão apoiar mais que nós da TEC.

Até que atualize seu ambiente infelizmente vai ter que conviver com essa situação.

Grato,
