### ISSUE TITLE
Generate WS Protheus gera um arquivo em branco

### ISSUE THREAD

**Issue by luislacombe** [totvs/tds-vscode#624]
Ao tentar a rotina Generate WS Protheus para gerar um fonte para consumir um WS ocorre o erro abaixo e logo em seguida gera o fonte em branco:

[Info  - 10:36:03] Starting generate Wsdl.
[Info  - 10:36:03] Generating WSDL client at server.
[Error - 10:36:04] *** ERRO AO GERAR FONTE ADVPL ***
Source URL : http://app.smartdocx.com.br/service/Areas/WebService/Integracao.asmx
-------------------------------------------------------------------------------
WSCERR066 / INVALID WSDL Content-Type (Content-Type: text/html; charset=utf-8) from http://app.smartdocx.com.br/service/Areas/WebService/Integracao.asmx
ADVPL WSDL Client 1.120703 / TOTVS Constru��o e Projetos Totvs_lg on 20210118 10:36:04
-------------------------------------------------------------------------------
Estou usando o plugin da Totvs versão v1.2.1

**Comment by lwtnb-wrk** [comment]
@luislacombe Ao tentar abrir o link http://app.smartdocx.com.br/service/Areas/WebService/Integracao.asmx ocorre erro, pois não é um WSDL válido.
Veja com o provedor desse serviço a correção do WSDL e quando estiver funcionando o cliente WSDL deve ser gerado.

**Comment by luislacombe** [comment]
O provedor está funcionando normalmente. Fiz uma referência do serviço no Visual Studio e trouxe tudo certo. Só não funciona no VS Code com a extensão da Totvs.

**Comment by lwtnb-wrk** [comment]
@luislacombe Ah okay. Seu link está incompleto. Use com um ?wsdl no final... Esse é o endereço correto do WSDL necessário para a geração do cliente WSDL.
http://app.smartdocx.com.br/service/Areas/WebService/Integracao.asmx?wsdl

**Comment by luislacombe** [comment]
Perfeito era isso mesmo. Muito Obrigado pela pronta ajuda.
