### ISSUE TITLE
Erro na aplicação de Patch de LIB

### ISSUE THREAD

**Issue by Smmartinez** [totvs/tds-vscode#625]
Bom dia Pessoal!
Estou tentando aplicar patch de LIB e é apresentado erro na validação do arquivo aparece a mensagem Invalid Vector <T> subscript
Notei que é apenas nesse tipo de patch, os demais de módulos aplica sem problema.
Em anexo a imagem que aparece
![error](https://user-images.githubusercontent.com/4532855/104928161-1604d200-5981-11eb-9b91-c79f1c1fd807.png)

**Comment by Smmartinez** [comment]
Boa tarde pessoal... Notei que na versão 1.2.1 consegui aplicar o patch com a LIB mas na versão 1.2.2 ocorre o erro citado acima

**Comment by brodao** [comment]
@Smmartinez 

Favor anexar o log do servidor protheus no momento da aplicação.

No aguardo.

**Comment by Smmartinez** [comment]
Bomdia @brodao Segue o arquivo LOG do APPSERVER.

[console.zip](https://github.com/totvs/tds-vscode/files/5879992/console.zip)

**Comment by Smmartinez** [comment]
@brodao pelo que pude notar ele até aplica o Patch por que o RPO muda a data. A versão do server que estou usando é a 19.3.1.5

**Comment by Smmartinez** [comment]
Boa tarde! Ainda não esta sendo possível aplicar LIB na versão 1.2.2 com o appserver na versão 19.3.1.5 tenho que sempre voltar para a versão 1.2.1 para aplicar.

**Comment by brodao** [comment]
@Smmartinez 

Pelas modificações efetuadas no processo de aplicação entre as versões 1.2.1 e 1.2.2 (esta passou a ser mais rigorosa com condições de aplicação), parece que seu ambiente não esta de acordo com o esperado pelo pacote sendo aplicado e "encobrindo" o motivo do erro. Estou montando o ambiente com as mesmas builds que você usa para tentar reproduzir.
Ainda hoje dou retorno.

Grato pela compreensão.

**Comment by brodao** [comment]
@Smmartinez 

Reproduzi a ocorrência e já arrumei. A correção estará disponível na próxima liberação.
Se quiser, em https://drive.google.com/file/d/1O9OcIFceOqR2TEFlDCN7JP6Zv3Mr93ea/view?usp=sharing há uma versão RC com a correção.

Grato pela colaboração.

**Comment by Smmartinez** [comment]
Ah tranquilo, bom que acharam o problema.

Tem previsão de liberação para o oficial?


Att.
Sergio Martinez Martinez
 
 



De: "Alan Cândido" <notifications@github.com>
Enviada: 2021/02/19 15:04:05
Para: tds-vscode@noreply.github.com
Cc:  mm_sa@uol.com.br, mention@noreply.github.com
Assunto:  Re: [totvs/tds-vscode] Erro na aplicação de Patch de LIB (#625)
 

 

@Smmartinez

Reproduzi a ocorrência e já arrumei. A correção estará disponível na próxima liberação.
Se quiser, em https://drive.google.com/file/d/1O9OcIFceOqR2TEFlDCN7JP6Zv3Mr93ea/view?usp=sharing há uma versão RC com a correção.

Grato pela colaboração.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/totvs/tds-vscode/issues/625#issuecomment-782241501", "url": "https://github.com/totvs/tds-vscode/issues/625#issuecomment-782241501", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by ricardomansano** [comment]
Boa tarde, versão 1.2.3 ja disponivel no marketplace, basta atualizar
