### ISSUE TITLE
Erro na compilação do fonte RTMSR35

### ISSUE THREAD

**Issue by Jafreal** [totvs/tds-vscode#626]
Bom dia

Abri o chamado na Totvs 10522728. Ai me disseram para posta aqui meu problema. Pois bem Esse fonte, sem nenhuma customização ao ser compilado apresenta a seguinte mensagem
 {	"resource": "/c:/Sistemas/CBAA_NEW/Cte/RTMSR35.PRW",
	"owner": "AdvPL",
	"severity": 8,
	"message": "Duplicated function U_RTMSR35 (found in RTMSR35 (1).PRW)",
	"source": "compile",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 2,
	"endColumn": 1
}
Não importa o q faça sempre dá o mesmo erro. Já troquei e peguei do site da totvs o programa e nda. Com certeza é alguma configuração no VSCode. Só nesse programa.

**Comment by lwtnb-wrk** [comment]
@Jafreal Voce por acaso tem o arquivo "RTMSR35 (1).PRW" que deve ser uma copia do "RTMSR35.PRW"?

**Comment by Jafreal** [comment]
Não dr. esse (1) significa q o erro ta na linha 1

**Comment by danielbolognani** [comment]
@Jafreal Vc provavelmente compilou alguma vez esse fonte com o nome RTMSR35 (1).PRW (não quer dizer que é erro na linha 1).
Para resolver, crie um arquivo com esse nome (RTMSR35 (1).PRW) e utilize o comando para apagar fontes do RPO.

**Comment by Jafreal** [comment]
Já fiz isso dr. Conforme já expliquei se eu desabilitar a primeira linha e da erro em outra linha.
![image](https://user-images.githubusercontent.com/74660547/105364279-c1a95e80-5bdb-11eb-877b-82363ca1bb68.png)

**Comment by danielbolognani** [comment]
O erro agora não é mais de Função duplicada, só pelo print não da para
saber qual é exatamente o problema. Consegue anexar o fonte por aqui?

Em qui., 21 de jan. de 2021 às 11:28, Jose de Aguiar Ferreira Real Neto <
notifications@github.com> escreveu:

**Comment by Jafreal** [comment]
Vou fazer isso. Feito e agradeço a ajuda.

[rtmsr35.zip](https://github.com/totvs/tds-vscode/files/5849993/rtmsr35.zip)

**Comment by danielbolognani** [comment]
@Jafreal Verifique os seus includes, aqui está compilando normalmente.
