### ISSUE TITLE
Suport ao TOTVS Developer Studio ou VScode

### ISSUE THREAD

**Issue by Veronicadourado** [totvs/tds-vscode#627]
Preciso compilar um relatorio customizado no sistema protheus, porem no chamado totvs me informaram que eu deveria abrir um chamado aqui..
Gostaria de saber em qual programa posso compilar este relatorio TDS ou VScode e se voces poderiam me orientar.
att
21 996733270
veronica

**Comment by brodao** [comment]
@Veronicadourado 

Recomendo o uso do TDS-VSCode. Em [Compilação](https://github.com/totvs/tds-vscode/blob/master/docs/compilation.md) há informações de como proceder.

A disposição.
