### ISSUE TITLE
Compilação de Project Function no VS Code

### ISSUE THREAD

**Issue by beto-goncalves** [totvs/tds-vscode#629]
Olá, boa tarde!

Na rotina MATA461 existe a chamada de Project Function conforme abaixo:

![image](https://user-images.githubusercontent.com/64914971/105406485-43fd4700-5c0b-11eb-9c70-a3f39881218c.png)

![image](https://user-images.githubusercontent.com/64914971/105406584-60997f00-5c0b-11eb-957f-d6c08cf36d9b.png)

Temos implementado no cliente a Project Function P_M461PRCV que vinha sendo utilizada sem problema algum com o TDS. Realizamos a atualização do RPO (utilizando o D-1), atualizamos os binários e também desabilitamos o TDS para usar o VS Code. 

Ocorre que ao compilar esse fonte o VS Code apresenta a seguinte mensagem:
functions are not allowed in code. Use USER FUNCTION or STATIC FUNCTION.
![image](https://user-images.githubusercontent.com/64914971/105406674-858df200-5c0b-11eb-9cc4-2dffc8217d71.png)

Como resolver essa questão?

Grato!

**Comment by ricardomansano** [comment]
Bom dia Roberto,

Conforme conversamos, as Project Functions exigem chave de compilação

Abra pfv um chamado com o Segmento de Materiais, ja que este ponto de entreda é deles, eles lhe indicarão o melhor caminho pra solicitar essa chave, caso seja autorizada.

At,
