### ISSUE TITLE
Instalação off-line do VS-Code e extensões 

### ISSUE THREAD

**Issue by PauloHCSilva** [totvs/tds-vscode#630]
Boa tarde,
Posso baixar o VS-Code e extensões  e copiar para uma outra maquina SEM ACESSO a internet, qual o procedimento?

**Comment by brodao** [comment]
@PauloHCSilva 

Não recomendo efetuar uma copia. Baixe o instalador https://code.visualstudio.com/download# e o VSIX direto do MarketPlace.
Copie os arquivos para a máquina alvo, na máquina alvo, instale o VSCode. No VS Code, acione F1, install vsix. Selecione o arquivo da extensão.

A disposição.
