### ISSUE TITLE
Ao debugar um fonte o VSCODE não mostra a linha correta e ou não obedece os breakpoints - Só no ambiente Totvs Cloud

### ISSUE THREAD

**Issue by luiz2505** [totvs/tds-vscode#631]
Ao tentar fazer um debug numa cópia do RPO de produção, via Balance1, o VsCode não para nas linhas certas, assinaladas como Breakpoints e ou quando pára, não pára na linha correta.   

Isto só ocorre na compilação/debug num ambiente que fia na Cloud Totvs.  Em ambiente locais não ocorre. 

https://user-images.githubusercontent.com/78000128/106134369-33862880-6145-11eb-8490-07b639138f0a.mp4

**Comment by lwtnb-wrk** [comment]
@luiz2505 Isso deve ocorrer por nao ser o codigo fonte da versão exata que esta compilado no RPO da Cloud. 
Voce compilou exatamente este codigo fonte no ambiente Cloud que esta debugando?

**Comment by luiz2505** [comment]
Sim é a versão exata.  Testei com outros códigos fonte e o problema se
repete. Dá a impressão que o fonte compilado não está sendo enviado para o
RPO.
Também experimentei excluir o fonte do RPO e compilar novamente: mesmo
problema.
Também experimentei partir de um RPO que não tem o fonte: mesmo problema.
Não consegui identificar o porquê, já que eu trabalho compilando fontes em
outros ambientes e não tenho esse problema.

Em qui., 28 de jan. de 2021 às 08:50, lwtnb-wrk <notifications@github.com>
escreveu:

**Comment by danielbolognani** [comment]
Ola @luiz2505 
Como o problema ocorre apenas no ambiente Cloud, por favor abra um chamado para que a equipe de Cloud consiga te auxiliar.
Minha suspeita é que vc está apontando para um balance e o debug não cai no mesmo appserver que a compilação.

**Comment by luiz2505** [comment]
Daniel é uma das minhas suspeitas também. Vou retomar o contato com a Cloud da Totvs e depois darei notícias.

**Comment by brodao** [comment]
@luiz2505 

Veja em [Depuração](https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md) nota para cliente Cloud.

**Comment by luiz2505** [comment]
Valeu. Eu tinha aberto um chamado lá e me mandaram para cá. Agora com essas
excelentes explanações que você passou, vou reabrir o chamado e ligar lá.
Assim que me atenderem e responderem, darei notícias para vocês.
A galera aqui é top. Grato a todos!!!!

Em qui., 28 de jan. de 2021 às 11:31, Daniel Otto Bolognani <
notifications@github.com> escreveu:
