### ISSUE TITLE
Falha de conexão com o servidor - CONNECTION TOKEN WAS NOT INFORMED

### ISSUE THREAD

**Issue by vitormds22** [totvs/tds-vscode#632]
Olá, tudo bem ? 

Estou com problema na hora de compilar um fonte na minha base de teste, aparece a mensagem abaixo:
[Info  - 2:11:13 PM] Starting connection to the server 'MASPAC_TESTE' (187.94.63.146@2030)
[Error - 2:11:13 PM] Connection failed. Could not connect to server 187.94.63.146:2030.
[Error - 2:11:24 PM] One or more validations errors detected:
- Connection token was not informed.

E também aparece a mensagem do print abaixo:

![Screenshot_20210204_144642](https://user-images.githubusercontent.com/33588882/106933977-5477ec00-66f8-11eb-9adb-2a3115f1fcfb.png)

At.te

**Comment by vitormds22** [comment]
Pessoa, algum retorno ? 

Precisava muito resolver esse problema, e nem desinstalando o VS Code funciona.... 

Tem alguma forma de resetar as configurações do plugin ? 

At.te

**Comment by lwtnb-wrk** [comment]
@vitormds22 Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie seus logs para analises.

**Comment by vitormds22** [comment]
Segue em anexo, 

O arquivo dap.log não está sendo gerado.

At.te
[totvsls.log](https://github.com/totvs/tds-vscode/files/5946858/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/5946859/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/5946860/totvsls_out.log)

**Comment by lwtnb-wrk** [comment]
@vitormds22 O dap.log é somente para caso de problemas no debug.
Os logs não apresentaram nada sobre a compilação. Após ligar as configurações de log você precisa repetir as operações para serem logadas. Favor reenviar os logs assim que refazer as operações.

**Comment by vitormds22** [comment]
Consegui!!! 

Exclui o server e inseri novamente e voltou;

Já havia feito, mas dessa vez ele solicitou para inserir o diretorio de includes e o exe do smartclient.

Obrigado.

**Comment by ricardomansano** [comment]
Bom dia @vitormds22 ,
Grato pelo retorno
