### ISSUE TITLE
Compilar arquivo .tres User with no rights to change resource.

### ISSUE THREAD

**Issue by DouglasChagas** [totvs/tds-vscode#634]
@lwtnb-wrk  mesmo meu settings.json estando assim:
{
"totvsLanguageServer.welcomePage": false,
"[advpl]": {
"files.encoding": "windows1252"
},
"totvsLanguageServer.askEncodingChange": false,
"totvsLanguageServer.askCompileResult": true,
"totvsLanguageServer.folder.extensionsAllowed": [
".TRES",
".PRW",
".PRX",
".PRG",
".PPX",
".PPP",
".TLPP",
".APW",
".APH",
".APL",
".AHU",
".TRES",
".PNG",
".BMP",
".RES",
".4GL",
".PER",
".JS"
]
}

Ele não compila o arquivo .tres informando:
[Info - 00:16:54] Start secure compiling d:/vscode_fontes/caracol/caracol/antigos/rh/fontes_totvs/impirpf_pt-br.tres (1/1).
[Error - 00:16:54] User with no rights to change resource.
[Info - 00:16:54] Aborting end build (rollback changes).
[Error - 00:16:54] One or more files have errors and/or warnings. See problems and logs for details.
[Info - 00:16:54] Recompile finished.

Sabe o que pode ser?

**Comment by lwtnb-wrk** [comment]
@DouglasChagas Esse arquivo "impirpf_pt-br.tres" parece ser um fonte padrão e portanto não deve ser sobrescrito. Por isso parece ocorrer erro de permissão (User with no rights to change resource.).
Porque você está tentando compilar este arquivo?

**Comment by DouglasChagas** [comment]
> @DouglasChagas Esse arquivo "impirpf_pt-br.tres" parece ser um fonte padrão e portanto não deve ser sobrescrito. Por isso parece ocorrer erro de permissão (User with no rights to change resource.).
> Porque você está tentando compilar este arquivo?

Pq ele consta no pacote da dirf PACOTE_DE_CORRECAO_10567712_DRHGCH-23055_12.1.25.ZIP
O arquivo .ch vai para o diretorio de includes.
Porém os arquivos .tres é dito que precisa ser compilado, pois é mais recente do que o recurso existente no rpo.

**Comment by lwtnb-wrk** [comment]
@DouglasChagas De onde você pegou esse arquivo "PACOTE_DE_CORRECAO_10567712_DRHGCH-23055_12.1.25.ZIP"? No portal o arquivo que encontrei foi o "PACOTE_DE_CORRECAO_000000_DRHGCH-16253_12.1.25.ZIP"...
Enfim de qualquer forma no "pacote de correção" acredito que você deveria aplicar os patches (arquivos .ptm) e não precisaria compilar fontes e recursos como parece que está fazendo. No ZIP não existem arquivos .ptm para serem aplicados?

**Comment by DouglasChagas** [comment]
> @DouglasChagas De onde você pegou esse arquivo "PACOTE_DE_CORRECAO_10567712_DRHGCH-23055_12.1.25.ZIP"? No portal o arquivo que encontrei foi o "PACOTE_DE_CORRECAO_000000_DRHGCH-16253_12.1.25.ZIP"...
> Enfim de qualquer forma no "pacote de correção" acredito que você deveria aplicar os patches (arquivos .ptm) e não precisaria compilar fontes e recursos como parece que está fazendo. No ZIP não existem arquivos .ptm para serem aplicados?

Peguei neste link oficial totvs: https://tdn.engpro.totvs.com.br/pages/releaseview.action?pageId=587632704

E os arquivos impirpf.prx e impirpj.prx precisam ser compilados, constam no pacote e são mais recentes. E para serem compilados precisam do .ch, que já coloquei no diretorio includes, e que estes .tres que agora não residem mais no .ch sejam compilados no RPO, tbm por serem mais recentes.

O problema é, pq mesmo estando descrito no settings a extensão .tres, o vscode não esta permitindo subir os arquivos para o RPO?

**Comment by lwtnb-wrk** [comment]
@DouglasChagas Ao invés de compilar os fontes e recursos, aplique o patch adequado ao seu ambiente.

**Comment by ricardomansano** [comment]
Bom dia @DouglasChagas ,
     Como o @lwtnb-wrk comentou, estes arquivos TRES foram compilados com privilégio alto no RPO padrão, sem uma chave de autorização, não conseguirá substituí-los.
     Por aqui nao temos como te ajudar, e acredito que esses arquivos tenham sido enviados por acidente no ZIP.
     Abra um chamado no suporte informando o ocorrido e comente que foi minha sugestão, acredito que eles possam lhe confirmar minha suspeita

At
Ricardo Mansano
PO SmartClient’s / IDE’s

**Comment by DouglasChagas** [comment]
> Bom dia @DouglasChagas ,
> Como o @lwtnb-wrk comentou, estes arquivos TRES foram compilados com privilégio alto no RPO padrão, sem uma chave de autorização, não conseguirá substituí-los.
> Por aqui nao temos como te ajudar, e acredito que esses arquivos tenham sido enviados por acidente no ZIP.
> Abra um chamado no suporte informando o ocorrido e comente que foi minha sugestão, acredito que eles possam lhe confirmar minha suspeita
> 
> At
> Ricardo Mansano
> PO SmartClient’s / IDE’s

Em documentação de vcs diz para compilar, em outras diz para colocar na pasta Include.
Coloquei na include e segui adiante.
