### ISSUE TITLE
Patch Generation from File/Folder não funciona na release 12.1.17

### ISSUE THREAD

**Issue by raquelhager** [totvs/tds-vscode#635]
Bom dia!

Utilizando o binário **LG-17 64 Bits** para release 12.1.17 não é gerado patch a partir da opção 'Patch Generation from File/Folder' no VS Code.

Appserver - appserver-19.3.0.3-winx64
https://arte.engpro.totvs.com.br/tec/appserver/lobo_guara/windows/64/latest/

SmartClient - smartclient-17.3.0.18_rc1-win64-shared
https://arte.engpro.totvs.com.br/tec/smartclient/lobo_guara/windows/64/latest/

RPO - 07/02/2021 17:02:59	
https://arte.engpro.totvs.com.br/protheus/padrao/builds/12.1.17-201808/latest/repositorio/lobo_guara/

* TOTVS - Build 7.00.191205P - Mar 31 2020 - 12:54:19
* Build: 64 bits
* SVN Revision: 26467
* Build Version: 19.3.0.3

**Observação importante:** também foi realizado o mesmo teste utilizando binário **NG-32 Bits** Latest, o erro permanece!
Os dados de ambos os testes estão anexo!
[Dados-Issue-635.zip](https://github.com/totvs/tds-vscode/files/5943872/Dados-Issue-635.zip)

**Comment by lwtnb-wrk** [comment]
@raquelhager Grato pelas informações. Porém acho que tem alguns dados misturados. Os "Dados-NG" tem informação do appserver-19.3.0.3.
Enfim esse appserver 19.3.0.3 tinha realmente problemas na geração de patches que foram corrigidas já. Atualize seu appserver e refaça seus testes.
Pelos logs não vejo nenhum erro durante a geração de patches. O arquivo simplesmente não é gerado? Ocorre alguma mensagem de erro nos logs do appserver?

**Comment by raquelhager** [comment]
@lwtnb-wrk  agradeço o retorno!

Enviei os dados que utilizei para teste com o binário NG 32 Bits errado, segue arquivo correto:
[Dados-NG.txt](https://github.com/totvs/tds-vscode/files/5951469/Dados-NG.txt)

Desculpe, não entendi onde devo pegar um binário atualizado pois eu peguei o arquivo do appserver appserver-19.3.0.3-winx64 na pasta **LATEST** do Arte:
https://arte.engpro.totvs.com.br/tec/appserver/lobo_guara/windows/64/latest/

O problema é que o arquivo simplesmente não é gerado e não ocorre nenhuma mensagem de erro nos logs do appserver.

**Comment by danielbolognani** [comment]
@raquelhager Parece ter algum problema nessa pasta lastest do ARTE, o correto seria essa versão:
https://arte.engpro.totvs.com.br/tec/appserver/lobo_guara/windows/64/next/
Que é a versão 17 do Lobo Guara

**Comment by raquelhager** [comment]
Bom dia,

Realizei os testes conforme solicitado e ainda não foi gerado pacote.

Segue dados em anexo:

[Dadps LG-17 64 Bits.zip](https://github.com/totvs/tds-vscode/files/5965214/Dadps.LG-17.64.Bits.zip)

**Comment by lwtnb-wrk** [comment]
@raquelhager Pelo log vi que sua extensão está bem desatualizada. Tivemos um problema no marketplace então será necessário desinstalar a extensão desatualizada e instalar a extensão mais atual.
Veja se isso resolve o problema da geração de patches.

**Comment by raquelhager** [comment]
Desinstalei a extensão e reinstalei, continua sem gerar patch.
Segue dados em anexo:
[Dadps LG-17 64 Bits.zip](https://github.com/totvs/tds-vscode/files/5967927/Dadps.LG-17.64.Bits.zip)

**Comment by lwtnb-wrk** [comment]
@raquelhager Pelos logs do tds-vscode e do AppServer realmente não parece ocorrer nenhum erro.
Testei aqui num AppServer 17.3.0.20 só que meu RPO está na versão 12.1.025 e não tive problemas para gerar o patch a partir de uma pasta.
O diretório que você seleciona para a geração do patch tem permissão de escrita? Está em um drive normal na sua maquina local? Existe uma questão que não permite o uso de pastas de rede, então se for o caso, experimente um drive e diretório diferente para testar.

**Comment by raquelhager** [comment]
Bom dia!

Você pode me passar onde vc baixou esse RPO?

O diretório que estou usando para geração é o mesmo que eu utilizo quando gero para as demais versões (23,25,27) e para todas as demais, o patch é gerado.
Eu inclusive testei outros diretórios para validar se este era o problema, no meu entendimento, não é essa a questão.

**Comment by ricardomansano** [comment]
Encerrando devido ao tempo sem interação, qualquer problema estamos a disposição
