### ISSUE TITLE
C2090  File not found PRTOPDEF.CH

### ISSUE THREAD

**Issue by Robsondpm** [totvs/tds-vscode#636]
**Por favor estou com esse erro ao compilar um fonte e vi várias postagens do meio do ano passado que a solução seria somente via downgrade mas nem isso estou conseguindo. Alguma sugestão ainda que paliativa por favor?

Include ok e atualizado. Extensão Totvs DevStudio 1.2.1 e a opção de instalar outra versão está desabilitada conforme anexo.

Obrigado.
![image](https://user-images.githubusercontent.com/69259802/107424623-a788df00-6afc-11eb-9cc7-bccbb932850f.png)
![ErroInclude](https://user-images.githubusercontent.com/69259802/107424645-aeafed00-6afc-11eb-9f98-e994b78028d1.jpg)

**Comment by lwtnb-wrk** [comment]
@Robsondpm Veja se configurou corretamente a pasta de includes.
https://github.com/totvs/tds-vscode/blob/master/docs/compilation.md#configura%C3%A7%C3%A3o-de-include-busca-de-arquivos-de-defini%C3%A7%C3%A3o

**Comment by Robsondpm** [comment]
Ola, sim está certinho. Configurei até localmente pra evitar problemas. Estava compilando tudo até agora a pouco. é o mesmo erro que tem dezenas de postagens falando que ocorre o mesmo e só resolveu voltando a extensão pra versão 1.0.3. Obrigado

**Comment by lwtnb-wrk** [comment]
@Robsondpm Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e  repita as operações de compilação. Depois nos envie os logs para analise.

**Comment by Robsondpm** [comment]
Boa noite. Não Gerou o arquivo de log de jeito nenhum. Anexo como ficaram meus arquivos de configuração. Poderia ajudar se estou fazendo algo errado?
![LogVSCODE](https://user-images.githubusercontent.com/69259802/107436340-26d1df00-6b0c-11eb-89c9-9851f7b69d2e.jpg)

Obrigado

**Comment by lwtnb-wrk** [comment]
@Robsondpm Os logs deveriam ter sido gerados na raiz do projeto (Customizacoes).
Notei que mencionou que estava funcionando e parou de repente. Depois de fazer o que ele parou de funcionar?

**Comment by Robsondpm** [comment]
Bom dia,
reiniciamos tudo dos servidores ontem e hoje fui compilar e funcionou dessa vez. Muito obrigado pela atenção.
Quanto a geração de LOG, ve algo que possa estar errado no meu arquivo de configurações para não gerar? Obrigado.

**Comment by lwtnb-wrk** [comment]
@Robsondpm Parece tudo certo pra mim.
