### ISSUE TITLE
Sem retorno para tentativa de conexão a ambiente

### ISSUE THREAD

**Issue by raulvictorrosa** [totvs/tds-vscode#64]
Estou tentando realizar uma conexão a um ambiente mas não obtenho nenhum retorno dizendo se a conexão foi ou não estabelecida.

Identifiquei que a conexão não foi estabelecida e o seguinte log é apresentado no console do chrome.

[log-chrome.log](https://github.com/totvs/tds-vscode/files/3249266/log-chrome.log)

**Comment by lwtnb-wrk** [comment]
@raulvictorrosa Essa tentativa foi imediatamente apos a inicializacao do vscode? Em que circustancia ela ocorreu? Pelo log informado o Language Client ainda não estava pronto para uso. É uma instalação nova? Voce tentou desinstalar e reinstalar a extensão tds-vscode? Grato pelos testes e pelas informacoes.

**Comment by raulvictorrosa** [comment]
Fiz a configuração do smartclient e dos includes pela extensão, digitei Ctrl+P e pesquisei pela opção TOTVS: Select Server, digitei as informação do server e nada aconteceu, então consultei o console deu erro que te passei.

**Comment by lwtnb-wrk** [comment]
@raulvictorrosa Voce tem servidores cadastrados? Eles foram importados do smartclient ou configurados por voce? Onde esse log-chrome.log foi gerado? Eu nao encontrei nenhum arquivo com esse nome em meu ambiente. Abs

**Comment by raulvictorrosa** [comment]
Sim, os servidores foram importados do smartclient. O nome do arquivo fui eu quem colocou, esse log do erro que está dentro do arquivo aparece se eu acessar o terminal do vscode e ir na área output, ou se eu acessar no menu do vscode "Help -> Toogle Developer Tools".
![image](https://user-images.githubusercontent.com/13530065/58903886-d2425380-86dc-11e9-857a-4cd1dd8bbf65.png)

**Comment by raulvictorrosa** [comment]
![image](https://user-images.githubusercontent.com/13530065/58904148-5268b900-86dd-11e9-99c5-936d0b77f4a4.png)

**Comment by lwtnb-wrk** [comment]
@raulvictorrosa Voce poderia realizar um teste? Cadastre um servidor manualmente na visão de Servidores clicando no icone "+" indique os dados requisitados e tente se conectar neste servidor da mesma forma. Se nao se importar, anexe o arquivo "servers.json" que esta na pasta "C:\Users\<seu_usuario>\.totvsls" para verificarmos seu conteudo. Abs

**Comment by raulvictorrosa** [comment]
Resolvido, limpei os servers cadastrados na pasta .totvsls e adicionei novamente manualmente, tentei conectar e funcionou.

**Comment by lwtnb-wrk** [comment]
@raulvictorrosa Grato pelos testes. Se tiver outros problemas fique a vontade para abrir novas issues.
