### ISSUE TITLE
ERRO COMPILAR VSCODE TOTVS

### ISSUE THREAD

**Issue by LeoDantas** [totvs/tds-vscode#643]
Boa tarde, ao tentar compilar tanto no VSCODE local quanto direto no servidor ocorre o problema em anexo. Semana passada estava compilando normalmente
.
![image](https://user-images.githubusercontent.com/19985004/108247512-7f6b3280-7131-11eb-8f00-d71bcbdc1a7c.png)

**Comment by brodao** [comment]
Favor consultar #607 e se não for o caso, ajude a ajuda-lo conforme https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md.

**Comment by lwtnb-wrk** [comment]
@LeoDantas Esse erro estava realmente ocorrendo em versões desatualizadas de um Appserver conforme descrito na #607 
Caso não seja esse o problema abra uma outra issue com mais detalhes e anexe os logs requisitados acima.
