### ISSUE TITLE
Aplicar patch no repositório do TSS pelo vscode

### ISSUE THREAD

**Issue by rnogueiradev** [totvs/tds-vscode#644]
Ao tentar aplicar um patch do tss no ambiente do tss aparece o erro abaixo (patch file not found)

[Info - 12:21:41 PM] Starting apply patch.
[Info - 12:21:41 PM] Starting build for environment sped.
[Info - 12:21:42 PM] Applying patch file: c:/Users/Administrator.STECK/Downloads/21-02-04_ATUALIZACAO_12.1.25_TSS_PROTHEUS_EXPEDICAO_CONTINUA/expedicao_continua_12.1.25_tss_protheus_tttp120_lg.ptm
[Error - 12:21:42 PM] Patch (expedicao_continua_12.1.25_tss_protheus_tttp120_lg.ptm) could not be applied. Server returned: Patch file not found.
[Info - 12:21:42 PM] Aborting end build (rollback changes).
[Info - 12:21:42 PM] Apply patch finished.

**Comment by brodao** [comment]
Favor consultar #607 e se não for o caso, ajude a ajuda-lo conforme https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md.

**Comment by rnogueiradev** [comment]
Boa tarde Alan, obrigado pela interação mas o problema é outro e a solução foi atualizar o appserver, já estou com o último appserver do portal na versão 12.1.25 que é a que usamos.

**Comment by rnogueiradev** [comment]
> Favor consultar #607 e se não for o caso, ajude a ajuda-lo conforme https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md.

Boa tarde Alan, obrigado pela interação mas o problema é outro e a solução foi atualizar o appserver, já estou com o último appserver do portal na versão 12.1.25 que é a que usamos.

**Comment by DanielYampolschi** [comment]
Ola @rnogueiradev Obrigado pela informação. Como o problema foi resolvido, vamos encerrar essa issue. Caso tenha qualquer outro problema por favor abra uma nova issue para acompanharmos.
