### ISSUE TITLE
Erro de compilação

### ISSUE THREAD

**Issue by AstraFarma** [totvs/tds-vscode#645]
**Describe the bug**
Ao Compilar um fonte no ambiente, acusa o erro "Invalid use of Annotation in ADVPL source file"  em uma linha fixa do fonte e não compila por nada, e não consigo resolver de forma alguma.

**Screenshots**

![image](https://user-images.githubusercontent.com/47606107/108411744-bf9ce480-7207-11eb-94e4-5197230eaed8.png)

**Desktop (please complete the following information):**
 - OS/Architecture: [e.g. Windows 64 bits]

**Appserver (please complete the following information):**

![image](https://user-images.githubusercontent.com/47606107/108413703-17d4e600-720a-11eb-9a6c-9348fa612891.png)

**Comment by ricardomansano** [comment]
Bom dia, 
Nos envie o trecho de fonte que acusa o erro.

**Comment by AstraFarma** [comment]
O Erro fica fixo em uma linha específica, e mesmo que eu comente o trecho ou de enter, ele continua o erro na mesma linha.

segue o erro em uma linha com código.

![image](https://user-images.githubusercontent.com/47606107/108510827-c413dc80-729d-11eb-930f-34efbf19e846.png)

e na linha sem código.

![image](https://user-images.githubusercontent.com/47606107/108510995-02110080-729e-11eb-8fa1-423ca7b6e2b4.png)

e segue o fonte zipado abaixo !


[MATR924AF.zip](https://github.com/totvs/tds-vscode/files/6010311/MATR924AF.zip)

**Comment by ricardomansano** [comment]
@AstraFarma 
Manda o CH pra mim pfv

	"message": "C2090  File not found MATR924.CH",

**Comment by AstraFarma** [comment]
Segue

[matr924.zip](https://github.com/totvs/tds-vscode/files/6010478/matr924.zip)

**Comment by ricardomansano** [comment]
@AstraFarma ,
Tive 23 Warnings mas compilou (enviando print), faz o seguinte:

-Exclue o fonte do RPO via VSCode, partindo do principio que um dia vc ja compilou ele
-Faz uma copia dele pra outra pasta, só pra garantir
-Coloque o CH na mesma pasta, tambem só pra garantir
-Refaça a compilação

F
![vscode_645_1](https://user-images.githubusercontent.com/33813921/108515374-c11bea80-72a3-11eb-809d-57b539d87480.png)
ico na escuta

**Comment by AstraFarma** [comment]
Nada ainda, será que pode ser alguma extensão do VSCODE que pode estar dando esse erro ?

Segue as extensões que tenho instaladas.

![image](https://user-images.githubusercontent.com/47606107/108519286-41444f00-72a8-11eb-9f71-a2c3917df2ed.png)

**Comment by ricardomansano** [comment]
@AstraFarma ,

Pode ser que sim, alguns plugins podem colocar TAGs no diretório .vscode que prejudiquem o plugin da IDE.

Para testar isso é um pouco complexo, mas vms lá: 

-Desabilite as demais extensões (não precisa desinstalar)
-O TOTVS Monitor você pode até desinstalar pois já incluímos o Monitor no plugin da IDE, basta clicar com o botão direito do mouse no AppServer conectado e selecionar “Open monitor view”
-Vá até o diretório principal (raiz) da sua workspace (onde estão os fontes, resource, etc)
-renomeie a pasta .vscode para .vscode-2 (por exemplo)
-feche o vscode e reabra
-ao abrir a pasta ele vai pedir para você refazer a configuração dos appserver’s e smartclient
-crie um apenas um server para o teste
-tente recompilar

Se isso funcionar foi alguma das extensões que prejudicaram o uso da nossa, a única que sabemos ser incompatível pois usa muitas TAGs iguais é a I Love AdvPL

Fico na escuta,

**Comment by AstraFarma** [comment]
Grande Mansano, era isso mesmo, recriei a pasta do vccode e agora voltou a compilar. Muito obrigado pela atenção !!!

**Comment by ricardomansano** [comment]
Ótima noticia @AstraFarma ,

Estamos aqui se precisar
