### ISSUE TITLE
Não compila quando tem warning

### ISSUE THREAD

**Issue by fabiohayama** [totvs/tds-vscode#646]
Boa tarde turma,

Está meio estranho, quando o fonte tem warning não está compilando de verdade.
Ele não apresenta nenhum erro, mas se olharmos no inspetor, o fonte não foi compilado.

E depois de ajustarmos o warning ele compila.
Só que são uns warning mais simples, tipo variavel não utilizada.

Muito obrigado.

**Comment by lwtnb-wrk** [comment]
@fabiohayama Você está compilando uma pasta inteira ou projeto?
Acredito que deve estar ocorrendo algum outro erro além dos warnings e deve estar ocorrerendo o "rollback" de todos os arquivos.
Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envies os logs gerados para analises.
