### ISSUE TITLE
Erro ao debugar via VSCODE

### ISSUE THREAD

**Issue by andreiarochaasrconsult** [totvs/tds-vscode#647]
Utilizamos o sistema Protheus e ao tentar debugar via VSCODE, apresenta o erro que segue em anexo, porém, os usuários acessam pela mesma pasta System e não apresentaram problemas de acesso. Parei o sistema e alterei o arquivo sigapss pelo bkp anterior, por via das dúvidas, mas não surtiu efeito no debug.
Segue erro ao debugar via VSCODE. Segue também o arquivo sigapss:

![erro_vscode](https://user-images.githubusercontent.com/79719746/109344024-efbe3600-784c-11eb-921f-2a056a72d525.PNG)

**Comment by andreiarochaasrconsult** [comment]
Boa tarde,
Alguma analise do erro?

**Comment by lwtnb-wrk** [comment]
@andreiarochaasrconsult O Appserver utilizado está em um servidor remoto? Não entendi a questão de outros usuários acessarem a mesma pasta System.
Em que momento ocorre esse erro? O erro acima está sendo exibido no console do Appserver?
De qualquer forma veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs e nos envie os logs para analises.
