### ISSUE TITLE
Erro ao compilar

### ISSUE THREAD

**Issue by csescobar** [totvs/tds-vscode#648]
Ao tentar compilar um fonte, aparece uma mensagem informando que o arquivo não foi encontrado.

Print da pasta com os arquivos:
![image](https://user-images.githubusercontent.com/29630079/109498203-e9f56a00-7a71-11eb-8b93-3515e41dcad5.png)

```
(  44.363s) [querydb         ]  connection_manager.cc:826   | cFile=/home/cesar/Totvs/src/Gestão de Pessoal/Relatorios/MODR022.prw, drive=, dir=/home/cesar/Totvs/src/Gestão de Pessoal/Relatorios/, name=MODR022, ext=.prw
(  44.363s) [querydb         ]  connection_manager.cc:867   | File /home/cesar/Totvs/src/Gestão de Pessoal/Relatorios/MODR022.prw not found.
(  44.363s) [querydb         ]               timer.cc:41    | [perf] Compile took 0.225 ms
(  44.363s) [querydb         ]  connection_manager.cc:3441  | Aborting end build (rollback changes).
```

Sistema operacional: Zorin OS 15.3

**Comment by danielbolognani** [comment]
Ola, tente não utilizar espaços, letras maiúsculas e nem caracteres especiais no nome do arquivo e nem no path. Principalmente por ser Linux.

**Comment by lwtnb-wrk** [comment]
@csescobar Somente complementando, esse é um comportamento dos Appservers Linux e que não temos controle.
Somente essa solução de contorno, removendo espaços, letras maiúsculas e caracteres especiais no nome do arquivo e no path, resolvem o problema.
