### ISSUE TITLE
Compilar todo o Projeto

### ISSUE THREAD

**Issue by Welintonf** [totvs/tds-vscode#649]
Pessoal, 
Percebi que quando eu mando compilar todo o projeto ou toda a pasta, a compilação nao é executada mesmo dando mensagem positiva.
O Fonte não vai para o RPO.
Tem algum processo pra fazer isso?

**Comment by lwtnb-wrk** [comment]
@Welintonf Muito provavelmente esta ocorrendo algum erro critico em um dos fontes que esta sendo compilado e todo o processo é desfeito (rollback).
No console você pode ver em qual fonte está ocorrendo o problema e alem disso ele deveria aparecer na lista de "Problemas".
Se isso não estiver ocorrendo, veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analises.
