### ISSUE TITLE
Escolher onde salvar as configurações dos servidores

### ISSUE THREAD

**Issue by luizhj** [totvs/tds-vscode#65]
Sou consultor e com o workspace do antigo TDS dava para configurar os servidores de cada cliente em seus respectivos workspaces.

Hoje a extensão salva os servidores em uma pasta do usuário sendo assim todos os servidores configurados ficam disponíveis em todas as pastas de projeto abertas.

Teria como ter uma configuração para alterar onde salvar esse arquivo ou se ele existir na pasta de ambiente aberta ele ser mandatório sobre o arquivo da pasta do usuário?

Desde já obrigado, essa versão no vscode tá ficando show!

**Comment by lwtnb-wrk** [comment]
@luizhj Grato pela sugestão e testes. Vamos pensar em uma solução para a situação que voce descreveu. Se tiver outras ideias por favor abra outras issues pois nada melhor que as ideias dos desenvolvedores que usam o produto para tornar-lo melhor.

**Comment by izacsc** [comment]
Geralmente as configurações das extensões ficam no arquivo de configurações do vscode ( que já tem essa configuração por workspace e por usuário ). Pq optaram por fazer um arquivo a parte?

**Comment by lwtnb-wrk** [comment]
@luizhj @izacsc A cada workspace novo criado seria necessario recadastrar os servidores entao optamos por gravar em um outro local para que todos os workspaces pudessem compartilhar das informações de servidores, mas por outro lado nao haviamos pensado que era o que alguem iria precisar. De qualquer forma acho que o mundo ideal seria um local onde sera possivel manter todas as configuracoes de todos os servidores, mas que apenas os servidores que fossem utilizados por um determinado workspace fosse exibidos nele. Por exemplo:
- Configuracao Master
  - servidor1
  - servidor2
  - servidor3
  - servidor4
  - servidor5
- Workspace 1
  - ref servidor 1
  - ref servidor 2
- Workspace 2
  - ref servidor 2
  - ref servidor 4
- Workspace 3
  - ref servidor 3
Assim ficaria melhor?

**Comment by luizhj** [comment]
pra mim faz sentido, acredito que me atenderia tranquilamente

**Comment by izacsc** [comment]
Na verdade a configuração de usuário serve para todos os workspaces criados, mas existe também a configuração por workspace.

![image](https://user-images.githubusercontent.com/423449/58971660-4be84900-8792-11e9-9a47-833b3467e37b.png)

https://code.visualstudio.com/docs/getstarted/settings

Pelo que eu sei funciona assim. Existem as configurações padrão. O usuário pode sobrescrever as configurações padrão com configurações de usuário e workspace. A ordem de prevalência das regras é WorkSpace>Usário>Padrão. A configuração de usuário é salva em um arquivo dentro da pasta do usuário no windows ( por exemplo C:\Users\izac.ciszevski\AppData\Roaming\Code\User\settings.json) e a pasta de workspace numa pasta oculta dentro do workspace (C:\TFS\Protheus Padrão\Master\WebService\RH\.vscode\settings.json)

E você pode ter as duas configurações ao mesmo tempo, mas só a mais "forte" prevalece. Se quiser conversar sobre assunto pode me chamar no hangouts.

Nesse cenário que você comentou, acredito que uma configuração geral ficaria na configuração de usuário e pra cada workspace criaria uma nova configuração.

**Comment by lwtnb-wrk** [comment]
@izacsc O que voce menciona faz sentido, mas apesar de serem configuracoes, nao achamos que misturar os settings do vscode com as configuracoes de servidores faria sentido para o vscode, entao o arquivo ficou separado mesmo. Para o caso dos servidores vamos utilizar uma solucao particular para nossas necessidades que deve atender a todos.

**Comment by likid** [comment]
@lwtnb-wrk o ideal é seguir os padrões do vscode, pois o que estamos vendo é que seguir por uma solução particular acabou gerando esta issue pois atende para alguns mas não atende para outros. No início fui procurar onde estavam as configurações do tds e achei estranho estarem em uma pasta fora do vscode. Com este modelo particular que criaram acabou gerando um problema que eu comentei em uma issue onde em uma configuração de workspace com multiple roots, eu preciso criar a configuração do debug na primeira pasta (primeiro root), se eu colocar nas demais ocorre um erro e o debug não é lançado, a configuração do debug deveria neste caso estar no escopo da workspace.

**Comment by luizhj** [comment]
> @izacsc O que voce menciona faz sentido, mas apesar de serem configuracoes, nao achamos que misturar os settings do vscode com as configuracoes de servidores faria sentido para o vscode, entao o arquivo ficou separado mesmo. Para o caso dos servidores vamos utilizar uma solucao particular para nossas necessidades que deve atender a todos.

que tal manter o arquivo servers.json dentro da pasta .vscode do workspace?
assim não mistura o server com as configurações do vscode, mas ele fica junto do workspace.

**Comment by likid** [comment]
@luizhj uso a extensão sftp e ela faz exatamente isso, cria uma pasta .vscode e dentro dela um arquivo chamado sftp.json onde ficam as configurações dele e isso dentro da workspace.

**Comment by tgmti** [comment]
Estou usando a extensão [advpl-vscode](https://marketplace.visualstudio.com/items?itemName=KillerAll.advpl-vscode) praticamente desde que lançou.

Num primeiro momento ela também só funcionava com o .settings do usuário ou da pasta. Depois evoluiu e adicionou a funcionalidade de Workspace.

Hoje ela está funcionando com os três. Se não me engano dando preferência para a pasta, depois o Workspace e por último o usuário.

Funciona muito bem desta forma. Mas poderia ser até melhor. No caso, como vocês estão usando um arquivo a parte (servers.json), talvez uma boa abordagem seria concatenar (talvez um Object.assign) as configurações de todos os locais onde esteja gravado.

Exemplo de uso: 
 - Os servidores de teste locais da minha máquina, eu deixo nas configurações de usuário, assim qualquer pasta que abro posso compilar neste ambiente sem configurar nada.

 - Nos workspaces que possuem vários projetos, eu coloco a configuração dos servidores de teste específicos (exemplo: bases para testes de módulos específicos, ou clientes grandes que possuem vários servidores e mais de um projeto).

 - As pastas com os fontes de projetos ou clientes pequenos, deixo apenas os servidores deles.

Na extensão Advpl-VsCode, tenho que copiar manualmente meus ambientes de testes para todos os arquivos quando quero testar algo localmente.

Acredito que seria legal se, estando dentro de uma pasta que tenha configurações, ele apresentasse tanto os servidores da configuração geral (de usuário), quanto as específicas, sempre o mais específico sobrepondo o superior em caso de duplicidades.

O que acham da ideia? Seria viável?

**Comment by ricardomansano** [comment]
Boa tarde,

Agradecemos as sugestões/interações de todos porém a feature não será implementada por uma questão de padronização de ambiente da ferramenta.

Muito grato
