### ISSUE TITLE
Erro ao compilar em WS para geração de Client

### ISSUE THREAD

**Issue by AllanThomazelli** [totvs/tds-vscode#650]
Equipe, bom dia.

Sou analista de infraestrutura cloud da Totvs, e temos um cliente o qual está com um problema relacionado a compilação no WebService Soap no VS Code.

Abri o ticket  #11015992 pelo Zendesk explicando a ocorrência, porém o analista de ADVPL orientou no ticket a abrir essa requisição diretamente pelo github. 

Mesmo com as execuções sendo efetuadas via VS Code, ainda ocorre o problema informado, como se tivesse algum bloqueio.

A plataforma Tcloud, onde o ambiente está alocado, não possui restrições de acesso que possam impedir esse tipo de ação.

Conforme relata o cliente:

Após diversas tentativas de acesso ao Web Services, mesmo com dificuldades para compilação do client não estamos conseguindo acessar o mesmo, pois ele não retorna o conteúdo, fizemos testes simples para retorno do conteúdo mas o memo não funciona.

No exemplo abaixo ele retorna o conteúdo como NIL:
![image](https://user-images.githubusercontent.com/79986689/109819823-362be000-7c13-11eb-80fe-35b4720e3022.png)

No segundo exemplo direto pelo endereço ele também dá erro.
![image](https://user-images.githubusercontent.com/79986689/109819908-46dc5600-7c13-11eb-9f2c-44e4424da482.png)

--------------------------------------------------------

Estou anexando nessa issue o appserver.ini com as configurações, e abaixo seguem especificações do ambiente:

![image](https://user-images.githubusercontent.com/79986689/109820004-5cea1680-7c13-11eb-9429-14cc30197a78.png)

[appserver.zip](https://github.com/totvs/tds-vscode/files/6076559/appserver.zip)

Podem apoiar-nos, por gentileza?

Fico a disposição para auxilio no que for necessário.

Att,​
Equipe Cloud Protheus

Allan Thomazelli dos Santos

**Comment by danielbolognani** [comment]
Bom dia, não entendi muito bem onde está o problema, foi possível compilar o programa no ambiente? o problema está na execução?
Se não conseguir executar a função compilada (fora do debug), não é por aqui que iremos te ajudar. A ferramenta apenas compila o fonte prw no appserver, a execução do programa em si não é responsabilidade da extensão.

**Comment by danielbolognani** [comment]
Bom dia, dado o tempo sem resposta, acredito que o problema foi resolvido. Se precisar favor reabrir o chamado com as informações solicitadas.
