### ISSUE TITLE
Insufficient privileges for APPLY_PATCH

### ISSUE THREAD

**Issue by emnovaes** [totvs/tds-vscode#651]
**Describe the bug**
A chave AllowApplyPatch passou a funcionar no TDN VSCode, porém não da forma esperada descrita na documentação da versão eclipse, que aceitava IP ou nome do computador (hostname).

Atualmente funciona apenas informando o IP, mas a maioria dos clientes usam DHCP para liberação de IP's.

Estou implementando um controle para para limitar analistas efetuarem atualizações em produção e este ajuste seria essencial.

**Desktop (please complete the following information):**
 - OS/Architecture: [e.g. linux 64 bits]

**Appserver (please complete the following information):**
 - Build (with date): [e.g. Build 7.00.191205P - Jan 15 2021 - 00:04:48]
 - OS/Architecture: [e.g. Linux 64 bits Oracle Linux]
 - Build Version [e.g. 19.3.1.5]

**Comment by emnovaes** [comment]
TDS*

**Comment by amjgfarias** [comment]
Também tenho necessidade desta melhoria.

**Comment by lwtnb-wrk** [comment]
@emnovaes @amjgfarias Estamos com uma versão pré-release disponível com a implementação desta feature. Se puder testar e validar a implementação isso auxiliará na liberação oficial.
https://github.com/totvs/tds-vscode/releases/tag/v1.3.4
