### ISSUE TITLE
Authentication error: Server returned a non numeric value.

### ISSUE THREAD

**Issue by EduradoPessoa** [totvs/tds-vscode#652]
Não consigo conectar o serviço para poder compilar

**Comment by lwtnb-wrk** [comment]
@EduradoPessoa Por essa mensagem acredito que o RPO esta retornando algo inesperado. Veja se consegue efetuar um backup e pegar um RPO novo para testar.
Se isso não resolver, veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by HMSimoes** [comment]
Estou com mensagens parecidas na versão 12.1.33, estamos tentando aplicar patch's oficiais e esta ocorrendo esse erro ao tentar conectar:

[Error - 15:11:16] Authentication error: Server returned a non numeric value.
[Error - 15:11:16] Authentication failed. Could not authenticate to server.

**Comment by brodao** [comment]
@HMSimoes 

Verifique no log de console se esta ocorrendo algum problema no processo de validação. Se não houver nenhuma informação relevante, verifique se o server esta esperando conexão segura ou não e ajuste a chave "secure" na definição do [servidor](https://github.com/totvs/tds-vscode/blob/master/docs/servers.md).

Atente que se o servidor estiver no TCloud, você deve entrar em contato com ele para saber como proceder.
