### ISSUE TITLE
Unable to connect to the server

### ISSUE THREAD

**Issue by lucaslopezvr** [totvs/tds-vscode#653]
Muito boa tarde! Tudo bem ?

Estou com um problema ao tentar conectar no server que é apresentada a mensagem

[Error - 13:53:22] Unable to connect to the server. Check if the IP:port is correct, the server is online and try again.

Eu usava outra extensão e agora estou mudando para a oficial da Totvs.

Launch.json

{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "TOTVS Language Debug",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "C:/totvs/bin/smartclient/smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true
		}
	]
}

Settings.json

{
    "totvsLanguageServer.welcomePage": false
}

**Comment by lwtnb-wrk** [comment]
@lucaslopezvr Certifique-se que os outros plugins estejam desabilitados ou desinstale-os para evitar conflitos.
Voce seguiu https://github.com/totvs/tds-vscode/blob/master/docs/servers.md para cadastrar novamente os servidores?
Se ainda assim estiver com problemas veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e envie os logs para nossa analise.
