### ISSUE TITLE
Erro ao tentar debugar com Vscode

### ISSUE THREAD

**Issue by fabiopedroza** [totvs/tds-vscode#654]
Hoje o meu vscode começou a dar erro. Percebi quando fui debugar

1a coisa é que sumiu os itens do debug e depois começou dar o erro de memória (seguem os anexos)
![erro_vscode](https://user-images.githubusercontent.com/59176849/110981357-c8d02b80-8345-11eb-8623-63b22fac4d3c.PNG)
![VSCODE_DEBUG](https://user-images.githubusercontent.com/59176849/110981363-ca015880-8345-11eb-8c93-8def6b8648a1.PNG)

**Comment by brodao** [comment]
Olá @fabiopedroza,

Pela mensagem apresentada, não é um problema do TDS-VSCode. Lembro que em versões mais antigas da LIB, alguns parâmetros específicos de depuração interferiam na execução da função "getMV", pois esta travava os parâmetros de depuração de forma indevida. Pode estar ocorrendo algo semelhante.

Entre em contato com o suporte de AdvPL ou FW da TOTVS. Vou fechar o chamado e caso tenha outras informações que indiquem problema no TDS-VSCode, reabra esse mesmo chamado.

A disposição.
