### ISSUE TITLE
Debug variáveis com com nome de atributos iguais

### ISSUE THREAD

**Issue by saulogm** [totvs/tds-vscode#655]
**Describe the bug**
Ao realizar o debug com variáveis diferente, mas com nome de atributos iguais o vscode não mostra o conteúdo correto.

**To Reproduce**
1. Compile o programa:
```advpl
Class xteste
	data xvalor
	Method New()
EndClass

Method New() Class xteste
	::xvalor	:= {}
Return self

User function ytst()
	Local oteste	:= xteste():New()
	Local oteste2	:= xteste():New()
	AADD(oteste:xvalor,"codigo A")
	AADD(oteste2:xvalor,"codigo B")
Return
```
2. Coloque um ponto de parada antes de adicionar valor no oteste2
3. Veja o resultado nas variáveis

**Expected behavior**
- oteste:xvalor está correto
- oteste2:xvalor está errado, era esperado Array {size=0}

**Screenshots**
![image](https://user-images.githubusercontent.com/5121888/111234928-62aa0980-85ce-11eb-8a4c-e6af43e17c56.png)

**Desktop:**
 - OS/Architecture: Windows 10 64 bit

**Appserver:**
 - Build 7.00.191205P - Jan 14 2021 - 21:11:32
 - OS/Architecture: Windows 10 64 bit
 - Build Version 19.3.1.5

**Additional context**
Se ir pelo console de depuração direto na oteste2:xvalor ele mostra o valor correto

**Comment by DanielYampolschi** [comment]
Ola @saulogm, Isso acontece usando Debug normal ou o TDS Replay? Obrigado.

**Comment by saulogm** [comment]
no normal mesmo

**Comment by DanielYampolschi** [comment]
Bom dia @saulogm, apenas para avisar que esse problema foi corrigido e estará disponível na próxima atualização.

**Comment by lwtnb-wrk** [comment]
@saulogm Estamos com uma versão pré-release disponível com a correção deste problema. Se puder testar e validar a correção isso auxiliará na liberação oficial.
https://github.com/totvs/tds-vscode/releases/tag/v1.3.4
