### ISSUE TITLE
Configuração de servidores por workspace

### ISSUE THREAD

**Issue by alexandredalpiaz** [totvs/tds-vscode#656]
Bom dia
Tenho uma sugestão de melhoria (não vi se já tem essa ideia aqui):
Acho interessante que cada workspace tenha seu próprio conjunto de servidores, evitando assim a compilação de fontes em RPOs de outros clientes.
Bem como, na troca de uma WS pra outra, poderia já voltar logado no servidor em que estava logado anteriormente.

**Comment by brodao** [comment]
@alexandredalpiaz 

Favor ler [Local de gravação](https://github.com/totvs/tds-vscode/blob/master/docs/servers.md#local-de-grava%C3%A7%C3%A3o-de-serversjson).

A disposição.
