### ISSUE TITLE
C2090  File not found PRTOPDEF.CH

### ISSUE THREAD

**Issue by LeonardoPFranca** [totvs/tds-vscode#657]
Boa tarde, estou com o seguinte problema para compilar um fonte.
C2090  File not found PRTOPDEF.CH

Extensão Totvs DevStudio 1.2.1

![image](https://user-images.githubusercontent.com/80850317/111520009-6f497180-8736-11eb-91fa-aa621f7cbb96.png)

![image](https://user-images.githubusercontent.com/80850317/111520129-9011c700-8736-11eb-95c0-1fd210544fa7.png)

Segue os logs.
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/6158874/totvsls_out.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/6158876/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/6158877/totvsls_in.log)

Obrigado.

**Comment by lwtnb-wrk** [comment]
@LeonardoPFranca Verifique suas configurações de Includes
https://github.com/totvs/tds-vscode/blob/master/docs/compilation.md#configura%C3%A7%C3%A3o-de-include-busca-de-arquivos-de-defini%C3%A7%C3%A3o
Aparentemente não apontam para onde os includes devem estar.

**Comment by LeonardoPFranca** [comment]
Excluí o server e adicionei novamente com as configurações do include, e agora funcionou. Obrigado.
