### ISSUE TITLE
Erro na compilação do fonte RTMSR35

### ISSUE THREAD

**Issue by Jafreal** [totvs/tds-vscode#658]
Estou com problemas para compilar o fonte RTMSR35.prw ao tentar compilar ocorre o erro {
"resource": "/c:/Sistemas/CBAA_NEW/src/Cte/rtmsr35.prw",
"owner": "AdvPL",
"severity": 8,
"message": "Duplicated function U_RTMSR35 (found in RTMSR35 (1).PRW)",
"source": "compile",
"startLineNumber": 1,
"startColumn": 1,
"endLineNumber": 2,
"endColumn": 1
} Que é referente a primeira linha do programa #INCLUDE "PROTHEUS.CH"
Já peguei o fonte disponivel no site da Totvs, mas o erro persiste. Caso eu tire essa linha q o erro aponta e recompilo ele da erro {
"resource": "/c:/Sistemas/CBAA_NEW/src/Cte/rtmsr35.prw",
"owner": "AdvPL",
"severity": 8,
"message": "Syntax Error",
"source": "compile",
"startLineNumber": 1474,
"startColumn": 1,
"endLineNumber": 1475,
"endColumn": 1
} Nessa linha esta  a contem a instrução abaixo.
Default nCnt := 1
Esse tipo de erro só ocorre nesse programa.

**Comment by lwtnb-wrk** [comment]
@Jafreal Veja a solução em https://github.com/totvs/tds-vscode/blob/dev/TROUBLESHOOTING.md#duplicated-function
