### ISSUE TITLE
Projeto compilando com User Function Duplicada

### ISSUE THREAD

**Issue by bardez** [totvs/tds-vscode#659]
**Describe the bug**
Na compilação de Folder/workspace está permitindo compilar duas User Functions com mesmo nome, porém em fontes (PRW) diferentes, prevalecendo por ordem de execução, a última que foi compilada.

Nenhum erro é mostrado.

**To Reproduce**
1. Ter a "mesma" User Function em fontes diferentes

**Expected behavior**
Mostrar erro de user Function Duplicada

**Desktop (please complete the following information):**
 - Windows 10 64Bits

**Appserver (please complete the following information):**
 - Build 7.00.191205P-20210315 - 64 bits
 - Windows 10 64Bits
 - Appserver version: 19.3.1.6_rc5_DTAPPSRV-4331

**Comment by lwtnb-wrk** [comment]
@bardez Fiz um teste aqui e o segundo fonte com a função duplicada deu erro no console como era esperado.
[Error - 10:24:27 AM] [FATAL] Aborting: Duplicated function U_TST1 (found in TST1.PRW) 
Veja no Output se essa mensagem [FATAL] não está ocorrendo durante a compilação.
Se não localizar a mensagem, veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e no mande os logs para analise.

**Comment by bardez** [comment]
@lwtnb-wrk  Isso realmente acontece se eu compilar em fontes com nomes diferentes. O problema é com o mesmo nome de prw em pastas diferentes, como mostrado abaixo.

![image](https://user-images.githubusercontent.com/12939672/111998234-97e8b700-8afa-11eb-82ee-4f4ee11b8150.png)

**Comment by danielbolognani** [comment]
Bom dia @bardez 
Isso é uma característica, se vc tem dois fontes com mesmo nome, um sobrescreve o outro, independente do conteúdo do arquivo.
Esse tipo de controle (dois fontes com mesmo nome em pastas diferentes), deve ser por conta do próprio usuário.
At.

**Comment by bardez** [comment]
@danielbolognani é possível indicar isso em um Warning para os usuários?

**Comment by danielbolognani** [comment]
Não acredito que isso deve virar um warning. Esse comportamento é o esperado principalmente porque é a forma como o mesmo fonte é recompilado no RPO.
Se acredita que isso possa ser útil, fique a vontade para alterar os fontes da extensão e enviar um Pull Request que analisaremos (de preferência com opção de ligar/desligar).

**Comment by bardez** [comment]
Sabe me informar como é organizada a ordem de execução de pastas, se é por ordem alfabética?
