### ISSUE TITLE
tds-vscode MacOS

### ISSUE THREAD

**Issue by rcarloslima** [totvs/tds-vscode#66]
Boa noite,

Utilizo a extensão no Windows sem problema, fui configurar a versão 0.2.1 no MacOS e tive a seguinte mensagem de erro:

[Error - 11:52:08 PM] Starting client failed
Error: Unsupported server configuration {
    "args": [
        "--language-server"
    ],
    "options": {
        "env": {
            "PATH": "/Users/rcarloslima/.pyenv/plugins/pyenv-virtualenv/shims:/Users/rcarloslima/.pyenv/shims:/Users/rcarloslima/.pyenv/bin:/Users/rcarloslima/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin",
            "HOME": "/Users/rcarloslima",
            "USER": "rcarloslima"
        }
    }
}
	at createMessageTransports._getServerWorkingDir.then.serverWorkingDir (/Users/rcarloslima/.vscode/extensions/totvs.tds-vscode-0.2.1/node_modules/vscode-languageclient/lib/main.js:356:35)

A extensão do KillerAll funciona sem problema, como posso corrigir esse problema?

**Comment by lwtnb-wrk** [comment]
@rcarloslima Primeiramente grato pelo interesse em utilzar o tsd-vscode. Ainda nao liberamos a versao para o MacOS mas devemos faze-lo em breve. Estamos estabilizando o produto inicialmente para Windows e Linux, mas em breve teremos a versão para MacOS. Como pode perceber a interface do cliente (VSCode) sera a mesma, porem ainda falta o Language Server (e Debug Adapter) na versão MacOS. Assim que liberarmos esses componentes essenciais para o funcionamento. Peço um pouco de paciencia e ficaremos felizes em saber se o produto atende os desenvolvedores que utilizam o MacOS tambem. Grato

**Comment by rodrigopg** [comment]
Caro @lwtnb-wrk, tudo bem?

Primeiramente parabéns ao time pelo trabalho!
Configurei em uma VM do Windows e está ficando muito bom o plugin!

Já tem alguma previsão para liberar para o MacOS?

Podemos auxiliar de alguma forma?

Obrigado!

**Comment by lwtnb-wrk** [comment]
@rodrigopg Estamos trabalhando com uma previsão de liberar a versão para MacOS entre o final deste mes de Julho e o começo de Agosto. São questões da compilação do Language Server (LS) e estão sendo realizada internamente. 
Certamente vamos precisar de auxilio para testar nos ambientes MacOS assim que tivermos o LS compilado para o MacOS!!!

**Comment by marcosnqsdev** [comment]
> @rodrigopg Estamos trabalhando com uma previsão de liberar a versão para MacOS entre o final deste mes de Julho e o começo de Agosto. São questões da compilação do Language Server (LS) e estão sendo realizada internamente.
> Certamente vamos precisar de auxilio para testar nos ambientes MacOS assim que tivermos o LS compilado para o MacOS!!!

Também estou aguardando (ansiosamente) liberar a versão para MacOS.

**Comment by EvaldoBatista** [comment]
@rodrigopg, Também estou aguardando a liberação para macOS, desde já agradeço se puder nos avisar quando estiver liberado para testes. já uso para Windows e para Linux (Ubuntu) e está muito bom.

**Comment by charlesreitz** [comment]
+1

**Comment by DanielYampolschi** [comment]
Versão para Mac disponível com a última liberação de 30/08/2019 versão 0.3.13

**Comment by toniguede** [comment]
@DanielYampolschi atualizei agora para a versão 0.3.13 e ainda aparecem as mensagens "There is no data provider registered that can provide view data." na aba de configuração de servidores e "command 'totvs-developer-studio.add' not found" se clico em + para adicionar um server.

Será que estou fazendo algo errado?

Vs Code version Update 1.37.1
MacOS Mojave 10.14.6 (18G95)

**Comment by DanielYampolschi** [comment]
Ola @toniguede , testei aqui e não tive esse problema, tudo ocorreu normalmente, a versão do VsCode que utilizei é a mesma que a sua, a única diferença é que meu Mac é um HighSierra, mas não acho que seja isso.
Enfim, para que esse erro que você informa ocorra, a visão de servidores teve algum problema para ser carregada e esse comando não foi registrado. E isso deve ocorrer por algum problema na instalação e não do plugin em si... 
Se for possível, sugiro que você desinstale seu VsCode e instale-o novamente.
Se isso for um problema para você por ja ter o ambiente configurado, desinstale o plugin do tds-vscode, vá na área onde o VsCode armazena as extensões (No Mac não sei de cabeça, você terá que pesquisar) e apague quaisquer pasta com versões antigas do plugin tds-vscode. Após fazer pode instalar novamente a versão 0.3.13

**Comment by rodrigopg** [comment]
Estou usando na versão beta do macOS Catalina, e está funcionando perfeitamente.

As extensões no Mac ficam salvas em ~/.vscode/extensions/

**Comment by toniguede** [comment]
Reinstalei aqui e tudo funcionou perfeitamente!
Obrigado!

**Comment by emersonmuniz** [comment]
> Reinstalei aqui e tudo funcionou perfeitamente!
> Obrigado!

Uso a mesma versão do macOS 10.14.6.

Apaguei o VSCode e apaguei as extenções em ~/.vscode/extensions, instalei novamente o VSCode e instalei a extenção novamente e continuo com o erro "command 'totvs-developer-studio.add' not found"

Algum componente a mais devo instalar e não notei ?

Grato...
