### ISSUE TITLE
TOTVS > VSCode

### ISSUE THREAD

**Issue by heybrunomaia** [totvs/tds-vscode#660]
Bom dia,

Estou tentando compilar e aplicar um fonte e sou advertido com a mensagem abaixo. Criei uma nova conexão de Servidores (no VSCode) e ainda sem êxito.
Estou utilizando a versão 1.54.3 do VSCode e os binários estão atualizados. Utilizamos a versão 12.1.25 do Protheus.

Mensagem:

Starting the compilation of the source: e:\Totvs\Protheus\Producao\Protheus\my projects\PE\ACDI011.PRW
Compilation started at Tue Mar 23 2021 09:25:57 GMT-0300 (Horário Padrão de Brasília)
Para utilizar SSL na conexao ou binario superior ao 170117A, utilize o alpha compile. Maiores info. em: https://github.com/totvs/advpl-vscode/wiki/Suporte-ao-bin%C3%A1rio-191205P
Compilation aborted, check the log or the Problems tab!
Compilation finished at Tue Mar 23 2021 09:25:57 GMT-0300 (Horário Padrão de Brasília) Elapsed (0.874 secs.)
1 processed files (see log output).

Desde já muito obrigado.
Atenciosamente,
Bruno Maia

**Comment by lwtnb-wrk** [comment]
@heybrunomaia Essa mensagem de erro está sendo emitida por outra extensão. Abra um chamado com eles ou desinstale-o e utilize a extensão oficial tds-vscode.
