### ISSUE TITLE
Erro de compilação/exclusão do rpo

### ISSUE THREAD

**Issue by rbncosta** [totvs/tds-vscode#661]
Boa tarde!

Ao tentar compilar um determinado  fonte ocorre a mensagem de erro abaixo:

{
	"resource": "/c:/Users/robson.costa/git/Fontes Mobly/TKM_COM_DIC/TKM/RDMAKES/WebXFun.PRW",
	"owner": "AdvPL",
	"severity": 8,
	"message": "Cannot overwrite TOTVS programs (WEBXFUN.PRW)",
	"source": "compile",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 2,
	"endColumn": 1
}

Para esse tipo de erro, a recomendação da TOTVS é excluir o fonte do RPO e compilar novamente, mas ao fazer isso, ocorre a mensagem abaixo:

[Error - 15:32:13] One or more programs could not be deleted from RPO.

Utilizo Windows 10, outros fontes consigo compilar normalmente.

Podem me ajudar pf?

Obrigado.

**Comment by lwtnb-wrk** [comment]
@rbncosta O programa (WEBXFUN.PRW) que está tentando sobrescrever/apagar é um programa TOTVS e portanto não deve ser alterado.
O tds-vscode está funcionando como deveria nesta situação.
Procure ajuda em relação a programaçao AdvPL.

**Comment by rbncosta** [comment]
O conflito de fato era o nome do pragrama.

Obrigado @lwtnb-wrk 

Abraço
