### ISSUE TITLE
Apply Patch ocasiona erro DBGCpyFile error

### ISSUE THREAD

**Issue by JhonatanLuizMorfim** [totvs/tds-vscode#662]
**Describe the bug**
Ao tentar aplicar Patch por via da extensão no VS Code, o erro DBGCpyFile error aparece. Foi testado aplicando o patch 10827288_dlogwmsmsp-11876_12.1.27_tttp120_lg  e com o patch P12_SetupRobo_por_lobo_guara

**To Reproduce**
1. Vá na extensão aplicar patch selecionar o patch desejado.
2. Clique em Aply

**Expected behavior**
A aplicação do patch ser executada e o êxito no terminal do app server

**Screenshots**
App Server
![image](https://user-images.githubusercontent.com/81650410/113049217-c0675580-9179-11eb-8cbc-294ef5a1c0c7.png)
Ao selecionar Patch Info
![image](https://user-images.githubusercontent.com/81650410/113049639-41265180-917a-11eb-90cc-92ac5d533f66.png)

**Desktop (please complete the following information):**
 - OS/Architecture: Windows 10 64 bit

**Appserver (please complete the following information):**
 - Build (with date):  Build 7.00.191205P - Feb 20 2020 - 17:32:02
 - OS/Architecture: Windows 10 64 bit
 - Build Version 19.3.0.2

**Comment by ricardomansano** [comment]
Boa tarde,
Dado tempo sem resposta acredito que o testes tenha sido feito com sucesso
Estou encerrando a issue
Continuamos a disposição
