### ISSUE TITLE
Erro no apply patch TSS via VS Code

### ISSUE THREAD

**Issue by marcossaabo** [totvs/tds-vscode#666]
Descreva o bug

Ao tentar aplicar um patch diretamente no TSS, apresenta os erros em anexo e não consigo aplicar. 

Reproduzir
Passos para reproduzir o comportamento:

 1 Vá na extensão do TDS aplicar patch selecionar o patch desejado.
  2 Clique em Apply.

Comportamento esperado
Aplicar o patch com sucesso no TSS.

Capturas de tela

Segue os erros abaixo e como o ambiemte apresenta-se conectado, nosso TSS não tem login e senha ao colocar o nome do servidor,ambiente e o include ele fica com o status verde. 

![image](https://user-images.githubusercontent.com/31674300/114386760-081db200-9b68-11eb-9e19-56ab0fb3f66b.png)

![image](https://user-images.githubusercontent.com/31674300/114386854-24215380-9b68-11eb-83fe-bcd2531085cd.png)

![image](https://user-images.githubusercontent.com/31674300/114388597-487e2f80-9b6a-11eb-9457-1331f4a37f92.png)

![image](https://user-images.githubusercontent.com/31674300/114388659-5df35980-9b6a-11eb-864f-f9f4e69bd794.png)

Desktop (preencha as seguintes informações):

  OS/Architecture: Windows 10 64 bit 

Appserver (preencha as seguintes informações):

    Versão (com data): Versão 7.00.19205P-2020-11-12  11 de Dezembro de 2020.
  OS/Architecture: Windows 10 64 bit 
    Versão da compilação [por exemplo, 19.3.1.1

**Comment by lwtnb-wrk** [comment]
@marcossaabo O erro apresentado mostra que o environment P12TST_SPED não foi encontrado no appserver.ini
Verifique qual é o nome correto do environment e tente se conectar novamente.
Lembrando que o usuario/senha deve ser o utilizado pelo Smartclient padrão. Não utilize o usuario/senha do SPED...

**Comment by marcossaabo** [comment]
@lwtnb-wrk  Grato pelas informações e orientações validei o appserver.ini e realmente estava somente SPED e não P12TST_SPED que é o nome do serviço do SPED.
