### ISSUE TITLE
Recurso para Cobertura de Código

### ISSUE THREAD

**Issue by cicerocruz** [totvs/tds-vscode#667]
Seria possível implementar o teste de cobertura de código no tds-vscode?

Referência: https://medium.com/liferay-engineering-brazil/um-pouco-sobre-cobertura-de-c%C3%B3digo-e-cobertura-de-testes-4fd062e91007

**Comment by ricardomansano** [comment]
Boa tarde Cicero,
Não temos esta intensão, a TOTVS tem os motores de teste para uso interno,
que não é parte do VsCode, porém para clientes não haverá este produto.
