### ISSUE TITLE
Compilação de WS no VSCode

### ISSUE THREAD

**Issue by AleSeth** [totvs/tds-vscode#668]
Ao tentar compilar um WS, estou tendo a mensagem: "**functions are not allowed in code. Use USER FUNCTION or STATIC FUNCTION.**"

Esse mesmo fonte já foi usado no passado no IDE e TDS, só no VSCode que não consigo compilar ele.

Há alguma configuração diferente à se fazer no VSCode para compilar WS?

**Comment by lwtnb-wrk** [comment]
@AleSeth Essa mensagem está sendo gerada pelo AppServer. Esse fonte em questão foi compilado no mesmo AppServer pelo IDE e TDS? A principio um usuario sem chave de compilacao somente pode compilar USER FUNCTION e STATIC FUNCTION mesmo.
Se for o caso veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by AleSeth** [comment]
@lwtnb-wrk Não, IDE e TDS foram usados em versões antigas, antes da .25
Esse processo do VSCode, estamos fazendo na .27, um RPO Limpo e ambiente instalado do zero.

Como gero a chave de compilação??
não tenho essa parte configurada no meu VSCode

**Comment by AleSeth** [comment]
@lwtnb-wrk  Segue Logs

[totvsls_in.log](https://github.com/totvs/tds-vscode/files/6312320/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/6312322/totvsls_out.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/6312323/totvsls.log)

**Comment by AleSeth** [comment]
Conseguimos resolver!
o problema estava entre os nomes do WsRestful e WSMethod.

Obrigado pelo apoio.

**Comment by lwtnb-wrk** [comment]
@AleSeth Excelente!
Se possível detalhe um pouco mais o problema e a solução, caso outros devs encontrem o mesmo problema que você teve e já saberá como resolver.

**Comment by AleSeth** [comment]
@lwtnb-wrk Blz!

Como exemplo, segue o cabeçalho que causava o problema:

`WsRestful **XXXXX** Description "WebService REST"

WsMethod POST Description "Sincronização de dados via POST" WsSyntax "/POST/{method}"  PRODUCES APPLICATION_JSON

End WsRestful  

WSMETHOD POST WSRECEIVE WSSERVICE **XXXXX**`

O problema era por causa do nome usado no WsRestful e no WSMETHOD POST WSRECEIVE (como no exemplo: "**XXXXX**"), corrigimos deixando igual o nome  e não usando um nome muito extenso.

Dessa maneira compilou sem o erro mencionado.
