### ISSUE TITLE
Erro VSCODE ao tentar subir fontes para o GITlab

### ISSUE THREAD

**Issue by marsellomoraes** [totvs/tds-vscode#669]
Ao tentar subir os fontes do VSCODE para o GITlab aparece a mensagem:

unable to access 'https://gitlab.com/ciee/Homologacao.git/': SSL certificate problem: unable to get local issuer certificate

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS/Architecture: [e.g. Windows 64 bits]

**Appserver (please complete the following information):**
 - Build (with date): [e.g. Build 7.00.170117A - Jun 28 2019 - 11:16:56]
 - OS/Architecture: [e.g. Linux 64 bits Ubuntu]
 - Build Version [e.g. 17.3.0.13]

**Additional context**

**Comment by danielbolognani** [comment]
Boa tade @marsellomoraes , tudo bem?
Aqui apenas damos suporte a extensão do VSCode "Totvs Developer Studio". 
Problemas com o VSCode em si, ferramentas externas (Git ou qualquer outra extensão) ou extensões de terceiros, não temos como ajudar.
At.

**Comment by brodao** [comment]
@marsellomoraes ,

O GITLab é de terceiros. Favor entrar em contato com o mantenedor do GITLab ou os responsáveis pelo repositório.

A disposição.
