### ISSUE TITLE
Mensagem indefinida ao tentar conectar em um ambiente inexistente

### ISSUE THREAD

**Issue by likid** [totvs/tds-vscode#67]
Quando é feito a tentativa de conexão no servidor e é informado um nome de ambiente inexistente, o vscode informa um erro genérico, onde parece não haver tratamento para o retorno informado.

![Code_2019-06-04_13-28-59](https://user-images.githubusercontent.com/10984007/58896763-0c0b5e00-86cd-11e9-838e-0edbee416e54.png)

**Comment by lwtnb-wrk** [comment]
@likid Não existe um tratamento especifico para ambiente inexistente. Apenas detectamos que existe um problema durante a autenticacao do usuario. O erro generico (Server returned a non numerica value) é exatamente o que o erro diz: O servidor retornou um valor nao numerico, mas o sever nao diz se o problema esta no environment, user ou password. Entao nao temos como informar nada diferente disso.

**Comment by likid** [comment]
Quando a senha está errada o vscode informa que houve erro de usuário e/ou senha, então já existe tratamento para isto, não seria só fazer o mesmo tratamento para os ambientes? Como não tenho acesso ao DAP, não consigo ter muitas idéias para vocês.

**Comment by likid** [comment]
Bom, fiz um teste agora no TDS em Java e nesta mesma situação ele só informa que as informações para a conexão são inválidas. O ideal era fazer igual o TDS em Java que ao fazer a primeira conexão com o server já carregar todos os ambientes, mas acho que já criaram uma issue para isso.

**Comment by lwtnb-wrk** [comment]
@likid Em relação a lista de ambiente, tanto o TDS quando o vscode não vão carregar a lista de ambientes mais. Essa foi uma questão levantada pelo time de segurança e então exigimos que o usuário informe o ambiente que ele vai se conectar pela 1a vez. Depois deixamos essa informação armazenada, pois entendemos que o usuario que conhece o ambiente deve ter acesso nas proximas conexoes. 
Gratos pelos testes e se tiver outras ideia fique a vontade para criar outra Issue.
