### ISSUE TITLE
Não consigo mais conectar no server via vscode

### ISSUE THREAD

**Issue by charllesrox** [totvs/tds-vscode#670]
Bom dia, está apresentando o erro abaixo ao tentar conectar. Já loguei com o usuário no protheus normalmente, já reiniciei os serviços, etc. Não faz login via vscode.
----

[Error - 11:11:49] Reconnection failed. Could not reconnect to server (TVD-PRD-COMPILA).
[Info  - 11:12:27] Starting connection to the server 'TVD-PRD-COMPILA' (10.0.0.228@4290)
[Info  - 11:12:30] Connection to the server 'TVD-PRD-COMPILA' finished.
[Info  - 11:12:33] Starting user 'charlles' authentication.
[Info  - 11:12:33] Secure authenticating...
[Error - 11:12:35] Authentication error: Server returned a non numeric value.
[Error - 11:12:35] Authentication failed. Could not authenticate to server.

#Server_returned_a_non_numeric_value.

**Comment by lwtnb-wrk** [comment]
@charllesrox Algo foi atualizado em seu ambiente? Binário do AppServer, Lib ou qualquer outra coisa?
Você está se conectando com o Smartclient padrão? Ou é um ambiente SPED?
Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by charllesrox** [comment]
Teve atualização apenas de pacotes acumulados de módulo e dicionário de dados, não teve atualização de bin/lib/smartclient.

**Comment by lwtnb-wrk** [comment]
@charllesrox Mas você está conseguindo se logar com o Smartclient padrão nesse ambiente? Aparentemente algo no RPO está com problema, pois ao tentar se conectar o AppServer está retornando um valor invalido para o tds-vscode, mas o estranho é que o Smartclient e tds-vscode deveriam utilizar os mesmos mecanismo para se logar no Protheus.
Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by ricardomansano** [comment]
Dado prazo sem resposta creio que o problema tenha sido resolvido
