### ISSUE TITLE
Erro importação arquivo TOTVS Replay

### ISSUE THREAD

**Issue by gustavo-krug** [totvs/tds-vscode#672]
TOTVS Replay enviado pelo cliente possui 31Mb, mas ao importar ele indica quase 500Mb
Além disso, o arquivo não importa e não executa.
Ele vai até uns 100Mb e simplesmente termina, inviabilizando o processo.
Consigo importar outros arquivos trplay, peguei esta situação somente com este arquivo.
Ele simplesmente indica finalizado e não inicia o debug.

Detalhes estão no vídeo abaixo:

https://user-images.githubusercontent.com/45034725/116283666-841c1a80-a762-11eb-87bf-bd65294a53b1.mp4

TOTVS Replay utilizado no teste: https://drive.google.com/file/d/1tDUV0FmqlayZzdU694a23Fh0k10gs98M/view?usp=sharinghttps://drive.google.com/file/d/1tDUV0FmqlayZzdU694a23Fh0k10gs98M/view?usp=sharingv 

Inspetor de objetos do cliente, o qual gravou o TOTVS Replay
[inspetor12042021.zip](https://github.com/totvs/tds-vscode/files/6386379/inspetor12042021.zip)

Extensão TOTVS Developer Studio for VSCode está na versão v1.2.1

**Comment by DanielYampolschi** [comment]
Olá @gustavo-krug . Desculpe a demora para responder. Quando você enviou essa mensagem estava no meio de uma outra issue, enfim... Eu testei o arquivo que você enviou e consegui reproduzir o problema. Ele já foi identificado e corrigido. Por favor instale a atualização do seu plug-in pelo VSIX no link abaixo e me diga se tudo ocorre bem agora:

https://drive.google.com/file/d/1rejmVbjhu-JamCE9gcXCB33ghI0zPyEl/view?usp=sharing

**Comment by gustavo-krug** [comment]
Instalei o VSIX e o problema foi corrigido

**Comment by DanielYampolschi** [comment]
Muito obrigado @gustavo-krug
