### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by Jeff-Rubens** [totvs/tds-vscode#673]
VsCode não consegue abrir o sigaadv através do Start Debugging (F5) ou Run Without Debuggin (Ctrl + F5).
A barra permanece indicando o carregamento, porém, nada acontece.

**Comment by lwtnb-wrk** [comment]
@Jeff-Rubens Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.
Como se trata de Debug envie tambem o dap.log.

**Comment by ricardomansano** [comment]
Dado tempo sem retorno, encerramos a issue
