### ISSUE TITLE
No  realiza la aplicación de Patch.

### ISSUE THREAD

**Issue by LuisMata119** [totvs/tds-vscode#674]
Se esta intentando realizar la aplicación de un patch de solución, sin embargo, no me permite hacerlo arrojando el siguiente mensaje de error:

<img width="511" alt="Captura" src="https://user-images.githubusercontent.com/83595877/116891282-21a89b80-abf4-11eb-8409-b7080d4ec1e0.PNG">

![image](https://user-images.githubusercontent.com/83595877/116891175-0473cd00-abf4-11eb-9b25-4e9c1a33b52d.png)

**Comment by lwtnb-wrk** [comment]
@LuisMata119 Qual a versão do AppServer que está utilizando? Sabemos que existe um problema do AppServer 19.3.0.5 e anteriores que causava esse tipo de erro. Se estiver com essas versões antigas você precisará atualizar seu AppServer para um mais atual 19.3.0.6 ou superior.
Se não for o caso veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os log para analise.

**Comment by ricardomansano** [comment]
Dado tempo sem retorno, encerramos a issue
