### ISSUE TITLE
Compilação incompleta pulando etapas

### ISSUE THREAD

**Issue by AndreDryko** [totvs/tds-vscode#676]
Bom dia, toda vez que tentamos compilar um projeto ADVPL inteiro no VSCode ele não compila tudo, todos os serviços fechados, tudo certo para compilar e ainda sim não compila.
Exemplo: temos 5 programas TOTVS para ser compiliado no mesmo projeto, ele começa a compilar o 1, 2, pula os 3 e 4 e vai para o 5, ai depois temos que ir e compilar os 3 e 4 separadamente, ou seja, ele não compila todos os 5 que estão dentro do mesmo projeto, alguém já teve algum problema assim? Lembrando que ele não apresenta erro apenas pula algumas etapas.

Desde já agradeço

**Comment by lwtnb-wrk** [comment]
@AndreDryko Poderia detalhar melhor como você está fazendo para compilar seu projeto? Que opção está utilizando no tds-vscode?
De qualquer forma, veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analises.

**Comment by ricardomansano** [comment]
Dado tempo sem retorno, encerramos a issue
