### ISSUE TITLE
Acesso ao Dicionário de Dados via VSCode

### ISSUE THREAD

**Issue by jalberto2004** [totvs/tds-vscode#677]
No TDS tínhamos a visão do Dicionário de Dados ( https://tdn.totvs.com/pages/viewpage.action?pageId=110430172 ).

O VSCode não terá funcionalidade ?

**Comment by ricardomansano** [comment]
Boa tarde @jalberto2004 ,

Com o dicionário em banco esta feature fica inviável via VSCode, então nao iremos implantá-la, pfv use os ferramentas de LIB/Frame para acessar o banco de dados e os dicionarios

At
Mansano
