### ISSUE TITLE
Bug na falha de conexão com um servidor

### ISSUE THREAD

**Issue by efdeiasoliveira** [totvs/tds-vscode#678]
**Describe the bug**
Quando tentamos conectar com um servidor, e o mesmo esta inacessível a legenda do servidor fica verde como se estivesse conectada, porém não foi possível realizar a conexão.

**To Reproduce**
1. Pare o serviço de um servidor pré configurado
2. Selecione a opção conectar no servidor no VsCode
3. O VsCode irá exibir a notificação An error ocurred while connection.
4. A legenda do servidor irá ficar verde indevidamente como se estivesse conectado.

**Expected behavior**
O esperado é que a legenda mostrasse que não estava conectado ou que ficasse vermelha para identificar que não foi possível conectar.

**Screenshots**
![image](https://user-images.githubusercontent.com/51671824/117588038-5be3d280-b0f7-11eb-9c88-e6a03716c09a.png)

**Desktop:**
 - OS/Architecture: [Windows 64 bits]

**Comment by danielbolognani** [comment]
Boa tarde, disponibilizamos uma correção em pré-release:
https://github.com/totvs/tds-vscode/releases/tag/v1.3.3
Nossa previsão é subir oficialmente no MarketPlace semana que vem.

**Comment by danielbolognani** [comment]
Versão 1.3.3. liberada no MarketPlace
