### ISSUE TITLE
Sintax Error DEFINE MSDIALOG

### ISSUE THREAD

**Issue by h2danilo** [totvs/tds-vscode#679]
**Describe the bug**
Quando tento compilar (ctrl+f9), um fonte antigo, ocorre erro: "Syntax Error Compile" na linha abaixo:
DEFINE MSDIALOG oDlg TITLE "Posição Contrato" FROM 0, 0 TO 310, 600 Pixel

Fato que fonte sempre funcionou e agora começou a ocorrer o erro.

**Screenshots**
![image](https://user-images.githubusercontent.com/38380833/117723980-7bdbca80-b1b9-11eb-993b-ca9e4b22d7d6.png)

**Desktop:**
 - OS/Architecture: Windows 64 bits

**VS Code About:**
Version: 1.55.0 (system setup)
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T16:01:55.261Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 6.3.9600

**TOTVS Developer Studio for VSCode:** v1.0.6

**Dados do Server **

Versão: TOTVS Manufatura
Build AppServer: 7.00.170117A-20200331 - 64 bits
Appserver version: 17.3.0.20
Build DBAccess: 20191119-20200217
Release do RPO:  12.1.023
Release do dicionário: 12.1.023
Local files: CTREE
License server: 2014 - 1.03.016
DB DataBase: MSSQL
DB API Build: 20181212-20190724

Versão da Lib:20200214
Data da Lib: 20200401_161621

**Comment by h2danilo** [comment]
[tdsSupport.zip](https://github.com/totvs/tds-vscode/files/6454944/tdsSupport.zip)

**Comment by brodao** [comment]
@h2danilo 

Favor atualizar o TDS-VSCode para a versão 1.2.1 (mais recente). Caso ainda persista o problema, atualize os arquivos de definição (.ch) a partir da área de *downloads* da TOTVS. Se ainda continuar coma ocorrência, favor entrar em contato com o suporte AdvPL ou Framework.

A disposição.

**Comment by h2danilo** [comment]
Problema foi sanado, atualizando  arquivos de definição (.ch) e versão TDS-VSCode! Obrigado
