### ISSUE TITLE
Erro ao abrir o SmartClient ao utilizar o Debug

### ISSUE THREAD

**Issue by sandroalves1971** [totvs/tds-vscode#680]
Prezados estou passando pelo mesmo problema do link abaixo:
https://github.com/totvs/tds-vscode/issues/186#issue-506603212

vejo que vocês passaram por esse problema.
Estou com VS Code atualizado 1.56.2
E a extensão do Totvs Developer Studio na versão 1.0.6

como resolverão?

**Comment by brodao** [comment]
Ola @sandroalves1971 

Favor atualizar o TDS_VSCode para a versão 1.2.1 Caso o problema persista, reabra este chamado informando a build do servidor e anexando os logs conforme https://github.com/totvs/tds-vscode#resolu%C3%A7%C3%A3o-de-problemas

A disposição,

**Comment by sandroalves1971** [comment]
Obrigado atualizado e passou a funcionar
