### ISSUE TITLE
Data do programa no Resultado de Compilação

### ISSUE THREAD

**Issue by efdeiasoliveira** [totvs/tds-vscode#681]
**Is your feature request related to a problem? Please describe.**
No VsCode não é possível ver as datas dos fontes e muitas das vezes que compilamos não temos certeza se o fonte esta atualizado e qual é a sua data. Também temos o costume de guardar o log ou enviar como sinalização de atualização para outros programadores.

**Describe the solution you'd like**
Ao compilarmos vários arquivos o plugin da Totvs gera um log Compilation Result, com o nome do arquivo, resultado, caminho  e etc. Gostaria que fosse adicionada a data do programa.

**Describe alternatives you've considered**
Atualmente a alternativa que estou tendo é visualizar a data através do Inspetor de Objetos.

**Additional context**
![image](https://user-images.githubusercontent.com/51671824/118377703-3d715180-b5a5-11eb-82b6-50199d99a063.png)

**Comment by ricardomansano** [comment]
Boa tarde @efdeiasoliveira ,

A data da compilação neste caso sera a data corrente, se precisa guardar esta informação pode coloca-la como parte no nome de seu arquivo de LOG e terá o controle que procura, não vejo motivo para que esta informação seja inserida neste ponto.

O inspetor de objetos, que ja esta usando, é a ferramenta ideal para este tipo de controle.

De qualquer forma nosso plugin é open-source, caso tenha real necessidade desta informação pode fazer um fork de nosso projeto e implementar essa melhoria em uma versão que poderá manter.

At
Mansano

**Comment by efdeiasoliveira** [comment]
@ricardomansano por favor dê uma outra avaliada nesta solicitação, não tem prioridade. A data do programa fonte (arquivo) não é a data da compilação, ou seja, a data que aparece no inspetor de objeto não é a data do fonte. Exemplo quando aplicamos um patch o sistema gera o log de repositório com as datas dos fontes e não a data da compilação.

Desde já agradeço sua atenção.
