### ISSUE TITLE
Ao debugar no Linux o smartclient não fecha automaticamente

### ISSUE THREAD

**Issue by delsonfilho** [totvs/tds-vscode#685]
Prezados, boa noite.

toda vez ao debugar as rotinas no vscode, ao encerrar o debug o smartclient fica ativo no Linux (Ubuntu 20.04), tendo que ir pelo monitor e dar o kill no processo do smartclient ou então quando da erro não fecha também.

**Comment by delsonfilho** [comment]
Bom dia!

Alguma previsão da correção?

**Comment by lwtnb-wrk** [comment]
@delsonfilho Isso esta ocorrendo com alguma versão em particular do smartclient? Qual a versão que está utilizando de smartclient e tambem qual a versão do appserver? Voce tem outras versoes para confirmar se isso esta ocorrendo com uma versão especifica?
Se possivel veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise. Em especial o DAP.log pois trata-se de debug.

**Comment by delsonfilho** [comment]
@lwtnb-wrk inclusive o @ricardomansano já reproduziu o mesmo erro, mas vou coletar essas infos.

**Comment by ricardomansano** [comment]
@lwtnb-wrk , aconteceu comigo com a 19 do Portal, usando Ubuntu 20.04
@delsonfilho qto mais info melhor, a hora que eu tiver um respiro vou tentar gerar os logs tbem

**Comment by danielbolognani** [comment]
Boa tarde, disponibilizamos uma correção em pré-release:
https://github.com/totvs/tds-vscode/releases/tag/v1.3.3
Nossa previsão é subir oficialmente no MarketPlace semana que vem.

**Comment by danielbolognani** [comment]
Versão 1.3.3 liberada no MarketPlace com a correção
