### ISSUE TITLE
VsCode não para no Debug nas Linhas Corretas dependendo da Quantidade de Includes

### ISSUE THREAD

**Issue by carloseniemeyer** [totvs/tds-vscode#687]
Estou tendo problemas para realizar o Debug no VsCode com o TDS.

Dependendo da quantidade de includes que colocamos no fonte, falha o Debug.

Já foi tentado fazer o downgrade da versão do VsCode e analisar em outros ambientes com binários e libs desatulizados, mas o problema persiste. 

Foi tentado também usar includes atualizados e desatualizados, mudar a ordem, incluir um Include dentro de outro. Ao usar menos includes o Debug posiciona corretamente.

Paramos Serviços, Desfragmentamos RPO, fizemos testes diretos chamando a rotina pelo VsCode e pelo Protheus e o problema persiste. Tudo isso usando SmartClient Local.

Segue dados do ambiente, do fonte, imagem do problema e logs do VsCode para nos ajudar a analisar essa questão.

**Dados do Server** 

Versão: TOTVS Varejo
Build AppServer: 7.00.191205P-20210114 - 64 bits
Nome do servidor: SRVRAOTVSTESTE2
Sistema operacional: Windows Server 2012 R2
Appserver version: 19.3.1.5
Build DBAccess: 20200606-20201110
Release do RPO:  12.1.025
Release do dicionário: 12.1.025
Local files: CTREE
License server: 2014 - 2.0.0
DB DataBase: ORACLE
DB API Build: 20200606-20201110

Ambiente: Teste_unitarizacao_desenv_viveo03
Objeto: CMAFATI2
Programa: CMAFATI2.PRW
Tipo: ADVPL
Build: BUILD_USER
Data: 26/05/2021 13:45:26
Dicionário no banco de dados: Não

**Dados do Remote** 

Remote build: 7.00.191205P-20210108
Remote version: 19.3.1.2
Remote type: 1 - QT-5.14.2 WIN
Módulo: COM
Nome do computador: DRAO1DES005015
Sistema operacional: Windows 10 - 
Memória: 16174
Processador: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz

Versão da Lib: 20210405
Data da Lib: 20210408_143338
Commit ID:4261175451db58da5f3c5625a9a79e082ab10b9c

**VSCODE**

Versão: 1.56.2 (user setup)
Confirmar: 054a9295330880ed74ceaedda236253b4f39a335
Data: 2021-05-12T17:13:13.157Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
SO: Windows_NT x64 10.0.19042

**TDS no VsCode**
Versão: 1.2.1

**Conteúdo do Fonte de Teste**
[COMA23Tst.zip](https://github.com/totvs/tds-vscode/files/6552959/COMA23Tst.zip)

**Imagem do Problema de Debug**
[ProblemaDeDebug.zip](https://github.com/totvs/tds-vscode/files/6552960/ProblemaDeDebug.zip)

**Logs VsCode**
[LogsVsCode.zip](https://github.com/totvs/tds-vscode/files/6553018/LogsVsCode.zip)

**Comment by carloseniemeyer** [comment]
Fonte PRW e PPO - Faltou no anexo.
[COMA23Tst.zip](https://github.com/totvs/tds-vscode/files/6553065/COMA23Tst.zip)

**Comment by carloseniemeyer** [comment]
**Arquivo Gerado do TDS Support**
[tdsSupport.zip](https://github.com/totvs/tds-vscode/files/6553081/tdsSupport.zip)

**Comment by brodao** [comment]
@carloseniemeyer 

Analisei os logs e fiz testes com os arquivos enviados e não reproduzi a ocorrência.
Solicito que envie o arquivo viveo.ch (pode mandar direto para acandido@totvs.com.br) para análise e mais testes.

Se possível, favor testar com o _appServer  version_ 19.3.1.6.

No aguardo.

**Comment by carloseniemeyer** [comment]
Enviado por E-mail o include viveo.ch.
Sobre o AppServer vou verificar no portal essa atualização e verificar aqui internamente a possibilidade de atualizar.

**Comment by carloseniemeyer** [comment]
Teria esse problema alguma relação com meu profile local?

Se fosse excluído as pastas:
.vscode
.totvsls

E reinstalar o VsCode e TDS. Seria uma possibilidade?

**Comment by brodao** [comment]
Não creio que seja problema no _profile_ local.

Verifiquei o arquivo CH enviado e não há nada demais. Refiz o teste usando esse arquivo e o processo ocorreu conforme esperado.

Esqueci de comentar que nos logs enviados não há indicação que o fonte foi compilado.
Favor forçar a compilação e testar novamente.

No aguardo.

**Comment by lwtnb-wrk** [comment]
@carloseniemeyer Conforme informado pelo @brodao confirme se realmente o fonte debugado está compilado corretamente no RPO. Veja pelo "Inspetor de Objetos" a data e horário de compilação, pois geralmente nestes casos de falta de sincronia entre linhas durante a depuração são ocasionados pelas diferença entre o fonte exibido no editor e o que está compilado no RPO.

**Comment by carloseniemeyer** [comment]
Um ponto importante é que se eu mantenho apenas um include (Exemplo: "TOTVS.CH" ou "VIVEO.CH", o Debug fica na linha correta.

**Comment by lwtnb-wrk** [comment]
@carloseniemeyer Também não reproduzi o problema aqui. Compilei o fonte COMA23Tst e adicionei um breakpoint na linha 19. Ao iniciar o debug ele parou corretamente nesta linha e tudo ocorreu conforme esperado. Utilizando os includes de 21-05-12-P12_INCLUDES e AppServer 19.3.1.6.
![lsda_tests-1622124359769](https://user-images.githubusercontent.com/49563478/119840820-b0e75d00-bedb-11eb-92ae-e7e93e591021.gif)

**Comment by lwtnb-wrk** [comment]
@carloseniemeyer Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie esses logs para analises tambem.

**Comment by carloseniemeyer** [comment]
Fiz a limpeza do meu profile local (**Exclui as pastas .totvsls e .vscode**) e reinstalei o VsCode e o TDS, sem instalar mais nenhuma outra extensão.

Mas mesmo assim o problema persiste aqui para mim.

Com relação a versão AppServer 19.3.1.6 está disponível para download no suporte TOTVS? Encontrei apenas a versão de Janeiro 19.3.1.5 (21-01-21-P12_APPSERVER_BUILD-19.3.1.5_WINDOWS_X64.ZIP).

Atualizei aqui entretanto a versão do remote para (Fiz o teste também com esse remote o problema persiste):
**Dados do Remote** 
Remote build: 7.00.191205P-20210513
Remote version: 19.3.1.4

Eu descartaria a versão do AppServer pelo fato do time aqui da VIVEO conseguir debugar normalmente na versão 19.3.1.5 e com essa versão mais atualizada do VsCode como no seu teste. Para que infelizmente o problema está somente comigo. 

Estarei gerando os arquivos de logs solicitados e envio na sequencia.

**Comment by carloseniemeyer** [comment]
**GIF do Debug com problema:**
![debug](https://user-images.githubusercontent.com/52763295/119863524-07f72d00-bef0-11eb-8ab4-6bb049a95452.gif)

**Comment by carloseniemeyer** [comment]
Fiz alguns procedimentos adicionais: Limpei o Temp da máquina, Executei ferramenta de limpeza do Windows, mas nada muda esse comportamento.

Notei que ao manter 2 includes apenas e o restante comentado, o fonte que tem 25 linhas, mostra no console.log do appserver que foi compilado um fonte com 23 linhas. Seria isso alguma possível pista do que ocorre?

**2021-05-27T13:36:34.609000-03:00 8928|COMA24TST.PRW:23**

**Comment by danielbolognani** [comment]
Carlos, tenta atualizar seus includes, pega os mais atuais no portal de
clientes e verifique se o comportamento continua o mesmo.

At.

Em qui., 27 de mai. de 2021 às 13:38, carloseniemeyer <
***@***.***> escreveu:

**Comment by carloseniemeyer** [comment]
Independe dos includes em específico.
Tentamos várias versões de includes aqui. Antigas e Novas (A mais nova testada foi 21-05-12-P12_INCLUDES).

Notei que ao compilar o fonte com um único include no cabeçalho ele compila o fonte com o tamanho de 23 linhas. 
Quando compilo o fonte com mais de um include o tamanho do fonte é reduzido. Exemplo: Ao colocar 3 includes é compilado com 21 linhas. Se coloco 5 includes ele compila com 9 linhas.

Com 3 Includes
**2021-05-27T14:40:47.584000-03:00 10496|COMA24TST.PRW:21**

Com 5 Includes
**2021-05-27T14:42:56.006000-03:00 10496|COMA24TST.PRW:9**

**Comment by carloseniemeyer** [comment]
Reinstalei o VsCode, Configuramos o Server e o Launch novamente do básico e mesmo assim o problema persiste.
O VsCode compila com menos linhas e no Debug falha.
Em outras máquinas, com a mesma do VsCode, TDS, Binário, Include, apontando para o mesmo ambiente não ocorre isso.
O Fonte é compilado corretamente com 23 linhas.

O que poderia provocar essa redução de linhas ao compilar?

**Comment by carloseniemeyer** [comment]
Parece que o problema pode estar relacionado com o que aconteceu nesse outro Issue:
**https://github.com/totvs/tds-vscode/issues/408**

**Comment by carloseniemeyer** [comment]
Testamos com WorkSpace e abrindo fonte direto na pasta.

**Comment by carloseniemeyer** [comment]
Vou tentar reinstalar o VsCode em Outra pasta no Arquivos de Programas, limpar o profile local novamente, reiniciar a máquina e refazer todo o processo do zero, configurando launch e servers manualmente.

**Comment by carloseniemeyer** [comment]
Antes da reinstalação tentei excluir todos os arquivos contidos nas pastas:
C:\Users\carlos.niemeyer\AppData\Roaming\Code
C:\Users\carlos.niemeyer\AppData\Roaming\@totvs

E Instalei o VsCode em outra pasta: C:\Users\carlos.niemeyer\AppData\Local\Programs\Microsoft VSCode

Feito todo o processo de instalação da extensão e configuração de launch, server com includes atualizados novamente após a reinstalação, porém o problema persiste.

**Comment by lwtnb-wrk** [comment]
@carloseniemeyer Testei aqui com todos os includes e sempre com o mesmo resultado.
Qual o SO que voce usa? O AppServer é local ou está em outra máquina? Se for outra máquina, que SO ela usa?
Você tem mais de uma pasta com o mesmo nome de arquivo que está debugando?

**Comment by lwtnb-wrk** [comment]
@carloseniemeyer Outra pasta que voce poderia tambem tentar remover (na verdade faça um backup ou apenas renomeie) seria o .totvsls que está na sua pasta de usuário.

**Comment by danielbolognani** [comment]
Consegue verificar se tem algum fonte que por acaso pode estar trocando os
caracteres de final de linha?
Para o advpl precisa ser CRLF (0x13 e 0x10), se estiver qualquer arquivo
envolvido (mesmo os chs) com o padrão Linux (apenas LF) pode ocorrer esse
tipo de problema.

Em qui., 27 de mai. de 2021 às 17:14, lwtnb-wrk ***@***.***>
escreveu:

**Comment by carloseniemeyer** [comment]
O SO é Windows 10 - SO: Windows_NT x64 10.0.19042 conforme logs acima.

O VsCode e smartClient utilizados estão locais, acessando o server remotamente via VPN.

O Arquivo não tem outras versões iguais em nenhuma outra pasta e não tem acentuação nas pastas. Foi feito um fonte somente de teste para evitar qualquer homônimo.

Arquivo do Fonte testado e outros estão com CRLF e padrão ANSI (confirmado pelo Notepad++) - Fonte foi enviado em anexo nos posts acima.

Como dito acima também já foi feito o teste de excluir essas pastas locais antes da reinstalação:
**.vscode
.totvsls**

E também essa:
**C:\Users\carlos.niemeyer\AppData\Roaming\Code
C:\Users\carlos.niemeyer\AppData\Roaming@totvs**

Mudei inclusive a pasta de instalação do VsCode para ver se mudava qualquer referência.

Como falei outros Devs conseguem compilar. O problema ocorre somente comigo e ainda sem solução.

Obrigado pelo apoio.

**Comment by lwtnb-wrk** [comment]
@carloseniemeyer Você chegou a remover as linhas de comentários (linhas 7 a 15)? Lembrei de uma ocorrência que acontecia especificamente com os comentários. Como já estamos sem muitas opções favor fazer este teste tambem.

**Comment by carloseniemeyer** [comment]
Pessoal,

Bom Dia!

O problema não está relacionado com os comentários. Já tínhamos tentado isso. Mas descobrimos o motivo do problema.

Fiz novos testes com e sem workspace, mudando a localização dos fontes a serem debugados.

Criei alguns Fontes chamados: TSTDEBUG, TST2DEBUG, TST3DEBUG e coloquei eles em pastas distintas na hierarquia de pastas, com e sem Workspace (O que geralmente uso com caminhos relativos, conforme enviado nos posts acima)

Esses fontes são exatamente iguais com 5 includes e comentários (Não usei nenhum INCLUDE Personalizado para não confundir).
[TSTDEBUG.zip](https://github.com/totvs/tds-vscode/files/6561532/TSTDEBUG.zip)

Ao fazer o Debug na Raiz o Debug funcionou normalmente.

Ao fazer o Debug em uma determinada estrutura de pastas começou a ter esse efeito colateral explicado nos posts acima, com e sem workspace (Abrindor por pastas). Não realizando o debug conforme o nº de includes.

**Portanto o problema tem a ver com a estrutura local de pastas.**

**Caminho de pasta onde o Debug Funciona:**
C:\MAFRA\Workspace\Workspace_MAFRA\GrupoMafra_Protheus\Fontes\Desenvolvimento\Projeto Unitarizacao\Empresa01\ADVPL\Modulos\COM\TSTDEBUG.PRW

**Caminho de pasta onde ocorre o Problema:**
C:\MAFRA\Workspace\Workspace_MAFRA\GrupoMafra_Protheus\Fontes\Desenvolvimento\Projeto Unitarizacao\Empresa01\ADVPL\Modulos\COM\Rotinas\TST2DEBUG.PRW

Analisem por favor se conseguem reproduzir o problema com vocês recriando a estrutura de pastas, usando o VsCode abrindo direto a pasta e com WorkSpace relativo/absoluto.

Acredito que possa ser uma limitação do VsCode ou do Plugin do TDS com relação a isso ou a uma limitação do Windows em possíveis passagens de parâmetros na comunicação entre o APPSERVER e o VsCode

**Comment by carloseniemeyer** [comment]
**Reproduzindo o Problema:**
![ReproducaoDoProblema](https://user-images.githubusercontent.com/52763295/120001490-39ccca00-bfaa-11eb-9a51-7e31498d6182.gif)

**Comment by lwtnb-wrk** [comment]
@carloseniemeyer Quando você diz workspace, está se referindo a configuração .code-workspace? Explicado em https://code.visualstudio.com/docs/editor/workspaces
Eu teste abrindo a pasta diretamente e usando em um workspace e nada mudou. Continuo compilando e debugando conforme esperado sem reproduzir a sua ocorrência.

**Comment by carloseniemeyer** [comment]
@lwtnb-wrk Sim estou me referindo a configuração .code-workspace como mandei em anexo nos posts acima.

Entretanto, mesmo não usando o conceito de Workspaces e sim abrindo a pasta diretamente ocorre o cenário.

Fiz o teste novamente em outra máquina (mesma versão do VsCode, TDS, AppServer e Windows 10), recriando a estrutura de diretórios que citei acima e consegui reproduzir o mesmo problema.

A minha sugestão aqui é que vcs recriem o mesmo cenário, criando a mesma estrutura de pastas para avaliar o problema.

Exemplo:
**C:\MAFRA\Workspace\Workspace_MAFRA\GrupoMafra_Protheus\Fontes\Desenvolvimento\Projeto Unitarizacao\Empresa01\ADVPL\Modulos\COM\Rotinas**

Nesse caso, abri no VsCode a pasta a partir da pasta "**GrupoMafra_Protheus**" e consegui reproduzir o mesmo problema.

E coloque a rotina TSTDEBUG.prw para realizar o Debug com 3 includes apenas, comentando as demais.

Agora que sei que o problema está relacionado a estrutura de pastas vamos evitar aqui e reorganizar o nosso processo interno.

Porém fica a dica para quem tiver problemas de Debug.

Se possível, avaliem se existe algo que possa ser feito no VsCode/TDS para avisar dessa limitação se conseguirem reproduzir. O ponto é que tem a ver com a hierarquia de pastas e não se usa ou não o conceito de WS do VsCode.

Obrigado pelo apoio até então.

**Comment by lwtnb-wrk** [comment]
@carloseniemeyer Se puder realize um teste tambem, reduza os nomes e quantidade de sub pastas por exemplo
ao inves de: C:\MAFRA\Workspace\Workspace_MAFRA\GrupoMafra_Protheus\Fontes\Desenvolvimento\Projeto Unitarizacao\Empresa01\ADVPL\Modulos\COM\Rotinas
use algo como: C:\MAFRA\Workspace\Protheus\Fontes\Dev\Unit\Emp01\ADVPL\Modulos\COM\Rotinas
ou ate mais simplificadamente para confirmar se a quantidade de estruturas e tamanho do path podem causar problemas, pois ja vimos algo semelhante ocorrer no passado.
Como ainda nao conseguimos reproduzir o problema aqui seria interessante este teste com alguem que reproduz o problema.
Grato

**Comment by carloseniemeyer** [comment]
@lwtnb-wrk  Bom Dia!

Já fizemos esse ajuste de simplificação do caminho e já deu certo.

Alterado para:
**=> C:\MAFRA\Workspace\Workspace_MAFRA\GrupoMafra_Protheus\Fontes\Desenvolvimento\Projeto Unitarizacao\Empresa01**

Acredito que vcs já podem fechar essa Issue, tendo em vista que não conseguiram reproduzir.
Pode ser que esteja associado ao novo AppServer que ainda não testamos.
Quando a nós tomaremos cuidado com o tamanho do Path dos fontes.

Obrigado!

**Comment by lwtnb-wrk** [comment]
@carloseniemeyer Grato pelos testes e retorno. 
Então apenas para resumir a issue para referencias futuras, o problema está realmente na estrutura de arquivos que causa uma diferença na compilação do arquivo.
Ao usar um estrutura com muitos níveis (na verdade com muitos caracteres) o path começa a ficar longo e por algum motivo na compilação isso está ocasionando uma diferença nas linhas compiladas.
Com isso ao tentar debugar esse fonte, ocorre uma diferença entre o que está sendo apresentado no Editor em relação ao que está compilado no RPO.
Enfim vou levantar essa questão internamente para avaliarmos se algo pode ser feito para que isso não ocorra mais em novos Appservers.

**Comment by paulopx3000** [comment]
Bom dia,

O Visual Studio Code direto tenho que ficar reiniciando os serviços por conta de erros (ele para debugar) sozinho sempre foi assim.

**Comment by DanielYampolschi** [comment]
Ola @paulopx3000 ,

Essa issue já foi fechada a bastante tempo e não temos outros relatos parecidos com o seu no momento, 
então por favor abra uma nova issue informando o máximo de detalhes que você conseguir e seguindo os passos abaixo para anexar os logs para tentarmos identificar porque isso acontece no seu ambiente.

https://github.com/totvs/tds-vscode/blob/dev/TROUBLESHOOTING.md#gerando-logs

Obrigado.

**Comment by paulopx3000** [comment]
vou fazer isso obrigado!
