### ISSUE TITLE
Erro ao Compilar qualquer programa: appre6334(17) Error C2006 Statement not allowed outside procedure or function

### ISSUE THREAD

**Issue by RobertaDionisio** [totvs/tds-vscode#688]
**Describe the bug**
Não esta sendo possível compilar nenhum programa, apresenta o erro abaixo:

appre6334(17) Error C2006 Statement not allowed outside procedure or function

e aponta para linha:

Local aArea     	:= GetArea() 

Isso ocorre para qualquer programa...

Para aplicar Patchs está normal.

**To Reproduce**

**Expected behavior**
Compilar normalmente

**Screenshots**

![image](https://user-images.githubusercontent.com/52183110/119846230-543a7100-bee0-11eb-832f-3a8c9c7b2669.png)

**Desktop (please complete the following information):**

**Appserver (please complete the following information):**

![image](https://user-images.githubusercontent.com/52183110/119846569-a24f7480-bee0-11eb-8cfa-85b6705bf1da.png)

**Additional context**

**Comment by brodao** [comment]
@RobertaDionisio 

Experimente atualizar os "includes" baixando-os do portal de suporte ao cliente.

Aguardo retorno.

**Comment by RobertaDionisio** [comment]
@brodao valeu!
Era isso mesmo, tudo certo agora!
Obrigada
