### ISSUE TITLE
Automatização geração Patch 

### ISSUE THREAD

**Issue by charlesreitz** [totvs/tds-vscode#69]
Olá, existe como automatizar a geração de patchs via VSCode, uma lista de JSON  com o nome dos fontes por exemplo. 

OU

Algum Crlt + Shift + P  passa a lista de fontes para gerar, ao invés de aparecer a tela para selecionar

**Comment by ricardomansano** [comment]
@charlesreitz , com bia, a automatização deve ser feita via TDSCli, ja temos uma versão que roda sob a plataforma que construimos pro VS, e contempla novas caracteristicas que ja estão em testes pelo nosso setor de Cloud, o Leo (@lwtnb-wrk ) pode lhe passar mais informações.

Só lembrando que ele roda em linha de comando, onde a automação é mais performática.
