### ISSUE TITLE
Incluir configuração para definir o local dos arquivos pré-processados para que não conflitem com os arquivos do projeto durante o processo de compilação de forma a evitar a mensagem do tipo Duplicated function U_BFG136A (found in APPRE25547.PRW)

### ISSUE THREAD

**Issue by NaldoDj** [totvs/tds-vscode#690]
Incluir configuração para definir o local dos arquivos pré-processados para que não conflitem com os arquivos do projeto durante o processo de compilação de forma a evitar a mensagem do tipo Duplicated function U_BFG136A (found in APPRE25547.PRW)

![image](https://user-images.githubusercontent.com/4443278/120486494-7d994800-c38b-11eb-9bb0-85692d0c2873.png)

_Originally posted by @NaldoDj in https://github.com/totvs/tds-vscode/issues/306#issuecomment-853018982_

**Comment by danielbolognani** [comment]
@NaldoDj Quem da o aviso de erro de Função duplicada é o appserver, nesse seu caso os arquivos APPREXXXX.prw estão compilados no RPO e não necessariamente são arquivos locais.
O pré compilador gera arquivos temporários e não são arquivos .prw, portanto não causariam esse tipo de problema.

Para resolver o seu problema será necessário ou mudar o nome das funções nos seus arquivos ou excluir os fontes APPREXXXX.prw do seu rpo.
