### ISSUE TITLE
ERRO NO MEU VSCODE

### ISSUE THREAD

**Issue by LeonardoFelix385** [totvs/tds-vscode#692]
Prezados, Boa tarde!

Após tentar realizar um aplicação de alguns Patchs no ambiente de um cliente meu VSCode parou de funcionar, não consigo mais me conectar a nenhuma empresa e aparece esse erro abaixo, preciso de ajuda para normalizar meu VSCode.

![Screenshot_2](https://user-images.githubusercontent.com/85514049/121066170-f8a19a80-c79f-11eb-9060-9f23b9be0a93.png)

**Comment by ricardomansano** [comment]
@LeonardoFelix385 ,
Enviado procedimento pra resetar seu ambiente via email
At,
Mansano

**Comment by ricardomansano** [comment]
Suponho que o processo de rest tenha funcionado, encerrando issue
