### ISSUE TITLE
Syntaxe erro compile - com as includes 21-05-12-p12

### ISSUE THREAD

**Issue by disolucaodigital** [totvs/tds-vscode#693]
Ao realizar toda atualização, e alterar as includes novas. ao tentar compilar é dado erro de syntaxe erro compile.

conforme video anexo.
https://user-images.githubusercontent.com/85687710/121545817-3a6d5380-c9e1-11eb-94c8-90b830a6bb0b.mp4

Includes Anteriores e Atuais
[includes.zip](https://github.com/totvs/tds-vscode/files/6632291/includes.zip)

**Comment by danielbolognani** [comment]
Pelo que entendi, a atualização de includes causou o problema, certo?
A extensão TDS-VSCode não tem atuação em cima disso. Favor abrir chamado para a equipe responsável pelos Includes (normalmente é o Framework Protheus).

**Comment by disolucaodigital** [comment]
hum... abri um chamado com a TOTVS e eles responderam assim:

ERIKA CARVALHO BRAGA
Hoje às 09:17
Sérgio, bom dia. 
A ferramenta VSCode não é desenvolvida pela TOTVS.
Sendo assim, todas as dúvidas e erros referente a extensão TOTVS Developer Studio for VS Code, devem ser direcionadas a equipe responsável através do canal oficial (https://github.com/totvs/tds-vscode).

Segue abaixo link  para abertura de chamados referente ao plugin TOTVS Developer Studio for VS Code :
https://github.com/totvs/tds-vscode/issues

Segue abaixo documentação
MP - ADVPL - VSCODE

**Comment by danielbolognani** [comment]
Boa tarde,
O VSCode não é desenvolvido pela TOTVS, mas a extensão é sim.
Explique que a diferença está apenas nos Includes, do nosso lado não temos
como agir. Pode até mencionar que eu encaminhei o seu contato e se precisar
podem me chamar para tirarem a dúvida.

At.te.

Em qui., 10 de jun. de 2021 às 14:32, disolucaodigital <
***@***.***> escreveu:

**Comment by disolucaodigital** [comment]
Boa tarde,
agradeço sua atenção. ja retornei o chamado com a TOTVS, e irei aguardar.
Att., Sergio Bastos
