### ISSUE TITLE
Problema ao Aplicar patch a partir de maquina local V. 1.2.3

### ISSUE THREAD

**Issue by paulocwb** [totvs/tds-vscode#695]
Após a atualização para versão 1.2.3 ao tentar aplicar um patch  a partir de uma maquina local, ele faz as validações com sucesso e após a leitura (reading) dos programas no patch, a atualização é abortada e executado rollback com a sequinte mensagem:

>  Get patch resource content could not be executed. Server returned: Patch file D:\PROTHEUS\Ambientes\D:\Users\PAULO\Desktop\expedicao_continua_12_1_25_rh_tttp120_lg.ptm not found

Aparentemente é algum problema com questão de diretorio, ele está lendo incorretamente.

**To Reproduce**
1. Download patch
2. Conectar a um servidor a partir de uma maquina local c/ windows 10
3. aplicar patch
4. retorna erro.

**Expected behavior**
É esperado a aplicação com sucesso do patch.

**Screenshots**

**Desktop (please complete the following information):**
Windows 10 Pro - 64 Bits

**Comment by lwtnb-wrk** [comment]
@paulocwb Favor informar qual a build do AppServer que esta utilizando. Tivemos essa ocorrencia no passado com builds antigas do AppServer.
E de qualquer forma se possivel, veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by lwtnb-wrk** [comment]
@paulocwb E se possivel envie o appserver.ini pois pode ser tambem um problema de configuracao do appserver, pois o caminho do patch esta bem estranho mesmo...
Voce tambem atualizou seu AppServer recentemente?

**Comment by cmregazzo** [comment]
Bom dia @lwtnb-wrk ,

Estamos com o mesmo problema aqui.

Após atualizar o VsCode, não estamos conseguindo aplicar patch.

O erro que aparece no AppServer é o seguinte:

[WARN ][SERVER] [Thread 3300] Error Loading TLPP RPO. Env: Teste
[ERROR][SERVER] Patch file E:\ToTvs12\Microsiga\Protheus\Protheus_Data\\tmptds9q
dvfv2/expedicao_continua_12_1_25_extrator_tttp120_lg14-06-2021-11-07-52.ptm not
found

Eu não atualizei o meu AppServer.

Att,

**Comment by lwtnb-wrk** [comment]
@cmregazzo Mas qual o AppServer que esta utilizando? Favor informar a build exata, para confirmarmos o problema.

**Comment by cmregazzo** [comment]
Bom dia @lwtnb-wrk,

Seguem os dados solicitados:

Remote build: 7.00.191205P-20200714
Remote version: 19.3.0.9
Remote type: 1 - QT-5.14.0 WIN

Obrigado.

**Comment by lwtnb-wrk** [comment]
@cmregazzo O Remote version é a build do Smartclient. Qual a build do AppServer?

**Comment by paulocwb** [comment]
> @paulocwb Favor informar qual a build do AppServer que esta utilizando. Tivemos essa ocorrencia no passado com builds antigas do AppServer.
> E de qualquer forma se possivel, veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

Build: 7.00.191205P

Foi atualizado recentemente sim, voltei para a versão 1.2.1 onde não ocorre o problema.
Segue anexo o appserver.ini

[AppServer_paulo.zip](https://github.com/totvs/tds-vscode/files/6649091/AppServer_paulo.zip)

**Comment by paulocwb** [comment]
Dados mais completos:
Versão: TOTVS Manufatura
Build AppServer: 7.00.191205P-20200424 - 64 bits
Sistema operacional: Windows Server 2016
Appserver version: 19.3.0.4
Build DBAccess: 20191119-20200706
Release do RPO:  12.1.025
Release do dicionário: 12.1.025
Local files: CTREE
License server: 2014 - 3.2.0
DB DataBase: MSSQL
DB API Build: 20191119-20200116

**Comment by cmregazzo** [comment]
Bom dia @lwtnb-wrk ,

Seguem os dados:

Dados do Server 

Versão: TOTVS Manufatura
Build AppServer: 7.00.191205P-20200724 - 64 bits
Nome do servidor: XXXX
Sistema operacional: Windows Server 2012 R2
Appserver version: 19.3.0.6_RC7
Build DBAccess: 20181212-20191121
Release do RPO:  12.1.025
Release do dicionário: 12.1.025
Local files: CTREE
License server: 2014 - 3.0.3
DB DataBase: MSSQL7

Dados do Remote 

Remote build: 7.00.191205P-20200714
Remote version: 19.3.0.9
Remote type: 1 - QT-5.14.0 WIN

Obrigado.

**Comment by lwtnb-wrk** [comment]
@paulocwb Realmente seu Appserver está bem desatualizado e realmente tinhamos esse problema relatado nessa versão.

@cmregazzo Seu Appserver é um RC7. Esse problema foi corrigido nessa versão (19.3.0.6) oficial, de qualquer forma é melhor atualiza-lo para um versão oficial mais atualizada também.

Creio que irão verificar que o problema não ocorre mais nos AppServers atualizados. 
Se o problema continuar a ocorrer em AppServer mais atualizado, precisaremos obter mais informações.

**Comment by felipe-brainbox** [comment]
O meu está totalmente atualizado e está dando o mesmo problema que o pessoal aí.
Tive que voltar para a versao 1.2.1

**Comment by felipe-brainbox** [comment]
Dados do Server 

Versão: TOTVS Varejo
Build AppServer: 7.00.191205P-20210114 - 64 bits
Nome do servidor: PROTHEUS-PROD-S
Sistema operacional: Windows Server 2016
Appserver version: 19.3.1.5
Build DBAccess: 20200606-20201110
Release do RPO:  12.1.027 - Out  2020
Release do dicionário: 12.1.027 - Out  2020
Local files: ctree
License server: 2014 - 3.2.0
DB DataBase: MSSQL7
DB API Build: 20200606-20201110

**Comment by lwtnb-wrk** [comment]
@felipe-brainbox A principio não tínhamos relatos de problemas com essa sua versão de AppServer.
Se puder depois testar e nos enviar os logs conforme descrito em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs.

Eu testei aqui com a 19.3.1.5 e um patch que peguei do portal e apliquei sem problemas.
Qualquer patch dava problema? Tem algum exemplo para nos passar?

**Comment by danielbolognani** [comment]
Pessoal, por favor sigam os passos desse link: https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs 
E nos enviem esses logs, só assim a gente vai conseguir entender o que está acontecendo realmente (não temos problemas para aplicar os patchs por aqui).

**Comment by brodao** [comment]
´Senhores,

Há algum tempo, tive relato de problemas e devia-se ao nome longo do caminho e do arquivo.
Copie o pacote de atualização para uma pasta de nome curto, p.e. c:\patchs e renomeie o arquivo para um tamanho máximo de 8 caracteres, um ponto e a extensão, p.e. de "expedicao_continua_12_1_25_extrator_tttp120_lg14-06-2021-11-07-52.ptm" para "extrator.ptm".

**Comment by brodao** [comment]
Senhores,

Consegui reproduzir a ocorrência ao utilizar caracteres acentuados e iremos verificar. 
Como paliativo, o caminho completo e o nome do arquivo, não podem ter nenhum caractere acentuado ou especial e utilize um nome curto para a pasta (com um ou dois níveis no máximo).

O ambiente utilizado para testes foi:

- TDS-VSCode 1.2.3
- AppServer 19.3.1.7
- SO Windows 10

Mesmo que a versão do appServer seja outra, experimente o paliativo.

Grato pela compreensão e paciência.

**Comment by daniellourencojp** [comment]
Boa tarde..

No meu não funcionou.. coloquei no caminho curtíssimo, mesmo assim ele pega o caminho do servidor..

Info  - 17:14:40] Patch info finished.
[Info  - 17:14:40] Starting get patch resource.
[Info  - 17:14:40] Starting build for environment valida1.
[Error - 17:14:42] Get patch resource content could not be executed. Server returned: Patch file C:\Totvs\TOTVS_MITANI\P12\D:\patch\tttp120_lg.ptm not found

O caminho é : D:\patch\tttp120_lg.ptm

**Comment by brodao** [comment]
> 
> 
> Boa tarde..
> 
> No meu não funcionou.. coloquei no caminho curtíssimo, mesmo assim ele pega o caminho do servidor..
> 
> Info - 17:14:40] Patch info finished.
> [Info - 17:14:40] Starting get patch resource.
> [Info - 17:14:40] Starting build for environment valida1.
> [Error - 17:14:42] Get patch resource content could not be executed. Server returned: Patch file C:\Totvs\TOTVS_MITANI\P12\D:\patch\tttp120_lg.ptm not found
> 
> O caminho é : D:\patch\tttp120_lg.ptm

Esse caminho é local ou de rede (mapeado)?

**Comment by daniellourencojp** [comment]
D:\patch\tttp120_lg.ptm é no meu computador..caminho local

C:\Totvs\TOTVS_MITANI\P12 é o caminho da estrutura do Protheus lá no servidor.. não na minha maquina

**Comment by lwtnb-wrk** [comment]
Identificamos um erro e geramos uma correção. 
Ainda estamos em fase de testes mas se quiserem/puderem ajudar nos testes segue o link:
https://github.com/totvs/tds-vscode/releases/tag/v1.2.4

**Comment by Smmartinez** [comment]
Bom dia! Fiz a atualização para a versão 1.2.4 e agora o Icone da TOTVS não aparece.

![image](https://user-images.githubusercontent.com/4532855/122211706-670bea00-ce7d-11eb-8d0d-395138db8718.png)

**Comment by lwtnb-wrk** [comment]
> Bom dia! Fiz a atualização para a versão 1.2.4 e agora o Icone da TOTVS não aparece.
> 
> ![image](https://user-images.githubusercontent.com/4532855/122211706-670bea00-ce7d-11eb-8d0d-395138db8718.png)

Valeu pelo aviso Sergio.

**Comment by lwtnb-wrk** [comment]
> > Bom dia! Fiz a atualização para a versão 1.2.4 e agora o Icone da TOTVS não aparece.
> > ![image](https://user-images.githubusercontent.com/4532855/122211706-670bea00-ce7d-11eb-8d0d-395138db8718.png)
> 
> Valeu pelo aviso Sergio.

Se puder desintalar o vsix atual, baixar o novo vsix e validar se o icone esta okay, eu agradeço

**Comment by Smmartinez** [comment]
@lwtnb-wrk @leowww Agora esta certo!

**Comment by danielbolognani** [comment]
@Smmartinez a parte de aplicação de patch também está ok agora?

**Comment by lwtnb-wrk** [comment]
@danielbolognani O @Smmartinez não havia relatado o problema de aplicação de patches e pode nem ter tido problemas, pois foram em apenas alguns ambientes que o erro ocorria...

**Comment by Smmartinez** [comment]
Apenas para reportar acabei de fazer um teste de aplicacao do patch e nao tive erroa.
Esse é o caminho que utilizo:

Patch file: m:/Protheus10/AtualizacaoPTM/21-05-17_ATUALIZACAO_12.1.27_CTB_EXPEDICAO_CONTINUA/expedicao_continua_12_1_27_ctb_tttp120_lg.ptm


M é uma letra mapeada do servidor


Att.
Sergio Martinez Martinez

 
 



De: "lwtnb-wrk" ***@***.***>
Enviada: 2021/06/16 11:04:33
Para: ***@***.***
Cc:  ***@***.***, ***@***.***
Assunto:  Re: [totvs/tds-vscode] Problema ao Aplicar patch a partir de maquina local V. 1.2.3 (#695)
 

 

@danielbolognani O @Smmartinez não havia relatado o problema de aplicação de patches e pode nem ter tido problemas, pois foram em apenas alguns ambientes que o erro ocorria...

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/totvs/tds-vscode/issues/695#issuecomment-862409390", "url": "https://github.com/totvs/tds-vscode/issues/695#issuecomment-862409390", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by gustavocunha88** [comment]
Boa tarde
Instalei a nova versão e o erro de aplicação de patch permaneceu.

Get patch resource content could not be executed. Server returned: Patch file T:\TOTVS12\Microsiga\protheus_global\c:/Patchs/tttp120.ptm not found

Mesmo com nome curto de diretório.

E tbm o icone Totvs não aparece, igual ao analista lwtnb-wrk

**Comment by lwtnb-wrk** [comment]
@gustavocunha88 Voce baixou o vsix agora? Corrigimos hoje de manha a questao do icone. 
Mas qual a versao do AppServer que voce esta usando?

**Comment by gustavocunha88** [comment]
Meu appserver

AppServer
Build AppServer: 7.00.170117A-20190628 - 64 bit

**Comment by lwtnb-wrk** [comment]
> Fiz o download hoje de manhã.

Na duvida realize novamente o download pois sobrescrevemos o arquivo apenas.
Mas reforçando, qual a build exata do AppServer? 19.3.?? algo assim?

**Comment by lwtnb-wrk** [comment]
@gustavocunha88 Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para ajudar nas analises. Valeu!

**Comment by gustavocunha88** [comment]
@lwtnb-wrk Fiz novamente o download e o simbolo da Totvs apareceu.

Porém o erro de aplicação persiste.

Abaixo os dados do appserver e anexo os logs solicitados.

Dados do Server 

Versão: TOTVS Serviços
Build AppServer: 7.00.170117A-20190628 - 64 bits
Appserver version: 17.3.0.13
Build DBAccess: 20181212-20190627
Release do RPO:  12.1.025
Release do dicionário: 12.1.025
Local files: ctree
License server: 2014 - 2.3.4
DB DataBase: ORACLE
DB API Build: 20181212-20190627
[totvsls.log](https://github.com/totvs/tds-vscode/files/6670527/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/6670528/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/6670529/totvsls_out.log)

**Comment by paulocwb** [comment]
Atualizei para o ultimo appserver disponivel e aplicou o patch.

**Comment by EVandroCleto** [comment]
Ontem abri a Issue #705, que foi foi encerrada, mas meu problema não foi resolvido após atualização para a versão 1.2.3
Seguem os logs por aqui
[LOgs_VSCODE_Evandro2.zip](https://github.com/totvs/tds-vscode/files/6670609/LOgs_VSCODE_Evandro2.zip)

Nesta Issue voces orientaram a atualização do appserver, mas solicitei a um colega da equipe para aplicar a patch(mesmo ambiente) que precisava e ele fez a aplicação com sucesso. 
Ele está usando o Totvs Developer versão 1.2.1

**_Vocês conseguem me mandar o arquivo vsix desta versão, pfv?_**

Quanto a atualização da appserver, é um processo na empresa extremamente moroso que depende de orçamento, aprovação de diretorias, envolvimento de usuário para validação, etc, ou seja muito trabalho e custo envolvido para resolver um problema pequeno, cuja solução contorno é simples(a disponibilização da versão 1.2.1).
Muito Obrigado.

**Comment by daniellourencojp** [comment]
> Ontem abri a Issue #705, que foi foi encerrada, mas meu problema não foi resolvido após atualização para a versão 1.2.4
> Seguem os logs por aqui
> [LOgs_VSCODE_Evandro2.zip](https://github.com/totvs/tds-vscode/files/6670609/LOgs_VSCODE_Evandro2.zip)
> 
> Nesta Issue voces orientaram a atualização do appserver, mas solicitei a um colega da equipe para aplicar a patch(mesmo ambiente) que precisava e ele fez a aplicação com sucesso.
> Ele está usando o Totvs Developer versão 1.2.1
> 
> **_Vocês conseguem me mandar o arquivo vsix desta versão, pfv?_**
> 
> Quanto a atualização da appserver, é um processo na empresa extremamente moroso que depende de orçamento, aprovação de diretorias, envolvimento de usuário para validação, etc, ou seja muito trabalho e custo envolvido para resolver um problema pequeno, cuja solução contorno é simples(a disponibilização da versão 1.2.1).
> Muito Obrigado.

Verdade. Voltei para a versão anterior...

No meu caso que é uma indústria que funciona 24/7.. Para o sistema só no domingo.. numa janela pequena de tempo..

**Comment by gustavocunha88** [comment]
Boa tarde
Também voltei para versão 1.2.1 e consegui aplicar.

**Comment by danielbolognani** [comment]
Pessoal, já identificamos as possíveis causas. Estamos trabalhando na solução que deve ser submetida ao marketplace nos próximos dias. 
Enquanto isso, quem estiver com problemas, favor voltar para a versão 1.2.1.

**Comment by lwtnb-wrk** [comment]
Geramos uma nova correção para o problema de Aplicação de Patches.
Ainda estamos em fase de testes mas se quiserem/puderem ajudar nos testes segue o link:
https://github.com/totvs/tds-vscode/releases/tag/v1.2.4
Se ainda estiverem com uma versão 1.2.4 instalada é necessário desinstalar e reiniciar o VS Code antes de instalar novamente.
Quem já tinha retornado para a versão anterior, instalem do vsix e confirmem se o problema foi solucionado em seu ambiente.

**Comment by Elcymerson** [comment]
Eu estava na versão 1.2.3. Atualizei para 1.2.4 e continuo tendo erro ao aplicar o patch:

[Info  - 5:34:20 PM] Starting get patch resource.
[Info  - 5:34:20 PM] Patch file: c:/TEMP/update.ptm
[Info  - 5:34:20 PM] Starting build for environment COMPILA.
[Info  - 5:34:21 PM] Aborting end build (rollback changes).
[Info  - 5:34:21 PM] Getting organizations (company/branch)

**Comment by lwtnb-wrk** [comment]
@Elcymerson Seu ambiente eh SPED TSS?

**Comment by Elcymerson** [comment]
Olá. Não é SPED TSS.

Conseguiu aplicar o patch mas não está 100%. Olhe a sequência e os tempos abaixo desde o início, principalmente a partir da última linha em 05:44:04 PM. Deu uma 'pausa' de quase 1 minuto e depois ele se reconectou ao server, ainda com algumas msg de aparente erro e finalizou com sucesso.

Espero que essa sequência os ajude a entender o que está acontecendo.

[Info  - 5:42:48 PM] Starting patch validate.
[Info  - 5:42:48 PM] Patch file: c:/TEMP/update.ptm
[Info  - 5:42:48 PM] Starting build for environment COMPILA.
[Info  - 5:42:49 PM] Aborting end build (rollback changes).
[Info  - 5:42:49 PM] Patch validate finished.
[Info  - 5:43:58 PM] Starting patch validate.
[Info  - 5:43:58 PM] Patch file: c:/TEMP/update.ptm
[Info  - 5:43:58 PM] Starting build for environment COMPILA.
[Info  - 5:43:59 PM] Aborting end build (rollback changes).
[Info  - 5:43:59 PM] Patch validate finished.
[Info  - 5:43:59 PM] Starting function inspector.
[Info  - 5:43:59 PM] Loading functions from server.
[Info  - 5:44:01 PM] Functions loaded (Duration: 2.305000)
[Info  - 5:44:02 PM] 111032 functions successfully retrieved.
[Info  - 5:44:02 PM] Function inspector finished.
[Info  - 5:44:02 PM] Starting patch info.
[Info  - 5:44:02 PM] Patch file: c:/TEMP/update.ptm
[Info  - 5:44:02 PM] Starting build for environment COMPILA.
[Info  - 5:44:03 PM] Aborting end build (rollback changes).
[Info  - 5:44:03 PM] Patch info finished.
[Info  - 5:44:03 PM] Starting get patch resource.
[Info  - 5:44:03 PM] Patch file: c:/TEMP/update.ptm
[Info  - 5:44:03 PM] Starting build for environment COMPILA.
[Info  - 5:44:04 PM] Aborting end build (rollback changes).
[Info  - 5:44:04 PM] Getting organizations (company/branch)
[Info  - 5:44:58 PM] Starting reconnection to the server 'PRD_SLAVE_1_rpc'
[Info  - 5:44:58 PM] Authenticating...
[Info  - 5:45:06 PM] User authenticated successfully.
[Info  - 5:45:06 PM] Reconnection to the server 'PRD_SLAVE_1_rpc' finished.
[Info  - 5:45:07 PM] Secure authenticating...
[Info  - 5:45:20 PM] User authenticated successfully.
[Info  - 5:45:20 PM] Validating a package in Protheus application
[Info  - 5:45:20 PM] Starting call proc ex ().
[Info  - 5:45:20 PM] Could not call proc ex.
[Info  - 5:45:20 PM] Call proc ex finished.
[Warn  - 5:45:20 PM] 
[Info  - 5:45:20 PM] Server 'PRD_SLAVE_1_rpc' successfully disconnected.
[Info  - 5:45:20 PM] Starting apply patch.
[Info  - 5:45:20 PM] Starting build for environment COMPILA.
[Info  - 5:45:21 PM] Applying patch file: c:/TEMP/update.ptm
[Info  - 5:45:22 PM] Patch (update.ptm) successfully applied.
[Info  - 5:45:22 PM] Committing end build.
[Info  - 5:45:23 PM] Apply patch finished.

**Comment by danielbolognani** [comment]
@Elcymerson O processo de aplicação de patch na versão 1.2.3 ou superior adicionou uma etapa a mais que é a validação do patch pelos fontes do framework ADVPL, por isso está mais demorado, apesar das mensagens mostradas, todas são esperadas e esse é o processo normal.
O único alerta foi no tempo de quase 1 minuto após pegar a empresa/filiais. Iremos analisar e qualquer novidade a gente informa por aqui.

**Comment by Elcymerson** [comment]
Obrigado @danielbolognani 
O ambiente possui 1 empresa e 5 filiais. Dicionário no banco de dados.

**Comment by lwtnb-wrk** [comment]
@Elcymerson Grato pelas informações.
Somente para entendermos melhor, poderia detalhar como é a sua infra estrutura?
Pelo nome, acredito que o servidor PRD_SLAVE_1 pertence a um load balance, correto? 
Voce estava conectado diretamente nesse servidor ao aplicar o Patch?
Reforço que o Patch foi aplicado somente nesse servidor e posteriormente deve ser aplicado nos outros servidores deste load balance tambem.
Alem disso os servidores estão em uma máquina remota? Em outro SO como Windows Server?

**Comment by Elcymerson** [comment]
Bom dia @lwtnb-wrk!

Balanceamento de serviços com um RPO para operação. São slaves para
balanceamento de carga. Estava conectado ao servidor via conexão remota. A
aplicação está concentrada em um servidor. Temos um repositório COMPILA,
estava conectado para aplicar o patch nesse RPO e depois promovê-lo.



Em ter., 22 de jun. de 2021 às 09:04, lwtnb-wrk ***@***.***>
escreveu:

**Comment by lwtnb-wrk** [comment]
liberada versão 1.2.4 no marketplace.
quem chegou a instalar a pre-release 1.2.4 e quiser atualizar para a oficial, vai precisar desinstalar a pre-release 1.2.4, reiniciar o VS Code e atualizar novamente.

**Comment by felipe-brainbox** [comment]
Continua com problema na aplicação de patch na 1.2.4, agora de "privilegio":
[Info  - 17:38:42] Starting patch validate.
[Error - 17:38:42] Insufficient privileges for APPLY_PATCH
Além disso, por que a interface mudou?

Felipe de Castro S. Lucas
Consultoria e Desenvolvimento
+55 (11) 97662-0592
***@***.***
***@***.***>skype: felipe.fox
<http://brainbox.com.br/>


Em qua., 23 de jun. de 2021 às 14:33, lwtnb-wrk ***@***.***>
escreveu:

**Comment by danielbolognani** [comment]
Boa tarde @felipe-brainbox 
A mensagem de insufficient privileges, tem relação com a chave AllowApplyPatch no appserver.ini
https://tdn.totvs.com/pages/viewpage.action?pageId=268823462
No VSCode só são aceitas endereços IPs nessa chave ou * para qualquer estação.

Sobre a interface, percebemos que algumas coisas ficaram mais confusas e iremos retornar a interface anterior no próximo release.

**Comment by felipe-brainbox** [comment]
Tem razão, tinha colocado restrição para somente 1 e não me atentei.

Legal voltar a interface, a antiga com logo da totvs me parece mais
amigável.

Testei novamente, agora está abortando e da erro:
[image: image.png]
Felipe de Castro S. Lucas
Consultoria e Desenvolvimento
+55 (11) 97662-0592
***@***.***
***@***.***>skype: felipe.fox
<http://brainbox.com.br/>


Em qua., 23 de jun. de 2021 às 17:56, Daniel Otto Bolognani <
***@***.***> escreveu:

**Comment by danielbolognani** [comment]
Olá @felipe-brainbox as imagens anexadas por e-mail não aparecem aqui para gente, consegue anexar diretamente pelo github?

**Comment by TiberinaMG** [comment]
Estou com o problema quando vou aplicar um patch na versão 12.1.33 (HARPIA) com 2 RPO´s na versão V.1.3.4 do plugin...
Patch validate could not be executed. Possible RPO in use.
***************************************************************
2021-10-14T17:01:20.329000-03:00 18928|*  TOTVS S/A  *
*  www.totvs.com.br  *
* TOTVS - Build 7.00.210324P - Oct  6 2021 - 23:33:57 
* Build: 64 bits
* SVN Revision: 32672
* Build Version: 20.3.0.2

**Comment by MarcoMilk** [comment]
Olá a todos.
Vcs acreditam que estava com esse mesmo problema depois de muito sofrimento (tentei tudo) no meu caso era o nome do arquivo muito grande(acho), diminui e passou.
expedicao_continua_12_1_33_fin_tttm120_hp.ptm

Abraço.

**Comment by MarcoMilk** [comment]
Ahhhhhhhhh ou pode ser também o caminho muito longo.
