### ISSUE TITLE
Erro na aplicação de um Patch

### ISSUE THREAD

**Issue by pedrojlima** [totvs/tds-vscode#697]
Quando tento aplicar um patch exibe uma tela de erro. 

![erro server](https://user-images.githubusercontent.com/85879332/121958538-28b9e200-cd3a-11eb-95e3-48607cea62d0.PNG)

**Comment by lwtnb-wrk** [comment]
@pedrojlima Quais a build do AppServer que esta usando? Em que SO o Appserver esta instalado?
Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by pedrojlima** [comment]
SO: Windows Server 2012

![image](https://user-images.githubusercontent.com/85879332/121968747-42165a80-cd49-11eb-8870-73f3cca0c6ad.png)

**Comment by lwtnb-wrk** [comment]
@pedrojlima Favor informar a build exata do AppServer. Algo como 19.3.???

**Comment by pedrojlima** [comment]
Build: 13.3.1.5

**Comment by lwtnb-wrk** [comment]
@pedrojlima Poderia ver em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analises?

Meu AppServer é o mesmo que está utilizando mas meu SO é o Windows 10. E aqui não reproduzo esse problema. Vamos ver se aparece algo nos logs...

**Comment by pedrojlima** [comment]
Bom dia, estou usando o VSCode a pouco tempo, então ainda estou me adaptando a algumas coisas. 
quando gerei o log pelo passo a passo ele diz que é gerado na raiz do projeto. Seria então esse arquivo?
[launch.zip](https://github.com/totvs/tds-vscode/files/6656089/launch.zip)

**Comment by joenesilva** [comment]
@lwtnb-wrk  o mesmo problema está acontecendo comigo poderia me ajudar?

**Comment by danielbolognani** [comment]
Pessoal, por favor sigam os passos desse link: https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs 
E nos enviem esses logs, só assim a gente vai conseguir entender o que está acontecendo realmente (não temos problemas para aplicar os patchs por aqui).

**Comment by pedrojlima** [comment]
[totvsls.log](https://github.com/totvs/tds-vscode/files/6657290/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/6657291/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/6657292/totvsls_out.log)

**Comment by danielbolognani** [comment]
@pedrojlima Esses logs são antigos, precisa alterar os arquivos json conforme a documentação e tentar realizar o processo de aplicação de patch.
Após alterar os arquivos json, é necessário reiniciar o VSCode para que os logs sejam gerados corretamente e eles devem ficar na raiz do seu workspace/projeto

**Comment by pedrojlima** [comment]
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/6657747/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/6657748/totvsls_out.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/6657749/totvsls.log)

**Comment by lwtnb-wrk** [comment]
@pedrojlima Seu AppServer parece estar configurado com ALLOWAPPLYPATCH e sua estação não está na lista de permissões.
Durante a validação não apareceu uma mensagem informando "Insufficient privileges for APPLY_PATCH" ?

**Comment by pedrojlima** [comment]
Não, só informa que está inicializando a aplicação e depois exibe que tem um erro mas não mostra o erro.
![vscode](https://user-images.githubusercontent.com/85879332/122105471-2feef780-cdef-11eb-82e7-9f3a2c39bed4.PNG)

**Comment by pedrojlima** [comment]
Boa tarde, tirando o ALLOWAPPLYPATCH eu consegui aplicar o patch

**Comment by lwtnb-wrk** [comment]
@pedrojlima Grato pelo retorno.

**Comment by pedrojlima** [comment]
Obrigado pelo apoio.

**Comment by joenesilva** [comment]
@danielbolognani, @lwtnb-wrk  não localizei o arquivo settings.json na pasta .vscode para fazer a alteração. Poderia me ajudar?

**Comment by lwtnb-wrk** [comment]
@joenesilva Essa é uma configuração do AppServer, procure por appserver.ini

**Comment by joenesilva** [comment]
@lwtnb-wrk estava fazendo a configuração sugerida através do link: https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs , porém não encontrei o arquivo "settings.json" na pasta ".vscode" .
Já retirei o parâmetro ALLOWAPPLYPATCH  do meu arquivo appserver.ini, porém o erro persiste, de não conseguir aplicar patch.

**Comment by lwtnb-wrk** [comment]
@joenesilva Qual o SO em que o AppServer está instalado? Qual a build exata do AppServer??

**Comment by joenesilva** [comment]
@lwtnb-wrk 
![Informacoes](https://user-images.githubusercontent.com/25109069/122232596-bb20c980-ce91-11eb-9d32-8caf06143a8c.jpg)

**Comment by lwtnb-wrk** [comment]
@joenesilva Tivemos um outro problema em relação a aplicação de patches mesmo com sintomas parecidos.
Ainda estamos em fase de testes mas se quiser/puder ajudar nos testes segue o link:
https://github.com/totvs/tds-vscode/releases/tag/v1.2.4
