### ISSUE TITLE
Problema na compilação de um fonte não versão VsCode 12.1.33

### ISSUE THREAD

**Issue by marivaldo3101** [totvs/tds-vscode#698]
Olá boa tarde,

Estou fazendo a compilação de um patch na nova versão do VsCode na 12.1.33, porem esta sendo apresentado o erro conforme texto abaixo.

Versão da build que esta sendo utilizada

* TOTVS - Build 7.00.210324P - Jun  4 2021 - 20:33:24
* Build: 64 bits
* SVN Revision: 31140
* Build Version: 20.3.0.0_ts20
 
 Erro apresentado:
[Info  - 17:59:07] Starting patch validate.
[Info  - 17:59:07] Patch file: c:\debug_sis\Fontes\Patch\p12_setuprobo_multi_harpia.ptm
[Info  - 17:59:07] Starting build for environment arg_33sis.
[Error - 17:59:07] Start build error: Server returned: Request ignored -- RMS_DBGSTARTBUILD -- Already building ...

**Comment by lwtnb-wrk** [comment]
Problemas referente a testes no Harpia
