### ISSUE TITLE
Totvs Servidor no VSCODE 1.57.0

### ISSUE THREAD

**Issue by Ragoy** [totvs/tds-vscode#699]
Bom dia.

Não estou conseguindo fazer funcionar o servidor no VScode 1.57.0, já tentei também na versão anterior e agora não funciona também.

Error running command totvs-developer-studio.connect: Running the contributed command: 'totvs-developer-studio.connect' failed.. This is likely caused by the extension that contributes totvs-developer-studio.connect.

Já refiz a instalação várias vezes e não estou conseguindo resolver, preciso aplicar um pacote do e-social urgente.

**Comment by lwtnb-wrk** [comment]
@Ragoy Depois das desinstalações você está reiniciando o VS Code?

**Comment by lwtnb-wrk** [comment]
@Ragoy Atualizei meu VS Code para a 1.57.0 e continuo utilizando o tds-vscode 1.2.3 sem problemas aqui.
Você está com um projeto/pasta/workspace aberto?

**Comment by Ragoy** [comment]
Bom dia.

Já fiz de tudo, inclusive voltar a versão anterior e não tenho sucesso.

É possível usar na versão anterior do VSCODE com as extensões da totvs 1.2.3?

**Comment by Ragoy** [comment]
Como disse, já refiz todo o processo e não funciona, não conecta no servidor.

**Comment by danielbolognani** [comment]
@Ragoy, consegue seguir esse passo a passo: https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs 
E nos enviar esses logs?

**Comment by Ragoy** [comment]
Daniel, bom dia.

Não consigo conectar no servidor em nenhum dos ambientes, produção e teste.
Na semana do dia 7 a 11/06 o VScode atualizou e tudo parou de funcionar.
Seguem os arquivos.

Att.




Roger Rodrigo Ragoy
Tecnologia da Informação – Desenvolvimento de Sistemas
+55 [11] 3670-5300, Ramal 5325


[cid:homee73cfa]<http://www.vunesp.com.br> [cid:facebookfc8532] <http://pt-br.facebook.com/VunespOficial/>  [cid:twitter593990] <http://www.twitter.com/vunesp>
[cid:assinatura-vunespfd4084]<http://www.vunesp.com.br/>

De: Daniel Otto Bolognani ***@***.***
Enviada em: terça-feira, 15 de junho de 2021 11:02
Para: totvs/tds-vscode
Cc: Roger Rodrigo Ragoy; Mention
Assunto: Re: [totvs/tds-vscode] Totvs Servidor no VSCODE 1.57.0 (#699)


@Ragoy<https://github.com/Ragoy>, consegue seguir esse passo a passo: https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs
E nos enviar esses logs?

**Comment by danielbolognani** [comment]
Bom dia @Ragoy, por favor anexe os arquivos de algum outra forma, por e-mail eles não chegam aqui para gente

**Comment by Ragoy** [comment]
[totvsls.log](https://github.com/totvs/tds-vscode/files/6656441/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/6656442/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/6656443/totvsls_out.log)

**Comment by danielbolognani** [comment]
@Ragoy, o problema provavelmente é porque vc está utilizando uma pasta na rede, copie os arquivos para uma pasta local ou Mapeie a unidade de rede para uma unidade local.

**Comment by Ragoy** [comment]
@danielbolognani.

Realmente esse era o problema, removi o compartilhamento administrativo e funcionou, obrigado.

Então agora não é mais possível usar o VScode se não for local?

Att

**Comment by lwtnb-wrk** [comment]
@Ragoy O uso de drives de rede sempre foram problemáticos e portanto desaconselhados.
Você utilizava assim antes e parou de funcionar depois da atualização??

**Comment by Ragoy** [comment]
@lwtnb-wrk 

Correto, até antes da 1.57.0 funcionava perfeitamente.
Agora será necessário pensar em outra forma de dar segurança para os fontes, que no modelo anterior já era feito o backup no servidor.
A única coisa que ficava na máquina do analista ou terceiro era o VScode, agora no caso de terceiros vai ficar difícil manter o sincronismo.

Att

**Comment by lwtnb-wrk** [comment]
@Ragoy Interessante, pois isso, até onde sabemos, era uma limitação do VS Code, mas não sabia que passou a funcionar em algum momento e que voltou a não funcionar agora...

**Comment by Ragoy** [comment]
@lwtnb-wrk 

Eu usada assim desde que ocorreu a obrigatoriedade do VSCode para o Protheus, só agora na versão 1.57.0 parou de funcionar.
Agora está rodando, mas os fontes estão na minha máquina local o que não é bom.

**Comment by danielbolognani** [comment]
@Ragoy, o ideal seria tentar usar alguma ferramenta de versionamento de
código (GIT, SVN, etc), ou então como disse, se utilizar a pasta de rede
mapeada no Windows deve funcionar sem problemas também.

Como o Leo comentou, sempre tivemos problemas com o uso de paths UNC
(começados com \\) no workspace, inclusive nem tínhamos essa ciência de que
um dia funcionou.


Em ter., 15 de jun. de 2021 às 13:27, Ragoy ***@***.***>
escreveu:
