### ISSUE TITLE
Conteúdos strings não são apresentadas como sendo tipo string

### ISSUE THREAD

**Issue by izacsc** [totvs/tds-vscode#7]
Ao verificar uma variável no watch, ou no mouse hover no debug, ou no debug console as variáveis do tipo caracter são apresentadas sem aspas, o que faz que elas possam ser apresentadas de forma incorreta.

![image](https://user-images.githubusercontent.com/423449/57934937-0a513600-7897-11e9-8ae2-ed158b71ebf9.png)

No exemplo acima a variável cPercent é do tipo caracter, mas é apresentada como numérica.

**Comment by DanielYampolschi** [comment]
Corrigido, estará disponível na próxima atualização.
