### ISSUE TITLE
Geração de patch não respeita filtro *

### ISSUE THREAD

**Issue by charlesreitz** [totvs/tds-vscode#70]
Olá, ao tentar gerar um patch e realizar o filtro, o resultado não é apresentando. 

![image](https://user-images.githubusercontent.com/1248135/58913508-ba75ca00-86f2-11e9-9ced-b17055ad46eb.png)

![image](https://user-images.githubusercontent.com/1248135/58913559-d2e5e480-86f2-11e9-96f7-24b756449f5e.png)

**Comment by ricardomansano** [comment]
Bom dia, @charlesreitz , o "*" quer esta prejudicando a pesquisa, retire e repita o processo de busca pra testes por gentileza.

@lwtnb-wrk , vale a pena ignorar o "*" caso haja dados preenchidos no campo de busca, já que não informamos essa caracteristica aos DEVs, coloca na fila por favor.

Grato

**Comment by lwtnb-wrk** [comment]
Vamos remover o "*" se houverem, pois neste filtro o "*" representa realmente o caracter '*'. É uma caracteristica do componente que utilizamos.
