### ISSUE TITLE
Geração de WS Client Protheus via TDS VSCODE

### ISSUE THREAD

**Issue by felipesalesmartinez90** [totvs/tds-vscode#700]
**Describe the bug**
Estou com problema ao tentar gerar um client de WebService Portheus usando a versão 1.2.3 do TOTVS Developer Studio for VSCode

**To Reproduce**
1. No VSCode, pressionar F1.
2. Selecionar a opção "TOTVS: Generate WS Protheus"
3. Será apresentada tela, onde deverão ser preenchido os seguintes dados:
     URL Web Service / WSDL File: Neste caso é um arquivo WSDL, localizado na pasta C:\temp\ReinfClient.wsdl
     File Directory: c:\temp (onde sera gerado o arquivo de testeClient.prw)
     Output File Name: testeClient.prw
4. Ao preencher todos os campos acima e clicar no botão "SAVE/CLOSE" é apresentada as seguintes mensagens:
    [Info  - 11:22:37] Starting generate Wsdl.
    [Info  - 11:22:37] Generating WSDL client at server.
    [Info  - 11:22:37] Starting build for environment P12133SISTDB.
    [Info  - 11:22:39] Starting build using RPO token eyJhbGciOiJSUzU...
    [Info  - 11:22:39] Committing end build.
    [Error - 11:22:42] *** ERRO AO GERAR FONTE ADVPL ***
    Source URL : \tmptdsspon019400564/WsReinf.wsdl
    -------------------------------------------------------------------------------
    WSCERR019 / (\tmptdsspon019400564/WsReinf.wsdl) Arquivo n�o encontrado.
    ADVPL WSDL Client 1.120703 / TOTVS Servi�os P12133sistdb on 20210615 11:22:42
    -------------------------------------------------------------------------------
    [Info  - 11:22:42] Generate Wsdl finished.

5. O arquivo "testeClient.prw" é gerado na pasta c:\temp\ porem sem conteúdo (em branco).

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/69321563/122081017-1e98f180-cdd5-11eb-8663-af60f2f4a988.png)
![image](https://user-images.githubusercontent.com/69321563/122081037-2193e200-cdd5-11eb-94d5-5fac78c39ac0.png)
![image](https://user-images.githubusercontent.com/69321563/122081045-235da580-cdd5-11eb-8911-e89f4fdccc5b.png)
![image](https://user-images.githubusercontent.com/69321563/122081057-26589600-cdd5-11eb-8845-75c45192d187.png)
![image](https://user-images.githubusercontent.com/69321563/122081064-28225980-cdd5-11eb-994c-8d4363254c42.png)

**Desktop (please complete the following information):**
 - OS/Architecture: Windows 64 bits

**Appserver (please complete the following information):**
2021-06-15T12:28:55.579000-03:00 69796|***  TOTVS S/A  ***
***  www.totvs.com.br  ***
* TOTVS - Build 7.00.210324P - Jun  4 2021 - 20:33:24
* Build: 64 bits
* SVN Revision: 31140
* Build Version: 20.3.0.0_ts20

**Comment by danielbolognani** [comment]
Boa tarde @felipesalesmartinez90. Esse problema acontece também na versão 19? Se for apenas na versão 20.3.0.0 favor abrir uma task no Ryver pois é por lá que estamos acompanhando os testes da nova versão.
Inclusive tente atualizar a versão do seu appserver, pois já sairam versões mais novas.
