### ISSUE TITLE
Erro na aplicação de Patch

### ISSUE THREAD

**Issue by gustavocunha88** [totvs/tds-vscode#703]
Boa tarde
Ao tentar aplicar um pacote, na validação ele esta considerando o endereço do protheus _data  concatenado com o endereço do pacote na minha máquina e ocorre o erro abaixo

Get patch resource content could not be executed. Server returned: Patch file T:\TOTVS12\Microsiga\protheus_global\G:\VSCODE\reinf\Atualizacao_extrator_FISCAL_CONTABIL\expedicao_continua_12_1_25_extrator_tttp120_lg.ptm not found

**Comment by brodao** [comment]
Favor informar versão do appServer, da extensão TDS-VSCode e realizar os procedimentos de log.
https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md

**Comment by daniellourencojp** [comment]
To com o mesmo Problema.  isso foi depois de atualizar a versão da extensão do VsCode

**Comment by daniellourencojp** [comment]
Versão [1.2.3]
"buildVersion": "7.00.170117A",

**Comment by daniellourencojp** [comment]
Version: 1.57.0 (user setup)
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:18:42.354Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by brodao** [comment]
Ocorrência em duplicidade (#695). 
Favor ver https://github.com/totvs/tds-vscode/issues/695#issuecomment-861796241

**Comment by gustavocunha88** [comment]
Abaixo dados solicitados

AppServer
Build AppServer: 7.00.170117A-20190628 - 64 bit

Versão VS Code
Version: 1.57.0 (user setup)
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:18:42.354Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.18363

Versão da Extensão
v1.2.3

**Comment by gustavocunha88** [comment]
Ok, vou seguir o solução da ocorrência
Obrigado

**Comment by gustavocunha88** [comment]
Mesmo seguindo o paleativo não funcionou, estou usando esse caminho.

Get patch resource content could not be executed. Server returned: Patch file T:\TOTVS12\Microsiga\protheus_global\C:\Patchs\tttp120.ptm not found

**Comment by brodao** [comment]
@gustavocunha88 

Você pode mandar para mim o ini do server. Pode mandar direto para acandido@totvs.com.br.
