### ISSUE TITLE
Erro ao na Ferramenta Patch Apply

### ISSUE THREAD

**Issue by EVandroCleto** [totvs/tds-vscode#705]
Boa tarde.

Fiz a atualização do plugin TOTVSDEVELOPER do VSCODE essa semana e depois disso não está sendo possível aplicar patch pela ferramenta.

Ao selecionar o servidor, clicar com o botão direito do mouse, selecionar o botão Apply Patch e selecionar a patch, ao acionar Botão Validate Patch retorna "Error" e no detalhes  "Newer resources in file patchs then RPO". 
Ao se tentar Clicar em "Aplicar" com a opção "somente mais novos" e clicar em "Apply Patch" retorna "Get patch resource content could not be executed. Server returned: Patch file E:\Outsourcing\Clientes\ML1UI9_TST\Protheus_data\E:\expedicao_continua_12_1_25_tss_protheus_tttp120_lg.ptm not found".
Favor orientar a solução,
Segue log no anexo.
Obrigado.
Evandro Cleto
[tdsSupport1623862281708.zip](https://github.com/totvs/tds-vscode/files/6664665/tdsSupport1623862281708.zip)

**Comment by lwtnb-wrk** [comment]
@EVandroCleto Essa questao ja esta sendo tratada em #695 
Ja identificamos um erro e geramos uma correção.
Ainda estamos em fase de testes mas se quiser/puder ajudar nos testes segue o link:
https://github.com/totvs/tds-vscode/releases/tag/v1.2.4

**Comment by EVandroCleto** [comment]
Tava vendo no forum e achei essa versão, mas estou não sei como instala-la. Pode me orientar?
Obrigado.

**Comment by lwtnb-wrk** [comment]
@EVandroCleto No VS Code, selecione a aba de extensões clique em "..." > "Install from VSIX" e selecione o arquivo .vsix que está no link.

**Comment by danielbolognani** [comment]
Segue imagem para facilitar o que o @lwtnb-wrk comentou:
![image](https://user-images.githubusercontent.com/25229827/122264820-60e23180-ceae-11eb-9f72-3b149e6421fe.png)

**Comment by EVandroCleto** [comment]
Obrigado Pessoal. 
Fiz a instalação da versao 1.2.4, mas o problema ainda persiste.
Segue dados do Server:
Build AppServer: 7.00.191205P-20200220 - 64 bits
Appserver version: 19.3.0.2
Build DBAccess: 20191119-20200217
Release do RPO:  12.1.025
Release do dicionário: 12.1.025
Local files: ctree
License server: 2014 - 3.2.2
DB DataBase: ORACLE
DB API Build: 20181212-20191121


Segue log no anexo.
[tdsSupport1623864776240.zip](https://github.com/totvs/tds-vscode/files/6664794/tdsSupport1623864776240.zip)

**Comment by lwtnb-wrk** [comment]
@EVandroCleto Seu problema nesse caso é a versão do AppServer. Atualize seu AppServer pois essa versão tinha realmente problemas.

**Comment by EVandroCleto** [comment]
Então, mas eu não tinha problemas ate instalar a versão 1.2.3.
Consegue me disponibilizar uma versão anterior à 1.2.3 p/ Testar?
Obrigado.

**Comment by danielbolognani** [comment]
@EVandroCleto no próprio VSCode na mesma aba de extensões, se clicar na "engrenagem" da extensão "Totvs Developer Studio for VSCode" tem a opção de "Install another version"
![image](https://user-images.githubusercontent.com/25229827/122270287-87a36680-ceb4-11eb-97c4-c13aeaeccce7.png)

**Comment by danielbolognani** [comment]
Se puder antes disso gerar os logs conforme essa documentação, ajuda a gente a descobrir o problema:
https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs

**Comment by EVandroCleto** [comment]
Olá Daniel.

Segue... 
Obrigado
[tdsSupport1623864776240.zip](https://github.com/totvs/tds-vscode/files/6665028/tdsSupport1623864776240.zip)

**Comment by danielbolognani** [comment]
@EVandroCleto precisa seguir os passos da documentação que eu enviei e mandar os arquivos que forem gerados, esse log não nos ajuda

**Comment by EVandroCleto** [comment]
@diogodamiani . Fiz as configurações do passo a passo mas nao gera os logs.
![image](https://user-images.githubusercontent.com/28540804/122276475-32b71e80-cebb-11eb-9cc6-5316da5f2ce7.png)
Reiniciei o VS CODE e nada de gerar os logs.

**Comment by danielbolognani** [comment]
Para ter certeza que o arquivo é o correto, abra-o pelo próprio VSCode:
File/Preferences/Settings
Nessa tela procure a parte Extensions/TOTVS e Procure a parte "Totvs Language Server › Launch: Args" e clique em "Edit in settings.json"
![image](https://user-images.githubusercontent.com/25229827/122277507-5b8be380-cebc-11eb-94b7-9c9be3a11c96.png)
![image](https://user-images.githubusercontent.com/25229827/122277566-69416900-cebc-11eb-96c7-128e7ce0b0d1.png)

**Comment by EVandroCleto** [comment]
Agora Sim @diogodamiani.
Seguem os logs.
Obrigado pela ajuda.

**Comment by danielbolognani** [comment]
@EVandroCleto Os logs vieram mas parece que não foi feito nada, nem conexão com o appserver nem aplicação de patch, chegou a fazer isso com o log ligado?

**Comment by EVandroCleto** [comment]
Fiz a configuração do settings.json e fechei o VSCODE.
Abri o VSCODE conectei no servidor e ai apliquei a patch.
Vou fazer novamente

**Comment by EVandroCleto** [comment]
Segue novamente os logs.
Fiz o teste da seguinte forma:
1. Fechei o VSCODE;
2. Deletei os logs antigos;
3. Abri o VSCODE;
4. Desconectei o Server;
5. Conectei o Server novamente;
6. Compilei um fonte para validar a conexão com o Server;
7. Cliquei em cima do Server e selecionei Apply Patch;
8. Selecionei a patch no diretorio;
9. Cliquei em Validate Patch em Actions;
10. Apresentou erro;
11. Selecionei "somente mais novos ou;
12. Cliquei em Apply Patch;
[LOgs_VSCODE_Evandro2.zip](https://github.com/totvs/tds-vscode/files/6665538/LOgs_VSCODE_Evandro2.zip)

**Comment by EVandroCleto** [comment]
Bom dia.

Solicitei a um colega da equipe para aplicar a patch que precisava e ele
fez a aplicação com sucesso.
Ele está usando o Totvs Developer versão 1.2.1
Vocês conseguem me mandar o arquivo vsix desta versão, pfv?

Quanto a atualização da appserver, é um processo na empresa extremamente
moroso que depende de orçamento, aprovação de diretorias, envolvimento de
usuário para validação, etc, ou seja muito trabalho e custo envolvido para
resolver um problema pequeno, cuja solução contorno é simples(a
disponibilização da versão 1.2.1).

Muito Obrigado.


*Evandro Cleto*

*+55(11)97069-0730*
*Skype: evandro.cleto*
*linkedin.com/in/evandro-cleto-51b49340 **Profile URL*
<https://www.linkedin.com/public-profile/settings?trk=d_flagship3_profile_self_view_public_profile>


Em qua., 16 de jun. de 2021 às 16:34, Daniel Otto Bolognani <
***@***.***> escreveu:

**Comment by danielbolognani** [comment]
> @EVandroCleto no próprio VSCode na mesma aba de extensões, se clicar na "engrenagem" da extensão "Totvs Developer Studio for VSCode" tem a opção de "Install another version"
> ![image](https://user-images.githubusercontent.com/25229827/122270287-87a36680-ceb4-11eb-97c4-c13aeaeccce7.png)

@EVandroCleto Só fazer o processo indicado nesse reply que vc consegue instalar outras versões da Extensão

**Comment by EVandroCleto** [comment]
Bom dia Daniel.

Segui o processo acima e instalei a 1.2.1 e consegui aplicar a patch.
Muito obrigado pela ajuda.

Abs,

*Evandro Cleto*

*+55(11)97069-0730*
*Skype: evandro.cleto*
*linkedin.com/in/evandro-cleto-51b49340 **Profile URL*
<https://www.linkedin.com/public-profile/settings?trk=d_flagship3_profile_self_view_public_profile>


Em qui., 17 de jun. de 2021 às 10:39, Daniel Otto Bolognani <
***@***.***> escreveu:
