### ISSUE TITLE
Erro ao aplicar patch

### ISSUE THREAD

**Issue by Elcymerson** [totvs/tds-vscode#708]
**Describe the bug**
Ao tentar aplicar um patch, o sistema exibe mensagem de erro informando que não foi possível validar o patch. Esse patch foi aplicado em outro ambiente antes da atualização do VSCode.

**To Reproduce**
1. Clicar com o botão direito sobre a conexão
2. Clicar em Patch Apply
3. Selecionar o patch
4. Clicar em Aplicar
5. Ver a msg de erro no Output
[PACOTE_DE_CORRECAO_11183487_DMANMAT02-32207_12.1.25.ZIP](https://github.com/totvs/tds-vscode/files/6689152/PACOTE_DE_CORRECAO_11183487_DMANMAT02-32207_12.1.25.ZIP)

**Expected behavior**
Espero conseguir aplicar o patch, pois preciso corrigir erro no Protheus.

**Screenshots**

**Desktop (please complete the following information):**
 - VSCode:
 - Version: 1.57.1 (user setup)
 - Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
 - Date: 2021-06-17T13:28:07.755Z (4 days ago)
 - Electron: 12.0.7
 - Chrome: 89.0.4389.128
 - Node.js: 14.16.0
 - V8: 8.9.255.25-electron.0
 - OS: Windows_NT x64 10.0.14393

**Appserver (please complete the following information):**
- TOTVS - Build 7.00.170117A - Jun 28 2019 - 11:16:56 
- Build: 64 bits
- SVN Revision: 23527
- Build Version: 17.3.0.13

**Additional context**

**Comment by lwtnb-wrk** [comment]
@Elcymerson Liberamos um VSIX com uma correção para o problema relatado.
Acompanhe em #695

**Comment by Elcymerson** [comment]
Caro @lwtnb-wrk, o que é um VSIX?

**Comment by lwtnb-wrk** [comment]
@Elcymerson É um arquivo de instalação do VS Code. Pegue o VSIX 1.2.4 em 
https://github.com/totvs/tds-vscode/releases/tag/v1.2.4
E no VS Code abra a aba de extensões, clique em "..." > "Install from VSIX"
Quando tivermos uma confirmação de que o VSIX está funcionando continuaremos com a publicação no Marketplace
