### ISSUE TITLE
Erro ao aplicar um patch 

### ISSUE THREAD

**Issue by pedrojlima** [totvs/tds-vscode#709]
Bom dia, estou tentando aplicar um patch em minha base mas exibe um erro. 

Version: 1.57.1 (user setup)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:07.755Z (4 days ago)
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 6.3.9600
Appserver (please complete the following information):

TOTVS - Build 7.00.191205P - Jan 14 2021 -
Build: 64 bits
SVN Revision: 29345
Build Version: 19.3.1.5
[totvsls.log](https://github.com/totvs/tds-vscode/files/6694097/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/6694098/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/6694099/totvsls_out.log)

**Comment by danielbolognani** [comment]
Bom dia @pedrojlima, novamente, já existe uma issue aberta sobre isso (#695) e inclusive liberamos por lá uma pré-release com a correção.

**Comment by lwtnb-wrk** [comment]
@pedrojlima Aparentemente pelos logs, seu erro pode estar relacionado com o tamanho do caminho (path) onde o patch esta.
Veja se copiando o patch para um caminho mais curto resolve.
Ao inves de E:\TOTVS12.1.27\protheus_data\__UPGRADE\Atualizações 2021\21-04-30_ATUALIZACAO_12.1.25_CTB_ECD_EXPEDICAO_CONTINUA\expedicao_continua_12.1.25_ctb_ecd_tttp120_lg.ptm
Copie o patch para E:\TOTVS12.1.27\Atualizações 2021\expedicao_continua_12.1.25_ctb_ecd_tttp120_lg.ptm
