### ISSUE TITLE
Depuração: verificar se o fonte sendo depurado é o mesmo do RPO.

### ISSUE THREAD

**Issue by brodao** [totvs/tds-vscode#71]
Ao abrir um fonte para depuração, verificar se esse fonte é o mesmo compilado e caso não seja, apresentar as opções:
* Cancelar depuração
* Ignorar e continuar
* Cancelar depuração, compilar o fonte e reiniciar a depurção

**Comment by ricardomansano** [comment]
@Boa tarde @brodao ,

Esta característica implicaria na engenharia reversa do fonte, ou em um re-compilação para comparação entre as "origens", o que é tecnicamente inviável.

Agradecemos a sugestão mas ela não será implementada.
