### ISSUE TITLE
Erro em aplicação de patch apos atualização do plugin

### ISSUE THREAD

**Issue by Adailton-lanca** [totvs/tds-vscode#713]
Plugin do protheus no vscode atualizou automaticamente e depois disto, todos os patchs que tento aplicar dão erro, inclusive, os ultimos que eu havia aplicado na versao anterior do plugin.

**Comment by lwtnb-wrk** [comment]
@Adailton-lanca Favor dar mais detalhes do problema, sem informações não temos como investigar. 
Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by danielbolognani** [comment]
Boa tarde, soltamos uma atualização hoje relacionado a aplicação de patches. Verifique se sua versão é a 1.2.4. Se ainda assim estiver com problemas, favor gerar os logs conforme o @lwtnb-wrk pediu no comentário acima.

**Comment by Adailton-lanca** [comment]
sim, atualizou para 1.2.4, mas estou com problemas muito urgentes aqui, entao fiz o downgrade para 1.2.1 e conseguir aplicar o patch. Obrigado.

**Comment by Adailton-lanca** [comment]
Boa tarde! Fiz uma nova instalação do vscode pois precisava atualizar um patch em uma estacao PDV, ocorreu o mesmo erro na aplicação do patch, tentei fazer o downgrade mas não funcionou como na aplicação antiga que eu tinha. Posso continuar por este chamado e gerar os logs conforme sugestão ?

**Comment by danielbolognani** [comment]
Boa tarde @Adailton-lanca, pode ser por aqui mesmo, vou reabrir aqui enquanto isso. Por favor gerar os logs com a extensão na versão 1.2.4
