### ISSUE TITLE
Erro ao executar SIGAADV via Debug

### ISSUE THREAD

**Issue by fabiano-manhaes** [totvs/tds-vscode#714]
Bom tarde,

Prezados, ao tentar chamar a função SIGAADV pelo Debug do VsCode, a seguinte mensagem aparece: "Application Server
Failed to load APPMAP - Environment VV7JMP_DEV_CMP - File c:\Totvs\vv7jmp_dev\apo_cmp\tttp120.rpo".
Poderiam me ajudar a resolver este problema?

Atenciosamente,
Fabiano G. Manhães

**Comment by lwtnb-wrk** [comment]
@fabiano-manhaes Favor ver em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by lwtnb-wrk** [comment]
@fabiano-manhaes Geramos e estamos testando a versão pre release 1.2.5 com a correção desse problema.
Se quiser/puder testar e validar a correção, instale o VSIX que está disponivel em 
https://github.com/totvs/tds-vscode/releases/tag/v1.2.5
Para instalar o VSIX entre no VS Code na aba de extensões, clique em "..." > "Instalar de VSIX"

**Comment by gabrielhklok** [comment]
A correção deste problema fez com que a correção realizada na 1.2.4 voltasse a ocorrer.
