### ISSUE TITLE
Debug Linux não cria smartclient.ini temporário corretamente

### ISSUE THREAD

**Issue by ronrodrigues** [totvs/tds-vscode#717]
Problema ocorre ao tentar debugar no VSCode no Linux. Pelo que parece ele não cria corretamente os arquivos na pasta /tmp/.
Os mesmos seguem em anexo.

[informações do Protheus, VSCode e demais informações](https://github.com/totvs/tds-vscode/files/6720335/Principais.Dados.txt)
[smartclient.ini criado em /tmp/](https://github.com/totvs/tds-vscode/files/6720346/smartclient_user_ronilson_22454.ini.txt)
[Error Log do smartclient criado em /tmp/](https://github.com/totvs/tds-vscode/files/6720347/totvs_smartclient_error_log__-1.log)
![Versão da Extensão Usada
![Print Error](https://user-images.githubusercontent.com/42922200/123518729-98569800-d67d-11eb-9a5a-352c4ae2b8d8.png)
](https://user-images.githubusercontent.com/42922200/123518440-51b46e00-d67c-11eb-9a7c-326fc5fe734b.png)

**Comment by danielbolognani** [comment]
Bom dia @ronrodrigues, pelos arquivos enviado, parece que o VSCode está sem permissão para alterar os arquivos da pasta do smartclient. Verifique as permissões da pasta e garanta que o VSCode tenha permissão para acesso de escrita e leitura.
Se ainda assim não conseguir, favor gerar os logs como descrito em:
https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs

**Comment by lwtnb-wrk** [comment]
@ronrodrigues Nada relacionado com o problema informado, mas apenas uma informação referente ao AppServer, a versão 19.3.0.5 tem problemas conhecido na aplicação de patches então recomendamos atualizar para no mínimo a versão 19.3.0.6, mas se possível atualize para a última versão 19.3.1.7.

**Comment by ronrodrigues** [comment]
> 
> 
> @ronrodrigues Nada relacionado com o problema informado, mas apenas uma informação referente ao AppServer, a versão 19.3.0.5 tem problemas conhecido na aplicação de patches então recomendamos atualizar para no mínimo a versão 19.3.0.6, mas se possível atualize para a última versão 19.3.1.7.

Obrigado pela informação, estaremos providenciando atualização.

**Comment by ronrodrigues** [comment]
> 
> 
> Bom dia @ronrodrigues, pelos arquivos enviado, parece que o VSCode está sem permissão para alterar os arquivos da pasta do smartclient. Verifique as permissões da pasta e garanta que o VSCode tenha permissão para acesso de escrita e leitura.
> Se ainda assim não conseguir, favor gerar os logs como descrito em:
> https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs

Estarei verificando as informações de permissão de acesso, e retornarei.

**Comment by brodao** [comment]
Favor passar a acompanhar pelo chamado #726, pois trata-se de erro semelhante.
