### ISSUE TITLE
Não executa SmartClient - Debug VsCode

### ISSUE THREAD

**Issue by eduardofm1** [totvs/tds-vscode#719]
Bom dia pessoal, 

Após atualização do VsCode estou com problema ao tentar executar o Debug. 
Abaixo o que está acontecendo:
![image](https://user-images.githubusercontent.com/57256971/123650683-2eff9200-d801-11eb-9a6c-794f042d95dd.png)

Exclui o launch.json e o recriei , porém seu sucesso. 
Como ele está agora: 
![image](https://user-images.githubusercontent.com/57256971/123650836-56565f00-d801-11eb-9fa5-d1b38b14186f.png)

Olhei também alguns artigos, como mesmo problema como o https://github.com/totvs/tds-vscode/issues/339  e segui o passo a passo, porém meu caso parece ser outra coisa. 

Podem me ajudar ? 

Anexo aqui  o daplog.log para verificação. 
[daplog.log](https://github.com/totvs/tds-vscode/files/6726925/daplog.log)

Obrigado.

**Comment by DanielYampolschi** [comment]
Ola @eduardofm1 por favor atualize seu plugin. Esse problema ja foi identificado e corrigido. Obrigado.

**Comment by eduardofm1** [comment]
Bom dia @DanielYampolschi !
Estou na versão 1.2.5, não consegui encontrar versão mais recente. 
![image](https://user-images.githubusercontent.com/57256971/123652648-da5d1680-d802-11eb-8ad3-f4495aa28346.png)

Pode me ajudar ?

**Comment by DanielYampolschi** [comment]
@eduardofm1 voce esta com a versao correta.. estranho que voce esteja com esse problema.. Isso acontece chamando apenas a funçao SIGACTB ou qualquer outra, como a SIGAADV por exemplo?

**Comment by eduardofm1** [comment]
Qualquer função, estava tentando antes com SIGAMDI ou SIGAADV, vendo em posts parecidos tentei direto no módulo, mas também não deu!

**Comment by DanielYampolschi** [comment]
ok, obrigado. Vou te pedir outro teste por favor. Se voce executar sem ser em modo Debug (com CTRL+F5), qual o resultado?

**Comment by eduardofm1** [comment]
@DanielYampolschi consegui solucionar excluindo o token do meu usuário nesse ambiente e adicionado novamente. 
Teste agora tanto pelo F5 como pelo CTRL+F5 e funcionou , tanto SIGAADV como direto pelo módulo. 
Pode encerrar. Obrigado pela ajuda!

**Comment by DanielYampolschi** [comment]
legal, muito obrigado pelos testes e pela informação. Vamos verificar essa questão do token.
