### ISSUE TITLE
Comentar várias linhas do fonte

### ISSUE THREAD

**Issue by caiadofelipe** [totvs/tds-vscode#72]
Bom dia.

No TDS podíamos comentar várias linhas pressionando CTRL+/.
Teria como no VSCODE ter essa opção também? Isso facilita no desenvolvimento.

**Comment by luizhj** [comment]
o padrão de comentário no visual studio e no vscode é ctrl + K + C e para descomentar é ctrl + k + u.
Também serve para o sql management studio.
