### ISSUE TITLE
A correção deste problema fez com que a correção realizada na 1.2.4 voltasse a ocorrer.

### ISSUE THREAD

**Issue by gabrielhklok** [totvs/tds-vscode#721]
A correção deste problema fez com que a correção realizada na 1.2.4 voltasse a ocorrer.

_Originally posted by @gabrielhklok in https://github.com/totvs/tds-vscode/issues/714#issuecomment-870044121_

**Comment by danielbolognani** [comment]
Boa tarde @gabrielhklok, de qual problema estamos falando? Na 1.2.4 foi apenas correção em cima de aplicação de patch.

**Comment by gabrielhklok** [comment]
Sim, mas ao atualizar para versão 1.2.5, o problema que existia na 1.2.3 corrigido na 1.2.4, voltou.

**Comment by danielbolognani** [comment]
Então, o problema que estamos falando é da aplicação de patch?
Qual mensagem de erro que apresenta para vc? Consegue gerar os logs? 
https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs

**Comment by gabrielhklok** [comment]
O erro não permanece, algo deve ter ficado "desatualizado" em minha base. De qualquer forma agradeço a atenção, obrigado.
