### ISSUE TITLE
Erro de Compilação do APH

### ISSUE THREAD

**Issue by Smmartinez** [totvs/tds-vscode#722]
Bom dia!
Estou com um erro de compilação no fontes aph.
Alguns fontes deram erro de Syntax Error em outros deram o erro C2002  Statement unterminated at end of line/unbalanced parentesis/brackets

Estou na versão 1.2.5 do TDS
AppServer:
***  TOTVS S/A  ***
***  www.totvs.com.br  ***
* TOTVS - Build 7.00.191205P - May 22 2021 - 12:42:55
* Build: 64 bits
* SVN Revision: $WCRANGE$
* Build Version: 19.3.1.7
![compilacaoaph](https://user-images.githubusercontent.com/4532855/123798259-629ff200-d8bd-11eb-9dd1-9c59db36b576.png)

Não sei se tem a versão mas atualizei os includes que estão disponível no portal.

**Comment by Smmartinez** [comment]
O problema não é com o includes, voltei para o include anterior e recompilei o fonte e o erro ocorre.

**Comment by danielbolognani** [comment]
Bom dia @Smmartinez consegue passar para gente esse arquivo que acontece erro de compilação?

**Comment by Smmartinez** [comment]
[Help.zip](https://github.com/totvs/tds-vscode/files/6733638/Help.zip)
Segue

**Comment by danielbolognani** [comment]
Boa tarde @Smmartinez, o erro apresentado é devido ao terminador de linha desses arquivos estarem em padrão UNIX (apenas LF ou 0x10). Mude o padrão para Windows (CRLF ou 0x13 e 0x10) que tudo deve ser resolvido.
