### ISSUE TITLE
Aplicação de Patch

### ISSUE THREAD

**Issue by WMaxxxx** [totvs/tds-vscode#723]
Boa tarde pessoal,

O VS agora está nessa de dar essa mensagem ao aplicar qualquer pacote, ou seja, não consigo aplicar com essa jossa!

Agora tá falando de uma pasta: "tmptdsvmtotvs", aí eu vou lá e colocar a patch dentro dela mas mesmo assim a patch não vai nem por decreto.

Poderiam me ajudar nessa?

Anexei print do "erro".

Grato.
![2021-06-29_12-44-43](https://user-images.githubusercontent.com/86680479/123840712-0c46a980-d8e5-11eb-87ec-e4b01934ac4c.jpg)

**Comment by lwtnb-wrk** [comment]
@WMaxxxx Qual a build exata do AppServer que voce esta usando?

**Comment by WMaxxxx** [comment]
Opa,

Boa tarde!

Informações do AppServer
	
Tipo do servidor	Console
AppServer Build	7.00.191205P-20200629
Appserver Version	19.3.0.5
Servidor 64 bits	Sim
Servidor Unix		Não

Grato.

**Comment by lwtnb-wrk** [comment]
@WMaxxxx Atualize para o 19.3.0.6 ou melhor ainda se for para o 19.3.1.7, que o problema esta no AppServer de versão 19.3.0.5 ou anteriores.

**Comment by WMaxxxx** [comment]
Perfeito meu caro!

Vou baixar os pacotes e proceder com a atualização!

Muito obrigado na agilidade em ajudar!

Abraço!
