### ISSUE TITLE
DEBUG VSCode Linux e AppServer Windows

### ISSUE THREAD

**Issue by gabrielhklok** [totvs/tds-vscode#726]
O servidor está em uma máquina Windows 10, e o VSCode está no Linux Debian 10.
Dito isso vamos ao cenário, consigo compilar, aplicar path, etc... Normalmente pelo VSCode (que está no linux).
Se eu usar o SmartClient (que também está no linux) consigo acessar normalmente o sistema.
O problema acontece se eu tento debugar um fonte nesse cenário, VSCode linux e servidor no windows.

**VSCode:***
- VSCode: 1.57.1
- TDS-VSCode: 1.3.0

**Desktop (VS Code):**
 - OS/Architecture: Linux Debian 10

**Appserver:**
 - Build: 7.00.191205P-20210114 - 64 bits
 - OS/Architecture: Windows 10
 - Build Version 19.3.1.5

**Logs:**
[dap.log](https://github.com/totvs/tds-vscode/files/6737191/dap.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/6737192/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/6737193/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/6737194/totvsls_out.log)

**Comment by danielbolognani** [comment]
Bom dia @gabrielhklok, pelos Logs vc está utilizando o Smartclient em uma pasta com letras maiúsculas (rrConsultoria). No Linux temos limitações e as pastas devem ser todas em lowercase e sem espaços. Verifique se isso resolve o seu problema.

**Comment by gabrielhklok** [comment]
> Bom dia @gabrielhklok, pelos Logs vc está utilizando o Smartclient em uma pasta com letras maiúsculas (rrConsultoria). No Linux temos limitações e as pastas devem ser todas em lowercase e sem espaços. Verifique se isso resolve o seu problema.

Infelizmente não resolveu, segue o log da tentativa de depuração com os caminhos em *lowercase*.

[dap.log](https://github.com/totvs/tds-vscode/files/6740921/dap.log)

**Comment by lwtnb-wrk** [comment]
@gabrielhklok Pelos logs aparentemente ocorre erro de conexão com o AppServer.
Poderia tentar o seguinte?
- Desconectar do AppServer
- Conectar novamente do AppServer (não utilizar o reconectar), informando novamente usuario/senha
Tentar depurar novamente

**Comment by gabrielhklok** [comment]
> @gabrielhklok Pelos logs aparentemente ocorre erro de conexão com o AppServer.
> Poderia tentar o seguinte?
> 
>     * Desconectar do AppServer
> 
>     * Conectar novamente do AppServer (não utilizar o reconectar), informando novamente usuario/senha
>       Tentar depurar novamente

Na verdade nunca uso o reconectar kkkk, inclusive fiz testes de recriar conexões, limpar tokens...

De qualquer forma, fiz o teste e o problema permanece.

**Comment by delsonfilho** [comment]
Bom dia! @lwtnb-wrk, esse problema só ocorre na versão 1.3.0, fiz o update do plugin para essa versão e qualquer debug diz que não foi possível se conectar ao appserver, voltei para 1.2.5 e voltou a funcionar.

**Comment by gabrielhklok** [comment]
Bom dia!

Vamos por partes.

- @danielbolognani realmente o problema do nome estava atrapalhando, corrigi.
- @delsonfilho e @lwtnb-wrk após corrigir a questão acima, fiz o teste com a versão 1.2.5 e funcionou perfeitamente, porém na 1.3.0 o erro persiste.

Sendo assim, temos um problema de debug para corrigir na versão nova.

**Comment by lwtnb-wrk** [comment]
@gabrielhklok Grato pelas informações. Vamos avaliar o que pode ter ocorrido.

**Comment by Felipe-Raposo** [comment]
> Bom dia @gabrielhklok, pelos Logs vc está utilizando o Smartclient em uma pasta com letras maiúsculas (rrConsultoria). No Linux temos limitações e as pastas devem ser todas em lowercase e sem espaços. Verifique se isso resolve o seu problema.

@danielbolognani, esse problema de aceitar somente letras minúsculas no Linux é algo que será corrigido também?

**Comment by danielbolognani** [comment]
O problema de aceitar apenas letras minúsculas está mais para o appserver do que para a extensão. Verifique em: https://tdn.totvs.com/pages/viewpage.action?pageId=189317255

**Comment by fa6ricio** [comment]
Uso o TDS no linux a muito tempo, estou com o mesmo problema no versão nova  1.3.0 não conecta por nada para depuração na versão 1.2.5 está normal.

**Comment by lkznogueira** [comment]
Estou com este msm problema no MacOs.. Até tinha aberto uma issue mas pelo visto mac/linux estão com msm problema.

**Comment by delsonfilho** [comment]
Bom dia.

Jà há uma data para liberar a correção?

**Comment by ricardomansano** [comment]
Dia @delsonfilho , testa esse cara, vou testar daqui a pouco
https://github.com/totvs/tds-vscode/releases/tag/v1.3.1

**Comment by ricardomansano** [comment]
@delsonfilho , aqui consegui debugar, depois testa pra gente pfv
![image](https://user-images.githubusercontent.com/33813921/124271792-45189580-db14-11eb-89da-b0f3d83939b5.png)

**Comment by fa6ricio** [comment]
Por segurança vou esperar sair como release oficial pra atualizar!

**Comment by delsonfilho** [comment]
@ricardomansano realizei os testes de debug e funcionou normalmente.

Correção validada!

**Comment by lwtnb-wrk** [comment]
@delsonfilho Grato pelos testes. Em breve publicaremos a correção no Marketplace
