### ISSUE TITLE
falso warning no linter

### ISSUE THREAD

**Issue by likid** [totvs/tds-vscode#727]
**Describe the bug**
Existe um warning de variável não utilizada que sempre ocorria na compilação e agora também ocorre no linter porém a variável é utilizada. Se o valor for atribuído após a declaração, aí a variável é considerada como utilizada.

**To Reproduce**
Declarar uma variável caracter.
Utilizar a variável com macrosubstituição.

**Expected behavior**
Não ocorrer o warning.

**Screenshots**
![image](https://user-images.githubusercontent.com/10984007/123955841-76f8f300-d980-11eb-95e4-463bac33e146.png)

**Comment by ricardomansano** [comment]
Bom dia,

Favor abrir um chamado convencional, teremos que passar essa situação ao time do AppServer, pois este é um problema no pre-compilador

**Comment by likid** [comment]
@ricardomansano mas ele ocorre no linter também, o linter está utilizando o pré-compilador para fazer as validações?

**Comment by ricardomansano** [comment]
Sim, o pré-compilador é parte do processo do linter, e nao pode ser diferente, ja que qqer novo comportamento aplicado ao compilador oficial deve ser replicado ao Lint tbem
