### ISSUE TITLE
Error(-1) Falha ao iniciar o smartclient. Command:

### ISSUE THREAD

**Issue by Adailton-lanca** [totvs/tds-vscode#728]
Ao tentar executar debugando em uma estação de PDV (front loja), ocorre a mensagem abaixo:

Error(-1) Falha ao iniciar o smartclient. Command:
c:\caixa06\protheus\bin\smartclient_32\samrtclient.exe -DEBUG=1852 -C=DBG_TEMP "-E=MP11PDV2" "-P=sigamdi" -M -A= < -a=nill -A=>
![ErroVscode](https://user-images.githubusercontent.com/64661146/123967086-5f276c00-d98c-11eb-9910-5106b7c1e9c8.png)

**Comment by danielbolognani** [comment]
Bom dia @Adailton-lanca, por favor apague os argumentos do launch.json (abaixo do "lastPrograms"), deixe assim:
"args": [],

**Comment by Adailton-lanca** [comment]
O erro continuou e eu apaguei o <nil> do description, mas continua, conforme abaixo:
"lastPrograms": [
		{
			"label": "sigamdi",
			"description": "<nil>"
		},
		{
			"args": [],
			"label": "sigamdi",
			"description": " < nil >"
		}
![image](https://user-images.githubusercontent.com/64661146/123970811-d9a5bb00-d98f-11eb-9104-8d10bb7c418a.png)

**Comment by Adailton-lanca** [comment]
O problema são os parametros passados, mas, como estou utilizando estação PDV, eu preciso informa-los como orientação abaixo:
https://centraldeatendimento.totvs.com/hc/pt-br/articles/235075208-MP-TOTVS-PDV-Desvendando-o-TOTVS-PDV

**Comment by Adailton-lanca** [comment]
Meu parametros atuais para o smartclient são estes:
C:\CAIXA06\Protheus\bin\smartclient_32\smartclient.exe -P=SIGAFRT -E=MP11PDV -C=TCP -A= -A=006 -M

**Comment by lwtnb-wrk** [comment]
@Adailton-lanca Experimente então adicionar o argumento requerido

"args": [ "006" ],

Se ainda assim o problema persistir veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise

**Comment by lwtnb-wrk** [comment]
@Adailton-lanca Qual a versão de seu tds-vscode?

**Comment by Adailton-lanca** [comment]
Bom dia.
Versao Maio 2021 / 1.57.1
Sds,
Adailton

De: lwtnb-wrk ***@***.***>
Enviada em: sexta-feira, 2 de julho de 2021 09:15
Para: totvs/tds-vscode ***@***.***>
Cc: Adailton Lança ***@***.***>; Mention ***@***.***>
Assunto: Re: [totvs/tds-vscode] Error(-1) Falha ao iniciar o smartclient. Command: (#728)


@Adailton-lanca<https://github.com/Adailton-lanca> Qual a versão de seu tds-vscode?

**Comment by lwtnb-wrk** [comment]
@Adailton-lanca Qual a versão da extensão instalada?
Você chegou a adicionar os argumentos no launch.json conforme orientamos?

**Comment by Adailton-lanca** [comment]
A versão da extensão é 1.2.1.
Sim, adicionei os argumentos mas o erro continuou.


@Adailton-lanca<https://github.com/Adailton-lanca> Qual a versão da extensão instalada?
Você chegou a adicionar os argumentos no launch.json conforme orientamos?

**Comment by lwtnb-wrk** [comment]
@Adailton-lanca Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.
Em especial o dap.log pois trata-se problema ao iniciar o smartclient.

**Comment by caarolbritto** [comment]
Boa tarde! Estou com um erro parecido. Alguém pode me ajudar? 
![falha ao iniciar o smartclient](https://github.com/totvs/tds-vscode/assets/99297825/aded9dd8-9fac-40b0-8048-ee7e593bfaaf)

**Comment by lwtnb-wrk** [comment]
@caarolbritto Essa issue está fechada a muito tempo e o erro pode não ter relação com essa issue antiga.
Favor abrir uma nova issue com o máximo de detalhes possíveis como, em que situação ocorreu? Execução de programa ou depuração? 
Se possível, já adicione os logs gerados por https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs
