### ISSUE TITLE
Erro Linter

### ISSUE THREAD

**Issue by HTM-Felipe** [totvs/tds-vscode#729]
Ao abrir um fonte, o Linter acusa o seguinte erro na primeira linha do código..

**is empty or corrupted..**

Já realizamos a configuração dos includes para ter certeza que não havia nenhum problema, porém o erro persiste.
![image](https://user-images.githubusercontent.com/69156392/123978847-9438bc00-d996-11eb-8b5a-ba3e8083cc03.png)

É necessário realizar alguma configuração adicional para remover esse erro?

**Comment by lwtnb-wrk** [comment]
@HTM-Felipe Ao tentar compilar esse fonte, ele compila corretamente?
Poderia anexar o fonte aqui na issue?

**Comment by HTM-Felipe** [comment]
@lwtnb-wrk o fonte é compilado sem problemas, porém, qualquer alteração realizada ele acusa o mesmo erro.

Infelizmente não posso anexar o fonte, mas o problema não ocorre em apenas com um único fonte, todos nossos fontes estão apresentando a mensagem de erro.

![lint-vscode](https://user-images.githubusercontent.com/69156392/123995852-1d56ef80-d9a5-11eb-8eb8-01a9e9bf085e.png)

**Comment by danielbolognani** [comment]
@HTM-Felipe, por curiosidade, esse seu fonte possui em algum ponto BeginContent e EndContent?
Se sim, é um problema que já está mapeado e será corrigido na próxima versão.

**Comment by marcosnataqs** [comment]
> @lwtnb-wrk o fonte é compilado sem problemas, porém, qualquer alteração realizada ele acusa o mesmo erro.
> 
> Infelizmente não posso anexar o fonte, mas o problema não ocorre em apenas com um único fonte, todos nossos fontes estão apresentando a mensagem de erro.
> 
> ![lint-vscode](https://user-images.githubusercontent.com/69156392/123995852-1d56ef80-d9a5-11eb-8eb8-01a9e9bf085e.png)

Estou com mesmo erro em todos os fontes do workspace.

**Comment by HTM-Joaquim** [comment]
Boa tarde @danielbolognani. Conforme informamos anteriormente o problema não ocorre somente com um fonte, mas com todo e qualquer fonte aberto no workspace. O erro é apresentando ja na primeira linha informando que o arquivo pode estar corrompido ou vazio.

Cheguei a desinstalar a extensão e instalar novamente, e o mesmo erro é apresentado. 

A princípio achei que o problema fosse na configuração do vscode  ou alguma outra extensão. Portanto tentei instalar a extensão novamente em um ambiente novo, e também tentei limpar o arquivo setting.json do vscode, ambas as tentativas sem sucesso.

Nenhuma das tentativas obtive sucesso.

**Comment by danielbolognani** [comment]
@HTM-Felipe o problema está no espaço que existe no seu path (my projects), já identificamos aqui o problema e a próxima versão terá a correção. Se quiser utilizar enquanto isso, apenas renomeei a pasta e retire o espaço do seu path.

**Comment by lwtnb-wrk** [comment]
@HTM-Joaquim e @marcosnataqs Reproduzimos o problema e trata-se do espaço no caminho do fonte.
Por favor eliminem os espaço/acentuação por enquanto, por exemplo "my project" > "myproject"
Já estamos trabalhando na correção.
Grato pelas informações.

**Comment by lwtnb-wrk** [comment]
@HTM-Joaquim e @marcosnataqs Já estamos testando a correção, se quiserem ajudar com o teste e instalar a v1.3.1 e confirmar que o problema foi resolvido, peguem o VSIX em:
https://github.com/totvs/tds-vscode/releases/tag/v1.3.1
Se não souberem como instalar pelo VSIX veja em https://github.com/totvs/tds-vscode/blob/master/docs/install.md
Valeu!

**Comment by HTM-Joaquim** [comment]
@lwtnb-wrk Efetuei os testes, e o problema do espaçamento no caminho da pasta aparentemente foi resolvido. 

Continuarei testando, e comunicarei caso encontre algo fora do comum.

**Comment by lwtnb-wrk** [comment]
@HTM-Joaquim Grato pelos testes. Em breve publicaremos a correção no Marketplace.

**Comment by Elcymerson** [comment]
Eu estava na versão 1.3.0 e o erro ocorria também para os includes, ainda que não houvesse espaço no caminho: C:\TOTVS\include. Apliquei a 1.3.1 e a mensagem não aparece mais.
Obrigado!!
