### ISSUE TITLE
Inspetor de funções não mostra o arquivo

### ISSUE THREAD

**Issue by likid** [totvs/tds-vscode#73]
O inspetor de funções mostra apenas a lista de funções, mas não mostra em que arquivo fonte está escrita a função.
Poderiam mostrar o fonte ao lado em parênteses e com o número da linha se for possível saber Ex: U_MINHAFUNCAO (MEUFONTE.PRW:10)

**Comment by matheus-sales** [comment]
Correção efetuada, estará disponível na próxima versão
