### ISSUE TITLE
Não consigo excluir pontos de entradas do RPO

### ISSUE THREAD

**Issue by Rmkodama** [totvs/tds-vscode#730]
Boa tarde!

Sempre utilizei o caminho clicar no mouse com botão direito no Totvs:Server e seleciono  Delete File/Resource from RPO.
Em vez de descompilar o programa, abre uma pasta Delete File from RPO. com o procedimento que é o procedimento que estou fazendo.
Deleting source/resource from RPO
In order to delete a source/resource from RPO follow these steps:
Find source/resource in workspace;
Select source/recourse with rigth mouse buttom;
Select the option 'Delete source/resource from RPO' on popup menu;
Confirm file deletion selecting the option 'YES' in the form displayed on the bottom right corner..

**Comment by Rmkodama** [comment]
complementando, consigo compilar, aplicar patch normalmente e debugar normalmente

**Comment by lwtnb-wrk** [comment]
@Rmkodama Qual o erro que está aparecendo?
Em quaisquer fontes ocorre isso, ou em alguns especificamente?
Você quem criou esses fontes?
Qual a build exata do appserver e qual a lib utilizada?

**Comment by Rmkodama** [comment]
Não apresenta erro! conforme em vez de excluir abre um pasta Delete File from RPO. com o procedimento
são dois pontos de entradas MA330TRB e MA330SEQ
Fonte bem antigo
Sistema operacional: Windows Server 2016
Appserver version: 19.3.1.4
Build DBAccess: 20200606-20201110
Release do RPO:  12.1.025
Release do dicionário: 12.1.025
Local files: CTREE
Versão da Lib:20210405
Data da Lib: 20210408_143338

**Comment by Rmkodama** [comment]
boa noite!

Reiniciei o Servidor e voltou a funcionar corretamente
