### ISSUE TITLE
Debugar Mac OS  "It was not possible to connect the Application Server"

### ISSUE THREAD

**Issue by lkznogueira** [totvs/tds-vscode#731]
*** Esse problema só acontece com a ultima versao da extensão 1.3.0** com a versão 1.2.5 não acontece o problema abaixo.

Olá..

Estou usando a ultima versão do MacOs - Big Sur, fiz toda a instalação padrão do Vscode juntamente com a extensão .

Após abertura, fiz a adição de um servidor, conectei e consegui realizar as seguintes tarefas:

- Compilar Fontes
- Inspetor de Objetos

Porem quando clico para debugar um código fonte que ele vai abrir o smartclient ele me da essa msg abaixo

![image](https://user-images.githubusercontent.com/12913181/124041297-00d6a980-d9dd-11eb-9b8e-afdc095db553.png)

![image](https://user-images.githubusercontent.com/12913181/124041422-311e4800-d9dd-11eb-9a64-fe50aad2fb48.png)

Quando executo o smartclient sem ser via DEBUG, ele abre o client normal e me permite logar e utilizar.. Ele só da esse problema quando clico pra DEBUGAR.

![image](https://user-images.githubusercontent.com/12913181/124042257-d1c13780-d9de-11eb-8302-aace7e263a31.png)

**Comment by brodao** [comment]
Veja em [depurar](https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md) como fazer as configurações necessárias.

**Comment by lkznogueira** [comment]
@brodao Já corri esse documento e de nada me ajudou.. Conforme dito no inicio da postagem "Esse problema só acontece com a ultima versao da extensão 1.3.0 com a versão 1.2.5 não acontece o problema abaixo."  Ou sejá voltando a versão estou conseguindo debugar normalmente.

Dexei algo escapar do link q vc me enviou?

**Comment by brodao** [comment]
Favor passar a acompanhar o chamado #726 , pois é problema semelhante e já estamos trabalhando na resolução.
