### ISSUE TITLE
Ao atualizar o plugin para versão 1.3.1, passou a exigir a include prtopdef.ch

### ISSUE THREAD

**Issue by delsonfilho** [totvs/tds-vscode#733]
**Describe the bug**
Bom dia.
Ao atualizar o plugin para versão 1.3.1, passou a exigir a include prtopdef.ch, verificando os paths tanto dos fontes quanto das includes nao há letras maiusculas e nem espaços, exemplo: "/home/delson_filho/git/xxxx/include"

**To Reproduce**
1. Atualizar para versão 1.3.1
2. Abrir qualquer fonte que não tenha a include prtopdef.ch
3. Abrir vários fontes e no output mostrará que todos os fontes precisam da prtopdef.ch;

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/27447637/124277020-f5899800-db1a-11eb-9450-3535d89bb230.png)

**Desktop (please complete the following information):**
 - OS/Architecture: Ubuntu x64

**Appserver (please complete the following information):**
 - Build 7.00.191205P 2021-05-13
 - OS/Architecture: WINDOWS 2019
 - Build Version 19.3.1.7

**Additional context**

**Comment by danielbolognani** [comment]
@delsonfilho por favor apenas reinicie o VSCode, esse include sempre foi necessário. Pelo que vi aqui parece alguma falha ao carregar a pasta de includer assim que realiza a atualização da extensão.

**Comment by lwtnb-wrk** [comment]
@delsonfilho No Linux, todo o caminho precisa estar em letras minúsculas, não apenas a pasta de Includes
Troque o "Gestao_servico/Rotina" por "gestao_servico/rotina"
Lembrando que isso é um comportamento do AppServer [Convenção para nomenclatura de File System em ambiente Linux](https://tdn.totvs.com/pages/viewpage.action?pageId=189317255)

**Comment by delsonfilho** [comment]
@danielbolognani já reiniciei o VS, porém ele continua exigindo a include, se você testar na versão 1.2.5 perceberá que ele não exige.

**Comment by delsonfilho** [comment]
@lwtnb-wrk fiz o ajsute conforme solicitado /home/delson_filho/git/cliente/gestao_servico/rotinas/ATEC022.prw, porém veja que no VS continua solicitando a include:

![image](https://user-images.githubusercontent.com/27447637/124280529-2d92da00-db1f-11eb-9a76-4de73b1b43fc.png)

**Comment by danielbolognani** [comment]
@delsonfilho Vc tem esses arquivos na sua pasta include? Se vc compilar esse arquivo da o mesmo erro?

**Comment by delsonfilho** [comment]
@danielbolognani tenho sim, está junto com o projeto /home/delson_filho/git/cliente/include, testei aqui compilando sem inserir a prtopdef.ch e parou de mostrar a mensagem de erro.

**Comment by danielbolognani** [comment]
@delsonfilho a principio o processo de pré-compilação (que é onde aponta esse erro) é o mesmo tanto no Linter como na compilação de fato (ctrl-F9). Consegue mandar o seu servers.json e a lista de arquivos das suas pastas de include?

**Comment by lwtnb-wrk** [comment]
@delsonfilho Pegamos uma situação semelhante ao seu erro aqui, veja se é o seu caso também.
O Linter e a compilação no final usam o mesmo mecanismo para gerar os erros/warnings, porem o Linter usa a lista de includes gerais, pois o Linter não depende de um server conectado.
Quando você esta com um server conectado e manda compilar, se o server tiver uma configuração de includes dele, o server usa essa informação para compilar, então o fonte pode estar compilando normalmente e dando erro de Linter por causa da diferença de Includes.
Na visão de Servers, acione o menu de contexto e a opção Include ou acione CTRL + SHIFT + P e execute "TOTVS: Include", essa é a configuração que o Linter está usando então confirme se ela aponta para as pastas de Includes corretas.

**Comment by delsonfilho** [comment]
@lwtnb-wrk Estou apontando para a mesma pasta de include e mesmo assim ainda dá o erro da include.

**Comment by lwtnb-wrk** [comment]
@delsonfilho Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analises.

**Comment by danielbolognani** [comment]
@delsonfilho envia pra gente também o seu servers.json e se possível a lista de arquivos da sua pasta de includes:
entra na pasta de include pelo cmd e digita dir > arquivos.txt e anexa esse arquivos.txt aqui pra gente por favor

**Comment by delsonfilho** [comment]
[filenames.txt](https://github.com/totvs/tds-vscode/files/6765855/filenames.txt)
[servers (copy).txt](https://github.com/totvs/tds-vscode/files/6765863/servers.copy.txt)

Segue.

**Comment by lwtnb-wrk** [comment]
@delsonfilho Assim que conseguir gerar, nos envie os logs para analises então.

**Comment by delsonfilho** [comment]
Segue!

[totvsls.log](https://github.com/totvs/tds-vscode/files/6766055/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/6766057/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/6766058/totvsls_out.log)

**Comment by lwtnb-wrk** [comment]
@delsonfilho Grato pelos logs, mas o erro parou de ocorrer?
Pelos logs voce abriu 4 arquivos e em nenhum deles ocorreu o erro de prtopdef.ch.

**Comment by delsonfilho** [comment]
@lwtnb-wrk na verdade, qualquer fonte que abra, lá no output sempre mostra o erro, se eu recompilo, ele some. Mas se fechar e abrir de novo o vs, Volta o erro no output

**Comment by lwtnb-wrk** [comment]
@delsonfilho Revi os logs e eles mostraram apenas uns warnings e erros, mas nada referente ao prtopdef.ch
Se o problema aparecer apenas na abertura do tds-vscode com um fonte aberto, isso realmente pode exibir um erro na primeira linha que "some" ao abrir/fechar ou recompilar. Isso ocorre pois o Linter tentou efetuar o parser sem ter a informação de Includes. Isso ja esta sendo corrigido e deve sair na proxima atualizacao.
Nesse logs enviado vejo apenas a abertura do tds-vscode, aparentemente sem nenhum fonte aberto no editor, seguido da reconexão a um appserver. Depois ao abrir os fontes ATEC023.prw ele acusou um simples warning, assim como no RTEC014.prw. O RFAT006.prw não apresentou nenhum problem e o FAPPMOBI.tlpp apresentou erro de variavel não local usada em um loop For. E nesse log não mostrou que houve a recompilação.
Então se puder refazer os testes, reinicie o tds-vscode e efetue as operações na ordem que apresentem o problema seguido da recompilação que remove o problema. 
Caso contrario aguarde a nova atualizacao para ver se ela resolve seu problema, pois aqui nao conseguimos reproduzir o problema.

**Comment by delsonfilho** [comment]
@lwtnb-wrk Como não é impeditivo e tem como contornar, vou aguardar a proxima atualização.

**Comment by ClodoaldoRibeiro** [comment]
Olá bom dia, também na empresa que trabalho estamos sofrendo com o erro descrito pelo colega. Todo fonte que abro ele mostra o erro, mas quando compilo o erro desaparece.

![tds](https://user-images.githubusercontent.com/15166265/125295698-dc8f9c80-e2fb-11eb-9a92-d65f56e6464a.png)

**Comment by lwtnb-wrk** [comment]
@ClodoaldoRibeiro Veja a configuração de Linter em https://github.com/totvs/tds-vscode/blob/master/docs/linter.md

**Comment by lwtnb-wrk** [comment]
Estamos testando uma nova versão onde alteramos os processos de carga de includes para o Linter.
Se puderem/quiserem avaliar a alteração, baixe o VSIX em https://github.com/totvs/tds-vscode/releases/tag/v1.3.2
Para instalar veja https://github.com/totvs/tds-vscode/blob/master/docs/install.md

**Comment by ClodoaldoRibeiro** [comment]
OK, @thiagoasw refiz as configurações e deu certo, obrigado.

**Comment by danielbolognani** [comment]
Problema corrigido na versão 1.3.2 que já foi expedido ao MarketPlace.
