### ISSUE TITLE
Erro ao tentar compilar fonte

### ISSUE THREAD

**Issue by SabrinaKaren** [totvs/tds-vscode#736]
Instalei o plugin na minha IDE, conectei e autentiquei um usuário, tudo feito com sucesso.
Ao tentar compilar meu fonte, a seguinte mensagem é exibida: "**Start build error: Server returned: Cannot open RPO File. Check file access permissions / Read-Only status. It wasn't possible to obtain exclusive access to the objects repository**".
Eu sei que esta mensagem é padrão para quando o repositório está sendo utilizado, e que a primeira recomendação é derrubar todos os acessos. Eu fiz exatamente isso... abri o Monitor e derrubei todos os usuários, para garantir que o repositório não estará sendo utilizado por ninguém. Mesmo assim o erro procede.
Minha segunda tentativa foi reiniciar o servidor... mas o erro continuou.
O servidor que eu estou tentando acessar está na cloud da totvs e é de teste/dev.
Eu abri um chamado junto ao portal do cliente da TOTVS reportando meu erro, mas eles me orientaram a abrir uma issue por aqui.
Então gostaria de saber se tem alguém que possa me ajuda com este erro de compilação.

**Comment by brodao** [comment]
Ola @SabrinaKaren 

Verifique se você tem privilégios do sistema operacional para acessar o arquivo RPO e se este não está como *read only*. 

Detalhes em:
https://centraldeatendimento.totvs.com/hc/pt-br/articles/360019473052-MP-ADVPL-ERRO-IT-WASN-T-POSSIBLE-TO-OBTAIN-EXCLUSIVE-ACCESS-TO-THE-OBJECTS-REPOSITORY

A disposição.

**Comment by SabrinaKaren** [comment]
Olá @brodao, agradeço pela resposta! Mas inclusive eu já usei este link como referência e compartilhei com o pessoal da totvs. Como que eu consigo ver os privilégios de acesso sendo que o servidor está na cloud?

**Comment by brodao** [comment]
Como seu ambiente esta no cloud, tem que entrar em contato com eles, pois há restrições de acesso.

Clientes TCloud : Os ambientes que estão no TCloud em produção são bloqueados para depuração/atualização. Promova o RPO para DEV e use esse ambiente, e se necessário, promova-o de volta para produção. Para detalhes, entre em contato com o suporte do TCloud.

**Comment by danielbolognani** [comment]
@SabrinaKaren Isso também pode ocorrer se tiver algum job rodando no appserver. Pede para adicionarem a chave BUILDKILLUSERS=1 no GENERAL do appserver.ini. De qualquer forma, por aqui a gente não tem ação, se precisar pode reabrir o chamado com eles e pode falar que nós que recomendamos, inclusive pode passar meu contato no chamado (daniel.bolognani).
