### ISSUE TITLE
Erro ao tentar aplicar patch 

### ISSUE THREAD

**Issue by ederneo** [totvs/tds-vscode#737]
Ao tentar aplicar um patch a seguinte mensagem é apresentada.

"One or more validations errors detected:
The following patch(es) contains at least one upper case character,
which is not allowed for unix base systems:

Já foi tratado anteriormente, mas parece que voltou a apresentar na versão 1.31

![Captura de Tela 2021-07-05 às 17 12 34](https://user-images.githubusercontent.com/37152616/124515135-140ac000-ddb5-11eb-8e6e-c0d7f57e3466.png)
![Captura de Tela 2021-07-05 às 17 12 49](https://user-images.githubusercontent.com/37152616/124515138-153bed00-ddb5-11eb-98c9-8eac3c00b43e.png)
![Captura de Tela 2021-07-05 às 17 13 11](https://user-images.githubusercontent.com/37152616/124515141-15d48380-ddb5-11eb-9d47-f46f46f6e2f1.png)
![Captura de Tela 2021-07-05 às 17 16 10](https://user-images.githubusercontent.com/37152616/124515144-166d1a00-ddb5-11eb-93e5-a41dc4ce04ca.png)
![Captura de Tela 2021-07-05 às 17 19 53 (2)](https://user-images.githubusercontent.com/37152616/124515219-3d2b5080-ddb5-11eb-9c5a-799fcaa4a520.png)

**Comment by lwtnb-wrk** [comment]
@ederneo Já estamos removendo essa validação. Estará disponível na próxima atualização.

**Comment by lwtnb-wrk** [comment]
@ederneo Estamos testando a correção onde removemos essa validação obrigatória. 
Se puder validar, baixe o VSIX em https://github.com/totvs/tds-vscode/releases/tag/v1.3.2
Para instalar veja https://github.com/totvs/tds-vscode/blob/master/docs/install.md

**Comment by ederneo** [comment]
Boa noite Validado. 

Obrigado

<img width="1131" alt="Captura de Tela 2021-07-13 às 22 47 55" src="https://user-images.githubusercontent.com/37152616/125548324-a92e49f8-da83-4364-9bc3-5fb8032ea1b7.png">

**Comment by lwtnb-wrk** [comment]
@ederneo Grato pela confirmação
