### ISSUE TITLE
Versão 1.3.1 inicia o debugAdapter ocupando 12 Gb no MacOS Catalina 10.15.7

### ISSUE THREAD

**Issue by emebatista** [totvs/tds-vscode#738]
**Describe the bug**
Ao executar a função debug do VScode com a versão 1.3.1 do plugin, a memória em pouco tempo ocupa muitos Gb de memória, praticamente congelando o computador.

**To Reproduce**
Clicar em F5 para debugar.

**Expected behavior**
Comportamento típico de debug.

**Screenshots**

**Desktop (please complete the following information):**
 - OS/Architecture: MacOS Catalina 10.15.7

**Appserver (please complete the following information):**
 - Build (with date): 7.00.191205P-20210114 
 - OS/Architecture: MacOS Catalina 10.15.7 64 bits
 - Build Version 7.00.191205P

**Additional context**
![image](https://user-images.githubusercontent.com/48991443/124594937-c2a31500-de36-11eb-994b-c249070eb981.png)
![image](https://user-images.githubusercontent.com/48991443/124595376-54ab1d80-de37-11eb-8c5a-272ff56fe0ce.png)

**Comment by DanielYampolschi** [comment]
bom dia @emebatista, o processo chega a parar em algum breakpoint, ou isso acontece log apos lançar o SmartClient em modo de debug e mesmo sem nenhuma parada a memória do debugAdapter sobe?

**Comment by danielbolognani** [comment]
@emebatista Pode por favor gerar os logs de debug também?
https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs

**Comment by emebatista** [comment]
Bom dia, Daniel, tudo bem?
O processo não estava em nenhum breakpoint. Eu estava usando o SmartClient para acessar uma rotina padrão. Depois de alguns minutos percebi a máquina lenta e fui verificar a memória, que deu os 12 Gb. Assim que consegui finalizar o VSCode a memória liberou. Agora voltei para a versão 1.2.1 que não apresenta esse comportamento. Eu já havia tentado a 1.3.0 e tinha ocorrido o mesmo. Então esperei sair a 1.3.1, porém aconteceu de novo.

**Comment by DanielYampolschi** [comment]
ok @emebatista muito obrigado pelas informações, vamos verificar por aqui e qualquer coisa te pedimos mais testes.

**Comment by delsonfilho** [comment]
Boa tarde.

Isso acontece também no Linux (Ubuntu), já chegou a ocupar 100% da memória, tive que dar o kill no processo, mas isso só acontece que ficar debugando várias vezes.

**Comment by mmateusmedeiros** [comment]
![image](https://user-images.githubusercontent.com/8399045/125514995-8ecf215f-3cc3-4a4f-831b-5ebcb6e44c2a.png)

Estou com o mesmo problema relatado no ubuntu e mac os no Windows 10.  Ao lançar o debugerAdapter o smartclient não inicializa.

**Comment by lwtnb-wrk** [comment]
@mmateusmedeiros Acredito que seja outra questão. No Ubuntu e Mac OS estao apontando o alto consumo de memoria.
Abra uma issue em separado e adicione o maior numero de informacoes possiveis e tambem os logs do dap. 
Veja https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs

**Comment by DanielYampolschi** [comment]
@emebatista Reforço a solicitação do Daniel e do Leo, por favor gere os logs conforme o link abaixo. Até o momento não conseguimos reproduzir o problema e o log pode nos direcionar melhor. Obrigado.

https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs

**Comment by emebatista** [comment]
Oi, Daniel, tudo bem? O erro é intermitente. E depois que atualizei para o 1.3.2 ainda não aconteceu. Vou deixar ativo aqui o log para enviar.  Peço desculpas pela demora.

**Comment by DanielYampolschi** [comment]
Muito obrigado @emebatista , realmente... esses problemas intermitentes são bem chatos de investigar... como te falei, por aqui ainda não conseguimos reproduzir tb... Fico aguardando sua comunicação então caso consiga reproduzir.
Mas te peço atenção a um detalhe, o log "dap.log" é reinicializado toda vez que você começa um novo debug, então te peço pra salvar o arquivo assim que o problema ocorrer ok?
Obrigado mais uma vez.

**Comment by danielbolognani** [comment]
Boa tarde, disponibilizamos uma correção em pré-release:
https://github.com/totvs/tds-vscode/releases/tag/v1.3.3
Nossa previsão é subir oficialmente no MarketPlace semana que vem.

**Comment by danielbolognani** [comment]
Boa tarde, liberamos essa semana a versão 1.3.3 e tiveram algumas melhorias para diminuir consumo de memória, caso volte a acontecer favor reabrir a issue.
