### ISSUE TITLE
Erro na aplicação de Patch em MacOS Catalina

### ISSUE THREAD

**Issue by emebatista** [totvs/tds-vscode#739]
Prezados,

Estou usando a versão 10.15.7 (19H1217) do MacOS Catalina. Fui aplicar um patch usando a versão 1.3.1 do plugin e precisei voltar para o 1.2.1.

O caminho do patch foi /Users/emebatista/Downloads/lib.ptm
Vejam que o U e o D são de pastas padrões do MacOS. 

Porém, ocorre o erro abaixo:

One or more validations errors detected:
The patch contains at least one upper case character,
which is not allowed for unix base systems:

/Users/emebatista/Downloads/lib.ptm;

**Comment by lwtnb-wrk** [comment]
@emebatista Favor acompanhar pela #737
