### ISSUE TITLE
Estrutura do fonte (Outline)

### ISSUE THREAD

**Issue by guilhermebigois** [totvs/tds-vscode#74]
No TOTVS Developer Studio 11.3 temos a visão Estrutura dentro da Perspectiva Plataforma TOTVS.

Seria possível habilitar essa opção na extensão?

![image](https://user-images.githubusercontent.com/22408258/59125020-88a17500-8937-11e9-9cd1-6cf04ce7149c.png)

**Comment by lwtnb-wrk** [comment]
@guilhermebigois Sabemos da importancia desta funcionalidade e ela ja estava no planejamento. Estamos trabalhando nisso mas ainda sem previsão para liberar, ok?

**Comment by ricardomansano** [comment]
Essa implementação depende da criação do nosso motor de parser que foi prorrogada para o primeiro semestre de 2020, manteremos os canais informados quando da liberação.
