### ISSUE TITLE
Running the contributed command: 'tds-monitor.open-monitor-view' failed.

### ISSUE THREAD

**Issue by HTM-Joaquim** [totvs/tds-vscode#740]
**Describe the bug**
Tentar abrir o Monitor-TDS após ter fechado uma instância do mesmo, causa erro e é necessário abrir o Workspace novamente para conseguir utiliza-lo.

**To Reproduce**
1. Abrir Projeto
2. Conectar a um servidor ativo
3. Abrir o Monitor 
4. Fechar o Monitor e tentar abri-lo novamente

**Expected behavior**
Abertura do monitor 

**Screenshots**
![image](https://user-images.githubusercontent.com/69199727/124785207-0bcd9480-df1d-11eb-86f3-f0ff5cbbbdae.png)

**Desktop:**
 - OS/Architecture: Windows 10 Pro 64 bits

**Comment by lwtnb-wrk** [comment]
@HTM-Joaquim Grato por avisar. Iremos avaliar o que está ocorrendo.

**Comment by DanielYampolschi** [comment]
Ola @HTM-Joaquim reforçando o comentário do @leowww , obrigado por avisar, o problema foi identificado, corrigido e estará disponível na próxima atualização.
