### ISSUE TITLE
Há programas que recebem a mensagem de que foram compilados, mas não estão no repositório

### ISSUE THREAD

**Issue by MGall1970** [totvs/tds-vscode#742]
**Describe the bug**
Ao compilar a workspace há fontes que são informados que foram compilados e não estão sendo executados.

**To Reproduce**
Compilar toda a workspace;
Ao final observa-se que o programa foi marcado como compilado com sucesso;
Quando da execução do programa no smartclient recebemos a mensagem de que o programa não existe
Observamos esse comportamento somente na base migrada para a release 12.1.27

**Expected behavior**
Que o fonte compilado seja executado no smartclient.

**Screenshots**
[compilação.txt](https://github.com/totvs/tds-vscode/files/6784078/compilacao.txt)
![tela1](https://user-images.githubusercontent.com/67472754/124914220-7a1a6180-dfc6-11eb-8703-f8dfae94c7a7.jpg)
![tela2](https://user-images.githubusercontent.com/67472754/124914233-7f77ac00-dfc6-11eb-8e64-63f39b5182fe.jpg)

**Desktop (please complete the following information):**
 - OS/Architecture: Windows Server 2012

**Appserver (please complete the following information):**
 - Build (with date): 7.00.191205P-20210522 - 64 bits
 - OS/Architecture: Windows Server 2012
 - Build Version  19.3.1.7

**Additional context**
VsCode: 1.57.1
Totvs.vsix: 1.31

**Comment by lwtnb-wrk** [comment]
@MGall1970 Pelo log enviado, claramente verificamos que ocorreu um erro durante a compilação, pois no final temos as mensagens:
[Info  - 08:18:50] Aborting end build (rollback changes).
[Error - 08:18:50] One or more files have errors and/or warnings. See problems and logs for details.
e investigando melhor o log vemos tambem diversos fontes acusando "Duplicated function" corrigindo estes fontes a compilação deve ocorrer conforme esperado

**Comment by MGall1970** [comment]
Olá,
Sim, observamos o erro mas em outros fontes, naquele que citamos está correto, portanto entendo que aquele deveria ter sido gravado com sucesso. Pelo menos é assim na versão de produção: 12.1.25. Esse conceito foi mudado?

**Comment by lwtnb-wrk** [comment]
@MGall1970 Isso não é questão da versão do Appserver.
O tds-vscode vem por padrão marcado para reverter a compilação (rollback) em caso de erros/alertas encontrados, porem se preferir altere a configuração 'Commit With Error Or Warning' e os fontes que não deram erros serão comitados no RPO.

**Comment by MGall1970** [comment]
Marcamos a opção 'comitar a compilação com erros/alertas' na configuração da extensão da Totvs. Dessa maneira nos atendeu perfeitamente. Obrigado.
