### ISSUE TITLE
Erro no lançador ( ExitCode=-1073741819 ExistStatus=CancelExit )

### ISSUE THREAD

**Issue by jalberto2004** [totvs/tds-vscode#743]
Após executar o lançador, é aberto o Protheus. Coloco o usuário e senha normalmente. Escolho a Empresa, Filial e o Módulo então após clicar no botão "Entrar" o Protheus fecha e retorna para o VSCode.

**Dados do Remote** 
Remote build: 7.00.191205P-20200714
Remote version: 19.3.0.9
Remote type: 1 - QT-5.14.0 WIN
Módulo: PCP
Nome do computador: GSWTS
Sistema operacional: Windows Server 2008 R2 - Service Pack 1
Memória: 12287
Processador: QEMU Virtual CPU version (cpu64-rhel6)

**Dados do Server**
Versão: TOTVS Manufatura
Build AppServer: 7.00.191205P-20201012 - 64 bits
Nome do servidor: protheus-app
Sistema operacional: Linux
Appserver version: 19.3.1.0
Build DBAccess: 20200606-20201110
Release do RPO:  12.1.025
Release do dicionário: 12.1.025
Local files: CTREE
License server: 2014 - 3.1.7
DB DataBase: MSSQL
DB API Build: 20200606-20201110

[dap.log](https://github.com/totvs/tds-vscode/files/6785587/dap.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/6785588/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/6785590/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/6785591/totvsls_out.log)

**Comment by lwtnb-wrk** [comment]
@jalberto2004 Infelizmente o VS Code tem limitações e não suportam Windows Server conforme https://github.com/totvs/tds-vscode#guia-r%C3%A1pido
Instale o tds-vscode em um SO conforme https://code.visualstudio.com/docs/supporting/requirements
Grato

**Comment by jalberto2004** [comment]
Olá @lwtnb-wrk,
Foram realizados testes nas versões 1.3.1, 1.3.0, 1.2.5 e 1.2.3 da extensão da TOTVS e todas deram o erro.
Na versão 1.2.1 funcionou normalmente.

Precisa de algum log ?

**Comment by lwtnb-wrk** [comment]
@jalberto2004 Este é um problema estranho, pois mesmo funcionando na 1.2.1 o tds-vscode não deveria ser executado no Windows Server, pois não é uma plataforma homologada pela Microsoft para uso do VS Code.
No futuro isso pode voltar a funcionar, mas não testaremos especificamente, pois sempre teremos essa dúvida por não ser um SO homologado.
Aconselhamos fortemente a usar um SO homologado para uso do VS Code.

**Comment by brodao** [comment]
@jalberto2004 

Favor consultar https://code.visualstudio.com/docs/supporting/requirements.

**Comment by viniciusdeso** [comment]
> Esse problema a principio apenas ocorre em ambiente Virtualizado, via acesso remoto ou ambiente Windows Server, máquina física não temos relatos. Para contornar, dentro da pasta do Smartclient/dlls514 existe um arquivo com o nome opengl32sw.dll copie ele para a raiz do Smartclient e renomeie para opengl32.dll. Então na pasta Smartclient vai existir o arquivo opengl32.dll e na pasta Smartclient/dlls514 vai existir o arquivo opengl32sw.dll Dessa forma, força o Smartclient a utilizar a renderização via software e deve resolver o seu problema até uma próxima versão ser gerada com a correção. At.te

Solução para quem tenta debugar mas o Protheus fica fechando! Obrigado @danielbolognani .
