### ISSUE TITLE
SEM: 0x7f8650f90c48 init sem: 0x7f8650f90c50 ret: -1 err: 78 (Exeções ao Salvar, AutoComplete, etc)

### ISSUE THREAD

**Issue by lkznogueira** [totvs/tds-vscode#744]
Olá.

Utilizo o sistema macOs Big Sur com a ultima extensão 1.3.1 e percebi que constantemente ele ficava aparecendo esses erros abaixo e que até o momento não entendia o que poderia ser...
![image](https://user-images.githubusercontent.com/12913181/125482110-9f05a3fa-c831-40eb-9a98-1fec7527fc08.png)

Mas hoje verifiquei que sempre que digito algo na janela esse erro sai aparecendo disparadamento e percebi que o AutoComplete não está funcionando. 
Para poder auxiliar no log habilitei nas extensões da extensão  o Trace Server com o modo [Messagens] e dpois disso passou a mostrar as informações a abaixo..
![image](https://user-images.githubusercontent.com/12913181/125481910-e65469aa-0fc0-4a13-ab99-ff3a1f3a0d04.png)

Por fim limpei os Logs e cliquei para salvar o código fonte e também me gerou as exeções abaixo..
![image](https://user-images.githubusercontent.com/12913181/125482769-906c96d6-c201-4a92-800b-9b7b869dcd46.png)

Até o momento a questão de salvar/compilar está tudo OK msm apresentando esses 'erros' mas o que está me impactando mais mesmo seria o Auto-Complete que está comprometido, pois hora funciona e hr nao funciona.

**Comment by lwtnb-wrk** [comment]
@lkznogueira Pelo que entendi o tds-vscode está instalado no Mac Big Sur correto? Mas o AppServer esta em qual SO?
De qualquer forma o VS Code ainda não está totalmente testado e homologado para o Big Sur conforme [requirements](https://code.visualstudio.com/docs/supporting/requirements), então podem ocorrer problemas que estão fora de nosso controle.

**Comment by lkznogueira** [comment]
> @lkznogueira Pelo que entendi o tds-vscode está instalado no Mac Big Sur correto? Mas o AppServer esta em qual SO?
> De qualquer forma o VS Code ainda não está totalmente testado e homologado para o Big Sur conforme [requirements](https://code.visualstudio.com/docs/supporting/requirements), então podem ocorrer problemas que estão fora de nosso controle.

Windows Server

**Comment by lwtnb-wrk** [comment]
@lkznogueira A partir da versão 1.3.0 temos o Linter que está sempre analisando o fonte utilizando processos internos compartilhados com o AppServer. 
Pelo erro apresentado podemos ver que trata-se de algum problema na inicialização de semáforos que aparentemente tem algum problema interno e que não é suportado pelo SO.
Se possível veja em [Gerando logs](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs) como gerar e nos envie os logs para análise.

**Comment by lwtnb-wrk** [comment]
@lkznogueira O erro parou de ocorrer? Nos logs ele não apareceu em nenhum pontos pelo que vi...

**Comment by lkznogueira** [comment]
@lwtnb-wrk 
Também não entendi... segue novamente os logs com um print da tela.. mas novamente tbem não vi esse 'erro' aparecer no LOG.

![image](https://user-images.githubusercontent.com/12913181/125504337-5ece1efc-ddc0-407f-8876-ffaf5042b292.png)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/6811089/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/6811091/totvsls_out.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/6811092/totvsls.log)

**Comment by lwtnb-wrk** [comment]
@lkznogueira Estamos testando uma nova versão onde alteramos os processos de carga de includes para o Linter e que pode também ter resolvido essa questão do auto complete que você necessita.
Se quiser avaliar a alteração, baixe o VSIX em https://github.com/totvs/tds-vscode/releases/tag/v1.3.2
Para instalar veja https://github.com/totvs/tds-vscode/blob/master/docs/install.md

Lembrando que por se tratar de Big Sur podem ocorrer outros problemas que não teremos como resolver até que o VS Code esteja suportanto este SO.

**Comment by lkznogueira** [comment]
@lwtnb-wrk instalei ela aqui e a principio o problema do auto complete ta OK.. irei fazer mais testes!

Porem aquele do semafaro "SEM: 0x7ff7fc061878 init sem: 0x7ff7fc061880 ret: -1 err: 78" ainda continua aparecendo no console..

**Comment by lwtnb-wrk** [comment]
@lkznogueira Essa mensagem deve ser removida em outra atualização mais para frente. Estou fechando esta issue pois a mensagem não causa nenhum outro problema além da poluição do console.
Mas fique de olho nas atualizações.
