### ISSUE TITLE
Copia de arquivos Plugin da Totvs para VSCODE

### ISSUE THREAD

**Issue by ricpinheirols** [totvs/tds-vscode#745]
**Describe the bug**

Pessoal, boa tarde! estou tentando instalar o plugin da totvs para o meu vscode no server (sem internet), alguém sabe qual arquivo para eu copiar na máquina local e jogar no server ?

**Appserver (please complete the following information):**

Build (with date): 7.00.191205P-20201124 - 64 bits
OS/Architecture: Windows Server 2012 R2
Build Version 7.00.191205P

**Comment by lwtnb-wrk** [comment]
@ricpinheirols O tds-vscode não deve ser instalado em Windows Server, conforme https://github.com/totvs/tds-vscode#guia-r%C3%A1pido 
O VS Code não homologa este tipo de SO segundo https://code.visualstudio.com/docs/supporting/requirements
