### ISSUE TITLE
Webservices com cores

### ISSUE THREAD

**Issue by brunoviskz** [totvs/tds-vscode#748]
Olá, bom dia. Tenho uma requisição bem simples para fazer, se possível.
Dentro do PRW com Webservices os textos não ficam destacados, seria muito interessante se isso fosse implementado.

Muito obrigado pela ótima extensão!

Segue exemplo:
![exemplo](https://user-images.githubusercontent.com/60655337/125632940-9853cbf2-11d5-4185-a9d8-8ac80d2a73b8.png)

**Comment by likid** [comment]
Bruno, estranho, aqui está com as cores. Não é alguma configuração sua ou conflito com outra extensão?

![image](https://user-images.githubusercontent.com/10984007/126555080-2135a6c6-f407-4149-8f14-f0370d9b395f.png)

**Comment by ricardomansano** [comment]
Boa tarde @brunoviskz ,

Testei e confirmei o mesmo que o  @likid , o highlight esta funcionando para WS, favor verificar o encavalamento de plugin AdvPL
![image](https://user-images.githubusercontent.com/33813921/127540340-ff0f6fe2-6887-4076-ba18-add005eaffe7.png)

Grato pelo report
