### ISSUE TITLE
Protheus ao iniciar debuger adapter Windows 10 

### ISSUE THREAD

**Issue by mmateusmedeiros** [totvs/tds-vscode#749]
Ao iniciar o debuger adapter no windows 10 home , tenho tido o problema da não inicialização do smartclient para prosseguir com o debug. Mesmo com as configurações corretas, o smartclient.exe não inicia de forma alguma. 

Segue os arquivos de log: 

[totvsls.log](https://github.com/totvs/tds-vscode/files/6817011/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/6817013/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/6817014/totvsls_out.log)
![image](https://user-images.githubusercontent.com/8399045/125645099-6f959030-58eb-4e22-8cec-8baae8af69a7.png)
![image](https://user-images.githubusercontent.com/8399045/125645248-ceda316a-8b81-4885-b4f7-649ccb62a84a.png)

A disposição para enviar mais informações.

**Comment by lwtnb-wrk** [comment]
@mmateusmedeiros Como trata-se de problema em depuração, favor gerar e enviar o dap.log tambem.

Se ao inves de iniciar a Depuração com F5, voce consegue executar o Smartclient com CTRL + F5 ?

**Comment by mmateusmedeiros** [comment]
@lwtnb-wrk Mesmo com o atalho CTRL + F5 o smartclient não é aberto. Fiz a geração do arquivo dap.log, conforme solicitado. 

[totvsls.log](https://github.com/totvs/tds-vscode/files/6818135/totvsls.log)
 
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/6818136/totvsls_in.log)

[totvsls_out.log](https://github.com/totvs/tds-vscode/files/6818137/totvsls_out.log)
[dap.log](https://github.com/totvs/tds-vscode/files/6818134/dap.log)

**Comment by lwtnb-wrk** [comment]
@mmateusmedeiros Por algum motivo um dos breakpoints está vindo com uma informação incorreta de encoding por conta da acentuação no nome da pasta:

(   0.217s) [main thread     ]        tMessageDAP.cpp:122   | DAP Received < - {"command":"setBreakpoints","arguments":{"source":{"name":"FORCAR.prw","path":"c:\\Users\\mateu\\OneDrive\\??rea de Trabalho\\FORCAR.prw"},"lines":[79,88],"breakpoints":[{"line":79},{"line":88}],"sourceModified":false},"type":"request","seq":8}

Se estiver depurando o fonte "FORCAR.prw", mude ele de pasta (tire da pasta "Área de Trabalho" com acentuação) ou se não estiver depurando ele, remova da lista de breakpoints.

Isso deve contornar o problema por enquanto.

**Comment by mmateusmedeiros** [comment]
@lwtnb-wrk, muito obrigado. 
Retirei o breakpoint do fonte "FOCAR.PRW", pois não estava realizando a depuração nele e o smartclient abriu. Muito obrigado pela orientação.

**Comment by lwtnb-wrk** [comment]
@mmateusmedeiros Excelente.

Só para deixar claro em caso de mais alguém ter esse problema, no passado realmente tivemos problemas com depuração em fontes que estavam em caminho com alguma acentuação. A lista de breakpoints fica "gravada" no VS Code e é enviada ao iniciar uma depuração. Se tivermos um breakpoint "antigo" gravado com o caminho errado, ele causará a falha na abertura da depuração.

A mensagem de erro encontrada no dap.log é a seguinte:
(   0.217s) [main thread     ]        tMessageDAP.cpp:122   | DAP Received < - {"command":"setBreakpoints","arguments":{"source":{"name":"FORCAR.prw","path":"c:\\Users\\mateu\\OneDrive\\??rea de Trabalho\\FORCAR.prw"},"lines":[79,88],"breakpoints":[{"line":79},{"line":88}],"sourceModified":false},"type":"request","seq":8}
(   0.217s) [main thread     ]        tMessageDAP.cpp:129   | Error parsing JSon (invalid UTF8 string)

Basta remover, e se necessário readicionar, o breakpoint no fonte que esta com um caminho invalido que o problema deve ser sanado.
