### ISSUE TITLE
Erro ao Adicionar Servidores

### ISSUE THREAD

**Issue by emersonmuniz** [totvs/tds-vscode#75]
Prezados,

Hoje instalei no VSC para começar a estudar o ADVPL, já que acho o VSC leve e rápido.

Ao tentar adicionar um servidor está retornando: command 'totvs-developer-studio.add' not found

Alguma dica ?

SO: Mac OS X Mojave

Att,

Emerson Muniz

**Comment by lwtnb-wrk** [comment]
@emersonmuniz Primeiramente grato pelo interesse em utilzar o tsd-vscode. Ainda nao liberamos a versao para o MacOS mas devemos faze-lo em breve. Estamos estabilizando o produto inicialmente para Windows e Linux, mas em breve teremos a versão para MacOS. Como pode perceber a interface do cliente (VSCode) sera a mesma, porem ainda falta o Language Server (e Debug Adapter) na versão MacOS. Assim que liberarmos esses componentes essenciais para o funcionamento. Peço um pouco de paciencia e ficaremos felizes em saber se o produto atende os desenvolvedores que utilizam o MacOS tambem. Grato

**Comment by lwtnb-wrk** [comment]
@emersonmuniz Acompanhe a liberação da versão para MacOS atraves da issue #66 ok?

**Comment by jslaurentino** [comment]
Olá.

Ao tenta realizar a inclusão do novo server na versão 0.3.22 Windows.

Retorna : command 'totvs-developer-studio.add' not found

Print: http://prntscr.com/qarpr3

**Comment by lwtnb-wrk** [comment]
@jslaurentino Não reproduzo esse problema aqui. Tente desinstalar e reinstalar o plugin e tente novamente. Se continuar com o problema abra uma nova issue e não use uma que está fechada.
