### ISSUE TITLE
TOTVS Replay 2.0 - Melhoria para busca de informações na Timeline

### ISSUE THREAD

**Issue by FernandaHirle** [totvs/tds-vscode#750]
Boa tarde!

Atualmente em análises de log muito grandes fica difícil navegar pela Time line  principalmente quando estamos avaliando cenários de fontes e funções muito extensas. Gostaríamos de sugerir uma melhoria de  abrir opção de busca dentro da Time line para localizar um fonte ou uma função a ser analisada.

**Comment by DanielYampolschi** [comment]
ola @FernandaHirle obrigado pela sugestão. Essa melhorai já está no nosso Roadmap.
