### ISSUE TITLE
TOTVS Replay 2.0 - Melhoria - Usabilidade nos produtos de Portais

### ISSUE THREAD

**Issue by FernandaHirle** [totvs/tds-vscode#751]
Atualmente o time de Recursos Humanos Protheus possui alta demanda de produtos Web, como MEURH e os Portais de Capital Humano e Portal do Candidato.
Esses produtos trabalham com Threds, e inclusive para debug precisamos subir uma Thread específica para análises.

Existe algum possibilidade de melhoria na ferramenta, que futuramente nos permita um log de análise off line para produtos como esses?

**Comment by DanielYampolschi** [comment]
Ola @FernandaHirle. Essa é realmente uma questão complicada. Hoje o Replay consegue atuar apenas na Thread de debug e isso acontece por limitações do servidor e não da ferramenta TDS Replay. Estamos cientes dessa necessidade e vamos olhar com cuidado assim que possível.
