### ISSUE TITLE
TOTVS Replay 2.0 - Inconsistência no Exclude/Include da Launcher 

### ISSUE THREAD

**Issue by FernandaHirle** [totvs/tds-vscode#754]
Boa tarde!

As opções de Include e Exclude na configuração de Launcher do Replay 2.0 não funcionando corretamente.
Como exemplo, temos o seguinte ### caso:
1 - Ao configurar a Launcher solicitamos a exclusão do fonte GPEXIDC.PRX ou *PRX 
2 - Conforme é possível verificar na evidência enviada ao e-mail daniel.yampolschi, mesmo com os dados para exclusão, eles são demonstrados na Time Line deixando o log muito extenso e dificultando na navegação nas páginas. 

Obs: como o analista possui todos os fontes baixados no projeto, não funcionando a opção de exclusão e existindo o fonte na Time Line, todos serão abertos conforme a execução do Debug, deixando a análise muito extensa e muitas vezes até travando, devido o grande volume de informações.

**Comment by DanielYampolschi** [comment]
Ola @FernandaHirle realmente identifiquei alguns problemas com esse filtro de inclusao e exclusao de fontes... Fiz a correção e ela estará disponível oficialmente a partir da versão 1.3.4 do plugin tds_vscode.

Obrigado pelo chamado.

**Comment by lwtnb-wrk** [comment]
@FernandaHirle Estamos com uma versão pré-release disponível com a correção deste problema. Se puder testar e validar a correção isso auxiliará na liberação oficial.
https://github.com/totvs/tds-vscode/releases/tag/v1.3.4
