### ISSUE TITLE
TOTVS Replay 2.0 - Timeline travando

### ISSUE THREAD

**Issue by FernandaHirle** [totvs/tds-vscode#755]
Boa tarde!

Na timeline dependendo do Log não conseguimos avançar a página. Fica travado e dessa forma não conseguimos avaliar as demais linhas do debug.
Parece ser algo intermitente, pois às vezes se fechar e abrir o VSCODE novamente, funciona.

Podem nos auxiliar com essa questão.

Evidência encaminhada via e-mail para daniel.yampolschi.

**Comment by DanielYampolschi** [comment]
Ola @FernandaHirle , peço desculpas pela demora em retornar esse chamado. Por favor use última verão gerada que está em Release Candidate pelo link abaixo que isso não deve mais ocorrer.

Qualquer questão relacionada a esse problema pode reabrir esse chamado.

Muito obrigado.

https://github.com/totvs/tds-vscode/releases/tag/v1.3.9-RC2
