### ISSUE TITLE
Acesso exclusivo RPO

### ISSUE THREAD

**Issue by pedropgtorres** [totvs/tds-vscode#756]
Mesmo não tendo nenhum acesso ao ambiente, a IDE reclama de não ter acesso exclusivo para compilar.
**It wasn't possible to obtain exclusive access to the objects repository**

Versão da IDE: 1.58.1
Versção plugin: 1.3.2

Alguém mais está com esse problema?

**Comment by lwtnb-wrk** [comment]
@pedropgtorres Poderia dar mais detalhes do que está ocorrendo?
Além disso se possível já inclua os logs conforme [Gerando logs](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs)

**Comment by pedropgtorres** [comment]
Olá @lwtnb-wrk .
Acabamos de descobrir que o problema não está no plugin e sim na lib do Protheus que estamos utilizando.

Agradeço a atenção e peço desculpas pela abertura da issue.

**Comment by lwtnb-wrk** [comment]
@pedropgtorres Sem problemas.
Se puder detalhe a ocorrência para ajudar outros que possam encontrar a mesma situação.
Qual lib que causou o erro, e o que foi feito para resolver?
Grato

**Comment by pedropgtorres** [comment]
Segue o problema.,,,

A **LIB 20210517** cria uma thread **FWGRVCUSTOMMETRICS** e ela impede as compilações.
retornando a seguinte mensagem no output: **It wasn't possible to obtain exclusive access to the objects repository**.

Para resolver o problema adicionamos a chave **[buildKillUser](https://centraldeatendimento.totvs.com/hc/pt-br/articles/360018481631-MP-ADVPL-ENCERRAR-TODAS-AS-CONEX%C3%95ES-QUANDO-SOLICITADO-UMA-COMPILA%C3%87%C3%83O-)**

Exemplo de como usar:
[General]
InstallPath= C:\PROTHEUS
BuildKillUsers=1

Com essa chave habilitada, todas as instâncias são encerradas para que a preferência seja do compilador.
