### ISSUE TITLE
TOTVS Replay 2.0 - Melhoria - Validação de Pontos de Parada

### ISSUE THREAD

**Issue by FernandaHirle** [totvs/tds-vscode#757]
No vídeo de demonstração da ferramenta é observada a possibilidade de se usar os pontos de parada para análise, mas esses pontos devem estar em acordo às linhas apresentadas na Timeline.

Essa usabilidade poderia ser aplicada sem estar de acordo com as linhas da timeline? Validando por exemplo um limite de linhas que foram registradas na foto do ambiente?
Exemplo: Na Timeline são demonstrados registros da linha 010 à 250 do fonte GPEXCID.PRX. O analista gostaria de depurar/analisar somente das linhas 15 a 120, sem ter que cumprir cada linha da Timeine.
Como em um debug online onde informamos os pontos de paradas.

Atualmente quando temos log muito extensos a opção de análise via ponto de parada se torna ineficaz por ter que seguir exatamente as linhas da timeline.

Evidência e demonstração encaminhada ao e-mail daniel.yampolschi@.

**Comment by DanielYampolschi** [comment]
Ola @FernandaHirle. 
Acredito que essa situação poderia ser observada quando a opção "Run" do Debug com o TDS Replay parava na primeira linha de cada página. 

Fizemos uma modificação onde agora, ao colocar um ponto de parada em uma linha do fonte e executar a opção "Run" (via botão ou pelo atalho padrão F5), a execução irá diretamente para a primeira timeline encontrada que corresponde ao(s) ponto(s) de parada adicionado(s).
