### ISSUE TITLE
Next <variavel> retorna erro de sintaxe.

### ISSUE THREAD

**Issue by vitor-vyas** [totvs/tds-vscode#761]
Ao tentar compilar qualquer fonte com a versão 1.2.1+ utilizando a sintaxe abaixo:

FOR <variável> := <expressão inicial> TO <expressão final>
          < instruções >
NEXT <variável>

Ele me erro de sintaxe:
{
	"resource": "/c:/RdMakes/Grupo_Vyas/PRD/RH/Rel Gen Empregados/GPE08RAE.PRW",
	"owner": "AdvPL",
	"severity": 8,
	"message": "Syntax Error",
	"source": "Linter",
	"startLineNumber": 321,
	"startColumn": 1,
	"endLineNumber": 322,
	"endColumn": 1
}

![image](https://user-images.githubusercontent.com/84542988/126014249-d0b5aed4-c56a-4f39-b19e-79a616f1bcbb.png)

**Comment by lwtnb-wrk** [comment]
@vitor-vyas Qual era o problema afinal? 

Se puder deixe seu comentário caso outro desenvolvedor encontre o mesmo erro e possa resolve-lo tambem.

**Comment by vitor-vyas** [comment]
![image](https://user-images.githubusercontent.com/84542988/126163270-6a2ece8e-8329-4073-8ea1-aa1b66b345cb.png)
Quando coloco "Next <Variavel>" ele me retorna erro de sintaxe, se retiro a variável, ele deixa passar.

**Comment by erivaltonoliveira** [comment]
![image](https://user-images.githubusercontent.com/56845297/175749081-3a485c4e-471a-499d-b7d0-4e60068e123c.png)

![image](https://user-images.githubusercontent.com/56845297/175749091-be0cebf3-3eac-495f-aaf0-d7e2ee75ddd3.png)

**Comment by danielbolognani** [comment]
Ola,
O comando For ... Next no ADVPL/TLPP não deve ser utilizado com a variável após o Next:
https://tdn.totvs.com/display/tec/O+Comando+FOR...NEXT

**Comment by erivaltonoliveira** [comment]
Temos um projeto com mais de 500 fontes e a maioria está escrito desta maneira.
Alias este mesmo projeto foi submetido ao Code Analyse algumas vezes e não foi retornado erro algum relacionado a estrutura FOR...NEXT
Somente agora nesta versão 1.3.14 estamos recebendo este erro

**Comment by erivaltonoliveira** [comment]
Depois de muito desinstalar, instalar, voltar versões, analisar várias estruturas de códigos, identifiquei que o problema esta sendo causado pelos dois arquivos na pasta include
![image](https://user-images.githubusercontent.com/56845297/175752854-c4ea1f8f-0a20-40e5-a434-032cf34cdd5c.png)

**Comment by lwtnb-wrk** [comment]
@erivaltonoliveira Somente pra gente saber, voce recentemente não atualizou sua pasta de includes tambem? Se voce identificou que a diferenca de comportamento ocorre ao atualizar esses dois includes, parece ser mais algo de framework do que do tds-vscode...
