### ISSUE TITLE
Smartclient travando ao tentar rodar pelo VSCode

### ISSUE THREAD

**Issue by h2danilo** [totvs/tds-vscode#763]
**Describe the bug**
Estou tentando rodar programa pelo VSCode e esta aparecendo seguinte erro:
![image](https://user-images.githubusercontent.com/38380833/126208632-1b971ef0-2c07-424f-9ea4-e75356635532.png)

**To Reproduce**
- Inicío AppServer
- Conecto Server no VSCode
- Pressiono F5;
- Digito Módulo desejado: SIGAFIN ou SIGAFAT ou SIGAAGR
- Abre smartclient com tela para digitar usuário e senha
- após digitar, trava e fecha programa disparando para appserver mensagem informada no inicio.

**Desktop (please complete the following information):**
 - OS/Architecture: Windows Server 2016 DataCenter - x64

**Appserver (please complete the following information):**
 - Build (with date): 7.00.170117A (Mar 31 2020 - 12:20:16) 26547
 - OS/Architecture: Windows Server 2016 DataCenter - x64
 - Build Version 17.3.0.20

Versão TOTVS Developer Studio fo VSCode:
![image](https://user-images.githubusercontent.com/38380833/126209677-3f2ed271-4e55-43a6-86ac-005b5239e950.png)

**Additional context**
launch:json:
`{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Debug",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "E:\\TOTVS\\Microsiga\\protheus\\bin\\smartclient_dbg\\smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true
		}
	],
	"lastPrograms": [
		{
			"args": [],
			"label": "SIGAADV",
			"description": ""
		},
		{
			"args": [],
			"label": "SIGAAGR",
			"description": ""
		},
		{
			"args": [],
			"label": "SIGACOM",
			"description": ""
		},
		{
			"label": "SIGAAGR",
			"description": "<nil>"
		}
	],
	"lastProgramExecuted": "SIGAAGR"
}`

Server.json:
`{
	"version": "0.2.0",
	"includes": [
		"E:\\TOTVS\\Microsiga\\protheus\\include"
	],
	"permissions": {
		"authorizationtoken": ""
	},
	"connectedServer": {
		"id": "xxxxxxxxxxxxxx",
		"type": "totvs_server_protheus",
		"name": "DEBUG",
		"port": 9999,
		"address": "xxx.xxx.xxx",
		"buildVersion": "7.00.170117A",
		"secure": false,
		"includes": [
			"E:\\TOTVS\\Microsiga\\protheus\\include"
		],
		"environments": [
			"producao"
		],
		"username": "admin",
		"environment": "producao",
		"token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
	},
	"configurations": [
		{
			"id": "xxxxxxxxxxx",
			"type": "totvs_server_protheus",
			"name": "DEBUG",
			"port": 9999,
			"address": "xxx.xxx.xx.xxx",
			"buildVersion": "7.00.170117A",
			"secure": false,
			"includes": [
				"E:\\TOTVS\\Microsiga\\protheus\\include"
			],
			"environments": [
				"producao"
			],
			"username": "admin",
			"environment": "producao",
			"token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
		}
	],
	"savedTokens": [
		[
			"xxxxxxxxxxxx:producao",
			{
				"id": "xxxxxxxxxxxxxxxxxxxxx",
				"token": "xxxxxxxxxxxxxxxxxxxx"
			}
		]
	],
	"lastConnectedServer": "xxxxxxxxxxxxxxxxxxxx"
}`

SmartClient.ini:
`[config]
lastmainprog=sigaadv
envserver=producao

[drivers]
active=tcp

[tcp]
server=xxx.xxx.xx.xxx
port=9999

[_DBG_TEMP]
server=xxx.xxx.xx.xxx
port=9999
SecureConnection=0`

APPSERVER.INI:
`;MASTER

[producao]
SourcePath=E:\TOTVS\Microsiga\protheus\apo\compilacao
RootPath=E:\TOTVS\Microsiga\protheus_data
StartPath=\system\
x2_path=
RpoDb=SQLR
RpoLanguage=portuguese
RpoVersion=120
LocalFiles=CTREE
localdbextension=.DTC
TopMemoMega=1
PictFormat=DEFAULT
DateFormat=DEFAULT
RegionalLanguage=BRA
Trace=0
HELPSERVER=127.0.0.1:8081
AUTONFE_DEBUG=1

[Drivers]
Active=TCP

[TCP]
TYPE=TCPIP
Port=9999

[Service]
Name=tp12producaomaster
DisplayName=TOTVS | PROTHEUS 12 - PRODUCAO - DEBUG (9999)

[LICENSECLIENT]
SERVER=127.0.0.1
PORT=5555
EnableNumber=0

[GENTCPIP]
Enable=0

[DBACCESS]
SERVER=127.0.0.1
PORT=7891
DATABASE=MSSQL
ALIAS=protheus_prd

[GENERAL]
CtreeMode=Server
EnableNumber=0
ConsoleLog=1
ConsoleFile=E:\TOTVS\Microsiga\protheus\bin\appserver_dbg\console.log
ConsoleMaxSize=120000

[ctreeserver]
ctuserid=ADMIN 
ctuserpass=ADMIN 
ctservername=FAIRCOMS@127.0.0.1

[TDS]
ALLOWAPPLYPATCH=*
ALLOWEDIT=*

[HTTP]
;ENABLE=1
;PATH==E:\TOTVS\Microsiga\help-online\portuguese
;PORT=8081

[MAIL]
Protocol=POP3
ExtendSMTP=1
`

**Comment by danielbolognani** [comment]
Boa tarde @h2danilo, o VSCode não é homologado para S.O. Windows Server:
https://code.visualstudio.com/docs/supporting/requirements
E a parte de debug também só é homologada nos mesmos SOs que o Smartclient:
https://tdn.totvs.com/display/tec/SmartClient+-+Sistemas+operacionais

Já recebemos relatos de problemas com o Windows Server no passado e não recomendamos a sua utilização exatamente por causa desses problemas apresentados.

**Comment by h2danilo** [comment]
Boa Tarde @danielbolognani , estranho que o problema começou após atualizar totvs Developer para a versão 1.3.2, pois, até então estava utilizando normalmente.

**Comment by danielbolognani** [comment]
@h2danilo é exatamente isso que acontece com um S.O. não homologado. Pode funcionar ou pode ter funcionado em algum ponto, mas como é um sistema que a gente não suporta, pode começar a ocorrer problemas em alguma atualização, seja ela do S.O., do produto, etc.
Continuo aconselhando a utilização de um S.O. homologado, mas, se não tiver como utilizar outro SO, pode tentar voltar versão da extensão para uma que funcione.
