### ISSUE TITLE
Uso excessivo de memória pelo advpls.exe, conforme o vscode é utilizado.

### ISSUE THREAD

**Issue by lucaskonradfranca** [totvs/tds-vscode#765]
Conforme vou utilizando o VSCode, e alterando fontes ADVPL, noto que o processo "advpls.exe" vai aumentando muito o consumo de memória, até o ponto de começar a travar a máquina. A memória só é liberada após fechar o VsCode.
![image](https://user-images.githubusercontent.com/22057713/126706762-da4ecaa0-109b-4dd0-aea9-4a81fe487ebb.png)

Quanto maior o tamanho do código fonte em manipulação no VSCode, mais rápido é para subir o consumo de memória.
Tenho que fechar o vscode diversas vezes, pois chega determinado momento a máquina começa a travar por conta deste consumo de memória.

A versão do plugin instalada é 1.3.2
![image](https://user-images.githubusercontent.com/22057713/126707025-096d6461-5fd4-4bca-9427-2a4911c0df0c.png)

**Comment by danielbolognani** [comment]
Obrigado pelo report, já estamos analisando.

**Comment by danielbolognani** [comment]
Boa tarde, disponibilizamos uma correção em pré-release:
https://github.com/totvs/tds-vscode/releases/tag/v1.3.3
Nossa previsão é subir oficialmente no MarketPlace semana que vem.

**Comment by danielbolognani** [comment]
Versão 1.3.3 liberada no marketplace
