### ISSUE TITLE
Funcionalidades para o Logix perdidas

### ISSUE THREAD

**Issue by eduardonogueira0405** [totvs/tds-vscode#766]
Após atualização as tags Logix deixaram de ficar em caixa alta, não aparecem mais na caixa de sugestões.
Funcionalidades advpl não utilizadas no Logix passaram a aparecer na caixa de sugestões para auto-complemento da instrução digitada.

**Comment by eduardonogueira0405** [comment]
Boa tarde, tem algum procedimento a ser executado?

**Comment by eduardonogueira0405** [comment]
Não tive retorno da pergunta realizada, qual o procedimento para ativar o processo de formatação de fontes 4gl? Tendo em vista que já estava executando normalmente e parou de funcionar repentinamente.
At
Eduardo

**Comment by brodao** [comment]
Favor aguardar a liberação da próxima versão (1.3.3) ou superior e seguir os procedimentos conforme [TDS: Formatação de Código Fonte]( https://github.com/totvs/tds-vscode/blob/dev/docs/formatter/format_config.md).
