### ISSUE TITLE
Porblema com Linter quando utilizar variável com macro substituição

### ISSUE THREAD

**Issue by Smmartinez** [totvs/tds-vscode#767]
Bom dia Pessoal, não sei se abro aqui o problema do linter, se não for por favor me desculpe e só me encaminhe onde devo abrir.
Baixei um fonte da TOTVS o DANFII.PRW que gera o DANFE da NFe, e no TDS no linter ele mostra que uma variável não esta sendo utilizada, mas ela é usada com macro substituição.
local cProg		:= iif(existBlock("DANFEProc"),"U_DANFEProc","DANFEProc")
&cProg.(@oDanfe, , cIDEnt, Nil, Nil, @lExistNFe, lIsLoja )

Não ocorre erro de compilação, mas apresenta o erro.
![linter](https://user-images.githubusercontent.com/4532855/127513317-1fc845af-0ae8-4e90-a110-b0dcd9f011d6.png)

**Comment by danielbolognani** [comment]
Bom dia @Smmartinez o Linter utiliza o mesmo motor de pré compilação e compilação do appserver. Se mesmo após compilar o programa no Appserver, a mensagem de "Warning" continuar, esse problema deve ser aberto para a equipe do Appserver.

Abraços!

**Comment by Smmartinez** [comment]
Maravilha @danielbolognani vou abrir um chamado para eles.

**Comment by likid** [comment]
@Smmartinez estou com um appserver de testes aqui que resolveu esta situação, então em breve deve ter a liberação da versão que corrige.
