### ISSUE TITLE
Debug Macbook

### ISSUE THREAD

**Issue by henrycharriere** [totvs/tds-vscode#769]
**Describe the bug**
Boa tarde! Estou iniciando o debug, tentando compilar me deparei com o erro abaixo e ainda não consegui resolver.

smartclient bin not found. File: /Users/henrycharriereca/Desktop/smartclient

Abaixo launch.json
"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Depuração do idioma TOTVS",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "/Users/henrycharriereca/Desktop/smartclient",
			"isMultiSession": true,
			"enableTableSync": true
		}
	],
	"lastPrograms": [
		{
			"args": [],
			"label": "nomeFunction",
			"description": ""
		},
		{
			"label": "nomeFunction",
			"description": "<nil>"
		},
		{
			"args": [],
			"label": "U_nomeFunction",
			"description": ""
		},
		{
			"label": "U_nomeFunction",
			"description": "<nil>"
		},
		{
			"label": "sigamdi",
			"description": "<nil>"
		},
		{
			"configurations": [
				{
					"enableMultiThread": true
				}
			]
		}
	],
	"lastProgramExecuted": "sigamdi"
}

**Screenshots**
Anexo
![Uploading Captura de Tela 2021-08-05 às 15.06.25.png…]()

**Comment by DanielYampolschi** [comment]
Boa Tarde @henrycharriere, 

No Mac não aponte para o ".app":

ao inves de "/Users/henrycharriereca/Desktop/smartclient"
utilize "/Users/henrycharriereca/Desktop/smartclient.app/Contents/MacOS/smartclient"

**Comment by henrycharriere** [comment]
Obrigado @DanielYampolschi !! Funcionou perfeitamente bem!
