### ISSUE TITLE
IntelliSense na utilização das variáveis declaradas

### ISSUE THREAD

**Issue by marcosnqsdev** [totvs/tds-vscode#77]
Quando declaramos uma variável o IntelliSense não autocompleta na utilização da variável declarada. Essa é uma funcionalidade muito interessante que eu já utilizava pela extensão: https://github.com/totvs/advpl-vscode

**Comment by marcosnqsdev** [comment]
Voltei a utilizar a extensão https://github.com/totvs/advpl-vscode por este problemas: 1 - Autocompleta do IntelliSense e 2 - Falta as tabelas e conteúdos no debugger (Já vi que está pronto para próxima release).

**Comment by luizhj** [comment]
Tem uma configuração que muda para o intellisense padrão básico do vscode que autocompleta as variáveis e não faz o autocomplete das funções adpvl.

para isso vá em File -> Preferences -> Settings e na barra superior pesquise por AutoComplete.
Irá aparece a opção 
Totvs Langauge Server > Editor > Toogle: Autocomplete onde:
- Basic = autocomplete básico do vscode.
- LS = autocomplete do language server que retorna as funções adbvpl.

**Comment by DanielYampolschi** [comment]
Ola @marcosnqsdev, como o @luizhj comentou, existe essa funcionalidade que alterna entre os tipos de autocomplete, porém, uma forma mais direta de fazê-lo é com a combinação de teclas **Ctrl+Alt+Space**. Repare na barra inferior do VsCode a mudança. 

Quanto ao sincronismo de tabelas, realmente já está implementado e sairá na próxima liberação, a qual está em processo final de testes da versão "Release Candidate".

**Comment by luizhj** [comment]
> Quanto ao sincronismo de tabelas, realmente já está implementado e sairá na próxima liberação, a qual está em processo final de testes da versão "Release Candidate".

dá pra ver as alterações da nova release aqui:
https://github.com/totvs/tds-vscode/releases/tag/0.3.4

**Comment by marcosnqsdev** [comment]
> Ola @marcosnqsdev, como o @luizhj comentou, existe essa funcionalidade que alterna entre os tipos de autocomplete, porém, uma forma mais direta de fazê-lo é com a combinação de teclas **Ctrl+Alt+Space**. Repare na barra inferior do VsCode a mudança.
> 
> Quanto ao sincronismo de tabelas, realmente já está implementado e sairá na próxima liberação, a qual está em processo final de testes da versão "Release Candidate".

Não seria possível combinar as duas funcionalidades "Basic" e "LS"?
Tem alguma data prevista de lançamento da release?

**Comment by matheus-sales** [comment]
> > Ola @marcosnqsdev, como o @luizhj comentou, existe essa funcionalidade que alterna entre os tipos de autocomplete, porém, uma forma mais direta de fazê-lo é com a combinação de teclas **Ctrl+Alt+Space**. Repare na barra inferior do VsCode a mudança.
> > Quanto ao sincronismo de tabelas, realmente já está implementado e sairá na próxima liberação, a qual está em processo final de testes da versão "Release Candidate".
> 
> Não seria possível combinar as duas funcionalidades "Basic" e "LS"?
> Tem alguma data prevista de lançamento da release?

@marcosnqsdev  ainda não é possível mescar as duas opções. Estamos trabalhando nisso. 
Também não temos data exata para a próxima liberação, estamos fazendo testes e melhorando algumas coisas antes de liberar.

**Comment by DanielYampolschi** [comment]
@marcosnqsdev Não é possível combinar os dois processos, o que podemos/iremos fazer é o LS prover uma solução de autocomplete mais inteligente/completa. Mas isso depende de outras coisas mais pesadas que estão em andamento (como por exemplo o parser).
