### ISSUE TITLE
Logix - Ao compilar um fonte, está mostrando na aba 'Problemas' informações relativas aos fontes não compilados

### ISSUE THREAD

**Issue by eduardonogueira0405** [totvs/tds-vscode#770]
Ao abrir vários arquivos 4gl ou PER no vscode, já estão sendo marcados em 'vermelho' e apresentam erros de compilação na primeira linha.

Quando compila um arquivo apenas, mostra na aba "Problemas" várias mensagens de erro de todos os arquivos abertos, e mesmo compilando com sucesso o fonte volta a ficar em destaque vermelho como se houvesse erro de compilação.
No print em anexo, veja que há fontes que estão em modo leitura (os que possuem um numero de série iniciado com C) e mesmo assim mostram com erros de compilação.

![image](https://user-images.githubusercontent.com/72161552/128410513-f830f91f-f0e0-4a6b-b7a6-088ceee94ff2.png)

**Comment by danielbolognani** [comment]
Boa tarde @eduardonogueira0405 
Para os fontes Logix, o Linter necessita acesso ao arquivo *.sch (nesse caso logix.sch), para isso coloque ele em uma de suas pastas de include ou adicione a pasta que está esse arquivo nos includes globais.
Abraços!

**Comment by leogr85** [comment]
Boa tarde! 
Sou do protheus e estou comecando agora no logix, mesmo problema, onde arrumo o arquivo "logix.sch"?

**Comment by lwtnb-wrk** [comment]
@leogr85 este fórum é reservado a discussões sobre a ferramenta tds-vscode apenas. 
para outros assuntos sobre a linguagem de programação procure o suporte da TOTVS diretamente.
