### ISSUE TITLE
Debug  vs code executa  em ambiente cloundig developer

### ISSUE THREAD

**Issue by MILLE2020** [totvs/tds-vscode#771]
*Boa tarde!
Estou tentando debugar no VS code uma rotina customizada minha no ambiente de desenvolvimento do Clouding o Vscode conecta normalmente no ambiente em modo exclusivo porem no debug a rotina não é acionada no debug conforme demonstrado no video poderiam me passar qual o problema ?

**Comment by MILLE2020** [comment]
[AutoScreenRecorder_01 Aug. 06 14.16.zip](https://github.com/totvs/tds-vscode/files/6947690/AutoScreenRecorder_01.Aug.06.14.16.zip)

**Comment by brodao** [comment]
@MILLE2020 

Certifique-se que a versão do fonte é o mesmo do RPO (recomendo compilar) e esta sendo chamado (coloque um conout no inicio da função).
Entre direto no módulo (não use sigamdi) e caso seja rotina executada em job, habilite a depuração multithread (https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md#depura%C3%A7%C3%A3o-de-servi%C3%A7os-jobs).

Caso o problema persista favor gerar os logs (https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs) e anexo-os ao chamado.

A disposição.

**Comment by MILLE2020** [comment]
bOM DIA !  SENHORES  VALEU PELA AJUDA  DEU CERTINHO...
