### ISSUE TITLE
Vscode encerrando processo de debug após atualização versão 1.59

### ISSUE THREAD

**Issue by mmateusmedeiros** [totvs/tds-vscode#773]
Ao utilizar a função debbuger o sistema abre perfeitamente, porém ao colocar a senha e acessar um módulo o sistema fecha e o processo de debug é encerrado. 

Segue os logs para análise: 

[dap.log](https://github.com/totvs/tds-vscode/files/6970443/dap.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/6970444/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/6970445/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/6970446/totvsls_out.log)

**Comment by mmateusmedeiros** [comment]
> Ao utilizar a função debbuger o sistema abre perfeitamente, porém ao colocar a senha e acessar um módulo o sistema fecha e o processo de debug é encerrado.
> 
> Segue os logs para análise:
> 
> [dap.log](https://github.com/totvs/tds-vscode/files/6970443/dap.log)
> [totvsls.log](https://github.com/totvs/tds-vscode/files/6970444/totvsls.log)
> [totvsls_in.log](https://github.com/totvs/tds-vscode/files/6970445/totvsls_in.log)
> [totvsls_out.log](https://github.com/totvs/tds-vscode/files/6970446/totvsls_out.log)

Fiz toda a desinstalação do Vscode e reinstalei o mesmo e mesmo assim não obtive sucesso no depuração.

**Comment by mmateusmedeiros** [comment]
Olá @brodao,
O meu server é no totvs cloud, e sim, é Windows Server. 

O que vai nos complicar é que é a única ferramenta que temos hoje para realizar o debug.

**Comment by danielbolognani** [comment]
@mmateusmedeiros Só para esclarecer melhor, o ambiente do Appserver não tem problema ser Windows Server, o problema é VSCode rodar em ambiente Windows Server, nem o VSCode nem o Smartclient são homologados para essa plataforma.

https://code.visualstudio.com/docs/supporting/requirements
https://tdn.totvs.com/display/tec/SmartClient+-+Sistemas+operacionais
