### ISSUE TITLE
VSCODE (vsix 1.3.3) - Monitor  "stop server"

### ISSUE THREAD

**Issue by 0007black** [totvs/tds-vscode#775]
Monitor "stop server", ao selecionar botão cancelar ou apertar "esc", com objetivo de cancelar a ação de "stop server", o "Monitor" tem o mesmo comportamento de "stop server". Onde na verdade o objetivo seria "Cancelar" a ação, ou seja cancelar a ação de "parar o server".

1)Objetivo (stop server) periféricos.
2)Botões (OK,CANCEL) e "ESC".
3)Resultado esperado (Confirmar,Sair) e "abortar".
4)Resultado obtido: Ambos os periféricos estão derrubando server.

https://user-images.githubusercontent.com/89214779/130112367-8f2b41d0-465f-4270-a67d-ecf7f2004747.mp4

**Comment by danielbolognani** [comment]
Versão 1.3.3 liberada no marketplace
