### ISSUE TITLE
VSCODE (vsix 1.3.3) - Monitor "update speed" - 

### ISSUE THREAD

**Issue by 0007black** [totvs/tds-vscode#776]
Monitor "update speed", ao selecionar opção "update speed", e executando "Interval between", (15,30,60 segundos e manual), dentre as variações ofertadas, selecionando individualmente e clicando no botão "CANCEL", logo após essa ação, clicar novamente em "update speed", a operação não está sendo concluída com sucesso, pois a opção selecionada é mantida, mesmo cancelando a operação.(abaixo evidência).

1)Objetivo (Interval between);
2)Botões (CANCEL) e "ESC".
3)Resultado esperado (Cancelar seleção) e manter seleção anterior.
4)Resultado obtido: Botão cancelar não cancela seleção.

https://user-images.githubusercontent.com/89214779/130139192-fd1506f7-6c2d-446b-abf0-d85be543cbbf.mp4

.

**Comment by danielbolognani** [comment]
Versão 1.3.3 liberada no marketplace
