### ISSUE TITLE
Data Breakpoint (tambem conhecido como watchpoint)

### ISSUE THREAD

**Issue by nicociri** [totvs/tds-vscode#779]
Existe no advpl a posibilidade de parar o debug cuando uma variable troca de valor?
Eu nao sei ONDE ela troca, nao posso poner un breakpoint numa linha do codigo.... 
(perdon por meu portugues e bem ruim).
----------------------------------
Hay forma de parar un debug cuando una variable cambia de valor? No se donde ocurre, quiero que el debug se detenga donde sea que la variable cambia. No puedo usar un break condicional, porque no se en que linea ponerlo.
----------------------------------
Is there a way to make the debugger stop when a variable changes value? I do not know where/when/how it changes, hence i cannot put a breakpoint on any line of the source code.

**Comment by ricardomansano** [comment]
Boa tarde,

Entendi sua ideia, mas não há como ser implementada, a ferramenta neste caso é o breakpoint condicional, e você precisará colocar hooks em todas os assigns desta variável nos seus fonte.

Sei que isso dará um certo trabalho mas irá resolver sua necessidade.

Mais informações em:
https://code.visualstudio.com/docs/editor/debugging#_conditional-breakpoints

**Comment by izacsc** [comment]
Não sei se é uma limitação do nosso binário para implementar  mas, só para conhecimento, o data breakpoint faz parte da especificação do DAP: 
https://github.com/microsoft/vscode/issues/58304

Parece que a partir da versão 1.34 ele foi implementado:
https://microsoft.github.io/debug-adapter-protocol/changelog

**Comment by danielbolognani** [comment]
Bom dia @izacsc , só para esclarecer melhor, isso hoje não é suportado pelo Appserver, portanto não temos como fazer isso no VSCode sem o próprio appserver ter esse suporte.
Abs!
