### ISSUE TITLE
Totvs CodeAnalisys

### ISSUE THREAD

**Issue by luizhj** [totvs/tds-vscode#78]
Existe algum guia de melhores práticas de desenvolvimento em ADVPL que vão de encontro com as validações feitas pelo Totvs CodeAnalisys e que possa ser tornada publica para que possamos seguir?

Sei que essa não é exatamente uma issue do tds-vscode, mas acho que a médio e longo prazo a extensão já poderia fazer algumas validações dessas boas práticas como visual studio faz para c#.

**Comment by matheus-sales** [comment]
Olá @luizhj pelo que sabemos não há esse guia. 

Mas a equipe tinha uma iniciativa de análise estática de código. Por enquanto não está no nosso RoadMap essa funcionalidade.

**Comment by ricardomansano** [comment]
Boa tarde @luizhj ,

Esta questão vem sendo tratada a algum tempo pelo time de GCAD da TOTVS, e esta desacoplada das nossas plataformas de desenvolvimento, VSCode/Eclipse.

Então, este assunto realmente não deve ser tratado neste forum.

Muito grato pelo sua sugestão.
