### ISSUE TITLE
Versão 1.3.3 - Não abre debug

### ISSUE THREAD

**Issue by Smmartinez** [totvs/tds-vscode#780]
Bom dia! Realizei a instalação para teste da versão 1.3.3 mas quando vou abrir o debug via F5 ou pelo lauch aparece uma mensagem de não foi possível conectar no servidor. Eu voltei para a versão 1.3.2 e conecta e ativa o DEBUG sem problema.

![Sem título](https://user-images.githubusercontent.com/4532855/130636488-5550a1e6-1e36-4b9d-b12c-bdd8e2a9e458.png)

**Comment by danielbolognani** [comment]
Boa tarde @Smmartinez , não pegamos esse tipo de problema durante os nossos testes iniciais, de qualquer forma poderia reinstalar a versão 1.3.3?
https://github.com/totvs/tds-vscode/releases/tag/v1.3.3
Tivemos uma nova pré-release ontem, então por favor faça novamente o download e a instalação. Se ainda continuar com problemas, poderia gerar os logs para analisarmos?
https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs
Principalmente o daplog.log

**Comment by Smmartinez** [comment]
Boa tarde! Acabei de baixar e não funcionou.

[Pertech.zip](https://github.com/totvs/tds-vscode/files/7042007/Pertech.zip)

**Comment by danielbolognani** [comment]
Boa tarde, só para entender um pouco melhor, qual a versão exata do Smartclient?
Para isso execute o Smartclient com o parâmetro -t
https://tdn.totvs.com/pages/viewpage.action?pageId=6066051

Pode anexar também o servers.json?

**Comment by Smmartinez** [comment]
Segue os dados solicitado.

[Área de Trabalho.zip](https://github.com/totvs/tds-vscode/files/7042391/Area.de.Trabalho.zip)

**Comment by danielbolognani** [comment]
Obrigado pelos arquivos @Smmartinez , descobrimos o problema e já corrigimos, por enquanto pode ficar na versão 1.3.2 que a próxima pré-release/release final já vai ter essa correção

**Comment by Smmartinez** [comment]
Maravilha que bom que ajudei!
