### ISSUE TITLE
Bug Versão 1.3.3 - Não Compila

### ISSUE THREAD

**Issue by maximinocastro** [totvs/tds-vscode#781]
Boa tarde Prezados,

 Após atualizar a versão 1.3.2 para 1.3.3 começou a ocorrer o seguinte bug,

Depois de algum tempo utilizando o plugin durante o dia, simplesmente ele não compila mais, mesmo desconectando o server e conectando novamente continua a não compilar.

Quando ocorre esse BUG as opções de compilar WorkSpace/Folder/File simplesmente somem.

![image](https://user-images.githubusercontent.com/42280023/130664206-7977d28c-4e91-485c-9667-bc4a48b95806.png)

Para que volte a funcionar eu tenho que fechar o VsCode e abrir novamente e já a 4x que isso acontece desde que atualizei.

**Desktop (please complete the following information):**
 - Windows 10 Pro arquitetura 64 bits

**Appserver (please complete the following information):**
Dados do Server 

Versão: TOTVS Serviços
Build AppServer: 7.00.191205P-20210114 - 64 bits
Nome do servidor: LABOR-APP1
Sistema operacional: Windows Server 2016
Appserver version: 19.3.1.5
Build DBAccess: 20200606-20201110
Release do RPO:  12.1.027 - Out  2020
Release do dicionário: 12.1.027 - Out  2020
Local files: ctree
License server: 2014 - 3.2.2
DB DataBase: MSSQL7
DB API Build: 20200606-20201110

**Comment by danielbolognani** [comment]
Boa tarde @maximinocastro , a versão v1.3.3 está em testes internamente e essa situação já deve estar corrigida. Ontem no final do dia foi publicado novamente a versão 1.3.3 como pré-release. Se puder, por favor reinstale a partir do VSIX:
https://github.com/totvs/tds-vscode/releases/tag/v1.3.3

**Comment by maximinocastro** [comment]
Perfeito vou reinstalar
