### ISSUE TITLE
Aplicar patch MacOSX

### ISSUE THREAD

**Issue by alanFaccin** [totvs/tds-vscode#783]
Ao tentar aplicar patch, o validador reclama do Case Sensitive. Mas no Mac mesmo sendo base Unix é possível utilizar patch com Upper Case. 

Já havia aberto um chamado no sobre a mesma situação e havia sido corrigido:

https://github.com/totvs/tds-vscode/issues/386

<img width="2152" alt="image" src="https://user-images.githubusercontent.com/9438826/131327410-cb505405-7fa9-4b0b-afa3-2c289b550672.png">

<img width="299" alt="image" src="https://user-images.githubusercontent.com/9438826/131327867-056fa7fb-6bc6-4ad0-ae45-6bf739162821.png">

<img width="629" alt="image" src="https://user-images.githubusercontent.com/9438826/131328040-2d41edd3-b4a5-4a56-a0dc-3eafe777c35b.png">

**Comment by danielbolognani** [comment]
Bom dia @alanFaccin , só para confirmar, qual a versão da Extensão utilizada?

**Comment by alanFaccin** [comment]
Bom dia na versão 1.3.2 o problema não ocorre, porém nesta versão fica apresentando o erro abaixo no console, a cada edição de linha. 

 SEM: 0x7fdf86168a78 init sem: 0x7fdf86168a80 ret: -1 err: 78 

<img width="2160" alt="image" src="https://user-images.githubusercontent.com/9438826/131333887-cf255f91-e4ee-410a-a8da-303681344d76.png">

Além de ter problemas na depuração, onde o smart client trava e não consigo mais matar o processo, assim tive que voltar para a versão v1.2.5 a qual não estava com este Problema.

**Comment by danielbolognani** [comment]
Esse problema de edição (mensagens de erro) já foi endereçado e está resolvido na próxima versão. Se preferir adiantar, já está disponível como pré-release:
https://github.com/totvs/tds-vscode/releases/tag/v1.3.3

Favor abrir problemas relacionados apenas a última versão disponível no MarketPlace.
