### ISSUE TITLE
Generación de cliente de Web Service

### ISSUE THREAD

**Issue by albertordgz** [totvs/tds-vscode#786]
Generación de cliente de WS.
(Ctrl+Shift+P TOTVS: Generate WS Protheus)

No se obtiene respuesta completa al consumir el Web Service de Nómina del proveedor tecnológico The Factory HKA de Colombia. El problema es que en la respuesta del WS, no se recuperan los mensajes de validaciones y rechazos que deben estar en un objeto de tipo array, éste siempre está vacío:
![ws1](https://user-images.githubusercontent.com/57117390/131897094-c2bcb834-f1c5-43d7-a2fb-2e3f187cae38.png)

Tenemos funcionando otro cliente de consumo de WS del mismo proveedor para factura electrónica. Ambos WS, de nómina y de factura electrónica, usan el método SOAP.
Comparando el código fuente de las rutinas de nómina y de facturación, encontré una diferencia en el método _**SOAPRECV**_ del servicio _**Service_ArrayOfstring**_, el cual contiene los mensajes de validaciones y rechazos:

Cliente WS de Facturación (WSNFECol.prw):
![ws2-fac](https://user-images.githubusercontent.com/57117390/131898567-74d2a666-eb09-47f0-a8a9-a23e95a62c8e.png)

Cliente WS de Nómina (WSNominaCol.prw):
![ws3-nom](https://user-images.githubusercontent.com/57117390/131898593-37b85516-6515-4124-9add-53f0162d12e1.png)

Como se puede ver, la diferencia es el segundo parámetro que se envía a la función _WSAdvValue()_.

En la fuente de nómina WSNominaCol modifiqué esa llamada de la función WSAdvValue() para enviar el segundo parámetro como "**_B_STRING**" (quedando igual que en la fuente WSNFECol), después de compilar, el problema quedó corregido en la respuesta del WS. Ahora ya muestra el arreglo de mensajes:
![ws4-array2](https://user-images.githubusercontent.com/57117390/131898916-48e12999-f8d8-429b-b849-81308d00f374.png)

Cabe señalar que ejecutando la petición en la aplicación _SOAPUI_, la respuesta siempre incluye los mensajes de validaciones y rechazos:
![ws5-soapui](https://user-images.githubusercontent.com/57117390/131898998-4a67d261-7944-4750-b768-defaf85113e2.png)

Hice una prueba más, volviendo a generar el cliente de WS para Factura Electrónica, el resultado es que ahora genera el mismo problema!!

Siguen las url's de prueba de los servicios web desde donde se generan los clientes de consumo de WS:

Factura electrónica:
http://testubl21.thefactoryhka.com.co/ws/v1.0/Service.svc?wsdl

Nómina electrónica:
http://demo-nomina-soap.thefactoryhka.com.co/Service.svc?wsdl

**Desktop:**
 - OS/Architecture: Windows 10 64 bits

**Appserver:**
 - Build:  7.00.191205P - Mar 31 2021 - 17:47:11
 - OS/Architecture: Win 64b
 - SVN Revision: 30184
 - Build Version: 19.3.1.6

**Comment by danielbolognani** [comment]
Boa tarde @albertordgz,
A geração de WSDL é feita pelo Appserver. A extensão TDS-VSCode é apenas o frontend para enviar a URL para o Appserver gerar o código ADVPL/WS, portanto será necessário abrir o chamado diretamente para a equipe de Appserver.
Por aqui infelizmente não conseguiremos te ajudar.
Abraços.
