### ISSUE TITLE
Botões APPLY e APPLY/CLOSE da aplicação de patchs estão editáveis

### ISSUE THREAD

**Issue by vanessamelo83** [totvs/tds-vscode#787]
**Describe the bug**
Ao acessar a opção de aplicação de patchs identificado que os botões "apply" e "apply/close" estão editáveis.
Alinhei a abertura de issue com Mansano e com Alan.

**To Reproduce**
![Binário](https://user-images.githubusercontent.com/57493625/131904265-0064f348-e0f8-4c8d-8e2f-21772baaf0da.JPG)
[VSCODE.zip](https://github.com/totvs/tds-vscode/files/7101265/VSCODE.zip)
![Plugin](https://user-images.githubusercontent.com/57493625/131904267-fbfe094f-f277-4822-baf8-6ea90367bfd8.JPG)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS/Architecture: [e.g. Windows 64 bits]

**Appserver (please complete the following information):**
 - Build (with date): [e.g. Build 7.00.170117A - Jun 28 2019 - 11:16:56]
 - OS/Architecture: [e.g. Linux 64 bits Ubuntu]
 - Build Version [e.g. 17.3.0.13]

**Additional context**
[](url)

**Comment by brodao** [comment]
Resolvido no chamado interno [DTCLIENT01-2896](https://jiraproducao.totvs.com.br/browse/DTCLIENT01-2896).
Revistos outras definições semelhantes.

**Comment by lwtnb-wrk** [comment]
@vanessamelo83 Estamos com uma versão pré-release disponível com a correção deste problema. Se puder testar e validar a correção isso auxiliará na liberação oficial.
https://github.com/totvs/tds-vscode/releases/tag/v1.3.4

**Comment by vanessamelo83** [comment]
Olá @lwtnb-wrk  realizei os testes e agora está OK.
Obrigada
