### ISSUE TITLE
Aplicação template CDV

### ISSUE THREAD

**Issue by pamelabsouza** [totvs/tds-vscode#788]
Boa tarde, 

Ao aplicar o template do CDV que ultima versão do portal, está dando erro de falha de conexão no server mostra a msg:
[INFO ][SERVER] [Thread 20840] JOB Thread finished [-PSWADMIN]
[VDRPORT] 210902_183314 45E0 BPC2249 E x 04 ctx:008 error 64 (operacao em conexao fechada remotamente) on reception from client 127.0.0.1:60514

[WARN ][SERVER] [THROW][Thread  11128] tConnnErrorException (8:Erro de comunicacao: Erro de sincronismo) on D:\bamboo\xml-data\build-dir\TP11-OF19310-TECXWIN64\lib_comm\msgmanager.cpp:472

e Vscode perde a conexão com o RPO
 
att,
[CDV12-20180412.zip](https://github.com/totvs/tds-vscode/files/7101893/CDV12-20180412.zip)

**Comment by brodao** [comment]
Favor informar versão do TDS-VSCode e do appServer.
