### ISSUE TITLE
[improvement] Viabilizar a criação de um novo RPO ("zerado")

### ISSUE THREAD

**Issue by specs439** [totvs/tds-vscode#79]
**Sugestão de melhoria**

Viabilizar uma forma de conectar em um ambiente sem RPO, para então ser possível criar um "do zero".
Isso era possível através do TDS, por exemplo, e é extremamente útil para nossa suíte de testes!
Seria interessante ter essa possibilidade tbm nessa nova ferramenta.

Tks!..

**Comment by ricardomansano** [comment]
Boa tarde @specs439 ,

Na verdade esta opção é disponibilizada apenas ao time de GCAD, o único autorizado à criação de RPOs vazios, já que o RPO deve ao mínimo ter as funções de validação de usuário, caso contrário será inválido.

Agradecemos a sugestão mas a feature não será implementada por motivos de segurança.
