### ISSUE TITLE
Parâmetro "dpiMode = true" no lauch.json não funciona

### ISSUE THREAD

**Issue by fmercurio** [totvs/tds-vscode#791]
Olá,

Estou tentando passar o parâmetro "-DPI" do SmartClient.exe no debug porém sem sucesso.

Verifiquei que configurando o depurador via "TOTVS: Laucher Configuration" existe um argumento chamado -DPI, habilitei-o e o dpiMode = true foi incluído no laucher.json, porém nem assim o SmartClient.exe sobe com o -DPI habilitado no Debug.

![image](https://user-images.githubusercontent.com/15571697/132568949-b862cc5b-2335-4f2f-bbd0-fd41cf9d234c.png)

Segue abaixo o lauch.json completo:

`{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Depuração do idioma TOTVS",
			"program": "${command:AskForProgramName}",
			"programArguments": [
				"-DPI"
			],
			"cwb": "${workspaceFolder}",
			"smartclientBin": "C:\\TOTVS\\PROTHEUS\\microsiga_hml\\protheus\\bin\\smartclient_win\\smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true,
			"enableMultiThread": false,
			"enableProfile": false,
			"isAccessibilityMode": false,
			"doNotShowSplash": false,
			"openglMode": false,
			"dpiMode": true,
			"language": "",
			"ignoreFiles": false
		}
	],
	"lastPrograms": [
		{
			"label": "SIGAMDI"
		}
	],
	"lastProgramExecuted": "SIGAMDI"
}`

**Comment by lwtnb-wrk** [comment]
@fmercurio Veja em [Gerando logs](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs) como gerar e nos envie os logs para análise. Tanto os logs de LS quanto os de DA.
