### ISSUE TITLE
Erro na Primeira linha 

### ISSUE THREAD

**Issue by BrunoSingelo** [totvs/tds-vscode#792]
Ao abrir um fonte,  acusa o seguinte erro na primeira linha do código:

Systax Error Linter

Já realizamos a configuração dos includes para ter certeza que não havia nenhum problema, porém o erro persiste, também foi feito a reinstalação da extensão, sem sucesso também.

![erroLinter](https://user-images.githubusercontent.com/71949549/132698466-82b9cdef-e223-4439-996b-2d3a4cb89f81.PNG)

É necessário realizar alguma configuração adicional para que não apresente mais esse erro?

Desde já, agradeço a atenção.

**Comment by brodao** [comment]
Favor consultar https://github.com/totvs/tds-vscode/blob/master/CHANGELOG.md#vers%C3%A3o-130

**Comment by BrunoSingelo** [comment]
como eu vou realizar as functions sem adicionar o #include 'totvs.ch' ? poderia me explicar ou me dar um exemplo, porque sempre utilizamos o #include 'totvs.ch'. 

Desde já, agradeço a atenção.

**Comment by danielbolognani** [comment]
Boa tarde @BrunoSingelo , por acaso vc já tentou compilar esse arquivo? Se sim, o erro sumiu ou continua o mesmo erro?
Se o erro sumir após compilar, teria como nos passar esse arquivo para análise? Acontece apenas com esse arquivo?

Só garanta que a configuração de include esteja correta (Ctrl-Shift-P e procure "TOTVS: Include").

**Comment by BrunoSingelo** [comment]
Boa tarde @danielbolognani, foi um erro no ENDCASE que faltava, porem o Linter não exibia o erro no código apenas exibindo o aquele mensagem de erro na imagem acima, agradeço a atenção (para simular o erro e só remover o ENDCASE).

`
 #INCLUDE 'totvs.ch'
User Function M410STTS()

	Local _nOper := PARAMIXB[1]

	DO CASE

	CASE _nOper == 3 //inclusao

		if(Reclock("SC5",.F.))
			SC5->C5_XXLOGUI := cUserName
			SC5->(Msunlock())
		endif

	CASE _nOper == 4 //alteracao

		if(Reclock("SC5",.F.))
			SC5->C5_XXLOGUA := cUserName
			SC5->(Msunlock())
		endif

	CASE _nOper == 5 //exclusao

		if(Reclock("SC5",.F.))
			SC5->C5_XXLOGUE := cUserName
			SC5->(Msunlock())
		endif

	CASE _nOper == 6 //copia

		if(Reclock("SC5",.F.))
			SC5->C5_XXLOGUC := cUserName
			SC5->(Msunlock())
		endif

	CASE _nOper == 7 //devolucao de compras

		if(Reclock("SC5",.F.))
			SC5->C5_XXLOGUD := cUserName
			SC5->(Msunlock())
		endif

	ENDCASE //faltava o fechamento do laço e o plugin mostrava erro no include

Return Nil
`

**Comment by danielbolognani** [comment]
Opa, que bom que achou o problema. 
Infelizmente o Linter só consegue analisar exatamente o que o compilador analisa, se acusa o mesmo erro na compilação de fato, precisa abrir um chamado para a equipe do Appserver diretamente.
Abs!
