### ISSUE TITLE
Debugar VSCODE no PDV (front loja) 

### ISSUE THREAD

**Issue by Adailton-lanca** [totvs/tds-vscode#794]
Olá!
Estou precisando debugar pontos de entrada na estação de PDV do front loja.
Quando estou entrando diretamente no smart client passo os parametros abaixo, mas quando entro via VSCODE depurando, nao estou conseguindo.

C:\CAIXA06\Protheus\bin\smartclient_32\smartclient.exe -P=SIGAFRT -E=MP11PDV -C=TCP -A= -A=006 -M

![image](https://user-images.githubusercontent.com/64661146/133107102-ca65b5cc-ca0e-4cdb-8c01-ca77284be6c1.png)

Estou passando os parametros da maneira abaixo:
![image](https://user-images.githubusercontent.com/64661146/133107606-adfa5b4a-4521-41e9-b2e5-9e7cd6e36c79.png)

[logs.zip](https://github.com/totvs/tds-vscode/files/7155268/logs.zip)

**Comment by brodao** [comment]
A passagem de parâmetros ao informar o programa a executar equivale ao argumento -a do SC.
Veja nota em (https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md#vari%C3%A1veis-de-substitui%C3%A7%C3%A3ovariable).

Os demais argumentos são automáticos e montados com base na conexão atual. Você precisa estar conectado ao ambiente mp11pdv. NO seu caso, é algo como sigaFrt("006")

**Comment by brodao** [comment]
Não conheço o sistema PDV, mas se você esta tentando depurar, coloque um ponto de parada no seu código e tente verificar por alguma variável com apoio da pilha de execução (call stack).

**Comment by Sergio-Infostore** [comment]
Para depurar como PDV:

"args": [
"-A= -A=006"
],
"label": "SIGALOJA"

**Comment by Ti-Portao** [comment]
Complementando o que o @Sergio-Infostore disse.
Para fazer debug em Totvs PDV usando a rotina STIPOSMAIN e usando a impressora fiscal ou não fiscal corretamente, é necessário que o launch.json esteja com a configuração abaixo.

Para explicar melhor  o "003" representa a estação, no smartclient para abrir o sistema normal, o smartclient estaria assim 
-a= -a=003

	"lastPrograms": [
		{
			"args": [
				"",
				"003"
			],
			"label": "SIGAFRT"
		}
	],

**Comment by Ti-Portao** [comment]
Agora com o WebApp passem assim no Vs Code SIGAFRT&A=&A=MINHAESTACAO

![Image](https://github.com/user-attachments/assets/aa611821-9814-4d93-9c49-88e5cd090afc)

**Comment by lwtnb-wrk** [comment]
Apenas complementando que isso já deveria ocorrer assim caso o launch.json esteja configurado como indicado acima, passando o 1o argumento vazio ("")

"lastPrograms": [
	{
		"args": [
			"",
			"003"
		],
		"label": "SIGAFRT"
	}
],
