### ISSUE TITLE
INFO: ExitCode=-1073741819 ExistStatus=CancelExit

### ISSUE THREAD

**Issue by lkznogueira** [totvs/tds-vscode#795]
Olá..

Após startar o DEBUG utilizando SIGAMDI, faço o login normal, seleciono o módulo e do nada tudo se encerra dando essa mensagem no console..
![image](https://user-images.githubusercontent.com/12913181/134053225-fd3c7076-9062-4afc-af7f-59351d348d2a.png)

Appserv -> Windows Server
Vscode -> Rodando em uma máquina separada com Windows 10.

Segue dados do Servidor e Remote
![image](https://user-images.githubusercontent.com/12913181/134052094-6ecb64d2-f060-4772-8464-817c39dd7502.png)

Depois de conversar com alguns desenvolvedores e clientes foi levantado que esse problema não acontece com a versão 1.2.1 da extensão.  Imagino que deva ter uma quantidade grande de pessoas que esteja trabalhando com a versão desatualizada por conta desse problema.

Logs VsCode gerados a partir do tutorial (https://github.com/totvs/tds-vscode#capturador-de-logs)
[tdsSupport.zip](https://github.com/totvs/tds-vscode/files/7197810/tdsSupport.zip)

**Comment by danielbolognani** [comment]
Boa tarde @lkznogueira 
Por acaso o windows 10 é uma VM ou está sendo acessado via alguma ferramenta de acesso remoto?
Se sim, já temos isso mapeado e o problema está na renderização do TWebEgine via opengl.

**Comment by lkznogueira** [comment]
@brodao 

Segue os Logs
[Workspace.zip](https://github.com/totvs/tds-vscode/files/7198958/Workspace.zip)
 
@danielbolognani 
Em ambos apresentarem o mesmo problema..

O que percebi é que esse erro é intermitente tem hora que acontece todo segundo e as vezes vc consegue depurar normal sem erro algum.

**Comment by danielbolognani** [comment]
@lkznogueira Esse problema a principio apenas ocorre em ambiente Virtualizado ou via acesso remoto, máquina física não temos relatos.
Para contornar, dentro da pasta do Smartclient/dlls514 existe um arquivo com o nome opengl32sw.dll copie ele para a raiz do Smartclient e renomeie para opengl32.dll. Então na pasta Smartclient vai existir o arquivo opengl32.dll e na pasta Smartclient/dlls514 vai existir o arquivo opengl32sw.dll
Dessa forma, força o Smartclient a utilizar a renderização via software e deve resolver o seu problema até uma próxima versão ser gerada com a correção.
At.te

**Comment by lkznogueira** [comment]
@danielbolognani Mto Obrigado.. Irei usar desta forma.
