### ISSUE TITLE
Erro na versão 1.3.4

### ISSUE THREAD

**Issue by maximinocastro** [totvs/tds-vscode#796]
Erro ao tentar compilar fonte e após esse erro o sistema não deixa mais conectar em nenhum ambiente.

E pra voltar a funcionar tenho que abrir e fechar o VSCode.

Segue abaixo o erro:

![image](https://user-images.githubusercontent.com/42280023/134172931-abd1a9e1-9a91-4231-9149-1ac3596716dc.png)

Versão: TOTVS Saúde
Build AppServer: 7.00.191205P-20210114 - 64 bits
Nome do servidor: CXDFFKPRTSTCR30
Sistema operacional: Windows Server 2012 R2
Appserver version: 19.3.1.5
Build DBAccess: 20200606-20201110
Release do RPO:  12.1.025
Release do dicionário: 12.1.025
Local files: ctree
License server: 2014 - 1.03.018
DB DataBase: MSSQL
DB API Build: 20200606-20201110

**Comment by danielbolognani** [comment]
Bom dia @maximinocastro 
Quando exatamente isso começou a acontecer? Por favor [gere os logs](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs) para podermos analisar.

**Comment by maximinocastro** [comment]
@lwtnb-wrk segue as extensões instaladas.

![image](https://user-images.githubusercontent.com/42280023/134175327-a862770d-613c-4974-9250-41e1cf2da71a.png)

**Comment by lwtnb-wrk** [comment]
@maximinocastro Nos envie os logs conforme o @danielbolognani requisitou e a versão do AppServer que está utilizando pois não reproduzimos esse problema em nossos ambientes.

**Comment by maximinocastro** [comment]
O Log eu já coloquei o script agora é esperar acontecer o erro.

Segue os dados do AppServer:

Appserver version: 19.3.1.5
Build DBAccess: 20200606-20201110
Release do RPO: 12.1.025
Release do dicionário: 12.1.025
Local files: ctree
License server: 2014 - 1.03.018
DB DataBase: MSSQL
DB API Build: 20200606-20201110

**Comment by DanielYampolschi** [comment]
@maximinocastro Me tira uma dúvida por favor. Voce lembra se quando o erro aconteceu, você tinha aberto, no editor, algum fonte Advpl, ou se você fez a conexão com o server, clicou com o botão direito no fonte que está na árvore do lado esquerdo e mandou compilar?

**Comment by maximinocastro** [comment]
Puts @DanielYampolschi não lembro. Mas até agora o erro ainda não ocorreu.

**Comment by lwtnb-wrk** [comment]
@maximinocastro Como o erro não voltou a ocorrer imagino que tenha sido algo pontual, então vou fechar esta issue.

Eu tambem percebi somente agora que usa um Windows Server, se o tds-vscode estiver rodando nesse SO, ele pode não funcionar adequadamente mesmo, pois é um SO que não é homologado para o uso do tds-vscode.

**Comment by maximinocastro** [comment]
Perfeito
