### ISSUE TITLE
Lentidão na compilação de artefatos na 12.1.33 (Harpia)

### ISSUE THREAD

**Issue by rafaelkleestadt** [totvs/tds-vscode#797]
**Describe the bug**
Ao compilar fica 2 minutos em "Committing end build." até finalizar com "Recompile finished." 

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/91149696/134217669-e1bd938e-a8d7-4eec-a9be-4bef97299517.png)

**Desktop (please complete the following information):**
 - OS/Architecture:  Windows 64 bits

**Appserver (please complete the following information):**
 - Build (with date): 7.00.210324P - Jul  2 2021 - 04:54:27
 - OS/Architecture:  Windows 64 bits
 - Build Version: 20.3.0.0_ts33

**Additional context**

[totvsls_out.log](https://github.com/totvs/tds-vscode/files/7205085/totvsls_out.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/7205087/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/7205088/totvsls_in.log)

**Comment by lwtnb-wrk** [comment]
@rafaelkleestadt Não temos nenhuma ação neste caso.
É um demora nos processos interno do AppServer após sinalizarmos o final da compilação (end build).
E seu AppServer _ts33 já está bem desatualizado, experimente atualiza-lo e veja se o pessoal do AppServer já melhorou isso.
