### ISSUE TITLE
Intelisense omite variáveis e funções locais

### ISSUE THREAD

**Issue by Vitor-Santos-Totvs** [totvs/tds-vscode#8]
As sugestões do intelisense do plugin estão sobrescrevendo as sugestões de variáveis e funções locais, fazendo com que elas nunca sejam sugeridas. Estas sugestões costumam ser automáticas quando o plugin utilizado não tem intelisense, como o antigo plugin do advpl para vscode.

**Comment by rcarloslima** [comment]
Concordo plenamente, ajudou com algumas coisas, mas pra mim tirou um dos principais recursos que usa o vscode.

**Comment by lwtnb-wrk** [comment]
Na proxima liberacao vamos disponibilizar um atalho (Ctrl + Alt + space) para habilitar e desabilitar esse comportamento enquanto o autocomplete real não está pronto. Semana que vem deve estar disponivel.
