### ISSUE TITLE
Desenhador MVC 

### ISSUE THREAD

**Issue by giovanni77rj** [totvs/tds-vscode#800]
Olá a todos.

Alguém sabe se existe algum plugin dentro do Vusual Code que faça o mesmo processo do desenhador de telas do antigo DevStudio ?
Obrigado

**Comment by danielbolognani** [comment]
Boa tarde @giovanni77rj, tudo bem?
Essa área deve ser utilizada para problemas/sugestões relacionadas a extensão Totvs Developer Studio for VSCode e, no caso, não temos o desenhador de telas nessa extensão.
Abs!
