### ISSUE TITLE
smartclient bin not found

### ISSUE THREAD

**Issue by andremartinsti** [totvs/tds-vscode#801]
Não consigo executar o primeiro programa, estoura este erro.

**Comment by brodao** [comment]
Precisamos de mais detalhes.Que erro?

**Comment by andremartinsti** [comment]
Obrigado pelas respostas, mas esse link que mandou é a configuração padrão para começar a executar no vs-code e Tcloud ?
teriam mais links para me mandar, de como configura o vs-code com a versão cloud da totvs?

**Comment by andremartinsti** [comment]
"type": "totvs_language_debug",
			"request": "launch",
			"name": "Depuração do idioma TOTVS",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "C:/totvs/smartclient_Test/smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true

**Comment by brodao** [comment]
Como é uma user function, deve ser chamada como "u_aula"

**Comment by brodao** [comment]
A configuração é semelhante, mudando o endereço do server. Entre em contato co o Cloud para obter as informações necessárias de conexão.
