### ISSUE TITLE
Salvar Compilation Result

### ISSUE THREAD

**Issue by iba-git** [totvs/tds-vscode#802]
Sempre que preciso compilar meu projeto, no output do console mostra apenas a contagem de fontes compilados, de 100 em 100, devido ao grande número de fontes.. eu preciso de uma evidência de compilação, sei que existe a tabela compilation result que pode ser exibida ao final da compilação, mas como salvar ou copiar todos os dados nela contidos se eles não são apresentados na mesma tela.. no meu caso mostrando de 100/100 registros preciso dar Next 12 vezes para ver tudo.

Seria muito interessante um botão "Salvar" para baixar seu conteúdo para um arquivo CSV.

Ou permitir que fossem exibidos todos os registros em uma única tela, facilitando o comando Copiar

![image](https://user-images.githubusercontent.com/91420975/135130710-a3e55ffe-7dfb-46f2-86ca-c6ad5d499ace.png)

![image](https://user-images.githubusercontent.com/91420975/135130575-77c90ced-d599-491d-af2d-a58dfa7d4dee.png)

Obrigado.

**Comment by lwtnb-wrk** [comment]
@iba-git Grato pela sugestão.

**Comment by lwtnb-wrk** [comment]
@iba-git De uma olhada no TDS CLi tambem, acho que ele ja faz o que voce precisa, pois mesmo com mais de 100 arquivos ele vai informar tudo nos logs e voce pode direcionar para um arquivo de saida.
https://github.com/totvs/tds-ls/blob/master/TDS-CLi.md

**Comment by ricardomansano** [comment]
Encerrando pois não houve interesse de nenhum Dev em implementar essa melhoria
