### ISSUE TITLE
Erro ao aplicar patch em linux

### ISSUE THREAD

**Issue by klausTotvs** [totvs/tds-vscode#806]
Olá, meu nome é Klaus, eu sou da Totvs Espirito Santo. Eu sou entusiasta do Linux e tenho um ambiente de testes todo em linux (sistema operacional, banco postgres, appserver, smartclient e vscode) e quando eu tento aplicar um patch o output do vscode emite a mensagem de erro abaixo. A seção tds no appserver.ini já está com a chave allowapplypatch habilitada pro endereço ip do meu computador, mas mesmo assim continua com a mensagem de erro abaixo. 

Procurei na internet, mas não encontrei nenhuma solução pra isso.  Podem me ajudar com isso, por favor? Obrigado.

/home/ubuntu/Downloads/updates/Lib/21-08-30-LIB_LABEL_09082021_P12_LOBO/30-08-18-LIB_LABEL_09082021_P12_LOBO-TTTP120.PTM;
[Info  - 19:28:37] Starting patch validate.
[Info  - 19:28:37] Patch file: /home/ubuntu/Downloads/updates/Lib/21-08-30-LIB_LABEL_09082021_P12_LOBO/30-08-18-LIB_LABEL_09082021_P12_LOBO-TTTP120.PTM
[Info  - 19:28:37] Starting build for environment p12prd.
[Error - 19:28:37] File could not be copied to the server.
[Error - 19:28:37] Patch validate could not be executed. Server returned: Patch file /totvs/protheus/protheus_data/p12prd//tmptdsubuntu/30-08-18-lib_label_09082021_p12_lobo-tttp12010-10-2021-19-28-37.ptm not found
[Info  - 19:28:37] Aborting end build (rollback changes).
[Info  - 19:28:37] Patch validate finished.
[Error - 19:28:37] Patch validate could not be executed. Possible RPO in use.

**Comment by lwtnb-wrk** [comment]
@klausTotvs O sistema de segurança do Linux é bem mais elaborado e pode estar impedindo a cópia do arquivo por questões de permissões. Certifique-se de que tem as devidas permissões nas pastas do AppServer para o usuário que está rodando o tds-vscode.
Além disso qual a versão do AppServer que está utilizando?

**Comment by klausTotvs** [comment]
![IMG_20211011_085031.jpg](https://user-images.githubusercontent.com/63023261/136785616-f4cdc348-8726-48a4-b608-9d4ffdaa7688.jpg)

Tinha uma chave changeencondingbeahvior ativada no general. Eu tirei. O código de erro mudou, mas a msg em si permanece a mesma.

**Comment by lwtnb-wrk** [comment]
@klausTotvs Ah, não havia entendido que já tinha mudado para outra pasta com letras minúsculas.
Enfim, parece ser então algum problema interno no AppServer, se puder ver em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar logs, nos envie para que possamos dar uma olhada.
Se possível nos envie o console.log do AppServer também. 
Nos passe mais informações sobre o seu Linux, versões e tudo mais para que possamos tentar reproduzir o problema aqui.

**Comment by klausTotvs** [comment]
> @klausTotvs Grato pelos logs, mas realmente não encontrei nada de errado nos logs do tds-vscode. Acontece que ao chamar o Patch Validate o AppServer dá erro e a execução falha (conforme apresentado em console-1234.log).
> 
> Esse patch você pegou no Suporte Downloads? Não consegui localizá-lo para testar aqui. E chegou a testar com outros patches alem desse??
> 
> De qualquer forma, nesse caso, você deverá abrir um chamado na TOTVS para o time do AppServer analisar porque a validação esta caindo, pois aparentemente não tem nada de errado no tds-vscode.

Esse é o patch acumulado do backoffice. Peguei no portal de downloads. Com o patch da lib da a mesma coisa.

Eu sei que o Ubuntu não é homologado pra protheus, então se eu abrir o chamado pode ser que o retorno seja o que eu espero. Vou preparar uma vm com uma versão do Linux homologada e aí eu faço os restes novamente e abro o chamado.

Obrigado pelo apoio.
