### ISSUE TITLE
Stop Debug e Não conecta mais no Server

### ISSUE THREAD

**Issue by maximinocastro** [totvs/tds-vscode#808]
Pessoal ao tentar parar o debug o VsCode não está derrubando ai tenho que clicar umas 3x e aparece a mensagem, "2000 milissegundos error de conexão"

**Mensagem RPO em Uso.**

[Info  - 09:47:24] Starting build for environment CXDFFK_TST_COMP07.
[Error - 09:47:24] Start build error: Start build execution failed. Please check if the server is on-line or the RPO is not in use.
[Info  - 09:47:36] Starting recompile.
[Error - 09:47:38] Retrieve connection error: An error ocurred while autoReconnect.\n\rServer: cxdffk-tst-protheus.totvscloud.com.br:33.011 [serverName]
[Info  - 09:48:26] Starting connection to the server 'Base Teste - Comp07' (cxdffk-tst-protheus.totvscloud.com.br@33011)
[Error - 09:48:28] Connection failed. Could not connect to server cxdffk-tst-protheus.totvscloud.com.br:33011.

![image](https://user-images.githubusercontent.com/42280023/137320685-72f92c45-fd72-44fe-acaf-93b7ca0085e5.png)

**Para corrigir o problema é necessário reiniciar o server.** 

Dados do Server 

Versão: TOTVS Saúde
Build AppServer: 7.00.191205P-20210114 - 64 bits
Nome do servidor: CXDFFKPRTSTBN31
Sistema operacional: Windows Server 2012 R2
Appserver version: 19.3.1.5
Build DBAccess: 20200606-20201110
Release do RPO:  12.1.025
Release do dicionário: 12.1.025
Local files: ctree
License server: 2014 - 3.3.1
DB DataBase: MSSQL
DB API Build: 20200606-20201110

**VISUAL STUDIO CODE**

Versão: 1.61.0 (user setup)
Confirmar: ee8c7def80afc00dd6e593ef12f37756d8f504ea
Data: 2021-10-07T18:13:09.652Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
SO: Windows_NT x64 10.0.19043

![image](https://user-images.githubusercontent.com/42280023/137329362-3df75dbe-2c37-4456-9f3d-b198e3564a9b.png)

**Windows 10 Pro
Sistema operacional de 64 bits,**

**Comment by amjgfarias** [comment]
As vezes isso acontece comigo tambem.

**Comment by brodao** [comment]
@maximinocastro 

Consegui reproduzir a ocorrência. Experimente desativar o webApp e reinicializar o appServer

```
[WEBAPP]
Active=0      <<<<<<<<<<<<
...
```

**Comment by brodao** [comment]
Duplicate #820

**Comment by brodao** [comment]
Aguardando geração de versão.

**Comment by brodao** [comment]
Senhores,

Efetuando testes, consigo reproduzir quando:
- Não específico a chave RPOCustom
- E no ini, tenho configurado a conexão:
``
[Drivers]
Active=TCP
Secure=SSL
MultiProtocolPortSecure=1

[TCP]
TYPE=TCPIP
Port=2029

[SSL]
TYPE=TCPIP
Port=2030
`` 
- Efetuo a conexão do TDS-VSCode na porta 2030 e ocorre erro.

Se um mudo para:
``
[Drivers]
Active=TCP
``
Passa a funcionar. 
Por um acaso um de vocês tem algo semelhante na configuração?

Grato pelo apoio

**Comment by amjgfarias** [comment]
@brodao eu nao uso rpocustom e nem SSL.

aqui esta desta forma abaixo.

appserver.ini
[Drivers]
Active=TCP
MultiProtocolPort=0
MultiProtocolPortSecure=0

Smartclient.ini
[tcp]
server=IP
port=Porta
SecureConnection=0

**Comment by maximinocastro** [comment]
@brodao Não Uso RPO Custom e nem SSL e aqui esta desta forma abaixo.

[Drivers]
Active=TCP
MultiProtocolPort=0
MultiProtocolPortSecure=0

[TCP]
Type=TCPIP
Port=33011

**Comment by brodao** [comment]
@maximinocastro 

Se usa server Harpia, favor adicionar a chave RPOCustom no sessão do seu ambiente e ver se resolve.
```
[p12]
....
RPOCUSTOM=M:\protheus\Protheus_Data\custom.rpo
```

**Comment by maximinocastro** [comment]
@brodao,

Release do dicionário: 12.1.025

**Comment by brodao** [comment]
Senhores,

Encontra-se a disposição pré release do TDS 1.3.5.
https://github.com/totvs/tds-vscode/releases/tag/v1.3.5

Agradeço retorno.

**Comment by crsgustav0** [comment]
Mesmo erro aqui, porém nao consigo debugar fontes Web Services, mesmo estando conectado a mesma porta que o serviço, coloco ponto de parada no fonte e nao para, porém tem retorno via console.log

**Comment by brodao** [comment]
@crsgustav0 

Para depurar _web services_, veja [Depuração de serviços](https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md#depura%C3%A7%C3%A3o-de-servi%C3%A7os-jobs).

**Comment by crsgustav0** [comment]
> @crsgustav0
> 
> Para depurar _web services_, veja [Depuração de serviços](https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md#depura%C3%A7%C3%A3o-de-servi%C3%A7os-jobs).

Fui instalar a versão disponibilizada como 1.3.5, comentada ali em cima e retornou o log 
```
12/11/2021 10:44:15 - Microsoft VSIX Installer
12/11/2021 10:44:15 - -------------------------------------------
12/11/2021 10:44:15 - vsixinstaller.exe version:
12/11/2021 10:44:15 - 16.9.1050
12/11/2021 10:44:15 - -------------------------------------------
12/11/2021 10:44:15 - Command line parameters:
12/11/2021 10:44:15 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\cristian.dias\Downloads\tds-vscode-1.3.5.vsix
12/11/2021 10:44:15 - -------------------------------------------
12/11/2021 10:44:15 - Microsoft VSIX Installer
12/11/2021 10:44:15 - -------------------------------------------
12/11/2021 10:44:15 - Initializing Install...
12/11/2021 10:44:17 - Detalhes da Extensão...
12/11/2021 10:44:17 - 	Identifier         : tds-vscode
12/11/2021 10:44:17 - 	Name               : TOTVS Developer Studio for VSCode (AdvPL, TLPP e 4GL)
12/11/2021 10:44:17 - 	Author             : TOTVS
12/11/2021 10:44:17 - 	Version            : 1.3.5
12/11/2021 10:44:17 - 	Description        : TOTVS Developer Studio for VSCode
12/11/2021 10:44:17 - 	Locale             : en-US
12/11/2021 10:44:17 - 	MoreInfoURL        : 
12/11/2021 10:44:17 - 	InstalledByMSI     : False
12/11/2021 10:44:17 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
12/11/2021 10:44:17 - 
12/11/2021 10:44:18 - 	SignatureState     : Unsigned
12/11/2021 10:44:19 - 	Produtos com Suporte : 
12/11/2021 10:44:19 - 		Microsoft.VisualStudio.Code
12/11/2021 10:44:19 - 			Version : 
12/11/2021 10:44:19 - 
12/11/2021 10:44:19 - 	Referências        : 
12/11/2021 10:44:19 - Detalhes da Assinatura…
12/11/2021 10:44:19 - 	Extension is not signed.
12/11/2021 10:44:19 - 
12/11/2021 10:44:19 - Pesquisando produtos aplicáveis...
12/11/2021 10:44:19 - Produto instalado encontrado - Local Global
12/11/2021 10:44:19 - Produto instalado encontrado - Visual Studio Community 2019
12/11/2021 10:44:19 - VSIXInstaller.NoApplicableSKUsException: Uma ou mais extensões são para o Visual Studio Code. Tente instalá-las no Visual Studio Code.
   em VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   em VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   em VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   em VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   em VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   em VSIXInstaller.App.Initialize()
   em System.Threading.Tasks.Task`1.InnerInvoke()
   em System.Threading.Tasks.Task.Execute()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

```

**Comment by brodao** [comment]
Você tentou instalar no Microsoft Visual Studio e não no VS-Code.
https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix

**Comment by crsgustav0** [comment]
Consegui debugar de outra manteira, sem instalar outra extensão.

no arquivo **launch.json** adicionei a tag **"enableMultiThread": true**

O que faltava para conseguir debugar através de cliente externo, Insomnia ou Postman:

```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Totvs Language Debug",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "C:\\Protheus_Remote_TESTE\\smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true,
			"enableMultiThread": true
		}
	],
	"lastPrograms": [
		{
			"args": [],
			"label": "SIGAADV",
			"description": ""
		}
	],
	"lastProgramExecuted": "SIGAADV"
}
```

Com isso bastava acessar a mesma porta que o serviço, apontando para a mesma base e realizando o debug via F5, restando apenas realizar a requisição, parando no ponto de parada adicionado.

[launch.zip](https://github.com/totvs/tds-vscode/files/7528100/launch.zip)

**Comment by danielbolognani** [comment]
Versão 1.3.5 expedida no Marketplace, se continuarem com problema fiquem a vontade para reabrir essa Task.
