### ISSUE TITLE
Cannot execute Linter. Includes not defined.

### ISSUE THREAD

**Issue by amjgfarias** [totvs/tds-vscode#809]
Prezados no plugin 1.2.1 o erro "Cannot execute Linter. Includes not defined." nâo existe.
Apos atualizacao para o 1.3.4 o erro passou a apresentar.
Todos os ambientes estao configurados os includes, pois consigo compilar normalmente.
Nâo importa a versao do appserver.

VSCode:
Versão: 1.61.0 (user setup)
Confirmar: ee8c7def80afc00dd6e593ef12f37756d8f504ea
Data: 2021-10-07T18:13:09.652Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
SO: Windows_NT x64 10.0.19044

![image](https://user-images.githubusercontent.com/35508301/137328291-02d1865b-6bf7-426f-b7c4-625229cd1945.png)

**Comment by brodao** [comment]
Essa é uma nova funcionalidade. Favor consultar [TDS: Linter](https://github.com/totvs/tds-vscode/blob/master/docs/linter.md)

**Comment by brodao** [comment]
Favor enviar as definições de servers.json (acione a engrenagem no topo da visão de servidores e cole o conteúdo).
