### ISSUE TITLE
Assistente de Dicionário

### ISSUE THREAD

**Issue by caiadofelipe** [totvs/tds-vscode#81]
Bom dia.

No TDS possui um assistente de dicionário (http://tdn.totvs.com/pages/viewpage.action?pageId=108662178) que facilita bastante o desenvolvimento.

Seria possível desenvolver o mesmo para o VSCODE?

**Comment by ricardomansano** [comment]
Boa tarde @caiadofelipe ,

Dado o fato do dicionário no Logo-Guara ser obrigatório em banco (SGDB), e por motivos de segurança, o acesso as informações deverá ser feito apenas via APSDU.

Agradecemos sua sugestão mas ela não entrará em roadmap.
