### ISSUE TITLE
ExitCode=-1073741819 ExistStatus=CancelExit

### ISSUE THREAD

**Issue by eurairapelli** [totvs/tds-vscode#810]
**Describe the bug**
  Erro ao depurar: ExitCode=-1073741819 ExistStatus=CancelExit
  Após tela de login

VSCode versão: 1.61.0

Informações do servidor:
  "buildVersion": "7.00.170117A",
  "secure": false,

Funciona na versão 1.2.1

Desktop, windows 10 64 bits

Server infor:
  Versão: TOTVS Manufatura
  Build AppServer: 7.00.170117A-20191024 - 64 bits
  Sistema operacional: Windows Server 2016
  Appserver version: 17.3.0.16
  Build DBAccess: 20181212-20190211
  Release do RPO:  12.1.025
  Release do dicionário: 12.1.025
  Local files: CTREE
  License server: 2014 - 3.2.2
  DB DataBase: MSSQL
  DB API Build: 20181212-20190724

**Comment by danielbolognani** [comment]
Boa tarde,
Esse problema a principio apenas ocorre em ambiente Virtualizado, via acesso remoto ou windows server.
A última versão do Smartclient Lobo Guara 19 (19.3.1.7) já resolve esse problema.

Para contornar, dentro da pasta do Smartclient/dlls514 existe um arquivo com o nome opengl32sw.dll copie ele para a raiz do Smartclient e renomeie para opengl32.dll. Então na pasta Smartclient vai existir o arquivo opengl32.dll e na pasta Smartclient/dlls514 vai existir o arquivo opengl32sw.dll
Dessa forma, força o Smartclient a utilizar a renderização via software e deve resolver o seu problema, de qualquer forma nossa recomendação é a atualização para as últimas versões do Smartclient Lobo Guará disponíveis no portal.
At.te
