### ISSUE TITLE
invalidafunction:SIGAMDI  plugin versão 1.3.4 após várias configurações de REST

### ISSUE THREAD

**Issue by ammarcossbo** [totvs/tds-vscode#816]
Após iniciar a configuração nos appserver.ini para servidor Rest na versão 33 simplesmente deixou de funcionar dando a mensagem invalidafunction:SIGAMDI.
Eu estava somente configurando o appserver nada demais. 
Conversando ontem com outros analistas me informaram erro similar ao meu. Tive que desinstalar o plugin e instalar novamente para voltar a funcionar

**Comment by brodao** [comment]
Favor reabrir seu chamado e completa-lo, conforme [Informações importantes....](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#informa%C3%A7%C3%B5es-importantes-ao-abrir-uma-issue).
