### ISSUE TITLE
Exportar inspetor de objetos diretamente para arquivo texto

### ISSUE THREAD

**Issue by edusfc15** [totvs/tds-vscode#82]
Boa noite,

seria possivel adicionar uma opção para exportar o inspetor de objetos e funções diretamente para um arquivo texto, sem precisar passar pela interface?

![objectinspector](https://user-images.githubusercontent.com/13476234/59469665-e0465180-8e0b-11e9-95a9-5c5f010976c5.gif)

**Comment by matheus-sales** [comment]
@edusfc15 Não é possível fazer isso. Nesse momento o foco do plugin é fazer visualmente. Essa opção de exportar diretamente será feita no tdscli. 

Há a possibilidade de você fazer um fork no código e alterar para sua necessidade. 

Qualquer dúvida estamos à disposição.
