### ISSUE TITLE
Nao consigo aplicar patch na release 33. 

### ISSUE THREAD

**Issue by ElrCandido** [totvs/tds-vscode#820]
Boa Tarde, 

Ao tentar aplicar o patch, tenho o seguinte retorno:

Tentei com outros caminhos e outras versoes (1.2.5) do Developer Studio. 
O RPO não está em uso, pois a compilação está ok. 

---------------------------v---------------------------------------------------
   //////  ////    //////  |  TOTVS Developer Studio for VS-Code
    //    //  //  //       |  Version 1.3.4
   //    //  //  //////    |  TOTVS Technology
  //    //  //      //     |
 //    ////    //////      |  https://github.com/totvs/tds-vscode
 --------------------------^---------------------------------------------------
[Info  - 16:20:30] Initializing Language Server.
[Info  - 16:20:30] Language Server initialized.
[Info  - 16:20:30] Starting reconnection to the server 'Teste33'
[Info  - 16:20:31] Secure authenticating...
[Info  - 16:20:35] User authenticated successfully.
[Info  - 16:20:35] Reconnection to the server 'Teste33' finished.
[Info  - 16:20:35] Checks the user permissions.
[Info  - 16:21:13] Applying file:///d%3A/TOTVS/P12/protheus_data/%40upd/sst1/PACOTE_DE_CORRECAO_000000_DNG-14296_12.1.33/release_piloto_000000_dng-14296_12_1_33_tttm120_hp.ptm (0/1)
[Info  - 16:21:13] Starting patch validate.
[Info  - 16:21:13] Patch file: d:/TOTVS/P12/protheus_data/@upd/sst1/PACOTE_DE_CORRECAO_000000_DNG-14296_12.1.33/release_piloto_000000_dng-14296_12_1_33_tttm120_hp.ptm
[Info  - 16:21:13] Starting build for environment teste.
[Info  - 16:21:17] Starting build using RPO token ...
[Info  - 16:21:17] Patch validated without structure problems.
[Info  - 16:21:17] Aborting end build (rollback changes).
[Info  - 16:21:17] Patch validate finished.
[Info  - 16:21:17] Starting function inspector.
[Info  - 16:21:17] Loading functions from server.
[Info  - 16:21:22] Functions loaded (Duration: 4.981000)
[Info  - 16:21:22] 120613 functions successfully retrieved.
[Info  - 16:21:22] Function inspector finished.
[Info  - 16:21:22] Starting patch info.
[Info  - 16:21:22] Patch file: d:/TOTVS/P12/protheus_data/@upd/sst1/PACOTE_DE_CORRECAO_000000_DNG-14296_12.1.33/release_piloto_000000_dng-14296_12_1_33_tttm120_hp.ptm
[Info  - 16:21:22] Starting build for environment teste.
[Info  - 16:21:25] Starting build using RPO token ...
[Info  - 16:21:25] Aborting end build (rollback changes).
[Info  - 16:21:26] Patch info finished.
[Info  - 16:21:26] Starting get patch resource.
[Info  - 16:21:26] Patch file: d:/TOTVS/P12/protheus_data/@upd/sst1/PACOTE_DE_CORRECAO_000000_DNG-14296_12.1.33/release_piloto_000000_dng-14296_12_1_33_tttm120_hp.ptm
[Info  - 16:21:26] Starting build for environment teste.
[Info  - 16:21:29] Starting build using RPO token ...
[Info  - 16:21:29] Aborting end build (rollback changes).
[Info  - 16:21:29] Getting organizations (company/branch)
[Info  - 16:21:33] Starting reconnection to the server 'Teste33_rpc'
[Info  - 16:21:33] Authenticating...
[Info  - 16:21:37] User authenticated successfully.
[Info  - 16:21:37] Reconnection to the server 'Teste33_rpc' finished.
[Info  - 16:21:37] Validating a package in Protheus application
[Info  - 16:21:37] Starting call proc ex ().
[Info  - 16:21:37] Secure authenticating...
[Info  - 16:21:38] User authenticated successfully.
[Info  - 16:21:41] Call proc ex finished.
[Warn  - 16:21:41] 
[Info  - 16:21:41] Server 'Teste33_rpc' successfully disconnected.
[Info  - 16:21:41] Starting apply patch.
[Info  - 16:21:41] Starting build for environment teste.
[Error - 16:21:45] Start build error: Server returned: 

[Error - 16:21:45] Patch validate could not be executed. Possible RPO in use.
[Info  - 16:23:45] Starting recompile.
[Info  - 16:23:45] Starting build for environment teste.
[Info  - 16:23:48] Starting build using RPO token ...
[Info  - 16:23:48] Start file recompile.
[Info  - 16:23:48] Using Includes: d:/TOTVS/P12TESTE/Protheus/include
[Info  - 16:23:48] Start secure compiling d:/TOTVS/P12/projetos/mca/compras/etiquetas/FB_ETIQC.prw (1/1).
[Info  - 16:23:49] [WARNING] Source d:/TOTVS/P12/projetos/mca/compras/etiquetas/FB_ETIQC.prw compiled with warnings and/or non fatal errors.
[Info  - 16:23:49] Committing end build.
[Warn  - 16:23:49] One or more files have warnings. See problems and logs for details.
[Info  - 16:23:49] Recompile finished.
[Info  - 16:27:48] Applying file:///d%3A/TOTVS/P12/protheus_data/%40upd/sst1/PACOTE_DE_CORRECAO_000000_DNG-14296_12.1.33/release_piloto_000000_dng-14296_12_1_33_tttm120_hp.ptm (0/1)
[Info  - 16:27:48] Starting patch validate.
[Info  - 16:27:48] Patch file: d:/TOTVS/P12/protheus_data/@upd/sst1/PACOTE_DE_CORRECAO_000000_DNG-14296_12.1.33/release_piloto_000000_dng-14296_12_1_33_tttm120_hp.ptm
[Info  - 16:27:48] Starting build for environment teste.
[Info  - 16:27:52] Starting build using RPO token ...
[Info  - 16:27:52] Patch validated without structure problems.
[Info  - 16:27:52] Aborting end build (rollback changes).
[Info  - 16:27:52] Patch validate finished.
[Info  - 16:27:52] Starting function inspector.
[Info  - 16:27:52] Loading functions from server.
[Info  - 16:27:57] Functions loaded (Duration: 5.258000)
[Info  - 16:27:57] 120613 functions successfully retrieved.
[Info  - 16:27:57] Function inspector finished.
[Info  - 16:27:57] Starting patch info.
[Info  - 16:27:57] Patch file: d:/TOTVS/P12/protheus_data/@upd/sst1/PACOTE_DE_CORRECAO_000000_DNG-14296_12.1.33/release_piloto_000000_dng-14296_12_1_33_tttm120_hp.ptm
[Info  - 16:27:57] Starting build for environment teste.
[Info  - 16:28:01] Starting build using RPO token ...
[Info  - 16:28:01] Aborting end build (rollback changes).
[Info  - 16:28:01] Patch info finished.
[Info  - 16:28:01] Starting get patch resource.
[Info  - 16:28:01] Patch file: d:/TOTVS/P12/protheus_data/@upd/sst1/PACOTE_DE_CORRECAO_000000_DNG-14296_12.1.33/release_piloto_000000_dng-14296_12_1_33_tttm120_hp.ptm
[Info  - 16:28:01] Starting build for environment teste.
[Info  - 16:28:05] Starting build using RPO token ...
[Info  - 16:28:05] Aborting end build (rollback changes).
[Info  - 16:28:05] Getting organizations (company/branch)
[Info  - 16:28:08] Starting reconnection to the server 'Teste33_rpc'
[Info  - 16:28:09] Authenticating...
[Info  - 16:28:13] User authenticated successfully.
[Info  - 16:28:13] Reconnection to the server 'Teste33_rpc' finished.
[Info  - 16:28:13] Validating a package in Protheus application
[Info  - 16:28:13] Starting call proc ex ().
[Info  - 16:28:13] Secure authenticating...
[Info  - 16:28:14] User authenticated successfully.
[Info  - 16:28:17] Call proc ex finished.
[Warn  - 16:28:17] 
[Info  - 16:28:17] Server 'Teste33_rpc' successfully disconnected.
[Info  - 16:28:17] Starting apply patch.
[Info  - 16:28:17] Starting build for environment teste.
[Error - 16:28:21] Start build error: Server returned: 

[Error - 16:28:21] Patch validate could not be executed. Possible RPO in use.
[Info  - 16:39:31] Starting patch validate.
[Info  - 16:39:31] Patch file: d:/TOTVS/P12/protheus_data/@upd/sst1/PACOTE_DE_CORRECAO_000000_DNG-14296_12.1.33/release_piloto_000000_dng-14296_12_1_33_tttm120_hp.ptm
[Info  - 16:39:31] Starting build for environment teste.
[Info  - 16:39:35] Starting build using RPO token ...
[Info  - 16:39:35] Patch validated without structure problems.
[Info  - 16:39:35] Aborting end build (rollback changes).
[Info  - 16:39:35] Patch validate finished.
[Info  - 16:39:35] Starting function inspector.
[Info  - 16:39:35] Loading functions from server.
[Info  - 16:39:41] Functions loaded (Duration: 5.446000)
[Info  - 16:39:41] 120613 functions successfully retrieved.
[Info  - 16:39:41] Function inspector finished.
[Info  - 16:39:41] Starting patch info.
[Info  - 16:39:41] Patch file: d:/TOTVS/P12/protheus_data/@upd/sst1/PACOTE_DE_CORRECAO_000000_DNG-14296_12.1.33/release_piloto_000000_dng-14296_12_1_33_tttm120_hp.ptm
[Info  - 16:39:41] Starting build for environment teste.
[Info  - 16:39:44] Starting build using RPO token ...
[Info  - 16:39:44] Aborting end build (rollback changes).
[Info  - 16:39:44] Patch info finished.
[Info  - 16:39:44] Starting get patch resource.
[Info  - 16:39:44] Patch file: d:/TOTVS/P12/protheus_data/@upd/sst1/PACOTE_DE_CORRECAO_000000_DNG-14296_12.1.33/release_piloto_000000_dng-14296_12_1_33_tttm120_hp.ptm
[Info  - 16:39:44] Starting build for environment teste.
[Info  - 16:39:48] Starting build using RPO token ...
[Info  - 16:39:48] Aborting end build (rollback changes).
[Info  - 16:39:48] Getting organizations (company/branch)
[Info  - 16:39:52] Starting reconnection to the server 'Teste33_rpc'
[Info  - 16:39:52] Authenticating...
[Info  - 16:39:56] User authenticated successfully.
[Info  - 16:39:56] Reconnection to the server 'Teste33_rpc' finished.
[Info  - 16:39:56] Validating a package in Protheus application
[Info  - 16:39:56] Starting call proc ex ().
[Info  - 16:39:56] Secure authenticating...
[Info  - 16:39:58] User authenticated successfully.
[Info  - 16:40:01] Call proc ex finished.
[Warn  - 16:40:01] 
[Info  - 16:40:01] Server 'Teste33_rpc' successfully disconnected.
[Info  - 16:40:01] Starting patch validate.
[Info  - 16:40:01] Patch file: d:/TOTVS/P12/protheus_data/@upd/sst1/PACOTE_DE_CORRECAO_000000_DNG-14296_12.1.33/release_piloto_000000_dng-14296_12_1_33_tttm120_hp.ptm
[Info  - 16:40:01] Starting build for environment teste.
[Info  - 16:40:07] Starting build using RPO token ...
[Info  - 16:40:07] Patch validated without structure problems.
[Info  - 16:40:07] Aborting end build (rollback changes).
[Info  - 16:40:07] Patch validate finished.
[Info  - 16:40:07] Starting function inspector.
[Info  - 16:40:07] Loading functions from server.
[Info  - 16:40:12] Functions loaded (Duration: 5.290000)
[Info  - 16:40:12] 120613 functions successfully retrieved.
[Info  - 16:40:12] Function inspector finished.
[Info  - 16:40:12] Starting patch info.
[Info  - 16:40:12] Patch file: d:/TOTVS/P12/protheus_data/@upd/sst1/PACOTE_DE_CORRECAO_000000_DNG-14296_12.1.33/release_piloto_000000_dng-14296_12_1_33_tttm120_hp.ptm
[Info  - 16:40:12] Starting build for environment teste.
[Info  - 16:40:16] Starting build using RPO token ...
[Info  - 16:40:16] Aborting end build (rollback changes).
[Info  - 16:40:16] Patch info finished.
[Info  - 16:40:16] Starting get patch resource.
[Info  - 16:40:16] Patch file: d:/TOTVS/P12/protheus_data/@upd/sst1/PACOTE_DE_CORRECAO_000000_DNG-14296_12.1.33/release_piloto_000000_dng-14296_12_1_33_tttm120_hp.ptm
[Info  - 16:40:16] Starting build for environment teste.
[Info  - 16:40:20] Starting build using RPO token ...
[Info  - 16:40:20] Aborting end build (rollback changes).
[Info  - 16:40:20] Getting organizations (company/branch)
[Info  - 16:40:24] Starting reconnection to the server 'Teste33_rpc'
[Info  - 16:40:24] Authenticating...
[Info  - 16:40:28] User authenticated successfully.
[Info  - 16:40:28] Reconnection to the server 'Teste33_rpc' finished.
[Info  - 16:40:28] Validating a package in Protheus application
[Info  - 16:40:28] Starting call proc ex ().
[Info  - 16:40:28] Secure authenticating...
[Info  - 16:40:29] User authenticated successfully.
[Info  - 16:40:33] Call proc ex finished.
[Warn  - 16:40:33] 
[Info  - 16:40:33] Server 'Teste33_rpc' successfully disconnected.
[Info  - 16:41:02] Starting patch info.
[Info  - 16:41:02] Patch file: d:\TOTVS\P12\protheus_data\@upd\sst1\PACOTE_DE_CORRECAO_000000_DNG-14296_12.1.33\release_piloto_000000_dng-14296_12_1_33_tttm120_hp.ptm
[Info  - 16:41:02] Starting build for environment teste.
[Info  - 16:41:06] Starting build using RPO token ...
[Info  - 16:41:06] Aborting end build (rollback changes).
[Info  - 16:41:06] Patch info finished.
[Info  - 16:48:48] Starting reconnection to the server 'Teste33_monitor'
[Info  - 16:48:48] Authenticating...
[Info  - 16:48:52] User authenticated successfully.
[Info  - 16:48:52] Reconnection to the server 'Teste33_monitor' finished.
[Info  - 16:48:52] Starting get users.
[Info  - 16:48:52] Get users finished.
[Info  - 16:48:52] Starting get connection status (Teste33_monitor).
[Info  - 16:48:52] Connection status successfully get.
[Info  - 16:48:52] Get connection status finished.
[Info  - 16:48:58] Starting get users.
[Info  - 16:48:58] Get users finished.
[Info  - 16:49:08] Server 'Teste33_monitor' successfully disconnected.
[Info  - 16:49:50] Applying file:///d%3A/TOTVS/P12TESTE/PACOTE_DE_CORRECAO_000000_DNG-14296_12.1.33/release_piloto_000000_dng-14296_12_1_33_tttm120.ptm (0/1)
[Info  - 16:49:50] Starting patch validate.
[Info  - 16:49:50] Patch file: d:/TOTVS/P12TESTE/PACOTE_DE_CORRECAO_000000_DNG-14296_12.1.33/release_piloto_000000_dng-14296_12_1_33_tttm120.ptm
[Info  - 16:49:50] Starting build for environment teste.
[Info  - 16:49:54] Starting build using RPO token ...
[Info  - 16:49:54] Patch validated without structure problems.
[Info  - 16:49:54] Aborting end build (rollback changes).
[Info  - 16:49:54] Patch validate finished.
[Info  - 16:49:54] Starting function inspector.
[Info  - 16:49:54] Loading functions from server.
[Info  - 16:49:59] Functions loaded (Duration: 5.396000)
[Info  - 16:49:59] 120613 functions successfully retrieved.
[Info  - 16:49:59] Function inspector finished.
[Info  - 16:49:59] Starting patch info.
[Info  - 16:49:59] Patch file: d:/TOTVS/P12TESTE/PACOTE_DE_CORRECAO_000000_DNG-14296_12.1.33/release_piloto_000000_dng-14296_12_1_33_tttm120.ptm
[Info  - 16:49:59] Starting build for environment teste.
[Info  - 16:50:03] Starting build using RPO token ...
[Info  - 16:50:03] Aborting end build (rollback changes).
[Info  - 16:50:03] Patch info finished.
[Info  - 16:50:03] Starting get patch resource.
[Info  - 16:50:03] Patch file: d:/TOTVS/P12TESTE/PACOTE_DE_CORRECAO_000000_DNG-14296_12.1.33/release_piloto_000000_dng-14296_12_1_33_tttm120.ptm
[Info  - 16:50:03] Starting build for environment teste.
[Info  - 16:50:06] Starting build using RPO token ...
[Info  - 16:50:06] Aborting end build (rollback changes).
[Info  - 16:50:06] Getting organizations (company/branch)
[Info  - 16:50:10] Starting reconnection to the server 'Teste33_rpc'
[Info  - 16:50:10] Authenticating...
[Info  - 16:50:14] User authenticated successfully.
[Info  - 16:50:14] Reconnection to the server 'Teste33_rpc' finished.
[Info  - 16:50:14] Validating a package in Protheus application
[Info  - 16:50:14] Starting call proc ex ().
[Info  - 16:50:14] Secure authenticating...
[Info  - 16:50:15] User authenticated successfully.
[Info  - 16:50:19] Call proc ex finished.
[Warn  - 16:50:19] 
[Info  - 16:50:19] Server 'Teste33_rpc' successfully disconnected.
[Info  - 16:50:19] Starting apply patch.
[Info  - 16:50:19] Starting build for environment teste.
[Error - 16:50:23] Start build error: Server returned: 

[Error - 16:50:23] Patch validate could not be executed. Possible RPO in use.

**Comment by brodao** [comment]
Senhores,

Efetuando testes, consigo reproduzir quando:
- Não específico a chave RPOCustom
- E no ini, tenho configurado a conexão:
 
```
[Drivers]
Active=TCP
Secure=SSL
MultiProtocolPortSecure=1

[TCP]
TYPE=TCPIP
Port=2029

[SSL]
TYPE=TCPIP
Port=2030
```
 
- Efetuo a conexão do TDS-VSCode na porta 2030 e ocorre erro.

Se um mudo para:

```
[Drivers]
Active=TCP
```

Passa a funcionar. 
Por um acaso um de vocês tem algo semelhante na configuração?

Grato pelo apoio

**Comment by brodao** [comment]
Senhores,

Efetuando mais testes, consegui reproduzir o erro ao retirar somente a chave ``RPOCustom``.

**Comment by brodao** [comment]
Senhores,

Encontra-se a disposição pré release do TDS 1.3.5.
https://github.com/totvs/tds-vscode/releases/tag/v1.3.5

Agradeço retorno.

**Comment by brodao** [comment]
Senhores,

Foi detectado uma ocorrência em appServer build 19.3.1.7 no processo de aplicação de determinados pacotes (patchs), quando o servidor esta configurado para utilizar comunicação SSL e encontra-se remoto.

Como paliativo, favor desligar o multi protocolo seguro.
Detalhes em https://tdn.totvs.com/display/tec/Application+Server+-+Porta+Multiprotocolo, tópico "Não quero utilizar a comunicação segura, o que devo fazer ?"

A disposição.

**Comment by danielbolognani** [comment]
Como o problema está do lado do appserver, não temos ação por aqui.
