### ISSUE TITLE
Integração com dicionário de dados

### ISSUE THREAD

**Issue by asreisbr** [totvs/tds-vscode#823]
Na versão do TDS para Eclipse existe a possibilidade de se visualizar informações do dicionário de dados, que ao meu ver agiliza nas consultas de tabelas e campos. Seria possível trazer essa funcionalidade para o VSCode?

**Comment by danielbolognani** [comment]
Olá, obrigado pela sugestão, mas hoje isso pode ser feito pelo APSDU/SIGACFG.
