### ISSUE TITLE
Erro de compilação em Includes - 12.1.33

### ISSUE THREAD

**Issue by IBRAMED** [totvs/tds-vscode#824]
Ao realizar a compilação de alguns fontes para a versão esta apresentando erro em alguns includes.

Erro: "C2090  File not found msobjects.ch"

Os includes ja foram atualizados com a ultima versão disponível. 
Abri um chamado na totvs, e me informaram que o problema é do VSCode.

**Comment by eduardobrust** [comment]
@IBRAMED  boa tarde amigo.
Pelo que vi do seu problema. O seu vscode já esta conseguindo conectar ao protheus na release 33.
Estou um passo anterior ao seu. eu poderia te mandar meu ini e o meu servers.json para comparar o que temos de diferente ?

**Comment by rodstephanel** [comment]
@IBRAMED Verifique como está o nome do arquivo .CH no fonte que você está tentando compilar, já peguei casos em que no fonte o arquivo .CH estava como msobject.ch, sem o 's'

**Comment by brodao** [comment]
o @rodstephanel  está correto. O nome do arquivos é sem "s".
![image](https://user-images.githubusercontent.com/949914/140399483-7ace04ad-fa89-46aa-9630-84d61bb5f3ec.png)
