### ISSUE TITLE
Aplicacao de ptm, mas o ptm ja foi copiado para o protheus_data previamente.

### ISSUE THREAD

**Issue by amjgfarias** [totvs/tds-vscode#827]
Pessoal tudo bem ?
É possível aplicar um ptm, mas esse ptm ja tenha sido copiado previamente para o protheus_data ?
Igual ao antigo IDE.
estou com um problema de lentidao ao aplicar ptm quando o mesmo é muito grande.
no vscode ele gera esse erro abaixo.
[Error - 15:36:33] File could not be copied to the server.
Desta forma eu faço a copia para o protheus_data e depois no vscode aplico esse ptm e a falha na copia nao existirá mais.
Obrigado.

**Comment by amjgfarias** [comment]
Voce pelo visto nao entendeu o problema e nem a sugestao.

em um ambiente que trabalho a aplicacao de ptm esta gerando erro "DBGCpyFile error".
eu tentei com plugin atualizado (1.3.4) e a versao 1.2.1 e mesmo assim o erro ocorre.
o appserver esta na versao mais recente do portal.

solucao paliativa que tomei aqui.
desativei o plugin 1.3.4 e instalaei o plugin do killerall "i love advpl" e com o plugin dele eu tive sucesso na aplicacao do ptm, mas com o plugin de voces nao funciona de forma nenhuma neste ambiente.

refoço aqui que o problema só esta ocorrendo com ptms acumulados com maise 10Mb de tamanho.

Obrigado.

**Comment by danielbolognani** [comment]
Boa tarde @amjgfarias 
O que o Alan quis dizer é que precisamos de mais informações para tentar reproduzir e corrigir o erro do nosso lado. A sua sugestão de já copiar o arquivo na mão antes de executar o processo de aplicação de patch não faz sentido se o processo inicial de aplicação de patch não está funcionando como deveria.

Se por exemplo, tivesse mais informações sobre o problema (qual patch ocorre isso? todos?), qual SO onde está instalado o VSCode, qual SO onde está o appserver, qual a versão exata do Appserver (existe mais de uma versão de Appserver no portal, uma Lobo Guara e outra do Harpia por exemplo). Tudo isso auxilia a gente a chegar no problema e na solução.

At.te

**Comment by lwtnb-wrk** [comment]
@amjgfarias Favor enviar os logs do tds-vscode conforme https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs
E tambem o console.log do appserver para podermos entender esse problema que esta tendo na copia do arquivo para o Appserver.
Grato

**Comment by amjgfarias** [comment]
porque o chamado foi fechado ?

**Comment by amjgfarias** [comment]
O problema ainda persiste no plugin 1.3.5, mas nao tive tempo para gerar logs para voces.
Voces precisam ter mais paciencia.

**Comment by danielbolognani** [comment]
Boa tarde @amjgfarias 
Normalmente, se passar 1 semana fechamos o chamado se estivermos sem resposta.
Mas fique tranquilo, assim que vc responder com os logs o chamado será reaberto.
Abs!

**Comment by amjgfarias** [comment]
Ok.
Obrigado pelo retorno.
Vou ver se neste fim de semana gero esses logs.
