### ISSUE TITLE
Connection failed. Could not connect to server - Release 12.1.33 do protheus

### ISSUE THREAD

**Issue by eduardobrust** [totvs/tds-vscode#828]
![error](https://user-images.githubusercontent.com/60935165/139966854-d9377f37-7992-4424-bc29-9154515b05fc.PNG)
**Desktop (please complete the following information):**
[Windows 64 bits]

***  TOTVS S/A  ***
***  www.totvs.com.br  ***
* TOTVS - Build 7.00.210324P - Oct  6 2021 - 23:33:57
* Build: 64 bits
* SVN Revision: 32672
* Build Version: 20.3.0.2

**Additional context**

Quando vou add meu server no vscode o mesmo não pede usuário e senha. somente o ambiente.
Consigo conectar com o client do protheus normalmente ao server.
Somente no vscode não consigo.
Não estou usando balance. só tenho o master configurado.

![appserver](https://user-images.githubusercontent.com/60935165/139966690-dc334d4e-e927-42d9-819b-1684c4dc2850.PNG)

![servers](https://user-images.githubusercontent.com/60935165/139966477-79dfd0a0-e28e-4d98-871d-17369366577d.PNG)

[Info  - 20:28:06] Starting connection to the server 'Harpia-master' (localhost@1234)
[Error - 20:28:06] Connection failed. Could not connect to server localhost:1234.

**Comment by brodao** [comment]
@eduardobrust 

Atualize o [TDS-VSCode](https://marketplace.visualstudio.com/items?itemName=totvs.tds-vscode) para a ultima versão (1.3.4).

Verifique no log de console se há alguma informação que possa nos ajudar. Também sugiro pegar um RPO atualizado (houve relatos semelhantes).

Caso não resolva, favor [gerar as informações](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema) e anexá-los ao chamado.

No aguardo.

**Comment by eduardobrust** [comment]
![SERVERS_V2](https://user-images.githubusercontent.com/60935165/140090614-ababe744-28b4-4b6e-aa7d-60c349f20e01.PNG)
![versao_vscode](https://user-images.githubusercontent.com/60935165/140090619-b1753ee6-434a-450b-ab2e-50319fa690ba.PNG)
![VERSAO_TDS](https://user-images.githubusercontent.com/60935165/140090623-8a33d64e-ed89-4e80-a69b-f127fb9b5c76.PNG)

Coloquei as propriedades para geração dos logs no servers.json porem nao consegui localizar na pasta do meu projeto os arquivos. 

Meu vscode e minha extensão do TDS estão atualizados.
Meu RPO do protheus é o último da release 33
já tentei colocar no servers.json. tanto localhost quanto 127.0.0.1
a porta que configurei no vscode é a porte do master do protheus que esta no ar.
Consigo conectar tanto pelo smartclient quanto pelo webbrowse.

Quando mudo para outra workspace que tem as configuracoes para release 27 meu tds conecta

**Comment by brodao** [comment]
As chaves de log e no arquivo settings.json
Experimenta remover e adicionar novamente

**Comment by brodao** [comment]
Ah, você não pode ser conectar a um server de balance. Somente em slaves.

**Comment by eduardobrust** [comment]
[totvsls.log](https://github.com/totvs/tds-vscode/files/7470429/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/7470430/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/7470431/totvsls_out.log)

Consegui gerar os logs.
Quanto a questão  do master e slave o meu ambiente do protheus não esta com balance. só tenho 1 appserver. 
Devo criar um slave e fazer o apontamento para ele ?

**Comment by lwtnb-wrk** [comment]
@eduardobrust Os logs não apresentam o problema relatado. Voce repetiu as operacoes apor habilitar a geracao de logs?
Se seu ambiente nao é Master/Slaves desconsidere essa informação. Deveria aplicar corretamente no seu AppServer único.

**Comment by eduardobrust** [comment]
@lwtnb-wrk  sim. os logs foram gerados após eu tentar uma conexão sem sucesso. uma coisa que percebo pois estou com o console do server aberto. a porta tcp que eu informo no servers.json e que esta com o serviço do protheus de pé. não passa nem um tipo de conexão com erro. como se a extensão não conseguisse nem tentar conexão com esta porta. 
Posso tentar apagar os logs e tentar uma nova conexão. mas todas as tentativas que faço não passa nada no console do protheus tb.

**Comment by eduardobrust** [comment]
@lwtnb-wrk vcs teriam um ini modelo do appserver do protheus para que eu possa comparar com o meu ? talvez o erro esteja na minha configuração do ini. apesar de tudo no protheus estar funcionando pode ser que para a extensão de vocês funcionar eu tenha que modificar alguma chave no ini.

**Comment by lwtnb-wrk** [comment]
@eduardobrust Eu confundi as issues, achei que seu problema era referente a patches.
Enfim, pelos logs realmente o tds-vscode na conseguiu se conectar ao AppServer. Acho que seu problema esta relacionado a configuração "secure".
Seu Appserver esta configurado como MULTIPROTOCOLPORTSECURE=0 (desligado) enquanto que seu Appserver (server.json) esta como "secure": true (ligado).
Assim sendo eles estão incompatíveis. Altere um deles e tente novamente.

**Comment by eduardobrust** [comment]
@lwtnb-wrk o problema de conexão foi resolvido.
porém não resolveu somente igualando MULTIPROTOCOLPORTSECURE com o secure do servers.json
Eu tive que colocar a porta do SSL  do meu ini e não a porta do TCP.
porém agora não consigo compilar uma rotina simples de teste com somente um alert nela.
[totvsls.log](https://github.com/totvs/tds-vscode/files/7475837/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/7475838/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/7475839/totvsls_out.log)
![ERRO_COMPILAR](https://user-images.githubusercontent.com/60935165/140339228-7222977b-b9b8-4560-b6ce-e56a757d9a58.PNG)


"name": "Harpia-master",
		**"port": 25001,**
		"address": "localhost",
		"buildVersion": "7.00.210324P",
		"secure": true,
		"includes": [

[Drivers]
Active=TCP
MULTIPROTOCOLPORT=1
MULTIPROTOCOLPORTSECURE=1
Secure=SSL

;PORTA SEGURA DO APPSERVER
[SSL]
Type=TCPIP
Port=25001

;PORTA PADRAO DO APPSERVER
[TCP]
TYPE=TCPIP
Port=1000

**Comment by eduardobrust** [comment]
@lwtnb-wrk  consigo entrar normalmente.
Mas pelo meu entendimento o rpo agora para customizações é separado. e o meu esta zerado pq não tenho nada compilado ainda. 
![smartclient](https://user-images.githubusercontent.com/60935165/140387256-1a949793-aa5d-4019-9c0f-38fea016e468.PNG)

**Comment by eduardobrust** [comment]
passou isso no meu server ao entrar no configurador do protheus.

[INFO ][SERVER] [04/11/2021 14:13:23] Starting Program SIGACFG Thread 11036 (Brust,DESKTOP-R380MRD)
(c:\protheusharpia\protheus\apo\tttm120.rpo, C:\PROTHEUSHARPIA\Protheus\bin\appserver_master\tlpp.rpo, C:\PROTHEUSHARPIA\protheus\apo\custom.rpo)

[WARN ][SERVER] [Thread 2664] OPEN EMPTY RPO - Environment HARPIA - File C:\PROTHEUSHARPIA\protheus\apo\custom.rpo
[INFO ][SERVER] Not loading annotation from empty env/rpo: HARPIA/C:\PROTHEUSHARPIA\protheus\apo\custom.rpo

preciso configurar annotation para compilar ?

**Comment by lwtnb-wrk** [comment]
@eduardobrust Quando da erro no tds-vscode aparece algum erro no console.log?

**Comment by eduardobrust** [comment]
@lwtnb-wrk  
processo de autenticação do tds ao appserver protheus
![processo de conexao entre o tds e o appserver do protheus para logar no ambiente](https://user-images.githubusercontent.com/60935165/140394151-0240d755-6f33-464b-828d-c39306fa4836.PNG)

processo de compilação do tds ao appserver protheus
![compilacao](https://user-images.githubusercontent.com/60935165/140394158-9408e119-68b6-40f2-8b4b-3c8ce1f9ba1e.PNG)

**Comment by lwtnb-wrk** [comment]
@eduardobrust Voce tem a chave BuildKillUsers configurada?
Se não tiver, adicione a chave BuildKillUsers=1 na seção [General] do seu AppServer, reinicie seu AppServer e tente novamente.

**Comment by eduardobrust** [comment]
@lwtnb-wrk sem palavras para agradecer a dedicação.
por isso sou fiel ao projeto de vcs. 
Muito obrigado.
![sucessoooooooooooooooo](https://user-images.githubusercontent.com/60935165/140395974-a39486cf-2586-430b-8460-ee1a6455ee49.PNG)
![rpo](https://user-images.githubusercontent.com/60935165/140395991-671efc62-e61a-4793-997f-fac3b5568dc0.PNG)

Agora é brincar e conhecer esta Ave Harpia kkkk

**Comment by crondinelli** [comment]
Meu não conecta mais ao VSCode, após atualização para 33 :

[24/11/2021 21:22:16] TOTVSVm Server started.
[VDRPORT] 211124_212304 3CB4 BPC2146 E x 01 ctx:027 MULTIPORT - error 5 unrecognized client 127.0.0.1:62677
[VDRPORT] 211124_212304 3CB4 BPC2146 E x 01 ctx:028 MULTIPORT - error 5 unrecognized client 127.0.0.1:62678
[VDRPORT] 211124_212304 3CB4 BPC2146 E x 01 ctx:029 MULTIPORT - error 5 unrecognized client 127.0.0.1:62680

Sistema está normal, meu custom está setado, mas simplesmente é como se o VsCode não achasse a porta.

**Comment by brodao** [comment]
@crondinelli 

Favor informar os dados conforme  [Gerando informações sobre o problema](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema).

No aguardo.

**Comment by viniciusgati** [comment]
> Meu não conecta mais ao VSCode, após atualização para 33 :
> 
> [24/11/2021 21:22:16] TOTVSVm Server started. [VDRPORT] 211124_212304 3CB4 BPC2146 E x 01 ctx:027 MULTIPORT - error 5 unrecognized client 127.0.0.1:62677 [VDRPORT] 211124_212304 3CB4 BPC2146 E x 01 ctx:028 MULTIPORT - error 5 unrecognized client 127.0.0.1:62678 [VDRPORT] 211124_212304 3CB4 BPC2146 E x 01 ctx:029 MULTIPORT - error 5 unrecognized client 127.0.0.1:62680
> 
> Sistema está normal, meu custom está setado, mas simplesmente é como se o VsCode não achasse a porta.

versao do appserver e smartclient incompativeis... verifica se tá igual meu rei
