### ISSUE TITLE
Geração de patch e aplicação release 33 (Harpia)

### ISSUE THREAD

**Issue by rodstephanel** [totvs/tds-vscode#829]
Bom dia pessoal,

Não se mais alguém se deparou com isso, mas segue o que encontrei na geração e aplicação de patch para a release 33:

1 - Segui a orientação da TOTVS em inserir a tag RPOCustom no appserver.ini da release 33 (https://tdn.totvs.com/display/tec/RpoCustom)

2 - Gerei um patch onde mantive a tag dessa forma: RPOCustom=D:\PROTHEUS\TOTVS_33\Protheus\apo\custom\mycustom.rpo

3 - Quando aplico o patch gerado em outra base onde o nome do RPO customizado está diferente de 'mycustom' apresenta o seguinte erro no VSCode:

[Error - 09:26:41] Patch validate could not be executed. Server returned: Path version incorrect, file MYCUSTOM can't be applied in RPO D:\PROTHEUS\TOTVS_33\PROTHEUS\APO\CUSTOM\RPOCUSTOM.RPO

4 - No caso acima a tag no appserver.ini estava como RPOCustom=D:\PROTHEUS\TOTVS_33\Protheus\apo\custom\rpocustom.rpo

Alguma sugestão do que pode ser?

**Comment by eduardobrust** [comment]
@rodstephanel bom dia amigo. vc poderia me enviar o modelo do seu ini do appserver que esta conectando com o vscode ?
estou tentando conectar o meu vscode com esta extensão tds na release 33 mas não esta conectando. 
na release 27 conecta normal. Talvez eu resolvendo este problema consigo tentar aplicar uma patch aqui e possa resolver o seu problema .

**Comment by lwtnb-wrk** [comment]
@rodstephanel Tentei reproduzir o problema, mas não ocorreu erro aqui no meu ambiente com Appserver 20.3.0.2 com o ultimo RPO "21-10-08-REPOSITORIO_DE_OBJETOS_BRASIL_12_1_33_TTTM120.RPO". 
Gerei em um ambiente com RPOCUSTOM diferente do que apliquei e aplicou sem problema.
Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analises.

**Comment by rodstephanel** [comment]
@eduardobrust Segue meu appserver.ini
[appserver.txt](https://github.com/totvs/tds-vscode/files/7477312/appserver.txt)

**Comment by rodstephanel** [comment]
@lwtnb-wrk Vou pegar as informações solicitadas e já disponibilizo.

**Comment by lwtnb-wrk** [comment]
@rodstephanel Essas bases diferentes estavam com as mesmas versões do AppServer e as mesmas versões de RPO?
Nos meus teste eu usei os mesmos AppServer e RPO então verifique se não é isso que pode estar causando essa incompatibilidade.

**Comment by rodstephanel** [comment]
@lwtnb-wrk para efeito de teste, antes de abrir a Issue, fiz exatamente isso.
Gerei o patch em minha base, apaguei o rpo customizado que é gerado, parei os serviços do appserver, renomeei o nome do RPO customizado, subi novamente os serviços do appserver e tentei aplicar o patch que tinha gerado.
Inclusive o log do VSCode que coloquei no inicio da Issue é da minha máquina.

**Comment by lwtnb-wrk** [comment]
@rodstephanel Era só para ter certeza mesmo.
E qual a build exata de seu AppServer e de quando é seu RPO?

**Comment by rodstephanel** [comment]
@lwtnb-wrk Segue:

**Informações do AppServer**	
Tipo do servidor;Console
AppServer Build;7.00.210324P-20211006
Appserver version;20.3.0.2
Servidor 64 bits;Sim
Servidor Unix;Não

**Informações da LIB**	
Versão da Lib;20211004
Data da Lib;20211006_135652
ID da Lib;94c212d6522f77c511f4ddc68641247405742f8b
Release	12.1.033
HardLock;2014
Versão do License Server;3.2.2
Versão do Protheus;TOTVS Construção e Projetos
Dicionário no banco de dados;Sim

**Comment by lwtnb-wrk** [comment]
@rodstephanel Aparentemente as versões são as mesmas que estou usando, mas não reproduzo o problema aqui.
De qualquer forma essa validação é realizada pelo AppServer e talvez acesse o FW. Mas tambem não identifiquei nenhuma grande diferença nos ambientes.

Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analises.

**Comment by rodstephanel** [comment]
Bom dia @lwtnb-wrk , fiz como solicitado no link porém não gera os logs mencionado.
Tem algo mais que eu precise configurar?

Segue como ficou meu launch.json e settings.json:

{
    "totvsLanguageServer.launch.args": [
        "--log-file=totvsls.log",
        "--record=totvsls"
    ],
    "totvsLanguageServer.welcomePage": false,
    "totvsLanguageServer.askEncodingChange": false,
    "totvsLanguageServer.askCompileResult": true,
}

******************************************************************
"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Totvs Language Debug",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "D:\\PROTHEUS\\TOTVS_27\\Protheus\\bin\\SmartClient\\smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true,
			"logFile": "${workspaceFolder}\\daplog.log"
		}
	],

**Comment by lwtnb-wrk** [comment]
@rodstephanel Realmente pelos logs não tem nenhum problema além do AppServer retornar que o patch MYCUSTOM é incompatível com o RPO.
Favor abrir um chamado na TOTVS com a equipe de AppServer para que eles possam analisar e dar um direcionamento.
Aparentemente não é nada do lado do tds-vscode pois exibimos apenas o retorno que o AppServer está enviando.
Grato pelos testes e logs.

**Comment by danielbolognani** [comment]
Bom dia @rodstephanel 
Abri um chamado para a equipe do Application Server para já adiantar esse caso, mas recomendo que seja aberto também um ticket como cliente para priorizar essa necessidade.
Abraços!

**Comment by antunesls** [comment]
Estou com o mesmo problema, foi corrigido ?

**Comment by rodstephanel** [comment]
@antunesls ainda não, como solução paliativa normalizamos o nome do RPO customizado dos clientes que atendemos.
Acabamos adotando o nome 'Custom', por ser um nome já usado pela própria TOTVS nos cliente TCloud.

**Comment by Evertonpx** [comment]
Boa noite, o problema já foi corrigido?

**Comment by rodstephanel** [comment]
@Evertonpx ainda estou seguindo com a solução paliativa de gerar o patch em um rpoCustom com o mesmo nome de onde será aplicado.

**Comment by lwtnb-wrk** [comment]
@Evertonpx Este problema ocorre na camada do AppServer, fique de olho nas liberações dos novos binários com a correção para este problema. 

Não temos nada que possamos fazer do lado do tds-vscode.
