### ISSUE TITLE
Vs code apresenta erro ao aplicar patch

### ISSUE THREAD

**Issue by luisnagasakooxi** [totvs/tds-vscode#830]
Vs Code ao tentar aplicar patch na versão 12.1.33 do Protheues, apresenta erro Possible RPO in use, mesmo sem ter ninguém conectado. Alguns patch ele aplica normalmente, outros não. Mesmo refazendo a conexão do vscode com o server, tentando aplicar um patch por vez. 

Tentar aplicar mais de um pacote de acumulados para a release 12.1.33 via vscode.

Dados do server
Dados do Server 

Versão: TOTVS Manufatura
Build AppServer: 7.00.210324P-20211006 - 64 bits
Nome do servidor: APPSERVER
Sistema operacional: Windows Server 2016
Appserver version: 20.3.0.2
Build DBAccess: 20210202-20210930
Release do RPO:  12.1.033
Release do dicionário: 12.1.033
Local files: ctreeserver
License server: 2014 - 3.3.3
DB DataBase: MSSQL
DB API Build: 20210202-20210826

Dados do remote
Remote build: 7.00.210324P-20210914
Remote version: 20.3.0.0
Remote type: 1 - QT-5.15.3 WIN

Versão da Lib:20211004
Data da Lib: 20211006_135652
Commit ID:94c212d6522f77c511f4ddc68641247405742f8b

Dicionário no banco de dados = Sim

Vs Code 1.62.0

**Comment by lwtnb-wrk** [comment]
@luisnagasakooxi O Harpia, por padrão, pede para ligar um monitoramento e com isso acaba subindo um job na inicialização.
Você tem a chave buildkillusers=1 na seção [General] de seu AppServer configurada?
Se não tem, adicione essa chave, reinicie o AppServer e repita a operação de aplicação de patches.

**Comment by luisnagasakooxi** [comment]
> @luisnagasakooxi O Harpia, por padrão, pede para ligar um monitoramento e com isso acaba subindo um job na inicialização. Você tem a chave buildkillusers=1 na seção [General] de seu AppServer configurada? Se não tem, adicione essa chave, reinicie o AppServer e repita a operação de aplicação de patches.

Muito obrigado! Deu certo aqui!
