### ISSUE TITLE
Debug sigafrt

### ISSUE THREAD

**Issue by jailtonurbanoschumann** [totvs/tds-vscode#831]
Bom dia.

Como posso efetuar um debug no ambiente sigafrt? Mantendo a conexão com retaguarda?

Estamos na versão 12.1.27 e PDV no sqlite.

**Comment by danielbolognani** [comment]
Bom dia,
A principio o processo de debug é sempre o mesmo, qual o problema ao tentar realizar o debug do SIGAFRT?

**Comment by jailtonurbanoschumann** [comment]
O smartclient simplesmente fecha.
[PDV_SQLITE.log](https://github.com/totvs/tds-vscode/files/7729195/PDV_SQLITE.log)

**Comment by danielbolognani** [comment]
Por favor [gere informações sobre o problema](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)

Pelo seu log deu para ver que o Appserver é bem antigo, aproveita e já atualiza os binários (appserver e smartclient) para as últimas versões disponíveis no portal.

Abraços!

**Comment by jailtonurbanoschumann** [comment]
Atualizei, O resultado foi o mesmo.

**Comment by danielbolognani** [comment]
Boa tarde, 
Sem [**os logs**](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema) não temos como ajudar!

**Comment by jailtonurbanoschumann** [comment]
Segue log.
[PDV_SQLITE.log](https://github.com/totvs/tds-vscode/files/7730381/PDV_SQLITE.log)

**Comment by danielbolognani** [comment]
Precisamos dos logs da extensão que devem ser gerados conforme o endereço
abaixo:
https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema



Em qui., 16 de dez. de 2021 17:59, Jailton Urbano ***@***.***>
escreveu:

**Comment by jailtonurbanoschumann** [comment]
Segue logs.
[dap.log](https://github.com/totvs/tds-vscode/files/7745008/dap.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/7745009/totvsls_out.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/7745010/totvsls_in.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/7745011/totvsls.log)

**Comment by brodao** [comment]
@jailtonurbanoschumann 

Analisei os logs e estes não apresentam nenhuma ocorrência que justifique esse comportamento, fora que no log do protheus, a sua rotina é finalizada.

Caso você esteja tentando depurar um serviço (_job_), veja [Depuração de serviços (jobs)](https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md#depura%C3%A7%C3%A3o-de-servi%C3%A7os-jobs)
```
[INFO ][SSL] [tSSLSocketAPI][Connect] Connecting SSL OK.
2021-12-16T17:59:04.126000-03:00 5660|TOTVS PDV - Conexao estabelecida com o Servidor
2021-12-16T17:59:06.302000-03:00 5660|Entrou na funcao - STDRecGenTabServer
2021-12-16T17:59:06.531000-03:00 5660|TOTVS PDV - Conexao finalizada com o Servidor
2021-12-16T17:59:07.275000-03:00 5660|
[INFO ][SERVER] [Thread  5660] JOB Thread finished [STWUPDATA-STWUPDATA]
```

Como parece ser algo específico, solicito que abra um novo chamado, informando os dados e anexe os logs, conforme [Gerando informações sobre o problema](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema).

É de suma importância, que informe os passos para reprodução ou um vídeo que demonstre a ocorrência.

No aguardo.
