### ISSUE TITLE
Compilar todo espaço de trabalho

### ISSUE THREAD

**Issue by sistemasfarroupilha** [totvs/tds-vscode#832]
**Describe the bug**
A função "Compilar todo espaço de trabalho" não está funcionando.
Usando a função "Compilar todo espaço de trabalho" alguns fontes não estão sendo compilados. 
Tem que compilar um por um.

https://user-images.githubusercontent.com/79849549/140756683-ee405224-495c-49bf-a0a8-1b6f9b4766af.mp4

Appserver:
 - Build (with date): [Build 7.00.191205P-20210522 - 64 bits]
 - OS/Architecture: [Windows Server 2016]
 - Build Version [19.3.1.7]

Extensão TOTVS vscode: v1.3.4

![image](https://user-images.githubusercontent.com/79849549/140756486-33bb3a8f-8481-44b2-b7d7-68f1d0f8183b.png)

**Comment by lwtnb-wrk** [comment]
@sistemasfarroupilha Pelo vídeo vi que ocorreu um erro FATAL em um ou mais arquivos (por exemplo o CFGA020.PRW).
Por padrão, ao ocorrer um erro FATAL ocorre o rollback e nenhuma compilação é commitada no RPO.
Você pode ou corrigir os erros FATAIS (procure os fontes com erros na aba de Problemas) ou alterar as configurações do tds-vscode para ocorrer o COMMIT mesmo com fontes que tenha erros FATAIS de compilação (nas preferencias, procure por "Commit With Error Or Warning" e marque a opção).

**Comment by sistemasfarroupilha** [comment]
@lwtnb-wrk Porque não compilar um X fonte se o Y fonte tiver erro FATAL? 
Sendo que ambos não tem relacionamento!

**Comment by lwtnb-wrk** [comment]
@sistemasfarroupilha Partimos de um pressuposto que os fontes de um workspace são interdependentes e podem causar comportamentos inesperados caso apenas uma parte dos fontes forem compilados (e comitados) no RPO, porem não temos como saber que eles não tem relacionamento. Mas caso o desenvolvedor tenha um cenário em que isso não ocorra, ele pode alterar isso através da configuração que mencionei.
Se seus projetos não tem dependências como parecem ser o caso, você pode criar workspaces separados, ou compilar apenas uma pasta e não todo seu workspace.
