### ISSUE TITLE
Usar smartclient diferente para debug no vscode

### ISSUE THREAD

**Issue by luisnagasakooxi** [totvs/tds-vscode#833]
Bom dia, 

Senhores, é possível no VSCODE configurar diferentes versões de smartclient para debug?
Pergunto pois estou precisando configurar o ambiente para 12.1.33 e usando as mesmas configurações da 12.1.25 dá incompatibilidade de versão.

**Comment by luisnagasakooxi** [comment]
Resolvi criando outra workspace separada para a release 12.1.33

**Comment by danielbolognani** [comment]
Bom dia, para isso nem precisaria criar dois workspaces, só precisaria criar 2 debuggers:
https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md
Para selecionar qual smartclient utilizar é só utilizar a Combo ao lado da "engrenagem" na visão de debug.
Abs.

**Comment by luisnagasakooxi** [comment]
> Bom dia, para isso nem precisaria criar dois workspaces, só precisaria criar 2 debuggers: https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md Para selecionar qual smartclient utilizar é só utilizar a Combo ao lado da "engrenagem" na visão de debug. Abs.

Obrigado Daniel!
