### ISSUE TITLE
fonte é compilado porém no inspetor de funções aparece  #NONE#FUNCAO.PRW#NONE#

### ISSUE THREAD

**Issue by cervmalta** [totvs/tds-vscode#836]
Ao compilar um rdmake no vscode, a compilação é concluída com sucesso, porém ao consultar a função no inspetor de funções, o nome da função aparece da seguinte forma: #NONE#TST_FER1.PRW#NONE# (TST_FER1.PRW:0)

![compile](https://user-images.githubusercontent.com/94193049/141515393-fec1925a-3fec-4c4e-8d58-fbb92dd732ae.png)
[UPDBINFER.zip](https://github.com/totvs/tds-vscode/files/7529605/UPDBINFER.zip)

abaixo informações do ambiente:
2021-11-07T21:59:09.010050-03:00 15231|***  TOTVS S/A  ***
***  www.totvs.com.br  ***
* TOTVS - Build 7.00.191205P - May 22 2021 - 14:38:28
* Build: 64 bits
* SVN Revision: 30949
* Build Version: 19.3.1.7

OS: Linux version 5.4.17-2102.201.3.el7uek.x86_64 (mockbuild@host-100-100-224-4) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39.0.3) (GCC)) #2 SMP Fri Apr 23 09:05:55 PDT 2021
Oracle Linux 7.9

**Comment by lwtnb-wrk** [comment]
@cervmalta O AppServer está rodando no Linux ou o tds-vscode?
Realizei uma compilação aqui e não reproduzi o problema, mas vi que existem alguns itens no "Inspetor de Funções" com esse formato estranho "#NONE#XXX#NONE#". Porém essa informação é a que vem do AppServer então provavelmente é algo que o AppServer está formatando.
Enfim, se tiver um roteiro mais detalhado de como eu posso reproduzir o problema, favor prover mais detalhes de como devemos proceder.

**Comment by cervmalta** [comment]
@lwtnb-wrk  o Appserver está rodando no Linux.
Não consegui reproduzir esse erro com outros fontes, apenas com esse fonte está dando esse problema. Não consegui identificar se é alguma parte do código que possa estar ocasionando esse problema.

O problema dele gravar a função dessa maneira, não consigo utilizar esse rdmake, pois o nome do fonte não fica reconhecido.

**Comment by lwtnb-wrk** [comment]
@cervmalta Pode compartilhar esse fonte conosco para vermos se conseguimos reproduzir o problema aqui? O fonte anexado na issue aparentemente não é o mesmo que aparece no print da tela em anexo...
Outra questão: Você tem/usa chave de compilação?

**Comment by cervmalta** [comment]
@lwtnb-wrk  o fonte é o mesmo.
No print está com nome diferente, pois estava alterando o nome pra analisar se dessa forma o erro não é reproduzido.

**Comment by cervmalta** [comment]
@lwtnb-wrk  não tenho/utilizo chave de compilação

**Comment by lwtnb-wrk** [comment]
@cervmalta Consegue testar com um RPO zerado? Só para descartar qualquer questão em relação ao RPO?

**Comment by lwtnb-wrk** [comment]
@cervmalta E será que você tem um AppServer dessa mesma versão em um sevidor Windows para ver se é algo da versão do Linux? 
Eu digo isso pois não reproduzi no AppServer 19.3.1.7 rodando no Windows 10.

**Comment by cervmalta** [comment]
@lwtnb-wrk  não tenho um serve win.

vou tentar subir um e validar esse teste

**Comment by brodao** [comment]
Encerrado por falta de retorno.
