### ISSUE TITLE
Compilar Ponto de Entrada EICDI154...

### ISSUE THREAD

**Issue by aflitos** [totvs/tds-vscode#838]
estou seguindo a documentação do link: https://tdn.totvs.com/pages/releaseview.action?pageId=574364993
para implementar o ponto de entrada EICDI154.
Ocorre que após compilar o fonte com esse nome que contem a declaração "USER FUNCTION EICDI154()",  ao executar a rotina de Recebimento de Importação pelo menu do modulo EIC, recebo o seguinte error.log:
THREAD ERROR ([7724], marcio, CICLO-0048) 17/11/2021 16:03:52
InterFunctionCall: cannot find function EICDI154 in AppMap on __EXECUTE(APLIB090.PRW) 30/09/2021 11:46:45 line : 721
[TOTVS build: 7.00.191205P-20210522]
Called from MDIEXECUTE(APLIB260.PRW) 30/09/2021 11:46:45 line : 924
Se "descompilo", volta a acessar normal porem fico sem o p.e.

**Expected behavior**
Se existe uma documentação com um exemplo/modelo para implementar um PE, a expectiva é de que, no minimo, não cause conflito com uma função padrão.

Mais informações sobre o ambiente estão no error.log anexo, gerado após compilar o PE sugerido.
[error_log_EICDI154.txt](https://github.com/totvs/tds-vscode/files/7562691/error_log_EICDI154.txt)

**Comment by brodao** [comment]
@aflitos 

O nome do fonte que contem a _user function_ não pode ser EICDI154.PRW (isso não esta claro qual o nome do seu fonte).
Se uso esse nome, mude-o para outro e tente novamente. Se não resolver ou o nome do seu fonte já é outro, favor entrar em contato com o suporte do módulo ou de AdvPL.

A disposição.

**Comment by aflitos** [comment]
Bom dia, @brodao, o nome do arquivo do meu fonte estava como EICDI154.prw, depois de seu comentário, fiz um teste renomeando para "myEICDI154.prw", nele eu declaro User Function EICDI154(), conforme documentação do TDN (link acima)
Porém, o erro persiste.
Antes de vir aqui, abri um chamado no  suporte ADVPL e eles me responderam dizendo para que eu abrisse abrisse uma issue pelo Github.

Att.
Marcio

**Comment by danielbolognani** [comment]
Bom dia @aflitos, dei uma olhada aqui e o fonte EICDI154.prw já existe no RPO padrão, portanto o seu fonte não pode ter o mesmo nome. Como aparentemente já conseguiu compilar uma vez o fonte no RPO, ele foi sobrescrito, então o mais fácil seria pegar novamente um RPO limpo e compilar o seu fonte com outro nome (pode ser o "myEICDI154.prw").
Por acaso vc tem alguma chave de compilação configurada?

**Comment by aflitos** [comment]
@danielbolognani, não tenho chave de compilação configurada. Mas o caso é que, segundo orientação do link que passei na abertura dessa issue, para implementar o ponto de entrada, ele tem que chamar EICDI154. Eu também acho estranho o que esse link manda fazer, pois sei que não pode haver de funções com o mesmo nome (independente do nome do arquivo do fonte), principalmente conflitando com fontes do padrão que é o caso dessa EICDI154.
