### ISSUE TITLE
Informação do Plugin na Saida do VsCode 

### ISSUE THREAD

**Issue by maximinocastro** [totvs/tds-vscode#839]
Bom dia Prezados,

Reparei que após a atualização do VsCode/Plugin, TOTVSLS só está aparecendo quando eu clico no Servers.

![image](https://user-images.githubusercontent.com/42280023/142425101-900cfada-a18e-4f8e-80fc-06339abfb8fc.png)

Att.

Michael Castro

**Comment by brodao** [comment]
@maximinocastro 

Esse é o comportamento normal do VS-Code. As extensões são inicializadas somente quando necessário.
Se você não tem nenhum fonte aberto, o TOTVS LS será inicializado somente se na sessão anterior você deixou um servidor conectado e esta com a configuração de reconexão ativa OU fonte(s) TOTVS aberto na edição.

A disposição.
.

**Comment by maximinocastro** [comment]
Perfeito muito obrigado
