### ISSUE TITLE
Alinhamento do Return

### ISSUE THREAD

**Issue by Smmartinez** [totvs/tds-vscode#84]
Bom dia! Na versão 0.3.5, o alinhamento do return não esta junto a declaração da função como pode ser visto na figura.
Outra coisa que notei foi que agora ele da um espaçamento padrão.
![Sem título](https://user-images.githubusercontent.com/4532855/59603004-a2348080-90de-11e9-8b67-7d69efed6818.png)

**Comment by likid** [comment]
Já criei um PR que corrige este último Return, agora é só aguardar a análise deles para liberar no proximo release.

**Comment by matheus-sales** [comment]
> Já criei um PR que corrige este último Return, agora é só aguardar a análise deles para liberar no proximo release.

Iremos avaliar o PR. Obrigado!

**Comment by marcosnqsdev** [comment]
O "Protheus.doc" também está com identação errada também. Verifique este ponto.
![img01](https://user-images.githubusercontent.com/29627996/59607650-1cb6cd80-90ea-11e9-9bde-e816b116794f.png)

**Comment by likid** [comment]
> O "Protheus.doc" e comentários encima de funções também estão com identações erradas.
> ![img01](https://user-images.githubusercontent.com/29627996/59607650-1cb6cd80-90ea-11e9-9bde-e816b116794f.png)

Pelo teste que fiz aqui com a alteração que eu fiz para o PR, o Protheus.doc parou de avançar também.

**Comment by brodao** [comment]
Revisto processo de formatação de fontes, onde foram corrigidos:
- Alinhamento do comando return, quando este for o último de uma função/método.
- Blocos de comentários e linha comentada. Quando iniciado na coluna 1, o bloco não será indentado e se iniciado nas demais, seguirá a indentação do bloco.
- Respeito as configurações de formatação na [salva do fonte](https://code.visualstudio.com/updates/v1_6#_format-on-save) ou na colagem de blocos.
