### ISSUE TITLE
Compilação de arquivo de template(*.tpl) pelo VsCode

### ISSUE THREAD

**Issue by denisrgr** [totvs/tds-vscode#840]
Bom dia.
Estou tentando aplicar (ou compilar) um arquivo de template (*.tpl) pelo VsCode porem ele inicia o processo, mas trava e não mostra a mensagem que aplicou com sucesso ou se deu erro (evidencia em anexo). A ultima vez que tive que fazer isso era no TDS e funcionava corretamente.

Estou tentando compilar na Build 12.1.33.

Alguem poderia me ajudar?

[Evidencia_template.zip](https://github.com/totvs/tds-vscode/files/7565497/Evidencia_template.zip)

**Comment by brodao** [comment]
@denisrgr 

Informações estão incompletas. Favor informar conforme [Gerando informações sobre o problema](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema) e anexar os logs, conforme [Gerando logs](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs).
Informar também o endereço do template baixado.

No aguardo.

**Comment by denisrgr** [comment]
Bom dia,
segue as informações

**Versão do VS Code e da extensão tds-vscode**
Version: 1.62.2 (user setup)
Commit: 3a6960b964327f0e3882ce18fcebd07ed191b316
Date: 2021-11-11T20:56:38.428Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.14393

**Versão do RPO (LIB) e do TOTVS Server**
Dados do Server 

Versão: TOTVS Serviços
Build AppServer: 7.00.210324P-20211006 - 64 bits
Nome do servidor: WVHA3008
Sistema operacional: Windows Server 2016
Appserver version: 20.3.0.2
Build DBAccess: 20210202-20210930
Release do RPO:  12.1.033
Release do dicionário: 12.1.033
Local files: CTREE
License server: 2014 - 3.3.3
DB DataBase: MSSQL
DB API Build: 20210202-20210826

**Dados do Remote**

Remote build: 7.00.210324P-20210914
Remote version: 20.3.0.0
Remote type: 1 - QT-5.15.3 WIN
Versão da Lib:20211004
Data da Lib: 20211006_135652
Commit ID:94c212d6522f77c511f4ddc68641247405742f8b

**Endereço do template baixado**
https://suporte.totvs.com/portal/p/10098/download#detail/434470

**Log de compilação do VsCode**
Esta em anexo
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/7570644/totvsls_in.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/7570646/totvsls.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/7570647/totvsls_out.log)

**Comment by brodao** [comment]
Senhores,

Liberação da RC [1.3.8](https://github.com/totvs/tds-vscode/releases/tag/v1.3.8) a disposição.

**Comment by danielbolognani** [comment]
Ainda estamos analisando o problema com aplicação de template, assim que tivermos alguma novidade avisaremos por aqui

**Comment by danielbolognani** [comment]
Bom dia, a aplicação de Templates em Appserver Igual ou superior a 20.3.0.0 está descontinuada:
https://tdn.totvs.com/pages/viewpage.action?pageId=189311804

Esclarecendo um pouco melhor: Não é a extensão que não suporta mais, e sim o próprio Appserver (a extensão apenas informa que não possui mais suporte).

Se precisar dos arquivos do template favor abrir um chamado para a área responsável.


Abraços!
