### ISSUE TITLE
Cannot execute Linter. Includes not define.

### ISSUE THREAD

**Issue by thiagomeschiatti** [totvs/tds-vscode#841]
Pessoal após a atualização para a versão do pluggin 1.3.5 começou a ocorrer o erro abaixo.
Todos os servidores estão com as includes configuradas, mas ao que parece o Linter não esta conseguindo interpretá-la. 
Conseguem me ajudar, por favor?

[Info  - 16:47:16] Cannot execute Linter. Includes not defined.
[Info  - 16:47:16] Cannot execute Linter. Includes not defined.
[Info  - 16:47:16] Cannot execute Linter. Includes not defined.
[Info  - 16:47:16] Cannot execute Linter. Includes not defined

Abaixo o arquivo servers.json
[servers - Copia.txt](https://github.com/totvs/tds-vscode/files/7565607/servers.-.Copia.txt)
.

**Comment by brodao** [comment]
@thiagomeschiatti 

Você precisa configurar as pastas que contém os arquivos de definição ou desligar o [TDS: Linter](https://github.com/totvs/tds-vscode/blob/master/docs/linter.md).

**Comment by thiagomeschiatti** [comment]
@brodao qual configuração é necessária, consegue me apoiar, por favor?

**Comment by danielbolognani** [comment]
Boa tarde @thiagomeschiatti, o Linter utiliza a pasta de includes Global, para configurar:
ctrl-shift-p e procure por "TOTVS: Include"
Configure então a pasta de include.
Abs!
