### ISSUE TITLE
Erro ao verificar pacotes da patch

### ISSUE THREAD

**Issue by TalitaTD** [totvs/tds-vscode#842]
Boa Tarde,

Estou com um problema ao visualizar o conteúdo da patch apresenta o erro abaixo:
![erro vscode](https://user-images.githubusercontent.com/89851034/142647423-ae6e3573-36c0-4a17-9243-9e2f85895e64.jpg)

Eu fiz o teste desinstalando tudo vscode, extenção, instalando a extenção do vscode, instalando a versão que encontrei aqui mais ainda assim não funcionou. Poderiam me ajudar.

**Comment by brodao** [comment]
@TalitaTD 

Favor complementar seu chamado com as informações solicitadas conforme [Informações importantes ao abrir chamado](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#informa%C3%A7%C3%B5es-importantes-ao-abrir-uma-issue) e [Gerando Logs](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs).

No aguardo.

**Comment by TalitaTD** [comment]
Boa Tarde,

Segue os dados conforme o solicitado:

Versão: TOTVS Saúde
Build AppServer: 7.00.191205P-20210114 - 64 bits
Nome do servidor: CXDFFKPRPRDBN12
Sistema operacional: Windows Server 2012 R2
Appserver version: 19.3.1.5
Build DBAccess: 20200606-20201110
Release do RPO:  12.1.025
Release do dicionário: 12.1.025
Local files: ctree
License server: 2014 - 3.3.1
DB DataBase: MSSQL
DB API Build: 20200606-20201110
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/7583304/totvsls_out.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/7583305/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/7583306/totvsls_in.log)

**Comment by brodao** [comment]
@TalitaTD 

Favor experimentar copiar o pacote para uma pasta sem acentos e espaços e aplicar este arquivo.

**Comment by TalitaTD** [comment]
Bom dia,

Fiz um teste com pacote sem acentos porém o erro permanece. 

![image](https://user-images.githubusercontent.com/89851034/143027871-f5a2218e-f577-401c-8807-a284078f39dd.png)

**Comment by brodao** [comment]
@TalitaTD 

Favor informar o endereço do qual obteve o pacote de atuação (_patch_), por favor.

No aguardo.

**Comment by TalitaTD** [comment]
Isso está acontecendo com qualquer patch seja gerado via totvs ou alguma pacth que geramos internamente para aplicação em outros rpo.

Segue um endereço de exemplo: https://suporte.totvs.com/portal/p/10098/download#detail/779711

Att,

**Comment by brodao** [comment]
@TalitaTD 

Fiz vários testes aqui e não reproduzi a ocorrência. Pedi para fazer testes sem que a pasta contenha acentos ou espaços e a imagem que anexou, mostra ainda com acentos e espaços. Pode fazer novamente, sem acentos e espaços.
Qual a versão do TDS-VSCode? Favor anexar log de console do Protheus.

No aguardo.

**Comment by TalitaTD** [comment]
Eu consegui resolver aqui mudando da pasta da rede deixando local na minha maquina. Pode encerrar por favor.
