### ISSUE TITLE
FWBrwRelation com problema na 12.1.33

### ISSUE THREAD

**Issue by tidiefra** [totvs/tds-vscode#843]
Tenho uma customização onde utilizamos 2 FwMBrowse, o segundo exibe dados dos itens dos primeiro (SF1/SD1), através da FWBrwRelation. Após migrar para a 12.1.33 isto parou de funcionar. Já chequei as query´s e as tabelas temporárias geradas por elas e estão com dados. Peguei um registro na tabela da parte superior e filtrei na tabela da parte inferior e vieram os registros correspondentes. 

oRelacTRB := FWBrwRelation():New()
oRelacTRB:AddRelation( oBrowse, oBrowseDown, { ;
				{ 'TC_NFISCAL'			, 'TR_NFISCAL' },;
				{ 'TC_FORNECE'			, 'TR_FORNECE' },;
				{ 'TC_LOJA'				, 'TR_LOJA'    } } )

**Comment by brodao** [comment]
@tidiefra,

Essa lista de chamado é exclusivo para ocorrências no TDS-VSCode.
Favor entrar em contato com suporte de Fraemwork via [Suporte TOTVS](https://totvscst.zendesk.com/hc/pt-br/#home).

A disposição.
