### ISSUE TITLE
Debug em MultiThread binário Harpia

### ISSUE THREAD

**Issue by evanstos** [totvs/tds-vscode#844]
Não estou conseguindo debugar em MultiThread utilizando o binário Harpia, a rotina utilizada é um serviço WS e o IDE não está parando nos breakpoints, realizei um teste utilizando o binário lobo-guará e o debug funcionou corretamente. 

Utilizei:
RPO D-1 e o Publicado.
TDS na versão atual e na versão 1.3.2

Arquivo lauch.json
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "__harpia",
			"cwb": "${workspaceFolder}",
			"program": "${command:AskForProgramName}",
			"programArguments": [
				"${command:AskForProgramArguments}"
			],
			"smartclientBin": "C:\\Totvs\\21-07-12-P12-SMARTCLIENT_BUILD-20.3.0.0 RC10_WINDOWS_X64\\smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true,
			"enableMultiThread": true,
			"enableProfile": false,
			"isAccessibilityMode": false,
			"doNotShowSplash": false,
			"openglMode": false,
			"dpiMode": false,
			"language": "",
			"ignoreFiles": true
		},
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "loboGuara",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "C://Totvs//lobo_guara//smartclient//smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true,
			"enableMultiThread": true
		}
	]
}

**Comment by brodao** [comment]
@evanstos 

Favor verificar o tópico [Depuração de serviços e job](https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md#depura%C3%A7%C3%A3o-de-servi%C3%A7os-jobs) para verificar procedimentos e detalhes.

Se continuar com a ocorrência, favor ativar os logs e anexá-los ao chamado, juntamente [Gerando informações sobe o problema](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema).

A disposição
