### ISSUE TITLE
Gerando arquivos appre* ao compilar

### ISSUE THREAD

**Issue by AugustoPontin** [totvs/tds-vscode#845]
**Describe the bug**
Toda compilação que faço gera um arquivo appreXXXXX.prw na pasta do projeto, fazendo com que fique vários lixos e tenho que ficar apagando manualmente.

**To Reproduce**
1. Compilar um fonte advpl
2. Verificar na mesma pasta desse fonte o arquivo gerado

**Screenshots**
![image](https://user-images.githubusercontent.com/45875161/142732198-7efd6358-af00-4091-b3ac-5d63720eb5a7.png)

**Desktop (please complete the following information):**
Windows 10 64 bits

O problema ocorre em diferentes ambientes e versões do Protheus.

**Comment by brodao** [comment]
@AugustoPontin 

Favor efetuar um testes desativando o [linter](https://github.com/totvs/tds-vscode/blob/master/docs/linter.md).

Caso o problema persista, favor ativar os logs e complementar as informações sobre o chamado conforme [Gerando informações sobre o chamado](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema).

No aguardo.

**Comment by danielbolognani** [comment]
@AugustoPontin verifique se nas preferências da extensão (File/Preferences/Settings na parte TOTVS), se estão habilitadas aa opções "Generate PPO file" ou "Show Pre compiler", se estiver, desative-as.

**Comment by AugustoPontin** [comment]
@danielbolognani essas opções já estavam desativadas.

@brodao desativei o linter e continua gerando o appre*.

Seguem informações complementares:

**Versão VSCODE**
Version: 1.62.3 (user setup)
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Extensão do tds instalada é a v.1.3.5**

**Dados do Server** 
Versão: TOTVS Manufatura
Build AppServer: 7.00.170117A-20200331 - 64 bits
Appserver version: 17.3.0.20
Build DBAccess: 20191119-20200706
Release do RPO:  12.1.025
Release do dicionário: 12.1.025
Local files: CTREE
License server: 2014 - 3.3.2
DB DataBase: MSSQL7
DB API Build: 20191119-20200706

**Versão da Lib:20200504**
Data da Lib: 20200518_142132
Commit ID:33d5ae77620b2b81654c05f22d98c4ee0129e917

Seguem logs:
[BiancogresIncesa_V12.zip](https://github.com/totvs/tds-vscode/files/7588423/BiancogresIncesa_V12.zip)

**Comment by brodao** [comment]
@AugustoPontin 

Reparei que você usando DropBox. Pode fazer um teste retirando a pasta "fontes facile" para fora do DropBox (acho que desligar o DropBox também server).

Pode-se que quando o linter vai remover os arquivos de trabalho, este encontra-se em uso (sendo sincronizado).

NO aguardo.

**Comment by brodao** [comment]
Encerrado por falta de retorno.
