### ISSUE TITLE
Migração Fontes 12.1.25 para 12.1.33

### ISSUE THREAD

**Issue by gabrielbravim87** [totvs/tds-vscode#849]
Comecei os testes de migração da **Release 12.1.25 para 12.1.33** e não encontrei nenhuma documentação para **migrar as User Functions de uma release para a outra**.
Como tivemos vários técnicos realizando a implantação acredito termos funções aplicadas diretamente do notebook do técnico que não temos mais acesso à ela, com isso queria saber se tem alguma rotina para realizar essa migração.

Obs.: Eu abri um ticket diretamente no Portal do Cliente e eles me aconselharam a verificar juntamente com a Equipe do VScode.

**Comment by danielbolognani** [comment]
Boa tarde @gabrielbravim87. Por aqui não temos como te ajudar, os fontes dentro do RPO são criptografados e não é possível realizar a leitura.

**Comment by danielbolognani** [comment]
Boa tarde @gabrielbravim87 fiquei sabendo que existe a possibilidade de realizar esse procedimento porém é feito sobre demanda e precisa ser tratado caso a caso. Recomendaram conversar com o seu ESN e tratar diretamente com ele.
Abraços.
