### ISSUE TITLE
Não esta aplicando patch TSS HARPIA 12.1.33

### ISSUE THREAD

**Issue by ejzanardo** [totvs/tds-vscode#851]
**Describe the bug**

Ao tentar aplicar um patch no tss do harpia. Esta apresentando erro e nao conclui.
[Info  - 10:12:59] Starting patch validate.
[Info  - 10:12:59] Patch file: d:/Sistemas/Protheus33/12.1.33/TSS/21-11-11_ATUALIZACAO_12.1.33_TSS_PROTHEUS_EXPEDICAO_CONTINUA/expedicao_continua_12_1_33_tss_protheus_tttm120_hp.ptm
[Info  - 10:12:59] Starting build for environment sped.
[Info  - 10:13:00] Starting build using RPO token ...
[Info  - 10:13:00] Patch validated without structure problems.
[Info  - 10:13:00] Aborting end build (rollback changes).
[Info  - 10:13:00] Patch validate finished.
[Info  - 10:13:00] Starting function inspector.
[Info  - 10:13:00] Loading functions from server.
[Info  - 10:13:02] Functions loaded (Duration: 1.540000)
[Info  - 10:13:02] 11241 functions successfully retrieved.
[Info  - 10:13:02] Function inspector finished.
[Info  - 10:13:02] Starting patch info.
[Info  - 10:13:02] Patch file: d:/Sistemas/Protheus33/12.1.33/TSS/21-11-11_ATUALIZACAO_12.1.33_TSS_PROTHEUS_EXPEDICAO_CONTINUA/expedicao_continua_12_1_33_tss_protheus_tttm120_hp.ptm
[Info  - 10:13:02] Starting build for environment sped.
[Info  - 10:13:03] Starting build using RPO token ...
[Info  - 10:13:03] Aborting end build (rollback changes).
[Info  - 10:13:03] Patch info finished.
[Info  - 10:13:03] Starting get patch resource.
[Info  - 10:13:03] Patch file: d:/Sistemas/Protheus33/12.1.33/TSS/21-11-11_ATUALIZACAO_12.1.33_TSS_PROTHEUS_EXPEDICAO_CONTINUA/expedicao_continua_12_1_33_tss_protheus_tttm120_hp.ptm
[Info  - 10:13:03] Starting build for environment sped.
[Info  - 10:13:04] Starting build using RPO token ...
[Info  - 10:13:04] Aborting end build (rollback changes).
[Info  - 10:13:04] Getting organizations (company/branch)
[Error - 10:13:05] Get organization list could not be executed. Server returned: Error reading data from SX's files.
[Info  - 10:13:05] Starting apply patch.
[Info  - 10:13:05] Starting build for environment sped.
[Error - 10:13:09] std::runtime_error
[Error - 10:13:09] Start build error: Server returned: 

[Error - 10:13:09] Patch validate could not be executed.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS/Architecture: [e.g. Windows 64 bits]

**Appserver (please complete the following information):**
 - Build (with date): [e.g. Build 7.00.170117A - Jun 28 2019 - 11:16:56]
 - OS/Architecture: [e.g. Linux 64 bits Ubuntu]
 - Build Version [e.g. 17.3.0.13]

**Additional context**

**Comment by brodao** [comment]
@ejzanardo 

No log, é informado que não foi possível obter a lista de empresas/filiais, favor anexar o log do appServer com o momento da ocorrência,

No aguardo.

**Comment by brodao** [comment]
Duplicate #850
