### ISSUE TITLE
Erro no Linter ao comparar programas fontes

### ISSUE THREAD

**Issue by gtrabach** [totvs/tds-vscode#852]
**Describe the bug**
Ao utilizar a opção de Controle do Código-Fonte do Visual Studio Code para comparar modificações em um programa fonte, o Linter buga e informa que existe um arquivo corrompido. Esse problema persiste mesmo após fechar a comparação e só é corrigido depois que o VS Code seja reiniciado.

**To Reproduce**
1) Possua um fonte que tenha controle de versão e efetue alguma alteração no mesmo.
2) Clique na opção Controle de Código-Fonte conforme imagem em anexo.
3) Clique no fonte desejado e observe que será gerado um problema de arquivo corrompido.
4) Feche a comparação e perceba que o problema continua.

**Expected behavior**
Acredito que por mais que o Linter identifique um fonte com problema devido a arquivos temporários gerados pela comparação, o mesmo não deve continuar exibindo a mensagem de problema após fechar o comparativo.

**Screenshots**
![image](https://user-images.githubusercontent.com/46979335/143064470-951bd553-f2e8-45aa-a525-86f8f0991444.png)

**Desktop (please complete the following information):**
Windows 10 Pro 64-bits

**Appserver (please complete the following information):**
AppServer 19.3.1.7 64-bits
Windows Server 2012 R2
Totvs Developer Studio for VsCode 1.3.5

**Comment by brodao** [comment]
Senhores,

Liberação da RC [1.3.8](https://github.com/totvs/tds-vscode/releases/tag/v1.3.8) a disposição.

**Comment by gtrabach** [comment]
Boa tarde!

Como posso fazer pra testar esse RC?

**Comment by brodao** [comment]
Baixe o VSIX disponibilizado no link e instale manualmente (https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix)

**Comment by gtrabach** [comment]
Bom dia! Deu certo, obrigado.

**Comment by brodao** [comment]
Senhores,

Foi liberado a versão 1.3.8 do TDS-VSCode no Market Place. 
Em alguns minutos, estará a disposição para atualização.

A disposição.
