### ISSUE TITLE
Debug VSCode - informar driver de conexão

### ISSUE THREAD

**Issue by PauloFigueira2018** [totvs/tds-vscode#854]
Boa tarde pessoal, tudo bem?

Queria saber se poderia me ajudar em uma dúvida no vscode?
Se existe algum lugar que eu consiga informar o driver de conexão que vai iniciar. Pois sempre que eu entro em debug acredito que o smartclient pega como default o tcp da pasta SmartClient.ini... Aí da incompatibilidade de versão, pois o correto não é o tcp, seria o mac no caso deste cliente.

Muito obrigado

**Comment by danielbolognani** [comment]
@PauloFigueira2018 O VSCode sempre se conecta via debug no appserver conectado atualmente, se está dando mensagem de incompatibilidade é porque o Debugger selecionado está configurado com um smartclient de versão diferente do Appserver.
Verifique a documentação abaixo:
https://github.com/totvs/tds-vscode/wiki#configura%C3%A7%C3%B5es-de-debug

Abraços
