### ISSUE TITLE
Desfragmentação de RPO

### ISSUE THREAD

**Issue by josuelsilva** [totvs/tds-vscode#855]
Olá boa noite,
Na versão do appserver 20.3.0.2 com release 12.1.033, após aplicação de patch o vscode não está desfragmentando de forma otimizada e o rpo está crescendo muito.

O Rpo da versão 12.0.33 começou com tamanho de 311MB e ao aplicarmos libs, acumulados que vem sendo liberados, já encontra-se em +590MB.

Ou seja, mesmo realizado a desfragmentação para cada patch não reduz o suficiente e o rpo só aumenta.
A nível de comparação, a release  12.1.025, após aplicação de um patch/Lib de 50MB, após desfragmentar o tamanho volta para algo proximo do tamanho anterior.

Abaixo informações do ambiente e vscode.

**VSCODE**
![vscode](https://user-images.githubusercontent.com/23218591/144139121-5d4d3017-701e-4d94-9ab4-c9446d363d1b.png)

**Informações do Ambiente**
![Guia-Atd](https://user-images.githubusercontent.com/23218591/144139151-744addd5-cc54-4660-98e5-4ad0212a21ea.png)

**Comment by brodao** [comment]
@josuelsilva 

Conforme imagens anexas, o processo está sendo executado conforme esperado.
Caso acredite que há algum problema, reabra este chamado com mais detalhes, como:
- imagens do antes e depois
- procedimentos para reprodução.
- console log do _appServer_

A disposição.

![image](https://user-images.githubusercontent.com/949914/144220992-8b92e236-716e-4157-b70c-3179e3a5d3cb.png)
![image](https://user-images.githubusercontent.com/949914/144221036-7e5ca00f-5599-4cb6-bc94-2d1a9bde1ed7.png)
![image](https://user-images.githubusercontent.com/949914/144221146-932c8a46-7be7-42d0-8d9c-a4b3cf7d6ad2.png)

**Comment by danielbolognani** [comment]
Bom dia, só para completar a informação do Alan, esse processo é inteiramente feito pelo Appserver, a extensão TDS-VSCode apenas envia o pedido para o Appserver realizar a desfragmentação. Pelas suas informações, o processo está funcionando porém está aquém do esperado. Devido a isso, por aqui nós não temos como ajudar, será necessário abrir o chamado para a equipe do Application Server.
Abraços!
