### ISSUE TITLE
Erro compilação 12.1.33

### ISSUE THREAD

**Issue by stamandre** [totvs/tds-vscode#856]
O vscode está apresentando erro na compilação dos patchs da TOTVS junto ao repositório da versão 12.1.33:

[Error - 14:59:01] std::runtime_error
[Error - 14:59:01] Start build error: Server returned: 
[Error - 14:59:01] Patch validate could not be executed.

Abri um chamado junto ao Prime e me foi passado o seguinte link para correção (https://github.com/totvs/tds-vscode/commit/319d4f88692b250618dd0ff41d313fcea535bdb6) onde é solicitado a alteração de três arquivos da estrutura do vscode. Não consegui localizar nos arquivos em minha instalação onde devo aplicar as alterações, como devo proceder?

**Comment by brodao** [comment]
@stamandre 

Você não precisa alterar nada na estrutura de arquivos. Em https://github.com/totvs/tds-vscode/releases/tag/v1.3.8, há um VSIX RC que corrige essa ocorrência.

A disposição.
