### ISSUE TITLE
Erro ao conectar Binário Harpia , estou mandando também console Log

### ISSUE THREAD

**Issue by cmjsilva1209** [totvs/tds-vscode#858]
Versão do VS Code e da extensão tds-vscode

Versão: 1.62.3
Confirmar: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Data: 2021-11-17T08:11:14.551Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
SO: Windows_NT x64 10.0.19043

![Versão da extensão tds-vscode](https://user-images.githubusercontent.com/95702866/145060719-4dd303f4-c396-4f82-861b-16b7182cdd7f.png)

Informações do TOTVS Server
Informações do AppServer
Tipo do servidor;Console
AppServer Build;7.00.210324P-20211006
Appserver version;20.3.0.2
Servidor 64 bits;Sim
Servidor Unix;N

Informações da LIB
Versão da Lib:20211004
Data da Lib: 20211006_135652
Commit ID:94c212d6522f77c511f4ddc68641247405742f8b
Release;12.1.033

Versão: TOTVS Distribuição e Logística
Build AppServer: 7.00.210324P-20211006 - 64 bits
Nome do servidor: MASTER
Sistema operacional: Windows Server 2012 R2
Appserver version: 20.3.0.2
Build DBAccess: 20200606-20210903
Release do RPO:  12.1.033
Release do dicionário: 12.1.033
Local files: CTREE
License server: 2014 - 3.2.2
DB DataBase: ORACLE
DB API Build: 20210202-20210826
[totvsls.log](https://github.com/totvs/tds-vscode/files/7669776/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/7669777/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/7669778/totvsls_out.log)

**Comment by cmjsilva1209** [comment]
[console.log](https://github.com/totvs/tds-vscode/files/7669791/console.log)

**Comment by brodao** [comment]
@cmjsilva1209 

Favor atualizar a extensão VS-Code. Olhando o console .log, parece que seu ambiente não está 100%.
Você consegue usar o SmartCLient?

021-12-07T12:47:17.468000-03:00 5988|
[WARN ][SERVER] FREEOBJ - Invalid parameter type U, call ignored at: __XNULOAD__(APLIB180.PRW) 06/10/2021 13:57:35

2021-12-07T12:47:26.476000-03:00 10928|
[WARN ][SERVER] FREEOBJ - Invalid parameter type U, call ignored at: __XNULOAD__(APLIB180.PRW) 06/10/2021 13:57:35

**Comment by danielbolognani** [comment]
Reforçando, é **obrigatório** atualizar a sua versão da extensão do VSCode, a atual é a v1.3.8

**Comment by cmjsilva1209** [comment]
Olá bom dia

Obrigado pela ajuda atualizei e deu certo


Att,

*Marcio Silva*
Departamento de Tecnologia da Informação
*Gerente de Sistemas - T.I.*
*Tel:* 11-3314-6400 *R**:* 6506 / 11 98802-7187
*Skype: *cmjsilva

<http://www.issam.com.br/>


Em ter., 7 de dez. de 2021 às 14:13, Daniel Otto Bolognani <
***@***.***> escreveu:
