### ISSUE TITLE
Problema para Compilar Arquivo aph

### ISSUE THREAD

**Issue by cmregazzo** [totvs/tds-vscode#859]
Bom dia,

Fiz a atualização do meu Plugin do TDS no VsCode para versão v1.3.8, e ao tentar compilar um fonte .aph, o fonte não compila e é mostrado o seguinte erro:

C2001  Syntax error: appre [7,1]

A linha que ele está dando tem uma tag <body>.

Print do Erro:

https://ibb.co/5r7t158

Existe algum e-mail que eu possa enviar o fonte?

No aguardo.

Obrigado.

Cristian Regazzo

**Comment by brodao** [comment]
@cmregazzo 

Pode enviar para acandido@totvs.com.br, juntamente com os arquivos de log conforme [Gerando Logs](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs).

No aguardo.

**Comment by cmregazzo** [comment]
Boa Tarde Alan,

Obrigado pelo feedback,

Enviei no seu e-mail o fonte e os logs de compilação.

Obrigado.

**Comment by brodao** [comment]
@cmregazzo 

Verifiquei seu fonte e ele esta com EOL (end-od-line) com LF.
![image](https://user-images.githubusercontent.com/949914/145266600-84c7949e-3e1b-45e1-93d8-5b5255c35112.png)

Trocando para CRLF, a compilação corre sem problemas.
![image](https://user-images.githubusercontent.com/949914/145266758-2c7b7823-9212-43e8-8084-31ef2bb067a1.png)


Nos fontes Protheus, o terminador (EOL) deve ser sempre CRLF.

Se na sua barra de status não estiver visível, acione o menu de contexto na barra de status e selecione `Editor End Of Line`.
Para mudar, acione o mouse sobre o indicador do EOL na barra de status.

A disposição.
