### ISSUE TITLE
Connection lost.

### ISSUE THREAD

**Issue by likid** [totvs/tds-vscode#86]
Cada vez que é feito uma operação no server como compilação, aplicação de patches ou defrag do rpo, o vscode exibe uma informação de conexão perdida e faz a reconexão com o server.
![2019-06-17_09-21-44](https://user-images.githubusercontent.com/10984007/59604044-6949db00-90e1-11e9-8364-497f526a0ad7.png)

**Comment by lwtnb-wrk** [comment]
@likid Não conseguimos reproduzir este problema. 

Que servidor voce esta utilizando? Versão, OS e build?

Tentou apagar e recadastrar o servidor??

**Comment by likid** [comment]
Leo, removi a conexão e testei novamente, mesmo problema.
Usamos Windows Server 2008 R2. Build 131227A.

**Comment by edusfc15** [comment]
Mesmo problema aqui com Windows 7 e 131227A

**Comment by likid** [comment]
O Windows server que mencionei ali é onde roda o appserver, no meu pc de desenvolvimento uso Windows 10.

**Comment by edusfc15** [comment]
Meu appserver está rodando em um Windows server 2012 R2.

**Comment by lwtnb-wrk** [comment]
ocorreu um problema de incompatibilidade em uma nova mensagem, mas ja estamos testando a correcao que deve sair logo

**Comment by likid** [comment]
@lwtnb-wrk por favor não demorem heheheh, esta reconexão fez praticamente dobrar o tempo de compilação.

**Comment by lwtnb-wrk** [comment]
Estamos efetuando testes na versao [pre-release 0.3.7](https://github.com/totvs/tds-vscode/releases/tag/0.3.7) que corrige esse problema, mas devemos liberar logo sim...

**Comment by lwtnb-wrk** [comment]
A versao [pre-release 0.3.7](https://github.com/totvs/tds-vscode/releases/tag/0.3.7) apresentou problemas que foram corrigidas. 
Agora estamos testando a [pre-release 0.3.10](https://github.com/totvs/tds-vscode/releases/tag/0.3.10) que será liberada assim que testada.
