### ISSUE TITLE
Não considerando aspas simples e dupla na validação da linha

### ISSUE THREAD

**Issue by sandroalves1971** [totvs/tds-vscode#860]
Prezados,
Encontrei um problema na validação de linha e compilação do programa fonte.
Exemplo:
Quando declarei por engano a variavel cArquivo:= cPath+"Nota_Debito_SubAlocacao.dotx'

Veja que possui uma Aspa dupla no inicio e no final esta a aspa simples....
passou no compilador e na validação visual
O proprio Protheus não gerou erro na comparação e a variável que ficou invalida a rotina só não retorna erro porque usei a validação na função File() e retornava ".F."  sempre

**Comment by danielbolognani** [comment]
Bom dia, esse problema precisa ser tratado com a equipe do Appserver, no TDS-VSCode apenas enviamos o arquivo para ser compilado e o Appserver que valida a sintaxe.
Mas te respondendo de antemão, final de linha esta sendo considerado final de string (caso a aspas duplas não seja finalizada) e no final a variável cArquivo ficou com a string ' (aspas simples) literal no final, por isso que falhou a validação via File().
