### ISSUE TITLE
Erro ao Compilar Aplicação PO-UI

### ISSUE THREAD

**Issue by cmregazzo** [totvs/tds-vscode#861]
Boa Tarde,

Fiz a migração do meu Protheus para o release 33, e ao tentar compilar o APP feito em PO-UI com a Extensão .app, o TDS v1.3.8 gera os seguintes alertas/erros:

This is deprecated, the new recommended way to configure your default shell is by creating a terminal profile in `#terminal.integrated.profiles.windows#` and setting its profile name as the default in `#terminal.integrated.defaultProfile.windows#`. This will currently take priority over the new profiles settings but that will change in the future.

Duplicate object key

No release 25 do Protheus utilizando a mesma versão do TDS v1.3.8, o arquivo .app, é compilado normalmente.

Dados do Server:

Versão: TOTVS Manufatura
Build AppServer: 7.00.210324P-20211206 - 64 bits
Nome do servidor: XXXX
Sistema operacional: Windows Server 2012 R2
Appserver version: 20.3.0.4
Build DBAccess: 20210202-20210930
Release do RPO:  12.1.033
Release do dicionário: 12.1.033
Local files: CTREE
License server: 2014 - 3.3.3
DB DataBase: MSSQL
DB API Build: 20210202-20210930

Dados do Remote:

Remote build: 7.00.210324P-20210914
Remote version: 20.3.0.0
Remote type: 1 - QT-5.15.3 WIN

Versão da Lib: 20211116
Data da Lib: 20211112_144246

Obrigado.

**Comment by danielbolognani** [comment]
Boa tarde @cmregazzo 
A mensagem apresentada não é da nossa extensão, aparenta ser algo relacionado ao terminal integrado do VSCode.
Por favor gere os logs (https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs) da extensão e envie também o console.log do appserver para podermos analisar.
Abraços!

**Comment by brodao** [comment]
@cmregazzo 

Essa mensagem é do VS-CODE, onde essa mensagem aparece exatamente?
Se puder anexar um print-screen, ajuda.

**Comment by cmregazzo** [comment]
Boa Tarde,

Obrigado pelos feedbacks.

Eu estava com o MPP ativado, e não estava compilando.

Desative o MPP ai compilou.

Podem encerrar a Issue.

Muito obrigado.

**Comment by danielbolognani** [comment]
A MPP (porta multi protocolo) não deveria influenciar na compilação. Verifique se a chave BUILDKILLUSERS=1 está presente no [General] do seu appserver.ini.
