### ISSUE TITLE
Debug Sigaloja

### ISSUE THREAD

**Issue by danielblaia** [totvs/tds-vscode#862]
Bom dia
Estou com dificuldades pra conseguir debugar no sigaloja
O caminho que uso aqui pra rodar é:
C:\TOTVS12\smartclient.exe -m -p=sigaloja -e=environment -c=tcp -a -a=001

como configurar o launcher pra debugar?

VS Code 1.63.0
Plugin Totvs Developer Studio for VSCode 1.3.8

obrigado

**Comment by brodao** [comment]
Olá

Em [Configuração de executores](https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md#configura%C3%A7%C3%A3o-de-executores) há informações de como proceder, com destaque em [Variáveis de substituição](https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md#vari%C3%A1veis-de-substitui%C3%A7%C3%A3o).

No seu caso, `C:\TOTVS12\smartclient.exe -m -p=sigaloja -e=environment -c=tcp -a -a=001`, os argumentos `e` e `c`, serão os do servidor/ambientes conectados. Fica mais ou menos assim, `sigaloja("001")`.

Se necessário mais alguma coisa, reabra esse chamado.

**Comment by danielblaia** [comment]
deu certo Alan obrigado!

Em qua., 15 de dez. de 2021 às 11:48, Alan Cândido ***@***.***>
escreveu:

**Comment by rafaelschumann** [comment]
inclusive não é utilizado o SMARTCLIENT.EXE PARA EXECUÇÃO DO TOTVS PDV NESTE CASO USAMOS O SIGAPAF.exe estado de SANTA CATARINA É PAF-ECF
