### ISSUE TITLE
Debugar fórmulas do roteiro de cálculo

### ISSUE THREAD

**Issue by gtrabach** [totvs/tds-vscode#863]
**Describe the bug**
Gostaria de saber como é possível depurar fórmulas do roteiro de cálculo através da extensão do TDS para o VsCode. Segui o mesmo processo que era feito anteriormente para o TDS para o Eclipse, mas o IDE não para nos breakpoints. 

**To Reproduce**
Foi utilizado o mesmo passo a passo disponibilizado na documentação anterior: https://centraldeatendimento.totvs.com/hc/pt-br/articles/360007020711-MP-BD-Como-debugar-f%C3%B3rmulas-e-roteiros-do-sistema-e-de-usu%C3%A1rio-na-vers%C3%A3o-12

**Expected behavior**
A IDE deveria parar nos breakpoints de acordo com o processo normal de depuração.

**Desktop (please complete the following information):**
Windows 10 Pro 64-bits
TDS for VsCode 1.3.8

**Appserver (please complete the following information):**
AppServer 19.3.1.8
Windows Server 2012 R2

**Additional context**
Essa é mais uma issue de dúvida, pois não encontrei nenhuma documentação na TOTVS e através de chamado com eles, eles informaram que não dão suporte a ferramenta VsCode e não sabem se é possível realizar este processo através da mesma. Isso é possível? Se sim devo realizar alguma configuração a mais?

**Comment by danielbolognani** [comment]
Bom dia @gtrabach Eu não entendi muito bem o processo e a dúvida precisa ser levada para o pessoal responsável por essas fórmulas/modulo.
Se o processo de debug foi feito corretamente conforme [link](https://github.com/totvs/tds-vscode/wiki#configura%C3%A7%C3%B5es-de-debug) e ainda assim não parou nos breakpoints, a suspeita fica para o arquivo compilado no RPO ser diferente do fonte na sua máquina (o que pode ter número de linhas diferentes e não parar corretamente nos breakpoints). E de qualquer forma precisaria de auxilio da equipe responsável pelo arquivos fontes.
Abraços

**Comment by gtrabach** [comment]
Bom dia, Daniel.

Então, eu realizei o processo corretamente, conferi se as fórmulas do roteiro estão corretas dentro do Roteiro de Cálculo do Protheus e dentro da pasta rpofrm mas ainda assim continua não parando nos breakpoints.

Essas fórmulas usam um rpo diferente do rpo do sistema, que é um rpo que fica justamente dentro da pasta rpofrm. É necessário alguma configuração adicional nesse caso?

Eu entrei em contato com o suporte do módulo GPE por ticket, mas eles me informaram que problemas com o uso do VsCode devem ser tratados aqui pelo GitHub. Número da solicitação no suporte: 13169854.

**Comment by brodao** [comment]
@gtrabach 

Me parece que a sua ocorrência é bem específica. Favor abrir um novo chamado, informando os dados e anexando os logs, conforme [Gerando informações sobre o problema](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema).

É de extrema importância informar um passo a passo e se possível, anexe print de telas ou vídeo e o console log do Protheus.

A disposição.
