### ISSUE TITLE
Erro ao gerar patch do RPO na versão 33

### ISSUE THREAD

**Issue by brunoviskz** [totvs/tds-vscode#864]
Olá, boa tarde. Tudo bem?
Gostaria de saber se possuem algum histórico para falha na tentativa de geração de fonte padrão na release 33.

Quando gero patchs do customizado, que o sistema busca do RPOCustom funciona bem mas ao gerar do padrão, que deveria vir do tttm120, o sistema gera o erro em anexo.

Muito obrigado pela prestatividade e apoio de sempre! 
![geraPatch](https://user-images.githubusercontent.com/60655337/146265779-76b26d77-b75a-48b8-9843-9fbbad50b25c.png)

**Comment by brodao** [comment]
@brunoviskz 

Verifique no log de console do protheus se há alguma ocorrência no momento que executa esse procedimento.
Favor complementar a abertura da ocorrência, conforme [Gerando informações sobre o problema](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema) e anexe os logs gerados.

No aguardo.

**Comment by danielbolognani** [comment]
Bom dia, a geração de patch em cima de fontes do RPO padrão (appserver Harpia, protheus 12.1.33) agora possui proteção e só é possível se tiver um Token configurado, e mesmo assim o patch só poderá ser gerado em cima de fontes que estejam com o status de "dev" ou seja, que tenham sido compilados manualmente.
Criar patch de fontes do padrão sem nenhum tipo de alteração só pode ser feito com Token de produção e apenas internamente pela Totvs.

Abraços!
