### ISSUE TITLE
Geração de patch e aplicação release 33 (Harpia)

### ISSUE THREAD

**Issue by domaia** [totvs/tds-vscode#865]
Erro ao aplicar patch Release 33. Build atualizada 7.00.210324P, DBACCESS v21.1.1.0
---------------------------v---------------------------------------------------
   //////  ////    //////  |  TOTVS Developer Studio for VS-Code
    //    //  //  //       |  Version 1.3.8
   //    //  //  //////    |  TOTVS Technology
  //    //  //      //     |
 //    ////    //////      |  https://github.com/totvs/tds-vscode
---------------------------^---------------------------------------------------

-------------------------------------------------------------------------------
SOBRE O USO DE CHAVES E TOKENS DE COMPILAÇÃO                                   

As chaves de compilação ou tokens de compilação empregados na construção do    
Protheus e suas funcionalidades, são de uso restrito dos desenvolvedores de    
cada módulo.                                                                   

Em caso de mau uso destas chaves ou tokens, por qualquer outra parte, que não  
a referida acima, a mesma irá se responsabilizar, direta ou regressivamente,   
única e exclusivamente, por todos os prejuízos, perdas, danos, indenizações,   
multas, condenações judiciais, arbitrais e administrativas e quaisquer outras  
despesas relacionadas ao mau uso, causados tanto à TOTVS quanto a terceiros,   
eximindo a TOTVS de toda e qualquer responsabilidade.                          
-------------------------------------------------------------------------------
[Info  - 10:24:20] Initializing Language Server.
[Info  - 10:24:20] Language Server initialized.
[Info  - 10:24:20] Starting reconnection to the server 'Protheus 12.33'
[Info  - 10:24:20] Secure authenticating...
[Info  - 10:24:27] User authenticated successfully.
[Info  - 10:24:27] Reconnection to the server 'Protheus 12.33' finished.
[Info  - 10:25:09] Server 'Protheus 12.33' successfully disconnected.
[Info  - 10:25:21] Starting connection to the server 'Protheus 12.33' (localhost@6000)
[Info  - 10:25:23] Connection to the server 'Protheus 12.33' finished.
[Info  - 10:25:26] Starting user 'admin' authentication.
[Info  - 10:25:26] Secure authenticating...
[Info  - 10:25:33] User authenticated successfully.
[Info  - 10:25:33] User 'admin' authentication finished.
[Info  - 10:25:41] Starting object inspector.
[Info  - 10:25:41] Loading objects from server.
[Info  - 10:25:47] Objects loaded (Duration: 6.499000)
[Info  - 10:25:47] 122509 objects successfully retrieved.
[Info  - 10:25:47] Object inspector finished.
[Info  - 10:26:08] Starting generate patch.
[Info  - 10:26:08] Starting build for environment protheus12.1.33.
[Info  - 10:26:11] Starting build using RPO token ...
[Error - 10:26:11] Patch could not be generated.
[Info  - 10:26:11] Cleaning up appserver OK.
[Info  - 10:26:11] Aborting end build (rollback changes).
[Info  - 10:30:45] Starting RPO defragmentation.
[Info  - 10:30:45] Starting build for environment protheus12.1.33.
[Info  - 10:30:48] Starting build using RPO token ...
[Warn  - 10:30:48] This process may take a while.
[Info  - 10:30:56] RPO successfully defragged.
[Info  - 10:30:56] Committing end build.
[Info  - 10:30:58] RPO defragmentation finished.
[Info  - 10:31:09] Starting object inspector.
[Info  - 10:31:09] Loading objects from server.
[Info  - 10:31:15] Objects loaded (Duration: 5.315000)
[Info  - 10:31:15] 122509 objects successfully retrieved.
[Info  - 10:31:15] Object inspector finished.
[Info  - 10:31:36] Starting generate patch.
[Info  - 10:31:36] Starting build for environment protheus12.1.33.
[Info  - 10:31:39] Starting build using RPO token ...
[Error - 10:31:39] Patch could not be generated.
[Info  - 10:31:39] Cleaning up appserver OK.
[Info  - 10:31:39] Aborting end build (rollback changes).
[Info  - 10:33:07] Starting generate patch.
[Info  - 10:33:07] Starting build for environment protheus12.1.33.
[Info  - 10:33:09] Starting build using RPO token ...
[Error - 10:33:09] Patch could not be generated.
[Info  - 10:33:09] Cleaning up appserver OK.
[Info  - 10:33:09] Aborting end build (rollback changes).

**Comment by brodao** [comment]
@domaia 

Favor reabrir esse chamado complementando-o com informações e anexando os logs conforme [Gerando informações sobre o problema](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema).

A disposição.
