### ISSUE TITLE
Mensagens de compilação não são mais mostradas 

### ISSUE THREAD

**Issue by cirilorocha** [totvs/tds-vscode#866]
Nas  versões 1.3.5 em diante (até a 1.3.8 atual) ao compilar um fonte com alguns alertas estes não são mais mostrados na aba PROBLEMAS, como era anteriormente. Hoje as mensagens aparecem exclusivamente no console do appserver.

Como reproduzir:
Compilar qualquer fonte onde exista alguma situação de aviso (como W0003 Local variable LRET never used) e observar que no VSCode não vai mostrar nada de aviso.

**Expected behavior**
Espero que volte a mostrar essas mensagens no compilador, assim ajudando a desenvolver um código melhor e com menos erros.

**Desktop (please complete the following information):**
 - OS/Architecture: Windows 10 20h2 x64

**Appserver (please complete the following information):**
 - Build (with date): 7.00.191205P-20210522 - 64 bits
 - OS/Architecture: Windows Server 2012 R2
 - Build Version 19.3.1.7

**Comment by brodao** [comment]
Fixed

**Comment by brodao** [comment]
Senhores,

Foi disponibilizado a versão **1.3.9** do **TDS-VSCode** no _Market Place_ do _VS-Code_.
Para detalhes da liberação, leia o [CHANGELOG](https://github.com/totvs/tds-vscode/releases/tag/v1.3.9).

Caso esteja configurado para atualização automática, aguarde notificação de atualização disponível.
Se for manual, execute a verificação por atualização após as 13hs de hoje, pois o _Market Place_ pode demorar um pouco para deixa-la pública.

A disposição.

**Comment by rafaelschumann** [comment]
Boa tarde @brodao, obrigado pelo retorno!

Não consegui obter sucesso na execução do debug com o SIGAPAF.

Poderia por gentileza me informar como conseguiu debugar ai?

No [Vídeo](https://www.loom.com/share/7031adce94ab4d7688fc997a4e89132d) demonstro o processo que executei aqui, onde pode ser observado que estou com o tds-vscode já atualizado na **release v1.3.9** e também com as configurações de acordo com o conteúdo informado em **docs/debugger.md** 

Abaixo segue o conteúdo do arquivo launch.json que foi utilizado, onde consta as tentativas de depuração que aparecem no vídeo e mais outras tentativas com passagem de parâmetros tanto com SIGAFRT como também com o SIGALOJA.

Parâmetros em uso atualmente no atalho do SIGAPAF:
C:/totvs/PDV/JOINVILLE/Protheus/bin/smartclient_x86_2/SIGAPAF.exe -p=SIGAFRT -E=ENVIRONMENT -C=pdv -m -a= -a=001

{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_sigapaf_debug",
			"request": "launch",
			"name": "TOTVS Language SigaPAF Debug",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"sigapafBin": "C:/totvs/PDV/JOINVILLE/Protheus/bin/smartclient_x86_2/SIGAPAF.exe",
			"isMultiSession": true,
			"enableTableSync": true
		}
	],
	"lastPrograms": [
		{
			"label": "sigafrt"
		},
		{
			"args": [
				"-E=ENVIRONMENT",
				"-C=pdv",
				"-m",
				null,
				"001"
			],
			"label": "sigafrt"
		},
		{
			"args": [
				"-E=ENVIRONMENT",
				"-C=pdv",
				"-m",
				null,
				"001"
			],
			"label": "sigaloja"
		},
		{
			"label": "sigaloja"
		},
		{
			"label": "sigfrt"
		},
		{
			"args": [
				"-E=ENVIRONMENT -C=pdv"
			],
			"label": "SIGAFRT"
		},
		{
			"args": [
				"-p=SIGAFRT",
				"-E=ENVIRONMENT",
				"-C=pdv",
				"001"
			],
			"label": "SIGAFRT"
		},
		{
			"args": [
				"-p=SIGAFRT",
				"-E=ENVIRONMENT",
				"-C=pdv",
				"-m",
				"001"
			],
			"label": "SIGAFRT"
		}
	],
	"lastProgramExecuted": "SIGAFRT"
}

**Comment by brodao** [comment]
@rafaelschumann 

Os argumentos ``-E -C``, não devem ser informados. Estes serão preenchidos pela extensão, usando o servidor e ambiente conectado. O argumento ``-M``, é ativado com a chave ``isMultiSession: true``, portanto  não o informe.

Seu executor fica assim:

```JSON
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "totvs_language_sigapaf_debug",
            "request": "launch",
            "name": "TOTVS Language SigaPAF Debug (SigaPAF)",
            "program": "${command:AskForProgramName}",
            "cwb": "${workspaceFolder}",
            "sigapafBin": "C:/totvs/bin/smartclient/sigapaf.exe",
            "isMultiSession": true,
            "enableTableSync": true
        }
    ]
}
```

Ao executá-lo (F5), informe o programa e o argumento "001"
![image](https://user-images.githubusercontent.com/949914/147280671-15be231a-6779-4f31-ae61-68e5739ff1b6.png)

Após a execução, o executor fica:
```JSON
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_sigapaf_debug",
			"request": "launch",
			"name": "TOTVS Language SigaPAF Debug (SigaPAF)",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"sigapafBin": "C:/totvs/bin/smartclient/sigapaf.exe",
			"isMultiSession": true,
			"enableTableSync": true
		}
	],
	"lastPrograms": [
		{
			"args": [
				"001"
			],
			"label": "sigaloja"
		}
	],
	"lastProgramExecuted": "sigaloja"
}
```
