### ISSUE TITLE
Desfragmentação de RPO não reduz tamanho do RPO na release 12.1.33

### ISSUE THREAD

**Issue by cirilorocha** [totvs/tds-vscode#867]
**Describe the bug**
Na release 12.1.33 ao executar o comando para desfragmentar o RPO do servidor o mesmo não é reduzido de tamanho (como ocorria nas releases e binários anteriores), ficando o mesmo cada vez maior quando aplicamos os patchs de atualização.
Testado com as versões 1.3.4 em diante (até 1.3.8 mais atual)

**To Reproduce**
Aplicar alguns patchs no RPO do servidor, observar o tamanho do mesmo irá aumentar (ele começa com cerca de 300mb). O nosso aqui apenas com alguns patchs já passou de 420mb.
Após isso escolher a opção Desfragmentar RPO no VSCode.
Observar que o tamanho do RPO não reduz para próximo ao tamanho original (300mb) como ocorria nas versões anteriores do sistema.

**Expected behavior**
Espero que essa operação de desfragmentação volte a reduzir o tamanho do RPO como era o comportamento anterior.

**Desktop (please complete the following information):**
 - OS/Architecture: Windows 10 20h2 x64

**Appserver (please complete the following information):**
 - Build (with date):  7.00.210324P-20211206 - 64 bits
 - OS/Architecture: Windows Server 2012 R2
 - Build Version 20.3.0.4

**Comment by cirilorocha** [comment]
Localizei outra ocorrência que orienta abrir direto com o Protheus.

**Comment by josuelsilva** [comment]
@cirilorocha você conseguiu evoluir com esse assunto ? 
Nosso rpo já está com 900MB e não volta mais.

**Comment by cirilorocha** [comment]
Abri um ticket com a equipe do protheus relatando o problema, já que eles disseram que era com o AppServer. Ainda não me deram previsão de solução.

**Comment by cirilorocha** [comment]
@josuelsilva Abri um ticket com a equipe do protheus relatando o problema, já que eles disseram que era com o AppServer. Ainda não me deram previsão de solução.

**Comment by lbbsantos** [comment]
@cirilorocha Tem como você me enviar o número da sua solicitação.

**Comment by cirilorocha** [comment]
@lbbsantos o ticket que eu abri no suporte da totvs é o 13227247. Já cobre retorno e até agora eles não responderam nada.

**Comment by lbbsantos** [comment]
@cirilorocha Eu associei o meu ticket (13396910)  ao seu.
Eu ainda não fiz a migração, identifiquei isso no teste, esta muito louco. A minha RPO Harpia do teste esta com 1.2GB

**Comment by cirilorocha** [comment]
@lbbsantos eu também estou apenas efetuando testes e ajustes para depois colocar em produção, também detectei essa situação, e por isso relatei para eles corrigirem.

**Comment by danielbolognani** [comment]
Boa tarde, a equipe de Appserver me informou que essa situação será corrigida na versão 20.3.0.6 do Appserver que deve ser disponibilizada no portal até o final de Fev/2022.
