### ISSUE TITLE
Debug SIGAPAF 

### ISSUE THREAD

**Issue by rafaelschumann** [totvs/tds-vscode#869]
Estou enfrentando problemas ao tentar debugar em um ambiente fiscal PAF-ECF no TOTVS PDV 12.1.27.

No arquivo launch.json em smartclientBin se faço uso do C:/totvs/PDV/Protheus/bin/smartclient/smarclient.exe o smartclient é iniciado normalmente via debug no entanto ao tentar acessar o TOTVS PDV é apresentada a seguinte mensagem:
Nos estados aonde é obrigatório o uso do PAF-ECF, o acesso deve ser realizado pelo executárvel homologado SIGAPAF.exe

No arquivo launch.json em smartclientBin se faço uso do C:/totvs/PDV/Protheus/bin/smartclient/SIGAPAF.exe e inicializo o debug com SIGAFRT passando os parâmetros em "programArguments"  como apresentado a seguir
"programArguments": [
				"-e=PDV",
				"-c=PDV",
				"-m",
				"",
				"001"
			],
ocorre o seguinte erro: 
Session [-E=PDV] not found in appserver.ini. Verify the "Environment in the Server" in file
C:\bamboo\xml-data\build-dir\TP11-OF19310-TECXWIN64\lib\config.cpp at line 98

No arquivo launch.json em smartclientBin se faço uso do C:/totvs/PDV/Protheus/bin/smartclient/SIGAPAF.exe e inicializo o debug com SIGAFRT passando sem a parâmetros em "programArguments", no entanto indicando para inicializar com  o conteúdo
SIGAPAF -p=sigafrt -e=PDV -c=PDV -m -a= -a=001 ocorre o mesmo erro citado acima:
Session [-E=PDV] not found in appserver.ini. Verify the "Environment in the Server" in file
C:\bamboo\xml-data\build-dir\TP11-OF19310-TECXWIN64\lib\config.cpp at line 98

No arquivo launch.json em smartclientBin se faço uso do C:/totvs/PDV/Protheus/bin/smartclient/SIGAPAF.exe e inicializo o debug informando SIGAFRT("001"), ou SIGAFRT 001, ou SIGALOJA 001, ou SIGALOJA("001") aparece a mensagem abaixo:
Para acesso ao PAF-ECF, configure os parâmetros do atalho SIGAPAF com o conteúdo: -P=SIGAFRT 

OBS: Ao acessar o SIGAPAF através do atalho abaixo o sistema loga normalmente "só que eu preciso debugar":
C:\totvs\JOINVILLE\Protheus\bin\smartclient\SIGAPAF.exe -p=sigafrt -e=PDV -c=PDV -m -a= -a=001

Olhei na documentação https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md#configura%C3%A7%C3%A3o-de-executores no entanto não encontrei nenhuma informação referente ao SIGAPAF.

VS Code 1.63.2
Plugin Totvs Developer Studio for VSCode 1.3.8

Por gentileza como devo proceder para conseguir debugar no SIGAPAF!

**Comment by brodao** [comment]
Duplicate #862

**Comment by rafaelschumann** [comment]
Este problema citado na #862 não trata de PAF-ECF preciso debugar no SIGAPAF!
