### ISSUE TITLE
Problemas com Identação de Function/Return

### ISSUE THREAD

**Issue by fwsoares** [totvs/tds-vscode#87]
Após a liberação da versão 0.3.5, o sistema está fazendo a identação automática do código, mas não está fechando a chave Function/Return adequadamente, deixando o Return desalinhado, e não permite que seja alterado manualmente, pois quando fazemos isso ao salvar o arquivo volta a ficar errado de novo.

**Comment by marcosnqsdev** [comment]
> Após a liberação da versão 0.3.5, o sistema está fazendo a identação automática do código, mas não está fechando a chave Function/Return adequadamente, deixando o Return desalinhado, e não permite que seja alterado manualmente, pois quando fazemos isso ao salvar o arquivo volta a ficar errado de novo.

Verdade! Acabei de testar aqui também. Está fazendo automático ao salvar o fonte.

**Comment by likid** [comment]
Isso acontece porque no padrão do VSCode ele formata o código ao salvar, porém existe uma forma de salvar sem formatação, o que fiz aqui foi alterar a tecla de atalho Ctrl+S para chamar a opção de salvar sem formatar, assim não ocorre a reindentação ao salvar.

**Comment by matheus-sales** [comment]
@fwsoares por favor acompanhe pela issue https://github.com/totvs/tds-vscode/issues/84. 

Essa issue será fechada por duplicidade.
