### ISSUE TITLE
Debug SIGAPAF!

### ISSUE THREAD

**Issue by rafaelschumann** [totvs/tds-vscode#870]
VOCES NÃO LERAM É **IMPRESSORA FISCAL** - ESTE NÃO É O MESMO PROBLEMA DA #862 

Estou enfrentando problemas ao tentar debugar em um ambiente fiscal **PAF-ECF** no TOTVS PDV 12.1.27.

No arquivo launch.json em smartclientBin se faço uso do C:/totvs/PDV/Protheus/bin/smartclient/smarclient.exe o smartclient é iniciado normalmente via debug no entanto ao tentar acessar o TOTVS PDV é apresentada a seguinte mensagem:
Nos estados aonde é obrigatório o uso do PAF-ECF, o acesso deve ser realizado pelo executárvel homologado SIGAPAF.exe

No arquivo launch.json em smartclientBin se faço uso do C:/totvs/PDV/Protheus/bin/smartclient/SIGAPAF.exe e inicializo o debug com SIGAFRT passando os parâmetros em "programArguments" como apresentado a seguir
"programArguments": [
"-e=PDV",
"-c=PDV",
"-m",
"",
"001"
],
ocorre o seguinte erro:
Session [-E=PDV] not found in appserver.ini. Verify the "Environment in the Server" in file
C:\bamboo\xml-data\build-dir\TP11-OF19310-TECXWIN64\lib\config.cpp at line 98

No arquivo launch.json em smartclientBin se faço uso do C:/totvs/PDV/Protheus/bin/smartclient/SIGAPAF.exe e inicializo o debug com SIGAFRT passando sem a parâmetros em "programArguments", no entanto indicando para inicializar com o conteúdo
SIGAPAF -p=sigafrt -e=PDV -c=PDV -m -a= -a=001 ocorre o mesmo erro citado acima:
Session [-E=PDV] not found in appserver.ini. Verify the "Environment in the Server" in file
C:\bamboo\xml-data\build-dir\TP11-OF19310-TECXWIN64\lib\config.cpp at line 98

No arquivo launch.json em smartclientBin se faço uso do C:/totvs/PDV/Protheus/bin/smartclient/SIGAPAF.exe e inicializo o debug informando SIGAFRT("001"), ou SIGAFRT 001, ou SIGALOJA 001, ou SIGALOJA("001") aparece a mensagem abaixo:
Para acesso ao PAF-ECF, configure os parâmetros do atalho SIGAPAF com o conteúdo: -P=SIGAFRT

OBS: Ao acessar o SIGAPAF através do atalho abaixo o sistema loga normalmente "só que eu preciso debugar":
C:\totvs\JOINVILLE\Protheus\bin\smartclient\SIGAPAF.exe -p=sigafrt -e=PDV -c=PDV -m -a= -a=001

Olhei na documentação https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md#configura%C3%A7%C3%A3o-de-executores no entanto não encontrei nenhuma informação referente ao SIGAPAF.

VS Code 1.63.2
Plugin Totvs Developer Studio for VSCode 1.3.8

Por gentileza como devo proceder para conseguir debugar no SIGAPAF!

**Comment by brodao** [comment]
LI SIM.

Você que não entendeu como é a configuração.

```
{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Debug",
			program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"isMultiSession": true,
			"enableTableSync": true,
			"waitForAttach": 20000,
			**"smartclientBin": "C:/totvs/PDV/Protheus/bin/smartclient/SIGAPAF.exe",**
			"logFile": "${workspaceFolder}\\daplog.log"
		}

```

**Comment by rafaelschumann** [comment]
No arquivo launch.json em smartclientBin se faço uso do C:/totvs/PDV/Protheus/bin/smartclient/SIGAPAF.exe e inicializo o debug informando SIGAFRT("001"), ou SIGAFRT 001, ou SIGALOJA 001, ou SIGALOJA("001") aparece a mensagem abaixo:
Para acesso ao PAF-ECF, configure os parâmetros do atalho SIGAPAF com o conteúdo: -P=SIGAFRT

**Comment by rafaelschumann** [comment]
No arquivo launch.json em smartclientBin se faço uso do C:/totvs/PDV/Protheus/bin/smartclient/SIGAPAF.exe e inicializo o debug com SIGAFRT passando sem a parâmetros em "programArguments", no entanto indicando para inicializar com o conteúdo
SIGAPAF -p=sigafrt -e=PDV -c=PDV -m -a= -a=001 ocorre o mesmo erro citado acima:
Session [-E=PDV] not found in appserver.ini. Verify the "Environment in the Server" in file
C:\bamboo\xml-data\build-dir\TP11-OF19310-TECXWIN64\lib\config.cpp at line 98

**Comment by brodao** [comment]
@rafaelschumann 

Estou com dificuldades para localizar o executável do SIGAPAF. Você pode disponibilizá-lo ou indicar onde posso pegar?

Grato.

**Comment by rafaelschumann** [comment]
Boa tarde @brodao! 

No endereço abaixo fiz a gravação de um vídeo demonstrando o processo de execução, onde realizei várias tentativas de acesso ao TOTVS PDV, se puder visualizar talvez encontre algum procedimento que eu esteja realizando de forma incorreta:
[Vídeo](https://www.loom.com/share/4cfb5ff4014245d79a4611ea5230d34e)

Neste [endereço ](https://drive.google.com/drive/folders/1tbegMeGa8c50LRfjPAthUhOcKaVG3v-8?usp=sharing) **temporário** fiz o upload dos seguintes arquivos:
smartclient DO PDV completo com o SIGAPAF.exe em uso no meu ambiente;
appserver [DO PDV] completo em uso no meu ambiente;
SIGAPAF - JOINVILLE [ATALHO DO SIGAPAF UTILIZADO].lnk;
PDV_JOINVILLE [LOG GERADO NO PDV].log , o mesmo também está no arquivo compactado appserver [DO PDV];
launch.json [arquivo de configuração em uso no VsCode]

Testei também com a instrução "waitForAttach": 20000 no launch.json mas o erro foi o mesmo, não interferiu em nada esta alteração.

[Endereço ](httpstdn.totvs.compagesviewpage.actionpageId=618874868) do conteúdo da TOTVS citando o erro que ocorreu durante a depuração.
OBS: Estamos com o Licence na versão 3.3.2 . Não sei se isso interfere em alguma coisa pois o PDV não usa o Licence para execução. Tentei ativar a sessão LICENSECLIENT no appserver do pdv e também não mudou em nada, o erro continua ocorrendo.

**Comment by ricardomansano** [comment]
Boa tarde @rafaelschumann ,

O Sigapaf.exe é um executável escrito em Delphi que simplemente "chama" o SmartClient, vc não pode usá-lo no lugar do SmartClient.

Partindo deste principio, qual é o seu problema em depurar seu ambiente usando diretamente o SmartClient.exe?

**Comment by brodao** [comment]
Complementando, fiz alguns testes e o SigaPAF não aceita alguns parâmetros, server e environment a utilizar. Também acho que não trabalha com comunicação segura (SSL).

![image](https://user-images.githubusercontent.com/949914/146981716-1030d52d-acc8-4aa0-b257-a81576b8153b.png)

**Comment by rafaelschumann** [comment]
Boa tarde @ricardomansano estou usando o SIGAPAF pois estamos no estado de Santa Catarina, para faturar aqui via TOTVS PDV aqui não podemos usar o SmartClient.exe.
Se acessar o módulo SIGAFRT utilizando o SmartClient.exe ao tentar acessar o TOTVS PDV rotina padrão da TOTVS denominada STIPOSMAIN o próprio sistema impede de prosseguir apresentando a seguinte mensagem:
Nos estados aonde é obrigatório o uso do PAF-ECF, o acesso deve ser realizado pelo executável homologado [SIGAPAF.exe]

**Comment by rafaelschumann** [comment]
@brodao agradeço a atenção dispensada! veja bem... se o SIGAPAF não aceita parâmetros de entrada então jamais iremos conseguir debugar no TOTVS PDV aqui no estado de Santa Catarina.. eis a questão e agora o que fazer ... o dilema.... 
de qualquer maneira abri um chamado na TOTVS talvez consiga avançar neste caso.
OBS: Como já citado anteriormente, nos estados aonde é obrigatório o uso do PAF-ECF, o acesso deve ser realizado pelo executável homologado [SIGAPAF.exe].

**Comment by brodao** [comment]
@rafaelschumann 

Falamos com a equipe responsável pelo SIGAPAF e com suas observação, entendemos o porquê isso.
Vou implementar uma melhoria no TDS-VSCode, que permitirá você executar o SIGAPAF.
Amanhã cedo, o mais tardar, libero uma RC do TDS-VSCode.

**Comment by ricardomansano** [comment]
Bo tarde novamente @rafaelschumann 

O Alan vai tentar fazer uma mágica pra enganar o depurador, porque o sigapaf tá propagando os params diferentes do smartclient, vms torcer pra que consigamos contornar no plugin

O correto seria recompilar o sigapaf.exe, porem com isso perderíamos a licença de uso dele, que esta amarrada ao MD5 deste executável, então acredito que o pessoal do Sigaloja não conseguiria mexer nisso

Te mantemos informado

**Comment by brodao** [comment]
Senhores,

Foi disponibilizado a versão **1.3.9** do **TDS-VSCode** no _Market Place_ do _VS-Code_.
Para detalhes da liberação, leia o [CHANGELOG](https://github.com/totvs/tds-vscode/releases/tag/v1.3.9).

Caso esteja configurado para atualização automática, aguarde notificação de atualização disponível.
Se for manual, execute a verificação por atualização após as 13hs de hoje, pois o _Market Place_ pode demorar um pouco para deixa-la pública.

A disposição.

**Comment by rafaelschumann** [comment]
Boa tarde @brodao, obrigado pelo retorno!

Não consegui obter sucesso na execução do debug com o SIGAPAF.

Poderia por gentileza me informar como conseguiu debugar ai?

No Vídeo demonstro o processo que executei aqui, onde pode ser observado que estou com o tds-vscode já atualizado na release v1.3.9 e também com as configurações de acordo com o conteúdo informado em docs/debugger.md

Abaixo segue o conteúdo do arquivo launch.json que foi utilizado, onde consta as tentativas de depuração que aparecem no vídeo e mais outras tentativas com passagem de parâmetros tanto com SIGAFRT como também com o SIGALOJA.

Parâmetros em uso atualmente no atalho do SIGAPAF:
C:/totvs/PDV/JOINVILLE/Protheus/bin/smartclient_x86_2/SIGAPAF.exe -p=SIGAFRT -E=ENVIRONMENT -C=pdv -m -a= -a=001

{
"version": "0.2.0",
"configurations": [
{
"type": "totvs_language_sigapaf_debug",
"request": "launch",
"name": "TOTVS Language SigaPAF Debug",
"program": "${command:AskForProgramName}",
"cwb": "${workspaceFolder}",
"sigapafBin": "C:/totvs/PDV/JOINVILLE/Protheus/bin/smartclient_x86_2/SIGAPAF.exe",
"isMultiSession": true,
"enableTableSync": true
}
],
"lastPrograms": [
{
"label": "sigafrt"
},
{
"args": [
"-E=ENVIRONMENT",
"-C=pdv",
"-m",
null,
"001"
],
"label": "sigafrt"
},
{
"args": [
"-E=ENVIRONMENT",
"-C=pdv",
"-m",
null,
"001"
],
"label": "sigaloja"
},
{
"label": "sigaloja"
},
{
"label": "sigfrt"
},
{
"args": [
"-E=ENVIRONMENT -C=pdv"
],
"label": "SIGAFRT"
},
{
"args": [
"-p=SIGAFRT",
"-E=ENVIRONMENT",
"-C=pdv",
"001"
],
"label": "SIGAFRT"
},
{
"args": [
"-p=SIGAFRT",
"-E=ENVIRONMENT",
"-C=pdv",
"-m",
"001"
],
"label": "SIGAFRT"
}
],
"lastProgramExecuted": "SIGAFRT"
}

**Comment by brodao** [comment]
@rafaelschumann 

Os argumentos ``-E -C``, não devem ser informados. Estes serão preenchidos pela extensão, usando o servidor e ambiente conectado. O argumento ``-M``, é ativado com a chave ``isMultiSession: true``, portanto  não o informe.

Seu executor fica assim:

```JSON
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "totvs_language_sigapaf_debug",
            "request": "launch",
            "name": "TOTVS Language SigaPAF Debug (SigaPAF)",
            "program": "${command:AskForProgramName}",
            "cwb": "${workspaceFolder}",
            "sigapafBin": "C:/totvs/bin/smartclient/sigapaf.exe",
            "isMultiSession": true,
            "enableTableSync": true
        }
    ]
}
```

Ao executá-lo (F5), informe o programa e o argumento "001"
![image](https://user-images.githubusercontent.com/949914/147286225-9a1c75ed-253e-4d6f-9eb6-f958110c1bed.png)

Após a execução, o executor fica:
```JSON
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_sigapaf_debug",
			"request": "launch",
			"name": "TOTVS Language SigaPAF Debug (SigaPAF)",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"sigapafBin": "C:/totvs/bin/smartclient/sigapaf.exe",
			"isMultiSession": true,
			"enableTableSync": true
		}
	],
	"lastPrograms": [
		{
			"args": [
				"001"
			],
			"label": "sigaloja"
		}
	],
	"lastProgramExecuted": "sigaloja"
}
```

**Comment by rafaelschumann** [comment]
@brodao refiz os testes mas não funcionou!

No [Video](https://loom.com/share/22a1f27e378c48eb8897b968a4840835)
mostro o processo de execução do debug iniciando com a copia seu código do launch.json supracitado e também fazendo o uso do sigapaf no mesmo diretório que foi usado em seu launch "C:/totvs/bin/smartclient/sigapaf.exe".

Informando SIGALOJA 001 ou SIGAFRT 001 os erros apresentados no Appserver são os mesmos e ocorrem na seguinte sequência:

**Mensagem 01:** 
2021-12-23T17:13:41.959000-03:00 12220|
[FATAL][SERVER] 23/12/2021 17:13:41[Thread 12220] [THROW] Invalid ReadMSChar at file d:\bamboo\xml-data\build-dir\tp11-of19310-tecxwin64\lib_base\memstream.hpp line 856

**Mensagem 02:** 
2021-12-23T17:13:41.989000-03:00 18672|
[WARN ][SERVER] [THROW][Thread  18672] tConnnErrorException (8:Erro de comunicacao: Erro de sincronismo) on D:\bamboo\xml-data\build-dir\TP11-OF19310-TECXWIN64\lib_comm\msgmanager.cpp:472

**OBS:** Não vou poder utilizar o SIGALOJA preciso que execute com o SIGAFRT (nos estados aonde é obrigatório o uso do PAF-ECF, o acesso deve ser realizado pelo executável homologado [SIGAPAF.exe])

Por fim é finalizado o debug sem acessar o sistema:
2021-12-23T17:14:16.584000-03:00 6652|
[INFO ][SERVER] [Thread 6652] [23/12/2021 17:14:16] Thread finished (rafael.binda, SCHUMANN1389) 

O resultado final do launch.json é este abaixo:
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_sigapaf_debug",
			"request": "launch",
			"name": "TOTVS Language SigaPAF Debug (SigaPAF)",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"sigapafBin": "C:/totvs/bin/smartclient/sigapaf.exe",
			"isMultiSession": true,
			"enableTableSync": true
		}
	],
	"lastPrograms": [
		{
			"args": [
				"001"
			],
			"label": "SIGALOJA"
		},
		{
			"args": [
				"001"
			],
			"label": "SIGAFRT"
		}
	],
	"lastProgramExecuted": "sigaloja"
}

**Comment by brodao** [comment]
@rafaelschumann 

Favor informar a build do appServer, algo semelhante a:
```
***  www.totvs.com.br  ***
* TOTVS - Build ?????????????????????????
* Build: 64 bits
* DEBUG VERSION
* SVN Revision: $WCRANGE$
* Build Version: ?????????????????????
```

**Comment by rafaelschumann** [comment]
Bom dia @brodao ! 

Seguem informações apresentadas ao iniciar o AppServer do PDV:
AppServer do PDV e da Retaguarda na mesma release:
* TOTVS - Build 7.00.191205P - Jan 14 2021 - 21:11:32
* Build: 64 bits
* SVN Revision: 29345
* Build Version: 19.3.1.5

Outros dados extraídos através do SHIFT+F6 estando logado com o SIGAPAF:

**Dados do Server :**
Versão: TOTVS 
Build AppServer: 7.00.191205P-20210114 - 64 bits
Nome do servidor: SCHUMANN1389
Sistema operacional: Windows 10
Appserver version: 19.3.1.5
Build DBAccess: 20190101-20210114
Release do RPO:  12.1.027 - Out  2020
Release do dicionário: 12.1.027 - Out  2020
Local files: SQLITE
License Server não encontrado
DB DataBase: SQLITE
DB API Build: 20190101-20210114

**Dados do Remote:**
Remote build: 7.00.191205P-20210108
Remote version: 19.3.1.2
Remote type: 1 - QT-5.14.2 WIN
Módulo: FRT
Nome do computador: SCHUMANN1389
Sistema operacional: Windows 10 - 
Memória: 8006
Processador: Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz

Versão da Lib:20210517
Data da Lib: 20210526_14416
Commit ID:afbce57a13ae79f63f1cff6f25c732fae5eb0d24

Se quiser fazer o download disponibilizei o AppServer do PDV + todo diretório do SmartClient com SIGAPAF do meu ambiente no endereço abaixo:
[AppServer + SmartClient/SIGAPAF](https://drive.google.com/drive/folders/1tbegMeGa8c50LRfjPAthUhOcKaVG3v-8)

**Comment by ricardomansano** [comment]
Bom dia @rafaelschumann ,

O @brodao fez um ajuste de teste, mas sem sucesso aparentemente, reforço que a depuração deve ocorrer somente a partir do SmartClient.exe

O binário deste ambiente esta muito desatualizado(Jan/2021), acredito ser por que é uma estação PDV, porém é importante que monte um ambiente com os ultimos binarios do Portal e teste

Caso este ambiente também não funcione não teremos ação sobre essa issue, e ela será encerrada

Voce deve usar o SmartClient.exe na depuração, e pode fazer a depuração mediante conouts, não é o mais prático, mas será efetivo, ja que esse não é um ambiente padrão de desenvolvimento

Caso precise de mais informações relativas ás funções do padrão, pode abrir um chamado no Portal para o time do SigaLoja

Aguardamos o teste com o ambiente atualizado

At,

**Comment by rafaelschumann** [comment]
Bom dia!

Não funciona nem com a última versão do binário disponível.

**Comment by ricardomansano** [comment]
Bom dia novamente,

Conforme comentei, a depuração com o Sigapaf deve seguir usando conouts, nosso plugin opera apenas com o SmartClient binário, em todos os Sistemas Operacionais homologados

Estou encerrando este atendimento

At
Ricardo Mansano
Gerente de Desenvolvimento & Suporte
