### ISSUE TITLE
Tipagem de Dados do tlpp

### ISSUE THREAD

**Issue by AlexandreBeh** [totvs/tds-vscode#871]
Quando declaramos uma variavel com o tipo definido o VSCode muda o estilo da letras e cores para demonstrar qual o tipo da variavel.
Como na foto abaixo:
![image](https://user-images.githubusercontent.com/11984884/146988962-6f3e04ff-546f-4ba6-a010-eb256e4e4ae2.png)
Porém isto só ocorre com os tipos nativos do ADVPL e não acontece com os novos tipos introduzidos no TLPP, como na foto abaixo:
![image](https://user-images.githubusercontent.com/11984884/146989163-4d7dd6f0-02a6-4006-b91f-086f14661785.png)

Seria muito bom se a extensão também conseguisse mudar a formatação dos novos tipos de variáveis, assim facilitando a visualização ao utilizar todos os novos tipos de dados.

Versão Extensão: 1.3.8
Versão VSCode: 1.63.2

**Comment by brodao** [comment]
Senhores,

Foi disponibilizado a versão **1.3.9** do **TDS-VSCode** no _Market Place_ do _VS-Code_.
Para detalhes da liberação, leia o [CHANGELOG](https://github.com/totvs/tds-vscode/releases/tag/v1.3.9).

Caso esteja configurado para atualização automática, aguarde notificação de atualização disponível.
Se for manual, execute a verificação por atualização após as 13hs de hoje, pois o _Market Place_ pode demorar um pouco para deixa-la pública.

A disposição.
