### ISSUE TITLE
Vs Code fica derrubando a conexão quando está em Debug: "Tempo limite após 2000 ms para 'terminate'"

### ISSUE THREAD

**Issue by heraldoadolpho** [totvs/tds-vscode#872]
Boa tarde!

Ao executar debug, em um período curto de tempo recebo o retorno mencionado acima. O Cliente é derrubado e tenho que recomeçar o Debug. 

Versão Vscode: 1.63.2

![image](https://user-images.githubusercontent.com/96540881/147126707-7e50309c-2a0c-49b1-be17-f9ca5936819a.png)

Verifiquei o appserver.ini e não consta nenhum timeout informado.

[CMY2SN_DEV_HOMOLOGA]
sourcepath=d:\outsourcing\totvs\protheus\apo_core\apo\CMY2SN_DEV_HOMOLOGA\portuguese\20211214141718\
RootPath=d:\outsourcing\totvs\protheus_data\
FormPath=d:\outsourcing\totvs\protheus_data\formpath
CtreeRootpath=d:\outsourcing\totvs\protheus_data
StartPath=/system/
x2_path=
RpoDb=top
RpoLanguage=portuguese
RpoVersion=120
LocalFiles=ctree
localdbextension=.dtc
PictFormat=DEFAULT
DateFormat=DEFAULT
RegionalLanguage=BRA
dbALIAS=CMY2SN_121810_PR_DV
dbPORT=7891
dbSERVER=10.0.2.4
dbdatabase=mssql
SpecialKey=CMY2SN
lastupdated=20141209
helpserver=***
TOPMemoMega=1
;StartSysInDB=1
theme=Sunset

**Comment by brodao** [comment]
@heraldoadolpho 

Informe os dados e anexando os logs, conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)

É de extrema importância informar um passo a passo e se possível, anexe print de telas ou vídeo e o console log do Protheus.

No aguardo

**Comment by ricardomansano** [comment]
Encerrado por falta de retorno
