### ISSUE TITLE
Erro ao tentar debugar P12.33

### ISSUE THREAD

**Issue by danps2005** [totvs/tds-vscode#873]
Boa tarde!
Após configurar e conectar a um porta slave de um ambiente P12.33 no TCloud
Ao executar o DEBUG é apresentada a seguinte mensagem:

"Invalid setting. Verify STARTPATH variable in your environment option or verify if your file settings (.ini) is corrupted"

**OBS**: como não temos acesso ao appserver.ini do TCLOUD foi aberto um chamado para o TCloud que solicitou a abertura da issue por aqui.
Grato

![DEBUG_33](https://user-images.githubusercontent.com/87481832/147141620-3cf00cb0-839e-494d-b06e-cf266bdc7f93.jpg)

**Comment by brodao** [comment]
@danps2005 

Favor verificar [TDS: Depuração e execução](https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md#tds-depura%C3%A7%C3%A3o-e-execu%C3%A7%C3%A3o), o bloco em destaque `Recomendações`.

Pelo mensagem de erro, suponho que:
- O seu ambiente é de `produção` e não `dev`
- Nome do ambiente informado incorreto

Verifique as situações acima junto ao **TCloud**.

Caso o problema continue ou tenha outras ocorrências, reabra este chamado, informando os dados e anexando os logs, conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)

É de extrema importância informar um passo a passo e se possível, anexe print de telas ou vídeo e o console log do Protheus.

A disposição.
