### ISSUE TITLE
Erros ao compiar

### ISSUE THREAD

**Issue by eduardowilliams** [totvs/tds-vscode#874]

**Comment by brodao** [comment]
Abra novo chamado, informando os dados e anexando os logs, conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)

É de extrema importância informar um passo a passo e se possível, anexe print de telas ou vídeo e o console log do Protheus.
