### ISSUE TITLE
Debug no longer works

### ISSUE THREAD

**Issue by elQuau** [totvs/tds-vscode#877]
On the run and debug panel y select my configuration and click de green arrow button and the message "Unexpected token s in JSON at position 0" and it does nothing else.

It worked fine last tuesday.

![image](https://user-images.githubusercontent.com/56559099/147601175-53f1e2f8-ab7e-40b3-905e-b23b80243746.png)

Edition	Windows 11 Pro
Version	21H2
Installed on	‎06/‎10/‎2021
OS build	22000.376
Experience	Windows Feature Experience Pack 1000.22000.376.0

Build AppServer: 7.00.191205P-20210114 - 64 bits
Sistema operativo:Windows Server 2012 R2
Appserver version: 19.3.1.5
Build DBAccess: 20191119-20200217
Release del RPO:  12.1.027
Release del diccionario: 12.1.027 - Fev  2020
Local files: CTREE
License server:2014 - 3.0.1
DB DataBase:MSSQL
DB API Build:20200606-20201110

Remote build:7.00.191205P-20210108
Remote version:19.3.1.2
Remote type:1 - QT-5.14.2 WIN
Modulo: FAT
Nombre de la computadora: 
Sistema operativo: Windows 10 - 
Memoria: 16292
Procesador: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz

Versión de la Lib:20210701
Fecha de Lib: 20210706_16629

VSCODE
Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

TDS v1.3.10

**Comment by brodao** [comment]
@elQuau

**Comment by elQuau** [comment]
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"cwb": "${workspaceRoot}",
			"name": "cloud",
			"smartclientBin": "C:\\totvs\\client\\smartclient-19.3.1.2\\smartclient.exe",
			"program": "sigaadv",
			"programArguments": [],
			"enableMultiThread": true,
			"enableProfile": true,
			"isMultiSession": true,
			"isAccessibilityMode": false,
			"doNotShowSplash": true,
			"openglMode": true,
			"dpiMode": false,
			"language": "2",
			"ignoreFiles": false,
			"enableTableSync": true,
			"logFile": "${workspaceFolder}\\dap.log"
		}
	]
}

**Comment by brodao** [comment]
@elQuau 

The file appears to be correct, but the VS-code not recognizing it.
I will try to find out what it is.
As a workaround, remove the file and create the debug definition again.
Do not use backslash, use a slash or two backslashes wich folder separator.

**Comment by elQuau** [comment]
Thanks.

**Comment by elQuau** [comment]
I belive it has something to do with this line:
 "program": "sigaadv",
when I changed it for:
 "program": "${command:AskForProgramName}",

It works.
