### ISSUE TITLE
PROBLEMAS NA DEPURAÇÃO UTILIZANDO REST NO PORTAL MEURH

### ISSUE THREAD

**Issue by bocaotmkt** [totvs/tds-vscode#879]
Ao tentarmos efetuar a depuração do Portal MEURH o sistema dificilmente para nos pontos de interrupção, aparentemente o debug não está funcionando corretamente. Quando conseguimos executar o debug gera a tela de erro de sincronismo obrigado a restartar todos os serviços dbaccess, appserver, vscode e depuração para fazer uma nova tentativa.

Dados do Server 
Versão: TOTVS Serviços
Build AppServer: 7.00.210324P-20211216 - 64 bits
Nome do servidor: SPON0010115508
Sistema operacional: Windows 10
Appserver version: 20.3.0.5_rc02
Build DBAccess: 20210202-20210930
Release do RPO:  12.1.033
Release do dicionário: 12.1.033
Local files: CTREE
License server: 2014 - 3.3.3
DB DataBase: MSSQL
DB API Build: 20210202-20210930

Dados do Remote 
Remote build: 7.00.210324P-20210914
Remote version: 20.3.0.0
Remote type: 1 - QT-5.15.3 WIN
Módulo: GPE
Nome do computador: SPON0010115508
Sistema operacional: Windows 10 - 
Memória: 16259
Processador: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz

Versão da Lib:20211227
Data da Lib: 20211119_17411
Commit ID:fa612d5a0fcc730cc8898b146037b5cd468fba99

![ERRO DE SINCRONISMO NO DEBUG](https://user-images.githubusercontent.com/72392906/147778192-7fc2cb8d-59e9-450d-ae82-bb7414bc4202.jpg)

**Comment by bocaotmkt** [comment]
[launch - Copia.txt](https://github.com/totvs/tds-vscode/files/7794151/launch.-.Copia.txt)
[settings - Copia.txt](https://github.com/totvs/tds-vscode/files/7794152/settings.-.Copia.txt)

Segue itens

**Comment by brodao** [comment]
@bocaotmkt 

Favor anexar os logs, conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)

No aguardo.

**Comment by bocaotmkt** [comment]
Segue as informações dos logs de hoje 30/12/2021.
[logs.txt](https://github.com/totvs/tds-vscode/files/7794186/logs.txt)

**Comment by brodao** [comment]
Eu preciso dos logs da extensão https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs

**Comment by bocaotmkt** [comment]
[dap.log](https://github.com/totvs/tds-vscode/files/7794238/dap.log)

**Comment by brodao** [comment]
Veja [Depuração de serviços](https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md#depura%C3%A7%C3%A3o-de-servi%C3%A7os-jobs) se ajuda.

**Comment by bocaotmkt** [comment]
Mas essa solução de criar uma função é paliativa certo?

**Comment by danielbolognani** [comment]
Essa não é uma solução paliativa. Para o debug funcionar, a thread de debug precisa subir antes de todas as outras, portanto a única forma de realizar a depuração de um Job (rest ou qualquer outro tipo de serviço) é fazer com que a thread de Job suba pelo debugger (ou depois dele).
Abs.

**Comment by brodao** [comment]
Não. É devido a forma que o REST (jobs) trabalham. Como não possuem interface, você precisa iniciá-lo de alguma forma e ter uma conexão de interface para a depuração em si. Usando dessa forma, você supre as duas necessidades.
