### ISSUE TITLE
Após Atualização do VSCode - Problemas ao Conectar ao Server

### ISSUE THREAD

**Issue by lucsarruda** [totvs/tds-vscode#88]
Bom dia,

Após atualização automática do VSCode, não consigo conectar com Server Local e/ou Remoto. 

Apresenta um erro no log durante a tentativa de conexão : 

[FATAL][SERVER] [Thread 17292] [THROW] Unhandled message at file C:\bamboo-agent-5.7.2\xml-data\build-dir\TP11-BUILDV2APPSRV-TEC11WIN32RPO32\advtec9_tt11\lib_comm\tprotocolrmt.cpp line 15017
Unhandled message in file C:\bamboo-agent-5.7.2\xml-data\build-dir\TP11-BUILDV2APPSRV-TEC11WIN32RPO32\advtec9_tt11\lib_comm\tprotocolrmt.cpp at line 15017

![image](https://user-images.githubusercontent.com/14772095/59608623-1a557300-90ec-11e9-8e6a-92608e11a5a6.png)

![image](https://user-images.githubusercontent.com/14772095/59608579-0578df80-90ec-11e9-99e6-8d1486ddb80e.png)

**Comment by lwtnb-wrk** [comment]
@lucsarruda Qual o servidor que voce esta utilizando? Versão, OS e build?

**Comment by antunesls** [comment]
Tambem estou com esse problema. após atualizar para 0.3.6 , o erro aparece e é o mesmo do relatado acima.

OS : W10

Dados do Server 

Versão: TOTVS Série T 
Build AppServer: 7.00.131227A-20190114 NG - 32 bits
Build DbAccess: 20170202
Release do RPO:  12.1.017
Ambiente: Totvs12
Local files: CTREE
Top DataBase: MSSQL7
Versão da Lib:20180413
Data da Lib: 20180420_95455

**Comment by lwtnb-wrk** [comment]
Mesmo problema da issue #86

**Comment by FrancisOliveira** [comment]
Boa Tarde !!!

O problema da conexão da base local é diferente da #issue 86 .

Tambem estou com problema para conectar base local .

Obrigado

**Comment by rafaeldepaula5000** [comment]
Boa tarde!

Exatamente com o mesmo problema relatado. 

O meu VsCode estava com 1.33.1 e apresentou o problema. Hoje atualizei para 1.35.1 e persiste. Não conecto local nem no servidor.

Att.

**Comment by FrancisOliveira** [comment]
Rafael , 

O #caiadofelipe me deu uma dica pra voltar a versão do TDS VSCODE fiz isso e resolveu . 

Estou utilizando a 0.2.1 e voltou a funcionar  .

Valeu ...

**Comment by linx1010** [comment]
> Rafael ,
> 
> O #caiadofelipe me deu uma dica pra voltar a versão do TDS VSCODE fiz isso e resolveu .
> 
> Estou utilizando a 0.2.1 e voltou a funcionar .
> 
> Valeu ...

Olá Francis, estou com o mesmo problema, como você retornou a versão? reinstalou ou tem como fazer pelo próprio VSCode?

**Comment by charlesreitz** [comment]
+1 
![image](https://user-images.githubusercontent.com/1248135/68297607-2e3b4a80-0076-11ea-8c94-a8564b929245.png)

**Comment by lwtnb-wrk** [comment]
> +1
> ![image](https://user-images.githubusercontent.com/1248135/68297607-2e3b4a80-0076-11ea-8c94-a8564b929245.png)
> 
> ![image](https://user-images.githubusercontent.com/1248135/68297704-5fb41600-0076-11ea-9018-03ac5a29f34d.png)

@charlesreitz Favor não utilizar uma issue fechada para reportar um problema semelhante. Utilize o template "Bug report" e preencha as informacoes requisitadas. Grato

**Comment by charlesreitz** [comment]
> Rafael ,
> 
> O #caiadofelipe me deu uma dica pra voltar a versão do TDS VSCODE fiz isso e resolveu .
> 
> Estou utilizando a 0.2.1 e voltou a funcionar .
> 
> Valeu ...

![image](https://user-images.githubusercontent.com/1248135/68297963-fed90d80-0076-11ea-9a32-f5396a58396a.png)

**Comment by charlesreitz** [comment]
> > +1
> > ![image](https://user-images.githubusercontent.com/1248135/68297607-2e3b4a80-0076-11ea-8c94-a8564b929245.png)
> > ![image](https://user-images.githubusercontent.com/1248135/68297704-5fb41600-0076-11ea-9018-03ac5a29f34d.png)
> 
> @charlesreitz Favor não utilizar uma issue fechada para reportar um problema semelhante. Utilize o template "Bug report" e preencha as informacoes requisitadas. Grato

Blz! Depois que me liguei que ela estava fechada, rs..
