### ISSUE TITLE
Erro na Importação de Arquivos TOTVS Replay

### ISSUE THREAD

**Issue by DaniloTotvs** [totvs/tds-vscode#880]
Ao realizar a importação de um arquivo no Laucher do TOTVS Replay, durante a importação o sistema simplesmente aborta o processo e dá como finalizado, é necessário repetir a importação algumas vezes até que o sistema conclua

A evidência de erro (com áudio) e o arquivo que utilizei em teste foram anexados.
Este comportamento foi reportado por algumas pessoas no suporte.

[Erro TDSReplay.zip](https://github.com/totvs/tds-vscode/files/7809228/Erro.TDSReplay.zip)
[Arquivo de teste.zip](https://github.com/totvs/tds-vscode/files/7809230/Arquivo.de.teste.zip)
.

**Comment by ricardomansano** [comment]
Chamado já sendo acompanhado atraves de ticket interno da Totvs

**Comment by DanielYampolschi** [comment]
Favor baixar e instalar o VSIX do link abaixo com a correção.

https://github.com/totvs/tds-vscode/releases/tag/untagged-fcd4e05c7cd210780aaa
