### ISSUE TITLE
Unexpected token S at position 0

### ISSUE THREAD

**Issue by lucianoaol** [totvs/tds-vscode#881]
04/01/2022

No VsCode, ao tentar executar o debug, aparece a mensagem:

Unexpected token S at position 0, esse 'S' que aparece é SIGAADV que eu coloquei no parâmetro "program": "SIGAADV", do meu arquivo launch,json, segue abaixo o arquivo. Alguém sabe o que pode ser?

Atitudes que já tomei: reiniciei a máquina, deletei o launch.json e deixei o VSCode criar, peguei o launch.json de outra máquina que está funcionando corretamente e sobrepus ao da minha máquina e fiz a mesma coisa com o servers.json. Nenhuma das ações acima surtiu efeito.

Windows 10/Protheus 12.1.27

{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Producao",
			"program": "SIGAADV",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "C:\\PROTHEUS\\smartclient_64\\smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true
		},
	]
}

**Comment by lucianoaol** [comment]
Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by brodao** [comment]
@lucianoaol 

Identificamos um bug e como paliativo, no lugar de fixar uma programa no parâmetro "program", informe "${command:AskForProgramName}". Ao acionar a depuração, lhe será solicitado o nome do programa a ser executado.

Já estamos trabalhando na correção.

Grato pela colaboração.

**Comment by brodao** [comment]
Senhores,

Foi disponibilizado a versão **1.3.11-RC1** do **TDS-VSCode** no projeto do _GITHub_.
Para detalhes da liberação, leia o [CHANGELOG](https://github.com/totvs/tds-vscode/releases/tag/v1.3.11-RC1).

A disposição.
