### ISSUE TITLE
Environment ""does not require authentication

### ISSUE THREAD

**Issue by moisesoliveirabatista** [totvs/tds-vscode#882]
Olá, meu vscode parou de funcionar, quando tento conectar apresenta o erro da imagem a seguir 

![Screenshot_14](https://user-images.githubusercontent.com/65296697/148117560-230f25e3-931f-4246-8a0f-6a50c575478b.jpg)

**Comment by brodao** [comment]
@moisesoliveirabatista 

Parece-me que ao conectar você informou um ambiente (_environment_) que não existe no _appServer.ini_ ou há alguma falha na configuração do ambiente. Veja no log do _appServer_, se há informações que podem nos ajudar.

Se puder anexar o log de console do _appServer_, melhor ainda.

No aguardo.

**Comment by moisesoliveirabatista** [comment]
@brodao 
Olá!!! Segue em anexo o log e appserver para análise.
[Protheus12_dev.log](https://github.com/totvs/tds-vscode/files/7814402/Protheus12_dev.log)
[appserver.txt](https://github.com/totvs/tds-vscode/files/7814413/appserver.txt)

**Comment by danielbolognani** [comment]
Bom dia, aparentemente o seu RPO está corrompido:
[ERROR][SERVER] CheckAuth ERROR: Load APO failed.
Verifique seu ambiente, pegue um novo RPO do portal, se estiver utilizando um RPO Custom, crie um novo e tente novamente.

**Comment by moisesoliveirabatista** [comment]
Boa tarde Daniel, fiz o procedimento e funcionou. Obrigado.
