### ISSUE TITLE
Compilação/Exclusão

### ISSUE THREAD

**Issue by JoelberGarcia** [totvs/tds-vscode#883]
Boa noite, estou com problema tanto na compilação de um fonte, quanto na exclusão do mesmo. Caso eu compile todos os fontes do projeto o VsCode compila normalmente, porém este fonte fala de Aborting: Duplicated function e não deixa eu excluir o fonte.

[Info  - 22:42:51] Using Includes: w:/protheus/protheus/include
[Info  - 22:42:51] Start regular compiling f:/git/work_cemil/CEMIL4.0/COMPRAS/ATUALIZACAO/ACOM012.prw (1/1).
[Error - 22:42:53] [FATAL] Aborting: Duplicated function U_BSMARC() on ACOM012.PRW line:1196. found in RCOMA005.PRW
Duplicated function U_DELOBSENT1() on ACOM012.PRW line:4105. found in RCOMA005.PRW
Duplicated function U_ENTOBS() on ACOM012.PRW line:4078. found in RCOMA005.PRW
Duplicated function U_TL01PORT() on ACOM012.PRW line:22. found in RCOMA005.PRW
Duplicated function U_TL03PORT() on ACOM012.PRW line:336. found in RCOMA005.PRW
Duplicated function U_TL1EXPEDICAO() on ACOM012.PRW line:2714. found in RCOMA005.PRW
Duplicated function U_TL1OUTROS() on ACOM012.PRW line:2884. found in RCOMA005.PRW
Duplicated function U_TL1PORTLIB() on ACOM012.PRW line:141. found in RCOMA005.PRW
Duplicated function U_TL2PORTLIB() on ACOM012.PRW line:248. found in RCOMA005.PRW
Duplicated function U_TL4BALACA() on ACOM012.PRW line:789. found in RCOMA005.PRW
Duplicated function U_TL5BALANCA() on ACOM012.PRW line:1519. found in RCOMA005.PRW
Duplicated function U_TL6BALANCA() on ACOM012.PRW line:2393. found in RCOMA005.PRW
Duplicated function U_TL7BALANCA() on ACOM012.PRW line:3054. found in RCOMA005.PRW
Duplicated function U_TLCARG() on ACOM012.PRW line:468. found in RCOMA005.PRW
Duplicated function U_TLEXPEDICAO() on ACOM012.PRW line:927. found in RCOMA005.PRW
Duplicated function U_TLLAB() on ACOM012.PRW line:2544. found in RCOMA005.PRW
Duplicated function U_TLLAB1() on ACOM012.PRW line:1237. found in RCOMA005.PRW
Duplicated function U_TLOUTROS() on ACOM012.PRW line:1378. found in RCOMA005.PRW
Duplicated function U_TLP1ENTMAT() on ACOM012.PRW line:2246. found in RCOMA005.PRW
Duplicated function U_TLP1SAIDAMAT() on ACOM012.PRW line:654. found in RCOMA005.PRW
Duplicated function U_TLP2ENTMAT() on ACOM012.PRW line:3313. found in RCOMA005.PRW
Duplicated function U_TLP2SAIDAMAT() on ACOM012.PRW line:1867. found in RCOMA005.PRW
Duplicated function U_TLSEXPEDICAO() on ACOM012.PRW line:1721. found in RCOMA005.PRW
Duplicated function U_VALENT1() on ACOM012.PRW line:2358. found in RCOMA005.PRW
Duplicated function U_VALENT2() on ACOM012.PRW line:3294. found in RCOMA005.PRW
Duplicated function U_VALENT3() on ACOM012.PRW line:765. found in RCOMA005.PRW
Duplicated function U_VLD1PLAC() on ACOM012.PRW line:2207. found in RCOMA005.PRW
Duplicated function U_VLDKM() on ACOM012.PRW line:443. found in RCOMA005.PRW
Duplicated function U_VLDPESMAN() on ACOM012.PRW line:3548. found in RCOMA005.PRW
Duplicated function U_VLDPLAC() on ACOM012.PRW line:3712. found in RCOMA005.PRW
Duplicated function U_VLENTPESO() on ACOM012.PRW line:3274. found in RCOMA005.PRW
Duplicated function U_VLNF() on ACOM012.PRW line:1208. found in RCOMA005.PRW

[Info  - 22:42:53] Aborting end build (rollback changes).
[Error - 22:42:53] One or more files have errors and/or warnings. See problems and logs for details.
[Info  - 22:42:53] Recompile finished.

Quando vou excluir, gera a mensagem abaixo.

[Info  - 23:02:04] Starting program deletion.
[Info  - 23:02:04] Starting build for environment cpl.
[Info  - 23:02:06] Starting build using RPO token ...
[Error - 23:02:06] One or more programs could not be deleted from RPO.
[Info  - 23:02:06] Aborting end build (rollback changes).

**Comment by danielbolognani** [comment]
Bom dia, o programa que "precisa" excluir é o RCOMA005.PRW, para isso, crie um arquivo com esse nome (pode deixar ele em branco) e utilize a opção de "Delete File/Resource from RPO".
Se ele foi compilado com Token de compilação, o token é necessário para exclusão também.
Uma outra opção seria recriar o RPO customizado, ou seja, retirar o atual da pasta e recompilar os fontes customizados novamente.
Abs.

**Comment by JoelberGarcia** [comment]
Funcionou conforme orientado, obrigado !
