### ISSUE TITLE
Erro ao compilar no VsCode

### ISSUE THREAD

**Issue by lnesolucoes** [totvs/tds-vscode#884]
Ao atualizar a versão do Protheus para a 12.1.033 o VsCode apresenta o seguinte erro ao tentar compilar qualquer pacote ou customização.

Start build error: Server returned: 
COMPILEERROR-300 
Invalid RPO signature. Please update your RPO file.

**Comment by danielbolognani** [comment]
Bom dia,
Pela mensagem, verifique se o RPO não está corrompido (RPO padrão e Customizado) e adicione a chave BUILDKILLUSERS=1 no General do Appserver.ini

**Comment by lnesolucoes** [comment]
Bom dia,

Eu estou utlizando o rpo que acabei de baixar do portal da TOTVS. Não estou conseguindo em aplicar a LIB.
E mesmo aplicando a chave mencionada o erro ainda persiste.

**Comment by danielbolognani** [comment]
Verifique também o RPO Custom:
https://tdn.totvs.com/display/tec/Application+Server+-+RPOs+Segregados

**Comment by lnesolucoes** [comment]
Muito Obrigado.
Minha configuração do custom estava incorreta, pois eu tinha copiado o RPO principal para a pasta do custom e na verdade ele é criado automaticamente.
