### ISSUE TITLE
Launcher Config sem opção Choose Launcher

### ISSUE THREAD

**Issue by enakamatu** [totvs/tds-vscode#885]
# Help us to help you.

## Before opening an issue

- Make sure the extension is up to date.
- See [Resolução de Problemas](TROUBLESHOOTING.md#problemas-gerais), with common and/or known occurrences.

## Enter the data below

**Describe the bug**
VSCode 1.63.2 em um windows 10
Plugin 1.3.10

Na Criação do launcher não aparece opções no Choose Launcher e não jabilita botão salvar/ fechar

**To Reproduce**
CTRL + p
TOTVS:CONFIGURE LAUNCHERS

**Expected behavior**
Todas as caixas com opções de seleção

**Screenshots**
![image](https://user-images.githubusercontent.com/6952231/148470320-c167db45-12b3-4385-962a-3cf5c9dd24a7.png)

**Desktop (please complete the following information):**
 - Windows 10 x64
 

**Appserver (please complete the following information):**
 - Windows 2012 r2, windows 2016
 - Appserver Harpia ou Lobo Guara - do portal

**Comment by brodao** [comment]
@enakamatu 

Conforme abaixo, o formulário esta funcionando corretamente. No seu caso, não deve haver um lançador definido.
Nesse caso, preencha os campos solicitados e finalize o formulário.  Use a caixa de opções, para editar lançadores já existentes.

![image](https://user-images.githubusercontent.com/949914/148534057-f53ffb9b-1900-4df1-a78e-e4d09011e59d.png)

A disposição.

**Comment by enakamatu** [comment]
Essa janela de opções não aparece...

Em sex, 7 de jan de 2022 07:58, Alan Cândido ***@***.***>
escreveu:

**Comment by brodao** [comment]
O arquivo `.vscode/launcher.json` tem algum lançador definido? Aparentemente não.
Como disse, informe os dados, começando por um nome, depois programa e assim por diante.
Detalhes em [Criando um executor com assistente](https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md#criando-um-executor-com-assistente).
