### ISSUE TITLE
Depurar JSON 

### ISSUE THREAD

**Issue by fsbarbosa90** [totvs/tds-vscode#886]
Olá!

Quando incluímos uma variável na opção de depurar -> inspeção e a variável é um JSON ele não mostra as propriedades do objeto, mostrando apenas um J.

É possível aplicar uma melhoria para podemos ver os dados da variável do tipo JSON na opção watch do VsCode? 

![image](https://user-images.githubusercontent.com/20998140/148585151-4efb1188-0687-4aa9-9689-3605bd289ad0.png)

atenciosamente;
Fernando Barbosa - [GitHub](https://github.com/fsbarbosa90)

**Comment by brodao** [comment]
Fix

**Comment by brodao** [comment]
Senhores,

Foi disponibilizado a versão **1.3.11-RC1** do **TDS-VSCode** no projeto do _GITHub_.
Para detalhes da liberação, leia o [CHANGELOG](https://github.com/totvs/tds-vscode/releases/tag/v1.3.11-RC1).

A disposição.

**Comment by fsbarbosa90** [comment]
Olá.

Deu certo, obrigado!

![image](https://user-images.githubusercontent.com/20998140/153045048-2bd687f6-3d71-4281-8c5a-091729b95880.png)
