### ISSUE TITLE
DEBUG NA VERSÃO 12.1.33 DO PROTHEUS

### ISSUE THREAD

**Issue by mateus-erp** [totvs/tds-vscode#887]
Boa tarde, Pessoal.

Após atualizar a versão do Protheus para a 12.1.33 não conseguimos debugar web services. Conseguem nos ajudar com esse problema?

Informações adicionais:
Versão extensão tds-vscode: 1.3.10
Versão binário: 20.3.0.4

Desde já, agradeço.

**Comment by brodao** [comment]
@mateus-erp 

Veja [Depuração de serviços](https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md#depura%C3%A7%C3%A3o-de-servi%C3%A7os-jobs) se ajuda.

**Comment by mateus-erp** [comment]
@brodao 

Tenho configurado outras versões de binário e consigo utilizar esse recurso normalmente. Com essa afirmação acredito que não é o caso de má configuração.

**Comment by brodao** [comment]
Quais versões de binário?
Parece-me que no Harpia (20 e superiores), os webjobs não inicializam automaticamente. 
Lembrando que o job tem que ser inicializado após a conexão de depuração ter sido efetuada.

**Comment by mateus-erp** [comment]
Segue versão que conseguimos debugar:
Versão do binário: 17.3.0.13

Em meu caso o job é inicializado, digo isso porque consigo fazer requisições ao mesmo via Postman ou Insomnia.

**Comment by brodao** [comment]
Como comentei, ele é inicializado após a conexão de depuração ter sido efetuada? 
Veja os logs dos dois. Salvo engano meu, na 17.3.0.13 seu job será inicializado automaticamente.

**Comment by mateus-erp** [comment]
@brodao 

Ela é inicializada normalmente. Inicio a conexão do debug e marco o break point no local desejado, após isso uso o Postman ou Insomnia para realizar a requisição onde a mesma recebe uma resposta valida e ignora o meu ponto de parada.

**Comment by mateus-erp** [comment]
Abri o ticket 13320028 para o Framework, o anlista realizou acesso remoto a minha máquina e percebeu que não estava respeitando o ponto de parada. Se desejar acessar minha máquina estarei a disposição para ajudar no que possível.

**Comment by mateus-erp** [comment]
![image](https://user-images.githubusercontent.com/58174530/148813751-38b25e0b-72b5-4cca-817d-c0b0c8f3c602.png)

@brodao 

Se notar na imagem o JOB é inicializado antes da thread do debug, mas não funciona. Usando um fonte para iniciar o serviço HTTP o mesmo respeita o ponto de parada. Tem alguma ideia do que seja?

**Comment by mateus-erp** [comment]
Percebi aqui que pode ser as ordens do serviço a serem inicializados. Conforme você disse em notas anteriores a thread do debug tem que ser inicializada antes.

**Comment by git-denison** [comment]
Olá,

Estamos utilizando a versão 33 e percebi que na depuração de serviços (exemplo: API REST), o breakpoint é respeitado somente caso eu realize o passo-a-passo abaixo:

- Comentar a seção OnStart;
- Iniciar o modo de depuração de qualquer função (para deixar a thread em modo de escuta);
- Executar o startrest ou HTTP_START no programa inicial;
- E por último, executar a requisição via postman, thunder client etc).

Seria possível depurar como na versão 25, na qual era necessário apenas executar qualquer função e chamar a requisição (via postman por exemplo)?

Obrigado.

**Comment by mateus-erp** [comment]
O assunto desta issue foi resolvida atualizando o appserver para a versão 20.3.0.8 ou superior.
