### ISSUE TITLE
Erro ao compilar no release 12.33

### ISSUE THREAD

**Issue by zenuellins** [totvs/tds-vscode#889]
No release 12.33 sempre que vamos compilar aparece o seguinte erro:
[INFO ][SERVER] [Thread 25172] Start Build.
2022-01-08T17:44:11.280000-03:00 25172|
[WARN ][SERVER] [Thread 25172] OPEN EMPTY RPO - Environment TESTE - File F:\TOTVS12\B_TESTE\Protheus\apo\custom\custom.rpo
2022-01-08T17:44:11.281000-03:00 25172|
[ERROR][SERVER] Error when loading Rpo DEFAULT
2022-01-08T17:44:11.285000-03:00 25172|------0--f:\totvs12\microsiga\protheus\atualizacoes-12.33\21-11-16-lib_label_16112021_p12_harpia.ptm
2022-01-08T17:44:14.379000-03:00 25172|
[FATAL][SERVER] 08/01/2022 17:44:14[Thread 25172] [THROW] RPO in use at file C:\bamboo\xml-data\build-dir\TP11-OF20300-TECXWIN64\advpl\appmap.hpp line 1710
2022-01-08T17:44:14.380000-03:00 25172|RPO in use in file C:\bamboo\xml-data\build-dir\TP11-OF20300-TECXWIN64\advpl\appmap.hpp at line 1710
2022-01-08T17:44:25.307000-03:00 24228|

 Windows 64 bits SERVER 2019 
 
2022-01-08T17:26:31.348000-03:00 17708|***  TOTVS S/A  ***
***  www.totvs.com.br  ***
* TOTVS - Build 7.00.210324P - Dec  6 2021 - 23:11:05 
* Build: 64 bits
* SVN Revision: 33224

* Build Version: 20.3.0.4
*

**Comment by danielbolognani** [comment]
O RPO está em uso, Para facilitar, utilize a chave BUILDKILLUSERS=1 na seção general do appserver.ini

**Comment by zenuellins** [comment]
Obrigado.


Zenuel Lins
***@***.***
Twitter: @zenuel


Em seg., 10 de jan. de 2022 às 07:48, Daniel Otto Bolognani <
***@***.***> escreveu:

**Comment by leandroayala** [comment]
Aconteceu comigo esse caso, mas se trata de um rpo custom novo. 
No caso do "em uso" o compilador também valida o rpo padrão?

Por exemplo tenho o ambiente **producao : apo01 e custom01**
e tenho o **ambiente compila: apo01 e custom02**

O apo padrão está em uso, mas acredito  que o compilador so valide no caso do custom, ou não?

**Comment by lwtnb-wrk** [comment]
@leandroayala Se todos os ambientes estiverem no mesmo AppServer, e se qualquer ambiente estiver em uso, ocorrerá erro de RPO em uso ao compilar se não houver a presença da chave BUILDKILLUSERS=1 na seção general do appserver.ini

Se não for esta a situação, favor abrir uma nova issue com o maior numero de informacoes possiveis e ja veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.
