### ISSUE TITLE
Ultimo programa executado - F5

### ISSUE THREAD

**Issue by Smmartinez** [totvs/tds-vscode#89]
Boa tarde! Notei um comportamento diferente na versão 0.3.5, quando vamos iniciar o debug apertamos o F5 e digitamos o módulo (função ADVPL) que será executada, quando executamos a primeira vez, o nome da função é salva no arquivo launch.json, quando executamos novamente a função é alterada novamente, mas na terceira execução não é mais alterado ficando sempre a segunda execução.

**Comment by likid** [comment]
Apenas para complementar, a última função utilizada é salva apenas quando o nome não está na lista das funções já utilizadas, por exemplo, utilizo sigaadv para debugar na maioria das vezes, mas se eu chamar uma user function apenas para debug e ela não está na lista de programas já chamados, esta user function é que ficará gravado como sugestão de programa para ser executado, mesmo que eu selecione ou escreta sigaadv novamente.

**Comment by charlesreitz** [comment]
+1

**Comment by danielbolognani** [comment]
Resolvido em versão 0.3.17 ou superior
