### ISSUE TITLE
Erro na aplicação de patch: 

### ISSUE THREAD

**Issue by crondinelli** [totvs/tds-vscode#890]
![image](https://user-images.githubusercontent.com/48812291/148691996-afbc0bf2-e5a6-4ff2-afac-f3d642e261c8.png)
Server atualizado, release 33.  3 patchs acumulados aconteceram a mesma coisa, outras aplicara normalmente.

**Comment by crondinelli** [comment]
Acrescentando, no log do appserver:
------0--d:\clientes\arican\atualizacoes33\expedicao_continua_12_1_33_varejo_tttm120_hp.ptm
[VDRPORT] 220109_135820 258C VSS0315 E ctx:028 CONNECTED,APP_READY sslRead fatal error 1 [SSL_ERROR_SSL]
[VDRPORT] 220109_135820 258C VSS0782 E ctx:028 CONNECTED,APP_READY line=320 cmd=[SSL_read, alocated: 16384] error=336130329 msg=[error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac]
[VDRPORT] 220109_135820 258C VSS0566 E ctx:028 CONNECTED,APP_READY onRecvConnected: processing error or EOF in SSL_read
[VDRPORT] 220109_135820 258C BPC2115 E x 04 ctx:028 error 1 (Incorrect function.) in receive from client 10.0.1.4:60182

**Comment by crondinelli** [comment]
Mais info:
[FATAL][SERVER] 09/01/2022 14:05:01[Thread 10328] [THROW] Invalid ReadMSInt at file C:\bamboo\xml-data\build-dir\TP11-OF20300-TECXWIN64\lib_base\memstream.hpp line 660
Invalid ReadMSInt in file C:\bamboo\xml-data\build-dir\TP11-OF20300-TECXWIN64\lib_base\memstream.hpp at line 660

**Comment by brodao** [comment]
@crondinelli 

Dê uma olhada em #850 e veja se ajuda. 

Caso não resolva, favor reabrir o chamado informando os dados solicitado e anexando os logs, conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema).

É de extrema importância informar um passo a passo e se possível, anexe print de telas ou vídeo e o console log do Protheus.

No aguardo
