### ISSUE TITLE
TDS Replay file not informed

### ISSUE THREAD

**Issue by dyanshythan** [totvs/tds-vscode#891]
**Describe the bug**

Quando solicito a execução aparece a mensagem 
**TDS File not informed**

Encontrei um outro usuário (Nogueira-Candido) com o mesmo problema no issue 440
https://github.com/totvs/tds-vscode/issues/440

Meu arquivo de configuração também está igual ao dele:
-----
{
	"version": "0.2.0",
	"configurations": [
		
		{
			"type": "totvs_tdsreplay_debug",
			"request": "launch",
			"name": "${1:%tds.package.tdsreplay.debug%}",
			"cwb": "${workspaceFolder}",
			"tdsReplayFile": "",
			"ignoreFiles": false,
			"password": "",
			"includeSources": "*",
			"excludeSources": "",
			"smartclientBin": "C:\\TOTVS12127\\Protheus\\bin\\smartclient\\smartclient.exe"
		}
	]
}
-----

O DanielYampolschi sugeriu excluir a configuração do launch.json e criar uma nova. Contudo, onde eu acho as instruções para criar um novo launch.json?

VSCODE 1.63.2 (System Setup)
TDS 1.3.10
(Windows Server 2019 - x64)

Grato desde já

**Comment by DanielYampolschi** [comment]
boa tarde @dyanshythan,

apenas olhando o Json que voce enviou ja da pra perceber que o campo: "tdsReplayFile" está vazio. 
É nele que você deve informar o caminho completo do arquivo do TDS Replay.
ex: "C:\Totvs\TDS Replay\gravacao_replay.trplay"

Você também pode usar um assistente visual conforme o link abaixo:

https://github.com/totvs/tds-vscode/wiki/TDS-Replay#configurando-o-executor

**Comment by danielbuceli** [comment]
@dyanshythan , tive o mesmo problema, não entendi também o que houve.
Eu alterei o launch.json pro conteúdo anterior e funcionou. Vou mandar aqui, só mudar o que for pertinente:

`{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Depuração TOTVS",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "C:\\TOTVS\\ERP\\Protheus\\bin\\smartclient\\smartclient.exe",
			"isMultiSession": true,
			"enableMultiThread": true,
			"enableTableSync": true
		}
	],
}`

**Comment by DanielYampolschi** [comment]
@danielbuceli Esse erro vai aparecer sempre que:

O tipo do launcher for: "type": "totvs_tdsreplay_debug" (Lan;cador do TDS Replay) e o parametro "tdsReplayFile" for vazio ou houver algum problema no caminho informado (Ex: Caminho errado, separador de path errado, extensao errada e etc)


No seu caso, pelo launch.json que você enviou, o seu type agora é "totvs_language_debug" (Lançador de SmartClient, em modo Run ou Debug), o qual possui suas próprias configurações, como por exemplo o parâmetro "smartclientBin", onde deve informar o caminho do executável o do SmartClient. 

Portanto, caso isso apareça, sugiro verificar o arquivo launch.json se está tudo configurado corretamente para o seu objetivo de lançador.

Dito isso, informo que a versão 1.3.10 saiu com problemas na geração e salvamento do arquivo launch.json que poderia fazer com que alguns lançadores mudassem de tipo ou tivessem parâmetros incorretos para o tipo configurado.

Esse comportamento já foi corrigido e a correção estará disponível na versão 1.3.11 liberada oficialmente.

Caso tenha interesse, e por sua conta e risco, você pode instalar o versão 1.3.11-NB disponível no link abaixo via arquivo vsix:

https://github.com/totvs/tds-vscode/releases/tag/v1.3.11-NB1

Caso não saiba como instalar atualização via arquivo .vsix, você pode encontrar tutorial detalhado de como proceder tanto aqui no projeto do plugin quanto na internet de forma geral.

**Comment by xhuntet** [comment]
Srs.,
Possuo a mesma versão apresentada no inicio dessa issue pelo dyanshythan  e utilizei a solução de contorno apresentada pelo danielbuceli.

Nada possibilitou o debug de um fonte particular, que em nada tem haver com o TDS Replay.

Segui os procedimentos passados pelo DanielYampolschi para as configurações do TDS Replay e não localizei as configurações do TDSReplay: Configure Launchers ao pressionar "CTRL + p".

Qual a saida para este cenário?

Obrigado!

**Comment by MarcioDorisbor** [comment]
@xhuntet cara no VS Code Aperta CRTL + SHIFT + P e digita TDSREPLAY vai aparecer a tela para configurar, estava com este problema e depois de 2 hrs procurando na internet achei esse link:
https://marketplace.visualstudio.com/items?itemName=totvs.tds-vscode

**Comment by GabrielCordeiro01** [comment]
boa tarde, o método do @danielbuceli funcionou na minha máquina, juntamente com o auxílio do @DanielYampolschi, muito obrigado!

**Comment by xhuntet** [comment]
MarcioDorisbor, obrigado!

Funcionou.

Abraço!
