### ISSUE TITLE
Erro formatação Classes quando usa ponto e vírgula

### ISSUE THREAD

**Issue by cirilorocha** [totvs/tds-vscode#893]
formatação classes
strings abertas aspa simples e duplas

**Describe the bug**
O VSCode não consegue fazer a formatação do código (colocando as cores de cada elemento) quando é utilizado ; (ponto e vírgula) logo após o nome do método (eu uso esse recurso apenas para deixar o código mais organizado)

**To Reproduce**
Criar uma classe qualquer em ADVLP ou TLPP onde após o nome de um método() colocar um ; e o restante da declaração (Class YYYYYY) na linha abaixo como é esperado. Desta forma todo o texto abaixo não recebe qualquer formatação de cores, dificultando a leitura do código. Porém é tudo compilado normalmente, não gera nenhum erro no código.

**Expected behavior**
Poderia ser tratada essa situação para mostrar a formatação.

**Screenshots**
Como está agora:
![Captura de tela 2022-01-12 170238](https://user-images.githubusercontent.com/96308173/149310946-615d8fd0-324f-4d7a-89ec-81ed4fc8d7a0.jpg)

Como é a formatação correta:
![Captura de tela 2022-01-12 170255](https://user-images.githubusercontent.com/96308173/149311048-485e944c-81b5-48d6-9a80-78282f031012.jpg)

**Desktop (please complete the following information):**
OS/Architecture: Windows 10 20h2 x64

**Appserver (please complete the following information):**
Build (with date): 7.00.191205P-20211019 - 64 bits
OS/Architecture: Windows Server 2012 R2
Build Version: 19.3.1.8

**Comment by cirilorocha** [comment]
@brodao-zz infelizmente essa situação não foi corrigida. Fiz testes com essa versão 1.3.16 e continua exatamente da mesma forma.

**Comment by brodao2** [comment]
Reavaliando a ocorrência.

**Comment by brodao2** [comment]
Foi efetuada a correção, mas apresentou efeito colateral o destaque da sintaxe.

**Comment by lwtnb-wrk** [comment]
Geramos uma versão Pré-Release da v1.3.17 que já deve corrigir este problema.
Se quiser/puder testar, instale a versão https://github.com/totvs/tds-vscode/releases/tag/v1.3.17-RC1 manualmente seguindo https://github.com/totvs/tds-vscode/blob/master/docs/install.md

**Comment by cirilorocha** [comment]
O bug que limpava toda a formação abaixo do ponto e vírgula resolveu. Agora a formatação dos termos Local, Private, Array, Character, etc... foram perdidos.

![image](https://user-images.githubusercontent.com/96308173/210631270-b89da8eb-0a2e-47f7-b898-c419b44c55f0.png)

**Comment by lwtnb-wrk** [comment]
@cirilorocha Pode disponibilizar esse fonte? Nos meus testes não observei esses problemas aqui.

**Comment by cirilorocha** [comment]
Claro segue em anexo. Mandei só um pequeno trecho que já mostra a situação. Obs.: a extensão original é .prw renomeei só para anexar aqui.

[FonteTeste.txt](https://github.com/totvs/tds-vscode/files/10346956/FonteTeste.txt)

**Comment by lwtnb-wrk** [comment]
@cirilorocha Já reproduzimos a ocorrência, realmente nos focamos demais no ';'. Já estamos corrigindo. Grato pelos testes.

**Comment by lwtnb-wrk** [comment]
@cirilorocha Poderia validar a https://github.com/totvs/tds-vscode/releases/tag/v1.3.17-RC3 para confirmar que o problema foi corrigido?

**Comment by cirilorocha** [comment]
@lwtnb-wrk Fiz testes com essa versão e ele trouxe a formatação apenas do escopo (Loca, Private,etc.) os tipos das variáveis (AS Numeric, Character, etc.) ainda permanecem sem destaque de cor.

![image](https://user-images.githubusercontent.com/96308173/211892562-3e42de72-e4da-43a9-bbce-d2d411df430d.png)
