### ISSUE TITLE
Compilador aceita strings sem caractere de fechamento

### ISSUE THREAD

**Issue by cirilorocha** [totvs/tds-vscode#894]
**Describe the bug**
No VSCode (e nos compiladores anteriores também acontecia) o compilador aceita deixar strings faltando o caractere de fechamento (aspa simples ou aspa dupla) e compila o código normalmente. Não é um problema crítico, porém, as vezes oculta algum ponto onde podem existir erros, já que o restante inteiro da linha fica como sendo parte da string.

**To Reproduce**
Em um código qualquer ADVPL ou TLPP escrever uma string iniciando com aspa simples ou dupla e não fechando o a mesma como respectivo caractere. Ao compilar tudo ocorre normalmente e o fonte até funciona, mas, não deveria porque existe uma estrutura aberta (a string).

**Expected behavior**
Nesses cenários deveria apresentar um erro de compilação ou no mínimo um alerta informando esse ponto onde a string não foi corretamente encerrada.

**Screenshots**
Forma errada (atualmente aceita):
![Captura de tela 2022-01-13 072103](https://user-images.githubusercontent.com/96308173/149312863-d7c6355b-e84e-430e-b4cc-69d26c718a88.jpg)

Forma correta:
![Captura de tela 2022-01-13 072109](https://user-images.githubusercontent.com/96308173/149312908-9441f694-40e3-4e61-beb4-2f0c4adffb1d.jpg)

**Desktop (please complete the following information):**
OS/Architecture: Windows 10 20h2 x64

**Appserver (please complete the following information):**
Build (with date): 7.00.191205P-20211019 - 64 bits
OS/Architecture: Windows Server 2012 R2
Build Version: 19.3.1.8

**Comment by brodao** [comment]
@cirilorocha 

O _EOL_ (fim de linha) é considerado como terminador de string válido pelo compilador.

**Comment by cirilorocha** [comment]
Eu entendo que o funcionamento seja assim, porém, é uma situação bastante incomum e que pode induzir a erros, seria muito mais seguro e padrão de outras linguagens tratar o fechamento. É como se pudesse usar um parêntese sem o seu correspondente final.

**Comment by danielbolognani** [comment]
Bom dia @cirilorocha. concordo com o seu posicionamento, porém a nossa extensão é apenas uma ponte entre o usuário e o Appserver e quem controla a sintaxe da linguagem é o próprio Appserver.
Nós não temos como alterar esse comportamento, portanto se preferir abra um chamado direto para a equipe de Appserver através do portal de clientes.

Abraços!

**Comment by cirilorocha** [comment]
Entendo @danielbolognani que o plugin é uma ponte, mas ele pode fazer esse controle, a programação ficaria mais segura e robusta com esse tratamento e isso não iria interferir em nada o funcionamento da linguagem. Caso isso não seja possível com ADVPL seria interessante implementar em TLPP (já que é uma revisão melhorada da linguagem), essa alteração seria muito interessante e só agregaria.
