### ISSUE TITLE
Não mostra tabela como resultados da compilação

### ISSUE THREAD

**Issue by cirilorocha** [totvs/tds-vscode#895]
**Describe the bug**
Na versão mais recento do plugin do VSCode (v1.3.10) o sistema não mostra mais os resultados da compilação na tela na forma de tabela como era antes. Isso dificulta muito identificar erros quando compilamos muitos fontes de uma vez, já que o compilador nesse caso não vai exibir os resultados no console.

**To Reproduce**
Compilar vários arquivos de um projeto de uma vez só clicando com botão direito nos arquivos ou pasta e escolhendo a opção Compilar Arquivo/Pasta (Ctrl+F9). O sistema vai compilar os arquivos e apresentar uma notificação 'Show table with compile results?' questionando se quer que mostre os resultados em uma tabela, ao clicar em Yes o compilador abre a tela porém sem informação alguma (em branco).

**Expected behavior**
Antes esta tela aparecia normalmente, deveria continuar aparecendo e mostrando os resultados.

**Screenshots**
![Captura de tela 2022-01-13 073214](https://user-images.githubusercontent.com/96308173/149314992-04e0bd31-58af-4896-b614-60d4b0fa1555.jpg)

https://user-images.githubusercontent.com/96308173/149315156-fd46b9cb-e069-4e50-8fcd-033d0552933f.mp4

Desktop (please complete the following information):
OS/Architecture: Windows 10 20h2 x64

Appserver (please complete the following information):
Build (with date): 7.00.191205P-20211019 - 64 bits
OS/Architecture: Windows Server 2012 R2
Build Version: 19.3.1.8

**Comment by brodao** [comment]
@cirilorocha 

Já foi corrigido. Favor aguardar próxima liberação.

Grato por nos avisar.

**Comment by brodao** [comment]
Senhores,

Foi disponibilizado a versão **1.3.11-RC1** do **TDS-VSCode** no projeto do _GITHub_.
Para detalhes da liberação, leia o [CHANGELOG](https://github.com/totvs/tds-vscode/releases/tag/v1.3.11-RC1).

A disposição.

**Comment by brodao** [comment]
Senhores,

Esta correção apresentou efeitos colaterais. 
Favor aguardar próxima liberação.

**Comment by brodao** [comment]
Senhores,

Foi disponibilizado a versão [1.3.11-RC2](https://github.com/totvs/tds-vscode/releases/tag/v1.3.11-RC2) do TDS-VSCode no projeto do GITHub.
Para detalhes da liberação, leia o [CHANGELOG](https://github.com/totvs/tds-vscode/blob/dev/CHANGELOG.md).

A disposição.

**Comment by Smmartinez** [comment]
Boa tarde! Baixei para testar essa liberação e o CTRL+F9 parou de compilar o fonte aberto. testei o CTRL+10 e compilou todas as janelas abertas.

**Comment by lwtnb-wrk** [comment]
@Smmartinez Valeu pelo aviso. Já estamos averiguando a ocorrencia.

**Comment by brodao** [comment]
Corrigido. Favor aguardar liberação.
