### ISSUE TITLE
Problema ao aplicar customização dentro do vscode

### ISSUE THREAD

**Issue by saulobsb** [totvs/tds-vscode#896]
![image](https://user-images.githubusercontent.com/81323360/149822157-3f6c87e7-1cff-4c41-a9f2-239f4edf0cdc.png)

Tenho uma customização no totvs protheus, a aplicava no antigo modulo IDE development, agora não estou conseguindo aplicar a customização, aparentemente está sinalizando que está em uso a aplicação.

Como posso resolver ?

**Comment by danielbolognani** [comment]
Boa tarde @saulobsb 
Provavelmente existe algum serviço/job em execução (REST?), de qualquer forma, adicione a chave BUILDKILLUSERS=1 na seção general do appserver.ini que irá derrubar qualquer serviço/job que esteja em execução.

Abraços!

**Comment by lwtnb-wrk** [comment]
@saulobsb Pelo erro retornado pelo Appserver seu RPO parece estar com permissão de leitura somente (Read-Only status). 
Para funcionar corretamente nesse caso o RPO necessita ter permissões de escrita também. Verifique as permissões de seu RPO e reinicie o Appserver após liberar a permissão de escrita nele.

**Comment by saulobsb** [comment]
Deu certo, stop no serviço tss e taf_full para o vscode conseguir aplicar a customização

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
