### ISSUE TITLE
Erro ao abrir Debug da Release 12.1.33 do Protheus 

### ISSUE THREAD

**Issue by Miguel-Renan** [totvs/tds-vscode#897]
Boa tarde  !

Estou com erro ao tentar iniciar o DEBUG na versão 12.1.33 do Protheus é apresentado o erro abaixo:

![image](https://user-images.githubusercontent.com/67808410/150013271-6155e68a-de56-40a7-ae8a-7e874bfc2df6.png)

Nas release anteriores o DEBUG funciona de forma correta.

Poderiam me auxiliar no processo.

Obrigado.

**Comment by brodao** [comment]
Reabra este chamado informando os dados solicitados e anexe os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)

É de extrema importância informar um passo a passo e se possível, anexe print de telas ou vídeo e o console log do Protheus.

No aguardo
