### ISSUE TITLE
Compilation Result está em branco

### ISSUE THREAD

**Issue by marloncostabhz** [totvs/tds-vscode#898]
Após compilar um fonte no Protheus Release 12.1.27 a tela que deveria conter a lista dos fontes compilados (Compilation Result), está vazia.

**Comment by brodao** [comment]
Reabra este chamado informando os dados solicitados e anexe os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)

É de extrema importância informar um passo a passo e se possível, anexe print de telas ou vídeo e o console log do Protheus.

No aguardo

**Comment by danielbolognani** [comment]
Duplicated #895
