### ISSUE TITLE
O monitor de usuários fica apenas com tela preta

### ISSUE THREAD

**Issue by lumattioli** [totvs/tds-vscode#899]
**Describe the bug**
O monitor de usuários fica apenas com tela preta

**To Reproduce**
1. Conecto no servidor
2. Seleciono o Ambiente
3. Digito usuário e senha
4. O servidor conecta com sucesso
5. Seleciono a opção Abrir Exibição Monitor
6. No console de saída apresenta que esta conectado, Starting get users e Get users finished
7. No monitor a tela apenas fica preta o tempo todo, não mostrando os resultados

**Expected behavior**
Deve ser exibidos os usuários conectados no ambiente selecionado

**Screenshots**
![image](https://user-images.githubusercontent.com/98025802/150152786-d773449a-4bb9-41e3-b5ff-caf74061be72.png)

**Desktop**
 Windows 64 bits

**Appserver**
Dados do Server 

Versão: TOTVS Distribuição e Logística
Build AppServer: 7.00.191205P-20210522 - 64 bits
Nome do servidor: BOSON
Sistema operacional: Windows Server 2016
Appserver version: 19.3.1.7
Build DBAccess: 20200606-20210903
Release do RPO:  12.1.027 - Out  2020
Release do dicionário: 12.1.027 - Out  2020
Local files: ctree
License server: 2014 - 3.3.1
DB DataBase: MSSQL
DB API Build: 20200606-20210405

**Additional context**
Em casos de dúvidas por favor entrar em contato no telefone 035-99135-6874 (Luciano Mattioli - Expresso Nepomuceno)
Vários desenvolveres e analistas estão com o mesmo problema

A versão do plugin Totvs no VsCode já é a mais atualizada e não existe mais nenhum outro plugin atualizado.

**Comment by danielbolognani** [comment]
Bom dia,
Já corrigimos esse problema que estará disponível na próxima versão do VSCode.

**Comment by lumattioli** [comment]
Mais não seria problema no plugin da TOTVS? Seria então na versão do programa VSCode mesmo? Assim que tiver ok, receberei o email e fazer a atualização, obrigado!

**Comment by danielbolognani** [comment]
Só corrigindo o comentário, na próxima versão da extensão do TDS VSCode.
O problema está em nossa extensão mesmo.
Abraços!

**Comment by brodao** [comment]
Senhores,

Foi disponibilizado a versão **1.3.11-RC1** do **TDS-VSCode** no projeto do _GITHub_.
Para detalhes da liberação, leia o [CHANGELOG](https://github.com/totvs/tds-vscode/releases/tag/v1.3.11-RC1).

A disposição.
