### ISSUE TITLE
Parâmetros das funções do intelisense não tem nome

### ISSUE THREAD

**Issue by Vitor-Santos-Totvs** [totvs/tds-vscode#9]
Nas funções sugeridas pelo intelisense, os parâmetros aparecem apenas com o nome de seus tipos e não com o nome do parâmetro, dificultando assim identificar o que significa cada parâmetro.

![bug parametro plugin vscode](https://user-images.githubusercontent.com/50745570/57936591-a6307100-789a-11e9-98cc-f491422fea71.jpg)

**Comment by izacsc** [comment]
Relacionado ao intelisense, as variáveis lógicas não estão sendo apresentadas corretamente, como dá pra ver no print. 

O último argumento seria lChangeCase conforme o tdn 
http://tdn.totvs.com/display/tec/FCreate

**Comment by Vitor-Santos-Totvs** [comment]
Nao mencionei esse problema das variáveis lógicas porque seria muito mais eficiente trocar esses tipos que aparecem na assinatura diretamente para o nome dos parâmetros usando a primeira letra para identificar o tipo, como usado no padrão do advpl.

**Comment by matheus-sales** [comment]
Srs, 

Essa é uma lista que montamos para simplificar o processo e ter alguma informações (mesmo que minima) sobre as funções. Iremos trabalhar para atualizar a lista e traze informações mais completas (Como nome de cada parâmetro e documentação). 

A intenção é trazermos informações que estão no TDN, mas precisamos estudar a viabilidade.

**Comment by Vitor-Santos-Totvs** [comment]
> Srs,
> 
> Essa é uma lista que montamos para simplificar o processo e ter alguma informações (mesmo que minima) sobre as funções. Iremos trabalhar para atualizar a lista e traze informações mais completas (Como nome de cada parâmetro e documentação).
> 
> A intenção é trazermos informações que estão no TDN, mas precisamos estudar a viabilidade.

Imaginei mesmo que já estavam cientes dessa questão. Aconselho colocarem o roadmap do plugin, mesmo que parcial, aqui no git para evitar solicitações cuja implementação já está programada.

**Comment by DanielYampolschi** [comment]
Essa tarefa é duplicada com a issue #14 a qual está no roadmap e será acompanhada por lá.

**Comment by ricardomansano** [comment]
Senhores, os fontes do binário (c++) nao guardam nome dos parametros, se alguem publicou isso pegou manualmente ou do TDN, @matheus-sales e @DanielYampolschi , creio que será possivel pegar essas informações  do RPO, mas que fique claro que do BIN, sistemicamente, não é possivel.

**Comment by Vitor-Santos-Totvs** [comment]
> Senhores, os fontes do binário (c++) nao guardam nome dos parametros, se alguem publicou isso pegou manualmente ou do TDN, @matheus-sales e @DanielYampolschi , creio que será possivel pegar essas informações do RPO, mas que fique claro que do BIN, sistemicamente, não é possivel.

Sim, pelo que eu vi no binário não tem informação sobre o nome das variáveis, apenas o tipo. Até onde eu sei o RPO guarda apenas funções compiladas em advpl, portanto nao teria como pegar informações da assinatura das funções do binário nele. Imagino que para pegar essas informações da assinatura, os dados teriam que ser retirados do TDN mesmo, como alguns outros plugins do advpl fizeram.

**Comment by ricardomansano** [comment]
@Vitor-Santos-Totvs , exato, as arquiteturas são diferentes, o RPO trabalha como uma tabela, então temos essas informação lá, mas quando falamos de binário isso vira assembler/endereço de memória, temos até alguns identificadores pra definirmos as funções "publicadas" para o AdvPL/4GL, mas as informações são reduzidas. Pra melhorar (corretamente) isso precisamos mexer na arquitetura (camada de publicação de funções), é plausível mas "nada" trivial. Podemos deixar na wishlist, mas sem previsão para melhoria. Valew pela interação.

**Comment by ricardomansano** [comment]
Essa implementação depende da criação do nosso motor de parser que foi prorrogada para o primeiro semestre de 2020, manteremos os canais informados quando da liberação.
