### ISSUE TITLE
Erro ao conectar base Local 

### ISSUE THREAD

**Issue by FrancisOliveira** [totvs/tds-vscode#90]
Boa Tarde !

Estou tentando conectar o VSCode a minha base local porem apresenta o erro . 

Obs. Esse problema está acontecendo apenas para as bases locais fiz um teste em outra base de cliente e conectou sem problema  .

![image](https://user-images.githubusercontent.com/51196810/59706089-16058480-91d6-11e9-9a81-b3f3ad30d81f.png)

Obrigado

**Comment by caiadofelipe** [comment]
@FrancisOliveira , você atualizou a versão da Extensão? 
Estou com o mesmo problema na versão atualizada, voltei a versão para 0.2.1 e nela está funcionando

**Comment by lwtnb-wrk** [comment]
@FrancisOliveira Voce consegue se conectar nesse servidor 127.0.0.1:4012 atraves de um Smartclient??

**Comment by FrancisOliveira** [comment]
Sim , consigo conectar sem problema , nessa base eu estava conectando com o antigo TDS ... 

Valeu

**Comment by FrancisOliveira** [comment]
#Felipe

Legal , sua dica , so uma duvida  com fazer pra voltar a versão de uma Extensão ? 

Valeu ... e obrigado pela ajuda

**Comment by caiadofelipe** [comment]
![image](https://user-images.githubusercontent.com/49681823/59708387-0e94aa00-91db-11e9-99df-0c354b0a55da.png)

**Comment by FrancisOliveira** [comment]
Felipe  , 

Perfeito , deu certo ... então o problema está mesmo na nova versão, vamos aguardar a correção pra fazer um update ...  

Valeu ..

**Comment by lwtnb-wrk** [comment]
Estamos testando a [pre-release 0.3.10](https://github.com/totvs/tds-vscode/releases/tag/0.3.10) que será liberada assim que testada.
