### ISSUE TITLE
Erro na compilação com usuários presos/conectados

### ISSUE THREAD

**Issue by IvanSoares821** [totvs/tds-vscode#900]
Bom dia.

Após atualizar a versão do Protheus para 12.1.33 e o VSCode para a versão v 1.63.3, ao compilar o sistema com algum usuário preso/conectado, o VSCode não avisa mais que não foi possível acesso exclusivo e corrompe o RPO, não permitindo mais o acesso por nenhum usuário, a não ser voltando o backup do RPO.

Gostaria de saber como solucionar este problema.

Obrigado.

Att.

Ivan Soares

2022-01-17T17:47:03.091000-03:00 7640|
[WARN ][SERVER] [Thread 7640] Connection finished by inactivity (INACTIVETIMEOUT active)

2022-01-17T17:47:03.091000-03:00 7640|
[WARN ][SERVER] [THROW][Thread  7640] tConnnErrorException (16:Disconnection by inactivity) on C:\bamboo\xml-data\build-dir\TP11-OF20300-TECXWIN64\lib_comm\msgmanager.cpp:591

2022-01-17T17:47:03.093000-03:00 7640|
[WARN ][SERVER] [Thread 7640] [17/01/2022 17:47:03] Thread finished (ivan.gouvea, NOT-SGS-06) Disconnection by inactivity

2022-01-17T17:48:17.877000-03:00 12068|
[ERROR][SSL] PEM_read_bio_RSA_PUBKEY error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
2022-01-17T17:48:17.877000-03:00 12068|
[FATAL][SERVER] 17/01/2022 17:48:17[Thread 12068] [THROW] failed to decrypt 2 at file C:\bamboo\xml-data\build-dir\TP11-OF20300-TECXWIN64\lib\security.cpp line 719

2022-01-17T17:48:20.511000-03:00 12068|
[INFO ][SERVER] [Thread 12068] [17/01/2022 17:48:20] Error ending thread (ivan.gouvea, NOT-SGS-06) 

2022-01-17T17:48:45.269000-03:00 8692|
[INFO ][SERVER] [Thread 8692] Start Build.

2022-01-17T17:48:48.012000-03:00 8692|
[INFO ][SERVER] [Thread 8692] Compiling CONSPVEN.PRW

2022-01-17T17:48:48.021000-03:00 8692|CONSPVEN.PRW:348

**Comment by danielbolognani** [comment]
O pessoal do Appserver está revendo o processo de acesso ao RPO, enquanto isso, adicione a chave BUILDKILLUSERS=1 na seção General do seu appserver.ini que deve resolver o seu problema.
(Nossa extensão não tem controle sobre isso)

**Comment by IvanSoares821** [comment]
Boa tarde.

Obrigado Daniel.

Entao o problema nao é no Vscode e sim no novo appserver harpia ?

Att.

Ivan

Em qua., 19 de jan. de 2022 13:32, Daniel Otto Bolognani <
***@***.***> escreveu:
