### ISSUE TITLE
Desfragmentação com problema na versão HARPIA

### ISSUE THREAD

**Issue by lbbsantos** [totvs/tds-vscode#901]
Conforme vou aplicando pacotes e desfragmentando a minha RPO está só crescendo de tamanho.
Eu fiz uma simulação aplicando vários pacotes que tenho guardado de backup e o resultado foi o seguinte:

Arquivo: 21-10-08-REPOSITORIO_DE_OBJETOS_BRASIL_12_1_33_TTTM120.RPO
Tamanho original: 311MB
 
1.	Apliquei 12 pacotes e ficou no tamanho de 722MB, desfragmentei e ficou 428MB
2.	Apliquei mais 16 pacotes e ficou no tamanho de 846MB, desfragmentei e ficou 574MB
3.	Apliquei mais 23 pacotes e ficou no tamanho de 1.253MB, desfragmentei e ficou 830MB
4.	Apliquei mais 10 pacotes e ficou no tamanho de 1.123MB, desfragmentei e ficou 936MB
5.	Apliquei mais 19 pacotes e ficou no tamanho de 1.517MB, desfragmentei e ficou 1.150MB
6.	Apliquei mais 8 pacotes e ficou no tamanho de 1.418MB, desfragmentei e ficou 1.256MB
 
Tamanho final: 1.256MB

Vocês já tem alguma solução para esse problema?

**Comment by danielbolognani** [comment]
Boa tarde @lbbsantos, quem controla o defrag de RPO é o Appserver, não temos ação do lado da extensão TDS-VSCode.
Por favor abrir no portal de clientes, um chamado para a equipe de Appserver.

Abraços!
