### ISSUE TITLE
ERRO na COMPILAÇÃO DOS FONTES - Versão 12.1.33

### ISSUE THREAD

**Issue by FelipeDuarteLuna** [totvs/tds-vscode#902]
Boa Tarde Engenharia,

Sou Felipe e faço parte do Dev Team do TSS, não estou conseguindo compilar fontes no TSS ou M. Protheus versão 12.1.33. Consigo apenas tirar inspetor de objetos e aplicar patch.

![image](https://user-images.githubusercontent.com/29357935/150205602-9dd1e39a-d607-4e60-9d99-e6e1f8d183db.png)
"### [ERROR][SERVER] IPM.PRW(0)   Regular functions are not allowed in code. Use USER FUNCTION or STATIC FUNCTION."

Versão VS Code:
![image](https://user-images.githubusercontent.com/29357935/150205321-1b7769aa-6024-4400-8476-a4eaf8e0eedb.png)

Chave de compilação válida, emitida através do MACHIDE ID

![image](https://user-images.githubusercontent.com/29357935/150205455-0df481a8-4a11-45d6-8a29-42a847c5f049.png)

Seguimos a documentação oficial, para configuração do TOKEN e mesmo assim o incidente persiste.
https://code.engpro.totvs.com.br/engpro/vscode-engpro-extension/wiki/Instala%C3%A7%C3%A3o-%28PT-BR%29#personal-access-token

Poderia me ajudar ?

Meu e-mail e chat é felipe.luna

Atenciosamente,
Felipe Luna.
Desenvolvimento TSS-NFS-e.

**Comment by danielbolognani** [comment]
Boa tarde @FelipeDuarteLuna 
Esse erro é exatamente a falta de Token de compilação. Recomendo entrar em contato com o time da Engenharia, que é responsável pela geração dos tokens, pois na extensão TDS-VSCode o token é apenas repassado para o Appserver (caso ele esteja configurado corretamente).

Abraçoes!
