### ISSUE TITLE
"Communication error" ao realizar debug - Release 12.1.27

### ISSUE THREAD

**Issue by williankaneta** [totvs/tds-vscode#903]
Bom dia, 

Ao realizar o debug, em algumas situações aleatórias está ocorrendo o problema conforme print em anexo: "Communication error: Failure receiving message in file....", só voltando a funcionar o acesso após reiniciar os serviços pelo T-Cloud

Atualmente a base está com a release 12.1.27 e o binário do appserver está na última versão, a base está no T-Cloud. 

O plugin da TOTVS está na versão v1.3.1
![erro_base_protheus](https://user-images.githubusercontent.com/56980682/150343936-fd1397a2-05f6-44f2-80c7-2fb7f7476809.png)
0

**Comment by danielbolognani** [comment]
Bom dia @williankaneta 
Primeiramente precisamos analisar o problema na última versão disponível da extensão (que hoje é a versão 1.3.10), após isso se o problema continuar ocorrendo, precisamos dos logs da extensão (https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs) e também do console.log do Appserver com a ocorrência do erro.
Quando conseguir essas informações favor pode reabrir a issue.

**Comment by brodao** [comment]
@williankaneta 

Veja as notas sobre [depuração](https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md#tds-depura%C3%A7%C3%A3o-e-execu%C3%A7%C3%A3o). Se não for um dos casos citados, reabra este chamado informando os dados solicitados e anexe os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)

No aguardo
