### ISSUE TITLE
Erro ao iniciar o DEBUG na versão 12.1.33 do Protheus

### ISSUE THREAD

**Issue by Miguel-Renan** [totvs/tds-vscode#905]
Bom dia !
Estou com erro ao iniciar o DEBUG na versão 12.1.33 do Protheus é apresentado o erro abaixo:
 
![image](https://user-images.githubusercontent.com/67808410/150531956-4abf34e4-6536-48b0-82b3-2d2a3b37ceca.png)

Nas releases anteriores o DEBUG funciona de forma correta.
Poderiam me auxiliar no processo.

Logs e versões do ambiente :
 
![image](https://user-images.githubusercontent.com/67808410/150531975-1e1fc422-2bdd-483f-8dba-09cb3961f111.png)

![image](https://user-images.githubusercontent.com/67808410/150532000-ebdc099e-4add-4790-a091-80e03e5841a7.png)

Log:
 
[totvsls.log](https://github.com/totvs/tds-vscode/files/7913845/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/7913846/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/7913847/totvsls_out.log)
[dap.log](https://github.com/totvs/tds-vscode/files/7913850/dap.log)

Obrigado.

**Comment by brodao** [comment]
@Miguel-Renan 

Favor efetuar como teste a execução do comando abaixo no console de comando (cmd.com).
`C:\Program Files\PROTHEUS12_33\Protheus\bin\smartclient\smartclient.exe -z=Localhost -y=1236 -ssl "-E=d-1" "-P=SIGAMDI"  -M -L=1`

Retorna nesse chamado o que ocorreu e anexar o arquivo launcher.json.

No aguardo.

**Comment by Miguel-Renan** [comment]
Teste no CMD

![image](https://user-images.githubusercontent.com/67808410/150574759-7b3d0378-945a-41a5-84e2-43b68e431a45.png)

Arquivo .json
[launch.txt](https://github.com/totvs/tds-vscode/files/7915652/launch.txt)
[settings.txt](https://github.com/totvs/tds-vscode/files/7915653/settings.txt)

**Comment by brodao** [comment]
O teste em linha de comando, ficou errado. 
`"C:\Program Files\PROTHEUS12_33\Protheus\bin\smartclient\smartclient.exe" -z=Localhost -y=1236 -ssl "-E=d-1" "-P=SIGAMDI"  -M -L=1`

O caminho e o nome do executável tem que ficar entre aspas.

**Comment by Miguel-Renan** [comment]
Bom dia 

Ao incluir as aspas no comando o mesmo funciona e abre o Smart cliente subindo o Protheus.

**Comment by brodao** [comment]
@Miguel-Renan 

Efetuei vários testes aqui e não reproduzi sua ocorrência. Estou desconfiado que é algo relacionado a privilégios de acesso a pasta ``c:\Program Files``. Experimente executar o VS-Code como "administrador" (mesmo você sendo administrador). Se executar é questão de privilégio. 
Então mova a pasta que contém o _smartClient_ para o raiz do _drive_, ajuste a configuração para o novo endereço e teste novamente.

Aguardo retorno.
