### ISSUE TITLE
RPO corrompendo na aplicação de Patch - Release 12.1.33 Harpia

### ISSUE THREAD

**Issue by jpedrosantana** [totvs/tds-vscode#906]
Olá, há algum tempo estou com problemas na aplicação de Patch e pacotes emergenciais para a versão 12.1.33 do Protheus.

Algumas compilações são aplicadas com êxito, porém a maioria são aplicadas com data invalida, corrompendo o RPO até um ponto que o ambiente para de iniciar e eu tenho que solicitar um novo RPO para a TOTVS. Em chamados abertos no cloud, me orientaram a abrir uma issue aqui.

Solicitei um RPO zerado para efetuar novos testes antes de abrir essa issue, em anexo estou colocando um print do RPO inicial, e do RPO após a compilação mau sucedida. Apliquei a expedição contínua do backoffice, que foi bem sucedida (primeira data do print, 2022-01-23), e após isso apliquei a expedição do varejo, que apresentou esse problema de data invalida.

Na aplicação da patch eu não seleciono a opção para compilar arquivos antigos, também estou anexando o log do VsCode e o log do console.

Acompanhei a issue 850, porém o problema persiste, por isso estou abrindo uma nova.

Versão VSCode:
Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

Versão TDS: v1.3.11-RC1 (testei com a versão mais nova, mas também da problema nas versões 1.3.8, 1.3.9 e 1.3.10)

Informações da LIB	
Versão da Lib:	20211004
Data da Lib:	20211006_135652
ID da Lib:	94c212d6522f77c511f4ddc68641247405742f8b
Release:	12.1.033
HardLock:	2014
Versão do License Server:	3.3.3
Versão do Protheus:	TOTVS Serviços
Dicionário no banco de dados:	Sim

Informações do AppServer	
Tipo do servidor:	Console
AppServer Build:	7.00.210324P-20211206
Appserver version:	20.3.0.4
Servidor 64 bits:	Sim
Servidor Unix:	Não

RPO Zerado antes das aplicações
<img width="651" alt="RPO_zerado" src="https://user-images.githubusercontent.com/66541114/150699293-aea59f42-814e-4e50-af61-b4987e797470.PNG">
RPO com data invalida
<img width="496" alt="RPO_data_invalida" src="https://user-images.githubusercontent.com/66541114/150699292-60760f90-5298-4c91-998c-b4ea2d13e62c.PNG">

[console_log.txt](https://github.com/totvs/tds-vscode/files/7921517/console_log.txt)
[VsCode_log_varejo.txt](https://github.com/totvs/tds-vscode/files/7921518/VsCode_log_varejo.txt)

**Comment by brodao** [comment]
@jpedrosantana 

A extensão TDS-VSCode é apenas um camada de comunicação com o _appServer_. No seu caso, acredito que o pacote tenha sido gerado com algum problema de data. Solicito que abra um chamado para suporte do appServer no sítio [Suporte TOTVS](https://totvscst.zendesk.com/hc/pt-br/#home).

A disposição.
