### ISSUE TITLE
Depuração de REST em ambiente TCLOUD

### ISSUE THREAD

**Issue by eliandropaya** [totvs/tds-vscode#907]
Segui as orientações contidas no caminho

https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md

porém não consigo realizar o DEBUG de uma REST em Ambiente TCLOUD

**Comment by brodao** [comment]
Favor ser mais específico. Qual a ocorrência?

**Comment by eliandropaya** [comment]
Bom dia!

o Rest esta rodando com SSL, seguem abaixo os print.

<img width="551" alt="Captura de Tela 2022-01-25 às 09 51 54" src="https://user-images.githubusercontent.com/20544986/150990302-716be965-3b3a-4bb3-ab06-bcccebb221cb.png">
<img width="374" alt="Captura de Tela 2022-01-25 às 09 51 10" src="https://user-images.githubusercontent.com/20544986/150990312-d932af63-7c01-488d-90a4-9bf1563ef5cc.png">

**Comment by brodao** [comment]
@eliandropaya 

Certifique-se que esta em ambiente de desenvolvimento (veja as notas no inicio de [Depuração](https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md#tds-depura%C3%A7%C3%A3o-e-execu%C3%A7%C3%A3o) e que esteja conectado a um "slave" (se for ambiente master/slave). 

Para depurar serviços (_job_), certifique-se que esse foi inicializado após a conexão de depuração estabelecida.
Veja detalhes e um exemplo de inicialização de REST em [Depuração de Jobs](https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md#depura%C3%A7%C3%A3o-de-servi%C3%A7os-jobs).

Se necessário reabra o chamado.

A disposição.

**Comment by eliandropaya** [comment]
Segui estes passos e sigo com o mesmo erro.
A única coisa diferente que verifiquei é que o REST esta rodando em SSL
