### ISSUE TITLE
Invalid rootUri. Please fix your workspace configuration and try again.

### ISSUE THREAD

**Issue by viniciusdeso** [totvs/tds-vscode#908]
Bom dia 

Estou com problemas em abrir os servers no VSCode.
O estranho é que conectou normal na primeira vez que criei o server, depois que fechei e tentei abrir de novo começou a dar essa mensagem "invalid rootUri"

Como corrigir este erro ?

![image](https://user-images.githubusercontent.com/77012955/150983926-6eea1b13-a3f9-41d0-860b-4d2e7c0af8be.png)

**Comment by brodao** [comment]
@viniciusdeso 

Você deve abrir uma pasta antes de tentar acessar a visão de servidores. Detalhes em [](https://code.visualstudio.com/docs/editor/workspaces).

Se necessário reabra este chamado.

A disposição.
