### ISSUE TITLE
Identação Não funciona

### ISSUE THREAD

**Issue by robsonrosilva** [totvs/tds-vscode#91]
Os meus fontes não estão identando.

O VsCode Apresenta a seguinte mensagem:

Running the contributed command: 'totvs-developer-studio.run.formatter' failed.

Estou usando a extensão 0.3.6, Vscode 1.35.1,  Windows 7 x64 e Protheus 12.1.17

**Comment by brodao** [comment]
Ola Robson,

Experimente atualizar algumas pacotes de dependência  do TDS-VSCode.  Com o VSCode em execução, acione "terminal" e execute "npm --update".

**Comment by robsonrosilva** [comment]
Rodei o update local na pasta da extensão, rodei global e mesmo assim não funciona.
