### ISSUE TITLE
launch.json criado pelo 'Welcome' está gerando a configuração para o tds replay

### ISSUE THREAD

**Issue by filipenanclarez** [totvs/tds-vscode#910]
**Describe the bug**
launch.json criado pelo 'Welcome' está gerando a configuração para o tds replay

**To Reproduce**
Em uma nova instalação, instalar o plugin, e após preencher os dados na tela Welcome, conferir o arquivo launch.json

**Expected behavior**
launch.json ser criado com a configuração para depuração advpl, como acontecia nas versões anteriores.

**Screenshots**
![image](https://user-images.githubusercontent.com/27212546/151987547-12cf6a48-c087-4c38-b683-4b03fdad3ca1.png)

**Desktop (please complete the following information):**
Windows 10 Pro 64bits

**Comment by danielbolognani** [comment]
Bom dia @filipenanclarez 
Esse problema já foi reportado e está corrigido para a próxima versão.
Se quiser adiantar a correção com uma versão "Release Candidate":
https://github.com/totvs/tds-vscode/releases/tag/v1.3.11-RC2

Abraços!
