### ISSUE TITLE
PROBLEMAS AO TENTAR CONECTAR O VSCODE NO APPSERVER

### ISSUE THREAD

**Issue by marcosaleluia** [totvs/tds-vscode#912]
Prezados, bom dia!

Estou tentando conectar o VSCode no appserver da 12.1.25.

Fiz a instalação do Protheus do zero e na hora de tentar conectar para aplicar a lib dá a mensagem:

[Error - 14:12:10] One or more validations errors detected:
- Build version was not informed.

O que posso fazer para resolver esse problema?

**Comment by brodao** [comment]
@marcosaleluia 

Reabra este chamado informando os dados solicitados conforme [Informações importantes ao abrir o chama](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#informa%C3%A7%C3%B5es-importantes-ao-abrir-uma-issue) e anexe os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)

É de extrema importância informar um passo a passo e se possível, anexe print de telas ou vídeo e o console log do Protheus.

No aguardo
