### ISSUE TITLE
Problema geração classe WS Soap

### ISSUE THREAD

**Issue by cirilorocha** [totvs/tds-vscode#913]
**Describe the bug**
Estou tentando utilizar a rotina de geração de cliente WS padrão do plugin ADVLP, o mesmo não consegue gerar o fonte e apresenta um erro: 
[Info  - 07:50:32] Starting generate Wsdl.
[Info  - 07:50:32] Generating WSDL client at server.
[Error - 07:50:34] *** ERRO AO GERAR FONTE ADVPL ***
Source URL : https://ws.sempararempresas.com.br/ValePedagio.asmx?WSDL
-------------------------------------------------------------------------------
WSCERR037 / [RetornoMensagem] Estrutura Interna Inesperada.
ADVPL WSDL Client 1.120703 / TOTVS Servi?os Cirilo on 20220204 07:50:34
-------------------------------------------------------------------------------
[Info  - 07:50:34] Generate Wsdl finished.

**To Reproduce**
Utilizar o atalho Ctrl+Shift+P
pesquisar TOTVS:Generate WS Protheus
Preencher o assistente com a URL https://ws.sempararempresas.com.br/ValePedagio.asmx?WSDL
Um local para salvar o arquivo que será gerado
Um nome para o arquivo
Ao clicar em Salvar ou Salvar e Fechar o sistema apresenta o erro e grava o arquivo vazio.

**Expected behavior**
Espero que o plugin seja corrigido para que eu consiga gerar o fonte que preciso para fazer a integração do sistema.

**Desktop (please complete the following information):**
 - OS/Architecture: Windows 11 Pro x64

**Appserver (please complete the following information):**
 - Build (with date): 7.00.191205P-20211019 - 64 bits
 - OS/Architecture: Windows Server 2012 R2 Standard
 - Build Version 19.3.1.8

**Additional context**
Eu validei o WSDL tanto no aplicativo SoapUI da SmartBear como no site https://www.wsdl-analyzer.com/ e a estrutura é válida e está ok.

**Comment by lwtnb-wrk** [comment]
@cirilorocha Esse erro está sendo gerado pelo Appserver e apenas estamos informando.
Infelizmente não há nada que possa ser feito do lado do tds-vscode.
Favor abrir um chamado na TOTVS para que o time do Appserver possa avaliar esse incidente.
Grato por reportar o problema.
