### ISSUE TITLE
Problema geração cliente WS com arquivo local

### ISSUE THREAD

**Issue by cirilorocha** [totvs/tds-vscode#915]
**Describe the bug**
Estou tentando utilizar o assistente para criação de Cliente WS Protheus (Ctrl+Ship+P -> TOTVS: Generate WS Protheus) e tentando colocar um arquivo físico local para geração, porém o sistema apresenta um erro não gera nada. 

[Info  - 15:06:10] Starting generate Wsdl.
[Info  - 15:06:10] Generating WSDL client at server.
[Info  - 15:06:10] Starting build for environment compila_cr.
[Info  - 15:06:12] Committing end build.
[Error - 15:06:15] *** ERRO AO GERAR FONTE ADVPL ***
Source URL : \tmptdsnbk058/AtendeCliente.xml
-------------------------------------------------------------------------------
WSCERR019 / (\tmptdsnbk058/AtendeCliente.xml) Arquivo n�o encontrado.
ADVPL WSDL Client 1.120703 / TOTVS Servi�os Compila_cr on 20220204 15:06:15
-------------------------------------------------------------------------------
[Info  - 15:06:15] Generate Wsdl finished.

**To Reproduce**
Utilizar o atalho Ctrl+Shift+P e buscar pelo TOTVS: Generate WS Protheus
No assistente colocar um arquivo local (ex.: C:\temp\AtendeCliente.xml) ou um caminho do RootPath do servidor (ex.: \ws\AtendeCliente.xml)
Colocar o diretório onde será salvo e um nome para o arquivo gerado.
Clicar em Salvar ou Salvar/Fechar

**Expected behavior**
A correção desta situação para permitir gerar esses fontes a partir de arquivos locais ou que estejam no servidor.

**Desktop (please complete the following information):**
 - OS/Architecture: Windows 11 Pro x64

**Appserver (please complete the following information):**
 - Build (with date): 7.00.191205P-20211019 - 64 bits
- OS/Architecture: Windows Server 2012 R2 Standard
- Build Version 19.3.1.8

**Comment by lwtnb-wrk** [comment]
@cirilorocha Grato por notificar. Já reproduzi o problema reportado aqui. 
Vamos avaliar a correção pois envolve uma questão no AppServer também.

**Comment by lwtnb-wrk** [comment]
@cirilorocha Favor entrar em contato diretamente com o suporte da TOTVS e requisitar essa correção para o time do AppServer.
Mencione no chamado que o time do tds-vscode já avaliou o problema e que a correção precisa ser realizada no AppServer.

Enquanto o AppServer não é corrigido, realmente apenas será possível gerar o WS através de uma WSDL acessível por uma URL.
Grato pelas informações.
