### ISSUE TITLE
Linter acusa erro de variável não utilizada indevidamente

### ISSUE THREAD

**Issue by cirilorocha** [totvs/tds-vscode#916]
**Describe the bug**
O Linter (analisador de código) está apontando indevidamente a falta de uso de variáveis quando as mesmas são utilizadas com macros.

**To Reproduce**
Criar um fonte simples utilizando uma variável como macro. Ex.: o Danfeii.prw da Totvs.
User Function IMPDNFLJ(oNFE, cCodAutSef, dDtReceb, cDtHrRecCab)

local cProg		:= iif(existBlock("LJDNFNFE"),"U_LJDNFNFE","LJDNFNFE")

&cProg.(oNFE, cCodAutSef, dDtReceb, cDtHrRecCab)

Return Nil
Nesse fonte o Linter acusa que a variável cProg não é utilizada no fonte, o que claramente não está correto.

**Expected behavior**
A correção desse alerta indevido.

**Screenshots**
![image](https://user-images.githubusercontent.com/96308173/152597969-144d03cc-005f-43dc-90b6-0360295f5b07.png)

![image](https://user-images.githubusercontent.com/96308173/152597977-977bf7f9-45c9-4449-8353-e5890d912a0f.png)

**Desktop (please complete the following information):**
- OS/Architecture: Windows 11 Pro x64

**Appserver (please complete the following information):**
- Build (with date): 7.00.191205P-20211019 - 64 bits
- OS/Architecture: Windows Server 2012 R2 Standard
- Build Version 19.3.1.8

**Comment by danielbolognani** [comment]
@cirilorocha quem está acusando erro nesse caso é o próprio Appserver (veja o compile no final da linha, se fosse apenas o linter, essa mensagem iria sumir assim que compilasse).
Portanto é necessário abrir o chamado para a equipe do Appserver (no portal de clientes) para analisar essa ocorrência.

**Comment by cirilorocha** [comment]
@danielbolognani 
o linter mostra sim só coloquei o print errado
![image](https://user-images.githubusercontent.com/96308173/152600451-61629f89-798d-4538-805c-a0ac4b878987.png)

**Comment by lwtnb-wrk** [comment]
@cirilorocha O que o @danielbolognani quis dizer é que o AppServer vai acusar erro de qualquer forma na compilação.
O Linter usa o mesmo motor que o AppServer usa na compilação, então se isso não está correto, quem precisa corrigir é o AppServer.
E para isso é necessário que se abra um chamado na TOTVS para o time de AppServer avaliar essa questão.
