### ISSUE TITLE
Status do Objects Inspector - Status - NoAuth

### ISSUE THREAD

**Issue by OrismarEloy** [totvs/tds-vscode#918]
Boa tarde,

Após compila todas as customizações, vou verificar através do Objects Inspector se a rotina foi aplicado no repositório e estou verificando que seu statu está como NoAuth.
Conforme o documento em anexo
[Doc1.docx](https://github.com/totvs/tds-vscode/files/8018602/Doc1.docx)

**Comment by danielbolognani** [comment]
Boa tarde @OrismarEloy 
Esse dado apenas informa que a compilação desse fonte foi feito sem Token de compilação, portanto está no RPO Custom.
Para mais informações acesse:
https://tdn.totvs.com/display/tec/Application+Server+-+RPOs+Segregados

Abraços!
