### ISSUE TITLE
versão 0.3.6

### ISSUE THREAD

**Issue by ricardoaugustopereiradelima** [totvs/tds-vscode#92]
Bom Dia,

Gostaria de uma ajuda, depois de um tempo usando o plugin na versão 0.3.6, ele parou de conectar no Protheus, quando seleciono o server que quero conectar, o vscode com o plugin da totvs apresenta essa mensagem;
[Log   - 00:00:00] Starting connection to the server: 192.168.11.22@5000
[Log   - 00:00:00] Authenticating...
[Error - 08:41:47] Authentication failed. Could not connect to server 192.168.11.22:5000.

ja troque a senha do meu usuário e continua no mesmo erro.

podem ajudar nesse caso?

Obrigado
Ricardo Lima

**Comment by lwtnb-wrk** [comment]
Favor acompanhar pela issue #86
