### ISSUE TITLE
ExitCode=-1073741819 ExistStatus=CancelExit

### ISSUE THREAD

**Issue by jadilsonnery** [totvs/tds-vscode#920]
Ao atualizar o VSC o debug para de funcionar
com a mensagem : ExitCode=-1073741819 ExistStatus=CancelExit

Versão: 1.64.1 (user setup)
Commit: d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03
Data: 2022-02-07T17:16:22.147Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 6.2.9200.

Como resolver ?

**Comment by jadilsonnery** [comment]
Solução para o Problema :+

Problema a principio apenas ocorre em ambiente Virtualizado, via acesso remoto ou ambiente Windows Server:
1 - Para contornar, dentro da pasta do Smartclient / dlls514 
  1.1 - Existe um arquivo com o nome opengl32sw.dll 
  1.2 - Copie ele para a raiz do Smartclient
  1.3 - Renomeie para opengl32.dll. 
Então na pasta Smartclient vai existir o arquivo opengl32.dll e na pasta Smartclient / dlls514 vai existir no arquivo opengl32sw.dll 

Dessa forma, força o Smartclient a utilizar uma renderização via software e deve resolver o seu problema até uma próxima versão ser gerada com a correção.

**Solução dada anteriormente e somente melhor "Formatada" a mensagem para facilitar o entendimento.**

**Comment by jadilsonnery** [comment]
> Ao atualizar o VSC o debug para funcionar com a mensagem : ExitCode=-1073741819 ExistStatus=CancelExit
> 
> Versão: 1.64.1 (configuração do usuário) Commit: d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03 Data: 2022-02-07T17:16:22.147Z Electron: 13.5.2 Chromium: 91.0.4472.164 Node.js: 14.16.0 V8: 14.16.0 V8: SO: Windows_NT x64 6.2.9200.
> 
> Como resolver?

Solução para o Problema :+

Problema a princípio ocorre apenas em ambiente virtualizado, via acesso remoto ou ambiente Windows Server:
1 - Para definir, dentro da pasta do Smartclient / dlls514
1.1 - Existe um arquivo com o nomegl32sw.dll
1.2 - Copie ele para a raiz do Smartclient
1.3 - Renomeie para opengl32.dll.
Então na pasta Smartclient vai existir o arquivo opengl32.dll e na pasta Smartclient / dlls514 vai existir no arquivo opengl32sw.dll

Dessa forma, força o uso de uma renderização e resolvedor de seu problema até uma próxima versão ser realizada através do software Smart com correção.

**Solução dada anteriormente e somente melhor "Formatada" a mensagem para facilitar o entendimento.**

**Comment by danielbolognani** [comment]
Só para lembrar que as versões mais novas do Smartclient já está com esse arquivo na pasta e não deve ser necessário realizar mais esse procedimento.
