### ISSUE TITLE
Melhoria para Totvs Replay passe a gravar tabelas temporárias criadas no tempdb

### ISSUE THREAD

**Issue by fabiomello83** [totvs/tds-vscode#923]
Melhoria para Totvs Replay passe a gravar tabelas temporárias criadas no tempdb

Pois geralmente nas execuções de relatório é feito um select no banco e armazenado o select dentro de uma tabela temporária, posicionando os registros que estão dentro da tabela temporária e validando se o registro está adequado para ser apresentando no relatório.

Como o Totvs Replay não mostra em qual registro está posicionado na tabela temporária, não é possível sabe qual registro estamos posicionado.

**Comment by DanielYampolschi** [comment]
ola @fabiomello83 , Faz um favor? Me envia um arquivo de exemplo, ja gravado, do Replay, onde vc esperava que essas tabelas aparecessem mas não vieram.
Obrigado.

**Comment by ricardomansano** [comment]
Encerrado por falta de retorno
