### ISSUE TITLE
Erro compilacao na versao 12.1.33

### ISSUE THREAD

**Issue by AlexandreKenji** [totvs/tds-vscode#924]
**Describe the bug**
Estamos com um problema que ao compilar e o rpo estiver em uso, está corrompendo o RPO;
nas versões anteriores não ocorria esse problema dava a mensagem que o rpo estava em uso e não corrompia o rpo;
quando vai compilar surge o erro:
[Error - 15:25:18] Authentication error: Server returned a non numeric value. See Protheus Server log console for details.
[Error - 15:25:18] Retrieve connection error: An error ocurred while autoReconnect.\n\rServer: c2lcja-des-protheus.totvscloud.com.br:45.001 [serverName]
também não conseguimos acessar o protheus dando a mensagem: "RPO in use in file" (segue print em anexo);
já estamos utilizando a versão 20.3.0.4 do appserver (segue print em anexo);
o vscode está na versão 1.64.2 e a extensão totvs está na versão 1.3.12 (segue prints em anexo);
mas isso já acontecia nas versões anteriores do vscode e da extensão totvs;
há algum pacote que corrige esse problema? porque toda vez a gente precisa corrigir o rpo após tentar compilar se estiver algum usuario logado ou preso no appserver;

**To Reproduce**
usuario logado no protheus ou algum usuario 'preso' no appserver;
compilar no mesmo RPO;
o vscode começa a dar algumas mensagens como:
[Error - 15:25:18] Authentication error: Server returned a non numeric value. See Protheus Server log console for details.
[Error - 15:25:18] Retrieve connection error: An error ocurred while autoReconnect.\n\rServer: c2lcja-des-protheus.totvscloud.com.br:45.001 [serverName]
e ao acessar o protheus dá mensagem: "RPO in use in file"

**Expected behavior**
não corromper o RPO, nas versões anteriores a 12.1.33 isso não ocorria.
nas versões anteriores dava a mensagem de que o RPO estava em uso e não corrompia o rpo;

**Screenshots**
![erro](https://user-images.githubusercontent.com/56550558/154064806-2777bd4f-4745-46a2-8d40-42924bb00173.png)
![extensao](https://user-images.githubusercontent.com/56550558/154064825-eda5b3b3-6fb1-4015-a40f-e5a88a05663f.jpg)
![vscode](https://user-images.githubusercontent.com/56550558/154064851-c3830bc5-1e1c-4e07-9dcc-5a0ec2b6d6d1.jpg)
![protheus](https://user-images.githubusercontent.com/56550558/154064859-cfd0c029-30fd-4db4-b9d0-c3ca54d77927.jpg)

**Desktop (please complete the following information):**
 - OS/Architecture: Windows 10 64 bits e Windows 11 64 bits

 
**Appserver (please complete the following information):**
 - Build (with date): Build 7.00.210324P-20211206 - 64 bits
 - OS/Architecture: Cloud
 - Build Version: 7.00.210324P

**Additional context**

**Comment by danielbolognani** [comment]
Bom dia @AlexandreKenji 
Nós na extensão não temos esse tipo de controle, favor abrir um chamado no suporte direto para o time de Appserver.

Enquanto não resolver esse problema, utilize a chave BUILDKILLUSER=1 no general do appserver.ini para tentar evitar essa situação.
