### ISSUE TITLE
Conexão com servidor local

### ISSUE THREAD

**Issue by Zaniinn** [totvs/tds-vscode#925]
![Capturar](https://user-images.githubusercontent.com/99829317/154324934-7896c0df-bc2c-4eee-836c-b69663448932.PNG)

Boa tarde,

Estou tentando conectar com o servidor localhost com o protheus e esta aparecendo este erro, já verifiquei as portas de acesso, tanto a 1234 e 5555 padrões não estão dando certo.

Segue print do appserver.ini
![Capturar1](https://user-images.githubusercontent.com/99829317/154325449-8b0e892a-ca5e-4cea-8ac7-135017a033f1.PNG)

**Comment by brodao** [comment]
Reabra este chamado informando os dados solicitados conforme [Informações importantes ao abrir o chamado](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#informa%C3%A7%C3%B5es-importantes-ao-abrir-uma-issue) e anexe os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)

É de extrema importância informar um passo a passo e se possível, anexe print de telas ou vídeo e o console log do Protheus.

No aguardo.
