### ISSUE TITLE
Error al realizar un debug desde visual code.

### ISSUE THREAD

**Issue by luisAboytes** [totvs/tds-vscode#926]
Hola buenas tardes equipo de TOTVS.

Quiero reportar un error al momento de acceder a cualquier modulo realizando un debug desde Visual Code, este error solo se muestra cuando se realiza un debug.

El error se visualizando accediendo a cualquier modulo desde el smartclient  modo debug, este error:
![image](https://user-images.githubusercontent.com/99834241/154345029-e99fe8e4-fb19-407e-b1d8-72cc77fbc466.png)

Adjunto información

PC:
![image](https://user-images.githubusercontent.com/99834241/154345173-604856d0-31d9-4658-a260-166434c1c2a7.png)

Windows:
![image](https://user-images.githubusercontent.com/99834241/154345232-4408dc37-ae1f-4db2-9a22-84082f849f98.png)

DBAccess:
![image](https://user-images.githubusercontent.com/99834241/154345306-6fc8699a-56c9-4dc6-ae4a-45c29737817e.png)

AppServer:
![image](https://user-images.githubusercontent.com/99834241/154345365-50078fa2-9cf2-4da0-a58f-d7202be69bc4.png)

SmartClient:
![image](https://user-images.githubusercontent.com/99834241/154345524-63b02348-3ba6-4c97-bc7e-6a77f773e7bf.png)
![image](https://user-images.githubusercontent.com/99834241/154345546-cb9ae515-7eb4-4e96-9c97-e580ee36eeec.png)

Video de replica de error:
https://user-images.githubusercontent.com/99834241/154345604-7687ea12-2618-4f6d-8275-9241d8e8a8a1.mp4

Espero puedan ayudarme con este error ya que es muy tardado realizar debugs, tengo que realizar muchos intentos para que no me muestre el error.

Gracias y quedo atento a sus comentarios,

**Comment by danielbolognani** [comment]
Executar esse mesmo Smartclient sem ser pelo Debug funciona normalmente?
Parece ser falta de dll na pasta do Smartclient. Por favor faça um teste realizando o download novamente do Smartclient 20.3.0.0 no portal de clientes e crie uma nova pasta para extrair os arquivos.
Se o problema continuar, gere os logs da extensão (https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs) e anexe aqui para analisarmos.

**Comment by DanielYampolschi** [comment]
Ola @luisAboytes, alguma atualização referente ao teste pedido pelo @danielbolognani ?

**Comment by luisAboytes** [comment]
Muito obrigado, baixe os binários como você mencionou e funciona perfeitamente
