### ISSUE TITLE
Erro ao compilar

### ISSUE THREAD

**Issue by danielblaia** [totvs/tds-vscode#927]
ola bom dia
após atualizar o Protheus pra 12.1.33
estou com erro pra compilar:
Start build error: Server returned: 
Cannot open RPO File. Check file access permissions / Read-Only status.COMPILEERROR-300 

Já reiniciei o appserver, vscode, tudo

podem me ajudar?

**Comment by brodao** [comment]
Veja se ajuda #884 e https://github.com/totvs/tds-vscode/issues/850#issuecomment-979123502

**Comment by brodao** [comment]
Nesse caso, entre em contato com a equipe de suporte do appServer via https://totvscst.zendesk.com/hc/pt-br/#home 

A disposição.

**Comment by danielblaia** [comment]
obrigado Alan
