### ISSUE TITLE
Formatação com IF em Linha

### ISSUE THREAD

**Issue by josuelsilva** [totvs/tds-vscode#928]
**Describe the bug**
Quando o fonte contém uma regra com IF() em linha, a formatação fica quebrada para as próximas linhas.

**Antes**
![Formatação com IF em Linha - Antes](https://user-images.githubusercontent.com/23218591/154754089-9f6b0ae4-3010-4142-a375-db3d9ff2b48a.png)

**Expected behavior**
A formatação só fica correta quando é alterado o IF() por IIF()

**Depois**
![Formatação com IF em Linha - Depois](https://user-images.githubusercontent.com/23218591/154754108-80d31da3-8b45-4481-8b58-ba2172c999c3.png)

**Comment by danielbolognani** [comment]
Bom dia @josuelsilva 
A extensão apenas considera IIF como Inline IF, e isso deveria ser adotado como boas práticas para facilitar a leitura de código.

Fique a vontade para realizar um Pull Request com a correção, mas nós não iremos tratar isso como um problema.

Abraços!

**Comment by josuelsilva** [comment]
> Bom dia @josuelsilva A extensão apenas considera IIF como Inline IF, e isso deveria ser adotado como boas práticas para facilitar a leitura de código.
> 
> Fique a vontade para realizar um Pull Request com a correção, mas nós não iremos tratar isso como um problema.
> 
> Abraços!

Daniel, boa noite,
O caso em questão são os fontes já disponibilizados pela própria TOTVS. Por exemplo, NFESEFAZ, DANFEII, DANFEII, nfsexmlenv.prw etc.

Já adotamos o IIF como Inline para ajuste e formatação correta.

Irei abrir um ticket solicitação ajustes nos fontes disponibilizados.

Grato.
