### ISSUE TITLE
Erro conexão com servidor local

### ISSUE THREAD

**Issue by Zaniinn** [totvs/tds-vscode#931]
Boa tarde,

Estou tentando conectar com o servidor localhost  e esta aparecendo este erro, já verifiquei as portas de acesso, tanto a 1234 e 5555 padrões não estão dando certo.

![Capturar](https://user-images.githubusercontent.com/99829317/155420390-df7ba789-351e-4517-a63a-7120335ba786.PNG)

Segue print do appserver.ini
![Capturar1](https://user-images.githubusercontent.com/99829317/155420417-5971897d-f00d-44d9-aba2-540615daf498.PNG)

Versão vscode
![Versao vscode](https://user-images.githubusercontent.com/99829317/155420446-df8684b5-e93f-43ba-a7cf-ae2297fb49c7.PNG)

Versão tds-advpl
![versaotds ](https://user-images.githubusercontent.com/99829317/155420489-28323e79-94ed-43e6-8cad-647fbb9cddc9.PNG)

.json 
![erro](https://user-images.githubusercontent.com/99829317/155449961-dbad9e84-edd6-49e2-ace3-04473b361271.PNG)

**Comment by lwtnb-wrk** [comment]
@Zaniinn Pelas informacoes apresentadas realmente o tds-vscode não conseguiu se conectar no ip e porta informados.
Certifique-se que o AppServer esteja realmente online e não exista um impedimento de acesso por conta de um Firewall ou Anti-virus e tente se conectar novamente.
Caso ainda não seja possivel realizar a conexão, veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para auxiliar na analise do problema.

**Comment by Zaniinn** [comment]
@lwtnb-wrk Problema resolvido, o AppServer não estava sendo iniciado por conta de uma incompatibilidade com o Anti-virus. Consegui resolver recriando o atalho para abrir como console. Muito obrigado
