### ISSUE TITLE
Problema ao conectar no Server

### ISSUE THREAD

**Issue by altenir** [totvs/tds-vscode#932]
Quando vou adicionar meu server o mesmo não pede usuário e senha e sim somente o ambiente.
Consigo conectar com o client do protheus normalmente ao server, acesso o sistema normal.
Somente no vscode não consigo.
Tenho somente um ambiente configurado.

![image](https://user-images.githubusercontent.com/6899409/155915885-2d00ceac-259f-456c-bcc1-d3d508527df7.png)

![image](https://user-images.githubusercontent.com/6899409/155915924-5caae6ef-174d-43cd-84e3-303b0a6e24c5.png)

![image](https://user-images.githubusercontent.com/6899409/155915935-4f7c98f3-0522-4c32-bb24-3ec42bcd2a91.png)

![image](https://user-images.githubusercontent.com/6899409/155915954-6b745dee-c284-4fc1-9ce1-bdcf7ba1c0a3.png)

![image](https://user-images.githubusercontent.com/6899409/155915971-b9aa496d-815b-4379-918b-9825f06a02e7.png)

![image](https://user-images.githubusercontent.com/6899409/155915992-0d1f4e14-56b7-484d-aec8-f721334147ac.png)

![image](https://user-images.githubusercontent.com/6899409/155916015-eb3bbf85-1054-44f5-8d1d-2fb983c8a351.png)

![image](https://user-images.githubusercontent.com/6899409/155916037-ba4ad124-553c-4215-b38c-965cfa0aaca5.png)

**Comment by danielbolognani** [comment]
Olá, a sua build do Appserver está muito desatualizada!
Favor atualizar  appserver para a última versão disponível no portal (última build para o Protheus 12.1.17 é a 13.2.3.52 a sua é a 13.2.3.36).

**Comment by altenir** [comment]
isso não foi a solução
![image](https://user-images.githubusercontent.com/6899409/156003360-840a5b52-befb-48b5-9460-482ab1f9403a.png)

**Comment by altenir** [comment]
Sim, tudo novo, não peguei nada do antigo, é uma base de testes nova, uma instalação do zero. Consigo acessar o Protheus normalmente sim pelo smartclient.

**Comment by lwtnb-wrk** [comment]
@altenir Logs?

**Comment by altenir** [comment]
[totvsls.log.txt](https://github.com/totvs/tds-vscode/files/8157310/totvsls.log.txt)
[totvsls_in.log.txt](https://github.com/totvs/tds-vscode/files/8157311/totvsls_in.log.txt)
[totvsls_out.log.txt](https://github.com/totvs/tds-vscode/files/8157312/totvsls_out.log.txt)

**Comment by altenir** [comment]
@lwtnb-wrk deu certo na maquina nova, da forma como eu comentei, tudo zerado, e também somente com a extensão TOTVS Developer Studio instalada. 

Agora só me resta descobrir porque na minha maquina não está concetando, e acho que não é a questão da build pois vi que tem clientes que ainda está com 700131227A e lá está funcionado normalmente. Um dos primeiros testes que vou fazer é desinstalar todas as extensões que uso em outras linguagens. 

Quando eu descobrir comentarei aqui.

**Comment by RafaelCavalcante2468** [comment]
@altenir Conseguiu resolver como? Estou com esse mesmo problema e não consigo resolver de forma alguma. Formatar meu computador e instalar tudo do zero não é uma opção hehehehe. Já estou quase desistindo de estudar ADVPL por causa desse BUG. Ajudem o amigo a continuar kkkk

**Comment by lwtnb-wrk** [comment]
Pessoal,
Apesar de mensagens de erro semelhantes nem sempre o erro é o mesmo.
Caso necessitem de auxilio alem do que essa issue antiga oferece, abram uma nova issue com detalhes do seu problema.
Valeu
