### ISSUE TITLE
Problema ao conectar no Server

### ISSUE THREAD

**Issue by altenir** [totvs/tds-vscode#933]
Novamente, fiz uma nova instalação dos Totovs PRotheus v 12.1.333 mas quando vou adicionar meu server o mesmo não pede usuário e senha e sim somente o ambiente.
Consigo conectar com o client do protheus normalmente ao server, acesso o sistema normal.
Somente no vscode não consigo.
Tenho somente um ambiente configurado.

https://github.com/totvs/tds-vscode/issues/932

![image](https://user-images.githubusercontent.com/6899409/156004277-49357d61-9839-4d4c-8de1-243d6d45ceaf.png)

![image](https://user-images.githubusercontent.com/6899409/156004432-1743c60d-3886-4c9e-809b-d9905a130f70.png)

![image](https://user-images.githubusercontent.com/6899409/156004595-d68d1c8f-a4b0-47fb-abac-f86b795074df.png)

![image](https://user-images.githubusercontent.com/6899409/156004654-78a812c1-f0bc-4746-8d75-a3a791ce63fe.png)

![image](https://user-images.githubusercontent.com/6899409/156004855-d6cb8ac4-a217-474f-af14-3dd95621f0ef.png)

![image](https://user-images.githubusercontent.com/6899409/156017059-22cf9910-2ba0-41f3-90c7-e8ce08b1a906.png)

**Comment by lwtnb-wrk** [comment]
@altenir Aparentemente o tds-vscode não consegue enxergar seu AppServer. Normalmente isso ocorre por bloqueio de firewall e/ou antivirus.

Se ainda tiver dificuldades, veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analises.

**Comment by altenir** [comment]
Está tudo desativado firewall e antivirus.

**Comment by lwtnb-wrk** [comment]
@altenir Logs?

**Comment by lwtnb-wrk** [comment]
@altenir Vou fechar essa issue e continuar apenas pelo #932
