### ISSUE TITLE
Erro após compilação de fonte

### ISSUE THREAD

**Issue by VictorFreidinger** [totvs/tds-vscode#934]
Bom dia,
Ao aplicar os fontes personalizados no ambiente novo (v33), algumas rotinas aparecem a mensagem que o fonte não foi compilado, ao recompilar (tudo via VSCode, sem erros), estas rotinas voltam a funcionar, mas, outras acabam parando.
Exemplo: Tenho fonte A e fonte B
Ao compilar ambos, o fonte B funciona normalmente e o A não.
Ai recompilar o A, ele funciona normalmente e o B não.
Nós temos muitos fontes personalizados, isso acaba gerando uma recompilação de fontes muito forte.
Poderiam dar um apoio, por favor? 
Obrigado.

**Comment by danielbolognani** [comment]
Bom dia, favor gerar os [logs](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs) para conseguirmos analisar o problema.
Quando vc fala que um funciona e o outro não, o que acontece quando não funciona? Ao tentar chamar alguma função retorna que a função não existe?

Quando tivermos mais informações reabrimos a issue.

Abs!

**Comment by VictorFreidinger** [comment]
Bom dia Daniel, 
É dada a mensagem 'Função de Usuário, criada por meio de RDMake, não está compilada'. 
Consegui realizar um teste aqui e, incrivelmente, os fontes acabam sendo 'descompilados' após a aplicação de novos fontes. 
Um teste que consegui fazer é pegar todos os fontes existentes, colocar em uma pasta e aplicar todos eles, ai não há problema. 
Mas, em um determinado momento, se eu aplico apenas 1 dos fontes, todos os demais deixam de funcionar dando a mensagem acima mostrada e tanto no Inspetor de objetos quanto no Catálogo de Personalizações, eles 'somem'. 
Atualizei a versão do appserver novamente, baixando a última versão do portal, mas, nenhum efeito sobre isso. 
Qual ou quais evidências posso enviar para ajudar?
Obrigado.

**Comment by danielbolognani** [comment]
Olá @VictorFreidinger com os [logs da extensão](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs) podemos verificar ser tem algo acontecendo durante a compilação. Seria interessante também o console.log para verificarmos a ocorrência.
