### ISSUE TITLE
Não está aparecendo a lista de servidores

### ISSUE THREAD

**Issue by SilvaCleverson** [totvs/tds-vscode#935]
**Describe the bug**

A pedido do cliente instalei o Vscode no servidor Microsoft Windows [Version 6.3.9600] e a extensão do TOTVS, porém
não está aparecendo a lista dos servidores, mesmo após clicar no adicionar não aparece nada.
Gravei um arquivo server.sjon ( esse arquivo está em outra maquina maquina que está funcionando que um windows 10 64bits Microsoft Windows [versão 10.0.19043.1526]) e mesmo assim não lista os servidores.
**Screenshots**
![image](https://user-images.githubusercontent.com/45862282/157030501-cf5f278c-dc89-4be6-82a7-32c54444a981.png)
![image](https://user-images.githubusercontent.com/45862282/157031213-344d658a-4280-44dc-81e8-67d801395a77.png)

**Comment by DanielYampolschi** [comment]
Ola @SilvaCleverson tenta uma coisa antes por favor. Abre um fonte .PRW qualquer e garanta que o Language Server foi iniciado. Você consegue confirmar isso no comboBox do lado direito, onde no print aparece Tasks, tem que aparecer a informação "TOTVS LS".
Com isso confirmado, tente adicionar um servidor novamente.

**Comment by SilvaCleverson** [comment]
Fiz o procedimento e funcionou obrigado, posso aproveitar e tirar uma duvida eu só consigo abrir o vscode colocando --disable-gpu caso contrário a tela fica preta.

**Comment by danielbolognani** [comment]
Bom dia @SilvaCleverson windows server não é homologado para o VSCode nem para a nossa extensão (https://code.visualstudio.com/docs/supporting/requirements e https://github.com/totvs/tds-vscode/blob/master/README.md)
Esse problema com GPU pode estar relacionado a isso.

**Comment by lwtnb-wrk** [comment]
@SilvaCleverson Somente para confirmar, isso esta ocorrendo em um Windows 8.1 Update 1 correto?
Apesar do Windows 8.1 seja homologado para o VS Code pode ser que nesse SO muito antigo a aceleracao do GPU pode nao funcionar corretamente, mas é uma limitação do VS Code.
