### ISSUE TITLE
Validação do Linter Incorreta

### ISSUE THREAD

**Issue by AlexandreBeh** [totvs/tds-vscode#936]
O Linter da extensão está sinalizando uma operação como incompatibilidade de tipos em um fonte tlpp, mas é possível compilar e não ocorre erro na execução.

Local dLimitEmpenho := MV_PAR04 as date
Local nDiasEmpenho  := dLimitEmpenho - dDataBase   as integer

Aparece a seguinte mensagem "Incompatible types between I and D Linter".
Mas como dito antes, na execução do código é uma operação válida. Dessa forma o linter não deveria sinalizar o erro.

**Comment by danielbolognani** [comment]
Boa tarde @AlexandreBeh casos como esse são uma prévia do que o compilador da próxima versão de binário irá considerar como erro de compilação.
Nós da extensão não temos como mudar regras de compilação, portanto caso ache que isso é um erro mesmo, um chamado deve ser aberto diretamente para a equipe do appserver via portal do cliente.
Abraços!
