### ISSUE TITLE
Erro - RPO não está incrementando - V12.1.33

### ISSUE THREAD

**Issue by NicolasXM** [totvs/tds-vscode#937]
Boa tarde,

Ao criar um novo RPO Custom (arquivo ou pasta), ele não está incrementando o RPO. Ele apaga o conteúdo e carrega como se fosse um novo.
Versão do VSCode - Version 1.3.12

Appserver
Versão: TOTVS Versão: TOTVS Manufatura
Build AppServer: 7.00.210324P-20211206 - 64 bits
Nome do servidor: SATURNO
Sistema operacional: Windows Server 2012 R2
Appserver version: 20.3.0.4
Build DBAccess: 20210202-20210930
Release do RPO: 12.1.033
Release do dicionário: 12.1.033
Local files: CTREE
License server: 2014 - 3.3.3
DB DataBase: MSSQL
DB API Build: 20210202-20210930
Manufatura

**Comment by danielbolognani** [comment]
Bom dia @NicolasXM 
Não entendi muito bem a situação, mas em teste rápido aqui, após criar um RPO, se fizer uma nova compilação ele não apagou o RPO e criou um novo, manteve os dois "fontes" compilados no RPO.
De qualquer forma quem controla o RPO é o próprio appserver, a extensão apenas envia a mensagem para o appserver realizar a compilação do arquivo.
Do lado da extensão não temos ação, se realmente é um problema, recomendo abrir um chamado via suporte e direcionar para a equipe do Appserver.
Abs!

**Comment by lwtnb-wrk** [comment]
@NicolasXM Esse problema já está sendo tratado pelo time do AppServer e é causado pelo uso da chave RPOTLPP.
De qualquer forma não temos como contornar do lado do tds-vscode.

**Comment by NicolasXM** [comment]
Prezados, bom dia

Ok.. obrigado pelo retorno.
Vou retornar com o suporte e solicitar a correção.
