### ISSUE TITLE
Erro debug REST TCloud

### ISSUE THREAD

**Issue by danielblaia** [totvs/tds-vscode#939]
boa tarde
não estou conseguindo debugar um REST usando SOAPUI no TCloud

Recentemente o TCloud disponibilizou um appserver Debug, onde eu consigo debugar as rotinas normalmente

Mas estou tentando debugar um REST aqui e não consigo. Eu abro o F5 com uma rotina xxxx e depois consumo o WS pelo SOAPUI, mas não para no breakpoint

Abaixo o meu lauch.json

{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Depuração do idioma TOTVS",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "C:\\atalhos\\PROSOLUS\\smartclient.exe",
			"enableMultiThread": true,
			"isMultiSession": true,
			"enableTableSync": true
		}
	],
	"lastPrograms": [
		{
			"label": "sigaadv"
		},
		{
			"label": "xxyy"
		},
		{
			"label": "xxxx"
		}
	],
	"lastProgramExecuted": "sigaadv"
}

podem me ajudar?

**Comment by brodao** [comment]
Veja como depurar em https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md#depura%C3%A7%C3%A3o-de-servi%C3%A7os-jobs.

Atente que o serviço do rest deve ser inicializado após a conexão de depuração efetuada.
