### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [totvs/tds-vscode#94]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/totvs/tds-vscode/blob/master/package.json#L49

See https://nodejs.org/api/fs.html

You might want to remove it using `npm uninstall fs`.

**Comment by matheus-sales** [comment]
@DanielRuf 

Hi, 

We removed the dependence. 

Sorry
