### ISSUE TITLE
Function Inspector não permite pesquisar qdo no R.12.1.33

### ISSUE THREAD

**Issue by jcstorino** [totvs/tds-vscode#940]
# Help us to help you.

## Before opening an issue

- Make sure the extension is up to date.
- See [Resolução de Problemas](TROUBLESHOOTING.md#problemas-gerais), with common and/or known occurrences.

## Enter the data below

**Describe the bug**
Usando um servidor no Release 12.1.33, quando abro o Function Inspector, no console informa que as funções foram carregadas com sucesso e apresenta a quantidade, e "function inspector finished", porém não habilita para pesquisar as funções.

**To Reproduce**
1. Conectar em um servidor com o release 12.1.33 e rpo custom configurado.
2. Clicar com o botão direito sobre o servidor / Function Inspector.
3. A tela do Function Inspector se abre e fica bloqueada para carregamento das funções
4. No console do Totvs LS é informado que "Function Inspector Finished" e a qtde de funções recuperadas5. 
5. Mas a Tela do Function Inspector continua bloqueada ( com o ícone rotativo de processando )6. 

**Expected behavior**
Que após carregar as funções, libera a tela para realizar as devidas pesquisas...

**Screenshots**
![image](https://user-images.githubusercontent.com/19559870/158460415-c5cf0f20-78ca-4757-ba93-b950036f0a16.png)

**Desktop (please complete the following information):**
 - Mac OS 12.3 (chip Apple M1)

**Appserver (please complete the following information):**
 - Build (with date): 7.00.210324P-20211206 - 64bits - Lib 20220103 - Rpo 12.1.033
 - Windows Server 2012 R2 64 Bits
 - Build Version 9600

**Additional context**

**Comment by lwtnb-wrk** [comment]
@jcstorino Vamos confirmar algumas informacoes adicionais
- qual a build exata do appserver? 20.3.0.4??
- a extensão do tds-vscode esta atualizada? 1.3.12??

E se possivel veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by jcstorino** [comment]
Olá, segue informações..

Build do Servidor:   * Build Version: 20.3.0.4
Extensão do VSCode:  v1.3.12

Arquivos de Log gerados...
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/8262064/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/8262065/totvsls_out.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/8262066/totvsls.log)

**Comment by jcstorino** [comment]
ok.. fiz novamente o procedimento... acho que agora pegou..
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/8262752/totvsls_in.log)
[totvsls_out.log](http
[totvsls.log](https://github.com/totvs/tds-vscode/files/8262755/totvsls.log)
s://github.com/totvs/tds-vscode/files/8262754/totvsls_out.log)

**Comment by lwtnb-wrk** [comment]
@jcstorino Grato pelas informacoes.
Consegui reproduzir o problema e deve ser alguma coisa muito particular do Mac, pois isso funciona corretamente no Windows.
Estamos verificado.

**Comment by lwtnb-wrk** [comment]
@jcstorino Favor testar a versão 1.3.13 liberada hoje.

**Comment by jcstorino** [comment]
> @jcstorino Favor testar a versão 1.3.13 liberada hoje.

    Funcionando perfeitamente agora ! 👍🏻
