### ISSUE TITLE
Compilação de Customizados

### ISSUE THREAD

**Issue by RenatoJoseDamasceno** [totvs/tds-vscode#941]
# Help us to help you.

## Before opening an issue

- Make sure the extension is up to date.
- See [Resolução de Problemas](TROUBLESHOOTING.md#problemas-gerais), with common and/or known occurrences.

## Enter the data below

**Describe the bug**
Quando estamos compilando os nossos customizados, ele está danificando o repositório default da totvs, dando erros

**To Reproduce**

**Expected behavior**

Nosso appserver.ini está assim:
[SQL2019_12133_ORI]
SourcePath=D:\TOTVS12\Protheus_v12133\protheus\apo_v12133
RPOCustom=D:\TOTVS12\Protheus_v12133\protheus\apo_custom_v12133\usa.rpo
RootPath=D:\TOTVS12\Protheus_v12133\protheus_data
ctreerootpath=D:\TOTVS12\Protheus_v12133\protheus_data
StartPath=\system\
x2_path=
RpoDb=top
RpoLanguage=Portuguese
RpoVersion=120
LocalFiles=CTREE
Trace=0
localdbextension=.dtc
TopMemoMega=1
PictFormat=DEFAULT
DateFormat=DEFAULT
RegionalLanguage=BRA
TOPPORT=7899
TOPDATABASE=MSSQL7
TOPSERVER=10.80.0.6
TOPALIAS=adv_12133
;IXBLOG=NORUN
PROTHEUSONLY=0
THEME=SUNSET
;LogProfiler=1
HELPSERVER=ASVDVS03:8384
SpecialKey=V2019R12133
KillStack=1
AdvSQLReplay=1
AdvSQLReplayLog=1
AdvSQLReplayPath=\SQLReplay\

[SQL2019_12133_DEV]
SourcePath=D:\TOTVS12\Protheus_v12133\protheus\apo_v12133
RPOCustom=D:\TOTVS12\Protheus_v12133\protheus\apo_custom_dev12133\usadev.rpo
RootPath=D:\TOTVS12\Protheus_v12133\protheus_data
ctreerootpath=D:\TOTVS12\Protheus_v12133\protheus_data
StartPath=\system\
x2_path=
RpoDb=top
RpoLanguage=Portuguese
RpoVersion=120
LocalFiles=CTREE
Trace=0
localdbextension=.dtc
TopMemoMega=1
PictFormat=DEFAULT
DateFormat=DEFAULT
RegionalLanguage=BRA
TOPPORT=7899
TOPDATABASE=MSSQL7
TOPSERVER=10.80.0.6
TOPALIAS=adv_12133
;IXBLOG=NORUN
PROTHEUSONLY=0
THEME=SUNSET
;LogProfiler=1
HELPSERVER=ASVDVS03:8384
SpecialKey=V2019R12133
KillStack=1
AdvSQLReplay=1
AdvSQLReplayLog=1
AdvSQLReplayPath=\SQLReplay\

[DESENV01]
SourcePath=D:\TOTVS12\Protheus_v12133\protheus\apo_desenv01
RPOCustom=D:\TOTVS12\Protheus_v12133\protheus\apo_desenv01\custom.rpo
RootPath=D:\TOTVS12\Protheus_v12133\protheus_data
ctreerootpath=D:\TOTVS12\Protheus_v12133\protheus_data
StartPath=\system\
x2_path=
RpoDb=top
RpoLanguage=Portuguese
RpoVersion=120
LocalFiles=CTREE
Trace=0
localdbextension=.dtc
TopMemoMega=1
PictFormat=DEFAULT
DateFormat=DEFAULT
RegionalLanguage=BRA
TOPPORT=7899
TOPDATABASE=MSSQL7
TOPSERVER=10.80.0.6
TOPALIAS=adv_12133
;IXBLOG=NORUN
PROTHEUSONLY=0
THEME=SUNSET
;LogProfiler=1
HELPSERVER=ASVDVS03:8384
SpecialKey=V2019R12133
KillStack=1
AdvSQLReplay=1
AdvSQLReplayLog=1
AdvSQLReplayPath=\SQLReplay\

[ACD]
SourcePath=D:\TOTVS12\Protheus_v12133\protheus\apo_v12133
RPOCustom=D:\TOTVS12\Protheus_v12133\protheus\apo_acd\tttp120.rpo
RootPath=D:\TOTVS12\Protheus_v12133\protheus_data
ctreerootpath=D:\TOTVS12\Protheus_v12133\protheus_data
StartPath=\system\
x2_path=
RpoDb=top
RpoLanguage=Portuguese
RpoVersion=120
LocalFiles=CTREE
Trace=0
localdbextension=.dtc
TopMemoMega=1
PictFormat=DEFAULT
DateFormat=DEFAULT
RegionalLanguage=BRA
TOPPORT=7899
TOPDATABASE=MSSQL7
TOPSERVER=10.80.0.6
TOPALIAS=adv_12133
;IXBLOG=NORUN
PROTHEUSONLY=0
THEME=SUNSET
;LogProfiler=1
HELPSERVER=ASVDVS03:8384
SpecialKey=V2019R12133
KillStack=1
AdvSQLReplay=1
AdvSQLReplayLog=1
AdvSQLReplayPath=\SQLReplay\

[Drivers]
Active=TCP
MULTIPROTOCOLPORT=1
MULTIPROTOCOLPORTSECURE=0

[TCP]
TYPE=TCPIP
Port=1300

[Service]
Name=TOTVS-Appserver12_12133
DisplayName=TOTVS | Appserver 12_12133

[TDS] 
AllowApplyPatch=*
allowEdit=*
ENABLEDISCONNECTUSER=*
ENABLESENDMESSAGE=*
ENABLEBLOCKNEWCONNECTION=*
ENABLESTOPSERVER=*

[General]
InstallPath=D:\TOTVS12\Protheus_v12133
CONSOLELOG=1
ConsoleMaxSize=10485760
CONSOLEFILE=D:\TOTVS12\Protheus_v12133\Logs\console.log
SEGMENTO=pV2QYzlWQdud=HZy=JHb
CtreeMode=Server
MaxQuerySize=31960
MAXSTRINGSIZE=10
App_Environment=SQL2019_12133_ORI

[CtreeServer]
CTSERVERNAME=FAIRCOMS@ASVDVS03
CTUSERID=ADMIN
CTUSERPASS=ADMIN

[LICENSECLIENT]
server=10.80.0.13
port=5562

[TELNET]
Enable=1                            
Environment=SQL2019_12133_ORI
Main=SIGAACD                   
Port=23                               

[WEBAPP]
port=9995

[SSLConfigure]
HSM=0
Verbose=1
SSL2=0
SSL3=1
TLS1_0=1
TLS1_1=1
TLS1_2=1
BUGS=1
State=1

;###########################################################################
;CONFIGURACAES DO SCHEDULE
;###########################################################################

[OnStart]
jobs=FWSCHDMANAG_SQL2019_12133_SCHEDULE,FWSCHDQUEUE_SQL2019_12133_SCHEDULE
RefreshRate=120

[FWSCHDMANAG_SQL2019_12133_SCHEDULE]
Main=FWSCHDMANAG
Environment=SQL2019_12133_SCHEDULE

[FWSCHDQUEUE_SQL2019_12133_SCHEDULE]
Main=FWSCHDQUEUE
Environment=SQL2019_12133_SCHEDULE

[WebApp/webapp]
MPP=

**Screenshots**

**Desktop (please complete the following information):**
 - OS/Architecture: Windows Server 2019 Datacenter  - 64 bits

**Appserver (please complete the following information):**
[build: 7.00.210324P-20211206]
[environment: SQL2019_12133_ORI]
[thread: 22820]
[dbthread: 6784]
[dbversion: 21.1.1.0]
[dbapibuild: 20210202-20210930]
[dbarch: 64]
[dbso: WINDOWS]
[rpodb: top]
[localfiles: CTREE]

**Additional context**
[console.log](https://github.com/totvs/tds-vscode/files/8318553/console.log)

**Comment by lwtnb-wrk** [comment]
@RenatoJoseDamasceno O ambiente que esta sendo compilado pode estar sendo acessado por outros usuários durante a compilação?
Talvez o uso da chave BuildKillUsers=1 adicionada na seção General, ajude a minimizar problemas de usuários conectados, pois ela derruba todas as conexões antes de efetuar a compilação.
De qualquer forma, o AppServer tem tido alguns problemas nesse sentido e que já estão sendo corrigidos, então fique de olho nas próximas atualizações do AppServer.

**Comment by RenatoJoseDamasceno** [comment]
@lwtnb-wrk obrigado pela ajuda.    O que estranho é que, há usuários num ambiente, e estamos compilando em outro ambiente.
Seria solução colocarmos  a variável de repositório original da totvs em outro local ?
