### ISSUE TITLE
Erro Linter na compilacao de wsRest

### ISSUE THREAD

**Issue by snlacerda89** [totvs/tds-vscode#942]
Ao tentar compilar um fonte (que ja esta funcionando em produção) é apresentado o erro de Linter na linha 18, mas se vai mexendo o erro vai mudando de linha.

Protheus: 12.1.33
buildVersion: "7.00.210324P"

#include 'rwmake.ch'
#include 'totvs.ch'
#include 'restful.ch'

User Function YPWS016()
Return( .F. )

WSRESTFUL YPWS016 DESCRIPTION 'endpoint products API' FORMAT "application/json,text/html"   
    
    WSDATA aQueryString AS ARRAY OPTIONAL
    WSDATA cSequence    AS STRING OPTIONAL
    WSDATA cNumOP       as STRING OPTIONAL

    WSMETHOD GET ListAuthorization ;
	    DESCRIPTION "Listagem das Autorizacoes de Apontamento Pendentes";
	    WSSYNTAX "/api/v1/YPWS016/ListAuthorization" ;
        PATH "/api/v1/YPWS016/ListAuthorization" ;
	    **PRODUCES APPLICATION_JSON** --> Aqui é apresentado o erro

END WSRESTFUL

WSMETHOD GET ListAuthorization WSREST YPWS016
Return ProcList(self)

**Comment by lwtnb-wrk** [comment]
@snlacerda89 O erro é apontado na compilação e também no Linter? Se este for o caso, o Linter apenas está apontando o erro que o compilador está acusando depois na compilação e é isso o que esperamos mesmo.
Enfim, se o fonte foi compilado anteriormente e não está compilando agora, pode ser algo introduzido recentemente pelo AppServer, mas pode ser também alguma questão da versão de seus Includes. Seu AppServer e a pasta de Includes estão atualizados?
Se tudo estiver correto, veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise. 
No envie também se possível o console.log do AppServer mostrando a build exata do AppServer e o momento que ocorre o erro de compilação.

**Comment by snlacerda89** [comment]
[INFO ][SERVER] [Thread 70432] [22/03/2022 11:45:14] Starting Debugger (sergiolacerda, MacBook-Pro-de-Sergio.local)
2022-03-22T11:45:22.331000-03:00 68832|
*** Loading dbapi.dll
2022-03-22T11:45:22.333000-03:00 68832|*** dbapi.dll Build 20210202-20210930 RELEASE
2022-03-22T11:45:26.542000-03:00 68832|
[INFO ][SERVER] [Thread 68832] JOB Thread finished [-PSWADMIN]
2022-03-22T11:45:30.315000-03:00 70432|
[INFO ][SERVER] [Thread 70432] Start Build.
2022-03-22T11:45:37.596000-03:00 70432|
[INFO ][SERVER] [Thread 70432] Compiling U_YPWS016.PRW
2022-03-22T11:45:37.599000-03:00 70432|
[ERROR][SERVER] U_YPWS016.PRW(18)   C2003 Syntax Error
2022-03-22T11:45:37.671000-03:00 70432|
[WARN ][SERVER] Debugger - Rollback executed for the repository. Check IDE for details.
2022-03-22T11:45:37.671000-03:00 70432|
[INFO ][SERVER] [Thread 70432] [22/03/2022 11:45:37] End Build.

**Comment by snlacerda89** [comment]
[Info  - 11:45:29 AM] Starting recompile.
[Info  - 11:45:29 AM] Starting build for environment SALDOOP.
[Info  - 11:45:36 AM] Starting build using RPO token ...
[Info  - 11:45:36 AM] Start file recompile.
[Info  - 11:45:36 AM] Using Includes: /Users/sergiolacerda/Totvs/include
[Info  - 11:45:36 AM] Start secure compiling /Users/sergiolacerda/Totvs/VS_WORKSPACE/YPF/Protheus/src/Webservices/U_YPWS016.PRW (1/1).
[Error - 11:45:37 AM] [FATAL] Aborting: U_YPWS016.PRW(18)   C2003 Syntax Error
[Info  - 11:45:37 AM] Aborting end build (rollback changes).
[Error - 11:45:37 AM] One or more files have errors and/or warnings. See problems and logs for details.
[Info  - 11:45:37 AM] Recompile finished.

**Comment by snlacerda89** [comment]
Vai pra pqp!!! Desculpa galera! Atualizei as includes com as disponiveis no portal da totvs (16/03/2022) e voltou a compilar
