### ISSUE TITLE
Depuração em ambiente smarterp não para nos pontos

### ISSUE THREAD

**Issue by joycekellysantana** [totvs/tds-vscode#943]
Descrição
Ao tentar depurar um ambiente smarterp e colocar pontos de parada que o programa passe, o debug é derrubado, se tiver qualquer ponto de parada que a execução não passe, o debug é processado normalmente.

Versao do vscode
![image](https://user-images.githubusercontent.com/102364779/160170831-ec2ad894-14b4-4d0d-9853-600bf67fd5c3.png)
![image](https://user-images.githubusercontent.com/102364779/160170912-b02733c8-c8be-45aa-9a9b-15dd0768c018.png)

**Comment by lwtnb-wrk** [comment]
@joycekellysantana Creio de deva existir algum breakpoint com problema que está causando esta queda.
Se puder, remova todos os breakpoints existentes, mesmo que não sejam dos fontes que estiver debugando e depois recoloque os breakpoints que deseje. Isso pode resolver seu problema.
Se ainda assim as quedas continuarem, veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.
