### ISSUE TITLE
Problemas compilação de subpasta

### ISSUE THREAD

**Issue by markinsilva** [totvs/tds-vscode#944]
Ao realizar a compilação da pasta com o projeto inteiro, os arquivos que estão na pastas principais compilam normalmente, porém alguns fontes de subpastas estão sendo ignorados e não compilados, poderiam ser alguma configuração?

Config Server VS Code
                       "id": "legrbnpibqcl13j8e6uqn8rum5n3dl",
			"type": "totvs_server_protheus",
			"name": "TESTE_12_133_DEV",
			"port": 1400,
			"address": "10.80.0.7",
			"buildVersion": "7.00.210324P",
			"secure": false,
			"includes": [
				"C:\\GIT\\totvs\\Includes"
			],
			"environments": [
				"DESENV01",
				"DESENVMS"
			],
			"username": "admin",
			"environment": "DESENVMS"

**Desktop (please complete the following information):**
 - OS/Architecture: [Windows 64 bits]

**Appserver (please complete the following information):**
Dados do Server 
-Versão: TOTVS Agroindustria
-Build AppServer: 7.00.210324P-20220312 - 64 bits
-Nome do servidor: ASVDVS03
-Sistema operacional: Windows Server 2016
-Appserver version: 20.3.0.8
-Build DBAccess: 20210202-20210930
-Release do RPO:  12.1.033
-Release do dicionário: 12.1.033
-Local files: CTREE
-License server: 2014 - 3.3.3
-DB DataBase: MSSQL7
-DB API Build: 20210202-20210930

-Versão da Lib:20220207
-Data da Lib: 20220204_161331

--AppServer
[DESENV01]
SourcePath=D:\TOTVS12\Protheus_v12133\protheus\apo_desenv\apo_desenv01
RPOCustom=D:\TOTVS12\Protheus_v12133\protheus\apo_desenv\apo_desenv01\custom\mycustom.rpo
RootPath=D:\TOTVS12\Protheus_v12133\protheus_data
ctreerootpath=D:\TOTVS12\Protheus_v12133\protheus_data
StartPath=\system\
x2_path=
RpoDb=top
RpoVersion=120
LocalFiles=CTREE
Trace=0
localdbextension=.dtc
TopMemoMega=1
PictFormat=DEFAULT
DateFormat=DEFAULT
RegionalLanguage=BRA
TOPPORT=7899
TOPDATABASE=MSSQL7
TOPSERVER=10.80.0.6
TOPALIAS=adv_12133
PROTHEUSONLY=0
THEME=SUNSET
;SpecialKey=VT20190326
SpecialKey=V2019R12133
App_Environment=DESENV01
;#####################################
;Configura??es para o TDS no Ambiente
;#####################################
TDSVIEW=1
TDSHOST=*
;#####################################

[DESENVMS]
SourcePath=D:\TOTVS12\Protheus_v12133\protheus\apo_desenv\apo_desenvMS
RPOCustom=D:\TOTVS12\Protheus_v12133\protheus\apo_desenv\apo_desenvMS\custom\mycustom.rpo
RootPath=D:\TOTVS12\Protheus_v12133\protheus_data
ctreerootpath=D:\TOTVS12\Protheus_v12133\protheus_data
StartPath=\system\
x2_path=
RpoDb=top
RpoVersion=120
LocalFiles=CTREE
Trace=0
localdbextension=.dtc
TopMemoMega=1
PictFormat=DEFAULT
DateFormat=DEFAULT
RegionalLanguage=BRA
TOPPORT=7899
TOPDATABASE=MSSQL7
TOPSERVER=10.80.0.6
TOPALIAS=adv_12133
PROTHEUSONLY=0
THEME=SUNSET
SpecialKey=V2019R12133
App_Environment=DESENVMS
;#####################################
;Configura??es para o TDS no Ambiente
;#####################################
TDSVIEW=1
TDSHOST=*
;#####################################

[Drivers]
Active=TCP
MultiProtocolPortSecure=0
MultiProtocolPort=1

[TCP]
TYPE=TCPIP
Port=1400

[General]
InstallPath=D:\TOTVS12\Protheus_v12133
CONSOLELOG=1
ConsoleMaxSize=10485760
CONSOLEFILE=D:\TOTVS12\Protheus_v12133\Logs\console_desenv.log
SEGMENTO=pV2QYzlWQdud=HZy=JHb
CtreeMode=Server
MaxQuerySize=31960
MAXSTRINGSIZE=50
;App_Environment=DESENV01

[CtreeServer]
CTSERVERNAME=FAIRCOMS@ASVDVS03
CTUSERID=ADMIN
CTUSERPASS=ADMIN

[LICENSECLIENT]
server=10.80.0.13
port=5562

;[WebApp/webapp]
;MPP=

[Service]
Name=TOTVS-Appserver12_12133_desenv
DisplayName=TOTVS | Appserver 12_12133 DESENV

[TDS] 
AllowApplyPatch=*
allowEdit=*
ENABLEDISCONNECTUSER=*
ENABLESENDMESSAGE=*
ENABLEBLOCKNEWCONNECTION=*
ENABLESTOPSERVER=*

[SSLConfigure]
HSM=0
Verbose=1
SSL2=0
SSL3=1
TLS1_0=1
TLS1_1=1
TLS1_2=1
BUGS=1
State=1

**Comment by brodao** [comment]
@markinsilva 

Esse fontes que não foram compilados podem já ter  sido compilados anteriormente e não foram alterados desde então.
Para análise mais precisa, anexe os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)

No aguardo

**Comment by lwtnb-wrk** [comment]
@markinsilva Existe uma lista de extensões de arquivos que são considerados para a compilação. Procure por "Extensions Allowed" nas preferencias do VS Code.
De qualquer forma durante a compilação, os fontes desconsiderados emitem uma mensagem clara de que aquela extensão de fonte não está nesta lista.

**Comment by markinsilva** [comment]
> @markinsilva
> 
> Esse fontes que não foram compilados podem já ter sido compilados anteriormente e não foram alterados desde então. Para análise mais precisa, anexe os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)
> 
> No aguardo

@brodao Segue abaixo os demais dados:

Versão VScode
  -Versão 1.66.0 
![Versão VS Code](https://user-images.githubusercontent.com/82103976/161248227-92f3a15d-c02c-4057-8ef1-a77f2816346f.png)

Versão Extensão
TOTVS Developer Studio for VSCode (AdvPL, TLPP e 4GL)  v1.3.12 

Versão do RPO (LIB) e do TOTVS Server
![Dados Server](https://user-images.githubusercontent.com/82103976/161249113-370c78c4-64de-429e-b558-0d4e0aec5ad1.png)

Logs
[totvsls.log](https://github.com/totvs/tds-vscode/files/8397282/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/8397284/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/8397285/totvsls_out.log)

Peguei novamente o RPO padrão da TOTVS e compilei a pasta inteira e o fonte que anteriormente não havia sido compilado, compilou normalmente, então não teria no momento um fonte para poder lhe passar para validarmos esse bug.
Caso volte a ocorrer lhe aponto nessa ISSUE.

Att.

Marcos

**Comment by markinsilva** [comment]
> @markinsilva Existe uma lista de extensões de arquivos que são considerados para a compilação. Procure por "Extensions Allowed" nas preferencias do VS Code. De qualquer forma durante a compilação, os fontes desconsiderados emitem uma mensagem clara de que aquela extensão de fonte não está nesta lista.

@lwtnb-wrk As extensões eram as padrões para o ADVPL prw e tlpp

**Comment by lwtnb-wrk** [comment]
@markinsilva Analisei o log e realmente não vi nenhum fonte que não foi compilado, exceto os que estariam na condição que o @brodao mencionou, que são fontes compilados anteriormente e não tiveram alteração.

Vamos fechar esta issue e se observar o problema novamente abra uma nova issue já com os logs para analisarmos.
