### ISSUE TITLE
C2029  ENDDO does not match WHILE

### ISSUE THREAD

**Issue by fmapart** [totvs/tds-vscode#945]
Boa tarde!

Para qualquer fonte que eu abra no VSCode está sendo apresentado este problema: "C2029  ENDDO does not match WHILE"
Trata-se de uma instalação nova do VSCode, porém utilizando fontes que eu já havia compilado no RPO Customizado da versão 12.1.33.
![Screenshot_VSCode](https://user-images.githubusercontent.com/102625700/160922963-e263a257-d934-4389-a948-0ebdb7b59fe0.png)
![Screenshot_VSCode_2](https://user-images.githubusercontent.com/102625700/160922968-5badba9b-10f5-4db4-83d9-86a2de0f2741.png)

Já desinstalei e instalei novamente a extensão mas sem sucesso e sei que não se trata de problema no código, pois qualquer fonte apresenta essa mensagem.

Alguém saberia me dizer o que pode ser?

Segue anexo alguns prints de tela com informações de configuração.

Agradeço desde já pelo seu tempo e suporte
Felipe Azevedo

**Comment by lwtnb-wrk** [comment]
@fmapart Se voce compilar o fonte, ocorre a mesma mensagem de erro?
A principio quem indica o problema sem efetuar a compilação é o Linter, mas ele deve apresentar os mesmos erros que a compilação indicaria durante a compilação efetivamente.

Se acha que esse fonte não deveria apresentar essa mensagem de erro, geralmente é um problema de configuração da pasta de includes utilizada. Veja se a configuração está correta e aponta para a pasta que deveria ser utilizada para a compilação.

Se ainda assim não resolver o problema, veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by fmapart** [comment]
Bom dia lwtnb-wrk!

Respondendo ao seu questionamento; Sim, o VSCode apresenta o mesmo problema ao compilar qualquer fonte.

![Screenshot_VSCode_3](https://user-images.githubusercontent.com/102625700/161045722-07689aee-0f5b-429a-81f1-63b79a06b777.png)

Minha configuração dos includes está em c:\Includes;

![Screenshot_VSCode_4](https://user-images.githubusercontent.com/102625700/161047370-7158bad3-f13e-458f-b1fa-58514fbfc94f.png)

Segue os log´s conforme solicitado.


Grato,
Felipe Azevedo

**Comment by lwtnb-wrk** [comment]
@fmapart Ah sim, se na compilação o mesmo problema ocorre está correto o comportamento.

Então provavelmente os includes que você está utilizando não devem ser os corretos. Atualize sua pasta de includes e verifique que isso deve resolver seu problema.

**Comment by fmapart** [comment]
Cara,

Realmente você tinha razão, baixei os includes (22-03-15-P12_INCLUDES) e resolveu o problema!
Muito obrigado pelo seu tempo e suporte.


Grato,
Felipe Azevedo.
