### ISSUE TITLE
Patch Generation (from RPO) não funciona na release 12.1.33

### ISSUE THREAD

**Issue by jonathantorioni** [totvs/tds-vscode#946]
Ao tentar gerar patch de um serviço na release 12.1.33 temos o seguinte output:

[Info  - 8:55:51 AM] Starting generate patch.
[Info  - 8:55:51 AM] Starting build for environment W8PATW_HOM_COMP.
[Info  - 8:55:51 AM] Starting build using RPO token ...
[Error - 8:55:51 AM] Patch could not be generated.
[Info  - 8:55:51 AM] Cleaning up appserver OK.
[Info  - 8:55:51 AM] Aborting end build (rollback changes).

O teste foi realizado tanto em Windows quando em MacOS.

Passos para reproduzir o erro:

1. Conectar em um Serviço que esteja na release 12.1.33
2. Clicar com o botão direito do mouse sobre o serviço e selecionar a opção Patch Generation (from RPO)
3. Informar um fonte e pasta para gerar o patch
4. Clicar em GENERATE

Estou utilizando a extensão na na versão: 1.3.12

**Comment by lwtnb-wrk** [comment]
@jonathantorioni Precisamos de algumas informações adicionais para prosseguir.
- Qual a build exata do AppServer? 20.0.3.8?   
- Você utiliza o token de compilação?

Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by marciorollo** [comment]
> Ao tentar gerar patch de um serviço na release 12.1.33 temos o seguinte output:
> 
> [Info - 8:55:51 AM] Starting generate patch. [Info - 8:55:51 AM] Starting build for environment W8PATW_HOM_COMP. [Info - 8:55:51 AM] Starting build using RPO token ... [Error - 8:55:51 AM] Patch could not be generated. [Info - 8:55:51 AM] Cleaning up appserver OK. [Info - 8:55:51 AM] Aborting end build (rollback changes).
> 
> O teste foi realizado tanto em Windows quando em MacOS.
> 
> Passos para reproduzir o erro:
> 
> 1. Conectar em um Serviço que esteja na release 12.1.33
> 2. Clicar com o botão direito do mouse sobre o serviço e selecionar a opção Patch Generation (from RPO)
> 3. Informar um fonte e pasta para gerar o patch
> 4. Clicar em GENERATE
> 
> Estou utilizando a extensão na na versão: 1.3.12

**Comment by rafaelmrsa** [comment]
Boa tarde,
estou com um erro parecido.
Ao tentar gerar o ptm de uma rotina padrão, é reproduzido o erro abaixo:

[Info  - 4:46:50 PM] Starting build using RPO token ...
**[Error - 4:46:50 PM] Patch could not be generated.**
[Info  - 4:46:50 PM] Cleaning up appserver OK.
[Info  - 4:46:50 PM] Aborting end build (rollback changes).

**Comment by lwtnb-wrk** [comment]
@rafaelmrsa É esse mesmo o comportamento esperado para o 12.1.33.

Somente será possível gerar patches de fontes que você customizou.

Se tentar gerar um patch com fontes padrões o AppServer não irá permitir e ocorrerá esse erro na geração.

**Comment by Miqueiasfer** [comment]
porque nao conseguimos mais gerar patch de fontes padroes do sistema?

**Comment by danielbolognani** [comment]
Bom dia @Miqueiasfer 
Com o lançamento do binário 20.3.x.x ou superior do Appserver, o RPO recebeu uma alteração significativa para garantir a segurança dos fontes padrão que são distribuídos pela TOTVS, e isso levou ao bloqueio de qualquer acesso a esses fontes (inclusive geração de patch). Esse bloqueio não é dentro do TDS-VSCode e sim dentro do appserver que é quem acessa os RPOs e controla qualquer acesso relacionado a isso.
Hoje, apenas a TOTVS possui esse acesso liberado e consegue acessar e gerar patch em cima de fontes do RPO padrão.
