### ISSUE TITLE
Depois da atualização de 31/03 - Lentidão Excessiva

### ISSUE THREAD

**Issue by lucianoaol** [totvs/tds-vscode#947]
01/04/22

Depois da atualização de 31/03 o VS Code ficou excessivamente lento.

Anexei dados do meu SO e versão do VS Code.

![Capturar](https://user-images.githubusercontent.com/34626305/161253516-d0e9f1b5-0faa-42fb-aa40-2ad6bc7103d3.JPG)

**Comment by lucianoaol** [comment]
Impossível de trabalhar, tem como voltar um versão?

**Comment by lucianoaol** [comment]
![Capturar](https://user-images.githubusercontent.com/34626305/161254520-061a902b-aedd-4334-b134-821c407021f8.JPG)

**Comment by lwtnb-wrk** [comment]
@lucianoaol Você atualizou somente o VS Code e não a extensão?

Pelo screenshot percebemos que a extensão está bastante desatualizada. Atualize a extensão tds-vscode para verificar se a lentidão permanece. Nessa versão 1.2.1 não temos como averiguar nada...

**Comment by lucianoaol** [comment]
@lwtnb-wrk precisei reiniciar várias até ficar normal. Mas graças a sua dica, depois também atualizei a extensão. Problema resolvido.
