### ISSUE TITLE
Compilação na release 33

### ISSUE THREAD

**Issue by Smmartinez** [totvs/tds-vscode#948]
Bom dia! Estamos iniciando os processo de validação da release 33, e quando vamos compilar a compilação para no meio, e não atualiza o arquivo. estou enviando os arquivo de log e print do appserver com a mensagem.
Release 33
Appserver: 20.3.0.8

VSCODE:
Version: 1.66.0 (user setup)
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:14.623Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22581

Plugin:
v1.3.1
[totvsls_out.zip](https://github.com/totvs/tds-vscode/files/8409453/totvsls_out.zip)
![Sem título](https://user-images.githubusercontent.com/4532855/161539863-068f16a0-22b3-427a-81f0-d4358fb41470.png)

**Comment by lwtnb-wrk** [comment]
@Smmartinez Favor refazer a operação de compilação e reenviar os logs, pois nos logs em anexo não temos nenhuma evidencia da compilação.

No Output do VS Code não aparece nenhuma mensagem de erro?

**Comment by Smmartinez** [comment]
![Sem título_1](https://user-images.githubusercontent.com/4532855/161548085-28fabfdb-1c8e-4592-b2a9-365733e560c3.png)
[totvsls.log](https://github.com/totvs/tds-vscode/files/8409848/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/8409850/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/8409852/totvsls_out.log)

Não aparece nenhuma mensagem fica travado no arquivo e não sai.
Veja se agora os arquivos estão corretos.

**Comment by Smmartinez** [comment]
@leowww Fiz o teste de compilar apenas 1 fonte e deu certo, então fui compilando pasta a pasta, mas chegou numa pasta, bem depois da pasta daquela fonte e ocorreu o problema de travar.
Olhei no console e o erro citado por  você ocorreu.
Na release 25 esse tipo de problema não ocorre.

![processo_2](https://user-images.githubusercontent.com/4532855/161555356-310e4a76-b26e-4b7f-9e73-0c5cbed75986.png)

**Comment by Smmartinez** [comment]
@leowww Isso mesmo toda vez que ocorre o erro [vdrport] o processo trava.
Não trava no mesmo lugar, o aruqivo muda.

**Comment by Smmartinez** [comment]
@leowww é isso mesmo... neste serviço que estou testando não tinha a chave do multiprotocolo, eu coloquei a chave como 0 e compilei os fontes e não parou.
Vou fazer um teste recompilando tudo para ver se o problema não ocorre.

**Comment by DanielYampolschi** [comment]
Issue encerrado por falta de retorno. Caso ainda apresente o problema, pode reabri-la.
