### ISSUE TITLE
Demora na execução do debug após primeiro breakpoint

### ISSUE THREAD

**Issue by fwsoares** [totvs/tds-vscode#95]
boa tarde!

Após atualizar a extensão para a 0.3.10, quando inicio um debug o vscode para no breakpoint, após clicar em F11 ou F5 para continuar o processo, o VS fica como se estivesse travado e aba Variables fica carregando ou as Variáveis ou a Tabelas e nisso fica por muito tempo.
Segue print com uma demonstração.

![erro ao carregar tabelas](https://user-images.githubusercontent.com/38725127/60045598-9bd47480-969b-11e9-83b8-f52e5670cfbe.png)

**Comment by DanielYampolschi** [comment]
Ola @fwsoares qual a build do servidor que você esta usando por favor?

**Comment by fwsoares** [comment]
Daniel,

Segue dados abaixo:

Versão: TOTVS Manufatura
Build AppServer: 7.00.131227A-20190114 NG - 32 bits
Build DbAccess: 20181212
Release do RPO:  12.1.017
Ambiente: Desenv_tst
Local files: ctree
HardLock: 2014

Versão da Lib:20181101
Data da Lib: 20181023_18613
Commit ID:1ff41ef7e19999f1ea56e103b14714d5191a9aa6

**Comment by DanielYampolschi** [comment]
@fwsoares, desculpe a demora para respoder. Não consigo reproduzir esse problema em outras versões de servidores, estou montando um ambiente mais próximo do que voce informou para verificar.

Uma questao que reparei agora (Estava olhando apenas para tabelas), voce diz que isso acontece ao expandir variaveis também?

**Comment by fwsoares** [comment]
Sim Daniel, também acontece às vezes com as variáveis Locais ou Private. Eu estou usando agora a versão 0.2.1, e ainda sinto certo delay no carregamento, mas não trava. Não sei se é normal mas sempre que VS para no primeiro breakpoint e vai para o próximo ou para a execução linha a linha, tem uma demora de uns bons segundos, isso é normal?

**Comment by DanielYampolschi** [comment]
Ah ok. Não tinha reparado que você estava com a versão 0.2.1

Devemos liberar uma versão amanhã e como temos uma série de modificações no processo de depuração incluindo o sincronismo de tabelas, isso poderia ser uma explicação porque não consigo reproduzir. 

Vou aguardar você testar após a atualização e se ainda tivermos problemas voltamos a verificar isso ok?

**Comment by fwsoares** [comment]
O erro reportado ocorreu na 0.3.10, o Mansano disponibilizou ela no Grupo TotvsDev para testarmos, ai como eu precisava debugar, voltei a versão, só coloquei isso como comentário que mesmo na 0.2.1, também tem uma certa lentidão no sincronismo.
