### ISSUE TITLE
A função de Executar e Depurar

### ISSUE THREAD

**Issue by kleysongomesmorada** [totvs/tds-vscode#950]
# Help us to help you.

## Before opening an issue

- Make sure the extension is up to date.
- See [Resolução de Problemas](TROUBLESHOOTING.md#problemas-gerais), with common and/or known occurrences.

## Enter the data below

**Describe the bug**
Ao depurar utilizando Ctrl + F5 a primeira vez funciona mas a partir da segunda não depura. 
Funcionando apenas pelo clique de botões do VSCODE. 

**To Reproduce**
1. adicione um ponto de parada no fonte ADVPL
2. Pressione as combinação de teclas ctrl + F5
3. Esecute o processo até o momento da parada (vai notar que não vai respeitar a parada).
4. Caso não ocorra de primeira, execute novamente o passo 2 e notará o bug. 

**Expected behavior**
O debug pausar o sistema no ponto de parada marcado. 

**Screenshots**
![image](https://user-images.githubusercontent.com/98477885/162446120-01d05b6f-e902-48de-a2ad-3c94f0e20e5e.png)

**Desktop (please complete the following information):**
 - Windows 10 Pro 64 bits

**Comment by lwtnb-wrk** [comment]
@kleysongomesmorada O atalho CTRL + F5 executa o smartclient no modo de execução, logo não deveria parar nos breakpoints mesmo, para entrar no modo de depuração utilize apenas o F5
![image](https://user-images.githubusercontent.com/49563478/162447795-a759e4d2-3504-4c0e-8526-31e649e78024.png)

**Comment by kleysongomesmorada** [comment]
Certo, porém na primeira vez ele para no ponto de debug mas depois disso ele passa a não parar mais. 

Exemplo: criei meu ambiente agora, executei o comando ele para no ponto marcado, executo o comando novamente ai ele não para mais.

**Comment by lwtnb-wrk** [comment]
@kleysongomesmorada Mas isso usando o CTRL + F5? Nesse caso o "bug" seria ele parar na primeira vez, pois nem deveria entrar no modo de depuração...

**Comment by kleysongomesmorada** [comment]
Isso mesmo.

**Comment by lwtnb-wrk** [comment]
@kleysongomesmorada E utilizando somente o F5 você consegue depurar normalmente?

**Comment by kleysongomesmorada** [comment]
Funciona perfeitamente, obrigado!
