### ISSUE TITLE
Compilação RDMAKE (LOJRNFCE) 

### ISSUE THREAD

**Issue by wemersonbastos** [totvs/tds-vscode#951]
Estou compilando o RDMAKE LOJRNFCE e após compilação quando vou em inspetor de objeto, está com a data da alteração do fonte.
Porém no ERP esta considerando o fonte antigo anterior a compilação (2020).
Consigo verificar isso, pois  a rotina gerar um erro log, e ao verificar, ela está lendo o fonte antigo no RPO.

Versão 12.1.33 
Build AppServer: 7.00.210324P-20220312

**Comment by brodao** [comment]
@wemersonbastos 

Favor efetuar o teste:
1. Certifique-se que os ambientes sejam os mesmos (compilação e execução);
2. Remova o LOJRNFCE do repositório;
3. Execute os procedimentos e veja se o mesmo é executado (não deve);
4. Compile-o e certifique-se que não ocorreu erro
5. Refaça os testes.

Caso continue com a ocorrência, reabra este chamado informando os dados solicitados conforme [Informações importantes ao abrir o chamado](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#informa%C3%A7%C3%B5es-importantes-ao-abrir-uma-issue) e anexe os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)

No aguardo

**Comment by brodao** [comment]
Em complemento, certifique-se que a chave RPOCustom aponta para um local válido (não deixei de informá-la, mesmo que uso o padrão).
