### ISSUE TITLE
Breakpoint posicionado incorretamente

### ISSUE THREAD

**Issue by gtrabach** [totvs/tds-vscode#952]
**Describe the bug**
Ao depurar um fonte, uma das marcações do breakpoint é posicionada incorretamente dentro do nome de funções/variáveis/condições, ao invés de ser posicionada no final da linha em questão. Curiosamente esse bug não ocorre caso a linha possua um EndIf ou Return.

**To Reproduce**
1. Crie um fonte qualquer.
2. Inicie a depuração/debug do fonte e espalhe alguns breakpoints pelo programa.
3. Verifique que alguns breakpoints estarão espalhados dentro de variáveis e funções, ao invés de no final da linha.
4. Este bug ocorre apenas quando o VS Code está depurando.

**Expected behavior**
A marcação do breakpoint deveria ficar no final da linha.

**Screenshots**
![image](https://user-images.githubusercontent.com/46979335/163243710-d1c9a2c5-8704-493b-b848-f4ec62f304c9.png)

**Desktop (please complete the following information):**
Windows 10 Pro 21H1 64-bits

**Appserver (please complete the following information):**
AppServer 19.3.1.8
Windows Server 2012 R2

[issue depurar.zip](https://github.com/totvs/tds-vscode/files/8483718/issue.depurar.zip)

**Comment by gtrabach** [comment]
Complementando: 

Versão do plug-in: 1.3.12
Versão do VsCode: 1.66.2

**Comment by lwtnb-wrk** [comment]
@gtrabach Grato pelas informações.
Essa questão já era conhecida, porém por se tratar de algo meramente estético, pois para na linha correta, ainda não havia sido endereçada.
Vamos corrigir em breve, mas talvez não nesta próxima versão.
Fique de olho nas atualizações.
Valeu!
