### ISSUE TITLE
erro ao aplicar patch

### ISSUE THREAD

**Issue by rikeekir291190** [totvs/tds-vscode#953]
problema ao aplicar patch 

[Info  - 18:10:43] Starting patch validate.
[Info  - 18:10:43] Patch file: d:/Totvs/Protheus_Data/temp/tss.ptm
[Info  - 18:10:43] Starting build for environment OFICIAL.
[Info  - 18:10:45] Starting build using RPO token ...
[Error - 18:10:45] File could not be copied to the server.
[Error - 18:10:45] Patch validate could not be executed. Server returned: Patch file D:\Totvs\Protheus\protheus_Data\\tmptdssrv-cofapl01/tss13-04-2022-18-10-45.ptm not found
[Info  - 18:10:45] Aborting end build (rollback changes).
[Info  - 18:10:45] Patch validate finished.
[Info  - 18:11:12] Starting patch validate.
[Info  - 18:11:12] Patch file: d:/Totvs/Protheus_Data/temp/tss.ptm
[Info  - 18:11:12] Starting build for environment OFICIAL.
[Info  - 18:11:15] Starting build using RPO token ...
[Error - 18:11:15] File could not be copied to the server.
[Error - 18:11:15] Patch validate could not be executed. Server returned: Patch file D:\Totvs\Protheus\protheus_Data\\tmptdssrv-cofapl01/tss13-04-2022-18-11-15.ptm not found
[Info  - 18:11:15] Aborting end build (rollback changes).
[Info  - 18:11:15] Patch validate finished.
[Error - 18:11:15] Patch file D:\Totvs\Protheus\protheus_Data\\tmptdssrv-cofapl01/tss13-04-2022-18-11-15.ptm not found
[Info  - 18:11:56] Starting patch validate.
[Info  - 18:11:56] Patch file: d:/Totvs/Protheus_Data/temp/tss.ptm
[Info  - 18:11:56] Starting build for environment OFICIAL.
[Info  - 18:11:58] Starting build using RPO token ...
[Error - 18:11:58] File could not be copied to the server.
[Error - 18:11:58] Patch validate could not be executed. Server returned: Patch file D:\Totvs\Protheus\protheus_Data\\tmptdssrv-cofapl01/tss13-04-2022-18-11-58.ptm not found
[Info  - 18:11:58] Aborting end build (rollback changes).
[Info  - 18:11:58] Patch validate finished.
[Error - 18:11:58] Patch file D:\Totvs\Protheus\protheus_Data\\tmptdssrv-cofapl01/tss13-04-2022-18-11-58.ptm not found
[Info  - 18:11:58] Starting patch validate.
[Info  - 18:11:58] Patch file: d:/Totvs/Protheus_Data/tss.ptm
[Info  - 18:11:58] Starting build for environment OFICIAL.
[Info  - 18:12:01] Starting build using RPO token ...
[Error - 18:12:01] File could not be copied to the server.
[Error - 18:12:01] Patch validate could not be executed. Server returned: Patch file D:\Totvs\Protheus\protheus_Data\\tmptdssrv-cofapl01/tss13-04-2022-18-12-01.ptm not found
[Info  - 18:12:01] Aborting end build (rollback changes).
[Info  - 18:12:01] Patch validate finished.
[Error - 18:12:01] Patch file D:\Totvs\Protheus\protheus_Data\\tmptdssrv-cofapl01/tss13-04-2022-18-12-01.ptm not found
[Info  - 18:14:26] Starting patch validate.
[Info  - 18:14:26] Patch file: d:/Totvs/Protheus_Data/temp/tss.ptm
[Info  - 18:14:26] Starting build for environment OFICIAL.
[Info  - 18:14:29] Starting build using RPO token ...
[Error - 18:14:29] File could not be copied to the server.
[Error - 18:14:29] Patch validate could not be executed. Server returned: Patch file D:\Totvs\Protheus\protheus_Data\\tmptdssrv-cofapl01/tss13-04-2022-18-14-29.ptm not found
[Info  - 18:14:29] Aborting end build (rollback changes).
[Info  - 18:14:29] Patch validate finished.
[Error - 18:14:29] Patch file D:\Totvs\Protheus\protheus_Data\\tmptdssrv-cofapl01/tss13-04-2022-18-14-29.ptm not found
[Info  - 18:14:29] Starting patch validate.
[Info  - 18:14:29] Patch file: d:/Totvs/Protheus_Data/tss.ptm
[Info  - 18:14:29] Starting build for environment OFICIAL.
[Info  - 18:14:32] Starting build using RPO token ...
[Error - 18:14:32] File could not be copied to the server.
[Error - 18:14:32] Patch validate could not be executed. Server returned: Patch file D:\Totvs\Protheus\protheus_Data\\tmptdssrv-cofapl01/tss13-04-2022-18-14-32.ptm not found
[Info  - 18:14:32] Aborting end build (rollback changes).
[Info  - 18:14:32] Patch validate finished.
[Error - 18:14:32] Patch file D:\Totvs\Protheus\protheus_Data\\tmptdssrv-cofapl01/tss13-04-2022-18-14-32.ptm not found
[Info  - 18:14:32] Starting patch validate.
[Info  - 18:14:32] Patch file: d:/Totvs/Protheus_Data/patch/tss.ptm
[Info  - 18:14:32] Starting build for environment OFICIAL.
[Info  - 18:14:34] Starting build using RPO token ...
[Error - 18:14:34] File could not be copied to the server.
[Error - 18:14:34] Patch validate could not be executed. Server returned: Patch file D:\Totvs\Protheus\protheus_Data\\tmptdssrv-cofapl01/tss13-04-2022-18-14-34.ptm not found
[Info  - 18:14:34] Aborting end build (rollback changes).
[Info  - 18:14:34] Patch validate finished.
[Error - 18:14:34] Patch file D:\Totvs\Protheus\protheus_Data\\tmptdssrv-cofapl01/tss13-04-2022-18-14-34.ptm not found

**Comment by rikeekir291190** [comment]
ele esta procurando a patch em um caminho que não existe 
tem alguma configuração a ser aplicada ?

**Comment by lwtnb-wrk** [comment]
@rikeekir291190 Qual a build exata do seu AppServer?
Esse tipo de erro ocorreu bastante no passado mas era um problema no AppServer que foi corrigido a muito tempo...
Se seu AppServer estiver atualizado, veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by rikeekir291190** [comment]
Dados do Server 

Versão: TOTVS Manufatura
Build AppServer: 7.00.210324P-20220312 - 64 bits
Nome do servidor: SRV-COFAPL01
Sistema operacional: Windows Server 2016
Appserver version: 20.3.0.8
Build DBAccess: 20210202-20220202
Release do RPO:  12.1.033
Release do dicionário: 12.1.033
Local files: CTREE
License server: 2014 - 3.4.1
DB DataBase: MSSQL
DB API Build: 20210202-20220202


Versão da Lib:20220321
Data da Lib: 20220405_151734
Commit ID:1f22d5ff7ec3b8c4e16777799fdf3f096fa671b9

**Comment by lwtnb-wrk** [comment]
@rikeekir291190 Qual o tamanho do patch que voce está tentando aplicar? De onde você baixou esse patch?

Seu tds-vscode está instalado em uma máquina com qual SO?

**Comment by rikeekir291190** [comment]
a patch é da propria TOTVS 
o tamanho é pequeno 

tamanho em disco 4,00 KB (4.096 bytes)
tamanho do arquivo  122 bytes (122 bytes)

sistema operacional  que esta instalado o tds-code é windows 10-pro

**Comment by rikeekir291190** [comment]
so uma observação 

os erros começaram a ocorrer apos atualizacao do VS-CODE 
antes de fazer as atualizações ... em versões anteriores funcionava a aplicacao de patchs

**Comment by rikeekir291190** [comment]
e nunca foi alterado nada ... referente a workspace, appserver , smartclient , etc

**Comment by lwtnb-wrk** [comment]
@rikeekir291190 Por favor, veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

**Comment by DanielYampolschi** [comment]
@rikeekir291190 Estamos encerrando essa issue por falta de resposta, caso ainda tenha o problema e consiga gerar os logs conforme solicitado pelo @lwtnb-wrk pode reabri-lo.
