### ISSUE TITLE
Problemas na compilação de fontes AdvPL ASP (*.aph)

### ISSUE THREAD

**Issue by rafa2you** [totvs/tds-vscode#955]
Ao compilar fontes AdvPL-ASP (extensão .aph), o linter aponta erros de sintax indevidos.

![image](https://user-images.githubusercontent.com/62104671/163394208-2fa77c4c-ab4d-43c3-bbe4-5a6d59291286.png)

Mesmo nos fontes em que não aponta estes erros, ele compila, mas o resultado fica incorreo. 
![image](https://user-images.githubusercontent.com/62104671/163403328-d74af225-a6f7-4a64-912f-560075164e36.png)

Ao consultar um objeto do pré-compilador, nota-se que ele está deixando as tags em aberto, cortando o caractere de fechamento![image](https://user-images.githubusercontent.com/62104671/163403651-c441fab4-7ead-46c9-9c74-562d53baf6f1.png)

E no navegador, ao consultar o fonte, também nota-se o resultado com as tags todas abertas:
![image](https://user-images.githubusercontent.com/62104671/163404058-5f12541c-507a-4d6f-81ba-5d93c259085c.png)

 - OS/Architecture: Windows 64 bits

 - Build: 7.00.170117A-20200102 (estes prints, mas também reproduzido na build 7.00.210324P-20211206)
 - OS/Architecture: Windows (TOTVS Cloud)
 - Build Version: 17.3.0.18 (estes prints, mas também reproduzido na 20.3.0.4)

- VSCode: 1.66.0 (mas também reproduzido na 1.65.0)
- Extensão VSCode da TOTVS: 1.3.12 (mas também reproduzido na 1.3.11, 1.3.10 e 1.3.09, pelo menos)

Como workaround estamos operando na versão 1.3.0 da extensão para conseguir compilar. Na 1.2.9 também funciona, mas ela já não se conecta ao binário mais recente da TOTVS)

Se tiver mais alguma informação que eu possa fornecer para ajudar, estou à disposição.

**Comment by rafa2you** [comment]
Acrescentando,

A princípio pensamos que este problema seria relacionado ao compilador, e não à extensão do VSCode, e por isso abrimos um ticket no suporte da TOTVS, mas eles nos orientaram a abrir uma issue aqui.

![image](https://user-images.githubusercontent.com/62104671/163407045-afdf8fd6-5348-4d03-9b00-59ce1236107c.png)

Como em versões anteriores da extensão a compilação ocorre sem erros, talvez este seja o canal adequado mesmo.

Fico à diposição.

Att.,
Rafael

**Comment by danielbolognani** [comment]
@rafa2you Mesmo com o erro de Linter, se vc tentar compilar (ctrl-f9), acusa o mesmo erro? Pergunto isso pois o linter analisa os fontes localmente, mas a partir do momento que é feita a compilação, isso vai para o appserver.
De qualquer forma consegue anexar aqui algum exemplo com esse problema?

**Comment by lwtnb-wrk** [comment]
@rafa2you Essa issue me deixou bastante intrigado pois você diz que funciona apenas usando uma versão mais antiga 1.3.0...
De qualquer forma, se puder nos auxiliar realizando mais alguns testes nos ajudaria bastante.

Você está utilizando os Includes atualizados?
Caso negativo, sugiro realizar um novo teste baixando os Includes mais recentes no Suporte Downloads.
E se afirmativo, tente exatamente o contrário baixando os Includes mais antigos.
Esses problemas de pré-compilador geralmente estão associados com algumas alteração realizada nos Includes. 

Se o problema persistir, favor ver em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

PS.: Seus binários não estão muito desatualizados, mas a ultima versão do LG 17 é a 17.3.0.20 e a do Harpia é a 20.3.0.8. Sugiro atualizar pelo menos a do Harpia pois a 20.3.0.4 tinham alguns problemas críticos que foram corrigidos.

**Comment by rafa2you** [comment]
> @rafa2you Mesmo com o erro de Linter, se vc tentar compilar (ctrl-f9), acusa o mesmo erro? Pergunto isso pois o linter analisa os fontes localmente, mas a partir do momento que é feita a compilação, isso vai para o appserver. De qualquer forma consegue anexar aqui algum exemplo com esse problema?

Olá Daniel. Naqueles em que o Linter acusa erro em linha aleatória, nem compila mesmo. Mas mesmo nos que ele não acusa erro, ao compilar, gera essas tags todas abertas.

**Comment by rafa2you** [comment]
> @rafa2you Essa issue me deixou bastante intrigado pois você diz que funciona apenas usando uma versão mais antiga 1.3.0... De qualquer forma, se puder nos auxiliar realizando mais alguns testes nos ajudaria bastante.
> 
> Você está utilizando os Includes atualizados? Caso negativo, sugiro realizar um novo teste baixando os Includes mais recentes no Suporte Downloads. E se afirmativo, tente exatamente o contrário baixando os Includes mais antigos. Esses problemas de pré-compilador geralmente estão associados com algumas alteração realizada nos Includes.
> 
> Se o problema persistir, favor ver em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.
> 
> PS.: Seus binários não estão muito desatualizados, mas a ultima versão do LG 17 é a 17.3.0.20 e a do Harpia é a 20.3.0.8. Sugiro atualizar pelo menos a do Harpia pois a 20.3.0.4 tinham alguns problemas críticos que foram corrigidos.

Olá lwtnb-wrk,

Nossos binários são geridos pela TOTVS Cloud, e a atualização para a release 33 com essa versão do Hárpia está sendo executada por uma equipe de atualização da própria TOTVS, por isso seu comentário me deixou deveras preocupado. rs

Mas vou fazer o teste dos includes. Ainda na versão 1.3.11 da extensão eu havia pego os últimos disponíveis, mas realmente, agora que tenho o binário da Hárpia, falha minha não ter buscado os includes mais recentes dela. Farei esse teste. 

Obrigado pela dica. Volto com novidades (espero que as melhores).

**Comment by rafa2you** [comment]
Oi de novo pessoal,

Atualizei os includes, configurei pra gerar log, estava tentando criar cenários que facilitassem a análise de vocês e acho que descobri por acidente o que é: A sequência de fim de linha!

O problema acontece nos fontes com fim de linha LF, se eu troco para CRLF, na mesma hora o problema some.
![image](https://user-images.githubusercontent.com/62104671/163457958-87ed2544-0328-42ad-9276-7482f5d7580d.png)
![image](https://user-images.githubusercontent.com/62104671/163458030-12c3f72d-1b03-4468-bf47-a7f7cb0f275b.png)

Inclusive após compilação, o html gerado volta a ter o fechamento das tags finais.
![image](https://user-images.githubusercontent.com/62104671/163457628-f75067f2-81d4-45eb-9b44-7d54fd2cc265.png)

Esses LF nos nossos fontes devem surgir após copiar e colar de outras ferramentas de teste como o JSFiddle. O workaround agora passa a ser corrigir este setup nos fontes, mas para o bem da extensão, fica aí a recomendação de tratar esta minor issue no futuro.

Um grande abraço e obrigado!

**Comment by danielbolognani** [comment]
Os fontes advpl realmente precisam sempre usar finais de linha CR/LF (padrão Windows).
Obrigado por informar qual era o problema, vamos deixar como uma possível melhoria no futuro.

Abraços!
