### ISSUE TITLE
Erro ao excluir fonte do RPO

### ISSUE THREAD

**Issue by pointersp** [totvs/tds-vscode#957]
Ola,

Não estou conseguindo excluir um arquivo/recurso do RPO na R33.

Appserver - Linux
2022-04-20T11:15:26.040759-03:00 100519|***  TOTVS S/A  ***
***  www.totvs.com.br  ***
* TOTVS - Build 7.00.210324P - Mar 12 2022 - 03:40:24
* Build: 64 bits
* SVN Revision: 34023
* Build Version: 20.3.0.8

TOTVS Developer Studio for VSCode (AdvPL, TLPP e 4GL) - v1.3.13

Ao clicar com o botão direito sobre o projeto a ser excluído e selecionar "Excluir arquivo/recurso do RPO" tenho:
Vscode:
[Info  - 11:04:31] Starting program deletion.
[Info  - 11:04:31] Starting build for environment COMPILA2.
[Info  - 11:04:34] Starting build using RPO token ...
[Info  - 11:04:34] All programs successfully deleted from RPO.
[Info  - 11:04:34] Committing end build.
[Info  - 11:04:34] Program deletion finished.

Console.log do servidor:
2022-04-20T11:04:09.866773-03:00 88841|
[ERROR][SERVER] Fail to update Source Info Map at Remove Program Operantion.2022-04-20T11:04:09.866794-03:00 88841|
[ERROR][SERVER] Fail to update Source Info Map at Remove Program Operantion.2022-04-20T11:04:09.867565-03:00 88841|
[INFO ][SERVER] [Thread 88841] [20/04/2022 11:04:09] Updating RPO /totvsr33/microsiga/protheus/protheus/apo/compila2/custom.rpo2022-04-20T11:04:09.867606-03:00 88841|

Ao clicar com o botão direito sobre o projeto a ser excluído e selecionar "Advpl - Env - Excluir um(s) fonte(s) do RPO tenho um aviso no rodapé do VScode
*Please, select an environment!*

Em ambos os casos estou conectado no servidor e ambiente desejado e consigo compilar normalmente qualquer fonte, o erro ocorre somente ao tentar excluir um fonte.

Tenho 2 ambientes/rpo apontados no mesmo servidor.

Obrigado

**Comment by lwtnb-wrk** [comment]
@pointersp Voce tem outra extensão instalada além do tds-vscode para usar com o AdvPL? A extensão oficial tds-vscode tem apenas a opção "Exluir arquivo/recurso do RPO" para a exclusão mesmo, do jeito que você fez inicialmente. Esse segundo método aparentemente não é da nossa extensão...

E pelo logs no "Output" não ocorreu nenhum erro/problema, então aparentemente foi algum erro interno do AppServer.

De qualquer forma para que possamos analisar melhor, favor ver em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise.

Para evitar outros problemas, sugerimos não manter outras extensões além da tds-vscode para trabalhar com produtos da TOTVS.

**Comment by pointersp** [comment]
@lwtnb-wrk tinha outra extensão instalada, mas removi e realmente ficou somente a oficial agora

No LOG consta o envio do fonte para o RPO e posteriormente a tentativa de remoção do mesmo.

[log.zip](https://github.com/totvs/tds-vscode/files/8523558/log.zip)
.
Obrigado

**Comment by lwtnb-wrk** [comment]
@pointersp Realmente pelos logs não ocorre nenhum erro durante a execução da operação de exclusão do nosso lado.
A principio deve ser algum problema com o AppServer e possivelmente de configuração.
Neste caso você precisa abrir um chamado no suporte da TOTVS, pois pela extensão nada mais pode ser feito.
