### ISSUE TITLE
Error ao compilar 2 fontes ao mesmo tempo no servico REST

### ISSUE THREAD

**Issue by maximinocastro** [totvs/tds-vscode#958]
Bom dia Pessoal,

Compilando em um serviço rest, tentei compilar 2 fontes ao mesmo tempo e ele bugou e travou o Servico/RPO do Rest.

**Tentando conectar no Serviço:**

[Error - 12:10:13 PM] Could not retrieve appserver.ini contents.
[Info - 12:10:13 PM] Reconnection to the server 'Base Teste - Rest02' finished.
[Error - 12:10:13 PM] Retrieve connection error: Connection is not authenticated but requires authentication.

Após conectado no serviço com erro:

[Error - 12:09:28 PM] Start build error: Server returned:
It wasn't possible to obtain exclusive access to the objects repository
Impossible to decompress buffer

Obs. O protheus está no **CLOUD TOTVS** já reiniciamos o serviço e não volta de jeito nenhum, tentamos promover o RPO e apresenta falha e foi aberto um chamado  **14115514**  no portal para reiniciarem.

Versão: TOTVS Saúde
Build AppServer: 7.00.191205P-20210114 - 64 bits
Nome do servidor: CXDFFKPRPRDBN12
Sistema operacional: Windows Server 2012 R2
Appserver version: 19.3.1.5
Build DBAccess: 20200606-20201110
Release do RPO:  12.1.025
Release do dicionário: 12.1.025
Local files: ctree
License server: 2014 - 3.3.1
DB DataBase: MSSQL
DB API Build: 20200606-20201110

Versão da Lib:20210405
Data da Lib: 20210408_143338

MacOS Monterey - 12.3.1
Chip - M1

**Comment by danielbolognani** [comment]
@maximinocastro Primeira tentativa seria utilizar a chave BUILDKILLUSERS=1 (https://tdn.totvs.com/pages/viewpage.action?pageId=185743707) no General do Appserver, mas pela mensagem do appserver ("It wasn't possible to obtain exclusive access to the objects repository Impossible to decompress buffer"), eu diria que o RPO está corrompido e será necessário ou voltar algum backup ou pegar um novo RPO oficial.
Qualquer um dos casos, nós da extensão não temos ação em cima disso.
Abraços!

**Comment by maximinocastro** [comment]
@danielbolognani acredito que não seja a questão do BUILDKILLUSERS por que o servico REST não fica online, é apresentando que o serviço está online no portal do CLOUD porém não consigo abrir o smartclient e nem conectar no server.

**Comment by danielbolognani** [comment]
Então é como comentei, provavelmente o RPO está corrompido, será necessário subir algum backup ou pegar um oficial no portal de downloads. Pelo extensão TDS-VSCode não será possível recuperar.

**Comment by maximinocastro** [comment]
@danielbolognani acabei de falar com o pessoal do CLOUD e era espaço em disco acabou e não fomos notificados e nem apresentou na ferramenta do CLOUD e nem no VsCode essa informação. Após a manutenção deles voltou a funcionar o ambiente.

**Comment by danielbolognani** [comment]
Bom saber que resolveu, porém esse é o tipo de informação que não temos acesso via extensão. Só recebemos que falhou na abertura do RPO, e só com essa informação não temos como concluir que estava sem espaço em disco.
