### ISSUE TITLE
Erro ao aplicar patch

### ISSUE THREAD

**Issue by VctrAndrade** [totvs/tds-vscode#96]
Ao tentar aplicar um patch, é apresentado o erro abaixo: 

**"One or more validations errors detected: - Patch URI list was not informed."**

**Comment by lwtnb-wrk** [comment]
Reproduzi o erro apenas para aplicação direta do arquivo de patch pelo menu de contexto "Patch Apply from file".

**Comment by lwtnb-wrk** [comment]
Já foi corrigido e estará disponivel na proxima atualizacao

**Comment by brunos0** [comment]
Bom dia Galera.

Atualizei meu plugin para a última versão 0.3.12 e estou obtendo o essa mensagem de erro. Preciso zerar alguma configuração ou reset para funcionar o plugin atualizado?
