### ISSUE TITLE
Não consigo conectar no Github.

### ISSUE THREAD

**Issue by michelle2110** [totvs/tds-vscode#960]
Oi, vim pedir ajuda porque fuçei tudo a internet.. vi videos e não consigo conectar no github, enão meu vscode fica em modo de segurança e não consigo fazer nada.
Estou estudando Java, baixei ele pra codar e não to conseguindo fazer nada 
![image](https://user-images.githubusercontent.com/102696432/166127565-25f544b2-163b-45b4-a9b4-ecc7863aab93.png)
dá esse erro aqui. 
![image](https://user-images.githubusercontent.com/102696432/166127580-8aa39a1c-8162-4e80-82d7-5325d5f95d10.png)

e no fim não completa. 
![image](https://user-images.githubusercontent.com/102696432/166127599-39ad3034-d2e5-4f56-8088-3da3382fbd03.png)

**Comment by danielbolognani** [comment]
Bom dia @michelle2110 
Esse espaço é apenas para dúvidas/problemas em relação a extensão TDS-VSCode.
