### ISSUE TITLE
Conexão VScode com AppServer em um VPS

### ISSUE THREAD

**Issue by crondinelli** [totvs/tds-vscode#961]
Estou tentando conectar meu VScode em um appserver que está em um VPS, este servidor está em uma DMZ e portanto toda conexão passa por um redirecionamento de portas, tenho um appserver exclusivo, o qual meu smart acessa remotamente normalmente, mas o VScode apresenta: Unable to connect to the server. Check if the IP:port is correct, the server is online and try again.

**Comment by danielbolognani** [comment]
Boa tarde,
O VSCode e o Smartclient utilizam a mesma rota, ou seja, ip/porta para se conectarem no Appserver. No Appserver a conexão segura (SSL) está habilitada? Isso já funcionou alguma vez e parou agora?
Se teve atualização de versão do appserver, tenta excluir e criar novamente o appserver dentro da extensão, para ele pegar corretamente as informações atualizadas do appserver.

**Comment by crondinelli** [comment]
Não está habilitado SSL... tirei minha base do cloud e passei para um VPS com Windows Server 2019.
Daniel ja exclui e recriei diversas vezes, tenho diversas bases distintas em meu VScode, somente essa não conecta. Onde poderia pegar logs do VScode para tentar entender o que está havendo?

**Comment by crondinelli** [comment]
Vi esta mensagem no meu appserver:   Server not allowed to accept IDE/Debugger connections - From 10.100.35.37

**Comment by crondinelli** [comment]
Consegui Daniel, obrigado!! era uma tag na General do server!

**Comment by bigois** [comment]
A chave é a CanAcceptDebugger, normalmente ela estará com 0.
Comente ela ou altere para 1.
