### ISSUE TITLE
Debug pulando linhas

### ISSUE THREAD

**Issue by fabiofurlanc** [totvs/tds-vscode#962]
No processo de debug via vscode, o rpo está conforme o fonte tanto que recompilo ele durante o video da evidência para comprovar e mesmo, assim durante o debug ao chegar na linha de parada e selecionar a opção equivalente ao F10 para processar e ir para próxima linha o debug pula diversas linhas, veja no vídeo em anexo que da linha 311 pula direto para linha 320 sem qualquer motivo !
Em anexo também exportar dados do ambiente para demonstrar que está atualizado 

**Desktop (please complete the following information):**
 - OS/Architecture: Windows 64 bits
[golin_12_teste_compila_exportar_dados.csv](https://github.com/totvs/tds-vscode/files/8605743/golin_12_teste_compila_exportar_dados.csv)

https://user-images.githubusercontent.com/55297980/166318725-bc330760-48f1-4274-b541-087a5a887a4b.mp4

**Comment by danielbolognani** [comment]
Boa tarde,
Qual versão de appserver/smartclient que está em utilização?

**Comment by fabiofurlanc** [comment]
Bom dia, conforme já consta na evidência enviada arquivo .csv, repetindo:



Informações do remote
--
Lib do remote | QT-5.14.2 WIN
Tipo do remote | Microsoft Windows
Build do remote | 7.00.191205P-20211008
Versão do remote | 19.3.1.7
  |  
Informações   do AppServer
Tipo do servidor | Console
AppServer Build | 7.00.191205P-20211019
Appserver version | 19.3.1.8
Servidor 64 bits | Sim
Servidor Unix | Não

**Comment by DanielYampolschi** [comment]
Ola @fabiofurlanc informe também por favor a versão do plugin tds_vscode que voce esta usando. 
Tente remover todos os breakpoints e adicione-os novamente.

**Comment by danielbolognani** [comment]
Boa tarde, quando retornar com a versão do plugin, por favor já gerar os Logs (https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs) principalmente o dap.log da ocorrência.
