### ISSUE TITLE
Erro ao compilar Pacth - TDS - VSCODE

### ISSUE THREAD

**Issue by 83160900** [totvs/tds-vscode#964]
suporte bom dia
[erro compilação.zip](https://github.com/totvs/tds-vscode/files/8639674/erro.compilacao.zip)
!
Ao compilar qualquer Patch meu TDS apresenta o seguinte erro anexo, lembrando que esse erro acontece somente em Patchs, compilações de fontes não apresenta nenhum erro. ( Obs. erro também acontece no VSCODE.
att,

**Comment by danielbolognani** [comment]
Bom dia @83160900 
Aqui só tratamos problemas com o VSCode, favor anexar e gerar os logs da extensão TDS-VSCode (https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs), assim como todas as versões de Appserver, extensão e Protheus envolvidas.
