### ISSUE TITLE
Sobreposição de include na aplicação de patch

### ISSUE THREAD

**Issue by Belyukie** [totvs/tds-vscode#965]
A opção 'Apply old files' da aplicação de patch não verifica includes.
Caso aplique um patch contendo arquivos mais antigos que o rpo, sem marcar a opção (padrão), os arquivos fonte são mantidos em sua versão mais recente, mas os .tres sempre são sobrepostos pela versão do patch, independente da data.

OS/Architecture: Windows 10 x64
Appserver: 20.3.0.8 (recordo da ocorrência também no lobo guará 19)

**Comment by brodao** [comment]
@Belyukie 

O processo de aplicação de pacotes (_patchts_) é efetuado pelo _appServer_, sendo a extensão TDS-VSCode apenas uma interface entre o desenvolvedor e o processo.

Solicito que abra um chamado junto a equipe do _appServer_, via [Central de Relacionamento TOTVS](suporte.totvs.com.br/).

Grato.
