### ISSUE TITLE
Problema ao carregar snippets dentro do VSCode

### ISSUE THREAD

**Issue by vitor-gabriel** [totvs/tds-vscode#966]
Ao iniciar um novo fonte .PRW e .TLPP, e procuro pelos snippets do tds-vscode, alguns snippets carregam corretamente, outros me apresentam mal formatado, tem alguns snippets que preciso digitar toda a função para ele carregar dentro do VS-code, TDS versao 1.3.13.
Segue prints:

![image](https://user-images.githubusercontent.com/62556013/167444625-823ef82a-8667-4789-a92a-2ead64ea6c76.png)
![image](https://user-images.githubusercontent.com/62556013/167444648-f2072ab6-66f9-4c80-897d-1c080f88f598.png)
![image](https://user-images.githubusercontent.com/62556013/167444661-4922550e-7163-4b76-8d8c-8aa4e6a1a98e.png)

**Comment by DanielYampolschi** [comment]
ola @vitor-gabriel Qual a versão do plugin do tds_vscode você tem instalado?

**Comment by vitor-gabriel** [comment]
Boa tarde, estou com a versão 1.3.13 do tds_vscode
![image](https://user-images.githubusercontent.com/62556013/167943155-3d40ad59-8125-4e0f-99ab-f08da8568ac0.png)

**Comment by lwtnb-wrk** [comment]
@vitor-gabriel Reproduzimos a ocorrencia e estamos investigando.
Grato pelas informações.

**Comment by brodao2** [comment]
O chamado foi resolvido. Favor aguarda a liberação da próxima RC ou do versão final.

**Comment by vitor-gabriel** [comment]
Obrigado, aguardo ansiosamente mestre.

**Comment by lwtnb-wrk** [comment]
@vitor-gabriel Se quiser testar e validar a correção instale a versão Pré Release https://github.com/totvs/tds-vscode/releases/tag/v1.3.17-RC2 manualmente seguindo as instruções em https://github.com/totvs/tds-vscode/blob/master/docs/install.md

**Comment by vitor-gabriel** [comment]
Boa tarde,

Segue print da versao instalada:
![image](https://user-images.githubusercontent.com/62556013/211396056-6fde690b-1a6e-4d48-8cd5-465601062a9b.png)

Segue prints do snippets na versao informada pelo @lwtnb-wrk:
![image](https://user-images.githubusercontent.com/62556013/211396520-c543a7ba-a2f7-4469-9b8a-e2c40f97b51c.png)
![image](https://user-images.githubusercontent.com/62556013/211396554-25b9a997-0c3e-4933-91f9-ad4fe53d9742.png)
![image](https://user-images.githubusercontent.com/62556013/211396602-78326f64-4198-4eb2-8b17-e0ddb2754b3e.png)

**Comment by lwtnb-wrk** [comment]
@vitor-gabriel Opa, grato por testar e avisar. Talvez eu tenha me confundido com a versão em que essa correção vai sair. Amanhã devo gerar a RC3 e eu refaço meus testes para ver se está ok nessa outra versão.

**Comment by vitor-gabriel** [comment]
Boa tarde @lwtnb-wrk, segue prints do meu ambiente:

![tds-version](https://user-images.githubusercontent.com/62556013/211882657-48db4c87-40ba-4d63-adb6-51c4a8b7b953.png)
![dtos](https://user-images.githubusercontent.com/62556013/211882664-f0e495b8-eb15-4fc9-832b-bc15f065afe4.png)
![killapp](https://user-images.githubusercontent.com/62556013/211882625-f73e3e5b-5ee6-4d60-bfe2-33e46e5e3c87.png)
![procname](https://user-images.githubusercontent.com/62556013/211882648-f7872408-9000-4ac6-bf05-aa793c617019.png)

**Comment by lwtnb-wrk** [comment]
@vitor-gabriel Não era esse o resultado esperado?

**Comment by vitor-gabriel** [comment]
Os snippets que tenho criado como de usuário, esta carregando corretamente, (nos prints eu desativei), os da própria extensão carregam de mal formatados, com caixa alta, sem detalhes. Esta sim carregando todos os snippets, agora só mal formatado.

Esperava algo mais nesta forma @lwtnb-wrk :
![image](https://user-images.githubusercontent.com/62556013/211885216-ed5f64f5-89cc-4fb3-9234-1cc9ca7adeae.png)

Segue meu snippets, juntei alguns da comunidade e fiz alguns meus para fazer este arquivo zip (GitHub nao deixa subir arquivos com extensão json).
### [advpl.zip](https://github.com/totvs/tds-vscode/files/10394943/advpl.zip)

**Comment by lwtnb-wrk** [comment]
@vitor-gabriel Ah sim, quanto a formatação ser em caixa alta, cadastramos assim mesmo por padrão. Os detalhes realmente não são todas as funções que estão cadastradas por enquanto. Ainda devem existir funções faltando, pois são muitas funções existentes mesmo.
Vou tentar implementar uma ferramenta para que a comunidade possa sugerir alterações, mas por enquanto vamos alterando isso aos pouco.
De qualquer forma grato por apontar essa questão que deve permanecer em evolução constante.

**Comment by vitor-gabriel** [comment]
Show, fico aguardo dessa ferramenta, obrigado pelo suporte.

**Comment by lwtnb-wrk** [comment]
liberada versão 1.3.17 que deve resolver parcialmente esta questão, favor atualizar a extensão e caso necessário abra uma nova issue, mas essa questão ainda será revisitada no futuro para melhorias.
