### ISSUE TITLE
Exporta dados via VSCode

### ISSUE THREAD

**Issue by rodstephanel** [totvs/tds-vscode#967]
**Is your feature request related to a problem? Please describe.**
O exporta dados que era possível ser feito pelo próprio Protheus na release 25 ou anterior continha todos os fontes compilados, porém hoje na release 33 o exporta dados só traz os fontes que estão no RPO principal e não os fontes contidos no RPO customizado. Com isso tenho usado o inspetor de objetos pelo VSCode para localizar os fontes personalizados compilados, porém quando faço o export para um arquivo .txt as informações ficam "bagunçadas" por não conseguir fazer um filtro neste arquivo.

**Describe the solution you'd like**
Acredito que se as informações fossem separadas por ";" (ponto-vírgula), poderia importar o arquivo .txt para o Excel como .csv e assim conseguiria fazer os filtros que preciso para separar em uma lista o que são fontes personalizados e o que não são.

**Describe alternatives you've considered**
Assim eu colocaria os ";" conforme exemplo de linha abaixo:

ACDA010.PRW;              09/12/2019 10:42:13;      D;                        P;                        [object Object]

Dessa forma em .csv teríamos 5 colunas e facilitaria o filtro como era possível fazer na release 25

**Comment by brodao** [comment]
@rodstephanel 

Não esta claro onde esta o problema. Você cita versões de Protheus que não nos permite verificar a ocorrência.

Reabra este chamado informando os dados solicitados conforme [Informações importantes ao abrir o chamado](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#informa%C3%A7%C3%B5es-importantes-ao-abrir-uma-issue) e anexe os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)

É de extrema importância informar um passo a passo e se possível, anexe print de telas ou vídeo e o console log do Protheus.

No aguardo

**Comment by rodstephanel** [comment]
@brodao Na verdade abri essa Issue como uma sugestão de melhoria e não como problema.
As versões do Protheus que cito é a release 25 (Lobo Guará) e release 33 (Harpia).
Vou tentar explicar como um pouco mais de detalhamento.

Você já usou o Inspetor de Objetos no VSCode para verificar quais fontes encontram-se compilados no RPO? (https://github.com/totvs/tds-vscode/wiki#inspetor-de-objetos-do-rpo)
Se sim, acredito também que você notou que na versão v1.3.13 da extensão TOTVS Developer Studio é possível exportar a consulta feita no Inspetor de Objetos para um arquivo .txt
![image](https://user-images.githubusercontent.com/31445805/167457469-511ab78a-82a5-448c-98cc-437d0fe5fd58.png)

Minha sugestão é para que ao exportar esse arquivo (ver anexo) ele seja quebrado por ";" nos locais indicado para que seja possível abri-lo como .csv e assim poder criar os filtros necessários.
[Teste_exporta_dados.txt](https://github.com/totvs/tds-vscode/files/8653653/Teste_exporta_dados.txt)

Caso ainda necessite de mais alguma informação, por favor me avise.

E por favor, antes de  fechar a Issue, tente entender melhor o ocorrido.

**Comment by brodao** [comment]
Agora ficou claro. Vou reabrir seu chamado e deixar anotado essa melhoria.

Grato.

**Comment by lwtnb-wrk** [comment]
liberada v1.3.16 com a melhoria sugerida
