### ISSUE TITLE
Forçar recompilar fontes

### ISSUE THREAD

**Issue by cirilorocha** [totvs/tds-vscode#969]
**Is your feature request related to a problem? Please describe.**
Hoje quando usamos o atalho Ctrl+F9 o VsCode força a recompilação do fonte aberto independente da data do fonte no RPO. Quando clicamos em uma pasta do projeto e clicamos em Compilar Arquivo/Pasta o plugin compila apenas os fontes mais atuais não força a recompilação.

**Describe the solution you'd like**
Poderia ter alguma configuração ou outra opção no menu que permitisse forçar a recompilação da pasta ou projeto.

**Comment by danielbolognani** [comment]
Para forçar a recompilação através do menu de contexto, por favor utilize a tecla Alt+Botao direito que irá trocar as opções para Recompilar Projeto/Pasta.
