### ISSUE TITLE
Indentação

### ISSUE THREAD

**Issue by caiadofelipe** [totvs/tds-vscode#97]
Boa tarde.

Não consigo fazer funcionar a indentação com o SHIFT+ALT+F. 
Precisa ser feito alguma configuração?

**Comment by matheus-sales** [comment]
Olá Felipe,

Está com a ultima versão disponível? 

Habilitamos novamente a indentação nessa ultima versão liberada 0.3.10 e ela só funciona com o fonte aberto e pressionando ALT + SHIFT + F. 

Se estiver correto, tente formatar no fonte que eu anexei. Caso o problema persista, anexe o fonte que está tendo problema. 

Obrigado
[escolheNum.zip](https://github.com/totvs/tds-vscode/files/3331292/escolheNum.zip)

**Comment by caiadofelipe** [comment]
@matheus-sales , Realmente no seu fonte funciona, mas os que estão no meu projeto ele não indenta.
Segue um fonte meu que não compila.
[APPCO03.zip](https://github.com/totvs/tds-vscode/files/3331315/APPCO03.zip)

**Comment by caiadofelipe** [comment]
@matheus-sales , percebi uma coisa, meus cabeçalhos estão todos neste modelo.

/*/{Protheus.doc} APPCO03
Cadastro de Reservas
@author Felipe Caiado
@since 11/06/2019
@version undefined
@type function
/*/

Quando mudo para o modelo abaixo ele indenta a função, mas as outras funções ele não indenta. utilizo esse Modelo do protheus DOC que existia no TDS com a tecla de atalho CTRL+ALT+D

/*{Protheus.doc} APPCO03
Cadastro de Reservas
@author Felipe Caiado
@since 11/06/2019
@version undefined
@type function
*/

**Comment by matheus-sales** [comment]
Entendo Felipe, iremos analisar o problema e resolver

**Comment by caiadofelipe** [comment]
Obrigado @matheus-sales , fico no aguardo.

**Comment by likid** [comment]
@matheus-sales tem um problema que ocorreu aqui com a indentação em que ela é executada apenas na primeira vez, se eu tentar rodar novamente o vscode não reformata o código.
