### ISSUE TITLE
Atualização de LIB no VSCODE

### ISSUE THREAD

**Issue by thiagocomoti** [totvs/tds-vscode#970]
# Ajude-nos a ajudá-lo.

- Verifique se a extensão está atualizada.
- Ver [Resolução de Problemas](TROUBLESHOOTING.md#problemas-gerais), com ocorrências comuns e/ou conhecidas.

## Digite os dados abaixo

**Descreva o bug**
Erro ao atualizar a lib versão 12.1.33 harpia, download realizado do portal da TOTVS

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para 'VSCODE'
2. Clique em 'patch apply'
3. Role para baixo até 'arquivo  22-04-05-LIB_LABEL_21032022_P12_HARPIA-TTTM120.ptm'
4. Veja o erro

Patch file: e:/workspaceteste/P12_HARPIA-tttm120_hp.ptm
Starting build for environment taf.
Starting build using RPO token ...
Aborting end build (rollback changes).
Patch validate finished.
Patch validate could not be executed.

**Capturas de tela**
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

**Desktop (por favor, preencha as seguintes informações):**
 - OS/Arquitetura: Windows Server 2016 Standard 
 - versão TAF atualização da 12.1.27 para 12.1.33
[TAF atualização 12.1.27 para 12.1.33.docx](https://github.com/totvs/tds-vscode/files/8664599/TAF.atualizacao.12.1.27.para.12.1.33.docx)

**Comment by lwtnb-wrk** [comment]
@thiagocomoti Não entendi muito bem o que está tentando realizar...
Você está com um ambiente Lobo Guará ou seria um Harpia??
Ou está tendo migrar do LG para o Harpia??

**Comment by thiagocomoti** [comment]
Boa tarde,

Sim estou atualizando de LG versão 12.1.27 para HP 12.1.33


Thiago Gomes Comoti
Analista de T.I
***@***.***

+55 11    4341.9315
+55 11 9 8919.8678

Av. Robert Kennedy, 85
São Bernardo do Campo/SP
www.arteb.com.br<http://www.arteb.com.br>
***@***.***
Esta mensagem e seus anexos:
(i) contém informações confidenciais;
(ii) são exclusivos para o(s) destinatário(s) desse  e-mail;
(iii) possuem fins específicos; e
(iv) são protegidos pelo privilégio legal de comunicação entre advogado e cliente.
Se você não é o destinatário dessa mensagem, por favor, delete-a e avise ao remetente.

De: lwtnb-wrk ***@***.***>
Enviada em: quinta-feira, 12 de maio de 2022 16:52
Para: totvs/tds-vscode ***@***.***>
Cc: Thiago Gomes Comoti ***@***.***>; Mention ***@***.***>
Assunto: Re: [totvs/tds-vscode] Atualização de LIB no VSCODE (Issue #970)


@thiagocomoti<https://github.com/thiagocomoti> Não entendi muito bem o que está tentando realizar...
Você está com um ambiente Lobo Guará ou seria um Harpia??
Ou está tendo migrar do LG para o Harpia??

**Comment by danielbolognani** [comment]
Só para entender, vc já fez a atualização dos binários, rpo, banco para a versão 12.1.33?
Se ainda está com tudo na versão 12.1.27, não tem como aplicar o patch da versão 12.1.33.
Se precisar de auxilio para essa migração, não temos como ajudar por aqui, favor procurar atendimento direto pelo suporte.totvs.com.br
Abs!

**Comment by thiagocomoti** [comment]
Só para entender, vc já fez a atualização dos binários, rpo, banco para a versão 12.1.33?

Sim fa realizei a atualização.
Se ainda está com tudo na versão 12.1.27, não tem como aplicar o patch da versão 12.1.33.

Já estou na versão 12.1.33
Se precisar de auxílio para essa migração, não temos como ajudar por aqui, favor procurar atendimento direto pelo suporte.totvs.com.br

Já abri chamado na TOTVS, e fui informado para abrir chamado no GitHub


Fico no aguardo.



Thiago Gomes Comoti
Analista de T.I
***@***.***

+55 11    4341.9315
+55 11 9 8919.8678

Av. Robert Kennedy, 85
São Bernardo do Campo/SP
www.arteb.com.br<http://www.arteb.com.br>
***@***.***
Esta mensagem e seus anexos:
(i) contém informações confidenciais;
(ii) são exclusivos para o(s) destinatário(s) desse  e-mail;
(iii) possuem fins específicos; e
(iv) são protegidos pelo privilégio legal de comunicação entre advogado e cliente.
Se você não é o destinatário dessa mensagem, por favor, delete-a e avise ao remetente.

De: Daniel Otto Bolognani ***@***.***>
Enviada em: quinta-feira, 12 de maio de 2022 17:13
Para: totvs/tds-vscode ***@***.***>
Cc: Thiago Gomes Comoti ***@***.***>; Mention ***@***.***>
Assunto: Re: [totvs/tds-vscode] Atualização de LIB no VSCODE (Issue #970)


Só para entender, vc já fez a atualização dos binários, rpo, banco para a versão 12.1.33?
Se ainda está com tudo na versão 12.1.27, não tem como aplicar o patch da versão 12.1.33.
Se precisar de auxilio para essa migração, não temos como ajudar por aqui, favor procurar atendimento direto pelo suporte.totvs.com.br
Abs!

**Comment by lwtnb-wrk** [comment]
@thiagocomoti Agora sim ficou mais claro. Sem informações não temos como entender seu problema.
Se você já está com tudo migrado e configurado no Harpia com a LIB 12.1.33, seu problema não tem mais relação com a atualização da LIB 12.1.27 que causou essa pequena confusão.

Enfim, veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise após repetir a operação que está falhando.

Agora um segundo ponto, esse ambiente que está utilizando se trata de um ambiente TAF?

**Comment by lwtnb-wrk** [comment]
encerrando por falta de retorno
