### ISSUE TITLE
Não mostra tabela como resultados da compilação #895

### ISSUE THREAD

**Issue by cirilorocha** [totvs/tds-vscode#971]
Este problema de não mostrar os resultados da compilação (issue anterior #895) voltou a ocorrer na versão 1.3.13. Não vou detalhar aqui porque é exatamente a mesma situação da issue original

**Comment by lwtnb-wrk** [comment]
@cirilorocha Testei aqui e a tabela está sendo exibida normalmente. É dessa tabela que estamos falando correto?
![image](https://user-images.githubusercontent.com/49563478/168301987-3276846b-0b63-4815-af1a-d93223906778.png)

**Comment by brodao** [comment]
A tabela só é apresentada se forem compilados multiplos arquivos e se a opção totvsLanguageServer.askCompileResult estiver configurada com "Yes". Veja configurações (_settings_).

**Comment by cirilorocha** [comment]
A tela é exatamente esta ai mesmo. Aqui a configuração está da forma que Brodao falou mas não aparece.

https://user-images.githubusercontent.com/96308173/168325575-6b5b54d3-aed8-4daa-a70c-8713b8021885.mp4

**Comment by danielbolognani** [comment]
Isso acontece porque o VSCode não compilou nenhum arquivo pois todos já estavam compilados.
Para forçar a recompilação, utilize a tecla Alt + botão direito do mouse (para abrir o menu), assim a opção mostrada será "Recompile....". dessa forma deve mostrar o resultado da compilação.
Abs!

**Comment by cirilorocha** [comment]
Não sei o que pode estar ocorrendo, já desinstalei o plugin e instalei de novo e nada. Antes mesmo que nenhum fonte fosse compilado aparecia a pergunta para mostrar a janela. Agora não aparece mais, testei em outra máquina e realmente está funcionando só na minha que está com esse problema. vou tentar reconfigurar tudo para ver ser resolve.

**Comment by cirilorocha** [comment]
Vocês poderiam me indicar quais pastas preciso apagar para limpar todas as configurações e recomeçar. Limpei aqui algumas mas ele ainda está com os mesmos sintomas, não aparece a pergunta para mostrar os resultados.

**Comment by lwtnb-wrk** [comment]
@cirilorocha Vi pelo video que esta trabalhando com multiplos Workspaces.
Nas configuracoes voce mostrou suas configuracoes de Usuario, veja que existe ao lado dela as configurações de Workspace...
Veja como esta configurada a opcao de "As Compile Result" no Workspace...

**Comment by cirilorocha** [comment]
Show agora sim resolveu, a configuração era da workspace. Muito obrigado pela força.
