### ISSUE TITLE
Erro smartclient com VS CODE

### ISSUE THREAD

**Issue by Zaniinn** [totvs/tds-vscode#972]
Boa Tarde,

Estou com o seguinte erro:

Após realizar a instalação do Protheus, compilo um fonte no VSCODE que não envolve banco de dados e da tudo certo.
Quando tento compilar fontes que demandam uso do banco, acontecem alguns erros e daí para frente, não consigo mas fazer nada no protheus.
 
![Capturar3](https://user-images.githubusercontent.com/99829317/168671276-9db7faa0-fdba-488f-925c-57dfd508e4d5.PNG)
![Capturar](https://user-images.githubusercontent.com/99829317/168671288-500e211a-ad20-49a7-b05c-0d56497122c1.PNG)
![Capturar2](https://user-images.githubusercontent.com/99829317/168671292-938417b2-1968-4651-a960-402be8f8dfe2.PNG)

Após isso, não consigo mais compilar nenhum fonte e nem acesso ao configurador do smartclient tenho, como se supostamente corrompesse tudo.

![Capturar7](https://user-images.githubusercontent.com/99829317/168672370-00b0634f-ec8f-4d61-840f-ad89b222fb5f.PNG)

Outro erro que ocorre porém ainda na instalação, quando esta sendo criado as tabelas no banco o console do appserver fica mostrando um erro e é apenas na r33, testei na r27 e corre tudo normal
![appserver erro](https://user-images.githubusercontent.com/99829317/168671600-04e1660c-cb1e-445a-9189-d47a91f04213.PNG)

Versão vscode 1.67.1
versão extensão totvs 1.3.13
versão build 7.00.210324P

Ficarei grato pela ajuda, já testei de tudo kkkkkk

**Comment by lwtnb-wrk** [comment]
@Zaniinn Os erros estao ocorrendo durante a compilacao ou apenas depois na hora de executar esses programas??

De qualquer forma veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analise. Apos configurar os logs, repita as operacoes para que elas aparecam nos logs, ok?

**Comment by lwtnb-wrk** [comment]
encerrando por falta de retorno
