### ISSUE TITLE
Erro ao atualizar Path no VSCODE

### ISSUE THREAD

**Issue by thiagocomoti** [totvs/tds-vscode#975]
*Desktop (please complete the following information):**
 - OS/Architecture: [e.g. Windows 64 bits]

**Appserver (please complete the following information):**
 - Build (with date): [e.g. Build 7.00.210324P - 20211006]
 - OS/Architecture: Windows server 2016

Não consigo atualizar patch,
22-05-20-LIB_LABEL_02052022_P12_HARPIA-TTTM120.PTM,
e o path central_de_atualizacoes_v1_4_1_tttm120.ptm

Estou na versão 12.1.033 Totvs TAF
**Additional context**
![image](https://user-images.githubusercontent.com/104458357/170519512-4e7b981f-d24e-40ae-ae98-52526984e8df.png)
![image](https://user-images.githubusercontent.com/104458357/170519586-39a3fcbe-d9a7-406a-849b-ace60d7a1526.png)

VSCode esta atualizado
![image](https://user-images.githubusercontent.com/104458357/170536298-e3d967aa-35b4-4787-b89c-3ebbab4fb465.png)

[Dados Server.docx](https://github.com/totvs/tds-vscode/files/8780695/Dados.Server.docx)
[Dados Server.docx](https://github.com/totvs/tds-vscode/files/8780752/Dados.Server.docx)

**Comment by lwtnb-wrk** [comment]
@thiagocomoti Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para análise.

**Comment by thiagocomoti** [comment]
[totvsls.log](https://github.com/totvs/tds-vscode/files/8786190/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/8786191/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/8786192/totvsls_out.log)

**Comment by lwtnb-wrk** [comment]
@thiagocomoti Os logs em anexo não contem as informações das operações. Após configurar os logs é necessário repetir as operações para que elas constem nos logs.

**Comment by thiagocomoti** [comment]
[totvsls.log](https://github.com/totvs/tds-vscode/files/8787613/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/8787614/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/8787615/totvsls_out.log)

segue novos logs gerado, logs foram gerados após as operações.

**Comment by lwtnb-wrk** [comment]
@thiagocomoti Aparentemente pelos logs, vemos que o AppServer não está conseguindo executar a mensagem de validação do patch que enviamos para ele.
Poderia nos enviar o console.log do AppServer após o erro gerado na aplicação do patch?

**Comment by thiagocomoti** [comment]
opa sim, segue arquivo.
[console.log](https://github.com/totvs/tds-vscode/files/8788179/console.log)

**Comment by lwtnb-wrk** [comment]
@thiagocomoti Pelo console.log esta ocorrendo um erro no AppServer mesmo
[FATAL][SERVER] 27/05/2022 12:06:55[Thread 6272] [THROW] Error getting a valid map at file C:\bamboo\xml-data\build-dir\TP11-OF20300-TECXWIN64\advpl\publicenv.cpp line 12392

Mas antes de abrir um chamado na TOTVS, atualize seu AppServer pois notei que ele esta um pouco desatualizado. Atualize seu AppServer e repita os testes para ver se o erro persiste.
Se o erro persistir, vai ser necessário abrir um chamado na TOTVS e ja informe o suporte que voce já validou com o time do TDS pelo GitHub e que nos orientamos a abrir esse chamado.

**Comment by thiagocomoti** [comment]
entendi, obrigado vou realizar o procedimento informado.

**Comment by lwtnb-wrk** [comment]
@thiagocomoti E caso a atualização do AppServer resolva seu problema, por favor nos avise apenas para que outros usuarios que possam passar pela mesma situacao fiquem cientes de que a atualizacao pode resolver o problema.
E se nao resolver se puder, nos informe se conseguiu abrir um chamado na TOTVS.
Grato pelas informacoes

**Comment by lwtnb-wrk** [comment]
@thiagocomoti Voce atualizou seu appserver? Esse comportamento parece com um problema que foi resolvido no AppServer já. Nos AppServer novos deveria ocorrer um erro logo no inicio da aplicacao ao detectar que voce não tem acesso exclusivo do RPO, o que não está ocorrendo segundo os logs em anexo.

Para aplicar um patch, é necessário acesso exclusivo no RPO então realmente derrubar o serviço LSPULSE resolve o problema.  Você pode tambem adicionar a chave **BuildKillUsers=1** na seção [GENERAL] que ele faz isso automaticamente para você.

Eu costumo reiniciar o appserver para reiniciar os JOBS de sistema que sobem na inicialização.

**Comment by thiagocomoti** [comment]
Bom dia,

Sim atualizei o appserver para versão 20.3.0.8, já reiniciei o servidor mais não consigo startar o serviço


Thiago Gomes Comoti
Analista de T.I
***@***.***

+55 11    4341.9315
+55 11 9 8919.8678

Av. Robert Kennedy, 85
São Bernardo do Campo/SP
https://www.arteb.com.br
***@***.***
Esta mensagem e seus anexos:
(i) contém informações confidenciais;
(ii) são exclusivos para o(s) destinatário(s) desse  e-mail;
(iii) possuem fins específicos; e
(iv) são protegidos pelo privilégio legal de comunicação entre advogado e cliente.
Se você não é o destinatário dessa mensagem, por favor, delete-a e avise ao remetente.

De: lwtnb-wrk ***@***.***>
Enviada em: terça-feira, 31 de maio de 2022 08:38
Para: totvs/tds-vscode ***@***.***>
Cc: Thiago Gomes Comoti ***@***.***>; Mention ***@***.***>
Assunto: Re: [totvs/tds-vscode] Erro ao atualizar Path no VSCODE (Issue #975)


@thiagocomoti<https://github.com/thiagocomoti> Voce atualizou seu appserver? Esse comportamento parece com um problema que foi resolvido no AppServer já. Nos AppServer novos deveria ocorrer um erro logo no inicio da aplicacao ao detectar que voce não tem acesso exclusivo do RPO, o que não está ocorrendo segundo os logs em anexo.

Para aplicar um patch, é necessário acesso exclusivo no RPO então realmente derrubar o serviço LSPULSE resolve o problema. Você pode tambem adicionar a chave BuildKillUsers=1 na seção [GENERAL] que ele faz isso automaticamente para você.

Eu costumo reiniciar o appserver para reiniciar os JOBS de sistema que sobem na inicialização.

**Comment by lwtnb-wrk** [comment]
@thiagocomoti Esse erro é exatamente o comportamento esperado quando tentamos aplicar um patch ou efetuar uma compilação sem o acesso exclusivo ao RPO.

Se puder então, veja se consegue retornar ao RPO original onde o LSPULSE estava funcionando e adicione a chave BuildKillUsers=1 na seção [GENERAL] de seu AppServer (reinicie o AppServer por segurança). Em seguida aplique o patch mas sem derrubar o LSPULSE, a chave adicionada deve se encarregar disso. Depois verifique se o patch foi corretamente aplicado e o LSPULSE continua funcionando como esperado.

**Comment by lwtnb-wrk** [comment]
@thiagocomoti Não é possível desfazer uma aplicação de patch. Baixe um novo RPO do portal mesmo.

**Comment by thiagocomoti** [comment]
Bom dia,

Segundo orientação da Totvs foi reinstalado o appserver,

O problema foi resolvido.

Obrigado pela ajuda.


Thiago Gomes Comoti
Analista de T.I
***@***.***

+55 11    4341.9315
+55 11 9 8919.8678

Av. Robert Kennedy, 85
São Bernardo do Campo/SP
https://www.arteb.com.br
***@***.***
Esta mensagem e seus anexos:
(i) contém informações confidenciais;
(ii) são exclusivos para o(s) destinatário(s) desse  e-mail;
(iii) possuem fins específicos; e
(iv) são protegidos pelo privilégio legal de comunicação entre advogado e cliente.
Se você não é o destinatário dessa mensagem, por favor, delete-a e avise ao remetente.

De: lwtnb-wrk ***@***.***>
Enviada em: terça-feira, 31 de maio de 2022 09:18
Para: totvs/tds-vscode ***@***.***>
Cc: Thiago Gomes Comoti ***@***.***>; Mention ***@***.***>
Assunto: Re: [totvs/tds-vscode] Erro ao atualizar Path no VSCODE (Issue #975)


@thiagocomoti<https://github.com/thiagocomoti> Não é possível desfazer uma aplicação de patch. Baixe um novo RPO do portal mesmo.
