### ISSUE TITLE
Erro de conexão do servidor TSS

### ISSUE THREAD

**Issue by pedrojlima** [totvs/tds-vscode#976]
Boa tarde, 
[totvsls.log](https://github.com/totvs/tds-vscode/files/8781611/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/8781612/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/8781613/totvsls_out.log)
![TSS](https://user-images.githubusercontent.com/85879332/170563843-786fee8a-4c7a-4e92-bb32-e722de072cc5.PNG)
quando estou tentando conectar o servidor TSS exibe a mensagem abaixo. segue os logs também

**Comment by lwtnb-wrk** [comment]
@pedrojlima Pelos logs parece que o servidor simplesmente nem tentou responder ou recusou a conexão de imediato.
Experimente remover esse servidor e tente cadastrá-lo novamente. Se ele falhar no cadastro é porque ele não está sendo enxergado pelo tds-vscode.
Isso normalmente ocorre por questões de infraestrutura, pode ser a topologia da rede, firewall, antivírus, etc... Certifique-se que de tem acesso ao servidor e tente novamente.
Se o problema persistir nos envie os novos logs para vermos se houve alguma mudança...

**Comment by pedrojlima** [comment]
estava funcionando quando estava na versão 12.1.25 quando eu atualizei para a 12.1.27 parou a conexão.

**Comment by lwtnb-wrk** [comment]
@pedrojlima Alem da versao da LIB voce atualizou o AppServer??
Voce fez o procedimento que mencionei de remover e cadastrar o servidor novamente?

**Comment by pedrojlima** [comment]
Sim, todas as atualizações corretas, e remover e incluir o server também.

**Comment by lwtnb-wrk** [comment]
@pedrojlima Reenvie os novos logs para analisarmos
