### ISSUE TITLE
Não encontra o fonte em uma nova pasta ao debuggar

### ISSUE THREAD

**Issue by vitor-gabriel** [totvs/tds-vscode#978]
Compilo o fonte em uma pasta qualquer dentro do WorkSpace, e mudo o fonte de pasta, ao tentar debuggar, ele se perde na localização do fonte tentando abrir o fonte de onde ele foi compilado.

![image](https://user-images.githubusercontent.com/62556013/170725002-46178894-fa75-4e14-84c3-9b9509936480.png)

Windows 10 x64. TDS VSCode Versão 1.3.14, Protheus na release 12.1.33.

**Comment by lwtnb-wrk** [comment]
@vitor-gabriel Acredito que isso seja um comportamento do próprio VS Code, mas de qualquer forma veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos mande os logs para análise. Em especial o dap.log pois trata-se de debug.

**Comment by vitor-gabriel** [comment]
[logs.zip](https://github.com/totvs/tds-vscode/files/8788922/logs.zip)
@lwtnb-wrk segue logs

**Comment by lwtnb-wrk** [comment]
@vitor-gabriel Depois de mudar o fonte de lugar voce tentou recompilar o fonte?

**Comment by vitor-gabriel** [comment]
Sim, tentei recompilar, não funcionou, tentei excluir do repositório e compilar separadamente, funcionou

**Comment by lwtnb-wrk** [comment]
@vitor-gabriel Originalmente voce compilou na pasta "Fontes" e depois moveu para a "Processa Log" é isso?

**Comment by vitor-gabriel** [comment]
Exatamente, ao fazer isso, no debug ele me apresentava a tela do print acima, para solucionar, somente removendo do RPO e compilando na nova pasta.

**Comment by brodao** [comment]
@vitor-gabriel 

Tenho conhecimento de alguns comportamentos estranhos, que foram resolvidos informando a chave "RPOCUSTOM" no lugar de deixar o valor padrão. Tente ajustar para algo como ``RPOCUSTOM=M:\protheus\apo\custom.rpo``, atente-se que a pasta do ``custom.rpo`` já deve existir.

**Comment by vitor-gabriel** [comment]
Segue minha configuração do launcher.

``{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Depuração do idioma TOTVS",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "C:\\TOTVS\\SmartClient-FIEC\\smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true
		}
	],
	"lastPrograms": [
		{
			"label": "SIGAMDI"
		}
	],
	"lastProgramExecuted": "SIGAMDI"
}``

"GerenciamentoAPI-FIEC" é uma pasta aonde tenho .workspace com mesmo nome.
Encontrei problemas tambem na release 27, este **dap.log** se refere à release 27.

**Comment by brodao** [comment]
Pelo que entendi, você abre o _.workspace_ e este faz referencia a fontes de outras pastas que não esta dentro da pasta "GerenciamentoAPI-FIEC".

Se possível, anexa o arquivo _.workspace,_ por favor.

**Comment by vitor-gabriel** [comment]
Segue print em abaixo:
![image](https://user-images.githubusercontent.com/62556013/171059786-5807490f-a725-44b6-ab1d-64ab0edc49c8.png)

**Comment by DanielYampolschi** [comment]
@vitor-gabriel qual a versao do seu VsCode por favor? Voce pode ver a versao no menu: Ajuda -> Sobre
