### ISSUE TITLE
"failed to decrypt 2 in file" 

### ISSUE THREAD

**Issue by Zaniinn** [totvs/tds-vscode#979]
Boa Tarde,

Estou com o seguinte erro:

Após realizar a instalação do Protheus, ao depurar um fonte no VSCODE que não envolve banco de dados e da tudo certo.
Quando tento depurar fontes que demandam uso do banco, acontecem alguns erros e daí para frente, não consigo mais fazer nada no Protheus.
![Erro](https://user-images.githubusercontent.com/99829317/170744495-952ec5e8-e262-4795-b15b-376854ad4d78.PNG)

Ao tentar apenas entrar no smartclient, da o seguinte erro:

![Erro2](https://user-images.githubusercontent.com/99829317/170744627-15d91480-492d-49bf-a527-e2701495aa03.PNG)

Os erros ocorrem durante a depuração do fonte.

Versão vscode 1.67.1
versão extensão totvs 1.3.13
versão build 7.00.210324P

Logs abaixo.
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/8788222/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/8788223/totvsls_out.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/8788224/totvsls.log)
[dap.log](https://github.com/totvs/tds-vscode/files/8788226/dap.log)

**Comment by lwtnb-wrk** [comment]
@Zaniinn Antes de tudo, voce conseguia acessar o Protheus via Smartclient normalmente?
Somente apos a compilacao de determinados fontes que o problema passou a ocorrer?
No envie o console.log do AppServer para analises tambem.

**Comment by lwtnb-wrk** [comment]
@Zaniinn Pelo console.log vi que seu AppServer esta um pouco desatualizado.
Pegue a ultima versão no Portal e repita os testes, pois parece ser algum problema no AppServer.

**Comment by Zaniinn** [comment]
@lwtnb-wrk Baixei as versões mais recentes do AppServer e DBAccess e o problema persiste.
Essas versões tento do AppServer quanto DBAccess são do próprio instalador disponível no Portal.

A máquina esta no domínio da empresa, porém em outras máquinas funciona normalmente.

E já até mudei de máquina para ver se o erro poderia ser apenas nela, porém se replica a outras também.

**Comment by Zaniinn** [comment]
Creio que possa ser algo relacionado a comunicação que a extensão faz com o Protheus, pois como já passado, sem utilizar o VSCODE e aplicar fontes, consigo usar o Protheus normalmente.

**Comment by lwtnb-wrk** [comment]
@Zaniinn No envie todos os logs gerados apos a atualização para analisarmos novamente.

**Comment by brodao** [comment]
@Zaniinn 

Tenho conhecimento de alguns comportamentos semelhantes, que foram resolvidos informando a chave "RPOCUSTOM" no lugar de deixar o valor padrão. Tente ajustar para algo como ``RPOCUSTOM=M:\protheus\apo\custom.rpo``, atente-se que a pasta do ``custom.rpo`` já deve existir.

**Comment by Zaniinn** [comment]
@lwtnb-wrk Boa tarde,
Segue logs abaixo.
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/8799791/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/8799794/totvsls_out.log)
[dap.log](https://github.com/totvs/tds-vscode/files/8799795/dap.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/8799796/totvsls.log)
[console.log](https://github.com/totvs/tds-vscode/files/8799792/console.log)

**Comment by Zaniinn** [comment]
@brodao Tentei fazer como você especificou e também não deu certo.

**Comment by Zaniinn** [comment]
@lwtnb-wrk @brodao Se for necessário, posso informar como reproduzir este erro para tentarem reproduzir para teste.

**Comment by lwtnb-wrk** [comment]
@Zaniinn Nos passe então como podemos reproduzir o erro, pois tudo indica que está ocorrendo algum problema na carga do RPO após sua compilação.

Se possível refaça a compilação de causa o problema e nos envie os logs que mostrem a compilação no totvsls.log e console.log para verificarmos se esta ocorrendo alguma mensagem na compilação...

**Comment by DanielYampolschi** [comment]
Ola @Zaniinn reparei na suas mensagens ateriores que você informa que reproduz o problema ao debugar com o SmartClient já aberto: "Outa informação que pode ajudar é que, o problema é reproduzido ao tentar depurar um fonte já com o smartclient aberto." 

Quando uma depuração é iniciada, é lançado uma nova instância do SmartClient e a que já está aberta é apenas uma nova conexão que pode causar problemas caso os dois estejam apontando para o mesmo ambiente. Sugiro que tente reproduzir o problema sem que exista um outro, SmartClient aberto, usando apenas o lançador do VSCode.

**Comment by Zaniinn** [comment]
Após ter feito as conexões entre Banco de dados x Protheus x VSCODE, executo os fontes normalmente sem problemas nenhum, envolvendo ou não o banco de dados. Após tentar executar um fonte com o SmartClient já aberto, acontece este erro
![Erro](https://user-images.githubusercontent.com/99829317/171034971-7cfd7069-5ac9-4172-8d7d-99442e209389.PNG)
como já passado acima. Lembrando que o erro só acontece caso tente depurar um fonte com o SmartClient aberto.

**Comment by Zaniinn** [comment]
@DanielYampolschi Olá. Sim, este erro só ocorre quando tento depurar um fonte do VSCODE com uma instancia já iniciada do SmartClient. Porém isto não acontecia na r.27.

**Comment by Zaniinn** [comment]
Chamando-o diretamente. Sim, usando o mesmo ambiente.
Segue appServer.in
[appserver.docx](https://github.com/totvs/tds-vscode/files/8799922/appserver.docx)
i

**Comment by Zaniinn** [comment]
Senhores, tentei fazer um teste e funcionou. Excluí o arquivo "tttm120.rpo" da pasta apo e baixei-o novamente do Portal. Agora consigo compilar normalmente os fontes. Porém creio que seja normal isto estar ocorrendo.

**Comment by DanielYampolschi** [comment]
@Zaniinn Pelo seu relato, parece então que tinha algo no RPO substituído que estava corrompendo o mesmo. Como você disse que excluiu ele não vamos conseguir verificar, por isso vou encerrar essa issue, mas te peço então para que caso volte a acontecer, reabra-a e nos envie o RPO.

Muito obrigado.
