### ISSUE TITLE
O editor não pôde ser aberto porque o arquivo não foi encontrado

### ISSUE THREAD

**Issue by AndreSarraipa** [totvs/tds-vscode#981]
As vezes acontece de eu compilar um programa a partir da Pasta_A depois mover o arquivo para a Pasta_B, ai compilo novamente na Pasta_B, quando tendo debugar o Visual Studio Code fica procurando o arquivo na pasta errada.

Como posso resolver isso e fazer o Visual Studio Code procurar na pasta correta

**Comment by lwtnb-wrk** [comment]
@AndreSarraipa Voce ja tinha breakpoints marcados no fonte compilado na Pasta_A?
Voce moveu o fonte por dentro do VS Code ou por fora dele?

**Comment by AndreSarraipa** [comment]
O fonte foi movido fora do VS Code e depois aberto novamente no novo diretório e compilado.

**Comment by lwtnb-wrk** [comment]
@AndreSarraipa E provavelmente com breakpoints, correto? O problema maior não está na movimentação do fonte por fora do VS Code, mas sim nas informações que estão salvos nos breakpoints que existiam.

O VS Code mantem a informação de onde o fonte estava quando o breakpoint foi criado e não enxerga a alteração por fora dele.

Sugerimos entao que, _OU_ você remove os breakpoints antes de movimentar o fonte _OU_ movimenta por dentro do VS Code.

**Comment by AndreSarraipa** [comment]
Obrigado pela ajuda.

Remover os breakpoints resolve meu problema.

**Comment by AndreSarraipa** [comment]
Obrigado pela ajuda.

Remover os breakpoints resolve meu problema.
