### ISSUE TITLE
Erro não é mostrado quando a função é executada diretamente pelo VSCODE

### ISSUE THREAD

**Issue by edusfc15** [totvs/tds-vscode#99]
Estou executando uma função sem a interface do protheus utilizando Tbiconn e o plugin não exibe a mensagem de erro.

![errornotshown](https://user-images.githubusercontent.com/13476234/60212882-b3952f80-9838-11e9-9b1b-27235b9626ac.gif)

Testei fazendo o login e chamando pelo menu e o erro é exibido.

**Comment by DanielYampolschi** [comment]
Ola @edusfc15 , desculpe, mas não ficou claro sua questão, o que deveria ter acontecido? Aparecer no console do VsCode alguma mensagem de erro? Abrir uma janela de erro? Voce pode dar mais detalhes, anexando um video ou print do comportamento esperado por favor.

Muito obrigado.

**Comment by edusfc15** [comment]
@DanielYampolschi era pra o plugin ter exibido o erro que aconteceu.

Segue gif com exemplo da outra extensão:


![errornotshown2](https://user-images.githubusercontent.com/13476234/60284421-e1827e80-98e1-11e9-8d45-9c9951453af9.gif)


O erro é exibido na pilha, no debug console, e a linha com o erro é marcada.

Deu pra entender?

Grato.

**Comment by DanielYampolschi** [comment]
Ah ok, agora ficou mais claro. Muito obrigado pelas informações. Vamos verificar.

**Comment by DanielYampolschi** [comment]
Ola @edusfc15 , desculpe a demora em relação a essa issue. A correção foi efetuada e estará disponível na próxima liberação.
Lembrando que as mensagens referentes ao processo de depuração vão no Debug Console.

**Comment by edusfc15** [comment]
Oi @DanielYampolschi grato pelo comunicado. Estou aguardando o release.

**Comment by DanielYampolschi** [comment]
Correção liberada na versão 0.3.13
