### ISSUE TITLE
Gerando arquivos iniciado com "AP_" na pasta do projeto

### ISSUE THREAD

**Issue by jvvasquesn** [totvs/tds-vscode#990]
Ao compilar estar gerando arquivos iniciado com "AP_" na pasta do projeto
Estou usando o Ubuntu Ubuntu 22.04 LTS 64bits

![image](https://user-images.githubusercontent.com/55854184/173577388-b241e6ef-30f2-4f4a-8652-f60b44409dd0.png)

**Comment by brodao** [comment]
Favor informar os dados solicitados conforme [Informações importantes ao abrir o chamado](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#informa%C3%A7%C3%B5es-importantes-ao-abrir-uma-issue) e anexe os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)

No aguardo

**Comment by ramonmachadocarmo** [comment]
Estou com o mesmo problema. Ubuntu 22.04 LTS
Dados VSCode

> Versão: 1.67.2
> Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
> Data: 2022-05-17T18:23:40.286Z
> Electron: 17.4.1
> Chromium: 98.0.4758.141
> Node.js: 16.13.0
> V8: 9.8.177.13-electron.0
> OS: Linux x64 5.15.0-37-generic

**Comment by ramonmachadocarmo** [comment]
Estou com o mesmo problema. 
> Ubuntu 22.04 LTS

Dados VSCode
> Versão: 1.67.2
> Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
> Data: 2022-05-17T18:23:40.286Z
> Electron: 17.4.1
> Chromium: 98.0.4758.141
> Node.js: 16.13.0
> V8: 9.8.177.13-electron.0
> OS: Linux x64 5.15.0-37-generic

Versão extensão
> v1.3.14

**Comment by brodao** [comment]
@ramonmachadocarmo ,

Favor informar os dados solicitados conforme [Informações importantes ao abrir o chamado](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#informa%C3%A7%C3%B5es-importantes-ao-abrir-uma-issue) e anexe os logs conforme [Gerando informações sobre o problema.](https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-informa%C3%A7%C3%B5es-sobre-o-problema)

Atente que são vários itens (versão de rpo, de server, logs,...)

No aguardo.

**Comment by snlacerda89** [comment]
Estou com o mesmo problema
Rodo no MAC, versão 1.3.14

**Comment by ramonmachadocarmo** [comment]
O problema ocorre em vários servers diferentes, não tenho como enviar os dados do protheus deles

[totvsls.log](https://github.com/totvs/tds-vscode/files/8900670/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/8900672/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/8900677/totvsls_out.log)
.

**Comment by brodao** [comment]
Preciso saber as versões do server e um passo a passo para reproduzir, com um programa mais simples possível.

**Comment by brodao** [comment]
Anexem um desdes arquivos AP_, por favor.

**Comment by ramonmachadocarmo** [comment]
Os arquivos são vazios, adicionei a extensão .txt para poder anexar.
A geração deles é indepentende da execução de rotinas, ocorre quando faço qualquer alteração no arquivo.
Segue vídeo em anexo

[AP_0dFI4d.txt](https://github.com/totvs/tds-vscode/file

https://user-images.githubusercontent.com/66325829/173607668-e3ece9a3-0082-4a39-9f89-de4e65cb1526.mp4

s/8900805/AP_0dFI4d.txt)
o

**Comment by brodao** [comment]
Se desligar o linter? 
![image](https://user-images.githubusercontent.com/949914/173608855-8c53ed28-0123-4eca-96f8-ead2dd161d80.png)

**Comment by ramonmachadocarmo** [comment]
Funcionou, fiz alterações aqui e não gerou mais. Desabilitando o LINTER

**Comment by maximinocastro** [comment]
Boa tarde,

Estou estou tendo esse mesmo problema após atualização.

Version: 1.65.2
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:42:05.236Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.5.0

OS:
macOS Monterey
Versão: 12.4

Totvs Developer Studio for VsCode: v1.3.15-RC2

<img width="1245" alt="Captura de Tela 2022-06-21 às 16 05 52" src="https://user-images.githubusercontent.com/42280023/174880379-03511d16-bf43-4a98-90c1-a71aa578705a.png">

**Comment by snlacerda89** [comment]
Alguma solução definitiva?

**Comment by lwtnb-wrk** [comment]
ainda estamos investigando essa ocorrencia.

**Comment by maximinocastro** [comment]
@brodao após a atualização do Plugin parou de ocorrer o problema de gerar os arquivos "AP_" MacOS muito obrigado
