### ISSUE TITLE
Pasta de fontes como Projetos

### ISSUE THREAD

**Issue by LukeChagastec** [totvs/tds-vscode#991]
Boa tarde.

Seria possível criar uma configuração onde cada pasta de fontes dentro do VsCode pudesse se tornar um projeto?
Essa issue vem para confrontar quando possuímos mais de um fonte com o mesmo nome, mesmo que ele esteja em outra pasta que é considerada outro projeto.

Criar uma configuração onde possamos definir uma pasta como projeto.

Como alternativa, seria a troca do plugin oficial pelo plugin https://github.com/totvs/advpl-vscode

**Comment by danielbolognani** [comment]
É possível criar workspaces e adicionar as pastas necessárias em cada workspaces. Isso ajudaria? De qualquer forma não da para deixar vários workspaces abertos de uma vez, teria que trocar o workspace sempre que necessário.

Se quiser usar uma pasta só como projeto, também é possível, é só abrir diretamente a pasta na opção "Open folder", que será tratado como um projeto. Porém da mesma forma que anterior, se quiser mais de uma pasta aberta ao mesmo tempo, a extensão vai tratar como um único projeto e não vai trabalhar com duas versões de um mesmo arquivo fonte por exemplo.
