### ISSUE TITLE
VSCODE não pára nos breakpoints durante debug

### ISSUE THREAD

**Issue by CESaturninoo** [totvs/tds-vscode#992]
Não consigo efetuar o debug em um environment específico
O VSCode compila normalmente, consigo ver o fonte no Inspetor de objetos, porém ao debugar ele não para no BreakPoint (coloquei em todas as linhas do fonte)

Segue tbm o arquivo TDSSuport para análise do caso
[tdsSupport1655477321515.zip](https://github.com/totvs/tds-vscode/files/8928672/tdsSupport1655477321515.zip)

Dados Instalação VSCode

Versão: 1.68.1 (user setup)
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Data: 2022-06-14T12:48:58.283Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044

Versão da Extensão Totvs Developer Studio for VSCode

v1.3.14

Dados do Server 

Versão: TOTVS Serviços
Build AppServer: 7.00.210324P-20220312 - 64 bits
Nome do servidor: UNKNOWHOST
Sistema operacional: Linux
Appserver version: 20.3.0.8
Build DBAccess: 20210202-20220603
Release do RPO:  12.1.033
Release do dicionário: 12.1.033
Local files: ctree
License server: 2014 - 3.3.2
DB DataBase: MSSQL
DB API Build: 20210202-20220603

Dados do Remote 

Remote build: 7.00.210324P-20210914
Remote version: 20.3.0.0
Remote type: 1 - QT-5.15.3 WIN
Módulo: FAT
Nome do computador: DESKTOP-EDU
Sistema operacional: Windows 10 - 
Memória: 8136
Processador: Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz

Versão da Lib:20220613
Data da Lib: 20220608_165254

**Comment by CESaturninoo** [comment]
Dados Instalação VSCode

Versão: 1.68.1 (user setup)
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Data: 2022-06-14T12:48:58.283Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044

Versão da Extensão Totvs Developer Studio for VSCode

v1.3.14

**Comment by danielbolognani** [comment]
Por favor, gere os logs (https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs) principalmente o DAP.log e anexe ao chamado.

**Comment by brodao** [comment]
@CESaturninoo 

- O servidor esta em sua rede?
- O programa a depurar é um job (web-service ou rest)?

No aguardo.

**Comment by CESaturninoo** [comment]
1. O servidor esta em sua rede?
Não, o servidor é o TCloud

1. O programa a depurar é um job (web-service ou rest)?
Não é um ponto de Entrada

[totvsls_in.log](https://github.com/totvs/tds-vscode/files/8929448/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/8929449/totvsls_out.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/8929450/totvsls.log)
[dap.log](https://github.com/totvs/tds-vscode/files/8929451/dap.log)

**Comment by brodao** [comment]
Veja [TDS: Depuração e execução](https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md#tds-depura%C3%A7%C3%A3o-e-execu%C3%A7%C3%A3o), o bloco "Recomendações" sobre ambientes TCloud.

**Comment by brodao** [comment]
Verificando o dap.log parece que esta tudo correto.
Sugiro recompilar os fontes a serem depurados (pelo log não há essa indicação), verificando que não há nenhum erro e que o fonte compilado seja o mesmo sendo depurado.

Como trata-se de um ponto de entrada (PE), pode ser que as condições para a sua execução não estejam sendo satisfeita.
Sugiro colocar na entrada e na saidaa do PE,  conout indicando isso. Algo como ``conout("****** entrei")`` e verificar no log de console do protheus a existência desses logs. Veja também no console do protheus, se não ocorreu algum problema antes.

**Comment by lwtnb-wrk** [comment]
@CESaturninoo Pelos logs basicamente o que podemos ver é que aparentemente o programa M460QRY.PRW nunca foi chamado ou nunca passou pelas linhas 15 a 42, pois os breakpoints estão sendo enviados para o servidor, mas após o inicio da execução o servidor nunca manda um comando de parada para o tds-vscode.

**Comment by CESaturninoo** [comment]
Efetuei a compilação do fontes antes, e coloque um FWAlertSuccess antes do breakpoint (que inseri dessa vez, antes de acionar o comando de debug).

Mesmo resultado anterior. Não apresentou a janela do FWAlertSuccess, bem como não parou nos Break´points

Segue Logs do VSCode 
[totvsls.log](https://github.com/totvs/tds-vscode/files/8929741/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/8929742/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/8929743/totvsls_out.log)

**Comment by CESaturninoo** [comment]
Segue novos arquivos para análise, evidenciando a compilação do programa, colocando os pontos de parada antes de iniciar a depuração, bem como inclui uma função de aviso na linha 20 (antes dos pontos de parada)

![image](https://user-images.githubusercontent.com/107700063/174357608-aec01561-2a66-4cc7-bb8e-b8479c4d61f5.png)

[dap1.log](https://github.com/totvs/tds-vscode/files/8929858/dap1.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/8929859/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/8929860/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/8929861/totvsls_out.log)

**Comment by lwtnb-wrk** [comment]
@CESaturninoo Se não mostrou o alerta com a mensagem "Passou por aqui", ou a execução da função U_M460MQY nunca ocorreu (ou seja o MATA460 não chamou este ponto de entrada) ou a compilação não foi feita neste appserver.
Faça o seguinte teste para confirmar que o U_M460MQY foi compilado com sucesso. Ao inves de chamar o program SIGAMDI no inicio, chame diretamente o U_M460MQY. 
Se aparecer o alerta com a mensagem e a depuração parar nos breakpoints, significa que o fonte está sendo compilado com sucesso e a depuração funciona corretamente, mas o uso desse ponto de entrada não está correto, e nesse caso, abra um chamado na TOTVS para que possam dar a solução para o seu problema.

**Comment by CESaturninoo** [comment]
Acabei de efetuar o teste chamando diretamente o nome do ponto de entrada, e apareceu o alert, bem como parou nos pontos de parada do VSCode.
Muito Obrigado
