### ISSUE TITLE
Erro ao compilar 

### ISSUE THREAD

**Issue by ArlanBarros** [totvs/tds-vscode#993]
## 2022/06/20

**Arquivo PRTOPDEF.CH não encontrado mesmo estando na pasta include**

"resource": "/r:/Protheus_Produção_33/Protheus/Genericos/Faturamento/Política Comercial/FUNC0092.PRW",
	"owner": "AdvPL",
	"severity": 8,
	"message": "C2090  File not found PRTOPDEF.CH",

Ao realizar a compilação de um projeto utilizando o VSCode com o GIT apenas em alguns fontes ocorre erro de compilação informando que o arquivo PRTOPDEF.CH não foi encontrado na pasta include e o mesmo está na pasta. 

Seguem em anexo logs do VSCode

Versão: TOTVS Distribuição e Logística
Build AppServer: 7.00.210324P-20220312 - 64 bits
Nome do servidor: FAS03WAP
Sistema operacional: Windows Server 2008 R2
Appserver version: 20.3.0.8
Build DBAccess: 20200606-20201110
Release do RPO:  12.1.033
Release do dicionário: 12.1.033
Local files: CTREE
License server: 2014 - 3.3.3
DB DataBase: MSSQL7
DB API Build: 20210202-20220202
Versão da Lib:20220207
Data da Lib: 20220204_161331
Commit ID:79535bd6bae95725d7c1e82e21351db1a96e3aaf

**Additional context**
[Erro compilação.txt](https://github.com/totvs/tds-vscode/files/8941783/Erro.compilacao.txt)
[json.txt](https://github.com/totvs/tds-vscode/files/8941784/json.txt)
[output.txt](https://github.com/totvs/tds-vscode/files/8941785/output.txt)
[totvsls.log](https://github.com/totvs/tds-vscode/files/8941786/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/8941787/totvsls_in.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/8941788/totvsls_out.log)
![versao vscode](https://user-images.githubusercontent.com/107867008/174632502-7dc135e5-6114-4842-bf1a-42b690a0dc16.png)

**Comment by danielbolognani** [comment]
Boa tarde @ArlanBarros 
Nossa extensão não suporta caminhos de rede diretamente (endereços iniciados com \\), utilize uma pasta local para os includes.

Abraços!
