### ISSUE TITLE
Atualização de versão .33 não permite compilar mesmo com exclusividade

### ISSUE THREAD

**Issue by emilyfb13** [totvs/tds-vscode#996]
# Não permite compilação

Atualizamos recentemente da versão .27 para a .33, porém estamos com problema para compilar nossos fontes, tanto nas bases teste quando na base oficial.

O seguinte erro é apresentado:
Start build error: Server returned:
Win : The process cannot access the file because it is being used by another process.COMPILEERROR-300 It wasn't possible to obtain exclusive access to the objects repository.

Mesmo tendo exclusividade no sistema e com o monitor vazio, o mesmo erro é apresentado.

**Comment by lwtnb-wrk** [comment]
@emilyfb13 Existem servicos (jobs) que normalmente inicializam e rodam na .33
Voce tem a chave BuildKillUsers=1 na secao [general] de seu appserver.ini ?
Geralmente essa configuração ajuda nestas situacoes, pois elas derrubam todas as conexoes antes de iniciar a compilacao.

[General]
BuildKillUsers=1

**Comment by emilyfb13** [comment]
@lwtnb-wrk sim, já temos essa chave como 1

**Comment by lwtnb-wrk** [comment]
@emilyfb13 Confirme a build exata de seu AppServer, algo como Build Version: 20.3.0.10

E veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analises.

**Comment by cirilorocha** [comment]
Já observou se esse ambiente não tem mesmo usuários logados? 
Outra coisa se no ambiente você habilitar a chave App_Environment ele também fica preso e não deixa aplicar dicionários e compilar porque o REST fica com o ambiente aberto o tempo todo.

**Comment by lwtnb-wrk** [comment]
@cirilorocha  A chave BuildKillUsers=1 é exatamente para derrubar quaisquer usuarios conectados ao ambiente antes da compilacao, para garantir o acesso exclusivo. Mas parece que já está sendo utilizada, então pode ser algum problema no AppServer. Para isso preciso confirmar a versão que estão usando.
Mas seu apontamento está correto, normalmente esse aviso de acesso exclusivo ocorre quando temos usuarios conectados no ambiente, inclusive jobs como é o caso do REST

**Comment by emilyfb13** [comment]
@lwtnb-wrk Dados do Server 

Build AppServer: 7.00.210324P-20220608 - 64 bits
Appserver version: 20.3.0.10
Release do RPO:  12.1.033
Release do dicionário: 12.1.033

Antes de enviar o log, fiz uma observação. 

Temos duas bases de testes em um mesmo servidor, elas sempre funcionaram nas outras versões.
Mas observei hoje que compila normalmente se tiver acesso exclusiva em ambas as bases testes, porém se na base 1 tiver usuário eu não consigo compilar na base 2.

**Comment by lwtnb-wrk** [comment]
@emilyfb13 Quando voce diz duas bases de testes, seriam dois ambientes (environment) no mesmo appserver?

**Comment by lwtnb-wrk** [comment]
@emilyfb13 Acabei de retestar esse cenario com dois ambientes no mesmo appserver e deixei um usuario conectado no segundo ambiente. Ao disparar uma compilacao no primeiro ambiente o usuario conectado foi derrubado e a compilacao ocorreu sem problemas.
Poderia confirmar se em seu appserver.ini para a chave BuildKillUsers=1 esta grafada corretamente e esta na seção [general] mesmo?

**Comment by HTM-Joaquim** [comment]
Boa tarde!

Tenho um problema parecido quando os appserver estão em portas TCP distintas, funcionando em formato de Master - Slave.
Ao enviar o comando de compilação no Slave 1, os usuários do Slave 2 não são derrubados automaticamente, é necessário derrubar o serviço manualmente para conseguir efetuar a compilação.

**Comment by brodao** [comment]
Por acaso os slaves apontam param o mesmo RPO? Se sim, cada slave deve ter o seu.
De qualquer modo, não recomendo o desenvolvimento em ambientes master/slaves.
Pode ocorrer de alguém se conectar e cair justamente no slave que você esta usando.

**Comment by emilyfb13** [comment]
Bom dia @lwtnb-wrk, encontramos o problema, estava no apontamento de uma das seções. Muito obrigada pelo atendimento.
