### ISSUE TITLE
Release 12.1.33 - Errorlog ao debugar qualquer rotina no MacOS

### ISSUE THREAD

**Issue by flaviohideki** [totvs/tds-vscode#997]
Bom dia, 

Identificamos que ao tentar efetuar Debug no MacOS em qualquer rotina na release 12.1.33, ocorre errorlog em fontes padrões.

Ao efetuar o debug em maquina Windows, o problema não ocorre.

Obs: Ate a release 12.1.27 o debug no MacOs funcionava perfeitamente.

VSCODE May 2022 (version 1.68)

Plugin : Ultima atualização
09/06/2022 10:19:49
Identificador
totvs.tds-vscode

Build AppServer: 7.00.210324P-20220312 - 64 bits
Versão da Lib : 20220321
SmartClient : 22-04-14-P12-SMARTCLIENT_BUILD-20.3.0.3_MAC_X64

Atenciosamente

**Comment by flaviohideki** [comment]
Bom dia,

Segue alguns errorlogs e consolelog, lembrando que ocorre para todas as rotinas independente do modulo.

Ao efetuar o debug para as mesmas rotinas, mesma porta, mesmo environment no Windows funciona normalmente sem erros.

 
[ERROR_DANFE.TXT](https://github.com/totvs/tds-vscode/files/9020730/ERROR_DANFE.TXT)
[ERRORCOPIA_PEDIDO.TXT](https://github.com/totvs/tds-vscode/files/9020732/ERRORCOPIA_PEDIDO.TXT)
[ERROR_CUSTO_MEDIO.TXT](https://github.com/totvs/tds-vscode/files/9020733/ERROR_CUSTO_MEDIO.TXT)
[CONSOLELOG.TXT](https://github.com/totvs/tds-vscode/files/9020734/CONSOLELOG.TXT)

**Comment by lwtnb-wrk** [comment]
@flaviohideki Deixa eu ver se entendi direito.
Se voce inicia um Debug pelo tds-vscode em uma maquina Windows nao ocorre erro, mas se iniciar um Debug no mesmo appserver só que pelo tds-vscode em uma maquina Mac ocorre erro?

Veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie esses logs para analise, em especial o dap.log pois trata-se de problema na depuracao

**Comment by flaviohideki** [comment]
Bom dia,

Exatamente, ocorre somente no MAC no mesmo appserver.

Segue logs solicitado: 

[totvsls.log](https://github.com/totvs/tds-vscode/files/9021083/totvsls.log)
[dap.log](https://github.com/totvs/tds-vscode/files/9021087/dap.log)
[totvsls_out.log](https://github.com/totvs/tds-vscode/files/9021088/totvsls_out.log)
[totvsls_in.log.zip](https://github.com/totvs/tds-vscode/files/9021092/totvsls_in.log.zip)

**Comment by lwtnb-wrk** [comment]
@flaviohideki Poderia gerar e enviar os mesmo logs gerados no Windows para compararmos?

**Comment by flaviohideki** [comment]
Boa tarde,

Segue arquivo dap gerado na maquina Windows onde nao houve erros.
[dap_windows.log](https://github.com/totvs/tds-vscode/files/9021816/dap_windows.log)

**Comment by lwtnb-wrk** [comment]
@flaviohideki Eu vejo apenas alguns pontos que poderiam causar esse comportamento diferente entre os SO.

Qual a build exata dos smartclients que estao sendo utilizados no Windows e no Mac? São ambos a mesma versão??

E os launchers podem estar um pouco diferente entre os dois SO. No Mac parece que esta passando como argumento o SIGAMDI alem do programa... E apesar de nao deveria fazer diferenca tem a configuraçao de language no Mac...

Verifique esses dois pontos para ver se consegue perceber alguma diferenca enquanto tentamos reproduzir o problema localmente.

**Comment by flaviohideki** [comment]
Boa tarde,

Deu certo. 

Muito obrigado, é a chave "language" mesmo.

Ate a release 12.1.27 precisamos informar a linguagem, porem na 12.1.33 o apperver é multi-idiomas onde não precisa informar na chave language.

Atenciosamente

**Comment by lwtnb-wrk** [comment]
@flaviohideki Realmente é um "problema" estranho, mas esse parametro language do Smartclient não é o mesmo que o language do AppServer.

De qualquer forma o comportamento nesse caso parece ser de FW ou do Produto quando o Smartclient informa esse parametro.

Enfim, grato pelas informacoes e testes.
