### ISSUE TITLE
Compilação MultiThreads

### ISSUE THREAD

**Issue by cirilorocha** [totvs/tds-vscode#998]
Estou com uma pequena dúvida técnica quanto ao processo de compilação no plugin do VSCode. Como ele controla a quantidade de processos durante a compilação? Ele aloca de acordo com a máquina onde está rodando? Tem alguma configuração para determinar essa funcionalidade?

**Comment by cirilorocha** [comment]
Não sei como os compiladores anteriores faziam, mas existia uma configuração (tanto no eclipse como no devstudio) que determinava quantos threads eram usados para fazer a compilação de forma paralelizada e mais mais rápida.
Eu até entendo esse conceito de em casos de erros fazer um rollback da transação, mas os processamentos dos fontes convertendo no formato do RPO não poderia ser feito em paralelo e sendo enviado para o protheus server ? Ou a compilação ocorre diretamente no AppServer sendo o compilador apenas uma ponte? Pergunto isso porque como antes era possível fazer um processo paralelo?

**Comment by lwtnb-wrk** [comment]
@cirilorocha O que tinhamos no Eclipse era uma compilacao em multiplos AppServer em paralelo apenas. Ou seja, o mesmo fonte era compilado em mais de um AppServer no mesmo comando. 

E até onde sabemos o AppServer não está preparado para efetuar compilacoes em paralelo. Ele consegue processar apenas um fonte de cada vez. O AppServer é bastante restrito em relação ao acesso ao RPO então não seria possivel abrir duas conexoes em paralelo para compilar simultaneamente.

**Comment by cirilorocha** [comment]
Pelo que entendi é na Pré-Compilação, pelo menos no DevStudio. No Eclipse ele diz processos simultâneos. Se for pré-compilador mesmo o VSCode tem opção também de usar múltiplos threads para ser mais rápido ou é automático?

![Captura de tela 2022-06-30 170518](https://user-images.githubusercontent.com/96308173/176768064-3659bbef-19c2-4126-bf51-da240b0df54c.jpg)
![Captura de tela 2022-06-30 170529](https://user-images.githubusercontent.com/96308173/176768072-f365bb32-ff18-4a96-9285-ed9a186d77e0.jpg)

**Comment by lwtnb-wrk** [comment]
@cirilorocha A pré-compilação é um processo intermediário que ocorre antes da compilação, mas a compilação no AppServer era sequencial depois, por limitação do AppServer. 

Podemos até testar para ver os ganhos, mas não sei se hoje a diferença seria tão grande visto a capacidade de processamento maior dos computadores mais modernos.

De qualquer forma, grato pelos questionamentos, pois foi um recurso que existia no passado, mas não foi implementada no tds-vscode. Faremos uns testes para ver se teriamos um ganho real e caso isso ocorra, podemos implementar futuramente.

**Comment by cirilorocha** [comment]
@ricardomansano sei que essa opção era para processadores antigos, porém vejo que ainda assim seria interessante ter essa melhoria sim, se o pré-compilador usar mais de um thread ajudaria, observo que meu pc quando compilo o processo advpls.exe usa 100% de um processador, então vejo que isso seria um gargalo, se houvessem mais threads acredito que o server conseguiria ir mais rápido. Antes lembro que ele iniciava vários desses processos durante a compilação cada um usando 1 core e trabalhando em paralelo. O meu projeto tem 1400 fontes e leva vários minutos compilando desta forma.
