### ISSUE TITLE
Invalid setting. Verify STARTPATH variable

### ISSUE THREAD

**Issue by HTM-Joaquim** [totvs/tds-vscode#999]
**Describe the bug**
Após atualização dos binários para a release .33, não é possível abrir Debug em nenhum ambiente, é apresentada a mensagem: 

![image](https://user-images.githubusercontent.com/69199727/177207780-5f8d29e9-f61b-4d0a-aff0-5714fb43fe95.png)

**To Reproduce**
1. Entrar em modo depuração em qualquer ambiente

**Expected behavior**
Abertura da rotina em modo Debug

**Desktop:**
 - OS/Architecture: Windows 11

**Appserver**
 - Build (with date): 7.00.210324P-20220608 - 64 bits
 - OS/Architecture: Windows Server 2016
 - Build Version 7.00.210324P-20220608 - 64 bits

**Extra**

Ja verifiquei a documentação em https://github.com/totvs/tds-vscode/blob/master/docs/debugger.md#tds-depura%C3%A7%C3%A3o-e-execu%C3%A7%C3%A3o porém não me foi de ajuda. 
Mesmo executando outra configuração seguindo o tutorial, o mesmo erro é apresentado.

`smartclient.ini` em `C:\smartclient\smartclient`
``` 
[config]
lastmainprog=SIGAMDI
envserver=Producao,Producao_Homologacao

[drivers]
active=tcp

[tcp]
server=192.168.0.66
port=5231
```

**Comment by HTM-Joaquim** [comment]
Segue configuração do arquivo `launch.json`:

```
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "TOTVS Language Debug",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "c:/smartclient/smartclient/smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true
		},
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"cwb": "${workspaceRoot}",
			"name": "P12 DEBUG",
			"smartclientBin": "C:\\smartclient\\smartclient\\smartclient.exe",
			"program": "${command:AskForProgramName}",
			"programArguments": [],
			"enableMultiThread": true,
			"enableProfile": true,
			"isMultiSession": true,
			"isAccessibilityMode": false,
			"doNotShowSplash": false,
			"openglMode": false,
			"dpiMode": false,
			"language": "",
			"ignoreFiles": true,
			"enableTableSync": true
		}
	],
	"lastPrograms": [
		{
			"label": "SIGAMDI"
		}
	],
	"lastProgramExecuted": "SIGAMDI"
}
```

**Comment by lwtnb-wrk** [comment]
@HTM-Joaquim A execução dos programas ocorre normalmente? O erro ocorre somente na depuração??

De qualquer forma veja em https://github.com/totvs/tds-vscode/blob/master/TROUBLESHOOTING.md#gerando-logs como gerar e nos envie os logs para analises.

**Comment by brodao** [comment]
O problema parece estar na configuração do appServer. Consegue executar o SmarClient por fora do VS-Code?

**Comment by HTM-Joaquim** [comment]
Boa tarde!

Executando o programa por fora do VS-Code o programa roda normalmente.

Seguem os logs:

[totvsls_out.log](https://github.com/totvs/tds-vscode/files/9041810/totvsls_out.log)
[totvsls.log](https://github.com/totvs/tds-vscode/files/9041808/totvsls.log)
[totvsls_in.log](https://github.com/totvs/tds-vscode/files/9041809/totvsls_in.log)

**Comment by HTM-Joaquim** [comment]
@lwtnb-wrk Sim, somente na depuração, em execução padrão, vai sem problemas.

**Comment by lwtnb-wrk** [comment]
@HTM-Joaquim Antes de depurar nesse servidor, experimente desconectar uma vez e realizar uma nova conexão (Não utilize a opção "Reconectar"). Veja se isso resolve seu problema.

Se isso não resolver nos envie tambem o dap.log, pois trata-se de problema na depuração...

**Comment by brodao** [comment]
Não tenho certeza, mas lembro que alguém comentou algo sobre o uso da chave ``"language": ""`` em servidor Harpia.
Experimente remove-la da definição do executor.

**Comment by HTM-Joaquim** [comment]
Boa noite pessoal!

Acabei encontrando o problema: 
O ambiente ao qual estava tentando me conectar não existia no arquivo `appserver.ini`. Após configurado o ambiente no slave de Debug, a operação funcionou corretamente.

Agradeço a atenção e peço desculpas pelo incomodo.
